### ISSUE TITLE
game crash on starting server

### ISSUE THREAD

**Issue by bruhmogus** [Regalis11/Barotrauma#10053]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I started the game, tried to download Lua for Barotrauma client side, but the game crashed when I clicked start. My settings were Casual, 10 player limit, Karma off, and Campaign mode. The crash did not happen immediately, but rather about one and a half seconds after the loading box appeared.  My only mod was Lua for Barotrauma, however, it will still occur without it or any mods enabled. I have checked the bug tracker, and I did find something, but I could not decipher an answer from it.

### Reproduction steps

1. Start game on version 0.19.11.0
2. Host server
3. Set fire to California due to game crash

### Bug prevalence

Happens every time I play

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 10/10/2022 21:44:19)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


178AA6DAE559A23A7407976D333C2410


Game version 0.19.11.0 (ReleaseWindows, branch release, revision 45964c6e22)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla, Lua For Barotrauma
Level seed: no level loaded
Loaded submarine: None
Selected screen: Barotrauma.MainMenuScreen
SteamManager initialized
Client (Round hadn't been started)


System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit
    GPU name: NVIDIA GeForce MX130
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal


Exception: ChildServerRelay readTask did not run to completion: status was WaitingForActivation. (System.Exception)
Target site: Int32 ReadIncomingMsgs()
Stack trace: 
   at Barotrauma.Networking.ChildServerRelay.ReadIncomingMsgs() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\ChildServerRelay.cs:line 132
   at Barotrauma.Networking.ChildServerRelay.<UpdateRead>g__readBytes|40_0(Span`1 readTo) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\ChildServerRelay.cs:line 163
   at Barotrauma.Networking.ChildServerRelay.UpdateRead() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\ChildServerRelay.cs:line 155


Last debug messages:
[10/10/2022 21:44:19] WARNING: Tried to restore enabled packages multiple times/without performing a backup
[10/10/2022 21:44:19] Exiting...
[10/10/2022 21:41:30] WARNING: The following errors occurred while loading the content package "Normal Health Outposts NPCs - Anniversary Update compatible". The package might not work correctly.
Failed to load file "Mods/Normal Health Outposts NPCs Updated/OutpostGenerationNpcs.xml" of type "NPCSets": file not found.
[10/10/2022 21:41:22] Overriding an affliction or a buff with the identifier 'huskinfection' using the file 'C:/Users/ditch/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2782887123/content/Afflictions.xml'
[10/10/2022 21:41:21] Overriding an affliction or a buff with the identifier 'thal_scan' using the file 'C:/Users/ditch/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2660379561/GeneAfflictions.xml'
[10/10/2022 21:41:21] WARNING: Unrecognized element in affliction "thal_maggotinfection" (StatusEffect)
[10/10/2022 21:41:19] WARNING: Error in "thal_chaoshorn"'s fabrication recipe: out condition is above 100% (10000).
[10/10/2022 21:41:19] WARNING: Error in "thal_bananapeel"'s fabrication recipe: out condition is above 100% (10000).
[10/10/2022 21:41:18] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/ditch/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2651035690/talentIcon.png, size: 117x117)
[10/10/2022 21:41:14] Sprite "Content/ContentPackages/Afflictionicons.png" not found!
[10/10/2022 21:41:08] Overriding an affliction or a buff with the identifier 'huskinfection' using the file 'C:/Users/ditch/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2085783214/Afflictions.xml'
[10/10/2022 21:40:19] Attempting to open ALC device "OpenAL Soft on Speakers (Realtek(R) Audio)"
[10/10/2022 21:40:16] Logged in as The Headless Horseless Horsemann (SteamID STEAM_1:1:163514037)
```

**Comment by Regalis11** [comment]
Thank you for the report!  I would suspect the server is crashing for some reason - I wonder if there's some mods enabled server-side or if it's trying to launch a different executable than the vanilla one (the lua server)? If you see a server crash report in the game folder, that might help us diagnose the issue.

We also [have an existing ticket about the error](https://github.com/Regalis11/Barotrauma/issues/7783), closing this one.

**Comment by bruhmogus** [comment]
i found some files named servercrashreport.log, but the most recent was four months ago, meaning it didnt create one on the crash.
