### ISSUE TITLE
Dedicated Server crash (nullref exception in RepairTool.Repair)

### ISSUE THREAD

**Issue by cshingle** [Regalis11/Barotrauma#10079]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Dedicated Server crashed about 5 minutes into a round. We had around 10 players in the game. While fighting all the other players disappeared. I checked the dedicates server terminal and it had crashed back to shell. I restarted the dedicated server and had everyone disconnect and rejoin and everything worked fine.

I run the dedicated server on the same system I run the client. I have a powerful system so I don't notice a performance difference with the dedicated server running vs hosting via P2P.

I found a few older issues with similar stack traces, but they all seemed to be resolved.

### Reproduction steps

I have haven't had many dedicated server crashes so I doubt this is easily reproducible.

### Bug prevalence

Just once

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Linux

### Relevant error messages and crash reports

```shell
﻿Barotrauma Dedicated Server crash report (generated on 10/14/2022 00:35:46)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


Game version 0.19.11.0 (ReleaseLinux, branch release, revision 45964c6e22)
Language: English
Selected content packages: Vanilla, Europa Depths Vanilla Monsters, Europa Depths Events, Europa Depths Equipment, Europa Depths Items, Europa Depths Npcs, D-7 Dromedary, Europa Depths More Plants
Level seed: AylesburyTelephassa Linea
Loaded submarine: D-7 Dromedary (59B08BC822C1044D82024E6FCF0FC39F)
Selected screen: Barotrauma.GameScreen
Server (Round had started)


System info:
    Operating system: Unix 5.15.0.50 64 bit


Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void Repair(Microsoft.Xna.Framework.Vector2, Microsoft.Xna.Framework.Vector2, Single, Barotrauma.Character, Single, System.Collections.Generic.List`1[FarseerPhysics.Dynamics.Body])
Stack trace: 
   at Barotrauma.Items.Components.RepairTool.Repair(Vector2 rayStart, Vector2 rayEnd, Single deltaTime, Character user, Single degreeOfSuccess, List`1 ignoredBodies) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Holdable\RepairTool.cs:line 520
   at Barotrauma.Items.Components.RepairTool.Use(Single deltaTime, Character character) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Holdable\RepairTool.cs:line 293
   at Barotrauma.Item.Use(Single deltaTime, Character character, Limb targetLimb) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 2639
   at Barotrauma.Character.Control(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 2076
   at Barotrauma.Character.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 3077
   at Barotrauma.Character.UpdateAll(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 2870
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 195
   at Barotrauma.GameMain.Run() in <DEV>\Barotrauma\BarotraumaServer\ServerSource\GameMain.cs:line 325
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Program.cs:line 78


Last debug messages:
   10/14/2022 00:35:46 - [10/14/2022 00:35:46]
  Saving banlist
   10/14/2022 00:35:46 - [10/14/2022 00:35:46]
  zig158 used Diving Knife on Hammerhead_veteran.
   10/14/2022 00:35:46 - [10/14/2022 00:35:46]
  Hammerhead_veteran attacked by zig158. Lacerations: 13 Bleeding: 13 Stun: 0.325
   10/14/2022 00:35:46 - [10/14/2022 00:35:46]
  zig158 used Europan Handshake on Hammerhead_veteran.
   10/14/2022 00:35:46 - [10/14/2022 00:35:46]
  Hammerhead_veteran attacked by zig158. Lacerations: 7.5 Bleeding: 7.5 Stun: 0.25 Morbusine poisoning: 1
   10/14/2022 00:35:45 - [10/14/2022 00:35:45]
  zig158 used Diving Knife on Hammerhead_veteran.
   10/14/2022 00:35:45 - [10/14/2022 00:35:45]
  Hammerhead_veteran attacked by zig158. Lacerations: 9.75 Bleeding: 9.75 Stun: 0.325
   10/14/2022 00:35:45 - [10/14/2022 00:35:45]
  Hammerhead_veteran attacked by MM. Blank. Bleeding: 45 Gunshot wound: 46.875 Stun: 0.3125 Blunt force trauma: 9.375
   10/14/2022 00:35:45 - [10/14/2022 00:35:45]
  Beer started repairing Junction Box
   10/14/2022 00:35:44 - [10/14/2022 00:35:44]
  Knox launched Double Coilgun (projectile: Coilgun Bolt)
   10/14/2022 00:35:44 - [10/14/2022 00:35:44]
  Knox launched Double Coilgun (projectile: Coilgun Bolt)
   10/14/2022 00:35:44 - [10/14/2022 00:35:44]
  Knox launched Double Coilgun (projectile: Coilgun Bolt)
   10/14/2022 00:35:44 - [10/14/2022 00:35:44]
  Knox launched Double Coilgun (projectile: Coilgun Bolt)
   10/14/2022 00:35:44 - [10/14/2022 00:35:44]
  Knox launched Double Coilgun (projectile: Coilgun Bolt)
```

**Comment by Regalis11** [comment]
Potentially fixed in https://github.com/Regalis11/Barotrauma-development/commit/f50440d10b2d60dd7d98b0185909c9baafe9da5c

**Comment by cshingle** [comment]
I have had several more of these crashes. Here are two. The stack trace looks to be the same so I don't know how helpful these will be.
```
﻿Barotrauma Dedicated Server crash report (generated on 10/16/2022 04:49:19)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


Game version 0.19.11.0 (ReleaseLinux, branch release, revision 45964c6e22)
Language: English
Selected content packages: Vanilla, Europa Depths Vanilla Monsters, Europa Depths Events, Europa Depths Equipment, Europa Depths Items, Europa Depths Npcs, D-7 Dromedary, Europa Depths More Plants
Level seed: Gortyna FlexusJokull
Loaded submarine: D-7 Dromedary (EA43020C2C8969AC715F0349C7E6A3B1)
Selected screen: Barotrauma.GameScreen
Server (Round had started)


System info:
    Operating system: Unix 5.15.0.50 64 bit


Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void Repair(Microsoft.Xna.Framework.Vector2, Microsoft.Xna.Framework.Vector2, Single, Barotrauma.Character, Single, System.Collections.Generic.List`1[FarseerPhysics.Dynamics.Body])
Stack trace: 
   at Barotrauma.Items.Components.RepairTool.Repair(Vector2 rayStart, Vector2 rayEnd, Single deltaTime, Character user, Single degreeOfSuccess, List`1 ignoredBodies) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Holdable\RepairTool.cs:line 520
   at Barotrauma.Items.Components.RepairTool.Use(Single deltaTime, Character character) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Holdable\RepairTool.cs:line 291
   at Barotrauma.Item.Use(Single deltaTime, Character character, Limb targetLimb) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 2639
   at Barotrauma.Character.Control(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 2076
   at Barotrauma.Character.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 3077
   at Barotrauma.Character.UpdateAll(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 2870
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 195
   at Barotrauma.GameMain.Run() in <DEV>\Barotrauma\BarotraumaServer\ServerSource\GameMain.cs:line 325
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Program.cs:line 78


Last debug messages:
   10/16/2022 04:49:19 - [10/16/2022 04:49:19]
  Saving banlist
   10/16/2022 04:49:19 - [10/16/2022 04:49:19]
  Motortruck launched Double Coilgun (projectile: Coilgun Bolt)
   10/16/2022 04:49:19 - [10/16/2022 04:49:19]
  Motortruck launched Double Coilgun (projectile: Coilgun Bolt)
   10/16/2022 04:49:19 - [10/16/2022 04:49:19]
  Motortruck launched Double Coilgun (projectile: Coilgun Bolt)
   10/16/2022 04:49:19 - [10/16/2022 04:49:19]
  Motortruck launched Double Coilgun (projectile: Coilgun Bolt)
   10/16/2022 04:49:18 - [10/16/2022 04:49:18]
  Motortruck launched Double Coilgun (projectile: Coilgun Bolt)
   10/16/2022 04:49:18 - [10/16/2022 04:49:18]
  Mudraptor_veteran attacked by Archinauld. Gunshot wound: 31.200003 Bleeding: 14.625 Stun: 0.40625
   10/16/2022 04:49:18 - [10/16/2022 04:49:18]
  Motortruck launched Double Coilgun (projectile: Coilgun Bolt)
   10/16/2022 04:49:18 - [10/16/2022 04:49:18]
  Motortruck launched Double Coilgun (projectile: Coilgun Bolt)
   10/16/2022 04:49:18 - [10/16/2022 04:49:18]
  Motortruck launched Double Coilgun (projectile: Coilgun Bolt)
   10/16/2022 04:49:18 - [10/16/2022 04:49:18]
  Motortruck launched Double Coilgun (projectile: Coilgun Bolt)
   10/16/2022 04:49:18 - [10/16/2022 04:49:18]
  Motortruck launched Double Coilgun (projectile: Coilgun Bolt)
   10/16/2022 04:49:18 - [10/16/2022 04:49:18]
  Motortruck launched Double Coilgun (projectile: Coilgun Bolt)
   10/16/2022 04:49:18 - [10/16/2022 04:49:18]
  Motortruck launched Double Coilgun (projectile: Coilgun Bolt)
```
```
﻿Barotrauma Dedicated Server crash report (generated on 10/16/2022 04:04:50)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


Game version 0.19.11.0 (ReleaseLinux, branch release, revision 45964c6e22)
Language: English
Selected content packages: Vanilla, Europa Depths Vanilla Monsters, Europa Depths Events, Europa Depths Equipment, Europa Depths Items, Europa Depths Npcs, D-7 Dromedary, Europa Depths More Plants
Level seed: Gortyna FlexusJokull
Loaded submarine: D-7 Dromedary (41C63C4F220B76773DA7C4DC20DD20B7)
Selected screen: Barotrauma.GameScreen
Server (Round had started)


System info:
    Operating system: Unix 5.15.0.50 64 bit


Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void Repair(Microsoft.Xna.Framework.Vector2, Microsoft.Xna.Framework.Vector2, Single, Barotrauma.Character, Single, System.Collections.Generic.List`1[FarseerPhysics.Dynamics.Body])
Stack trace: 
   at Barotrauma.Items.Components.RepairTool.Repair(Vector2 rayStart, Vector2 rayEnd, Single deltaTime, Character user, Single degreeOfSuccess, List`1 ignoredBodies) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Holdable\RepairTool.cs:line 520
   at Barotrauma.Items.Components.RepairTool.Use(Single deltaTime, Character character) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Holdable\RepairTool.cs:line 293
   at Barotrauma.Item.Use(Single deltaTime, Character character, Limb targetLimb) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 2639
   at Barotrauma.Character.Control(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 2076
   at Barotrauma.Character.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 3077
   at Barotrauma.Character.UpdateAll(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 2870
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 195
   at Barotrauma.GameMain.Run() in <DEV>\Barotrauma\BarotraumaServer\ServerSource\GameMain.cs:line 325
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Program.cs:line 78


Last debug messages:
   10/16/2022 04:04:50 - [10/16/2022 04:04:50]
  Saving banlist
   10/16/2022 04:04:48 - [10/16/2022 04:04:48]
  Outer wall breached by Spineling_giant
   10/16/2022 04:04:48 - [10/16/2022 04:04:48]
  Outer wall breached by Spineling_giant
   10/16/2022 04:04:46 - [10/16/2022 04:04:46]
  zig158 picked up Coilgun Ammunition Box
   10/16/2022 04:04:46 - [10/16/2022 04:04:46]
  zig158 equipped Coilgun Ammunition Box
   10/16/2022 04:04:46 - [10/16/2022 04:04:46]
  zig158 removed Coilgun Ammunition Box from Coilgun Loader (ID: 430)
   10/16/2022 04:04:46 - [10/16/2022 04:04:46]
  zig158 placed Coilgun Ammunition Box in Coilgun Loader (ID: 430)
   10/16/2022 04:04:45 - [10/16/2022 04:04:45]
  Knox used item Morphine
   10/16/2022 04:04:45 - [10/16/2022 04:04:45]
  Knox used item Plastiseal
   10/16/2022 04:04:43 - [10/16/2022 04:04:43]
  zig158 picked up Coilgun Ammunition Box
   10/16/2022 04:04:43 - [10/16/2022 04:04:43]
  zig158 equipped Coilgun Ammunition Box
   10/16/2022 04:04:40 - [10/16/2022 04:04:40]
  Knox used item Morphine
   10/16/2022 04:04:40 - [10/16/2022 04:04:40]
  Knox used item Plastiseal
   10/16/2022 04:04:33 - [10/16/2022 04:04:33]
  Roy Awesome started repairing Large Engine (Boost)
```

**Comment by Rokvach** [comment]
There hasn't been any sightings of this crash during Unstable community testing, seems to be working correctly. Closing.
