### ISSUE TITLE
Attempting to open reserved drive folder crashes game

### ISSUE THREAD

**Issue by Xenosplitter** [Regalis11/Barotrauma#10084]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

In attempting to add an image, I was poking around and noticed my system reserved drives appeared in the file list. For fun, I clicked through the folders, trying to see what I could find, only for the game to crash when trying to open /Reserved/ or /System Volume Information/.

### Reproduction steps

0. Perform a clean installation of Win10
0.5. Assign a letter to the system reserved drive
(Steps 0 and 0.5 are only required on certain OS installations)
1. Launch the submarine editor
2. Shift-Right click within the editor window
3. Click on Add Image
4. Change to a reserved drive
5. Open the /Reserved/ or /System Volume Information/

### Bug prevalence

Just once

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 10/14/2022 21:23:06)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


178AA6DAE559A23A7407976D333C2410


Game version 0.19.11.0 (ReleaseWindows, branch release, revision 45964c6e22)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla, PowerBlock, Testbed, CycleAirlockLTR, CycleAirlockExit, ExtraAutoReactor, CycleAirlockEnter, CycleAirlockRTL, CycleAirlockUTD, CycleAirlockDTU, BeterDuct, MultiCamSystem, Indev, Lumpy, Sealable Autodock
Level seed: no level loaded
Loaded submarine: Testbed (D873286AE3DA585DD510B5522DB33F92)
Selected screen: Barotrauma.SubEditorScreen
SteamManager initialized


System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit
    GPU name: NVIDIA GeForce GTX 1070
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal


Exception: Error reading the Y:/System Volume Information/ directory. (System.IO.FileNotFoundException)
Target site: Void StartRaisingEvents()
Stack trace: 
   at System.IO.FileSystemWatcher.StartRaisingEvents()
   at System.IO.FileSystemWatcher.StartRaisingEventsIfNotDisposed()
   at Barotrauma.FileSelection.set_CurrentDirectory(String value) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\FileSelection.cs:line 96
   at Barotrauma.FileSelection.<>c.<Init>b__28_5(GUIComponent child, Object userdata) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\FileSelection.cs:line 260
   at Barotrauma.GUIListBox.Select(Int32 childIndex, Force force, AutoScroll autoScroll, TakeKeyBoardFocus takeKeyBoardFocus, PlaySelectSound playSelectSound) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIListBox.cs:line 1068
   at Barotrauma.GUIListBox.UpdateChildrenRect() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIListBox.cs:line 789
   at Barotrauma.GUIListBox.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIListBox.cs:line 909
   at Barotrauma.GUI.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1242
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 879
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58


Last debug messages:
[10/14/2022 21:21:00] Attempting to open ALC device "OpenAL Soft on Speakers (2- Logitech G933 Gaming Headset)"
[10/14/2022 21:20:58] Logged in as Xenosplitter (SteamID STEAM_1:0:52553395)
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b89fd18007ce7bd00a571f7caec20989dfc0b532 (commit in our private repository)

**Comment by NilanthAnimosus** [comment]
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/09b8873e88f8ca7b179d3f0fda9384e6ec5e727e, no issues found, closing.

Notes: Used my own windows system reserved drive and modified a folder (With an image)'s permissions in a variety of ways, making it appear/disappear and trying to give or deny access without any visible issues occurring. Can't be fully sure this fixes the issue but I encountered no issues in my tests.
