### ISSUE TITLE
Kinetic Weapons crash in Multiplayer Lobby

### ISSUE THREAD

**Issue by AptGetGnome** [Regalis11/Barotrauma#10125]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Every single time someone shoots a kinetic weapon, be it ship guns, or more likely the harpoon gun or a stun gun, the server crashes, we have re-verified our game files and nobody uses mods

### Reproduction steps

1. Start a multiplayer game, doesn't matter if its campaign or sandbox
2. Use a weapon like the harpoon gun a few times.
3. Server crashes and we are all sent back to the main menu

### Bug prevalence

Happens every time I play

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Dedicated Server crash report (generated on 10/20/2022 17:40:29)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


Game version 0.19.11.0 (ReleaseWindows, branch release, revision 45964c6e22)
Language: English
Selected content packages: Vanilla
Level seed: VortaMenec Fossa
Loaded submarine: Orca2 (390E157498BCEEDC422BFEC6F46FA14B)
Selected screen: Barotrauma.GameScreen
Server (Round had started)


System info:
    Operating system: Microsoft Windows NT 10.0.19043.0 64 bit


Exception: Component event creation failed: Projectile.ValidateEventData returned false (System.Exception)
Target site: Void CreateServerEvent[T](T, IEventData)
Stack trace: 
   at Barotrauma.Item.CreateServerEvent[T](T ic, IEventData extraData) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Items\Item.cs:line 373
   at Barotrauma.Items.Components.Projectile.Shoot(Character user, Vector2 weaponPos, Vector2 spawnPos, Single rotation, List`1 ignoredBodies, Boolean createNetworkEvent, Single damageMultiplier, Single launchImpulseModifier) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Projectile.cs:line 349
   at Barotrauma.StatusEffect.<>c__DisplayClass101_6.<Apply>b__7(Item newItem) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\StatusEffects\StatusEffect.cs:line 1790
   at Barotrauma.EntitySpawner.Update(Boolean createNetworkEvents) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\EntitySpawner.cs:line 422
   at Barotrauma.MapEntity.UpdateAll(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\MapEntity.cs:line 611
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 256
   at Barotrauma.GameMain.Run() in <DEV>\Barotrauma\BarotraumaServer\ServerSource\GameMain.cs:line 325
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Program.cs:line 78


Last debug messages:
   10/20/2022 17:40:29 - [10/20/2022 17:40:29]
  Saving banlist
   10/20/2022 17:40:29 - [10/20/2022 17:40:29]
  Hammerhead_m attacked by Nyk. Lacerations: 11.25 Bleeding: 0.75 Stun: 0.025
   10/20/2022 17:40:29 - [10/20/2022 17:40:29]
  Nyk launched Double Coilgun (projectile: Coilgun Bolt)
   10/20/2022 17:40:29 - [10/20/2022 17:40:29]
  Hammerhead_m attacked by Nyk. Lacerations: 11.25 Bleeding: 0.75 Stun: 0.025
   10/20/2022 17:40:29 - [10/20/2022 17:40:29]
  Nyk launched Double Coilgun (projectile: Coilgun Bolt)
   10/20/2022 17:40:29 - [10/20/2022 17:40:29]
  Nyk launched Double Coilgun (projectile: Coilgun Bolt)
   10/20/2022 17:40:29 - [10/20/2022 17:40:29]
  Hammerhead_m attacked by Nyk. Lacerations: 11.25 Bleeding: 0.75 Stun: 0.025
   10/20/2022 17:40:29 - [10/20/2022 17:40:29]
  Spineling attacked by Nyk. Lacerations: 15 Bleeding: 1 Stun: 0.025
   10/20/2022 17:40:28 - [10/20/2022 17:40:28]
  Nyk launched Double Coilgun (projectile: Coilgun Bolt)
   10/20/2022 17:40:28 - [10/20/2022 17:40:28]
  Nyk launched Double Coilgun (projectile: Coilgun Bolt)
   10/20/2022 17:40:28 - [10/20/2022 17:40:28]
  Hammerhead_m attacked by Nyk. Lacerations: 8.25 Bleeding: 0.1 Stun: 0.025
   10/20/2022 17:40:28 - [10/20/2022 17:40:28]
  Hammerhead_m attacked by Nyk. Lacerations: 8.25 Bleeding: 0.1 Stun: 0.025
   10/20/2022 17:40:28 - [10/20/2022 17:40:28]
  Nyk launched Double Coilgun (projectile: Coilgun Bolt)
   10/20/2022 17:40:28 - [10/20/2022 17:40:28]
  Nyk launched Double Coilgun (projectile: Coilgun Bolt)
```

**Comment by AptGetGnome** [comment]
`Barotrauma Dedicated Server crash report (generated on 10/20/2022 17:09:28)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


Game version 0.19.11.0 (ReleaseWindows, branch release, revision 45964c6e22)
Language: English
Selected content packages: Vanilla
Level seed: peniscockandballs
Loaded submarine: Orca2 (390E157498BCEEDC422BFEC6F46FA14B)
Selected screen: Barotrauma.GameScreen
Server (Round had started)


System info:
    Operating system: Microsoft Windows NT 10.0.19043.0 64 bit


Exception: Component event creation failed: Projectile.ValidateEventData returned false (System.Exception)
Target site: Void CreateServerEvent[T](T, IEventData)
Stack trace: 
   at Barotrauma.Item.CreateServerEvent[T](T ic, IEventData extraData) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Items\Item.cs:line 373
   at Barotrauma.Items.Components.Projectile.HandleProjectileCollision(Fixture target, Vector2 collisionNormal, Vector2 velocity) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Projectile.cs:line 1021
   at Barotrauma.Items.Components.Projectile.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Projectile.cs:line 669
   at Barotrauma.Item.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 1871
   at Barotrauma.MapEntity.UpdateAll(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\MapEntity.cs:line 600
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 256
   at Barotrauma.GameMain.Run() in <DEV>\Barotrauma\BarotraumaServer\ServerSource\GameMain.cs:line 325
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Program.cs:line 78


Last debug messages:
   10/20/2022 17:09:28 - [10/20/2022 17:09:28]
  Saving banlist
   10/20/2022 17:09:28 - [10/20/2022 17:09:28]
  Nyk attacked by Adam. Lacerations: 0.45 Stun: 0.1 ProgressiveStun: 1
   10/20/2022 17:09:24 - [10/20/2022 17:09:24]
  Adam equipped Stun Gun
   10/20/2022 17:09:16 - [10/20/2022 17:09:16]
  Nyk threw Blue Paint
   10/20/2022 17:09:04 - [10/20/2022 17:09:04]
  Adam picked up Stun Gun
   10/20/2022 17:08:41 - [10/20/2022 17:08:41]
  Adam placed Diving Suit in Diving Suit Locker (ID: 569)
   10/20/2022 17:08:11 - [10/20/2022 17:08:11]
  Adam set the pumping speed of Small Pump to -100 %
   10/20/2022 17:08:11 - [10/20/2022 17:08:11]
  Adam set the pumping speed of Small Pump to -60 %
   10/20/2022 17:08:11 - [10/20/2022 17:08:11]
  Adam set the pumping speed of Small Pump to 50 %
   10/20/2022 17:08:10 - [10/20/2022 17:08:10]
  Adam set the pumping speed of Small Pump to 100 %
   10/20/2022 17:08:10 - [10/20/2022 17:08:10]
  Adam set the pumping speed of Small Pump to 90 %
   10/20/2022 17:08:10 - [10/20/2022 17:08:10]
  Adam set the pumping speed of Small Pump to 80 %
   10/20/2022 17:08:10 - [10/20/2022 17:08:10]
  Adam set the pumping speed of Small Pump to 60 %
   10/20/2022 17:08:10 - [10/20/2022 17:08:10]
  Adam set the pumping speed of Small Pump to 50 %
`

**Comment by Regalis11** [comment]
Thank you for the report! I unfortunately could not find a way to reproduce this. I can't get any errors to occur by firing weapons (even though I verified the exact same code path to `Item.CreateServerEvent` runs when firing those). So I guess this requires some more specific circumstances to occur, but so far I couldn't figure out what those could be. :/

**Comment by AptGetGnome** [comment]
So upon further testing, we all individually went into our own hosted servers and tested projectile weapons by ourselves, no crash, however i believe the issue now isn't just projectile weapons, but when projectile weapons are fired at an ally / enemy, loaded into a multiplayer lobby, immedietly shot my friend with a revolver, no issues, no crash.
I shoot them with a harpoon gun / syringe gun / stun gun, after half a second the server crashes, this is happening EVERY time.

```bash
Barotrauma Dedicated Server crash report (generated on 10/21/2022 13:40:54)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


Game version 0.19.14.0 (ReleaseWindows, branch release, revision 0daf5b87bd)
Language: English
Selected content packages: Vanilla
Level seed: dvuGxSnZ
Loaded submarine: Orca2 (390E157498BCEEDC422BFEC6F46FA14B)
Selected screen: Barotrauma.GameScreen
Server (Round had started)


System info:
    Operating system: Microsoft Windows NT 10.0.19043.0 64 bit


Exception: Component event creation failed: Projectile.ValidateEventData returned false (System.Exception)
Target site: Void CreateServerEvent[T](T, IEventData)
Stack trace: 
   at Barotrauma.Item.CreateServerEvent[T](T ic, IEventData extraData) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Items\Item.cs:line 373
   at Barotrauma.Items.Components.Projectile.HandleProjectileCollision(Fixture target, Vector2 collisionNormal, Vector2 velocity) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Projectile.cs:line 1021
   at Barotrauma.Items.Components.Projectile.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Projectile.cs:line 669
   at Barotrauma.Item.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 1871
   at Barotrauma.MapEntity.UpdateAll(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\MapEntity.cs:line 600
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 256
   at Barotrauma.GameMain.Run() in <DEV>\Barotrauma\BarotraumaServer\ServerSource\GameMain.cs:line 325
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Program.cs:line 78


Last debug messages:
   10/21/2022 13:40:54 - [10/21/2022 13:40:54]
  Saving banlist
   10/21/2022 13:40:54 - [10/21/2022 13:40:54]
  Lil Mushroom attacked by AptGetGnome. Lacerations: 20 Bleeding: 30 Stun: 0.5
   10/21/2022 13:40:53 - [10/21/2022 13:40:53]
  AptGetGnome equipped Harpoon Gun
   10/21/2022 13:40:52 - [10/21/2022 13:40:52]
  Lil Mushroom attacked by AptGetGnome. Gunshot wound: 14 Bleeding: 18.75 Stun: 0.3
   10/21/2022 13:40:51 - [10/21/2022 13:40:51]
  Lil Mushroom attacked by AptGetGnome. Gunshot wound: 14 Bleeding: 18.75 Stun: 0.3
   10/21/2022 13:40:50 - [10/21/2022 13:40:50]
  Lil Mushroom attacked by AptGetGnome. Gunshot wound: 14 Bleeding: 18.75 Stun: 0.3
   10/21/2022 13:40:50 - [10/21/2022 13:40:50]
  AptGetGnome has lost more than 25 karma in the past minute.
   10/21/2022 13:40:50 - [10/21/2022 13:40:50]
  Lil Mushroom attacked by AptGetGnome. Gunshot wound: 14 Bleeding: 18.75 Stun: 0.3
   10/21/2022 13:40:49 - [10/21/2022 13:40:49]
  Lil Mushroom attacked by AptGetGnome. Gunshot wound: 14 Bleeding: 18.75 Stun: 0.3
   10/21/2022 13:40:49 - [10/21/2022 13:40:49]
  Lil Mushroom attacked by AptGetGnome. Gunshot wound: 14 Bleeding: 18.75 Stun: 0.3
   10/21/2022 13:40:47 - [10/21/2022 13:40:47]
  AptGetGnome equipped Revolver
   10/21/2022 13:40:45 - [10/21/2022 13:40:45]
  AptGetGnome picked up Harpoon Gun
   10/21/2022 13:40:43 - [10/21/2022 13:40:43]
  AptGetGnome picked up Revolver
   10/21/2022 13:40:40 - [10/21/2022 13:40:40]
  Lil Mushroom set the value "Channel" of the item "Headset" to "0".

```

**Comment by Regalis11** [comment]
Thank you for the extra info! Still no luck in reproducing this though I'm afraid. :/

https://user-images.githubusercontent.com/14351070/197112389-f6e57584-fa33-4d20-9c9f-493e645d09e5.mp4

Just to make sure, you are not using any mods? I can see the crash report only lists the Vanilla content package but are you using some kind of source code mods?

**Comment by AptGetGnome** [comment]
No we are not, i can produce a video of the crash happening if you need it, nobody is using mods, and we have all uninstalled, and reinstalled, including re-verifying our game files.

**Comment by AptGetGnome** [comment]
Also i don't know if something in-game keeps corrupting the files or if this is anything important, but multiple times i re-verify my game files and i see that 1.5kb of files are "corrupt", this happens a few tiems, but then it will go periods where those files are fine but the game still crashes so i really don't know whats going on and whats causing the issue
![image](https://user-images.githubusercontent.com/12438639/197118045-bbc9be47-c3b5-4f49-a573-92949303b6b5.png)

**Comment by PhilippFr** [comment]
This bug crashes my multiplayer lobbies every time some shooting is happening (which is pretty much every round).

Exactly the same exception...
I also had the "3 files failed to validate", but hat might be a red herring.

```
Game version 0.19.14.0 (ReleaseWindows, branch release, revision 0daf5b87bd)
Language: English
Selected content packages: Vanilla
Level seed: UndermoistVellamo's Crevasse
Loaded submarine: Barsuk (405497E77935CEA32ED77A5F1688939B)
Selected screen: Barotrauma.GameScreen
Server (Round had started)


System info:
    Operating system: Microsoft Windows NT 10.0.22621.0 64 bit


Exception: Component event creation failed: Projectile.ValidateEventData returned false (System.Exception)
Target site: Void CreateServerEvent[T](T, IEventData)
Stack trace: 
   at Barotrauma.Item.CreateServerEvent[T](T ic, IEventData extraData) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Items\Item.cs:line 373
   at Barotrauma.Items.Components.Projectile.HandleProjectileCollision(Fixture target, Vector2 collisionNormal, Vector2 velocity) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Projectile.cs:line 1021
   at Barotrauma.Items.Components.Projectile.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Projectile.cs:line 669
   at Barotrauma.Item.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 1871
   at Barotrauma.MapEntity.UpdateAll(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\MapEntity.cs:line 600
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 256
   at Barotrauma.GameMain.Run() in <DEV>\Barotrauma\BarotraumaServer\ServerSource\GameMain.cs:line 325
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Program.cs:line 78
```

**Comment by PhilippFr** [comment]
@Regalis11 Is there anything I can do to help fix this issue? It keeps us from playing...
