### ISSUE TITLE
Uploading Network Error Data Log - Server Disconnected All Clients at Mission Start

### ISSUE THREAD

**Issue by CptDumbo** [Regalis11/Barotrauma#10123]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Was playing through a modded campaign with some friends. Did a couple missions and traveled to several stations. Once arriving at a station and finishing a mission everyone got disconnected after it loaded the station. Log is attached.
[networkerror_data.log](https://github.com/Regalis11/Barotrauma/files/9825172/networkerror_data.log)

### Reproduction steps

Not sure how to reproduce this without going through another campaign. Unsure what caused the crash.

### Bug prevalence

Happens every now and then

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
I dug around for a crash report but I guess the game didn't "crash" but just disconnect everyone. Below is the Network Error Log Data:

     V ,AßŸ/(ýßÿmA’t" €Ð‘" àÁò" `N–" @{†"  €\•" `^ªÃ" À2Ü/# àà@A oàÐá`ù•YA   àï
Index was outside the bounds of the array.
Message length: 2624 (328 bytes)
Read position: 2609
Header: ENTITY_POSITION
Previous header: ENTITY_POSITION
Previous object was 760 bits long (95 bytes)
 
   at Barotrauma.Networking.MsgReader.ReadSingle(Byte[] buf, Int32& bitPos)
   at Barotrauma.Character.ClientReadPosition(IReadMessage msg, Single sendingTime)
   at Barotrauma.Networking.GameClient.ReadIngameUpdate(IReadMessage inc)
 
 - Human
 - Mudraptor_player
 - Mudraptor_player
Last console messages:
[10/19/2022 20:16:29] [SERVER] Propagating config to all clients...
[10/19/2022 20:16:27] Lobby created!
[10/19/2022 20:16:26] [CLIENT] Got config packet!
[10/19/2022 20:16:26] Performance Fix: Executing init.lua
[10/19/2022 20:16:26] Playable Mudraptor Job 3 (Electric Boogaloo): Executing init.lua
[10/19/2022 20:16:26] Performance Fix: Executing init.lua
[10/19/2022 20:16:26] Let Them All In: Executing letthemallin.lua
[10/19/2022 20:16:25] Using LuaSetup.lua from the content package.
[10/19/2022 20:16:25] BetterHealthUIMod..ctor
[10/19/2022 20:16:25] [CLIENT] Created settings button
[10/19/2022 20:16:25] [CLIENT] Collected 7 pirate outposts
[10/19/2022 20:16:25] [CLIENT] Sorting modules by their diff ranges...
[10/19/2022 20:16:25] [CLIENT] Collecting pirate outposts...
[10/19/2022 20:16:25] [CLIENT] Collected 7 pirate outposts
[10/19/2022 20:16:25] [CLIENT] Sorting modules by their diff ranges...
[10/19/2022 20:16:25] [CLIENT] Collecting pirate outposts...
[10/19/2022 20:16:23] [CLIENT] Sent config packet to server!
[10/19/2022 20:16:23] [CLIENT] 
-Pirate Config-
Spawn Chance: 10
Husk Chance: 1
Spawn Noise: 10
Diff Noise: 10
Add Diff: True
-General Config-
RuinMoveChance: 25
[10/19/2022 20:16:23] [CLIENT] Mod Init
```

**Comment by Regalis11** [comment]
No known steps to repro, closing
