### ISSUE TITLE
[0.20.0.0] Unstable crashes when enemy attack happens

### ISSUE THREAD

**Issue by PanmanS** [Regalis11/Barotrauma#10170]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When enemy starts to fight, you getting crashed after start of confrontation with them. With me it happened with Giant Spineling, Spinelings and Pirate submarine being present (Also TMWReborn has same issue as me and i seen his problem)
[servercrashreport (4).log](https://github.com/Regalis11/Barotrauma/files/9882655/servercrashreport.4.log)
[servercrashreport (3).log](https://github.com/Regalis11/Barotrauma/files/9882685/servercrashreport.3.log)
[servercrashreport (5).log](https://github.com/Regalis11/Barotrauma/files/9882695/servercrashreport.5.log)

### Reproduction steps

1. start pirate mission in p2p server lobby on 100% without bots
2. go to pirates and be lucky with spinelings (you could spawn them too)
3. start fighting them
4. crash after 15 seconds - 60 seconds
5. ????
6. Profit

### Bug prevalence

Happens every time I play

### Version

Other

### -

0.20.0.0 Unstable

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Dedicated Server crash report (generated on 10/27/2022 22:35:03)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


Game version 0.20.0.0 (UnstableWindows, branch dev, revision 69b079928e)
Language: English
Selected content packages: Vanilla, Vanilla Submarines
Level seed: a6g514Wp
Loaded submarine: Reginleif (BF5B51A029729E1427F3EA9DD59F819C)
Selected screen: Barotrauma.GameScreen
Server (Round had started)


System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit


Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void UpdateAttack(Single)
Stack trace: 
   at Barotrauma.EnemyAIController.UpdateAttack(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\EnemyAIController.cs:line 1890
   at Barotrauma.EnemyAIController.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\EnemyAIController.cs:line 441
   at Barotrauma.Character.UpdateAll(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 2917
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 195
   at Barotrauma.GameMain.Run() in <DEV>\Barotrauma\BarotraumaServer\ServerSource\GameMain.cs:line 325
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Program.cs:line 78


Last debug messages:
   10/27/2022 22:35:03 - [10/27/2022 22:35:03]
  Saving banlist
   10/27/2022 22:35:03 - [10/27/2022 22:35:03]
  Rehex dropped Ceremonial Sword
   10/27/2022 22:35:03 - [10/27/2022 22:35:03]
  Rehex dropped Genetic Material (Hammerhead)
   10/27/2022 22:35:03 - [10/27/2022 22:35:03]
  Rehex picked up Fire Extinguisher
   10/27/2022 22:35:03 - [10/27/2022 22:35:03]
  Rehex equipped Fire Extinguisher
   10/27/2022 22:35:02 - [10/27/2022 22:35:02]
  Rehex dropped Genetic Material (Hammerhead)
   10/27/2022 22:35:02 - [10/27/2022 22:35:02]
  Rehex dropped Ceremonial Sword
   10/27/2022 22:35:02 - [10/27/2022 22:35:02]
  Rehex picked up Gene Splicer
   10/27/2022 22:35:01 - [10/27/2022 22:35:01]
  Outer wall breached by Spineling_giant
   10/27/2022 22:35:01 - [10/27/2022 22:35:01]
  Outer wall breached by Spineling_giant
   10/27/2022 22:35:01 - [10/27/2022 22:35:01]
  Inner wall breached by Spineling_giant
   10/27/2022 22:35:00 - [10/27/2022 22:35:00]
  Outer wall breached by Spineling_giant
   10/27/2022 22:35:00 - [10/27/2022 22:35:00]
  Rehex picked up Gene Splicer
   10/27/2022 22:34:59 - [10/27/2022 22:34:59]
  Console command "fixitems" executed by hUbert.
```

**Comment by Lefttroll** [comment]
So yeah, spinelings are main issue it seems

**Comment by PokkeTigrex** [comment]
This is easily replicated in sub editor as well, just spawn a bunch of spineling in testing mode.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c65d0274b13d411ec78b3fbeb57bdd3aa145dddc

**Comment by NilanthAnimosus** [comment]
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/c8ceeef48ec332d821d71a3a61df167f473a313b, no issues found, closing.
