### ISSUE TITLE
All games crashed simultaneously

### ISSUE THREAD

**Issue by Arobi485** [Regalis11/Barotrauma#10171]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Was sinking and then the game randomly crashed

### Reproduction steps

Sink :/

### Bug prevalence

Just once

### Version

Other

### -

v0.20.0.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 10/27/2022 23:17:08)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


CF121C94D13F01CFA90FC9F4FB013714


Game version 0.20.0.0 (UnstableWindows, branch dev, revision 69b079928e)
Graphics mode: 2560x1440 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla, Sub Creation, Azimuth- editting, Duct, Duct Assembly, Eel - Scout, Humpback - Modified, KastrullDrone - Inverted, Kestral, Kestrel, R-29 - Shuttle Transport, Aroboid
Level seed: Butterdon LineaSerac
Loaded submarine: Camel (A5AF17C7FCC916F40A3F614928254EAE)
Selected screen: Barotrauma.GameScreen
SteamManager initialized
Client (Round had started)


System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit
    GPU name: NVIDIA GeForce RTX 2070 SUPER
    Display mode: {Width:2560 Height:1440 Format:Color AspectRatio:1.7777778}
    GPU status: Normal


Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void Control(Single, Barotrauma.Camera)
Stack trace: 
   at Barotrauma.Character.Control(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 2083
   at Barotrauma.Character.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 3124
   at Barotrauma.AICharacter.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AICharacter.cs:line 72
   at Barotrauma.Character.UpdateAll(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 2917
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 192
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 859
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58


Last debug messages:
[10/27/2022 22:58:15] Kyldriis
[10/27/2022 22:58:15] Fróst.
[10/27/2022 22:58:15] Nonabyssal
[10/27/2022 22:58:15] Arobi
[10/27/2022 22:58:10] Kyldriis
[10/27/2022 22:58:10] Fróst.
[10/27/2022 22:58:10] Nonabyssal
[10/27/2022 22:58:10] Arobi
[10/27/2022 22:58:07] Server running slowly (57 updates/s)!
[10/27/2022 22:58:06] Kyldriis
[10/27/2022 22:58:06] Fróst.
[10/27/2022 22:58:06] Nonabyssal
[10/27/2022 22:58:06] Arobi
[10/27/2022 22:58:04] Kyldriis
[10/27/2022 22:58:04] Fróst.
[10/27/2022 22:58:04] Nonabyssal
[10/27/2022 22:58:03] Arobi
[10/27/2022 22:58:03] Received STARTGAMEFINALIZE packet. Round init status: Started
[10/27/2022 22:58:01] Task count: 0
[10/27/2022 22:58:01] Received STARTGAMEFINALIZE packet. Round init status: WaitingForStartGameFinalize
[10/27/2022 22:57:58] Generating an outpost for the start of the level... (Location: Butterdon Linea Prospecting Outpost, level type: LocationConnection)
[10/27/2022 22:57:58] Generating an outpost for the end of the level... (Location: Serac, level type: LocationConnection)
[10/27/2022 22:57:58] WARNING: Failed to find a valid position far enough from the main path. Choosing the furthest possible position.
   at System.Environment.get_StackTrace()
   at Barotrauma.Level.FindPosAwayFromMainPath(Double minDistance, Boolean asCloseAsPossible, Nullable`1 limits) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Map\Levels\Level.cs:line 2209
   at Barotrauma.Level.GenerateCaves(Tunnel parentTunnel) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Map\Levels\Level.cs:line 1936
   at Barotrauma.Level.Generate(Boolean mirror, Location startLocation, Location endLocation) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Map\Levels\Level.cs:line 659
   at Barotrauma.Level.Generate(LevelData levelData, Boolean mirror, Location startLocation, Location endLocation, SubmarineInfo startOutpost, SubmarineInfo endOutpost) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Map\Levels\Level.cs:line 466
   at Barotrauma.GameSession.StartRound(LevelData levelData, Boolean mirrorLevel, SubmarineInfo startOutpost, SubmarineInfo endOutpost) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameSession.cs:line 425
   at Barotrauma.CampaignMode.<>c__DisplayClass33_0.<<SelectSummaryScreen>b__0>d.MoveNext() in E:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GameSession\GameModes\CampaignMode.cs:line 269
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecuteFromThreadPool(Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
[10/27/2022 22:57:58] Level identifier: ridgebasic
[10/27/2022 22:57:53] Kyldriis
[10/27/2022 22:57:53] Fróst.
[10/27/2022 22:57:53] Nonabyssal
[10/27/2022 22:57:53] Arobi
[10/27/2022 22:57:52] Kyldriis
[10/27/2022 22:57:52] Fróst.
[10/27/2022 22:57:52] Nonabyssal
[10/27/2022 22:57:52] Arobi
[10/27/2022 22:57:51] Kyldriis
[10/27/2022 22:57:51] Fróst.
[10/27/2022 22:57:51] Nonabyssal
[10/27/2022 22:57:51] Arobi
[10/27/2022 22:57:51] Kyldriis
[10/27/2022 22:57:51] Fróst.
[10/27/2022 22:57:51] Nonabyssal
[10/27/2022 22:57:51] Arobi
[10/27/2022 22:46:00] Kyldriis
[10/27/2022 22:46:00] Fróst.
[10/27/2022 22:46:00] Nonabyssal
[10/27/2022 22:46:00] Arobi
[10/27/2022 22:46:00] Kyldriis
[10/27/2022 22:46:00] Fróst.
[10/27/2022 22:46:00] Nonabyssal
[10/27/2022 22:46:00] Arobi
[10/27/2022 22:45:55] Server running slowly (58 updates/s)!
[10/27/2022 22:45:53] Kyldriis
[10/27/2022 22:45:53] Fróst.
[10/27/2022 22:45:53] Nonabyssal
[10/27/2022 22:45:53] Arobi
[10/27/2022 22:45:51] Kyldriis
[10/27/2022 22:45:51] Fróst.
[10/27/2022 22:45:51] Nonabyssal
[10/27/2022 22:45:51] Arobi
[10/27/2022 22:45:49] Received STARTGAMEFINALIZE packet. Round init status: Started
[10/27/2022 22:45:49] Task count: 0
[10/27/2022 22:45:49] Received STARTGAMEFINALIZE packet. Round init status: WaitingForStartGameFinalize
[10/27/2022 22:45:46] Generating an outpost for the start of the level... (Location: Serac, level type: Outpost)
[10/27/2022 22:45:46] Level identifier: outpostlevel
[10/27/2022 22:45:38] Server running slowly (57 updates/s)!
[10/27/2022 22:42:57] Lobby created!
[10/27/2022 22:42:04] Attempting to open ALC device "OpenAL Soft on Headset Earphone (CORSAIR VIRTUOSO XT Wireless Gaming Headset)"
[10/27/2022 22:42:00] Logged in as Arobi (SteamID STEAM_1:1:85187883)
```

**Comment by Arobi485** [comment]
All 4 people who were playing, had there games crash at the same time

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c4761240f404c0d6fe5806371bc01f265dedb33e

**Comment by Rokvach** [comment]
There hasn't been any sighting of this appearing in GA after the fix nor has it caused any new issues to surface, seems to be working correctly. Closing.
