### ISSUE TITLE
Error occurs when using new melee weapons on shields

### ISSUE THREAD

**Issue by PokkeTigrex** [Regalis11/Barotrauma#10179]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

If you strike one of the two shields with the ceremonial sword or heavy wrench, a error like this pops up. Happens every time it strikes the shield.
Only the new weapons seem to be an issue, though stuff like the 40mm acid grenades nor the arc emitter don't have any issue.
![image](https://user-images.githubusercontent.com/85914375/198600235-7e5576d8-5cdd-47c3-80c4-ef3992baf63d.png)
![image](https://user-images.githubusercontent.com/85914375/198604846-80da8159-78ac-4f11-ab14-fad7205389c8.png)

### Reproduction steps

Get someone to hold the riot shield of moloch shell fragment, attempt to hit the shield itself with the ceremonial sword or heavy wrench.

### Bug prevalence

Happens every time I play

### Version

Other

### -

0.20.0.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
ItemComponent.DegreeOfSuccess failed (character was null).
   at System.Environment.get_StackTrace()
   at Barotrauma.Items.Components.ItemComponent.DegreeOfSuccess(Character character, List`1 requiredSkills) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\ItemComponent.cs:line 676
   at Barotrauma.Items.Components.ItemComponent.DegreeOfSuccess(Character character) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\ItemComponent.cs:line 663
   at Barotrauma.Items.Components.MeleeWeapon.HandleImpact(Fixture targetFixture) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Holdable\MeleeWeapon.cs:line 451
   at Barotrauma.Items.Components.MeleeWeapon.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Holdable\MeleeWeapon.cs:line 193
   at Barotrauma.Item.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 1930
   at Barotrauma.MapEntity.UpdateAll(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\MapEntity.cs:line 600
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 254
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 859
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 651
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/368aea907fb4d5862b1c8a2fcd281d5802c1dff8

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
