### ISSUE TITLE
Game random crash (CharacterAbilityGroupInterval.UpdateAbilityGroup)

### ISSUE THREAD

**Issue by Slaneche** [Regalis11/Barotrauma#10204]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

the game crashed 10 min after starting multiplayer. the only thing we've done is tidy up 

### Reproduction steps

Go out the sub, in water

### Bug prevalence

Everytime in water

### Version

0.20.1.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
The server has crashed: servercrashreport.log||
Object reference not set to an instance of an object. (NullReferenceException)    at Barotrauma.Abilities.CharacterAbilityGiveItemStatToTags.ApplyEffect() in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\Talents\Abilities\CharacterAbilityGiveItemStatToTags.cs:line 30
   at Barotrauma.Abilities.CharacterAbilityGroupInterval.UpdateAbilityGroup(Single deltaTime) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\Talents\AbilityGroups\CharacterAbilityGroupInterval.cs:line 53
   at Barotrauma.CharacterTalent.UpdateTalent(Single deltaTime) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\Talents\CharacterTalent.cs:line 70
   at Barotrauma.Character.Update(Single deltaTime, Camera cam) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 2975
   at Barotrauma.Character.UpdateAll(Single deltaTime, Camera cam) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 2920
   at Barotrauma.GameScreen.Update(Double deltaTime) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 195
   at Barotrauma.GameMain.Run() in E:\Barotrauma-development\Barotrauma\BarotraumaServer\ServerSource\GameMain.cs:line 325
   at Barotrauma.Program.Main(String[] args) in E:\Barotrauma-development\Barotrauma\BarotraumaServer\ServerSource\Program.cs:line 78
```

**Comment by Slaneche** [comment]
![image](https://user-images.githubusercontent.com/111175806/199339914-42ad3c00-d04b-49a1-8c2d-a9640f7d344a.png)

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4f36b9f307ce379687df77357e5f4a4da37b3e27
