### ISSUE TITLE
Game crash in combat (EnemyAIController.UpdateLimbAttack)

### ISSUE THREAD

**Issue by Slaneche** [Regalis11/Barotrauma#10249]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

the game as crash in combat

### Reproduction steps

no reproduction for now

### Bug prevalence

Just once

### Version

0.20.3.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
The server has crashed: servercrashreport (4).log||
Object reference not set to an instance of an object. (NullReferenceException)    at Barotrauma.EnemyAIController.UpdateLimbAttack(Single deltaTime, Vector2 attackSimPos, IDamageable damageTarget, Single distance, Limb targetLimb) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\EnemyAIController.cs:line 2148
   at Barotrauma.EnemyAIController.UpdateAttack(Single deltaTime) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\EnemyAIController.cs:line 1892
   at Barotrauma.EnemyAIController.Update(Single deltaTime) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\EnemyAIController.cs:line 441
   at Barotrauma.Character.UpdateAll(Single deltaTime, Camera cam) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 2931
   at Barotrauma.GameScreen.Update(Double deltaTime) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 195
   at Barotrauma.GameMain.Run() in E:\Barotrauma-development\Barotrauma\BarotraumaServer\ServerSource\GameMain.cs:line 325
   at Barotrauma.Program.Main(String[] args) in E:\Barotrauma-development\Barotrauma\BarotraumaServer\ServerSource\Program.cs:line 78
```

**Comment by BiffW** [comment]
Another crash in singleplayer campaign, this time hammerheads breached my upper hatch and game crashed.

`Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Boolean UpdateLimbAttack(Single, Microsoft.Xna.Framework.Vector2, Barotrauma.IDamageable, Single, Barotrauma.Limb)
Stack trace: 
   at Barotrauma.EnemyAIController.UpdateLimbAttack(Single deltaTime, Vector2 attackSimPos, IDamageable damageTarget, Single distance, Limb targetLimb) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\EnemyAIController.cs:line 2237
   at Barotrauma.EnemyAIController.UpdateAttack(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\EnemyAIController.cs:line 1963
   at Barotrauma.EnemyAIController.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\EnemyAIController.cs:line 440
   at Barotrauma.Character.UpdateAll(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 2925
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 192
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 860
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58`

**Comment by Rokvach** [comment]
This crash hasn't shown up in the GameAnalytics, seems to be working correctly. Closing.
