### ISSUE TITLE
[Factions] Scripted Event related crash at the start of a round inside an outpost

### ISSUE THREAD

**Issue by evilfactory** [Regalis11/Barotrauma#10314]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

At the start of a round inside an outpost, i get these console errors 
![Barotrauma_3u1Txgm12Y](https://user-images.githubusercontent.com/36804725/201390160-7216bf39-b7eb-46a5-a516-9cbd49910a91.png)
and after i resumed the game, it immediately crashed.
[crashreport (178).log](https://github.com/Regalis11/Barotrauma/files/9992116/crashreport.178.log)

### Reproduction steps
[Save 31.save.txt](https://github.com/Regalis11/Barotrauma/files/9992174/Save.31.save.txt)

- Load the above save file
- Crash

### Bug prevalence

Just once

### Version

Faction test branch

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 11/11/2022 13:49:44)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

466C335B980323833CB03ED31E64590A

Game version 100.2.0.0 (UnstableWindows, branch feature/fullrelease-testing, revision 7dbb372cb3)
Graphics mode: 1280x1024 (BorderlessWindowed)
VSync OFF
Language: English
Selected content packages: Vanilla, Lua For Barotrauma, traitormod2
Level seed: St. Musk
Loaded submarine: Dugong (F9EBE2F02EE9EDFFB975972EEA27534B)
Selected screen: Barotrauma.GameScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit
    GPU name: AMD Radeon(TM) Vega 8 Graphics
    Display mode: {Width:1280 Height:1024 Format:Color AspectRatio:1.25}
    GPU status: Normal

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Boolean IsFinished(System.String ByRef)
Stack trace: 
   at Barotrauma.EventAction.SubactionGroup.IsFinished(String& goTo) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\EventActions\EventAction.cs:line 49
   at Barotrauma.BinaryOptionAction.DetermineFinished(String& goTo) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\EventActions\BinaryOptionAction.cs:line 66
   at Barotrauma.ScriptedEvent.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\ScriptedEvent.cs:line 189
   at Barotrauma.EventManager.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\EventManager.cs:line 796
   at Barotrauma.GameSession.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameSession.cs:line 765
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 150
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 860
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[11/11/2022 13:49:19] System.NullReferenceException: Object reference not set to an instance of an object.
   at Barotrauma.EventAction.Instantiate(ScriptedEvent scriptedEvent, ContentXElement element) in C:\Users\joona\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Events\EventActions\EventAction.cs:line 159
[11/11/2022 13:49:19] System.NullReferenceException: Object reference not set to an instance of an object.
   at Barotrauma.EventAction.Instantiate(ScriptedEvent scriptedEvent, ContentXElement element) in C:\Users\joona\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Events\EventActions\EventAction.cs:line 159
[11/11/2022 13:49:19] System.NullReferenceException: Object reference not set to an instance of an object.
   at Barotrauma.EventAction.Instantiate(ScriptedEvent scriptedEvent, ContentXElement element) in C:\Users\joona\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Events\EventActions\EventAction.cs:line 159
[11/11/2022 13:49:12] Generating an outpost for the start of the level... (Location: St. Musk Habitation Outpost, level type: Outpost)
[11/11/2022 13:49:12] Level identifier: outpostlevel
[11/11/2022 13:48:57] Transitioning to St. Musk (current location: Shinkonai Biomedical Research Center, selected location: St. Musk Habitation Outpost, leaving sub: Dugong, at start: False, at end: True, transition type: ProgressToNextLocation)
[11/11/2022 13:47:41] teleport
[11/11/2022 13:47:40] teleport
[11/11/2022 13:47:40] teleport
[11/11/2022 13:47:36] teleport
[11/11/2022 13:47:36] teleport
[11/11/2022 13:47:35] teleport
[11/11/2022 13:47:35] teleport
[11/11/2022 13:47:16] Godmode on
[11/11/2022 13:47:16] godmode_mainsub
[11/11/2022 13:47:12] fixhulls
[11/11/2022 13:47:07] teleportsub
[11/11/2022 13:47:06] teleportsub
[11/11/2022 13:47:06] teleportsub
[11/11/2022 13:47:05] teleportsub
[11/11/2022 13:47:05] teleportsub
[11/11/2022 13:47:04] teleportsub
[11/11/2022 13:47:04] teleportsub
[11/11/2022 13:47:03] teleportsub
[11/11/2022 13:46:58] fixhulls
[11/11/2022 13:46:49] Lighting disabled
[11/11/2022 13:46:49] lighting
[11/11/2022 13:46:47] freecam
[11/11/2022 13:46:41] Start a new round to apply the upgrades.
[11/11/2022 13:46:41] Upgraded mechanicaldevices.decreaselowskillfixduration by 0 levels.
[11/11/2022 13:46:41] Upgraded mechanicaldevices.decreasedeteriorationspeed by 0 levels.
[11/11/2022 13:46:41] Upgraded junctionboxes.increaseovervoltageresistance by 0 levels.
[11/11/2022 13:46:41] Upgraded deconstructors.decreasedeconstructiontime by 0 levels.
[11/11/2022 13:46:41] Upgraded pumps.increasemaxpumpflow by 0 levels.
[11/11/2022 13:46:41] Upgraded weapons.turretincreaserotationlowskill by 0 levels.
[11/11/2022 13:46:41] Upgraded weapons.turretdecreasepowerconsumption by 0 levels.
[11/11/2022 13:46:41] Upgraded weapons.turretincreaseoffsetonselected by 0 levels.
[11/11/2022 13:46:41] Upgraded batteries.increasebatterycapacity by 0 levels.
[11/11/2022 13:46:41] Upgraded batteries.increasebatteryrechargespeed by 0 levels.
[11/11/2022 13:46:41] Upgraded reactors.increasereactoroutput by 0 levels.
[11/11/2022 13:46:41] Upgraded reactors.decreasefuelconsumption by 0 levels.
[11/11/2022 13:46:41] Upgraded walls.increasewallhealth by 0 levels.
[11/11/2022 13:46:41] Upgraded monitors.enablemineralscanner by 0 levels.
[11/11/2022 13:46:41] Upgraded supercapacitors.increasesupercapacitorcapacity by 0 levels.
[11/11/2022 13:46:41] Upgraded supercapacitors.increasesupercapacitorrechargespeed by 0 levels.
[11/11/2022 13:46:41] Upgraded electricaldevices.decreaselowskillfixduration by 0 levels.
[11/11/2022 13:46:41] Upgraded electricaldevices.decreasedeteriorationspeed by 0 levels.
[11/11/2022 13:46:41] Upgraded engines.increaseenginemaxforce by 0 levels.
[11/11/2022 13:46:41] Upgraded fabricators.increasefabricationspeed by 0 levels.
[11/11/2022 13:46:41] maxupgrades
[11/11/2022 13:46:37] Start a new round to apply the upgrades.
[11/11/2022 13:46:37] Upgraded mechanicaldevices.decreaselowskillfixduration by 0 levels.
[11/11/2022 13:46:37] Upgraded mechanicaldevices.decreasedeteriorationspeed by 0 levels.
[11/11/2022 13:46:37] Upgraded junctionboxes.increaseovervoltageresistance by 0 levels.
[11/11/2022 13:46:37] Upgraded deconstructors.decreasedeconstructiontime by 0 levels.
[11/11/2022 13:46:37] Upgraded pumps.increasemaxpumpflow by 0 levels.
[11/11/2022 13:46:37] Upgraded weapons.turretincreaserotationlowskill by 0 levels.
[11/11/2022 13:46:37] Upgraded weapons.turretdecreasepowerconsumption by 0 levels.
[11/11/2022 13:46:37] Upgraded weapons.turretincreaseoffsetonselected by 0 levels.
[11/11/2022 13:46:37] Upgraded batteries.increasebatterycapacity by 0 levels.
[11/11/2022 13:46:37] Upgraded batteries.increasebatteryrechargespeed by 0 levels.
[11/11/2022 13:46:37] Upgraded reactors.increasereactoroutput by 0 levels.
[11/11/2022 13:46:37] Upgraded reactors.decreasefuelconsumption by 0 levels.
[11/11/2022 13:46:37] Upgraded walls.increasewallhealth by 0 levels.
[11/11/2022 13:46:37] Upgraded monitors.enablemineralscanner by 0 levels.
[11/11/2022 13:46:37] Upgraded supercapacitors.increasesupercapacitorcapacity by 0 levels.
[11/11/2022 13:46:37] Upgraded supercapacitors.increasesupercapacitorrechargespeed by 0 levels.
[11/11/2022 13:46:37] Upgraded electricaldevices.decreaselowskillfixduration by 0 levels.
[11/11/2022 13:46:37] Upgraded electricaldevices.decreasedeteriorationspeed by 0 levels.
[11/11/2022 13:46:37] Upgraded engines.increaseenginemaxforce by 0 levels.
[11/11/2022 13:46:37] Upgraded fabricators.increasefabricationspeed by 0 levels.
[11/11/2022 13:46:37] maxupgrades
[11/11/2022 13:46:36] Start a new round to apply the upgrades.
[11/11/2022 13:46:36] Upgraded mechanicaldevices.decreaselowskillfixduration by 0 levels.
[11/11/2022 13:46:36] Upgraded mechanicaldevices.decreasedeteriorationspeed by 0 levels.
[11/11/2022 13:46:36] Upgraded junctionboxes.increaseovervoltageresistance by 0 levels.
[11/11/2022 13:46:36] Upgraded deconstructors.decreasedeconstructiontime by 0 levels.
[11/11/2022 13:46:36] Upgraded pumps.increasemaxpumpflow by 0 levels.
[11/11/2022 13:46:36] Upgraded weapons.turretincreaserotationlowskill by 0 levels.
[11/11/2022 13:46:36] Upgraded weapons.turretdecreasepowerconsumption by 0 levels.
[11/11/2022 13:46:36] Upgraded weapons.turretincreaseoffsetonselected by 0 levels.
[11/11/2022 13:46:36] Upgraded batteries.increasebatterycapacity by 0 levels.
[11/11/2022 13:46:36] Upgraded batteries.increasebatteryrechargespeed by 0 levels.
[11/11/2022 13:46:36] Upgraded reactors.increasereactoroutput by 0 levels.
[11/11/2022 13:46:36] Upgraded reactors.decreasefuelconsumption by 0 levels.
[11/11/2022 13:46:36] Upgraded walls.increasewallhealth by 0 levels.
[11/11/2022 13:46:36] Upgraded monitors.enablemineralscanner by 0 levels.
[11/11/2022 13:46:36] Upgraded supercapacitors.increasesupercapacitorcapacity by 0 levels.
[11/11/2022 13:46:36] Upgraded supercapacitors.increasesupercapacitorrechargespeed by 0 levels.
[11/11/2022 13:46:36] Upgraded electricaldevices.decreaselowskillfixduration by 0 levels.
[11/11/2022 13:46:36] Upgraded electricaldevices.decreasedeteriorationspeed by 0 levels.
[11/11/2022 13:46:36] Upgraded engines.increaseenginemaxforce by 0 levels.
[11/11/2022 13:46:36] Upgraded fabricators.increasefabricationspeed by 0 levels.
[11/11/2022 13:46:36] maxupgrades
[11/11/2022 13:46:36] Start a new round to apply the upgrades.
[11/11/2022 13:46:36] Upgraded mechanicaldevices.decreaselowskillfixduration by 0 levels.
[11/11/2022 13:46:36] Upgraded mechanicaldevices.decreasedeteriorationspeed by 0 levels.
[11/11/2022 13:46:36] Upgraded junctionboxes.increaseovervoltageresistance by 0 levels.
[11/11/2022 13:46:36] Upgraded deconstructors.decreasedeconstructiontime by 0 levels.
[11/11/2022 13:46:36] Upgraded pumps.increasemaxpumpflow by 0 levels.
[11/11/2022 13:46:36] Upgraded weapons.turretincreaserotationlowskill by 0 levels.
[11/11/2022 13:46:36] Upgraded weapons.turretdecreasepowerconsumption by 0 levels.
[11/11/2022 13:46:36] Upgraded weapons.turretincreaseoffsetonselected by 0 levels.
[11/11/2022 13:46:36] Upgraded batteries.increasebatterycapacity by 0 levels.
[11/11/2022 13:46:36] Upgraded batteries.increasebatteryrechargespeed by 0 levels.
[11/11/2022 13:46:36] Upgraded reactors.increasereactoroutput by 0 levels.
[11/11/2022 13:46:36] Upgraded reactors.decreasefuelconsumption by 0 levels.
[11/11/2022 13:46:36] Upgraded walls.increasewallhealth by 0 levels.
[11/11/2022 13:46:36] Upgraded monitors.enablemineralscanner by 0 levels.
[11/11/2022 13:46:36] Upgraded supercapacitors.increasesupercapacitorcapacity by 0 levels.
[11/11/2022 13:46:36] Upgraded supercapacitors.increasesupercapacitorrechargespeed by 0 levels.
[11/11/2022 13:46:36] Upgraded electricaldevices.decreaselowskillfixduration by 0 levels.
[11/11/2022 13:46:36] Upgraded electricaldevices.decreasedeteriorationspeed by 0 levels.
[11/11/2022 13:46:36] Upgraded engines.increaseenginemaxforce by 0 levels.
[11/11/2022 13:46:36] Upgraded fabricators.increasefabricationspeed by 0 levels.
[11/11/2022 13:46:36] maxupgrades
[11/11/2022 13:46:35] Start a new round to apply the upgrades.
[11/11/2022 13:46:35] Upgraded mechanicaldevices.decreaselowskillfixduration by 0 levels.
[11/11/2022 13:46:35] Upgraded mechanicaldevices.decreasedeteriorationspeed by 0 levels.
[11/11/2022 13:46:35] Upgraded junctionboxes.increaseovervoltageresistance by 0 levels.
[11/11/2022 13:46:35] Upgraded deconstructors.decreasedeconstructiontime by 0 levels.
[11/11/2022 13:46:35] Upgraded pumps.increasemaxpumpflow by 0 levels.
[11/11/2022 13:46:35] Upgraded weapons.turretincreaserotationlowskill by 0 levels.
[11/11/2022 13:46:35] Upgraded weapons.turretdecreasepowerconsumption by 0 levels.
[11/11/2022 13:46:35] Upgraded weapons.turretincreaseoffsetonselected by 0 levels.
[11/11/2022 13:46:35] Upgraded batteries.increasebatterycapacity by 0 levels.
[11/11/2022 13:46:35] Upgraded batteries.increasebatteryrechargespeed by 0 levels.
[11/11/2022 13:46:35] Upgraded reactors.increasereactoroutput by 0 levels.
[11/11/2022 13:46:35] Upgraded reactors.decreasefuelconsumption by 0 levels.
[11/11/2022 13:46:35] Upgraded walls.increasewallhealth by 0 levels.
[11/11/2022 13:46:35] Upgraded monitors.enablemineralscanner by 0 levels.
[11/11/2022 13:46:35] Upgraded supercapacitors.increasesupercapacitorcapacity by 0 levels.
[11/11/2022 13:46:35] Upgraded supercapacitors.increasesupercapacitorrechargespeed by 0 levels.
[11/11/2022 13:46:35] Upgraded electricaldevices.decreaselowskillfixduration by 0 levels.
[11/11/2022 13:46:35] Upgraded electricaldevices.decreasedeteriorationspeed by 0 levels.
[11/11/2022 13:46:35] Upgraded engines.increaseenginemaxforce by 0 levels.
[11/11/2022 13:46:35] Upgraded fabricators.increasefabricationspeed by 0 levels.
[11/11/2022 13:46:35] maxupgrades
[11/11/2022 13:46:32] fixhulls
[11/11/2022 13:46:16] Could not find a spawn point for a SpawnAction (spawn location: BeaconStation (tag: beacon_bandit), skipping.
[11/11/2022 13:45:55] Generating an outpost for the start of the level... (Location: St. Musk Habitation Outpost, level type: LocationConnection)
[11/11/2022 13:45:53] Generating an outpost for the end of the level... (Location: Shinkonai Biomedical Research Center, level type: LocationConnection)
[11/11/2022 13:45:29] Level identifier: greatseabasic
[11/11/2022 13:45:19] Transitioning to St. MuskShinkonai (current location: Shinkonai Biomedical Research Center, selected location: St. Musk Habitation Outpost, leaving sub: Dugong, at start: False, at end: True, transition type: ProgressToNextEmptyLocation)
[11/11/2022 13:45:00] Start a new round to apply the upgrades.
[11/11/2022 13:45:00] Upgraded mechanicaldevices.decreaselowskillfixduration by 1 levels.
[11/11/2022 13:45:00] Upgraded mechanicaldevices.decreasedeteriorationspeed by 1 levels.
[11/11/2022 13:45:00] Upgraded junctionboxes.increaseovervoltageresistance by 1 levels.
[11/11/2022 13:45:00] Upgraded deconstructors.decreasedeconstructiontime by 1 levels.
[11/11/2022 13:45:00] Upgraded pumps.increasemaxpumpflow by 1 levels.
[11/11/2022 13:45:00] Upgraded weapons.turretincreaserotationlowskill by 1 levels.
[11/11/2022 13:45:00] Upgraded weapons.turretdecreasepowerconsumption by 1 levels.
[11/11/2022 13:45:00] Upgraded weapons.turretincreaseoffsetonselected by 2 levels.
[11/11/2022 13:45:00] Upgraded batteries.increasebatterycapacity by 1 levels.
[11/11/2022 13:45:00] Upgraded batteries.increasebatteryrechargespeed by 1 levels.
[11/11/2022 13:45:00] Upgraded reactors.increasereactoroutput by 1 levels.
[11/11/2022 13:45:00] Upgraded reactors.decreasefuelconsumption by 1 levels.
[11/11/2022 13:45:00] Upgraded walls.increasewallhealth by 2 levels.
[11/11/2022 13:45:00] Upgraded monitors.enablemineralscanner by 1 levels.
[11/11/2022 13:45:00] Upgraded supercapacitors.increasesupercapacitorcapacity by 1 levels.
[11/11/2022 13:45:00] Upgraded supercapacitors.increasesupercapacitorrechargespeed by 1 levels.
[11/11/2022 13:45:00] Upgraded electricaldevices.decreaselowskillfixduration by 1 levels.
[11/11/2022 13:45:00] Upgraded electricaldevices.decreasedeteriorationspeed by 1 levels.
[11/11/2022 13:45:00] Upgraded engines.increaseenginemaxforce by 2 levels.
[11/11/2022 13:45:00] Upgraded fabricators.increasefabricationspeed by 1 levels.
[11/11/2022 13:45:00] maxupgrades
[11/11/2022 13:43:37] Enabled teleportation on the campaign map.
[11/11/2022 13:43:37] togglecampaignteleport
[11/11/2022 13:39:51] Could not find a suitable module for the location type LocationType (None). Module flag: Airlock.
[11/11/2022 13:39:51] Generating an outpost for the start of the level... (Location: Harmonia Linea, level type: LocationConnection)
[11/11/2022 13:39:50] Level identifier: coldcavernsbasic
[11/11/2022 13:39:39] Transitioning to Harmonia LineaHuronia (current location: Huronia, selected location: Harmonia Linea, leaving sub: Dugong, at start: True, at end: False, transition type: LeaveLocation)
[11/11/2022 13:39:30] teleport
[11/11/2022 13:39:30] teleport
[11/11/2022 13:39:29] teleport
[11/11/2022 13:39:28] teleport
[11/11/2022 13:39:28] teleport
[11/11/2022 13:39:28] teleport
[11/11/2022 13:39:21] teleport
[11/11/2022 13:39:21] teleport
[11/11/2022 13:39:21] teleport
[11/11/2022 13:39:20] teleport
[11/11/2022 13:39:20] teleport
[11/11/2022 13:39:17] Unlocked mission "Mining outpost material transport" in the connection from "Huronia" to "Harmonia Linea".
[11/11/2022 13:39:15] teleport
[11/11/2022 13:39:14] teleport
[11/11/2022 13:39:13] teleport
[11/11/2022 13:39:13] teleport
[11/11/2022 13:39:13] teleport
[11/11/2022 13:39:12] teleport
[11/11/2022 13:39:12] teleport
[11/11/2022 13:39:11] teleport
[11/11/2022 13:39:11] teleport
[11/11/2022 13:39:11] teleport
[11/11/2022 13:39:10] teleport
[11/11/2022 13:39:10] teleport
[11/11/2022 13:39:09] teleport
[11/11/2022 13:39:09] teleport
[11/11/2022 13:39:08] teleport
[11/11/2022 13:39:07] teleport
[11/11/2022 13:39:05] freecam
[11/11/2022 13:39:04] Lighting enabled
[11/11/2022 13:39:04] lighting
[11/11/2022 13:39:04] Lighting disabled
[11/11/2022 13:39:04] lighting
[11/11/2022 13:39:03] freecam
[11/11/2022 13:39:03] freecam
[11/11/2022 13:39:02] teleport
[11/11/2022 13:39:01] teleport
[11/11/2022 13:39:01] teleport
[11/11/2022 13:39:00] teleport
[11/11/2022 13:38:59] teleport
[11/11/2022 13:38:56] Steam achievements have been disabled during this play session.
[11/11/2022 13:38:56] Enabled cheat commands.
[11/11/2022 13:38:56] enablecheats
[11/11/2022 13:36:18] Loading a pre-selected outpost for the start of the level...
[11/11/2022 13:36:18] Level identifier: outpostlevel
[11/11/2022 13:32:24] Attempting to open ALC device "OpenAL Soft on Alto-falantes (Realtek High Definition Audio)"
[11/11/2022 13:32:21] Logged in as Evil Factory (SteamID STEAM_1:1:53859811)
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e98bf9bccfb9c860326042660163d8ff4dd7f80c

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
