### ISSUE TITLE
Multiplayer save not showing up after server crash

### ISSUE THREAD

**Issue by N5632** [Regalis11/Barotrauma#10418]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Was playing with 5 friends on a save we started up with the new update, was docking coming back from a personel and mining transport when server crashed (not the game) and sent me and my friends back to the main menu. I have looked at #4581 but I haven't been able to see on the character data the same issue that they had. It might be something else but I don't know if it is recoverable or where to start looking on the XML. I have made a backup of the files before editing but I was wondering if there are other fixes in the code that are possible for this save. 

Save Files: https://drive.google.com/drive/folders/1H08gLt1sdTnTlvJOBOw0egLXdd2wjmQT?usp=sharing

### Reproduction steps

Possibly having a personel transport mission
Attempting to recycle as the ship is docking 
Carrying too much on person before docking 

### Bug prevalence

Just once

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
[11/16/2022 03:50:03]
  Starting the server...
[11/16/2022 03:50:03]
  Using SteamP2P networking.
[11/16/2022 03:50:03]
  Server started
[11/16/2022 03:50:03]
  N5632 has joined the server.
[11/16/2022 03:50:03]
  Saving client permissions
[11/16/2022 03:50:03]
  Saving client permissions
[11/16/2022 03:50:05]
  Gamemode changed to Campaign
[11/16/2022 03:50:21]
  N5632 is ready to start the game.
[11/16/2022 03:50:46]
  Starting a new round...
[11/16/2022 03:50:46]
  N5632 is not ready to start the game.
[11/16/2022 03:50:47]
  Noodles has joined the server.
[11/16/2022 03:50:47]
  Saving client permissions
[11/16/2022 03:50:54]
  Game mode: Campaign
[11/16/2022 03:50:54]
  Submarine: Azimuth
[11/16/2022 03:50:54]
  Level seed: Dunwice
[11/16/2022 03:50:54]
  Andres Patel equipped Wrench
[11/16/2022 03:50:54]
  Andres Patel unequipped Wrench
[11/16/2022 03:50:54]
  Andres Patel equipped Screwdriver
[11/16/2022 03:50:54]
  Rupert Feinberg equipped Wrench
[11/16/2022 03:50:54]
  Rupert Feinberg unequipped Wrench
[11/16/2022 03:50:54]
  Rupert Feinberg equipped Screwdriver
[11/16/2022 03:50:54]
  Megan Eastman equipped Wrench
[11/16/2022 03:50:54]
  Megan Eastman unequipped Wrench
[11/16/2022 03:50:54]
  Megan Eastman equipped Screwdriver
[11/16/2022 03:50:54]
  Rene Gears equipped Wrench
[11/16/2022 03:50:54]
  Rene Gears unequipped Wrench
[11/16/2022 03:50:54]
  Rene Gears equipped Screwdriver
[11/16/2022 03:50:54]
  Rene Gears unequipped Screwdriver
[11/16/2022 03:50:54]
  Rene Gears equipped Crowbar
[11/16/2022 03:50:54]
  Cleopatra Donovan equipped Wrench
[11/16/2022 03:50:54]
  Cleopatra Donovan unequipped Wrench
[11/16/2022 03:50:54]
  Cleopatra Donovan equipped Screwdriver
[11/16/2022 03:50:55]
  Eliza Wiley equipped Crowbar
[11/16/2022 03:50:55]
  Katrina Hallett equipped Wrench
[11/16/2022 03:50:55]
  Round started.
[11/16/2022 03:50:56]
  Tod Swanger equipped Crowbar
[11/16/2022 03:50:56]
  Tod Swanger: You people look like you could use some rest.
[11/16/2022 03:50:56]
  Katrina Hallett unequipped Wrench
[11/16/2022 03:50:56]
  Rene Gears unequipped Crowbar
[11/16/2022 03:50:56]
  Eliza Wiley unequipped Crowbar
[11/16/2022 03:50:57]
  Andres Patel unequipped Screwdriver
[11/16/2022 03:50:57]
  Tod Swanger unequipped Crowbar
[11/16/2022 03:51:01]
  Megan Eastman: You know, I had a brilliant business idea the other day.
[11/16/2022 03:51:06]
  WARNING: event count very high: 291
1. EntitySpawner x79
2. Barotrauma.Hull x44
3. Human x27
[11/16/2022 03:51:19]
  N5632 set the value "Channel" of the item "Headset" to "0".
[11/16/2022 03:51:21]
  Noodles set the value "Channel" of the item "Headset" to "0".
[11/16/2022 03:51:40]
  Noodles equipped Plasma Cutter
[11/16/2022 03:51:53]
  Client "N5632" ended the round.
[11/16/2022 03:51:54]
  Ending the round...
   at System.Environment.get_StackTrace()
   at Barotrauma.Networking.GameServer.EndGame(TransitionType transitionType, Boolean wasSaved) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Networking\GameServer.cs:line 2605
   at Barotrauma.Networking.GameServer.ClientReadServerCommand(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Networking\GameServer.cs:line 1407
   at Barotrauma.Networking.GameServer.ReadDataMessage(NetworkConnection sender, IReadMessage inc) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Networking\GameServer.cs:line 804
   at Barotrauma.Networking.SteamP2PServerPeer.HandleDataMessage(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Networking\Primitives\Peers\Server\SteamP2PServerPeer.cs:line 237
   at Barotrauma.Networking.SteamP2PServerPeer.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Networking\Primitives\Peers\Server\SteamP2PServerPeer.cs:line 90
   at Barotrauma.Networking.GameServer.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Networking\GameServer.cs:line 581
   at Barotrauma.GameMain.Run() in <DEV>\Barotrauma\BarotraumaServer\ServerSource\GameMain.cs:line 329
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Program.cs:line 78
```

**Comment by N5632** [comment]
The log shown is the last log before the crash happened

**Comment by N5632** [comment]
[The sub that sank_2022-11-16_0243.txt](https://github.com/Regalis11/Barotrauma/files/10024848/The.sub.that.sank_2022-11-16_0243.txt)
apologies the log above is incorrect the log here is the last log before the server crashed
