### ISSUE TITLE
Crash (MutableWorkshopMenu)

### ISSUE THREAD

**Issue by Simon242908** [Regalis11/Barotrauma#10433]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

it crashed

### Reproduction steps

i dont know

### Bug prevalence

Just once

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 11/18/2022 14:30:58)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


0DC439F0B0CA5A5A6693500952309D61


Game version 0.19.14.0 (ReleaseWindows, branch release, revision 0daf5b87bd)
Graphics mode: 1920x1080 (Fullscreen)
VSync ON
Language: English
Selected content packages: Vanilla, Beacons Extended, Brighter Lights, Shipwrecks Extended, Lua For Barotrauma, Humpback Großreinigung, MoreMissionsMod, Stack Size Increase, Better Dive Suits, Meaningful Upgrades, Backpacks, IMC BEACON A-27, PROGENITOR, Combinable Ammo Revived (NOW WORKS WITH ALL AMMO), Enhanced Armaments, Cobalta
Level seed: no level loaded
Loaded submarine: None
Selected screen: Barotrauma.MainMenuScreen
SteamManager initialized


System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit
    GPU name: NVIDIA GeForce GTX 1660 Ti
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal


Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void <CreateSubscribeButton>b__3(Microsoft.Xna.Framework.Graphics.SpriteBatch, Barotrauma.GUICustomComponent)
Stack trace: 
   at Barotrauma.Steam.MutableWorkshopMenu.<>c__DisplayClass35_0.<CreateSubscribeButton>b__3(SpriteBatch spriteBatch, GUICustomComponent component) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Steam\WorkshopMenu\Mutable\ItemList.cs:line 406
   at Barotrauma.GUICustomComponent.Draw(SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUICustomComponent.cs:line 43
   at Barotrauma.GUIComponent.DrawManually(SpriteBatch spriteBatch, Boolean alsoChildren, Boolean recursive) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIComponent.cs:line 581
   at Barotrauma.GUIComponent.DrawChildren(SpriteBatch spriteBatch, Boolean recursive) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIComponent.cs:line 588
   at Barotrauma.GUIComponent.DrawChildren(SpriteBatch spriteBatch, Boolean recursive) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIComponent.cs:line 588
   at Barotrauma.GUIComponent.DrawChildren(SpriteBatch spriteBatch, Boolean recursive) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIComponent.cs:line 588
   at Barotrauma.GUIComponent.DrawChildren(SpriteBatch spriteBatch, Boolean recursive) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIComponent.cs:line 588
   at Barotrauma.GUIListBox.Draw(SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIListBox.cs:line 1291
   at Barotrauma.GUIComponent.DrawManually(SpriteBatch spriteBatch, Boolean alsoChildren, Boolean recursive) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIComponent.cs:line 581
   at Barotrauma.GUIListBox.Draw(SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIListBox.cs:line 1291
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Barotrauma.GUI.Draw(Camera cam, SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 251
   at Barotrauma.MainMenuScreen.Draw(Double deltaTime, GraphicsDevice graphics, SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\MainMenuScreen.cs:line 983
   at Barotrauma.GameMain.Draw(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 957
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 669
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 508
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58


Last debug messages:
[11/18/2022 14:12:55] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/pc/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2764968387/Turrets/turretschematics.png, size: 914x491)
[11/18/2022 14:12:54] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/pc/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2764968387/Afflictions/afflictions.png, size: 777x128)
[11/18/2022 14:11:46] Attempting to open ALC device "OpenAL Soft on Reproduktory (USB Audio Device)"
[11/18/2022 14:11:23] Logged in as SyStem_eRroR (SteamID STEAM_1:1:556993286)
```

**Comment by juanjp600** [comment]
Repro steps:
- Open the game while Steam is running
- Go into the Steam Workshop menu, look at the Popular Mods tab
- Exit Steam without closing the game

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/32f93563d2b5b9bfc836a5b6d1df5e5f06dffbfb
