### ISSUE TITLE
Скачал пиратскую версию, скачал пару модов, по инструкции установил Lua. При заходе вылетает ошибка.

### ISSUE THREAD

**Issue by CerberusTheDemon** [Regalis11/Barotrauma#10439]
Barotrauma Client crash report (generated on 11/19/2022 17:33:09)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

997CD079A4CCAE85B2B8B09434C7386D

Game version 0.19.11.0 (ReleaseWindows, branch master, revision 8fef89a255)
Graphics mode: 1920x1080 (Fullscreen)
VSync OFF
Language: Russian
Selected content packages: Vanilla, EK Armory, EK Utilities, Meaningful Upgrades, New Wrecks For Barotrauma (With sellable wrecks), MoreHeadgear, RIBA Portable Items - Брухма Апдейт, EK Gunnery, EK Dockyard, Lua For Barotrauma, Survivor Extended Monsters Fixes, Stations from beyond, [VH] The Iroh, Plasma Weapons, Испаритель, BaroDrama Diving Suits, Movable and Sellable Wrecks, Neurotrauma, NT Cybernetics, CsForBarotrauma, BetterHealthUI, P4 - Pufferfish, Sardine, [ACE] The Old Clown, Copperhead, Acolyte Job, The Atron
Level seed: no level loaded
Loaded submarine: None
Selected screen: None
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit
    GPU name: Radeon RX 570 Series
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Could not load file or assembly 'System.Net.Quic, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Не удается найти указанный файл. (System.IO.FileNotFoundException)
Target site: System.Object _CreateCaObject(System.Reflection.RuntimeModule, System.RuntimeType, System.IRuntimeMethodInfo, Byte**, Byte*, Int32*)
Stack trace: 
   at System.Reflection.CustomAttribute._CreateCaObject(RuntimeModule pModule, RuntimeType type, IRuntimeMethodInfo pCtor, Byte** ppBlob, Byte* pEndBlob, Int32* pcNamedArgs)
   at System.Reflection.CustomAttribute.AddCustomAttributes(ListBuilder`1& attributes, RuntimeModule decoratedModule, Int32 decoratedMetadataToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, ListBuilder`1 derivedAttributes)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeMethodInfo method, RuntimeType caType, Boolean inherit)
   at System.Attribute.GetCustomAttributes(MemberInfo element, Type attributeType, Boolean inherit)
   at System.Reflection.CustomAttributeExtensions.GetCustomAttributes[T](MemberInfo element, Boolean inherit)
   at System.Diagnostics.StackTrace.TryResolveStateMachineMethod(MethodBase& method, Type& declaringType)
   at System.Diagnostics.StackTrace.ToString(TraceFormat traceFormat, StringBuilder sb)
   at System.Diagnostics.StackTrace.ToString(TraceFormat traceFormat)
   at System.Exception.get_StackTrace()
   at System.Exception.ToString()
   at System.Exception.ToString()
   at Barotrauma.GameAnalyticsManager.CheckResponse(IRestResponse response)
   at Barotrauma.GameAnalyticsManager.<>c.<InitIfConsented>b__15_1(Task t)
   at Barotrauma.TaskPool.<>c__DisplayClass6_0.<Add>b__0(Task t, Object obj)
   at Barotrauma.TaskPool.Update()
   at Barotrauma.GameMain.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in C:\Users\joona\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in C:\Users\joona\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in C:\Users\joona\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in C:\Users\joona\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in C:\Users\joona\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args)

Last debug messages:
[11/19/2022 17:33:03] Overriding an affliction or a buff with the identifier 'combatstimulant' using the file 'LocalMods/2776270649/Xml/Afflictions.xml'
[11/19/2022 17:33:03] Overriding an affliction or a buff with the identifier 'implacable' using the file 'LocalMods/2776270649/Xml/Afflictions.xml'
[11/19/2022 17:33:03] Overriding an affliction or a buff with the identifier 'concussion' using the file 'LocalMods/2776270649/Xml/Afflictions.xml'
[11/19/2022 17:33:03] Overriding an affliction or a buff with the identifier 'radiationsickness' using the file 'LocalMods/2776270649/Xml/Afflictions.xml'
[11/19/2022 17:33:03] Overriding an affliction or a buff with the identifier 'drunk' using the file 'LocalMods/2776270649/Xml/Afflictions.xml'
[11/19/2022 17:33:03] Overriding an affliction or a buff with the identifier 'invertcontrols' using the file 'LocalMods/2776270649/Xml/Afflictions.xml'
[11/19/2022 17:33:03] Overriding an affliction or a buff with the identifier 'chemwithdrawal' using the file 'LocalMods/2776270649/Xml/Afflictions.xml'
[11/19/2022 17:33:03] Overriding an affliction or a buff with the identifier 'chemaddiction' using the file 'LocalMods/2776270649/Xml/Afflictions.xml'
[11/19/2022 17:33:03] Overriding an affliction or a buff with the identifier 'opiatewithdrawal' using the file 'LocalMods/2776270649/Xml/Afflictions.xml'
[11/19/2022 17:33:03] Overriding an affliction or a buff with the identifier 'opiateoverdose' using the file 'LocalMods/2776270649/Xml/Afflictions.xml'
[11/19/2022 17:33:03] Overriding an affliction or a buff with the identifier 'opiateaddiction' using the file 'LocalMods/2776270649/Xml/Afflictions.xml'
[11/19/2022 17:33:03] Overriding an affliction or a buff with the identifier 'burn' using the file 'LocalMods/2776270649/Xml/Afflictions.xml'
[11/19/2022 17:33:03] Overriding an affliction or a buff with the identifier 'explosiondamage' using the file 'LocalMods/2776270649/Xml/Afflictions.xml'
[11/19/2022 17:33:03] Overriding an affliction or a buff with the identifier 'organdamage' using the file 'LocalMods/2776270649/Xml/Afflictions.xml'
[11/19/2022 17:33:03] Overriding an affliction or a buff with the identifier 'gunshotwound' using the file 'LocalMods/2776270649/Xml/Afflictions.xml'
[11/19/2022 17:33:03] Overriding an affliction or a buff with the identifier 'bitewounds' using the file 'LocalMods/2776270649/Xml/Afflictions.xml'
[11/19/2022 17:33:03] Overriding an affliction or a buff with the identifier 'lacerations' using the file 'LocalMods/2776270649/Xml/Afflictions.xml'
[11/19/2022 17:33:03] Overriding an affliction or a buff with the identifier 'blunttrauma' using the file 'LocalMods/2776270649/Xml/Afflictions.xml'
[11/19/2022 17:33:03] Overriding an affliction or a buff with the identifier 'internaldamage' using the file 'LocalMods/2776270649/Xml/Afflictions.xml'
[11/19/2022 17:33:03] Overriding an affliction or a buff with the identifier 'bleedingnonstop' using the file 'LocalMods/2776270649/Xml/Afflictions.xml'
[11/19/2022 17:33:03] Overriding an affliction or a buff with the identifier 'bleeding' using the file 'LocalMods/2776270649/Xml/Afflictions.xml'
[11/19/2022 17:33:03] Overriding an affliction or a buff with the identifier 'sufforinpoisoning' using the file 'LocalMods/2776270649/Xml/Afflictions.xml'
[11/19/2022 17:33:03] Overriding an affliction or a buff with the identifier 'cyanidepoisoning' using the file 'LocalMods/2776270649/Xml/Afflictions.xml'
[11/19/2022 17:33:03] Overriding an affliction or a buff with the identifier 'morbusinepoisoning' using the file 'LocalMods/2776270649/Xml/Afflictions.xml'
[11/19/2022 17:33:03] Overriding an affliction or a buff with the identifier 'bloodloss' using the file 'LocalMods/2776270649/Xml/Afflictions.xml'
[11/19/2022 17:33:03] Overriding an affliction or a buff with the identifier 'oxygenlow' using the file 'LocalMods/2776270649/Xml/Afflictions.xml'
[11/19/2022 17:32:26] Error when reading attribute "steamworkshopid" from <contentpackage name="The Atron" modversion="1.0.20" corepackage="False" steamworkshopid="" gameversion="0.19.11.0" expectedhash="012C7434DA352D6423F15FB62C13489F">
  <Submarine file="%ModDir%/The Atron.sub" />
</contentpackage>! {Input string was not in a correct format.}
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.UInt64.Parse(String s, NumberStyles style, IFormatProvider provider)
   at Barotrauma.XMLExtensions.GetAttributeUInt64(XElement element, String name, UInt64 defaultValue)
[11/19/2022 17:32:25] Attempting to open ALC device "OpenAL Soft on Realtek HD Audio 2nd output (Realtek(R) Audio)"
[11/19/2022 17:32:23] Logged in as (here been my steam ID)

**Comment by Regalis11** [comment]
This crash report doesn't seem to be from the vanilla game but https://github.com/evilfactory/LuaCsForBarotrauma, I recommend creating an issue report in that repository instead
