### ISSUE TITLE
[Factions] Exception: Value cannot be null. (Parameter 'texture') (System.ArgumentNullException)

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10461]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Upon clicking the "host server" button and starting a Peer-to-Peer server for testing purposes, the game crashed and provided the error message below. Starting the game again did not result in a crash so I'm not sure what caused it.

### Bug prevalence

Just once

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 11/19/2022 16:05:08)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

539E54246B95DEE38D18ED39F17D51A4

Game version 100.5.0.0 (UnstableWindows, branch feature/fullrelease-testing, revision 4b66e05042)
Graphics mode: 2560x1440 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla, Fury, LETOHSS, Rex Malleus-Caput, SS HOTEL V.2, STVR, The Honked Mother, Typhon3, RVTS-Class, Sirens Violin, Sailor 4, The Schism
Level seed: no level loaded
Loaded submarine: None
Selected screen: Barotrauma.NetLobbyScreen
SteamManager initialized
Client (Round hadn't been started)

System info:
    Operating system: Microsoft Windows NT 10.0.19045.0 64 bit
    GPU name: NVIDIA GeForce RTX 2070
    Display mode: {Width:2560 Height:1440 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Value cannot be null. (Parameter 'texture') (System.ArgumentNullException)
Target site: Void CheckValid(Microsoft.Xna.Framework.Graphics.Texture2D)
Stack trace: 
   at Microsoft.Xna.Framework.Graphics.SpriteBatch.CheckValid(Texture2D texture) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\SpriteBatch.cs:line 249
   at Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(Texture2D texture, Vector2 position, Nullable`1 sourceRectangle, Color color, Single rotation, Vector2 origin, Vector2 scale, SpriteEffects effects, Single layerDepth) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\SpriteBatch.cs:line 472
   at Barotrauma.GUI.DrawBackgroundSprite(SpriteBatch spriteBatch, Sprite backgroundSprite, Color color) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 700
   at Barotrauma.NetLobbyScreen.Draw(Double deltaTime, GraphicsDevice graphics, SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\NetLobbyScreen.cs:line 2745
   at Barotrauma.GameMain.Draw(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 964
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 669
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 508
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[11/19/2022 16:05:08] Sprite "Content/Map/LocationPortraits/WorkCampResearchFacility4.png" not found!
[11/19/2022 16:05:08] Lobby created!
[11/19/2022 16:04:20] Attempting to open ALC device "OpenAL Soft on Speakers (Focusrite Usb Audio)"
[11/19/2022 16:04:08] Logged in as Wheatley1001 (SteamID STEAM_1:0:52539082)
```

**Comment by Regalis11** [comment]
Missing WorkCampResearchFacility4.png sprite fixed in https://github.com/Regalis11/Barotrauma-development/commit/d516446dfd1a1c75d95dcff3e080f835593f5493, + added a check that prevent missing location portraits from causing a crash in https://github.com/Regalis11/Barotrauma-development/commit/f83e8ef171ab8a9a8002e608ffc8cbcd493ef2d4

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
