### ISSUE TITLE
[unstable] launch the railgun makes crash

### ISSUE THREAD

**Issue by Cyana-ir** [Regalis11/Barotrauma#10547]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![Y_BFU2OM735Z7T}1LQNT%8A](https://user-images.githubusercontent.com/106088471/204043742-535849a3-a7b4-4d15-ac72-81e34e8bf098.png)
when trying to launch the railgun in sub editor\ MP server in ships ( Kastrull\Humpback\Typhon2) ,the game crashes.
[crashreport (12).log](https://github.com/Regalis11/Barotrauma/files/10094789/crashreport.12.log)
[crashreport (11).log](https://github.com/Regalis11/Barotrauma/files/10094791/crashreport.11.log)
[crashreport (13).log](https://github.com/Regalis11/Barotrauma/files/10094792/crashreport.13.log)

### Reproduction steps

1、start testing/playing the sub with railgun
2、waiting for supercapacitor charged
3、click the LMB
4、 game crashed

### Bug prevalence

Happens every now and then

### Version

0.20.8.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 11/26/2022 03:16:41)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

F908D4F0DB4650D0F8DE7CE57EB2BD32

Game version 0.20.8.0 (UnstableWindows, branch dev, revision 1d40fd4ca0)
Graphics mode: 1680x1050 (Windowed)
VSync OFF
Language: English
Selected content packages: Vanilla, Beacons Extended
Level seed: no level loaded
Loaded submarine: Kastrull (526731C1FB64885E7A49FA5291931C3A)
Selected screen: Barotrauma.GameScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19045.0 64 bit
    GPU name: NVIDIA GeForce GTX 1650
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Boolean TryLaunch(Single, Barotrauma.Character, Boolean)
Stack trace: 
   at Barotrauma.Items.Components.Turret.TryLaunch(Single deltaTime, Character character, Boolean ignorePower) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Turret.cs:line 647
   at Barotrauma.Items.Components.Turret.ReceiveSignal(Signal signal, Connection connection) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Turret.cs:line 1676
   at Barotrauma.Items.Components.Connection.SendSignal(Signal signal) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Signal\Connection.cs:line 304
   at Barotrauma.Item.SendSignal(Signal signal, Connection connection) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 2472
   at Barotrauma.Item.SendSignal(Signal signal, String connectionName) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 2414
   at Barotrauma.Items.Components.Controller.Use(Single deltaTime, Character activator) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Machines\Controller.cs:line 304
   at Barotrauma.Item.Use(Single deltaTime, Character character, Limb targetLimb) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 2700
   at Barotrauma.Character.Control(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 2185
   at Barotrauma.Character.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 3187
   at Barotrauma.AICharacter.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AICharacter.cs:line 72
   at Barotrauma.Character.UpdateAll(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 2969
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 192
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 863
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[11/26/2022 03:15:21] Created SMG Round (2203)
[11/26/2022 03:15:21] Created SMG Round (2202)
[11/26/2022 03:15:21] Created SMG Round (2201)
[11/26/2022 03:15:21] Created nucleargunbolt (2200)
[11/26/2022 03:15:21] Created nucleargunbolt (2199)
[11/26/2022 03:15:21] Created nucleargunbolt (2198)
[11/26/2022 03:15:21] Created nucleargunbolt (2197)
[11/26/2022 03:15:21] Created nucleargunbolt (2196)
[11/26/2022 03:15:21] Created nucleargunbolt (2195)
[11/26/2022 03:15:21] Created nucleargunbolt (2194)
[11/26/2022 03:15:20] Created Riot Helmet (2193)
[11/26/2022 03:15:20] Created Gunner's Helmet (2192)
[11/26/2022 03:15:20] Created Shotgun Shell (2191)
[11/26/2022 03:15:20] Created Shotgun Shell (2190)
[11/26/2022 03:15:20] Created Shotgun Shell (2189)
[11/26/2022 03:15:20] Created Shotgun Shell (2188)
(things below are same like this, I turned up additional log information)
```

**Comment by Wheatley1001** [comment]
same thing happened on 100.6.0.0: 

Barotrauma Dedicated Server crash report (generated on 11/25/2022 20:01:30)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


Game version 100.6.0.0 (UnstableWindows, branch feature/fullrelease-testing, revision 0dea95c273)
Language: English
Selected content packages: Vanilla, Fury, LETOHSS, Rex Malleus-Caput, SS HOTEL V.2, STVR, The Honked Mother, Typhon3, RVTS-Class, Sirens Violin, Sailor 4, The Schism
Level seed: Libya LineaBaal's Vent
Loaded submarine: Typhon2 (04212A4F1CEEF07D32190C43AD2F4A77)
Selected screen: Barotrauma.GameScreen
Server (Round had started)


System info:
    Operating system: Microsoft Windows NT 10.0.19045.0 64 bit


Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Boolean TryLaunch(Single, Barotrauma.Character, Boolean)
Stack trace: 
   at Barotrauma.Items.Components.Turret.TryLaunch(Single deltaTime, Character character, Boolean ignorePower) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Turret.cs:line 685
   at Barotrauma.Items.Components.Turret.UpdateAutoOperate(Single deltaTime, Identifier friendlyTag) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Turret.cs:line 1117
   at Barotrauma.SubmarineTurretAI.OperateTurrets(Single deltaTime, Identifier friendlyTag) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\Wreck\WreckAI.cs:line 74
   at Barotrauma.WreckAI.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\Wreck\WreckAI.cs:line 283
   at Barotrauma.Submarine.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Submarine.cs:line 1046
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 280
   at Barotrauma.GameMain.Run() in <DEV>\Barotrauma\BarotraumaServer\ServerSource\GameMain.cs:line 325
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Program.cs:line 78


Last debug messages:
   11/25/2022 20:01:30 - [11/25/2022 20:01:30]
  Saving banlist
   11/25/2022 20:01:29 - [11/25/2022 20:01:29]
  Udrakan closed Custom Hatch
   11/25/2022 20:01:27 - [11/25/2022 20:01:27]
  Udrakan dropped Shipwreck ID Card
   11/25/2022 20:01:24 - [11/25/2022 20:01:24]
  Rehex placed Plastiseal in Doctor's Uniform (ID: 10484)
   11/25/2022 20:01:24 - [11/25/2022 20:01:24]
  Rehex placed Plastiseal in Doctor's Uniform (ID: 10484)
   11/25/2022 20:01:24 - [11/25/2022 20:01:24]
  Rehex placed Plastiseal in Doctor's Uniform (ID: 10484)
   11/25/2022 20:01:24 - [11/25/2022 20:01:24]
  Udrakan dropped Rifle Bullet
   11/25/2022 20:01:24 - [11/25/2022 20:01:24]
  Udrakan dropped Rifle Bullet
   11/25/2022 20:01:24 - [11/25/2022 20:01:24]
  Hawkins picked up Oxygen Tank
   11/25/2022 20:01:21 - [11/25/2022 20:01:21]
  Udrakan opened Custom Hatch
   11/25/2022 20:01:20 - [11/25/2022 20:01:20]
  Udrakan placed Safety Harness in Large Steel Cabinet (ID: 1919)
   11/25/2022 20:01:18 - [11/25/2022 20:01:18]
  Rehex dropped Toolbelt
   11/25/2022 20:01:18 - [11/25/2022 20:01:18]
  Hawkins picked up Welding Fuel Tank
   11/25/2022 20:01:17 - [11/25/2022 20:01:17]
  bananaman placed Metal Crate in Crate Shelf (ID: 2567)

**Comment by Cyana-ir** [comment]
my first language is not English. I misread the "Bug prevalence-Happens every now and then",it should be everytime

**Comment by TheMinerBoy** [comment]
This happened to me as well during a campaign battle with a hammerhead. A bot tried to fire a railgun and the game crashed.
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/10095356/crashreport.log)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/da69f360fe051e2bfe5113216eb9580ac5e3a36c

**Comment by carloschenCH** [comment]
the same bug occurs at my game, when I shooting a railgun, the game crashed, both at local game and sever game.
this is my log.

Barotrauma Client crash report (generated on 11/29/2022 11:22:09)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

F908D4F0DB4650D0F8DE7CE57EB2BD32

Game version 0.20.8.0 (UnstableWindows, branch dev, revision 1d40fd4ca0)
Graphics mode: 1920x1080 (Windowed)
VSync ON
Language: Simplified Chinese
Selected content packages: Vanilla, 方位角改进型, Remora改, 小雀, Magic Reactor Controllers, [BOS]Ero-锤击点-海盗型, wurenji, 作业支援无人机II, 冰刺, 冰刺物资丰富版, 冰刺物资丰富版v1, 泽兰船坞无人机合集, 自动反应堆, 末世方舟, 定层升降梯, 测试场景, 冰刺, 攻击无人机对接舱, 攻击无人机控制, 核爆无人机对接舱, 核爆无人机控制, [ZS]LumenDrone电容改, 不响丸辣
Level seed: St. Musk
Loaded submarine: 冰刺 (8894523464B9609CC55B8AE3DCC10A2E)
Selected screen: Barotrauma.GameScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19043.0 64 bit
    GPU name: NVIDIA GeForce GTX 1650
    Display mode: {Width:2560 Height:1440 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Boolean TryLaunch(Single, Barotrauma.Character, Boolean)
Stack trace: 
   at Barotrauma.Items.Components.Turret.TryLaunch(Single deltaTime, Character character, Boolean ignorePower) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Turret.cs:line 647
   at Barotrauma.Items.Components.Turret.ReceiveSignal(Signal signal, Connection connection) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Turret.cs:line 1676
   at Barotrauma.Items.Components.Connection.SendSignal(Signal signal) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Signal\Connection.cs:line 304
   at Barotrauma.Item.SendSignal(Signal signal, Connection connection) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 2472
   at Barotrauma.Item.SendSignal(Signal signal, String connectionName) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 2414
   at Barotrauma.Items.Components.Controller.Use(Single deltaTime, Character activator) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Machines\Controller.cs:line 304
   at Barotrauma.Item.Use(Single deltaTime, Character character, Limb targetLimb) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 2700
   at Barotrauma.Character.Control(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 2185
   at Barotrauma.Character.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 3187
   at Barotrauma.AICharacter.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AICharacter.cs:line 72
   at Barotrauma.Character.UpdateAll(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 2969
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 192
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 863
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[11/29/2022 11:20:58] Generating an outpost for the start of the level... (Location: St. Musk设施, level type: Outpost)
[11/29/2022 11:20:58] Level identifier: outpostlevel
[11/29/2022 11:20:57] Creating hulls between docking ports failed. Could not find a hull next to the docking port.
[11/29/2022 11:19:54] Attempting to open ALC device "OpenAL Soft on 扬声器 (Realtek High Definition Audio)"
[11/29/2022 11:19:53] Logged in as 星空幻梦 (SteamID STEAM_1:1:428306604)

**Comment by mdaugbjerg** [comment]
I think I have the same issue. Fresh MP game in a Humpback with some bots, and as soon as the bot tries to fire the bottom Railgun, the game crashes.

**Comment by TheMinerBoy** [comment]
It'll be fixed whenever the next build releases.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing
