### ISSUE TITLE
Depth charges causing a crash

### ISSUE THREAD

**Issue by WeebCactus** [Regalis11/Barotrauma#10586]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Using the Herja submarine during a campaign, we launched a depth charge which caused a crash, I tested this in the submarine editor with other subs and they all crash too.

### Reproduction steps

Enter the submarine editor and pick a submarine with the ability to launch a depth charge
Launch the depth charge

### Bug prevalence

Happens regularly

### Version

0.20.8.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 11/27/2022 01:45:38)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

F908D4F0DB4650D0F8DE7CE57EB2BD32

Game version 0.20.8.0 (UnstableWindows, branch dev, revision 1d40fd4ca0)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla, Everit-MS, Everit-MS Main Sub test, Drumboy Drone, Fu7n, ER
Level seed: no level loaded
Loaded submarine: Typhon (386CCD43B3CCD4BE202BBC842A76D0D6)
Selected screen: Barotrauma.GameScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit
    GPU name: AMD Radeon RX 6600
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Boolean TryLaunch(Single, Barotrauma.Character, Boolean)
Stack trace: 
   at Barotrauma.Items.Components.Turret.TryLaunch(Single deltaTime, Character character, Boolean ignorePower) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Turret.cs:line 647
   at Barotrauma.Items.Components.Turret.Use(Single deltaTime, Character character) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Turret.cs:line 579
   at Barotrauma.Item.Use(Single deltaTime, Character character, Limb targetLimb) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 2700
   at Barotrauma.Items.Components.Turret.ReceiveSignal(Signal signal, Connection connection) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Turret.cs:line 1667
   at Barotrauma.Items.Components.Connection.SendSignal(Signal signal) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Signal\Connection.cs:line 304
   at Barotrauma.Item.SendSignal(Signal signal, Connection connection) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 2472
   at Barotrauma.Items.Components.CustomInterface.ButtonClicked(CustomInterfaceElement btnElement) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Signal\CustomInterface.cs:line 325
   at Barotrauma.Items.Components.CustomInterface.<CreateGUI>b__6_6(GUIButton _, Object userdata) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Components\Signal\CustomInterface.cs:line 187
   at Barotrauma.GUIButton.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIButton.cs:line 263
   at Barotrauma.GUI.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1259
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 888
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[11/27/2022 01:45:08] spawnitem Screwdriver inventory
[11/27/2022 01:42:32] Attempting to open ALC device "OpenAL Soft on Speakers (2- Realtek(R) Audio)"
[11/27/2022 01:42:31] Logged in as WeebCactus (SteamID STEAM_1:0:150699230)
```

**Comment by Regalis11** [comment]
Seems to be caused be the same issue as https://github.com/Regalis11/Barotrauma/issues/10547, closing as a duplicate
