### ISSUE TITLE
Memory leaks while playing the splash screen.

### ISSUE THREAD

**Issue by itchyOwl** [Regalis11/Barotrauma#1060]
There seems to be a nasty bug in the Microsoft.Xna.Framework.Media.VideoPlayer class (https://github.com/MonoGame/MonoGame/issues/5308), which prevents freeing the memory on disposing.

In Barotrauma, it seems that if the vsync is off, playing the splash screens will (at least on some Windows operated systems) eat up all the vram and then a major part of the system ram. If playing the video is stopped, memory is no more drained. But due to the abovementioned memory bug the lost resources are never retrieved until quitting the application.

Playing the splash screen may cause the game to crash or it can result into receiving an error like this:

`Playing splash screen video failed {HRESULT: [0x8007000E], Module: [General], ApiCode: [E_OUTOFMEMORY/Out of memory], Message: Not enough memory resources are available to complete this operation.}
  at SharpDX.Result.CheckError()
  at SharpDX.Direct3D11.Device.CreateTexture2D(Texture2DDescription& descRef, DataBox[] initialDataRef, Texture2D texture2DOut)
  at Microsoft.Xna.Framework.Graphics.Texture2D.CreateTexture()
  at Microsoft.Xna.Framework.Graphics.Texture2D.PlatformSetData[T](Int32 level, Int32 arraySlice, Rectangle rect, T[] data, Int32 startIndex, Int32 elementCount)
  at Microsoft.Xna.Framework.Graphics.Texture2D.SetData[T](T[] data)
  at Microsoft.Xna.Framework.Media.VideoPlayer.PlatformGetTexture()
  at Microsoft.Xna.Framework.Media.VideoPlayer.GetTexture()
  at Barotrauma.LoadingScreen.DrawSplashScreen(SpriteBatch spriteBatch)
  at Barotrauma.LoadingScreen.Draw(SpriteBatch spriteBatch, GraphicsDevice graphics, Single deltaTime)`

There's another implementation of the VideoPlayer, which we could test: https://github.com/SickheadGames/MonoGame/blob/stable_BtA/MonoGame.Framework/Media/VideoPlayer.WMS.cs

**Comment by Regalis11** [comment]
I believe this has been fixed in MonoGame 3.7: https://github.com/MonoGame/MonoGame/pull/5737

**Comment by Regalis11** [comment]
Fixed in d7a46d7
