### ISSUE TITLE
Opening fabricator crafting UI in sub editor crashes the game

### ISSUE THREAD

**Issue by Lepestochek** [Regalis11/Barotrauma#10618]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Trying to open crafting ui of both medical and engineering fabricators while in sub editor crashes the game. Does not affect anything else. Not sub dependent although crashes without a log if only the fabricator is present in the workspace.

### Reproduction steps

1. Open the sub editor
2. Place a fabricator
3. Try to open crafting UI using default interaction key, "e"
4. Instantly crashes

### Bug prevalence

Happens every time I play

### Version

0.20.8.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 11/29/2022 14:42:48)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

F908D4F0DB4650D0F8DE7CE57EB2BD32

Game version 0.20.8.0 (UnstableWindows, branch dev, revision 1d40fd4ca0)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync OFF
Language: Russian
Selected content packages: Vanilla, Саратов, Дверь с блокировкой, Клапан для воды (рабочий), Подольск, Подольск 2.0, Поломка, Реактор (декор), Омск, АВИАНОСЕЦ, Умный клапан, Умный сдвоенный клапан, Коробка для шатла авианосца, РБЗ-1, РБ-2, РБ-3, Бомбардир, Смена камеры по циклу (не работает), Цикл из трёх со смешными выходами, Взаимоисключающее из трёх (не работает), дозаправщик, Расстояние Distance, Древний, Большой клапан(умный)
Level seed: no level loaded
Loaded submarine: Саратов (597C5B033C55C1ABA0D3DF03DF79461A)
Selected screen: Barotrauma.SubEditorScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 6.1.7601 Service Pack 1 64 bit
    GPU name: NVIDIA GeForce GTX 1050 Ti
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: System.Collections.Immutable.ImmutableHashSet`1[Barotrauma.Character] GetSessionCrewCharacters(Barotrauma.CharacterType)
Stack trace: 
   at Barotrauma.GameSession.GetSessionCrewCharacters(CharacterType type) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameSession.cs:line 767
   at Barotrauma.Items.Components.Fabricator.CanBeFabricated(FabricationRecipe fabricableItem, IReadOnlyDictionary`2 availableIngredients, Character character) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Machines\Fabricator.cs:line 613
   at Barotrauma.Items.Components.Fabricator.UpdateHUD(Character character, Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Components\Machines\Fabricator.cs:line 854
   at Barotrauma.Item.UpdateHUD(Camera cam, Character character, Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Item.cs:line 1153
   at Barotrauma.SubEditorScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\SubEditorScreen.cs:line 5713
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 863
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[11/29/2022 14:41:40] Attempting to open ALC device "OpenAL Soft on Уж точно не динамики (Realtek High Definition Audio)"
[11/29/2022 14:41:39] Logged in as Лепесточек (SteamID STEAM_1:1:178318502)
```

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
