### ISSUE TITLE
Barotrauma crashed when i create new character in character editor

### ISSUE THREAD

**Issue by RozyCosmic** [Regalis11/Barotrauma#10620]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I want to make MG Ray from MGS. I go to character editor, click on "create new character", select spritesheet in /barotrauma/localmods/mg_ray/mg_ray_bara.png, create new packege, click on "create" and... game crashes! How?

Details in crashreport
[crashreport (8).log](https://github.com/Regalis11/Barotrauma/files/10111249/crashreport.8.log)
![mg_ray_bara](https://user-images.githubusercontent.com/105544621/204481537-1ea9becb-afa1-4a24-ae98-3ee39859716b.png)

### Reproduction steps

1. create new character
2. select "it can walk" and "can enter submarine"
3. select this spritesheet in /barotrauma/localmods/MG_RAY/mg_ray_bara.png
4. create new packege
5. click on "create character"
6. and gave will crash

### Bug prevalence

Happens every time I play

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Jasontti** [comment]
Tested with current stable 1.0.21.0 and dev build of 1.1.13.0
When replicating this i could not get it to load spritesheet from %ModDir%/Business-person/ as it forces different path than what was selected with "select texture" button.
When hitting "next" it gives "texture file does not exist" warning
![image](https://github.com/Regalis11/Barotrauma/assets/8488224/eee92bc2-6df4-42bd-b4cf-c2cb86a91c89)

When using the default path of  %ModDir%Characters/ it causes a crash (Kind of excepted too):
```
Trying to spawn human
Unhandled exception. Barotrauma.MissingContentPackageException: "Business-person" depends on a package with name or ID "Characters" that is not currently installed.
   at Barotrauma.ContentPath.get_Value() in /dev/Barotrauma-development/Barotrauma/BarotraumaShared/SharedSource/ContentManagement/ContentPath.cs:line 58
   at Barotrauma.CharacterEditor.Wizard.CharacterView.<>c__DisplayClass3_0.<Create>b__17(GUIButton b, Object d) in /dev/Barotrauma-development/Barotrauma/BarotraumaClient/ClientSource/Screens/CharacterEditor/Wizard.cs:line 412
   at Barotrauma.GUIButton.Update(Single deltaTime) in /dev/Barotrauma-development/Barotrauma/BarotraumaClient/ClientSource/GUI/GUIButton.cs:line 263
   at Barotrauma.GUIComponent.UpdateAuto(Single deltaTime) in /dev/Barotrauma-development/Barotrauma/BarotraumaClient/ClientSource/GUI/GUIComponent.cs:line 455
   at Barotrauma.GUI.Update(Single deltaTime) in /dev/Barotrauma-development/Barotrauma/BarotraumaClient/ClientSource/GUI/GUI.cs:line 1244
   at Barotrauma.GameMain.Update(GameTime gameTime) in /dev/Barotrauma-development/Barotrauma/BarotraumaClient/ClientSource/GameMain.cs:line 876
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in /dev/Barotrauma-development/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 651
   at Microsoft.Xna.Framework.Game.Tick() in /dev/Barotrauma-development/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in /dev/Barotrauma-development/Libraries/MonoGame.Framework/Src/MonoGame.Framework/SDL/SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in /dev/Barotrauma-development/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in /dev/Barotrauma-development/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in /dev/Barotrauma-development/Barotrauma/BarotraumaClient/ClientSource/Program.cs:line 58
```

After couple tries it correctly fills in the path and issue could not be replicated.

![image](https://github.com/Regalis11/Barotrauma/assets/8488224/c5418486-34ad-46f1-84cb-10d77db533b6)
