### ISSUE TITLE
Double crash report when trying to load multiplayer campaign

### ISSUE THREAD

**Issue by Jade-Harleyy** [Regalis11/Barotrauma#10638]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

After attempting to load a multiplayer campaign save, Barotrauma crashed and generated 2 crash reports.

### Reproduction steps

1. Unzip save files into multiplayer save folder.
2. Open multiplayer lobby.
3. Switch to Campaign mode.
4. Load the campaign.
5. After about 2-3 minutes of loading, the game will crash.

**[Save files](https://github.com/Regalis11/Barotrauma/files/10137244/VON_TAHM_MK_2.zip)**

### Bug prevalence

Happens every now and then

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
CRASH REPORT 1:

Barotrauma Client crash report (generated on 12/01/2022 18:38:34)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


7CB1A1D8EDB459DBB8FE6B7A40525156


Game version 0.19.14.0 (ReleaseWindows, branch master, revision c624ec6568)
Graphics mode: 2560x1440 (BorderlessWindowed)
VSync OFF
Language: English
Selected content packages: Vanilla
Level seed: ShinkonaiAlphesiboea Linea
Loaded submarine: The Tyrant (694CB4218F6D01AB38DD461C7E343107)
Selected screen: Barotrauma.NetLobbyScreen
SteamManager initialized
Client (Round hadn't been started)


System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit
    GPU name: NVIDIA GeForce GTX 1080
    Display mode: {Width:2560 Height:1440 Format:Color AspectRatio:1.7777778}
    GPU status: Normal


Exception: readStream was disconnected unexpectedly (System.Exception)
Target site: Void UpdateRead()
Stack trace: 
   at Barotrauma.Networking.ChildServerRelay.UpdateRead()
   at System.Threading.Thread.StartCallback()


Last debug messages:
[12/01/2022 18:37:18] Generating an outpost for the end of the level... (Location: Alphesiboea Linea Outpost, level type: LocationConnection)
[12/01/2022 18:37:17] Generating an outpost for the start of the level... (Location: Shinkonai Outpost, level type: LocationConnection)
[12/01/2022 18:37:14] Level identifier: plateaubasic
[12/01/2022 18:36:58] Server running slowly (55 updates/s)!
[12/01/2022 18:36:49] Lobby created!
[12/01/2022 18:35:58] Attempting to open ALC device "OpenAL Soft on Speakers (Realtek(R) Audio)"
[12/01/2022 18:35:56] Logged in as Jade Harley (SteamID STEAM_1:0:476582823)


====================================================================================================


CRASH REPORT 2:

Barotrauma Client crash report (generated on 12/01/2022 18:38:34)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


7CB1A1D8EDB459DBB8FE6B7A40525156


Game version 0.19.14.0 (ReleaseWindows, branch master, revision c624ec6568)
Graphics mode: 2560x1440 (BorderlessWindowed)
VSync OFF
Language: English
Selected content packages: Vanilla
Level seed: ShinkonaiAlphesiboea Linea
Loaded submarine: The Tyrant (694CB4218F6D01AB38DD461C7E343107)
Selected screen: Barotrauma.NetLobbyScreen
SteamManager initialized
Client (Round hadn't been started)


System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit
    GPU name: NVIDIA GeForce GTX 1080
    Display mode: {Width:2560 Height:1440 Format:Color AspectRatio:1.7777778}
    GPU status: Normal


Exception: Pipe is broken. (System.IO.IOException)
Target site: Void WriteCore(System.ReadOnlySpan`1[System.Byte])
Stack trace: 
   at System.IO.Pipes.PipeStream.WriteCore(ReadOnlySpan`1 buffer)
   at Barotrauma.Networking.ChildServerRelay.<UpdateWrite>g__writeMsg|41_0(WriteStatus writeStatus, <>c__DisplayClass41_0& )
   at Barotrauma.Networking.ChildServerRelay.UpdateWrite()
   at System.Threading.Thread.StartCallback()


Last debug messages:
[12/01/2022 18:37:18] Generating an outpost for the end of the level... (Location: Alphesiboea Linea Outpost, level type: LocationConnection)
[12/01/2022 18:37:17] Generating an outpost for the start of the level... (Location: Shinkonai Outpost, level type: LocationConnection)
[12/01/2022 18:37:14] Level identifier: plateaubasic
[12/01/2022 18:36:58] Server running slowly (55 updates/s)!
[12/01/2022 18:36:49] Lobby created!
[12/01/2022 18:35:58] Attempting to open ALC device "OpenAL Soft on Speakers (Realtek(R) Audio)"
[12/01/2022 18:35:56] Logged in as Jade Harley (SteamID STEAM_1:0:476582823)
```

**Comment by Jade-Harleyy** [comment]
UPDATE: I was able to fix the save by editing the save file's gamesession.xml using https://ignis05.github.io/baro-save-editor/ and removing all pending sub upgrades.

**Comment by Regalis11** [comment]
It seems there were essentially two issues in play here: 

- Applying upgrades to one of the drop pods crashed the server, fixed in https://github.com/Regalis11/Barotrauma-development/commit/956c4025fda79e29f3f12ec29c42cfa2767dcef0
- The server didn't properly communicate the crash to the client, preventing the client from shutting down the server connection gracefully (https://github.com/Regalis11/Barotrauma/issues/10194)

**Comment by NilanthAnimosus** [comment]
Tested against bugfixes commit https://github.com/Regalis11/Barotrauma-development/commit/14457d7dc22a5b12de8d84d2e57268378e1454d8, no issues found, closing.
