### ISSUE TITLE
Crash on round start | You are removing a body that is not in the simulation

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#10669]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Seems related to #10010 but the stack trace is different.

My friends' game crashed on starting a round with an alien ruins mission without a name.

### Reproduction steps

Possible: start a mission without a name
Otherwise: start an alien ruins mission

### Bug prevalence

Just once

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 12/04/2022 21:17:21)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


7CB1A1D8EDB459DBB8FE6B7A40525156


Game version 0.19.14.0 (ReleaseWindows, branch master, revision c624ec6568)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla, BaroTraumatic Nightmare, Improved Husks, Barotraumatic Creature Pack, Lua For Barotrauma, CsForBarotrauma, AVP-Aliens, Neurotrauma, Neurotrauma Cybernetics, NT Pharmacy, Enhanced Armaments, Enhanced Armaments Neurotrauma Patch, Visual Variety Pack, ADV Beacon Stations, Beacons Extended, EK | Dockyard, EK | Gunnery, Alarms Extended, Custom Fins and Decals (New custom letters added), Submarine Weapon Sound Makeover, Stations from beyond, Movable and Sellable Wrecks, New Wrecks For Barotrauma (With sellable wrecks), Spoon's Pirate Vessels Expanded, Avali Posters, MoreMissionsMod, Dont Open Debug Console On Errors, BaroCraftables, Acolyte Job, BetterHealthUI, BetterFabricatorUI, Lucifer, No Role Balance v2, ID cap Van, Auto Door Ginevra, Engineering_Room, 2x2 Coilgun, 3 Door Airlocks with pump, 4 door Airlocks with pump, Acelelator Coilgun, Advanced Airlock, Advanced Airlock Compact, Advanced Airlock double hatch, Anglerfish, Antena, Armory Clothes, Armory Locker, Armory Small D, Armory Small No Clothes, Auto Hatch Ginevra, Balast Flora Flamer With Light, Balast Flora Repelent, Ball 1 Drone, Ball 1 Drone, Ball 2 Shuttle, Ball 2 Shuttle, ball, Big Gun Case, Blast Auto Door, Bonfire, Burst Coilgun, cannon, cargo, Charge %, Coil Cannon, Coil Lights, Coilgun Assembly, Coilgun Pasive, Complete Diving Locker, Corner sub, cozy shuttle, Crow Prototype, Crystal Lamp, Darakan Twin Coilgun, Deco Bot 1, Deco bot 2 Long, Deco Top 1, Deco top 2 long, Deco Top 2, Display, Diving Suit (Vanilla Red), Diving Suit + Gear, Diving Suit, double wire coilgun set, Dragonewt Mk.3 Variant X, Dragonewt Mk.4, Dragonfly XS, Drone Ball 1, drone kastrul assembly, Duct 1, duct 2, duct 3, duct block 3, EK_Marauder_Mk-III, Engine FE-1x T, Engine RQ-R01, Falcon F01, Falcon, filelist, Fin D 3, Fin Deco Bottom, Fin Deco, fire ext full, front, Gun Cabinet (Revolver), Gun Holder, Gun Locker Big, Gun locker, gun lockers, harpoon locker 2, Horizontal AIrlock with Extra Ballast and Docking Left, Horizontal Airlock with Extra Ballast and Docking Right, Horizontal AIrlock With Extra Ballast Left, Horizontal AIrlock with Extra Ballast RIght, Horizontal Airlock With Pump Left, Horizontal Airlock with Pump Right, hydroponics, IMC Rake Deco 1, Interogator, Investor, Ironclad Mk IV Variant D4, Ironclad Mk IV, Irondrake Mk 2 Ver X, Irondrake Mk 3, Irondrake MK I, Jackal Mk2 X, Jackal X, jackal x, Kantan Triplet Coilgun, Kastrul Drone, lamp old, Large Diving Suit Set EK, Light Exterior gun, Light ramp, LittleRattler_Mk2, Medic Room Small, Medical room, Medical Supply, Multi Purpose Cabinet D, Multipurpose Supply, Oxygen Supply 2, Oxygen Supply, Pile Driver, Power Bank SC, Procrastinator, Pump Mar, pump marauder, RA-14, Rail Cannon, Railgun Assembly, Ratler, ReactorAssembly, Repair Supply, Seapnir, Sec Blast Door Auto, Sec Blast Hatch, Sec Coridor 1, Sec Room 1, Secure Cabinet Deco, Security Supplies, Security Supply 2, Shuttle shell top, SM15 Dual Loader, Small Window, Storage, Sub Repair Cabinet, Submarine Control, Supply Cabinet Collection, Supply of Light Sources, switch, T4 Madus, test 1, Tone, Tool Rack, Top Decoration 2, Top Decoration, Torrent, Unnamed, vent hatch, Vertical Airlock with Extra Ballast and Docking Down, Vertical Airlock with Extra Ballast and DOcking Up, Vertical Airlock with Extra Ballast Down, Vertical Airlock with Extra Ballast Up, Vertical Airlock With Pump Down, Vertical Airlock With Pump Up, Welding Supply (Vanilla), Dragonfly XS, Hawk H-01, Hawk-01
Level seed: no level loaded
Loaded submarine: None
Selected screen: Barotrauma.RoundSummaryScreen
SteamManager initialized


System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit
    GPU name: NVIDIA GeForce GTX 970
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal


Exception: You are removing a body that is not in the simulation (userdata: Ruin Wall Horizontal). (Parameter 'body') (System.ArgumentException)
Target site: Void Remove(FarseerPhysics.Dynamics.Body)
Stack trace: 
   at FarseerPhysics.Dynamics.World.Remove(Body body) in C:\Users\joona\Documents\Barotrauma-development\Libraries\Farseer Physics Engine 3.5\Dynamics\World.cs:line 1004
   at FarseerPhysics.Dynamics.World.Clear() in C:\Users\joona\Documents\Barotrauma-development\Libraries\Farseer Physics Engine 3.5\Dynamics\World.cs:line 1719
   at Barotrauma.Submarine.Unload()
   at Barotrauma.Networking.GameClient.ReturnToPreviousMenu(GUIButton button, Object obj)
   at Barotrauma.Networking.GameClient.OnClientPeerDisconnect(PeerDisconnectPacket disconnectPacket)
   at Barotrauma.Networking.SteamP2POwnerPeer.Close(PeerDisconnectPacket peerDisconnectPacket)
   at Barotrauma.Networking.GameClient.Quit()
   at Barotrauma.Networking.GameClient.Update(Single deltaTime)
   at Barotrauma.GameMain.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in C:\Users\joona\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in C:\Users\joona\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in C:\Users\joona\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in C:\Users\joona\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in C:\Users\joona\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args)


Last debug messages:
[12/04/2022 21:17:20]  - Ruin Light(ID 8883)

[12/04/2022 21:17:20]  - Ruin Light(ID 8877)

[12/04/2022 21:17:20]  - Ruin Light(ID 8872)

[12/04/2022 21:17:20]  - Ruin Light(ID 8866)

[12/04/2022 21:17:20]  - Ruin Light(ID 8859)

[12/04/2022 21:17:20]  - Ruin Light(ID 8853)

[12/04/2022 21:17:20]  - Ruin Light(ID 8848)

[12/04/2022 21:17:20]  - Ruin Light(ID 8847)

[12/04/2022 21:17:20]  - Ruin Light(ID 8846)

[12/04/2022 21:17:20]  - Ruin Light(ID 8845)

[12/04/2022 21:17:20]  - Ruin Light(ID 8844)

[12/04/2022 21:17:20]  - Ruin Light(ID 8843)

[12/04/2022 21:17:20]  - Ruin Light(ID 8842)

[12/04/2022 21:17:20]  - Ruin Light(ID 8841)

[12/04/2022 21:17:20]  - Ruin Light(ID 8840)

[12/04/2022 21:17:20]  - Ruin Light(ID 8839)

[12/04/2022 21:17:20]  - Ruin Light(ID 8838)

[12/04/2022 21:17:20]  - Ruin Light(ID 8837)

[12/04/2022 21:17:20]  - Ruin Light(ID 8836)

[12/04/2022 21:17:20]  - Ruin Light(ID 8835)

[12/04/2022 21:17:20]  - Ruin Light(ID 8834)

[12/04/2022 21:17:20]  - Ruin Light(ID 8833)

[12/04/2022 21:17:20]  - Ruin Light(ID 8832)

[12/04/2022 21:17:20] Some items were not removed in Entity.RemoveAll:

[12/04/2022 21:17:20]  - Ruin Light (ID: 8833)(ID 8833)

[12/04/2022 21:17:20]  - Ruin Light (ID: 8883)(ID 8883)

[12/04/2022 21:17:20]  - Ruin Back Wall Basic(ID 8880)

[12/04/2022 21:17:20]  - Barotrauma.Hull(ID 8881)

[12/04/2022 21:17:20]  - Ruin Wall Horizontal(ID 8882)

[12/04/2022 21:17:20]  - Ruin Wall Horizontal(ID 8879)

[12/04/2022 21:17:20]  - Barotrauma.WayPoint(ID 8878)

[12/04/2022 21:17:20]  - Ruin Light (ID: 8877)(ID 8877)

[12/04/2022 21:17:20]  - Ruin Wall Horizontal(ID 8876)

[12/04/2022 21:17:20]  - Barotrauma.Hull(ID 8875)

[12/04/2022 21:17:20]  - Ruin Back Wall Basic(ID 8874)

[12/04/2022 21:17:20]  - Ruin Wall Horizontal(ID 8873)

[12/04/2022 21:17:20]  - Ruin Light (ID: 8872)(ID 8872)

[12/04/2022 21:17:20]  - Ruin Wall Vertical(ID 8871)

[12/04/2022 21:17:20]  - Barotrauma.Hull(ID 8870)

[12/04/2022 21:17:20]  - Ruin Back Wall Basic(ID 8869)

[12/04/2022 21:17:20]  - Ruin Wall Vertical(ID 8868)

[12/04/2022 21:17:20]  - Barotrauma.WayPoint(ID 8867)

[12/04/2022 21:17:20]  - Ruin Light (ID: 8866)(ID 8866)

[12/04/2022 21:17:20]  - Ruin Wall Horizontal(ID 8865)

[12/04/2022 21:17:20]  - Barotrauma.Hull(ID 8864)

[12/04/2022 21:17:20]  - Ruin Back Wall Basic(ID 8863)

[12/04/2022 21:17:20]  - Ruin Wall Horizontal(ID 8862)

[12/04/2022 21:17:20]  - Barotrauma.WayPoint(ID 8860)

[12/04/2022 21:17:20]  - Barotrauma.WayPoint(ID 8861)

[12/04/2022 21:17:20]  - Ruin Light (ID: 8859)(ID 8859)

[12/04/2022 21:17:20]  - Ruin Back Wall Basic(ID 8856)

[12/04/2022 21:17:20]  - Barotrauma.Hull(ID 8857)

[12/04/2022 21:17:20]  - Ruin Wall Horizontal(ID 8858)

[12/04/2022 21:17:20]  - Ruin Wall Horizontal(ID 8855)

[12/04/2022 21:17:20]  - Barotrauma.WayPoint(ID 8854)

[12/04/2022 21:17:20]  - Ruin Light (ID: 8853)(ID 8853)

[12/04/2022 21:17:20]  - Ruin Wall Horizontal(ID 8852)

[12/04/2022 21:17:20]  - Barotrauma.Hull(ID 8851)

[12/04/2022 21:17:20]  - Ruin Back Wall Basic(ID 8850)

[12/04/2022 21:17:20]  - Ruin Wall Horizontal(ID 8831)

[12/04/2022 21:17:20]  - Ruin Decal(ID 8849)

[12/04/2022 21:17:20]  - Ruin Light (ID: 8847)(ID 8847)

[12/04/2022 21:17:20]  - Ruin Light (ID: 8848)(ID 8848)

[12/04/2022 21:17:20]  - Ruin Light (ID: 8845)(ID 8845)

[12/04/2022 21:17:20]  - Ruin Light (ID: 8840)(ID 8840)

[12/04/2022 21:17:20]  - Ruin Light (ID: 8841)(ID 8841)

[12/04/2022 21:17:20]  - Ruin Light (ID: 8842)(ID 8842)

[12/04/2022 21:17:20]  - Ruin Light (ID: 8839)(ID 8839)

[12/04/2022 21:17:20]  - Ruin Light (ID: 8843)(ID 8843)

[12/04/2022 21:17:20]  - Ruin Light (ID: 8844)(ID 8844)

[12/04/2022 21:17:20]  - Ruin Light (ID: 8846)(ID 8846)

[12/04/2022 21:17:20]  - Ruin Light (ID: 8837)(ID 8837)

[12/04/2022 21:17:20]  - Ruin Light (ID: 8836)(ID 8836)

[12/04/2022 21:17:20]  - Ruin Light (ID: 8838)(ID 8838)

[12/04/2022 21:17:20]  - Ruin Light (ID: 8834)(ID 8834)

[12/04/2022 21:17:20]  - Ruin Light (ID: 8835)(ID 8835)

[12/04/2022 21:17:20]  - Ruin Light (ID: 8832)(ID 8832)

[12/04/2022 21:17:20] Some entities were not removed in Entity.RemoveAll:

[12/04/2022 21:17:20] Failed to set the value of the property "Scale" of "Ruin Wall Horizontal" to 0.5 {Exception has been thrown by the target of an invocation.}
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, Object[] index)
   at Barotrauma.SerializableProperty.TrySetValue(Object parentObject, String value)

Inner exception: You are removing a body that is not in the simulation (userdata: Ruin Wall Horizontal). (Parameter 'body')
   at FarseerPhysics.Dynamics.World.Remove(Body body) in C:\Users\joona\Documents\Barotrauma-development\Libraries\Farseer Physics Engine 3.5\Dynamics\World.cs:line 1004
   at Barotrauma.Structure.UpdateSections()
   at Barotrauma.Structure.set_Rect(Rectangle value)
   at Barotrauma.Structure.set_Scale(Single value)
[12/04/2022 21:17:20] Failed to set the value of the property "Scale" of "Ruin Wall Horizontal" to 1 {Exception has been thrown by the target of an invocation.}
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, Object[] index)
   at Barotrauma.SerializableProperty.TrySetValue(Object parentObject, Object value)

Inner exception: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
   at FarseerPhysics.Dynamics.World.Remove(Body body) in C:\Users\joona\Documents\Barotrauma-development\Libraries\Farseer Physics Engine 3.5\Dynamics\World.cs:line 1045
   at Barotrauma.Structure.UpdateSections()
   at Barotrauma.Structure.set_Rect(Rectangle value)
   at Barotrauma.Structure.set_Scale(Single value)
[12/04/2022 21:17:20] Error while removing entity "Bandage (ID: 1012)" {Collection was modified; enumeration operation may not execute.}
   at Barotrauma.Item.Remove()
   at Barotrauma.Entity.RemoveAll()
[12/04/2022 21:17:19] Error while removing entity "Raptor Bane Seed (ID: 17)" {Collection was modified; enumeration operation may not execute.}
   at Barotrauma.Item.Remove()
   at Barotrauma.Entity.RemoveAll()
[12/04/2022 21:17:19] Error while removing entity "Stun Gun Dart (ID: 14)" {Collection was modified; enumeration operation may not execute.}
   at Barotrauma.Item.Remove()
   at Barotrauma.Entity.RemoveAll()
[12/04/2022 21:17:19] Error while removing entity "Sprayer (ID: 10)" {Collection was modified; enumeration operation may not execute.}
   at Barotrauma.Item.Remove()
   at Barotrauma.Entity.RemoveAll()
[12/04/2022 21:17:19] Error while removing entity "Ruin Light (ID: 8831)" {Collection was modified; enumeration operation may not execute.}
   at Barotrauma.Item.Remove()
   at Barotrauma.Entity.RemoveAll()
[12/04/2022 21:17:19] WARNING: Tried to restore enabled packages multiple times/without performing a backup
[12/04/2022 21:17:19] WARNING: Tried to restore enabled packages multiple times/without performing a backup
[12/04/2022 21:17:18] Stopping Lua...
[12/04/2022 21:17:18] Error while reading a message from server. {Collection was modified; enumeration operation may not execute.}
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at Barotrauma.GUICanvas.OnChildrenChanged(RectTransform _)
   at Barotrauma.GUIMessageBox..ctor(RichString headerText, RichString text, LocalizedString[] buttons, Nullable`1 relativeSize, Nullable`1 minSize, Alignment textAlignment, Type type, String tag, Sprite icon, String iconStyle, Sprite backgroundIcon, Func`1 autoCloseCondition, Boolean hideCloseButton)
   at Barotrauma.Networking.ChatMessage.ClientRead(IReadMessage msg)
   at Barotrauma.Networking.GameClient.ReadLobbyUpdate(IReadMessage inc)
   at Barotrauma.Networking.GameClient.ReadDataMessage(IReadMessage inc)
   at Barotrauma.Networking.SteamP2POwnerPeer.HandleMessageForOwner(PeerPacketHeaders peerPacketHeaders, IReadMessage inc)
   at Barotrauma.Networking.SteamP2POwnerPeer.Update(Single deltaTime)
   at Barotrauma.Networking.GameClient.Update(Single deltaTime)
[12/04/2022 21:17:15] Level identifier: greatseabasic
[12/04/2022 21:17:08] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/Łukasz/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2764968387/Turrets/tankturret.png, size: 505x430)
[12/04/2022 21:16:45] Tobiathan
[12/04/2022 21:16:45] Geoffrey
[12/04/2022 21:16:45] Tostiv
[12/04/2022 21:16:45] Dante Cornelius
[12/04/2022 21:16:43] Tobiathan
[12/04/2022 21:16:43] Geoffrey
[12/04/2022 21:16:43] Tostiv
[12/04/2022 21:16:43] Dante Cornelius
[12/04/2022 21:16:43] Tobiathan
[12/04/2022 21:16:43] Geoffrey
[12/04/2022 21:16:43] Tostiv
[12/04/2022 21:16:43] Dante Cornelius
[12/04/2022 21:16:42] Tobiathan
[12/04/2022 21:16:42] Geoffrey
[12/04/2022 21:16:42] Tostiv
[12/04/2022 21:16:42] Dante Cornelius
[12/04/2022 21:02:58] Tobiathan
[12/04/2022 21:02:58] Geoffrey
[12/04/2022 21:02:58] Tostiv
[12/04/2022 21:02:58] Dante Cornelius
[12/04/2022 21:02:58] Tobiathan
[12/04/2022 21:02:58] Tostiv
[12/04/2022 21:02:58] Dante Cornelius
[12/04/2022 21:02:58] Geoffrey
[12/04/2022 21:02:43] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/Łukasz/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2764968387/Jobgear/renegadeplatecarrier.png, size: 683x264)
[12/04/2022 21:02:42] Tobiathan
[12/04/2022 21:02:42] Geoffrey
[12/04/2022 21:02:42] Tostiv
[12/04/2022 21:02:41] Dante Cornelius
[12/04/2022 21:02:40] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/Łukasz/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2764968387/Jobgear/heavyarmor.png, size: 117x168)
[12/04/2022 21:02:39] Received STARTGAMEFINALIZE packet. Round init status: Started
[12/04/2022 21:02:39] Task count: 0
[12/04/2022 21:02:39] Received STARTGAMEFINALIZE packet. Round init status: WaitingForStartGameFinalize
[12/04/2022 21:02:31] Generating an outpost for the start of the level... (Location: Phoenix Linea Prospecting Outpost, level type: Outpost)
[12/04/2022 21:02:31] Level identifier: outpostlevel
[12/04/2022 21:01:56] Tobiathan
[12/04/2022 21:01:56] Geoffrey
[12/04/2022 21:01:56] Tostiv
[12/04/2022 21:01:56] Dante Cornelius
[12/04/2022 21:01:56] Tobiathan
[12/04/2022 21:01:56] Geoffrey
[12/04/2022 21:01:56] Tostiv
[12/04/2022 21:01:56] Dante Cornelius
[12/04/2022 21:01:56] Tobiathan
[12/04/2022 21:01:56] Geoffrey
[12/04/2022 21:01:56] Tostiv
[12/04/2022 21:01:56] Dante Cornelius
[12/04/2022 20:57:16] Tobiathan
[12/04/2022 20:57:16] Geoffrey
[12/04/2022 20:57:16] Tostiv
[12/04/2022 20:57:16] Dante Cornelius
[12/04/2022 20:52:58] Tobiathan
[12/04/2022 20:52:58] Geoffrey
[12/04/2022 20:52:58] friendly raccoon
[12/04/2022 20:52:58] Tostiv
[12/04/2022 20:52:58] Dante Cornelius
[12/04/2022 20:52:51] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/Łukasz/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2764968387/Jobgear/renegadeplatecarrier.png, size: 683x264)
[12/04/2022 20:52:51] WARNING: Received a potentially invalid ENTITY_POSITION message.Entity identifier does not match (server entity is saltbulb, client entity is custompill_horsepill). Ignoring the message...
[12/04/2022 20:52:46] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/Łukasz/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2831987252/Characters/OtherCreatures/Deepseaclown/deepclownhead.png, size: 82x82)
[12/04/2022 20:52:46] WARNING: Potentially incorrectly defined vitality multiplier in "FractalEnforcer". Could not find any afflictions of the type "bitewounds". Did you mean to define the afflictions by identifier instead?
[12/04/2022 20:52:46] WARNING: Potentially incorrectly defined vitality multiplier in "FractalEnforcer". Could not find any afflictions of the type "lacerations". Did you mean to define the afflictions by identifier instead?
[12/04/2022 20:52:46] WARNING: Potentially incorrectly defined vitality multiplier in "FractalEnforcer". Could not find any afflictions of the type "bitewounds". Did you mean to define the afflictions by identifier instead?
[12/04/2022 20:52:46] WARNING: Potentially incorrectly defined vitality multiplier in "FractalEnforcer". Could not find any afflictions of the type "lacerations". Did you mean to define the afflictions by identifier instead?
[12/04/2022 20:52:46] WARNING: Potentially incorrectly defined vitality multiplier in "FractalEnforcer". Could not find any afflictions of the type "bitewounds". Did you mean to define the afflictions by identifier instead?
[12/04/2022 20:52:46] WARNING: Potentially incorrectly defined vitality multiplier in "FractalEnforcer". Could not find any afflictions of the type "lacerations". Did you mean to define the afflictions by identifier instead?
[12/04/2022 20:52:46] WARNING: Potentially incorrectly defined vitality multiplier in "FractalEnforcer". Could not find any afflictions of the type "bitewounds". Did you mean to define the afflictions by identifier instead?
[12/04/2022 20:52:46] WARNING: Potentially incorrectly defined vitality multiplier in "FractalEnforcer". Could not find any afflictions of the type "bitewounds". Did you mean to define the afflictions by identifier instead?
[12/04/2022 20:52:46] WARNING: Potentially incorrectly defined vitality multiplier in "FractalEnforcer". Could not find any afflictions of the type "lacerations". Did you mean to define the afflictions by identifier instead?
[12/04/2022 20:52:44] Tobiathan
[12/04/2022 20:52:44] Geoffrey
[12/04/2022 20:52:43] friendly raccoon
[12/04/2022 20:52:43] Tostiv
[12/04/2022 20:52:43] Dante Cornelius
[12/04/2022 20:52:42] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/Łukasz/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2764968387/Ammo/rpgrockets.png, size: 281x187)
[12/04/2022 20:52:41] Received STARTGAMEFINALIZE packet. Round init status: Started
[12/04/2022 20:52:39] Sprite "%ModDir%/Characters/Vanilla_Creatures/Carrier/carrier.png" not found!
[12/04/2022 20:52:35] Sprite "%ModDir%/Characters/OtherCreatures/Deepseaclown/deepclownlegs.png" not found!
[12/04/2022 20:52:35] Sprite "%ModDir%/Characters/OtherCreatures/Deepseaclown/deepclownbody.png" not found!
[12/04/2022 20:52:35] Sprite "%ModDir%/Characters/OtherCreatures/Deepseaclown/deepclownhead.png" not found!
[12/04/2022 20:52:34] Sprite "%ModDir%/Characters/NewCreatures/Conjoined/limbs.png" not found!
[12/04/2022 20:52:34] Sprite "%ModDir%/Characters/NewCreatures/Conjoined/Huskmutanthunterhead.png" not found!
[12/04/2022 20:52:34] Sprite "%ModDir%/Characters/NewCreatures/Conjoined/Huskmutanthunter.png" not found!
[12/04/2022 20:52:33] Sprite "%ModDir%/Characters/NewCreatures/Undying/huskmutantarmoredhead.png" not found!
[12/04/2022 20:52:33] Sprite "%ModDir%/Characters/NewCreatures/Undying/huskmutantarmoredhead.png" not found!
[12/04/2022 20:52:31] Task count: 0
[12/04/2022 20:52:31] Received STARTGAMEFINALIZE packet. Round init status: WaitingForStartGameFinalize
[12/04/2022 20:52:24] Could not find a suitable module for the location type LocationType (None). Module flag: Airlock.
[12/04/2022 20:52:23] Generating an outpost for the end of the level... (Location: Ana, level type: LocationConnection)
[12/04/2022 20:52:08] Level identifier: plateaubasic
```

**Comment by Regalis11** [comment]
To me it seems like the stack trace is the exact same as in https://github.com/Regalis11/Barotrauma/issues/10010, closing as a duplicate
