### ISSUE TITLE
[Unstable] Crash when interacting with any campaign store

### ISSUE THREAD

**Issue by Maxraa** [Regalis11/Barotrauma#10674]
Barotrauma Client crash report (generated on 12/05/2022 20:43:24)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

842F398C138C3DEAAF5D1ADD56FE08EB

Game version 0.20.10.0 (UnstableWindows, branch release, revision b1238dadd9)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla
Level seed: Dolgovskoy
Loaded submarine: Barsuk (3F25206E3ECC6A5DE25B2F2CEC082D30)
Selected screen: Barotrauma.GameScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit
    GPU name: Radeon RX 580 Series
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void <CreateUI>b__9()
Stack trace: 
   at Barotrauma.Store.<>c__DisplayClass84_1.<CreateUI>b__9() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\Store.cs:line 511
   at Barotrauma.RectTransform.RecalculateAbsoluteSize() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\RectTransform.cs:line 497
   at Barotrauma.RectTransform.RecalculateChildren(Boolean resize, Boolean scale) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\RectTransform.cs:line 718
   at Barotrauma.RectTransform.RecalculateChildren(Boolean resize, Boolean scale) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\RectTransform.cs:line 718
   at Barotrauma.RectTransform.RecalculateChildren(Boolean resize, Boolean scale) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\RectTransform.cs:line 718
   at Barotrauma.GUILayoutGroup.Recalculate() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUILayoutGroup.cs:line 192
   at Barotrauma.GUI.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1259
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 889
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[12/05/2022 20:40:55] Generating an outpost for the start of the level... (Location: Dolgovskoy Mine, level type: Outpost)
[12/05/2022 20:40:55] Level identifier: outpostlevel
[12/05/2022 20:40:47] Couldn't find a GUI style "CategoryButton.None"
[12/05/2022 20:40:47] Couldn't find a GUI style "CategoryButton.None"
[12/05/2022 20:40:47] Couldn't find a GUI style "CategoryButton.None"
[12/05/2022 20:40:12] Attempting to open ALC device "OpenAL Soft on Headset Earphone (Arctis 5 Chat)"
[12/05/2022 20:40:09] Logged in as Supreme Kuwaiti Engineer (SteamID STEAM_1:0:86143986)

That's the second one, and here's the first one I got for doing the same thing

Barotrauma Client crash report (generated on 12/05/2022 20:39:46)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

842F398C138C3DEAAF5D1ADD56FE08EB

Game version 0.20.10.0 (UnstableWindows, branch release, revision b1238dadd9)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla
Level seed: Dolgovskoy
Loaded submarine: Barsuk (BC5EDED09958DC331E497052FC08E2E7)
Selected screen: Barotrauma.GameScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit
    GPU name: Radeon RX 580 Series
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void <CreateUI>b__9()
Stack trace: 
   at Barotrauma.Store.<>c__DisplayClass84_1.<CreateUI>b__9() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\Store.cs:line 511
   at Barotrauma.RectTransform.RecalculateAbsoluteSize() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\RectTransform.cs:line 497
   at Barotrauma.RectTransform.RecalculateChildren(Boolean resize, Boolean scale) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\RectTransform.cs:line 718
   at Barotrauma.RectTransform.RecalculateChildren(Boolean resize, Boolean scale) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\RectTransform.cs:line 718
   at Barotrauma.RectTransform.RecalculateChildren(Boolean resize, Boolean scale) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\RectTransform.cs:line 718
   at Barotrauma.GUILayoutGroup.Recalculate() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUILayoutGroup.cs:line 192
   at Barotrauma.GUI.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1259
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 889
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[12/05/2022 20:38:12] Unlocked mission "Personnel Transport" in the connection from "Dolgovskoy Mine" to "Gortyna Flexus Habitation Outpost".
[12/05/2022 20:38:10] Unlocked mission "Killing Hammerheads" in the connection from "Dolgovskoy Mine" to "Arid Troma Habitation Outpost".
[12/05/2022 20:38:08] Unlocked mission "Giant Spineling" in the connection from "Dolgovskoy Mine" to "Arid Troma Habitation Outpost".
[12/05/2022 20:37:17] Generating an outpost for the start of the level... (Location: Dolgovskoy Mine, level type: Outpost)
[12/05/2022 20:37:17] Level identifier: outpostlevel
[12/05/2022 20:37:08] Transitioning to Dolgovskoy (current location: Aitreles, selected location: Dolgovskoy Mine, leaving sub: Barsuk, at start: False, at end: True, transition type: ProgressToNextLocation)
[12/05/2022 20:25:40] Could not find a spawn point for a SpawnAction (spawn location: BeaconStation (tag: beacon_bandit), skipping.
[12/05/2022 20:25:26] Could not find a suitable module for the location type LocationType (None). Module flag: Airlock.
[12/05/2022 20:25:26] Generating an outpost for the end of the level... (Location: Aitreles, level type: LocationConnection)
[12/05/2022 20:25:26] Level identifier: coldcavernsadvanced
[12/05/2022 20:25:23] Couldn't find a GUI style "CategoryButton.None"
[12/05/2022 20:25:23] Couldn't find a GUI style "CategoryButton.None"
[12/05/2022 20:25:23] Couldn't find a GUI style "CategoryButton.None"
[12/05/2022 20:01:19] Could not find a spawn point for a SpawnAction (spawn location: BeaconStation (tag: beacon_bandit), skipping.
[12/05/2022 20:01:05] Could not find a suitable module for the location type LocationType (None). Module flag: Airlock.
[12/05/2022 20:01:05] Generating an outpost for the end of the level... (Location: Aitreles, level type: LocationConnection)
[12/05/2022 20:01:04] Level identifier: coldcavernsadvanced
[12/05/2022 20:00:54] Couldn't find a GUI style "CategoryButton.None"
[12/05/2022 20:00:54] Couldn't find a GUI style "CategoryButton.None"
[12/05/2022 20:00:54] Couldn't find a GUI style "CategoryButton.None"
[12/05/2022 20:00:12] Attempting to open ALC device "OpenAL Soft on Headset Earphone (Arctis 5 Chat)"
[12/05/2022 20:00:00] Logged in as Supreme Kuwaiti Engineer (SteamID STEAM_1:0:86143986)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/652545a7ebd81acbc8b1a9bd527ad5916de9d6fd

**Comment by Maxraa** [comment]
Oh waow that was so fast, thank you very much! Awesome game you have made btw I love it so much!

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
