### ISSUE TITLE
Frequency multiplier out of range: Infinity

### ISSUE THREAD

**Issue by Jade-Harleyy** [Regalis11/Barotrauma#10695]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I attempted to modify a Pulse Laser's stats to fire a burt of 10 shots, then wait.

However what actually happened, is that the game threw an error at me after the 10th shot.

### Reproduction steps

1. Open submarine editor.
2. Import this submarine: [pulse laser test.zip](https://github.com/Regalis11/Barotrauma/files/10203744/pulse.laser.test.zip).
3. Enter testing mode.
4. Use the periscope to continuously fire the Pulse Laser.
5. After the 10th shot, the console will display the error message.

### Bug prevalence

Happens every time I play

### Version

0.20.9.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Frequency multiplier out of range: Infinity   at System.Environment.get_StackTrace()
   at Barotrauma.Sounds.SoundChannel.set_FrequencyMultiplier(Single value) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Sounds\SoundChannel.cs:line 276
   at Barotrauma.Items.Components.Turret.UpdateProjSpecific(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Components\Turret.cs:line 269
   at Barotrauma.Items.Components.Turret.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Turret.cs:line 475
   at Barotrauma.Item.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 1937
   at Barotrauma.MapEntity.UpdateAll(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\MapEntity.cs:line 600
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 254
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 864
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 651
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58
```

**Comment by NilanthAnimosus** [comment]
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/f2a71f9b7c694ad3b5c28abf0e8d51906f87a843, no issues found, closing.
