### ISSUE TITLE
Blank lobby when joining a server with a big ban list, description or sub list

### ISSUE THREAD

**Issue by evilfactory** [Regalis11/Barotrauma#10719]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When joining a server with a big ban list, the lobby screen will remain blank and the server console will continuously spam
```
Failed to write a network message for the client "Robert Bingham"! {Too much data is being stored in SegmentTable<ServerNetSegment> (1 segments)}
   at Barotrauma.Networking.SegmentTableWriter`1.ThrowOnInvalidState() in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Utils/SegmentTable.cs:line 110
   at Barotrauma.Networking.SegmentTableWriter`1.Dispose() in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Utils/SegmentTable.cs:line 123
   at Barotrauma.Networking.GameServer.ClientWriteLobby(Client c) in <DEV>/Barotrauma/BarotraumaServer/ServerSource/Networking/GameServer.cs:line 2046
   at Barotrauma.Networking.GameServer.ClientWrite(Client c) in <DEV>/Barotrauma/BarotraumaServer/ServerSource/Networking/GameServer.cs:line 1586
   at Barotrauma.Networking.GameServer.Update(Single deltaTime) in <DEV>/Barotrauma/BarotraumaServer/ServerSource/Networking/GameServer.cs:line 605
```

### Reproduction steps

1. Join a server with a big ban list
2. Make sure to have admin permissions on the server
3. Watch the console spam the error

### Bug prevalence

Happens every time I play

### Version

0.20.15.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Failed to write a network message for the client "Robert Bingham"! {Too much data is being stored in SegmentTable<ServerNetSegment> (1 segments)}
   at Barotrauma.Networking.SegmentTableWriter`1.ThrowOnInvalidState() in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Utils/SegmentTable.cs:line 110
   at Barotrauma.Networking.SegmentTableWriter`1.Dispose() in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Utils/SegmentTable.cs:line 123
   at Barotrauma.Networking.GameServer.ClientWriteLobby(Client c) in <DEV>/Barotrauma/BarotraumaServer/ServerSource/Networking/GameServer.cs:line 2046
   at Barotrauma.Networking.GameServer.ClientWrite(Client c) in <DEV>/Barotrauma/BarotraumaServer/ServerSource/Networking/GameServer.cs:line 1586
   at Barotrauma.Networking.GameServer.Update(Single deltaTime) in <DEV>/Barotrauma/BarotraumaServer/ServerSource/Networking/GameServer.cs:line 605
```

**Comment by evilfactory** [comment]
This also seems to happen if you have too many submarines or a server description too large

**Comment by internet-person** [comment]
i'd like to note this is also a problem when hosting servers rather then just joining

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/48f2b551802792e075e0818b6e068bf4a8c732f2
