### ISSUE TITLE
Can't run DedicatedServer.exe after the update (InitGameServer returned false)

### ISSUE THREAD

**Issue by AmazingMiao** [Regalis11/Barotrauma#10756]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Every time I try to run DedicatedServer.exe, it crashes. The crashlog indicated that InitGameServer return false, but I don't know how to solve it. The crash started happening since the 0.20.15.0 update.

### Reproduction steps

_1. Run DedicatedServer.exe_
_2. After a few seconds, it crashes_

### Bug prevalence

Happens every now and then

### Version

0.20.15.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Dedicated Server crash report (generated on 12/18/2022 12:30:10)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


Game version 0.20.15.0 (ReleaseWindows, branch release, revision 0d1158d3aa)
Language: English
Selected content packages: Vanilla
Level seed: no level loaded
Loaded submarine: None
Selected screen: None
Server (Round hadn't been started)


System info:
    Operating system: Microsoft Windows NT 6.3.9600.0 64 bit


Exception: InitGameServer returned false (0,35788,27015,0,NoAuthentication,"1.0.0.0") (System.Exception)
Target site: Void Init(Steamworks.AppId, Steamworks.SteamServerInit, Boolean)
Stack trace: 
   at Steamworks.SteamServer.Init(AppId appid, SteamServerInit init, Boolean asyncCallbacks) in <DEV>\Libraries\Facepunch.Steamworks\SteamServer.cs:line 86
   at Barotrauma.Steam.SteamManager.CreateServer(GameServer server, Boolean isPublic) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Steam\SteamManager.cs:line 22
   at Barotrauma.Networking.GameServer.StartServer() in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Networking\GameServer.cs:line 187
   at Barotrauma.GameMain.StartServer() in <DEV>\Barotrauma\BarotraumaServer\ServerSource\GameMain.cs:line 246
   at Barotrauma.GameMain.Run() in <DEV>\Barotrauma\BarotraumaServer\ServerSource\GameMain.cs:line 291
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Program.cs:line 78


Last debug messages:
   12/18/2022 12:30:10 - [12/18/2022 12:30:10]
  Saving banlist
   12/18/2022 12:30:10 - [12/18/2022 12:30:10]
  Using Lidgren networking. Manual port forwarding may be required. If players cannot connect to the server, you may want to use the in-game hosting menu (which uses SteamP2P networking and does not require port forwarding).
   12/18/2022 12:30:10 - [12/18/2022 12:30:10]
  Starting the server...
   12/18/2022 12:30:10 - WARNING: File "serversettings.xml" not found. Starting the server with default settings.
   12/18/2022 12:30:10 - Couldn't load xml document "serversettings.xml"! {Could not find file 'C:\Program Files (x86)\steamcmd\steamapps\common\Barotrauma\serversettings.xml'.}
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at Barotrauma.IO.File.Open(String path, FileMode mode, FileAccess access, Nullable`1 share) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SafeIO.cs:line 400
   at Barotrauma.XMLExtensions.TryLoadXml(String filePath, Exception& exception) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Serialization\XMLExtensions.cs:line 110
   12/18/2022 12:30:10 - Selected shuttle: Hemulen
```

**Comment by Regalis11** [comment]
Thank you for the report! This error seems to imply the game somehow failed to register the server to Steam. There could be several potential explanations to this: the port settings could be invalid (which doesn't seem to be the case here, the values shown in that error message seem OK) or the game might be failing to connect Steam's servers. 

I would recommend [verifying file integrity as described here](https://trello.com/c/5RL4AQ8K/314-workaround-included-game-crashing-on-startup-after-update), and making sure that the game isn't getting blocked by e.g. firewall or an antivirus software. Please let us know if either of those help! Also, do you run into the same issue when trying to host from in-game, or does this only happen when you try to launch DedicatedServer.exe directly?

**Comment by Regalis11** [comment]
No known steps to repro, closing
