### ISSUE TITLE
Single Player crash (Adapter 'NVIDIA GeForce MX150' does not support the Reach profile)

### ISSUE THREAD

**Issue by Coral2** [Regalis11/Barotrauma#10778]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I arrived at the station after my mission, with red plants growing on the water pump. I didn't clean up in time, so **I tried to get log back to the site again**, but the game crashed and I couldn't open the software anymore. I tried to verify the integrity of the game. It didn't work.

I hope I can at least play other saves. Thank you very much.

### Reproduction steps

(1. Single Player campaign
2. mod sub named “小雀(Finch)” lost her drone and lifeboat while changing submarines
3. Go back to the main menu and the lost item comes back
4...)
5. Arrived at the station, with plants growing on the pump.
6. Try to log in to the site again, but the game crashes and can no longer open the software anymore.

### Bug prevalence

Just once

### Version

0.20.16.1

### -

.

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 12/21/2022 01:30:28)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

B5C3AB2BBD7769A420A018E6898F0875

Game version 0.20.16.1 (ReleaseWindows, branch release, revision 33a42adf77)
Graphics mode: 0x0 (Windowed)
VSync OFF
Language: 
Selected content packages: None
Level seed: no level loaded
Loaded submarine: None
Selected screen: None
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19045.0 64 bit
    Game not initialized

Exception: Adapter 'NVIDIA GeForce MX150' does not support the Reach profile. (Microsoft.Xna.Framework.Graphics.NoSuitableGraphicsDeviceException)
Target site: Void .ctor(Microsoft.Xna.Framework.Graphics.GraphicsAdapter, Microsoft.Xna.Framework.Graphics.GraphicsProfile, Microsoft.Xna.Framework.Graphics.PresentationParameters)
Stack trace: 
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice..ctor(GraphicsAdapter adapter, GraphicsProfile graphicsProfile, PresentationParameters presentationParameters) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\GraphicsDevice.cs:line 217
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice..ctor(GraphicsDeviceInformation gdi) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\GraphicsDevice.cs:line 189
   at Microsoft.Xna.Framework.GraphicsDeviceManager.CreateDevice(GraphicsDeviceInformation gdi) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\GraphicsDeviceManager.cs:line 131
   at Microsoft.Xna.Framework.GraphicsDeviceManager.CreateDevice() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\GraphicsDeviceManager.cs:line 114
   at Microsoft.Xna.Framework.GraphicsDeviceManager.ApplyChanges() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\GraphicsDeviceManager.cs:line 303
   at Barotrauma.GameMain..ctor(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 218
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 57

Last debug messages:
[12/21/2022 01:30:26] Logged in as 珊瑚 (SteamID STEAM_1:1:461073813)
```

**Comment by Coral2** [comment]
Ok, problem solved. I rebooted the computer and fixed it. Looks like some firmware won't connect, but the reason it's happening is... Right？
