### ISSUE TITLE
Barotrauma error when loading a save on crash (nullref exception in Submarine.MakeWreck)

### ISSUE THREAD

**Issue by ZakingYT** [Regalis11/Barotrauma#10784]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [x] My issue happened while using mods.

### What happened?

After sailing, the game crashed and gave the crash report, and then the save does not start

### Reproduction steps

[crashreport (12).log](https://github.com/Regalis11/Barotrauma/files/10276774/crashreport.12.log)

### Bug prevalence

Happens every now and then

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Dedicated Server crash report (generated on 12/21/2022 14:04:22)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


Game version 0.20.16.1 (ReleaseWindows, branch release, revision 33a42adf77)
Language: Russian
Selected content packages: Vanilla, BeaconStation_bandit, DockingModule_03, DockingModule_04, Mercury II CH4LLENGER COMPLETE, Таламы, Тапок 20, Alkonost, Medusa, Zyleand Shipyard Drone Collection, Талам-№3К, Manta Ray, Extract It!, Elevator demos, IMC HAVANA TRANSPORT, Кинжал, Стена с Окном, Смайлик, По-2, Статуя, Пирамида Иллюминатов, Перископ на 2 пушки, Окно с дверью, Окно, Модуль управления, Модуль наблюдения, Мимик, Локдаун, Комплекс склада у медика, Клапан, Кислород 10канал, Камикадзе-Дрон, ДверьСдопускомККапитану, Высота, Входная подсветка, Время без проиш, Вода 10канал, DockingModule_06, АвтоДверь, DockingModule_05, DockingModule_07, Irma, J.O.S.H, АвтоЛюк, Self Serve, MoonPool, Бар, Астрал, ''Штурм'' D-10, Пирамида Илюминатов (Remaster), ''Апокалипсис'' D-11, ''Дельфин'' F-1, бомбы, флора, BeaconStation4, Перила, Перила 2, Super Radar, Батарейки, Талам-2Д, Антенны, Антенна, Антенна 2, Стык. люк, ''Mira''-R-1, Плавник, моник, DockingModule_08, AloneBeacon1, редкое оружие, MineOfficeBuild
Level seed: no level loaded
Loaded submarine: None
Selected screen: Barotrauma.NetLobbyScreen
Server (Round hadn't been started)


System info:
    Operating system: Microsoft Windows NT 10.0.18363.0 64 bit


Exception: Pipe is broken. (System.IO.IOException)
Target site: Void WriteCore(System.ReadOnlySpan`1[System.Byte])
Stack trace: 
   at System.IO.Pipes.PipeStream.WriteCore(ReadOnlySpan`1 buffer)
   at Barotrauma.Networking.ChildServerRelay.<UpdateWrite>g__writeMsg|27_0(WriteStatus writeStatus, Byte[] msg) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\ChildServerRelay.cs:line 265
   at Barotrauma.Networking.ChildServerRelay.UpdateWrite() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\ChildServerRelay.cs:line 281
   at System.Threading.Thread.StartCallback()


Last debug messages:
   12/21/2022 14:04:22 - [12/21/2022 14:04:22]
  Saving banlist
   12/21/2022 14:04:22 - [12/21/2022 14:04:22]
  Saving banlist
   12/21/2022 14:04:01 - [12/21/2022 14:04:01]
  Round ended.
   12/21/2022 14:04:01 - Coroutine Barotrauma.Networking.GameServer+<StartGame>d__89 threw an exception: Object reference not set to an instance of an object.
   at Barotrauma.Submarine.MakeWreck() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Submarine.cs:line 348
   at Barotrauma.Level.SpawnSubOnPath(String subName, ContentFile contentFile, SubmarineType type) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Levels\Level.cs:line 3598
   at Barotrauma.Level.CreateWrecks() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Levels\Level.cs:line 3871
   at Barotrauma.Level.Generate(Boolean mirror, Location startLocation, Location endLocation) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Levels\Level.cs:line 1338
   at Barotrauma.Level.Generate(LevelData levelData, Boolean mirror, Location startLocation, Location endLocation, SubmarineInfo startOutpost, SubmarineInfo endOutpost) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Levels\Level.cs:line 466
   at Barotrauma.GameSession.StartRound(LevelData levelData, Boolean mirrorLevel, SubmarineInfo startOutpost, SubmarineInfo endOutpost) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameSession.cs:line 429
   at Barotrauma.Networking.GameServer.StartGame(SubmarineInfo selectedSub, SubmarineInfo selectedShuttle, GameModePreset selectedMode, CampaignSettings settings)+MoveNext() in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Networking\GameServer.cs:line 2209
   at Barotrauma.CoroutineManager.PerformCoroutineStep(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 199
   at Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 257
   12/21/2022 14:03:59 - Generating an outpost for the start of the level... (Location: Центр Vellamo's Crevasse, level type: LocationConnection)
   12/21/2022 14:03:57 - Level identifier: greatseabasic
   12/21/2022 14:03:54 - [12/21/2022 14:03:54]
  Starting a new round...
   12/21/2022 14:03:51 - [12/21/2022 14:03:51]
  Round ended.
   12/21/2022 14:03:51 - [12/21/2022 14:03:51]
  Ending the round...
   12/21/2022 14:03:50 - Transitioning to Vellamo's CrevasseMerrivale Linea (current location: Центр Vellamo's Crevasse, selected location: Merrivale Linea, leaving sub: ''Кинжал'' Z-11, at start: True, at end: False, transition type: LeaveLocation)
   12/21/2022 14:03:50 - [12/21/2022 14:03:50]
  Client "ZakingYT" ended the round.
   12/21/2022 14:02:32 - [12/21/2022 14:02:32]
  Kendall Stogner: Ты лучше о работе думай. Иначе окажешься там же, где твоя бутылка - в ящике.
   12/21/2022 14:02:27 - [12/21/2022 14:02:27]
  Mechelle Graves: Поскорей бы вернуться домой и откупорить бутылочку «Старого Кадма».
   12/21/2022 14:02:15 - Unlocked mission "Уничтожить гнездо грязевого раптора" in the connection from "Центр Vellamo's Crevasse" to "Merrivale Linea".
```

**Comment by Regalis11** [comment]
Thank you for the report! It seems the problem here is that the custom wreck doesn't have any hulls, and those are required for the sub's collider to generate properly. I addressed the issue in https://github.com/Regalis11/Barotrauma-development/commit/a23914008f569c01c99e66af012855d0c814ff32 (link to our private repo) - now these subs log an error in the debug console, but don't cause a crash. Until that fix is out, you should be able to work around the issue by disabling that custom wreck. Sorry for the inconvenience!

**Comment by ZakingYT** [comment]
I found that this problem exists not only with this shuttle, but with all the custom wrecks

**Comment by ZakingYT** [comment]
Okay, thanks for the answer.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
