### ISSUE TITLE
Trying to use a mod server-executable on macOS will result in a guaranteed crash

### ISSUE THREAD

**Issue by KilianKilmister** [Regalis11/Barotrauma#10798]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

The game running on macOS will unconditionally crash when it's told to use the server-executable provided by a mod.

When the game resolves the path to the mod executable and it's not running on Windows, it will prepend `./` to what on macOS is already absolute path to the executable file. As a result it will end up resolving the path against the current working directory and attempt to execute a non-existent file, resulting in a crash.

The path it's trying to execute will look something like this:
```Path
.//Users/<user>/Library/Application Support/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/<mod id>/<exec path>
```

A temporary fix for this is simply creating a symlink linking `<game-root-folder>/Users -> /Users`

As I found this to be rather peculiar, I ended up tracking down in the source code why this was happening:

- [line where `./` is prepended to `<mod exec path>`][prepend]
- [`<mod exec path>` for workshop mods is `<SaveUtil.DefaultSavePath>/WorkshopMod/Installed/<mod id>/<path in contentfile.xml>`][exec]
- [`SaveUtil.DefaultSavePath` is defined by an absolute path on macOS][default]

[exec]:
<https://github.com/Regalis11/Barotrauma/blob/master/Barotrauma/BarotraumaShared/SharedSource/ContentManagement/ContentPackage/ContentPackage.cs#L28>
[prepend]:<https://github.com/Regalis11/Barotrauma/blob/master/Barotrauma/BarotraumaClient/ClientSource/Screens/MainMenuScreen.cs#L907>
[default]:<https://github.com/Regalis11/Barotrauma/blob/master/Barotrauma/BarotraumaShared/SharedSource/Utils/SaveUtil.cs#L21>

### Reproduction steps

1. Be on macOS
2. MainMenu -> Host Server
3. Change the value for `Server executable` from `Vanilla` to any provided by mods.
4. Hit `Start`
5. Unconditional Crash

### Bug prevalence

Happens every time I play

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

MacOS

### Relevant error messages and crash reports

```shell
Last debug messages:
[12/22/2022 18:19:26] Failed to start server {An error occurred trying to start process './/Users/<user>/Library/Application Support/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/<mod id>/<exec path>' with working directory '/<steam path>/Library/steamapps/common/Barotrauma/Barotrauma.app/Contents/MacOS'. No such file or directory}
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Barotrauma.Networking.ChildServerRelay.Start(ProcessStartInfo processInfo) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Networking/ChildServerRelay.cs:line 32
   at Barotrauma.MainMenuScreen.StartServer() in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Screens/MainMenuScreen.cs:line 945
[12/22/2022 18:19:26] Failed to start ChildServerRelay Process. File: .//Users/<user>/Library/Application Support/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/<mod id>/<exec path>, arguments: -name "Server" -public False -playstyle Casual -banafterwrongpassword False -karmaenabled False -maxplayers 10 -nopassword -steamid <id> -ownerkey <key> -pipes <pipes pipes>
[12/22/2022 18:18:37] WARNING: Tried to restore enabled packages multiple times/without performing a backup
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/18003d85ddb389dee10849513323e80b77d30462

**Comment by Regalis11** [comment]
Example mod for testing this (not actually functional, but can be used to test that launching the executable works)

[ServerModTest.zip](https://github.com/Regalis11/Barotrauma/files/10374929/ServerModTest.zip)

**Comment by Rokvach** [comment]
Tested on Linux and this is working correctly, just needs to be tested on Mac still

**Comment by KilianKilmister** [comment]
I tried it, and it seems like it's able to find the specified file now. The path isn't normalized (still includes a `/./` in `...MacOS/./LocalMods/ServerModTest...`), but while I wouldn't call pretty, it's a valid system path.

The game crashed afterwards, but I expected as much. Not sure what's up with it encountering a `Permission denied` system error, though. That is probably just some fluke of the runtime trying to execute a windows executable and not directly related to any barotrauma code. 

```log
Last debug messages:
[01/25/2023 20:35:31] Exiting...
[01/25/2023 20:35:16] Failed to start server {An error occurred trying to start process '/Volumes/Case-Insensitive/Library/steamapps/common/Barotrauma/Barotrauma.app/Contents/MacOS/./LocalMods/ServerModTest/DedicatedServer.exe' with working directory '/Volumes/Case-Insensitive/Library/steamapps/common/Barotrauma/Barotrauma.app/Contents/MacOS'. Permission denied}
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Barotrauma.Networking.ChildServerRelay.Start(ProcessStartInfo processInfo) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Networking/ChildServerRelay.cs:line 32
   at Barotrauma.MainMenuScreen.StartServer() in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Screens/MainMenuScreen.cs:line 945
[01/25/2023 20:35:16] Failed to start ChildServerRelay Process. File: ./LocalMods/ServerModTest/DedicatedServer.exe, arguments: -name "KK" -public False -playstyle Casual -banafterwrongpassword False -karmaenabled False -maxplayers 10 -password "kk" -steamid <id> -ownerkey <key> -pipes 275 278
```

I quickly tried it again, replacing the `.exe` with a copy of the `DedicatedServer` file shipped with the game and the game did **not** crash. But I did get a message that the server process had "closed unexpectedly" right after. I don't know the mechanics of mod-server executables, so I don't know wether that was to be expected here, just thought I'd mention it.

**Comment by Rokvach** [comment]
Seems to be working correctly, closing.
