### ISSUE TITLE
Null reference exception caused by a door when trying to spectate an ongoing round

### ISSUE THREAD

**Issue by evilfactory** [Regalis11/Barotrauma#10801]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The error would continue to happen every time you rejoined unless the current round was restarted.

```cs
Error while reading a message from server. 
Exception thrown while reading segment EntityEventInitial at position 16.
Inner exception: Object reference not set to an instance of an object.
   at Barotrauma.Items.Components.Door.DisableBody() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Door.cs:line 462
   at Barotrauma.Items.Components.Door.set_IsBroken(Boolean value) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Door.cs:line 81
   at Barotrauma.Items.Components.Door.ClientEventRead(IReadMessage msg, Single sendingTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Components\Door.cs:line 339
   at Barotrauma.Item.ClientEventRead(IReadMessage msg, Single sendingTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Item.cs:line 1362
   at Barotrauma.Networking.ClientEntityEventManager.Read(ServerNetSegment type, IReadMessage msg, Single sendingTime, List1 entities) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\NetEntityEvent\ClientEntityEventManager.cs:line 221
   at Barotrauma.Networking.GameClient.<>c__DisplayClass116_0.<ReadIngameUpdate>b__0(ServerNetSegment segment, IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 2127
   at Barotrauma.Networking.SegmentTableReader1.Read(IReadMessage msg, SegmentDataReader segmentDataReader, ExceptionHandler exceptionHandler) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SegmentTable.cs:line 302
```

### Reproduction steps

1. Start a round
2. Break a door
3. Leave the server
4. Join again and click spectate
5. Error

### Bug prevalence

Happens every now and then

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Error while reading a message from server. 
Exception thrown while reading segment EntityEventInitial at position 16.
Inner exception: Object reference not set to an instance of an object.
   at Barotrauma.Items.Components.Door.DisableBody() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Door.cs:line 462
   at Barotrauma.Items.Components.Door.set_IsBroken(Boolean value) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Door.cs:line 81
   at Barotrauma.Items.Components.Door.ClientEventRead(IReadMessage msg, Single sendingTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Components\Door.cs:line 339
   at Barotrauma.Item.ClientEventRead(IReadMessage msg, Single sendingTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Item.cs:line 1362
   at Barotrauma.Networking.ClientEntityEventManager.Read(ServerNetSegment type, IReadMessage msg, Single sendingTime, List1 entities) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\NetEntityEvent\ClientEntityEventManager.cs:line 221
   at Barotrauma.Networking.GameClient.<>c__DisplayClass116_0.<ReadIngameUpdate>b__0(ServerNetSegment segment, IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 2127
   at Barotrauma.Networking.SegmentTableReader1.Read(IReadMessage msg, SegmentDataReader segmentDataReader, ExceptionHandler exceptionHandler) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SegmentTable.cs:line 302
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8f1fb67baa8b5d5afe2f92a0d014d596af5a0502

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
