### ISSUE TITLE
Server setting xml file isn't created if the server fails to find it

### ISSUE THREAD

**Issue by evilfactory** [Regalis11/Barotrauma#10806]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The default `serversettings.xml` file isn't created if the server fails to find one.

### Reproduction steps

1. Download the dedicated server
2. Notice how there's no serversettings.xml
3. Start the server
4. Still no serversettings.xml present

### Bug prevalence

Happens every time I play

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
12/18/2022 12:30:10 - WARNING: File "serversettings.xml" not found. Starting the server with default settings.
   12/18/2022 12:30:10 - Couldn't load xml document "serversettings.xml"! {Could not find file 'C:\BTServer\serversettings.xml'.}
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at Barotrauma.IO.File.Open(String path, FileMode mode, FileAccess access, Nullable`1 share) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SafeIO.cs:line 400
   at Barotrauma.XMLExtensions.TryLoadXml(String filePath, Exception& exception) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Serialization\XMLExtensions.cs:line 110
```

**Comment by theCrius** [comment]
Confirming this one on Linux.

Just rebuilt the docker image I use and where usually I would find the `serversettings.xml` file, there is nothing. I assumed it might have been moved with the other configuration files in the `Data/` folder but it's just not there.

This is preventing dedicated servers from being deployed unless you use a file generated "manually" and add it.

**Comment by theCrius** [comment]
You can test the issue by using [this repo](https://github.com/theCrius/barotrauma-docker) with docker configuration and [commenting line 57](https://github.com/theCrius/barotrauma-docker/blob/main/Dockerfile#L57)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/63d761711ecc9fac226834fbeefb88ca9b14b38d. As a workaround, you can make the server save the current settings by changing any setting or by closing the server.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
