### ISSUE TITLE
Error when protein bar is spawned

### ISSUE THREAD

**Issue by MikeBrBa** [Regalis11/Barotrauma#10819]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When a protein bar is spawned or a sub with a protein bar in a cabinet is loaded an error appears.

### Reproduction steps

1. Spawn a protein bar (through sub editor or vending machine)

### Bug prevalence

Happens every time I play

### Version

0.21.0.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Invalid sound type in Barotrauma.ContentXElement! {Must specify valid information for parsing in the string. (Parameter 'value')}
   at System.Enum.TryParse(Type enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
   at System.Enum.TryParse(Type enumType, String value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
   at Barotrauma.Items.Components.ItemComponent.LoadElemProjSpecific(ContentXElement subElement) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Components\ItemComponent.cs:line 546
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8650d05f17cee7897dfd96f0fbf0133fd6ad2f39

**Comment by Rokvach** [comment]
Tested, working correctly. closing.
