### ISSUE TITLE
Rope update client crash

### ISSUE THREAD

**Issue by cshingle** [Regalis11/Barotrauma#10830]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

The rope client crash. I am pretty sure I had this happen in past versions as well. I took a look for old items and found this one that looks similar. Hopefully this stack trace is useful, because reproducing this issue is pretty much impossible.
#9716

I am using a mod that makes the ropes not break until you release the aim button. It also makes them stick to walls they hit rather than bounce off. I don't think the mod is responsible because I have a few hundred hours into it after making this change.
https://steamcommunity.com/sharedfiles/filedetails/?id=2821614540

### Reproduction steps

1. Play a campaign multiplayer with dedicated server.
2. Use a lot of harpoons
3. After 40+ hours in the campaign half the clients crash with the error included
4. All clients where able to rejoin the server after starting the game back up

### Bug prevalence

Happens every now and then

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Linux

### Relevant error messages and crash reports

```shell
﻿Barotrauma Client crash report (generated on 12/26/2022 21:59:09)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

4BB1A67F0F7E5BF60D13A0A9735A5492

Game version 0.20.16.1 (ReleaseLinux, branch release, revision 33a42adf77)
Graphics mode: 2560x1440 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla, Europa Depths Vanilla Monsters, Europa Depths Trauma, Europa Depths Npcs, Europa Depths More Plants, Europa Depths Equipment, Europa Depths Items
Level seed: Jaavuari
Loaded submarine: Sea Snake (7D266EDA8F94CF390CE67436FB309B5B)
Selected screen: Barotrauma.GameScreen
SteamManager initialized
Client (Round had started)

System info:
    Operating system: Unix 5.15.0.56 64 bit
    GPU name: 
    Display mode: {Width:2560 Height:1440 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void Update(Single, Barotrauma.Camera)
Stack trace: 
   at Barotrauma.Items.Components.Rope.Update(Single deltaTime, Camera cam)
   at Barotrauma.Item.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 1937
   at Barotrauma.MapEntity.UpdateAll(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\MapEntity.cs:line 562
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 254
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 864
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[12/26/2022 21:59:09] Attempted to access a potentially removed ragdoll. Character: MM. Blank, id: 9139, removed: True, ragdoll removed: True
   at System.Environment.get_StackTrace()
   at Barotrauma.Ragdoll.get_Limbs() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Animation\Ragdoll.cs:line 58
   at Barotrauma.Ragdoll.ResetPullJoints(Func`2 condition) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Animation\Ragdoll.cs:line 928
   at Barotrauma.Items.Components.Rope.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Rope.cs:line 312
   at Barotrauma.Item.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 1937
   at Barotrauma.MapEntity.UpdateAll(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\MapEntity.cs:line 562
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 254
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 864
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 651
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58
[12/26/2022 21:57:19] zig158
[12/26/2022 21:57:19] NonT
[12/26/2022 21:57:19] MM. Blank
[12/26/2022 21:57:19] Beer
[12/26/2022 21:57:19] zig158
[12/26/2022 21:57:19] NonT
[12/26/2022 21:57:19] MM. Blankmsg
[12/26/2022 21:57:19] Beer
[12/26/2022 21:57:19] zig158
[12/26/2022 21:57:19] NonT
[12/26/2022 21:57:19] Beer
[12/26/2022 21:57:19] MM. Blank
[12/26/2022 21:57:17] zig158
[12/26/2022 21:57:17] NonT
[12/26/2022 21:57:17] MM. Blank
[12/26/2022 21:57:17] Beer
[12/26/2022 21:57:17] zig158
[12/26/2022 21:57:17] NonT
[12/26/2022 21:57:17] MM. Blank
[12/26/2022 21:57:17] Beer
[12/26/2022 21:57:17] zig158
[12/26/2022 21:57:17] NonT
[12/26/2022 21:57:17] MM. Blank
[12/26/2022 21:57:17] Beer
[12/26/2022 21:57:17] zig158
[12/26/2022 21:57:17] NonT
[12/26/2022 21:57:17] MM. Blank
[12/26/2022 21:57:17] Beer
[12/26/2022 21:54:41] zig158
[12/26/2022 21:54:41] NonT
[12/26/2022 21:54:41] MM. Blank
[12/26/2022 21:54:41] Beer
[12/26/2022 21:54:41] zig158
[12/26/2022 21:54:41] NonT
[12/26/2022 21:54:41] MM. Blank
[12/26/2022 21:54:41] Beer
[12/26/2022 21:54:40] zig158
[12/26/2022 21:54:40] NonT
[12/26/2022 21:54:40] MM. Blank
[12/26/2022 21:54:40] Beer
[12/26/2022 21:54:39] zig158
[12/26/2022 21:54:39] NonT
[12/26/2022 21:54:39] MM. Blank
[12/26/2022 21:54:39] Beer
[12/26/2022 21:54:39] zig158
[12/26/2022 21:54:39] NonT
[12/26/2022 21:54:39] MM. Blank
[12/26/2022 21:54:39] Beer
[12/26/2022 21:53:41] zig158
[12/26/2022 21:53:41] NonT
[12/26/2022 21:53:41] MM. Blank
[12/26/2022 21:53:41] Beer
[12/26/2022 21:53:23] zig158
[12/26/2022 21:53:23] NonT
[12/26/2022 21:53:23] MM. Blank
[12/26/2022 21:53:23] Beer
[12/26/2022 21:53:20] Server running slowly (57 updates/s)!
[12/26/2022 21:53:16] zig158
[12/26/2022 21:53:16] NonT
[12/26/2022 21:53:16] MM. Blank
[12/26/2022 21:53:16] Beer
[12/26/2022 21:53:15] Received STARTGAMEFINALIZE packet. Round init status: Started
[12/26/2022 21:53:15]  -0: LobbyQuery.RequestAsync (1), WaitingForActivation
[12/26/2022 21:53:15] Task count: 1
[12/26/2022 21:53:15] Received STARTGAMEFINALIZE packet. Round init status: WaitingForStartGameFinalize
[12/26/2022 21:53:11] Generating an outpost for the start of the level... (Location: Jaavuari Outpost, level type: Outpost)
[12/26/2022 21:53:11] Level identifier: outpostlevel
[12/26/2022 21:52:59] zig158
[12/26/2022 21:52:59] NonT
[12/26/2022 21:52:59] MM. Blank
[12/26/2022 21:52:59] Beer
[12/26/2022 21:52:58] Server running slowly (54 updates/s)!
[12/26/2022 21:52:57] zig158
[12/26/2022 21:52:57] NonT
[12/26/2022 21:52:57] MM. Blank
[12/26/2022 21:52:57] Beer
[12/26/2022 21:52:55] zig158
[12/26/2022 21:52:55] NonT
[12/26/2022 21:52:55] MM. Blank
[12/26/2022 21:52:55] Beer
[12/26/2022 21:52:55] zig158
[12/26/2022 21:52:55] NonT
[12/26/2022 21:52:55] MM. Blank
[12/26/2022 21:52:55] Beer
[12/26/2022 21:49:10] zig158
[12/26/2022 21:49:10] NonT
[12/26/2022 21:49:10] MM. Blank
[12/26/2022 21:49:10] Beer
[12/26/2022 21:49:10] zig158
[12/26/2022 21:49:10] NonT
[12/26/2022 21:49:10] MM. Blank
[12/26/2022 21:49:10] Beer
[12/26/2022 21:49:08] zig158
[12/26/2022 21:49:08] NonT
[12/26/2022 21:49:08] MM. Blank
[12/26/2022 21:49:08] Beer
[12/26/2022 21:49:08] zig158
[12/26/2022 21:49:08] NonT
[12/26/2022 21:49:08] MM. Blank
[12/26/2022 21:49:08] Beer
[12/26/2022 21:49:00] zig158
[12/26/2022 21:49:00] NonT
[12/26/2022 21:49:00] MM. Blank
[12/26/2022 21:49:00] Beer
```

**Comment by Regalis11** [comment]
Potentially fixed in https://github.com/Regalis11/Barotrauma-development/commit/729bf6287f07f13a4165aafd5dbee06b5af54bf8, but hard to say for sure considering we have no clear steps to repro the issue and the stack trace is missing the line number the exception was thrown from.

**Comment by Rokvach** [comment]
This is quite common crash in the GA so once this fix is released in Unstable it should be quite easy to tell if this crash still happens or not.

**Comment by Rokvach** [comment]
There hasn't been any sightings of this in GA, considering how common it was previously I would say that this is working correctly. Closing.
