### ISSUE TITLE
Crash when opening game (Could not find the language "Simplified Chinese")

### ISSUE THREAD

**Issue by Doomed9004** [Regalis11/Barotrauma#10859]
### Disclaimers

- [x] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Crash when opening game

### Reproduction steps

![image](https://user-images.githubusercontent.com/101614459/210311024-dc1b3c3e-0158-4bae-b689-d9da57170452.png)

### Bug prevalence
Happens every time l play

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 01/03/2023 14:45:20)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

To prevent further startup errors, installed mods will be disabled the next time you launch the game.

B5C3AB2BBD7769A420A018E6898F0875

Game version 0.20.16.1 (ReleaseWindows, branch release, revision 33a42adf77)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync OFF
Language: English
Selected content packages: Vanilla
Level seed: no level loaded
Loaded submarine: None
Selected screen: None
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit
    GPU name: NVIDIA GeForce RTX 3060 Laptop GPU
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Loading was interrupted due to an error. (Barotrauma.GameMain+LoadingException)
Target site: Void Update(Microsoft.Xna.Framework.GameTime)
Stack trace: 
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 727
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 651
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

InnerException: Object reference not set to an instance of an object.
Target site: Microsoft.Xna.Framework.Vector2 MeasureText(System.String)
Stack trace: 
   at Barotrauma.GUITextBlock.MeasureText(String text) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBlock.cs:line 433
   at Barotrauma.GUITextBlock.MeasureText(LocalizedString text) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBlock.cs:line 424
   at Barotrauma.GUITextBlock.SetTextPos() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBlock.cs:line 367
   at Barotrauma.GUITextBlock.set_Text(RichString value) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBlock.cs:line 101
   at Barotrauma.GUITextBlock..ctor(RectTransform rectT, RichString text, Nullable`1 textColor, GUIFont font, Alignment textAlignment, Boolean wrap, String style, Nullable`1 color) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBlock.cs:line 308
   at Barotrauma.DebugConsole.Init() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\DebugConsole.cs:line 83
   at Barotrauma.GameMain.Load(Boolean isSeparateThread)+MoveNext() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 480
   at Barotrauma.CoroutineManager.PerformCoroutineStep(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 198
   at Barotrauma.CoroutineManager.ExecuteCoroutineThread(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 206
Last debug messages:
[01/03/2023 14:45:20] Coroutine "Load" has failed
[01/03/2023 14:45:20] Coroutine "Load" has thrown an exception {Object reference not set to an instance of an object.}
   at Barotrauma.GUITextBlock.MeasureText(String text) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBlock.cs:line 433
   at Barotrauma.GUITextBlock.MeasureText(LocalizedString text) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBlock.cs:line 424
   at Barotrauma.GUITextBlock.SetTextPos() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBlock.cs:line 367
   at Barotrauma.GUITextBlock.set_Text(RichString value) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBlock.cs:line 101
   at Barotrauma.GUITextBlock..ctor(RectTransform rectT, RichString text, Nullable`1 textColor, GUIFont font, Alignment textAlignment, Boolean wrap, String style, Nullable`1 color) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBlock.cs:line 308
   at Barotrauma.DebugConsole.Init() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\DebugConsole.cs:line 83
   at Barotrauma.GameMain.Load(Boolean isSeparateThread)+MoveNext() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 480
   at Barotrauma.CoroutineManager.PerformCoroutineStep(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 198
   at Barotrauma.CoroutineManager.ExecuteCoroutineThread(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 206
[01/03/2023 14:45:20] Couldn't find a GUI style "GUIFrame"
[01/03/2023 14:45:20] Could not find the language "Simplified Chinese". Trying to switch to English...
[01/03/2023 14:45:20] Switching to default device...
[01/03/2023 14:45:20] ALC device initialization attempt #1 failed: device is null (error code Invalid value)
[01/03/2023 14:45:20] Attempting to open ALC device "<disconnected>"
[01/03/2023 14:45:20] Playback device has been disconnected. You can select another available device in the settings.
[01/03/2023 14:45:19] Attempting to open ALC device "OpenAL Soft on 扬声器 (7.1 Surround Sound)"
[01/03/2023 14:45:17] Logged in as DOOMed (SteamID STEAM_1:0:139940319)
```

**Comment by Regalis11** [comment]
Thank you for the report! The crash report seems to imply there's some files missing from the game folder:
```
[01/03/2023 14:45:20] Couldn't find a GUI style "GUIFrame"
[01/03/2023 14:45:20] Could not find the language "Simplified Chinese". Trying to switch to English...
```

I'd recommend [verifying file integrity](https://www.majorgeeks.com/content/page/validate_steam_cache.html) to ensure all the files are present. Please let us know if that helps!

**Comment by Doomed9004** [comment]
> 感谢您的报告！崩溃报告似乎暗示游戏文件夹中缺少一些文件：
> 
> ```
> [01/03/2023 14:45:20] Couldn't find a GUI style "GUIFrame"
> [01/03/2023 14:45:20] Could not find the language "Simplified Chinese". Trying to switch to English...
> ```
> 
> 我建议验证文件[完整性](https://www.majorgeeks.com/content/page/validate_steam_cache.html)以确保所有文件都存在。如果有帮助，请告诉我们！

The problem is solved, thank you
