### ISSUE TITLE
Changing the audio device when the game starts will cause crash

### ISSUE THREAD

**Issue by AnalogKnight** [Regalis11/Barotrauma#10874]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When the game is starting, changes in audio equipment will cause crash.

This is not a big problem, because few people happen to change their audio device when the game is starting.
But in some cases, this will happen more often. For example, I use Bluetooth headsets, and I sometimes start the game first, and then press my headset power switch. The game will crash at this time.

### Reproduction steps

1.Start the game
2.Wait for the Undertow Games Logo show up
2.Connect or disconnect audio device. For example, switch on Bluetooth headset
3.The game crash

### Bug prevalence

Happens every time I play

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

Barotrauma Client crash report (generated on 01/04/2023 23:44:53)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

To prevent further startup errors, installed mods will be disabled the next time you launch the game.

B5C3AB2BBD7769A420A018E6898F0875

Game version 0.20.16.1 (ReleaseWindows, branch release, revision 33a42adf77)
Graphics mode: 3840x2160 (Fullscreen)
VSync OFF
Language: English
Selected content packages: Vanilla, EuropaWaifu++
Level seed: no level loaded
Loaded submarine: None
Selected screen: None
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.22621.0 64 bit
    GPU name: NVIDIA GeForce RTX 3090
    Display mode: {Width:3840 Height:2160 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Loading was interrupted due to an error. (Barotrauma.GameMain+LoadingException)
Target site: Void Update(Microsoft.Xna.Framework.GameTime)
Stack trace: 
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 727
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

InnerException: Object reference not set to an instance of an object.
Target site: Microsoft.Xna.Framework.Vector2 MeasureText(System.String)
Stack trace: 
   at Barotrauma.GUITextBlock.MeasureText(String text) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBlock.cs:line 433
   at Barotrauma.GUITextBlock.MeasureText(LocalizedString text) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBlock.cs:line 424
   at Barotrauma.GUITextBlock.SetTextPos() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBlock.cs:line 367
   at Barotrauma.GUITextBlock.set_Text(RichString value) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBlock.cs:line 101
   at Barotrauma.GUITextBlock..ctor(RectTransform rectT, RichString text, Nullable`1 textColor, GUIFont font, Alignment textAlignment, Boolean wrap, String style, Nullable`1 color) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBlock.cs:line 308
   at Barotrauma.DebugConsole.Init() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\DebugConsole.cs:line 83
   at Barotrauma.GameMain.Load(Boolean isSeparateThread)+MoveNext() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 480
   at Barotrauma.CoroutineManager.PerformCoroutineStep(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 199
   at Barotrauma.CoroutineManager.ExecuteCoroutineThread(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 206
Last debug messages:
[01/04/2023 23:44:53] Coroutine "Load" has failed
[01/04/2023 23:44:53] Coroutine "Load" has thrown an exception {Object reference not set to an instance of an object.}
   at Barotrauma.GUITextBlock.MeasureText(String text) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBlock.cs:line 433
   at Barotrauma.GUITextBlock.MeasureText(LocalizedString text) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBlock.cs:line 424
   at Barotrauma.GUITextBlock.SetTextPos() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBlock.cs:line 367
   at Barotrauma.GUITextBlock.set_Text(RichString value) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBlock.cs:line 101
   at Barotrauma.GUITextBlock..ctor(RectTransform rectT, RichString text, Nullable`1 textColor, GUIFont font, Alignment textAlignment, Boolean wrap, String style, Nullable`1 color) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBlock.cs:line 308
   at Barotrauma.DebugConsole.Init() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\DebugConsole.cs:line 83
   at Barotrauma.GameMain.Load(Boolean isSeparateThread)+MoveNext() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 480
   at Barotrauma.CoroutineManager.PerformCoroutineStep(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 199
   at Barotrauma.CoroutineManager.ExecuteCoroutineThread(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 206
[01/04/2023 23:44:53] Couldn't find a GUI style "GUIFrame"
[01/04/2023 23:44:53] Could not find the language "Simplified Chinese". Trying to switch to English...
[01/04/2023 23:44:53] Switching to default device...
[01/04/2023 23:44:53] ALC device initialization attempt #1 failed: device is null (error code Invalid value)
[01/04/2023 23:44:53] Attempting to open ALC device "<disconnected>"
[01/04/2023 23:44:53] Playback device has been disconnected. You can select another available device in the settings.
[01/04/2023 23:44:48] Attempting to open ALC device "OpenAL Soft on 耳机 (Surface Headphones)"
[01/04/2023 23:44:46] Logged in as AnalogKnight (SteamID STEAM_1:0:174648424)

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
