### ISSUE TITLE
Crash when trying to make an upgrade increase an integer value

### ISSUE THREAD

**Issue by BiffW** [Regalis11/Barotrauma#10918]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I'm making a mod that allows turrets' "shotsperburst" to be upgraded.
A crash happened when I upgraded the sub and went for a new round.

Use this mod for test.
[Pulse Laser Upgrade.zip](https://github.com/Regalis11/Barotrauma/files/10403748/Pulse.Laser.Upgrade.zip)

### Reproduction steps

1. start a campaign with any attacker sub with a pulse laser (because I limited the upgrade to attacker class)
2. purchase the "Pulse Laser Overload" upgrade
3. go for a new round
4. crash happens

### Bug prevalence

Happens every time I play

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Exception: Unable to cast object of type 'System.Int32' to type 'System.Single'. (System.InvalidCastException)
Target site: System.Object CalculateUpgrade(Int32)
Stack trace: 
   at Barotrauma.PropertyReference.CalculateUpgrade(Int32 level) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Upgrades\Upgrade.cs:line 49
   at Barotrauma.Upgrade.ApplyUpgrade() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Upgrades\Upgrade.cs:line 364
   at Barotrauma.MapEntity.AddUpgrade(Upgrade upgrade, Boolean createNetworkEvent) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\MapEntity.cs:line 358
   at Barotrauma.Item.AddUpgrade(Upgrade upgrade, Boolean createNetworkEvent) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Item.cs:line 982
   at Barotrauma.UpgradeManager.BuyUpgrade(UpgradePrefab prefab, UpgradeCategory category, Submarine submarine, Int32 level, Submarine parentSub) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\UpgradeManager.cs:line 644
   at Barotrauma.UpgradeManager.ApplyUpgrades() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\UpgradeManager.cs:line 499
   at Barotrauma.SinglePlayerCampaign.Start() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameSession\GameModes\SinglePlayerCampaign.cs:line 249
   at Barotrauma.GameSession.InitializeLevel(Level level) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameSession.cs:line 614
   at Barotrauma.GameSession.StartRound(LevelData levelData, Boolean mirrorLevel, SubmarineInfo startOutpost, SubmarineInfo endOutpost) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameSession.cs:line 474
   at Barotrauma.CampaignMode.<>c__DisplayClass34_0.<<SelectSummaryScreen>b__0>d.MoveNext() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameSession\GameModes\CampaignMode.cs:line 257
--- End of stack trace from previous location ---
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 864
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b752bc67941d2cc9fba3df8575dd098c09c7c23e

Note for testing: can also be reproduced by e.g. modifying the vanilla turret upgrades like this:
![image](https://user-images.githubusercontent.com/14351070/212291266-77fc897b-4888-4b31-82d2-b16b84e345b5.png)

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
