### ISSUE TITLE
[Factions] Campaign kicked to lobby and other players have my file directory

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10933]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I want to preface this by saying this could be a one time, unreproducible bug that might never happen again. Regardless, I want to bring this to the surface.

We were playing our testing campaign as normal. Hex, our mechanic, had suffered a crash before and had rejoined (awaiting reconnection to his body in spectator mode). Before he could regain control of his character, however, the end-screen came up and everyone was forcibly returned to the lobby. Nobody triggered this. Only myself and Hex have perms in that server but neither of us triggered the return to lobby. 

What makes the issue more confusing is that, upon clicking "load campaign", Hex had every campaign save I have on my hard drive. The cherry on top is that these files were renamed to the **file directory they belong to, including my computer's name.** Had my computer not been named after my online tag and instead been named after my real name, Hex would've been able to see it. 

I do not know how to reproduce this. I do not know what caused this. I only have the experience and image to show that the issue happened. I can send the save file if needed, as we never got through the level.

![image](https://user-images.githubusercontent.com/105495756/212446536-6cd70e90-882d-402a-a587-c11738b86105.png)

### Bug prevalence

Just once

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed that error in https://github.com/Regalis11/Barotrauma-development/pull/3809, but we still need to look into that save file issue in more detail.

**Comment by Wheatley1001** [comment]
Potentially the same error code appeared in 1.0.0.0.

![image](https://user-images.githubusercontent.com/105495756/218347584-ddc10c40-d621-4f6d-8224-f728653355cd.png)

**Comment by Wheatley1001** [comment]
Issue again in 1.0.2.0.
![image](https://user-images.githubusercontent.com/105495756/221045841-c4e680f5-65f9-4793-ab07-7e5cf3074bc6.png)

**Comment by Wheatley1001** [comment]
Once again in 1.0.4.0:
![image](https://user-images.githubusercontent.com/105495756/222279336-91927890-af54-44ff-b13f-a6d7a106f6f6.png)

**Comment by Krzeszny** [comment]
1.0.7.0
```
Error while reading a message from server. 
Exception thrown while reading segment ChatMessage at position 5611. Previous segments: Segment { Identifier = SyncIds, Pointer = 32 }.
Inner exception: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at Barotrauma.GUICanvas.RefreshChildren() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUICanvas.cs:line 48
   at Barotrauma.CrossThread.RequestExecutionOnMainThread(TaskDelegate deleg) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\CrossThread.cs:line 61
   at Barotrauma.GUIMessageBox..ctor(RichString headerText, RichString text, LocalizedString[] buttons, Nullable`1 relativeSize, Nullable`1 minSize, Alignment textAlignment, Type type, String tag, Sprite icon, String iconStyle, Sprite backgroundIcon, Func`1 autoCloseCondition, Boolean hideCloseButton) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIMessageBox.cs:line 60
   at Barotrauma.Networking.ChatMessage.ClientRead(IReadMessage msg) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\ChatMessage.cs:line 20
   at Barotrauma.Networking.GameClient.<ReadLobbyUpdate>b__114_0(ServerNetSegment segment, IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 2057
   at Barotrauma.Networking.SegmentTableReader`1.Read(IReadMessage msg, SegmentDataReader segmentDataReader, ExceptionHandler exceptionHandler) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SegmentTable.cs:line 296
```
