### ISSUE TITLE
Broken level generation, too many waypoints causing a crash (ID 65532 is taken by Barotrauma.Submarine)

### ISSUE THREAD

**Issue by GreatBlueMoon** [Regalis11/Barotrauma#10944]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Whenever we try to load the game it will NOT let us start the game, after spinelings attacked the game keeps getting the same crash and we're unable to load the save at all, we put so many hours of work into the campaign, jovian radiation on, hardest difficulty yet the game cant be loaded.

### Reproduction steps

Load campaign save
Crash

### Bug prevalence

Happens every time I play

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Coroutine Barotrauma.Networking.GameClient+<StartGame>d__109 threw an exception: ID 65532 is taken by Barotrauma.Submarine (Berilia, 1)
   at Barotrauma.Entity..ctor(Submarine submarine, UInt16 id) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Entity.cs:line 122
   at Barotrauma.MapEntity..ctor(MapEntityPrefab prefab, Submarine submarine, UInt16 id) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\MapEntity.cs:line 252
   at Barotrauma.WayPoint..ctor(Type type, Rectangle newRect, Submarine submarine, UInt16 id) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\WayPoint.cs:line 124
   at Barotrauma.Level.GenerateWaypoints(Tunnel tunnel, Tunnel parentTunnel) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Levels\Level.cs:line 1567
   at Barotrauma.Level.Generate(Boolean mirror, Location startLocation, Location endLocation) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Levels\Level.cs:line 815
   at Barotrauma.Level.Generate(LevelData levelData, Boolean mirror, Location startLocation, Location endLocation, SubmarineInfo startOutpost, SubmarineInfo endOutpost) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Levels\Level.cs:line 466
   at Barotrauma.GameSession.StartRound(LevelData levelData, Boolean mirrorLevel, SubmarineInfo startOutpost, SubmarineInfo endOutpost) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameSession.cs:line 429
   at Barotrauma.Networking.GameClient.StartGame(IReadMessage inc)+MoveNext() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 1510
   at Barotrauma.CoroutineManager.PerformCoroutineStep(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 199
   at Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 257
```

**Comment by GreatBlueMoon** [comment]
> Thank you for the report!
> 
> If you could attach the save file here, it'd most likely help us a lot in diagnosing this (and it might even be possible for us to modify the save file so it can be loaded again). Thanks and sorry for the inconvenience!

i tried to but this site doesnt accept the file type, what do i do?

**Comment by GreatBlueMoon** [comment]
> > Thank you for the report!
> > If you could attach the save file here, it'd most likely help us a lot in diagnosing this (and it might even be possible for us to modify the save file so it can be loaded again). Thanks and sorry for the inconvenience!
> 
> i tried to but this site doesnt accept the file type, what do i do?

please get back soon on this as its urgent, i'd love the possibly of the save file getting edited because a group of people are counting on this working again, we put 7 days of effort into a jovian radiation run on the hardest settings.

**Comment by GreatBlueMoon** [comment]
[Alise4.txt](https://github.com/Regalis11/Barotrauma/files/10429262/Alise4.txt)

this is the best i can do in terms of files since it doesnt accept .save(s), hopefully it doesnt break it

**Comment by Regalis11** [comment]
Thank you! Yeah, I forgot to mention you need to change the file extension or for example .zip the file to attach it here, glad you figured that out!

It seems there's some kind of a level generation issue happening here that causes the game to generate a ridiculous amount of waypoints, making the game run out of possible entity IDs. I was able to fix the save file by changing the seed of that level, here's an updated version of the file: 
[Alise4.zip](https://github.com/Regalis11/Barotrauma/files/10433552/Alise4.zip)

We'll still need to look into what exactly is causing the level generation to fail with the previous seed though, so we'll keep the ticket open.

**Comment by Regalis11** [comment]
Glad it worked! There's no need to close this ticket though, we can keep this ticket open until we've managed to diagnose why the level generation fails and close it ourselves when we've managed to fix the issue.

**Comment by GreatBlueMoon** [comment]
![image](https://user-images.githubusercontent.com/105438570/213025256-326d1fce-ed12-4ff6-82a8-bf668504e7af.png)

We beat the game.

(i finally think i know what caused this problem, at the time of the perma non-load, i remembered a pirate submarine mission was selected, spinelings sunk us to crush depth, and a giant spineling was there too, but, it didn't "crash", we exited to server lobby to restart, but then never could load the game again until you fixed it.)

**Comment by GreatBlueMoon** [comment]
> ![image](https://user-images.githubusercontent.com/105438570/213025256-326d1fce-ed12-4ff6-82a8-bf668504e7af.png)
> 
> We beat the game.
> 
> (i finally think i know what caused this problem, at the time of the perma non-load, i remembered a pirate submarine mission was selected, spinelings sunk us to crush depth, and a giant spineling was there too, but, it didn't "crash", we exited to server lobby to restart, but then never could load the game again until you fixed it.)

in response to this, i think the waypointing problem is with the missions + the bots and the pirates and spinelings making their own navigation choices all at once.

**Comment by GreatBlueMoon** [comment]
[Alise4.txt](https://github.com/Regalis11/Barotrauma/files/10439859/Alise4.txt)

if you'd like to diagnose the game save as its completely finished and beaten, for more research or something, here you go, incase it helps.

**Comment by Regalis11** [comment]
Seems like this no longer occurs in the latest version of the game, closing
