### ISSUE TITLE
Server crash on restart

### ISSUE THREAD

**Issue by kanoriano** [Regalis11/Barotrauma#10955]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

every time when im type "exit" to cli, or restart dedicated server

at now i have 9 same servercrashreport.log

Example:
```
Barotrauma Dedicated Server crash report (generated on 01/16/2023 20:43:19)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


Game version 0.20.16.1 (ReleaseWindows, branch release, revision 33a42adf77)
Language: English
Selected content packages: Vanilla
Level seed: no level loaded
Loaded submarine: None
Selected screen: Barotrauma.NetLobbyScreen
Server (Round hadn't been started)


System info:
    Operating system: Microsoft Windows NT 6.1.7601 Service Pack 1 64 bit


Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void Quit()
Stack trace: 
   at Barotrauma.Networking.GameServer.Quit() in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Networking\GameServer.cs:line 3955
   at Barotrauma.GameMain.CloseServer() in <DEV>\Barotrauma\BarotraumaServer\ServerSource\GameMain.cs:line 278
   at Barotrauma.GameMain.Run() in <DEV>\Barotrauma\BarotraumaServer\ServerSource\GameMain.cs:line 386
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Program.cs:line 78


Last debug messages:
   01/16/2023 20:43:19 - [01/16/2023 20:43:19]
  Saving banlist
   01/16/2023 20:43:19 - [01/16/2023 20:43:19]
  Saving banlist
   01/16/2023 20:43:19 - exit
   01/16/2023 20:43:16 - ***************
   01/16/2023 20:43:16 - ***************
   01/16/2023 20:43:16 - clientlist
   01/16/2023 19:51:15 - [01/16/2023 19:51:15]
  Mad2001 has left the server.
   01/16/2023 19:50:20 - [01/16/2023 19:50:20]
  Saving client permissions
   01/16/2023 19:50:20 - [01/16/2023 19:50:20]
  Mad2001 has joined the server.
   01/16/2023 19:41:57 - WARNING: Running slowly (55 updates/s)!
   01/16/2023 19:41:56 - [01/16/2023 19:41:56]
  Round ended.
   01/16/2023 19:41:53 - [01/16/2023 19:41:53]
  Ending the round...
   01/16/2023 19:41:53 - [01/16/2023 19:41:53]
  Ending round (no living players left)
   01/16/2023 19:41:51 - [01/16/2023 19:41:51]
  Avery has left the server.

```

### Reproduction steps

1.Start dedicated server
2. Type "exit" when loaded

### Bug prevalence

Happens every now and then

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

This seems to happen when mod downloads are disabled. Can be reproduced simply by setting AllowModDownloads to false in serversettings.xml, starting up a dedicated server and quitting.

Fixed in https://github.com/Regalis11/Barotrauma-development/commit/63c7ec00d1a0b19317fcce071f53c7e302887ccd (commit in our private repo)

**Comment by kanoriano** [comment]
yes, AllowModDownloads="True" fix it

**Comment by NilanthAnimosus** [comment]
Tested against Fix/Bugfixes-2 commit https://github.com/Regalis11/Barotrauma-development/commit/97e99c225a92460269a4fc0937de649b36f450cb, no issues found, closing.
