### ISSUE TITLE
Buying sub upgrades with materials can crash the game

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#10967]
@JeroonBosch commented on [Wed Jan 18 2023](https://github.com/Regalis11/Barotrauma-development/issues/3876)

Spotted on the feature/wip branch, might also be on dev

**Steps to reproduce:**
1. Host a new game. I used a new multiplayer campaign with a Winterhalter (at least tier 2 sub needed)
2. Use `spawnitem Steel inventory 10` command to get Steel for the first upgrades
3. Buy the first two hull upgrades. Notice steel dropping on the floor. The steel cannot be interacted with
![image](https://user-images.githubusercontent.com/8641689/213200569-b05f3de3-d594-4539-ac04-fce3362ebdcc.png)
4. Use `spawnitem "Titanium-Steel Alloy" inventory 10` command
5. The spawnitem command crashes the game.

```
Failed to spawn item Titanium-Aluminum Alloy {ID 2939 is taken by Steel Bar (ID: 2939)}
   at Barotrauma.Entity..ctor(Submarine submarine, UInt16 id) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Entity.cs:line 93
   at Barotrauma.MapEntity..ctor(MapEntityPrefab prefab, Submarine submarine, UInt16 id) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\MapEntity.cs:line 249
   at Barotrauma.Item..ctor(Rectangle newRect, ItemPrefab itemPrefab, Submarine submarine, Boolean callOnItemLoaded, UInt16 id) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 891
   at Barotrauma.Item..ctor(ItemPrefab itemPrefab, Vector2 position, Submarine submarine, UInt16 id, Boolean callOnItemLoaded) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 876
   at Barotrauma.Item.ReadSpawnData(IReadMessage msg, Boolean spawn) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Item.cs:line 1773
Error while reading a message from server. 
Exception thrown while reading segment EntityEvent at position 16.
Inner exception: ID 2939 is taken by Steel Bar (ID: 2939)
   at Barotrauma.Entity..ctor(Submarine submarine, UInt16 id) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Entity.cs:line 93
   at Barotrauma.MapEntity..ctor(MapEntityPrefab prefab, Submarine submarine, UInt16 id) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\MapEntity.cs:line 249
   at Barotrauma.Item..ctor(Rectangle newRect, ItemPrefab itemPrefab, Submarine submarine, Boolean callOnItemLoaded, UInt16 id) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 891
   at Barotrauma.Item..ctor(ItemPrefab itemPrefab, Vector2 position, Submarine submarine, UInt16 id, Boolean callOnItemLoaded) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 876
   at Barotrauma.Item.ReadSpawnData(IReadMessage msg, Boolean spawn) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Item.cs:line 1773
   at Barotrauma.EntitySpawner.ClientEventRead(IReadMessage message, Single sendingTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\EntitySpawner.cs:line 39
   at Barotrauma.Networking.ClientEntityEventManager.ReadEvent(IReadMessage buffer, IServerSerializable entity, Single sendingTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\NetEntityEvent\ClientEntityEventManager.cs:line 251
   at Barotrauma.Networking.ClientEntityEventManager.Read(ServerNetSegment type, IReadMessage msg, Single sendingTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\NetEntityEvent\ClientEntityEventManager.cs:line 220
   at Barotrauma.Networking.GameClient.<>c__DisplayClass117_0.<ReadIngameUpdate>b__0(ServerNetSegment segment, IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 2139
   at Barotrauma.Networking.SegmentTableReader`1.Read(IReadMessage msg, SegmentDataReader segmentDataReader, ExceptionHandler exceptionHandler) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SegmentTable.cs:line 302
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/pull/3879/commits/85d7d86dd93027d5b98e820bc7be917a1e8dac5a

**Comment by Rokvach** [comment]
Tested, I wasn't able to reproduce the issue. Working correctly, can be merged and closed.
