### ISSUE TITLE
Crash when player equip a modded assault rifle with riot shield attached

### ISSUE THREAD

**Issue by BiffW** [Regalis11/Barotrauma#11026]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I'm trying to make a mod that allow players to attach a shield to their assault rifle.
When I equip the modded assault rifle with the riot shield attached, game crashes. 

[Shield Rifle Test.zip](https://github.com/Regalis11/Barotrauma/files/10496328/Shield.Rifle.Test.zip)

### Reproduction steps

1. enable "Shield Rifle Test" in mod list
2. in sub editor, spawn a "Test Rifle" and a riot shield
3. pick up the rifle and place the riot shield into its container
4. equip the rifle
5. crash occur

### Bug prevalence

Happens every time I play

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void Update(Single, Barotrauma.Camera)
Stack trace: 
   at Barotrauma.Items.Components.Wearable.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Wearable.cs:line 528
   at Barotrauma.Item.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 1961
   at Barotrauma.MapEntity.UpdateAll(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\MapEntity.cs:line 600
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 254
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 878
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/bfcb1810f910e777c65c56bea80e9920046647ac

**Comment by Rokvach** [comment]
Tested, didn't encounter a crash, can be merged and closed.
