### ISSUE TITLE
Game crashed with "blend state is already bound" message.

### ISSUE THREAD

**Issue by Tyelzor** [Regalis11/Barotrauma#11045]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Was trying to swim out to harpoon a swarm mother and the game crashed while opening the airlock.

### Bug prevalence

Just once

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 01/27/2023 21:17:04)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

B5C3AB2BBD7769A420A018E6898F0875

Game version 0.20.16.1 (ReleaseWindows, branch release, revision 33a42adf77)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla
Level seed: WolstoneTormsdale Linea
Loaded submarine: Dugong (B297B649E8B6FE9E2F37775EB3FDE42C)
Selected screen: Barotrauma.GameScreen
SteamManager initialized
Client (Round had started)

System info:
    Operating system: Microsoft Windows NT 10.0.22621.0 64 bit
    GPU name: AMD Radeon RX 5700 XT
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: This blend state is already bound to a different graphics device. (System.InvalidOperationException)
Target site: Void BindToGraphicsDevice(Microsoft.Xna.Framework.Graphics.GraphicsDevice)
Stack trace: 
   at Microsoft.Xna.Framework.Graphics.BlendState.BindToGraphicsDevice(GraphicsDevice device) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\States\BlendState.cs:line 26
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.set_BlendState(BlendState value) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\GraphicsDevice.cs:line 405
   at Barotrauma.GameScreen.DrawMap(GraphicsDevice graphics, SpriteBatch spriteBatch, Double deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\GameScreen.cs:line 379
   at Barotrauma.GameScreen.Draw(Double deltaTime, GraphicsDevice graphics, SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\GameScreen.cs:line 129
   at Barotrauma.GameMain.Draw(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 967
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 669
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 508
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[01/27/2023 21:16:54] WARNING: Received a potentially invalid ENTITY_POSITION message.Entity identifier does not match (server entity is smallcrawleregg, client entity is coilgunbolt). Ignoring the message...
[01/27/2023 21:14:28] WARNING: Received a potentially invalid ENTITY_POSITION message.Entity identifier does not match (server entity is smallcrawleregg, client entity is coilgunbolt). Ignoring the message...
[01/27/2023 21:05:44] Hugycsøvibri
[01/27/2023 21:05:44] Of_Fortune
[01/27/2023 21:05:37] Hugycsøvibri
[01/27/2023 21:05:37] Of_Fortune
[01/27/2023 21:05:36] Received STARTGAMEFINALIZE packet. Round init status: Started
[01/27/2023 21:05:35]  -0: EstimateSteamLobbyPing (STEAM_1:0:5559509), WaitingForActivation
[01/27/2023 21:05:35] Task count: 1
[01/27/2023 21:05:35] Received STARTGAMEFINALIZE packet. Round init status: WaitingForStartGameFinalize
[01/27/2023 21:05:33] Generating an outpost for the end of the level... (Location: Tormsdale Linea Outpost, level type: LocationConnection)
[01/27/2023 21:05:32] Generating an outpost for the start of the level... (Location: Wolstone Habitation Outpost, level type: LocationConnection)
[01/27/2023 21:05:32] Level identifier: coldcavernsadvanced
[01/27/2023 21:05:27] Hugycsøvibri
[01/27/2023 21:05:27] Of_Fortune
[01/27/2023 21:05:26] Hugycsøvibri
[01/27/2023 21:05:26] Of_Fortune
[01/27/2023 21:05:25] Hugycsøvibri
[01/27/2023 21:05:25] Of_Fortune
[01/27/2023 20:53:20] Hugycsøvibri
[01/27/2023 20:53:20] Of_Fortune
[01/27/2023 20:53:14] Received STARTGAMEFINALIZE packet. Round init status: Started
[01/27/2023 20:53:14] Received STARTGAMEFINALIZE packet. Round init status: Started
[01/27/2023 20:53:14] Received STARTGAMEFINALIZE packet. Round init status: Started
[01/27/2023 20:53:14] Received STARTGAMEFINALIZE packet. Round init status: Started
[01/27/2023 20:53:14]  -0: EstimateSteamLobbyPing (STEAM_1:0:5559509), WaitingForActivation
[01/27/2023 20:53:14] Task count: 1
[01/27/2023 20:53:14] Received STARTGAMEFINALIZE packet. Round init status: WaitingForStartGameFinalize
[01/27/2023 20:53:03] Generating an outpost for the start of the level... (Location: Wolstone Habitation Outpost, level type: Outpost)
[01/27/2023 20:53:03] Level identifier: outpostlevel
[01/27/2023 20:50:19] Attempting to open ALC device "OpenAL Soft on Headset Earphone (Sennheiser Communication Audio)"
[01/27/2023 20:50:14] Logged in as Hugycsøvibri (SteamID STEAM_1:1:39705208)
```

**Comment by Regalis11** [comment]
Thank you for the report!

Looking at the error message, I think this could be caused by the GPU resetting or temporarily disconnecting somehow. I'm afraid without further information it might not be possible for us to diagnose the issue - but if this was a one-off crash with no clear cause or a way to get it to happen again, I'm not sure what other information there could be that you can give us. :/ In any case, I'm sorry for the inconvenience, and I hope this was indeed a one-off crash and that you won't run into it again.

**Comment by Tyelzor** [comment]
Dear Regalis,

Thank you very much for you feedback, I will double check the cables to make sure everything is connected properly. Fortunately this was a one-time issue so far and the game is pretty awesome to play with friends especially since we don't know what we're doing.
Thanks again and keep up the great work.
