### ISSUE TITLE
[Factions] Unable to spectate (CancellationToken.ThrowOperationCanceledException, operation was canceled)

### ISSUE THREAD

**Issue by AtobaAzul** [Regalis11/Barotrauma#11046]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Attempting to spectate results in an error.

https://user-images.githubusercontent.com/94794129/215204388-3a1a4221-4c82-4318-ace7-6a0a8cddea2d.mp4

### Reproduction steps

1. Join a server, click Spectate

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Coroutine Barotrauma.Networking.GameClient+<StartGame>d__109 threw an exception: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Barotrauma.MapEntity.LoadAll(Submarine submarine, XElement parentElement, String filePath, Int32 idOffset) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\MapEntity.cs:line 653
   at Barotrauma.Submarine..ctor(SubmarineInfo info, Boolean showErrorMessages, Func`2 loadEntities, IdRemap linkedRemap) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Submarine.cs:line 1398
   at Barotrauma.GameSession.StartRound(LevelData levelData, Boolean mirrorLevel, SubmarineInfo startOutpost, SubmarineInfo endOutpost) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameSession.cs:line 422
   at Barotrauma.Networking.GameClient.StartGame(IReadMessage inc)+MoveNext() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 1510
   at Barotrauma.CoroutineManager.PerformCoroutineStep(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 199
   at Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 257
```

**Comment by Wheatley1001** [comment]
During the test session, we had several player error logs which prevented players from connecting to the game mid-round. I'm unsure if they all tie into this ticket or if they need their own individual tickets, but regardless of how they're handled they all caused the same thing: prevented players from joining an ongoing session.

![image](https://user-images.githubusercontent.com/105495756/215241444-62b394da-ad9e-4ebd-8b78-a9f2f047bcd3.png)
![image](https://user-images.githubusercontent.com/105495756/215241497-c7a88d64-5f7c-49d4-807e-1bf02de84db2.png)
![image](https://user-images.githubusercontent.com/105495756/215241709-d68cc1d6-24ed-455c-93ce-f3b5e43f717e.png)

**Comment by Regalis11** [comment]
Internal note, here's one way to reproduce this reliably:
1. Start a multiplayer campaign
2. Leave from the outpost: this will make the game start a round asynchronously, instantiating a start round cancellation token
3. After the round has started, quit to main menu. This will cancel the token.
4. Start any kind of new round (single player, test mode, multiplayer) - the exception will be thrown, because the same cancellation token is checked while loading a sub.

**Comment by NilanthAnimosus** [comment]
Tested against Fix/startround-cancellation-fix commit https://github.com/Regalis11/Barotrauma-development/commit/bcd762a819aa0242ea069a8777255bb95a03eb0f, no issues found, ready for merging
