### ISSUE TITLE
[Factions] Exception: Object reference not set to an instance of an object in Character.Update

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11056]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Possibly related to #10876.

### Issue Report
At first I thought this was a duplicate issue of the ticket mentioned above, but that ticket ended in .Character whilst this one ends with .Camera so I thought a new ticket was worth making. 
I came across this crash when attempting to test another bug before reporting it (relating to Thermal Goggles not working on specific characters, more on that if I manage to test it though). I repeated the issue again to make sure it wasn't a one time thing, and it's easily done. Steps are detailed below.

### Reproduction steps

1. Open sub editor
2. Select Winterhalter
3. Enter the following commands into the console:
disableenemyai
spawnitem "thermal goggles" inventory
los
spawn crawler cursor
4. Press F3
5. Observe how the game crashes

### Bug prevalence

Happens regularly

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 01/28/2023 03:07:52)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

C5AD892CF0B3D80A1402312411620C68

Game version 100.17.0.0 (UnstableWindows, branch feature/fullrelease-testing, revision cb10ee63e3)
Graphics mode: 2560x1440 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla, Fury, LETOHSS, Rex Malleus-Caput, SS HOTEL V.2, STVR, The Honked Mother, Typhon3, RVTS-Class, Sirens Violin, Sailor 4, The Schism, Mazara, Tadpole Trader, Medusa, [RH] Barrisk Campaign, [RH] Bivot Tier 3 Campaign
Level seed: no level loaded
Loaded submarine: Winterhalter (8DBD6E97C778C6852D65E6C9B3D889B3)
Selected screen: Barotrauma.GameScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19045.0 64 bit
    GPU name: NVIDIA GeForce RTX 2070
    Display mode: {Width:2560 Height:1440 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void Update(Single, Barotrauma.Camera)
Stack trace: 
   at Barotrauma.Character.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 3132
   at Barotrauma.AICharacter.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AICharacter.cs:line 72
   at Barotrauma.Character.UpdateAll(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 3016
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 192
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 883
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[01/28/2023 03:07:51] spawn crawler cursor
[01/28/2023 03:07:46] spawn "tiger thresher" cursor
[01/28/2023 03:07:37] spawn Tiger_Thresher cursor
[01/28/2023 03:07:33] Line of sight effect disabled
[01/28/2023 03:07:33] los
[01/28/2023 03:07:28] spawn Tiger_Thresher cursor
[01/28/2023 03:07:15] spawnitem "thermal goggles" inventory
[01/28/2023 03:05:29] Enemy AI disabled
[01/28/2023 03:05:29] disableenemyai
[01/28/2023 03:03:05] Attempting to open ALC device "OpenAL Soft on Speakers (Focusrite Usb Audio)"
[01/28/2023 03:02:58] Logged in as Wheatley1001 (SteamID STEAM_1:0:52539082)
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/198acc04ff62f28219aef824d5de607a3f0f7519

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
