### ISSUE TITLE
[Factions] Issues after completing the game in multiplayer

### ISSUE THREAD

**Issue by HawkinsThe71st** [Regalis11/Barotrauma#11081]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

After finishing the campaign and returning to main menu once the server closed I was unable to start the tutorial, a new game, host a multiplayer campaign or load any submarine in the sub editor and attempting to open the character editor seems to crash the game.
![image](https://user-images.githubusercontent.com/115734437/215291928-23e80374-32d1-4d1b-a714-f72d03b93af5.png)

### Bug prevalence

Just once

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Failed to load the submarine. The submarine file might be corrupted. {The operation was canceled.}
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Barotrauma.MapEntity.LoadAll(Submarine submarine, XElement parentElement, String filePath, Int32 idOffset) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\MapEntity.cs:line 653
   at Barotrauma.Submarine..ctor(SubmarineInfo info, Boolean showErrorMessages, Func`2 loadEntities, IdRemap linkedRemap) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Submarine.cs:line 1398
   at Barotrauma.SubEditorScreen.LoadSub(SubmarineInfo info) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\SubEditorScreen.cs:line 3548
Attempting to remove an already removed character
   at System.Environment.get_StackTrace()
   at Barotrauma.Character.Remove() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 4594
   at Barotrauma.SubEditorScreen.DeselectEditorSpecific() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\SubEditorScreen.cs:line 1586
   at Barotrauma.EditorScreen.Deselect() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\EditorScreen.cs:line 12
   at Barotrauma.Screen.Select() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\Screen.cs:line 20
   at Barotrauma.MainMenuScreen.Select() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\MainMenuScreen.cs:line 560
   at Barotrauma.GameMain.QuitToMainMenu(Boolean save) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 1118
   at Barotrauma.GUI.<>c.<TogglePauseMenu>b__179_4() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 2513
   at Barotrauma.GUI.<>c__DisplayClass179_1.<TogglePauseMenu>b__16(GUIButton _, Object __) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 2554
   at Barotrauma.GUIButton.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIButton.cs:line 263
   at Barotrauma.GUI.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1246
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 908
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 651
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58
Coroutine Barotrauma.SinglePlayerCampaign+<DoLoadInitialLevel>d__27 threw an exception: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Barotrauma.MapEntity.LoadAll(Submarine submarine, XElement parentElement, String filePath, Int32 idOffset) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\MapEntity.cs:line 653
   at Barotrauma.Submarine..ctor(SubmarineInfo info, Boolean showErrorMessages, Func`2 loadEntities, IdRemap linkedRemap) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Submarine.cs:line 1398
   at Barotrauma.GameSession.StartRound(LevelData levelData, Boolean mirrorLevel, SubmarineInfo startOutpost, SubmarineInfo endOutpost) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameSession.cs:line 422
   at Barotrauma.SinglePlayerCampaign.DoLoadInitialLevel(LevelData level, Boolean mirror)+MoveNext() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameSession\GameModes\SinglePlayerCampaign.cs:line 280
   at Barotrauma.CoroutineManager.PerformCoroutineStep(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 199
   at Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 257
dumptexts
Couldn't load xml document "Content/Texts/EnglishVanilla.xml"! {Could not find file 'C:\Program Files (x86)\Steam\steamapps\common\Barotrauma\Content\Texts\EnglishVanilla.xml'.}
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at Barotrauma.IO.File.Open(String path, FileMode mode, FileAccess access, Nullable`1 share) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SafeIO.cs:line 400
   at Barotrauma.XMLExtensions.TryLoadXml(String filePath, Exception& exception) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Serialization\XMLExtensions.cs:line 109
```

**Comment by Regalis11** [comment]
Based on the error message, this seems to be caused by the same issue as https://github.com/Regalis11/Barotrauma/issues/11046
