### ISSUE TITLE
Failed to create graphics device

### ISSUE THREAD

**Issue by beucismis** [Regalis11/Barotrauma#11117]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

It crashes when trying to launch the game on Steam.

### Bug prevalence

Just once

### Version

0.21.6.0

### -

Linux on Wayland

### Which operating system did you encounter this bug on?

Linux

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 02/01/2023 15:14:36)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

6DC8C3543ABBD764A08538983E924E0F

Game version 0.21.6.0 (ReleaseLinux, branch release, revision 480a2279e0)
Graphics mode: 0x0 (Windowed)
VSync OFF
Language: 
Selected content packages: None
Level seed: no level loaded
Loaded submarine: None
Selected screen: None
SteamManager initialized

System info:
    Operating system: Unix 6.1.0.2 64 bit
    Game not initialized

Exception: Failed to create graphics device! (Microsoft.Xna.Framework.Graphics.NoSuitableGraphicsDeviceException)
Target site: Void CreateDevice()
Stack trace: 
   at Microsoft.Xna.Framework.GraphicsDeviceManager.CreateDevice() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\GraphicsDeviceManager.cs:line 122
   at Microsoft.Xna.Framework.GraphicsDeviceManager.ApplyChanges() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\GraphicsDeviceManager.cs:line 303
   at Barotrauma.GameMain..ctor(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 223
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 57

InnerException: Object reference not set to an instance of an object.
Target site: System.String GetString(MonoGame.OpenGL.StringName)
Stack trace: 
   at MonoGame.OpenGL.GL.GetString(StringName name) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\OpenGL.cs:line 1384
   at MonoGame.OpenGL.GL.LoadExtensions() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\OpenGL.cs:line 1303
   at MonoGame.OpenGL.GL.LoadEntryPoints() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\OpenGL.cs:line 1285
   at MonoGame.OpenGL.GraphicsContext..ctor(IWindowInfo info) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\GraphicsContext.SDL.cs:line 49
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformSetup() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\GraphicsDevice.OpenGL.cs:line 249
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.Setup() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\GraphicsDevice.cs:line 247
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice..ctor(GraphicsAdapter adapter, GraphicsProfile graphicsProfile, PresentationParameters presentationParameters) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\GraphicsDevice.cs:line 223
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice..ctor(GraphicsDeviceInformation gdi) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\GraphicsDevice.cs:line 189
   at Microsoft.Xna.Framework.GraphicsDeviceManager.CreateDevice(GraphicsDeviceInformation gdi) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\GraphicsDeviceManager.cs:line 131
   at Microsoft.Xna.Framework.GraphicsDeviceManager.CreateDevice() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\GraphicsDeviceManager.cs:line 114
```
```

**Comment by Regalis11** [comment]
Thank you for the report!

This seems like it could potentially be a driver issue of some sort. Which GPU do you have? Are you using some kind of 3rd-party open source drivers perhaps?

**Comment by beucismis** [comment]
Hi, this is my graphics driver:

```
Graphics:
  Device-1: Intel Mobile GM965/GL960 Integrated Graphics driver: i915
    v: kernel
  Display: wayland server: X.org v: 1.21.1.6 with: Xwayland v: 22.1.7
    compositor: sway v: 1.7 driver: X: loaded: modesetting unloaded: fbdev,vesa
    dri: crocus gpu: i915 resolution: 1280x800~60Hz
  API: OpenGL v: 2.1 Mesa 22.3.4 renderer: Mesa Intel 965GM (CL)
```

**Comment by beucismis** [comment]
Starting with `SDL_VIDEODRIVER=x11` was a temporary solution for me.

**Comment by Regalis11** [comment]
Thank you for the extra info! Unfortunately the GPU you're using does not meet the game's minimum requirements; it seems like the issue might have something to do with the Wayland support on the GPU. I'm glad you were able to find a workaround though!
