### ISSUE TITLE
Gene mods cause crashes (item variants cause crashes if the base item can't be found)

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#11127]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

There doesn't seem to be proper error checking in place for situations where the base item an item variant is supposed to inherit cannot be found. Instead, the game just creates a (very broken) ItemPrefab from the variant XML, leading to various issues.

This seems to have been causing a bunch of mystery crashes in v0.21.6.0 in which we removed some of the genetic material prefabs (see https://github.com/Regalis11/Barotrauma/issues/10958).

### Reproduction steps

1. Add something like this to some item xml file:
`<Item name="" identifier="geneticmaterialbroken" variantof="thisdoesntexist"/>`
2. Launch the game, notice there's no error messages
3. Place a fabricator in the sub editor, crash

There are probably lots of different places where these crashes can occur, but fabricators seem to be the most common trigger.

### Bug prevalence

Happens every now and then

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
[MODDED] Error while loading entity of the type Barotrauma.Items.Components.Fabricator (System.NullReferenceException: Object reference not set to an instance of an object.
   at Barotrauma.Items.Components.Fabricator..ctor(Item item, ContentXElement element) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Machines\Fabricator.cs:line 108)
   at System.Environment.get_StackTrace()
   at Barotrauma.Items.Components.ItemComponent.Load(ContentXElement element, Item item, Boolean errorMessages) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\ItemComponent.cs:line 962
   at Barotrauma.Item..ctor(Rectangle newRect, ItemPrefab itemPrefab, Submarine submarine, Boolean callOnItemLoaded, UInt16 id) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 998
   at Barotrauma.Item.Load(ContentXElement element, Submarine submarine, Boolean createNetworkEvent, IdRemap idRemap) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 3273
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Barotrauma.MapEntity.LoadAll(Submarine submarine, XElement parentElement, String filePath, Int32 idOffset) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\MapEntity.cs:line 698
   at Barotrauma.Submarine..ctor(SubmarineInfo info, Boolean showErrorMessages, Func`2 loadEntities, IdRemap linkedRemap) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Submarine.cs:line 1341
```

**Comment by Regalis11** [comment]
Implemented a fix in https://github.com/Regalis11/Barotrauma-development/commit/3b5d8d14bfae613ddf6e8a96314a0c35faa6ec52. Testing instructions:

1. Add something like this to some item xml file: <Item name="" identifier="geneticmaterialbroken" variantof="thisdoesntexist"/>
2. Launch the game: there should be a console error about the item
3. Place a fabricator in the sub editor or try to spawn the item. This should no longer crash the game, it should just appear like the broken item doesn't exist at all.
4. Try creating a mod that fixes the item by implementing the missing base item. The item should start working again when enabling the mod. Here's an example mod that implements the "thisdoesntexist" item prefab:
[GeneFix.zip](https://github.com/Regalis11/Barotrauma/files/10685969/GeneFix.zip)

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
