### ISSUE TITLE
Crash after treating crew with medical service at outpost

### ISSUE THREAD

**Issue by BiffW** [Regalis11/Barotrauma#11126]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Game crash after treating crew with medical service at outpost

### Reproduction steps

1. Start a singleplayer campaign (set tutorial off so you can have access to medical service)
2. Enable cheats and give your crew some affliction
3. Go to the outpost doctor for medical service
4. Treat all your crewmates
5. Game crash

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void ClientSend(Barotrauma.INetSerializableStruct, NetworkHeader, Barotrauma.Networking.DeliveryMethod)
Stack trace: 
   at Barotrauma.MedicalClinic.ClientSend(INetSerializableStruct netStruct, NetworkHeader header, DeliveryMethod deliveryMethod) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameSession\MedicalClinic.cs:line 339
   at Barotrauma.MedicalClinic.SendUnsubscribeRequest() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameSession\MedicalClinic.cs:line 323
   at Barotrauma.MedicalClinicUI.OnDeselected() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\MedicalClinicUI.cs:line 1144
   at Barotrauma.CampaignMode.set_ShowCampaignUI(Boolean value) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameSession\GameModes\CampaignMode.cs:line 73
   at Barotrauma.SinglePlayerCampaign.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameSession\GameModes\SinglePlayerCampaign.cs:line 507
   at Barotrauma.GameSession.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameSession.cs:line 769
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 144
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 881
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/pull/3932/commits/4d61b1fce92d5244d5434e9cb9501de2d3806d9f
