### ISSUE TITLE
CTD when saving to a deleted folder

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#11145]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

trying to save an item assembly but game crashed

### Reproduction steps

1. save an item assembly (i.e., BOB)
2. delete the new BOB folder in /localmods
3. save an item assembly w/ same name BOB
4. 

### Bug prevalence

Happens regularly

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 02/03/2023 13:08:00)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

18B4B1F1463515508F0783BBFA6953EC

Game version 0.21.6.0 (ReleaseWindows, branch release, revision 480a2279e0)
Graphics mode: 2560x1440 (BorderlessWindowed)
VSync OFF
Language: English
Selected content packages: Vanilla, Scorpio 9, Better Sit-com house, War Nova, Flounder (PvP), Pear [pvp], [F.G.L.] Ana Mk. 1 (PvP), Humpback [Military] XMAS 2022, Humpback [Military], Humpback [Military] 2.2.1, Better Sit-com house for  Xmas, Minotaur Gunship, An Apple a Day, Mooncrusher, astraltor's campaign sub, Custom Icons, More Alarm Sounds, Kendris' Wrecks, Higher Shipwreck Count, Reprieve-Class Hospital Ship (Goph Original Ship), Better Camera Swapping, Upgrades For All, edge detector binary rising
Level seed: no level loaded
Loaded submarine: astraltor's campaign sub (46557F874E22B17295C112DA86149F5A)
Selected screen: Barotrauma.SubEditorScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19045.0 64 bit
    GPU name: NVIDIA GeForce GTX 1050 Ti
    Display mode: {Width:2560 Height:1440 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Could not find a part of the path 'D:\Programs\SteamLibrary\steamapps\common\Barotrauma\LocalMods\Edge Detector Binary Rising\Edge Detector Binary Rising.xml'. (System.IO.DirectoryNotFoundException)
Target site: Microsoft.Win32.SafeHandles.SafeFileHandle CreateFile(System.String, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare, System.IO.FileOptions)
Stack trace: 
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
   at System.Xml.XmlWriterSettings.CreateWriter(String outputFileName)
   at System.Xml.XmlWriter.Create(String outputFileName, XmlWriterSettings settings)
   at System.Xml.Linq.XDocument.Save(String fileName, SaveOptions options)
   at Barotrauma.IO.SafeXML.SaveSafe(XDocument doc, String path, SaveOptions saveOptions, Boolean throwExceptions) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SafeIO.cs:line 116
   at Barotrauma.SubEditorScreen.<>c__DisplayClass131_0.<SaveAssembly>g__Save|0() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\SubEditorScreen.cs:line 3084
   at Barotrauma.SubEditorScreen.SaveAssembly(GUIButton button, Object obj) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\SubEditorScreen.cs:line 3067
   at Barotrauma.GUIButton.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIButton.cs:line 263
   at Barotrauma.GUI.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1259
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 907
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[02/03/2023 12:47:36] Attempting to open ALC device "OpenAL Soft on Realtek HD Audio 2nd output (Realtek(R) Audio)"
[02/03/2023 12:47:28] Logged in as Lightning (SteamID STEAM_1:0:41823064)
```

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/c911a018864d06295e4074e84992bf86083913b1 by making this a console warning instead

**Comment by Rokvach** [comment]
Tested on steam Faction build by following the repro steps, the game still closes but doesn't create a crashreport

Re-tested on dev and received this
![image](https://user-images.githubusercontent.com/7299826/218414521-db517c30-87f9-470e-bcfd-a5b49f8a4095.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f3b2e4511f3627875713a5b329cd892965587d91

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
