### ISSUE TITLE
[Faction/Endgame] Tormsdale Report Mission can be interrupted if the location it is located in turns into abandoned

### ISSUE THREAD

**Issue by BiffW** [Regalis11/Barotrauma#11201]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I unlocked Tormsdale Report mission.
The mission is 3 steps away in a coalition outpost.
On the way to the mission location are 2 abyss missions.
I defeated one and reached the next empty node.
When the campaign map opens automatically, the game crashes.
I reloaded the save and found the mission location abandoned.

### Bug prevalence

Just once

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void <CreateLocationInfoOverlay>b__4(Microsoft.Xna.Framework.Graphics.SpriteBatch, Barotrauma.GUICustomComponent)
Stack trace: 
   at Barotrauma.Map.<>c__DisplayClass28_0.<CreateLocationInfoOverlay>b__4(SpriteBatch sb, GUICustomComponent component) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Map\Map\Map.cs:line 463
   at Barotrauma.GUICustomComponent.Draw(SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUICustomComponent.cs:line 43
   at Barotrauma.GUI.Draw(Camera cam, SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 273
   at Barotrauma.GameScreen.Draw(Double deltaTime, GraphicsDevice graphics, SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\GameScreen.cs:line 159
   at Barotrauma.GameMain.Draw(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 984
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 669
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 508
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58
```

**Comment by Rokvach** [comment]
Tested, working correctly, can be merged and closed.
