### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Teriri149** [Regalis11/Barotrauma#11225]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

When I am playing the game, I will crash when I arrive at the site

### Reproduction steps

1.Single player campaign mode
2.Arrive or leave the site

### Bug prevalence

Happens every time I play

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 02/13/2023 02:29:12)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

18B4B1F1463515508F0783BBFA6953EC

Game version 0.21.6.0 (ReleaseWindows, branch release, revision 480a2279e0)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: Simplified Chinese
Selected content packages: Vanilla, Halo Weapons（UNSC）, Halo Armors, AVP-Aliens, [BOS]Backpack, Enhanced Ryder‘s Waifu+ 莱德改进型分支, 32x Stack, 冒险级(改进版）, 小狐狸号（外贸版）, 小狐狸号（重炮型）, 小狐狸号（外贸版）
Level seed: VortaArgiope Linea
Loaded submarine: 小狐狸号（完整版） (CCAA8E36F906A9B867C1D13DAB6C2569)
Selected screen: Barotrauma.GameScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit
    GPU name: NVIDIA GeForce RTX 2060
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void DrawHUDFront(Microsoft.Xna.Framework.Graphics.SpriteBatch, Barotrauma.GUICustomComponent)
Stack trace: 
   at Barotrauma.Items.Components.MiniMap.DrawHUDFront(SpriteBatch spriteBatch, GUICustomComponent container) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Components\Machines\MiniMap.cs:line 732
   at Barotrauma.GUICustomComponent.Draw(SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUICustomComponent.cs:line 43
   at Barotrauma.GUI.Draw(Camera cam, SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 260
   at Barotrauma.GameScreen.Draw(Double deltaTime, GraphicsDevice graphics, SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\GameScreen.cs:line 158
   at Barotrauma.GameMain.Draw(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 985
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 669
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 508
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[02/13/2023 02:29:10] Error in projectile definition (ARC920弹丸): No body defined!
[02/13/2023 02:29:10] Invalid stat type type "AttackMultiplier" in item (arc920)
[02/13/2023 02:29:10] Invalid stat type type "AttackMultiplier" in item (m363prd)
[02/13/2023 02:29:06] WARNING: Potentially invalid damage modifier in "A型ODST战术盔甲, Wearable". Could not find any afflictions of the type "lacerations". Did you mean to use an affliction identifier instead?
[02/13/2023 02:29:06] WARNING: Potentially invalid damage modifier in "A型ODST战术头盔, Wearable". Could not find any afflictions of the type "concussion". Did you mean to use an affliction identifier instead?
[02/13/2023 02:29:06] WARNING: Potentially invalid damage modifier in "A型ODST战术盔甲, Wearable". Could not find any afflictions of the type "lacerations". Did you mean to use an affliction identifier instead?
[02/13/2023 02:29:06] WARNING: Potentially invalid damage modifier in "A型ODST战术头盔, Wearable". Could not find any afflictions of the type "concussion". Did you mean to use an affliction identifier instead?
[02/13/2023 02:29:06] WARNING: Potentially invalid damage modifier in "A型ODST战术盔甲, Wearable". Could not find any afflictions of the type "lacerations". Did you mean to use an affliction identifier instead?
[02/13/2023 02:29:06] WARNING: Potentially invalid damage modifier in "A型ODST战术头盔, Wearable". Could not find any afflictions of the type "concussion". Did you mean to use an affliction identifier instead?
[02/13/2023 02:29:06] WARNING: Potentially invalid damage modifier in "GEN2侦察型雷神锤盔甲, Wearable". Could not find any afflictions with the identifier "alieninfection". Did you mean to use an affliction type instead?
[02/13/2023 02:29:06] WARNING: Potentially invalid damage modifier in "GEN2侦察型雷神锤盔甲, Wearable". Could not find any afflictions of the type "radiationsickness". Did you mean to use an affliction identifier instead?
[02/13/2023 02:29:06] WARNING: Potentially invalid damage modifier in "GEN2侦察型雷神锤盔甲, Wearable". Could not find any afflictions of the type "lacerations". Did you mean to use an affliction identifier instead?
[02/13/2023 02:29:05] WARNING: Potentially invalid damage modifier in "GEN2侦察型雷神锤盔甲, Wearable". Could not find any afflictions with the identifier "alieninfection". Did you mean to use an affliction type instead?
[02/13/2023 02:29:05] WARNING: Potentially invalid damage modifier in "GEN2侦察型雷神锤盔甲, Wearable". Could not find any afflictions of the type "radiationsickness". Did you mean to use an affliction identifier instead?
[02/13/2023 02:29:05] WARNING: Potentially invalid damage modifier in "GEN2侦察型雷神锤盔甲, Wearable". Could not find any afflictions of the type "lacerations". Did you mean to use an affliction identifier instead?
[02/13/2023 02:29:05] Invalid stat type type "AttackMultiplier" in item (m392)
[02/13/2023 02:29:05] Invalid stat type type "AttackMultiplier" in item (m395)
[02/13/2023 02:29:05] WARNING: Potentially invalid damage modifier in "MARKVI型雷神锤盔甲, Wearable". Could not find any afflictions with the identifier "alieninfection". Did you mean to use an affliction type instead?
[02/13/2023 02:29:05] WARNING: Potentially invalid damage modifier in "MARKVI型雷神锤盔甲, Wearable". Could not find any afflictions of the type "radiationsickness". Did you mean to use an affliction identifier instead?
[02/13/2023 02:29:05] WARNING: Potentially invalid damage modifier in "MARKVI型雷神锤盔甲, Wearable". Could not find any afflictions of the type "lacerations". Did you mean to use an affliction identifier instead?
[02/13/2023 02:29:05] WARNING: Potentially invalid damage modifier in "A型ODST战术盔甲, Wearable". Could not find any afflictions of the type "lacerations". Did you mean to use an affliction identifier instead?
[02/13/2023 02:29:05] WARNING: Potentially invalid damage modifier in "A型ODST战术头盔, Wearable". Could not find any afflictions of the type "concussion". Did you mean to use an affliction identifier instead?
[02/13/2023 02:29:00] Generating an outpost for the start of the level... (Location: Vorta, level type: LocationConnection)
[02/13/2023 02:28:59] Generating an outpost for the end of the level... (Location: Argiope Linea矿, level type: LocationConnection)
[02/13/2023 02:28:59] Level identifier: coldcavernstransition
[02/13/2023 02:28:58] Error in projectile definition (ARC920弹丸): No body defined!
[02/13/2023 02:28:58] Error in projectile definition (ARC920弹丸): No body defined!
[02/13/2023 02:28:58] Error in projectile definition (ARC920弹丸): No body defined!
[02/13/2023 02:28:58] Error in projectile definition (ARC920弹丸): No body defined!
[02/13/2023 02:28:58] Invalid stat type type "AttackMultiplier" in item (ma5d)
[02/13/2023 02:28:58] Invalid stat type type "AttackMultiplier" in item (vk78)
[02/13/2023 02:28:58] Invalid stat type type "AttackMultiplier" in item (m7smg)
[02/13/2023 02:28:58] Invalid stat type type "AttackMultiplier" in item (mlrs1)
[02/13/2023 02:28:57] Invalid stat type type "AttackMultiplier" in item (br85hb)
[02/13/2023 02:28:53] WARNING: Potentially invalid damage modifier in "UNSC海军上将帽, Wearable". Could not find any afflictions of the type "concussion". Did you mean to use an affliction identifier instead?
[02/13/2023 02:28:52] WARNING: Potentially invalid damage modifier in "民用突击头盔, Wearable". Could not find any afflictions of the type "concussion". Did you mean to use an affliction identifier instead?
[02/13/2023 02:28:52] WARNING: Potentially invalid damage modifier in "民用突击头盔, Wearable". Could not find any afflictions of the type "concussion". Did you mean to use an affliction identifier instead?
[02/13/2023 02:28:52] WARNING: Potentially invalid damage modifier in "民用突击头盔, Wearable". Could not find any afflictions of the type "concussion". Did you mean to use an affliction identifier instead?
[02/13/2023 02:28:52] WARNING: Potentially invalid damage modifier in "民用突击头盔, Wearable". Could not find any afflictions of the type "concussion". Did you mean to use an affliction identifier instead?
[02/13/2023 02:28:52] Invalid stat type type "AttackMultiplier" in item (m739)
[02/13/2023 02:28:52] Invalid stat type type "AttackMultiplier" in item (m739)
[02/13/2023 02:28:52] Invalid stat type type "AttackMultiplier" in item (ma5b)
[02/13/2023 02:28:52] WARNING: Potentially invalid damage modifier in "UNSC测试型军用头盔, Wearable". Could not find any afflictions of the type "concussion". Did you mean to use an affliction identifier instead?
[02/13/2023 02:28:52] WARNING: Potentially invalid damage modifier in "UNSC测试型军用头盔, Wearable". Could not find any afflictions of the type "concussion". Did you mean to use an affliction identifier instead?
[02/13/2023 02:28:46] WARNING: Affliction "motesinfection" contains effects with overlapping strength ranges. Only one effect can be active at a time, meaning one of the effects won't work.
[02/13/2023 02:28:46] WARNING: Affliction "xenoinfectionpredalien" contains effects with overlapping strength ranges. Only one effect can be active at a time, meaning one of the effects won't work.
[02/13/2023 02:28:46] WARNING: Affliction "xenogrowthpredalienroyal" contains effects with overlapping strength ranges. Only one effect can be active at a time, meaning one of the effects won't work.
[02/13/2023 02:28:46] WARNING: Affliction "xenogrowthpredalienroyal" contains effects with overlapping strength ranges. Only one effect can be active at a time, meaning one of the effects won't work.
[02/13/2023 02:28:46] WARNING: Affliction "xenogrowthpredalienroyal" contains effects with overlapping strength ranges. Only one effect can be active at a time, meaning one of the effects won't work.
[02/13/2023 02:28:45] WARNING: Affliction "xenogrowthpredalien" contains effects with overlapping strength ranges. Only one effect can be active at a time, meaning one of the effects won't work.
[02/13/2023 02:28:45] WARNING: Affliction "xenoinfectionpredalienroyal" contains effects with overlapping strength ranges. Only one effect can be active at a time, meaning one of the effects won't work.
[02/13/2023 02:28:45] WARNING: Affliction "xenoinfection" contains effects with overlapping strength ranges. Only one effect can be active at a time, meaning one of the effects won't work.
[02/13/2023 02:28:45] WARNING: Affliction "blackgooimpregnation" contains effects with overlapping strength ranges. Only one effect can be active at a time, meaning one of the effects won't work.
[02/13/2023 02:28:45] WARNING: Affliction "xenoroyalinfection" contains effects with overlapping strength ranges. Only one effect can be active at a time, meaning one of the effects won't work.
[02/13/2023 02:28:45] WARNING: Affliction "trilobiteinfection" contains effects with overlapping strength ranges. Only one effect can be active at a time, meaning one of the effects won't work.
[02/13/2023 02:28:45] WARNING: Affliction "xenoinfectionx5" contains effects with overlapping strength ranges. Only one effect can be active at a time, meaning one of the effects won't work.
[02/13/2023 02:28:45] WARNING: Affliction "xenoinfectionx5" contains effects with overlapping strength ranges. Only one effect can be active at a time, meaning one of the effects won't work.
[02/13/2023 02:28:45] WARNING: Affliction "xenoinfectionx5" contains effects with overlapping strength ranges. Only one effect can be active at a time, meaning one of the effects won't work.
[02/13/2023 02:28:45] WARNING: Affliction "xenoinfectionx5" contains effects with overlapping strength ranges. Only one effect can be active at a time, meaning one of the effects won't work.
[02/13/2023 02:28:39] Transitioning to VortaArgiope Linea (current location: Argiope Linea矿, selected location: Vorta, leaving sub: 小狐狸号（完整版）, at start: True, at end: False, transition type: LeaveLocation)
[02/13/2023 02:24:26] Unlocked mission "开采磷氯铅矿" in the connection from "Argiope Linea矿" to "Adonis Linea".
[02/13/2023 02:24:24] Unlocked mission "杀死锤头煞" in the connection from "Argiope Linea矿" to "Udaeus Linea".
[02/13/2023 02:24:22] Unlocked mission "矿业中心原材料运输" in the connection from "Argiope Linea矿" to "Vorta".
[02/13/2023 02:24:07] WARNING: Potentially invalid damage modifier in "防弹头盔, Wearable". Could not find any afflictions of the type "concussion". Did you mean to use an affliction identifier instead?
[02/13/2023 02:23:32] WARNING: Potentially invalid damage modifier in "炮手头盔, Wearable". Could not find any afflictions of the type "concussion". Did you mean to use an affliction identifier instead?
[02/13/2023 02:23:32] WARNING: Potentially invalid damage modifier in "防弹头盔, Wearable". Could not find any afflictions of the type "concussion". Did you mean to use an affliction identifier instead?
[02/13/2023 02:23:31] WARNING: Potentially invalid damage modifier in "A型ODST战术盔甲, Wearable". Could not find any afflictions of the type "lacerations". Did you mean to use an affliction identifier instead?
[02/13/2023 02:23:31] WARNING: Potentially invalid damage modifier in "A型ODST战术头盔, Wearable". Could not find any afflictions of the type "concussion". Did you mean to use an affliction identifier instead?
[02/13/2023 02:23:30] WARNING: Potentially invalid damage modifier in "A型ODST战术盔甲, Wearable". Could not find any afflictions of the type "lacerations". Did you mean to use an affliction identifier instead?
[02/13/2023 02:23:30] WARNING: Potentially invalid damage modifier in "A型ODST战术头盔, Wearable". Could not find any afflictions of the type "concussion". Did you mean to use an affliction identifier instead?
[02/13/2023 02:23:30] WARNING: Potentially invalid damage modifier in "A型ODST战术盔甲, Wearable". Could not find any afflictions of the type "lacerations". Did you mean to use an affliction identifier instead?
[02/13/2023 02:23:30] WARNING: Potentially invalid damage modifier in "A型ODST战术头盔, Wearable". Could not find any afflictions of the type "concussion". Did you mean to use an affliction identifier instead?
[02/13/2023 02:23:30] WARNING: Potentially invalid damage modifier in "GEN2侦察型雷神锤盔甲, Wearable". Could not find any afflictions with the identifier "alieninfection". Did you mean to use an affliction type instead?
[02/13/2023 02:23:30] WARNING: Potentially invalid damage modifier in "GEN2侦察型雷神锤盔甲, Wearable". Could not find any afflictions of the type "radiationsickness". Did you mean to use an affliction identifier instead?
[02/13/2023 02:23:30] WARNING: Potentially invalid damage modifier in "GEN2侦察型雷神锤盔甲, Wearable". Could not find any afflictions of the type "lacerations". Did you mean to use an affliction identifier instead?
[02/13/2023 02:23:30] WARNING: Potentially invalid damage modifier in "GEN2侦察型雷神锤盔甲, Wearable". Could not find any afflictions with the identifier "alieninfection". Did you mean to use an affliction type instead?
[02/13/2023 02:23:30] WARNING: Potentially invalid damage modifier in "GEN2侦察型雷神锤盔甲, Wearable". Could not find any afflictions of the type "radiationsickness". Did you mean to use an affliction identifier instead?
[02/13/2023 02:23:30] WARNING: Potentially invalid damage modifier in "GEN2侦察型雷神锤盔甲, Wearable". Could not find any afflictions of the type "lacerations". Did you mean to use an affliction identifier instead?
[02/13/2023 02:23:30] Invalid stat type type "AttackMultiplier" in item (m392)
[02/13/2023 02:23:30] Invalid stat type type "AttackMultiplier" in item (m395)
[02/13/2023 02:23:30] WARNING: Potentially invalid damage modifier in "MARKVI型雷神锤盔甲, Wearable". Could not find any afflictions with the identifier "alieninfection". Did you mean to use an affliction type instead?
[02/13/2023 02:23:30] WARNING: Potentially invalid damage modifier in "MARKVI型雷神锤盔甲, Wearable". Could not find any afflictions of the type "radiationsickness". Did you mean to use an affliction identifier instead?
[02/13/2023 02:23:30] WARNING: Potentially invalid damage modifier in "MARKVI型雷神锤盔甲, Wearable". Could not find any afflictions of the type "lacerations". Did you mean to use an affliction identifier instead?
[02/13/2023 02:23:30] WARNING: Potentially invalid damage modifier in "A型ODST战术盔甲, Wearable". Could not find any afflictions of the type "lacerations". Did you mean to use an affliction identifier instead?
[02/13/2023 02:23:29] WARNING: Potentially invalid damage modifier in "A型ODST战术头盔, Wearable". Could not find any afflictions of the type "concussion". Did you mean to use an affliction identifier instead?
[02/13/2023 02:23:26] Generating an outpost for the start of the level... (Location: Argiope Linea矿, level type: Outpost)
[02/13/2023 02:23:26] Level identifier: outpostlevel
[02/13/2023 02:23:25] Error in projectile definition (ARC920弹丸): No body defined!
[02/13/2023 02:23:25] Error in projectile definition (ARC920弹丸): No body defined!
[02/13/2023 02:23:25] Error in projectile definition (ARC920弹丸): No body defined!
[02/13/2023 02:23:25] Error in projectile definition (ARC920弹丸): No body defined!
[02/13/2023 02:23:25] Invalid stat type type "AttackMultiplier" in item (ma5d)
[02/13/2023 02:23:25] Invalid stat type type "AttackMultiplier" in item (vk78)
[02/13/2023 02:23:25] Invalid stat type type "AttackMultiplier" in item (m7smg)
[02/13/2023 02:23:25] Invalid stat type type "AttackMultiplier" in item (mlrs1)
[02/13/2023 02:23:24] Invalid stat type type "AttackMultiplier" in item (br85hb)
[02/13/2023 02:23:20] WARNING: Potentially invalid damage modifier in "UNSC海军上将帽, Wearable". Could not find any afflictions of the type "concussion". Did you mean to use an affliction identifier instead?
[02/13/2023 02:23:19] WARNING: Potentially invalid damage modifier in "民用突击头盔, Wearable". Could not find any afflictions of the type "concussion". Did you mean to use an affliction identifier instead?
[02/13/2023 02:23:19] WARNING: Potentially invalid damage modifier in "民用突击头盔, Wearable". Could not find any afflictions of the type "concussion". Did you mean to use an affliction identifier instead?
[02/13/2023 02:23:19] WARNING: Potentially invalid damage modifier in "民用突击头盔, Wearable". Could not find any afflictions of the type "concussion". Did you mean to use an affliction identifier instead?
[02/13/2023 02:23:19] WARNING: Potentially invalid damage modifier in "民用突击头盔, Wearable". Could not find any afflictions of the type "concussion". Did you mean to use an affliction identifier instead?
[02/13/2023 02:23:19] Invalid stat type type "AttackMultiplier" in item (m739)
[02/13/2023 02:23:19] Invalid stat type type "AttackMultiplier" in item (m739)
[02/13/2023 02:23:19] Invalid stat type type "AttackMultiplier" in item (ma5b)
[02/13/2023 02:23:19] WARNING: Potentially invalid damage modifier in "UNSC测试型军用头盔, Wearable". Could not find any afflictions of the type "concussion". Did you mean to use an affliction identifier instead?
[02/13/2023 02:23:19] WARNING: Potentially invalid damage modifier in "UNSC测试型军用头盔, Wearable". Could not find any afflictions of the type "concussion". Did you mean to use an affliction identifier instead?
[02/13/2023 02:23:13] WARNING: Affliction "motesinfection" contains effects with overlapping strength ranges. Only one effect can be active at a time, meaning one of the effects won't work.
[02/13/2023 02:23:13] WARNING: Affliction "xenoinfectionpredalien" contains effects with overlapping strength ranges. Only one effect can be active at a time, meaning one of the effects won't work.
[02/13/2023 02:23:13] WARNING: Affliction "xenogrowthpredalienroyal" contains effects with overlapping strength ranges. Only one effect can be active at a time, meaning one of the effects won't work.
[02/13/2023 02:23:13] WARNING: Affliction "xenogrowthpredalienroyal" contains effects with overlapping strength ranges. Only one effect can be active at a time, meaning one of the effects won't work.
[02/13/2023 02:23:13] WARNING: Affliction "xenogrowthpredalienroyal" contains effects with overlapping strength ranges. Only one effect can be active at a time, meaning one of the effects won't work.
[02/13/2023 02:23:13] WARNING: Affliction "xenogrowthpredalien" contains effects with overlapping strength ranges. Only one effect can be active at a time, meaning one of the effects won't work.
[02/13/2023 02:23:13] WARNING: Affliction "xenoinfectionpredalienroyal" contains effects with overlapping strength ranges. Only one effect can be active at a time, meaning one of the effects won't work.
[02/13/2023 02:23:13] WARNING: Affliction "xenoinfection" contains effects with overlapping strength ranges. Only one effect can be active at a time, meaning one of the effects won't work.
[02/13/2023 02:23:13] WARNING: Affliction "blackgooimpregnation" contains effects with overlapping strength ranges. Only one effect can be active at a time, meaning one of the effects won't work.
[02/13/2023 02:23:13] WARNING: Affliction "xenoroyalinfection" contains effects with overlapping strength ranges. Only one effect can be active at a time, meaning one of the effects won't work.
[02/13/2023 02:23:13] WARNING: Affliction "trilobiteinfection" contains effects with overlapping strength ranges. Only one effect can be active at a time, meaning one of the effects won't work.
[02/13/2023 02:23:13] WARNING: Affliction "xenoinfectionx5" contains effects with overlapping strength ranges. Only one effect can be active at a time, meaning one of the effects won't work.
[02/13/2023 02:23:13] WARNING: Affliction "xenoinfectionx5" contains effects with overlapping strength ranges. Only one effect can be active at a time, meaning one of the effects won't work.
[02/13/2023 02:23:13] WARNING: Affliction "xenoinfectionx5" contains effects with overlapping strength ranges. Only one effect can be active at a time, meaning one of the effects won't work.
[02/13/2023 02:23:13] WARNING: Affliction "xenoinfectionx5" contains effects with overlapping strength ranges. Only one effect can be active at a time, meaning one of the effects won't work.
[02/13/2023 02:23:07] Transitioning to Argiope Linea (current location: Udaeus Linea, selected location: Argiope Linea矿, leaving sub: 小狐狸号（完整版）, at start: False, at end: True, transition type: ProgressToNextLocation)
[02/13/2023 02:19:49] Failed to initialize Steamworks network relay: Failed, Failed, Failed, No response from server
[02/13/2023 02:19:45] Could not find human prefab "Alien bandit" from "Alien abandonedoutpostnpcs".
[02/13/2023 02:19:27] WARNING: Potentially invalid damage modifier in "A型ODST战术盔甲, Wearable". Could not find any afflictions of the type "lacerations". Did you mean to use an affliction identifier instead?
[02/13/2023 02:19:27] WARNING: Potentially invalid damage modifier in "A型ODST战术头盔, Wearable". Could not find any afflictions of the type "concussion". Did you mean to use an affliction identifier instead?
[02/13/2023 02:19:27] WARNING: Potentially invalid damage modifier in "A型ODST战术盔甲, Wearable". Could not find any afflictions of the type "lacerations". Did you mean to use an affliction identifier instead?
[02/13/2023 02:19:27] WARNING: Potentially invalid damage modifier in "A型ODST战术头盔, Wearable". Could not find any afflictions of the type "concussion". Did you mean to use an affliction identifier instead?
[02/13/2023 02:19:27] WARNING: Potentially invalid damage modifier in "A型ODST战术盔甲, Wearable". Could not find any afflictions of the type "lacerations". Did you mean to use an affliction identifier instead?
[02/13/2023 02:19:27] WARNING: Potentially invalid damage modifier in "A型ODST战术头盔, Wearable". Could not find any afflictions of the type "concussion". Did you mean to use an affliction identifier instead?
[02/13/2023 02:19:27] WARNING: Potentially invalid damage modifier in "GEN2侦察型雷神锤盔甲, Wearable". Could not find any afflictions with the identifier "alieninfection". Did you mean to use an affliction type instead?
[02/13/2023 02:19:27] WARNING: Potentially invalid damage modifier in "GEN2侦察型雷神锤盔甲, Wearable". Could not find any afflictions of the type "radiationsickness". Did you mean to use an affliction identifier instead?
[02/13/2023 02:19:27] WARNING: Potentially invalid damage modifier in "GEN2侦察型雷神锤盔甲, Wearable". Could not find any afflictions of the type "lacerations". Did you mean to use an affliction identifier instead?
[02/13/2023 02:19:26] WARNING: Potentially invalid damage modifier in "GEN2侦察型雷神锤盔甲, Wearable". Could not find any afflictions with the identifier "alieninfection". Did you mean to use an affliction type instead?
[02/13/2023 02:19:26] WARNING: Potentially invalid damage modifier in "GEN2侦察型雷神锤盔甲, Wearable". Could not find any afflictions of the type "radiationsickness". Did you mean to use an affliction identifier instead?
[02/13/2023 02:19:26] WARNING: Potentially invalid damage modifier in "GEN2侦察型雷神锤盔甲, Wearable". Could not find any afflictions of the type "lacerations". Did you mean to use an affliction identifier instead?
[02/13/2023 02:19:26] Invalid stat type type "AttackMultiplier" in item (m392)
[02/13/2023 02:19:26] Invalid stat type type "AttackMultiplier" in item (m395)
[02/13/2023 02:19:26] WARNING: Potentially invalid damage modifier in "MARKVI型雷神锤盔甲, Wearable". Could not find any afflictions with the identifier "alieninfection". Did you mean to use an affliction type instead?
[02/13/2023 02:19:26] WARNING: Potentially invalid damage modifier in "MARKVI型雷神锤盔甲, Wearable". Could not find any afflictions of the type "radiationsickness". Did you mean to use an affliction identifier instead?
[02/13/2023 02:19:26] WARNING: Potentially invalid damage modifier in "MARKVI型雷神锤盔甲, Wearable". Could not find any afflictions of the type "lacerations". Did you mean to use an affliction identifier instead?
[02/13/2023 02:19:26] WARNING: Potentially invalid damage modifier in "A型ODST战术盔甲, Wearable". Could not find any afflictions of the type "lacerations". Did you mean to use an affliction identifier instead?
[02/13/2023 02:19:26] WARNING: Potentially invalid damage modifier in "A型ODST战术头盔, Wearable". Could not find any afflictions of the type "concussion". Did you mean to use an affliction identifier instead?
[02/13/2023 02:19:22] Could not find a suitable module for the location type LocationType (None). Module flag: Airlock.
[02/13/2023 02:19:21] Generating an outpost for the end of the level... (Location: Udaeus Linea, level type: LocationConnection)
[02/13/2023 02:19:21] Level identifier: coldcavernstransition
[02/13/2023 02:19:20] Error in projectile definition (ARC920弹丸): No body defined!
[02/13/2023 02:19:20] Error in projectile definition (ARC920弹丸): No body defined!
[02/13/2023 02:19:20] Error in projectile definition (ARC920弹丸): No body defined!
[02/13/2023 02:19:20] Error in projectile definition (ARC920弹丸): No body defined!
[02/13/2023 02:19:20] Invalid stat type type "AttackMultiplier" in item (ma5d)
[02/13/2023 02:19:20] Invalid stat type type "AttackMultiplier" in item (vk78)
[02/13/2023 02:19:20] Invalid stat type type "AttackMultiplier" in item (m7smg)
[02/13/2023 02:19:20] Invalid stat type type "AttackMultiplier" in item (mlrs1)
[02/13/2023 02:19:20] Invalid stat type type "AttackMultiplier" in item (br85hb)
[02/13/2023 02:19:16] WARNING: Potentially invalid damage modifier in "UNSC海军上将帽, Wearable". Could not find any afflictions of the type "concussion". Did you mean to use an affliction identifier instead?
[02/13/2023 02:19:15] WARNING: Potentially invalid damage modifier in "民用突击头盔, Wearable". Could not find any afflictions of the type "concussion". Did you mean to use an affliction identifier instead?
[02/13/2023 02:19:15] WARNING: Potentially invalid damage modifier in "民用突击头盔, Wearable". Could not find any afflictions of the type "concussion". Did you mean to use an affliction identifier instead?
[02/13/2023 02:19:15] WARNING: Potentially invalid damage modifier in "民用突击头盔, Wearable". Could not find any afflictions of the type "concussion". Did you mean to use an affliction identifier instead?
[02/13/2023 02:19:15] WARNING: Potentially invalid damage modifier in "民用突击头盔, Wearable". Could not find any afflictions of the type "concussion". Did you mean to use an affliction identifier instead?
[02/13/2023 02:19:15] Invalid stat type type "AttackMultiplier" in item (m739)
[02/13/2023 02:19:15] Invalid stat type type "AttackMultiplier" in item (m739)
[02/13/2023 02:19:15] Invalid stat type type "AttackMultiplier" in item (ma5b)
[02/13/2023 02:19:15] WARNING: Potentially invalid damage modifier in "UNSC测试型军用头盔, Wearable". Could not find any afflictions of the type "concussion". Did you mean to use an affliction identifier instead?
[02/13/2023 02:19:15] WARNING: Potentially invalid damage modifier in "UNSC测试型军用头盔, Wearable". Could not find any afflictions of the type "concussion". Did you mean to use an affliction identifier instead?
[02/13/2023 02:19:09] WARNING: Affliction "motesinfection" contains effects with overlapping strength ranges. Only one effect can be active at a time, meaning one of the effects won't work.
[02/13/2023 02:19:09] WARNING: Affliction "xenoinfectionpredalien" contains effects with overlapping strength ranges. Only one effect can be active at a time, meaning one of the effects won't work.
[02/13/2023 02:19:09] WARNING: Affliction "xenogrowthpredalienroyal" contains effects with overlapping strength ranges. Only one effect can be active at a time, meaning one of the effects won't work.
[02/13/2023 02:19:09] WARNING: Affliction "xenogrowthpredalienroyal" contains effects with overlapping strength ranges. Only one effect can be active at a time, meaning one of the effects won't work.
[02/13/2023 02:19:09] WARNING: Affliction "xenogrowthpredalienroyal" contains effects with overlapping strength ranges. Only one effect can be active at a time, meaning one of the effects won't work.
[02/13/2023 02:19:09] WARNING: Affliction "xenogrowthpredalien" contains effects with overlapping strength ranges. Only one effect can be active at a time, meaning one of the effects won't work.
[02/13/2023 02:19:09] WARNING: Affliction "xenoinfectionpredalienroyal" contains effects with overlapping strength ranges. Only one effect can be active at a time, meaning one of the effects won't work.
[02/13/2023 02:19:09] WARNING: Affliction "xenoinfection" contains effects with overlapping strength ranges. Only one effect can be active at a time, meaning one of the effects won't work.
[02/13/2023 02:19:09] WARNING: Affliction "blackgooimpregnation" contains effects with overlapping strength ranges. Only one effect can be active at a time, meaning one of the effects won't work.
[02/13/2023 02:19:09] WARNING: Affliction "xenoroyalinfection" contains effects with overlapping strength ranges. Only one effect can be active at a time, meaning one of the effects won't work.
[02/13/2023 02:19:09] WARNING: Affliction "trilobiteinfection" contains effects with overlapping strength ranges. Only one effect can be active at a time, meaning one of the effects won't work.
[02/13/2023 02:19:09] WARNING: Affliction "xenoinfectionx5" contains effects with overlapping strength ranges. Only one effect can be active at a time, meaning one of the effects won't work.
[02/13/2023 02:19:09] WARNING: Affliction "xenoinfectionx5" contains effects with overlapping strength ranges. Only one effect can be active at a time, meaning one of the effects won't work.
[02/13/2023 02:19:09] WARNING: Affliction "xenoinfectionx5" contains effects with overlapping strength ranges. Only one effect can be active at a time, meaning one of the effects won't work.
[02/13/2023 02:19:09] WARNING: Affliction "xenoinfectionx5" contains effects with overlapping strength ranges. Only one effect can be active at a time, meaning one of the effects won't work.
[02/13/2023 02:18:18] Attempting to open ALC device "OpenAL Soft on 扬声器 (Realtek High Definition Audio)"
[02/13/2023 02:18:15] Logged in as 德丽莎Theresa (SteamID STEAM_1:1:544916041)
```

**Comment by Regalis11** [comment]
Potentially fixed in https://github.com/Regalis11/Barotrauma-development/commit/8b5ff127db7eb7f4bf39371a3eed9ee123f28c56 (commit in our private repository). Based on the error message, it looks like the game is trying to draw the UI of a status monitor, but the status monitor view hasn't been properly created yet (which could happen if the item hasn't been inside any sub during the whole round). I suspect this could be caused by some modded item, possibly something your character has equipped?

**Comment by Rokvach** [comment]
Checked GA and there hasn't been any sightings of this crash, as there is no known repro steps it seems like this is working correctly on 1.1, closing.
