### ISSUE TITLE
When i save my sub in editor, throw a error, And i restart my game, cannot open my sub file

### ISSUE THREAD

**Issue by CaloteString** [Regalis11/Barotrauma#11242]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

My sub have been finished, and i save it. The throw a error, there is an item cannot delete. I just quit my game. And restart , sub file cannot open, get some error message in console. And i try to load autosave but it crash. It happened twice.

The crash log and two sub file is here.
Please help me. Thanks!

### Reproduction steps

[crashreport (10).log](https://github.com/Regalis11/Barotrauma/files/10725160/crashreport.10.log)

[subfiles.zip](https://github.com/Regalis11/Barotrauma/files/10725178/subfiles.zip)

### Bug prevalence

Happens every now and then

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Failed to load the submarine. The submarine file might be corrupted. {Duplicate ID: 99}
   at Barotrauma.IdRemap.InsertId(Int32 id) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\IdRemap.cs:line 73
   at Barotrauma.IdRemap..ctor(XElement parentElement, Int32 offset) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\IdRemap.cs:line 28
   at Barotrauma.MapEntity.LoadAll(Submarine submarine, XElement parentElement, String filePath, Int32 idOffset) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\MapEntity.cs:line 647
   at Barotrauma.Submarine..ctor(SubmarineInfo info, Boolean showErrorMessages, Func`2 loadEntities, IdRemap linkedRemap) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Submarine.cs:line 1341
   at Barotrauma.SubEditorScreen.LoadSub(SubmarineInfo info) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\SubEditorScreen.cs:line 3537
```

**Comment by Regalis11** [comment]
Thank you for the report!

I was able to fix your submarine files by removing those entities with duplicate IDs from them: 
[subs_fixed.zip](https://github.com/Regalis11/Barotrauma/files/10786256/subs_fixed.zip)

There seemed to be a coilgun somewhere very far away from the sub in LittleGun, with the same ID as one of the ladders in the sub. In 深潜 there was a waypoint with a duplicate id. I have no clue how those ended up there though - there must be some issue that's causing these overlapping IDs somewhere in the game.

**Comment by CaloteString** [comment]
Thanks for your help! 
I will edit my sub and try to find a way which can cause this bug. if I get more idea, I will report more.

**Comment by Regalis11** [comment]
No steps to repro, closing
