### ISSUE TITLE
Console error "Attempting to remove an already removed item"

### ISSUE THREAD

**Issue by Aurani** [Regalis11/Barotrauma#11265]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Played a MP campaign with 2 friends, after we finished 2 stages and begun the 3rd we saved and quit for the night. The red console error message appeared after I went to main menu. We had no active missions on the current stages but both had inactive beacons.

### Bug prevalence

Just once

### Version

0.22.0.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Attempting to remove an already removed item (Status Monitor (Wrecked))
   at System.Environment.get_StackTrace()
   at Barotrauma.Item.Remove() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 3622
   at Barotrauma.Entity.RemoveAll() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Entity.cs:line 245
   at Barotrauma.Submarine.Unload() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Submarine.cs:line 1713
   at Barotrauma.MainMenuScreen.Select() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\MainMenuScreen.cs:line 569
   at Barotrauma.MainMenuScreen.ReturnToMainMenu(GUIButton button, Object obj) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\MainMenuScreen.cs:line 712
   at Barotrauma.GUIButton.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIButton.cs:line 263
   at Barotrauma.GUI.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1264
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 906
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 651
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58
```

Some items were not removed in Entity.RemoveAll:
 - Status Monitor (Wrecked)(ID 3496)

**Comment by Regalis11** [comment]
No known steps to repro, closing
