### ISSUE TITLE
Error while reading a message from server. {Input contains duplicate packages}

### ISSUE THREAD

**Issue by BiffW** [Regalis11/Barotrauma#11277]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Similar to #9987
When I try to join a heavily modded server, this happens.
![duplicate_packages](https://user-images.githubusercontent.com/99462070/219875605-be14ff9c-dfa1-4f87-9048-d62f7d6a446c.png)

### Bug prevalence

Happens regularly

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

**Comment by BiffW** [comment]
This happened after the game fail to update a mod. This time it is "Dynamic Europa 汉化补丁" And I shut down the game and resubscribed the mod.
I don't think it's specific to mod. Last time it was "CsForBarotrauma".

**Comment by Regalis11** [comment]
Thank you for the report!

I haven't been able to find a way to reproduce this, but I'm a bit unclear on the repro steps. What exactly do you mean by the game failing to update a mod? Do you mean you tried to download the latest version of the mod from the Workshop? Was there some error message when that failed? Or were you trying to upload a newer version of your own mod?

**Comment by BiffW** [comment]
I attempted to update a mod made by other person to the latest version. When the green progress indicator fully surrounded the update button, it just paused. The green indicator did not disappear. I returned to the mod list and could not find the mod. I believed that the mod didn't install correctly. The steam download showed a Barotrauma workshop task in the waiting list. I tried to pull it to active list but it doesn't work. I restarted the game and could not find the mod. So I verified the game files and thought it would fix it. After that, the mod seems to have installed correctly. But I still couldn't join the server I mentioned above. It shows the same error in the console.

**Comment by Krzeszny** [comment]
Same here. A mod failed to download so I pressed Cancel and I can't join that server.

**Comment by Krzeszny** [comment]
Currently caused by subscribing to Husk Mod Missions from the server joining prompt:
![Barotrauma_5egVSDeSG7](https://user-images.githubusercontent.com/10529134/225135868-b9d951cb-3bb3-4c1f-be89-3cfb3d02fd0a.png)

**Comment by Krzeszny** [comment]
After reproducing the bug 5 times by subscribing to the culprit mod, I tried downloading it from the server. That action caused a full crash:
[crashreport (27).log](https://github.com/Regalis11/Barotrauma/files/10973789/crashreport.27.log)

**Comment by Krzeszny** [comment]
```
Error while reading a message from server. 
Input contains duplicate packages
   at Barotrauma.ContentPackageManager.EnabledPackages.ThrowIfDuplicates(IEnumerable`1 pkgs) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\ContentManagement\ContentPackageManager.cs:line 121
   at Barotrauma.ContentPackageManager.EnabledPackages.SetRegularEnumerable(IReadOnlyList`1 inNewRegular)+MoveNext() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\ContentManagement\ContentPackageManager.cs:line 84
   at Barotrauma.Extensions.IEnumerableExtensions.Consume[T](IEnumerable`1 enumerable) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Extensions\IEnumerableExtensions.cs:line 155
   at Barotrauma.ModDownloadScreen.Select() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\ModDownloadScreen.cs:line 116
   at Barotrauma.Networking.GameClient.OnConnectionInitializationComplete() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 1117
   at Barotrauma.Networking.SteamP2PClientPeer.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\Primitives\Peers\SteamP2PClientPeer.cs:line 244
   at Barotrauma.Networking.GameClient.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 500
```

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
