### ISSUE TITLE
Exception: Component event creation failed: Projectile.ValidateEventData returned false

### ISSUE THREAD

**Issue by terokorp** [Regalis11/Barotrauma#11282]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Every time when someone or something shoots anything game crashes.
"spinelingspike", "stungundart", "antidama1"

### Reproduction steps

1. Make clean install
2. Host camaign
3. Start beacon
4. Go to ship and wait for crash.

### Bug prevalence

Happens every time I play

### Version

0.21.6.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Dedicated Server crash report (generated on 02/19/2023 22:02:37)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


Game version 0.21.6.0 (ReleaseWindows, branch release, revision 480a2279e0)
Language: English
Selected content packages: Vanilla
Level seed: Sparti LineaBeenalaght Fossa
Loaded submarine: Dugong (D617FE49DDACABDC2629FE7C59A6CE60)
Selected screen: Barotrauma.GameScreen
Server (Round had started)


System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit


Exception: Component event creation for the item "antidama1" failed: Projectile.ValidateEventData returned false. (System.Exception)
Target site: Void CreateServerEvent[T](T, IEventData)
Stack trace: 
   at Barotrauma.Item.CreateServerEvent[T](T ic, IEventData extraData) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Items\Item.cs:line 377
   at Barotrauma.Items.Components.Projectile.HandleProjectileCollision(Fixture target, Vector2 collisionNormal, Vector2 velocity) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Projectile.cs:line 1057
   at Barotrauma.Items.Components.Projectile.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Projectile.cs:line 693
   at Barotrauma.Item.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 1951
   at Barotrauma.MapEntity.UpdateAll(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\MapEntity.cs:line 600
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 256
   at Barotrauma.GameMain.Run() in <DEV>\Barotrauma\BarotraumaServer\ServerSource\GameMain.cs:line 326
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Program.cs:line 78


Last debug messages:
   02/19/2023 22:02:37 - [02/19/2023 22:02:37]
  Saving banlist
   02/19/2023 22:02:34 - [02/19/2023 22:02:34]
  AnotherPlayer equipped Syringe Gun
   02/19/2023 22:02:31 - [02/19/2023 22:02:31]
  HostPlayer placed Signal Check Component in Medium Steel Cabinet (ID: 666)
   02/19/2023 22:02:31 - [02/19/2023 22:02:31]
  Mudraptor_unarmored attacked by AnotherPlayer. Lacerations: 15.0 Bleeding: 1.0
   02/19/2023 22:02:31 - [02/19/2023 22:02:31]
  AnotherPlayer launched Coilgun (projectile: Coilgun Bolt)
   02/19/2023 22:02:31 - [02/19/2023 22:02:31]
  Mudraptor_unarmored attacked by AnotherPlayer. Lacerations: 15.0 Bleeding: 1.0
   02/19/2023 22:02:30 - [02/19/2023 22:02:30]
  AnotherPlayer launched Coilgun (projectile: Coilgun Bolt)
   02/19/2023 22:02:30 - [02/19/2023 22:02:30]
  Mudraptor_unarmored attacked by AnotherPlayer. Lacerations: 15.0 Bleeding: 1.0
   02/19/2023 22:02:30 - [02/19/2023 22:02:30]
  AnotherPlayer launched Coilgun (projectile: Coilgun Bolt)
   02/19/2023 22:02:30 - [02/19/2023 22:02:30]
  Mudraptor_unarmored attacked by AnotherPlayer. Lacerations: 15.0 Bleeding: 1.0
   02/19/2023 22:02:30 - [02/19/2023 22:02:30]
  AnotherPlayer launched Coilgun (projectile: Coilgun Bolt)
   02/19/2023 22:02:30 - [02/19/2023 22:02:30]
  Mudraptor_unarmored attacked by AnotherPlayer. Lacerations: 15.0 Bleeding: 1.0
   02/19/2023 22:02:30 - [02/19/2023 22:02:30]
  Outer wall breached by Mudraptor_unarmored
   02/19/2023 22:02:30 - [02/19/2023 22:02:30]
  AnotherPlayer launched Coilgun (projectile: Coilgun Bolt)



=================

Game version 0.21.6.0 (ReleaseWindows, branch release, revision 480a2279e0)
Language: English
Selected content packages: Vanilla
Level seed: h8qbnnpS
Loaded submarine: Hemulen (378ADE5D99E1C33B6B207C8B24C1427F)
Selected screen: Barotrauma.GameScreen
Server (Round had started)


System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit


Exception: Component event creation for the item "spinelingspike" failed: Projectile.ValidateEventData returned false. (System.Exception)
Target site: Void CreateServerEvent[T](T, IEventData)
Stack trace: 
   at Barotrauma.Item.CreateServerEvent[T](T ic, IEventData extraData) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Items\Item.cs:line 377
   at Barotrauma.Items.Components.Projectile.Shoot(Character user, Vector2 weaponPos, Vector2 spawnPos, Single rotation, List`1 ignoredBodies, Boolean createNetworkEvent, Single damageMultiplier, Single launchImpulseModifier) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Projectile.cs:line 362
   at Barotrauma.StatusEffect.<>c__DisplayClass104_6.<Apply>b__8(Item newItem) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\StatusEffects\StatusEffect.cs:line 1867
   at Barotrauma.EntitySpawner.ItemSpawnInfo.OnSpawned(Entity spawnedItem) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\EntitySpawner.cs:line 116
   at Barotrauma.EntitySpawner.Update(Boolean createNetworkEvents) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\EntitySpawner.cs:line 422
   at Barotrauma.MapEntity.UpdateAll(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\MapEntity.cs:line 611
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 256
   at Barotrauma.GameMain.Run() in <DEV>\Barotrauma\BarotraumaServer\ServerSource\GameMain.cs:line 326

=================

Game version 0.21.6.0 (ReleaseWindows, branch release, revision 480a2279e0)
Language: English
Selected content packages: Vanilla
Level seed: LUCMj2uF
Loaded submarine: Barsuk (89937A74FF3F968733813208DD44694E)
Selected screen: Barotrauma.GameScreen
Server (Round had started)


System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit


Game version 0.21.6.0 (ReleaseWindows, branch release, revision 480a2279e0)
Language: English
Selected content packages: Vanilla
Level seed: cJklMsWM
Loaded submarine: Hemulen (378ADE5D99E1C33B6B207C8B24C1427F)
Selected screen: Barotrauma.GameScreen
Server (Round had started)


System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit


Exception: Component event creation for the item "spinelingspike" failed: Projectile.ValidateEventData returned false. (System.Exception)
Target site: Void CreateServerEvent[T](T, IEventData)
Stack trace: 
   at Barotrauma.Item.CreateServerEvent[T](T ic, IEventData extraData) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Items\Item.cs:line 377
   at Barotrauma.Items.Components.Projectile.Shoot(Character user, Vector2 weaponPos, Vector2 spawnPos, Single rotation, List`1 ignoredBodies, Boolean createNetworkEvent, Single damageMultiplier, Single launchImpulseModifier) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Projectile.cs:line 362
   at Barotrauma.StatusEffect.<>c__DisplayClass104_6.<Apply>b__8(Item newItem) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\StatusEffects\StatusEffect.cs:line 1867
   at Barotrauma.EntitySpawner.ItemSpawnInfo.OnSpawned(Entity spawnedItem) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\EntitySpawner.cs:line 116
   at Barotrauma.EntitySpawner.Update(Boolean createNetworkEvents) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\EntitySpawner.cs:line 422
   at Barotrauma.MapEntity.UpdateAll(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\MapEntity.cs:line 611
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 256
   at Barotrauma.GameMain.Run() in <DEV>\Barotrauma\BarotraumaServer\ServerSource\GameMain.cs:line 326
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Program.cs:line 78

=================

Exception: Component event creation for the item "spinelingspike" failed: Projectile.ValidateEventData returned false. (System.Exception)
Target site: Void CreateServerEvent[T](T, IEventData)
Stack trace: 
   at Barotrauma.Item.CreateServerEvent[T](T ic, IEventData extraData) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Items\Item.cs:line 377
   at Barotrauma.Items.Components.Projectile.Shoot(Character user, Vector2 weaponPos, Vector2 spawnPos, Single rotation, List`1 ignoredBodies, Boolean createNetworkEvent, Single damageMultiplier, Single launchImpulseModifier) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Projectile.cs:line 362
   at Barotrauma.StatusEffect.<>c__DisplayClass104_6.<Apply>b__8(Item newItem) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\StatusEffects\StatusEffect.cs:line 1867
   at Barotrauma.EntitySpawner.Update(Boolean createNetworkEvents) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\EntitySpawner.cs:line 422
   at Barotrauma.MapEntity.UpdateAll(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\MapEntity.cs:line 611
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 256
   at Barotrauma.GameMain.Run() in <DEV>\Barotrauma\BarotraumaServer\ServerSource\GameMain.cs:line 326
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Program.cs:line 78

=================

Game version 0.21.6.0 (ReleaseWindows, branch release, revision 480a2279e0)
Language: English
Selected content packages: Vanilla
Level seed: Novaya Moskva
Loaded submarine: Dugong (F9EBE2F02EE9EDFFB975972EEA27534B)
Selected screen: Barotrauma.GameScreen
Server (Round had started)


System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit


Exception: Component event creation for the item "stungundart" failed: Projectile.ValidateEventData returned false. (System.Exception)
Target site: Void CreateServerEvent[T](T, IEventData)
Stack trace: 
   at Barotrauma.Item.CreateServerEvent[T](T ic, IEventData extraData) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Items\Item.cs:line 377
   at Barotrauma.Items.Components.Projectile.HandleProjectileCollision(Fixture target, Vector2 collisionNormal, Vector2 velocity) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Projectile.cs:line 1057
   at Barotrauma.Items.Components.Projectile.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Projectile.cs:line 693
   at Barotrauma.Item.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 1951
   at Barotrauma.MapEntity.UpdateAll(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\MapEntity.cs:line 600
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 256
   at Barotrauma.GameMain.Run() in <DEV>\Barotrauma\BarotraumaServer\ServerSource\GameMain.cs:line 326
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Program.cs:line 78
```

**Comment by Regalis11** [comment]
Thank you for the report!

We've gotten [one report about a seemingly similar bug before](https://github.com/Regalis11/Barotrauma/issues/10826), but unfortunately haven't been able to find a way to reproduce the issue at our end. I think there must be some specific thing that's causing this error to happen consistently for some players, while most players seem to never encounter it. To be sure, are you playing a completely unmodified version of the game, installed from Steam?

Thanks and sorry for the inconvenience!

**Comment by terokorp** [comment]
It is completely unmodified version and installed from steam.
I have played it before and it was working totally fine, but after the long break I tried it again and now it is totally unplayable.

I can run tests and debug builds if needed; I am on Undertow Games discord and posted same errors to baro-tech-support ch. You can find me there also.

**Comment by terokorp** [comment]
Found fast way to reproduce this bug:
1. Host any online game
2. Get Harpoon Gun
3. Aim and then click shooting button multiple times, do not wait for reload.

**Comment by terokorp** [comment]
I made a build from master 48c66adcdcb50d28d1b735218f5dbc10b9a971da , it works fine.

**Comment by redmoogle** [comment]
I have this issue as well looking through VS with the debugger attached to the server the arg `data` in `ValidateEventData` is null despite being constructed one line above
