### ISSUE TITLE
CTD when opening destination map (null reference exception in CanHaveCampaignInteraction)

### ISSUE THREAD

**Issue by Robo798814** [Regalis11/Barotrauma#11496]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![image](https://user-images.githubusercontent.com/29616390/224785773-9874cd38-0f9d-487e-b806-efad6379bfad.png)
The game will crash when you open the map in campaign mode. I was previously using mods but disabled them all. I've also tried verifying the integrity and all files were validated, however, the issue was not fixed.

### Reproduction steps

1. Launch campaign
2. Open destination map

### Bug prevalence

Happens every time I play

### Version

Other

### -

1.0.7.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 03/13/2023 13:44:27)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

71290F513E6B598EAA3CFF037A2EAB34

Game version 1.0.7.0 (ReleaseWindows, branch release/1.0, revision e1df60d5cc)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla, Auto-Doors for Outposts
Level seed: Phineus Linea21
Loaded submarine: Dugong (F9EBE2F02EE9EDFFB975972EEA27534B)
Selected screen: Barotrauma.GameScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19045.0 64 bit
    GPU name: NVIDIA GeForce GTX 1070 Ti
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Boolean CanHaveCampaignInteraction(InteractionType)
Stack trace: 
   at Barotrauma.OutpostGenerationParams.CanHaveCampaignInteraction(InteractionType interactionType) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Outposts\OutpostGenerationParams.cs:line 331
   at Barotrauma.Location.<>c__DisplayClass164_0.<CanHaveCampaignInteraction>b__0(OutpostGenerationParams p) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Map\Location.cs:line 1398
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Barotrauma.Location.CanHaveCampaignInteraction(InteractionType interactionType) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Map\Location.cs:line 1396
   at Barotrauma.Location.CanHaveSubsForSale() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Map\Location.cs:line 1377
   at Barotrauma.Map.CreateLocationInfoOverlay(Location location) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Map\Map\Map.cs:line 393
   at Barotrauma.Map.Update(CampaignMode campaign, Single deltaTime, GUICustomComponent mapContainer) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Map\Map\Map.cs:line 557
   at Barotrauma.CampaignUI.UpdateMap(Single deltaTime, GUICustomComponent mapContainer) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\CampaignUI.cs:line 179
   at Barotrauma.GUI.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1247
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 906
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[03/13/2023 13:44:27] Could not find human prefab "repairnpc" from "outpostnpcs1".
[03/13/2023 13:44:19] Unlocked mission "Mining outpost material transport" in the connection from "Phineus Linea" to "St. May Outpost".
[03/13/2023 13:42:34] Could not find human prefab "securitynpc" from "outpostnpcs1".
[03/13/2023 13:42:30] Loading a pre-selected outpost for the start of the level...
[03/13/2023 13:42:30] Level identifier: outpostlevel
[03/13/2023 13:42:21] Could not find human prefab "securitynpc" from "outpostnpcs1".
[03/13/2023 13:42:21] Could not find human prefab "securitynpc" from "outpostnpcs1".
[03/13/2023 13:42:21] Could not find human prefab "securitynpc" from "outpostnpcs1".
[03/13/2023 13:42:21] Could not find human prefab "repairnpc" from "outpostnpcs1".
[03/13/2023 13:42:21] Could not find human prefab "securitynpc" from "outpostnpcs1".
[03/13/2023 13:42:21] Could not find human prefab "securitynpc" from "outpostnpcs1".
[03/13/2023 13:42:21] Could not find human prefab "repairnpc" from "outpostnpcs1".
[03/13/2023 13:42:21] Could not find human prefab "securitynpc" from "outpostnpcs1".
[03/13/2023 13:42:21] Could not find human prefab "securitynpc" from "outpostnpcs1".
[03/13/2023 13:42:21] Could not find human prefab "securitynpc" from "outpostnpcs1".
[03/13/2023 13:42:21] Could not find human prefab "repairnpc" from "outpostnpcs1".
[03/13/2023 13:42:21] Could not find human prefab "securitynpc" from "outpostnpcs1".
[03/13/2023 13:42:21] Could not find human prefab "securitynpc" from "outpostnpcs1".
[03/13/2023 13:42:21] Could not find human prefab "securitynpc" from "outpostnpcs1".
[03/13/2023 13:42:21] Could not find human prefab "securitynpc" from "outpostnpcs1".
[03/13/2023 13:42:21] Could not find human prefab "securitynpc" from "outpostnpcs1".
[03/13/2023 13:42:21] Could not find human prefab "repairnpc" from "outpostnpcs1".
[03/13/2023 13:42:21] Could not find human prefab "securitynpc" from "outpostnpcs1".
[03/13/2023 13:42:21] Could not find human prefab "securitynpc" from "outpostnpcs1".
[03/13/2023 13:42:21] Could not find human prefab "repairnpc" from "outpostnpcs1".
[03/13/2023 13:40:55] Attempting to open ALC device "OpenAL Soft on Speakers (High Definition Audio Device)"
[03/13/2023 13:40:53] Logged in as Robo7988143 (SteamID STEAM_1:0:118786967)
```

**Comment by Robo798814** [comment]
Hi there,

I forgot to mention that I previously had a mod called "Auto-Doors for Outposts", which on the surface added motion sensors to outpost doors. I didn't know the intricacies of it, and I assumed that the mod only did just that rather than something major like an overhaul mod. 

I found a Steam discussion that reported a similar issue to mine and removed the mod which fixed the issue. I want to apologize if my report seemed to be a false alarm. Thank you for the amazing game!

Best regards

**Comment by Regalis11** [comment]
Thank you for taking the time to close this, but we'll keep the ticket open until we've tested the fix internally and verified it's working as expected. :)

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
