### ISSUE TITLE
Modded Campaign can't open the map after update

### ISSUE THREAD

**Issue by Gamling23** [Regalis11/Barotrauma#11535]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

After the update the old modded campaign a group of friends had has started crashing everytime we try to open the campaign map. 

### Reproduction steps

1. Start modded campaign
2. Try to open the campaign map
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/10975846/crashreport.log)

### Bug prevalence

Happens every time I play

### Version

v1.0.7.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 03/14/2023 09:37:07)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

35B85F62D7B9D401E74CE519DDE94DB4

Game version 1.0.7.0 (ReleaseWindows, branch master, revision fa6b6a590f)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync OFF
Language: English
Selected content packages: Vanilla, Lua For Barotrauma, BaroTraumatic, Neurotrauma, DynamicEuropa, BaroDrama V4.1, EK | Dockyard, EK | Utility, EK | Gunnery, SFB with DE, Improved Husks, Stations from beyond, Hazardous Reactors, ADV Beacon Stations, Material IO, Enhanced Armaments, Shipwrecks Extended, Neurotrauma Cybernetics, The Plague Rat, Super Plague Rat, Fat Fish, BetterHealthUI, Cs For Barotrauma, Bronze Age, NT Surgery Plus, EK | Armory, [VH] The Iroh, Real Sonar, New Wrecks For Barotrauma (With sellable wrecks), Beacons Extended, Movable and Sellable Wrecks, Performance Fix, NT Blahaj Plus, BaroCraftables+, NT Pharmacy
Level seed: Aylesbury
Loaded submarine: Typhon (AC5BB98DE0D168D1B6E373358A0E7097)
Selected screen: Barotrauma.GameScreen
SteamManager initialized
Client (Round had started)

System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit
    GPU name: NVIDIA GeForce RTX 3060
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void DrawConnection(Microsoft.Xna.Framework.Graphics.SpriteBatch, Barotrauma.LocationConnection, Microsoft.Xna.Framework.Rectangle, Microsoft.Xna.Framework.Vector2, Barotrauma.Location, System.Nullable`1[Microsoft.Xna.Framework.Color])
Stack trace: 
   at Barotrauma.Map.DrawConnection(SpriteBatch spriteBatch, LocationConnection connection, Rectangle viewArea, Vector2 viewOffset, Location currentDisplayLocation, Nullable`1 overrideColor)
   at Barotrauma.Map.Draw(CampaignMode campaign, SpriteBatch spriteBatch, GUICustomComponent mapContainer)
   at Barotrauma.GUICustomComponent.Draw(SpriteBatch spriteBatch)
   at Barotrauma.GUI.Draw(Camera cam, SpriteBatch spriteBatch)
   at Barotrauma.GameScreen.Draw(Double deltaTime, GraphicsDevice graphics, SpriteBatch spriteBatch)
   at Barotrauma.GameMain.Draw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime) in C:\Users\joona\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 669
   at Microsoft.Xna.Framework.Game.Tick() in C:\Users\joona\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 508
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in C:\Users\joona\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in C:\Users\joona\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in C:\Users\joona\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args)

Last debug messages:
[03/14/2023 09:36:50] Apollo
[03/14/2023 09:36:50] Stealthmean
[03/14/2023 09:36:50] Miji
[03/14/2023 09:36:50] itzBreaker
[03/14/2023 09:36:50] kitykity
[03/14/2023 09:36:50] Kiyate
[03/14/2023 09:36:50] Gamling
[03/14/2023 09:36:45] Stealthmean
[03/14/2023 09:36:45] Miji
[03/14/2023 09:36:45] itzBreaker
[03/14/2023 09:36:45] kitykity
[03/14/2023 09:36:45] Kiyate
[03/14/2023 09:36:45] Gamling
[03/14/2023 09:35:53] Stealthmean
[03/14/2023 09:35:53] Miji
[03/14/2023 09:35:53] itzBreaker
[03/14/2023 09:35:53] kitykity
[03/14/2023 09:35:53] Kiyate
[03/14/2023 09:35:53] Gamling
[03/14/2023 09:35:52] Stealthmean
[03/14/2023 09:35:52] Miji
[03/14/2023 09:35:52] itzBreaker
[03/14/2023 09:35:52] kitykity
[03/14/2023 09:35:52] Kiyate
[03/14/2023 09:35:52] Gamling
[03/14/2023 09:35:45] Stealthmean
[03/14/2023 09:35:45] Miji
[03/14/2023 09:35:45] itzBreaker
[03/14/2023 09:35:45] kitykity
[03/14/2023 09:35:45] Kiyate
[03/14/2023 09:35:45] Gamling
[03/14/2023 09:35:43] Stealthmean
[03/14/2023 09:35:43] Miji
[03/14/2023 09:35:43] itzBreaker
[03/14/2023 09:35:43] kitykity
[03/14/2023 09:35:43] Kiyate
[03/14/2023 09:35:43] Gamling
[03/14/2023 09:35:43] Stealthmean
[03/14/2023 09:35:43] Miji
[03/14/2023 09:35:43] itzBreaker
[03/14/2023 09:35:43] kitykity
[03/14/2023 09:35:43] Kiyate
[03/14/2023 09:35:43] Gamling
[03/14/2023 09:35:43] Stealthmean
[03/14/2023 09:35:43] Miji
[03/14/2023 09:35:43] itzBreaker
[03/14/2023 09:35:43] kitykity
[03/14/2023 09:35:43] Kiyate
[03/14/2023 09:35:43] Gamling
[03/14/2023 09:35:43] Stealthmean
[03/14/2023 09:35:43] Miji
[03/14/2023 09:35:43] itzBreaker
[03/14/2023 09:35:43] kitykity
[03/14/2023 09:35:43] Kiyate
[03/14/2023 09:35:43] Gamling
[03/14/2023 09:35:41] Stealthmean
[03/14/2023 09:35:41] Miji
[03/14/2023 09:35:41] itzBreaker
[03/14/2023 09:35:41] kitykity
[03/14/2023 09:35:41] Kiyate
[03/14/2023 09:35:41] Gamling
[03/14/2023 09:35:41] Stealthmean
[03/14/2023 09:35:41] Miji
[03/14/2023 09:35:41] itzBreaker
[03/14/2023 09:35:41] kitykity
[03/14/2023 09:35:41] Kiyate
[03/14/2023 09:35:41] Gamling
[03/14/2023 09:35:41] Stealthmean
[03/14/2023 09:35:41] Miji
[03/14/2023 09:35:41] itzBreaker
[03/14/2023 09:35:41] kitykity
[03/14/2023 09:35:41] Kiyate
[03/14/2023 09:35:41] Gamling
[03/14/2023 09:34:09] Stealthmean
[03/14/2023 09:34:09] Miji
[03/14/2023 09:34:09] itzBreaker
[03/14/2023 09:34:09] kitykity
[03/14/2023 09:34:09] Kiyate
[03/14/2023 09:34:09] Gamling
[03/14/2023 09:31:30] Stealthmean
[03/14/2023 09:31:30] Miji
[03/14/2023 09:31:30] Apollo
[03/14/2023 09:31:30] itzBreaker
[03/14/2023 09:31:30] kitykity
[03/14/2023 09:31:30] Kiyate
[03/14/2023 09:31:30] Gamling
[03/14/2023 09:28:46] Stealthmean
[03/14/2023 09:28:46] Kush Koma
[03/14/2023 09:28:46] Miji
[03/14/2023 09:28:46] Apollo
[03/14/2023 09:28:46] itzBreaker
[03/14/2023 09:28:46] kitykity
[03/14/2023 09:28:46] Kiyate
[03/14/2023 09:28:46] Gamling
[03/14/2023 09:28:40] Kush Koma
[03/14/2023 09:28:40] Miji
[03/14/2023 09:28:40] Apollo
[03/14/2023 09:28:40] itzBreaker
[03/14/2023 09:28:40] kitykity
[03/14/2023 09:28:40] Kiyate
[03/14/2023 09:28:40] Gamling
[03/14/2023 09:28:38] Kush Koma
[03/14/2023 09:28:38] Miji
[03/14/2023 09:28:38] Apollo
[03/14/2023 09:28:38] itzBreaker
[03/14/2023 09:28:38] kitykity
[03/14/2023 09:28:38] Kiyate
[03/14/2023 09:28:38] Gamling
[03/14/2023 09:28:37] Kush Koma
[03/14/2023 09:28:37] Miji
[03/14/2023 09:28:37] Apollo
[03/14/2023 09:28:37] itzBreaker
[03/14/2023 09:28:37] kitykity
[03/14/2023 09:28:37] Kiyate
[03/14/2023 09:28:37] Gamling
[03/14/2023 09:28:33] Kush Koma
[03/14/2023 09:28:33] Miji
[03/14/2023 09:28:33] Apollo
[03/14/2023 09:28:33] itzBreaker
[03/14/2023 09:28:33] kitykity
[03/14/2023 09:28:33] Kiyate
[03/14/2023 09:28:33] Gamling
[03/14/2023 09:28:33] Kush Koma
[03/14/2023 09:28:33] Miji
[03/14/2023 09:28:33] Apollo
[03/14/2023 09:28:33] itzBreaker
[03/14/2023 09:28:33] kitykity
[03/14/2023 09:28:33] Kiyate
[03/14/2023 09:28:33] Gamling
[03/14/2023 09:28:27] Kush Koma
[03/14/2023 09:28:27] Miji
[03/14/2023 09:28:27] Apollo
[03/14/2023 09:28:27] itzBreaker
[03/14/2023 09:28:27] kitykity
[03/14/2023 09:28:27] Kiyate
[03/14/2023 09:28:27] Gamling
[03/14/2023 09:28:25] Kush Koma
[03/14/2023 09:28:25] Miji
[03/14/2023 09:28:25] Apollo
[03/14/2023 09:28:25] itzBreaker
[03/14/2023 09:28:25] kitykity
[03/14/2023 09:28:25] Kiyate
[03/14/2023 09:28:25] Gamling
[03/14/2023 09:28:24] Kush Koma
[03/14/2023 09:28:24] Miji
[03/14/2023 09:28:24] Apollo
[03/14/2023 09:28:24] itzBreaker
[03/14/2023 09:28:24] kitykity
[03/14/2023 09:28:24] Kiyate
[03/14/2023 09:28:24] Gamling
[03/14/2023 09:28:24] Kush Koma
[03/14/2023 09:28:24] Miji
[03/14/2023 09:28:24] Apollo
[03/14/2023 09:28:24] itzBreaker
[03/14/2023 09:28:24] kitykity
[03/14/2023 09:28:24] Kiyate
[03/14/2023 09:28:24] Gamling
[03/14/2023 09:28:22] WARNING: Character "Huskabyssold" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -Infinity to Infinity.
[03/14/2023 09:28:21] WARNING: Character "Husk" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -Infinity to Infinity.
[03/14/2023 09:28:21] WARNING: Received a potentially invalid ENTITY_POSITION message. Entity type does not match (server entity is not an item, client entity is Barotrauma.Item). Ignoring the message...
[03/14/2023 09:28:21] Kush Koma
[03/14/2023 09:28:21] WARNING: Received a potentially invalid ENTITY_POSITION message. Entity type does not match (server entity is not an item, client entity is Barotrauma.Item). Ignoring the message...
[03/14/2023 09:28:21] WARNING: Received a potentially invalid ENTITY_POSITION message. Entity type does not match (server entity is not an item, client entity is Barotrauma.Item). Ignoring the message...
[03/14/2023 09:28:21] WARNING: Received a potentially invalid ENTITY_POSITION message. Entity type does not match (server entity is not an item, client entity is Barotrauma.Item). Ignoring the message...
[03/14/2023 09:28:21] WARNING: Received a potentially invalid ENTITY_POSITION message. Entity type does not match (server entity is not an item, client entity is Barotrauma.Item). Ignoring the message...
[03/14/2023 09:28:21] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[03/14/2023 09:28:21] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[03/14/2023 09:28:21] Miji
[03/14/2023 09:28:21] itzBreaker
[03/14/2023 09:28:21] WARNING: Received a potentially invalid ENTITY_POSITION message. Entity type does not match (server entity is not an item, client entity is Barotrauma.Item). Ignoring the message...
[03/14/2023 09:28:21] WARNING: Received a potentially invalid ENTITY_POSITION message. Entity type does not match (server entity is not an item, client entity is Barotrauma.Item). Ignoring the message...
[03/14/2023 09:28:21] WARNING: Received a potentially invalid ENTITY_POSITION message. Entity type does not match (server entity is not an item, client entity is Barotrauma.Item). Ignoring the message...
[03/14/2023 09:28:21] WARNING: Received a potentially invalid ENTITY_POSITION message. Entity type does not match (server entity is not an item, client entity is Barotrauma.Item). Ignoring the message...
[03/14/2023 09:28:21] WARNING: Received a potentially invalid ENTITY_POSITION message. Entity type does not match (server entity is not an item, client entity is Barotrauma.Item). Ignoring the message...
[03/14/2023 09:28:21] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[03/14/2023 09:28:20] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[03/14/2023 09:28:20] Apollo
[03/14/2023 09:28:20] kitykity
[03/14/2023 09:28:20] Kiyate
[03/14/2023 09:28:20] WARNING: Received a potentially invalid ENTITY_POSITION message. Entity type does not match (server entity is not an item, client entity is Barotrauma.Item). Ignoring the message...
[03/14/2023 09:28:20] WARNING: Received a potentially invalid ENTITY_POSITION message. Entity type does not match (server entity is not an item, client entity is Barotrauma.Item). Ignoring the message...
[03/14/2023 09:28:20] WARNING: Received a potentially invalid ENTITY_POSITION message. Entity type does not match (server entity is not an item, client entity is Barotrauma.Item). Ignoring the message...
[03/14/2023 09:28:20] WARNING: Received a potentially invalid ENTITY_POSITION message. Entity type does not match (server entity is not an item, client entity is Barotrauma.Item). Ignoring the message...
[03/14/2023 09:28:20] WARNING: Received a potentially invalid ENTITY_POSITION message. Entity type does not match (server entity is not an item, client entity is Barotrauma.Item). Ignoring the message...
[03/14/2023 09:28:20] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[03/14/2023 09:28:20] WARNING: Received a potentially invalid ENTITY_POSITION message. Entity type does not match (server entity is not an item, client entity is Barotrauma.Item). Ignoring the message...
[03/14/2023 09:28:20] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[03/14/2023 09:28:20] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[03/14/2023 09:28:20] Gamling
[03/14/2023 09:28:20] WARNING: Received a potentially invalid ENTITY_POSITION message. Entity type does not match (server entity is not an item, client entity is Barotrauma.Item). Ignoring the message...
[03/14/2023 09:28:20] WARNING: Received a potentially invalid ENTITY_POSITION message. Entity type does not match (server entity is not an item, client entity is Barotrauma.Item). Ignoring the message...
[03/14/2023 09:28:20] WARNING: Received a potentially invalid ENTITY_POSITION message. Entity type does not match (server entity is not an item, client entity is Barotrauma.Item). Ignoring the message...
[03/14/2023 09:28:20] WARNING: Received a potentially invalid ENTITY_POSITION message. Entity type does not match (server entity is not an item, client entity is Barotrauma.Item). Ignoring the message...
[03/14/2023 09:28:20] WARNING: Received a potentially invalid ENTITY_POSITION message. Entity type does not match (server entity is not an item, client entity is Barotrauma.Item). Ignoring the message...
[03/14/2023 09:28:20] WARNING: Received a potentially invalid ENTITY_POSITION message. Entity type does not match (server entity is not an item, client entity is Barotrauma.Item). Ignoring the message...
[03/14/2023 09:28:20] WARNING: Received a potentially invalid ENTITY_POSITION message. Entity type does not match (server entity is not an item, client entity is Barotrauma.Item). Ignoring the message...
[03/14/2023 09:28:20] WARNING: Received a potentially invalid ENTITY_POSITION message. Entity type does not match (server entity is not an item, client entity is Barotrauma.Item). Ignoring the message...
[03/14/2023 09:28:20] WARNING: Potentially invalid damage modifier in "Marine Helmet, Wearable". Could not find any afflictions of the type "concussion". Did you mean to use an affliction identifier instead?
[03/14/2023 09:28:20] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[03/14/2023 09:28:19] WARNING: Received a potentially invalid ENTITY_POSITION message. Entity type does not match (server entity is not an item, client entity is Barotrauma.Item). Ignoring the message...
[03/14/2023 09:28:19] Received STARTGAMEFINALIZE packet. Round init status: Started
[03/14/2023 09:28:19] Received STARTGAMEFINALIZE packet. Round init status: Started
[03/14/2023 09:28:18] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[03/14/2023 09:28:18] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[03/14/2023 09:28:18] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[03/14/2023 09:28:18] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[03/14/2023 09:28:18] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[03/14/2023 09:28:18] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[03/14/2023 09:28:18] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[03/14/2023 09:28:18] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[03/14/2023 09:28:17] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[03/14/2023 09:28:17] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[03/14/2023 09:28:17] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[03/14/2023 09:28:17] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[03/14/2023 09:28:17] WARNING: Character "Human" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -30000 to 1300.
[03/14/2023 09:28:17] Task count: 0
[03/14/2023 09:28:17] Received STARTGAMEFINALIZE packet. Round init status: WaitingForStartGameFinalize
[03/14/2023 09:28:17] [CL LUA ERROR] C:/Users/edu23/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2547888957/Lua/Autorun/HazardousReactor_bothside.lua:(43,11-44,70): attempt to perform arithmetic on a userdata value
[03/14/2023 09:28:04] Generating an outpost for the start of the level... (Location: Aylesbury Outpost, level type: Outpost)
[03/14/2023 09:28:04] Level identifier: outpostlevel
[03/14/2023 09:28:03] WARNING: Potentially invalid damage modifier in "Marine Helmet, Wearable". Could not find any afflictions of the type "concussion". Did you mean to use an affliction identifier instead?
[03/14/2023 09:28:03] WARNING: Potentially invalid damage modifier in "Utility Mk-I Hardsuit, Wearable". Could not find any afflictions of the type "concussion". Did you mean to use an affliction identifier instead?
[03/14/2023 09:28:03] WARNING: Potentially invalid damage modifier in "Utility Mk-I Hardsuit, Wearable". Could not find any afflictions with the identifier "glowing". Did you mean to use an affliction type instead?
[03/14/2023 09:28:03] WARNING: Potentially invalid damage modifier in "Utility Mk-I Hardsuit, Wearable". Could not find any afflictions with the identifier "exposure". Did you mean to use an affliction type instead?
[03/14/2023 09:28:03] WARNING: Potentially invalid damage modifier in "Utility Mk-I Hardsuit, Wearable". Could not find any afflictions with the identifier "radiation". Did you mean to use an affliction type instead?
[03/14/2023 09:27:56] [SV LUA ERROR] C:/Users/edu23/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2547888957/Lua/Autorun/HazardousReactor_bothside.lua:(43,11-44,70): attempt to perform arithmetic on a userdata value
[03/14/2023 09:27:56] WARNING: Potentially invalid damage modifier in "Utility Mk-I Hardsuit (Mechanic), Wearable". Could not find any afflictions of the type "concussion". Did you mean to use an affliction identifier instead?
[03/14/2023 09:27:56] WARNING: Potentially invalid damage modifier in "Utility Mk-I Hardsuit (Mechanic), Wearable". Could not find any afflictions with the identifier "glowing". Did you mean to use an affliction type instead?
[03/14/2023 09:27:56] WARNING: Potentially invalid damage modifier in "Utility Mk-I Hardsuit (Mechanic), Wearable". Could not find any afflictions with the identifier "exposure". Did you mean to use an affliction type instead?
[03/14/2023 09:27:56] WARNING: Potentially invalid damage modifier in "Utility Mk-I Hardsuit (Mechanic), Wearable". Could not find any afflictions with the identifier "radiation". Did you mean to use an affliction type instead?
[03/14/2023 09:27:56] WARNING: Potentially invalid damage modifier in "Utility Mk-I Hardsuit, Wearable". Could not find any afflictions of the type "concussion". Did you mean to use an affliction identifier instead?
[03/14/2023 09:27:56] WARNING: Potentially invalid damage modifier in "Utility Mk-I Hardsuit, Wearable". Could not find any afflictions with the identifier "glowing". Did you mean to use an affliction type instead?
[03/14/2023 09:27:56] WARNING: Potentially invalid damage modifier in "Utility Mk-I Hardsuit, Wearable". Could not find any afflictions with the identifier "exposure". Did you mean to use an affliction type instead?
[03/14/2023 09:27:56] WARNING: Potentially invalid damage modifier in "Utility Mk-I Hardsuit, Wearable". Could not find any afflictions with the identifier "radiation". Did you mean to use an affliction type instead?
[03/14/2023 09:27:40] WARNING: Affliction "radiationresistance" contains effects with overlapping strength ranges. Only one effect can be active at a time, meaning one of the effects won't work.
[03/14/2023 09:27:35] Stealthmean
[03/14/2023 09:27:35] Miji
[03/14/2023 09:27:35] Apollo
[03/14/2023 09:27:35] itzBreaker
[03/14/2023 09:27:35] kitykity
[03/14/2023 09:27:35] Kiyate
[03/14/2023 09:27:35] Gamling
[03/14/2023 09:27:35] Stealthmean
[03/14/2023 09:27:35] Miji
[03/14/2023 09:27:35] Apollo
[03/14/2023 09:27:35] itzBreaker
[03/14/2023 09:27:35] kitykity
[03/14/2023 09:27:35] Kiyate
[03/14/2023 09:27:35] Gamling
[03/14/2023 09:27:35] Stealthmean
[03/14/2023 09:27:35] Miji
[03/14/2023 09:27:35] Apollo
[03/14/2023 09:27:35] itzBreaker
[03/14/2023 09:27:35] kitykity
[03/14/2023 09:27:35] Kiyate
[03/14/2023 09:27:35] Gamling
[03/14/2023 09:27:35] Stealthmean
[03/14/2023 09:27:35] Miji
[03/14/2023 09:27:35] Apollo
[03/14/2023 09:27:35] itzBreaker
[03/14/2023 09:27:35] kitykity
[03/14/2023 09:27:35] Kiyate
[03/14/2023 09:27:35] Gamling
[03/14/2023 09:27:35] Stealthmean
[03/14/2023 09:27:35] Miji
[03/14/2023 09:27:35] Apollo
[03/14/2023 09:27:35] itzBreaker
[03/14/2023 09:27:35] kitykity
[03/14/2023 09:27:35] Kiyate
[03/14/2023 09:27:35] Gamling
[03/14/2023 09:27:34] Stealthmean
[03/14/2023 09:27:34] Miji
[03/14/2023 09:27:34] Apollo
[03/14/2023 09:27:34] itzBreaker
[03/14/2023 09:27:34] kitykity
[03/14/2023 09:27:34] Kiyate
[03/14/2023 09:27:34] Gamling
[03/14/2023 09:27:34] Stealthmean
[03/14/2023 09:27:34] Miji
[03/14/2023 09:27:34] Apollo
[03/14/2023 09:27:34] itzBreaker
[03/14/2023 09:27:34] kitykity
[03/14/2023 09:27:34] Kiyate
[03/14/2023 09:27:34] Gamling
[03/14/2023 09:27:33] Stealthmean
[03/14/2023 09:27:33] Miji
[03/14/2023 09:27:33] Apollo
[03/14/2023 09:27:33] itzBreaker
[03/14/2023 09:27:33] kitykity
[03/14/2023 09:27:33] Kiyate
[03/14/2023 09:27:33] Gamling
[03/14/2023 09:27:33] Stealthmean
[03/14/2023 09:27:33] Miji
[03/14/2023 09:27:33] Apollo
[03/14/2023 09:27:33] itzBreaker
[03/14/2023 09:27:33] kitykity
[03/14/2023 09:27:33] Kiyate
[03/14/2023 09:27:33] Gamling
[03/14/2023 09:27:33] Stealthmean
[03/14/2023 09:27:33] Miji
```

**Comment by ZenithVal** [comment]
We had this same issue in our brand new campaign, it turned out to be the "Stations from Beyond." Mod for us.

Many mods are broken as of the most recent update due to some core game functionality changes. From your error log I can see the EK mods, those are all broken ATM according to the author. You'll need to disable them or wait for the authors to update them.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8adba4a65aa712349d97b22c9c93c3624964e261
