### ISSUE TITLE
[Unstable] Game Crash when selling items through submarine tab in shop (CargoManager.SellItems)

### ISSUE THREAD

**Issue by GaoDong64** [Regalis11/Barotrauma#11565]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

When selling items from the submarine tab of a shop, occasionally crashes the game once items are sold.

### Reproduction steps

1. Start a singleplayer campaign with dugong
2. Go to any shop
3. Go to submarine tab and sell all items
4. game will crash

### Bug prevalence

Happens regularly

### Version

v1.1.2.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 03/16/2023 15:30:12)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

C046658B8B25445758BE7EBED6696C33

Game version 1.1.3.0 (UnstableWindows, branch very-unstable-1.1, revision ae8c30120d)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla (34EC211), Selkie Drone Sub (FBC0D95), Pistol Shrimp (94B5C46), Longfin (T1 Transport) (B8B3628), Cuttlefish (06D748E), Super Plague Rat (2B391E2), ATK-89 "Sardine" (94EA46E), [AP] Warden (C94A7AD), Shipwrecks Extended (86CFB5E), Beacons Extended (94354F0), Apo-4A "Saber" (8B96E52), Wreck Locator (774CC80), [VH] The Iroh (B49665F), New Wrecks For Barotrauma (With sellable wrecks) (FAB1A6B), Amberjack (4F3049C), Winterhalter Test (E335430), Sea Snail (C4A77BD), Triggerfish (84040A0), Bluegill (FEF2AC9)
Level seed: Drumskinny Linea37
Loaded submarine: Dugong (F90623B9959CDAC51FBD577074D9F247)
Selected screen: Barotrauma.GameScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit
    GPU name: NVIDIA GeForce GTX 965M
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Specified argument was out of the range of valid values. (Parameter 'index') (System.ArgumentOutOfRangeException)
Target site: Void ThrowArgumentOutOfRangeException(System.Linq.ExceptionArgument)
Stack trace: 
   at System.Linq.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument)
   at System.Linq.Enumerable.ElementAt[TSource](IEnumerable`1 source, Int32 index)
   at Barotrauma.CargoManager.SellItems(Identifier storeIdentifier, List`1 itemsToSell, StoreTab sellingMode) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameSession\CargoManager.cs:line 174
   at Barotrauma.Store.SellItems() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\Store.cs:line 2139
   at Barotrauma.Store.<SetConfirmButtonBehavior>b__126_2(GUIButton b, Object o) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\Store.cs:line 2192
   at Barotrauma.GUIButton.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIButton.cs:line 263
   at Barotrauma.GUI.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1247
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 906
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[03/16/2023 15:28:52] Generating an outpost for the start of the level... (Location: Drumskinny Linea Outpost, level type: Outpost)
[03/16/2023 15:28:52] Level identifier: outpostlevel
[03/16/2023 15:27:03] Attempting to open ALC device "OpenAL Soft on Speakers (Realtek High Definition Audio)"
```

**Comment by GaoDong64** [comment]
Retested with no mods and issue still occurs.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2fd48a321d77da25e46ff41e82ed8106d5025c19

**Comment by Regalis11** [comment]
Actually no, not fixed: I referenced an incorrect issue in the commit message. The linked commit addressed https://github.com/Regalis11/Barotrauma/issues/11563

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c34a8746bbed5175b71d19d9886265ce5db47493
