### ISSUE TITLE
After publishing the submarine with "mod" version "2" can't save the submarine or click on it in the "publish" tab

### ISSUE THREAD

**Issue by UnibelUnibel** [Regalis11/Barotrauma#11581]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I've updated my submarine and selected "mod" version "2" when publishing it. After this, the submarine can be played on, can be downloaded without issues, but I can't update it as saving it causes crashes and I can't click on its image in the "publish" tab because it crashes too. Crash report attached.
[crashreport (7).txt](https://github.com/Regalis11/Barotrauma/files/11005329/crashreport.7.txt)
![Zrzut ekranu 2023-03-17 205607](https://user-images.githubusercontent.com/30161104/226017881-dba0e8c7-5e5d-4ae2-ba56-0822f2f4a5ff.jpg)

(The sub is Dionysus Deep Diver on steam workshop)
[Dionysus Deep Diver.zip](https://github.com/Regalis11/Barotrauma/files/11005386/Dionysus.Deep.Diver.zip)

### Bug prevalence

Happens every time I play

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 03/17/2023 20:43:39)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

14984747362A6EE8B69319866DD5C730

Game version 1.0.8.0 (ReleaseWindows, branch release/1.0-hotfix, revision 08ecc207eb)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla, Dionysus Deep Diver, Galdur Scout Pod, Barotraumatic Creature Pack, Zeus Deep Diver [OUTDATED - check Dionysus Deep Diver], Yangtze, Automatic oscilating searchlight, Automated searchlight, The Accident Button, Dionysus Deep Diver
Level seed: no level loaded
Loaded submarine: None
Selected screen: Barotrauma.MainMenuScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit
    GPU name: NVIDIA GeForce GTX 1660 Ti
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Index was outside the bounds of the array. (System.IndexOutOfRangeException)
Target site: System.String IncrementModVersion(System.String)
Stack trace: 
   at Barotrauma.ModProject.IncrementModVersion(String modVersion) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\ContentManagement\ContentPackage\ModProject.cs:line 129
   at Barotrauma.Steam.MutableWorkshopMenu.PopulatePublishTab(Either`2 itemOrPackage, GUIFrame parentFrame) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Steam\WorkshopMenu\Mutable\PublishTab.cs:line 245
   at Barotrauma.Steam.MutableWorkshopMenu.<>c__DisplayClass28_0.<CreateWorkshopItemDetailContainer>b__2(Either`2 itemOrPackage) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Steam\WorkshopMenu\Mutable\ItemList.cs:line 106
   at Barotrauma.Steam.MutableWorkshopMenu.<>c__DisplayClass32_0.<CreateWorkshopItemOrPackageList>b__1(GUIComponent component, Object userData) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Steam\WorkshopMenu\Mutable\ItemList.cs:line 171
   at Barotrauma.GUIListBox.Select(Int32 childIndex, Force force, AutoScroll autoScroll, TakeKeyBoardFocus takeKeyBoardFocus, PlaySelectSound playSelectSound) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIListBox.cs:line 1068
   at Barotrauma.GUIListBox.UpdateChildrenRect() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIListBox.cs:line 788
   at Barotrauma.GUIListBox.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIListBox.cs:line 908
   at Barotrauma.GUI.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1247
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 906
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[03/17/2023 20:43:29] WARNING: Entity "suicidevest" has no name!
[03/17/2023 20:43:29] WARNING: Entity "raining" has no name!
[03/17/2023 20:43:29] WARNING: Entity "xandepthchargeshell" has no name!
[03/17/2023 20:43:29] WARNING: Entity "raining" has no name!
[03/17/2023 20:43:29] WARNING: Entity "suicidevest" has no name!
[03/17/2023 20:43:29] WARNING: Entity "xandepthchargeshell" has no name!
[03/17/2023 20:43:24] WARNING: Tried to restore enabled packages multiple times/without performing a backup
[03/17/2023 20:41:08] Unibel
[03/17/2023 20:41:08] WARNING: Character "Mudraptor_unarmored" has a negative crush depth. Previously the crush depths were defined as display units (e.g. -30000 would correspond to 300 meters below the level), but now they're in meters (e.g. 3000 would correspond to a depth of 3000 meters displayed on the nav terminal). Changing the crush depth from -Infinity to Infinity.
[03/17/2023 20:41:07] Received STARTGAMEFINALIZE packet. Round init status: Started
[03/17/2023 20:41:07] Task count: 0
[03/17/2023 20:41:07] Received STARTGAMEFINALIZE packet. Round init status: WaitingForStartGameFinalize
[03/17/2023 20:41:04] Could not find a suitable module for the location type LocationType (None). Module flag: Airlock.
[03/17/2023 20:41:03] Generating an outpost for the start of the level... (Location: Paaru, level type: LocationConnection)
[03/17/2023 20:41:03] Level identifier: coldcavernsbasic
[03/17/2023 20:40:45] WARNING: Affliction "wasteinfection" contains effects with overlapping strength ranges. Only one effect can be active at a time, meaning one of the effects won't work.
[03/17/2023 20:40:39] Unibel
[03/17/2023 20:38:59] Unibel
[03/17/2023 20:38:57] Server running slowly (57 updates/s)!
[03/17/2023 20:38:56] Received STARTGAMEFINALIZE packet. Round init status: Started
[03/17/2023 20:38:56] Task count: 0
[03/17/2023 20:38:56] Received STARTGAMEFINALIZE packet. Round init status: WaitingForStartGameFinalize
[03/17/2023 20:38:52] Generating an outpost for the start of the level... (Location: Harmonia Linea Outpost, level type: Outpost)
[03/17/2023 20:38:52] Level identifier: outpostlevel
[03/17/2023 20:38:40] WARNING: Affliction "wasteinfection" contains effects with overlapping strength ranges. Only one effect can be active at a time, meaning one of the effects won't work.
[03/17/2023 20:38:25] Lobby created!
[03/17/2023 20:35:37] WARNING: Entity "suicidevest" has no name!
[03/17/2023 20:35:37] WARNING: Entity "raining" has no name!
[03/17/2023 20:35:37] WARNING: Entity "xandepthchargeshell" has no name!
[03/17/2023 20:35:37] WARNING: Entity "raining" has no name!
[03/17/2023 20:35:37] WARNING: Entity "suicidevest" has no name!
[03/17/2023 20:35:37] WARNING: Entity "xandepthchargeshell" has no name!
[03/17/2023 20:35:37] WARNING: Entity "suicidevest" has no name!
[03/17/2023 20:35:37] WARNING: Entity "raining" has no name!
[03/17/2023 20:35:37] WARNING: Entity "xandepthchargeshell" has no name!
[03/17/2023 20:35:37] WARNING: Entity "raining" has no name!
[03/17/2023 20:35:37] WARNING: Entity "suicidevest" has no name!
[03/17/2023 20:35:37] WARNING: Entity "xandepthchargeshell" has no name!
[03/17/2023 20:34:57] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: C:/Users/patwo/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2831987252/Items/Herbs/contaminationv1.png, size: 129x128)
[03/17/2023 20:34:57] WARNING: Unrecognized element in affliction "cytokine" (Affliction)
[03/17/2023 20:34:57] WARNING: Unrecognized element in affliction "cytokine" (Affliction)
[03/17/2023 20:34:57] Overriding an affliction or a buff with the identifier 'watchersgaze' using the file 'C:/Users/patwo/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2831987252/Afflictions/VANAfflictions.xml'
[03/17/2023 20:34:32] Attempting to open ALC device "OpenAL Soft on Głośniki (Realtek(R) Audio)"
[03/17/2023 20:34:30] Logged in as Unibel (SteamID STEAM_1:0:49555430)
```

**Comment by UnibelUnibel** [comment]
Manual fix for this bug: "go to the barotrauma folder, open up local mods, your sub,  filelist.xml and change modversion to your fitting and see if it changes anything". (Thanks lewkaj from Barotrauam Discord)
I've changed "mod version" to be smaller than one, in this case "1.0.8" and everything went back to normal.

Still, the bug exists.

**Comment by Regalis11** [comment]
Thank you for the report!

Fixed in https://github.com/Regalis11/Barotrauma-development/commit/778ffa9b687023da99484fed8deaeea9af03f73b (commit in our private repo).

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
