### ISSUE TITLE
Crash when using wikiimage_sub when wikiimage.png is open in another program

### ISSUE THREAD

**Issue by Jade-Harleyy** [Regalis11/Barotrauma#11605]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When I used the `wikiimage_sub` command while I had the wikiimage.png file open in another program, the game crashed to desktop.

This was definitely my fault, but I think it'd be preferable if it produced an error instead of crashing.

### Reproduction steps

1. Open any submarine in the submarine editor
2. Use the `wikiimage_sub` command
3. Open wikiimage.png with any external program
4. Use the `wikiimage_sub` command again

### Bug prevalence

Just once

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 03/19/2023 18:34:05)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

14984747362A6EE8B69319866DD5C730

Game version 1.0.8.0 (ReleaseWindows, branch release/1.0-hotfix, revision 08ecc207eb)
Graphics mode: 2560x1440 (BorderlessWindowed)
VSync OFF
Language: English
Selected content packages: Vanilla
Level seed: no level loaded
Loaded submarine: HumpbackPirate (8428F750FB6024786028F442EF34CC59)
Selected screen: Barotrauma.SubEditorScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19045.0 64 bit
    GPU name: NVIDIA GeForce GTX 1080
    Display mode: {Width:2560 Height:1440 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: The process cannot access the file 'C:\SteamLibrary\steamapps\common\Barotrauma\wikiimage.png' because it is being used by another process. (System.IO.IOException)
Target site: Microsoft.Win32.SafeHandles.SafeFileHandle CreateFile(System.String, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare, System.IO.FileOptions)
Stack trace: 
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at Barotrauma.IO.File.Open(String path, FileMode mode, FileAccess access, Nullable`1 share) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SafeIO.cs:line 400
   at Barotrauma.WikiImage.Create(Submarine sub) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Utils\WikiImage.cs:line 153
   at Barotrauma.DebugConsole.<>c.<InitProjectSpecific>b__23_23(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\DebugConsole.cs:line 643
   at Barotrauma.DebugConsole.Command.Execute(String[] args) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\DebugConsole.cs:line 86
   at Barotrauma.DebugConsole.ExecuteCommand(String command) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\DebugConsole.cs:line 0
   at Barotrauma.DebugConsole.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\DebugConsole.cs:line 195
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 881
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[03/19/2023 18:34:05] wikiimage_sub
[03/19/2023 18:33:34] wikiimage_sub
[03/19/2023 18:21:51] wikiimage_sub
[03/19/2023 18:21:25] wikiimage_sub
[03/19/2023 18:20:57] wikiimage_sub
[03/19/2023 18:17:29] wikiimage_sub
[03/19/2023 18:17:09] wikiimage_sub
[03/19/2023 18:13:07] wikiimage_sub
[03/19/2023 18:11:31] wikiimage_sub
[03/19/2023 18:09:58] wikiimage_sub
[03/19/2023 18:09:16] wikiimage_sub
[03/19/2023 18:08:27] wikiimage_sub
[03/19/2023 18:07:23] wikiimage_sub
[03/19/2023 18:06:34] wikiimage_sub
[03/19/2023 18:05:42] wikiimage_sub
[03/19/2023 18:04:45] wikiimage_sub
[03/19/2023 18:02:59] wikiimage_sub
[03/19/2023 18:01:33] wikiimage_sub
[03/19/2023 17:53:56] wikiimage_sub
[03/19/2023 17:05:38] wikiimage_sub
[03/19/2023 17:04:43] wikiimage_sub
[03/19/2023 16:51:15] wikiimage_sub
[03/19/2023 16:08:27] Attempting to open ALC device "OpenAL Soft on Speakers (Realtek(R) Audio)"
[03/19/2023 16:08:22] Logged in as Jade Harley (SteamID STEAM_1:0:476582823)
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/59cf15d4862e307aa2bc25dfcb7a7d8740081d8e

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
