### ISSUE TITLE
Handheld Itemfinder crash a game

### ISSUE THREAD

**Issue by Gerangam** [Regalis11/Barotrauma#11626]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

An attempt to use Handheld Itemfinder outside of a submarine or any other structure leads to a crash

### Reproduction steps

1. Pickup a Handheld Itemfinder in your inventory
2. Go outside a sub
3. Take a Handheld itemfinder in your hand
4. Click on the text input window in the Handheld Itemfinder interfaces
5. Suffer

### Bug prevalence

Happens every time I play

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 03/21/2023 21:14:12)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

14984747362A6EE8B69319866DD5C730

Game version 1.0.8.0 (ReleaseWindows, branch release/1.0-hotfix, revision 08ecc207eb)
Graphics mode: 1600x900 (BorderlessWindowed)
VSync OFF
Language: Russian
Selected content packages: Vanilla
Level seed: no level loaded
Loaded submarine: Camel (D12BB7674F200D4D5AEED1F2F7879EB5)
Selected screen: Barotrauma.GameScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit
    GPU name: NVIDIA GeForce GTX 1660 SUPER
    Display mode: {Width:1600 Height:900 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Boolean VisibleOnItemFinder(Barotrauma.Item)
Stack trace: 
   at Barotrauma.Items.Components.MiniMap.VisibleOnItemFinder(Item it) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Components\Machines\MiniMap.cs:line 406
   at Barotrauma.Items.Components.MiniMap.<CreateGUI>b__62_9(Item it) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Components\Machines\MiniMap.cs:line 369
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Immutable.ImmutableHashSet`1.Union(IEnumerable`1 other, MutationInput origin)
   at System.Collections.Immutable.ImmutableHashSet`1.Union(IEnumerable`1 items, Boolean avoidWithComparer)
   at System.Collections.Immutable.ImmutableHashSet.ToImmutableHashSet[TSource](IEnumerable`1 source)
   at Barotrauma.Items.Components.MiniMap.<CreateGUI>b__62_3(GUITextBox sender, Keys key) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Components\Machines\MiniMap.cs:line 369
   at Barotrauma.GUITextBox.Select(Int32 forcedCaretIndex, Boolean ignoreSelectSound) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBox.cs:line 373
   at Barotrauma.GUITextBox.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBox.cs:line 481
   at Barotrauma.GUI.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1247
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 906
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[03/21/2023 21:12:58] Attempting to open ALC device "OpenAL Soft on Динамики (HECATE G2 II GAMING HEADSET)"
[03/21/2023 21:12:56] Logged in as Gerangam (SteamID STEAM_1:1:60007339)
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ccc9f99a59f32b6670b227c116520e1fa5fc0f02

**Comment by Gerangam** [comment]
What this link mean?

**Comment by duarm** [comment]
> What this link mean?

it means they fixed the issue, that's a link to their private project they always leave once they fix something to let you know it's fixed and also to keep track of the fixed issues internally, it will land on the next hotfix or you can opt-in into the unstable branch on steam.

**Comment by Rokvach** [comment]
I was still able to reproduce this crash

Do theo original repro steps but after you've gone outside
1. Still hold the itemfinder
2. Swim to airlock so the sub appears on the itemfinder
3. Select the textbox and write something on it
4. Swim outside so the sub disappears, notice that the textbox is still visible
5. Select the textbox
6. Crash

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
