### ISSUE TITLE
having "2" as a mods version number crashes the game

### ISSUE THREAD

**Issue by Mannatwo** [Regalis11/Barotrauma#11649]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

i have a custom submarine mod that i wanted to update.
saving a custom submarine automatically increments the mods version number.
the method that handles this incrementation seems to struggle with any form of non-conformity when it comes to what is being incremented.
the previous version number, that it tried to increment upon me saving the submarine was "2".
needless to say, an exception was thrown and the submarine refused to save. see the first attached screenshot.
i thought that it might have been faulty files, so i deleted the local copy of the mod entirely and used the "create local copy" feature when looking at published mods.
a similar error was thrown, this time in the console. see the second attached screenshot.
any attempt to view the workshop object ingame while this local copy with the version number "2" was in the localmods folder resulted in the game crashing. see the third attached screenshot and the attached crashlog.

### Reproduction steps

For the part that doesn't crash:

1. Create a custom submarine
2. Publish it, with the version number being "2"
3. Edit and save the custom submarine. The game should throw an error.

For the part that does crash:

4. Delete the local copy of the same published mod
5. Ingame, View the published mod. A prompt to create a local copy should appear. Accept it. The game should create a local copy but throw an error in the process.
6. Ingame, View the published mod again. The game should crash.

### Bug prevalence

Happens regularly

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

![the first error, displayed after saving a custom submarine with version number "2"](https://cdn.discordapp.com/attachments/954858082742202419/1088782816579432468/image.png)
![the second error, displayed after creating a local copy of a custom submarine with version number "2"](https://cdn.discordapp.com/attachments/954858082742202419/1088783109622861835/image.png)
![the game crashing after viewing a published custom submarine workshop object with version number "2"](https://cdn.discordapp.com/attachments/954858082742202419/1088783237842739260/image.png)

```shell
Barotrauma Client crash report (generated on 03/24/2023 12:20:21)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

14984747362A6EE8B69319866DD5C730

Game version 1.0.8.0 (ReleaseWindows, branch release/1.0-hotfix, revision 08ecc207eb)
Graphics mode: 1600x900 (Windowed)
VSync ON
Language: English
Selected content packages: Vanilla, CsForBarotrauma, Lua For Barotrauma, Lua Audio Overhaul, BetterHealthUI, Neurotrauma, MannaBuildables, Neurotrauma Tutorial map: Mercy Hospital
Level seed: no level loaded
Loaded submarine: None
Selected screen: Barotrauma.MainMenuScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19045.0 64 bit
    GPU name: NVIDIA GeForce GTX 1070
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Index was outside the bounds of the array. (System.IndexOutOfRangeException)
Target site: System.String IncrementModVersion(System.String)
Stack trace: 
   at Barotrauma.ModProject.IncrementModVersion(String modVersion) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\ContentManagement\ContentPackage\ModProject.cs:line 129
   at Barotrauma.Steam.MutableWorkshopMenu.PopulatePublishTab(Either`2 itemOrPackage, GUIFrame parentFrame) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Steam\WorkshopMenu\Mutable\PublishTab.cs:line 245
   at Barotrauma.Steam.MutableWorkshopMenu.<>c__DisplayClass28_0.<CreateWorkshopItemDetailContainer>b__2(Either`2 itemOrPackage) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Steam\WorkshopMenu\Mutable\ItemList.cs:line 106
   at Barotrauma.Steam.MutableWorkshopMenu.<>c__DisplayClass32_0.<CreateWorkshopItemOrPackageList>b__1(GUIComponent component, Object userData) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Steam\WorkshopMenu\Mutable\ItemList.cs:line 171
   at Barotrauma.GUIListBox.Select(Int32 childIndex, Force force, AutoScroll autoScroll, TakeKeyBoardFocus takeKeyBoardFocus, PlaySelectSound playSelectSound) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIListBox.cs:line 1068
   at Barotrauma.GUIListBox.UpdateChildrenRect() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIListBox.cs:line 788
   at Barotrauma.GUIListBox.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIListBox.cs:line 908
   at Barotrauma.GUI.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1247
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 906
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58
```

**Comment by Mannatwo** [comment]
oops
already reported
i apologize for the inconvenience
