### ISSUE TITLE
Rope Crash (again)

### ISSUE THREAD

**Issue by Hifume** [Regalis11/Barotrauma#11666]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Harpoon rope bug is back! I created a previous issue that was closed after being unrecreatable, then another issue was created when the issue was thought to be resolved... last time I was using a lot of mods, this time 0 mods in use.

I was server host, another player shot me with harpoons while I was in late stage husk infection. We were both inside the submarine, I was passed out on the floor dying from internal damage (husk). After the second harpoon was fired, both of our clients crashed.

### Reproduction steps

This bug has been difficult to reproduce in the past, and inconsistent on how it happens, but here's what I did:
1. Load an existing campaign.
2. Put on a diving suit.
3. Get husk infection
4. While dying from internal damage (husk infection), have another player shoot you with harpoon gun repeatedly. It's possible that a harpoon was fired on the same frame that my player died (deceased).

### Bug prevalence

Happens every now and then

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 03/26/2023 16:43:26)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

14984747362A6EE8B69319866DD5C730

Game version 1.0.8.0 (ReleaseWindows, branch release/1.0-hotfix, revision 08ecc207eb)
Graphics mode: 2560x1440 (BorderlessWindowed)
VSync OFF
Language: English
Selected content packages: Vanilla
Level seed: Delphi Flexus36Apep48
Loaded submarine: Barsuk (08ED99B5BFBB03E9448D9A90EF145144)
Selected screen: Barotrauma.GameScreen
SteamManager initialized
Client (Round had started)

System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit
    GPU name: AMD Radeon RX 6950 XT
    Display mode: {Width:2560 Height:1440 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void Update(Single, Barotrauma.Camera)
Stack trace: 
   at Barotrauma.Items.Components.Rope.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Rope.cs:line 0
   at Barotrauma.Item.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 1972
   at Barotrauma.MapEntity.UpdateAll(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\MapEntity.cs:line 649
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 248
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 881
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[03/26/2023 16:43:25] Doctor Chad
[03/26/2023 16:43:25] Cpt. Stan
[03/26/2023 16:33:13] WARNING: Received a potentially invalid ENTITY_POSITION message.Entity identifier does not match (server entity is smallcrawleregg, client entity is coilgunbolt). Ignoring the message...
[03/26/2023 16:32:44] WARNING: Received a potentially invalid ENTITY_POSITION message.Entity identifier does not match (server entity is smallcrawleregg, client entity is coilgunbolt). Ignoring the message...
[03/26/2023 16:32:43] WARNING: Received a potentially invalid ENTITY_POSITION message.Entity identifier does not match (server entity is smallcrawleregg, client entity is coilgunbolt). Ignoring the message...
[03/26/2023 16:27:41] Doctor Chad
[03/26/2023 16:27:41] Cpt. Stan
[03/26/2023 16:27:29] Server running slowly (58 updates/s)!
[03/26/2023 16:27:26] Doctor Chad
[03/26/2023 16:27:26] Cpt. Stan
[03/26/2023 16:27:25] Received STARTGAMEFINALIZE packet. Round init status: Started
[03/26/2023 16:27:23] Task count: 0
[03/26/2023 16:27:23] Received STARTGAMEFINALIZE packet. Round init status: WaitingForStartGameFinalize
[03/26/2023 16:27:21] Generating an outpost for the start of the level... (Location: Delphi Flexus Mining Facility, level type: LocationConnection)
[03/26/2023 16:27:20] Generating an outpost for the end of the level... (Location: Apep, level type: LocationConnection)
[03/26/2023 16:27:20] Level identifier: coldcavernstransition
[03/26/2023 16:27:16] Server running slowly (58 updates/s)!
[03/26/2023 16:27:14] Doctor Chad
[03/26/2023 16:27:14] Cpt. Stan
[03/26/2023 16:27:13] Doctor Chad
[03/26/2023 16:27:13] Cpt. Stan
[03/26/2023 16:24:46] Doctor Chad
[03/26/2023 16:24:46] Cpt. Stan
[03/26/2023 16:24:44] Server running slowly (58 updates/s)!
[03/26/2023 16:24:40] Doctor Chad
[03/26/2023 16:24:40] Cpt. Stan
[03/26/2023 16:24:38] Received STARTGAMEFINALIZE packet. Round init status: Started
[03/26/2023 16:24:38] Task count: 0
[03/26/2023 16:24:38] Received STARTGAMEFINALIZE packet. Round init status: WaitingForStartGameFinalize
[03/26/2023 16:24:36] Generating an outpost for the start of the level... (Location: Apep, level type: Outpost)
[03/26/2023 16:24:35] Level identifier: outpostlevel
[03/26/2023 16:22:30] Lobby created!
[03/26/2023 16:22:00] Attempting to open ALC device "OpenAL Soft on Headphones (High Definition Audio Device)"
[03/26/2023 16:21:56] Logged in as Hifume (SteamID STEAM_1:1:204152888)
```

**Comment by beenoc** [comment]
We just had a crash with an identical error message. This one was caused by 2 players on a dive fighting a crawler - one of them fired a harpoon at the crawler and it crashed. Below is the summary of what each player saw: P1 is the player who fired the harpoon, P2 is the other player. The other 3 players are all on the submarine and not really doing anything.

P1: I was dragging P2 with the scooter - the crawler attacked P2. P2 pulled out a revolver and shot the crawler. I pulled out the harpoon gun and shot 3 harpoons - the first hit, the second hit a wall and stopped normally, the third harpoon hit the same wall but kept going, stretching the rope with it. The game crashes shortly afterwards.

P2: We get attacked by the crawler. I am holding a slime mold in my left hand and revolver in my right. I tell P1 to let go of me and fire 5 rounds at the revolver. P1 pulls out the harpoon gun and fires his harpoons. The crawler dies, I go to find P1, and I just find a disembodied harpoon gun with a rope coming out of it - the game crashes shortly afterwards.

This only just happened and some of the players got off because it was late so we aren't able to recreate it - the log is below and the save is attached.
```
Barotrauma Client crash report (generated on 03/31/2023 22:03:41)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

14984747362A6EE8B69319866DD5C730

Game version 1.0.8.0 (ReleaseWindows, branch release/1.0-hotfix, revision 08ecc207eb)
Graphics mode: 2560x1440 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla, Remora 2.0, Remora 2.0 2.0, Remora 2.0 3.0, RemoraDrone2, Shelf unit, DIY Reactor Controllers, Winterhalter 2.0, Winterhalter 3.0, Winterhalter 3.5, Winterhalter UltraMax, droneframe 1, Winterhalter Drone, Winterhalter GigantoMax, AutoReactor, AutoReactor w Alert, Reactor Automation mk2, Herring, The Coffin, ATK-89 "Sardine", Medusa, M870, K-28 Alligator, The Peregrine, [VH] The Iroh, Escape van, Blorf | A purposefully terrible submarine, R-29 Hammerhead [1.0 Update], Cyclops Mk-II
Level seed: Brunhes7Ihegga57
Loaded submarine: Barsuk (820B72A23A815AC717F6B0E3003119F0)
Selected screen: Barotrauma.GameScreen
SteamManager initialized
Client (Round had started)

System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit
    GPU name: NVIDIA GeForce RTX 2070 SUPER
    Display mode: {Width:2560 Height:1440 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void Update(Single, Barotrauma.Camera)
Stack trace: 
   at Barotrauma.Items.Components.Rope.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Rope.cs:line 0
   at Barotrauma.Item.Update+(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 1972
   at Barotrauma.MapEntity.UpdateAll(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\MapEntity.cs:line 649
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 248
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 881
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[03/31/2023 21:33:19] Curie
[03/31/2023 21:33:19] Rocky Olympus
[03/31/2023 21:33:19] Captain Bitchman
[03/31/2023 21:33:18] Augur of Lowest Terrestrial Area
[03/31/2023 21:33:18] Donson Dave
[03/31/2023 21:33:17] Received STARTGAMEFINALIZE packet. Round init status: Started
[03/31/2023 21:33:15] Task count: 0
[03/31/2023 21:33:15] Received STARTGAMEFINALIZE packet. Round init status: WaitingForStartGameFinalize
[03/31/2023 21:33:08] Server running slowly (56 updates/s)!
[03/31/2023 21:33:06] Generating an outpost for the start of the level... (Location: Brunhes Fortification, level type: LocationConnection)
[03/31/2023 21:33:06] Level identifier: ridgebasic
[03/31/2023 21:32:52] Curie
[03/31/2023 21:32:52] Rocky Olympus
[03/31/2023 21:32:52] Captain Bitchman
[03/31/2023 21:32:52] Augur of Lowest Terrestrial Area
[03/31/2023 21:32:52] Donson Dave
[03/31/2023 21:32:52] Curie
[03/31/2023 21:32:52] Rocky Olympus
[03/31/2023 21:32:52] Captain Bitchman
[03/31/2023 21:32:52] Augur of Lowest Terrestrial Area
[03/31/2023 21:32:52] Donson Dave
[03/31/2023 21:32:51] Curie
[03/31/2023 21:32:51] Rocky Olympus
[03/31/2023 21:32:51] Captain Bitchman
[03/31/2023 21:32:51] Augur of Lowest Terrestrial Area
[03/31/2023 21:32:51] Donson Dave
[03/31/2023 21:07:24] Curie
[03/31/2023 21:07:24] Rocky Olympus
[03/31/2023 21:07:24] Captain Bitchman
[03/31/2023 21:07:24] Augur of Lowest Terrestrial Area
[03/31/2023 21:07:24] Donson Dave
[03/31/2023 21:07:21] Curie
[03/31/2023 21:07:20] Rocky Olympus
[03/31/2023 21:07:20] Captain Bitchman
[03/31/2023 21:07:20] Augur of Lowest Terrestrial Area
[03/31/2023 21:07:20] Donson Dave
[03/31/2023 21:07:18] Received STARTGAMEFINALIZE packet. Round init status: Started
[03/31/2023 21:07:18] Task count: 0
[03/31/2023 21:07:18] Received STARTGAMEFINALIZE packet. Round init status: WaitingForStartGameFinalize
[03/31/2023 21:07:13] Generating an outpost for the start of the level... (Location: Brunhes Fortification, level type: Outpost)
[03/31/2023 21:07:13] Level identifier: outpostlevel
[03/31/2023 21:07:05] Server running slowly (57 updates/s)!
[03/31/2023 20:24:56] WARNING: Received a potentially invalid ENTITY_POSITION message.Entity identifier does not match (server entity is smallcrawleregg, client entity is coilgunbolt). Ignoring the message...
[03/31/2023 20:24:46] WARNING: Received a potentially invalid ENTITY_POSITION message.Entity identifier does not match (server entity is smallcrawleregg, client entity is coilgunbolt). Ignoring the message...
[03/31/2023 20:24:46] WARNING: Received a potentially invalid ENTITY_POSITION message.Entity identifier does not match (server entity is smallcrawleregg, client entity is coilgunbolt). Ignoring the message...
[03/31/2023 20:24:07] Curie
[03/31/2023 20:24:07] Rocky Olympus
[03/31/2023 20:24:07] Captain Bitchman
[03/31/2023 20:24:07] Augur of Lowest Terrestrial Area
[03/31/2023 20:24:07] Donson Dave
[03/31/2023 20:24:04] Rocky Olympus
[03/31/2023 20:24:04] Captain Bitchman
[03/31/2023 20:24:04] Augur of Lowest Terrestrial Area
[03/31/2023 20:24:04] Donson Dave
[03/31/2023 20:23:29] Rocky Olympus
[03/31/2023 20:23:29] Captain Bitchman
[03/31/2023 20:23:29] Augur of Lowest Terrestrial Area
[03/31/2023 20:23:29] Donson Dave
[03/31/2023 20:23:28] Rocky Olympus
[03/31/2023 20:23:28] Captain Bitchman
[03/31/2023 20:23:28] Augur of Lowest Terrestrial Area
[03/31/2023 20:23:28] Donson Dave
[03/31/2023 20:23:28] Rocky Olympus
[03/31/2023 20:23:28] Captain Bitchman
[03/31/2023 20:23:28] Augur of Lowest Terrestrial Area
[03/31/2023 20:23:28] Donson Dave
[03/31/2023 20:23:28] Rocky Olympus
[03/31/2023 20:23:28] Captain Bitchman
[03/31/2023 20:23:28] Augur of Lowest Terrestrial Area
[03/31/2023 20:23:28] Donson Dave
[03/31/2023 20:22:19] Rocky Olympus
[03/31/2023 20:22:19] Captain Bitchman
[03/31/2023 20:22:19] Augur of Lowest Terrestrial Area
[03/31/2023 20:22:19] Donson Dave
[barotrauma crash save file.zip](https://github.com/Regalis11/Barotrauma/files/11128234/barotrauma.crash.save.file.zip)

[03/31/2023 20:22:17] Rocky Olympus
[03/31/2023 20:22:17] Captain Bitchman
[03/31/2023 20:22:17] Augur of Lowest Terrestrial Area
[03/31/2023 20:22:17] Donson Dave
[03/31/2023 20:22:15] Rocky Olympus
[03/31/2023 20:22:15] Captain Bitchman
[03/31/2023 20:22:15] Augur of Lowest Terrestrial Area
[03/31/2023 20:22:14] Donson Dave
[03/31/2023 20:22:13] Server running slowly (56 updates/s)!
[03/31/2023 20:22:13] Received STARTGAMEFINALIZE packet. Round init status: Started
[03/31/2023 20:22:11] Task count: 0
[03/31/2023 20:22:11] Received STARTGAMEFINALIZE packet. Round init status: WaitingForStartGameFinalize
[03/31/2023 20:22:05] Generating an outpost for the start of the level... (Location: Brunhes Fortification, level type: LocationConnection)
[03/31/2023 20:22:04] Generating an outpost for the end of the level... (Location: Serac, level type: LocationConnection)
[03/31/2023 20:22:04] Level identifier: ridgebasic
[03/31/2023 20:21:56] Rocky Olympus
[03/31/2023 20:21:56] Captain Bitchman
[03/31/2023 20:21:56] Curie
[03/31/2023 20:21:56] Augur of Lowest Terrestrial Area
[03/31/2023 20:21:56] Donson Dave
[03/31/2023 20:21:56] Rocky Olympus
[03/31/2023 20:21:56] Captain Bitchman
[03/31/2023 20:21:56] Curie
[03/31/2023 20:21:56] Augur of Lowest Terrestrial Area
[03/31/2023 20:21:56] Donson Dave
[03/31/2023 20:21:55] Rocky Olympus
[03/31/2023 20:21:55] Captain Bitchman
[03/31/2023 20:21:55] Curie
[03/31/2023 20:21:55] Augur of Lowest Terrestrial Area
[03/31/2023 20:21:55] Donson Dave
[03/31/2023 20:21:55] Rocky Olympus
[03/31/2023 20:21:55] Captain Bitchman
[03/31/2023 20:21:55] Curie
[03/31/2023 20:21:55] Augur of Lowest Terrestrial Area
[03/31/2023 20:21:55] Donson Dave
[03/31/2023 20:21:55] Rocky Olympus
[03/31/2023 20:21:55] Captain Bitchman
[03/31/2023 20:21:55] Curie
[03/31/2023 20:21:55] Augur of Lowest Terrestrial Area
[03/31/2023 20:21:55] Donson Dave
[03/31/2023 20:21:54] Rocky Olympus
[03/31/2023 20:21:54] Captain Bitchman
[03/31/2023 20:21:54] Curie
[03/31/2023 20:21:54] Augur of Lowest Terrestrial Area
[03/31/2023 20:21:54] Donson Dave
[03/31/2023 20:21:54] Rocky Olympus
[03/31/2023 20:21:54] Captain Bitchman
[03/31/2023 20:21:54] Curie
[03/31/2023 20:21:54] Augur of Lowest Terrestrial Area
[03/31/2023 20:21:54] Donson Dave
[03/31/2023 20:21:54] Curie
[03/31/2023 20:01:49] Rocky Olympus
[03/31/2023 20:01:49] Captain Bitchman
[03/31/2023 20:01:49] Curie
[03/31/2023 20:01:49] Augur of Lowest Terrestrial Area
[03/31/2023 20:01:49] Donson Dave
[03/31/2023 20:01:42] Rocky Olympus
[03/31/2023 20:01:42] Captain Bitchman
[03/31/2023 20:01:42] Curie
[03/31/2023 20:01:42] Augur of Lowest Terrestrial Area
[03/31/2023 20:01:42] Donson Dave
[03/31/2023 20:01:39] Rocky Olympus
[03/31/2023 20:01:38] Captain Bitchman
[03/31/2023 20:01:38] Curie
[03/31/2023 20:01:38] Augur of Lowest Terrestrial Area
[03/31/2023 20:01:38] Donson Dave
[03/31/2023 20:01:36] Received STARTGAMEFINALIZE packet. Round init status: Started
[03/31/2023 20:01:36] Task count: 0
[03/31/2023 20:01:36] Received STARTGAMEFINALIZE packet. Round init status: WaitingForStartGameFinalize
[03/31/2023 20:01:31] Generating an outpost for the start of the level... (Location: Serac, level type: Outpost)
[03/31/2023 20:01:31] Level identifier: outpostlevel
[03/31/2023 20:01:18] Server running slowly (57 updates/s)!
[03/31/2023 19:50:55] Rocky Olympus
[03/31/2023 19:50:55] Captain Bitchman
[03/31/2023 19:50:55] Curie
[03/31/2023 19:50:55] Augur of Lowest Terrestrial Area
[03/31/2023 19:50:55] Donson Dave
[03/31/2023 19:45:54] Captain Bitchman
[03/31/2023 19:45:54] Curie
[03/31/2023 19:45:54] Augur of Lowest Terrestrial Area
[03/31/2023 19:45:54] Donson Dave
[03/31/2023 19:45:43] Captain Bitchman
[03/31/2023 19:45:43] Curie
[03/31/2023 19:45:43] Augur of Lowest Terrestrial Area
[03/31/2023 19:45:43] Donson Dave
[03/31/2023 19:45:42] Captain Bitchman
[03/31/2023 19:45:42] Donson Dave
[03/31/2023 19:45:42] Curie
[03/31/2023 19:45:42] Augur of Lowest Terrestrial Area
[03/31/2023 19:45:42] Captain Bitchman
[03/31/2023 19:45:42] Curie
[03/31/2023 19:45:42] Augur of Lowest Terrestrial Area
[03/31/2023 19:45:42] Donson Dave
[03/31/2023 19:45:42] Captain Bitchman
[03/31/2023 19:45:42] Curie
[03/31/2023 19:45:42] Augur of Lowest Terrestrial Area
[03/31/2023 19:45:42] Donson Dave
[03/31/2023 19:33:08] Captain Bitchman
[03/31/2023 19:33:08] Curie
[03/31/2023 19:33:08] Augur of Lowest Terrestrial Area
[03/31/2023 19:33:08] Donson Dave
[03/31/2023 19:33:08] Captain Bitchman
[03/31/2023 19:33:08] Curie
[03/31/2023 19:33:08] Augur of Lowest Terrestrial Area
[03/31/2023 19:33:08] Donson Dave
[03/31/2023 19:33:04] Captain Bitchman
[03/31/2023 19:33:04] Curie
[03/31/2023 19:33:04] Augur of Lowest Terrestrial Area
[03/31/2023 19:33:04] Donson Dave
[03/31/2023 19:33:03] Received STARTGAMEFINALIZE packet. Round init status: Started
[03/31/2023 19:33:01] Task count: 0
[03/31/2023 19:33:01] Received STARTGAMEFINALIZE packet. Round init status: WaitingForStartGameFinalize
[03/31/2023 19:32:58] Generating an outpost for the end of the level... (Location: Serac, level type: LocationConnection)
[03/31/2023 19:32:56] Generating an outpost for the start of the level... (Location: Sharpitor Linea Research Facility, level type: LocationConnection)
[03/31/2023 19:32:56] Level identifier: coldcavernsadvanced
[03/31/2023 19:32:49] Captain Bitchman
[03/31/2023 19:32:49] Curie
[03/31/2023 19:32:49] Augur of Lowest Terrestrial Area
[03/31/2023 19:32:48] Captain Bitchman
[03/31/2023 19:32:48] Curie
[03/31/2023 19:32:48] Augur of Lowest Terrestrial Area
[03/31/2023 19:32:48] Donson Dave
[03/31/2023 19:32:47] Captain Bitchman
[03/31/2023 19:32:47] Curie
[03/31/2023 19:32:47] Augur of Lowest Terrestrial Area
[03/31/2023 19:32:47] Donson Dave
[03/31/2023 19:32:47] Captain Bitchman
[03/31/2023 19:32:47] Curie
[03/31/2023 19:32:47] Augur of Lowest Terrestrial Area
[03/31/2023 19:32:47] Donson Dave
[03/31/2023 19:32:47] Captain Bitchman
[03/31/2023 19:32:47] Curie
[03/31/2023 19:32:47] Augur of Lowest Terrestrial Area
[03/31/2023 19:32:47] Donson Dave
[03/31/2023 19:32:46] Captain Bitchman
[03/31/2023 19:32:46] Curie
[03/31/2023 19:32:46] Augur of Lowest Terrestrial Area
[03/31/2023 19:32:46] Donson Dave
[03/31/2023 19:32:46] Captain Bitchman
[03/31/2023 19:32:46] Curie
[03/31/2023 19:32:46] Augur of Lowest Terrestrial Area
[03/31/2023 19:32:46] Donson Dave
[03/31/2023 19:32:45] Captain Bitchman
[03/31/2023 19:32:45] Curie
[03/31/2023 19:32:45] Augur of Lowest Terrestrial Area
[03/31/2023 19:32:45] Donson Dave
[03/31/2023 19:32:45] Captain Bitchman
[03/31/2023 19:32:45] Curie
[03/31/2023 19:32:45] Augur of Lowest Terrestrial Area
[03/31/2023 19:32:45] Donson Dave
[03/31/2023 19:32:45] Curie
[03/31/2023 19:32:45] Augur of Lowest Terrestrial Area
[03/31/2023 19:17:00] Captain Bitchman
[03/31/2023 19:17:00] Curie
[03/31/2023 19:17:00] Augur of Lowest Terrestrial Area
[03/31/2023 19:17:00] Donson Dave
[03/31/2023 19:01:45] Rocky Olympus
[03/31/2023 19:01:45] Captain Bitchman
[03/31/2023 19:01:45] Curie
[03/31/2023 19:01:45] Augur of Lowest Terrestrial Area
[03/31/2023 19:01:45] Donson Dave
[03/31/2023 19:01:44] Rocky Olympus
[03/31/2023 19:01:44] Donson Dave
[03/31/2023 19:01:43] Received STARTGAMEFINALIZE packet. Round init status: Started
[03/31/2023 19:01:43] Task count: 0
[03/31/2023 19:01:43] Received STARTGAMEFINALIZE packet. Round init status: WaitingForStartGameFinalize
[03/31/2023 19:01:30] Generating an outpost for the start of the level... (Location: Sharpitor Linea Research Facility, level type: Outpost)
[03/31/2023 19:01:30] Level identifier: outpostlevel
[03/31/2023 19:01:16] Rocky Olympus
[03/31/2023 19:01:16] Captain Bitchman
[03/31/2023 19:01:16] Curie
[03/31/2023 19:01:16] Augur of Lowest Terrestrial Area
[03/31/2023 19:01:16] Donson Dave
[03/31/2023 19:01:16] Rocky Olympus
[03/31/2023 19:01:16] Captain Bitchman
[03/31/2023 19:01:16] Curie
[03/31/2023 19:01:16] Augur of Lowest Terrestrial Area
[03/31/2023 19:01:16] Donson Dave
[03/31/2023 19:01:16] Rocky Olympus
[03/31/2023 19:01:16] Captain Bitchman
[03/31/2023 19:01:16] Curie
[03/31/2023 19:01:16] Augur of Lowest Terrestrial Area
[03/31/2023 19:01:16] Donson Dave
[03/31/2023 19:01:16] Rocky Olympus
[03/31/2023 19:01:16] Captain Bitchman
[03/31/2023 19:01:16] Curie
[03/31/2023 19:01:16] Augur of Lowest Terrestrial Area
[03/31/2023 19:01:16] Donson Dave
[03/31/2023 19:01:15] Rocky Olympus
[03/31/2023 19:01:15] Captain Bitchman
[03/31/2023 19:01:15] Curie
[03/31/2023 19:01:15] Augur of Lowest Terrestrial Area
[03/31/2023 19:01:15] Donson Dave
[03/31/2023 19:01:14] Rocky Olympus
[03/31/2023 19:01:14] Captain Bitchman
[03/31/2023 19:01:14] Curie
[03/31/2023 19:01:14] Augur of Lowest Terrestrial Area
[03/31/2023 19:01:14] Donson Dave
[03/31/2023 19:01:14] Rocky Olympus
[03/31/2023 19:01:14] Captain Bitchman
[03/31/2023 19:01:14] Curie
[03/31/2023 19:01:14] Augur of Lowest Terrestrial Area
[03/31/2023 19:01:14] Donson Dave
[03/31/2023 19:01:13] Rocky Olympus
[03/31/2023 19:01:13] Captain Bitchman
[03/31/2023 19:01:13] Curie
[03/31/2023 19:01:13] Augur of Lowest Terrestrial Area
[03/31/2023 19:01:13] Donson Dave
[03/31/2023 19:01:13] Rocky Olympus
[03/31/2023 19:01:13] Captain Bitchman
[03/31/2023 19:01:13] Curie
[03/31/2023 19:01:13] Augur of Lowest Terrestrial Area
[03/31/2023 19:01:13] Donson Dave
[03/31/2023 19:01:13] Curie
[03/31/2023 18:36:20] Rocky Olympus
[03/31/2023 18:36:20] Captain Bitchman
[03/31/2023 18:36:20] Curie
[03/31/2023 18:36:20] Augur of Lowest Terrestrial Area
[03/31/2023 18:36:20] Donson Dave
[03/31/2023 18:36:17] Rocky Olympus
[03/31/2023 18:36:17] Captain Bitchman
[03/31/2023 18:36:17] Curie
[03/31/2023 18:36:17] Augur of Lowest Terrestrial Area
[03/31/2023 18:36:17] Donson Dave
[03/31/2023 18:36:17] Captain Bitchman
[03/31/2023 18:36:17] Curie

```

**Comment by Regalis11** [comment]
Got a ticket with repro steps now: https://github.com/regalis11/barotrauma/issues/11887

> have a character's projectile rope (like the tongue from the latcher) attached to your character
> give yourself a custom affliction that removes the character using
> Game crashes

Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4218d43cc06596c383d2f92bfc4f3a9080c1efff

**Comment by Regalis11** [comment]
For internal testing:

Here's a simple way to reproduce this without having to implement much custom content:
1. Remove all attacks from LatcherDefaultRagdoll except CharacterTongueAttack
2. Take control of a latcher, fire the tongue at some character (easiest to do if that character's AI is disabled)
3. When the tongue is stuck, F3, kill the target, `despawnnow`
4. The character should now be removed and the game should crash after unpausing

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
