### ISSUE TITLE
Dedicated Server Crash Report RangedStructureDamage

### ISSUE THREAD

**Issue by cshingle** [Regalis11/Barotrauma#11686]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Dedicated Server crashed. None of the clients crashed.
We where fighting a Thalamus.
The other similar issues didn't seem to happen in RangedStructureDamage.

### Reproduction steps

no idea

### Bug prevalence

Just once

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Linux

### Relevant error messages and crash reports

```shell
﻿Barotrauma Dedicated Server crash report (generated on 03/28/2023 01:58:10)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


Game version 1.0.8.0 (ReleaseLinux, branch release/1.0-hotfix, revision 08ecc207eb)
Language: English
Selected content packages: Vanilla, Europa Depths Vanilla Monsters, Europa Depths Npcs, Europa Depths Trauma, Europa Depths More Plants, Europa Depths Items, Europa Depths Equipment
Level seed: Naur81Aegirsgrave109
Loaded submarine: Impulse (191FE16EF03680072446521DE652E747)
Selected screen: Barotrauma.GameScreen
Server (Round had started)


System info:
    Operating system: Unix 5.15.0.67 64 bit


Exception: Collection was modified; enumeration operation may not execute. (System.InvalidOperationException)
Target site: Void ThrowInvalidOperationException_InvalidOperation_EnumFailedVersion()
Stack trace: 
   at Barotrauma.Explosion.RangedStructureDamage(Vector2 worldPosition, Single worldRange, Single damage, Single levelWallDamage, Character attacker, IEnumerable`1 ignoredSubmarines, Boolean emitWallDamageParticles) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Explosion.cs:line 516
   at Barotrauma.Explosion.Explode(Vector2 worldPosition, Entity damageSource, Character attacker) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Explosion.cs:line 122
   at Barotrauma.StatusEffect.Apply(Single deltaTime, Entity entity, IReadOnlyList`1 targets, Nullable`1 worldPosition) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\StatusEffects\StatusEffect.cs:line 1432
   at Barotrauma.StatusEffect.Apply(ActionType type, Single deltaTime, Entity entity, ISerializableEntity target, Nullable`1 worldPosition) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\StatusEffects\StatusEffect.cs:line 1162
   at Barotrauma.Character.ApplyStatusEffects(ActionType actionType, Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 4370
   at Barotrauma.Character.Kill(CauseOfDeathType causeOfDeath, Affliction causeOfDeathAffliction, Boolean isNetworkMessage, Boolean log) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 4466
   at Barotrauma.CharacterHealth.Kill() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Health\CharacterHealth.cs:line 1014
   at Barotrauma.CharacterHealth.AddLimbAffliction(LimbHealth limbHealth, Affliction newAffliction, Boolean allowStacking) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Health\CharacterHealth.cs:line 763
   at Barotrauma.CharacterHealth.AddLimbAffliction(Limb limb, Affliction newAffliction, Boolean allowStacking) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Health\CharacterHealth.cs:line 695
   at Barotrauma.CharacterHealth.ApplyDamage(Limb hitLimb, AttackResult attackResult, Boolean allowStacking) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Health\CharacterHealth.cs:line 586
   at Barotrauma.Character.DamageLimb(Vector2 worldPosition, Limb hitLimb, IEnumerable`1 afflictions, Single stun, Boolean playSound, Single attackImpulse, Character attacker, Single damageMultiplier, Boolean allowStacking, Single penetration, Boolean shouldImplode) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 4179
   at Barotrauma.Character.AddDamage(Vector2 worldPosition, IEnumerable`1 afflictions, Single stun, Boolean playSound, Single attackImpulse, Limb& hitLimb, Character attacker, Single damageMultiplier) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 4072
   at Barotrauma.Explosion.DamageCharacters(Vector2 worldPosition, Attack attack, Single force, Entity damageSource, Character attacker, Boolean applyToSelf) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Explosion.cs:line 386
   at Barotrauma.Explosion.Explode(Vector2 worldPosition, Entity damageSource, Character attacker) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Explosion.cs:line 234
   at Barotrauma.Structure.CreateWallDamageExplosion(Gap gap, Character attacker) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Structure.cs:line 1298
   at Barotrauma.Structure.SetDamage(Int32 sectionIndex, Single damage, Character attacker, Boolean createNetworkEvent, Boolean createExplosionEffect) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Structure.cs:line 1217
   at Barotrauma.Explosion.RangedStructureDamage(Vector2 worldPosition, Single worldRange, Single damage, Single levelWallDamage, Character attacker, IEnumerable`1 ignoredSubmarines, Boolean emitWallDamageParticles) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Explosion.cs:line 485
   at Barotrauma.Explosion.Explode(Vector2 worldPosition, Entity damageSource, Character attacker) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Explosion.cs:line 122
   at Barotrauma.StatusEffect.Apply(Single deltaTime, Entity entity, IReadOnlyList`1 targets, Nullable`1 worldPosition) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\StatusEffects\StatusEffect.cs:line 1432
   at Barotrauma.StatusEffect.Apply(ActionType type, Single deltaTime, Entity entity, ISerializableEntity target, Nullable`1 worldPosition) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\StatusEffects\StatusEffect.cs:line 1162
   at Barotrauma.Character.ApplyStatusEffects(ActionType actionType, Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 4370
   at Barotrauma.Character.Kill(CauseOfDeathType causeOfDeath, Affliction causeOfDeathAffliction, Boolean isNetworkMessage, Boolean log) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 4466
   at Barotrauma.CharacterHealth.Kill() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Health\CharacterHealth.cs:line 1014
   at Barotrauma.CharacterHealth.AddLimbAffliction(LimbHealth limbHealth, Affliction newAffliction, Boolean allowStacking) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Health\CharacterHealth.cs:line 763
   at Barotrauma.CharacterHealth.AddLimbAffliction(Limb limb, Affliction newAffliction, Boolean allowStacking) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Health\CharacterHealth.cs:line 695
   at Barotrauma.CharacterHealth.ApplyDamage(Limb hitLimb, AttackResult attackResult, Boolean allowStacking) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Health\CharacterHealth.cs:line 586
   at Barotrauma.Character.DamageLimb(Vector2 worldPosition, Limb hitLimb, IEnumerable`1 afflictions, Single stun, Boolean playSound, Single attackImpulse, Character attacker, Single damageMultiplier, Boolean allowStacking, Single penetration, Boolean shouldImplode) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 4179
   at Barotrauma.StatusEffect.Apply(Single deltaTime, Entity entity, IReadOnlyList`1 targets, Nullable`1 worldPosition) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\StatusEffects\StatusEffect.cs:line 1470
   at Barotrauma.StatusEffect.Apply(ActionType type, Single deltaTime, Entity entity, ISerializableEntity target, Nullable`1 worldPosition) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\StatusEffects\StatusEffect.cs:line 1162
   at Barotrauma.Attack.DoDamage(Character attacker, IDamageable target, Vector2 worldPosition, Single deltaTime, Boolean playSound, PhysicsBody sourceBody, Limb sourceLimb) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Attack.cs:line 519
   at Barotrauma.Limb.ExecuteAttack(IDamageable damageTarget, Limb targetLimb, AttackResult& attackResult) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Limb.cs:line 1158
   at Barotrauma.Limb.UpdateAttack(Single deltaTime, Vector2 attackSimPos, IDamageable damageTarget, AttackResult& attackResult, Single distance, Limb targetLimb) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Limb.cs:line 1074
   at Barotrauma.EnemyAIController.UpdateLimbAttack(Single deltaTime, Vector2 attackSimPos, IDamageable damageTarget, Single distance, Limb targetLimb) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\EnemyAIController.cs:line 2254
   at Barotrauma.EnemyAIController.UpdateAttack(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\EnemyAIController.cs:line 1980
   at Barotrauma.EnemyAIController.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\EnemyAIController.cs:line 449
   at Barotrauma.Character.UpdateAll(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 3035
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 189
   at Barotrauma.GameMain.Run() in <DEV>\Barotrauma\BarotraumaServer\ServerSource\GameMain.cs:line 331
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Program.cs:line 78


Last debug messages:
   03/28/2023 01:58:10 - [03/28/2023 01:58:10]
  Saving banlist
   03/28/2023 01:58:10 - [03/28/2023 01:58:10]
  Terminalcell has died (Cause of death: Lacerations)
   03/28/2023 01:58:10 - [03/28/2023 01:58:10]
  Terminalcell has died (Cause of death: Lacerations)
   03/28/2023 01:58:07 - [03/28/2023 01:58:07]
  Beer (as zig158) equipped Screwdriver
   03/28/2023 01:58:07 - [03/28/2023 01:58:07]
  Frayace started fabricating Exploding Ammunition Box (recycle) in Fabricator
   03/28/2023 01:58:06 - Failed to write an event for the entity "Flesh Spike (ID: 11010)" {Object reference not set to an instance of an object.}
   at Barotrauma.Items.Components.Turret.ServerEventWrite(IWriteMessage msg, Client c, IData extraData) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Turret.cs:line 1865
   at Barotrauma.Item.ServerEventWrite(IWriteMessage msg, Client c, IData extraData) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Items\Item.cs:line 52
   at Barotrauma.Networking.NetEntityEventManager.Write(IWriteMessage msg, List`1 eventsToSync, List`1& sentEvents, Client recipient) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\NetEntityEvent\NetEntityEventManager.cs:line 28
   03/28/2023 01:58:06 - Failed to write an event for the entity "Flesh Spike (ID: 11010)" {Object reference not set to an instance of an object.}
   at Barotrauma.Items.Components.Turret.ServerEventWrite(IWriteMessage msg, Client c, IData extraData) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Turret.cs:line 1865
   at Barotrauma.Item.ServerEventWrite(IWriteMessage msg, Client c, IData extraData) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Items\Item.cs:line 52
   at Barotrauma.Networking.NetEntityEventManager.Write(IWriteMessage msg, List`1 eventsToSync, List`1& sentEvents, Client recipient) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\NetEntityEvent\NetEntityEventManager.cs:line 28
   03/28/2023 01:58:06 - Failed to write an event for the entity "Flesh Spike (ID: 11010)" {Object reference not set to an instance of an object.}
   at Barotrauma.Items.Components.Turret.ServerEventWrite(IWriteMessage msg, Client c, IData extraData) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Turret.cs:line 1865
   at Barotrauma.Item.ServerEventWrite(IWriteMessage msg, Client c, IData extraData) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Items\Item.cs:line 52
   at Barotrauma.Networking.NetEntityEventManager.Write(IWriteMessage msg, List`1 eventsToSync, List`1& sentEvents, Client recipient) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\NetEntityEvent\NetEntityEventManager.cs:line 28
   03/28/2023 01:58:06 - Failed to write an event for the entity "Flesh Spike (ID: 11010)" {Object reference not set to an instance of an object.}
   at Barotrauma.Items.Components.Turret.ServerEventWrite(IWriteMessage msg, Client c, IData extraData) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Turret.cs:line 1865
   at Barotrauma.Item.ServerEventWrite(IWriteMessage msg, Client c, IData extraData) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Items\Item.cs:line 52
   at Barotrauma.Networking.NetEntityEventManager.Write(IWriteMessage msg, List`1 eventsToSync, List`1& sentEvents, Client recipient) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\NetEntityEvent\NetEntityEventManager.cs:line 28
   03/28/2023 01:58:06 - Failed to write an event for the entity "Flesh Spike (ID: 11010)" {Object reference not set to an instance of an object.}
   at Barotrauma.Items.Components.Turret.ServerEventWrite(IWriteMessage msg, Client c, IData extraData) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Turret.cs:line 1865
   at Barotrauma.Item.ServerEventWrite(IWriteMessage msg, Client c, IData extraData) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Items\Item.cs:line 52
   at Barotrauma.Networking.NetEntityEventManager.Write(IWriteMessage msg, List`1 eventsToSync, List`1& sentEvents, Client recipient) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\NetEntityEvent\NetEntityEventManager.cs:line 28
   03/28/2023 01:58:06 - Failed to write an event for the entity "Flesh Spike (ID: 11010)" {Object reference not set to an instance of an object.}
   at Barotrauma.Items.Components.Turret.ServerEventWrite(IWriteMessage msg, Client c, IData extraData) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Turret.cs:line 1865
   at Barotrauma.Item.ServerEventWrite(IWriteMessage msg, Client c, IData extraData) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Items\Item.cs:line 52
   at Barotrauma.Networking.NetEntityEventManager.Write(IWriteMessage msg, List`1 eventsToSync, List`1& sentEvents, Client recipient) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\NetEntityEvent\NetEntityEventManager.cs:line 28
   03/28/2023 01:58:06 - Failed to write an event for the entity "Flesh Spike (ID: 11010)" {Object reference not set to an instance of an object.}
   at Barotrauma.Items.Components.Turret.ServerEventWrite(IWriteMessage msg, Client c, IData extraData) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Turret.cs:line 1865
   at Barotrauma.Item.ServerEventWrite(IWriteMessage msg, Client c, IData extraData) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Items\Item.cs:line 52
   at Barotrauma.Networking.NetEntityEventManager.Write(IWriteMessage msg, List`1 eventsToSync, List`1& sentEvents, Client recipient) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\NetEntityEvent\NetEntityEventManager.cs:line 28
   03/28/2023 01:58:06 - Failed to write an event for the entity "Flesh Spike (ID: 11010)" {Object reference not set to an instance of an object.}
   at Barotrauma.Items.Components.Turret.ServerEventWrite(IWriteMessage msg, Client c, IData extraData) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Turret.cs:line 1865
   at Barotrauma.Item.ServerEventWrite(IWriteMessage msg, Client c, IData extraData) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Items\Item.cs:line 52
   at Barotrauma.Networking.NetEntityEventManager.Write(IWriteMessage msg, List`1 eventsToSync, List`1& sentEvents, Client recipient) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\NetEntityEvent\NetEntityEventManager.cs:line 28
   03/28/2023 01:58:06 - Failed to write an event for the entity "Flesh Spike (ID: 11010)" {Object reference not set to an instance of an object.}
   at Barotrauma.Items.Components.Turret.ServerEventWrite(IWriteMessage msg, Client c, IData extraData) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Turret.cs:line 1865
   at Barotrauma.Item.ServerEventWrite(IWriteMessage msg, Client c, IData extraData) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Items\Item.cs:line 52
   at Barotrauma.Networking.NetEntityEventManager.Write(IWriteMessage msg, List`1 eventsToSync, List`1& sentEvents, Client recipient) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\NetEntityEvent\NetEntityEventManager.cs:line 28
```

**Comment by itchyOwl** [comment]
Thanks for the report, we'll be looking into it!

**Comment by Regalis11** [comment]
Couldn't find a way to reproduce this, but implemented a fix that _should_ prevent this from happening in https://github.com/Regalis11/Barotrauma-development/commit/9ff0da74d189894657bb8524b86668ebbb0d1da5

**Comment by evilfactory** [comment]
Got this crash on v1.0.13.2, on a dedicated server.
[servercrashreport (21).log](https://github.com/Regalis11/Barotrauma/files/11470444/servercrashreport.21.log)
