### ISSUE TITLE
All ui interfaces (like deconstructor or fabricator) unpin after every round.

### ISSUE THREAD

**Issue by Spyer123** [Regalis11/Barotrauma#11681]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

All windows like deconstructor or fabricator unpin after every round. It means that if you change the positions of the interfaces and even if you pin them to the certain position then in the next round it will reset. After resetting interfaces take random positions. Please, make the button that will pin the interfaces forever. Interfaces should not unpin after the end of the round. This happens on both Windows and Linux systems.

### Reproduction steps

1. Start a campaign.
2. Enter the fabricator or another thing which connected between themselves (if you check the box that connects interfaces of the fabricator and of the closet in the submarine editor).
3. Pin the interfaces of the fabricator and of the closet.
4. End the round.
5. Interfaces reset their positions.

### Bug prevalence

Happens every time I play

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Linux

**Comment by itchyOwl** [comment]
Not sure if it's intentional or not, but I've found it irritating as well.

**Comment by Regalis11** [comment]
Implemented in https://github.com/Regalis11/Barotrauma-development/commit/7c6b5bda40f4f33649e4c2bdfbb6f99d26627e62

**Comment by Rokvach** [comment]
Tested, doesn't work in multiplayer, all the positions reset in the next round when you have locked them in the previous.

**Comment by Rokvach** [comment]
1. It seems that even unlocked GUIFrames keeps their position after level transition and the Reset Position button stops functioning

2. In singleplayer if you move a window it causes a crash
![image](https://github.com/Regalis11/Barotrauma/assets/7299826/2f729864-e336-4f22-be3d-b75b050c37a3)
```
Barotrauma Client crash report (generated on 08/15/2023 11:41:18)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

F5583DEC71D5A8CD2394E2F53B73417B

Game version 1.1.2.0 (ReleaseWindows, branch feature/persistent-guiframe-positions, revision 84872a13ff)
Graphics mode: 2560x1440 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla (0CC4FE2), OTFX (5FC01DF), Typhon2 from save (D41CD5D)
Level seed: St. May76
Loaded submarine: Dugong (9F76C5AA441902AB31C9FB783E7BB481)
Selected screen: Barotrauma.GameScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.22621.0 64 bit
    GPU name: NVIDIA GeForce RTX 4080
    Display mode: {Width:2560 Height:1440 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void UpdateHUD(Barotrauma.Character, Single, Barotrauma.Camera)
Stack trace: 
   at Barotrauma.Items.Components.ItemComponent.UpdateHUD(Character character, Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Components\ItemComponent.cs:line 480
   at Barotrauma.Item.UpdateHUD(Camera cam, Character character, Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Item.cs:line 1207
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 131
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 851
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 651
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[08/15/2023 11:41:00] Generating an outpost for the start of the level... (Location: St. May Habitation Outpost, level type: Outpost)
[08/15/2023 11:40:59] Level identifier: outpostlevel
[08/15/2023 11:40:55] WARNING: Tried to restore enabled packages multiple times/without performing a backup
[08/15/2023 11:39:06] Rokvach
[08/15/2023 11:39:05] Received STARTGAMEFINALIZE packet. Round init status: Started
[08/15/2023 11:39:05] Task count: 0
[08/15/2023 11:39:05] Received STARTGAMEFINALIZE packet. Round init status: WaitingForStartGameFinalize
[08/15/2023 11:39:04] Generating an outpost for the start of the level... (Location: Chandelle Crevasse Habitation Outpost, level type: LocationConnection)
[08/15/2023 11:39:04] Level identifier: coldcavernsbasic
[08/15/2023 11:38:58] Rokvach
[08/15/2023 11:36:18] Rokvach
[08/15/2023 11:36:17] Rokvach
[08/15/2023 11:36:15] Received STARTGAMEFINALIZE packet. Round init status: Started
[08/15/2023 11:36:15] Task count: 0
[08/15/2023 11:36:15] Received STARTGAMEFINALIZE packet. Round init status: WaitingForStartGameFinalize
[08/15/2023 11:36:13] Generating an outpost for the start of the level... (Location: Chandelle Crevasse Habitation Outpost, level type: Outpost)
[08/15/2023 11:36:13] Level identifier: outpostlevel
[08/15/2023 11:36:05] WARNING: Hair index out of range (character: Rokvach, index: 36)
[08/15/2023 11:36:05] Loading submarine "C:\Users\ronik\AppData\Local\Daedalic Entertainment GmbH\Barotrauma\temp\Dugong.sub" failed! {Could not find a part of the path 'C:\Users\ronik\AppData\Local\Daedalic Entertainment GmbH\Barotrauma\temp\Dugong.sub'.}
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at Barotrauma.IO.File.Open(String path, FileMode mode, FileAccess access, Nullable`1 share) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SafeIO.cs:line 410
   at Barotrauma.SaveUtil.DecompressFileToStream(String fileName) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SaveUtil.cs:line 418
   at Barotrauma.SubmarineInfo.OpenFile(String file, Exception& exception) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\SubmarineInfo.cs:line 704
[08/15/2023 11:35:57] Lobby created!
[08/15/2023 11:35:57] WARNING: Hair index out of range (character: Rokvach, index: 36)
[08/15/2023 11:35:15] Attempting to open ALC device "OpenAL Soft on Beyerdynamic dt 990 pro (2- Realtek USB Audio)"
```

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/pull/4102/commits/5ed5bc23373a901cdd35d137ad63bf171c3ad58c and https://github.com/Regalis11/Barotrauma-development/pull/4102/commits/6e0ff35deb575f545b3bc1a1c0b77ed95a69413f

> It seems that even unlocked GUIFrames keeps their position after level transition 

This was actually intentional, I made the positions always stay the same between rounds regardless if the UI is locked or not. I'm not sure if there's a need to change that and make them reset if they haven't been locked?

**Comment by Rokvach** [comment]
Pressing "Lock position" in singleplayer causes a crash

```
Barotrauma Client crash report (generated on 08/24/2023 11:28:44)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

6523EDC86D6373EFA32489510F0C9956

Game version 1.1.2.0 (ReleaseWindows, branch feature/persistent-guiframe-positions, revision 031d35c6d5)
Graphics mode: 2560x1440 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla (171A3E0), LIGHT ISSUE (C2D519C)
Level seed: Krytogorsk85
Loaded submarine: Dugong (9F76C5AA441902AB31C9FB783E7BB481)
Selected screen: Barotrauma.GameScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.22621.0 64 bit
    GPU name: NVIDIA GeForce RTX 4080
    Display mode: {Width:2560 Height:1440 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void <TryCreateDragHandle>b__72_3()
Stack trace: 
   at Barotrauma.Items.Components.ItemComponent.<TryCreateDragHandle>b__72_3() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Components\ItemComponent.cs:line 682
   at Barotrauma.GUIContextMenu.OnSelected(GUIComponent _, Object data) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIContextMenu.cs:line 222
   at Barotrauma.GUIListBox.Select(Int32 childIndex, Force force, AutoScroll autoScroll, TakeKeyBoardFocus takeKeyBoardFocus, PlaySelectSound playSelectSound) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIListBox.cs:line 1068
   at Barotrauma.GUIListBox.UpdateChildrenRect() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIListBox.cs:line 788
   at Barotrauma.GUIListBox.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIListBox.cs:line 908
   at Barotrauma.GUI.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1244
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 876
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 651
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[08/24/2023 11:28:15] Generating an outpost for the start of the level... (Location: Krytogorsk Habitation Outpost, level type: Outpost)
[08/24/2023 11:28:15] Level identifier: outpostlevel
[08/24/2023 11:27:42] Attempting to open ALC device "OpenAL Soft on Beyerdynamic dt 990 pro (2- Realtek USB Audio)"
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/pull/4102/commits/1f4582f34c2da602e81dd7fb88cb5b35cd7a79e1

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
