### ISSUE TITLE
Entering too high of a value in the alpha field when editing RGB of lights in-game causes a crash (campaign)

### ISSUE THREAD

**Issue by joberg87** [Regalis11/Barotrauma#11700]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Editing the RGB values of a light in-game during campaign I made a typo when editing the 'A' field and game crashed.

### Reproduction steps

1. In Single player campaign.
2. Docked at colony.
3. Edited RGB value of a light in one of the subs. (Dugong)
4. Tabbed over one too many times into the alpha field and accidently inserted 255 before 80, leading to a value of 25580.
5. Game crashed.

### Bug prevalence

Just once

### Version

v1.0.8.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Copy Paste of crash log

Barotrauma Client crash report (generated on 03/30/2023 05:41:40)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

14984747362A6EE8B69319866DD5C730

Game version 1.0.8.0 (ReleaseWindows, branch release/1.0-hotfix, revision 08ecc207eb)
Graphics mode: 2560x1440 (BorderlessWindowed)
VSync OFF
Language: English
Selected content packages: Vanilla
Level seed: Belenos Mensa32
Loaded submarine: Dugong (F9EBE2F02EE9EDFFB975972EEA27534B)
Selected screen: Barotrauma.GameScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.22621.0 64 bit
    GPU name: NVIDIA GeForce GTX 1080
    Display mode: {Width:2560 Height:1440 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: System.Collections.Generic.IEnumerable`1[Barotrauma.GUITextBox] <ReceiveSpecialInput>g__GetAndSortTextBoxes|133_3(Barotrauma.GUIComponent)
Stack trace: 
   at Barotrauma.GUITextBox.<ReceiveSpecialInput>g__GetAndSortTextBoxes|133_3(GUIComponent parent) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBox.cs:line 801
   at Barotrauma.GUITextBox.<ReceiveSpecialInput>g__SelectNextTextBox|133_4(GUIListBox listBox) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBox.cs:line 804
   at Barotrauma.GUITextBox.ReceiveSpecialInput(Keys key) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBox.cs:line 792
   at EventInput.KeyboardDispatcher.EventInput_KeyDown(Object sender, KeyEventArgs e) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\EventInput\KeyboardDispatcher.cs:line 41
   at Microsoft.Xna.Framework.SdlGamePlatform.SdlRunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 150
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[03/30/2023 05:35:09] Unlocked mission "Crawler Mother" in the connection from "Belenos Mensa Outpost" to "Sarpedon Linea".
[03/30/2023 05:35:06] Unlocked mission "Terminate a Swarm" in the connection from "Belenos Mensa Outpost" to "Boeotia Macula".
[03/30/2023 05:35:03] Unlocked mission "Coalition Personnel Transport" in the connection from "Belenos Mensa Outpost" to "Sarpedon Linea".
[03/30/2023 05:32:55] Generating an outpost for the start of the level... (Location: Belenos Mensa Outpost, level type: Outpost)
[03/30/2023 05:32:55] Level identifier: outpostlevel
[03/30/2023 05:32:42] Transitioning to Belenos Mensa32 (current location: Skadi's Cauldron Station, selected location: Belenos Mensa Outpost, leaving sub: Dugong, at start: False, at end: True, transition type: ProgressToNextLocation)
[03/30/2023 05:15:28] Could not find a spawn point for a SpawnAction (spawn location: BeaconStation (tag: beacon_bandit), skipping.
[03/30/2023 05:15:23] Generating an outpost for the end of the level... (Location: Belenos Mensa Outpost, level type: LocationConnection)
[03/30/2023 05:15:21] Generating an outpost for the start of the level... (Location: Skadi's Cauldron Station, level type: LocationConnection)
[03/30/2023 05:15:21] Level identifier: coldcavernsadvanced
[03/30/2023 05:15:09] Transitioning to Skadi's Cauldron1Belenos Mensa32 (current location: Skadi's Cauldron Station, selected location: Belenos Mensa Outpost, leaving sub: Dugong, at start: True, at end: False, transition type: LeaveLocation)
[03/30/2023 05:13:11] Unlocked mission "Coalition Personnel Transport" in the connection from "Skadi's Cauldron Station" to "Belenos Mensa Outpost".
[03/30/2023 05:13:04] Unlocked mission "Killing a large Crawler" in the connection from "Skadi's Cauldron Station" to "Belenos Mensa Outpost".
[03/30/2023 05:13:02] Unlocked mission "Mining outpost material transport" in the connection from "Skadi's Cauldron Station" to "Belenos Mensa Outpost".
[03/30/2023 05:04:30] Generating an outpost for the start of the level... (Location: Skadi's Cauldron Station, level type: Outpost)
[03/30/2023 05:04:30] Level identifier: outpostlevel
[03/30/2023 05:04:19] Transitioning to Skadi's Cauldron1 (current location: Asmundur, selected location: Skadi's Cauldron Station, leaving sub: Dugong, at start: False, at end: True, transition type: ProgressToNextLocation)
[03/30/2023 05:01:30] Could not find a suitable module for the location type LocationType (None). Module flag: Airlock.
[03/30/2023 05:01:29] Generating an outpost for the end of the level... (Location: Asmundur, level type: LocationConnection)
[03/30/2023 05:01:29] Level identifier: coldcavernsbasic
[03/30/2023 05:01:17] Transitioning to Skadi's Cauldron1Asmundur21 (current location: Asmundur, selected location: Skadi's Cauldron Station, leaving sub: Dugong, at start: False, at end: True, transition type: ProgressToNextEmptyLocation)
[03/30/2023 04:41:27] Could not find a suitable module for the location type LocationType (None). Module flag: Airlock.
[03/30/2023 04:41:26] Generating an outpost for the start of the level... (Location: Asmundur, level type: LocationConnection)
[03/30/2023 04:41:26] Level identifier: coldcavernsbasic
[03/30/2023 04:41:13] Transitioning to Asmundur21Krytogorsk34 (current location: Krytogorsk, selected location: Asmundur, leaving sub: Dugong, at start: True, at end: False, transition type: LeaveLocation)
[03/30/2023 04:39:46] Unlocked mission "Mining outpost material transport" in the connection from "Krytogorsk" to "Asmundur".
[03/30/2023 04:32:48] Loading a pre-selected outpost for the start of the level...
[03/30/2023 04:32:48] Level identifier: outpostlevel
[03/30/2023 04:27:48] WARNING: No core package selected. Switching to the "Vanilla" package.
```

**Comment by TerminatorTM** [comment]
> Duplicate of #11700

This issue is #11700 itself.
