### ISSUE TITLE
Crash when using wikiimage_character on Endworm

### ISSUE THREAD

**Issue by HawkinsThe71st** [Regalis11/Barotrauma#11819]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Game crashes when using `wikiimage_character` while controlling an endworm, not sure if it happens on any other creatures but taking images of human, mudraptor, moloch and charybdis seems to work fine.

### Reproduction steps

1. `spawn Endworm`
2. `control Endworm`
3. `wikiimage_character`

### Bug prevalence

Happens regularly

### Version

v1.0.9.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 04/13/2023 21:39:26)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

8BE661744288B03127E103F2FAFCC948

Game version 1.0.9.0 (ReleaseWindows, branch release/1.0-hotfix-2, revision 64dcc9f061)
Graphics mode: 1600x900 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla
Level seed: no level loaded
Loaded submarine: Camel (D12BB7674F200D4D5AEED1F2F7879EB5)
Selected screen: Barotrauma.GameScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19045.0 64 bit
    GPU name: NVIDIA GeForce GTX 1050 Ti
    Display mode: {Width:1600 Height:900 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid Arguments], Message: The parameter is incorrect.
 (SharpDX.SharpDXException)
Target site: SharpDX.Direct3D11.Resource CreateTexture()
Stack trace: 
   at Microsoft.Xna.Framework.Graphics.Texture2D.CreateTexture() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\Texture2D.DirectX.cs:line 410
   at Microsoft.Xna.Framework.Graphics.RenderTarget2D.CreateTexture() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\RenderTarget2D.DirectX.cs:line 154
   at Microsoft.Xna.Framework.Graphics.RenderTarget2D.GenerateIfRequired() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\RenderTarget2D.DirectX.cs:line 25
   at Barotrauma.WikiImage.Create(Character character) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Utils\WikiImage.cs:line 73
   at Barotrauma.DebugConsole.<>c.<InitProjectSpecific>b__23_22(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\DebugConsole.cs:line 635
   at Barotrauma.DebugConsole.Command.Execute(String[] args) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\DebugConsole.cs:line 86
   at Barotrauma.DebugConsole.ExecuteCommand(String command) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\DebugConsole.cs:line 0
   at Barotrauma.DebugConsole.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\DebugConsole.cs:line 195
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 881
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[04/13/2023 21:39:26] wikiimage_character
[04/13/2023 21:39:21] control Endworm
[04/13/2023 21:39:17] Enemy AI disabled
[04/13/2023 21:39:17] disableenemyai
[04/13/2023 21:39:14] spawn Endworm cursor
[04/13/2023 21:39:09] freecamera
[04/13/2023 21:38:04] Attempting to open ALC device "OpenAL Soft on Speakers (HyperX Cloud Stinger S)"
[04/13/2023 21:38:02] Logged in as Hawkins (SteamID STEAM_1:1:72180162)
```

**Comment by Regalis11** [comment]
I'm afraid I could not reproduce the issue.

I think it could have something to do with the size of the texture (it's over 10k pixels in width/height due to the size of the endworm) - maybe your GPU doesn't support textures that large or something along those lines? In any case, the fix implemented for https://github.com/Regalis11/Barotrauma/issues/11605 should prevent this from crashing the game, and log an error instead.

**Comment by HawkinsThe71st** [comment]
> I think it could have something to do with the size of the texture (it's over 10k pixels in width/height due to the size of the endworm) - maybe your GPU doesn't support textures that large or something along those lines?

This is probably the case since when I tried taking an image of a coiled endworm the game didn't crash
