### ISSUE TITLE
Crash EKM Stiletto Mk-V

### ISSUE THREAD

**Issue by LishoiKot** [Regalis11/Barotrauma#11823]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Departure when leaving the base on a mod submarine

### Reproduction steps

After buying and entering the submarine EKM Stiletto Mk-V, such an accident occurs, I would like to get help, because I would not want to go through the floor of the company on a new one.

### Bug prevalence

Happens every time I play

### Version

v1.0.9.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 04/14/2023 20:45:25)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

8BE661744288B03127E103F2FAFCC948

Game version 1.0.9.0 (ReleaseWindows, branch release/1.0-hotfix-2, revision 64dcc9f061)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync OFF
Language: Russian
Selected content packages: Vanilla, Enhanced Armaments, EK | Armory, EK | Utility, EK | Dockyard, EK | Gunnery
Level seed: Phoenix Linea94Castalia Macula95
Loaded submarine: EKM_Stiletto_Mk-V (07DCD5230F3CCD2FF4E2C6D4DC58DCFC)
Selected screen: Barotrauma.NetLobbyScreen
SteamManager initialized
Client (Round hadn't been started)

System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit
    GPU name: NVIDIA GeForce RTX 2060 SUPER
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: ChildServerRelay readTask did not run to completion: status was WaitingForActivation. (System.Exception)
Target site: Barotrauma.Option`1[System.Int32] ReadIncomingMsgs()
Stack trace: 
   at Barotrauma.Networking.ChildServerRelay.ReadIncomingMsgs() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\ChildServerRelay.cs:line 155
   at Barotrauma.Networking.ChildServerRelay.<UpdateRead>g__readBytes|43_0(Span`1 readTo) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\ChildServerRelay.cs:line 183
   at Barotrauma.Networking.ChildServerRelay.UpdateRead() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\ChildServerRelay.cs:line 175
   at System.Threading.Thread.StartCallback()

Last debug messages:
[04/14/2023 20:45:25] Exiting...
[04/14/2023 20:45:15] Generating an outpost for the end of the level... (Location: Жилой аванпост Phoenix Linea, level type: LocationConnection)
[04/14/2023 20:45:14] Generating an outpost for the start of the level... (Location: Castalia Macula, level type: LocationConnection)
[04/14/2023 20:45:11] Level identifier: greatseabasic
[04/14/2023 20:45:02] WARNING: Potentially invalid damage modifier in "Military Mk-II Hardsuit, Wearable". Could not find any afflictions of the type "concussion". Did you mean to use an affliction identifier instead?
[04/14/2023 20:45:02] WARNING: Potentially invalid damage modifier in "Military Mk-II Hardsuit, Wearable". Could not find any afflictions with the identifier "contamination". Did you mean to use an affliction type instead?
[04/14/2023 20:45:02] WARNING: Potentially invalid damage modifier in "Military Mk-II Hardsuit, Wearable". Could not find any afflictions with the identifier "glowing". Did you mean to use an affliction type instead?
[04/14/2023 20:45:02] WARNING: Potentially invalid damage modifier in "Military Mk-II Hardsuit, Wearable". Could not find any afflictions with the identifier "exposure". Did you mean to use an affliction type instead?
[04/14/2023 20:45:02] WARNING: Potentially invalid damage modifier in "Military Mk-II Hardsuit, Wearable". Could not find any afflictions with the identifier "radiation". Did you mean to use an affliction type instead?
[04/14/2023 20:45:01] WARNING: Potentially invalid damage modifier in "Utility Mk-I Hardsuit, Wearable". Could not find any afflictions of the type "concussion". Did you mean to use an affliction identifier instead?
[04/14/2023 20:45:01] WARNING: Potentially invalid damage modifier in "Utility Mk-I Hardsuit, Wearable". Could not find any afflictions with the identifier "contamination". Did you mean to use an affliction type instead?
[04/14/2023 20:45:01] WARNING: Potentially invalid damage modifier in "Utility Mk-I Hardsuit, Wearable". Could not find any afflictions with the identifier "glowing". Did you mean to use an affliction type instead?
[04/14/2023 20:45:01] WARNING: Potentially invalid damage modifier in "Utility Mk-I Hardsuit, Wearable". Could not find any afflictions with the identifier "exposure". Did you mean to use an affliction type instead?
[04/14/2023 20:45:01] WARNING: Potentially invalid damage modifier in "Utility Mk-I Hardsuit, Wearable". Could not find any afflictions with the identifier "radiation". Did you mean to use an affliction type instead?
[04/14/2023 20:44:45] Lobby created!
[04/14/2023 20:40:12] Attempting to open ALC device "OpenAL Soft on Динамики (Logitech PRO X Gaming Headset)"
```

**Comment by Regalis11** [comment]
Thank you for the report!

I unfortunately could not get this to happen at my end. Would it be possible to send us the save file where this occurs? Thanks and sorry for the inconvenience!

**Comment by Regalis11** [comment]
No known steps to repro, closing
