### ISSUE TITLE
Dedicated server crashes

### ISSUE THREAD

**Issue by pavel4win** [Regalis11/Barotrauma#11845]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I tried to start windows dedicated server with ports 27015:27016 forwarded via VPN tunnel. as described in my issue https://github.com/Regalis11/Barotrauma/issues/11453
I got crash when server starts
crashreport is in attachment
I used to study how to configure iptables and now
my VPS server iptables settings is
~~~~~~~~~~~~~~~~~~~~~~~~~~~~
################ reset iptables settings
iptables -F
iptables -X
iptables -t nat -F
iptables -t nat -X

############### Allow forwarding via tunnel
iptables -A INPUT -i tun0 -j ACCEPT
iptables -A FORWARD -i tun0 -j ACCEPT
iptables -A OUTPUT -o tun0 -j ACCEPT
iptables -A FORWARD -o tun0 -j ACCEPT

################## allow SSH
iptables -A INPUT -i eth0 -p tcp --dport 22 -j ACCEPT

#################### forward ports 27015:27016 
iptables -t nat -A PREROUTING -p udp -i eth0 --dport 27015:27016 -j DNAT --to-destination 10.8.0.10:27015-27016
iptables -A FORWARD -p udp -d 10.8.0.10 --dport 27015:27016 -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT
iptables -t nat -A POSTROUTING -p udp -s 10.8.0.10 --sport 27015:27016 -j SNAT --to-source 194.87.94.145:27015-27016

######################### it is for web server
iptables -A FORWARD -i eth0 -p tcp --dport  80 -j ACCEPT
iptables -A FORWARD -i eth0 -p tcp --dport 443 -j ACCEPT

iptables -t nat -A POSTROUTING -j MASQUERADE
~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[servercrashreport (3).log](https://github.com/Regalis11/Barotrauma/files/11239120/servercrashreport.3.log)

### Reproduction steps

described in "What happened" section

### Bug prevalence

Happens every time I play

### Version

v1.0.9.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Here is copy of my server console output
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\Users\pasha\Desktop>F:\SteamCMD\steamcmd +login anonymous +app_run 1026340 +quit
Redirecting stderr to 'F:\SteamCMD\logs\stderr.txt'
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[  0%] Проверка на наличие обновлений...
[----] Проверка установки...
Steam Console Client (c) Valve Corporation - version 1679680174
-- type 'quit' to exit --
Loading Steam API...OK

Connecting anonymously to Steam Public...Retrying. . .
Retrying. . .
Retrying. . .
OK
Waiting for client config...OK
Waiting for user info...OK
src\public\tier1\interface.h (265) : m_pModule
src\public\tier1\interface.h (265) : m_pModule
Barotrauma Dedicated Server 1.0.9.0 (ReleaseWindows, branch master, revision 1186719)
Loading game settings
Initializing SteamManager
Initializing GameScreen
Barotrauma Dedicated Server crash report (generated on 04/15/2023 13:11:27)


Barotrauma seems to have crashed. Sorry for the inconvenience!


Game version 1.0.9.0 (ReleaseWindows, branch master, revision 1186719)
Language: English
Selected content packages: Vanilla, CsForBarotrauma, Lua For Barotrauma, Larger Deconstructor, Toolbox Expanded, EuropaWaifu++, Headsight, 32x Stack, Super Mining Sonar + oClockRadar [UPDATED], Deep Containers, [BOS]Backpack, New Wrecks For Barotrauma (With sellable wrecks), Beacons Extended, Exosuit in Diving Lockers, Dont Open Debug Console On Errors, R-278 «Dugong», Movable and Sellable Wrecks, Enhanced Armaments, Shipwrecks Extended, ADV Beacon Stations, Backpacks, BaroCraftables+, Talent Gear Found In Wrecks, More Arts (AOCS), MoreMissionsMod, ModularHeadset, C.S.S. Palestar II S, Performance Fix, BetterHealthUI, Local Voice Fix, BetterFabricatorUI, Lua Linker, Oxygen Reloader
Level seed: no level loaded
Loaded submarine: None
Selected screen: None
Server (Round hadn't been started)


System info:
    Operating system: Microsoft Windows NT 10.0.14393.0 64 bit


Exception: Обычно разрешается только одно использование адреса сокета (протокол/сетевой адрес/порт). (System.Net.Sockets.SocketException)
Target site: Void UpdateStatusAfterSocketErrorAndThrowException(System.Net.Sockets.SocketError, System.String)
Stack trace:
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Lidgren.Network.NetPeer.BindSocket(Boolean reBind) in <DEV>/Libraries/Lidgren.Network/NetPeer.Internal.cs:line 155
   at Lidgren.Network.NetPeer.InitializeNetwork() in <DEV>/Libraries/Lidgren.Network/NetPeer.Internal.cs:line 193
   at Lidgren.Network.NetPeer.Start() in <DEV>/Libraries/Lidgren.Network/NetPeer.cs:line 150
   at Barotrauma.Networking.LidgrenServerPeer.Start() in <DEV>/Barotrauma/BarotraumaServer/ServerSource/Networking/Primitives/Peers/Server/LidgrenServerPeer.cs:line 60
   at Barotrauma.Networking.GameServer.StartServer() in <DEV>/Barotrauma/BarotraumaServer/ServerSource/Networking/GameServer.cs:line 185
   at Barotrauma.GameMain.StartServer() in <DEV>/Barotrauma/BarotraumaServer/ServerSource/GameMain.cs:line 258
   at Barotrauma.GameMain.Run() in <DEV>/Barotrauma/BarotraumaServer/ServerSource/GameMain.cs:line 311
   at Barotrauma.Program.Main(String[] args) in <DEV>/Barotrauma/BarotraumaServer/ServerSource/Program.cs:line 82


Last debug messages:
   04/15/2023 13:11:27 - [04/15/2023 13:11:27]
  Saving banlist
   04/15/2023 13:11:27 - [04/15/2023 13:11:27]
  Using Lidgren networking. Manual port forwarding may be required. If players cannot connect to the server, you may want to use the in-game hosting menu (which uses SteamP2P networking and does not require port forwarding).
   04/15/2023 13:11:27 - [04/15/2023 13:11:27]
  Starting the server...
   04/15/2023 13:11:27 - Selected shuttle: RS-5 Rescue shuttle [ENG]
   04/15/2023 13:11:27 - Selected sub: C.S.S. Palestar II S
   04/15/2023 13:11:26 - WARNING: Potential error in item variant "wrenchhardened": the base item "wrench" requires x2 "iron" to fabricate. The variant only overrides the required item, not the amount, resulting in a requirement of x2 "wrench". Specify the amount in the variant to fix this.
   04/15/2023 13:11:26 - WARNING: Potential error in item variant "wrenchdementonite": the base item "wrench" requires x2 "iron" to fabricate. The variant only overrides the required item, not the amount, resulting in a requirement of x2 "wrench". Specify the amount in the variant to fix this.
   04/15/2023 13:11:26 - WARNING: Potential error in item variant "divingknifehardened": the base item "divingknife" requires x2 "iron" to fabricate. The variant only overrides the required item, not the amount, resulting in a requirement of x2 "divingknife". Specify the amount in the variant to fix this.
   04/15/2023 13:11:26 - WARNING: Potential error in item variant "divingknifedementonite": the base item "divingknife" requires x2 "iron" to fabricate. The variant only overrides the required item, not the amount, resulting in a requirement of x2 "divingknife". Specify the amount in the variant to fix this.
   04/15/2023 13:11:26 - WARNING: Potential error in item variant "crowbarhardened": the base item "crowbar" requires x2 "iron" to fabricate. The variant only overrides the required item, not the amount, resulting in a requirement of x2 "crowbar". Specify the amount in the variant to fix this.
   04/15/2023 13:11:26 - WARNING: Potential error in item variant "crowbardementonite": the base item "crowbar" requires x2 "iron" to fabricate. The variant only overrides the required item, not the amount, resulting in a requirement of x2 "crowbar". Specify the amount in the variant to fix this.
   04/15/2023 13:11:26 - WARNING: Potential error in item variant "slipsuit": the item inherits the fabrication requirement of x1 "rubber"  from the base item "combatdivingsuit". If this is not intentional, you can use empty <RequiredItem /> elements in the item variant to remove any excess inherited fabrication requirements.
   04/15/2023 13:11:26 - WARNING: Potential error in item variant "slipsuit": the item inherits the fabrication requirement of x1 "titaniumaluminiumalloy"  from the base item "combatdivingsuit". If this is not intentional, you can use empty <RequiredItem /> elements in the item variant to remove any excess inherited fabrication requirements.
   04/15/2023 13:11:26 - WARNING: Potential error in item variant "screwdriverhardened": the base item "screwdriver" requires x2 "iron" to fabricate. The variant only overrides the required item, not the amount, resulting in a requirement of x2 "screwdriver". Specify the amount in the variant to fix this.
A crash report("servercrashreport.log") was saved in the root folder of the game. The error was not sent to the developers because user statistics have been disabled, but if you'd like to help fix this bug, you may post it on Barotrauma's GitHub issue tracker: https://github.com/Regalis11/Barotrauma/issues/
```

**Comment by Regalis11** [comment]
The error message ("Обычно разрешается только одно использование адреса сокета (протокол/сетевой адрес/порт)") seems to imply the ports are misconfigured somehow.

**Comment by pavel4win** [comment]
I seem to be able to forward the ports. I'll test it tomorrow and report back
If any players will be able to connect I'll dance lower breakdance
here is my iptables config

[barotrauma-new.txt](https://github.com/Regalis11/Barotrauma/files/11240383/barotrauma-new.txt)
