### ISSUE TITLE
Crash when creating a character that doesn't have any health parameters

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#11904]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

If you try to create a character whose xml config doesn't include a <health> element, the game will crash.

```
Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void set_DoesBleed(Boolean)
Stack trace: 
   at Barotrauma.CharacterHealth.set_DoesBleed(Boolean value) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Health\CharacterHealth.cs:line 108
   at Barotrauma.CharacterHealth..ctor(Character character) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Health\CharacterHealth.cs:line 250
   at Barotrauma.Character..ctor(CharacterPrefab prefab, Vector2 position, String seed, CharacterInfo characterInfo, UInt16 id, Boolean isRemotePlayer, RagdollParams ragdollParams, Boolean spawnInitialItems) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 1348
   at Barotrauma.AICharacter..ctor(CharacterPrefab prefab, Vector2 position, String seed, CharacterInfo characterInfo, UInt16 id, Boolean isNetworkPlayer, RagdollParams ragdoll, Boolean spawnInitialItems) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AICharacter.cs:line 15
   at Barotrauma.Character.Create(CharacterPrefab prefab, Vector2 position, String seed, CharacterInfo characterInfo, UInt16 id, Boolean isRemotePlayer, Boolean hasAi, Boolean createNetworkEvent, RagdollParams ragdoll, Boolean spawnInitialItems) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 1202
   at Barotrauma.Character.Create(Identifier speciesName, Vector2 position, String seed, CharacterInfo characterInfo, UInt16 id, Boolean isRemotePlayer, Boolean hasAi, Boolean createNetworkEvent, RagdollParams ragdoll, Boolean throwErrorIfNotFound, Boolean spawnInitialItems) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 1194
```

### Reproduction steps

1. Remove the <health> element from e.g. Crawler.xml
2. Spawn a crawler
3. Crash

### Bug prevalence

Happens every now and then

### Version

v1.0.9.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/07f2166d1d7479c54f39c8314f63ef5d83760403
