### ISSUE TITLE
Using <StatusEffect target="NearbyItems"> inside an Affliction crash the game

### ISSUE THREAD

**Issue by AzureNocte** [Regalis11/Barotrauma#11945]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I was writing a .xml file which defines an Affliction,  and when I test the game crashed.

```
    <Affliction name="Cyborg Effects" identifier="cyborgeffects" type="geneticmaterialbuff" limbspecific="false" indicatorlimb="Torso" hideiconafterdelay="true" showiconthreshold="0" treatmentthreshold="100" maxstrength="100" iconcolors="94,54,95;163,73,164;200,191,231">
      <Effect minstrength="0" maxstrength="20">
        <StatusEffect type="Always" target="NearbyItems" Range="800" interval="1.0" condition="0.75" disabledeltatime="true" >
          <Conditional HasTag="fabricator,deconstructor,medicalfabricator,door,engine,oxygengenerator,pump,turretammosource,junctionbox,battery,navterminal,statusmonitor,sonarmonitaor,supercapacitor,electrical,geneticresearchstation,reactor,chargingdock,light" />
        </StatusEffect>
		<StatusEffect type="Always" target="Character" interval="1.0">
		  <Explosion range="800" force="0.0" camerashake="0" smoke="false" flames="false" flash="false" sparks="false" underwaterbubble="false" structuredamage="-3" />
		</StatusEffect>
      </Effect>
      <Effect minstrength="20" maxstrength="40">
        <StatusEffect type="Always" target="NearbyItems" Range="800" interval="1.0" condition="1.5" disabledeltatime="true" >
          <Conditional HasTag="fabricator,deconstructor,medicalfabricator,door,engine,oxygengenerator,pump,turretammosource,junctionbox,battery,navterminal,statusmonitor,sonarmonitaor,supercapacitor,electrical,geneticresearchstation,reactor,chargingdock,light" />
        </StatusEffect>
		<StatusEffect type="Always" target="Character" interval="1.0">
		  <Explosion range="800" force="0.0" camerashake="0" smoke="false" flames="false" flash="false" sparks="false" underwaterbubble="false" structuredamage="-6" />
		</StatusEffect>
      </Effect>
      <Effect minstrength="40" maxstrength="60">
        <StatusEffect type="Always" target="NearbyItems" Range="800" interval="1.0" condition="2.25" disabledeltatime="true" >
          <Conditional HasTag="fabricator,deconstructor,medicalfabricator,door,engine,oxygengenerator,pump,turretammosource,junctionbox,battery,navterminal,statusmonitor,sonarmonitaor,supercapacitor,electrical,geneticresearchstation,reactor,chargingdock,light" />
        </StatusEffect>
		<StatusEffect type="Always" target="Character" interval="1.0">
		  <Explosion range="800" force="0.0" camerashake="0" smoke="false" flames="false" flash="false" sparks="false" underwaterbubble="false" structuredamage="-9" />
		</StatusEffect>
      </Effect>
      <Effect minstrength="60" maxstrength="80">
        <StatusEffect type="Always" target="NearbyItems" Range="800" interval="1.0" condition="3.0" disabledeltatime="true" >
          <Conditional HasTag="fabricator,deconstructor,medicalfabricator,door,engine,oxygengenerator,pump,turretammosource,junctionbox,battery,navterminal,statusmonitor,sonarmonitaor,supercapacitor,electrical,geneticresearchstation,reactor,chargingdock,light" />
        </StatusEffect>
		<StatusEffect type="Always" target="Character" interval="1.0">
		  <Explosion range="800" force="0.0" camerashake="0" smoke="false" flames="false" flash="false" sparks="false" underwaterbubble="false" structuredamage="-12" />
		</StatusEffect>
      </Effect>
      <Effect minstrength="80" maxstrength="100">
        <StatusEffect type="Always" target="NearbyItems" Range="800" interval="1.0" condition="3.75" disabledeltatime="true" >
          <Conditional HasTag="fabricator,deconstructor,medicalfabricator,door,engine,oxygengenerator,pump,turretammosource,junctionbox,battery,navterminal,statusmonitor,sonarmonitaor,supercapacitor,electrical,geneticresearchstation,reactor,chargingdock,light" /> 
	    </StatusEffect>
        <StatusEffect type="Always" target="Character" interval="1.0">
		  <Explosion range="800" force="0.0" camerashake="0" smoke="false" flames="false" flash="false" sparks="false" underwaterbubble="false" structuredamage="-15" />
		</StatusEffect>
	  </Effect>
      <icon texture="Content/UI/TalentsIcons3.png" sheetindex="4,0" sheetelementsize="128,128" color="163,73,764,255" origin="0,0" />
    </Affliction>
```

The item which uses the affliction is here:
```
  <Item name="" identifier="geneticmaterialcyborg" variantof="geneticmaterialcrawler" nameidentifier="geneticmaterial">
    <Deconstruct>
      <Item identifier="geneticmaterialcyborg" />
    </Deconstruct>
    <InventoryIcon texture="%ModDir%/Genetic_ancient.png" sheetindex="1,1" sheetelementsize="64,64" origin="0.5,0.5" />
    <Sprite texture="%ModDir%/Genetic_ancient.png" sheetindex="1,0" sheetelementsize="32,32" depth="0.6" origin="0.5,0.5" />
    <GeneticMaterial nameidentifier="character.cyborg" effect="cyborgeffects" tooltipvaluemin="0.75" tooltipvaluemax="3.75" />
  </Item>
```

I'm not sure if my grammar is wrong, but I think the logic should be fine.

### Reproduction steps

1. Add the XML code above to an localmod
2. spawn a genesplicer and the genetic item, insert it, wear it
3. the game crushed

### Bug prevalence

Happens every time I play

### Version

v1.0.9.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 05/02/2023 14:25:17)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

BD9A52E22A984D5C04FD9165F629CD07

Game version 1.0.9.0 (ReleaseWindows, branch master, revision 1186719e62)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: Simplified Chinese
Selected content packages: Vanilla, Lua For Barotrauma, DynamicEuropa, Davey Jones Locker, Craftable Faction items, Funbringer launches mini nuke, Extended Upgrades, Transferable Symbiosis, Ancient Genes, Skitter and Mollusc Genes Buff, Better Cthulhu Pet, Glowing Harpoons, Let Them All In, Creatures of the Depth, MN Creatures, Makeshift Containers, 更强的宠物迅猛龙, Blahaj Pet, BFT Nuclear Torpedo, New Wrecks For Barotrauma (With sellable wrecks), Movable and Sellable Wrecks, Sellable Pirates, Beacons Extended, Shipwrecks Extended, Cat Propaganda Banner Override, XML Hot Reloader, Nebuchadnezzar, Citrinitas, Golden mice, RS-1050 'The Charlatan', Saluki [Bots Fixed], GOBLINO, Glacial-9, 咸鱼级, Imp All-Purpose Sub, Barracuda II Escort Corvette, Silhouette Light Patrol, Mini Hammerhead Pets, Chimera, Sand Shark, Liatris, Northumberland, Mercury, Fer-de-Lance, King Layne Mining Cruiser, Cyclops Mk-II, Arclite Brawler Sub, Scrapper Junkyard Sub, Scrapjack Bomber, The Deep Manatee, Bronze Age, [VH] The Iroh, Apo-5 "Chainsaw", 御冬 PWM改线版, Camelite, Remora+, Camel+, Scrapper Private, CamelDrone+, Smuggler
Level seed: no level loaded
Loaded submarine: Camel (D12BB7674F200D4D5AEED1F2F7879EB5)
Selected screen: Barotrauma.GameScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.22000.0 64 bit
    GPU name: NVIDIA GeForce RTX 3060 Laptop GPU
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void AddNearbyTargets(Microsoft.Xna.Framework.Vector2, System.Collections.Generic.List`1[Barotrauma.ISerializableEntity])
Stack trace: 
   at Barotrauma.StatusEffect.AddNearbyTargets(Vector2 worldPosition, List`1 targets) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\StatusEffects\StatusEffect.cs:line 907
   at Barotrauma.Affliction.ApplyStatusEffect(ActionType type, StatusEffect statusEffect, Single deltaTime, CharacterHealth characterHealth, Limb targetLimb) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Health\Afflictions\Affliction.cs:line 492
   at Barotrauma.Affliction.ApplyStatusEffects(ActionType type, Single deltaTime, CharacterHealth characterHealth, Limb targetLimb) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Health\Afflictions\Affliction.cs:line 465
   at Barotrauma.CharacterHealth.ApplyAfflictionStatusEffects(ActionType type) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Health\CharacterHealth.cs:line 1039
   at Barotrauma.Character.ApplyStatusEffects(ActionType actionType, Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 4402
   at Barotrauma.Character.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 3092
   at Barotrauma.AICharacter.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AICharacter.cs:line 72
   at Barotrauma.Character.UpdateAll(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 3048
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 185
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 891
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in C:\Users\joona\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in C:\Users\joona\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in C:\Users\joona\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in C:\Users\joona\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in C:\Users\joona\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[05/02/2023 14:25:00] Package reloaded.
[05/02/2023 14:25:00] reloadpackage "Ancient Genes"
[05/02/2023 14:24:40] WARNING: Entity "gravityspherespawned" has no name!
[05/02/2023 14:24:40] WARNING: Entity "leucocytespawner" has no name!
[05/02/2023 14:24:40] WARNING: Entity "terminalcellspawner" has no name!
[05/02/2023 14:24:40] WARNING: Entity "gravityspherespawned" has no name!
[05/02/2023 14:24:40] WARNING: Entity "leucocytespawner" has no name!
[05/02/2023 14:24:40] WARNING: Entity "terminalcellspawner" has no name!
[05/02/2023 14:24:31] Invalid action type "Alwaysd" in StatusEffect (Cyborg Effects)
[05/02/2023 14:24:06]  - init.lua (Took 0.00204ms)
[05/02/2023 14:24:06] XML Hot Reloader 1.3
[05/02/2023 14:24:06]  - sellablepirates.lua (Took 0.00033ms)
[05/02/2023 14:24:06] Sellable Pirates 1.1.3
[05/02/2023 14:24:06]  - sellablewrecks.lua (Took 0.00172ms)
[05/02/2023 14:24:06]  - movablewrecks.lua (Took 0.00686ms)
[05/02/2023 14:24:06] Movable and Sellable Wrecks 1.0.5
[05/02/2023 14:24:06]  - letthemallin.lua (Took 0.00598ms)
[05/02/2023 14:24:06] Let Them All In 1.0.10
[05/02/2023 14:24:06]  - items.lua (Took 0.00171ms)
[05/02/2023 14:24:06] Transferable Symbiosis 1.0.9.4
[05/02/2023 14:24:05] Using LuaSetup.lua from the content package.
[05/02/2023 14:24:05] Lua! Version 1186719e62
[05/02/2023 14:24:05] WARNING: Entity "gravityspherespawned" has no name!
[05/02/2023 14:24:05] WARNING: Entity "leucocytespawner" has no name!
[05/02/2023 14:24:05] WARNING: Entity "terminalcellspawner" has no name!
[05/02/2023 14:24:05] WARNING: Entity "gravityspherespawned" has no name!
[05/02/2023 14:24:05] WARNING: Entity "leucocytespawner" has no name!
[05/02/2023 14:24:05] WARNING: Entity "terminalcellspawner" has no name!
[05/02/2023 14:24:05] WARNING: Entity "gravityspherespawned" has no name!
[05/02/2023 14:24:05] WARNING: Entity "leucocytespawner" has no name!
[05/02/2023 14:24:05] WARNING: Entity "terminalcellspawner" has no name!
[05/02/2023 14:24:05] WARNING: Entity "gravityspherespawned" has no name!
[05/02/2023 14:24:05] WARNING: Entity "leucocytespawner" has no name!
[05/02/2023 14:24:05] WARNING: Entity "terminalcellspawner" has no name!
[05/02/2023 14:22:49] Overriding an affliction or a buff with the identifier 'hyperactivityondamage' using the file 'C:/Users/Azure/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2947717430/AfflictionsGeneticMaterial.xml'
[05/02/2023 14:22:49] Overriding an affliction or a buff with the identifier 'vigorondamage' using the file 'C:/Users/Azure/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2947717430/AfflictionsGeneticMaterial.xml'
[05/02/2023 14:22:21] Attempting to open ALC device "OpenAL Soft on Speaker (Realtek(R) Audio)"
[05/02/2023 14:22:19] Logged in as Azure Nocte (SteamID STEAM_1:0:171865524)
```

**Comment by Regalis11** [comment]
Seems to be the same issue as https://github.com/Regalis11/Barotrauma/issues/11459, should be fixed in the next patch.
