### ISSUE TITLE
I crashed when fighting a Thalamus

### ISSUE THREAD

**Issue by NoIWontBruh0831** [Regalis11/Barotrauma#11964]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

As I was fighting a Thalamus, my game started becoming extremely laggy. I was using a Prototype Steam Cannon against boarded Terminal Cells while having 3 FPS when my game crashed. 

### Reproduction steps

1. Become really laggy I guess?
2. Get hooked by a Thalamus and get many hulls and machinery destroyed
3. Keep lagging and crash?
4. I think this was a rare occassion
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/11414212/crashreport.log)

### Bug prevalence

Just once

### Version

v1.0.9.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 05/07/2023 12:24:44)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

8BE661744288B03127E103F2FAFCC948

Game version 1.0.9.0 (ReleaseWindows, branch release/1.0-hotfix-2, revision 64dcc9f061)
Graphics mode: 1920x1080 (Fullscreen)
VSync ON
Language: English
Selected content packages: Vanilla
Level seed: New Nanhui34Tyre47
Loaded submarine: Camel (F4D865248C29873605540B283D2F8A3B)
Selected screen: Barotrauma.GameScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit
    GPU name: NVIDIA GeForce GTX 1060 with Max-Q Design
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Collection was modified; enumeration operation may not execute. (System.InvalidOperationException)
Target site: Void ThrowInvalidOperationException_InvalidOperation_EnumFailedVersion()
Stack trace: 
   at Barotrauma.Explosion.RangedStructureDamage(Vector2 worldPosition, Single worldRange, Single damage, Single levelWallDamage, Character attacker, IEnumerable`1 ignoredSubmarines, Boolean emitWallDamageParticles) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Explosion.cs:line 516
   at Barotrauma.Explosion.Explode(Vector2 worldPosition, Entity damageSource, Character attacker) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Explosion.cs:line 122
   at Barotrauma.StatusEffect.Apply(Single deltaTime, Entity entity, IReadOnlyList`1 targets, Nullable`1 worldPosition) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\StatusEffects\StatusEffect.cs:line 1434
   at Barotrauma.StatusEffect.Apply(ActionType type, Single deltaTime, Entity entity, ISerializableEntity target, Nullable`1 worldPosition) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\StatusEffects\StatusEffect.cs:line 1162
   at Barotrauma.Character.ApplyStatusEffects(ActionType actionType, Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 4370
   at Barotrauma.Character.Kill(CauseOfDeathType causeOfDeath, Affliction causeOfDeathAffliction, Boolean isNetworkMessage, Boolean log) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 4466
   at Barotrauma.CharacterHealth.Kill() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Health\CharacterHealth.cs:line 1014
   at Barotrauma.CharacterHealth.AddLimbAffliction(LimbHealth limbHealth, Affliction newAffliction, Boolean allowStacking) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Health\CharacterHealth.cs:line 747
   at Barotrauma.CharacterHealth.AddLimbAffliction(Limb limb, Affliction newAffliction, Boolean allowStacking) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Health\CharacterHealth.cs:line 695
   at Barotrauma.CharacterHealth.ApplyDamage(Limb hitLimb, AttackResult attackResult, Boolean allowStacking) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Health\CharacterHealth.cs:line 586
   at Barotrauma.Character.DamageLimb(Vector2 worldPosition, Limb hitLimb, IEnumerable`1 afflictions, Single stun, Boolean playSound, Single attackImpulse, Character attacker, Single damageMultiplier, Boolean allowStacking, Single penetration, Boolean shouldImplode) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 4179
   at Barotrauma.StatusEffect.Apply(Single deltaTime, Entity entity, IReadOnlyList`1 targets, Nullable`1 worldPosition) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\StatusEffects\StatusEffect.cs:line 1458
   at Barotrauma.StatusEffect.Apply(ActionType type, Single deltaTime, Entity entity, IReadOnlyList`1 targets, Nullable`1 worldPosition) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\StatusEffects\StatusEffect.cs:line 1212
   at Barotrauma.Items.Components.RepairTool.ApplyStatusEffectsOnTarget(Character user, Single deltaTime, ActionType actionType, Item targetItem, Character character, Limb limb, Structure structure) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Holdable\RepairTool.cs:line 892
   at Barotrauma.Items.Components.RepairTool.FixBody(Character user, Single deltaTime, Single degreeOfSuccess, Body targetBody) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Holdable\RepairTool.cs:line 640
   at Barotrauma.Items.Components.RepairTool.Repair(Vector2 rayStart, Vector2 rayEnd, Single deltaTime, Character user, Single degreeOfSuccess, List`1 ignoredBodies) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Holdable\RepairTool.cs:line 411
   at Barotrauma.Items.Components.RepairTool.Use(Single deltaTime, Character character) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Holdable\RepairTool.cs:line 304
   at Barotrauma.Item.Use(Single deltaTime, Character character, Limb targetLimb) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 2752
   at Barotrauma.Character.<Control>g__tryUseItem|575_1(Item item, Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 2203
   at Barotrauma.Character.Control(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 2189
   at Barotrauma.Character.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 3257
   at Barotrauma.AICharacter.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AICharacter.cs:line 72
   at Barotrauma.Character.UpdateAll(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 3037
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 186
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 881
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[05/07/2023 12:19:07] Could not find a spawn point for a SpawnAction (spawn location: BeaconStation (tag: beacon_bandit), skipping.
[05/07/2023 12:18:34] Generating an outpost for the end of the level... (Location: Tyre Institute of Astrobiology, level type: LocationConnection)
[05/07/2023 12:18:31] Generating an outpost for the start of the level... (Location: New Nanhui, level type: LocationConnection)
[05/07/2023 12:18:20] Level identifier: plateaubasic
[05/07/2023 12:17:51] Transitioning to New Nanhui34Tyre47 (current location: New Nanhui, selected location: Tyre Institute of Astrobiology, leaving sub: Camel, at start: True, at end: False, transition type: LeaveLocation)
[05/07/2023 12:13:16] Unlocked mission "Explosive cargo" in the connection from "New Nanhui" to "Tyre Institute of Astrobiology".
[05/07/2023 12:13:14] Unlocked mission "Wreck salvage" in the connection from "New Nanhui" to "Tyre Institute of Astrobiology".
[05/07/2023 12:13:12] Unlocked mission "Scan ruin" in the connection from "New Nanhui" to "Oshan Fortification".
[05/07/2023 12:13:10] Unlocked mission "Destroy a Tiger Thresher nest" in the connection from "New Nanhui" to "Calyx Cave".
[05/07/2023 12:11:10] Unlocked mission "The Ultimate Jest" in the location "Cyclades Macula".
[05/07/2023 12:07:01] Generating an outpost for the start of the level... (Location: New Nanhui, level type: Outpost)
[05/07/2023 12:07:01] Level identifier: outpostlevel
[05/07/2023 12:06:31] Transitioning to New Nanhui34 (current location: Castalia Macula Habitation Outpost, selected location: New Nanhui, leaving sub: Camel, at start: False, at end: True, transition type: ProgressToNextLocation)
[05/07/2023 11:42:51] Could not find a spawn point for a SpawnAction (spawn location: BeaconStation (tag: beacon_bandit), skipping.
[05/07/2023 11:42:20] Generating an outpost for the start of the level... (Location: New Nanhui, level type: LocationConnection)
[05/07/2023 11:42:18] Generating an outpost for the end of the level... (Location: Castalia Macula Habitation Outpost, level type: LocationConnection)
[05/07/2023 11:42:06] Level identifier: plateaubasic
[05/07/2023 11:41:37] Transitioning to New Nanhui34Castalia Macula51 (current location: Castalia Macula Habitation Outpost, selected location: New Nanhui, leaving sub: Camel, at start: True, at end: False, transition type: LeaveLocation)
[05/07/2023 11:41:00] Unlocked mission "Destroy a Mudraptor nest" in the connection from "Castalia Macula Habitation Outpost" to "New Nanhui".
[05/07/2023 11:40:58] Unlocked mission "Destroy a Tiger Thresher nest" in the connection from "Castalia Macula Habitation Outpost" to "Topol Outpost".
[05/07/2023 11:40:56] Unlocked mission "Mining Thorianite" in the connection from "Castalia Macula Habitation Outpost" to "The Bucket".
[05/07/2023 11:40:55] Unlocked mission "Salvaging an artifact" in the connection from "Castalia Macula Habitation Outpost" to "The Bucket".
[05/07/2023 11:35:21] Generating an outpost for the start of the level... (Location: Castalia Macula Habitation Outpost, level type: Outpost)
[05/07/2023 11:35:21] Level identifier: outpostlevel
[05/07/2023 11:19:12] Unlocked mission "Mining outpost material transport" in the connection from "Castalia Macula Habitation Outpost" to "New Nanhui".
[05/07/2023 11:19:09] Unlocked mission "Wreck salvage" in the connection from "Castalia Macula Habitation Outpost" to "Noctae Prospecting Outpost".
[05/07/2023 11:19:07] Unlocked mission "Arms Delivery" in the connection from "Castalia Macula Habitation Outpost" to "New Nanhui".
[05/07/2023 11:19:05] Unlocked mission "Separatist Vessel" in the connection from "Castalia Macula Habitation Outpost" to "Noctae Prospecting Outpost".
[05/07/2023 11:16:50] Generating an outpost for the start of the level... (Location: Castalia Macula Habitation Outpost, level type: Outpost)
[05/07/2023 11:16:50] Level identifier: outpostlevel
[05/07/2023 11:16:21] Transitioning to Castalia Macula51 (current location: Topol Outpost, selected location: Castalia Macula Habitation Outpost, leaving sub: Camel, at start: False, at end: True, transition type: ProgressToNextLocation)
[05/07/2023 11:05:15] Could not find a spawn point for a SpawnAction (spawn location: BeaconStation (tag: beacon_bandit), skipping.
[05/07/2023 11:04:50] Generating an outpost for the end of the level... (Location: Castalia Macula Habitation Outpost, level type: LocationConnection)
[05/07/2023 11:04:48] Generating an outpost for the start of the level... (Location: Topol Outpost, level type: LocationConnection)
[05/07/2023 11:04:25] Level identifier: plateaubasic
[05/07/2023 11:03:59] Transitioning to Topol26Castalia Macula51 (current location: Topol Outpost, selected location: Castalia Macula Habitation Outpost, leaving sub: Camel, at start: True, at end: False, transition type: LeaveLocation)
[05/07/2023 10:59:19] Generating an outpost for the start of the level... (Location: Topol Outpost, level type: Outpost)
[05/07/2023 10:59:19] Level identifier: outpostlevel
[05/07/2023 10:58:51] Transitioning to Topol26 (current location: Asterius Linea Mining Facility, selected location: Topol Outpost, leaving sub: Camel, at start: False, at end: True, transition type: ProgressToNextLocation)
[05/07/2023 10:28:54] Could not find a spawn point for a SpawnAction (spawn location: BeaconStation (tag: beacon_bandit), skipping.
[05/07/2023 10:28:27] Generating an outpost for the end of the level... (Location: Topol Outpost, level type: LocationConnection)
[05/07/2023 10:28:25] Generating an outpost for the start of the level... (Location: Asterius Linea Mining Facility, level type: LocationConnection)
[05/07/2023 10:28:13] Level identifier: plateaubasic
[05/07/2023 10:27:45] Transitioning to Asterius Linea20Topol26 (current location: Asterius Linea Mining Facility, selected location: Topol Outpost, leaving sub: Camel, at start: True, at end: False, transition type: LeaveLocation)
[05/07/2023 10:26:50] Unlocked mission "Terminate a Thresher Swarm" in the connection from "Asterius Linea Mining Facility" to "The Bucket".
[05/07/2023 10:26:48] Unlocked mission "Giant Spineling" in the connection from "Asterius Linea Mining Facility" to "The Bucket".
[05/07/2023 10:26:46] Unlocked mission "Salvaging an artifact" in the connection from "Asterius Linea Mining Facility" to "The Bucket".
[05/07/2023 10:23:09] Generating an outpost for the start of the level... (Location: Asterius Linea Mining Facility, level type: Outpost)
[05/07/2023 10:23:08] Level identifier: outpostlevel
[05/07/2023 10:21:45] Attempting to open ALC device "OpenAL Soft on Speakers/Headphones (Realtek(R) Audio)"
[05/07/2023 10:21:33] Logged in as No (SteamID STEAM_1:1:207725746)
```

**Comment by NoIWontBruh0831** [comment]
Oh sorry. I know nothing about coding and just assumed that dedicated server and solo play crashes were different

**Comment by Regalis11** [comment]
No worries! :) It's often hard even for us in the dev team to figure out whether some issue is caused by the same underlying bug, but in this case it seems the crash occurred on the exact same part of the code. But in any case, I'm sorry for the inconvenience! We've got a fix coming up for this in the next patch.
