### ISSUE TITLE
Game crashed while playing (connection was modified in MapEntity.UpdateAll)

### ISSUE THREAD

**Issue by Bocharik** [Regalis11/Barotrauma#11973]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

The game crashes after a while or when the bot takes damage.
[crashreport (10).log](https://github.com/Regalis11/Barotrauma/files/11432406/crashreport.10.log)

### Reproduction steps

1.Start campaign.
2.Hire a 5-6 bots.
3.Go on a misson.
4Play for 10-15 minutes or make the bot take damage.

### Bug prevalence

Happens every time I play

### Version

v1.0.9.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
BD9A52E22A984D5C04FD9165F629CD07
Game version 1.0.9.0 (ReleaseWindows, branch master, revision 1186719e62)
Graphics mode: 1366x768 (BorderlessWindowed)
VSync ON
Language: Russian
Selected content packages: Vanilla, Lua For Barotrauma, Cs For Barotrauma, Performance Fix, DynamicEuropa, Frith's Biomes, Stations from beyond, SFB with DE, DynamicEuropa - Frith's Biomes Compatibility Patch, Dynamic Europa RU, BetterHealthUI, Neurotrauma, NT Surgery Plus, NT Pharmacy, Neurotrauma Cybernetics, Enhanced Armaments, Saber Armaments (Uprising Midpoint Update), Saber Personal Protection (Abyss Hotfix), EK | Utility, EK | Armory, EK | Dockyard, EK | Gunnery, Improved Husks, Shipwrecks Extended, Vanilla Weapons Overhaul, Beacons Extended, Enhanced Armaments Neurotrauma Patch, Ruins Enhanced, Enhanced Armaments - Legacy Archive, Enhanced Armaments RU, Husk Mod Missions, Let Them All In, New Wrecks For Barotrauma (With sellable wrecks), Meaningful Upgrades, [VH] The Iroh, Lootbelt, Enhanced Armaments Barotraumatic Patch
Level seed: Sarpedon Linea242
Loaded submarine: [VH] The Iroh (E9F57CEAB2808304EE063B640AA706C7)
Selected screen: Barotrauma.GameScreen
SteamManager initialized
System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit
    GPU name: NVIDIA GeForce GTX 1050 Ti
    Display mode: {Width:1366 Height:768 Format:Color AspectRatio:1.7786459}
    GPU status: Normal
Exception: Collection was modified; enumeration operation may not execute. (System.InvalidOperationException)
Target site: Void ThrowInvalidOperationException_InvalidOperation_EnumFailedVersion()
Stack trace: 
   at Barotrauma.MapEntity.UpdateAll(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\MapEntity.cs:line 660
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 247
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 891
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in C:\Users\joona\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in C:\Users\joona\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in C:\Users\joona\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in C:\Users\joona\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in C:\Users\joona\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58
Last debug messages:
[05/09/2023 17:32:22] teleportsub end
[05/09/2023 17:32:11] Steam achievements have been disabled during this play session.
[05/09/2023 17:32:11] Enabled cheat commands.
[05/09/2023 17:32:11] enablecheats
[05/09/2023 17:28:47] 
/// Running Neurotrauma V A1.8.4h2 ///
--------------------------------------------
+ Cybernetics V A1.2.3h3
+ Pharmacy V A1.0.3h1
+ Surgery Plus V A1.2.6h1
[05/09/2023 17:27:57] Level identifier: ridgeadvanced
```

**Comment by Regalis11** [comment]
Thank you for the report!

To our knowledge, this doesn't happen in the vanilla game. It seems you have enabled a bunch of mods (including source code mods), so it seems very likely one, or some combination of, the mods is causing the crash.
