### ISSUE TITLE
Sonarbeacon problem on dedicated server

### ISSUE THREAD

**Issue by Hegny** [Regalis11/Barotrauma#12012]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Not possible to enter any text in a SonarBeacon. The text field becomes empty.
Client doesn't get any error.
When spawning a new sonarbeacon server console gives an error (see attached).
If the beacon was already in the sub, no errors arise but it is not possible to set the text.

### Reproduction steps

1. Start a dedicated server
2. Start any round
3. Use Sonar Beacon (no text can be set)
4. Spawn Sonar Beacon (will give a server error)

### Bug prevalence

Happens every time I play

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Attempted to create a network event for an item (Sonar Beacon) that hasn't been fully initialized yet.
   at System.Environment.get_StackTrace()
   at Barotrauma.Item.CreateServerEvent[T](T ic, IEventData extraData) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Items\Item.cs:line 367
   at Barotrauma.Items.Components.CustomInterface.OnItemLoaded() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Signal\CustomInterface.cs:line 304
   at Barotrauma.Item..ctor(Rectangle newRect, ItemPrefab itemPrefab, Submarine submarine, Boolean callOnItemLoaded, UInt16 id) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 1112
   at Barotrauma.Item..ctor(ItemPrefab itemPrefab, Vector2 position, Submarine submarine, UInt16 id, Boolean callOnItemLoaded) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 889
   at Barotrauma.EntitySpawner.ItemSpawnInfo.Spawn() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\EntitySpawner.cs:line 79
   at Barotrauma.EntitySpawner.Update(Boolean createNetworkEvents) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\EntitySpawner.cs:line 415
   at Barotrauma.MapEntity.UpdateAll(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\MapEntity.cs:line 660
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 250
   at Barotrauma.GameMain.Run() in <DEV>\Barotrauma\BarotraumaServer\ServerSource\GameMain.cs:line 331
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Program.cs:line 78
```

**Comment by Regalis11** [comment]
Thank you for the report! Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a8cb7759cebcc4dbcb9e65cf6d9fbb0def03924b and https://github.com/Regalis11/Barotrauma-development/commit/144d38eb39e67e50748df00ff6be4809b8bc99db

**Comment by Jasontti** [comment]
Tested with dedicated server and "Host server" button.
Working and closing ticket.
