### ISSUE TITLE
Crash when trying to combine items in sub editor

### ISSUE THREAD

**Issue by BiffW** [Regalis11/Barotrauma#12032]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

When I try to combine 2 non-full non-empty oxygen tanks in the sub editor, game crash.

### Reproduction steps

1. go to sub editor
2. spawn 2 oxygen tanks and set their condition to non-full and non-empty
3. put them in a container
4. combine them in the container

### Bug prevalence

Just once

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 05/16/2023 10:14:08)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

295B64BA38A96B8A182C1BB9CF3B4305

Game version 1.0.13.2 (ReleaseWindows, branch lua-xpath-1.0.13, revision 14e80a2)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: Simplified Chinese
Selected content packages: Vanilla (E7A137B), Cs For Barotrauma (965D27D), BetterHealthUI (5C86226), BetterFabricatorUI (9A068E8), Sort Container UI (6136523), Lua Audio Overhaul (9CB166C), Item IO Purchasable (E4D8AB9), Item IO Framework (396BB3B), Storage Icons (CA9F78A), Better Item Drop Key (E184BE6), Update Campaign Store (B376CC4), ExtraXP (MoreXP Lua Remake) (E6047F5), More Responsive Reactor Controls (3CD449C), Biff's Labs (AD11804), BiffRemodSubs (EFDF204), BiffVanillaSubModCollection (24BF829), ADV Beacon Stations (115F91F), [BOS]Wrecks (64DE267), More Outposts for Europa (95A2CFD), Shipwrecks Extended (17A736B), Backpacks - No Encumbrance (EE2F180), Lootbelt (B6971B3), Biff_W的神奇妙妙工具 (4B4F866), Material IO (57E6AC8), BVTA Extension (77A5FEF), Ssparky's Gauss Cannon(remix) (1C16031), Genes+ Revived and Expanded (tweaked) (F747E20), [SGM]Blackmarket Gene Restored(xpath) (BB69E6D), [SGM]Skill Book Trigger Talents(xpath) (4630291), BVTA Rebalance xpath (50C1323), Better Vanilla Turret Ammo xpath (0BA0FCC), [SGM]Compact Campaign (C6302C5), [SGM]Start With All Jobs (EAB6165), Stronger NPC    装备更好更加强大的NPC (AADC62E), 爬爬娘化 (D391C86), 泥偶迅猛龙大家族sfw (CEF3CD7), 脊刺家族nsfw (DD9B805), [EA-HI]Animated Barotrauma Lite (4BCE009), Extended Upgrades (B1F2CEA), Reworked Vanilla Weapons (2957604), Talent Rework and Tweaks (F67D096), Husked human can talk (9B5101C)
Level seed: no level loaded
Loaded submarine: Lab-Template (0C3C3BA41622C0B36EB570DAFC8E118B)
Selected screen: Barotrauma.SubEditorScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19045.0 64 bit
    GPU name: NVIDIA GeForce GTX 1650
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Boolean Combine(Barotrauma.Item, Barotrauma.Character)
Stack trace: 
   at Barotrauma.Items.Components.ItemComponent.Combine(Item item, Character user) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Items/Components/ItemComponent.cs:line 534
   at Barotrauma.Item.Combine_Patch2(Item this, Item item, Character user)
   at Barotrauma.Inventory.TryPutItem(Item item, Int32 i, Boolean allowSwapping, Boolean allowCombine, Character user, Boolean createNetworkEvent, Boolean ignoreCondition) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Items/Inventory.cs:line 517
   at Barotrauma.ItemInventory.TryPutItem(Item item, Int32 i, Boolean allowSwapping, Boolean allowCombine, Character user, Boolean createNetworkEvent, Boolean ignoreCondition) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Items/ItemInventory.cs:line 116
   at Barotrauma.Inventory.UpdateDragging() in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Items/Inventory.cs:line 1263
   at Barotrauma.CharacterHUD.Update(Single deltaTime, Character character, Camera cam) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Characters/CharacterHUD.cs:line 293
   at Barotrauma.SubEditorScreen.Update(Double deltaTime) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Screens/SubEditorScreen.cs:line 5822
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/GameMain.cs:line 891
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Program.cs:line 58
```

**Comment by BiffW** [comment]
I've just tested it again. It seems not to happen again.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/349cc59d02fda6210b36e3ac07e436399af2f1f3
