### ISSUE TITLE
[Unstable] Crash in the connection panel interface when wearing electrician's goggles

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#12030]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Crash in the connection panel interface when wearing electrician's goggles

### Reproduction steps

1. Equip electrician's goggles
2. Start rewiring a junction box
3. Move all the wires from the power connection to one of the signal connections
4. Hover over one of those moved wires
5. Connection.GetTooltip tries to get the power of the grid the device at the other end of the wire is connected to, even though it's no longer part of any grid

### Bug prevalence

Just once

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Barotrauma.LocalizedString GetToolTip()
Stack trace: 
   at Barotrauma.Items.Components.Connection.GetToolTip() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Components\Signal\Connection.cs:line 394
   at Barotrauma.Items.Components.Connection.DrawConnections(SpriteBatch spriteBatch, ConnectionPanel panel, Rectangle dragArea, Character character) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Components\Signal\Connection.cs:line 118
   at Barotrauma.Items.Components.ConnectionPanel.DrawConnections(SpriteBatch spriteBatch, GUICustomComponent container) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Components\Signal\ConnectionPanel.cs:line 127
   at Barotrauma.GUICustomComponent.Draw(SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUICustomComponent.cs:line 43
   at Barotrauma.GUI.Draw(Camera cam, SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 273
   at Barotrauma.GameScreen.Draw(Double deltaTime, GraphicsDevice graphics, SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\GameScreen.cs:line 159
   at Barotrauma.GameMain.Draw(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 988
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 669
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 508
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58
```
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a1d11d0d393c2c674666f172bdf126de4c5e2b10

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
