### ISSUE TITLE
Message byte position incorrect after reading an event for the entity "Harpoon (ID: 4291)"

### ISSUE THREAD

**Issue by cheapcents** [Regalis11/Barotrauma#12084]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

After being suddenly disconnected from a friend's server, I crashed everytime whenever I reconnected and pressed 'spectate', until the crew docked to an outpost.

### Reproduction steps

1. Start a multiplayer campaign, not as the host
2. Get disconnected
3. Reconnect
4. Click 'spectate'
5. Crash
6. Cry as your friends tell you your character has suffocated to death

### Bug prevalence

Just once

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Error while reading a message from server. 
Exception thrown while reading segment EntityEventInitial at position 32.
Inner exception: Message byte position incorrect after reading an event for the entity "Harpoon (ID: 4291)" (ID 4291). The previous entity was "Harpoon (ID: 4291)" (ID 4291) Read 184 bits, expected message length was 192 bits.
   at Barotrauma.Networking.ClientEntityEventManager.Read(ServerNetSegment type, IReadMessage msg, Single sendingTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\NetEntityEvent\ClientEntityEventManager.cs:line 233
   at Barotrauma.Networking.GameClient.<>cDisplayClass119_0.<ReadIngameUpdate>b0(ServerNetSegment segment, IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 2140
   at Barotrauma.Networking.SegmentTableReader`1.Read(IReadMessage msg, SegmentDataReader segmentDataReader, ExceptionHandler exceptionHandler) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SegmentTable.cs:line 296
```

**Comment by NilanthAnimosus** [comment]
Thanks for the report!

I've tested this on 1.0.13.2 and couldn't reproduce any issues and likely need more information if possible such as the save file from the host when it occurs (Before the end of the round if possible), what mods are in use if any (though you reported as none) that might modify harpoon projectiles and other details if they are known.

Notes:
Dead characters with attached harpoons.
character removal with attached harpoons.
Characters being eaten with attached harpoons
walls/floors and such with stuck harpoons.
harpoons fired into the ocean
fired harpoons deconstructed.
