### ISSUE TITLE
Grabbing minerals with bare hands shows "Detaching" despite it being impossible to detach

### ISSUE THREAD

**Issue by Vykn** [Regalis11/Barotrauma#12102]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

If you come across any kind of minerals, you can grab it with your hands by pressing [left click]. When you do this, a bar shows up and text says "Detaching". Despite this, the bar never starts to fill, and you just swim there holding the rock in your hands forever.

It was expected that since you cannot rip minerals straight from the rock face using your bare hands, there would not be a popup saying "Detaching".

![image](https://github.com/Regalis11/Barotrauma/assets/37850646/049858e2-e358-4504-883c-64c235a212be)

### Reproduction steps

1. Swim up to some minerals
2. Left click on the minerals
3. Be told that your character is "Detaching" the minerals, despite nothing happening

### Bug prevalence

Happens regularly

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
Repro steps confirmed.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/0d36449b96b1e62d776d905207843b390c4e0589

**Comment by itchyOwl** [comment]
You can still grab the minerals, which is a bit weird: ![image](https://github.com/Regalis11/Barotrauma/assets/5370738/04aa18b1-000c-4518-8280-27a446d30f65)

**Comment by Jasontti** [comment]
There is also a crash when you are "holding" the ore with bare hands and return to sub editor.

```
Unhandled exception. System.Exception: Tried to put a removed item (Uranium Ore) in an inventory
   at Barotrauma.CharacterInventory.TryPutItem(Item item, Character user, IEnumerable`1 allowedSlots, Boolean createNetworkEvent, Boolean ignoreCondition) in /home/joonas/dev/Barotrauma-development/Barotrauma/BarotraumaShared/SharedSource/Items/CharacterInventory.cs:line 312
   at Barotrauma.CharacterInventory.TryPutItemWithAutoEquipCheck(Item item, Character user, IEnumerable`1 allowedSlots, Boolean createNetworkEvent) in /home/joonas/dev/Barotrauma-development/Barotrauma/BarotraumaShared/SharedSource/Items/CharacterInventory.cs:line 292
   at Barotrauma.Items.Components.Pickable.OnPicked(Character picker, Boolean pickDroppedStack) in /home/joonas/dev/Barotrauma-development/Barotrauma/BarotraumaShared/SharedSource/Items/Components/Holdable/Pickable.cs:line 142
   at Barotrauma.Items.Components.Pickable.OnPicked(Character picker) in /home/joonas/dev/Barotrauma-development/Barotrauma/BarotraumaShared/SharedSource/Items/Components/Holdable/Pickable.cs:line 118
   at Barotrauma.Items.Components.Holdable.OnPicked(Character picker) in /home/joonas/dev/Barotrauma-development/Barotrauma/BarotraumaShared/SharedSource/Items/Components/Holdable/Holdable.cs:line 576
   at Barotrauma.Items.Components.Pickable.WaitForPick(Character picker, Single requiredTime)+MoveNext() in /home/joonas/dev/Barotrauma-development/Barotrauma/BarotraumaShared/SharedSource/Items/Components/Holdable/Pickable.cs:line 224
   at Barotrauma.CoroutineManager.PerformCoroutineStep(CoroutineHandle handle) in /home/joonas/dev/Barotrauma-development/Barotrauma/BarotraumaShared/SharedSource/CoroutineManager.cs:line 213
   at Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle) in /home/joonas/dev/Barotrauma-development/Barotrauma/BarotraumaShared/SharedSource/CoroutineManager.cs:line 223
   at Barotrauma.CoroutineManager.Update(Boolean paused, Single deltaTime) in /home/joonas/dev/Barotrauma-development/Barotrauma/BarotraumaShared/SharedSource/CoroutineManager.cs:line 252
   at Barotrauma.GameMain.Update(GameTime gameTime) in /home/joonas/dev/Barotrauma-development/Barotrauma/BarotraumaClient/ClientSource/GameMain.cs:line 900
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in /home/joonas/dev/Barotrauma-development/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 651
   at Microsoft.Xna.Framework.Game.Tick() in /home/joonas/dev/Barotrauma-development/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in /home/joonas/dev/Barotrauma-development/Libraries/MonoGame.Framework/Src/MonoGame.Framework/SDL/SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in /home/joonas/dev/Barotrauma-development/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in /home/joonas/dev/Barotrauma-development/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in /home/joonas/dev/Barotrauma-development/Barotrauma/BarotraumaClient/ClientSource/Program.cs:line 58
```

**Comment by Regalis11** [comment]
Fixed the grabbing in https://github.com/Regalis11/Barotrauma-development/pull/4332/commits/9ed62523c702770e3b6439f919a0d5456c98a07b and the exception when returning to the editor in https://github.com/Regalis11/Barotrauma-development/pull/4332/commits/840f55ae4e7ebe28c49c74b806d51279edaa24bd

**Comment by Jasontti** [comment]
No issues found.
Closing.
