### ISSUE TITLE
[Crash on launch] Exception: Loading was interrupted due to an error. | Object reference not set

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#12100]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I've literally only opened the game and clicked through the title screens. 

It crashed before I saw the loading screen.

### Reproduction steps

Non-reproducible

### Bug prevalence

Just once

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 05/29/2023 21:23:35)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

To prevent further startup errors, installed mods will be disabled the next time you launch the game.

1F05303D4AB76BACE6EE576870D83561

Game version 1.0.13.2 (ReleaseWindows, branch master, revision 09c36a9213)
Graphics mode: 1920x1080 (Fullscreen)
VSync OFF
Language: English
Selected content packages: None
Level seed: no level loaded
Loaded submarine: None
Selected screen: None
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19045.0 64 bit
    GPU name: Radeon RX Vega
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Loading was interrupted due to an error. (Barotrauma.GameMain+LoadingException)
Target site: Void Update(Microsoft.Xna.Framework.GameTime)
Stack trace: 
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 752
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

InnerException: Object reference not set to an instance of an object.
Target site: Boolean MoveNext()
Stack trace: 
   at Barotrauma.GameMain.Load(Boolean isSeparateThread)+MoveNext() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 477
   at Barotrauma.CoroutineManager.PerformCoroutineStep(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 198
   at Barotrauma.CoroutineManager.ExecuteCoroutineThread(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 206
Last debug messages:
[05/29/2023 21:23:35] Coroutine "Load" has failed
[05/29/2023 21:23:35] Coroutine "Load" has thrown an exception {Object reference not set to an instance of an object.}
   at Barotrauma.GameMain.Load(Boolean isSeparateThread)+MoveNext() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 477
   at Barotrauma.CoroutineManager.PerformCoroutineStep(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 198
   at Barotrauma.CoroutineManager.ExecuteCoroutineThread(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 206
[05/29/2023 21:23:31] Attempting to open ALC device "OpenAL Soft on SPDIF Interface (3- FiiO USB DAC-E10)"
[05/29/2023 21:23:28] Logged in as Krzeszny (SteamID STEAM_1:1:17098743)
```

**Comment by Regalis11** [comment]
This seems like it could be caused by an error in some of the mods you've installed (probably the core package), but I don't think we can diagnose this without knowing which mods you're using.

**Comment by Krzeszny** [comment]
Happened only once. You can close it, I can't provide more info.
