### ISSUE TITLE
The game crashed when the submarine reached the buffer zone near the end of the level and few crewmembers suffered a damage

### ISSUE THREAD

**Issue by UzbekyMan** [Regalis11/Barotrauma#12149]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

**Precondition:**
The new campaign has been started few months ago. There were 5 players plus one bot played this campaign while the error occured. Level identifier: plateaubasic, biom: Aphotic Plateau.
Game events on this level we have met: the ruins (according to the "Scan ruins" mission), the cave with thorium ore (according to "Mine minerals" mission), thalamus, few spinelings, few crawlers and tiger threshers.

**Observed behavior:**
The submarine and all healthy crewmembers (5 players and 1 bot) reached the buffer zone between two levels. We were still on the previous level but it was about 25 meters away from borderline between levels and we already could open the map on the top of the screen. In this time the tiger threshers attacked us, killed the bot and knocked out one player. Then in few seconds the game has crushed for every five players.
[06/10/2023 21:36:15] Received STARTGAMEFINALIZE packet. Round init status: Started
[06/10/2023 21:36:14] Received STARTGAMEFINALIZE packet. Round init status: Started
[06/10/2023 21:36:12]  -0: EstimateSteamLobbyPing (STEAM_1:1:117664308), WaitingForActivation
[06/10/2023 21:36:12] Task count: 1
[06/10/2023 21:36:12] Received STARTGAMEFINALIZE packet. Round init status: WaitingForStartGameFinalize
[06/10/2023 21:36:06] Could not find a suitable module for the location type LocationType (None). Module flag: Airlock.
[06/10/2023 21:36:06] Generating an outpost for the start of the level... (Location: Asterius Linea, level type: LocationConnection)
[06/10/2023 21:36:04] Server running slowly (56 updates/s)!
[06/10/2023 21:36:00] Level identifier: plateaubasic
[06/10/2023 21:35:48] Cosy
[06/10/2023 21:35:48] FBI Ludmila
[06/10/2023 21:35:48] UzbekyMan
[06/10/2023 21:35:48] dorianclover
[06/10/2023 21:35:48] Jake Gyllenhaal
[06/10/2023 21:35:48] WARNING: Failed to activate a location type change in the location "Kermario Fossa". Location index out of bounds (1).

**Two full crash reports are attached below**

**Expected behavior:**
We should being manage to successfully docking the end of the level and be able to launch the next level after that.
IMPORTANT: the next level to us in this campaign is caverns, not an outpost (meanwhile according to logs the game tried to generate the outpost for us).

### Reproduction steps

1. Start the new level of the campaign
2. Reach the edge of the level and be near the docking point to finish the level and enter the new caverns without outpost
3. Make sure one or few crewmembers took serios damage, killed or incapasitated
4. Observe the game crash

### Bug prevalence

Just once

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 06/10/2023 23:03:59)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

9336E644980627F155F3EC9C12F39BCC

Game version 1.0.13.2 (ReleaseWindows, branch release/1.0-patch-1-hotfix, revision 122a798c9a)
Graphics mode: 2560x1440 (BorderlessWindowed)
VSync ON
Language: Russian
Selected content packages: Vanilla (E7A137B)
Level seed: Asterius Linea96Brunhes125
Loaded submarine: Herja (9821DED452F78B4A887CCD4C756B0178)
Selected screen: Barotrauma.GameScreen
SteamManager initialized
Client (Round had started)

System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit
    GPU name: AMD Radeon RX 6800 XT
    Display mode: {Width:2560 Height:1440 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void Update(Single, Barotrauma.Camera)
Stack trace: 
   at Barotrauma.Items.Components.Rope.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Rope.cs:line 0
   at Barotrauma.Item.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 1991
   at Barotrauma.MapEntity.UpdateAll(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\MapEntity.cs:line 649
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 248
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 881
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[06/10/2023 21:40:56] Error while reading a message from the server. Entity event data exceeds the size of the buffer (current position: 208, length: 224).
Previous entities:
Навигационный терминал (ID: 416)
Живострел (ID: 7581)
Вырост (ID: 7337)
[06/10/2023 21:36:39] Cosy
[06/10/2023 21:36:39] FBI Ludmila
[06/10/2023 21:36:39] UzbekyMan
[06/10/2023 21:36:39] dorianclover
[06/10/2023 21:36:39] Jake Gyllenhaal
[06/10/2023 21:36:30] Cosy
[06/10/2023 21:36:30] FBI Ludmila
[06/10/2023 21:36:30] UzbekyMan
[06/10/2023 21:36:30] dorianclover
[06/10/2023 21:36:30] Jake Gyllenhaal
[06/10/2023 21:36:16] FBI Ludmila
[06/10/2023 21:36:16] UzbekyMan
[06/10/2023 21:36:16] dorianclover
[06/10/2023 21:36:16] Jake Gyllenhaal
[06/10/2023 21:36:16] Cosy
[06/10/2023 21:36:15] Received STARTGAMEFINALIZE packet. Round init status: Started
[06/10/2023 21:36:14] Received STARTGAMEFINALIZE packet. Round init status: Started
[06/10/2023 21:36:12]  -0: EstimateSteamLobbyPing (STEAM_1:1:117664308), WaitingForActivation
[06/10/2023 21:36:12] Task count: 1
[06/10/2023 21:36:12] Received STARTGAMEFINALIZE packet. Round init status: WaitingForStartGameFinalize
[06/10/2023 21:36:06] Could not find a suitable module for the location type LocationType (None). Module flag: Airlock.
[06/10/2023 21:36:06] Generating an outpost for the start of the level... (Location: Asterius Linea, level type: LocationConnection)
[06/10/2023 21:36:04] Server running slowly (56 updates/s)!
[06/10/2023 21:36:00] Level identifier: plateaubasic
[06/10/2023 21:35:48] Cosy
[06/10/2023 21:35:48] FBI Ludmila
[06/10/2023 21:35:48] UzbekyMan
[06/10/2023 21:35:48] dorianclover
[06/10/2023 21:35:48] Jake Gyllenhaal
[06/10/2023 21:35:48] WARNING: Failed to activate a location type change in the location "Kermario Fossa". Location index out of bounds (1).
[06/10/2023 21:35:47] Cosy
[06/10/2023 21:35:47] FBI Ludmila
[06/10/2023 21:35:47] UzbekyMan
[06/10/2023 21:35:47] dorianclover
[06/10/2023 21:35:47] Jake Gyllenhaal
[06/10/2023 21:35:47] Cosy
[06/10/2023 21:35:47] FBI Ludmila
[06/10/2023 21:35:47] UzbekyMan
[06/10/2023 21:35:47] dorianclover
[06/10/2023 21:35:47] Jake Gyllenhaal
[06/10/2023 21:15:09] Cosy
[06/10/2023 21:15:09] FBI Ludmila
[06/10/2023 21:15:09] UzbekyMan
[06/10/2023 21:15:09] dorianclover
[06/10/2023 21:15:09] Jake Gyllenhaal
[06/10/2023 21:15:09] Cosy
[06/10/2023 21:15:09] FBI Ludmila
[06/10/2023 21:15:09] UzbekyMan
[06/10/2023 21:15:09] dorianclover
[06/10/2023 21:15:09] Jake Gyllenhaal
[06/10/2023 21:15:05] dorianclover
[06/10/2023 21:15:05] Cosy
[06/10/2023 21:15:05] FBI Ludmila
[06/10/2023 21:15:05] UzbekyMan
[06/10/2023 21:15:05] Jake Gyllenhaal
[06/10/2023 21:14:55] FBI Ludmila
[06/10/2023 21:14:55] UzbekyMan
[06/10/2023 21:14:54] dorianclover
[06/10/2023 21:14:54] Jake Gyllenhaal
[06/10/2023 21:14:54] Cosy
[06/10/2023 21:14:52] Received STARTGAMEFINALIZE packet. Round init status: Started
[06/10/2023 21:14:52]  -0: EstimateSteamLobbyPing (STEAM_1:1:117664308), WaitingForActivation
[06/10/2023 21:14:52] Task count: 1
[06/10/2023 21:14:52] Received STARTGAMEFINALIZE packet. Round init status: WaitingForStartGameFinalize
[06/10/2023 21:14:46] Generating an outpost for the start of the level... (Location: Жилой аванпост Brunhes, level type: Outpost)
[06/10/2023 21:14:46] Level identifier: outpostlevel
[06/10/2023 21:14:34] Cosy
[06/10/2023 21:14:34] FBI Ludmila
[06/10/2023 21:14:34] UzbekyMan
[06/10/2023 21:14:34] dorianclover
[06/10/2023 21:14:34] Jake Gyllenhaal
[06/10/2023 21:14:32] Cosy
[06/10/2023 21:14:32] FBI Ludmila
[06/10/2023 21:14:32] UzbekyMan
[06/10/2023 21:14:32] dorianclover
[06/10/2023 21:14:32] Jake Gyllenhaal
[06/10/2023 21:14:32] Cosy
[06/10/2023 21:14:32] FBI Ludmila
[06/10/2023 21:14:32] UzbekyMan
[06/10/2023 21:14:32] dorianclover
[06/10/2023 21:14:32] Jake Gyllenhaal
[06/10/2023 21:14:31] Server running slowly (56 updates/s)!
[06/10/2023 20:51:09] Cosy
[06/10/2023 20:51:09] FBI Ludmila
[06/10/2023 20:51:09] UzbekyMan
[06/10/2023 20:51:09] dorianclover
[06/10/2023 20:51:09] Jake Gyllenhaal
[06/10/2023 20:51:07] Cosy
[06/10/2023 20:51:07] FBI Ludmila
[06/10/2023 20:51:07] UzbekyMan
[06/10/2023 20:51:07] dorianclover
[06/10/2023 20:51:07] Jake Gyllenhaal
[06/10/2023 20:50:58] dorianclover
[06/10/2023 20:50:58] Jake Gyllenhaal
[06/10/2023 20:50:58] Cosy
[06/10/2023 20:50:58] FBI Ludmila
[06/10/2023 20:50:58] UzbekyMan
[06/10/2023 20:50:56] FBI Ludmila
[06/10/2023 20:50:55] UzbekyMan
[06/10/2023 20:50:55] dorianclover
[06/10/2023 20:50:55] Jake Gyllenhaal
[06/10/2023 20:50:54] Cosy
[06/10/2023 20:50:53] Received STARTGAMEFINALIZE packet. Round init status: Started
[06/10/2023 20:50:53] Server running slowly (54 updates/s)!
[06/10/2023 20:50:53] Received STARTGAMEFINALIZE packet. Round init status: Started
[06/10/2023 20:50:50]  -0: EstimateSteamLobbyPing (STEAM_1:1:117664308), WaitingForActivation
[06/10/2023 20:50:50] Task count: 1
[06/10/2023 20:50:50] Received STARTGAMEFINALIZE packet. Round init status: WaitingForStartGameFinalize
[06/10/2023 20:50:42] Generating an outpost for the end of the level... (Location: Жилой аванпост Brunhes, level type: LocationConnection)
[06/10/2023 20:50:38] Level identifier: plateaubasic
[06/10/2023 20:46:13] Attempting to open ALC device "OpenAL Soft on Динамики (Realtek(R) Audio)"
[06/10/2023 20:46:11] Logged in as UzbekyMan (SteamID STEAM_1:0:80285749)

ANOTHER CRASH REPORT FROM THE HOST OF THIS CAMPAIGN

Barotrauma Client crash report (generated on 06/10/2023 23:03:58)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

9336E644980627F155F3EC9C12F39BCC

Game version 1.0.13.2 (ReleaseWindows, branch release/1.0-patch-1-hotfix, revision 122a798c9a)
Graphics mode: 3840x2160 (Fullscreen)
VSync ON
Language: Russian
Selected content packages: Vanilla (E7A137B)
Level seed: Asterius Linea96Brunhes125
Loaded submarine: Herja (9821DED452F78B4A887CCD4C756B0178)
Selected screen: Barotrauma.GameScreen
SteamManager initialized
Client (Round had started)

System info:
    Operating system: Microsoft Windows NT 10.0.19045.0 64 bit
    GPU name: NVIDIA GeForce RTX 3070
    Display mode: {Width:2560 Height:1440 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void Update(Single, Barotrauma.Camera)
Stack trace: 
   at Barotrauma.Items.Components.Rope.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Rope.cs:line 0
   at Barotrauma.Item.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 1991
   at Barotrauma.MapEntity.UpdateAll(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\MapEntity.cs:line 649
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 248
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 881
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[06/10/2023 21:40:54] Error while reading a message from the server. Entity event data exceeds the size of the buffer (current position: 208, length: 224).
Previous entities:
Навигационный терминал (ID: 416)
Живострел (ID: 7581)
Вырост (ID: 7337)
[06/10/2023 21:36:37] Cosy
[06/10/2023 21:36:37] FBI Ludmila
[06/10/2023 21:36:37] UzbekyMan
[06/10/2023 21:36:37] dorianclover
[06/10/2023 21:36:37] Jake Gyllenhaal
[06/10/2023 21:36:29] Cosy
[06/10/2023 21:36:29] FBI Ludmila
[06/10/2023 21:36:29] UzbekyMan
[06/10/2023 21:36:29] dorianclover
[06/10/2023 21:36:29] Jake Gyllenhaal
[06/10/2023 21:36:14] Cosy
[06/10/2023 21:36:14] FBI Ludmila
[06/10/2023 21:36:14] UzbekyMan
[06/10/2023 21:36:14] dorianclover
[06/10/2023 21:36:14] Jake Gyllenhaal
[06/10/2023 21:36:11] Cosy
[06/10/2023 21:36:11] FBI Ludmila
[06/10/2023 21:36:11] UzbekyMan
[06/10/2023 21:36:11] dorianclover
[06/10/2023 21:36:11] Jake Gyllenhaal
[06/10/2023 21:36:09] FBI Ludmila
[06/10/2023 21:36:09] UzbekyMan
[06/10/2023 21:36:08] dorianclover
[06/10/2023 21:36:08] Jake Gyllenhaal
[06/10/2023 21:36:08] Cosy
[06/10/2023 21:36:07] Received STARTGAMEFINALIZE packet. Round init status: Started
[06/10/2023 21:36:06] Task count: 0
[06/10/2023 21:36:06] Received STARTGAMEFINALIZE packet. Round init status: WaitingForStartGameFinalize
[06/10/2023 21:36:03] Server running slowly (56 updates/s)!
[06/10/2023 21:36:01] Could not find a suitable module for the location type LocationType (None). Module flag: Airlock.
[06/10/2023 21:36:01] Generating an outpost for the start of the level... (Location: Asterius Linea, level type: LocationConnection)
[06/10/2023 21:35:56] Level identifier: plateaubasic
[06/10/2023 21:35:47] Cosy
[06/10/2023 21:35:47] FBI Ludmila
[06/10/2023 21:35:47] UzbekyMan
[06/10/2023 21:35:47] dorianclover
[06/10/2023 21:35:47] Jake Gyllenhaal
[06/10/2023 21:35:47] Cosy
[06/10/2023 21:35:47] FBI Ludmila
[06/10/2023 21:35:47] UzbekyMan
[06/10/2023 21:35:47] dorianclover
[06/10/2023 21:35:47] Jake Gyllenhaal
[06/10/2023 21:35:46] Cosy
[06/10/2023 21:35:46] FBI Ludmila
[06/10/2023 21:35:46] UzbekyMan
[06/10/2023 21:35:46] dorianclover
[06/10/2023 21:35:46] Jake Gyllenhaal
[06/10/2023 21:35:46] WARNING: Failed to activate a location type change in the location "Kermario Fossa". Location index out of bounds (1).
[06/10/2023 21:35:45] Cosy
[06/10/2023 21:35:45] FBI Ludmila
[06/10/2023 21:35:45] UzbekyMan
[06/10/2023 21:35:45] dorianclover
[06/10/2023 21:35:45] Jake Gyllenhaal
[06/10/2023 21:15:08] FBI Ludmila
[06/10/2023 21:15:08] UzbekyMan
[06/10/2023 21:15:08] dorianclover
[06/10/2023 21:15:08] Jake Gyllenhaal
[06/10/2023 21:15:08] Cosy
[06/10/2023 21:15:08] FBI Ludmila
[06/10/2023 21:15:08] UzbekyMan
[06/10/2023 21:15:08] dorianclover
[06/10/2023 21:15:08] Jake Gyllenhaal
[06/10/2023 21:15:08] Cosy
[06/10/2023 21:15:04] FBI Ludmila
[06/10/2023 21:15:04] UzbekyMan
[06/10/2023 21:15:04] Jake Gyllenhaal
[06/10/2023 21:15:04] Cosy
[06/10/2023 21:15:03] dorianclover
[06/10/2023 21:14:51] Cosy
[06/10/2023 21:14:51] FBI Ludmila
[06/10/2023 21:14:51] UzbekyMan
[06/10/2023 21:14:51] dorianclover
[06/10/2023 21:14:51] Jake Gyllenhaal
[06/10/2023 21:14:49] Cosy
[06/10/2023 21:14:49] FBI Ludmila
[06/10/2023 21:14:49] UzbekyMan
[06/10/2023 21:14:49] dorianclover
[06/10/2023 21:14:49] Jake Gyllenhaal
[06/10/2023 21:14:48] FBI Ludmila
[06/10/2023 21:14:48] UzbekyMan
[06/10/2023 21:14:48] dorianclover
[06/10/2023 21:14:48] Cosy
[06/10/2023 21:14:48] Jake Gyllenhaal
[06/10/2023 21:14:47] Received STARTGAMEFINALIZE packet. Round init status: Started
[06/10/2023 21:14:47] Task count: 0
[06/10/2023 21:14:47] Received STARTGAMEFINALIZE packet. Round init status: WaitingForStartGameFinalize
[06/10/2023 21:14:42] Generating an outpost for the start of the level... (Location: Жилой аванпост Brunhes, level type: Outpost)
[06/10/2023 21:14:42] Level identifier: outpostlevel
[06/10/2023 21:14:32] Cosy
[06/10/2023 21:14:32] FBI Ludmila
[06/10/2023 21:14:32] UzbekyMan
[06/10/2023 21:14:32] dorianclover
[06/10/2023 21:14:32] Jake Gyllenhaal
[06/10/2023 21:14:32] Cosy
[06/10/2023 21:14:32] FBI Ludmila
[06/10/2023 21:14:32] UzbekyMan
[06/10/2023 21:14:32] dorianclover
[06/10/2023 21:14:32] Jake Gyllenhaal
[06/10/2023 21:14:31] Cosy
[06/10/2023 21:14:31] FBI Ludmila
[06/10/2023 21:14:31] UzbekyMan
[06/10/2023 21:14:31] dorianclover
[06/10/2023 21:14:31] Jake Gyllenhaal
[06/10/2023 21:14:31] Cosy
[06/10/2023 21:14:31] FBI Ludmila
[06/10/2023 21:14:31] UzbekyMan
[06/10/2023 21:14:31] dorianclover
[06/10/2023 21:14:31] Jake Gyllenhaal
[06/10/2023 21:14:31] Server running slowly (56 updates/s)!
[06/10/2023 20:56:41] WARNING: Received a potentially invalid ENTITY_POSITION message.Entity identifier does not match (server entity is chaingunbolt, client entity is depletedfuelbolt). Ignoring the message...
[06/10/2023 20:51:07] Cosy
[06/10/2023 20:51:07] FBI Ludmila
[06/10/2023 20:51:07] UzbekyMan
[06/10/2023 20:51:07] dorianclover
[06/10/2023 20:51:07] Jake Gyllenhaal
[06/10/2023 20:51:05] Cosy
[06/10/2023 20:51:05] FBI Ludmila
[06/10/2023 20:51:05] UzbekyMan
[06/10/2023 20:51:05] dorianclover
[06/10/2023 20:51:05] Jake Gyllenhaal
[06/10/2023 20:50:55] Cosy
[06/10/2023 20:50:55] FBI Ludmila
[06/10/2023 20:50:55] UzbekyMan
[06/10/2023 20:50:55] dorianclover
[06/10/2023 20:50:55] Jake Gyllenhaal
[06/10/2023 20:50:52] Cosy
[06/10/2023 20:50:52] FBI Ludmila
[06/10/2023 20:50:52] UzbekyMan
[06/10/2023 20:50:52] dorianclover
[06/10/2023 20:50:52] Jake Gyllenhaal
[06/10/2023 20:50:46] FBI Ludmila
[06/10/2023 20:50:46] Server running slowly (54 updates/s)!
[06/10/2023 20:50:44] UzbekyMan
[06/10/2023 20:50:44] dorianclover
[06/10/2023 20:50:44] Jake Gyllenhaal
[06/10/2023 20:50:44] Cosy
[06/10/2023 20:50:43] Received STARTGAMEFINALIZE packet. Round init status: Started
[06/10/2023 20:50:42] Received STARTGAMEFINALIZE packet. Round init status: Started
[06/10/2023 20:50:41] Task count: 0
[06/10/2023 20:50:41] Received STARTGAMEFINALIZE packet. Round init status: WaitingForStartGameFinalize
[06/10/2023 20:50:36] Generating an outpost for the end of the level... (Location: Жилой аванпост Brunhes, level type: LocationConnection)
[06/10/2023 20:50:34] Level identifier: plateaubasic
[06/10/2023 20:46:03] Lobby created!
[06/10/2023 20:45:18] Attempting to open ALC device "OpenAL Soft on Динамики (Logitech G432 Gaming Headset)"
[06/10/2023 20:45:12] Logged in as Cosy (SteamID STEAM_1:1:117664308)
```

**Comment by Regalis11** [comment]
Based on the crash report, this seems to be a duplicate of https://github.com/Regalis11/Barotrauma/issues/11666.

Sorry for the inconvenience - we've got a fix coming up for this in the next patch.
