### ISSUE TITLE
Console command `analyzeitem ???` crashes game

### ISSUE THREAD

**Issue by Next-Door-Tech** [Regalis11/Barotrauma#12142]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Entering the command `analyzeitem ???` into the in-game F3 console causes a crash. I suspect this may have to do with the fact that there are multiple different items with the in-game name "???".

Placing the item name in quotes, i.e. `analyzeitem "???"` gives the same error.

Note: this issue appears similar, but not identical to resolved issue #7386

---

Note that other commands using "???" as an item name *do* work without crashing, for instance:
`enablecheats` then `spawnitem ??? inventory 1`  gives the player one researcherscribbble1, though I think it may have given me a different item by the same name (some sort of alien artifact) at another point, which is interesting.

### Reproduction steps

Open F3 console (either in menu or in game) and enter one of:
`analyzeitem ???`
`analyzeitem "???"`

### Bug prevalence

Just once

### Version

v1.0.13.2

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 06/09/2023 16:15:25)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

9336E644980627F155F3EC9C12F39BCC

Game version 1.0.13.2 (ReleaseWindows, branch release/1.0-patch-1-hotfix, revision 122a798c9a)
Graphics mode: 2560x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla (E7A137B)
Level seed: no level loaded
Loaded submarine: None
Selected screen: Barotrauma.MainMenuScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit
    GPU name: AMD Radeon Pro 5500M
    Display mode: {Width:2560 Height:1080 Format:Color AspectRatio:2.3703704}
    GPU status: Normal

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void <InitProjectSpecific>b__23_70(System.String[])
Stack trace: 
   at Barotrauma.DebugConsole.<>c.<InitProjectSpecific>b__23_70(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\DebugConsole.cs:line 1467
   at Barotrauma.DebugConsole.Command.Execute(String[] args) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\DebugConsole.cs:line 86
   at Barotrauma.DebugConsole.ExecuteCommand(String command) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\DebugConsole.cs:line 0
   at Barotrauma.DebugConsole.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\DebugConsole.cs:line 195
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 881
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[06/09/2023 16:15:25] analyzeitem ???
[06/09/2023 16:14:50] Attempting to open ALC device "OpenAL Soft on Speakers (2- Apple Audio Device)"
[06/09/2023 16:14:48] Logged in as Cancun101 (SteamID STEAM_1:0:45147753)
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a4017db5f36dbeae222e3b72369a2da9f41c0dce (commit in our private repo)

**Comment by Jasontti** [comment]
Tested.
No issues found.
Closing ticket.
