### ISSUE TITLE
Enabling an updated workshop item crashed the game.

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#1216]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I had my workshop items enabled, I learned of an update to a submarine and went to enable it again as it had been updated. the game then crashed.

**Steps To Reproduce**
Not 100% sure, but may be because I manually wiped my old submarines clean before going to enable relevant workshop addons again, which it appeared as inactive.

**Version**
0.8.9.5 closed alpha

**Additional information**
```
Exception: Object reference not set to an instance of an object.
Target site: Boolean ToggleItemEnabled(Barotrauma.GUITickBox)
Stack trace: 
   at Barotrauma.SteamWorkshopScreen.ToggleItemEnabled(GUITickBox tickBox)
   at Barotrauma.GUITickBox.Update(Single deltaTime)
   at Barotrauma.GUI.<>c__DisplayClass96_0.<Update>b__0(GUIComponent c)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Barotrauma.GUI.Update(Single deltaTime)
   at Barotrauma.GameMain.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at MonoGame.Framework.WinFormsGameWindow.TickOnIdle(Object sender, EventArgs e)
   at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at MonoGame.Framework.WinFormsGameWindow.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Barotrauma.Program.Main()


Last debug messages:
[05/03/2019 01:15:15] Cannot enable workshop item "Capelin Mk4". The file "Data\ContentPackages\Capelin Mk4.xml" would be overwritten by the item.
[05/03/2019 01:14:38] Enter "help" for a list of available console commands
[05/03/2019 01:14:38] Press F3 to open/close the debug console
[05/03/2019 01:14:35] Error in content package "Capelin Mk4" - file "Submarines\Capelin Mk4.sub" not found.
```

**Comment by Regalis11** [comment]
Should be fixed by b2e8ed5 and acb7c1e
