### ISSUE TITLE
Unable to load single player campaign save (an item with the same key has already been added in LevelData..ctor)

### ISSUE THREAD

**Issue by Arbiter1479** [Regalis11/Barotrauma#12170]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

This save file has been around for quite a fair bit, around 1.0 when I first got the game till now. I've been playing it on and off with mods and stuff.

It's only today where I was able to load into the save just fine that when I came back to reload it again afterwards, it threw an error and reattempting to reload it causes the game to crash.

Looking at the console log, it seems to be referencing to an outpost event by the husk cult that somehow has a duplicate.

I originally thought it was a mod I had added (Of which one was an ID card mod and another was a molloch mod) but neither seems to be the culprit as removing them still results in the same error.

![ApplicationFrameHost_2023-06-16_20-09-54](https://github.com/Regalis11/Barotrauma/assets/14255076/804de265-7ac2-4598-9610-78d8f6ef96be)

### Reproduction steps

1. Load save file
2. Game tries to load, throws error
3. Player is kicked back to load save menu
4. Error log is shown

### Bug prevalence

Happens every time I play

### Version

Other

### -

LuaCsForBarotrauma revision fd74c08a8f version 1.0.66

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Loading save "C:\Users\chnyi\AppData\Local\Daedalic Entertainment GmbH\Barotrauma\Save 2V2.save" failed {An item with the same key has already been added. Key: Barotrauma.EventSet (outpostevents.huskcult)}
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Barotrauma.LevelData..ctor(XElement element, Nullable`1 forceDifficulty, Boolean clampDifficultyToBiome) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Levels\LevelData.cs:line 181
   at Barotrauma.Location..ctor(CampaignMode campaign, XElement element) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Map\Location.cs:line 640
   at Barotrauma.Map..ctor(CampaignMode campaign, XElement element) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Map\Map.cs:line 120
   at Barotrauma.Map.Load(CampaignMode campaign, XElement element) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Map\Map.cs:line 1428
   at Barotrauma.SinglePlayerCampaign..ctor(XElement element) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameSession\GameModes\SinglePlayerCampaign.cs:line 123
   at Barotrauma.GameSession..ctor(SubmarineInfo submarineInfo, List`1 ownedSubmarines, XDocument doc, String saveFile) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameSession.cs:line 161
   at Barotrauma.SaveUtil.LoadGame(String filePath) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SaveUtil.cs:line 144
   at Barotrauma.MainMenuScreen.LoadGame(String saveFile) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\MainMenuScreen.cs:line 1222
```

**Comment by Arbiter1479** [comment]
After some additional testing, it seems like one of the two mentioned mods is causing the save file corruption as with the two enabled, I can't even start a new campaign.

Removing both of the mods allows me to start a new campaign normally

**Comment by Arbiter1479** [comment]
So the same thing happened yet again, but this time round, starting a new campaign works fine but not loading the save. Funny thing is it loaded just fine mere moments before.

The error code is the same as well, but this time round the `outpostevents.huskcult` is replaced with `outpostevents.separatists.triggeralways`

![ApplicationFrameHost_2023-06-17_18-56-40](https://github.com/Regalis11/Barotrauma/assets/14255076/d69e1c1d-81b7-45e2-baf9-dddf1542fa04)

**Comment by Regalis11** [comment]
Thank you for the report! Based on the error message, it seems like the same event was completed twice in the same level, and there was a bug that caused this exception to be thrown when when loading the event history. Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/a9703189cfe7f2aab1c256a8a4e60b9cefbb4799 (commit in our private repository).

Would it be possible for you to send us the save file (note that you need to .zip it first, because github doesn't allow attaching files with the .save file extension)? That'd help us a lot in testing the fix and verifying the issue has been resolved. Thanks and sorry for the inconvenience!

**Comment by Arbiter1479** [comment]
I can send the save file over, downside is it's heavily modded (uses a custom workshop sub and all) stuff so I'm not sure if it'll load correctly but I've included both the custom submarine and the save file along with this reply for your testing! 
[Barotrauma Save Test File.zip](https://github.com/Regalis11/Barotrauma/files/11787649/Barotrauma.Save.Test.File.zip)

**Comment by Regalis11** [comment]
Thanks! It does seem like the fixed worked and the save loads with no issues now. We've now tested the fix internally so I'll close the ticket. We're hoping to release a hotfix soon to get this and couple of the other issues in the latest patch fixed.
