### ISSUE TITLE
Crash (Access to the path '\AppData\Local\Daedalic Entertainment GmbH\Barotrauma\temp\Dugong.sub' is denied)

### ISSUE THREAD

**Issue by Koalko69** [Regalis11/Barotrauma#12203]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

[Barotrauma Client crash report.docx](https://github.com/Regalis11/Barotrauma/files/11804313/Barotrauma.Client.crash.report.docx)

### Reproduction steps

Barotrauma Client crash report (generated on 06/20/2023 20:22:25)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

9336E644980627F155F3EC9C12F39BCC

Game version 1.0.13.2 (ReleaseWindows, branch release/1.0-patch-1-hotfix, revision 122a798c9a)
Graphics mode: 1366x768 (BorderlessWindowed)
VSync ON
Language: Russian
Selected content packages: Vanilla (E7A137B)
Level seed: no level loaded
Loaded submarine: None
Selected screen: Barotrauma.MainMenuScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 6.1.7601 Service Pack 1 64 bit
    GPU name: ATI Mobility Radeon HD 5470
    Display mode: {Width:1366 Height:768 Format:Color AspectRatio:1.7786459}
    GPU status: Normal

Exception: Access to the path 'C:\Users\Ярослав\AppData\Local\Daedalic Entertainment GmbH\Barotrauma\temp\Dugong.sub' is denied. (System.UnauthorizedAccessException)
Target site: Void CopyFile(System.String, System.String, Boolean)
Stack trace: 
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at Barotrauma.IO.File.Copy(String src, String dest, Boolean overwrite) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SafeIO.cs:line 350
   at Barotrauma.MainMenuScreen.StartGame(SubmarineInfo selectedSub, String savePath, String mapSeed, CampaignSettings settings) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\MainMenuScreen.cs:line 1174
   at Barotrauma.SinglePlayerCampaignSetupUI.FinishSetup(GUIButton btn, Object userdata) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\CampaignSetupUI\SinglePlayerCampaignSetupUI.cs:line 461
   at Barotrauma.GUIButton.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIButton.cs:line 263
   at Barotrauma.GUI.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1247
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 906
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[06/20/2023 20:21:26] WARNING: Server could not be shut down gracefully
[06/20/2023 20:21:24] WARNING: Tried to restore enabled packages multiple times/without performing a backup
[06/20/2023 20:16:29] Attempting to open ALC device "OpenAL Soft on Динамики (Устройство с поддержкой High Definition Audio)"
[06/20/2023 20:16:09] Logged in as FreeTP.Org (SteamID STEAM_1:1:693267135)

### Bug prevalence

Happens every time I play

### Version

Other

### -

v1.0.13.2 by Pioneer

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 06/20/2023 20:22:25)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

9336E644980627F155F3EC9C12F39BCC

Game version 1.0.13.2 (ReleaseWindows, branch release/1.0-patch-1-hotfix, revision 122a798c9a)
Graphics mode: 1366x768 (BorderlessWindowed)
VSync ON
Language: Russian
Selected content packages: Vanilla (E7A137B)
Level seed: no level loaded
Loaded submarine: None
Selected screen: Barotrauma.MainMenuScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 6.1.7601 Service Pack 1 64 bit
    GPU name: ATI Mobility Radeon HD 5470
    Display mode: {Width:1366 Height:768 Format:Color AspectRatio:1.7786459}
    GPU status: Normal

Exception: Access to the path 'C:\Users\Ярослав\AppData\Local\Daedalic Entertainment GmbH\Barotrauma\temp\Dugong.sub' is denied. (System.UnauthorizedAccessException)
Target site: Void CopyFile(System.String, System.String, Boolean)
Stack trace: 
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at Barotrauma.IO.File.Copy(String src, String dest, Boolean overwrite) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SafeIO.cs:line 350
   at Barotrauma.MainMenuScreen.StartGame(SubmarineInfo selectedSub, String savePath, String mapSeed, CampaignSettings settings) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\MainMenuScreen.cs:line 1174
   at Barotrauma.SinglePlayerCampaignSetupUI.FinishSetup(GUIButton btn, Object userdata) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\CampaignSetupUI\SinglePlayerCampaignSetupUI.cs:line 461
   at Barotrauma.GUIButton.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIButton.cs:line 263
   at Barotrauma.GUI.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1247
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 906
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[06/20/2023 20:21:26] WARNING: Server could not be shut down gracefully
[06/20/2023 20:21:24] WARNING: Tried to restore enabled packages multiple times/without performing a backup
[06/20/2023 20:16:29] Attempting to open ALC device "OpenAL Soft on Динамики (Устройство с поддержкой High Definition Audio)"
[06/20/2023 20:16:09] Logged in as FreeTP.Org (SteamID STEAM_1:1:693267135)
```

**Comment by Koalko69** [comment]
Windows 7 64-bit

**Comment by Regalis11** [comment]
Thank you for the report, and sorry for taking so long to reply!

It could be that this is an issue with file access permissions. We've gotten similar reports earlier, here's one with potential steps for fixing the issue: https://github.com/Regalis11/Barotrauma/issues/11489

It could also be that an antivirus program is preventing the game from accessing the AppData folder.

Please let us know if the steps in that earlier ticket help or if you find some other way to work around the issue. Thanks and sorry for the inconvenience!

**Comment by Regalis11** [comment]
Insufficient information to address the issue, closing
