### ISSUE TITLE
Client disconnect with "Failed to spawn item Oxygen Tank {ID 3920 is taken by Oxygen Tank (ID: 3920)}"

### ISSUE THREAD

**Issue by ghost** [Regalis11/Barotrauma#12316]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Public RP server. (seemingly) Custom submarine - everything else is pure vanilla.
We docked - and I got disconnected with following error in console.
![20230710010439_1](https://github.com/Regalis11/Barotrauma/assets/81986452/c0e66b43-c671-40df-9f34-2b7d792df6e1)
Not entirely sure if the intel so slim might come handy for anything - but who knows...

### Reproduction steps

Which ongoing seemingly relevant events we had right before docking (or what I was able to spot anyway):
- 1 man did CPR to a deceased VIP from Escort mission. Which probably did had an oxygen mask in her inventory,
- few +10% quality oxygen tanks were being refilled in a cabinet underneath diving suit locker.

### Bug prevalence

Just once

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Linux (of course)

### Relevant error messages and crash reports

```shell
Failed to spawn item Oxygen Tank {ID 3920 is taken by Oxygen Tank (ID: 3920)}
   at Barotrauma.Entity..ctor(Submarine submarine, UInt16 id) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Entity.cs:line 119
   at Barotrauma.MapEntity..ctor(MapEntityPrefab prefab, Submarine submarine, UInt16 id) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\MapEntity.cs:line 273
   at Barotrauma.Item..ctor(Rectangle newRect, ItemPrefab itemPrefab, Submarine submarine, Boolean callOnItemLoaded, UInt16 id) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 931
   at Barotrauma.Item..ctor(ItemPrefab itemPrefab, Vector2 position, Submarine submarine, UInt16 id, Boolean callOnItemLoaded) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 924
   at Barotrauma.Item.ReadSpawnData(IReadMessage msg, Boolean spawn) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Item.cs:line 1804

Error while reading a message from server. 
Exception thrown while reading segment EntityEvent at position 32.
Inner exception: ID 3920 is taken by Oxygen Tank (ID: 3920)
   at Barotrauma.Entity..ctor(Submarine submarine, UInt16 id) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Entity.cs:line 119
   at Barotrauma.MapEntity..ctor(MapEntityPrefab prefab, Submarine submarine, UInt16 id) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\MapEntity.cs:line 273
   at Barotrauma.Item..ctor(Rectangle newRect, ItemPrefab itemPrefab, Submarine submarine, Boolean callOnItemLoaded, UInt16 id) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 931
   at Barotrauma.Item..ctor(ItemPrefab itemPrefab, Vector2 position, Submarine submarine, UInt16 id, Boolean callOnItemLoaded) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 924
   at Barotrauma.Item.ReadSpawnData(IReadMessage msg, Boolean spawn) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Item.cs:line 1804
   at Barotrauma.EntitySpawner.ClientEventRead(IReadMessage message, Single sendingTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\EntitySpawner.cs:line 13
   at Barotrauma.Networking.ClientEntityEventManager.Read(ServerNetSegment type, IReadMessage msg, Single sendingTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\NetEntityEvent\ClientEntityEventManager.cs:line 220
   at Barotrauma.Networking.GameClient.<>c__DisplayClass119_0.<ReadIngameUpdate>b__0(ServerNetSegment segment, IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 2140
   at Barotrauma.Networking.SegmentTableReader`1.Read(IReadMessage msg, SegmentDataReader segmentDataReader, ExceptionHandler exceptionHandler) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SegmentTable.cs:line 296
```

**Comment by Regalis11** [comment]
No known steps to repro, closing
