### ISSUE TITLE
Starting a new multiplayer campaign throws an error about not being able to load a submarine file

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#12439]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I was able to reproduce this on Windows and Linux

The campaign save does load normally after the error so the error doesn't seem to affect gameplay. 

### Reproduction steps

1. Start a new campaign in multiplayer
2. Notice while the campaign loads there's a error message

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

Unstable (v1.1.3.0)

### -

Latest Unstable build

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Loading submarine "C:\Users\ronik\AppData\Local\Daedalic Entertainment GmbH\Barotrauma\temp\Dugong.sub" failed! {Could not find a part of the path 'C:\Users\ronik\AppData\Local\Daedalic Entertainment GmbH\Barotrauma\temp\Dugong.sub'.}
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at Barotrauma.IO.File.Open(String path, FileMode mode, FileAccess access, Nullable`1 share) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SafeIO.cs:line 400
   at Barotrauma.SaveUtil.DecompressFileToStream(String fileName) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SaveUtil.cs:line 427
   at Barotrauma.SubmarineInfo.OpenFile(String file, Exception& exception) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\SubmarineInfo.cs:line 760
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ff54c1e1669f67917f24978b7affec8beaad9316

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
