### ISSUE TITLE
Failed to find item with ID X for CircuitBoxNode with ID Y

### ISSUE THREAD

**Issue by 3e849f2e5c** [Regalis11/Barotrauma#12502]
This is **not** related to #12501

Something is causing CircuitBoxNode to fail finding the backing item and fail loading, need repro steps

```
Exception: Failed to find item with ID 516 for CircuitBoxNode with ID 0 (System.Exception)
Target site: Barotrauma.CircuitBoxNode LoadFromXML(Barotrauma.ContentXElement, Barotrauma.Items.Components.CircuitBox)
Stack trace: 
   at Barotrauma.CircuitBoxNode.LoadFromXML(ContentXElement element, CircuitBox circuitBox) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CircuitBox\CircuitBoxNode.cs:line 39
   at Barotrauma.Items.Components.CircuitBox.OnMapLoaded() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Signal\CircuitBox.cs:line 176
   at Barotrauma.Item.OnMapLoaded() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 3885
   at Barotrauma.MapEntity.MapLoaded(List`1 entities, Boolean updateHulls) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\MapEntity.cs:line 814
   at Barotrauma.Submarine..ctor(SubmarineInfo info, Boolean showErrorMessages, Func`2 loadEntities, IdRemap linkedRemap) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Submarine.cs:line 1616
   at Barotrauma.GameSession.StartRound(LevelData levelData, Boolean mirrorLevel, SubmarineInfo startOutpost, SubmarineInfo endOutpost) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameSession.cs:line 425
   at Barotrauma.SubEditorScreen.TestSubmarine(GUIButton button, Object obj) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\SubEditorScreen.cs:line 1062
   at Barotrauma.GUIButton.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIButton.cs:line 263
   at Barotrauma.GUI.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1244
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 876
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58
```

**Comment by Regalis11** [comment]
Possible repro steps or more clues here? https://github.com/Regalis11/Barotrauma/issues/12501#issuecomment-1678964839

**Comment by Jasontti** [comment]
Repro steps:


[Crashing-circuit.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBazRKIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3f3408ffb17c819fd0e2441dca58b90bd75cf3c4/Crashing-circuit.zip)

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbEFKIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c550a7bf6bad28c7cbceb770391e6df482b0bff5/2023-08-16%2009-47-47.mp4)

```
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at Barotrauma.CircuitBoxNode..ctor(UInt16 id, Item item, Vector2 position, CircuitBox circuitBox) in /home/joonas/dev/Barotrauma-development/Barotrauma/BarotraumaShared/SharedSource/CircuitBox/CircuitBoxNode.cs:line 19
   at Barotrauma.CircuitBoxNode.LoadFromXML(ContentXElement element, CircuitBox circuitBox) in /home/joonas/dev/Barotrauma-development/Barotrauma/BarotraumaShared/SharedSource/CircuitBox/CircuitBoxNode.cs:line 42
   at Barotrauma.Items.Components.CircuitBox.OnMapLoaded() in /home/joonas/dev/Barotrauma-development/Barotrauma/BarotraumaShared/SharedSource/Items/Components/Signal/CircuitBox.cs:line 175
   at Barotrauma.Item.OnMapLoaded() in /home/joonas/dev/Barotrauma-development/Barotrauma/BarotraumaShared/SharedSource/Items/Item.cs:line 3880
   at Barotrauma.MapEntity.MapLoaded(List`1 entities, Boolean updateHulls) in /home/joonas/dev/Barotrauma-development/Barotrauma/BarotraumaShared/SharedSource/Map/MapEntity.cs:line 818
   at Barotrauma.Submarine..ctor(SubmarineInfo info, Boolean showErrorMessages, Func`2 loadEntities, IdRemap linkedRemap) in /home/joonas/dev/Barotrauma-development/Barotrauma/BarotraumaShared/SharedSource/Map/Submarine.cs:line 1616
   at Barotrauma.GameSession.StartRound(LevelData levelData, Boolean mirrorLevel, SubmarineInfo startOutpost, SubmarineInfo endOutpost) in /home/joonas/dev/Barotrauma-development/Barotrauma/BarotraumaShared/SharedSource/GameSession/GameSession.cs:line 426
   at Barotrauma.SubEditorScreen.TestSubmarine(GUIButton button, Object obj) in /home/joonas/dev/Barotrauma-development/Barotrauma/BarotraumaClient/ClientSource/Screens/SubEditorScreen.cs:line 1062
   at Barotrauma.GUIButton.Update(Single deltaTime) in /home/joonas/dev/Barotrauma-development/Barotrauma/BarotraumaClient/ClientSource/GUI/GUIButton.cs:line 263
   at Barotrauma.GUIComponent.UpdateAuto(Single deltaTime) in /home/joonas/dev/Barotrauma-development/Barotrauma/BarotraumaClient/ClientSource/GUI/GUIComponent.cs:line 455
   at Barotrauma.GUI.Update(Single deltaTime) in /home/joonas/dev/Barotrauma-development/Barotrauma/BarotraumaClient/ClientSource/GUI/GUI.cs:line 1244
   at Barotrauma.GameMain.Update(GameTime gameTime) in /home/joonas/dev/Barotrauma-development/Barotrauma/BarotraumaClient/ClientSource/GameMain.cs:line 876
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in /home/joonas/dev/Barotrauma-development/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 651
   at Microsoft.Xna.Framework.Game.Tick() in /home/joonas/dev/Barotrauma-development/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in /home/joonas/dev/Barotrauma-development/Libraries/MonoGame.Framework/Src/MonoGame.Framework/SDL/SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in /home/joonas/dev/Barotrauma-development/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in /home/joonas/dev/Barotrauma-development/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in /home/joonas/dev/Barotrauma-development/Barotrauma/BarotraumaClient/ClientSource/Program.cs:line 58
../baro-script.sh: line 28: 10275 Aborted                 ./Barotrauma/bin/$2Linux/net6.0/Barotrauma

```

**Comment by 3e849f2e5c** [comment]
Possibly fixed in https://github.com/Regalis11/Barotrauma-development/commit/d5e1a99e6a5ab1865eecd58f0970b20c296a6466

**Comment by Rokvach** [comment]
Looking at GA, so far there hasn't been any circuit box related crashes in the latest Unstable build, this seems to have been fixed and working correctly. Closing.
