### ISSUE TITLE
[Unstable] Crash when killing a thalamus

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#12536]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Killing a thalamus can sometimes cause a crash.

### Reproduction steps

1. `spawnsub Dugong_Wrecked true`
2. Go and kill a couple of the leucocytes
3. Kill the thalamus by destroying the brain

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

Unstable (v1.1.8.0)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Object reference not set to an instance of an object. Void Kill(Barotrauma.CauseOfDeathType, Barotrauma.Affliction, Boolean, Boolean)

Barotrauma Client crash report (generated on 08/20/2023 10:17:39)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

DF657A6096DBB2B49DBDC130AA07B56F

Game version 1.1.8.0 (UnstableWindows, branch release/very-unstable-1.1, revision 9a5f6a3caa)
Graphics mode: 1920x1080 (Fullscreen)
VSync ON
Language: French
Selected content packages: Vanilla (97B31F5)
Level seed: Alkonost63Drizzlecomb Linea81
Loaded submarine: Typhon2 (3C2F610572F01986644510912B94B78A)
Selected screen: Barotrauma.GameScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.22621.0 64 bit
    GPU name: NVIDIA GeForce RTX 3060 Ti
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void Kill(Barotrauma.CauseOfDeathType, Barotrauma.Affliction, Boolean, Boolean)
Stack trace: 
   at Barotrauma.Character.Kill(CauseOfDeathType causeOfDeath, Affliction causeOfDeathAffliction, Boolean isNetworkMessage, Boolean log) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 4600
   at Barotrauma.WreckAI.<>c.<Kill>b__33_2(Character c) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\Wreck\WreckAI.cs:line 383
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Barotrauma.WreckAI.Kill() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\Wreck\WreckAI.cs:line 383
   at Barotrauma.WreckAI.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\Wreck\WreckAI.cs:line 264
   at Barotrauma.Submarine.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Submarine.cs:line 1109
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 280
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 851
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/38252f398a2838873d911da7c9eda73ef893ddb3

**Comment by Jasontti** [comment]
Tested.
No issues found.
Closing ticket.
