### ISSUE TITLE
Crash: "Collection was modified" in `AIObjectiveManager.GetObjective()`

### ISSUE THREAD

**Issue by Daniel-Chin** [Regalis11/Barotrauma#12568]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

After docking with a station, the game entered the "loading" screen but several seconds later crashed. 

### Reproduction steps

Unknown. 

### Bug prevalence

Just once

### Single player or multiplayer?

Single player

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 08/27/2023 16:26:07)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

9F5E3061E92D485CB02263313B29506B

Game version 1.0.21.0 (ReleaseWindows, branch release/summer-patch-hotfix, revision adb80ccd6e)
Graphics mode: 1280x768 (Fullscreen)
VSync OFF
Language: English
Selected content packages: Vanilla (65E9331)
Level seed: Chthonius Linea45
Loaded submarine: Typhon (19BD34AFF564C7028D885C9CE1179D4B)
Selected screen: Barotrauma.RoundSummaryScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19045.0 64 bit
    GPU name: Intel(R) Iris(R) Xe Graphics
    Display mode: {Width:3840 Height:2400 Format:Color AspectRatio:1.6}
    GPU status: Normal

Exception: Collection was modified; enumeration operation may not execute. (System.InvalidOperationException)
Target site: Void ThrowInvalidOperationException_InvalidOperation_EnumFailedVersion()
Stack trace: 
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at Barotrauma.AIObjectiveManager.GetObjective[T]() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\Objectives\AIObjectiveManager.cs:line 203
   at Barotrauma.CrewManager.AddCharacter(Character character, Boolean sortCrewList) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\CrewManager.cs:line 191
   at Barotrauma.CrewManager.InitRound() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\CrewManager.cs:line 319
   at Barotrauma.CrewManager.InitSinglePlayerRound() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameSession\CrewManager.cs:line 3612
   at Barotrauma.SinglePlayerCampaign.Start() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameSession\GameModes\SinglePlayerCampaign.cs:line 250
   at Barotrauma.GameSession.InitializeLevel(Level level) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameSession.cs:line 620
   at Barotrauma.GameSession.StartRound(LevelData levelData, Boolean mirrorLevel, SubmarineInfo startOutpost, SubmarineInfo endOutpost) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameSession.cs:line 470
   at Barotrauma.CampaignMode.<>c__DisplayClass32_0.<<SelectSummaryScreen>b__0>d.MoveNext() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameSession\GameModes\CampaignMode.cs:line 298
--- End of stack trace from previous location ---
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 884
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[08/27/2023 16:26:01] Generating an outpost for the start of the level... (Location: Chthonius Linea Research Facility, level type: Outpost)
[08/27/2023 16:26:00] Level identifier: ridgeoutpost
[08/27/2023 16:25:39] Transitioning to Chthonius Linea45 (current location: Chthonius Linea Research Facility, selected location: Seosu Station, leaving sub: Typhon, at start: True, at end: False, transition type: ReturnToPreviousLocation)
[08/27/2023 15:55:24] Generating an outpost for the start of the level... (Location: Seosu Station, level type: LocationConnection)
[08/27/2023 15:55:23] Generating an outpost for the end of the level... (Location: Chthonius Linea Research Facility, level type: LocationConnection)
[08/27/2023 15:55:22] Level identifier: ridgeadvanced
[08/27/2023 15:55:04] Transitioning to Seosu16Chthonius Linea45 (current location: Chthonius Linea Research Facility, selected location: Seosu Station, leaving sub: Typhon, at start: True, at end: False, transition type: LeaveLocation)
[08/27/2023 15:51:20] Unlocked mission "Mining Diamond" in the connection from "Chthonius Linea Research Facility" to "Rhadamanthys Linea Research Facility".
[08/27/2023 15:51:17] Unlocked mission "Arms Delivery" in the connection from "Chthonius Linea Research Facility" to "Tyre Research Facility".
[08/27/2023 15:51:15] Unlocked mission "Terminate a Swarm" in the connection from "Chthonius Linea Research Facility" to "Bramerton Station".
[08/27/2023 15:51:12] Unlocked mission "Prisoner Transport" in the connection from "Chthonius Linea Research Facility" to "Tyre Research Facility".
[08/27/2023 15:44:41] Unlocked mission "Praise the honkmother" in the connection from "Chthonius Linea Research Facility" to "Seosu Station".
[08/27/2023 15:43:26] Generating an outpost for the start of the level... (Location: Chthonius Linea Research Facility, level type: Outpost)
[08/27/2023 15:43:26] Level identifier: ridgeoutpost
[08/27/2023 15:43:06] Transitioning to Chthonius Linea45 (current location: Bramerton Station, selected location: Chthonius Linea Research Facility, leaving sub: Typhon, at start: False, at end: True, transition type: ProgressToNextLocation)
[08/27/2023 15:32:38] Could not find a spawn point for a SpawnAction (spawn location: BeaconStation (tag: beacon_bandit), skipping.
[08/27/2023 15:32:26] Generating an outpost for the start of the level... (Location: Chthonius Linea Research Facility, level type: LocationConnection)
[08/27/2023 15:32:24] Generating an outpost for the end of the level... (Location: Bramerton Station, level type: LocationConnection)
[08/27/2023 15:32:24] Level identifier: ridgeadvanced
[08/27/2023 15:32:02] Transitioning to Chthonius Linea45Bramerton86 (current location: Bramerton Station, selected location: Chthonius Linea Research Facility, leaving sub: Typhon, at start: True, at end: False, transition type: LeaveLocation)
[08/27/2023 15:18:46] Generating an outpost for the start of the level... (Location: Bramerton Station, level type: Outpost)
[08/27/2023 15:18:46] Level identifier: ridgeoutpost
[08/27/2023 15:18:29] Transitioning to Bramerton86 (current location: Bramerton Station, selected location: Chthonius Linea Research Facility, leaving sub: Typhon, at start: True, at end: False, transition type: ReturnToPreviousLocation)
[08/27/2023 15:17:02] Could not find a spawn point for a SpawnAction (spawn location: BeaconStation (tag: beacon_bandit), skipping.
[08/27/2023 15:16:51] Generating an outpost for the start of the level... (Location: Chthonius Linea Research Facility, level type: LocationConnection)
[08/27/2023 15:16:50] Generating an outpost for the end of the level... (Location: Bramerton Station, level type: LocationConnection)
[08/27/2023 15:16:49] Level identifier: ridgeadvanced
[08/27/2023 15:16:28] Transitioning to Chthonius Linea45Bramerton86 (current location: Bramerton Station, selected location: Chthonius Linea Research Facility, leaving sub: Typhon, at start: True, at end: False, transition type: LeaveLocation)
[08/27/2023 15:13:08] Unlocked mission "Jailbreak" in the location "Harmonia Linea".
[08/27/2023 15:06:52] WARNING: Failed to unlock a mission with the tag "mudraptornest": all available missions have already been unlocked.
[08/27/2023 15:06:49] Unlocked mission "Getting rid of Mudraptors" in the connection from "Bramerton Station" to "Couwola Mining Facility".
[08/27/2023 15:06:46] Unlocked mission "Separatist Activist Transport" in the connection from "Bramerton Station" to "Chthonius Linea Research Facility".
[08/27/2023 15:06:42] Unlocked mission "Mining Titanite" in the connection from "Bramerton Station" to "Couwola Mining Facility".
[08/27/2023 15:03:00] WARNING: Failed to unlock a mission with the tag "cargohuskcult": all available missions have already been unlocked.
[08/27/2023 15:01:47] Generating an outpost for the start of the level... (Location: Bramerton Station, level type: Outpost)
[08/27/2023 15:01:47] Level identifier: ridgeoutpost
[08/27/2023 15:01:28] Transitioning to Bramerton86 (current location: Autonoe Linea Research Center, selected location: Bramerton Station, leaving sub: Typhon, at start: False, at end: True, transition type: ProgressToNextLocation)
[08/27/2023 14:38:16] Could not find a spawn point for a SpawnAction (spawn location: BeaconStation (tag: beacon_bandit), skipping.
[08/27/2023 14:38:02] Generating an outpost for the start of the level... (Location: Bramerton Station, level type: LocationConnection)
[08/27/2023 14:38:01] Generating an outpost for the end of the level... (Location: Autonoe Linea Research Center, level type: LocationConnection)
[08/27/2023 14:38:01] Level identifier: ridgebasic
[08/27/2023 14:37:44] Transitioning to Bramerton86Autonoe Linea113 (current location: Autonoe Linea Research Center, selected location: Bramerton Station, leaving sub: Typhon, at start: True, at end: False, transition type: LeaveLocation)
[08/27/2023 14:36:49] WARNING: Failed to unlock a mission with the tag "escortterroristscoalition": all available missions have already been unlocked.
[08/27/2023 14:36:46] Unlocked mission "Wreck salvage" in the connection from "Autonoe Linea Research Center" to "Bramerton Station".
[08/27/2023 14:36:44] Unlocked mission "Separatist Vessel" in the connection from "Autonoe Linea Research Center" to "Bramerton Station".
[08/27/2023 14:36:42] Unlocked mission "Arms Delivery" in the connection from "Autonoe Linea Research Center" to "Sidon Flexus Institute of Astrobiology".
[08/27/2023 14:31:59] Generating an outpost for the start of the level... (Location: Autonoe Linea Research Center, level type: Outpost)
[08/27/2023 14:31:59] Level identifier: ridgeoutpost
[08/27/2023 14:31:41] Transitioning to Autonoe Linea113 (current location: Sidon Flexus Institute of Astrobiology, selected location: Autonoe Linea Research Center, leaving sub: Typhon, at start: False, at end: True, transition type: ProgressToNextLocation)
[08/27/2023 14:27:08] Could not find a spawn point for a SpawnAction (spawn location: BeaconStation (tag: beacon_bandit), skipping.
[08/27/2023 14:26:57] Generating an outpost for the start of the level... (Location: Autonoe Linea Research Center, level type: LocationConnection)
[08/27/2023 14:26:56] Generating an outpost for the end of the level... (Location: Sidon Flexus Institute of Astrobiology, level type: LocationConnection)
[08/27/2023 14:26:56] Level identifier: ridgebasic
[08/27/2023 14:26:37] Transitioning to Autonoe Linea113Sidon Flexus130 (current location: Sidon Flexus Institute of Astrobiology, selected location: Autonoe Linea Research Center, leaving sub: Typhon, at start: True, at end: False, transition type: LeaveLocation)
[08/27/2023 14:26:14] Unlocked mission "Mining minerals" in the connection from "Sidon Flexus Institute of Astrobiology" to "Couwola Mining Facility".
[08/27/2023 14:26:11] Unlocked mission "Arms Delivery" in the connection from "Sidon Flexus Institute of Astrobiology" to "Couwola Mining Facility".
[08/27/2023 14:26:07] Unlocked mission "Crawler Mother" in the connection from "Sidon Flexus Institute of Astrobiology" to "Couwola Mining Facility".
[08/27/2023 14:26:04] Unlocked mission "Mining Thorianite" in the connection from "Sidon Flexus Institute of Astrobiology" to "Couwola Mining Facility".
[08/27/2023 14:19:13] Unlocked mission "Civilian Transport" in the connection from "Sidon Flexus Institute of Astrobiology" to "Autonoe Linea Research Center".
[08/27/2023 14:14:40] Generating an outpost for the start of the level... (Location: Sidon Flexus Institute of Astrobiology, level type: Outpost)
[08/27/2023 14:14:40] Level identifier: ridgeoutpost
[08/27/2023 14:14:22] Transitioning to Sidon Flexus130 (current location: Autonoe Linea Research Center, selected location: Sidon Flexus Institute of Astrobiology, leaving sub: Typhon, at start: False, at end: True, transition type: ProgressToNextLocation)
[08/27/2023 14:06:03] Could not find a spawn point for a SpawnAction (spawn location: BeaconStation (tag: beacon_bandit), skipping.
[08/27/2023 14:05:54] Generating an outpost for the end of the level... (Location: Sidon Flexus Institute of Astrobiology, level type: LocationConnection)
[08/27/2023 14:05:54] Generating an outpost for the start of the level... (Location: Autonoe Linea Research Center, level type: LocationConnection)
[08/27/2023 14:05:53] Level identifier: ridgebasic
[08/27/2023 13:49:39] Could not find a spawn point for a SpawnAction (spawn location: BeaconStation (tag: beacon_bandit), skipping.
[08/27/2023 13:49:27] Generating an outpost for the end of the level... (Location: Sidon Flexus Institute of Astrobiology, level type: LocationConnection)
[08/27/2023 13:49:26] Generating an outpost for the start of the level... (Location: Autonoe Linea Research Center, level type: LocationConnection)
[08/27/2023 13:49:26] Level identifier: ridgebasic
[08/27/2023 13:49:09] Transitioning to Autonoe Linea113Sidon Flexus130 (current location: Autonoe Linea Research Center, selected location: Sidon Flexus Institute of Astrobiology, leaving sub: Typhon, at start: True, at end: False, transition type: LeaveLocation)
[08/27/2023 13:42:36] Generating an outpost for the start of the level... (Location: Autonoe Linea Research Center, level type: Outpost)
[08/27/2023 13:42:36] Level identifier: ridgeoutpost
[08/27/2023 13:41:23] WARNING: Beard index out of range (character: IslandWind, index: 1)
[08/27/2023 13:41:22] Enabling "Dont Open Debug Console On Errors" (TempMods_Download\Workshop_Dont Open Debug Console On Errors_2807566753)
[08/27/2023 13:40:57] WARNING: Tried to restore enabled packages multiple times/without performing a backup
```

**Comment by itchyOwl** [comment]
Addressed in Regalis11/Barotrauma-development@be6243b.

**Comment by itchyOwl** [comment]
Seems to be a race condition. The AI code shouldn't be run in parallel in the first place, so the question is: is there something fishy in how the `GameMain.GameSession.StartRound()` is called inside an async task in `SelectSummaryScreen()`. To me that doesn't seem safe, but if it's just some edge case where this crash happens, it might not require further action.

**Comment by Daniel-Chin** [comment]
> Seems to be a race condition. The AI code shouldn't be run in parallel in the first place, so the question is: is there something fishy in how the `GameMain.GameSession.StartRound()` is called inside an async task in `SelectSummaryScreen()`. To me that doesn't seem safe, but if it's just some edge case where this crash happens, it might not require further action.

Maybe I should mention: My save was intact and no game progress was lost.

**Comment by Regalis11** [comment]
> is there something fishy in how the GameMain.GameSession.StartRound() is called inside an async task in SelectSummaryScreen()

The intention of doing that is to prevent freezing the loading screen (and the RoundSummary UI that's visible during the level transitions). Nothing else but the loading screen logic should be running at the same time as the `StartRound` method - there should be no AI code or any other in-game logic running in parallel. But it seems in this case something went wrong and there was something else running; maybe some error the client received from the server or a disconnect caused the client to interrupt the partially-started round ungracefully?
