### ISSUE TITLE
Closing Barotrauma during the intro videos causes crashes

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#12564]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Accidentally launched Barotrauma on Steam and when I went to close it, I noticed that a crash report popped up, tried it couple more times and there seems to be two different crashes that happens by doing this, could be more depending what the game is loading at the time. 

I haven't seen this happening previously but not sure why it is happening now. 

### Reproduction steps

1. Launch Unstable on Steam
2. During Undertow Games intro video close the game
3. Notice that a crash report message prompts up

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens outside single player or multiplayer game modes (e.g. game launches on startup, something broken in the main menu)

### Version

Unstable (v1.1.9.0)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
CRASH 1
===================================================

Barotrauma Client crash report (generated on 08/26/2023 14:00:42)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

To prevent further startup errors, installed mods will be disabled the next time you launch the game.

71C51AD0C8CDC1A792A4E469716EC6A6

Game version 1.1.9.0 (UnstableWindows, branch release/very-unstable-1.1, revision f6e331f34e)
Graphics mode: 2560x1440 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla (BF54ACE)
Level seed: no level loaded
Loaded submarine: None
Selected screen: None

System info:
    Operating system: Microsoft Windows NT 10.0.22621.0 64 bit
    Graphics device not set

Exception: Failed to set listener position: Invalid operation (System.Exception)
Target site: Void set_ListenerPosition(Microsoft.Xna.Framework.Vector3)
Stack trace: 
   at Barotrauma.Sounds.SoundManager.set_ListenerPosition(Vector3 value) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Sounds\SoundManager.cs:line 56
   at Barotrauma.Camera.UpdateTransform(Boolean interpolate, Boolean updateListener) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Camera.cs:line 235
   at Barotrauma.Camera..ctor() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Camera.cs:line 155
   at Barotrauma.GameScreen..ctor(GraphicsDevice graphics) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\GameScreen.cs:line 32
   at Barotrauma.GameMain.Load() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 499
   at System.Threading.Thread.StartCallback()

Last debug messages:
[08/26/2023 14:00:42] WARNING: Error in GameAnalyticsManager.GetConsent: Could not get a Steam authentication ticket (not connected to Steam).
[08/26/2023 14:00:38] Exiting...
[08/26/2023 14:00:32] Attempting to open ALC device "OpenAL Soft on Beyerdynamic dt 990 pro (2- Realtek USB Audio)"

CRASH 2
===================================================

Barotrauma Client crash report (generated on 08/26/2023 14:00:04)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

To prevent further startup errors, installed mods will be disabled the next time you launch the game.

71C51AD0C8CDC1A792A4E469716EC6A6

Game version 1.1.9.0 (UnstableWindows, branch release/very-unstable-1.1, revision f6e331f34e)
Graphics mode: 2560x1440 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla (BF54ACE)
Level seed: no level loaded
Loaded submarine: None
Selected screen: None

System info:
    Operating system: Microsoft Windows NT 10.0.22621.0 64 bit
    Graphics device not set

Exception: Error while loading the core content package "Vanilla": Loading the preview image of the submarine "Azimuth" failed. The file may be corrupted. {PreviewImage texture returned null}
   at Barotrauma.SubmarineInfo.InitProjectSpecific() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Map\SubmarineInfo.cs:line 22 (System.Exception)
Target site: Void Load()
Stack trace: 
   at Barotrauma.GameMain.Load() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 472
   at System.Threading.Thread.StartCallback()

Last debug messages:
[08/26/2023 14:00:04] Loading the preview image of the submarine "Azimuth" failed. The file may be corrupted. {PreviewImage texture returned null}
   at Barotrauma.SubmarineInfo.InitProjectSpecific() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Map\SubmarineInfo.cs:line 22
[08/26/2023 14:00:04] Exiting...
[08/26/2023 14:00:01] Attempting to open ALC device "OpenAL Soft on Beyerdynamic dt 990 pro (2- Realtek USB Audio)"
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3fea80942e30f9c99d87de9fc8e8b85ec9aaf946

**Comment by Jasontti** [comment]
Tested in: https://github.com/Regalis11/Barotrauma-development/pull/4436/commits/ad8a00975de30dcd281146ac3b1684e0272bc421

Was able to get crash report similar to Crash 1 in original ticket.
Happened when closing the window in very late stage of startup.

```
Barotrauma Client crash report (generated on 01/12/2024 11:28:56)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

To prevent further startup errors, installed mods will be disabled the next time you launch the game.

EECCFBD8FAFBD47C3E982D7F743A1F8A

Game version 1.2.10.0 (ReleaseWindows, branch very-unstable-unstable-dec23, revision 91fa3a622b)
Graphics mode: 1600x900 (Windowed)
VSync ON
Language: English
Selected content packages: Vanilla (1B6D8C6)
Level seed: no level loaded
Loaded submarine: None
Selected screen: None

System info:
    Operating system: Microsoft Windows NT 10.0.19045.0 64 bit
    Graphics device not set

Exception: Failed to set listener position: Invalid operation (System.Exception)
Target site: Void set_ListenerPosition(Microsoft.Xna.Framework.Vector3)
Stack trace: 
   at Barotrauma.Sounds.SoundManager.set_ListenerPosition(Vector3 value) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Sounds\SoundManager.cs:line 56
   at Barotrauma.Camera.UpdateTransform(Boolean interpolate, Boolean updateListener) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Camera.cs:line 230
   at Barotrauma.Camera..ctor() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Camera.cs:line 151
   at Barotrauma.TestScreen..ctor() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\TestScreen.cs:line 27
   at Barotrauma.GameMain.Load() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 540
   at System.Threading.Thread.StartCallback()

Last debug messages:
[01/12/2024 11:28:56] Exiting...
[01/12/2024 11:28:37] Attempting to open ALC device "OpenAL Soft on Kaiuttimet (High Definition Audio Device)"
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/16fe07d3623eb7849d806785724804310b1b58db
