### ISSUE TITLE
NullReferenceException in UpdateAutoPilot

### ISSUE THREAD

**Issue by rasmus-bjerreskov** [Regalis11/Barotrauma#12584]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Crash to desktop for all players.

### Reproduction steps

We're not sure what triggered it, but looking at the stack trace, it might be relevant that one player who had died during the round had just returned with the respawn shuttle. The main submarine was also in autopilot mode. One player (the host) was swimming some distance from the main sub when the crash happened.

### Bug prevalence

Just once

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

Unstable (v1.1.10.0)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 08/29/2023 21:14:51)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

D5DA12B5A13913EE65B3D3F7A25D8F57

Game version 1.1.10.0 (UnstableWindows, branch release/very-unstable-1.1, revision ee42d0064c)
Graphics mode: 2560x1440 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla (D1F63D5), Typhon_B (50CB6AE)
Level seed: GangpoSt. Musk
Loaded submarine: Typhon_B (D35E1A25416BB3AB7B0AF1F4F4BA9A89)
Selected screen: Barotrauma.GameScreen
SteamManager initialized
Client (Round had started)

System info:
    Operating system: Microsoft Windows NT 10.0.19045.0 64 bit
    GPU name: AMD Radeon RX 5700 XT
    Display mode: {Width:2560 Height:1440 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void UpdateAutoPilot(Single)
Stack trace: 
   at Barotrauma.Items.Components.Steering.UpdateAutoPilot(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Machines\Steering.cs:line 511
   at Barotrauma.Items.Components.Steering.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Machines\Steering.cs:line 323
   at Barotrauma.Item.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 2161
   at Barotrauma.MapEntity.UpdateAll(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\MapEntity.cs:line 644
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 247
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 851
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[08/29/2023 21:12:13] Tulpia
[08/29/2023 21:12:13] Ulthius
[08/29/2023 21:12:13] Hurky
[08/29/2023 21:12:13] Rasmus
[08/29/2023 21:06:53] Tulpia
[08/29/2023 21:06:53] Ulthius
[08/29/2023 21:06:53] Rasmus
[08/29/2023 21:00:44] WARNING: Received a potentially invalid ENTITY_POSITION message.Entity identifier does not match (server entity is toothspike, client entity is chaingunboltphysicorium). Ignoring the message...
[08/29/2023 21:00:34] WARNING: Received a potentially invalid ENTITY_POSITION message.Entity identifier does not match (server entity is tonguetendon, client entity is chaingunboltphysicorium). Ignoring the message...
[08/29/2023 20:43:30] Tulpia
[08/29/2023 20:43:30] Ulthius
[08/29/2023 20:43:30] Hurky
[08/29/2023 20:43:30] Rasmus
[08/29/2023 20:43:22] Tulpia
[08/29/2023 20:43:22] Ulthius
[08/29/2023 20:43:22] Hurky
[08/29/2023 20:43:22] Rasmus
[08/29/2023 20:43:19] Tulpia
[08/29/2023 20:43:19] Ulthius
[08/29/2023 20:43:19] Hurky
[08/29/2023 20:43:19] Rasmus
[08/29/2023 20:43:18] Received STARTGAMEFINALIZE packet. Round init status: Started
```

**Comment by Regalis11** [comment]
Thank you for the report! Fixed in https://github.com/Regalis11/Barotrauma-development/commit/22461ed27d60271e0314963c732b0e6d26c2134d (commit in our private repo)
