### ISSUE TITLE
The game crashes later when trying to complete a mission (CharacterAbilityGivePermanentStat.ApplyEffectSpecific)

### ISSUE THREAD

**Issue by StranDead1** [Regalis11/Barotrauma#12587]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The game starts when the mission starts one minute after the start of the game.
From the new on the submarine: A new crew member. Captain "Paula Riddle" infected with husk from the beginning of the previous mission.
[crashreport (14).log](https://github.com/Regalis11/Barotrauma/files/12471534/crashreport.14.log)
I attach a link to the game save
https://drive.google.com/file/d/1tcDD76L6NgiXDQ6Xysq_aCuUKZ-Yoa9Q/view?usp=sharing
[Сохранение.zip](https://github.com/Regalis11/Barotrauma/files/12471562/default.zip)

### Reproduction steps

1. the beginning of the mission 
2. one minute passes 
3. crash

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

Unstable (v1.1.10.0)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 08/29/2023 23:14:58)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

D5DA12B5A13913EE65B3D3F7A25D8F57

Game version 1.1.10.0 (UnstableWindows, branch release/very-unstable-1.1, revision ee42d0064c)
Graphics mode: 1920x1080 (Fullscreen)
VSync OFF
Language: Russian
Selected content packages: Vanilla (D1F63D5)
Level seed: Amar30
Loaded submarine: Humpback (E814271BE5FFD774DB71459268000A99)
Selected screen: Barotrauma.GameScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19045.0 64 bit
    GPU name: NVIDIA GeForce GTX 1060 3GB
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void ApplyEffectSpecific()
Stack trace: 
   at Barotrauma.Abilities.CharacterAbilityGivePermanentStat.ApplyEffectSpecific() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Talents\Abilities\CharacterAbilityGivePermanentStat.cs:line 69
   at Barotrauma.Abilities.CharacterAbilityGivePermanentStat.ApplyEffect() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Talents\Abilities\CharacterAbilityGivePermanentStat.cs:line 59
   at Barotrauma.Abilities.CharacterAbilityGroupInterval.UpdateAbilityGroup(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Talents\AbilityGroups\CharacterAbilityGroupInterval.cs:line 56
   at Barotrauma.CharacterTalent.UpdateTalent(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Talents\CharacterTalent.cs:line 70
   at Barotrauma.Character.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 3140
   at Barotrauma.AICharacter.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AICharacter.cs:line 76
   at Barotrauma.Character.UpdateAll(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 3075
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 185
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 851
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[08/29/2023 23:13:49] Generating an outpost for the start of the level... (Location: Аванпост Amar, level type: Outpost)
[08/29/2023 23:13:49] Level identifier: outpostlevel
[08/29/2023 23:11:10] Generating an outpost for the start of the level... (Location: Жилой аванпост Pelorus Linea, level type: LocationConnection)
[08/29/2023 23:11:09] Generating an outpost for the end of the level... (Location: Аванпост Dyfed, level type: LocationConnection)
[08/29/2023 23:11:09] Level identifier: coldcavernsbasic
[08/29/2023 23:10:58] Transitioning to Dyfed64Pelorus Linea55 (current location: Жилой аванпост Pelorus Linea, selected location: Аванпост Dyfed, leaving sub: Camel, at start: True, at end: False, transition type: LeaveLocation)
[08/29/2023 23:10:31] Unlocked mission "Добыча минералов (Кварц)" in the connection from "Жилой аванпост Pelorus Linea" to "Аванпост Dyfed".
[08/29/2023 23:10:29] Unlocked mission "Убийство большого ползуна" in the connection from "Жилой аванпост Pelorus Linea" to "Аванпост Dyfed".
[08/29/2023 23:10:27] Unlocked mission "Доставка медицинских материалов" in the connection from "Жилой аванпост Pelorus Linea" to "Аванпост Dyfed".
[08/29/2023 23:09:57] Generating an outpost for the start of the level... (Location: Жилой аванпост Pelorus Linea, level type: Outpost)
[08/29/2023 23:09:56] Level identifier: outpostlevel
[08/29/2023 23:09:25] Attempting to open ALC device "OpenAL Soft on Динамики (High Definition Audio Device)"
[08/29/2023 23:09:22] Logged in as StranDead (SteamID STEAM_1:1:453609364)
```

**Comment by Regalis11** [comment]
Thank you for the report! Addressed in https://github.com/Regalis11/Barotrauma-development/pull/4411/commits/97eea771c0afb661452c51fed6ffd62b5ec8a4e8 (commit in our private repo)

**Comment by Jasontti** [comment]
Tested.
No issues found.
Closing ticket.
