### ISSUE TITLE
Crash when changing window mode with russian language (ArgumentOutOfRangeException in ScalableFont.DrawString)

### ISSUE THREAD

**Issue by Jasontti** [Regalis11/Barotrauma#12594]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Game crashed when going from windowed to fullscreen (or vice versa) with russian language

1. Quickstart (SP and MP crashes too)
2. Open reactor
3. Switch window mode 

1.0.21.0 and latest traitor-update build

### Reproduction steps

1. Change language to russian
2. Quickstart (SP and MP crashes too)
3. Open reactor
4. Switch window mode 

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

Other

1.1.2.0

### Which operating system did you encounter this bug on?

Windows and linux

### Relevant error messages and crash reports

```
Exception: Specified argument was out of the range of valid values. (Parameter 'Error while rendering text. Texture index was out of range. Text: Возможно, вам не хватает знаний, чтобы использовать этот предмет! Для этого необходим навык "электрика" не ниже 50 уровня., char: 1042 index: 0, texture count: 0') (System.ArgumentOutOfRangeException)
Target site: Void DrawString(Microsoft.Xna.Framework.Graphics.SpriteBatch, System.String, Microsoft.Xna.Framework.Vector2, Microsoft.Xna.Framework.Color, Single, Microsoft.Xna.Framework.Vector2, Microsoft.Xna.Framework.Vector2, Microsoft.Xna.Framework.Graphics.SpriteEffects, Single, Barotrauma.Alignment, Barotrauma.ForceUpperCase)
Stack trace: 
   at Barotrauma.ScalableFont.DrawString(SpriteBatch sb, String text, Vector2 position, Color color, Single rotation, Vector2 origin, Vector2 scale, SpriteEffects se, Single layerDepth, Alignment alignment, ForceUpperCase forceUpperCase) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Fonts\ScalableFont.cs:line 523
   at Barotrauma.GUI.DrawMessages(SpriteBatch spriteBatch, Camera cam) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1759
   at Barotrauma.GUI.Draw(Camera cam, SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 622
   at Barotrauma.GameScreen.Draw(Double deltaTime, GraphicsDevice graphics, SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\GameScreen.cs:line 159
   at Barotrauma.GameMain.Draw(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 990
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 669
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 508
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58
```

Another crash when being near reactor and changing window mode.
```
Unhandled exception. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'Error while rendering text. Texture index was out of range. Text: Пункт назначения: Добывающий центр Yelland Linea, char: 1055 index: 0, texture count: 0')
   at Barotrauma.ScalableFont.DrawString(SpriteBatch sb, String text, Vector2 position, Color color, Single rotation, Vector2 origin, Vector2 scale, SpriteEffects se, Single layerDepth, Alignment alignment, ForceUpperCase forceUpperCase) in /home/joonas/dev/Barotrauma-development/Barotrauma/BarotraumaClient/ClientSource/Fonts/ScalableFont.cs:line 523
   at Barotrauma.ScalableFont.DrawString(SpriteBatch sb, String text, Vector2 position, Color color, Single rotation, Vector2 origin, Single scale, SpriteEffects se, Single layerDepth, Alignment alignment, ForceUpperCase forceUpperCase) in /home/joonas/dev/Barotrauma-development/Barotrauma/BarotraumaClient/ClientSource/Fonts/ScalableFont.cs:line 538
   at Barotrauma.GUI.DrawMessages(SpriteBatch spriteBatch, Camera cam) in /home/joonas/dev/Barotrauma-development/Barotrauma/BarotraumaClient/ClientSource/GUI/GUI.cs:line 1773
   at Barotrauma.GUI.Draw(Camera cam, SpriteBatch spriteBatch) in /home/joonas/dev/Barotrauma-development/Barotrauma/BarotraumaClient/ClientSource/GUI/GUI.cs:line 622
   at Barotrauma.GameScreen.Draw(Double deltaTime, GraphicsDevice graphics, SpriteBatch spriteBatch) in /home/joonas/dev/Barotrauma-development/Barotrauma/BarotraumaClient/ClientSource/Screens/GameScreen.cs:line 159
   at Barotrauma.GameMain.Draw(GameTime gameTime) in /home/joonas/dev/Barotrauma-development/Barotrauma/BarotraumaClient/ClientSource/GameMain.cs:line 981
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime) in /home/joonas/dev/Barotrauma-development/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 666
   at Microsoft.Xna.Framework.Game.Tick() in /home/joonas/dev/Barotrauma-development/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 508
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in /home/joonas/dev/Barotrauma-development/Libraries/MonoGame.Framework/Src/MonoGame.Framework/SDL/SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in /home/joonas/dev/Barotrauma-development/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in /home/joonas/dev/Barotrauma-development/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in /home/joonas/dev/Barotrauma-development/Barotrauma/BarotraumaClient/ClientSource/Program.cs:line 58
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/74369d056f139ffcc3331ed53e7a93fa77806095. The reactor or Russian language don't seem to be required for this, this happens whenever you switch the resolution when there's GUIMessages visible on the screen.

**Comment by Rokvach** [comment]
Tested by changing my language to Russian (couldn't repro with just English), selecting a reactor to get the insufficient skills message and then changed resolution, on current Unstable it caused a crash while on the PR it didn't, so working correctly. Can be merged and closed.
