### ISSUE TITLE
Level equality check failed (client value FloatingIce: 2EE6C48E, server value FloatingIce: 175BF234)

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#12618]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Multiplayer save for immediate error repro [equalitycheckfailed_saveinside.zip](https://github.com/Regalis11/Barotrauma/files/12517245/equalitycheckfailed_saveinside.zip)

### Reproduction steps

1. Started a new multiplayer campaign with Typhon 2
2. Used the following commands
![image](https://github.com/Regalis11/Barotrauma/assets/7299826/c566b146-0d79-45c2-a0e0-5b6518d554cf)
3. Teleported to Great Sea (I teleported to the last outpost in that biome)
4. Received the error and was disconnected from server right when the round loaded

Recommend trying multiple different paths in the Great Sea, when I tried to repro this again I had to teleport to 3 different locations until it happened. 

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

Unstable (v1.1.10.0)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Error while reading a message from server. 
Level equality check failed. The level generated at your end doesn't match the level generated by the server (client value FloatingIce: 2EE6C48E, server value FloatingIce: 175BF234, level value count: 17, seed: Borvo Mensa14Undermoist31, sub: Typhon2 (1E6F6E6), mirrored: False). Round init status: WaitingForStartGameFinalize. Round start save ID: 4, last save id: 4, pending save id: 4.
   at Barotrauma.Networking.GameClient.ReadStartGameFinalize(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 942
   at Barotrauma.Networking.GameClient.ReadDataMessage(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 747
   at Barotrauma.Networking.SteamP2POwnerPeer.HandleMessageForOwner(PeerPacketHeaders peerPacketHeaders, IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\Primitives\Peers\SteamP2POwnerPeer.cs:line 368
   at Barotrauma.Networking.SteamP2POwnerPeer.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\Primitives\Peers\SteamP2POwnerPeer.cs:line 242
   at Barotrauma.Networking.GameClient.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 504
```

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
