### ISSUE TITLE
Detaching a circuit box containing components and transitioning to the next level causes a crash (Failed to find item with ID)

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#12632]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![image](https://github.com/Regalis11/Barotrauma/assets/7299826/cd384727-99ff-4e09-92b1-17fbb8449334)

### Reproduction steps

(My exact steps)
1. Start a singleplayer round
2. Spawn in a circuit box and place it down somewhere in the sub
3. Place two Atan components and wire them up to ther inputs and outputs
5. Undock from outpost
6. Detach circuit box and have it in your inventory
7. Dock back to outpost
8. Game crashes when loading into outpost completes

### Bug prevalence

Just once

### Single player or multiplayer?

Single player

### Version

Other

### -

Circuit box PR

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 09/07/2023 11:27:10)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

5780DF80A9C77F30D785012FE599AAD8

Game version 1.1.2.0 (ReleaseWindows, branch feature/circuit-box-prototype, revision 0a12bccb94)
Graphics mode: 2560x1440 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla (5F45FC7), LIGHT ISSUE (C2D519C), flying room (A2A7F50)
Level seed: Cilicia Flexus17
Loaded submarine: Dugong (7A156E8B6BE69F28AC99F877099032C9)
Selected screen: Barotrauma.GameScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.22621.0 64 bit
    GPU name: NVIDIA GeForce RTX 4080
    Display mode: {Width:2560 Height:1440 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Failed to find item with ID 1012 for CircuitBoxNode with ID 1 (System.Exception)
Target site: Barotrauma.CircuitBoxComponent LoadFromXML(Barotrauma.ContentXElement, Barotrauma.Items.Components.CircuitBox, Barotrauma.IdRemap)
Stack trace: 
   at Barotrauma.CircuitBoxComponent.LoadFromXML(ContentXElement element, CircuitBox circuitBox, IdRemap idRemap) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CircuitBox\CircuitBoxComponent.cs:line 48
   at Barotrauma.Items.Components.CircuitBox.TryInitializeNodes() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Signal\CircuitBox.cs:line 203
   at Barotrauma.Item.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 2190
   at Barotrauma.MapEntity.UpdateAll(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\MapEntity.cs:line 644
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 247
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 851
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 651
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[09/07/2023 11:27:06] Generating an outpost for the start of the level... (Location: Cilicia Flexus Habitation Outpost, level type: Outpost)
[09/07/2023 11:27:06] Level identifier: outpostlevel
[09/07/2023 11:26:59] Transitioning to Cilicia Flexus17 (current location: Cilicia Flexus Habitation Outpost, selected location: Binnsmouth Outpost, leaving sub: Dugong, at start: True, at end: False, transition type: ReturnToPreviousLocation)
[09/07/2023 11:26:04] fixitems
[09/07/2023 11:26:03] teleport "Jared Castillo"
[09/07/2023 11:25:59] Lighting disabled
[09/07/2023 11:25:59] lighting
[09/07/2023 11:25:58] Line of sight effect disabled
[09/07/2023 11:25:58] los
[09/07/2023 11:25:54] spawnitem Wrench inventory
[09/07/2023 11:25:51] spawnitem Screwdriver inventory
[09/07/2023 11:14:38] spawnitem "Storage Container" inventory
[09/07/2023 11:13:41] spawnitem "Atan Component" inventory
[09/07/2023 11:13:35] spawnitem Toolbelt inventory
[09/07/2023 11:13:09] Generating an outpost for the end of the level... (Location: Binnsmouth Outpost, level type: LocationConnection)
[09/07/2023 11:13:09] Generating an outpost for the start of the level... (Location: Cilicia Flexus Habitation Outpost, level type: LocationConnection)
[09/07/2023 11:13:09] Level identifier: coldcavernsbasic
[09/07/2023 11:12:40] Generating an outpost for the end of the level... (Location: Binnsmouth Outpost, level type: LocationConnection)
[09/07/2023 11:12:40] Generating an outpost for the start of the level... (Location: Cilicia Flexus Habitation Outpost, level type: LocationConnection)
[09/07/2023 11:12:40] Level identifier: coldcavernsbasic
[09/07/2023 11:12:32] Transitioning to Cilicia Flexus17Binnsmouth19 (current location: Cilicia Flexus Habitation Outpost, selected location: Binnsmouth Outpost, leaving sub: Dugong, at start: True, at end: False, transition type: LeaveLocation)
[09/07/2023 11:10:23] spawnitem "Atan Component" inventory
[09/07/2023 11:10:14] spawnitem "Atan Component" inventory
[09/07/2023 11:09:58] spawnitem "Circuit Box" inventory
[09/07/2023 11:09:55] Steam achievements have been disabled during this play session.
[09/07/2023 11:09:55] Enabled cheat commands.
[09/07/2023 11:09:55] enablecheats
[09/07/2023 11:09:53] Enabling cheats will disable Steam achievements during this play session.
[09/07/2023 11:09:53] You need to enable cheats using the command "enablecheats" before you can use the command "spawnitem".
[09/07/2023 11:09:53] spawnitem "Circuit Box" cursor
[09/07/2023 11:09:27] Generating an outpost for the start of the level... (Location: Cilicia Flexus Habitation Outpost, level type: Outpost)
[09/07/2023 11:09:27] Level identifier: outpostlevel
[09/07/2023 11:08:26] spawnitem "Atan Component" inventory
[09/07/2023 11:05:39] Attempting to open ALC device "OpenAL Soft on Beyerdynamic dt 990 pro (2- Realtek USB Audio)"
```

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c8806ba367b4a63a73ae605dd97dac291f527217

This is a breaking change and older saves with circuit boxes will break so needs to be tested on new saves

**Comment by Rokvach** [comment]
I have already tested this and noted about a new issue about components not being rendered
[Preliminary circuit box](https://github.com/Regalis11/Barotrauma-development/issues/4343)

**Comment by Rokvach** [comment]
The above issue has already been tested and fixed and gone through review as well, don't see the need to keep this ticket open any further. Closing.
