### ISSUE TITLE
Error while connecting to the game with custom Ukrainian localization mod

### ISSUE THREAD

**Issue by kastian-gh** [Regalis11/Barotrauma#12685]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Using localization mod (Ukrainian) when connecting to game it's throwing back to the main menu with this error:

```
Coroutine Barotrauma.Networking.GameClient+<StartGame>d__112 threw an exception: The given key 'Ukrainian' was not present in the dictionary.
   at System.Collections.Concurrent.ConcurrentDictionary`2.ThrowKeyNotFoundException(TKey key)
   at System.Collections.Concurrent.ConcurrentDictionary`2.get_Item(TKey key)
   at Barotrauma.TextManager.GetAll(Identifier tag) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Text/TextManager.cs:line 168
   at Barotrauma.TextManager.GetAll(String tag) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Text/TextManager.cs:line 164
   at Barotrauma.LocationType.get_NameFormats() in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Map/Map/LocationType.cs:line 60
   at Barotrauma.Location.RandomName(LocationType type, Random rand, IEnumerable`1 existingLocations) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Map/Map/Location.cs:line 1087
   at Barotrauma.Location..ctor(Vector2 mapPosition, Nullable`1 zone, Random rand, Boolean requireOutpost, LocationType forceLocationType, IEnumerable`1 existingLocations) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Map/Map/Location.cs:line 543
   at Barotrauma.GameSession.CreateDummyLocations(Random rand, LocationType forceLocationType) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/GameSession/GameSession.cs:line 295
   at Barotrauma.GameSession.get_StartLocation() in <DEV>/Barotrauma/BarotraumaShared/SharedSource/GameSession/GameSession.cs:line 78
   at Barotrauma.MissionMode..ctor(GameModePreset preset, IEnumerable`1 missionPrefabs) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/GameSession/GameModes/MissionMode.cs:line 21
   at Barotrauma.GameSession.InstantiateGameMode(GameModePreset gameModePreset, String seed, SubmarineInfo selectedSub, CampaignSettings settings, IEnumerable`1 missionPrefabs, MissionType missionType) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/GameSession/GameSession.cs:line 208
   at Barotrauma.Networking.GameClient.StartGame(IReadMessage inc)+MoveNext() in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Networking/GameClient.cs:line 1464
   at Barotrauma.CoroutineManager.PerformCoroutineStep(CoroutineHandle handle) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/CoroutineManager.cs:line 199
   at Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/CoroutineManager.cs:line 257
```

### Reproduction steps

1. Install localization mod https://steamcommunity.com/sharedfiles/filedetails/?id=2828450028
2. Enable Ukrainian language in settings
3. Enter any multiplayer vanilla campaign

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Coroutine Barotrauma.Networking.GameClient+<StartGame>d__112 threw an exception: The given key 'Ukrainian' was not present in the dictionary.
   at System.Collections.Concurrent.ConcurrentDictionary`2.ThrowKeyNotFoundException(TKey key)
   at System.Collections.Concurrent.ConcurrentDictionary`2.get_Item(TKey key)
   at Barotrauma.TextManager.GetAll(Identifier tag) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Text/TextManager.cs:line 168
   at Barotrauma.TextManager.GetAll(String tag) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Text/TextManager.cs:line 164
   at Barotrauma.LocationType.get_NameFormats() in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Map/Map/LocationType.cs:line 60
   at Barotrauma.Location.RandomName(LocationType type, Random rand, IEnumerable`1 existingLocations) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Map/Map/Location.cs:line 1087
   at Barotrauma.Location..ctor(Vector2 mapPosition, Nullable`1 zone, Random rand, Boolean requireOutpost, LocationType forceLocationType, IEnumerable`1 existingLocations) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Map/Map/Location.cs:line 543
   at Barotrauma.GameSession.CreateDummyLocations(Random rand, LocationType forceLocationType) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/GameSession/GameSession.cs:line 295
   at Barotrauma.GameSession.get_StartLocation() in <DEV>/Barotrauma/BarotraumaShared/SharedSource/GameSession/GameSession.cs:line 78
   at Barotrauma.MissionMode..ctor(GameModePreset preset, IEnumerable`1 missionPrefabs) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/GameSession/GameModes/MissionMode.cs:line 21
   at Barotrauma.GameSession.InstantiateGameMode(GameModePreset gameModePreset, String seed, SubmarineInfo selectedSub, CampaignSettings settings, IEnumerable`1 missionPrefabs, MissionType missionType) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/GameSession/GameSession.cs:line 208
   at Barotrauma.Networking.GameClient.StartGame(IReadMessage inc)+MoveNext() in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Networking/GameClient.cs:line 1464
   at Barotrauma.CoroutineManager.PerformCoroutineStep(CoroutineHandle handle) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/CoroutineManager.cs:line 199
   at Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/CoroutineManager.cs:line 257
```

**Comment by Regalis11** [comment]
Thank you for the report! I unfortunately couldn't find a way to reproduce the issue. I'm getting no crashes when joining a server with that mod enabled. Could be that I'm doing something differently than you though - to be clear, does this happen in the campaign mode or the mission mode? The error message seems to imply it was mission mode, but the report says it was the campaign. Thanks and sorry for the inconvenience!

**Comment by Regalis11** [comment]
Thanks for the extra info, I got it to happen at my end now too. The problem earlier was that I also had the mod installed server-side.

Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/59a63e45198b1493f8fbdb8c078c0839f74989e5 and https://github.com/Regalis11/Barotrauma-development/commit/94fbed3e5ef0af8544136e81541f91c81ccab333 (commits in our private repo)

**Comment by Jasontti** [comment]
Tested in: https://github.com/Regalis11/Barotrauma-development/pull/4480/commits/7ff110df94047882fd273572acb423c28fd90e3c

Hosted a server on second account that had no mods installed.
Connected with language mod provided and could connect.
Tested couple rounds

No issues found
Closing ticket
