### ISSUE TITLE
Operate Weapon marker is unhelpfully placed on the ship turret

### ISSUE THREAD

**Issue by WJohn** [Regalis11/Barotrauma#12723]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

**Description:**
When ordering a crewmember to operate one of the ship's turrets, the marker for it will be placed on the actual gun itself somewhere on the outside the hull, with an arrow leading outside the ship, rather than the Periscope the User needs to be navigating to. This is especially problematic for new players, or on submarines with unintuitive Periscope-to-Gun layouts.

**Expected:**
Operate Weapon marker is placed on the corresponding Periscope, possibly determined by the position_out or trigger_out wire. Multiple markers could be placed in cases of several Periscopes controlling the same gun.

**Notes:**
Issue occurs on both v1.0.21.0 and v1.1.14.0

![operate_weapons](https://github.com/Regalis11/Barotrauma/assets/5988156/dc52c65f-651c-4f3e-924c-be9c07b9d6ac)

### Reproduction steps

1. Launch the game
2. Enter the Submarine Editor
3. Run Test on any Submarine
4. Assign an "Operate Weapon" order to any of the crewmembers
5. Observe the Operate Weapon marker placement as that crewmember

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Single player

### Version

Unstable (v1.1.14.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/529ef237fe90d2a096a2dd4d83acd95805223df6

**Comment by Jasontti** [comment]
Tested in: https://github.com/Regalis11/Barotrauma-development/pull/4510/commits/b873d70553cc05e59c9a530f187089ba9e907972

Tested in listen server.
Commanded player character or NPC to use turret.
Marker is in correct position, but got error:

```
AI: Created an Order operateweapons that's set to use a Controller, but a Controller was not specified.
   at System.Environment.get_StackTrace()
   at Barotrauma.Order..ctor(Order other, OrderPrefab prefab, Identifier option, Nullable`1 manualPriority, Nullable`1 type, AIObjective objective, Entity targetEntity, ItemComponent targetItemComponent, Controller connectedController, Character orderGiver, OrderTarget targetPosition, Nullable`1 targetType, Nullable`1 wallSectionIndex, Nullable`1 useController) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/AI/Order.cs:line 671
   at Barotrauma.Order.WithManualPriority(Int32 newPriority) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/AI/Order.cs:line 683
   at Barotrauma.Networking.ChatMessage.ClientRead(IReadMessage msg) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Networking/ChatMessage.cs:line 131
   at Barotrauma.Networking.GameClient.<>c__DisplayClass119_0.<ReadIngameUpdate>b__0(ServerNetSegment segment, IReadMessage inc) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Networking/GameClient.cs:line 2146
   at Barotrauma.Networking.SegmentTableReader`1.Read(IReadMessage msg, SegmentDataReader segmentDataReader, ExceptionHandler exceptionHandler) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Utils/SegmentTable.cs:line 296
   at Barotrauma.Networking.GameClient.ReadIngameUpdate(IReadMessage inc) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Networking/GameClient.cs:line 2076
   at Barotrauma.Networking.GameClient.ReadDataMessage(IReadMessage inc) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Networking/GameClient.cs:line 649
   at Barotrauma.Networking.LidgrenClientPeer.HandleDataMessage(NetIncomingMessage lidgrenMsg) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Networking/Primitives/Peers/LidgrenClientPeer.cs:line 162
   at Barotrauma.Networking.LidgrenClientPeer.Update(Single deltaTime) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Networking/Primitives/Peers/LidgrenClientPeer.cs:line 124
   at Barotrauma.Networking.GameClient.Update(Single deltaTime) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Networking/GameClient.cs:line 505
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/GameMain.cs:line 878
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 651
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/SDL/SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Program.cs:line 58
```

**Comment by Jasontti** [comment]
Tested again in: https://github.com/Regalis11/Barotrauma-development/pull/4510/commits/27ba893d2569e207bcb927e7351f7dab035b30fc

No issues found
Closing ticket
