### ISSUE TITLE
Error when accessing tab menu in sub editor (Failed to display mission info in the tab menu (no level loaded))

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#12725]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

-

### Reproduction steps

1. Start singleplayer
2. Open Tab menu and leave it on the mission tab
3. Return to main menu and navigate to sub editor test mode
4. Press Tab
5. Get error

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Other

### -

Sub editor test mode

### Version

Unstable (v1.1.14.0)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Failed to display mission info in the tab menu (no level loaded).
   at System.Environment.get_StackTrace()
   at Barotrauma.TabMenu.CreateMissionInfo(GUIFrame infoFrame) in E:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GUI\TabMenu.cs:line 1476
   at Barotrauma.TabMenu.SelectInfoFrameTab(InfoFrameTab selectedTab) in E:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GUI\TabMenu.cs:line 378
   at Barotrauma.TabMenu..ctor() in E:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GUI\TabMenu.cs:line 169
   at Barotrauma.GameSession.ToggleTabMenu() in E:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GameSession\GameSession.cs:line 29
   at Barotrauma.GameSession.<CreateTopLeftButtons>b__20_3(GUIButton button, Object userData) in E:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GameSession\GameSession.cs:line 95
   at Barotrauma.GUIButton.Update(Single deltaTime) in E:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIButton.cs:line 263
   at Barotrauma.GUI.Update(Single deltaTime) in E:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1244
   at Barotrauma.GameMain.Update(GameTime gameTime) in E:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 876
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 651
   at Microsoft.Xna.Framework.Game.Tick() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in E:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/84de2c043cb1d27a40001838c28c9e896fb86fab

**Comment by Jasontti** [comment]
Tested in: https://github.com/Regalis11/Barotrauma-development/pull/4510/commits/b873d70553cc05e59c9a530f187089ba9e907972

Testede stepd above
Tab menu function in SP and MP

No issues found
Closing ticket
