### ISSUE TITLE
CTD with mod that modifies hull upgrades

### ISSUE THREAD

**Issue by Zantza** [Regalis11/Barotrauma#12730]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

When browsing submarine upgrades with the Chief Mechanic in the campaign, the game crashes to desktop with a mod that modifies the hull upgrades. The mod in question: https://steamcommunity.com/sharedfiles/filedetails/?id=2957927863

Not sure if this is the mod's fault or a bug with the game, but I thought I should make a ticket just in case. I tested only with the listen server. 

I reported the issue to the mod's developer as well.

### Reproduction steps

1. Start a listen server
2. Start a campaign
3. Go visit the nearest Chief Mechanic
4. CTD when scrolling down the upgrade menu

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 09/29/2023 13:25:53)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

9F5E3061E92D485CB02263313B29506B

Game version 1.0.21.0 (ReleaseWindows, branch release/summer-patch-hotfix, revision adb80ccd6e)
Graphics mode: 3840x2160 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla (65E9331), Extended Crush Depth (B8D87B4)
Level seed: Corick Linea119
Loaded submarine: Camel (644A95274125751B591BA4E81D029E08)
Selected screen: Barotrauma.GameScreen
SteamManager initialized
Client (Round had started)

System info:
    Operating system: Microsoft Windows NT 10.0.19045.0 64 bit
    GPU name: NVIDIA GeForce RTX 3070 Ti
    Display mode: {Width:3840 Height:2160 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Int32 GetBuyPrice(Int32, Barotrauma.Location, System.Collections.Immutable.ImmutableHashSet`1[Barotrauma.Character])
Stack trace: 
   at Barotrauma.UpgradePrice.GetBuyPrice(Int32 level, Location location, ImmutableHashSet`1 characterList) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Upgrades\UpgradePrefab.cs:line 50
   at Barotrauma.UpgradeStore.CreateUpgradeFrame(UpgradePrefab prefab, UpgradeCategory category, CampaignMode campaign, RectTransform rectTransform, Boolean addBuyButton) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\UpgradeStore.cs:line 1113
   at Barotrauma.UpgradeStore.CreateUpgradeEntry(UpgradePrefab prefab, UpgradeCategory category, GUIComponent parent, Submarine submarine, List`1 itemsOnSubmarine) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\UpgradeStore.cs:line 1252
   at Barotrauma.UpgradeStore.CreateUpgradePrefabList(GUIListBox parent, UpgradeCategory category, List`1 prefabs, Submarine submarine) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\UpgradeStore.cs:line 868
   at Barotrauma.UpgradeStore.SelectUpgradeCategory(List`1 prefabs, UpgradeCategory category, Submarine submarine) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\UpgradeStore.cs:line 856
   at Barotrauma.UpgradeStore.<CreateUpgradeTab>b__46_0(GUIComponent component, Object userData) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\UpgradeStore.cs:line 755
   at Barotrauma.GUIListBox.Select(Int32 childIndex, Force force, AutoScroll autoScroll, TakeKeyBoardFocus takeKeyBoardFocus, PlaySelectSound playSelectSound) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIListBox.cs:line 1068
   at Barotrauma.GUIListBox.SelectNext(Force force, AutoScroll autoScroll, TakeKeyBoardFocus takeKeyBoardFocus, PlaySelectSound playSelectSound) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIListBox.cs:line 1020
   at Barotrauma.GUIListBox.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIListBox.cs:line 990
   at Barotrauma.GUI.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1247
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 909
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[09/29/2023 13:25:10] Server running slowly (58 updates/s)!
[09/29/2023 13:25:07] Zantza
[09/29/2023 13:25:05] Received STARTGAMEFINALIZE packet. Round init status: Started
[09/29/2023 13:25:05] Task count: 0
[09/29/2023 13:25:05] Received STARTGAMEFINALIZE packet. Round init status: WaitingForStartGameFinalize
[09/29/2023 13:25:02] Generating an outpost for the start of the level... (Location: Corick Linea Habitation Outpost, level type: Outpost)
[09/29/2023 13:25:02] Level identifier: outpostlevel
[09/29/2023 13:24:39] Lobby created!
[09/29/2023 13:23:52] Attempting to open ALC device "OpenAL Soft on DELL S3221QS (NVIDIA High Definition Audio)"
[09/29/2023 13:23:50] Logged in as Zantza (SteamID STEAM_1:1:49098363)
```

**Comment by Regalis11** [comment]
Thank you for the report!

It seems the upgrade in this mod has no price defined, which lead to the crash when trying to view it in the upgrade menu. Fixed the crashing in https://github.com/Regalis11/Barotrauma-development/commit/67547412814ca0bd06e3dc9b153d9eb2f6c450ed (commit in our private repo).

**Comment by Jasontti** [comment]
Tested in https://github.com/Regalis11/Barotrauma-development/pull/4508/commits/67547412814ca0bd06e3dc9b153d9eb2f6c450ed

Upgraded sub with and without the mod provided in SP and MP.

No issues found.
Closing ticket.
