### ISSUE TITLE
[UNSTABLE] Swarmfeeders cause immense lag

### ISSUE THREAD

**Issue by PanmanS** [Regalis11/Barotrauma#12740]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Approaching ruins on "Scan Ruins" mission cause immense lag throughout whole level because of swarmfeeders failed to be removed????
![image](https://github.com/Regalis11/Barotrauma/assets/42521948/1e09cac2-28fe-4c30-8a0d-9f5668ed4ee4)
[log.txt](https://github.com/Regalis11/Barotrauma/files/12777049/log.txt)

Mods used and the save file:
![Barotrauma_NSQyhtuGbq](https://github.com/Regalis11/Barotrauma/assets/42521948/7b624d94-83fd-493e-a2cd-e846674a7686)
[Save.zip](https://github.com/Regalis11/Barotrauma/files/12777050/Save.zip)

### Reproduction steps

1. install all mods in order provided on image
2. load up save file on unstable version of game
3. approach ruins close enough (like on screenshot above)
4. observe the issue

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

Unstable (v1.1.14.0)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Coroutine Barotrauma.CoroutineManager+<DoInvokeAfter>d__11 threw an exception: Object reference not set to an instance of an object.
   at Barotrauma.Ragdoll.SetPosition(Vector2 simPosition, Boolean lerp, Boolean ignorePlatforms, Boolean forceMainLimbToCollider, Boolean detachProjectiles) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Animation\Ragdoll.cs:line 1809
   at Barotrauma.MonsterEvent.<>c__DisplayClass35_1.<Update>b__5() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\MonsterEvent.cs:line 634
   at Barotrauma.CoroutineManager.DoInvokeAfter(Action action, Single delay)+MoveNext() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 155
   at Barotrauma.CoroutineManager.PerformCoroutineStep(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 214
   at Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 236
Attempted to access a potentially removed ragdoll. Character: Swarmfeeder, id: 8526, removed: True, ragdoll removed: True
   at System.Environment.get_StackTrace()
   at Barotrauma.Ragdoll.LogAccessedRemovedCharacterError() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Animation\Ragdoll.cs:line 1494
   at Barotrauma.GameScreen.Draw(Double deltaTime, GraphicsDevice graphics, SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\GameScreen.cs:line 104
   at Barotrauma.GameMain.Draw(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 957
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 666
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 508
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58
Coroutine Barotrauma.CoroutineManager+<DoInvokeAfter>d__11 threw an exception: Object reference not set to an instance of an object.
   at Barotrauma.Ragdoll.SetPosition(Vector2 simPosition, Boolean lerp, Boolean ignorePlatforms, Boolean forceMainLimbToCollider, Boolean detachProjectiles) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Animation\Ragdoll.cs:line 1809
   at Barotrauma.MonsterEvent.<>c__DisplayClass35_1.<Update>b__5() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\MonsterEvent.cs:line 634
   at Barotrauma.CoroutineManager.DoInvokeAfter(Action action, Single delay)+MoveNext() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 155
   at Barotrauma.CoroutineManager.PerformCoroutineStep(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 214
   at Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 236
Attempted to access a potentially removed ragdoll. Character: Swarmfeeder, id: 8527, removed: True, ragdoll removed: True
   at System.Environment.get_StackTrace()
   at Barotrauma.Ragdoll.LogAccessedRemovedCharacterError() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Animation\Ragdoll.cs:line 1494
   at Barotrauma.GameScreen.Draw(Double deltaTime, GraphicsDevice graphics, SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\GameScreen.cs:line 104
   at Barotrauma.GameMain.Draw(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 957
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 666
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 508
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58
Coroutine Barotrauma.CoroutineManager+<DoInvokeAfter>d__11 threw an exception: Object reference not set to an instance of an object.
   at Barotrauma.Ragdoll.SetPosition(Vector2 simPosition, Boolean lerp, Boolean ignorePlatforms, Boolean forceMainLimbToCollider, Boolean detachProjectiles) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Animation\Ragdoll.cs:line 1809
   at Barotrauma.MonsterEvent.<>c__DisplayClass35_1.<Update>b__5() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\MonsterEvent.cs:line 634
   at Barotrauma.CoroutineManager.DoInvokeAfter(Action action, Single delay)+MoveNext() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 155
   at Barotrauma.CoroutineManager.PerformCoroutineStep(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 214
   at Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 236
Attempted to access a potentially removed ragdoll. Character: Swarmfeeder, id: 8528, removed: True, ragdoll removed: True
   at System.Environment.get_StackTrace()
   at Barotrauma.Ragdoll.LogAccessedRemovedCharacterError() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Animation\Ragdoll.cs:line 1494
   at Barotrauma.GameScreen.Draw(Double deltaTime, GraphicsDevice graphics, SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\GameScreen.cs:line 104
   at Barotrauma.GameMain.Draw(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 957
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 666
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 508
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58
Coroutine Barotrauma.CoroutineManager+<DoInvokeAfter>d__11 threw an exception: Object reference not set to an instance of an object.
   at Barotrauma.Ragdoll.SetPosition(Vector2 simPosition, Boolean lerp, Boolean ignorePlatforms, Boolean forceMainLimbToCollider, Boolean detachProjectiles) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Animation\Ragdoll.cs:line 1809
   at Barotrauma.MonsterEvent.<>c__DisplayClass35_1.<Update>b__5() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\MonsterEvent.cs:line 634
   at Barotrauma.CoroutineManager.DoInvokeAfter(Action action, Single delay)+MoveNext() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 155
   at Barotrauma.CoroutineManager.PerformCoroutineStep(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 214
   at Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 236
Attempted to access a potentially removed ragdoll. Character: Swarmfeeder, id: 8529, removed: True, ragdoll removed: True
   at System.Environment.get_StackTrace()
   at Barotrauma.Ragdoll.LogAccessedRemovedCharacterError() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Animation\Ragdoll.cs:line 1494
   at Barotrauma.GameScreen.Draw(Double deltaTime, GraphicsDevice graphics, SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\GameScreen.cs:line 104
   at Barotrauma.GameMain.Draw(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 957
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 666
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 508
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58
Coroutine Barotrauma.CoroutineManager+<DoInvokeAfter>d__11 threw an exception: Object reference not set to an instance of an object.
   at Barotrauma.Ragdoll.SetPosition(Vector2 simPosition, Boolean lerp, Boolean ignorePlatforms, Boolean forceMainLimbToCollider, Boolean detachProjectiles) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Animation\Ragdoll.cs:line 1809
   at Barotrauma.MonsterEvent.<>c__DisplayClass35_1.<Update>b__5() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\MonsterEvent.cs:line 634
   at Barotrauma.CoroutineManager.DoInvokeAfter(Action action, Single delay)+MoveNext() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 155
   at Barotrauma.CoroutineManager.PerformCoroutineStep(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 214
   at Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 236
Attempted to access a potentially removed ragdoll. Character: Swarmfeeder, id: 8530, removed: True, ragdoll removed: True
   at System.Environment.get_StackTrace()
   at Barotrauma.Ragdoll.LogAccessedRemovedCharacterError() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Animation\Ragdoll.cs:line 1494
   at Barotrauma.GameScreen.Draw(Double deltaTime, GraphicsDevice graphics, SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\GameScreen.cs:line 104
   at Barotrauma.GameMain.Draw(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 957
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 666
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 508
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58
Coroutine Barotrauma.CoroutineManager+<DoInvokeAfter>d__11 threw an exception: Object reference not set to an instance of an object.
   at Barotrauma.Ragdoll.SetPosition(Vector2 simPosition, Boolean lerp, Boolean ignorePlatforms, Boolean forceMainLimbToCollider, Boolean detachProjectiles) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Animation\Ragdoll.cs:line 1809
   at Barotrauma.MonsterEvent.<>c__DisplayClass35_1.<Update>b__5() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\MonsterEvent.cs:line 634
   at Barotrauma.CoroutineManager.DoInvokeAfter(Action action, Single delay)+MoveNext() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 155
   at Barotrauma.CoroutineManager.PerformCoroutineStep(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 214
   at Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 236
Attempted to access a potentially removed ragdoll. Character: Swarmfeeder, id: 8531, removed: True, ragdoll removed: True
   at System.Environment.get_StackTrace()
   at Barotrauma.Ragdoll.LogAccessedRemovedCharacterError() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Animation\Ragdoll.cs:line 1494
   at Barotrauma.GameScreen.Draw(Double deltaTime, GraphicsDevice graphics, SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\GameScreen.cs:line 104
   at Barotrauma.GameMain.Draw(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 957
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 666
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 508
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58
Coroutine Barotrauma.CoroutineManager+<DoInvokeAfter>d__11 threw an exception: Object reference not set to an instance of an object.
   at Barotrauma.Ragdoll.SetPosition(Vector2 simPosition, Boolean lerp, Boolean ignorePlatforms, Boolean forceMainLimbToCollider, Boolean detachProjectiles) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Animation\Ragdoll.cs:line 1809
   at Barotrauma.MonsterEvent.<>c__DisplayClass35_1.<Update>b__5() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\MonsterEvent.cs:line 634
   at Barotrauma.CoroutineManager.DoInvokeAfter(Action action, Single delay)+MoveNext() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 155
   at Barotrauma.CoroutineManager.PerformCoroutineStep(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 214
   at Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 236
Attempted to access a potentially removed ragdoll. Character: Swarmfeeder, id: 8532, removed: True, ragdoll removed: True
   at System.Environment.get_StackTrace()
   at Barotrauma.Ragdoll.LogAccessedRemovedCharacterError() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Animation\Ragdoll.cs:line 1494
   at Barotrauma.GameScreen.Draw(Double deltaTime, GraphicsDevice graphics, SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\GameScreen.cs:line 104
   at Barotrauma.GameMain.Draw(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 957
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 666
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 508
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58
Coroutine Barotrauma.CoroutineManager+<DoInvokeAfter>d__11 threw an exception: Object reference not set to an instance of an object.
   at Barotrauma.Ragdoll.SetPosition(Vector2 simPosition, Boolean lerp, Boolean ignorePlatforms, Boolean forceMainLimbToCollider, Boolean detachProjectiles) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Animation\Ragdoll.cs:line 1809
   at Barotrauma.MonsterEvent.<>c__DisplayClass35_1.<Update>b__5() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\MonsterEvent.cs:line 634
   at Barotrauma.CoroutineManager.DoInvokeAfter(Action action, Single delay)+MoveNext() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 155
   at Barotrauma.CoroutineManager.PerformCoroutineStep(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 214
   at Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 236
Attempted to access a potentially removed ragdoll. Character: Swarmfeeder, id: 8533, removed: True, ragdoll removed: True
   at System.Environment.get_StackTrace()
   at Barotrauma.Ragdoll.LogAccessedRemovedCharacterError() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Animation\Ragdoll.cs:line 1494
   at Barotrauma.GameScreen.Draw(Double deltaTime, GraphicsDevice graphics, SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\GameScreen.cs:line 104
   at Barotrauma.GameMain.Draw(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 957
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 666
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 508
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58
Coroutine Barotrauma.CoroutineManager+<DoInvokeAfter>d__11 threw an exception: Object reference not set to an instance of an object.
   at Barotrauma.Ragdoll.SetPosition(Vector2 simPosition, Boolean lerp, Boolean ignorePlatforms, Boolean forceMainLimbToCollider, Boolean detachProjectiles) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Animation\Ragdoll.cs:line 1809
   at Barotrauma.MonsterEvent.<>c__DisplayClass35_1.<Update>b__5() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\MonsterEvent.cs:line 634
   at Barotrauma.CoroutineManager.DoInvokeAfter(Action action, Single delay)+MoveNext() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 155
   at Barotrauma.CoroutineManager.PerformCoroutineStep(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 214
   at Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 236
Attempted to access a potentially removed ragdoll. Character: Swarmfeeder, id: 8534, removed: True, ragdoll removed: True
   at System.Environment.get_StackTrace()
   at Barotrauma.Ragdoll.LogAccessedRemovedCharacterError() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Animation\Ragdoll.cs:line 1494
   at Barotrauma.GameScreen.Draw(Double deltaTime, GraphicsDevice graphics, SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\GameScreen.cs:line 104
   at Barotrauma.GameMain.Draw(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 957
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 666
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 508
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/pull/4509/commits/b576006a04196656a104be6a543440790a2f7b7c

Note for testing: the mods don't seem necessary for reproducing this. Happens in any irradiated level with swarm feeders in it.

**Comment by PanmanS** [comment]
Nice

**Comment by Regalis11** [comment]
Thank you for taking the time to close this, but we'll keep it open until we've reviewed and tested the fix internally. :)

**Comment by Jasontti** [comment]
Tested in https://github.com/Regalis11/Barotrauma-development/pull/4509/commits/b576006a04196656a104be6a543440790a2f7b7c

Did not get error and had good performance with save file provided
Created a new save and no issues found.

Closing ticket.
