### ISSUE TITLE
[Unstable] Every time someone moves the text displayer GUI, all clients will disconnect from the server.

### ISSUE THREAD

**Issue by zhu-rengong** [Regalis11/Barotrauma#12772]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I moved the text displayer gui(Connection Panel), but I disconnected from the server and got:
```
Error while reading a message from server. 
Exception thrown while reading segment EntityEvent at position 32.
Inner exception: Message byte position incorrect after reading an event for the entity "Text Display (ID: 1196)" (ID 1196). The previous entity was "" (ID 0) Read 16 bits, expected message length was 80 bits.
   at Barotrauma.Networking.ClientEntityEventManager.Read(ServerNetSegment type, IReadMessage msg, Single sendingTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\NetEntityEvent\ClientEntityEventManager.cs:line 233
   at Barotrauma.Networking.GameClient.<>c__DisplayClass118_0.<ReadIngameUpdate>b__0(ServerNetSegment segment, IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 2120
   at Barotrauma.Networking.SegmentTableReader`1.Read(IReadMessage msg, SegmentDataReader segmentDataReader, ExceptionHandler exceptionHandler) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SegmentTable.cs:line 296
```

recent server log:
```
[10/07/2023 13:08:45]
  iivv has left the server.
[10/07/2023 13:08:46]
  iivv set the value "GuiFrameOffset" of the item "Text Display" to "-142,-72".
```

I think it's related to #10203 

### Reproduction steps

1. Host a server (I hosted a dedicated server)
2. Start a round
3. Use screw driver to interact with a text displayer and open its connection panel, then just move the gui frame.

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Multiplayer hosted using a dedicated server

### Version

Unstable (v1.1.14.0)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1b40cd204926bfbe8a6675dc65dfe810e1fbd726 (commit in our private repo)

**Comment by Jasontti** [comment]
Tested in https://github.com/Regalis11/Barotrauma-development/commit/eab0497fe9d11477c4b3afb3134ffe0d3eb56eb1

Tried moving gui boxes as a host and a client.
Poked around different items and connection dialogs.

No issues found
Closing ticket
