### ISSUE TITLE
Crash if there's corrupted save files in the save folder

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#12849]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The game crashes if there's corrupted save files (or files that can't be decompressed for whatever reason) in the save folder.

### Reproduction steps

1. Take a save file from the save folder
2. Open it in notepad, remove some random lines
3. Open the load game menu

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Happens outside single player or multiplayer game modes (e.g. game launches on startup, something broken in the main menu)

### Version

v1.1.18.0 (Treacherous Tides)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Exception: The archive entry was compressed using an unsupported compression method. (System.IO.InvalidDataException)
Target site: ErrorCode Inflate(FlushCode)
Stack trace: 
   at System.IO.Compression.Inflater.Inflate(FlushCode flushCode)
   at System.IO.Compression.Inflater.ReadInflateOutput(Byte* bufPtr, Int32 length, FlushCode flushCode, Int32& bytesRead)
   at System.IO.Compression.Inflater.ReadOutput(Byte* bufPtr, Int32 length, Int32& bytesRead)
   at System.IO.Compression.Inflater.InflateVerified(Byte* bufPtr, Int32 length)
   at System.IO.Compression.DeflateStream.CopyToStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.CopyTo(Stream destination, Int32 bufferSize)
   at System.IO.Compression.DeflateStream.CopyToStream.CopyFromSourceToDestination()
   at System.IO.Compression.DeflateStream.CopyTo(Stream destination, Int32 bufferSize)
   at Barotrauma.SaveUtil.DecompressFileToStream(String fileName) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SaveUtil.cs:line 427
   at Barotrauma.SaveUtil.ExtractGameSessionRootElementFromSaveFile(String savePath) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SaveUtil.cs:line 571
   at Barotrauma.SaveUtil.GetSaveFiles(SaveType saveType, Boolean includeInCompatible) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SaveUtil.cs:line 276
   at Barotrauma.SinglePlayerCampaignSetupUI.CreateLoadMenu(IEnumerable`1 saveFiles) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\CampaignSetupUI\SinglePlayerCampaignSetupUI.cs:line 586
   at Barotrauma.MainMenuScreen.SelectTab(Tab tab) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\MainMenuScreen.cs:line 636
   at Barotrauma.MainMenuScreen.SelectTab(GUIButton button, Object obj) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\MainMenuScreen.cs:line 605
   at Barotrauma.MainMenuScreen.<.ctor>b__33_3(GUIButton tb, Object userdata) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\MainMenuScreen.cs:line 191
   at Barotrauma.GUIButton.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIButton.cs:line 263
   at Barotrauma.GUI.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1244
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 876
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/12ddcb9c3ce4f3d71db4580a7838fbcb54683f16

**Comment by Rokvach** [comment]
Tested by corrupting a singleplayer and multiplayer save, load game menu works correctly and I can create/load new multiplayer campaigns just fine

Only issue I spotted was that the error message about a corrupted file was shown twice in the load game menu

![image](https://github.com/Regalis11/Barotrauma/assets/7299826/964a1575-f674-46fc-b95b-75d568df97f2)

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
