### ISSUE TITLE
Mod bug (Failed to add the prefab "Backpack")

### ISSUE THREAD

**Issue by Matiz753** [Regalis11/Barotrauma#12850]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Failed to load "C:/Users/mati7/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2251324465/Item/Rucksack.xml": Failed to add the prefab "Backpack", "Backpack" (Barotrauma.ItemPrefab) from "Duffle Bag 2.0, Backpack & WaistBelt" (C:\Users\mati7\AppData\Local\Daedalic Entertainment GmbH\Barotrauma\WorkshopMods\Installed\2251324465): a prefab with the same identifier from "Vanilla" (Content\ContentPackages) already exists; try overriding
   at Barotrauma.PrefabSelector`1.AddInternal(T prefab, Boolean isOverride) in B:\programming\c#\Barotrauma\Barotrauma\BarotraumaShared\SharedSource\Prefabs\PrefabSelector.cs:line 116
   at Barotrauma.PrefabSelector`1.Add(T prefab, Boolean isOverride) in B:\programming\c#\Barotrauma\Barotrauma\BarotraumaShared\SharedSource\Prefabs\PrefabSelector.cs:line 35
   at Barotrauma.PrefabCollection`1.Add(T prefab, Boolean isOverride) in B:\programming\c#\Barotrauma\Barotrauma\BarotraumaShared\SharedSource\Prefabs\PrefabCollection.cs:line 405
   at Barotrauma.GenericPrefabFile`1.LoadFromXElement(ContentXElement parentElement, Boolean overriding) in B:\programming\c#\Barotrauma\Barotrauma\BarotraumaShared\SharedSource\ContentManagement\ContentFile\GenericPrefabFile.cs:line 39
   at Barotrauma.GenericPrefabFile`1.LoadFromXElement(ContentXElement parentElement, Boolean overriding) in B:\programming\c#\Barotrauma\Barotrauma\BarotraumaShared\SharedSource\ContentManagement\ContentFile\GenericPrefabFile.cs:line 53
   at Barotrauma.ContentPackage.<>c__DisplayClass52_0.<<LoadContentEnumerable>g__loadFiles|1>d.MoveNext() in B:\programming\c#\Barotrauma\Barotrauma\BarotraumaShared\SharedSource\ContentManagement\ContentPackage\ContentPackage.cs:line 281

### Reproduction steps

yes

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Multiplayer hosted using a dedicated server

### Version

v1.1.18.0 (Treacherous Tides)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

It seems the issue here is that the mod includes an item with the identifier "backpack", which now conflicts with the vanilla "backpack" item. I'm afraid there's not much we can do about this at this point, unfortunately the creator of the mod will have to either decide to override the vanilla backpack, or change the identifier of the modded backpack if they want it to be a separate item. Sorry for the inconvenience!
