### ISSUE TITLE
Crash-To-Desktop when saving item assemblies, opening new sub file and then selecting parts.

### ISSUE THREAD

**Issue by WrillWasTaken** [Regalis11/Barotrauma#12887]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I opened Alien_Chasm3, I saved it as an item assembly. I opened Alien_DeadEndL, and attempted to select the entire thing and Alien_Chasm3 briefly appeared and seemed to be selected before my game crashed to desktop.

### Reproduction steps

1. Open sub file. Fully select except hulls. (I did not have hull view on so hulls were not selected)
2. Save as item assembly.
3. Open another sub file. Fully select except hulls.
4. Crash

### Bug prevalence

Just once

### Single player or multiplayer?

Happens outside single player or multiplayer game modes (e.g. game launches on startup, something broken in the main menu)

### Version

v1.1.18.1 (Treacherous Tides)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
(I've stripped the name of my user out of these logs since I use my real name.)

Barotrauma Client crash report (generated on 10/22/2023 12:03:41)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

F7D4E178CD6305F51EB2C98E0F1F2349

Game version 1.1.18.1 (ReleaseWindows, branch release/traitor-update-hotfix, revision c5ad1e362c)
Graphics mode: 2560x1440 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla (3A5F8F1), Advanced Headsets (3E13BB4), Backpacks (6D10E98), Enhanced Armaments + Chemical Agents (707E8CC), Enhanced Armaments Fuel for the Fire Expansion (9935848), Enhanced Armaments (441F09A), Chemical Agents (D851BD2), Saber Personal Protection REMAKE (E0DE49E), THG Armory - 'Vanilla' Armor Pack (2A8EC98), Huskmod - CM-DS (9B8BC17), Barotraumatic Xanmonsters1 Fixes (DE2B7CB), Improved  Stun (2BE3C39), GM Tools (E58B76F), Performance Fix (E5AC66F), Lua For Barotrauma (065607B), CM-DS Shipyard Assault (4835B04), Ruin Hallway Horizontal (6173916), Ruin Chamber 1 (7ED2952), Ruin Chamber 2 (3113F6A), Ruin Chamber 4 Way (1BB3B57), Ruin Chasm (E8554BD), Ruin Chasm 2 (418EAC6), Ruin Chasm 3 (0C8AC29)
Level seed: no level loaded
Loaded submarine: Alien_DeadEndL (0E724F21ABA6EA214B11B64442193389)
Selected screen: Barotrauma.SubEditorScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.22621.0 64 bit
    GPU name: NVIDIA GeForce GTX 1080 Ti
    Display mode: {Width:2560 Height:1440 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Could not set the transform of a body (World was null - has the body been removed?) (System.InvalidOperationException)
Target site: Void SetTransformIgnoreContacts(Microsoft.Xna.Framework.Vector2 ByRef, Single)
Stack trace: 
   at FarseerPhysics.Dynamics.Body.SetTransformIgnoreContacts(Vector2& position, Single angle) in <DEV>\Libraries\Farseer Physics Engine 3.5\Dynamics\Body.cs:line 740
   at Barotrauma.PhysicsBody.SetTransformIgnoreContacts(Vector2 simPosition, Single rotation, Boolean setPrevTransform) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Physics\PhysicsBody.cs:line 766
   at Barotrauma.Items.Components.TriggerComponent.Move(Vector2 amount, Boolean ignoreContacts) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\TriggerComponent.cs:line 267
   at Barotrauma.Item.Move(Vector2 amount, Boolean ignoreContacts) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 1576
   at Barotrauma.MapEntity.UpdateSelecting(Camera cam) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Map\MapEntity.cs:line 331
   at Barotrauma.SubEditorScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\SubEditorScreen.cs:line 5734
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 851
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[10/22/2023 12:03:33] WARNING: Entity "xandepthchargeshell" has no name!
[10/22/2023 12:03:33] WARNING: Entity "xandepthchargeshell" has no name!
[10/22/2023 12:03:16] WARNING: Entity "xandepthchargeshell" has no name!
[10/22/2023 12:03:16] WARNING: Entity "xandepthchargeshell" has no name!
[10/22/2023 12:02:40] WARNING: Entity "xandepthchargeshell" has no name!
[10/22/2023 12:02:39] WARNING: Entity "xandepthchargeshell" has no name!
[10/22/2023 12:01:57] WARNING: Entity "xandepthchargeshell" has no name!
[10/22/2023 12:01:57] WARNING: Entity "xandepthchargeshell" has no name!
[10/22/2023 12:01:27] WARNING: Entity "xandepthchargeshell" has no name!
[10/22/2023 12:01:27] WARNING: Entity "xandepthchargeshell" has no name!
[10/22/2023 12:00:59] WARNING: Entity "xandepthchargeshell" has no name!
[10/22/2023 12:00:59] WARNING: Entity "xandepthchargeshell" has no name!
[10/22/2023 12:00:05] WARNING: Entity "xandepthchargeshell" has no name!
[10/22/2023 12:00:05] WARNING: Entity "xandepthchargeshell" has no name!
[10/22/2023 11:50:56] WARNING: Entity "xandepthchargeshell" has no name!
[10/22/2023 11:50:56] WARNING: Entity "xandepthchargeshell" has no name!
[10/22/2023 11:50:56] WARNING: Entity "xandepthchargeshell" has no name!
[10/22/2023 11:50:55] WARNING: Entity "xandepthchargeshell" has no name!
[10/22/2023 11:50:15] Overriding an affliction or a buff with the identifier 'incrementalstun' using the file 'C:/Users//AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/3005836987/XMl/Med/Afflictions.xml'
[10/22/2023 11:50:15] Overriding an affliction or a buff with the identifier 'stun' using the file 'C:/Users//AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/3005836987/XMl/Med/Afflictions.xml'
[10/22/2023 11:50:14] WARNING: C:/Users//AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/3013221823/huskeventscampaign.xml: All root EventSets should have an identifier
[10/22/2023 11:50:14] WARNING: C:/Users//AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/3013221823/huskeventscampaign.xml: All root EventSets should have an identifier
[10/22/2023 11:50:14] WARNING: C:/Users//AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/3013221823/huskeventscampaign.xml: All root EventSets should have an identifier
[10/22/2023 11:50:14] WARNING: C:/Users//AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/3013221823/huskevents.xml: All root EventSets should have an identifier
[10/22/2023 11:50:14] WARNING: C:/Users//AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/3013221823/huskevents.xml: All root EventSets should have an identifier
[10/22/2023 11:50:14] WARNING: C:/Users//AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/3013221823/huskevents.xml: All root EventSets should have an identifier
[10/22/2023 11:50:14] Overriding an affliction or a buff with the identifier 'huskinfection' using the file 'C:/Users//AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/3013221823/Afflictions.xml'
[10/22/2023 11:48:59] Attempting to open ALC device "OpenAL Soft on Headset Earphone (HyperX Cloud Alpha S Chat)"
[10/22/2023 11:48:48] Logged in as Wrill (SteamID STEAM_1:0:229793864)
```

**Comment by WrillWasTaken** [comment]
Unsure if it matters but I selected using dragclick select.

**Comment by WrillWasTaken** [comment]
Happened again. Last frame looked like this.
![image](https://github.com/Regalis11/Barotrauma/assets/86113712/08609f69-732a-48ec-b7eb-511f9b548caa)

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
