### ISSUE TITLE
Game crash when nuking abyssal creatures with other content package enabled (GUIColor.op_Implicit)

### ISSUE THREAD

**Issue by Alpharius-30-milenium** [Regalis11/Barotrauma#12933]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

For some reason when you use nuke on endworm and charybdis game crashes with exception trace to source code. It did not happening in vanilla, replacing files in the mod did not work. (https://steamcommunity.com/sharedfiles/filedetails/?id=2610181908 happened with this mod, don't know about same issues in other mods)
*Once this bug did not happened but I wasn't able to replicate that situation

### Reproduction steps

1. Start round
2. Spawn Abyssal creature
3. Spawn nuclear shell
4. Nuke the creature
5. Get crash

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.1.18.1 (Treacherous Tides)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Microsoft.Xna.Framework.Color op_Implicit(Barotrauma.GUIColor)
Stack trace: 
   at Barotrauma.GUIColor.op_Implicit(GUIColor reference) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIPrefab.cs:line 326
   at Barotrauma.CharacterHUD.BossHealthBar.get_Color() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Characters\CharacterHUD.cs:line 102
   at Barotrauma.CharacterHUD.<UpdateBossProgressBars>g__SetColor|37_0(BossProgressBar bossHealthBar, GUIComponent container, Single alpha) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Characters\CharacterHUD.cs:line 838
   at Barotrauma.CharacterHUD.UpdateBossProgressBars(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Characters\CharacterHUD.cs:line 818
   at Barotrauma.CharacterHUD.Update(Single deltaTime, Character character, Camera cam) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Characters\CharacterHUD.cs:line 249
   at Barotrauma.Character.UpdateControlled(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Characters\Character.cs:line 449
   at Barotrauma.Character.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 3250
   at Barotrauma.AICharacter.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AICharacter.cs:line 76
   at Barotrauma.Character.UpdateAll(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 3101
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 185
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 851
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58
```

**Comment by Regalis11** [comment]
Thank you for the report!

The stack trace seems to imply that the recently added color "HealthBarColorPoisoned" is missing from the GUIStyle file. It should be possible to fix this by adding `<HealthBarColorPoisoned color="100,150,0,255"/>` to the style file.

A missing color obviously shouldn't cause the game to crash though, so I made the game use a hard-coded default color instead of crashing (commit in our private repo https://github.com/Regalis11/Barotrauma-development/commit/d86181e5630c66fdaa121c88b450ba433677675e).

**Comment by Regalis11** [comment]
Thank you for taking the time to close this, but we'll keep it open until we've tested the fix internally and merged the fix. :)

**Comment by Rokvach** [comment]
Tested, working correctly, compared to the current stable version where the crash happens. Can be merged and closed.
