### ISSUE TITLE
My name is Anton, i have problem in Barortauma, can you help me?

### ISSUE THREAD

**Issue by Yakyzza88228** [Regalis11/Barotrauma#12969]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

My name is Anton, i have problem in Barortauma, can you help me?
When i start the game, we crashed. 

Barotrauma Client crash report (generated on 11/04/2023 14:08:54)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

152BA3E19FDBF5D0CE7AEC3CB5E83BE4

Game version 1.1.19.3 (ReleaseWindows, branch release/traitor-update-hotfix-2, revision e92ea6f791)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: None
Selected content packages: None
Level seed: no level loaded
Loaded submarine: None
Selected screen: None
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19045.0 64 bit
    GPU name: NVIDIA GeForce GTX 1050 Ti
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: HRESULT: [0x8876017C], Module: [Unknown], ApiCode: [Unknown/Unknown], Message: Unknown (SharpDX.SharpDXException)
Target site: Void CheckError()
Stack trace: 
   at SharpDX.Result.CheckError()
   at SharpDX.DXGI.SwapChain.Present(Int32 syncInterval, PresentFlags flags)
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformPresent() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\GraphicsDevice.DirectX.cs:line 1010
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.Present() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\GraphicsDevice.cs:line 600
   at Microsoft.Xna.Framework.SdlGamePlatform.Present() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 267
   at Microsoft.Xna.Framework.Game.EndDraw() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 522
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 667
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 508
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
[crashreport (10).log](https://github.com/Regalis11/Barotrauma/files/13256727/crashreport.10.log)

   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[11/04/2023 14:08:50] Logged in as Yakyzza (SteamID STEAM_1:1:224478391)

### Reproduction steps

1) I start game in Steam 
2) He start
3. He crash 

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 11/04/2023 14:08:54)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

152BA3E19FDBF5D0CE7AEC3CB5E83BE4

Game version 1.1.19.3 (ReleaseWindows, branch release/traitor-update-hotfix-2, revision e92ea6f791)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: None
Selected content packages: None
Level seed: no level loaded
Loaded submarine: None
Selected screen: None
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19045.0 64 bit
    GPU name: NVIDIA GeForce GTX 1050 Ti
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: HRESULT: [0x8876017C], Module: [Unknown], ApiCode: [Unknown/Unknown], Message: Unknown (SharpDX.SharpDXException)
Target site: Void CheckError()
Stack trace: 
   at SharpDX.Result.CheckError()
   at SharpDX.DXGI.SwapChain.Present(Int32 syncInterval, PresentFlags flags)
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformPresent() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\GraphicsDevice.DirectX.cs:line 1010
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.Present() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\GraphicsDevice.cs:line 600
   at Microsoft.Xna.Framework.SdlGamePlatform.Present() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 267
   at Microsoft.Xna.Framework.Game.EndDraw() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 522
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 667
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 508
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[11/04/2023 14:08:50] Logged in as Yakyzza (SteamID STEAM_1:1:224478391)
```

**Comment by Yakyzza88228** [comment]
Please help me because my friend's waiting to me

**Comment by Yakyzza88228** [comment]
I managed! Just needed install official Windows

**Comment by Regalis11** [comment]
I'm glad you managed to figure it out! :) The error code 0x8876017C seems to mean that your system run out of video memory, which could potentially be explained by the unofficial windows install and maybe some outdated drivers. We've got [an existing report](https://github.com/Regalis11/Barotrauma/issues/7055) about this error, so I'll close this one.
