### ISSUE TITLE
Non-existent gaps

### ISSUE THREAD

**Issue by Bingbong-2000** [Regalis11/Barotrauma#12998]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

For some reason, the editor generates red gaps in the middle of nowhere, and when I try to remove them, my game crashes

### Reproduction steps

![image](https://github.com/Regalis11/Barotrauma/assets/150403602/25425174-44e5-489e-afdc-69551713132b)

this is what it looks like, theres no consistent way of achieving this, it just happens.

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Single player

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 11/10/2023 02:10:45)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

152BA3E19FDBF5D0CE7AEC3CB5E83BE4

Game version 1.1.19.3 (ReleaseWindows, branch release/traitor-update-hotfix-2, revision e92ea6f791)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla (D6A9CBF), Multi edge (D1C1C30), The cyclops cargo shuttle (AE007FC), BaroDrama V5 (91FE627), Zubtrauma (Dialog Only) (1BF5C45), Ulysses MkIVx (72C8738), The cyclops (8A2C705), Enhanced Armaments (5ECCD34), Enhanced Armaments Neurotrauma Patch (A5754DA), Vanilla Weapons Overhaul (Draconis) (C5DAFFB), realistic O2 generator (30FB0A2), EuropaWaifu++ Enhanced Armaments Patch (CC695BA), Random Number Generator (3E6E4FF), Enhanced Armaments DynamicEuropa Patch (9E76BF2), particle emitter (5E180C8), Modding Toolkit (E434CE7), Lua For Barotrauma (C98A633), CsForBarotrauma (09E517F), yay (E9FCA38), hatch (0E712D6), Dead Space (37A4D31), BS-64 (FA2AC31), Losharik (FDC93F9), B-64 scout drone (CE190F5), BeaconstationFusioncore (F6B30B1), USS Icebreaker (86F164F), Little mary (F90007C), Little mary drill (646FD4C), wip (3413203), Koka(Remade) (EE9503A), DE-R.A.A.S-V2 (196F81D), EK Dockyard (ED5F770), whale shutlle (381A60C), Engine (84D4310), Crew quarters (C3B5DF8), captainroom (9068F09), checker (B7C7A92), Uppergate (FF51534), Lowergate (88B5A4E), Lower gate (58A7057)
Level seed: no level loaded
Loaded submarine: wip (D8E813BBB9AE70FAE28227822F776F09)
Selected screen: Barotrauma.SubEditorScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.22621.0 64 bit
    GPU name: NVIDIA GeForce GTX 970
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: You are removing a body that is not in the simulation (userdata: CollisionBlocker (Gap 18)). (Parameter 'body') (System.ArgumentException)
Target site: Void Remove(FarseerPhysics.Dynamics.Body)
Stack trace: 
   at FarseerPhysics.Dynamics.World.Remove(Body body) in <DEV>\Libraries\Farseer Physics Engine 3.5\Dynamics\World.cs:line 1004
   at Barotrauma.Gap.Remove() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Gap.cs:line 813
   at Barotrauma.Extensions.IEnumerableExtensions.ForEach[T](IEnumerable`1 source, Action`1 action) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Extensions\IEnumerableExtensions.cs:line 128
   at Barotrauma.MapEntity.<UpdateSelecting>g__Delete|51_1() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Map\MapEntity.cs:line 180
   at Barotrauma.MapEntity.UpdateSelecting(Camera cam) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Map\MapEntity.cs:line 172
   at Barotrauma.SubEditorScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\SubEditorScreen.cs:line 5734
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 851
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58
```

**Comment by Regalis11** [comment]
Thank you for the report! 

When do these gaps appear? When you load the submarine? When you place a new wall? 

To me this looks like gaps generated on a damaged wall. I wonder if it could be somehow possible that the wall has gotten damaged? Have you for example been switching between the game view and the editor with console commands? What kind of mods are you using (wondering if there could be some modded item that's somehow doing damage to structures in the editor for example)?

Thanks and sorry for the inconvenience!

**Comment by Bingbong-2000** [comment]
(when they appear,) they only appear when I leave the testing mode in the editor

**Comment by Fachoj** [comment]
i think it save this gaps without linking it to wall or wall is null. i encounter this bug too, editing submarine and for some reason when i return from testing screen there was these error gaps beneath normal ones

**Comment by Saevon** [comment]
I have a sub file which keeps generating these, I have walls outside a hull, these walls are set to `HP: 0` to make them work as decorative pieces.

Whenever I load the sub it will recreate these gaps. Testing the sub will also recreate these gaps.   (Then trying to save the sub always gives me a "gaps shouldn't be outside a hull" warning so I have to manually remove them)


Secondly I have had these gaps sometimes appear in weird places (Cannot consistently reproduce, but it happened 3 times the last 2 hours). When this happens there are 2 copies of the hulls,,, sometimes on the same tile, sometimes its off by like 100pixels.  Either way the COPY crashes the game when I try to delete these.


(Will report back if I can make this happen consistently) BUT these hulls shouldn't be generated in the first place either?

**Comment by Fachoj** [comment]
hmm maybe easy solution is make 0 maxhealth walls do not make gaps and dont have collision. 0 health walls also part of "magnet" glitch-feature that makes game think that you still in sub and read info about connected hull that makes your character walk/swim outside of sub and not moving away from sub.

**Comment by Fachoj** [comment]
example(my unfinished submarine):
[watercorridors.sub.remove.zip](https://github.com/Regalis11/Barotrauma/files/13719790/watercorridors.sub.remove.zip)

**Comment by Regalis11** [comment]
Addressed in https://github.com/FakeFishGames/Barotrauma-development/commit/fca066564c400701a80203cce91503c1a6019697
