### ISSUE TITLE
Immediate crash to desktop when loading unmodded, vanilla save file after Treacherous Tides update

### ISSUE THREAD

**Issue by Aguateca** [Regalis11/Barotrauma#13042]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Hello, I have a long-running single-player campaign save file created earlier this year (maybe around March). Anyway, I came back to try the Treacherous Tides update but I immediately crash to desktop upon loading the save file. Vanilla game, no mods.

I had a couple of other, incomplete older campaign saves from late 2022 that load fine, but not my "main" save file. Attached is the crashreport:
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/13373645/crashreport.log)

I'd love to be able to play the new update on that campaign if possible, I spent a lot of time on that save file :)

### Reproduction steps

1. Select the campaign save
2. Wait for it to load and "press any key to continue" appears
3. Press any key, game immediately crashes to desktop

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 11/15/2023 22:22:57)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

152BA3E19FDBF5D0CE7AEC3CB5E83BE4

Game version 1.1.19.3 (ReleaseWindows, branch release/traitor-update-hotfix-2, revision e92ea6f791)
Graphics mode: 2560x1440 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla (D6A9CBF)
Level seed: Menec Fossa60
Loaded submarine: Winterhalter (2ED6374EA942DF7073C26C9306BC835F)
Selected screen: Barotrauma.GameScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19045.0 64 bit
    GPU name: NVIDIA GeForce RTX 3080
    Display mode: {Width:2560 Height:1440 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void Update(Single)
Stack trace: 
   at Barotrauma.SinglePlayerCampaign.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameSession\GameModes\SinglePlayerCampaign.cs:line 553
   at Barotrauma.GameSession.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameSession.cs:line 793
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 144
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 851
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[11/15/2023 22:22:46] WARNING: Kendall Petersen had talent that did not exist! Removing talent from CharacterInfo.
[11/15/2023 22:22:46] WARNING: Tried to add talent by identifier jackinthebox to character Kendall Petersen, but no such talent exists.
[11/15/2023 22:22:46] WARNING: Gloria Shah had talent that did not exist! Removing talent from CharacterInfo.
[11/15/2023 22:22:46] WARNING: Tried to add talent by identifier jackinthebox to character Gloria Shah, but no such talent exists.
[11/15/2023 22:22:46] WARNING: Rowena Newton had talent that did not exist! Removing talent from CharacterInfo.
[11/15/2023 22:22:46] WARNING: Tried to add talent by identifier jackinthebox to character Rowena Newton, but no such talent exists.
[11/15/2023 22:22:46] WARNING: Tania Krall had talent that did not exist! Removing talent from CharacterInfo.
[11/15/2023 22:22:46] WARNING: Tried to add talent by identifier jackinthebox to character Tania Krall, but no such talent exists.
[11/15/2023 22:22:46] WARNING: Megan Freeman had talent that did not exist! Removing talent from CharacterInfo.
[11/15/2023 22:22:46] WARNING: Tried to add talent by identifier jackinthebox to character Megan Freeman, but no such talent exists.
[11/15/2023 22:22:46] WARNING: Janessa Rivera had talent that did not exist! Removing talent from CharacterInfo.
[11/15/2023 22:22:46] WARNING: Tried to add talent by identifier jackinthebox to character Janessa Rivera, but no such talent exists.
[11/15/2023 22:22:42] Level identifier: outpostlevel
[11/15/2023 22:22:14] Attempting to open ALC device "OpenAL Soft on Speakers (High Definition Audio Device)"
[11/15/2023 22:22:09] Logged in as Luv (SteamID STEAM_1:1:33823659)
```

**Comment by Regalis11** [comment]
Thank you for the report!

Could you send us the save file so we could give it a test? Note that you need to .zip it first because github doesn't allow attaching files with the .save file extension. Thanks and sorry for the inconvenience!

**Comment by Aguateca** [comment]
Sure thing @Regalis11, see attachment! If I remember correctly, the only out-of-game modifications I ever made to this campaign (in a save editor) were:
- Was softlocked in Jacov Subra questline so I used a save editor to manually advance to the correct quest step
- The Winterhalter was updated in a patch (the one that attached the cabinet to the fab), but I already owned it and it didn't update my existing sub. I used a save editor to delete the Winterhalter I owned so I could re-buy the updated version

Let me know if you need any more info!

[Hard Campaign 2023.zip](https://github.com/Regalis11/Barotrauma/files/13383429/Hard.Campaign.2023.zip)

**Comment by Regalis11** [comment]
Thanks! This turned out to be a really strange edge case. :D

The sub in the save was in an outpost level with no outpost (the location was just an empty, uninhabited location). Normally that shouldn't be possible, but it seems this was cause by some of the changes we did to the campaign map in v1.0: the game forced the second-to-last location on the map to be uninhabited, and in this save the sub happened to be in that exact location.

I modified the save so the sub is now in the level leading up to that location, you should be able to use this to continue the save again: 
[Hard Campaign 2023_fixed.zip](https://github.com/Regalis11/Barotrauma/files/13393420/Hard.Campaign.2023_fixed.zip)

**Comment by Regalis11** [comment]
Fixed the crash in https://github.com/Regalis11/Barotrauma-development/commit/d99bc1ee01670af4545a325e6338aa05e9e79cb8 (commit in our private repo)

**Comment by Aguateca** [comment]
Great, I was able to load the fixed file and make my way back to an outpost. Thank you! Feel free to close this issue 👍

**Comment by Rokvach** [comment]
Tested with the provided save file, no issues. Closing.
