### ISSUE TITLE
Game crashes after getting a symbiote from event

### ISSUE THREAD

**Issue by N1ght-Raven** [Regalis11/Barotrauma#13064]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Game just crashes when i'm getting the husk symbiote in my singleplayer campaining. The only mod i did uset is perfrmance fix but disabling it not fix the problem. After some testing i notice that if i dont bring there one my bot that has spineling gene, everything works as it shoild, so guess it's happens because of additional limbs or something.

### Reproduction steps

1. Compleate a husk church quest line.
2. Use spineling gene.
3. Try to get the symbiote from last event.
3. Game crashes after getting a symbiote.

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 11/20/2023 10:42:09)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

856B384C4E526DFCCF2405379AABF26B

Game version 1.1.19.3 (ReleaseWindows, branch master, revision 759f66cf9f)
Graphics mode: 1360x768 (BorderlessWindowed)
VSync ON
Language: Russian
Selected content packages: Vanilla (D6A9CBF)
Level seed: Borvo Mensa80
Loaded submarine: Winterhalter (C16A980115160AFBA4FF112E0A3D9D27)
Selected screen: Barotrauma.GameScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19045.0 64 bit
    GPU name: NVIDIA GeForce GTX 1050 Ti
    Display mode: {Width:1360 Height:768 Format:Color AspectRatio:1.7708334}
    GPU status: Normal

Exception: Index was outside the bounds of the array. (System.IndexOutOfRangeException)
Target site: Void AddJoint(JointParams)
Stack trace: 
   at Barotrauma.Ragdoll.AddJoint(JointParams jointParams) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Animation\Ragdoll.cs:line 565
   at Barotrauma.AfflictionHusk.AttachHuskAppendage(Character character, Identifier afflictionIdentifier, ContentXElement appendageDefinition, Ragdoll ragdoll) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Health\Afflictions\AfflictionHusk.cs:line 460
   at Barotrauma.AfflictionHusk.ActivateHusk() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Health\Afflictions\AfflictionHusk.cs:line 220
   at Barotrauma.AfflictionHusk.Update(CharacterHealth characterHealth, Limb targetLimb, Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Health\Afflictions\AfflictionHusk.cs:line 86
   at Barotrauma.CharacterHealth.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Health\CharacterHealth.cs:line 859
   at Barotrauma.Character.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 3273
   at Barotrauma.AICharacter.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AICharacter.cs:line 76
   at Barotrauma.Character.UpdateAll(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 3116
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 184
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 859
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[11/20/2023 10:41:47] Unlocked mission "Биологическая угроза" in the connection from "Исследовательский центр Borvo Mensa" to "Шахта Topol".
[11/20/2023 10:33:58] Generating an outpost for the start of the level... (Location: Исследовательский центр Borvo Mensa, level type: Outpost)
[11/20/2023 10:33:58] Level identifier: outpostlevel
[11/20/2023 10:32:25] 
/// Running Oxygen Reloader version: 1.2.4 ///
--------------------------------------------------
Default tank swap button is: Q
Current tank swap button is: Q
[11/20/2023 10:32:15] Generating an outpost for the start of the level... (Location: Исследовательский центр Borvo Mensa, level type: Outpost)
[11/20/2023 10:32:15] Level identifier: outpostlevel
[11/20/2023 10:32:05]  - init.lua (Took 0.00471ms)
[11/20/2023 10:32:05] Oxygen Reloader 1.2.11
[11/20/2023 10:32:05]  - bagholdableitemswap.lua (Took 0.00040ms)
[11/20/2023 10:32:05] Bag HoldableItem SwapKey 1.0.0
[11/20/2023 10:32:05]  - init.lua (Took 0.03587ms)
[11/20/2023 10:32:05] Performance Fix 1.0.14
[11/20/2023 10:32:02] Using LuaSetup.lua from the content package.
[11/20/2023 10:32:02] Lua! Version 759f66cf9f
[11/20/2023 10:31:37] Attempting to open ALC device "OpenAL Soft on Наушники (2- High Definition Audio Device)"
[11/20/2023 10:31:34] Logged in as No4noi voron (SteamID STEAM_1:1:82037808)
```

**Comment by Regalis11** [comment]
Thank you for the report!

I unfortunately couldn't find a way to get this to happen. Tested by giving a character spineling genes and then the symbiosis. Also tested husk infection + symbiosis, and spineling genes + infection + symbiosis.

Based on the crash report it does seem like you still have some mods enabled, and are running a modified executable, so I wonder if those could have something to do with the error.

In any case, I added some more error handling to prevent this from crashing the game and to log a more descriptive error message (commit in our private repo https://github.com/Regalis11/Barotrauma-development/commit/4f64c4aafa2584f1c28b5b3e102c0872c2b15037).
