### ISSUE TITLE
[Unstable] Crash when bots try to shoot at ice spires

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#13080]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The game crashes when bots target ice spires

### Reproduction steps

1. Order a bot to man a turret
2. Find an ice spire

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.2.1.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Boolean CrewAIOperate(Single, Barotrauma.Character, Barotrauma.AIObjectiveOperateItem)
Stack trace: 
   at Barotrauma.Items.Components.Turret.CrewAIOperate(Single deltaTime, Character character, AIObjectiveOperateItem objective) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Turret.cs:line 1641
   at Barotrauma.AIObjectiveOperateItem.Act(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\Objectives\AIObjectiveOperateItem.cs:line 230
   at Barotrauma.HumanAIController.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\HumanAIController.cs:line 478
   at Barotrauma.Character.UpdateAll(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 3135
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 188
   at Barotrauma.GameMain.Run() in <DEV>\Barotrauma\BarotraumaServer\ServerSource\GameMain.cs:line 319
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Program.cs:line 78
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/705f94caed6346b820a60a3c9a738f1020934505

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
