### ISSUE TITLE
[Unstable] Crash after retrying round while choosing purchased item delivery option

### ISSUE THREAD

**Issue by HawkinsThe71st** [Regalis11/Barotrauma#13100]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

In a singleplayer campaign, purchasing an item and then retrying the round without picking the delivery option will cause the delivery option window to appear after loading. Picking an option causes a crash.

https://github.com/Regalis11/Barotrauma/assets/115734437/af40f0fb-2489-4406-81a3-cd541cf352f3

### Reproduction steps

1. Start a singleplayer campaign
2. Purchase any item from a merchant
3. Instead of picking the delivery option, exit the merchant menu and hit escape to retry the round
4. The delivery option window will still be visible after loading

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Single player

### -

v1.2.4.0 (Unstable)

### Version

Other

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 11/30/2023 12:02:08)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

37DB8696EE546E3C7F82F652F202D815

Game version 1.2.4.0 (ReleaseWindows, branch release/winter-update, revision 9dec27351e)
Graphics mode: 2560x1440 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla (C3A0328)
Level seed: LocationName.generic.30115
Loaded submarine: Dugong (11D74D6A2C33DBFB57D038F7B674EDE9)
Selected screen: Barotrauma.GameScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19045.0 64 bit
    GPU name: AMD Radeon RX 6650 XT
    Display mode: {Width:2560 Height:1440 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void PurchaseItems(Barotrauma.Identifier, System.Collections.Generic.List`1[Barotrauma.PurchasedItem], Boolean, Barotrauma.Networking.Client)
Stack trace: 
   at Barotrauma.CargoManager.PurchaseItems(Identifier storeIdentifier, List`1 itemsToPurchase, Boolean removeFromCrate, Client client) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\CargoManager.cs:line 301
   at Barotrauma.Store.<>c__DisplayClass123_0.<BuyItems>g__ConfirmPurchase|1(Boolean deliverImmediately) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\Store.cs:line 2124
   at Barotrauma.Store.<>c__DisplayClass123_1.<BuyItems>b__2(GUIButton btn, Object userdata) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\Store.cs:line 2105
   at Barotrauma.GUIButton.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIButton.cs:line 263
   at Barotrauma.GUI.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1252
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 880
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[11/30/2023 12:01:55] Generating an outpost for the start of the level... (Location: Corick Linea Habitation Outpost, level type: Outpost)
[11/30/2023 12:01:55] Level identifier: outpostlevel
[11/30/2023 12:01:21] Generating an outpost for the start of the level... (Location: Corick Linea Habitation Outpost, level type: Outpost)
[11/30/2023 12:01:21] Level identifier: outpostlevel
[11/30/2023 12:00:46] Attempting to open ALC device "OpenAL Soft on Speakers (High Definition Audio Device)"
[11/30/2023 12:00:45] Logged in as Hawkins (SteamID STEAM_1:1:72180162)
```

**Comment by Rokvach** [comment]
Tested, the prompt closes with the store now, so can't repro the original issue anymore, so working correctly. Closing.
