### ISSUE TITLE
Some console error after guards kill you

### ISSUE THREAD

**Issue by SomeRandomNoobKekeke** [Regalis11/Barotrauma#13151]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When your team is killed by security and the game ends, an error pops up
It doesn't seem to affect anything
I'm guessing some security guard still wants to beat up the already duffelbagged character

### Reproduction steps

Start campaign, you can take this [vanilla save](https://github.com/Regalis11/Barotrauma/files/13653534/test.zip) if you want
Attack security -> die
wait for this screen
![20231213004052_1](https://github.com/Regalis11/Barotrauma/assets/122838333/95f29f99-c3ff-4d15-bcac-82583bed0e7a)
check console

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Single player

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Attempted to access a potentially removed character. Character: Sara Petersen, id: 1570, removed: True. AnimController.Collider == null
   at System.Environment.get_StackTrace()
   at Barotrauma.Character.get_SimPosition() in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/Character.cs:line 1125
   at Barotrauma.Character.get_Position() in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/Character.cs:line 1142
   at Barotrauma.Entity.get_WorldPosition() in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Map/Entity.cs:line 49
   at Barotrauma.AIObjectiveCombat.Update(Single deltaTime) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/AI/Objectives/AIObjectiveCombat.cs:line 222
   at Barotrauma.AIObjectiveManager.UpdateObjectives(Single deltaTime) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/AI/Objectives/AIObjectiveManager.cs:line 293
   at Barotrauma.HumanAIController.Update(Single deltaTime) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/AI/HumanAIController.cs:line 410
   at Barotrauma.Character.UpdateAll(Single deltaTime, Camera cam) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/Character.cs:line 3108
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Screens/GameScreen.cs:line 184
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/GameMain.cs:line 859
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 651
   at Microsoft.Xna.Framework.Game.Tick() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Program.cs:line 58
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4332b765f1237c89f46fd1c17696feb9b65ed615

**Comment by NilanthAnimosus** [comment]
Tested against very-unstable-unstable-dec23 commit https://github.com/Regalis11/Barotrauma-development/commit/2f4a16d4bc5f0f9adc460be5186048fdbcaee4c5, no issues found, ready to merge
