### ISSUE TITLE
Event editor crash

### ISSUE THREAD

**Issue by Alpharius-30-milenium** [Regalis11/Barotrauma#13156]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I was editing some values in event editor and when I opened one of checkmoneyaction game crashed.

### Reproduction steps

It happened completely randomly, so, I can't tell right now how to reproduce this crash

### Bug prevalence

Just once

### Single player or multiplayer?

Other

### -

Event editor

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Exception: Unable to cast object of type 'System.Int32' to type 'System.Single'. (System.InvalidCastException)
Target site: Void CreateEditMenu(Barotrauma.ValueNode, Barotrauma.EventEditorNodeConnection)
Stack trace: 
   at Barotrauma.EventEditorScreen.CreateEditMenu(ValueNode node, EventEditorNodeConnection connection) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\EventEditor\EventEditorScreen.cs:line 860
   at Barotrauma.GUIContextMenu.OnSelected(GUIComponent _, Object data) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIContextMenu.cs:line 226
   at Barotrauma.GUIListBox.Select(Int32 childIndex, Force force, AutoScroll autoScroll, TakeKeyBoardFocus takeKeyBoardFocus, PlaySelectSound playSelectSound) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIListBox.cs:line 1068
   at Barotrauma.GUIListBox.UpdateChildrenRect() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIListBox.cs:line 788
   at Barotrauma.GUIListBox.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIListBox.cs:line 908
   at Barotrauma.GUI.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1244
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 876
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58
```

**Comment by Alpharius-30-milenium** [comment]
Ok, so when I tried to edit event again and tried to edit checkmoneyaction value it crashed again, so, I guess something might be wrong with it exactly

**Comment by Regalis11** [comment]
Thank you for the report!

The error seems to imply that the value that should be an integer or a float was set to something else (for example a string). I couldn't find a way to get that to occur - what exactly do you mean by editing the action?

**Comment by Alpharius-30-milenium** [comment]
> Thank you for the report!
> 
> The error seems to imply that the value that should be an integer or a float was set to something else (for example a string). I couldn't find a way to get that to occur - what exactly do you mean by editing the action?

So, I was editing other event that was chosen as template because literally all I needed is to change few tags and dialogue strings. Then I decided that I want that npc to be hired for higher price and of course I needed to change chekmoneyaction and moneyaction. When I opened node via rmb to edit value (that was set to 1000) game crashed.

**Comment by Regalis11** [comment]
Oh, I see, it was that simple! Just trying to edit the amount value (when it's set to any non-zero value) seems to crash the editor.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/654764c4e95ebe00d06bdc2e8be627e1db4fce28

**Comment by Jasontti** [comment]
Tested in: https://github.com/Regalis11/Barotrauma-development/pull/4769/commits/654764c4e95ebe00d06bdc2e8be627e1db4fce28

Tested editing CheckMoneyAction in vanilla events like blackmarket and miketheidiot1. No issues.
Tried to change integer fields strings. No issues.
Altered CheckMoneyAction externally to a string (amount="test") in .xml and got an error in the console
Altered CheckMoneyAction externally to a string (overridevalue="test") in .sevproj file and editor crashed as expected.

No issues found
Closing ticket
