### ISSUE TITLE
Client cannot run

### ISSUE THREAD

**Issue by DARKDEAD** [Regalis11/Barotrauma#1320]
v0.8.9.3

System info:
    Operating system: Microsoft Windows NT 6.2.9200.0 64 bit
    GPU name: Intel(R) HD Graphics 630
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1,777778}
    GPU status: Normal

Exception: Loading was interrupted due to an error: Адресат вызова создал исключение.
   в System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   в System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   в System.Security.Cryptography.CryptoConfig.CreateFromName(String name, Object[] args)
   в System.Security.Cryptography.MD5.Create()
   в Barotrauma.GameAnalyticsManager.Init()
   в Barotrauma.GameMain.InitUserStats()
   в Barotrauma.GameMain.<Load>d__86.MoveNext()
   в Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle)
Target site: Void Update(Microsoft.Xna.Framework.GameTime)
Stack trace: 
   в Barotrauma.GameMain.Update(GameTime gameTime)
   в Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   в Microsoft.Xna.Framework.Game.Tick()
   в MonoGame.Framework.WinFormsGameWindow.RunLoop()
   в Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   в Barotrauma.Program.Main()

Last debug messages:
[20.03.2019 16:43:01] Coroutine Barotrauma.GameMain+<Load>d__86 threw an exception: Адресат вызова создал исключение.
   в System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   в System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   в System.Security.Cryptography.CryptoConfig.CreateFromName(String name, Object[] args)
   в System.Security.Cryptography.MD5.Create()
   в Barotrauma.GameAnalyticsManager.Init()
   в Barotrauma.GameMain.InitUserStats()
   в Barotrauma.GameMain.<Load>d__86.MoveNext()
   в Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle)

**Comment by NilanthAnimosus** [comment]
it crashed while creating the MD5, attempting to create from name, and failed to invoke a method. thats very strange.

Not sure if this is a DLL issue or a .net issue or something along those lines.

**Comment by DARKDEAD** [comment]
Error  start server

System info:
    Operating system: Microsoft Windows NT 6.2.9200.0 64 bit

Exception: Адресат вызова создал исключение.
Target site: System.Object InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
Stack trace:
   в System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   в System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   в System.Security.Cryptography.CryptoConfig.CreateFromName(String name, Object[] args)
   в System.Security.Cryptography.MD5.Create()
   в Barotrauma.GameAnalyticsManager.Init()
   в Barotrauma.GameMain..ctor()
   в Barotrauma.Program.Main()


Last debug messages:
A crash report ("crashreport.log") was saved in the root folder of the game and sent to the developers.
Необработанное исключение: System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   в Barotrauma.Program.Main()
16:58:53 GameAnalyticsSDK.Net.Logging.GALogger Warning/GameAnalytics: Could not add error event: Datastore not initialized

**Comment by Akpo6at** [comment]
Barotrauma Client crash report (generated on 13.06.2019 12:53:03)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


84D97A22415E79CF8C19BAAC1D6B11B5


Game version 0.9.0.4
Graphics mode: 1920x1200 (BorderlessWindowed)
Selected content packages: Vanilla 0.9
Level seed: no level loaded
Loaded submarine: None
Selected screen: None
SteamManager initialized


System info:
    Operating system: Microsoft Windows NT 6.1.7601 Service Pack 1 64 bit
    Game not initialized


Exception: Object reference not set to an instance of an object.
Target site: Void Dispose(Boolean)
Stack trace: 
   at Microsoft.Xna.Framework.Graphics.Effect.Dispose(Boolean disposing)
   at Microsoft.Xna.Framework.Graphics.GraphicsResource.Dispose()
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.Dispose(Boolean disposing)
   at Microsoft.Xna.Framework.GraphicsDeviceManager.Dispose(Boolean disposing)
   at Microsoft.Xna.Framework.Game.Dispose(Boolean disposing)
   at Microsoft.Xna.Framework.Game.Dispose()
   at Barotrauma.Program.Main() in E:\Barotrauma-development\Barotrauma\BarotraumaClient\Source\Program.cs:line 84


Last debug messages:
[13.06.2019 12:51:29] Unknown SharpDX exception code (887A0005)
[13.06.2019 12:51:29] SharpDX exception caught. (HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown, 887A0005). Attempting to fix...
[13.06.2019 12:51:29] Loading texture "Content/Effects/waterbump.png" failed! {HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: Unknown}
   at SharpDX.Result.CheckError()
   at SharpDX.Direct3D11.DeviceContext.MapSubresource(Resource resourceRef, Int32 subresource, MapMode mapType, MapFlags mapFlags)
   at SharpDX.Direct3D11.DeviceContext.MapSubresource(Texture2D resource, Int32 mipSlice, Int32 arraySlice, MapMode mode, MapFlags flags, DataStream& stream)
   at SharpDX.Direct3D11.DeviceContext.MapSubresource(Resource resource, Int32 subresource, MapMode mode, MapFlags flags, DataStream& stream)
   at Microsoft.Xna.Framework.Graphics.Texture2D.PlatformGetData[T](Int32 level, Int32 arraySlice, Rectangle rect, T[] data, Int32 startIndex, Int32 elementCount)
   at Microsoft.Xna.Framework.Graphics.Texture2D.GetData[T](T[] data)
   at Barotrauma.TextureLoader.PreMultiplyAlpha(Texture2D& texture) in E:\Barotrauma-development\Barotrauma\BarotraumaClient\Source\Utils\TextureLoader.cs:line 102
   at Barotrauma.TextureLoader.FromFile(String path, Boolean preMultiplyAlpha) in E:\Barotrauma-development\Barotrauma\BarotraumaClient\Source\Utils\TextureLoader.cs:line 68
