### ISSUE TITLE
Level equality check failed when attempting to join a game in progress

### ISSUE THREAD

**Issue by Herbalicious** [Regalis11/Barotrauma#13288]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I am currently hosting a rather large modded campaign for a group of friends; ~20 people. Out of them, two (that joined late) reliably had this issue when attempting to join in progress, but had zero issues when the entire server backed out to the lobby to pick them up. After they were in the game, they were never kicked or errored out through about four or five round-end screens iirc. 

There's quite a few instances of this error on the issue tracker; I originally posted this as a comment on another issue, but at closer inspection is looks like the same error with an entirely different trigger, and I couldn't find a report that exactly mirrored the issue we were having, so I decided to split it into a separate report.

I am running a dedicated server (with Lua for Barotrauma, for transparency) on Ubuntu 20.04.6 LTS via a [Debian 12 based SteamCMD docker image](https://hub.docker.com/r/steamcmd/steamcmd/tags), and am using [these mods](https://i.imgur.com/cjf8Vd8.png). When testing, we never used a sub with a shuttle (Azimuth, Camel).

In testing, the two people in question were consistently unable to join in progress on my server, even on a new campaign, with only a slight variation in the beginning of the error messages. The remainder of the messages were identical to each other, and the stack traces were identical to the above reports.

`Level equality check failed. The level generated at your end doesn't match the level generated by the server (client value VoronoiGen: 426B8930, server value VoronoiGen: 6FDB7F00 [...]`
and
`Level equality check failed. The level generated at your end doesn't match the level generated by the server (client value TunnelGen2: 55BC9FC5, server value TunnelGen2: 26D34E64 [...]`

A third player, who had not joined in progress originally, was able to join in progress without issue in our tests, which lead me to believe this is a client issue and not (at least inherently) an issue with my server.

In an attempt to figure out how to reproduce the issue so we could work around it and/or report it, the player experiencing the `TunnelGen2` error seems to have had their issue magically disappear. I have to assume it was accidentally fixed as per the following information.

The player experiencing the `VoronoiGen` error was also consistently being asked to download one of my mods (`More Components`) from the server, even though they were already subscribed to it on the workshop and up to date. That mod is pretty simple and, while it uses Lua, shouldn't touch anything that would cause a level generation mismatch. None of it's items have been made, used, or placed yet to my knowledge. Forcing a complete reinstall of all of their Barotrauma mods seems to have fixed their issue for the time being.

A fourth player, who was able to solve the issue during our game, was experiencing other unrelated console errors. After they deleted all of their workshop mods and changed their moustache (??), they began showing the same `TunnelGen2` error as the second player, and began being prompted to download a different mod from the server, `ST_Pirates`. After restarting their game, the prompt stopped showing up and their issue was resolved.

So, at least in our case, it seems that players who grabbed all of the mods via workshop prior to joining (and had no errors in their downloads) were able to play without issue, while those that are being prompted to download the server's version of a given mod for one reason or another are throwing this error. Frankly, this solution just *feels* like it shouldn't be correct, but that's the only thing we could find. If it had only been one person I'd have wrote it off as a fluke, but now we're at two, maybe three. I'm not sure why this only appears when joining a game already in progress, or why people are being prompted to download mods which they already have the most updated version of, but.. that's where we are at the moment.

Hope this helps, somehow!

### Reproduction steps

None that we could reliably figure out (before we had to attend to other plans).
Presumably, getting the server to send a "You need to download this mod" message?

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Multiplayer hosted using a dedicated server

### Version

v1.2.7.0 (Winter Update hotfix)

### Which operating system did you encounter this bug on?

Windows

**Comment by Rokvach** [comment]
I took a look at game analytics regarding the level equality check failed error, it does seem to happen but it seems to be quite rarer than previously, mostly seems to be thrown by modded servers and way less non-modded ones. 

Here's a list of all the different values I could find

Server: 

```
Error while reading a message from server. 
Level equality check failed. The level generated at your end doesn't match the level generated by the server, (client value TopAndBottom:7FA88DFD, server value TopAndBottom: 44D0AB08, level value count: 19, seed: LocationName.generic.3130LocationName.alien.2541, missions: beacon3, sub: Orca2 (D3F43F2, mirrored: True). Round init status: WaitingForStartGameFinalize. Round start save ID: 7, last save id: 7, pending save id: 7.
   at Barotrauma.Networking.GameClient.ReadStartGameFinalize(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 1035
   at Barotrauma.Networking.GameClient.ReadDataMessage(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 819
   at Barotrauma.Networking.P2PClientPeer.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\Primitives\Peers\P2PClientPeer.cs:line 255
   at Barotrauma.Networking.GameClient.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 522
```

Client:

```
Level equality check failed. The level generated at your end doesn't match the level generated by the server, (client value TopAndBottom:7FA88DFD, server value TopAndBottom: 44D0AB08, level value count: 19, seed: LocationName.generic.3130LocationName.alien.2541, missions: beacon3, sub: Orca2 (D3F43F2, mirrored: True). Round init status: WaitingForStartGameFinalize. Round start save ID: 7, last save id: 7, pending save id: 7.
```

Server:

```
Error while reading a message from server. 
Level equality check failed. The level generated at your end doesn't match the level generated by the server, (client value LevelGenParams:F4CA671, server value LevelGenParams: CD09E61, level value count: 19, seed: LocationName.city.3175, missions: , sub: Berilia (074CF85, mirrored: False). Round init status: WaitingForStartGameFinalize. Round start save ID: 11, last save id: 11, pending save id: 11.
   at Barotrauma.Networking.GameClient.ReadStartGameFinalize(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 1035
   at Barotrauma.Networking.GameClient.ReadDataMessage(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 819
   at Barotrauma.Networking.LidgrenClientPeer.HandleDataMessage(NetIncomingMessage lidgrenMsg) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\Primitives\Peers\LidgrenClientPeer.cs:line 163
   at Barotrauma.Networking.LidgrenClientPeer.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\Primitives\Peers\LidgrenClientPeer.cs:line 129
   at Barotrauma.Networking.GameClient.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 522
```

Client:
```
Level equality check failed. The level generated at your end doesn't match the level generated by the server, (client value LevelGenParams:F4CA671, server value LevelGenParams: CD09E61, level value count: 19, seed: LocationName.city.3175, missions: , sub: Berilia (074CF85, mirrored: False). Round init status: WaitingForStartGameFinalize. Round start save ID: 11, last save id: 11, pending save id: 11.
```

Server:

```
[MODDED] Error while reading a message from server. 
Level equality check failed. The level generated at your end doesn't match the level generated by the server, (client value Outposts:5A4BB0A4, server value Outposts: 3873B260, level value count: 19, seed: XRRgAh6U, missions: random_killhammerhead, sub: Isonoe (CBC5FEE, mirrored: False). Round init status: WaitingForStartGameFinalize.
   at Barotrauma.Networking.GameClient.ReadStartGameFinalize(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 1035
   at Barotrauma.Networking.GameClient.ReadDataMessage(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 819
   at Barotrauma.Networking.P2PClientPeer.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\Primitives\Peers\P2PClientPeer.cs:line 255
   at Barotrauma.Networking.GameClient.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 522
```

Client:
```
[MODDED] Level equality check failed. The level generated at your end doesn't match the level generated by the server, (client value Outposts:F52E5F2, server value Outposts: 4FA9787A, level value count: 19, seed: 744WjuSf, missions: salvageartifactruins, sub: Isonoe (CBC5FEE, mirrored: False). Round init status: WaitingForStartGameFinalize.
```

Server:

```
[MODDED] Error while reading a message from server. 
Level equality check failed. The level generated at your end doesn't match the level generated by the server, (client value LevelBodies:31183A22, server value LevelBodies: 632A4223, level value count: 19, seed: Dank348LocationName.huskchurch.6355, missions: huntinggrounds2, sub: Борей-Мк2 (549178B, mirrored: False). Round init status: WaitingForStartGameFinalize. Round start save ID: 5, last save id: 5, pending save id: 5.
   at Barotrauma.Networking.GameClient.ReadStartGameFinalize(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 1035
   at Barotrauma.Networking.GameClient.ReadDataMessage(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 819
   at Barotrauma.Networking.P2PClientPeer.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\Primitives\Peers\P2PClientPeer.cs:line 255
   at Barotrauma.Networking.GameClient.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 522
```

Client:
```
[MODDED] Level equality check failed. The level generated at your end doesn't match the level generated by the server, (client value LevelBodies:31183A22, server value LevelBodies: 632A4223, level value count: 19, seed: Dank348LocationName.huskchurch.6355, missions: huntinggrounds2, sub: Борей-Мк2 (549178B, mirrored: False). Round init status: WaitingForStartGameFinalize. Round start save ID: 5, last save id: 5, pending save id: 5.
```

Server:

```
[MODDED] Error while reading a message from server. 
Level equality check failed. The level generated at your end doesn't match the level generated by the server, (client value VoronoiGen:65922D48, server value VoronoiGen: 5DF99CCF, level value count: 19, seed: LocationName.huskchurch.15126, missions: , sub: ALCS-178 St. Ecclesia (3F16249, mirrored: False). Round init status: WaitingForStartGameFinalize. Round start save ID: 4, last save id: 4, pending save id: 4.
   at Barotrauma.Networking.GameClient.ReadStartGameFinalize(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 1035
   at Barotrauma.Networking.GameClient.ReadDataMessage(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 819
   at Barotrauma.Networking.P2PClientPeer.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\Primitives\Peers\P2PClientPeer.cs:line 255
   at Barotrauma.Networking.GameClient.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 522
```

Client:
```
[MODDED] Level equality check failed. The level generated at your end doesn't match the level generated by the server, (client value VoronoiGen:65922D48, server value VoronoiGen: 5DF99CCF, level value count: 19, seed: LocationName.huskchurch.15126, missions: , sub: ALCS-178 St. Ecclesia (3F16249, mirrored: False). Round init status: WaitingForStartGameFinalize. Round start save ID: 4, last save id: 4, pending save id: 4.
```
