### ISSUE TITLE
Some console error after you kill guards

### ISSUE THREAD

**Issue by SomeRandomNoobKekeke** [Regalis11/Barotrauma#13311]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I got this error while trying to wipe some separatist outpost
And I only noticed it after a few rounds and don't have save
I'm not sure about repro steps, there was a lot of stuff going on
I think it's related to https://github.com/Regalis11/Barotrauma/issues/13151
I'll lazily search for repro steps, but i hope you still remember what was touched there and can guess what could be causing it

### Reproduction steps

So i was playing with Dynamic Europa 
There is a cool mission "Separatist Station-Takeover"
You are given a squad of coalition soldiers and a task to wreck adjacent separatist outpost to pieces
I had 5 guys with pistols vs ~20 separatists with assault rifles
I locked them in med bay so  they don't suicide and went drilling the outpost with alien plasma cutter
The outpost flooded instantly, half of inhabitants poped, but dummy me locked the hatch to med bay by connecting water detector  to hatch "set state"
When outpost flooded 1 drop of water touched water detector and my boys charger into half flooded outpost
Fortunately most of the guards drowned, several were cut off by water
My squad and the remnants of the separatists shot each other almost completely, i only had to finish 1-2 wounded
And then the rest of them yielded cowardly
And then i looted that 20-30 corpses for 20min

What to notice:

- 90% of corpses was dufflebaged
- people that poped in the beginning died in almost same spot and their dufflebags was stacked ( i guess )
- They died all over the place
- Some was dufflebaged while fight was going on
- around 30 people died there, but i got only 1 error message
- I didn't notice any side effects

### Bug prevalence

Just once

### Single player or multiplayer?

Single player

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Attempted to access a potentially removed character. Character: Marcel Simpson, id: 3578, removed: True. AnimController.Collider == null
   at System.Environment.get_StackTrace()
   at Barotrauma.Character.get_SimPosition() in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/Character.cs:line 1148
   at Barotrauma.Character.get_Position() in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/Character.cs:line 1165
   at Barotrauma.Entity.get_WorldPosition() in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Map/Entity.cs:line 49
   at Barotrauma.AIObjectiveGoTo.StopMovement() in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/AI/Objectives/AIObjectiveGoTo.cs:line 816
   at Barotrauma.AIObjectiveGoTo.OnAbandon() in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/AI/Objectives/AIObjectiveGoTo.cs:line 802
   at Barotrauma.CombatAction.Update(Single deltaTime) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Events/EventActions/CombatAction.cs:line 68
   at Barotrauma.ScriptedEvent.Update(Single deltaTime) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Events/ScriptedEvent.cs:line 389
   at Barotrauma.EventManager.Update(Single deltaTime) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Events/EventManager.cs:line 892
   at Barotrauma.GameSession.Update(Single deltaTime) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/GameSession/GameSession.cs:line 796
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Screens/GameScreen.cs:line 143
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/GameMain.cs:line 863
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 651
   at Microsoft.Xna.Framework.Game.Tick() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Program.cs:line 58
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/682a98cc5878ff0ea9a1b1c25449bd05ad8ae75f
