### ISSUE TITLE
control console command

### ISSUE THREAD

**Issue by Dekkar1218** [Regalis11/Barotrauma#1607]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When using console command with cheatsenabled to control an NPC, it crashes unless its legacycrawler, mantis, mudraptor, moloch, and baby moloch. All other creatrues such as tigerthresher , cherybdis, endworm, and all others not listed crash the server.
 
**Steps To Reproduce**
just enablecheats in multiplayer and control a creature, if its one other then the 5 listed, all others crash the server.

**Version**
latest barotrauma, tested on multiple windows OS. its a game related issue, issue was also in Legacy Version before it went to steam.

**Additional information**
Seems the first 5 work pretty good, except the Mantis ocssioanly causes crashes or game failure. Other NPCS work falwlessly when possessed / controlled such as legacycrawler (not new crawler, new crawler crashs)

**Comment by Dekkar1218** [comment]
also forgot to mention before crash is incoming noticeable de sync on client and serverside was noticed. Tested with 15 players on several occasions.

**Comment by Dekkar1218** [comment]
2 CRASH LOGS last 2 times server was hosted with 12-16 players on June 8th, and June 11th. 

Barotrauma Dedicated Server crash report (generated on 6/8/2019 11:39:52 PM)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


Game version 0.9.0.4
Selected content packages: Vanilla 0.9, The Iron Gear, General Purpose Submarine., SCS Barracuda, Dugong Mk. II, The Hammer, Aegir Mark V (AS), S(ub)Long Mk4, Typhon Mk. III, Aegir Mk. III (0.9 Remake 1.4, Updated!), The Syger VI, Type VIIS, Capelin MkV, Sweet Pea, 3_Tigerfish_UCN
Level seed: yl9gCCq9
Loaded submarine: Typhon Mk. III (B6B8EEBCE012FD117ABC5F3AD192060D)
Selected screen: Barotrauma.GameScreen
Server (Round had started)


System info:
    Operating system: Microsoft Windows NT 6.2.9200.0 64 bit


Exception: entity is not IServerSerializable
Target site: Void CreateEntityEvent(Barotrauma.Networking.INetSerializable, System.Object[])
Stack trace: 
   at Barotrauma.Networking.GameServer.CreateEntityEvent(INetSerializable entity, Object[] extraData) in E:\Barotrauma-development\Barotrauma\BarotraumaServer\Source\Networking\GameServer.cs:line 835
   at Barotrauma.CharacterInfo.IncreaseSkillLevel(String skillIdentifier, Single increase, Vector2 worldPos) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\Source\Characters\CharacterInfo.cs:line 763
   at Barotrauma.Items.Components.Steering.Update(Single deltaTime, Camera cam) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\Source\Items\Components\Machines\Steering.cs:line 226
   at Barotrauma.Item.Update(Single deltaTime, Camera cam) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\Source\Items\Item.cs:line 1068
   at Barotrauma.MapEntity.UpdateAll(Single deltaTime, Camera cam) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\Source\Map\MapEntity.cs:line 345
   at Barotrauma.GameScreen.Update(Double deltaTime) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\Source\Screens\GameScreen.cs:line 167
   at Barotrauma.GameMain.Run() in E:\Barotrauma-development\Barotrauma\BarotraumaServer\Source\GameMain.cs:line 284
   at Barotrauma.Program.Main(String[] args) in E:\Barotrauma-development\Barotrauma\BarotraumaServer\Source\Program.cs:line 37


Last debug messages:

----------------------------------------------------------------------

Barotrauma Dedicated Server crash report (generated on 6/12/2019 3:32:47 AM)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


Game version 0.9.0.4
Selected content packages: Vanilla 0.9, The Iron Gear, General Purpose Submarine., Eel, Dugong Mk. II, The Hammer, Bullshark V2, S(ub)Long Mk4, Typhon Mk. III, Aegir Mk. III (0.9 Remake 1.4, Updated!), The Syger VI, Type VIIS, Capelin MkV, Sweet Pea, 3_Tigerfish_UCN, Ghal Maraz, The Pill. EDS Mark Ib, Insirius, The Coffin, RU-46 , Cyclops, Orca MK3, Dugong MKII Super Super, Ocean Glider, Slavetown MK2, Nautilus X, S.S. UWU, FRS_Minor, HeeYaiSSS, Kaguya MK I, Polaris, Mercury III, SCS Barracuda, Razorback, EK Coseus Mk-II, Union Mk1, U.S.S. Fishbowl, Atolla
Level seed: H77Pcn0E
Loaded submarine: Dugong MKII Super Super (6946D5574961DC361CD974E7AE9FDBC9)
Selected screen: Barotrauma.GameScreen
Server (Round had started)


System info:
    Operating system: Microsoft Windows NT 6.2.9200.0 64 bit


Exception: entity is not IServerSerializable
Target site: Void CreateEntityEvent(Barotrauma.Networking.INetSerializable, System.Object[])
Stack trace: 
   at Barotrauma.Networking.GameServer.CreateEntityEvent(INetSerializable entity, Object[] extraData) in E:\Barotrauma-development\Barotrauma\BarotraumaServer\Source\Networking\GameServer.cs:line 835
   at Barotrauma.CharacterInfo.IncreaseSkillLevel(String skillIdentifier, Single increase, Vector2 worldPos) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\Source\Characters\CharacterInfo.cs:line 763
   at Barotrauma.Items.Components.Steering.Update(Single deltaTime, Camera cam) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\Source\Items\Components\Machines\Steering.cs:line 226
   at Barotrauma.Item.Update(Single deltaTime, Camera cam) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\Source\Items\Item.cs:line 1068
   at Barotrauma.MapEntity.UpdateAll(Single deltaTime, Camera cam) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\Source\Map\MapEntity.cs:line 345
   at Barotrauma.GameScreen.Update(Double deltaTime) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\Source\Screens\GameScreen.cs:line 167
   at Barotrauma.GameMain.Run() in E:\Barotrauma-development\Barotrauma\BarotraumaServer\Source\GameMain.cs:line 284
   at Barotrauma.Program.Main(String[] args) in E:\Barotrauma-development\Barotrauma\BarotraumaServer\Source\Program.cs:line 37


Last debug messages:

**Comment by Regalis11** [comment]
Fixed in 81b6d21
