### ISSUE TITLE
Server crash after 0.9.0.6. [Crash log provided]

### ISSUE THREAD

**Issue by OverwatchVoice** [Regalis11/Barotrauma#1645]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The Barotrauma server I was hosting had crashed multiple times because of this bug. Seems to have something to do with the way game garbles text messages over radio?
**Steps To Reproduce**
Unsure

**Additional information**
Debug log:

```
Exception: Object reference not set to an instance of an object.
Target site: Single GetGarbleAmount(Barotrauma.Entity, Barotrauma.Entity, Single, Single)
Stack trace: 
   at Barotrauma.Networking.ChatMessage.GetGarbleAmount(Entity listener, Entity sender, Single range, Single obstructionmult) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\Source\Networking\ChatMessage.cs:line 129
   at Barotrauma.Networking.VoipServer.CanReceive(Client sender, Client recipient) in E:\Barotrauma-development\Barotrauma\BarotraumaServer\Source\Networking\Voip\VoipServer.cs:line 86
   at Barotrauma.Networking.VoipServer.SendToClients(List`1 clients) in E:\Barotrauma-development\Barotrauma\BarotraumaServer\Source\Networking\Voip\VoipServer.cs:line 55
   at Barotrauma.Networking.GameServer.Update(Single deltaTime) in E:\Barotrauma-development\Barotrauma\BarotraumaServer\Source\Networking\GameServer.cs:line 353
   at Barotrauma.GameMain.Run() in E:\Barotrauma-development\Barotrauma\BarotraumaServer\Source\GameMain.cs:line 283
   at Barotrauma.Program.Main(String[] args) in E:\Barotrauma-development\Barotrauma\BarotraumaServer\Source\Program.cs:line 36


```

**Comment by provet1** [comment]
I've also got the exact same crash, multiple times. 
Time it takes before it happens differ.

**Comment by Regalis11** [comment]
We pushed a hotfix now that should fix this. The crash occurred when there were spectators on the server and a living player was trying to use the voice chat without an in-game headset.
