### ISSUE TITLE
Dedicated Server unable to use kick/ban 

### ISSUE THREAD

**Issue by Dekkar1218** [Regalis11/Barotrauma#1647]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Can only kick or ban players while at the round start screen before the round begins by right clicking them then selecting the method that way. In game wont work at all, not even for the console in dedicated

**Steps To Reproduce**
host and try to kick or ban someone, wont work with names or via clientlist ID number

**Version**
1.9.0.6

**Additional information**
BUUGGZXZ

**Comment by Regalis11** [comment]
> Can only kick or ban players while at the round start screen before the round begins by right clicking them then selecting the method that way.
You can also kick/ban them from the info menu that opens by holding tab in-game, or using console commands ("kick"/"kickip"/"ban"/"banip").

> In game wont work at all, not even for the console in dedicated
When you try to use it via the console, what exactly happens? Is there an error message of some sort? And by console, do you mean the server console (the server window that opens when you run DedicatedServer.exe) or the in-game debug console you see when you press F3?

**Comment by Dekkar1218** [comment]
> When you try to use it via the console, what exactly happens? Is there an error message of some sort? And by console, do you mean the server console (the server window that opens when you run DedicatedServer.exe) or the in-game debug console you see when you press F3?

Server console that opens when running dedicated. When typing the ID or Name, it says Reason? Then after typing a reason and enter, nothing appears, and nothing happens. No feedback what so ever, just blank. But it works like a charm in lobby.

**Comment by OverwatchVoice** [comment]
That's odd. It usually gives me a prompt to ask me how long you wish the ban to last.

**Comment by Dekkar1218** [comment]
Barotrauma Client crash report (generated on 6/15/2019 12:46:06 PM)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


13F36767B94A0DDCB262317168C3F82A


Game version 0.9.0.6
Graphics mode: 1920x1080 (BorderlessWindowed)
Selected content packages: Vanilla 0.9, Aqua Durum, Daedalus, Panda, Le Terrible, Remora Mobile Fortress, Nemo, K-318 Behemoth, Union Mk2, Narwhal, Beetle, EK_Coseus_Mk-III, Monarch Type M, ARK, CCC Spear, Foxtrot MK 2, Doory, Dager, Ragnarok 2, Korora, Blade, A Mistake, Cerberus mk E11, Vindi, Cyclops with guns, Razorback, Ironbolt Mark II, Stylin II, Atolla, Bronze Baron, BigBoy
Level seed: SmFZ9dw4
Loaded submarine: Remora (89022AE34CC1D35AC52184FD1FD6C660)
Selected screen: Barotrauma.GameScreen
SteamManager initialized
Client (Round had started)


System info:
    Operating system: Microsoft Windows NT 6.2.9200.0 64 bit
    GPU name: NVIDIA GeForce GTX 1060 6GB
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.777778}
    GPU status: Normal


Exception: Object reference not set to an instance of an object.
Target site: Boolean BanPlayer(Barotrauma.GUIButton, System.Object)
Stack trace: 
   at Barotrauma.NetLobbyScreen.BanPlayer(GUIButton button, Object userData) in E:\Barotrauma-development\Barotrauma\BarotraumaClient\Source\Screens\NetLobbyScreen.cs:line 1615
   at Barotrauma.GUIButton.Update(Single deltaTime) in E:\Barotrauma-development\Barotrauma\BarotraumaClient\Source\GUI\GUIButton.cs:line 217
   at Barotrauma.GUI.<>c__DisplayClass112_0.<Update>b__0(GUIComponent c) in E:\Barotrauma-development\Barotrauma\BarotraumaClient\Source\GUI\GUI.cs:line 645
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Barotrauma.GUI.Update(Single deltaTime) in E:\Barotrauma-development\Barotrauma\BarotraumaClient\Source\GUI\GUI.cs:line 645
   at Barotrauma.GameMain.Update(GameTime gameTime) in E:\Barotrauma-development\Barotrauma\BarotraumaClient\Source\GameMain.cs:line 708
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at MonoGame.Framework.WinFormsGameWindow.TickOnIdle(Object sender, EventArgs e)
   at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at MonoGame.Framework.WinFormsGameWindow.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Barotrauma.Program.Main() in E:\Barotrauma-development\Barotrauma\BarotraumaClient\Source\Program.cs:line 60


Last debug messages:

latest crash when using ban in game crashed my client

**Comment by Regalis11** [comment]
That's a crash report from the client application, not the dedicated server, so unfortunately it won't help us fix the dedicated server issue. But in any case, thanks for the report, it looks like there is a banning issue in the client as well.

**Comment by Rokvach** [comment]
This issue has most likely been fixed on the upcoming update. Closing.
