### ISSUE TITLE
Control command still broken

### ISSUE THREAD

**Issue by Dekkar1218** [Regalis11/Barotrauma#1650]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Using control to take over different NPCS still not functioning. Only Mudraptor, Legacycrawler and a moloch are useable without crashing the server or causing OOS issues.

**Steps To Reproduce**
Control anything except the 3 mentioned and the server crashs, or goes heavily OOS then disconnects.

**Version**
0.9.0.6

**Additional information**
Self explainaitory.

**Comment by Regalis11** [comment]
I wasn't able to reproduce this, could you please send a crash report?

**Comment by OverwatchVoice** [comment]
Same here. I never had issues with it.

**Comment by Dekkar1218** [comment]
Seems crashing was redcued, however players seem to be forced to desync and they are disconnected. Othertimes it crashs, heres a couple reports from lastnight. When I get more players on today i'll try to replicate it and get the logs.
-------------------------------------
[6/15/2019 10:52:18 AM] Christine Phoenix: Hull breach in amidships!
[6/15/2019 10:52:22 AM] Ramon Mason: Hull breach in airlock!
[6/15/2019 10:52:28 AM] Outer wall breached by Tigerthresher
[6/15/2019 10:53:28 AM] Successfully authenticated client via Steam (Steam ID: 76561198853731457).
[6/15/2019 10:53:28 AM] Disconnected unauthenticated client (Steam ID: 76561198853731457). Steam authentication failed, (AuthTicketCanceled).
[6/15/2019 10:53:28 AM] WARNING: ServerEntityEventManager is lagging behind! Last sent id: 2244, latest create id: 2245
[6/15/2019 10:53:28 AM] Disconnecting client Dekkar due to excessive desync (expected old event 2245 (created 53.27 s ago, -0.04 s older than last event sent to anyone) Events queued: 3, last sent to all: 2244
[6/15/2019 10:53:28 AM] Dekkar has left the server.
[6/15/2019 10:53:28 AM] Ending round (entire crew dead)
[6/15/2019 10:53:28 AM] Ending the round...
--------------------------------------------------------------------
Barotrauma Dedicated Server crash report (generated on 6/14/2019 9:55:56 PM)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


Game version 0.9.0.6
Selected content packages: Vanilla 0.9, Aqua Durum, Daedalus, Panda, Le Terrible, Remora Mobile Fortress, Nemo, K-318 Behemoth, Union Mk2, Narwhal, Beetle, EK_Coseus_Mk-III, Monarch Type M, ARK, CCC Spear, Foxtrot MK 2, Doory, Dager, Ragnarok 2, Korora, Blade, A Mistake, Cerberus mk E11, Vindi, Cyclops with guns, Razorback
Level seed: ThawSt. Musk
Loaded submarine: Razorback (74BFB88B7C7B488ADAF110AA3F68035E)
Selected screen: Barotrauma.GameScreen
Server (Round had started)


System info:
    Operating system: Microsoft Windows NT 6.2.9200.0 64 bit


Exception: Object reference not set to an instance of an object.
Target site: Boolean CanUseRadio(Barotrauma.Character, Barotrauma.Items.Components.WifiComponent ByRef)
Stack trace: 
   at Barotrauma.Networking.ChatMessage.CanUseRadio(Character sender, WifiComponent& radio) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\Source\Networking\ChatMessage.cs:line 241
   at Barotrauma.Networking.VoipServer.CanReceive(Client sender, Client recipient) in E:\Barotrauma-development\Barotrauma\BarotraumaServer\Source\Networking\Voip\VoipServer.cs:line 86
   at Barotrauma.Networking.VoipServer.SendToClients(List`1 clients) in E:\Barotrauma-development\Barotrauma\BarotraumaServer\Source\Networking\Voip\VoipServer.cs:line 55
   at Barotrauma.Networking.GameServer.Update(Single deltaTime) in E:\Barotrauma-development\Barotrauma\BarotraumaServer\Source\Networking\GameServer.cs:line 353
   at Barotrauma.GameMain.Run() in E:\Barotrauma-development\Barotrauma\BarotraumaServer\Source\GameMain.cs:line 283
   at Barotrauma.Program.Main(String[] args) in E:\Barotrauma-development\Barotrauma\BarotraumaServer\Source\Program.cs:line 36


Last debug messages:
--------------------------------------------------------------------------
Barotrauma Client crash report (generated on 6/14/2019 10:04:18 PM)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


13F36767B94A0DDCB262317168C3F82A


Game version 0.9.0.6
Graphics mode: 1920x1080 (BorderlessWindowed)
Selected content packages: Vanilla 0.9, Aqua Durum, Daedalus, Panda, Le Terrible, Remora Mobile Fortress, Nemo, K-318 Behemoth, Union Mk2, Narwhal, Beetle, EK_Coseus_Mk-III, Monarch Type M, ARK, CCC Spear, Foxtrot MK 2, Doory, Dager, Ragnarok 2, Korora, Blade, A Mistake, Cerberus mk E11, Vindi, Cyclops with guns, Razorback
Level seed: zS0vMiHe
Loaded submarine: Union MK2 (A68F23C6D64779579983ECE8BEAD3FFC)
Selected screen: Barotrauma.GameScreen
SteamManager initialized
Client (Round had started)


System info:
    Operating system: Microsoft Windows NT 6.2.9200.0 64 bit
    GPU name: NVIDIA GeForce GTX 1060 6GB
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.777778}
    GPU status: Normal


Exception: Object reference not set to an instance of an object.
Target site: Boolean BanPlayer(Barotrauma.GUIButton, System.Object)
Stack trace: 
   at Barotrauma.NetLobbyScreen.BanPlayer(GUIButton button, Object userData) in E:\Barotrauma-development\Barotrauma\BarotraumaClient\Source\Screens\NetLobbyScreen.cs:line 1615
   at Barotrauma.GUIButton.Update(Single deltaTime) in E:\Barotrauma-development\Barotrauma\BarotraumaClient\Source\GUI\GUIButton.cs:line 217
   at Barotrauma.GUI.<>c__DisplayClass112_0.<Update>b__0(GUIComponent c) in E:\Barotrauma-development\Barotrauma\BarotraumaClient\Source\GUI\GUI.cs:line 645
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Barotrauma.GUI.Update(Single deltaTime) in E:\Barotrauma-development\Barotrauma\BarotraumaClient\Source\GUI\GUI.cs:line 645
   at Barotrauma.GameMain.Update(GameTime gameTime) in E:\Barotrauma-development\Barotrauma\BarotraumaClient\Source\GameMain.cs:line 708
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at MonoGame.Framework.WinFormsGameWindow.TickOnIdle(Object sender, EventArgs e)
   at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at MonoGame.Framework.WinFormsGameWindow.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Barotrauma.Program.Main() in E:\Barotrauma-development\Barotrauma\BarotraumaClient\Source\Program.cs:line 60


Last debug messages:
[6/14/2019 10:03:21 PM] READING CHARACTER SPAWN DATA
[6/14/2019 10:03:21 PM] READING CHARACTER SPAWN DATA
[6/14/2019 10:03:21 PM] READING CHARACTER SPAWN DATA
[6/14/2019 10:03:20 PM] READING CHARACTER SPAWN DATA
[6/14/2019 10:03:20 PM] READING CHARACTER SPAWN DATA
[6/14/2019 10:03:20 PM] READING CHARACTER SPAWN DATA
[6/14/2019 10:03:20 PM] READING CHARACTER SPAWN DATA
[6/14/2019 10:03:20 PM] READING CHARACTER SPAWN DATA
[6/14/2019 10:03:20 PM] READING CHARACTER SPAWN DATA
[6/14/2019 10:03:20 PM] READING CHARACTER SPAWN DATA
[6/14/2019 10:02:52 PM] Pony Slaystation
[6/14/2019 10:02:52 PM] Frenaiik gGea
[6/14/2019 10:02:52 PM] TheGreatHox
[6/14/2019 10:02:52 PM] itsMyre
[6/14/2019 10:02:52 PM] Koba
[6/14/2019 10:02:52 PM] Coconutsales
[6/14/2019 10:02:52 PM] Dim Witted
[6/14/2019 10:02:52 PM] Grogdar
[6/14/2019 10:02:52 PM] Joseph Conrad
[6/14/2019 10:02:52 PM] YouwishyouwerecooL
[6/14/2019 10:02:52 PM] Iseemus Stronk
[6/14/2019 10:02:52 PM] Book
[6/14/2019 10:02:52 PM] Wilson Mounsion
[6/14/2019 10:02:52 PM] Mobile Meow Machine
[6/14/2019 10:02:52 PM] meep
[6/14/2019 10:02:52 PM] Corn
[6/14/2019 10:02:52 PM] Mr.Doge

**Comment by Regalis11** [comment]
Haven't found a way to reproduce this, and the crash reports seem to be caused by unrelated issues.
