### ISSUE TITLE
Using steamcmd to run a server doesn't work

### ISSUE THREAD

**Issue by BlueTheKing** [Regalis11/Barotrauma#1674]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When trying to run a dedicated server using steamcmd an error pops up and the server doesn't launch.
<code>/home/buildbot/buildslave/steam_rel_client_linux/build/src/public/tier1/interface.h (264) : Assertion Failed: m_pModule CHIDDeviceListSDL(): Couldn't load libSDL2-2.0.so.0, not enumerating devices</code>

**Steps To Reproduce**
Install the server using <code>app_update 102634</code>
Do <code>app_run 1026340</code>

**Version**
v0.9.0.6
Ubuntu 18.04

**Additional information**
On the server steamcmd is installed in its own home directory while the BT server is in its own seperate folder.

**Comment by marcelb** [comment]
Same problem. No solution yet.

**Comment by Panzergrenadier** [comment]
Have a same problem on Ubuntu 14.04

**Comment by Regalis11** [comment]
Should be fixed now!

**Comment by BlueTheKing** [comment]
Nice, although i managed to find a workaround for using the Launch_DedicatedServer thing somewhere on the steam discussions.
I'll check it works with steamcmd.

**Comment by BlueTheKing** [comment]
When starting it using <code>app_run 1026340</code> this is displayed in the console:
```
>>The executable you have launched is not present in the content package Vanilla 0.9. Do you want to launch DedicatedServer.exe?
Starting the server...

Initializing Steam server failed.
Server started
```
Writing "y" or "yes" makes it restart the server but it displays the same thing again.
The server doesn't seem to be playable.

**Comment by Dragony** [comment]
Same Issue here, running Ubuntu 18.04.2 LTS

**Comment by BlueTheKing** [comment]
The workaround to run the dedicated server using DedicatedServer.exe doesn't work after 0.9.2.1 .

**Comment by AndyLee1024** [comment]
2019-12-27  still have this issue on Ubuntu 18.04.

**Comment by henrikp** [comment]
Also having the same issue under Debian 10.5 (buster)

```
./barotrauma_dedicated.sh
Redirecting stderr to '/home/henrik/.steam/logs/stderr.txt'
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...Warning: failed to init SDL thread priority manager: SDL not found
OK.

Connecting anonymously to Steam Public...Logged in OK
Waiting for user info...OK
/data/src/public/tier1/interface.h (264) : Assertion Failed: m_pModule
Warning: failed to set thread priority: set failed for priority 8
Warning: support for elevated priorities is most likely unavailable, suppressing future warnings
CHIDDeviceListSDL(): Couldn't load libSDL2-2.0.so.0, not enumerating devices
Barotrauma Dedicated Server 0.10.4.0 (ReleaseLinux, branch release, revision 965c31410a)
Loading game settings
Loading MD5 hash cache
Initializing SteamManager
Initializing GameAnalytics
Initializing GameScreen
Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean                    
Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean                     
Selected sub: Remora                                                                                                                                                                                              
Selected shuttle: Selkie                                                                                                                                                                                          
[08/08/2020 13:11:00]
  Starting the server...                                                                                                                                                                                          
[08/08/2020 13:11:00]
  Using Lidgren networking. Manual port forwarding may be required. If players cannot connect to the server, you may want to use the in-game hosting menu (which uses SteamP2P networking and does not require port forwarding).                                                                                                                                                                                                     
Coroutine Barotrauma.Networking.GameServer+<StartServer>d__47 threw an exception: InitGameServer returned false (0,43840,27015,27016,2,"1.0.0.0")                                                                  
   at Steamworks.SteamServer.Init(AppId appid, SteamServerInit init, Boolean asyncCallbacks) in /home/joonas/Barotrauma/Libraries/Facepunch.Steamworks/SteamServer.cs:line 94                                     
   at Barotrauma.Steam.SteamManager.CreateServer(GameServer server, Boolean isPublic) in /home/joonas/Barotrauma/Barotrauma/BarotraumaServer/ServerSource/Networking/SteamManager.cs:line 26                      
   at Barotrauma.Networking.GameServer.StartServer(Boolean isPublic)+MoveNext() in /home/joonas/Barotrauma/Barotrauma/BarotraumaServer/ServerSource/Networking/GameServer.cs:line 195                             
   at Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle) in /home/joonas/Barotrauma/Barotrauma/BarotraumaShared/SharedSource/CoroutineManager.cs:line 212
```

**Comment by Kruk939** [comment]
Still not fixed:
4.15.0-122-generic #124-Ubuntu SMP Thu Oct 15 13:03:05 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

```
Redirecting stderr to '/root/.steam/logs/stderr.txt'
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.

Connecting anonymously to Steam Public...Logged in OK
Waiting for user info...OK
/data/src/public/tier1/interface.h (264) : Assertion Failed: m_pModule
Warning: failed to init SDL thread priority manager: SDL not found
CHIDDeviceListSDL(): Couldn't load libSDL2-2.0.so.0, not enumerating devices
Barotrauma Dedicated Server 0.10.6.2 (ReleaseLinux, branch release, revision d0702df35e)
Loading game settings
Loading MD5 hash cache
Initializing SteamManager
Initializing GameAnalytics
Initializing GameScreen
Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
Selected sub: Remora
Selected shuttle: Selkie
[11/09/2020 17:11:00]
  Starting the server...
[11/09/2020 17:11:00]
  Using Lidgren networking. Manual port forwarding may be required. If players cannot connect to the server, you may want to use the in-game hosting menu (which uses SteamP2P networking and does not require port forwarding).                
Coroutine Barotrauma.Networking.GameServer+<StartServer>d__47 threw an exception: InitGameServer returned false (0,19603,27015,0,NoAuthentication,"1.0.0.0")
   at Steamworks.SteamServer.Init(AppId appid, SteamServerInit init, Boolean asyncCallbacks) in <DEV>/Libraries/Facepunch.Steamworks/SteamServer.cs:line 93
   at Barotrauma.Steam.SteamManager.CreateServer(GameServer server, Boolean isPublic) in <DEV>/Barotrauma/BarotraumaServer/ServerSource/Networking/SteamManager.cs:line 24
   at Barotrauma.Networking.GameServer.StartServer(Boolean isPublic)+MoveNext() in <DEV>/Barotrauma/BarotraumaServer/ServerSource/Networking/GameServer.cs:line 195
   at Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/CoroutineManager.cs:line 212
```

**Comment by jerbob** [comment]
Same issue on Alpine with the following `Dockerfile` I've written:
```dockerfile
FROM steamcmd/steamcmd:alpine

RUN steamcmd +login anonymous +app_update 1026340 validate +quit
RUN echo "x86" > /etc/apk/arch && apk update && apk add --no-cache curl-dev

CMD steamcmd +login anonymous +app_run 1026340
```
```
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
Redirecting stderr to '/root/.steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.

Connecting anonymously to Steam Public...Logged in OK
Waiting for user info...OK
src/public/tier1/interface.h (264) : Assertion Failed: m_pModule
crash_20210606023812_17.dmp[29]: Uploading dump (out-of-process)
/tmp/dumps/crash_20210606023812_17.dmp

Warning: failed to init SDL thread priority manager: SDL not found
Warning: failed to set thread priority: set failed for priority 8
Warning: support for elevated priorities is most likely unavailable, suppressing future warnings
CHIDDeviceListSDL(): Couldn't load libSDL2-2.0.so.0, not enumerating devices```

**Comment by StoneMcYT** [comment]
Any updates on this?
Same issue on Ubuntu 20.04 

```
Steam>app_run 1026340
src/public/tier1/interface.h (264) : m_pModule
src/public/tier1/interface.h (264) : m_pModule
CHIDDeviceListSDL(): Couldn't load libSDL2-2.0.so.0, not enumerating devices
chdir /root/Steam/steamapps/common/Barotrauma Dedicated Server
src/steamexe/main.cpp (253) : Assertion Failed: reaping pid: 1446016 -- sh
```

**Comment by avitsiuk** [comment]
Exact same issue here. Ubuntu 20.04.4

```
$ ./steamcmd +login anonymous +app_run 1026340
Redirecting stderr to '/home/steam/.steam/logs/stderr.txt'
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1648077083
-- type 'quit' to exit --
Loading Steam API...OK

Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
src/public/tier1/interface.h (264) : m_pModule
Warning: failed to set thread priority: set failed for priority 8
Warning: support for elevated priorities is most likely unavailable, suppressing future warnings
chdir /home/steam/.steam/steamapps/common/Barotrauma Dedicated Server
src/public/tier1/interface.h (264) : m_pModule
CHIDDeviceListSDL(): Couldn't load libSDL2-2.0.so.0, not enumerating devices
src/steamexe/main.cpp (253) : Assertion Failed: reaping pid: 37972 -- sh
```

**Comment by brettg0396** [comment]
Likewise, Debian stretch:

```sh
/home/steam/.steam/steamcmd/steamcmd.sh +force_install_dir /home/steam/Barotrauma +login anonymous +app_update 1026340 validate +app_run 1026340
Redirecting stderr to '/home/steam/.steam/logs/stderr.txt'
/tmp/dumps is not owned by us - delete and recreate
Unable to delete /tmp/dumps. Continuing anyway.
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1648077083
-- type 'quit' to exit --
Loading Steam API...OK

Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
 Update state (0x5) verifying install, progress: 2.09 (6291456 / 300659995)
Success! App '1026340' fully installed.
src/public/tier1/interface.h (264) : m_pModule
Warning: failed to set thread priority: set failed for priority 8
Warning: support for elevated priorities is most likely unavailable, suppressing future warnings
src/public/tier1/interface.h (264) : m_pModule
chdir /home/steam/Barotrauma
CHIDDeviceListSDL(): Couldn't load libSDL2-2.0.so.0, not enumerating devices
src/steamexe/main.cpp (253) : Assertion Failed: reaping pid: 20072 -- sh
```

**Comment by shangjiaxuan** [comment]
Same problem here:
```
Steam>app_run 1026340
chdir /home/shang/Steam/steamapps/common/Barotrauma Dedicated Server
Warning: failed to set thread priority: set failed for 8: -1: setpriority() failed
Warning: failed to set thread priority: set failed for priority 8
Warning: support for elevated priorities is most likely unavailable, suppressing future warnings
Warning: failed to set thread priority: set failed for 8: -1: setpriority() failed
CHIDDeviceListSDL(): Couldn't load libSDL2-2.0.so.0, not enumerating devices
src/steamexe/main.cpp (254) : Assertion Failed: reaping pid: 507323 -- sh
```

**Comment by Darker** [comment]
My log looks very similar. I thought it's an issue with steam, but this thread was one of the first results.
```
steam@hometvpc:~$ steamcmd +force_install_dir ~/games +login anonymous +app_update 1026340 validate +app_run 1026340
Redirecting stderr to '/home/steam/.steam/logs/stderr.txt'
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1660762488
-- type 'quit' to exit --
Loading Steam API...OK

Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
 Update state (0x5) verifying install, progress: 0.00 (0 / 300348955)
Success! App '1026340' fully installed.
src/public/tier1/interface.h (264) : m_pModule
Warning: failed to set thread priority: set failed for priority 8
Warning: failed to set thread priority: set failed for priority 8
Warning: support for elevated priorities is most likely unavailable, suppressing future warnings
Warning: support for elevated priorities is most likely unavailable, suppressing future warnings
src/public/tier1/interface.h (264) : m_pModule
CHIDDeviceListSDL(): Couldn't load libSDL2-2.0.so.0, not enumerating devices
chdir /home/steam/games
src/steamexe/main.cpp (254) : Assertion Failed: reaping pid: 402025 -- sh

^C
```
