### ISSUE TITLE
Barotrauma crashes on startup

### ISSUE THREAD

**Issue by MOHAX2150** [Regalis11/Barotrauma#1762]
Tried to reinstall it, even performed a clean Windows installation but I still get the same error. 2 week ago game was working fine, and now  I am unable to launch it. Here is the crash report:

Barotrauma Client crash report (generated on 7/20/2019 9:17:55 PM)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

752C75DF67AE693C26C6B0BE9DF5D74B

Game version 0.9.1.0
Graphics mode: 1366x768 (BorderlessWindowed)
Selected content packages: Vanilla 0.9
Level seed: no level loaded
Loaded submarine: None
Selected screen: None
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 6.2.9200.0 64 bit
    GPU name: Intel(R) HD Graphics 4000
    Display mode: {Width:1366 Height:768 Format:Color AspectRatio:1.778646}
    GPU status: Normal

Exception: Loading was interrupted due to an error: Object reference not set to an instance of an object.
   at Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle) in D:\Barotrauma-development\Barotrauma\BarotraumaShared\Source\CoroutineManager.cs:line 185
Target site: Void Update(Microsoft.Xna.Framework.GameTime)
Stack trace: 
   at Barotrauma.GameMain.Update(GameTime gameTime) in D:\Barotrauma-development\Barotrauma\BarotraumaClient\Source\GameMain.cs:line 595
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in C:\Users\Admin\Desktop\Repos\Barotrauma\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 651
   at Microsoft.Xna.Framework.Game.Tick() in C:\Users\Admin\Desktop\Repos\Barotrauma\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in C:\Users\Admin\Desktop\Repos\Barotrauma\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in C:\Users\Admin\Desktop\Repos\Barotrauma\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Barotrauma.Program.Main(String[] args) in D:\Barotrauma-development\Barotrauma\BarotraumaClient\Source\Program.cs:line 61

Last debug messages:
[7/20/2019 9:17:55 PM] Coroutine Load threw an exception: Object reference not set to an instance of an object.
   at Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle) in D:\Barotrauma-development\Barotrauma\BarotraumaShared\Source\CoroutineManager.cs:line 185
[7/20/2019 9:17:54 PM] Coroutine "Load" has thrown an exception {Unable to load DLL 'soft_oal_x64.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)}
   at OpenAL.Alc.OpenDevice(String deviceName)
   at Barotrauma.Sounds.SoundManager..ctor() in D:\Barotrauma-development\Barotrauma\BarotraumaClient\Source\Sounds\SoundManager.cs:line 121
   at Barotrauma.GameMain.<Load>d__87.MoveNext() in D:\Barotrauma-development\Barotrauma\BarotraumaClient\Source\GameMain.cs:line 357
   at Barotrauma.CoroutineManager.ExecuteCoroutineThread(CoroutineHandle handle) in D:\Barotrauma-development\Barotrauma\BarotraumaShared\Source\CoroutineManager.cs:line 136

**Comment by Rokvach** [comment]
This is a known issue which will be fixed for the next patch, but for now I've written a workaround to the problem which you can find from our known issues section of the roadmap here

https://trello.com/c/hR6h94Fi/221-game-crashes-on-start-workaround-included

Closing this issue.
