### ISSUE TITLE
Debug console input crash after disconnecting without finishing a server command response.

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#1780]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I was configuring a server then disconnected after checking I could use giveperm without completing the command (leaving a question in my console)

Then I was editing a fairly old (Pre-steam release tester dev version) submarine edit of the typhon fixing its various graphical/item/structural glitches and problems from being from such a version.

I went into character mode unable to access a locked storage container without an ID Card with the appropriate tags, so I went to spawn one via console in character mode and figured I would toss it in world and add the tags - the game instead crashed upon using the command:

spawnitem id_card inventory

- NOTE: I do not think I used enablecheats and this is likely not even the correct item identifier, and after more testing appears to be reproduced from connecting to a server and using giveperm without finishing, if not other question-based commands.

**Steps To Reproduce**
requires connecting to a server (with giveperm permissions) - running the giveperm 1 command and not finishing it, having the server shutdown / disconnect from it then running another console command if not inputting anything.

**Version**
0.9.202.0 steam test version

**Additional information**
Crash log contents that are relevant:
```
Barotrauma Client crash report (generated on 03/08/2019 16:43:43)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


AEB10BEADD49B140F5E024151C56396C


Game version 0.9.202.0
Graphics mode: 1920x1080 (BorderlessWindowed)
Selected content packages: Vanilla 0.9
Level seed: no level loaded
Loaded submarine: -RS- Typhon retrofit (FD09AA5A73DD820A41D78BB08735B956)
Selected screen: Barotrauma.SubEditorScreen
SteamManager initialized


System info:
    Operating system: Microsoft Windows NT 6.1.7601 Service Pack 1 64 bit
    GPU name: NVIDIA GeForce GTX 970
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.777778}
    GPU status: Normal


Exception: Object reference not set to an instance of an object.
Target site: Void <InitProjectSpecific>b__100(System.String)
Stack trace: 
   at Barotrauma.DebugConsole.<>c__DisplayClass20_2.<InitProjectSpecific>b__100(String perm) in D:\Barotrauma-development\Barotrauma\BarotraumaClient\Source\DebugConsole.cs:line 1353
   at Barotrauma.DebugConsole.ExecuteCommand(String command) in D:\Barotrauma-development\Barotrauma\BarotraumaShared\Source\DebugConsole.cs:line 1210
   at Barotrauma.DebugConsole.Update(GameMain game, Single deltaTime) in D:\Barotrauma-development\Barotrauma\BarotraumaClient\Source\DebugConsole.cs:line 166
   at Barotrauma.GameMain.Update(GameTime gameTime) in D:\Barotrauma-development\Barotrauma\BarotraumaClient\Source\GameMain.cs:line 770
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in C:\Users\Admin\Desktop\Repos\Barotrauma\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 651
   at Microsoft.Xna.Framework.Game.Tick() in C:\Users\Admin\Desktop\Repos\Barotrauma\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in C:\Users\Admin\Desktop\Repos\Barotrauma\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in C:\Users\Admin\Desktop\Repos\Barotrauma\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Barotrauma.Program.Main(String[] args) in D:\Barotrauma-development\Barotrauma\BarotraumaClient\Source\Program.cs:line 60


Last debug messages:
[03/08/2019 16:43:43] spawnitem id_card inventory
[03/08/2019 16:04:32] Error loading item - item prefab "Riot Shield" (identifier "riotshield") not found.
[03/08/2019 16:03:34] Do not attempt reconnect (not allowed).
[03/08/2019 16:03:34] Received a disconnect message (Failed to establish connection - no response from remote host)
[03/08/2019 15:58:29] Do not attempt to reconnect (DisconnectReason doesn't allow reconnection).
[03/08/2019 15:58:29] Received a disconnect message (ServerShutdown)
[03/08/2019 15:57:36]  - All
[03/08/2019 15:57:36]  - KarmaImmunity
[03/08/2019 15:57:36]  - ManagePermissions
[03/08/2019 15:57:36]  - ManageSettings
[03/08/2019 15:57:36]  - ServerLog
[03/08/2019 15:57:36]  - ConsoleCommands
[03/08/2019 15:57:36]  - ManageCampaign
[03/08/2019 15:57:36]  - SelectMode
[03/08/2019 15:57:36]  - SelectSub
[03/08/2019 15:57:36]  - Unban
[03/08/2019 15:57:36]  - Ban
[03/08/2019 15:57:36]  - Kick
[03/08/2019 15:57:36]  - ManageRound
[03/08/2019 15:57:36]  - None
[03/08/2019 15:57:36] Valid permissions are:
[03/08/2019 15:57:36] giveperm 1
[03/08/2019 15:57:16] help
[03/08/2019 15:56:50] Decompressing message: 2008 to 2714
[03/08/2019 15:56:08] Decompressing message: 2008 to 2714
[03/08/2019 15:55:33] Logged in as Nilanth Animosus (SteamID STEAM_---)
```

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
