### ISSUE TITLE
Loading was interrupted due to an error: Illegal characters in path.

### ISSUE THREAD

**Issue by Sgt-Tetgmeyer** [Regalis11/Barotrauma#1788]
- [ X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Barotrauma bug splats upon launching

**Steps To Reproduce**
Unknown at this time, the new update hit and it stooped working I uninstalled and reinstalled and it worked until I changed the resolution settings in game it has since not worked despite uninstalling and reinstalling several times. I have tried to manually change the resolution but to no avail.  

**Version**
0.9.2.1 Windows 10 64 bit

**Additional information**

Bug splat below 

Barotrauma Client crash report (generated on 8/26/2019 1:39:39 PM)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

ADBF6AF534CD711288BF778BC276C786

Game version 0.9.2.1
Graphics mode: 2560x1440 (BorderlessWindowed)
Selected content packages: Vanilla 0.9
Level seed: no level loaded
Loaded submarine: None
Selected screen: None
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 6.2.9200.0 64 bit
    GPU name: NVIDIA GeForce GTX 1080 Ti
    Display mode: {Width:2560 Height:1440 Format:Color AspectRatio:1.777778}
    GPU status: Normal

Exception: Loading was interrupted due to an error: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String path1, String path2, String path3)
   at Barotrauma.Steam.SteamManager.CheckWorkshopItemEnabled(Item item, Boolean checkContentFiles) in E:\Barotrauma-development\Barotrauma\BarotraumaClient\Source\Networking\SteamManager.cs:line 1212
   at Barotrauma.Steam.SteamManager.<>c__DisplayClass59_0.<AutoUpdateWorkshopItems>b__0(Query q) in E:\Barotrauma-development\Barotrauma\BarotraumaClient\Source\Networking\SteamManager.cs:line 1267
   at Facepunch.Steamworks.Workshop.Query.ResultCallback(SteamUGCQueryCompleted_t data, Boolean bFailed)
   at SteamNative.CallResult`1.RunCallback()
   at SteamNative.CallResult.Try()
   at Facepunch.Steamworks.BaseSteamworks.RunUpdateCallbacks()
   at Barotrauma.Steam.SteamManager.AutoUpdateWorkshopItems() in E:\Barotrauma-development\Barotrauma\BarotraumaClient\Source\Networking\SteamManager.cs:line 1295
   at Barotrauma.GameMain.<Load>d__90.MoveNext() in E:\Barotrauma-development\Barotrauma\BarotraumaClient\Source\GameMain.cs:line 401
   at Barotrauma.CoroutineManager.ExecuteCoroutineThread(CoroutineHandle handle) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\Source\CoroutineManager.cs:line 136
Target site: Void Update(Microsoft.Xna.Framework.GameTime)
Stack trace: 
   at Barotrauma.GameMain.Update(GameTime gameTime) in E:\Barotrauma-development\Barotrauma\BarotraumaClient\Source\GameMain.cs:line 631
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in D:\Repos\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 651
   at Microsoft.Xna.Framework.Game.Tick() in D:\Repos\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in D:\Repos\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in D:\Repos\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Barotrauma.Program.Main(String[] args) in E:\Barotrauma-development\Barotrauma\BarotraumaClient\Source\Program.cs:line 61

Last debug messages:
[8/26/2019 1:39:39 PM] Coroutine "Load" has failed
[8/26/2019 1:39:39 PM] Coroutine "Load" has thrown an exception {Illegal characters in path.}
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String path1, String path2, String path3)
   at Barotrauma.Steam.SteamManager.CheckWorkshopItemEnabled(Item item, Boolean checkContentFiles) in E:\Barotrauma-development\Barotrauma\BarotraumaClient\Source\Networking\SteamManager.cs:line 1212
   at Barotrauma.Steam.SteamManager.<>c__DisplayClass59_0.<AutoUpdateWorkshopItems>b__0(Query q) in E:\Barotrauma-development\Barotrauma\BarotraumaClient\Source\Networking\SteamManager.cs:line 1267
   at Facepunch.Steamworks.Workshop.Query.ResultCallback(SteamUGCQueryCompleted_t data, Boolean bFailed)
   at SteamNative.CallResult`1.RunCallback()
   at SteamNative.CallResult.Try()
   at Facepunch.Steamworks.BaseSteamworks.RunUpdateCallbacks()
   at Barotrauma.Steam.SteamManager.AutoUpdateWorkshopItems() in E:\Barotrauma-development\Barotrauma\BarotraumaClient\Source\Networking\SteamManager.cs:line 1295
   at Barotrauma.GameMain.<Load>d__90.MoveNext() in E:\Barotrauma-development\Barotrauma\BarotraumaClient\Source\GameMain.cs:line 401
   at Barotrauma.CoroutineManager.ExecuteCoroutineThread(CoroutineHandle handle) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\Source\CoroutineManager.cs:line 136
[8/26/2019 1:39:37 PM] Logged in as Sgt. Tetgmeyer (SteamID STEAM_1:1:47962619)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1a30118afefe5ad8703675b99d8c306b27cba767 (private repo)

**Comment by Rokvach** [comment]
Seems to be working correctly now, closing.
