### ISSUE TITLE
Allow enabling content packages without restarting the game

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#1839]
We should implement a way to unload/load content packages at runtime. Seems easy-ish to implement, I guess we could just remove existing prefabs etc and call the relevant content Init/Load methods.

**Comment by Rokvach** [comment]
- [ ] When you subscribe to a mod in the "Popular Mods" tab the "Downloading..." text doesn't ever go away even when the downloading does finish.

- [ ] When you unsubscribe from a mod you found in the "Popular Mods" tab the mod doesn't re-appear in the "Popular Mods" tab. (Fully restarting the game does add them back)

- [ ] Getting "File "Mods/ModName/filelist.xml" not found" errors when subscribing to mods, even tho the mod does have a filelist.xml.

- [ ] When installing BTE manually while the game is running and switching to it, the game prompts the player to restart their game even tho the mod was loaded successfully. 

- [ ] BTE causes massive lag (Didn't happen earlier in testing)

- [ ] Game crashed when trying to reload corepackage while BTE was selected (Tried to fix the language issue without restarting)

```
Barotrauma Client crash report (generated on 19.12.2019 2:24:12)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


5DE1D0553566FADA0662195FEEE86833


Game version 0.9.5.1
Graphics mode: 2560x1440 (BorderlessWindowed)
Selected content packages: BTE
Level seed: no level loaded
Loaded submarine: None
Selected screen: Barotrauma.MainMenuScreen
SteamManager initialized


System info:
    Operating system: Microsoft Windows NT 10.0.17134.0 64 bit
    GPU name: NVIDIA GeForce GTX 980 Ti
    Display mode: {Width:2560 Height:1440 Format:Color AspectRatio:1,777778}
    GPU status: Normal


Exception: Index was outside the bounds of the array.
Target site: Void RemoveByPrefab(Barotrauma.Particles.ParticlePrefab)
Stack trace: 
   at Barotrauma.Particles.ParticleManager.RemoveByPrefab(ParticlePrefab prefab) in C:\Users\RoniK\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\Source\Particles\ParticleManager.cs:line 235
   at Barotrauma.Particles.ParticlePrefab.Dispose() in C:\Users\RoniK\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\Source\Particles\ParticlePrefab.cs:line 18
   at Barotrauma.PrefabCollection`1.Remove(T prefab) in C:\Users\RoniK\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\Source\Prefabs\PrefabCollection.cs:line 141
   at Barotrauma.PrefabCollection`1.RemoveByFile(String filePath) in C:\Users\RoniK\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\Source\Prefabs\PrefabCollection.cs:line 166
   at Barotrauma.GameSettings.DisableContentPackageItems(IOrderedEnumerable`1 files, Boolean& shouldRefreshSubs, Boolean& shouldRefreshFabricationRecipes, Boolean& shouldRefreshSoundPlayer, Boolean& shouldRefreshRuinGenerationParams, Boolean& shouldRefreshScriptedEventSets, Boolean& shouldRefreshMissionPrefabs, Boolean& shouldRefreshLevelObjectPrefabs, Boolean& shouldRefreshLocationTypes, Boolean& shouldRefreshMapGenerationParams, Boolean& shouldRefreshLevelGenerationParams) in C:\Users\RoniK\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\Source\GameSettings.cs:line 566
   at Barotrauma.GameSettings.SelectCorePackage(ContentPackage contentPackage, Boolean forceReloadAll) in C:\Users\RoniK\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\Source\GameSettings.cs:line 294
   at Barotrauma.DebugConsole.ExecuteCommand(String command) in C:\Users\RoniK\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\Source\DebugConsole.cs:line 1290
   at Barotrauma.DebugConsole.Update(Single deltaTime) in C:\Users\RoniK\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\Source\DebugConsole.cs:line 180
   at Barotrauma.GameMain.Update(GameTime gameTime) in C:\Users\RoniK\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\Source\GameMain.cs:line 823
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in D:\Repos\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 651
   at Microsoft.Xna.Framework.Game.Tick() in D:\Repos\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in D:\Repos\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in D:\Repos\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Barotrauma.Program.Main(String[] args) in C:\Users\RoniK\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\Source\Program.cs:line 45


Last debug messages:
[19.12.2019 2:24:12] Content package load order: BTE
[19.12.2019 2:24:12] reloadcorepackage
[19.12.2019 2:23:57] Text "ApplySettingsButtonUnsavedChanges" not found.
[19.12.2019 2:23:57] Text "DisplayName.WeldingFuelTankEmpty" not found.
[19.12.2019 2:23:57] Text "DisplayName.OxygenTankEmpty" not found.
[19.12.2019 2:23:56] Text "JobDescription.watchman" not found.
[19.12.2019 2:23:56] Text "JobName.watchman" not found.
[19.12.2019 2:23:56] Text "JobDescription.assistant" not found.
[19.12.2019 2:23:56] Text "JobName.assistant" not found.
[19.12.2019 2:23:56] Text "JobDescription.mechanic" not found.
[19.12.2019 2:23:56] Text "JobName.mechanic" not found.
[19.12.2019 2:23:56] Text "JobDescription.engineer" not found.
[19.12.2019 2:23:56] Text "JobName.engineer" not found.
[19.12.2019 2:23:56] Text "JobDescription.medicaldoctor" not found.
[19.12.2019 2:23:56] Text "JobName.medicaldoctor" not found.
[19.12.2019 2:23:56] Text "JobDescription.securityofficer" not found.
[19.12.2019 2:23:56] Text "JobName.securityofficer" not found.
[19.12.2019 2:23:56] Text "JobDescription.captain" not found.
[19.12.2019 2:23:56] Text "JobName.captain" not found.
[19.12.2019 2:23:55] Couldn't load xml document "Content/Texts/EnglishVanilla.xml"! {Could not find file 'C:\Users\RoniK\Documents\Barotrauma-development\Barotrauma\bin\ReleaseWindows\Content\Texts\EnglishVanilla.xml'.}
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.FinishInitUriString()
   at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
   at System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
   at Barotrauma.XMLExtensions.TryLoadXml(String filePath) in C:\Users\RoniK\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\Source\Serialization\XMLExtensions.cs:line 23
[19.12.2019 2:23:54] Couldn't load xml document "Content/Texts/EnglishVanilla.xml"! {Could not find file 'C:\Users\RoniK\Documents\Barotrauma-development\Barotrauma\bin\ReleaseWindows\Content\Texts\EnglishVanilla.xml'.}
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.FinishInitUriString()
   at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
   at System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
   at Barotrauma.XMLExtensions.TryLoadXml(String filePath) in C:\Users\RoniK\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\Source\Serialization\XMLExtensions.cs:line 23
[19.12.2019 2:23:53] Couldn't load xml document "Content/Texts/EnglishVanilla.xml"! {Could not find file 'C:\Users\RoniK\Documents\Barotrauma-development\Barotrauma\bin\ReleaseWindows\Content\Texts\EnglishVanilla.xml'.}
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.FinishInitUriString()
   at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
   at System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
   at Barotrauma.XMLExtensions.TryLoadXml(String filePath) in C:\Users\RoniK\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\Source\Serialization\XMLExtensions.cs:line 23
[19.12.2019 2:23:53] Content package load order: BTE
[19.12.2019 2:23:51] Content package load order: Vanilla 0.9
[19.12.2019 2:23:17] Text "ApplySettingsButtonUnsavedChanges" not found.
[19.12.2019 2:23:17] Text "DisplayName.WeldingFuelTankEmpty" not found.
[19.12.2019 2:23:17] Text "DisplayName.OxygenTankEmpty" not found.
[19.12.2019 2:23:17] Text "JobDescription.watchman" not found.
[19.12.2019 2:23:17] Text "JobName.watchman" not found.
[19.12.2019 2:23:17] Text "JobDescription.assistant" not found.
[19.12.2019 2:23:17] Text "JobName.assistant" not found.
[19.12.2019 2:23:17] Text "JobDescription.mechanic" not found.
[19.12.2019 2:23:17] Text "JobName.mechanic" not found.
[19.12.2019 2:23:17] Text "JobDescription.engineer" not found.
[19.12.2019 2:23:17] Text "JobName.engineer" not found.
[19.12.2019 2:23:17] Text "JobDescription.medicaldoctor" not found.
[19.12.2019 2:23:17] Text "JobName.medicaldoctor" not found.
[19.12.2019 2:23:17] Text "JobDescription.securityofficer" not found.
[19.12.2019 2:23:17] Text "JobName.securityofficer" not found.
[19.12.2019 2:23:17] Text "JobDescription.captain" not found.
[19.12.2019 2:23:17] Text "JobName.captain" not found.
[19.12.2019 2:23:16] Couldn't load xml document "Content/Texts/EnglishVanilla.xml"! {Could not find file 'C:\Users\RoniK\Documents\Barotrauma-development\Barotrauma\bin\ReleaseWindows\Content\Texts\EnglishVanilla.xml'.}
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.FinishInitUriString()
   at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
   at System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
   at Barotrauma.XMLExtensions.TryLoadXml(String filePath) in C:\Users\RoniK\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\Source\Serialization\XMLExtensions.cs:line 23
[19.12.2019 2:23:15] Couldn't load xml document "Content/Texts/EnglishVanilla.xml"! {Could not find file 'C:\Users\RoniK\Documents\Barotrauma-development\Barotrauma\bin\ReleaseWindows\Content\Texts\EnglishVanilla.xml'.}
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.FinishInitUriString()
   at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
   at System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
   at Barotrauma.XMLExtensions.TryLoadXml(String filePath) in C:\Users\RoniK\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\Source\Serialization\XMLExtensions.cs:line 23
[19.12.2019 2:23:14] Couldn't load xml document "Content/Texts/EnglishVanilla.xml"! {Could not find file 'C:\Users\RoniK\Documents\Barotrauma-development\Barotrauma\bin\ReleaseWindows\Content\Texts\EnglishVanilla.xml'.}
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.FinishInitUriString()
   at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
   at System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
   at Barotrauma.XMLExtensions.TryLoadXml(String filePath) in C:\Users\RoniK\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\Source\Serialization\XMLExtensions.cs:line 23
[19.12.2019 2:23:13] Content package load order: BTE
[19.12.2019 2:21:15] Content/Characters/Watcher/Watcher.xml
[19.12.2019 2:21:15] Content/Characters/Tigerthresher/Tigerthresher.xml
[19.12.2019 2:21:15] Content/Characters/Mudraptor/Mudraptor.xml
[19.12.2019 2:21:15] Content/Characters/Molochboss/Molochboss.xml
[19.12.2019 2:21:15] Content/Characters/Moloch/Moloch.xml
[19.12.2019 2:21:15] Content/Characters/Mantis/Mantis.xml
[19.12.2019 2:21:15] Content/Characters/Legacytigerthresher/Legacytigerthresher.xml
[19.12.2019 2:21:15] Content/Characters/Legacymoloch/Legacymoloch.xml
[19.12.2019 2:21:15] Content/Characters/Legacyhusk/Legacyhusk.xml
[19.12.2019 2:21:15] Content/Characters/Legacycrawler/Legacycrawler.xml
[19.12.2019 2:21:15] Content/Characters/Legacycharybdis/Legacycharybdis.xml
[19.12.2019 2:21:15] Content/Characters/Husk/Husk.xml
[19.12.2019 2:21:15] Content/Characters/Humanhusk/Humanhusk.xml
[19.12.2019 2:21:15] Content/Characters/Human/Human.xml
[19.12.2019 2:21:15] Content/Characters/Hammerheadspawn/Hammerheadspawn.xml
[19.12.2019 2:21:15] Content/Characters/Hammerheadmatriarch/Hammerheadmatriarch.xml
[19.12.2019 2:21:15] Content/Characters/Hammerheadgold/Hammerheadgold.xml
[19.12.2019 2:21:15] Content/Characters/Hammerhead/Hammerhead.xml
[19.12.2019 2:21:15] Content/Characters/Fractalguardian2/Fractalguardian2.xml
[19.12.2019 2:21:15] Content/Characters/Fractalguardian/Fractalguardian.xml
[19.12.2019 2:21:15] Content/Characters/Endworm/Endworm.xml
[19.12.2019 2:21:15] Content/Characters/Crawler/Crawler.xml
[19.12.2019 2:21:15] Content/Characters/Coelanth/Coelanth.xml
[19.12.2019 2:21:15] Content/Characters/Charybdis/Charybdis.xml
[19.12.2019 2:21:15] Content/Characters/Carrier/Carrier.xml
[19.12.2019 2:21:15] Content/Characters/Bonethresher/Bonethresher.xml
[19.12.2019 2:21:15] Trying to spawn Content/Characters/Human/Human.xml
[19.12.2019 2:21:09] Content package load order: Vanilla 0.9
[19.12.2019 2:21:09] Content package load order: Vanilla 0.9
[19.12.2019 2:20:42] Trying to spawn Mods/Europa Fishies/Characters/Irma/Irma.xml
[19.12.2019 2:20:34] Mods/Europa Fishies/Characters/Thrasherhusk/Thrasherhusk.xml
[19.12.2019 2:20:34] Mods/Europa Fishies/Characters/Thrasher/Thrasher.xml
[19.12.2019 2:20:34] Mods/Europa Fishies/Characters/Irmahusk/Irmahusk.xml
[19.12.2019 2:20:34] Mods/Europa Fishies/Characters/Irma/Irma.xml
[19.12.2019 2:20:34] Mods/Europa Fishies/Characters/Hullfishhusk/Hullfishhusk.xml
[19.12.2019 2:20:34] Mods/Europa Fishies/Characters/Hullfish/Hullfish.xml
[19.12.2019 2:20:34] Mods/Europa Fishies/Characters/Hawkfishhusk/Hawkfishhusk.xml
[19.12.2019 2:20:34] Mods/Europa Fishies/Characters/Hawkfish/Hawkfish.xml
[19.12.2019 2:20:34] Mods/Europa Fishies/Characters/Glowfishhusk/Glowfishhusk.xml
[19.12.2019 2:20:34] Mods/Europa Fishies/Characters/Glowfish/Glowfish.xml
[19.12.2019 2:20:34] Content/Characters/Watcher/Watcher.xml
[19.12.2019 2:20:34] Content/Characters/Tigerthresher/Tigerthresher.xml
[19.12.2019 2:20:34] Content/Characters/Mudraptor/Mudraptor.xml
[19.12.2019 2:20:34] Content/Characters/Molochboss/Molochboss.xml
[19.12.2019 2:20:34] Content/Characters/Moloch/Moloch.xml
[19.12.2019 2:20:34] Content/Characters/Mantis/Mantis.xml
[19.12.2019 2:20:34] Content/Characters/Legacytigerthresher/Legacytigerthresher.xml
[19.12.2019 2:20:34] Content/Characters/Legacymoloch/Legacymoloch.xml
[19.12.2019 2:20:34] Content/Characters/Legacyhusk/Legacyhusk.xml
[19.12.2019 2:20:34] Content/Characters/Legacycrawler/Legacycrawler.xml
[19.12.2019 2:20:34] Content/Characters/Legacycharybdis/Legacycharybdis.xml
[19.12.2019 2:20:34] Content/Characters/Husk/Husk.xml
[19.12.2019 2:20:34] Content/Characters/Humanhusk/Humanhusk.xml
[19.12.2019 2:20:34] Content/Characters/Human/Human.xml
[19.12.2019 2:20:34] Content/Characters/Hammerheadspawn/Hammerheadspawn.xml
[19.12.2019 2:20:34] Content/Characters/Hammerheadmatriarch/Hammerheadmatriarch.xml
[19.12.2019 2:20:34] Content/Characters/Hammerheadgold/Hammerheadgold.xml
[19.12.2019 2:20:34] Content/Characters/Hammerhead/Hammerhead.xml
[19.12.2019 2:20:34] Content/Characters/Fractalguardian2/Fractalguardian2.xml
[19.12.2019 2:20:34] Content/Characters/Fractalguardian/Fractalguardian.xml
[19.12.2019 2:20:34] Content/Characters/Endworm/Endworm.xml
[19.12.2019 2:20:34] Content/Characters/Crawler/Crawler.xml
[19.12.2019 2:20:34] Content/Characters/Coelanth/Coelanth.xml
[19.12.2019 2:20:34] Content/Characters/Charybdis/Charybdis.xml
[19.12.2019 2:20:34] Content/Characters/Carrier/Carrier.xml
[19.12.2019 2:20:34] Content/Characters/Bonethresher/Bonethresher.xml
[19.12.2019 2:20:34] Trying to spawn Content/Characters/Human/Human.xml
[19.12.2019 2:19:33] Content package load order: Vanilla 0.9  |  Europa Fishies
[19.12.2019 2:19:01] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish
[19.12.2019 2:19:01] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish
[19.12.2019 2:19:00] Logged in as Rokvach (SteamID STEAM_1:1:18660466)
```

**Comment by Rokvach** [comment]
Also, 

- [ ] Disable core package dropdown if player doesn't have any other core packages installed other than Vanilla. (Currently might cause a bit confusion on the UX side as its hard to tell if its a dropdown or not, but dropdowns will have arrows with the new UI art which helps with this)

**Comment by Regalis11** [comment]
- [ ] You cannot add tags to Workshop items in the "Publish" menu. When publishing a submarine, only the "submarine" tag appears, for other content packages the list of tags is empty.

**Comment by Regalis11** [comment]
- [ ] If you publish a new mod in the Workshop, it shows up as being disabled in the Workshop menu and trying to enable it prompts an error "failed to update because there is already a mod installed at [path]". Seems to happen because the SteamWorkshopUrl field of the local content package is not set at any point, causing the game to interpret the packages as different ones.

**Comment by Rokvach** [comment]
Tested, working correctly. Moving to Done.
