### ISSUE TITLE
Multiplayer Door Crash

### ISSUE THREAD

**Issue by TheAlphaJesus** [Regalis11/Barotrauma#1977]
After joining a server and loading in, Steam will crash and subsequently cause Barotrauma to crash. It seems to happen when a door is opened. Log below. 

Barotrauma Client crash report (generated on 1/9/2020 7:43:54 PM)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

82D5F98C9FFDE58E64CF140A88952446

Game version 0.9.6.0
Level seed: no level loaded
Loaded submarine: None
Selected screen: None

System info:
    Operating system: Microsoft Windows NT 10.0.18362.0 64 bit
    Game not initialized

Exception: Could not find a part of the path 'C:\WINDOWS\System32\Mods'.
Target site: Void WinIOError(Int32, System.String)
Stack trace: 
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetDirectories(String path)
   at Barotrauma.ContentPackage.LoadAll()
   at Barotrauma.GameSettings..ctor()
   at Barotrauma.GameMain..ctor(String[] args)
   at Barotrauma.Program.Main(String[] args)

**Comment by Rokvach** [comment]
No clear way to reproduce this issue, might be better to close it and re-open if it happens to come up again. Closing.
