### ISSUE TITLE
Unstable - Client crash going to main menu when connected to dedicated server

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#2049]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The crash was on my client, I was running the 09..701 Windows Server in visual studio, I closed the server by stopping the debug.

My client however was the steam unstable (not windows debug) for 0.9.701, the server was already gone yet I hit escape then immediately crashed on clicking main menu, This is not my first time crashing the game with the ChildServerRelay (But both times involved either a debug server or debug client).

I have had a second crash where I simply connected, did not close my own dedicated server, Clicked main menu and crashed with the same error.

**Additional information**

![image](https://user-images.githubusercontent.com/29177976/73122184-dd066d00-3f79-11ea-987f-35d77a10a274.png)

Log file:

[crashreport (2).log](https://github.com/Regalis11/Barotrauma/files/4112078/crashreport.2.log)

Stack trace:
```csharp
Exception: Object reference not set to an instance of an object.
Target site: Void PrivateShutDown()
Stack trace: 
   at Barotrauma.Networking.ChildServerRelay.PrivateShutDown() in D:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Networking\ChildServerRelay.cs:line 64
   at Barotrauma.Networking.ChildServerRelay.ShutDown() in D:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Networking\ChildServerRelay.cs:line 47
   at Barotrauma.Networking.GameClient.Disconnect() in D:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 1998
   at Barotrauma.GameMain.QuitToMainMenu(Boolean save) in D:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 955
   at Barotrauma.GUI.QuitClicked(GUIButton button, Object obj) in D:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1965
   at Barotrauma.GUI.<>c__DisplayClass165_0.<TogglePauseMenu>b__7(GUIButton btn, Object userData) in D:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1949
   at Barotrauma.GUIButton.Update(Single deltaTime) in D:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIButton.cs:line 227
   at Barotrauma.GUIComponent.UpdateAuto(Single deltaTime) in D:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIComponent.cs:line 379
   at Barotrauma.GUI.<>c__DisplayClass127_0.<Update>b__0(GUIComponent c) in D:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 965
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Barotrauma.GUI.Update(Single deltaTime) in D:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 965
   at Barotrauma.GameMain.Update(GameTime gameTime) in D:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 857
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in D:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in D:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in D:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in D:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in D:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in D:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 41
```

**Comment by NilanthAnimosus** [comment]
Appears this occurs for all clients, regardless of disconnect reason.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/78f5ad8a80e90181a797406f178d91b42164a1f7 (private repo)

**Comment by Rokvach** [comment]
Tested, working correctly. Moving to Done.

**Comment by NilanthAnimosus** [comment]
Closing issue, as this definately is fixed.

**Comment by Rokvach** [comment]
We keep the tickets open until they are fully reviewed

**Comment by NilanthAnimosus** [comment]
Alright, I'll refrain from closing them.
