### ISSUE TITLE
Crash in StatusEffect.ApplyProjSpecific when round starts

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#2182]
@Rokvach commented on [Fri Nov 22 2019](https://github.com/Regalis11/Barotrauma-development/issues/1184)

```
Barotrauma Client crash report (generated on 22/11/2019 3:44:34 PM)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


BD5D2BBF6BA9E54C1F83E3CC5E1A470E


Game version 0.9.5.1
Graphics mode: 1920x1080 (BorderlessWindowed)
Selected content packages: Vanilla 0.9
Level seed: Qfh00Kgt
Loaded submarine: Cityscape - Salthane (17D395321786AF820333F0DACC29EC7C)
Selected screen: Barotrauma.GameScreen
SteamManager initialized
Client (Round had started)


System info:
    Operating system: Microsoft Windows NT 10.0.18362.0 64 bit
    GPU name: Intel(R) UHD Graphics 630
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.777778}
    GPU status: Normal


Exception: Object reference not set to an instance of an object.
Target site: Void ApplyProjSpecific(Single, Barotrauma.Entity, System.Collections.Generic.List`1[Barotrauma.ISerializableEntity], Barotrauma.Hull, Microsoft.Xna.Framework.Vector2)
Stack trace: 
   at Barotrauma.StatusEffect.ApplyProjSpecific(Single deltaTime, Entity entity, List`1 targets, Hull currentHull, Vector2 worldPosition) in E:\Barotrauma-development\Barotrauma\BarotraumaClient\Source\StatusEffects\StatusEffect.cs:line 93
   at Barotrauma.StatusEffect.Apply(Single deltaTime, Entity entity, List`1 targets, Nullable`1 worldPosition) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\Source\StatusEffects\StatusEffect.cs:line 852
   at Barotrauma.DelayedEffect.Update(Single deltaTime) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\Source\StatusEffects\DelayedEffect.cs:line 93
   at Barotrauma.StatusEffect.UpdateAll(Single deltaTime) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\Source\StatusEffects\StatusEffect.cs:line 895
   at Barotrauma.GameScreen.Update(Double deltaTime) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\Source\Screens\GameScreen.cs:line 134
   at Barotrauma.GameMain.Update(GameTime gameTime) in E:\Barotrauma-development\Barotrauma\BarotraumaClient\Source\GameMain.cs:line 815
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in D:\Repos\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 651
   at Microsoft.Xna.Framework.Game.Tick() in D:\Repos\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in D:\Repos\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in D:\Repos\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Barotrauma.Program.Main(String[] args) in E:\Barotrauma-development\Barotrauma\BarotraumaClient\Source\Program.cs:line 42


Last debug messages:
[22/11/2019 3:44:34 PM] Juniper Dume
[22/11/2019 3:44:34 PM] Dixon Cider
[22/11/2019 3:44:34 PM] L
[22/11/2019 3:44:34 PM] rhettmurdoch
[22/11/2019 3:44:34 PM] Mr. Tibs
[22/11/2019 3:44:34 PM] troym2003
[22/11/2019 3:44:34 PM] Violent Quaker
[22/11/2019 3:44:34 PM] ThatGuy
[22/11/2019 3:44:34 PM] Dixon Cider
[22/11/2019 3:44:34 PM] L
[22/11/2019 3:44:34 PM] rhettmurdoch
[22/11/2019 3:44:34 PM] Mr. Tibs
[22/11/2019 3:44:34 PM] troym2003
[22/11/2019 3:44:34 PM] Violent Quaker
[22/11/2019 3:44:34 PM] ThatGuy
[22/11/2019 3:43:26 PM] Dixon Cider
[22/11/2019 3:43:26 PM] L
[22/11/2019 3:43:26 PM] rhettmurdoch
[22/11/2019 3:43:26 PM] Mr. Tibs
[22/11/2019 3:43:26 PM] troym2003
[22/11/2019 3:43:26 PM] Violent Quaker
[22/11/2019 3:43:26 PM] ThatGuy
[22/11/2019 3:43:26 PM] Piggy
[22/11/2019 3:43:25 PM] Dixon Cider
[22/11/2019 3:43:25 PM] L
[22/11/2019 3:43:25 PM] rhettmurdoch
[22/11/2019 3:43:25 PM] Mr. Tibs
[22/11/2019 3:43:25 PM] troym2003
[22/11/2019 3:43:25 PM] Violent Quaker
[22/11/2019 3:43:25 PM] ThatGuy
[22/11/2019 3:43:25 PM] Piggy
[22/11/2019 3:41:18 PM] Dixon Cider
[22/11/2019 3:41:18 PM] L
[22/11/2019 3:41:18 PM] rhettmurdoch
[22/11/2019 3:41:18 PM] Mr. Tibs
[22/11/2019 3:41:18 PM] troym2003
[22/11/2019 3:41:18 PM] Violent Quaker
[22/11/2019 3:41:18 PM] ThatGuy
[22/11/2019 3:41:18 PM] Piggy
[22/11/2019 3:41:18 PM] Dixon Cider
[22/11/2019 3:41:18 PM] L
[22/11/2019 3:41:18 PM] rhettmurdoch
[22/11/2019 3:41:18 PM] Mr. Tibs
[22/11/2019 3:41:18 PM] troym2003
[22/11/2019 3:41:18 PM] ThatGuy
[22/11/2019 3:40:19 PM] Dixon Cider
[22/11/2019 3:40:19 PM] L
[22/11/2019 3:40:19 PM] rhettmurdoch
[22/11/2019 3:40:19 PM] Mr. Tibs
[22/11/2019 3:40:19 PM] troym2003
[22/11/2019 3:40:19 PM] Violent Quaker
[22/11/2019 3:40:19 PM] ThatGuy
[22/11/2019 3:40:19 PM] Piggy
[22/11/2019 3:40:19 PM] Dixon Cider
[22/11/2019 3:40:19 PM] rhettmurdoch
[22/11/2019 3:40:19 PM] Mr. Tibs
[22/11/2019 3:40:19 PM] troym2003
[22/11/2019 3:40:19 PM] Violent Quaker
[22/11/2019 3:40:19 PM] ThatGuy
[22/11/2019 3:40:19 PM] Piggy
[22/11/2019 3:39:48 PM] Dixon Cider
[22/11/2019 3:39:48 PM] L
[22/11/2019 3:39:48 PM] rhettmurdoch
[22/11/2019 3:39:48 PM] Mr. Tibs
[22/11/2019 3:39:48 PM] troym2003
[22/11/2019 3:39:48 PM] Violent Quaker
[22/11/2019 3:39:48 PM] ThatGuy
[22/11/2019 3:39:48 PM] Piggy
[22/11/2019 3:39:48 PM] Dixon Cider
[22/11/2019 3:39:48 PM] L
[22/11/2019 3:39:48 PM] rhettmurdoch
[22/11/2019 3:39:48 PM] Mr. Tibs
[22/11/2019 3:39:48 PM] troym2003
[22/11/2019 3:39:48 PM] Piggy
[22/11/2019 3:37:15 PM] Dixon Cider
[22/11/2019 3:37:15 PM] L
[22/11/2019 3:37:15 PM] rhettmurdoch
[22/11/2019 3:37:15 PM] Mr. Tibs
[22/11/2019 3:37:15 PM] troym2003
[22/11/2019 3:37:15 PM] Violent Quaker
[22/11/2019 3:37:15 PM] ThatGuy
[22/11/2019 3:37:15 PM] Piggy
[22/11/2019 3:37:15 PM] L
[22/11/2019 3:37:15 PM] rhettmurdoch
[22/11/2019 3:37:15 PM] Mr. Tibs
[22/11/2019 3:37:15 PM] troym2003
[22/11/2019 3:37:15 PM] Violent Quaker
[22/11/2019 3:37:15 PM] ThatGuy
[22/11/2019 3:36:23 PM] L
[22/11/2019 3:36:23 PM] rhettmurdoch
[22/11/2019 3:36:23 PM] Mr. Tibs
[22/11/2019 3:36:23 PM] troym2003
[22/11/2019 3:36:23 PM] Violent Quaker
[22/11/2019 3:36:23 PM] ThatGuy
[22/11/2019 3:36:23 PM] Piggy
[22/11/2019 3:36:23 PM] rhettmurdoch
[22/11/2019 3:36:23 PM] troym2003
[22/11/2019 3:36:23 PM] Violent Quaker
[22/11/2019 3:36:23 PM] Piggy
[22/11/2019 3:36:23 PM] rhettmurdoch
[22/11/2019 3:36:23 PM] troym2003
[22/11/2019 3:36:23 PM] Violent Quaker
[22/11/2019 3:36:23 PM] Piggy
[22/11/2019 3:36:23 PM] rhettmurdoch
[22/11/2019 3:36:23 PM] troym2003
[22/11/2019 3:36:23 PM] Violent Quaker
[22/11/2019 3:36:23 PM] rhettmurdoch
[22/11/2019 3:36:23 PM] troym2003
[22/11/2019 3:36:23 PM] Violent Quaker
[22/11/2019 3:36:23 PM] rhettmurdoch
[22/11/2019 3:36:23 PM] troym2003
[22/11/2019 3:36:23 PM] Violent Quaker
[22/11/2019 3:36:23 PM] rhettmurdoch
[22/11/2019 3:36:23 PM] troym2003
[22/11/2019 3:36:23 PM] Violent Quaker
[22/11/2019 3:36:23 PM] rhettmurdoch
[22/11/2019 3:36:23 PM] troym2003
[22/11/2019 3:36:23 PM] Violent Quaker
[22/11/2019 3:36:23 PM] Violent Quaker
[22/11/2019 3:36:23 PM] Violent Quaker
[22/11/2019 3:36:23 PM] Violent Quaker
[22/11/2019 3:36:23 PM] Violent Quaker
[22/11/2019 3:36:23 PM] Violent Quaker
[22/11/2019 3:36:23 PM] Violent Quaker
[22/11/2019 3:36:23 PM] Violent Quaker
[22/11/2019 3:36:23 PM] Violent Quaker
[22/11/2019 3:36:23 PM] Violent Quaker
[22/11/2019 3:36:23 PM] Violent Quaker
[22/11/2019 3:36:23 PM] Violent Quaker
[22/11/2019 3:36:23 PM] Violent Quaker
[22/11/2019 3:36:23 PM] Violent Quaker
[22/11/2019 3:36:23 PM] Violent Quaker
[22/11/2019 3:36:23 PM] Violent Quaker
[22/11/2019 3:36:23 PM] Violent Quaker
[22/11/2019 3:36:23 PM] Violent Quaker
[22/11/2019 3:36:23 PM] Violent Quaker
[22/11/2019 3:36:23 PM] Violent Quaker
[22/11/2019 3:33:54 PM] OpenAL Soft on Stereo Mix (Realtek(R) Audio) 44
[22/11/2019 3:33:54 PM] OpenAL Soft on Microphone (Realtek(R) Audio) 44
[22/11/2019 3:33:31 PM] Logged in as Weaponized Saltiness (SteamID STEAM_1:0:180127286)



---

@ekqvist commented on [Tue Jan 14 2020](https://github.com/Regalis11/Barotrauma-development/issues/1184#issuecomment-574084721)

Could this be considered fixed or is there something more we should do about it? I see that @Regalis11 fixed the problem with the null reference causing this crash in 9e4fae9, at least.

---

@Regalis11 commented on [Thu Feb 06 2020](https://github.com/Regalis11/Barotrauma-development/issues/1184#issuecomment-583010282)

I think this may have been caused by some old delayed status effect being left over from a previous round. They should be stopped in GameSession.EndRound, but if the round had been ended ungracefully (for example a disconnect, switching to main menu with console commands), they might've stuck around to the next round and caused a crash when attempting to access some sound that has been disposed.

There's now 2 additional safeguard that make sure that shouldn't happen, implemented in 055ee730 and 740abbd, so I'm pretty confident this shouldn't happen anymore. And if it does, the null checks in 9e4fae9 should prevent the game from crashing.

**Comment by Udrakan** [comment]
I had 2 crashes with this and on top of that 1 round where an effect played after loading finished. Thing is that I played with grenades when hosting P2P server and crashed it. I started hosting new P2P server and the nade effect happened at start of round. 

Here is a gif of the effect right after loading finished (sry for discord in foreground)

![2_unstable_effectbug1](https://user-images.githubusercontent.com/59519434/73993449-7e19fe00-4952-11ea-9520-e3bce8f00115.gif)

Here are 2 sound crashes
[crashreport (45).log](https://github.com/Regalis11/Barotrauma/files/4168557/crashreport.45.log)
[crashreport (44).log](https://github.com/Regalis11/Barotrauma/files/4168558/crashreport.44.log)

**Comment by Udrakan** [comment]
Here is a video where you can see that I've started hosting a NEW P2P server and the delayed effect still plays out.
https://streamable.com/e2bmv

**Comment by Regalis11** [comment]
Oh, I see the issue now! Thank you so much for the reports. Based on the line numbers it seems that the exception actually happens when trying to log an error message; specifically when trying to access sound.Filename after the sound has been disposed. The underlying problem in this case is that there was a delayed explosion effect on a grenade, but while getting your client in sync, the server removed the grenade before the effect triggered.

Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3f68262ca297bb335dae6fe4683dd46aa71a50a1

**Comment by Rokvach** [comment]
Working correctly. Closing.
