### ISSUE TITLE
Crash in custominterface using mods - Index is out of range

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#2237]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
A modder had caused the game to crash in the submarine editor whenever an item was selected with the following XML code:

```xml
<CustomInterface canbeselected="false" drawhudwhenequipped="true">
      <GuiFrame relativesize="0.3,0.8" minsize="392,624" maxsize="581,819" absoluteoffset="0,40" anchor="TopCenter" style="docCap"/>
    </CustomInterface>
```

Why was this used? As a means of an item bringing up an image a player could read (in this case, barotrauma extended in game documents). it specifically pertains to the submarine editor.

workaround was to just use an itemcomponent instead to hold the GuiFrame - but this should perhaps throw an error instead of crash, or have logic to simply not crash to begin with despite the incorrect usage of not including buttons and such.

**Steps To Reproduce**
Use the included XML code then select an item with it in the submarine editor.

**Version**
0.9.705.0 unstable (Also effects 0.9.6.0 stable).

**Additional information**

stacktrace of a crash from my visual studio:

```csharp
System.ArgumentOutOfRangeException
  HResult=0x80131502
  Message=Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
  Source=System.Private.CoreLib
  StackTrace:
   at System.Collections.Generic.List`1.get_Item(Int32 index) in /_/src/System.Private.CoreLib/shared/System/Collections/Generic/List.cs:line 154
   at Barotrauma.Items.Components.CustomInterface.CreateEditingHUD(SerializableEntityEditor editor) in F:\Github Sources\BT-FA\Barotrauma\BarotraumaClient\ClientSource\Items\Components\Signal\CustomInterface.cs:line 112
   at Barotrauma.Item.CreateEditingHUD(Boolean inGame) in F:\Github Sources\BT-FA\Barotrauma\BarotraumaClient\ClientSource\Items\Item.cs:line 656
   at Barotrauma.Item.UpdateEditing(Camera cam) in F:\Github Sources\BT-FA\Barotrauma\BarotraumaClient\ClientSource\Items\Item.cs:line 457
   at Barotrauma.MapEntity.UpdateEditor(Camera cam) in F:\Github Sources\BT-FA\Barotrauma\BarotraumaClient\ClientSource\Map\MapEntity.cs:line 639
   at Barotrauma.SubEditorScreen.Update(Double deltaTime) in F:\Github Sources\BT-FA\Barotrauma\BarotraumaClient\ClientSource\Screens\SubEditorScreen.cs:line 2513
   at Barotrauma.GameMain.Update(GameTime gameTime) in F:\Github Sources\BT-FA\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 796
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in F:\Github Sources\BT-FA\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 651
   at Microsoft.Xna.Framework.Game.Tick() in F:\Github Sources\BT-FA\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in F:\Github Sources\BT-FA\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in F:\Github Sources\BT-FA\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in F:\Github Sources\BT-FA\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in F:\Github Sources\BT-FA\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 41


```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/tree/dev

**Comment by Rokvach** [comment]
Working correctly. Closing.
