### ISSUE TITLE
Crash after the update

### ISSUE THREAD

**Issue by Fr4Ckt3r** [Regalis11/Barotrauma#2401]
- [Not found simmilar] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Game crashes on start.

**Steps To Reproduce**
1. Update to silky smooth
2. PROFIT

**Version**
0.9.7.1
Windows 7 Maximal

**Additional information**
Barotrauma Client crash report (generated on 07.03.2020 11:51:28)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

30C54684AA148E0CE8B2F75522B1FE39

Game version 0.9.7.1 (ReleaseWindows, branch release, revision 6ec75fa2a)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Selected content packages: None
Level seed: no level loaded
Loaded submarine: None
Selected screen: None
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 6.1.7601 Service Pack 1 64 bit
    GPU name: NVIDIA GeForce GTX 1050 Ti
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1,7777778}
    GPU status: Normal

Exception: Loading was interrupted due to an error: Object reference not set to an instance of an object.
   at Barotrauma.GUI.Init(GameWindow window, IEnumerable`1 selectedContentPackages, GraphicsDevice graphicsDevice) in E:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 224
   at Barotrauma.GameMain.Load(Boolean isSeparateThread)+MoveNext() in E:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 421
   at Barotrauma.CoroutineManager.ExecuteCoroutineThread(CoroutineHandle handle) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 167 (System.Exception)
Target site: Void Update(Microsoft.Xna.Framework.GameTime)
Stack trace: 
   at Barotrauma.GameMain.Update(GameTime gameTime) in E:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 749
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 654
   at Microsoft.Xna.Framework.Game.Tick() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in E:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 42

Last debug messages:
[07.03.2020 11:51:28] Coroutine "Load" has failed
[07.03.2020 11:51:28] Coroutine "Load" has thrown an exception {Object reference not set to an instance of an object.}
   at Barotrauma.GUI.Init(GameWindow window, IEnumerable`1 selectedContentPackages, GraphicsDevice graphicsDevice) in E:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 224
   at Barotrauma.GameMain.Load(Boolean isSeparateThread)+MoveNext() in E:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 421
   at Barotrauma.CoroutineManager.ExecuteCoroutineThread(CoroutineHandle handle) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 167
[07.03.2020 11:51:28] No UI styles defined in the selected content package!
[07.03.2020 11:51:27] Attempting to open ALC device "OpenAL Soft"
[07.03.2020 11:51:27] Loaded languages: English
[07.03.2020 11:51:27] No text files available in any of the selected content packages. Attempting to find a vanilla English text file...
[07.03.2020 11:51:27] Content package 'G:\Steam\steamapps\common\Barotrauma\Data\ContentPackages\Vanilla 0.9.xml' not found.
[07.03.2020 11:51:27] Loaded languages: English
[07.03.2020 11:51:27] No text files available in any of the selected content packages. Attempting to find a vanilla English text file...
[07.03.2020 11:51:26] Logged in as 1H4Ck3Rru5 (SteamID STEAM_1:1:431581354)

**Comment by Regalis11** [comment]
It seems the game is unable to find the vanilla content package for some reason. Could you try navigating to the path G:\Steam\steamapps\common\Barotrauma\Data\ContentPackages\Vanilla 0.9.xml and seeing if that file is there?

You might also want to try righting clicking the game in your Steam library, and selecting Properties -> Local files .> Verify integrity of game files.

**Comment by Fr4Ckt3r** [comment]
> It seems the game is unable to find the vanilla content package for some reason. Could you try navigating to the path G:\Steam\steamapps\common\Barotrauma\Data\ContentPackages\Vanilla 0.9.xml and seeing if that file is there?
> 
> You might also want to try righting clicking the game in your Steam library, and selecting Properties -> Local files -> Verify integrity of game files.

I installed Beta version and it fixed.
(Sorry for errors, im not english)
