### ISSUE TITLE
[0.9.7.1] [Crash] Game always crashes after starting and loading to 68%.

### ISSUE THREAD

**Issue by bryson099** [Regalis11/Barotrauma#2415]
- I couldn't find any other reports of this problem but there were some others similar. 

**Description**
The game crashes at precisely 68% before loading in to the main menu,

**Steps To Reproduce**
It must be done after the update to 0.9.7.1
1. Press the play button
2. Watch the loading screen until it crashes at 68%

**Version**
0.9.7.1
Windows 10

**Additional information**
Here is the crash report that is generated after the crash. I've already verified my files twice, then I reinstalled the game four times (Wiped everything related to Barotrauma on the second). Still nothing has worked even after a fresh install.
 ```
Barotrauma Client crash report (generated on 09/03/2020 6:03:01 PM)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


30C54684AA148E0CE8B2F75522B1FE39


Game version 0.9.7.1 (ReleaseWindows, branch release, revision 6ec75fa2a)
Graphics mode: 1366x768 (BorderlessWindowed)
VSync ON
Selected content packages: Vanilla 0.9
Level seed: no level loaded
Loaded submarine: None
Selected screen: None
SteamManager initialized


System info:
    Operating system: Microsoft Windows NT 6.2.9200.0 64 bit
    GPU name: Intel(R) HD Graphics 520
    Display mode: {Width:1366 Height:768 Format:Color AspectRatio:1.7786459}
    GPU status: Normal


Exception: Loading was interrupted due to an error: Object reference not set to an instance of an object.
   at Barotrauma.CampaignSetupUI.UpdateLoadMenu(IEnumerable`1 saveFiles) in E:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Screens\CampaignSetupUI.cs:line 394
   at Barotrauma.CampaignSetupUI..ctor(Boolean isMultiplayer, GUIComponent newGameContainer, GUIComponent loadGameContainer, IEnumerable`1 submarines, IEnumerable`1 saveFiles) in E:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Screens\CampaignSetupUI.cs:line 217
   at Barotrauma.MainMenuScreen.CreateCampaignSetupUI() in E:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Screens\MainMenuScreen.cs:line 1075
   at Barotrauma.MainMenuScreen..ctor(GameMain game) in E:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Screens\MainMenuScreen.cs:line 346
   at Barotrauma.GameMain.Load(Boolean isSeparateThread)+MoveNext() in E:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 525
   at Barotrauma.CoroutineManager.ExecuteCoroutineThread(CoroutineHandle handle) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 167 (System.Exception)
Target site: Void Update(Microsoft.Xna.Framework.GameTime)
Stack trace: 
   at Barotrauma.GameMain.Update(GameTime gameTime) in E:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 749
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in E:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 42


Last debug messages:
[09/03/2020 6:03:01 PM] Coroutine "Load" has failed
[09/03/2020 6:03:01 PM] Coroutine "Load" has thrown an exception {Object reference not set to an instance of an object.}
   at Barotrauma.CampaignSetupUI.UpdateLoadMenu(IEnumerable`1 saveFiles) in E:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Screens\CampaignSetupUI.cs:line 394
   at Barotrauma.CampaignSetupUI..ctor(Boolean isMultiplayer, GUIComponent newGameContainer, GUIComponent loadGameContainer, IEnumerable`1 submarines, IEnumerable`1 saveFiles) in E:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Screens\CampaignSetupUI.cs:line 217
   at Barotrauma.MainMenuScreen.CreateCampaignSetupUI() in E:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Screens\MainMenuScreen.cs:line 1075
   at Barotrauma.MainMenuScreen..ctor(GameMain game) in E:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Screens\MainMenuScreen.cs:line 346
   at Barotrauma.GameMain.Load(Boolean isSeparateThread)+MoveNext() in E:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 525
   at Barotrauma.CoroutineManager.ExecuteCoroutineThread(CoroutineHandle handle) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 167
[09/03/2020 6:03:01 PM] Error decompressing C:\Users\Bryson\AppData\Local\Daedalic Entertainment GmbH\Barotrauma\Campaign SP.save {The archive entry was compressed using an unsupported compression method.}
   at System.IO.Compression.Inflater.Inflate(FlushCode flushCode)
   at System.IO.Compression.Inflater.ReadInflateOutput(Byte* bufPtr, Int32 length, FlushCode flushCode, Int32& bytesRead)
   at System.IO.Compression.Inflater.ReadOutput(Byte* bufPtr, Int32 length, Int32& bytesRead)
   at System.IO.Compression.Inflater.InflateVerified(Byte* bufPtr, Int32 length)
   at System.IO.Compression.DeflateStream.ReadCore(Span`1 buffer)
   at System.IO.Compression.DeflateStream.Read(Byte[] array, Int32 offset, Int32 count)
   at System.IO.Compression.GZipStream.Read(Byte[] array, Int32 offset, Int32 count)
   at Barotrauma.SaveUtil.DecompressFile(String sDir, GZipStream zipStream, ProgressDelegate progress) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Utils\SaveUtil.cs:line 324
   at Barotrauma.SaveUtil.DecompressToDirectory(String sCompressedFile, String sDir, ProgressDelegate progress) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Utils\SaveUtil.cs:line 389
   at Barotrauma.SaveUtil.LoadGameSessionDoc(String filePath) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Utils\SaveUtil.cs:line 144
[09/03/2020 6:02:51 PM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[09/03/2020 6:02:50 PM] Content package load order: Vanilla 0.9
[09/03/2020 6:02:48 PM] Attempting to open ALC device "OpenAL Soft"
[09/03/2020 6:02:47 PM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[09/03/2020 6:02:47 PM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[09/03/2020 6:02:44 PM] Logged in as bryson099 (SteamID STEAM_1:1:85727109)
```

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/502897d979a13498170026838c54bc5f1950fb3d (private repo)

**Comment by Regalis11** [comment]
This seems to happen when there's a corrupted save file in the save folder (in this case the one called "Campaign SP.save"). Until we release the next patch, you should be able to work around the issue by navigating to "C:\Users\[username]\AppData\Local\Daedalic Entertainment GmbH\Barotrauma\", and deleting the file "Campaign SP.save".

**Comment by bryson099** [comment]
Thanks for the response! After deleting the corrupted save files the game works fine and manages to get to the main menu.
