### ISSUE TITLE
E_OUTOFMEMORY exception during loading

### ISSUE THREAD

**Issue by JackFodao** [Regalis11/Barotrauma#2435]
Barotrauma Client crash report (generated on 14/03/2020 10:03:53)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

30C54684AA148E0CE8B2F75522B1FE39

Game version 0.9.7.1 (ReleaseWindows, branch release, revision 6ec75fa2a)
Graphics mode: 1280x1024 (BorderlessWindowed)
VSync ON
Selected content packages: Vanilla 0.9
Level seed: no level loaded
Loaded submarine: None
Selected screen: None

System info:
    Operating system: Microsoft Windows NT 6.2.9200.0 64 bit
    GPU name: Intel(R) G33/G31 Express Chipset Family (Microsoft Corporation - WDDM 1.0)
    Display mode: {Width:1440 Height:900 Format:Color AspectRatio:1,6}
    GPU status: Normal

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void Draw(Microsoft.Xna.Framework.Graphics.SpriteBatch, Microsoft.Xna.Framework.Graphics.GraphicsDevice, Single)
Stack trace: 
   at Barotrauma.LoadingScreen.Draw(SpriteBatch spriteBatch, GraphicsDevice graphics, Single deltaTime) in E:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GUI\LoadingScreen.cs:line 148
   at Barotrauma.GameMain.Draw(GameTime gameTime) in E:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 942
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime) in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 666
   at Microsoft.Xna.Framework.Game.Tick() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 508
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in E:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 41

Last debug messages:
[14/03/2020 10:03:41] Attempting to open ALC device "OpenAL Soft"
[14/03/2020 10:03:40] Loading texture "Content/UI/LoadingScreenOverlay.png" failed! {HRESULT: [0x8007000E], Module: [General], ApiCode: [E_OUTOFMEMORY/Out of memory], Message: Espaço insuficiente de armazenamento para concluir a operação.
}
   at SharpDX.Result.CheckError()
   at SharpDX.Direct3D11.Device.CreateTexture2D(Texture2DDescription& descRef, DataBox[] initialDataRef, Texture2D texture2DOut)
   at SharpDX.Direct3D11.Texture2D..ctor(Device device, Texture2DDescription description)
   at Microsoft.Xna.Framework.Graphics.Texture2D.CreateTexture() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\Texture2D.DirectX.cs:line 412
   at Microsoft.Xna.Framework.Graphics.Texture.GetTexture() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\Texture.DirectX.cs:line 33
   at Microsoft.Xna.Framework.Graphics.Texture2D.PlatformSetData[T](Int32 level, T[] data, Int32 startIndex, Int32 elementCount) in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\Texture2D.DirectX.cs:line 76
   at Microsoft.Xna.Framework.Graphics.Texture2D.SetData[T](T[] data) in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\Texture2D.cs:line 205
   at Barotrauma.TextureLoader.<>c__DisplayClass6_0.<FromStream>b__0() in E:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Utils\TextureLoader.cs:line 68
   at Barotrauma.CrossThread.RequestExecutionOnMainThread(TaskDelegate deleg) in E:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Utils\CrossThread.cs:line 61
   at Barotrauma.TextureLoader.FromStream(Stream fileStream, String path, Boolean mipmap) in E:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Utils\TextureLoader.cs:line 69
   at Barotrauma.TextureLoader.FromFile(String path, Boolean mipmap) in E:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Utils\TextureLoader.cs:line 44
[14/03/2020 10:03:39] Loading texture "Content/Map/LocationPortraits/AlienRuins.png" failed! {HRESULT: [0x8007000E], Module: [General], ApiCode: [E_OUTOFMEMORY/Out of memory], Message: Espaço insuficiente de armazenamento para concluir a operação.
}
   at SharpDX.Result.CheckError()
   at SharpDX.Direct3D11.Device.CreateTexture2D(Texture2DDescription& descRef, DataBox[] initialDataRef, Texture2D texture2DOut)
   at SharpDX.Direct3D11.Texture2D..ctor(Device device, Texture2DDescription description)
   at Microsoft.Xna.Framework.Graphics.Texture2D.CreateTexture() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\Texture2D.DirectX.cs:line 412
   at Microsoft.Xna.Framework.Graphics.Texture.GetTexture() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\Texture.DirectX.cs:line 33
   at Microsoft.Xna.Framework.Graphics.Texture2D.PlatformSetData[T](Int32 level, T[] data, Int32 startIndex, Int32 elementCount) in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\Texture2D.DirectX.cs:line 76
   at Microsoft.Xna.Framework.Graphics.Texture2D.SetData[T](T[] data) in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\Texture2D.cs:line 205
   at Barotrauma.TextureLoader.<>c__DisplayClass6_0.<FromStream>b__0() in E:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Utils\TextureLoader.cs:line 68
   at Barotrauma.CrossThread.RequestExecutionOnMainThread(TaskDelegate deleg) in E:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Utils\CrossThread.cs:line 61
   at Barotrauma.TextureLoader.FromStream(Stream fileStream, String path, Boolean mipmap) in E:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Utils\TextureLoader.cs:line 69
   at Barotrauma.TextureLoader.FromFile(String path, Boolean mipmap) in E:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Utils\TextureLoader.cs:line 44
[14/03/2020 10:03:36] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[14/03/2020 10:03:35] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean

**Comment by EdusFF** [comment]
If the provided hardware data is correct, the GPU is an integrated one from 2007. It has a maximum allocated RAM of 256mb which is unfortunately not enough after our graphical updates. Should update Steam requirements to reflect that

**Comment by Regalis11** [comment]
Hardware requirements have been updated on Steam. I think we can close this.
