### ISSUE TITLE
[0.9.7.1] Random client crashes in multiplayer (Probably caused by in-game voice chat)

### ISSUE THREAD

**Issue by Thanaen** [Regalis11/Barotrauma#2533]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When playing in multiplayer, client randomly closes without explanation.

**Steps To Reproduce**
No precise steps. Host a server, and have friends connect to it, and at some points a client might crash.

**Version**
Game version: 0.9.7.1
Windows version: 
- Windows 10 Family 1903 (18362.720)
- Windows 10 Family 1809 (17763.1098)
- Windows 10 Professional 1909 (18363.720)

**Additional information**

We aren't using any mod at all.
We are using the in-game voice chat.
Server logs simply indicate that the player has timed out.
I haven't found any client logs, except on the Windows Event Viewer (see attached files)

According to the log, it is [this specific line](https://github.com/Regalis11/Barotrauma/blob/3e99a49383aad941a29a86e51e022b115b09537f/Libraries/Concentus/CSharp/Concentus/Opus/Structs/OpusPacketInfo.cs#L241) that crashes the game

The error we're getting appears in the event files attached, but in case you can't open them, here is the exception that was generated: 

`
Application: Barotrauma.exe
CoreCLR Version: 4.700.19.46205
.NET Core Version: 3.0.0
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Concentus.Structs.OpusPacketInfo.GetEncoderMode(Byte[] packet, Int32 packet_offset) in E:\Barotrauma-development\Libraries\Concentus\CSharp\Concentus\Opus\Structs\OpusPacketInfo.cs:line 241
   at Concentus.Structs.OpusDecoder.opus_decode_native(Byte[] data, Int32 data_ptr, Int32 len, Int16[] pcm_out, Int32 pcm_out_ptr, Int32 frame_size, Int32 decode_fec, Int32 self_delimited, Int32& packet_offset, Int32 soft_clip) in E:\Barotrauma-development\Libraries\Concentus\CSharp\Concentus\Opus\Structs\OpusDecoder.cs:line 711
   at Concentus.Structs.OpusDecoder.Decode(Byte[] in_data, Int32 in_data_offset, Int32 len, Int16[] out_pcm, Int32 out_pcm_offset, Int32 frame_size, Boolean decode_fec) in E:\Barotrauma-development\Libraries\Concentus\CSharp\Concentus\Opus\Structs\OpusDecoder.cs:line 759
   at Barotrauma.Sounds.VoipSound.FillStreamBuffer(Int32 samplePos, Int16[] buffer) in E:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Sounds\VoipSound.cs:line 151
   at Barotrauma.Sounds.SoundChannel.UpdateStream() in E:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Sounds\SoundChannel.cs:line 647
   at Barotrauma.Sounds.SoundManager.UpdateStreaming() in E:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Sounds\SoundManager.cs:line 661
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
`

Sadly,  we haven't found a typical scenario that creates this exception. It appears to be a bit random.

Attached files:

[Win10-1903-event.zip](https://github.com/Regalis11/Barotrauma/files/4399326/Win10-1903-event.zip)
[Win10-1909-event.zip](https://github.com/Regalis11/Barotrauma/files/4399327/Win10-1909-event.zip)
[Win10-1809-event.zip](https://github.com/Regalis11/Barotrauma/files/4399328/Win10-1809-event.zip)

**Comment by Regalis11** [comment]
Had this occur during our recording session. It happened the moment people started leaving the server, so I guess it could be related to people disconnecting while voip is on.
![wehr67](https://user-images.githubusercontent.com/14351070/79490794-1c4ad400-8026-11ea-8fe6-7a7f40d7b249.png)

**Comment by Thanaen** [comment]
For your information, in our cases the crash occurred while we were in the game (not in the menus).
We haven't found a common factor between all our crashes, sadly. (excepted the fact that VOIP was turned on, of course.)

**Comment by juanjp600** [comment]
Potentially fixed in https://github.com/Regalis11/Barotrauma-development/commit/be51751a70d1faea5445a0c71fdfed3dcdd29ce4

**Comment by Thanaen** [comment]
A friend had the console showing with this error while playing on the 9.9.0 version:
https://imgur.com/fkNKZew

But note that he didn't crash.

**Comment by juanjp600** [comment]
Fix doesn't appear to have made it into master yet

**Comment by Rokvach** [comment]
This issue hasn't come up within the Unstable testing, we can re-open if this shows up again. Closing.
