### ISSUE TITLE
Crash on "Fire at Will" command

### ISSUE THREAD

**Issue by fdobrotv** [Regalis11/Barotrauma#2620]
**Description**
Error popup 
![Error message](https://i.imgur.com/F48OUPf.png)

**Steps To Reproduce**
Started a new campaign first time, got a little submarine, then selected mission for an artifact retrieval, and ordered to "fire at will"

**Version**
0.9.8.0 on Windows

**Additional information**
```Barotrauma Client crash report (generated on 12.04.2020 12:42:05)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


5F2265FBBD6C5E538A99B1A8D98CAEB7


Game version 0.9.8.0 (ReleaseWindows, branch release, revision c227d35b6)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Selected content packages: Vanilla 0.9
Level seed: Tormsdale LineaBinnsmouth
Loaded submarine: Selkie (EED784E41628C2D52EBD31C700429E70)
Selected screen: Barotrauma.GameScreen
SteamManager initialized


System info:
    Operating system: Microsoft Windows NT 10.0.17134.0 64 bit
    GPU name: NVIDIA GeForce GTX 1070
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1,7777778}
    GPU status: Normal


Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Boolean IsOperatedByAnother(Barotrauma.Character, Barotrauma.Items.Components.ItemComponent, Barotrauma.Character ByRef)
Stack trace: 
   at Barotrauma.AIObjectiveOperateItem.IsOperatedByAnother(Character character, ItemComponent target, Character& operatingCharacter) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\Objectives\AIObjectiveOperateItem.cs:line 85
   at Barotrauma.CrewManager.GetBestCharacterForOrder(Order order) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GameSession\CrewManager.cs:line 2292
   at Barotrauma.CrewManager.<CreateOrderOptionNode>b__129_0(GUIButton _, Object userData) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GameSession\CrewManager.cs:line 1982
   at Barotrauma.GUIButton.Update(Single deltaTime) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIButton.cs:line 234
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Barotrauma.GUI.Update(Single deltaTime) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1005
   at Barotrauma.GameMain.Update(GameTime gameTime) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 910
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 57


Last debug messages:
[12.04.2020 12:24:50] Content package load order: Vanilla 0.9
[12.04.2020 12:24:36] Content package load order: Vanilla 0.9
[12.04.2020 12:24:16] Do not attempt to reconnect (DisconnectReason doesn't allow reconnection).
[12.04.2020 12:24:16] Received a disconnect message (SteamAuthenticationFailed/ Steam authentication status changed: AuthTicketCanceled)
[12.04.2020 12:24:15] Content package load order: Vanilla 0.9
[12.04.2020 12:22:50] Received a disconnect message (ServerFull/)
[12.04.2020 12:22:45] Content package load order: Vanilla 0.9
[12.04.2020 12:21:46] Received a disconnect message (ServerFull/)
[12.04.2020 12:21:43] Received a disconnect message (ServerFull/)
[12.04.2020 12:21:17] Received a disconnect message (ServerFull/)
[12.04.2020 12:21:03] Received a disconnect message (ServerFull/)
[12.04.2020 12:19:40] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[12.04.2020 12:19:39] Content package load order: Vanilla 0.9
[12.04.2020 12:19:38] Attempting to open ALC device "OpenAL Soft"
[12.04.2020 12:19:37] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[12.04.2020 12:19:37] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[12.04.2020 12:19:36] Logged in as esp.fdobrotv (SteamID STEAM_1:1:32583896)
```

**Comment by profplum700** [comment]
I seem to have had the same crash when selecting the "Power up" command:

```Barotrauma Client crash report (generated on 12/04/2020 11:50:18)

Barotrauma seems to have crashed. Sorry for the inconvenience! 


5F2265FBBD6C5E538A99B1A8D98CAEB7


Game version 0.9.8.0 (ReleaseWindows, branch release, revision c227d35b6)
Graphics mode: 1920x1080 (Fullscreen)
VSync ON
Selected content packages: Vanilla 0.9
Level seed: TopolNew Siberia
Loaded submarine: Venture (3286F6B8608FA2B449E658E08A11A285)
Selected screen: Barotrauma.GameScreen
SteamManager initialized


System info:
    Operating system: Microsoft Windows NT 10.0.18363.0 64 bit
    GPU name: NVIDIA GeForce GTX 1060
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal


Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Boolean IsOperatedByAnother(Barotrauma.Character, Barotrauma.Items.Components.ItemComponent, Barotrauma.Character ByRef)
Stack trace: 
   at Barotrauma.AIObjectiveOperateItem.IsOperatedByAnother(Character character, ItemComponent target, Character& operatingCharacter) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\Objectives\AIObjectiveOperateItem.cs:line 85
   at Barotrauma.CrewManager.GetBestCharacterForOrder(Order order) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GameSession\CrewManager.cs:line 2292
   at Barotrauma.CrewManager.<CreateOrderOptionNode>b__129_0(GUIButton _, Object userData) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GameSession\CrewManager.cs:line 1982
   at Barotrauma.GUIButton.Update(Single deltaTime) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIButton.cs:line 234
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Barotrauma.GUI.Update(Single deltaTime) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1005
   at Barotrauma.GameMain.Update(GameTime gameTime) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 910
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 57


Last debug messages:
[12/04/2020 11:49:19] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[12/04/2020 11:49:18] Content package load order: Vanilla 0.9
[12/04/2020 11:49:16] Attempting to open ALC device "OpenAL Soft"
[12/04/2020 11:49:16] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[12/04/2020 11:49:15] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[12/04/2020 11:49:15] Logged in as Putty_pooper (SteamID STEAM_1:1:11750963)```

**Comment by Rokvach** [comment]
This issue has already been fixed for Unstable, it is caused because the shuttle doesn't have any weaponry. Closing.
