### ISSUE TITLE
Game crashes while fixing the submarine.

### ISSUE THREAD

**Issue by super9guy** [Regalis11/Barotrauma#2645]
I'm doing the quest hunting a swam of HammerHead. After kill them all, I go to the commander room to fixing the leaks and then the game crashes. 

My game used to crashed before, same situation, I go to fixing some leaks and then the game crashes. I have thought that was the mod I have installed, after remove that mod, the game works just fine without any crashes. But then today it just start crashing again. 

Here is the crash report:

--------------
Barotrauma Client crash report (generated on 4/17/2020 2:40:16 PM)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

5F2265FBBD6C5E538A99B1A8D98CAEB7

Game version 0.9.8.0 (ReleaseWindows, branch release, revision c227d35b6)
Graphics mode: 1360x768 (Fullscreen)
VSync ON
Selected content packages: Vanilla 0.9, Aphrodite, Atlas, Atolla, EK Armory, NUCLEAR U-31 MK2, Pod Pea, REALLYBIGMAP, Rorqual, Salut11, [SUB] The Grim Overlord
Level seed: MildaArid Troma
Loaded submarine: Rorqual (14455082F4D362149937D888ECE73CCC)
Selected screen: Barotrauma.GameScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.17134.0 64 bit
    GPU name: NVIDIA GeForce GTX 1070
    Display mode: {Width:1360 Height:768 Format:Color AspectRatio:1.7708334}
    GPU status: Normal

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void <Act>b__33_5()
Stack trace: 
   at Barotrauma.AIObjectiveContainItem.<Act>b__33_5() in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\Objectives\AIObjectiveContainItem.cs:line 161
   at Barotrauma.AIObjective.CheckState() in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\Objectives\AIObjective.cs:line 347
   at Barotrauma.AIObjective.CheckSubObjectives() in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\Objectives\AIObjective.cs:line 354
   at Barotrauma.AIObjective.CheckState() in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\Objectives\AIObjective.cs:line 347
   at Barotrauma.AIObjective.CheckSubObjectives() in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\Objectives\AIObjective.cs:line 354
   at Barotrauma.AIObjective.CheckState() in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\Objectives\AIObjective.cs:line 347
   at Barotrauma.AIObjective.CheckSubObjectives() in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\Objectives\AIObjective.cs:line 354
   at Barotrauma.AIObjective.CheckState() in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\Objectives\AIObjective.cs:line 347
   at Barotrauma.AIObjective.CheckSubObjectives() in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\Objectives\AIObjective.cs:line 354
   at Barotrauma.AIObjective.CheckState() in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\Objectives\AIObjective.cs:line 347
   at Barotrauma.AIObjective.CheckSubObjectives() in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\Objectives\AIObjective.cs:line 354
   at Barotrauma.AIObjective.CheckState() in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\Objectives\AIObjective.cs:line 347
   at Barotrauma.AIObjective.TryComplete(Single deltaTime) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\Objectives\AIObjective.cs:line 128
   at Barotrauma.HumanAIController.Update(Single deltaTime) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\HumanAIController.cs:line 259
   at Barotrauma.Character.UpdateAll(Single deltaTime, Camera cam) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 1980
   at Barotrauma.GameScreen.Update(Double deltaTime) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 173
   at Barotrauma.GameMain.Update(GameTime gameTime) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 882
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 57

Last debug messages:
[4/17/2020 2:23:23 PM] Overriding all background creatures with 'Mods/REALLYBIGMAP/Map/RBM_BGFish.xml'
[4/17/2020 2:04:47 PM] Overriding all ruin configuration parameters using the file Mods/REALLYBIGMAP/Map/RBM_Ruins.xml.
[4/17/2020 2:04:47 PM] Overriding all background creatures with 'Mods/REALLYBIGMAP/Map/RBM_BGFish.xml'
[4/17/2020 2:04:09 PM] Overriding all location types with 'Mods/REALLYBIGMAP/Map/RBM_LocationTypes.xml'
[4/17/2020 2:04:09 PM] Overriding all level object prefabs with 'Mods/REALLYBIGMAP/Map/RBM_LevelObjectPrefabs.xml'
[4/17/2020 2:04:05 PM] Overriding the level generation parameters with 'Mods/REALLYBIGMAP/Map/RBM_LevelGen.xml'
[4/17/2020 2:04:05 PM] Overriding the map generation parameters with 'Mods/REALLYBIGMAP/Map/RBM_MapGen.xml'
[4/17/2020 2:04:02 PM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[4/17/2020 2:04:02 PM] Content package load order: Vanilla 0.9  |  Aphrodite  |  Atlas  |  Atolla  |  EK Armory  |  NUCLEAR U-31 MK2  |  Pod Pea  |  REALLYBIGMAP  |  Rorqual  |  Salut11  |  [SUB] The Grim Overlord
[4/17/2020 2:04:01 PM] Attempting to open ALC device "OpenAL Soft"
[4/17/2020 2:04:00 PM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[4/17/2020 2:04:00 PM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[4/17/2020 2:03:59 PM] Logged in as SuperNiceGuy (SteamID STEAM_1:1:96181396)

**Comment by EdusFF** [comment]
Added a null check in https://github.com/Regalis11/Barotrauma-development/commit/eeb370221c856877eda4d763f564bcfa591c9d3e, let's see what's the effect of that

**Comment by Rokvach** [comment]
No issues, closing.
