### ISSUE TITLE
Game Crashes on Startup After New Update

### ISSUE THREAD

**Issue by Keldaris** [Regalis11/Barotrauma#2696]
Barotrauma Client crash report (generated on 4/24/2020 8:27:41 PM)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

To prevent further startup errors, installed mods will be disabled the next time you launch the game.

B88397013C2378C4A99C3E19DEBEE54F

Game version 0.9.9.0 (ReleaseWindows, branch release, revision 0534150c8)
Graphics mode: 2560x1080 (BorderlessWindowed)
VSync ON
Selected content packages: None
Level seed: no level loaded
Loaded submarine: None
Selected screen: None
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.18362.0 64 bit
    GPU name: Radeon RX 580 Series
    Display mode: {Width:2560 Height:1080 Format:Color AspectRatio:2.3703704}
    GPU status: Normal

Exception: Loading was interrupted due to an error. (Barotrauma.GameMain+LoadingException)
Target site: Void Update(Microsoft.Xna.Framework.GameTime)
Stack trace: 
   at Barotrauma.GameMain.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Microsoft.Xna.Framework.Game.Run()
   at Barotrauma.Program.Main(String[] args)

InnerException: Object reference not set to an instance of an object.
Target site: Void Init(Microsoft.Xna.Framework.GameWindow, System.Collections.Generic.IEnumerable`1[Barotrauma.ContentPackage], Microsoft.Xna.Framework.Graphics.GraphicsDevice)
Stack trace: 
   at Barotrauma.GUI.Init(GameWindow window, IEnumerable`1 selectedContentPackages, GraphicsDevice graphicsDevice)
   at Barotrauma.GameMain.Load(Boolean isSeparateThread)+MoveNext()
   at Barotrauma.CoroutineManager.ExecuteCoroutineThread(CoroutineHandle handle)
Last debug messages:
[4/24/2020 8:27:41 PM] Coroutine "Load" has failed
[4/24/2020 8:27:41 PM] Coroutine "Load" has thrown an exception {Object reference not set to an instance of an object.}
   at Barotrauma.GUI.Init(GameWindow window, IEnumerable`1 selectedContentPackages, GraphicsDevice graphicsDevice)
   at Barotrauma.GameMain.Load(Boolean isSeparateThread)+MoveNext()
   at Barotrauma.CoroutineManager.ExecuteCoroutineThread(CoroutineHandle handle)
[4/24/2020 8:27:41 PM] No UI styles defined in the selected content package!
[4/24/2020 8:27:41 PM] Attempting to open ALC device "OpenAL Soft"
[4/24/2020 8:27:40 PM] Loaded languages: English
[4/24/2020 8:27:40 PM] No text files available in any of the selected content packages. Attempting to find a vanilla English text file...
[4/24/2020 8:27:40 PM] Content package 'C:\Program Files (x86)\Steam\steamapps\common\Barotrauma\Data\ContentPackages\Vanilla 0.9.xml' not found.
[4/24/2020 8:27:40 PM] Loaded languages: English
[4/24/2020 8:27:40 PM] No text files available in any of the selected content packages. Attempting to find a vanilla English text file...
[4/24/2020 8:27:40 PM] Logged in as Adam (SteamID STEAM_1:0:17107694)

**Comment by N0zza** [comment]
I have the same problem.

Game version 0.9.9.0 (ReleaseWindows, branch release, revision 0534150c8)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Selected content packages: None
Level seed: no level loaded
Loaded submarine: None
Selected screen: None
SteamManager initialized


System info:
    Operating system: Microsoft Windows NT 10.0.18362.0 64 bit
    GPU name: NVIDIA GeForce GTX 1070
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal


Exception: Loading was interrupted due to an error. (Barotrauma.GameMain+LoadingException)
Target site: Void Update(Microsoft.Xna.Framework.GameTime)
Stack trace: 
   at Barotrauma.GameMain.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Microsoft.Xna.Framework.Game.Run()
   at Barotrauma.Program.Main(String[] args)


InnerException: Object reference not set to an instance of an object.
Target site: Void Init(Microsoft.Xna.Framework.GameWindow, System.Collections.Generic.IEnumerable`1[Barotrauma.ContentPackage], Microsoft.Xna.Framework.Graphics.GraphicsDevice)
Stack trace: 
   at Barotrauma.GUI.Init(GameWindow window, IEnumerable`1 selectedContentPackages, GraphicsDevice graphicsDevice)
   at Barotrauma.GameMain.Load(Boolean isSeparateThread)+MoveNext()
   at Barotrauma.CoroutineManager.ExecuteCoroutineThread(CoroutineHandle handle)
Last debug messages:
[25/04/2020 4:44:51 PM] Coroutine "Load" has failed
[25/04/2020 4:44:51 PM] Coroutine "Load" has thrown an exception {Object reference not set to an instance of an object.}
   at Barotrauma.GUI.Init(GameWindow window, IEnumerable`1 selectedContentPackages, GraphicsDevice graphicsDevice)
   at Barotrauma.GameMain.Load(Boolean isSeparateThread)+MoveNext()
   at Barotrauma.CoroutineManager.ExecuteCoroutineThread(CoroutineHandle handle)
[25/04/2020 4:44:51 PM] No UI styles defined in the selected content package!
[25/04/2020 4:44:51 PM] Attempting to open ALC device "OpenAL Soft"
[25/04/2020 4:44:50 PM] Loaded languages: English
[25/04/2020 4:44:50 PM] No text files available in any of the selected content packages. Attempting to find a vanilla English text file...
[25/04/2020 4:44:50 PM] Content package 'E:\Games\Steam\steamapps\common\Barotrauma\Data\ContentPackages\Vanilla 0.9.xml' not found.
[25/04/2020 4:44:50 PM] Loaded languages: English
[25/04/2020 4:44:50 PM] No text files available in any of the selected content packages. Attempting to find a vanilla English text file...
[25/04/2020 4:44:50 PM] Logged in as N0zza (SteamID STEAM_1:1:106006145)

**Comment by Regalis11** [comment]
It seems you're missing the vanilla content package (Barotrauma\Data\ContentPackages\Vanilla 0.9.xml) for some reason. You should be able to fix this by right-clicking the game in your Steam library, going to Properties -> Local files and clicking "verify integrity of game files".
