### ISSUE TITLE
"Level equality check failed" error when starting a round

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#2723]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Players sometimes get disconnected with a "level equality check failed" error message in the campaign. What this means is that the same seed produced a different kind of a level client-side than server side. 

Even though the level generation algorithm and the RNG should be deterministic and produce the exact same level, floating point inaccuracies can in very rare cases cause the levels to differ (example of that happening here: #848). There may also be other causes for the issue.

**Steps To Reproduce**
No reliable steps to reproduce.

**Version**
Any

**Additional information**
A "proper" way to fix this would be not to use floating point math in the level generation, but considering how rare this issue is and how huge changes switching to fixed point or integer math would require, I think we might want to instead go with a simpler solution. We could for example choose a different seed when this occurs (with some restrictions to prevent clients from abusing the system by always reporting that they got the error).

**Comment by Obrazets** [comment]
Its every time when we end mission without sub's shuttle. We drop it in the middle of round.

**Comment by Obrazets** [comment]
@Regalis11  plz fix this honorable man

**Comment by a7emenov** [comment]
Have the same issue as @Obrazets, arriving to a station without a shuttle ruined my online campaign save. Would love to see this fixed.

**Comment by Krisscut** [comment]
Hi !

In a campaign playthrough with 7 people on the current stable, we got this error message a lot.
Not sure if this is related but for the first time we tried to use the awesome vengeance mk3n and we never got the errors before with less complex and tinier submarine
https://steamcommunity.com/sharedfiles/filedetails/?id=2121725686

**Comment by Krisscut** [comment]
I have attached a save , not sure if it's enough but when i load it as the host i have this error 
![Barotrauma_2020-11-11_21-24-24](https://user-images.githubusercontent.com/8125922/98860643-49e4e800-2464-11eb-852c-4a1fe91c54e8.png)
[Multiplayer.zip](https://github.com/Regalis11/Barotrauma/files/5526567/Multiplayer.zip)

**Comment by nanohard** [comment]
On Linux, using Proton.
I get the same error when I try to host any game mode and then I select an area to go to on the map.

**Comment by JoneKone** [comment]
Tried to join a random campaign, after first join, and spawn while docket to the station. Everything worked fine. It was only after the host selected a new destination and we continued the server/save got scrambled. Most ppl couldn't join the new game and the server host went to lobby, and we re downloaded the game, I got the usual "please wait" loading screen and the game was going (no errors), then the server re hosted the game I joined and re downloaded the save and boom quality check fails.
![Screenshot from 2021-07-06 12-49-41](https://user-images.githubusercontent.com/1114115/124583132-61da0380-de5b-11eb-9892-cb13d6c2c808.png)
![Screenshot from 2021-07-06 12-44-48](https://user-images.githubusercontent.com/1114115/124583140-630b3080-de5b-11eb-9c2f-bf96828e6995.png)

**Comment by zogar1993** [comment]
It does not necessarily have to do with shuttles, we had none and still had the issue.
For us it started after one player was afk for a while and got disconnected for inactivity (he lost his progress when he rejoined). From then on, this error occurs for all players except the host whenever we change from one scenario to another (outpost to mission and vice versa). Every time this happens we need to go back to the lobby, everybody joins, and then we can continue playing until next loading screen, which lets us move forward, but is pretty tiresome. Restarting the game does not solve this, but the problem does not seem to affect new games that we begin from scratch.

**Comment by mswork** [comment]
The same problem

**Comment by sakego** [comment]
Any update on this? I like to play this game but the level equality check when entering and leaving stations is a real drag. Each time at least 1 of the players is dropped randomly. Server is on Linux and all Windows clients are integrity checked for game files - this still happens. 
This bug is very bad and causes us to have to go to lobby to get the dropped players back into game each time it happens. 
Would love for this to be fixed, so it will allow us to not have to break the flow of game play for long sessions.
Let me know if you want any logs from our side to assist. Thanks.

**Comment by sakego** [comment]
Update on this on my end. After doing a recent file integrity check on all PCs playing this issue was resolved for me. Wish Steam would tell me what files were changes so I can post them here. Anyone know how to find that out?

**Comment by Krzeszny** [comment]
I lost internet for half a minute and now when I try to join the same game, it won't let me. I tried twice.
![Barotrauma_MrlcBU129d](https://user-images.githubusercontent.com/10529134/139558150-3cbd5f4e-788e-4d37-a016-cbddb9811877.png)

**Comment by SylvaraWasTaken** [comment]
Same error. Happens any time i try to join a specific lobby, but does not seem reproducible in my experience, and does not consistently happen on other lobbies.

```
There was an error initializing the round. {Mission equality check failed. Mission count doesn't match the server (server: 0, client: 1)}
   at Barotrauma.Networking.GameClient.ReadStartGameFinalize(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 973
   at Barotrauma.Networking.GameClient.StartGame(IReadMessage inc)+MoveNext() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 1653
   Error
Coroutine "Barotrauma.Networking.GameClient+<StartGame>d__93" has failed
```

**Comment by rikusen0335** [comment]
It also happened to me. Connect to the specific server and then try to join as spectator, will occur this problem
![image](https://user-images.githubusercontent.com/19174234/142998502-60cac988-1572-44d1-a8e7-8713fa0e6fbc.png)

**Comment by Krzeszny** [comment]
![Barotrauma_IU3lpt9DUa](https://user-images.githubusercontent.com/10529134/145123525-b2eed26c-955b-4c6f-ae1d-93e39c0ca3ed.png)
It happened again

**Comment by Krzeszny** [comment]
![Barotrauma_yXXSmLw49i](https://user-images.githubusercontent.com/10529134/163731603-61875b9b-c63d-435e-a4dd-6a840b8a8cb5.png)
I keep getting this error 80% of the time

**Comment by Krzeszny** [comment]
5 times in a row
```
There was an error initializing the round. {Level equality check failed. The level generated at your end doesn't match the level generated by the server (client value #2: 1555020780, server value #2: 2FF8ACB3, level value count: 13, seed: Pelorus LineaRathmore Chaos, sub: DD-X Kusrab (5CEA355), mirrored: False).}
   at Barotrauma.Networking.GameClient.ReadStartGameFinalize(IReadMessage inc)
   at Barotrauma.Networking.GameClient.StartGame(IReadMessage inc)+MoveNext()
```

**Comment by Krzeszny** [comment]
Same server, same problem today as yesterday
```
There was an error initializing the round. {Level equality check failed. The level generated at your end doesn't match the level generated by the server (client value #2: 863010794, server value #2: 47CF8496, level value count: 13, seed: AnaAsterius Linea, sub: DD-X Kusrab (5887AF7), mirrored: False).}
   at Barotrauma.Networking.GameClient.ReadStartGameFinalize(IReadMessage inc)
   at Barotrauma.Networking.GameClient.StartGame(IReadMessage inc)+MoveNext()
```

**Comment by JoneKone** [comment]
There was an error initializing the round. {Level equality check failed. The level generated at your end doesn't match the level generated by the server (client value #12: 1433535912, server value #12: 45AECD12, level value count: 13, seed: ZDlrz82z, sub: Lympha (Mission) (64C78FE), mirrored: False).}
   at Barotrauma.Networking.GameClient.ReadStartGameFinalize(IReadMessage inc) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Networking/GameClient.cs:line 975
   at Barotrauma.Networking.GameClient.StartGame(IReadMessage inc)+MoveNext() in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Networking/GameClient.cs:line 1739

Coroutine "Barotrauma.Networking.GameClient+<StartGame>d__97" has failed

Just tried to join The Happy Traitor server, and got this bad boy. Mission server.
![20220609102223_1](https://user-images.githubusercontent.com/1114115/172789559-1d41ec9a-048a-4924-9435-4cbe1aeb7973.jpg)

**Comment by Krzeszny** [comment]
```
Error while reading a message from server. 
Mission equality check failed. Mission count doesn't match the server. Server: abandonedoutpostmudraptor, client: , game session: abandonedoutpostmudraptor)
   at Barotrauma.Networking.GameClient.ReadStartGameFinalize(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 891
   at Barotrauma.Networking.GameClient.ReadDataMessage(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 742
   at Barotrauma.Networking.SteamP2PClientPeer.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\Primitives\Peers\SteamP2PClientPeer.cs:line 260
   at Barotrauma.Networking.GameClient.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 500
```

**Comment by DarkDestiny21** [comment]
It so fucking annoying that I kept getting this error when I'm trying to join my friend server.

**Comment by kanoriano** [comment]
![image](https://user-images.githubusercontent.com/39070007/212398142-5b971466-4ed8-4799-b604-7a5693fa929c.png)

**Comment by Krzeszny** [comment]
```
There was an error initializing the round. {Level equality check failed. The level generated at your end doesn't match the level generated by the server (client value AbyssGen: 398F67B4, server value AbyssGen: 10701579, level value count: 17, seed: SermilikOnga Linea, sub: Super Plague Rat SONAR 1.0.9 (BAEB796), mirrored: False).}
   at Barotrauma.Networking.GameClient.ReadStartGameFinalize(IReadMessage inc)
   at Barotrauma.Networking.GameClient.StartGame(IReadMessage inc)+MoveNext()
```

**Comment by Krzeszny** [comment]
Today: same, but mission instead of level
```
There was an error initializing the round. {Mission equality check failed. Mission count doesn't match the server. Server: salvagewreck1, salvageartifactcave, killclowns, client: salvagewreck1, salvageartifactcave, game session: salvagewreck1, salvageartifactcave)}
   at Barotrauma.Networking.GameClient.ReadStartGameFinalize(IReadMessage inc)
   at Barotrauma.Networking.GameClient.StartGame(IReadMessage inc)+MoveNext()
```

**Comment by Krzeszny** [comment]
```
Error while reading a message from server. 
Level equality check failed. The level generated at your end doesn't match the level generated by the server (client value AbyssGen: 20E075E2, server value AbyssGen: 12980E32, level value count: 17, seed: Staldon LineaDank, sub: Barsuk (C542C22), mirrored: True).
   at Barotrauma.Networking.GameClient.ReadStartGameFinalize(IReadMessage inc)
   at Barotrauma.Networking.GameClient.ReadDataMessage(IReadMessage inc)
   at Barotrauma.Networking.SteamP2PClientPeer.Update(Single deltaTime)
   at Barotrauma.Networking.GameClient.Update(Single deltaTime)
``

**Comment by Regalis11** [comment]
Found one issue that can cause these types of errors, let's see if that gets rid of (or at least reduces) these after we've merged it: https://github.com/Regalis11/Barotrauma-development/pull/4009

**Comment by Krzeszny** [comment]
```
Error while reading a message from server. 
Mission equality check failed. Mission count doesn't match the server. Server: badvibrationsartifactruins, quartzcollectioncoalition, client: badvibrationsartifactruins, game session: badvibrationsartifactruins)
   at Barotrauma.Networking.GameClient.ReadStartGameFinalize(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 891
   at Barotrauma.Networking.GameClient.ReadDataMessage(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 742
   at Barotrauma.Networking.SteamP2PClientPeer.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\Primitives\Peers\SteamP2PClientPeer.cs:line 260
   at Barotrauma.Networking.GameClient.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 500
```

**Comment by Ksarper** [comment]
![image](https://user-images.githubusercontent.com/48825686/228323833-997538a9-f391-4c79-8a2f-9bb341714f09.png)

**Comment by Krzeszny** [comment]
```
Error while reading a message from server. 
Level equality check failed. The level generated at your end doesn't match the level generated by the server (client value AbyssGen: 24199A4B, server value AbyssGen: 13FD7355, level value count: 17, seed: Thorarinn455, sub: Porpoise (ED1FE0F), mirrored: False). Round init status: WaitingForStartGameFinalize. Round start save ID: 6, last save id: 6, pending save id: 6.
   at Barotrauma.Networking.GameClient.ReadStartGameFinalize(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 942
   at Barotrauma.Networking.GameClient.ReadDataMessage(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 750
   at Barotrauma.Networking.SteamP2PClientPeer.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\Primitives\Peers\SteamP2PClientPeer.cs:line 277
   at Barotrauma.Networking.GameClient.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 505
```

**Comment by Krzeszny** [comment]
```
Error while reading a message from server. 
Level equality check failed. The level generated at your end doesn't match the level generated by the server (client value AbyssGen: 312F3500, server value AbyssGen: 32F542CB, level value count: 17, seed: Echion Linea150, sub: Apo-4A Saber (C295CFA), mirrored: False). Round init status: WaitingForStartGameFinalize. Round start save ID: 7, last save id: 7, pending save id: 7.
   at Barotrauma.Networking.GameClient.ReadStartGameFinalize(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 942
   at Barotrauma.Networking.GameClient.ReadDataMessage(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 750
   at Barotrauma.Networking.SteamP2PClientPeer.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\Primitives\Peers\SteamP2PClientPeer.cs:line 277
   at Barotrauma.Networking.GameClient.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 505
```

**Comment by Morse1213** [comment]
Error while reading a message from server. 
Level equality check failed. The level generated at your end doesn't match the level generated by the server (client value AbyssGen: 1C719C82, server value AbyssGen: 2DFB0ABE, level value count: 17, seed: Ino Linea344Tara355, sub: X37-B (5483A91), mirrored: False). Round init status: WaitingForStartGameFinalize. Round start save ID: 5, last save id: 5, pending save id: 5.
   at Barotrauma.Networking.GameClient.ReadStartGameFinalize(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 940
   at Barotrauma.Networking.GameClient.ReadDataMessage(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 748
   at Barotrauma.Networking.SteamP2PClientPeer.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\Primitives\Peers\SteamP2PClientPeer.cs:line 277
   at Barotrauma.Networking.GameClient.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 505
   
   Happens any time i try to join a game with more than a few mods.

**Comment by Krzeszny** [comment]
Error while reading a message from server. 
Level equality check failed. The level generated at your end doesn't match the level generated by the server (client value TunnelGen2: 2E485EA7, server value TunnelGen2: 47EBC50C, level value count: 19, seed: Yasa144Sparti Linea134, sub: Explorer II (E0A2E8D), mirrored: False). Round init status: WaitingForStartGameFinalize. Round start save ID: 4, last save id: 4, pending save id: 4.
   at Barotrauma.Networking.GameClient.ReadStartGameFinalize(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 944
   at Barotrauma.Networking.GameClient.ReadDataMessage(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 749
   at Barotrauma.Networking.SteamP2PClientPeer.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\Primitives\Peers\SteamP2PClientPeer.cs:line 277
   at Barotrauma.Networking.GameClient.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 504

I was just joining a server with many mods

**Comment by Regalis11** [comment]
Thank you for the reports! I'm afraid we might not be able to diagnose the issue without knowing which mods it occurs with. If you could provide a mod list (and perhaps even the save too), it'd help us a lot in diagnosing this. Thanks and sorry for the inconvenience!

**Comment by gosver** [comment]
![Screenshot_1](https://github.com/Regalis11/Barotrauma/assets/31957860/3257aebb-59f1-4bee-968a-6d514605b1b6)

**Comment by gosver** [comment]
> Thank you for the reports! I'm afraid we might not be able to diagnose the issue without knowing which mods it occurs with. If you could provide a mod list (and perhaps even the save too), it'd help us a lot in diagnosing this. Thanks and sorry for the inconvenience!

I have level equality problem on windows 10, mods of server
![Screenshot_1](https://github.com/Regalis11/Barotrauma/assets/31957860/9a10ac8e-92ff-417c-bc3f-4dd7f27f480d)

**Comment by Regalis11** [comment]
Closing as outdated. This is a fairly "generic" error that can be caused by a variety of things, and many of the cases that caused this error have been fixed since the report was made (and newer reports are most likely caused by different things despite the same error message).
