### ISSUE TITLE
[0.8.0.1]server crash report

### ISSUE THREAD

**Issue by Mauregato783** [Regalis11/Barotrauma#278]
Barotrauma Client crash report (generated on 2018-02-22 11:41:01 PM)

Barotrauma seems to have crashed. Sorry for the inconvenience! 
If you'd like to help fix the bug that caused the crash, please send this file to the developers on the Undertow Games forums.

Game version 0.8.0.1
Graphics mode: 1280x720 (BorderlessWindowed)
Selected content package: Vanilla 0.8
Level seed: ug5zbGqz
Loaded submarine: Vellamo (987338BD3DF6F1C4518E81E879FB40FF)
Selected screen: Barotrauma.GameScreen
Server (Round had started)

System info:
    Operating system: Microsoft Windows NT 6.2.9200.0 64 bit
    GPU name: Intel(R) HD Graphics
    Display mode: {Width:1680 Height:1050 Format:Color AspectRatio:1.6}
    GPU status: Normal

Exception: Object reference not set to an instance of an object.
Target site: Void Draw(Microsoft.Xna.Framework.Graphics.SpriteBatch)
Stack trace: 
   at Barotrauma.Ragdoll.Draw(SpriteBatch spriteBatch) in E:\Barotrauma\Barotrauma\BarotraumaClient\Source\Characters\Animation\Ragdoll.cs:line 76
   at Barotrauma.GameScreen.DrawMap(GraphicsDevice graphics, SpriteBatch spriteBatch) in E:\Barotrauma\Barotrauma\BarotraumaClient\Source\Screens\GameScreen.cs:line 156
   at Barotrauma.GameScreen.Draw(Double deltaTime, GraphicsDevice graphics, SpriteBatch spriteBatch) in E:\Barotrauma\Barotrauma\BarotraumaClient\Source\Screens\GameScreen.cs:line 68
   at Barotrauma.GameMain.Draw(GameTime gameTime) in E:\Barotrauma\Barotrauma\BarotraumaClient\Source\GameMain.cs:line 449
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at MonoGame.Framework.WinFormsGameWindow.RunLoop()
   at MonoGame.Framework.WinFormsGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Barotrauma.Program.Main() in E:\Barotrauma\Barotrauma\BarotraumaClient\Source\Program.cs:line 41

Last debug messages:
   2018-02-22 11:39:20 PM - WRITING CHARACTER DATA: {GW}Assasin
   2018-02-22 11:39:20 PM - WRITING CHARACTER DATA: {GW}Assasin
   2018-02-22 11:39:20 PM - WRITING CHARACTER DATA: {GW}Assasin
   2018-02-22 11:39:20 PM - WRITING CHARACTER DATA: {GW}Assasin
   2018-02-22 11:39:20 PM - WRITING CHARACTER DATA: {GW}Assasin
   2018-02-22 11:39:20 PM - WRITING CHARACTER DATA: {GW}Assasin
   2018-02-22 11:39:20 PM - WRITING CHARACTER DATA: {GW}Assasin
   2018-02-22 11:39:20 PM - WRITING CHARACTER DATA: {GW}Assasin
   2018-02-22 11:39:20 PM - WRITING CHARACTER DATA: {GW}Assasin
   2018-02-22 11:39:20 PM - WRITING CHARACTER DATA: {GW}Assasin
   2018-02-22 11:39:20 PM - WRITING CHARACTER DATA: {GW}Assasin
   2018-02-22 11:39:20 PM - WRITING CHARACTER DATA: {GW}Assasin
   2018-02-22 11:39:20 PM - WRITING CHARACTER DATA: {GW}Assasin
   2018-02-22 11:37:23 PM - Shprot (80.89.156.192) couldn't join the server (wrong game version)
   2018-02-22 11:36:42 PM - WRITING CHARACTER DATA: Jeff
   2018-02-22 11:36:42 PM - WRITING CHARACTER DATA: Jeff
   2018-02-22 11:36:42 PM - WRITING CHARACTER DATA: Jeff
   2018-02-22 11:36:42 PM - WRITING CHARACTER DATA: Jeff
   2018-02-22 11:36:42 PM - WRITING CHARACTER DATA: Jeff
   2018-02-22 11:36:42 PM - WRITING CHARACTER DATA: Jeff
   2018-02-22 11:36:42 PM - WRITING CHARACTER DATA: Jeff
   2018-02-22 11:36:42 PM - WRITING CHARACTER DATA: Jeff
   2018-02-22 11:36:42 PM - WRITING CHARACTER DATA: Jeff
   2018-02-22 11:36:42 PM - WRITING CHARACTER DATA: Jeff
   2018-02-22 11:34:58 PM - WRITING CHARACTER DATA: Scotty
   2018-02-22 11:34:58 PM - WRITING CHARACTER DATA: hi
   2018-02-22 11:34:58 PM - WRITING CHARACTER DATA: Scotty
   2018-02-22 11:34:58 PM - WRITING CHARACTER DATA: hi
   2018-02-22 11:34:57 PM - WRITING CHARACTER DATA: hi
   2018-02-22 11:34:57 PM - WRITING CHARACTER DATA: {GW}Assasin
   2018-02-22 11:34:57 PM - WRITING CHARACTER DATA: Scotty
   2018-02-22 11:34:57 PM - WRITING CHARACTER DATA: hi
   2018-02-22 11:34:57 PM - WRITING CHARACTER DATA: Scotty
   2018-02-22 11:34:57 PM - WRITING CHARACTER DATA: hi
   2018-02-22 11:34:57 PM - WRITING CHARACTER DATA: hi
   2018-02-22 11:34:57 PM - WRITING CHARACTER DATA: {GW}Assasin
   2018-02-22 11:34:57 PM - WRITING CHARACTER DATA: Scotty
   2018-02-22 11:34:57 PM - WRITING CHARACTER DATA: hi
   2018-02-22 11:34:57 PM - WRITING CHARACTER DATA: hi
   2018-02-22 11:34:57 PM - WRITING CHARACTER DATA: {GW}Assasin
   2018-02-22 11:34:57 PM - WRITING CHARACTER DATA: Scotty
   2018-02-22 11:34:57 PM - WRITING CHARACTER DATA: hi
   2018-02-22 11:34:57 PM - WRITING CHARACTER DATA: hi
   2018-02-22 11:34:57 PM - WRITING CHARACTER DATA: {GW}Assasin
   2018-02-22 11:34:57 PM - WRITING CHARACTER DATA: Scotty
   2018-02-22 11:34:57 PM - WRITING CHARACTER DATA: hi
   2018-02-22 11:34:57 PM - WRITING CHARACTER DATA: Scotty
   2018-02-22 11:34:57 PM - WRITING CHARACTER DATA: hi
   2018-02-22 11:34:57 PM - WRITING CHARACTER DATA: Scotty
   2018-02-22 11:34:57 PM - WRITING CHARACTER DATA: hi
   2018-02-22 11:34:56 PM - WRITING CHARACTER DATA: hi
   2018-02-22 11:34:56 PM - WRITING CHARACTER DATA: {GW}Assasin
   2018-02-22 11:34:56 PM - WRITING CHARACTER DATA: {GW}Assasin
   2018-02-22 11:34:56 PM - WRITING CHARACTER DATA: Macaroni
   2018-02-22 11:34:56 PM - WRITING CHARACTER DATA: hi
   2018-02-22 11:34:56 PM - WRITING CHARACTER DATA: {GW}Assasin
   2018-02-22 11:34:56 PM - WRITING CHARACTER DATA: hi
   2018-02-22 11:34:56 PM - WRITING CHARACTER DATA: {GW}Assasin
   2018-02-22 11:34:56 PM - WRITING CHARACTER DATA: hi
   2018-02-22 11:34:56 PM - WRITING CHARACTER DATA: {GW}Assasin
   2018-02-22 11:34:56 PM - WRITING CHARACTER DATA: {GW}Assasin
   2018-02-22 11:34:56 PM - WRITING CHARACTER DATA: Macaroni
   2018-02-22 11:34:56 PM - WRITING CHARACTER DATA: {GW}Assasin
   2018-02-22 11:34:56 PM - WRITING CHARACTER DATA: Macaroni
   2018-02-22 11:34:56 PM - WRITING CHARACTER DATA: {GW}Assasin
   2018-02-22 11:34:56 PM - WRITING CHARACTER DATA: Macaroni
   2018-02-22 11:34:56 PM - WRITING CHARACTER DATA: {GW}Assasin
   2018-02-22 11:34:56 PM - WRITING CHARACTER DATA: Macaroni
   2018-02-22 11:34:56 PM - WRITING CHARACTER DATA: {GW}Assasin
   2018-02-22 11:34:56 PM - WRITING CHARACTER DATA: Macaroni
   2018-02-22 11:34:56 PM - WRITING CHARACTER DATA: {GW}Assasin
   2018-02-22 11:34:56 PM - WRITING CHARACTER DATA: Macaroni
   2018-02-22 11:34:06 PM - bob was kicked due to excessive desync (expected old event 3170)
   2018-02-22 11:33:38 PM - WRITING CHARACTER DATA: {GW}Assasin
   2018-02-22 11:33:37 PM - WRITING CHARACTER DATA: {GW}Assasin
   2018-02-22 11:33:37 PM - WRITING CHARACTER DATA: {GW}Assasin
   2018-02-22 11:33:37 PM - WRITING CHARACTER DATA: {GW}Assasin
   2018-02-22 11:33:37 PM - WRITING CHARACTER DATA: {GW}Assasin
   2018-02-22 11:33:37 PM - WRITING CHARACTER DATA: {GW}Assasin
   2018-02-22 11:33:37 PM - WRITING CHARACTER DATA: {GW}Assasin
   2018-02-22 11:33:37 PM - WRITING CHARACTER DATA: {GW}Assasin
   2018-02-22 11:33:37 PM - WRITING CHARACTER DATA: {GW}Assasin
   2018-02-22 11:33:37 PM - WRITING CHARACTER DATA: {GW}Assasin
   2018-02-22 11:33:37 PM - WRITING CHARACTER DATA: {GW}Assasin
   2018-02-22 11:33:37 PM - WRITING CHARACTER DATA: {GW}Assasin
   2018-02-22 11:33:01 PM - WRITING CHARACTER DATA: bob
   2018-02-22 11:33:01 PM - WRITING CHARACTER DATA: bob
   2018-02-22 11:33:01 PM - WRITING CHARACTER DATA: bob
   2018-02-22 11:33:01 PM - WRITING CHARACTER DATA: bob
   2018-02-22 11:33:01 PM - WRITING CHARACTER DATA: bob
   2018-02-22 11:33:01 PM - WRITING CHARACTER DATA: bob
   2018-02-22 11:33:01 PM - WRITING CHARACTER DATA: bob
   2018-02-22 11:33:01 PM - WRITING CHARACTER DATA: bob
   2018-02-22 11:33:01 PM - WRITING CHARACTER DATA: bob
   2018-02-22 11:31:20 PM - WRITING CHARACTER DATA: Jeff
   2018-02-22 11:31:20 PM - WRITING CHARACTER DATA: Jeff
   2018-02-22 11:31:20 PM - WRITING CHARACTER DATA: Jeff
   2018-02-22 11:31:20 PM - WRITING CHARACTER DATA: Jeff
   2018-02-22 11:31:20 PM - WRITING CHARACTER DATA: Jeff
   2018-02-22 11:31:20 PM - Maximum packet size exceeded (1409 > 1408)
   2018-02-22 11:31:20 PM - WRITING CHARACTER DATA: Jeff
   2018-02-22 11:31:20 PM - WRITING CHARACTER DATA: Jeff
   2018-02-22 11:31:20 PM - Maximum packet size exceeded (1410 > 1408)
   2018-02-22 11:31:20 PM - WRITING CHARACTER DATA: Jeff
   2018-02-22 11:31:20 PM - WRITING CHARACTER DATA: Scotty
   2018-02-22 11:31:20 PM - WRITING CHARACTER DATA: Jeff
   2018-02-22 11:31:20 PM - WRITING CHARACTER DATA: Jeff
   2018-02-22 11:31:20 PM - WRITING CHARACTER DATA: Scotty
   2018-02-22 11:31:20 PM - WRITING CHARACTER DATA: Jeff
   2018-02-22 11:31:20 PM - WRITING CHARACTER DATA: Jeff
   2018-02-22 11:31:19 PM - WRITING CHARACTER DATA: Jeff
   2018-02-22 11:31:19 PM - WRITING CHARACTER DATA: Scotty
   2018-02-22 11:31:19 PM - WRITING CHARACTER DATA: Jeff
   2018-02-22 11:31:19 PM - WRITING CHARACTER DATA: Scotty
   2018-02-22 11:31:19 PM - WRITING CHARACTER DATA: Jeff
   2018-02-22 11:31:19 PM - WRITING CHARACTER DATA: Scotty
   2018-02-22 11:31:19 PM - WRITING CHARACTER DATA: Jeff
   2018-02-22 11:31:19 PM - WRITING CHARACTER DATA: Scotty
   2018-02-22 11:31:19 PM - WRITING CHARACTER DATA: Jeff
   2018-02-22 11:31:19 PM - WRITING CHARACTER DATA: Scotty
   2018-02-22 11:31:19 PM - WRITING CHARACTER DATA: Jeff
   2018-02-22 11:31:19 PM - WRITING CHARACTER DATA: Scotty
   2018-02-22 11:31:19 PM - WRITING CHARACTER DATA: Jeff
   2018-02-22 11:31:19 PM - WRITING CHARACTER DATA: Scotty
   2018-02-22 11:31:19 PM - WRITING CHARACTER DATA: Jeff
   2018-02-22 11:31:19 PM - WRITING CHARACTER DATA: Scotty
   2018-02-22 11:31:17 PM - WRITING CHARACTER DATA: crawler
   2018-02-22 11:31:17 PM - WRITING CHARACTER DATA: crawler
   2018-02-22 11:31:17 PM - WRITING CHARACTER DATA: crawler
   2018-02-22 11:31:17 PM - WRITING CHARACTER DATA: crawler
   2018-02-22 11:31:17 PM - WRITING CHARACTER DATA: crawler
   2018-02-22 11:31:17 PM - WRITING CHARACTER DATA: crawler
   2018-02-22 11:31:17 PM - WRITING CHARACTER DATA: crawler
   2018-02-22 11:31:17 PM - WRITING CHARACTER DATA: crawler
   2018-02-22 11:31:17 PM - WRITING CHARACTER DATA: crawler
   2018-02-22 11:31:17 PM - WRITING CHARACTER DATA: crawler
   2018-02-22 11:31:15 PM - WRITING CHARACTER DATA: crawler
   2018-02-22 11:31:14 PM - WRITING CHARACTER DATA: crawler
   2018-02-22 11:31:14 PM - WRITING CHARACTER DATA: crawler
   2018-02-22 11:31:14 PM - WRITING CHARACTER DATA: crawler
   2018-02-22 11:31:14 PM - WRITING CHARACTER DATA: crawler
   2018-02-22 11:31:14 PM - WRITING CHARACTER DATA: crawler
   2018-02-22 11:31:14 PM - WRITING CHARACTER DATA: crawler
   2018-02-22 11:31:14 PM - WRITING CHARACTER DATA: crawler
   2018-02-22 11:31:14 PM - WRITING CHARACTER DATA: crawler
   2018-02-22 11:29:19 PM - WRITING CHARACTER DATA: ChronoAtog
   2018-02-22 11:29:19 PM - WRITING CHARACTER DATA: ChronoAtog
   2018-02-22 11:29:19 PM - WRITING CHARACTER DATA: ChronoAtog
   2018-02-22 11:29:19 PM - WRITING CHARACTER DATA: hi
   2018-02-22 11:29:18 PM - WRITING CHARACTER DATA: ChronoAtog
   2018-02-22 11:29:18 PM - WRITING CHARACTER DATA: hi
   2018-02-22 11:29:18 PM - WRITING CHARACTER DATA: hi
   2018-02-22 11:29:18 PM - WRITING CHARACTER DATA: {GW}Assasin
   2018-02-22 11:29:18 PM - WRITING CHARACTER DATA: Muhammad
   2018-02-22 11:29:18 PM - WRITING CHARACTER DATA: {GW}Assasin
   2018-02-22 11:29:18 PM - WRITING CHARACTER DATA: Muhammad
   2018-02-22 11:29:17 PM - WRITING CHARACTER DATA: bob
   2018-02-22 11:29:17 PM - WRITING CHARACTER DATA: Macaroni
   2018-02-22 11:29:17 PM - WRITING CHARACTER DATA: bob
   2018-02-22 11:29:17 PM - WRITING CHARACTER DATA: Macaroni
   2018-02-22 11:28:16 PM - WRITING CHARACTER DATA: ChronoAtog
   2018-02-22 11:28:16 PM - WRITING CHARACTER DATA: ChronoAtog
   2018-02-22 11:28:16 PM - WRITING CHARACTER DATA: ChronoAtog
   2018-02-22 11:28:16 PM - WRITING CHARACTER DATA: hi
   2018-02-22 11:28:16 PM - WRITING CHARACTER DATA: ChronoAtog
   2018-02-22 11:28:16 PM - WRITING CHARACTER DATA: hi
   2018-02-22 11:28:16 PM - WRITING CHARACTER DATA: hi
   2018-02-22 11:28:15 PM - WRITING CHARACTER DATA: hi
   2018-02-22 11:28:15 PM - WRITING CHARACTER DATA: {GW}Assasin
   2018-02-22 11:28:15 PM - WRITING CHARACTER DATA: Muhammad
   2018-02-22 11:28:15 PM - WRITING CHARACTER DATA: {GW}Assasin
   2018-02-22 11:28:15 PM - WRITING CHARACTER DATA: Muhammad
   2018-02-22 11:28:15 PM - WRITING CHARACTER DATA: bob
   2018-02-22 11:28:15 PM - WRITING CHARACTER DATA: Macaroni
   2018-02-22 11:28:15 PM - WRITING CHARACTER DATA: bob
   2018-02-22 11:28:15 PM - WRITING CHARACTER DATA: Macaroni
   2018-02-22 11:26:52 PM - WRITING CHARACTER DATA: ChronoAtog
   2018-02-22 11:26:52 PM - WRITING CHARACTER DATA: ChronoAtog
   2018-02-22 11:26:51 PM - WRITING CHARACTER DATA: ChronoAtog
   2018-02-22 11:26:51 PM - WRITING CHARACTER DATA: ChronoAtog
   2018-02-22 11:26:51 PM - WRITING CHARACTER DATA: ChronoAtog
   2018-02-22 11:26:51 PM - WRITING CHARACTER DATA: ChronoAtog
   2018-02-22 11:26:51 PM - WRITING CHARACTER DATA: ChronoAtog
   2018-02-22 11:26:51 PM - WRITING CHARACTER DATA: hi
   2018-02-22 11:26:51 PM - WRITING CHARACTER DATA: ChronoAtog
   2018-02-22 11:26:51 PM - WRITING CHARACTER DATA: ChronoAtog
   2018-02-22 11:26:51 PM - WRITING CHARACTER DATA: hi
   2018-02-22 11:26:51 PM - WRITING CHARACTER DATA: ChronoAtog
   2018-02-22 11:26:51 PM - WRITING CHARACTER DATA: hi
   2018-02-22 11:26:51 PM - WRITING CHARACTER DATA: ChronoAtog
   2018-02-22 11:26:51 PM - WRITING CHARACTER DATA: hi
   2018-02-22 11:26:51 PM - WRITING CHARACTER DATA: ChronoAtog
   2018-02-22 11:26:51 PM - WRITING CHARACTER DATA: hi
   2018-02-22 11:26:51 PM - WRITING CHARACTER DATA: ChronoAtog
   2018-02-22 11:26:51 PM - WRITING CHARACTER DATA: hi
   2018-02-22 11:26:51 PM - WRITING CHARACTER DATA: ChronoAtog
   2018-02-22 11:26:51 PM - WRITING CHARACTER DATA: hi
   2018-02-22 11:26:51 PM - WRITING CHARACTER DATA: ChronoAtog
   2018-02-22 11:26:51 PM - WRITING CHARACTER DATA: hi

**Comment by NilanthAnimosus** [comment]
Given my other two crashes were on round start and this crash above states "Round Not Started" and my own two other crashes were at round starts - I have a fair hypothesis for why this is occurring. Having looked at the limbs field the only case it is allowed to be null is if a character has been removed using the Remove() function.

Now normally, this means the character is removed but if its reference is being maintained and any of these crash reasons is going through the full list of characters its reasonable to assume somewhere is holding a character reference or even anim controller / ragdoll reference that is not being cleaned up properly once the round has been finished.

**Comment by Regalis11** [comment]
Yeah, it appears to be caused by accessing an already removed character. I still haven't figured out how that's possible, because the Remove() method should always remove the character from the character list and the ragdoll from the ragdoll list, and these crashes seem to imply that they're still present in the lists.

**Comment by NilanthAnimosus** [comment]
Yeah I was reviewing that just seconds ago now, the remove() has the character list remove its reference and its only added once on the characters creation.

**Comment by NilanthAnimosus** [comment]
I used the code changes from 7f740c2f67621ddaa9ce12806851026ec70090b9 early and played with my client/server mod using it. and this happened:

![image](http://puu.sh/zwyQL/a4b0d4e4c3.jpg)

It spammed a good deal of times before ending with "Connection status changed: Disconnected" where I assume the server I was on crashed.

**Comment by NilanthAnimosus** [comment]
Saw this crash report in the discord from billsofat, it is definitely relevant to the above issue:

[crashreport.txt](https://github.com/Regalis11/Barotrauma/files/1799800/crashreport.txt)

looking at the error it looks very close to the set enabled crash given it actually triggers it where the physics engine has a null fixture list. 

Extra interestingly there is a period of about 30 seconds in the debuglog where the issue appears then disappears then appears again with the same ID's

There are also two different crawlers triggering it, both have Removed: False but a null ragdoll limbs given the error shown.

The game eventually crashed in the FishAnimController. If I had to take a guess this is actually occurring to monster event creature spawns (And thus, potentially to any character spawn somehow ?)

**Comment by Regalis11** [comment]
I'm pretty sure this caused by a character from a previous round still being present in the character list on a new round.

In this crash report a moloch had been spawned, then the round ended (as indicated by the "Error while unloading submarines - item "Welding Tool" not removed" error) and during the next round the moloch caused a crash. [crashreport2.log](https://github.com/Regalis11/Barotrauma/files/1932253/crashreport2.log)

I still don't know how exactly this happens, but I feel I'm getting closer.
