### ISSUE TITLE
Loading failure with no specific error message

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#3]
```
Crash after launching the game.

Barotrauma crash report (generated on 31.05.2017 21:54:33)


Barotrauma seems to have crashed. Sorry for the inconvenience! 
If you'd like to help fix the bug that caused the crash, please send this file to the developers on the Undertow Games forums.


Game version 0.6.0.0
Graphics mode: 1920x1080 (Fullscreen)
Selected content package: Vanilla 0.3
Level seed: no level loaded
Loaded submarine: None
Selected screen: None


System info:
Operating system: Microsoft Windows NT 6.1.7601 Service Pack 1 64 bit


Exception: Object reference not set to an instance of an object.
Target site: Void Draw(Microsoft.Xna.Framework.GameTime)
Stack trace: 
at Barotrauma.GameMain.Draw(GameTime gameTime) in E:\Subsurface\Subsurface\Source\GameMain.cs:line 390
at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime)
at Microsoft.Xna.Framework.Game.Tick()
at MonoGame.Framework.WinFormsGameWindow.RunLoop()
at MonoGame.Framework.WinFormsGamePlatform.RunLoop()
at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
at Barotrauma.Program.Main() in E:\Subsurface\Subsurface\Source\Program.cs:line 43


Last debug messages:
31.05.2017 21:54:33 - Loading was interrupted due to an error
```

**Comment by Regalis11** [comment]
http://undertowgames.com/forum/viewtopic.php?f=21&t=7276
