### ISSUE TITLE
Trying to climb a spawned in ladder caused server and client to crash

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#3029]
Tested on Unstable 0.1002.0.0

Repro steps (Full steps unclear):
1. Spawn in a ladder in multiplayer
3. Place it down
2. Try and use it

Client crash report
```
Barotrauma Client crash report (generated on 09/06/2020 16:46:43)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


D7EA8964CC323357806D136F479AF058


Game version 0.1002.0.0 (UnstableWindows, branch feature/campaign-groundwork, revision 07ef298dd)
Graphics mode: 1600x900 (Windowed)
VSync ON
Language: English
Selected content packages: Vanilla 0.9, Aegir Mark III, Alkonost, Atolla, Cityscape - Salthane, Corsair, Duoton, E.C.A.C Prison Bus, EK_Dora_Mk-II, EK_Scrapper_Mk-I, HunnyBee, Hyperius Asperis Station, Legacy menu ost mod, Likho, Mining Station A, Nehalennia, Refuelling Depot, Research Station A, SB Shellfish, SB Smokescreen, SB Tuskar, The Iron Gear, [EMS] Prometheus Station, SB Cranefish, Mercury II, Aquatic Bus
Level seed: Hyperenor Linea
Loaded submarine: Orca (3D19AD5777DA795DB36DC73FA84603D0)
Selected screen: Barotrauma.GameScreen
SteamManager initialized
Client (Round had started)


System info:
    Operating system: Microsoft Windows NT 10.0.18362.0 64 bit
    GPU name: Intel(R) HD Graphics 520
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal


Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void UpdateClimbing()
Stack trace: 
   at Barotrauma.HumanoidAnimController.UpdateClimbing() in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\Animation\HumanoidAnimController.cs:line 1142
   at Barotrauma.HumanoidAnimController.UpdateAnim(Single deltaTime) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\Animation\HumanoidAnimController.cs:line 477
   at Barotrauma.Character.UpdateAnimAll(Single deltaTime) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 2088
   at Barotrauma.GameScreen.Update(Double deltaTime) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 238
   at Barotrauma.GameMain.Update(GameTime gameTime) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 956
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58


Last debug messages:
[09/06/2020 16:46:42] Server command: spawnitem Ladder cursor
[09/06/2020 16:46:42] spawnitem Ladder cursor
[09/06/2020 16:46:41] Server command: spawnitem Ladder cursor
[09/06/2020 16:46:41] spawnitem Ladder cursor
[09/06/2020 16:46:40] Server command: spawnitem Ladder cursor
[09/06/2020 16:46:40] spawnitem Ladder cursor
[09/06/2020 16:46:38] Server command: spawnitem Ladder cursor
[09/06/2020 16:46:38] spawnitem Ladder cursor
[09/06/2020 16:46:17] Server command: spawnitem "Office Chair" cursor
[09/06/2020 16:46:17] spawnitem "Office Chair" cursor
[09/06/2020 16:46:10] Server command: spawnitem "Office Chair" cursor
[09/06/2020 16:46:10] spawnitem "Office Chair" cursor
[09/06/2020 16:46:09] Server command: spawnitem "Office Chair" cursor
[09/06/2020 16:46:09] spawnitem "Office Chair" cursor
[09/06/2020 16:46:08] Server command: spawnitem "Office Chair" cursor
[09/06/2020 16:46:08] spawnitem "Office Chair" cursor
[09/06/2020 16:46:07] Server command: spawnitem "Office Chair" cursor
[09/06/2020 16:46:07] spawnitem "Office Chair" cursor
[09/06/2020 16:45:43] Server command: teleportcharacter
[09/06/2020 16:45:43] teleportcharacter
[09/06/2020 16:45:24] Server command: spawnitem "Oxygen Tank" inventory
[09/06/2020 16:45:24] spawnitem "Oxygen Tank" inventory
[09/06/2020 16:45:16] Server command: spawnitem "Plasma Cutter" inventory
[09/06/2020 16:45:16] spawnitem "Plasma Cutter" inventory
[09/06/2020 16:44:52] Server command: fixitems
[09/06/2020 16:44:52] fixitems
[09/06/2020 16:44:46] Bloop
[09/06/2020 16:44:46] Rokvach
[09/06/2020 16:44:45] Jerry Jalopy
[09/06/2020 16:44:45] John
[09/06/2020 16:44:45] Solbusaur
[09/06/2020 16:44:38] Generating an outpost for the start of the level... (Location: Hyperenor Linea Prospecting Outpost, level type: Outpost)
[09/06/2020 16:44:26] Bloop
[09/06/2020 16:44:26] Rokvach
[09/06/2020 16:44:26] Jerry Jalopy
[09/06/2020 16:44:26] John
[09/06/2020 16:44:26] Solbusaur
[09/06/2020 16:44:21] Bloop
[09/06/2020 16:44:21] Rokvach
[09/06/2020 16:44:21] Jerry Jalopy
[09/06/2020 16:44:21] John
[09/06/2020 16:44:21] Solbusaur
[09/06/2020 16:44:12] Generating an outpost for the end of the level... (Location: Noctae Mining Facility, level type: LocationConnection)
[09/06/2020 16:44:12] Generating an outpost for the start of the level... (Location: Hyperenor Linea Prospecting Outpost, level type: LocationConnection)
[09/06/2020 16:44:00] Bloop
[09/06/2020 16:44:00] Rokvach
[09/06/2020 16:44:00] Jerry Jalopy
[09/06/2020 16:44:00] John
[09/06/2020 16:44:00] Solbusaur
[09/06/2020 16:43:48] Server command: spawnitem "Stun Grenade" inventory
[09/06/2020 16:43:48] spawnitem "Stun Grenade" inventory
[09/06/2020 16:43:48] Server command: spawnitem "Stun Grenade" inventory
[09/06/2020 16:43:48] spawnitem "Stun Grenade" inventory
[09/06/2020 16:43:41] Server command: spawnitem "Compound N" inventory
[09/06/2020 16:43:41] spawnitem "Compound N" inventory
[09/06/2020 16:42:23] Server command: spawnitem Ethanol inventory
[09/06/2020 16:42:23] spawnitem Ethanol inventory
[09/06/2020 16:40:33] Server command: spawnitem "Stun Grenade" inventory
[09/06/2020 16:40:33] spawnitem "Stun Grenade" inventory
[09/06/2020 16:40:33] Server command: spawnitem "Stun Grenade" inventory
[09/06/2020 16:40:33] spawnitem "Stun Grenade" inventory
[09/06/2020 16:40:25] Server command: spawnitem "Stun Grenade" inventory
[09/06/2020 16:40:25] spawnitem "Stun Grenade" inventory
[09/06/2020 16:40:24] Server command: spawnitem "Stun Grenade" inventory
[09/06/2020 16:40:24] spawnitem "Stun Grenade" inventory
[09/06/2020 16:40:13] Server command: spawnitem "Compound N" inventory
[09/06/2020 16:40:13] spawnitem "Compound N" inventory
[09/06/2020 16:40:13] Server command: spawnitem "Compound N" inventory
[09/06/2020 16:40:13] spawnitem "Compound N" inventory
[09/06/2020 16:40:12] Server command: spawnitem "Compound N" inventory
[09/06/2020 16:40:12] spawnitem "Compound N" inventory
[09/06/2020 16:40:12] Server command: spawnitem "Compound N" inventory
[09/06/2020 16:40:12] spawnitem "Compound N" inventory
[09/06/2020 16:40:08] Server command: spawnitem "Compound N" inventory
[09/06/2020 16:40:08] spawnitem "Compound N" inventory
[09/06/2020 16:40:08] Server command: spawnitem "Compound N" inventory
[09/06/2020 16:40:08] spawnitem "Compound N" inventory
[09/06/2020 16:40:07] Server command: spawnitem "Compound N" inventory
[09/06/2020 16:40:07] spawnitem "Compound N" inventory
[09/06/2020 16:40:07] Server command: spawnitem "Compound N" inventory
[09/06/2020 16:40:07] spawnitem "Compound N" inventory
[09/06/2020 16:39:39] Server command: spawnitem "Compound N" inventory
[09/06/2020 16:39:39] spawnitem "Compound N" inventory
[09/06/2020 16:39:38] Server command: spawnitem "Compound N" inventory
[09/06/2020 16:39:38] spawnitem "Compound N" inventory
[09/06/2020 16:39:37] Server command: spawnitem "Compound N" inventory
[09/06/2020 16:39:37] spawnitem "Compound N" inventory
[09/06/2020 16:37:45] Bloop
[09/06/2020 16:37:45] Rokvach
[09/06/2020 16:37:44] Jerry Jalopy
[09/06/2020 16:37:44] John
[09/06/2020 16:37:44] Solbusaur
[09/06/2020 16:37:38] Generating an outpost for the start of the level... (Location: Hyperenor Linea Prospecting Outpost, level type: Outpost)
[09/06/2020 16:37:27] Bloop
[09/06/2020 16:37:27] Rokvach
[09/06/2020 16:37:27] Jerry Jalopy
[09/06/2020 16:37:27] John
[09/06/2020 16:37:27] Solbusaur
[09/06/2020 16:37:06] Bloop
[09/06/2020 16:37:06] Rokvach
[09/06/2020 16:37:06] Jerry Jalopy
[09/06/2020 16:37:06] John
[09/06/2020 16:37:06] Solbusaur
[09/06/2020 16:36:31] Bloop
[09/06/2020 16:36:31] Rokvach
[09/06/2020 16:36:31] Jerry Jalopy
[09/06/2020 16:36:31] John
[09/06/2020 16:36:31] Solbusaur
[09/06/2020 16:36:30] Bloop
[09/06/2020 16:36:28] Rokvach
[09/06/2020 16:36:27] Jerry Jalopy
[09/06/2020 16:36:27] John
[09/06/2020 16:36:27] Solbusaur
[09/06/2020 16:36:16] Generating an outpost for the end of the level... (Location: Hyperenor Linea Prospecting Outpost, level type: LocationConnection)
[09/06/2020 16:36:15] Generating an outpost for the start of the level... (Location: Xinzou Outpost, level type: LocationConnection)
[09/06/2020 16:35:59] Rokvach
[09/06/2020 16:35:59] Jerry Jalopy
[09/06/2020 16:35:59] John
[09/06/2020 16:35:59] Solbusaur
[09/06/2020 16:35:42] Server command: spawnitem Engine cursor
[09/06/2020 16:35:42] spawnitem Engine cursor
[09/06/2020 16:34:58] Server command: teleportcharacter
[09/06/2020 16:34:58] teleportcharacter
[09/06/2020 16:34:23] Server command: spawnitem "Office Chair" cursor
[09/06/2020 16:34:23] spawnitem "Office Chair" cursor
[09/06/2020 16:34:22] Server command: spawnitem "Office Chair" cursor
[09/06/2020 16:34:22] spawnitem "Office Chair" cursor
[09/06/2020 16:34:22] Server command: spawnitem "Office Chair" cursor
[09/06/2020 16:34:22] spawnitem "Office Chair" cursor
[09/06/2020 16:33:40] Server command: spawnitem "Office Chair" cursor
[09/06/2020 16:33:40] spawnitem "Office Chair" cursor
[09/06/2020 16:33:39] Server command: spawnitem "Office Chair" cursor
[09/06/2020 16:33:39] spawnitem "Office Chair" cursor
[09/06/2020 16:33:39] Server command: spawnitem "Office Chair" cursor
[09/06/2020 16:33:39] spawnitem "Office Chair" cursor
[09/06/2020 16:33:39] Server command: spawnitem "Office Chair" cursor
[09/06/2020 16:33:39] spawnitem "Office Chair" cursor
[09/06/2020 16:33:39] Server command: spawnitem "Office Chair" cursor
[09/06/2020 16:33:39] spawnitem "Office Chair" cursor
[09/06/2020 16:33:38] Server command: spawnitem "Office Chair" cursor
[09/06/2020 16:33:38] spawnitem "Office Chair" cursor
[09/06/2020 16:33:38] Server command: spawnitem "Office Chair" cursor
[09/06/2020 16:33:38] spawnitem "Office Chair" cursor
[09/06/2020 16:33:38] Server command: spawnitem "Office Chair" cursor
[09/06/2020 16:33:38] spawnitem "Office Chair" cursor
[09/06/2020 16:33:38] Server command: spawnitem "Office Chair" cursor
[09/06/2020 16:33:38] spawnitem "Office Chair" cursor
[09/06/2020 16:33:37] Server command: spawnitem "Office Chair" cursor
[09/06/2020 16:33:37] spawnitem "Office Chair" cursor
[09/06/2020 16:33:37] Server command: spawnitem "Office Chair" cursor
[09/06/2020 16:33:37] spawnitem "Office Chair" cursor
[09/06/2020 16:33:36] Server command: spawnitem "Office Chair" cursor
[09/06/2020 16:33:36] spawnitem "Office Chair" cursor
[09/06/2020 16:33:17] Server command: spawnitem "Office Chair" cursor
[09/06/2020 16:33:17] spawnitem "Office Chair" cursor
[09/06/2020 16:32:46] Server command: spawnitem "Office Chair" cursor
[09/06/2020 16:32:46] spawnitem "Office Chair" cursor
[09/06/2020 16:32:31] Server command: spawnitem "Office Chair" cursor
[09/06/2020 16:32:31] spawnitem "Office Chair" cursor
[09/06/2020 16:32:23] Server command: spawnitem "Office Chair" cursor
[09/06/2020 16:32:23] spawnitem "Office Chair" cursor
[09/06/2020 16:31:45] Server command: spawnitem "Office Chair" cursor
[09/06/2020 16:31:45] spawnitem "Office Chair" cursor
[09/06/2020 16:31:44] Server command: spawnitem "Office Chair" cursor
[09/06/2020 16:31:44] spawnitem "Office Chair" cursor
[09/06/2020 16:31:43] Rokvach
[09/06/2020 16:31:43] Jerry Jalopy
[09/06/2020 16:31:43] John
[09/06/2020 16:31:43] Solbusaur
[09/06/2020 16:31:33] Server command: spawnitem "Office Chair" cursor
[09/06/2020 16:31:33] spawnitem "Office Chair" cursor
[09/06/2020 16:31:32] Server command: spawnitem "Office Chair" cursor
[09/06/2020 16:31:32] spawnitem "Office Chair" cursor
[09/06/2020 16:31:32] Server command: spawnitem "Office Chair" cursor
[09/06/2020 16:31:32] spawnitem "Office Chair" cursor
[09/06/2020 16:31:31] Server command: spawnitem "Office Chair" cursor
[09/06/2020 16:31:31] spawnitem "Office Chair" cursor
[09/06/2020 16:30:53] Server command: spawnitem "Office Chair" cursor
[09/06/2020 16:30:53] spawnitem "Office Chair" cursor
[09/06/2020 16:30:47] Server command: spawnitem "Office Chair" cursor
[09/06/2020 16:30:47] spawnitem "Office Chair" cursor
[09/06/2020 16:30:41] Server command: spawnitem "Office Chair" cursor
[09/06/2020 16:30:41] spawnitem "Office Chair" cursor
[09/06/2020 16:30:36] Server command: spawnitem "Office Chair" cursor
[09/06/2020 16:30:36] spawnitem "Office Chair" cursor
[09/06/2020 16:29:59] Rokvach
[09/06/2020 16:29:59] Jerry Jalopy
[09/06/2020 16:29:59] John
[09/06/2020 16:29:59] Solbusaur
[09/06/2020 16:29:59] Rokvach
[09/06/2020 16:29:59] Jerry Jalopy
[09/06/2020 16:29:59] John
[09/06/2020 16:29:59] Solbusaur
[09/06/2020 16:29:57] Rokvach
[09/06/2020 16:29:57] Jerry Jalopy
[09/06/2020 16:29:57] John
[09/06/2020 16:29:57] Solbusaur
[09/06/2020 16:29:56] Jerry Jalopy
[09/06/2020 16:29:56] John
[09/06/2020 16:29:56] Solbusaur
[09/06/2020 16:29:47] Jerry Jalopy
[09/06/2020 16:29:47] John
[09/06/2020 16:29:47] Solbusaur
[09/06/2020 16:29:47] Jerry Jalopy
[09/06/2020 16:29:47] John
[09/06/2020 16:29:47] Solbusaur
[09/06/2020 16:29:42] Jerry Jalopy
[09/06/2020 16:29:42] John
[09/06/2020 16:29:42] Solbusaur
[09/06/2020 16:29:40] Rokvach
[09/06/2020 16:29:40] Jerry Jalopy
[09/06/2020 16:29:40] John
[09/06/2020 16:29:40] Solbusaur
[09/06/2020 16:29:35] Rokvach
[09/06/2020 16:29:35] Jerry Jalopy
[09/06/2020 16:29:35] John
[09/06/2020 16:29:35] Solbusaur
[09/06/2020 16:29:15] Rokvach
[09/06/2020 16:29:15] Jerry Jalopy
[09/06/2020 16:29:15] John
[09/06/2020 16:29:15] Solbusaur
[09/06/2020 16:29:09] Rokvach
[09/06/2020 16:29:09] Jerry Jalopy
[09/06/2020 16:29:09] John
[09/06/2020 16:29:09] Solbusaur
[09/06/2020 16:28:55] los
[09/06/2020 16:28:40] Rokvach
[09/06/2020 16:28:40] Jerry Jalopy
[09/06/2020 16:28:40] John
[09/06/2020 16:28:40] Solbusaur
[09/06/2020 16:28:40] Rokvach
[09/06/2020 16:28:40] Jerry Jalopy
[09/06/2020 16:28:40] John
[09/06/2020 16:28:40] Solbusaur
[09/06/2020 16:28:27] Rokvach
[09/06/2020 16:28:27] Jerry Jalopy
[09/06/2020 16:28:27] John
[09/06/2020 16:28:27] Solbusaur
[09/06/2020 16:28:10] Rokvach
[09/06/2020 16:28:10] Bloop
[09/06/2020 16:28:09] Jerry Jalopy
[09/06/2020 16:28:09] John
[09/06/2020 16:28:09] Solbusaur
[09/06/2020 16:28:06] Generating an outpost for the start of the level... (Location: Xinzou Outpost, level type: Outpost)
[09/06/2020 16:27:39] Jerry Jalopy
[09/06/2020 16:27:39] John
[09/06/2020 16:27:39] Solbusaur
[09/06/2020 16:27:03] Jerry Jalopy
[09/06/2020 16:27:03] John
[09/06/2020 16:27:03] Solbusaur
[09/06/2020 16:26:43] Jerry Jalopy
[09/06/2020 16:26:43] John
[09/06/2020 16:26:43] Solbusaur
[09/06/2020 16:26:21] Jerry Jalopy
[09/06/2020 16:26:21] John
[09/06/2020 16:26:21] Solbusaur
[09/06/2020 16:26:20] Jerry Jalopy
[09/06/2020 16:26:20] John
[09/06/2020 16:26:20] Solbusaur
[09/06/2020 16:26:09] Jerry Jalopy
[09/06/2020 16:26:09] John
[09/06/2020 16:26:09] Solbusaur
[09/06/2020 16:25:43] Jerry Jalopy
[09/06/2020 16:25:43] John
[09/06/2020 16:25:43] Solbusaur
[09/06/2020 16:25:43] Jerry Jalopy
[09/06/2020 16:25:43] John
[09/06/2020 16:25:43] Solbusaur
[09/06/2020 16:25:33] Jerry Jalopy
[09/06/2020 16:25:33] John
[09/06/2020 16:25:33] Solbusaur
[09/06/2020 16:25:33] John
[09/06/2020 16:25:33] Solbusaur
[09/06/2020 16:25:33] Jerry Jalopy
[09/06/2020 16:25:20] Jerry Jalopy
[09/06/2020 16:25:20] John
[09/06/2020 16:25:20] Solbusaur
[09/06/2020 16:25:20] Jerry Jalopy
[09/06/2020 16:25:20] John
[09/06/2020 16:25:20] Solbusaur
[09/06/2020 16:25:12] Jerry Jalopy
[09/06/2020 16:25:12] John
[09/06/2020 16:25:12] Solbusaur
[09/06/2020 16:25:10] Jerry Jalopy
[09/06/2020 16:25:10] John
[09/06/2020 16:25:10] Solbusaur
[09/06/2020 16:24:40] Jerry Jalopy
[09/06/2020 16:24:40] John
[09/06/2020 16:24:40] Solbusaur
[09/06/2020 16:24:40] Jerry Jalopy
[09/06/2020 16:24:40] John
[09/06/2020 16:24:40] Solbusaur
[09/06/2020 16:24:21] Jerry Jalopy
[09/06/2020 16:24:21] John
[09/06/2020 16:24:21] Solbusaur
[09/06/2020 16:24:21] Jerry Jalopy
[09/06/2020 16:24:21] John
[09/06/2020 16:24:21] Solbusaur
[09/06/2020 16:24:14] Jerry Jalopy
[09/06/2020 16:24:14] John
```

Server crash report
```
Barotrauma Dedicated Server crash report (generated on 06/09/2020 15:46:42)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


Game version 0.1002.0.0 (UnstableLinux, branch feature/campaign-groundwork, revision 07ef298dd7)
Language: English
Selected content packages: Vanilla 0.9
Level seed: Hyperenor Linea
Loaded submarine: Orca (C83B645E3F391798B8D20A513B4B0A96)
Selected screen: Barotrauma.GameScreen
Server (Round had started)


System info:
    Operating system: Unix 5.3.0.1017 64 bit


Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void UpdateClimbing()
Stack trace: 
   at Barotrauma.HumanoidAnimController.UpdateClimbing() in /home/joonas/Barotrauma/Barotrauma/BarotraumaShared/SharedSource/Characters/Animation/HumanoidAnimController.cs:line 1142
   at Barotrauma.HumanoidAnimController.UpdateAnim(Single deltaTime) in /home/joonas/Barotrauma/Barotrauma/BarotraumaShared/SharedSource/Characters/Animation/HumanoidAnimController.cs:line 477
   at Barotrauma.Character.UpdateAnimAll(Single deltaTime) in /home/joonas/Barotrauma/Barotrauma/BarotraumaShared/SharedSource/Characters/Character.cs:line 2088
   at Barotrauma.GameScreen.Update(Double deltaTime) in /home/joonas/Barotrauma/Barotrauma/BarotraumaShared/SharedSource/Screens/GameScreen.cs:line 238
   at Barotrauma.GameMain.Run() in /home/joonas/Barotrauma/Barotrauma/BarotraumaServer/ServerSource/GameMain.cs:line 352
   at Barotrauma.Program.Main(String[] args) in /home/joonas/Barotrauma/Barotrauma/BarotraumaServer/ServerSource/Program.cs:line 48


Last debug messages:
   06/09/2020 15:46:42 - [06/09/2020 15:46:42]
  Saving banlist
   06/09/2020 15:46:41 - [06/09/2020 15:46:41]
  Console command "spawnitem Ladder cursor" executed by Solbusaur.
   06/09/2020 15:46:40 - [06/09/2020 15:46:40]
  Console command "spawnitem Ladder cursor" executed by Solbusaur.
   06/09/2020 15:46:39 - [06/09/2020 15:46:39]
  Console command "spawnitem Ladder cursor" executed by Solbusaur.
   06/09/2020 15:46:37 - [06/09/2020 15:46:37]
  Console command "spawnitem Ladder cursor" executed by Solbusaur.
   06/09/2020 15:46:35 - [06/09/2020 15:46:35]
  Console command "teleport" executed by Jerry Jalopy.
   06/09/2020 15:46:33 - [06/09/2020 15:46:33]
  Console command "teleport" executed by Jerry Jalopy.
   06/09/2020 15:46:33 - [06/09/2020 15:46:33]
  Bloop picked up Flare
   06/09/2020 15:46:32 - [06/09/2020 15:46:32]
  Console command "teleport" executed by Jerry Jalopy.
   06/09/2020 15:46:31 - [06/09/2020 15:46:31]
  Console command "teleport" executed by Jerry Jalopy.
   06/09/2020 15:46:29 - [06/09/2020 15:46:29]
  Console command "teleport" executed by Jerry Jalopy.
   06/09/2020 15:46:27 - [06/09/2020 15:46:27]
  Console command "teleport" executed by Jerry Jalopy.
   06/09/2020 15:46:26 - [06/09/2020 15:46:26]
  Console command "teleport" executed by Jerry Jalopy.
   06/09/2020 15:46:19 - [06/09/2020 15:46:19]
  Console command "teleport" executed by Jerry Jalopy.
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/cd94cdf6bf6912e537fa64dc9595585473f23310

**Comment by Rokvach** [comment]
Wasn't able to reproduce the issue, working correctly. Closing.
