### ISSUE TITLE
[0.1002.0.0] Game crashes when leaving station

### ISSUE THREAD

**Issue by Camper125Lv** [Regalis11/Barotrauma#3072]
**Description**
It crashed when i left station and now it won't allow me load game cuz it saved right before crash.
```
Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void Update(Single, Barotrauma.Camera)
Stack trace: 
   at Barotrauma.Items.Components.Reactor.Update(Single deltaTime, Camera cam) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Machines\Reactor.cs:line 322
   at Barotrauma.Item.Update(Single deltaTime, Camera cam) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 1391
   at Barotrauma.MapEntity.UpdateAll(Single deltaTime, Camera cam) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Map\MapEntity.cs:line 518
   at Barotrauma.GameScreen.Update(Double deltaTime) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 228
   at Barotrauma.GameMain.Update(GameTime gameTime) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 956
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58
```

**Steps To Reproduce**
Open my save.

**Version**
0.1002.0.0 Windows.

**Additional information**
Save file and full crash log.
[WreckedSave+crashlog.zip](https://github.com/Regalis11/Barotrauma/files/4766011/WreckedSave%2Bcrashlog.zip)

**Comment by Regalis11** [comment]
Seems to be caused by one of the installed mods: the save file doesn't cause a crash in an unmodified game.

Fixed in https://github.com/Regalis11/Barotrauma-development/commit/44ad15598311d5265560b5f5d3fd80b5a6cf7d2d

**Comment by Camper125Lv** [comment]
It was caused by one of the wreck mods.
