### ISSUE TITLE
[0.1004.0] Unable to salvage mission artifact

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3141]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Unable to salvage mission artifact

![](https://cdn.discordapp.com/attachments/668819422919524352/723248485721440422/Capture.PNG)
![](https://media.discordapp.net/attachments/668819422919524352/723248529971085332/Capture.PNG)
![](https://cdn.discordapp.com/attachments/668819422919524352/723248770262892624/Capture.PNG)
![](https://cdn.discordapp.com/attachments/668819422919524352/723248885887139860/Capture.PNG)

**Version**
0.1004.0

**Additional Informations**
There was another Faraday artifact in the level that I deconstructed a lot earlier. I am not sure if this is technically the same one?

**Comment by Rokvach** [comment]
This is still a issue with artifacts, this error came up on a stream yesterday. They were also mining so it could also be related to that as well.

Here's the time where the artifact threw issues during the stream:
https://www.twitch.tv/videos/669903107?t=03h11m38s

Btw the "Received an attachment event for an item that's not attachable." part wasn't included in the crashreport_object.log file, found it from a console dump. 
```
Received an attachment event for an item that's not attachable.
Index was outside the bounds of the array.
Message length: 8216 (1027 bytes)
Read position: 8208
Header: ENTITY_EVENT
Error occurred on the very first header!
Previous object was 0 bits long (0 bytes)
 
   at Lidgren.Network.NetBitWriter.ReadByte(Byte[] fromBuffer, Int32 numberOfBits, Int32 readBitOffset) in /home/joonas/Barotrauma/Libraries/Lidgren.Network/NetBitWriter.cs:line 41
   at Lidgren.Network.NetBitWriter.ReadUInt16(Byte[] fromBuffer, Int32 numberOfBits, Int32 readBitOffset) in /home/joonas/Barotrauma/Libraries/Lidgren.Network/NetBitWriter.cs:line 229
   at Barotrauma.Networking.MsgReader.ReadUInt16(Byte[] buf, Int32& bitPos) in /home/joonas/Barotrauma/Barotrauma/BarotraumaShared/SharedSource/Networking/Primitives/Message/Message.cs:line 239
   at Barotrauma.Networking.ClientEntityEventManager.Read(ServerNetObject type, IReadMessage msg, Single sendingTime, List`1 entities) in /home/joonas/Barotrauma/Barotrauma/BarotraumaClient/ClientSource/Networking/NetEntityEvent/ClientEntityEventManager.cs:line 168
   at Barotrauma.Networking.GameClient.ReadIngameUpdate(IReadMessage inc) in /home/joonas/Barotrauma/Barotrauma/BarotraumaClient/ClientSource/Networking/GameClient.cs:line 2116
```

**Comment by Rokvach** [comment]
Also posted on the QA channel on Slack 2 days ago

I assume this was during a singleplayer round. 


> Got an error when trying to pick up artifact from artifact holder

```
System.Exception
  HResult=0x80131500
  Message=Tried to put a removed item (Thermal Alien Artifact) in an inventory
  Source=Barotrauma
  StackTrace:
   at Barotrauma.CharacterInventory.TryPutItem(Item item, Character user, List`1 allowedSlots, Boolean createNetworkEvent) in C:\Users\danie\Documents\Projects\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Items\CharacterInventory.cs:line 172
   at Barotrauma.CharacterInventory.TryPutItemWithAutoEquipCheck(Item item, Character user, List`1 allowedSlots, Boolean createNetworkEvent) in C:\Users\danie\Documents\Projects\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Items\CharacterInventory.cs:line 145
   at Barotrauma.CharacterInventory.QuickUseItem(Item item, Boolean allowEquip, Boolean allowInventorySwap, Boolean allowApplyTreatment) in C:\Users\danie\Documents\Projects\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Items\CharacterInventory.cs:line 1015
   at Barotrauma.CharacterInventory.Update(Single deltaTime, Camera cam, Boolean isSubInventory) in C:\Users\danie\Documents\Projects\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Items\CharacterInventory.cs:line 641
   at Barotrauma.CharacterHUD.Update(Single deltaTime, Character character, Camera cam) in C:\Users\danie\Documents\Projects\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Characters\CharacterHUD.cs:line 128
   at Barotrauma.Character.UpdateControlled(Single deltaTime, Camera cam) in C:\Users\danie\Documents\Projects\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Characters\Character.cs:line 338
   at Barotrauma.Character.Update(Single deltaTime, Camera cam) in C:\Users\danie\Documents\Projects\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 2338
   at Barotrauma.AICharacter.Update(Single deltaTime, Camera cam) in C:\Users\danie\Documents\Projects\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\AICharacter.cs:line 47
   at Barotrauma.Character.UpdateAll(Single deltaTime, Camera cam) in C:\Users\danie\Documents\Projects\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 2224
   at Barotrauma.GameScreen.Update(Double deltaTime) in C:\Users\danie\Documents\Projects\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 171
   at Barotrauma.GameMain.Update(GameTime gameTime) in C:\Users\danie\Documents\Projects\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 967
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in C:\Users\danie\Documents\Projects\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 651
   at Microsoft.Xna.Framework.Game.Tick() in C:\Users\danie\Documents\Projects\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in C:\Users\danie\Documents\Projects\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in C:\Users\danie\Documents\Projects\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in C:\Users\danie\Documents\Projects\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in C:\Users\danie\Documents\Projects\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58
```

**Comment by Kaillera** [comment]
Mine was SP too

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a0e92cd77ff9c12e84e3bbab5207f63c56af86ec. Steps to repro:
1. Select and start a salvage mission (either artifact or a wreck salvage)
2. Return back to the outpost without salvaging the item
3. Select the mission again and load the next level
4. Try to pick up the item

**Comment by Rokvach** [comment]
Working correctly, closing.
