### ISSUE TITLE
[Unstable 0.1004.0.0] Voting sometimes causes a mass disconnection

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#3184]
Not fully sure as to what causes it, but when the voting finishes it will sometimes cause all the client to crash from the server

We had 2 players on the round and a third player either joining during the vote or being a spectator when the voting ended. 

```
Error while reading a message from server. {Object reference not set to an instance of an object.}
   at Barotrauma.VotingInterface.GetSubmarineVoteResultMessage(SubmarineInfo info, VoteType type, String yesVoteString, String noVoteString, Boolean votePassed) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GUI\VotingInterface.cs:line 205
   at Barotrauma.Voting.ClientRead(IReadMessage inc) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Networking\Voting.cs:line 276
   at Barotrauma.Networking.GameClient.ReadLobbyUpdate(IReadMessage inc) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 1917
   at Barotrauma.Networking.GameClient.ReadDataMessage(IReadMessage inc) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 713
   at Barotrauma.Networking.SteamP2PClientPeer.Update(Single deltaTime) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Networking\Primitives\Peers\SteamP2PClientPeer.cs:line 196
   at Barotrauma.Networking.GameClient.Update(Single deltaTime) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 589
```

**Comment by Rokvach** [comment]
Voting works without any issues to the players that are on the server on the time of the vote, but haven't been able to test yet what happens if a player joins in to the server while vote is in progress.

**Comment by Rokvach** [comment]
I did receive this error when I tried to rejoin a server while voting was active, however I have no idea if the error is related to the voting as I can't be 100% sure if the voting was still ongoing when I returned to the server

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/6d7a8716-3368-4aa7-8297-24251af8506e)

**Comment by Rokvach** [comment]
Haven't encountered further issues with this, it is quite rare to encounter the issue during regular gameplay, I think its better to just wait for the patch to come out and see if we receive any further information if this is still an issue or not. Closing.
