### ISSUE TITLE
[Unstable 0.1005.0.0] All clients and server crashed when multiple players were using the switch terminal

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#3198]
Not sure about the reproduction, I was clicking around the sub switch terminal and Hubismal was also using it, I think he tried to switch to a different submarine and as soon as I selected a submarine everyone crashed.  

Client crash:

```
Barotrauma Client crash report (generated on 23.6.2020 19:44:00)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


49932678F465034F109C8D44059DB930


Game version 0.1005.0.0 (UnstableWindows, branch feature/campaign-groundwork, revision ce7ef3f2a)
Graphics mode: 2560x1440 (BorderlessWindowed)
VSync OFF
Language: English
Selected content packages: Vanilla 0.9
Level seed: Erlangshen
Loaded submarine: Dugong (3902A7EF0B6B99694D71EDE338221228)
Selected screen: Barotrauma.GameScreen
SteamManager initialized


System info:
    Operating system: Microsoft Windows NT 10.0.18362.0 64 bit
    GPU name: NVIDIA GeForce GTX 980 Ti
    Display mode: {Width:2560 Height:1440 Format:Color AspectRatio:1,7777778}
    GPU status: Normal


Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void SelectSubmarine(Barotrauma.SubmarineInfo, Microsoft.Xna.Framework.Rectangle)
Stack trace: 
   at Barotrauma.SubmarineSelection.SelectSubmarine(SubmarineInfo info, Rectangle backgroundRect) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GUI\SubmarineSelection.cs:line 496
   at Barotrauma.SubmarineSelection.<>c__DisplayClass58_1.<RefreshSubmarineDisplay>b__0(GUIButton button, Object userData) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GUI\SubmarineSelection.cs:line 323
   at Barotrauma.GUIButton.Update(Single deltaTime) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIButton.cs:line 234
   at Barotrauma.GUIComponent.UpdateAuto(Single deltaTime) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIComponent.cs:line 442
   at Barotrauma.GUI.<>c__DisplayClass142_0.<Update>b__0(GUIComponent c) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1167
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Barotrauma.GUI.Update(Single deltaTime) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1167
   at Barotrauma.GameMain.Update(GameTime gameTime) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 983
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58
```

Server Crash:
```
Barotrauma Dedicated Server crash report (generated on 23.6.2020 19:43:58)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


Game version 0.1005.0.0 (UnstableWindows, branch feature/campaign-groundwork, revision ce7ef3f2a)
Language: English
Selected content packages: Vanilla 0.9
Level seed: Erlangshen
Loaded submarine: Dugong (6B491B880ABC08A73EBB9E98C05C72F0)
Selected screen: Barotrauma.GameScreen
Server (Round had started)


System info:
    Operating system: Microsoft Windows NT 6.2.9200.0 64 bit


Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Boolean <SwitchSubmarine>b__0(Barotrauma.SubmarineInfo)
Stack trace: 
   at Barotrauma.GameSession.<>c__DisplayClass52_0.<SwitchSubmarine>b__0(SubmarineInfo s) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameSession.cs:line 222
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Barotrauma.GameSession.SwitchSubmarine(SubmarineInfo newSubmarine, Int32 cost) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameSession.cs:line 222
   at Barotrauma.Networking.GameServer.SwitchSubmarine() in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaServer\ServerSource\Networking\GameServer.cs:line 3026
   at Barotrauma.Networking.GameServer.Update(Single deltaTime) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaServer\ServerSource\Networking\GameServer.cs:line 394
   at Barotrauma.GameMain.Run() in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaServer\ServerSource\GameMain.cs:line 354
   at Barotrauma.Program.Main(String[] args) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaServer\ServerSource\Program.cs:line 48


Last debug messages:
   23.6.2020 19:43:58 - [23.6.2020 19:43:58]
  Saving banlist
   23.6.2020 19:43:54 - [23.6.2020 19:43:54]
  Rokvach: I didnt see it either
   23.6.2020 19:43:53 - [23.6.2020 19:43:53]
  Leo Sagan placed Toolbox in Duffel Bag (ID: 1591)
   23.6.2020 19:43:52 - [23.6.2020 19:43:52]
  Leo Sagan placed Stun Baton in Duffel Bag (ID: 1591)
   23.6.2020 19:43:51 - [23.6.2020 19:43:51]
  Leo Sagan placed SMG in Duffel Bag (ID: 1591)
   23.6.2020 19:43:49 - [23.6.2020 19:43:49]
  Leo Sagan placed Welding Tool in Duffel Bag (ID: 1591)
   23.6.2020 19:43:48 - [23.6.2020 19:43:48]
  Leo Sagan placed Bandage in Duffel Bag (ID: 1591)
   23.6.2020 19:43:47 - [23.6.2020 19:43:47]
  Leo Sagan placed Plasma Cutter in Duffel Bag (ID: 1591)
   23.6.2020 19:43:45 - [23.6.2020 19:43:45]
  Leo Sagan placed Stun Grenade in Duffel Bag (ID: 1591)
   23.6.2020 19:43:45 - [23.6.2020 19:43:45]
  Hub: i initaited a vote to switch to dugong but the dialogue doesn't even appear for me
   23.6.2020 19:43:44 - [23.6.2020 19:43:44]
  Leo Sagan placed Riot Helmet in Duffel Bag (ID: 1591)
   23.6.2020 19:43:42 - [23.6.2020 19:43:42]
  Leo Sagan picked up Riot Helmet
   23.6.2020 19:43:24 - [23.6.2020 19:43:24]
  Leo Sagan dropped Duffel Bag
   23.6.2020 19:43:04 - [23.6.2020 19:43:04]
  Rokvach: So its working correctly
```

**Comment by Regalis11** [comment]
Could not figure out a way to reproduce this, but the stack trace seems to imply that GameMain.GameSession was somehow null here:
![ftndyytftyj](https://user-images.githubusercontent.com/14351070/85513991-3a274d00-b604-11ea-8e4e-30cc2fd503c6.png)

I added some logging in https://github.com/Regalis11/Barotrauma-development/commit/9a8065dca467d53d1d5a4f502836f7b2e4c8e040 to diagnose how that can happen

**Comment by Rokvach** [comment]
I tried to reproduce this issue by doing the same exact thing which previously triggered this issue, but was unable to reproduce it.

**Comment by Regalis11** [comment]
I think we can close this and reopen if it reoccurs
