### ISSUE TITLE
Unable to load shared library 'freetype6' or one of its dependencies

### ISSUE THREAD

**Issue by Areso** [Regalis11/Barotrauma#3225]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Environment**  
Ubuntu 16.04 64 bit LTS with Unity

**Description**
It is crashed immediatly after showing the loading screen

**Steps To Reproduce**
Installed from Steam, run, got crash

**Crash report**
```
﻿Barotrauma Client crash report (generated on 06/26/2020 19:59:17)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


To prevent further startup errors, installed mods will be disabled the next time you launch the game.


DEA772B0BFA3ECD89C6536379D06C51F


Game version 0.9.10.0 (ReleaseLinux, branch release, revision 2876b0a66)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla 0.9
Level seed: no level loaded
Loaded submarine: None
Selected screen: None
SteamManager initialized


System info:
    Operating system: Unix 4.15.0.106 64 bit
    GPU name: 
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal


Exception: Loading was interrupted due to an error. (Barotrauma.GameMain+LoadingException)
Target site: Void Update(Microsoft.Xna.Framework.GameTime)
Stack trace: 
   at Barotrauma.GameMain.Update(GameTime gameTime) in /home/joonas/Barotrauma/Barotrauma/BarotraumaClient/ClientSource/GameMain.cs:line 790
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in /home/joonas/Barotrauma/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 654
   at Microsoft.Xna.Framework.Game.Tick() in /home/joonas/Barotrauma/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in /home/joonas/Barotrauma/Libraries/MonoGame.Framework/Src/MonoGame.Framework/SDL/SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in /home/joonas/Barotrauma/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in /home/joonas/Barotrauma/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in /home/joonas/Barotrauma/Barotrauma/BarotraumaClient/ClientSource/Program.cs:line 59


InnerException: Unable to load shared library 'freetype6' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libfreetype6: cannot open shared object file: No such file or directory
Target site: SharpFont.Error FT_Init_FreeType(IntPtr ByRef)
Stack trace: 
   at SharpFont.FT.FT_Init_FreeType(IntPtr& alibrary)
   at SharpFont.Library..ctor() in /home/joonas/Barotrauma/Libraries/SharpFont/Source/SharpFontShared/Library.cs:line 77
   at Barotrauma.ScalableFont..ctor(String filename, UInt32 size, GraphicsDevice gd, Boolean dynamicLoading, Boolean isCJK) in /home/joonas/Barotrauma/Barotrauma/BarotraumaClient/ClientSource/Fonts/ScalableFont.cs:line 80
   at Barotrauma.GUIStyle.LoadFont(XElement element, GraphicsDevice graphicsDevice) in /home/joonas/Barotrauma/Barotrauma/BarotraumaClient/ClientSource/GUI/GUIStyle.cs:line 329
   at Barotrauma.GUIStyle..ctor(XElement element, GraphicsDevice graphicsDevice) in /home/joonas/Barotrauma/Barotrauma/BarotraumaClient/ClientSource/GUI/GUIStyle.cs:line 210
   at Barotrauma.GUI.Init(GameWindow window, IEnumerable`1 selectedContentPackages, GraphicsDevice graphicsDevice) in /home/joonas/Barotrauma/Barotrauma/BarotraumaClient/ClientSource/GUI/GUI.cs:line 245
   at Barotrauma.GameMain.Load(Boolean isSeparateThread)+MoveNext() in /home/joonas/Barotrauma/Barotrauma/BarotraumaClient/ClientSource/GameMain.cs:line 452
   at Barotrauma.CoroutineManager.ExecuteCoroutineThread(CoroutineHandle handle) in /home/joonas/Barotrauma/Barotrauma/BarotraumaShared/SharedSource/CoroutineManager.cs:line 167
Last debug messages:
[06/26/2020 19:59:17] Coroutine "Load" has failed
[06/26/2020 19:59:17] Coroutine "Load" has thrown an exception {Unable to load shared library 'freetype6' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libfreetype6: cannot open shared object file: No such file or directory}
   at SharpFont.FT.FT_Init_FreeType(IntPtr& alibrary)
   at SharpFont.Library..ctor() in /home/joonas/Barotrauma/Libraries/SharpFont/Source/SharpFontShared/Library.cs:line 77
   at Barotrauma.ScalableFont..ctor(String filename, UInt32 size, GraphicsDevice gd, Boolean dynamicLoading, Boolean isCJK) in /home/joonas/Barotrauma/Barotrauma/BarotraumaClient/ClientSource/Fonts/ScalableFont.cs:line 80
   at Barotrauma.GUIStyle.LoadFont(XElement element, GraphicsDevice graphicsDevice) in /home/joonas/Barotrauma/Barotrauma/BarotraumaClient/ClientSource/GUI/GUIStyle.cs:line 329
   at Barotrauma.GUIStyle..ctor(XElement element, GraphicsDevice graphicsDevice) in /home/joonas/Barotrauma/Barotrauma/BarotraumaClient/ClientSource/GUI/GUIStyle.cs:line 210
   at Barotrauma.GUI.Init(GameWindow window, IEnumerable`1 selectedContentPackages, GraphicsDevice graphicsDevice) in /home/joonas/Barotrauma/Barotrauma/BarotraumaClient/ClientSource/GUI/GUI.cs:line 245
   at Barotrauma.GameMain.Load(Boolean isSeparateThread)+MoveNext() in /home/joonas/Barotrauma/Barotrauma/BarotraumaClient/ClientSource/GameMain.cs:line 452
   at Barotrauma.CoroutineManager.ExecuteCoroutineThread(CoroutineHandle handle) in /home/joonas/Barotrauma/Barotrauma/BarotraumaShared/SharedSource/CoroutineManager.cs:line 167
[06/26/2020 19:59:16] Playing the splash screen "Content/SplashScreens/Splash_UTG.webm" failed. {Unable to load shared library 'webm_mem_playback_x64.so' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libwebm_mem_playback_x64.so: cannot open shared object file: No such file or directory}
   at Barotrauma.Media.Video.Internal.loadVideo(String filename)
   at Barotrauma.Media.Video..ctor(GraphicsDevice graphicsDevice, SoundManager soundManager, String filename) in /home/joonas/Barotrauma/Barotrauma/BarotraumaClient/ClientSource/Media/Video.cs:line 83
   at Barotrauma.Media.Video.Load(GraphicsDevice graphicsDevice, SoundManager soundManager, String filename) in /home/joonas/Barotrauma/Barotrauma/BarotraumaClient/ClientSource/Media/Video.cs:line 74
   at Barotrauma.LoadingScreen.DrawSplashScreen(SpriteBatch spriteBatch, GraphicsDevice graphics) in /home/joonas/Barotrauma/Barotrauma/BarotraumaClient/ClientSource/GUI/LoadingScreen.cs:line 330
[06/26/2020 19:59:16] Attempting to open ALC device "OpenAL Soft"
[06/26/2020 19:59:15] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[06/26/2020 19:59:15] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[06/26/2020 19:59:14] Logged in as Areso (SteamID STEAM_1:0:59213852)
```

**Comment by sam-jackson** [comment]
I also had the same issue. It looks like the steam package is missing `libpng16`? I was able to resolve by installing the `libpng16-16` via apt.

**Comment by Areso** [comment]
I confirm, installation of this package allows me to run the game on my Ubuntu 16.04.

**Comment by juanjp600** [comment]
Reopening since libpng16 is an extraneous dependency, and we shouldn't require users to manually install more than Steam and its required packages for the game to run.

I've rebuilt libfreetype6.so without this dependency, this should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/66a5484ad17491adf3b8792b2a8b4ae84d3e150c.

**Comment by Rokvach** [comment]
Markus tested this on linux and didn't find anything, closing.
