### ISSUE TITLE
Exception when trying to query server rules

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#3251]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Occurred during community testing, a player would get the following error when trying to scan for servers:
```
QueryServerRules (GetServers,  [server name here], [IP address here])
   at Barotrauma.TaskPool.AddInternal(String name, Task task, Action`2 onCompletion, Object userdata) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Utils\TaskPool.cs:line 48
   at Barotrauma.Steam.SteamManager.<>c__DisplayClass17_0.<GetServers>b__2(ServerInfo info, Boolean responsive) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Networking\SteamManager.cs:line 368
   at Barotrauma.Steam.SteamManager.<>c__DisplayClass17_0.<GetServers>b__3(ServerInfo info) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Networking\SteamManager.cs:line 369
   at Steamworks.ServerList.Base.OnServer(ServerInfo serverInfo, Boolean responded) in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\Facepunch.Steamworks\ServerList\Base.cs:line 203
   at Steamworks.ServerList.Base.<UpdateResponsive>b__36_0(Int32 x) in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\Facepunch.Steamworks\ServerList\Base.cs:line 176
   at System.Collections.Generic.List`1.RemoveAll(Predicate`1 match)
   at Steamworks.ServerList.Base.UpdateResponsive() in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\Facepunch.Steamworks\ServerList\Base.cs:line 178
   at Steamworks.ServerList.Base.RunQueryAsync(Single timeoutSeconds) in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\Facepunch.Steamworks\ServerList\Base.cs:line 86
```

**Steps To Reproduce**
Unknown

**Version**
v0.10.0.0 RC 1

**Comment by Regalis11** [comment]
@juanjp600 Is https://github.com/Regalis11/Barotrauma-development/commit/38f1275 related to this?

**Comment by juanjp600** [comment]
Yep, moving to Review/QA

**Comment by Rokvach** [comment]
No encounters in Unstable 0.10.2.0, closing.
