### ISSUE TITLE
crash from indoors steering manager

### ISSUE THREAD

**Issue by NilanthAnimosus** [Regalis11/Barotrauma#326]
Version 0.8.0.4 + commit b49f47d3d9508b7e13a103fbf70bdb2c6222cfae
Was using my modification, but the line numbers are identical and the code for these classes isn't really changed by me in any particular way.

I've had 2 crashes so far from only this class, nothing else has caused a crash on my server for days.

The error stack from the crash report is:
```
Exception: Object reference not set to an instance of an object.
Target site: Microsoft.Xna.Framework.Vector2 DiffToCurrentNode()
Stack trace: 
   at Barotrauma.IndoorsSteeringManager.DiffToCurrentNode() in F:\Barotrauma\BT NilEdit\Barotrauma---Nilanths-Edits\Barotrauma\BarotraumaShared\Source\Characters\AI\IndoorsSteeringManager.cs:line 172
   at Barotrauma.IndoorsSteeringManager.DoSteeringSeek(Vector2 target, Single speed) in F:\Barotrauma\BT NilEdit\Barotrauma---Nilanths-Edits\Barotrauma\BarotraumaShared\Source\Characters\AI\IndoorsSteeringManager.cs:line 89
   at Barotrauma.SteeringManager.SteeringSeek(Vector2 targetSimPos, Single speed) in F:\Barotrauma\BT NilEdit\Barotrauma---Nilanths-Edits\Barotrauma\BarotraumaShared\Source\Characters\AI\SteeringManager.cs:line 40
   at Barotrauma.EnemyAIController.UpdateAttack(Single deltaTime) in F:\Barotrauma\BT NilEdit\Barotrauma---Nilanths-Edits\Barotrauma\BarotraumaShared\Source\Characters\AI\EnemyAIController.cs:line 378
   at Barotrauma.EnemyAIController.Update(Single deltaTime) in F:\Barotrauma\BT NilEdit\Barotrauma---Nilanths-Edits\Barotrauma\BarotraumaShared\Source\Characters\AI\EnemyAIController.cs:line 191
   at Barotrauma.AICharacter.Update(Single deltaTime, Camera cam) in F:\Barotrauma\BT NilEdit\Barotrauma---Nilanths-Edits\Barotrauma\BarotraumaShared\Source\Characters\AICharacter.cs:line 77
   at Barotrauma.Character.UpdateAll(Single deltaTime, Camera cam) in F:\Barotrauma\BT NilEdit\Barotrauma---Nilanths-Edits\Barotrauma\BarotraumaShared\Source\Characters\Character.cs:line 1830
   at Barotrauma.GameScreen.Update(Double deltaTime) in F:\Barotrauma\BT NilEdit\Barotrauma---Nilanths-Edits\Barotrauma\BarotraumaShared\Source\Screens\GameScreen.cs:line 151
   at Barotrauma.GameMain.Update(GameTime gameTime) in F:\Barotrauma\BT NilEdit\Barotrauma---Nilanths-Edits\Barotrauma\BarotraumaClient\Source\GameMain.cs:line 469
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at MonoGame.Framework.WinFormsGameWindow.RunLoop()
   at MonoGame.Framework.WinFormsGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Barotrauma.Program.Main() in F:\Barotrauma\BT NilEdit\Barotrauma---Nilanths-Edits\Barotrauma\BarotraumaClient\Source\Program.cs:line 47
```

This points to the code inside: 
```csharp
//we can safely skip to the next waypoint if the character is at a safe height above the floor,
                    //or if the next waypoint in the path is also on ladders
                    if ((heightFromFloor > 0.0f && heightFromFloor < collider.height * 1.5f) ||  //This is the crash line
                        (currentPath.NextNode != null && currentPath.NextNode.Ladders != null))
                    {
                        if (currentPath.NextNode.Ladders == null)
                        {
                            character.AnimController.Anim = AnimController.Animation.None;
                        }
                        currentPath.SkipToNextNode();
                    }
```

Judging by the line number I believe the collider can potentially be null somehow?

**Comment by Regalis11** [comment]
That's bizarre. The collider variable is also used on line 159 so if it's null the game should crash there. 🤔

**Comment by NilanthAnimosus** [comment]
I added additional debug code to this, and this is what came up:

![image](http://puu.sh/zEGhj/e09923e7a3.jpg)
