### ISSUE TITLE
[Unstable 0.10.0.0] Can't start multiplayer campaign if you have a custom sub set as a purchasable sub

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#3261]
Repro steps:
1. Subscribe to a submarine in workshop
2. Open the sub up in sub editor
3. Add a price and set a class for the sub
4. Save the sub
5. Host a server from main menu
6. Create new campaign save and select the newly saved submarine as a purchasable submarine
7. Hit start

Can't select a custom submarine as purchasable sub when creating a multiplayer campaign, throws a error when trying. 

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/d84d81c4-54b3-4ff6-88c4-02373c522ae8)

Verbose logging from host side (This just repeats endlessly):

```
Received file transfer message on the same machine: 
  File: C:\Users\RoniK\AppData\Local\Daedalic Entertainment GmbH\Barotrauma\Multiplayer\Custom sub test 2.save
  ID: 1
Loading game session doc: C:\Users\RoniK\AppData\Local\Daedalic Entertainment GmbH\Barotrauma\Multiplayer\Custom sub test 2.save
Decompressing C:\Users\RoniK\AppData\Local\Daedalic Entertainment GmbH\Barotrauma\Multiplayer\Custom sub test 2.save to C:\Users\RoniK\AppData\Local\Daedalic Entertainment GmbH\Barotrauma\temp...
Loading save file for an existing game session (C:\Users\RoniK\AppData\Local\Daedalic Entertainment GmbH\Barotrauma\Multiplayer\Custom sub test 2.save)
Decompressing C:\Users\RoniK\AppData\Local\Daedalic Entertainment GmbH\Barotrauma\Multiplayer\Custom sub test 2.save to C:\Users\RoniK\AppData\Local\Daedalic Entertainment GmbH\Barotrauma\temp...
Created brand new upgrade manager.
Restored upgrade manager from save file, (68 pending upgrades).
Campaign save received (C:\Users\RoniK\AppData\Local\Daedalic Entertainment GmbH\Barotrauma\Multiplayer\Custom sub test 2.save), save ID 1
Decompressing message: 1008 to 1146
Decompressing message: 1008 to 1146
[RagdollParams] Loading ragdoll from Content\Characters\Human\Ragdolls\HumanDefaultRagdoll.xml.
Decompressing message: 1008 to 1146
Decompressing message: 1008 to 1146
Decompressing message: 1008 to 1146
Decompressing message: 1008 to 1146
Decompressing message: 1008 to 1146
Decompressing message: 1008 to 1146
Decompressing message: 1008 to 1146
Decompressing message: 1008 to 1146
Decompressing message: 1008 to 1146
Decompressing message: 1008 to 1146
Decompressing message: 1008 to 1146
Decompressing message: 1008 to 1146
Decompressing message: 1008 to 1146
Decompressing message: 1008 to 1146
SteamManager authenticating Steam client 76561198049098774
Decompressing message: 1008 to 1146
Decompressing message: 1008 to 1146
Decompressing message: 1008 to 1146
Decompressing message: 1008 to 1146
Decompressing message: 1008 to 1146
76561198049098774 validation: OK, True
Decompressing message: 1008 to 1146
Decompressing message: 1008 to 1146
Decompressing message: 1008 to 1146
Decompressing message: 1008 to 1146
Decompressing message: 1008 to 1146
Decompressing message: 1008 to 1146
Decompressing message: 1008 to 1146
Decompressing message: 1008 to 1146
Decompressing message: 1008 to 1146
Decompressing message: 1008 to 1146
Decompressing message: 1008 to 1146
Decompressing message: 1008 to 1146
Decompressing message: 1008 to 1146
Decompressing message: 1008 to 1146
Decompressing message: 1008 to 1146
Decompressing message: 1008 to 1146
Decompressing message: 1008 to 1146
Decompressing message: 1008 to 1146
WARNING: message length comes close to exceeding MTU, forcing reliable send (1535 bytes)
Decompressing message: 1008 to 1146
Decompressing message: 1009 to 1146
Decompressing message: 1009 to 1146
Decompressing message: 1009 to 1146
Decompressing message: 1009 to 1146
Decompressing message: 1009 to 1146
Decompressing message: 1009 to 1146
Decompressing message: 1009 to 1146
Decompressing message: 1009 to 1146
Decompressing message: 1009 to 1146
Decompressing message: 1009 to 1146
Decompressing message: 1009 to 1146
Decompressing message: 1009 to 1146
Decompressing message: 1009 to 1146
Decompressing message: 1009 to 1146
Decompressing message: 1009 to 1146
Decompressing message: 1009 to 1146
Decompressing message: 1009 to 1146
Decompressing message: 1009 to 1146
Decompressing message: 1009 to 1146
Decompressing message: 1009 to 1146
Decompressing message: 1009 to 1146
Decompressing message: 1009 to 1146
Decompressing message: 1009 to 1146
Decompressing message: 1009 to 1146
Decompressing message: 1009 to 1146
Decompressing message: 1009 to 1146
Decompressing message: 1009 to 1146
Decompressing message: 1009 to 1146
Decompressing message: 1009 to 1146
Decompressing message: 1009 to 1146
Decompressing message: 1009 to 1146
Decompressing message: 1009 to 1146
Decompressing message: 1009 to 1146
Decompressing message: 1009 to 1146
Decompressing message: 1009 to 1146
Decompressing message: 1009 to 1146
Decompressing message: 1009 to 1146
Decompressing message: 1009 to 1146
```

**Comment by Regalis11** [comment]
Need steps to repro

**Comment by Rokvach** [comment]
Duplicate of #3262 closing.

**Comment by Regalis11** [comment]
Not a duplicate. In #3262 the issue is that custom submarines can't be selected as purchaseable, while this one is about starting a round with a custom sub.

**Comment by Rokvach** [comment]
I switched to bugfixes branch from Unstable an still got the same error I kept getting on Unstable to the "outposttest" part doesn't seem to be caused by my files

```
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading a level. Could not find level generation params with the ID "outposttest".
Error while loading the map (start location index out of bounds).
Error while loading the map (end location index out of bounds).
Error while reading a message from server. {Index was outside the bounds of the array.}
   at Barotrauma.Map.RemoveFogOfWar(Location location, Boolean removeFromAdjacentLocations) in C:\Users\RoniK\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Map\Map\Map.cs:line 192
   at Barotrauma.Map.LocationChanged(Location prevLocation, Location newLocation) in C:\Users\RoniK\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Map\Map\Map.cs:line 188
   at Barotrauma.Map.SetLocation(Int32 index) in C:\Users\RoniK\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Map\Map\Map.cs:line 558
   at Barotrauma.Map.LoadState(XElement element, Boolean showNotifications) in C:\Users\RoniK\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Map\Map\Map.cs:line 779
   at Barotrauma.Map.Load(CampaignMode campaign, XElement element) in C:\Users\RoniK\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Map\Map\Map.cs:line 768
   at Barotrauma.MultiPlayerCampaign.Load(XElement element) in C:\Users\RoniK\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameModes\MultiPlayerCampaign.cs:line 127
   at Barotrauma.MultiPlayerCampaign.LoadState(String filePath) in C:\Users\RoniK\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GameSession\GameModes\MultiPlayerCampaign.cs:line 735
   at Barotrauma.Networking.GameClient.OnFileReceived(FileTransferIn transfer) in C:\Users\RoniK\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 2425
   at Barotrauma.Networking.FileReceiver.ReadMessage(IReadMessage inc) in C:\Users\RoniK\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Networking\FileTransfer\FileReceiver.cs:line 312
   at Barotrauma.Networking.GameClient.ReadDataMessage(IReadMessage inc) in C:\Users\RoniK\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 907
   at Barotrauma.Networking.SteamP2POwnerPeer.HandleDataMessage(IReadMessage inc) in C:\Users\RoniK\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Networking\Primitives\Peers\SteamP2POwnerPeer.cs:line 0
   at Barotrauma.Networking.SteamP2POwnerPeer.Update(Single deltaTime) in C:\Users\RoniK\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Networking\Primitives\Peers\SteamP2POwnerPeer.cs:line 229
   at Barotrauma.Networking.GameClient.Update(Single deltaTime) in C:\Users\RoniK\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 589
```

**Comment by Rokvach** [comment]
Managed to solve the above error in the comment, now the new error I receive is this

```
Couldn't load xml document "C:\Users\RoniK\AppData\Local\Daedalic Entertainment GmbH\Barotrauma\temp\gamesession.xml"! {Could not find file 'C:\Users\RoniK\AppData\Local\Daedalic Entertainment GmbH\Barotrauma\temp\gamesession.xml'.}
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.FinishInitUriString()
   at System.Xml.XmlTextReaderImpl..ctor(String uriStr, XmlReaderSettings settings, XmlParserContext context, XmlResolver uriResolver)
   at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
   at System.Xml.XmlReader.Create(String inputUri, XmlReaderSettings settings)
   at System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
   at Barotrauma.XMLExtensions.TryLoadXml(String filePath) in C:\Users\RoniK\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Serialization\XMLExtensions.cs:line 23
Error while reading a message from server. {Object reference not set to an instance of an object.}
   at Barotrauma.Networking.GameClient.OnFileReceived(FileTransferIn transfer) in C:\Users\RoniK\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 2450
   at Barotrauma.Networking.FileReceiver.ReadMessage(IReadMessage inc) in C:\Users\RoniK\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Networking\FileTransfer\FileReceiver.cs:line 312
   at Barotrauma.Networking.GameClient.ReadDataMessage(IReadMessage inc) in C:\Users\RoniK\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 907
   at Barotrauma.Networking.SteamP2POwnerPeer.HandleDataMessage(IReadMessage inc) in C:\Users\RoniK\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Networking\Primitives\Peers\SteamP2POwnerPeer.cs:line 0
   at Barotrauma.Networking.SteamP2POwnerPeer.Update(Single deltaTime) in C:\Users\RoniK\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Networking\Primitives\Peers\SteamP2POwnerPeer.cs:line 229
   at Barotrauma.Networking.GameClient.Update(Single deltaTime) in C:\Users\RoniK\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 589
```

**Comment by Regalis11** [comment]
Fixed the 2nd issue in https://github.com/Regalis11/Barotrauma-development/commit/e02686373dd8a6b0cfb4688e052667d70f10ee0e, need to test and see if it also got rid of the 1st issue

**Comment by Rokvach** [comment]
Wasn't able to reproduce the issue after the fix, working correctly. Closing.
