### ISSUE TITLE
barotrauma crash

### ISSUE THREAD

**Issue by teodoj** [Regalis11/Barotrauma#344]
```Barotrauma Client crash report (generated on 25. 03. 2018 13:05:13)


Barotrauma seems to have crashed. Sorry for the inconvenience! 
If you'd like to help fix the bug that caused the crash, please send this file to the developers on the Undertow Games forums.


Game version 0.8.0.5
Graphics mode: 1280x720 (BorderlessWindowed)
Selected content package: Vanilla 0.7
Level seed: tuto
Loaded submarine: TutorialSub (C0ADC92902CE378B9640FBFAE1199C3B)
Selected screen: Barotrauma.MainMenuScreen


System info:
    Operating system: Microsoft Windows NT 6.2.9200.0 64 bit
    GPU name: AMD Radeon(TM) R4 Graphics
    Display mode: {Width:1600 Height:900 Format:Color AspectRatio:1,777778}
    GPU status: Normal


Exception: Object reference not set to an instance of an object.
Target site: System.Collections.Generic.List`1[Barotrauma.RuinGeneration.RuinShape] GenerateStructures(System.Collections.Generic.List`1[Voronoi2.VoronoiCell])
Stack trace: 
   at Barotrauma.RuinGeneration.Ruin.GenerateStructures(List`1 caveCells) in E:\Barotrauma\Barotrauma\BarotraumaShared\Source\Map\Levels\Ruins\RuinGenerator.cs:line 427
   at Barotrauma.RuinGeneration.Ruin.Generate(VoronoiCell closestPathCell, List`1 caveCells, Rectangle area) in E:\Barotrauma\Barotrauma\BarotraumaShared\Source\Map\Levels\Ruins\RuinGenerator.cs:line 292
   at Barotrauma.RuinGeneration.Ruin..ctor(VoronoiCell closestPathCell, List`1 caveCells, Rectangle area) in E:\Barotrauma\Barotrauma\BarotraumaShared\Source\Map\Levels\Ruins\RuinGenerator.cs:line 197
   at Barotrauma.Level.GenerateRuin(List`1 mainPath) in E:\Barotrauma\Barotrauma\BarotraumaShared\Source\Map\Levels\Level.cs:line 862
   at Barotrauma.Level.Generate(Boolean mirror) in E:\Barotrauma\Barotrauma\BarotraumaShared\Source\Map\Levels\Level.cs:line 438
   at Barotrauma.GameSession.StartRound(Level level, Boolean reloadSub, Boolean loadSecondSub) in E:\Barotrauma\Barotrauma\BarotraumaShared\Source\GameSession\GameSession.cs:line 208
   at Barotrauma.Tutorials.TutorialType.Initialize() in E:\Barotrauma\Barotrauma\BarotraumaClient\Source\GameSession\GameModes\Tutorials\TutorialType.cs:line 42
   at Barotrauma.TutorialMode.StartTutorial(TutorialType tutorialType) in E:\Barotrauma\Barotrauma\BarotraumaClient\Source\GameSession\GameModes\Tutorials\TutorialMode.cs:line 14
   at Barotrauma.MainMenuScreen.TutorialButtonClicked(GUIButton button, Object obj) in E:\Barotrauma\Barotrauma\BarotraumaClient\Source\Screens\MainMenuScreen.cs:line 236
   at Barotrauma.GUIButton.Update(Single deltaTime) in E:\Barotrauma\Barotrauma\BarotraumaClient\Source\GUI\GUIButton.cs:line 210
   at Barotrauma.GUIComponent.Update(Single deltaTime) in E:\Barotrauma\Barotrauma\BarotraumaClient\Source\GUI\GUIComponent.cs:line 475
   at Barotrauma.MainMenuScreen.Update(Double deltaTime) in E:\Barotrauma\Barotrauma\BarotraumaClient\Source\Screens\MainMenuScreen.cs:line 310
   at Barotrauma.GameMain.Update(GameTime gameTime) in E:\Barotrauma\Barotrauma\BarotraumaClient\Source\GameMain.cs:line 414
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at MonoGame.Framework.WinFormsGameWindow.RunLoop()
   at MonoGame.Framework.WinFormsGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Barotrauma.Program.Main() in E:\Barotrauma\Barotrauma\BarotraumaClient\Source\Program.cs:line 41


Last debug messages:
   25. 03. 2018 13:05:12 - Particle prefab hydrosmokesmall not found!
   25. 03. 2018 13:05:12 - Particle prefab hydrosmoke not found!
   25. 03. 2018 13:05:12 - Particle prefab hydrosmokesmall not found!
   25. 03. 2018 13:05:12 - Particle prefab hydrosmoke not found!
   25. 03. 2018 13:05:12 - Particle prefab hydrosmokesmall not found!
   25. 03. 2018 13:05:12 - Particle prefab hydrosmoke not found!
   25. 03. 2018 13:05:11 - Particle prefab bubbles not found!
   25. 03. 2018 13:05:11 - Particle prefab bubbles not found!
   25. 03. 2018 13:05:11 - Particle prefab bubbles not found!
   25. 03. 2018 13:05:11 - Particle prefab bubbles not found!
   25. 03. 2018 13:05:10 - Particle prefab fleshsmoke not found!
   25. 03. 2018 13:05:10 - Particle prefab weldsmoke not found!
   25. 03. 2018 13:05:10 - Particle prefab weldsmoke not found!
   25. 03. 2018 13:05:10 - Particle prefab weldspark not found!
   25. 03. 2018 13:05:10 - Particle prefab weldspark not found!
   25. 03. 2018 13:05:10 - Particle prefab weld not found!
   25. 03. 2018 13:05:10 - Particle prefab fleshsmoke not found!
   25. 03. 2018 13:05:10 - Particle prefab weldsmoke not found!
   25. 03. 2018 13:05:10 - Particle prefab weldsmoke not found!
   25. 03. 2018 13:05:10 - Particle prefab weldspark not found!
   25. 03. 2018 13:05:10 - Particle prefab weldspark not found!
   25. 03. 2018 13:05:10 - Particle prefab weld not found!
   25. 03. 2018 13:05:10 - Particle prefab fleshsmoke not found!
   25. 03. 2018 13:05:10 - Particle prefab weldsmoke not found!
   25. 03. 2018 13:05:10 - Particle prefab weldsmoke not found!
   25. 03. 2018 13:05:10 - Particle prefab weldspark not found!
   25. 03. 2018 13:05:10 - Particle prefab weldspark not found!
   25. 03. 2018 13:05:10 - Particle prefab weld not found!
   25. 03. 2018 13:05:10 - Particle prefab fleshsmoke not found!
   25. 03. 2018 13:05:10 - Particle prefab plasmasmoke not found!
   25. 03. 2018 13:05:10 - Particle prefab plasmasmoke not found!
   25. 03. 2018 13:05:10 - Particle prefab plasmaspark not found!
   25. 03. 2018 13:05:10 - Particle prefab plasmaspark not found!
   25. 03. 2018 13:05:10 - Particle prefab plasma not found!
   25. 03. 2018 13:05:10 - Particle prefab fleshsmoke not found!
   25. 03. 2018 13:05:10 - Particle prefab plasmasmoke not found!
   25. 03. 2018 13:05:10 - Particle prefab plasmasmoke not found!
   25. 03. 2018 13:05:10 - Particle prefab plasmaspark not found!
   25. 03. 2018 13:05:10 - Particle prefab plasmaspark not found!
   25. 03. 2018 13:05:10 - Particle prefab plasma not found!
   25. 03. 2018 13:05:10 - Particle prefab fleshsmoke not found!
   25. 03. 2018 13:05:10 - Particle prefab plasmasmoke not found!
   25. 03. 2018 13:05:10 - Particle prefab plasmasmoke not found!
   25. 03. 2018 13:05:10 - Particle prefab plasmaspark not found!
   25. 03. 2018 13:05:10 - Particle prefab plasmaspark not found!
   25. 03. 2018 13:05:10 - Particle prefab plasma not found!
   25. 03. 2018 13:05:09 - Particle prefab bubbles not found!
   25. 03. 2018 13:05:09 - Particle prefab bubbles not found!
   25. 03. 2018 13:05:09 - Particle prefab bubbles not found!
   25. 03. 2018 13:05:09 - Particle prefab bubbles not found!
   25. 03. 2018 13:05:09 - Particle prefab fleshsmoke not found!
   25. 03. 2018 13:05:09 - Particle prefab weldsmoke not found!
   25. 03. 2018 13:05:09 - Particle prefab weldsmoke not found!
   25. 03. 2018 13:05:09 - Particle prefab weldspark not found!
   25. 03. 2018 13:05:09 - Particle prefab weldspark not found!
   25. 03. 2018 13:05:09 - Particle prefab weld not found!
   25. 03. 2018 13:05:09 - Particle prefab fleshsmoke not found!
   25. 03. 2018 13:05:09 - Particle prefab weldsmoke not found!
   25. 03. 2018 13:05:09 - Particle prefab weldsmoke not found!
   25. 03. 2018 13:05:09 - Particle prefab weldspark not found!
   25. 03. 2018 13:05:09 - Particle prefab weldspark not found!
   25. 03. 2018 13:05:09 - Particle prefab weld not found!
   25. 03. 2018 13:05:09 - Particle prefab fleshsmoke not found!
   25. 03. 2018 13:05:09 - Particle prefab weldsmoke not found!
   25. 03. 2018 13:05:09 - Particle prefab weldsmoke not found!
   25. 03. 2018 13:05:09 - Particle prefab weldspark not found!
   25. 03. 2018 13:05:09 - Particle prefab weldspark not found!
   25. 03. 2018 13:05:09 - Particle prefab weld not found!
   25. 03. 2018 13:05:09 - Particle prefab fleshsmoke not found!
   25. 03. 2018 13:05:09 - Particle prefab plasmasmoke not found!
   25. 03. 2018 13:05:09 - Particle prefab plasmasmoke not found!
   25. 03. 2018 13:05:09 - Particle prefab plasmaspark not found!
   25. 03. 2018 13:05:09 - Particle prefab plasmaspark not found!
   25. 03. 2018 13:05:09 - Particle prefab plasma not found!
   25. 03. 2018 13:05:09 - Particle prefab fleshsmoke not found!
   25. 03. 2018 13:05:09 - Particle prefab plasmasmoke not found!
   25. 03. 2018 13:05:09 - Particle prefab plasmasmoke not found!
   25. 03. 2018 13:05:09 - Particle prefab plasmaspark not found!
   25. 03. 2018 13:05:09 - Particle prefab plasmaspark not found!
   25. 03. 2018 13:05:09 - Particle prefab plasma not found!
   25. 03. 2018 13:05:09 - Particle prefab fleshsmoke not found!
   25. 03. 2018 13:05:09 - Particle prefab plasmasmoke not found!
   25. 03. 2018 13:05:09 - Particle prefab plasmasmoke not found!
   25. 03. 2018 13:05:09 - Particle prefab plasmaspark not found!
   25. 03. 2018 13:05:09 - Particle prefab plasmaspark not found!
   25. 03. 2018 13:05:09 - Particle prefab plasma not found!
   25. 03. 2018 13:05:03 - Enter "help" for a list of available console commands
```
just can you tell me how to fix it? redownload the game???

**Comment by Regalis11** [comment]
You seem to be using the "Vanilla 0.7" content package on version 0.8 of the game. Try selecting the "Vanilla 0.8" package in the settings.
