### ISSUE TITLE
Unauthorized access to RandSync.Server

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#3440]
Warning: Reported by Deus Vult on baro-tech-support channel 31.07.2020 8:24AM

> found problem i pressed retry while the thing was loading and it broke
> now my save of like 5 hours is basically corrupt

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/0a0599d1-6b42-4610-8e44-4a0dc019d628)

Crash: Reported by oksts2904 on baro-tech-support channel 30.07.2020 5:49 PM

```
Barotrauma Client crash report (generated on 7/30/2020 9:49:19 PM)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


90AB60D51DD92D51657C9BB21A665329


Game version 0.10.4.0 (ReleaseMac, branch release, revision 965c31410a)
Graphics mode: 1440x900 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla 0.9
Level seed: no level loaded
Loaded submarine: None
Selected screen: Barotrauma.ServerListScreen
SteamManager initialized


System info:
    Operating system: Unix 18.7.0.0 64 bit
    GPU name: 
    Display mode: {Width:1440 Height:900 Format:Color AspectRatio:1.6}
    GPU status: Normal


Exception: Unauthorized multithreaded access to RandSync.Server (System.Exception)
Target site: Void CheckRandThreadSafety(RandSync)
Stack trace: 
   at Barotrauma.Rand.CheckRandThreadSafety(RandSync sync) in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Barotrauma/BarotraumaShared/SharedSource/Utils/Rand.cs:line 44
   at Barotrauma.Rand.Range(Single minimum, Single maximum, RandSync sync) in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Barotrauma/BarotraumaShared/SharedSource/Utils/Rand.cs:line 51
   at Barotrauma.CharacterInfo.GetRandomGender() in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Barotrauma/BarotraumaShared/SharedSource/Characters/CharacterInfo.cs:line 544
   at Barotrauma.CharacterInfo..ctor(String speciesName, String name, JobPrefab jobPrefab, String ragdollFileName, Int32 variant) in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Barotrauma/BarotraumaShared/SharedSource/Characters/CharacterInfo.cs:line 459
   at Barotrauma.Networking.GameClient..ctor(String newName, String ip, UInt64 steamId, String serverName, Int32 ownerKey, Boolean steamP2POwner) in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Barotrauma/BarotraumaClient/ClientSource/Networking/GameClient.cs:line 246
   at Barotrauma.GameMain.Update(GameTime gameTime) in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Barotrauma/BarotraumaClient/ClientSource/GameMain.cs:line 859
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Libraries/MonoGame.Framework/Src/MonoGame.Framework/SDL/SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Barotrauma/BarotraumaClient/ClientSource/Program.cs:line 59


Last debug messages:
[7/30/2020 9:49:11 PM]  - Handheld Sonar(ID 987)
[7/30/2020 9:49:11 PM] Some items were not removed in Entity.RemoveAll:
[7/30/2020 9:49:11 PM]  - Handheld Sonar(ID 987)
[7/30/2020 9:49:11 PM] Some entities were not removed in Entity.RemoveAll:
[7/30/2020 9:49:11 PM] Attempting to remove an already removed item (Handheld Sonar)
   at System.Environment.get_StackTrace()
   at Barotrauma.Item.Remove() in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Barotrauma/BarotraumaShared/SharedSource/Items/Item.cs:line 2663
   at Barotrauma.Entity.RemoveAll() in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Barotrauma/BarotraumaShared/SharedSource/Map/Entity.cs:line 211
   at Barotrauma.Submarine.Unload() in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Barotrauma/BarotraumaShared/SharedSource/Map/Submarine.cs:line 1423
   at Barotrauma.MainMenuScreen.Select() in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Barotrauma/BarotraumaClient/ClientSource/Screens/MainMenuScreen.cs:line 441
   at Barotrauma.GameMain.QuitToMainMenu(Boolean save) in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Barotrauma/BarotraumaClient/ClientSource/GameMain.cs:line 1125
   at Barotrauma.GUI.QuitClicked(GUIButton button, Object obj) in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Barotrauma/BarotraumaClient/ClientSource/GUI/GUI.cs:line 2248
   at Barotrauma.GUI.<>c__DisplayClass181_0.<TogglePauseMenu>b__10(GUIButton btn, Object userData) in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Barotrauma/BarotraumaClient/ClientSource/GUI/GUI.cs:line 2230
   at Barotrauma.GUIButton.Update(Single deltaTime) in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Barotrauma/BarotraumaClient/ClientSource/GUI/GUIButton.cs:line 247
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Barotrauma.GUI.Update(Single deltaTime) in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Barotrauma/BarotraumaClient/ClientSource/GUI/GUI.cs:line 1218
   at Barotrauma.GameMain.Update(GameTime gameTime) in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Barotrauma/BarotraumaClient/ClientSource/GameMain.cs:line 990
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 651
   at Microsoft.Xna.Framework.Game.Tick() in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Libraries/MonoGame.Framework/Src/MonoGame.Framework/SDL/SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Barotrauma/BarotraumaClient/ClientSource/Program.cs:line 59
[7/30/2020 9:49:11 PM] Attempting to remove an already removed item (Handheld Sonar)
   at System.Environment.get_StackTrace()
   at Barotrauma.Item.Remove() in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Barotrauma/BarotraumaShared/SharedSource/Items/Item.cs:line 2663
   at Barotrauma.Entity.RemoveAll() in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Barotrauma/BarotraumaShared/SharedSource/Map/Entity.cs:line 178
   at Barotrauma.Submarine.Unload() in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Barotrauma/BarotraumaShared/SharedSource/Map/Submarine.cs:line 1423
   at Barotrauma.MainMenuScreen.Select() in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Barotrauma/BarotraumaClient/ClientSource/Screens/MainMenuScreen.cs:line 441
   at Barotrauma.GameMain.QuitToMainMenu(Boolean save) in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Barotrauma/BarotraumaClient/ClientSource/GameMain.cs:line 1125
   at Barotrauma.GUI.QuitClicked(GUIButton button, Object obj) in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Barotrauma/BarotraumaClient/ClientSource/GUI/GUI.cs:line 2248
   at Barotrauma.GUI.<>c__DisplayClass181_0.<TogglePauseMenu>b__10(GUIButton btn, Object userData) in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Barotrauma/BarotraumaClient/ClientSource/GUI/GUI.cs:line 2230
   at Barotrauma.GUIButton.Update(Single deltaTime) in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Barotrauma/BarotraumaClient/ClientSource/GUI/GUIButton.cs:line 247
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Barotrauma.GUI.Update(Single deltaTime) in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Barotrauma/BarotraumaClient/ClientSource/GUI/GUI.cs:line 1218
   at Barotrauma.GameMain.Update(GameTime gameTime) in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Barotrauma/BarotraumaClient/ClientSource/GameMain.cs:line 990
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 651
   at Microsoft.Xna.Framework.Game.Tick() in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Libraries/MonoGame.Framework/Src/MonoGame.Framework/SDL/SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Barotrauma/BarotraumaClient/ClientSource/Program.cs:line 59
[7/30/2020 9:48:51 PM] Transitioning to SermilikWorm Cave (current location: The city of Worm Cave, selected location: Sermilik, leaving sub: Dugong, at start: True, at end: False, transition type: LeaveLocation)
[7/30/2020 9:46:16 PM] Generating an outpost for the start of the level... (Location: The city of Worm Cave, level type: Outpost)
[7/30/2020 9:44:43 PM] Generating an outpost for the start of the level... (Location: The city of Worm Cave, level type: Outpost)
[7/30/2020 9:43:48 PM] kotel artema
[7/30/2020 9:43:48 PM] Hank Kits
[7/30/2020 9:43:48 PM] Altunuz
[7/30/2020 9:43:48 PM] NIKO
[7/30/2020 9:43:48 PM] SirSalty
[7/30/2020 9:43:48 PM] ArcZero
[7/30/2020 9:43:48 PM] RedEyedRenegade
[7/30/2020 9:43:48 PM] Suicidal Larry
[7/30/2020 9:43:48 PM] BigSeksy
[7/30/2020 9:43:48 PM] kotel artema
[7/30/2020 9:43:48 PM] Hank Kits
[7/30/2020 9:43:48 PM] Altunuz
[7/30/2020 9:43:48 PM] NIKO
[7/30/2020 9:43:48 PM] SirSalty
[7/30/2020 9:43:48 PM] ArcZero
[7/30/2020 9:43:48 PM] RedEyedRenegade
[7/30/2020 9:43:48 PM] Suicidal Larry
[7/30/2020 9:43:48 PM] BigSeksy
[7/30/2020 9:43:30 PM] kotel artema
[7/30/2020 9:43:30 PM] Hank Kits
[7/30/2020 9:43:30 PM] Altunuz
[7/30/2020 9:43:30 PM] NIKO
[7/30/2020 9:43:30 PM] SirSalty
[7/30/2020 9:43:30 PM] ArcZero
[7/30/2020 9:43:30 PM] RedEyedRenegade
[7/30/2020 9:43:30 PM] Suicidal Larry
[7/30/2020 9:43:30 PM] BigSeksy
[7/30/2020 9:43:30 PM] kotel artema
[7/30/2020 9:43:30 PM] Hank Kits
[7/30/2020 9:43:30 PM] Altunuz
[7/30/2020 9:43:30 PM] NIKO
[7/30/2020 9:43:30 PM] SirSalty
[7/30/2020 9:43:30 PM] ArcZero
[7/30/2020 9:43:30 PM] RedEyedRenegade
[7/30/2020 9:43:30 PM] Suicidal Larry
[7/30/2020 9:43:30 PM] BigSeksy
[7/30/2020 9:42:47 PM] kotel artema
[7/30/2020 9:42:47 PM] Hank Kits
[7/30/2020 9:42:47 PM] Altunuz
[7/30/2020 9:42:47 PM] NIKO
[7/30/2020 9:42:47 PM] SirSalty
[7/30/2020 9:42:47 PM] ArcZero
[7/30/2020 9:42:47 PM] Suicidal Larry
[7/30/2020 9:42:47 PM] BigSeksy
[7/30/2020 9:42:46 PM] RedEyedRenegade
[7/30/2020 9:42:40 PM] Task count: 0
[7/30/2020 9:42:30 PM] Generating an outpost for the start of the level... (Location: Xinzou City, level type: Outpost)
[7/30/2020 9:41:53 PM] Content package load order: Vanilla 0.9
[7/30/2020 9:41:04 PM] Coroutine "Barotrauma.Networking.GameClient+<StartGame>d__82" has failed
[7/30/2020 9:41:04 PM] Error
[7/30/2020 9:41:04 PM] There was an error initializing the round. {Object reference not set to an instance of an object.}
   at Barotrauma.Networking.GameClient.StartGame(IReadMessage inc)+MoveNext() in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Barotrauma/BarotraumaClient/ClientSource/Networking/GameClient.cs:line 1542
[7/30/2020 9:41:02 PM] Error while reading a message from server. {Submarine equality check failed. The submarine loaded at your end doesn't match the one loaded by the server. There may have been an error in receiving the up-to-date submarine file from the server.}
   at Barotrauma.Networking.GameClient.ReadStartGameFinalize(IReadMessage inc) in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Barotrauma/BarotraumaClient/ClientSource/Networking/GameClient.cs:line 961
   at Barotrauma.Networking.GameClient.ReadDataMessage(IReadMessage inc) in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Barotrauma/BarotraumaClient/ClientSource/Networking/GameClient.cs:line 835
   at Barotrauma.Networking.SteamP2PClientPeer.Update(Single deltaTime) in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Barotrauma/BarotraumaClient/ClientSource/Networking/Primitives/Peers/SteamP2PClientPeer.cs:line 244
   at Barotrauma.Networking.GameClient.Update(Single deltaTime) in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Barotrauma/BarotraumaClient/ClientSource/Networking/GameClient.cs:line 603
[7/30/2020 9:41:01 PM] Task count: 0
[7/30/2020 9:40:52 PM] Generating an outpost for the start of the level... (Location: Sarpedon Linea, level type: LocationConnection)
[7/30/2020 9:40:35 PM] Task count: 0
[7/30/2020 9:40:29 PM] Generating an outpost for the start of the level... (Location: Pastonia City, level type: Outpost)
[7/30/2020 9:39:25 PM] Content package load order: Vanilla 0.9
[7/30/2020 9:38:29 PM] (Msg) RelayNetWorkStatus:  avail=OK  config=OK  anyrelay=OK   (OK)
[7/30/2020 9:38:29 PM] (Msg) Ping location: sgp=34+3/35+3,hkg=49+4,man=93+9/62+3,maa=242+24/67+3,bom=260+26/91+3,tyo1=100+10/102+4,tyo=101+10/103+4,dxb=232+23/117+3,syd=137+13,fra=226+22/188+18,iad=278+27/262+4,gru=404+40/397+4
[7/30/2020 9:38:29 PM] (Msg) Ping measurement completed
[7/30/2020 9:38:20 PM] (Verbose) Communications with routing cluster 'sto' established.
[7/30/2020 9:38:20 PM] (Verbose) Communications with routing cluster 'lim' established.
[7/30/2020 9:38:20 PM] (Verbose) Communications with routing cluster 'sto2' established.
[7/30/2020 9:38:20 PM] (Verbose) Communications with routing cluster 'sea' established.
[7/30/2020 9:38:20 PM] (Verbose) Communications with routing cluster 'waw' established.
[7/30/2020 9:38:20 PM] (Verbose) Communications with routing cluster 'vie' established.
[7/30/2020 9:38:20 PM] (Verbose) Communications with routing cluster 'gru' established.
[7/30/2020 9:38:20 PM] (Verbose) Communications with routing cluster 'jnb' established.
[7/30/2020 9:38:20 PM] (Verbose) Communications with routing cluster 'ord' established.
[7/30/2020 9:38:20 PM] (Verbose) Communications with routing cluster 'okc' established.
[7/30/2020 9:38:20 PM] (Verbose) Communications with routing cluster 'maa' established.
[7/30/2020 9:38:20 PM] (Verbose) Communications with routing cluster 'syd' established.
[7/30/2020 9:38:20 PM] (Verbose) Communications with routing cluster 'mad' established.
[7/30/2020 9:38:20 PM] (Verbose) Communications with routing cluster 'lux' established.
[7/30/2020 9:38:20 PM] (Verbose) Communications with routing cluster 'lhr' established.
[7/30/2020 9:38:20 PM] (Verbose) Communications with routing cluster 'par' established.
[7/30/2020 9:38:20 PM] (Verbose) Communications with routing cluster 'lax' established.
[7/30/2020 9:38:20 PM] (Verbose) Communications with routing cluster 'tyo1' established.
[7/30/2020 9:38:20 PM] (Verbose) Communications with routing cluster 'tyo' established.
[7/30/2020 9:38:20 PM] (Verbose) Communications with routing cluster 'iad' established.
[7/30/2020 9:38:20 PM] (Verbose) Communications with routing cluster 'atl' established.
[7/30/2020 9:38:20 PM] (Verbose) Communications with routing cluster 'bom' established.
[7/30/2020 9:38:20 PM] (Verbose) Communications with routing cluster 'sgp' established.
[7/30/2020 9:38:20 PM] (Verbose) Communications with routing cluster 'dxb' established.
[7/30/2020 9:38:20 PM] (Verbose) Communications with routing cluster 'fra' established.
[7/30/2020 9:38:20 PM] (Verbose) Communications with routing cluster 'eat' established.
[7/30/2020 9:38:20 PM] (Verbose) Communications with routing cluster 'man' established.
[7/30/2020 9:38:20 PM] (Verbose) Communications with routing cluster 'ams' established.
[7/30/2020 9:38:20 PM] (Verbose) Communications with routing cluster 'hkg' established.
[7/30/2020 9:38:20 PM] (Msg) RelayNetWorkStatus:  avail=Attempting  config=OK  anyrelay=Attempting   (Performing ping measurement)
[7/30/2020 9:38:20 PM] (Msg) Performing ping measurement
[7/30/2020 9:38:20 PM] (Msg) Got SDR network config.  Loaded revision 281 OK
[7/30/2020 9:38:19 PM] (Warning) SDR network config fetch first attempt failed.  HTTP 504.  .  Trying again.
[7/30/2020 9:38:05 PM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[7/30/2020 9:38:04 PM] Content package load order: Vanilla 0.9
[7/30/2020 9:38:03 PM] Content package load order: Vanilla 0.9
[7/30/2020 9:37:37 PM] Attempting to open ALC device "Built-in Output"
[7/30/2020 9:37:34 PM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[7/30/2020 9:37:33 PM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
```

**Comment by ekqvist** [comment]
Issue in the screenshot was also reported with crash reports in #3434

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2aa421a3

**Comment by mygamingaccount** [comment]
@Regalis11, was the fix merged into 0.10.4?

I encountered this the other day. Attaching the crash report:
[crashreport (14).log](https://github.com/Regalis11/Barotrauma/files/5095854/crashreport.14.log)

**Comment by Rokvach** [comment]
There hasn't been any sightings of this since the Unstable testing started nor any additional issues caused by this fix, looks to be working correctly. Closing.

**Comment by BassM8** [comment]
Second time a campaign was corrupted by this bug in the last 2 weeks.

This has not been fixed

Can send save file if needed

**Comment by Rokvach** [comment]
Did you encounter it in the Unstable build? This fix is coming in the next patch which can be already played in the Unstable branch on Steam

**Comment by BassM8** [comment]
No its in the current version. v 0.10.4.0
