### ISSUE TITLE
DXGI_ERROR_NOT_CURRENTLY_AVAILABLE

### ISSUE THREAD

**Issue by itchyOwl** [Regalis11/Barotrauma#3515]
"Cant start game after new update

recently got win 10 and wanted to check the game after the new update after a long break
i-3 cpu , gtx 1050Ti 12 GB RAM, never had an issue with the game"

crash log:

Barotrauma seems to have crashed. Sorry for the inconvenience!

EFAC70B2719BEBECDF0597D16251FCBE

Game version 0.10.4.0 (ReleaseWindows, branch release, revision 20132d25fb)
Graphics mode: 1920x1080 (Fullscreen)
VSync ON
Language: English
Selected content packages: Vanilla 0.9
Level seed: no level loaded
Loaded submarine: None
Selected screen: None
SteamManager initialized

System info:
Operating system: Microsoft Windows NT 10.0.19041.0 64 bit
GPU name: NVIDIA GeForce GTX 1050 Ti
Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1,7777778}
GPU status: Normal

Exception: HRESULT: [0x887A0022], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_NOT_CURRENTLY_AVAILABLE/NotCurrentlyAvailable], Message: A resource is not available at the time of the call, but may become available later.
(SharpDX.SharpDXException)
Target site: Void CheckError()
Stack trace:
at SharpDX.Result.CheckError()
at SharpDX.DXGI.Output.FindClosestMatchingMode(ModeDescription& modeToMatchRef, ModeDescription& closestMatchRef, IUnknown concernedDeviceRef)
at SharpDX.DXGI.Output.GetClosestMatchingMode(ComObject device, ModeDescription modeToMatch, ModeDescription& closestMatch)
at Microsoft.Xna.Framework.Graphics.GraphicsDevice.GetModeSwitchedSize(Int32& width, Int32& height) in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\GraphicsDevice.DirectX.cs:line 645
at Microsoft.Xna.Framework.Graphics.GraphicsDevice.CorrectBackBufferSize() in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\GraphicsDevice.DirectX.cs:line 503
at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformReset() in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\GraphicsDevice.DirectX.cs:line 480
at Microsoft.Xna.Framework.Graphics.GraphicsDevice.Reset() in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\GraphicsDevice.cs:line 616
at Microsoft.Xna.Framework.Graphics.GraphicsDevice.Reset(PresentationParameters presentationParameters) in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\GraphicsDevice.cs:line 632
at Microsoft.Xna.Framework.GraphicsDeviceManager.ApplyChanges() in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\GraphicsDeviceManager.cs:line 328
at Barotrauma.GameMain.SetWindowMode(WindowMode windowMode) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 297
at Barotrauma.GameMain.ApplyGraphicsSettings() in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 280
at Barotrauma.GameMain.LoadContent() in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 346
at Microsoft.Xna.Framework.Game.Initialize() in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 553
at Barotrauma.GameMain.Initialize() in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 325
at Microsoft.Xna.Framework.Game.DoInitialize() in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 685
at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 382
at Microsoft.Xna.Framework.Game.Run() in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
at Barotrauma.Program.Main(String[] args) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59

Last debug messages:
[04.08.2020 18:50:51] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[04.08.2020 18:50:50] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[04.08.2020 18:50:45] Logged in as Bear Brawnson (SteamID STEAM_1:0:29223478)

Source: https://steamcommunity.com/app/602960/discussions/1/2793873197773110607/

**Comment by itchyOwl** [comment]
Not sure if there's anything we can do for this, besides workarounds:
- update the OS
- update the VGA drivers
- update Direct X
- try different resolution
- try different refresh rate
- try switching the input method or port (DVI -> Display Port, HDMI)

**Comment by someone972** [comment]
As a data point, #4916 was filed recently and was fixed by changing to a lower resolution then back. I also think there's not much Barotrauma can do about this. Maybe what BT can do to help users here, is that if we catch that particular exception we could give a list of actions to try and work around it? Like the changing resolution that worked for the aforementioned issue.
