### ISSUE TITLE
Crash in GUIListBox.Draw

### ISSUE THREAD

**Issue by MoikeZ** [Regalis11/Barotrauma#3572]
Barotrauma Client crash report (generated on 8/16/2020 0:36:44 AM)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

EFAC70B2719BEBECDF0597D16251FCBE

Game version 0.10.4.0 (ReleaseWindows, branch release, revision 20132d25fb)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla 0.9, Brotherhood Mk1
Level seed: no level loaded
Loaded submarine: None
Selected screen: Barotrauma.SteamWorkshopScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19041.0 64 bit
    GPU name: NVIDIA GeForce GTX 1060 6GB
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Collection was modified; enumeration operation may not execute. (System.InvalidOperationException)
Target site: Void ThrowInvalidOperationException_InvalidOperation_EnumFailedVersion()
Stack trace: 
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at Barotrauma.GUIListBox.Draw(SpriteBatch spriteBatch) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIListBox.cs:line 977
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Barotrauma.GUI.Draw(Camera cam, SpriteBatch spriteBatch) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 305
   at Barotrauma.SteamWorkshopScreen.Draw(Double deltaTime, GraphicsDevice graphics, SpriteBatch spriteBatch) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Screens\SteamWorkshopScreen.cs:line 1865
   at Barotrauma.GameMain.Draw(GameTime gameTime) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 1047
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime) in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 669
   at Microsoft.Xna.Framework.Game.Tick() in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 511
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59

Last debug messages:
[8/16/2020 0:36:42 AM] Content package load order: Vanilla 0.9  |  Brotherhood Mk1
[8/16/2020 0:36:41 AM] Content package load order: Vanilla 0.9
[8/16/2020 0:36:41 AM] Published workshop item Brotherhood Mk1 successfully.
[8/16/2020 0:36:37 AM] Opening submarine file "Mods/Brotherhood Mk1/Brotherhood Mk1.sub" failed, retrying in 250 ms...
[8/16/2020 0:36:37 AM] Loading submarine "Mods/Brotherhood Mk1/Brotherhood Mk1.sub" failed! {The process cannot access the file 'C:\Program Files (x86)\Steam\steamapps\common\Barotrauma\Mods\Brotherhood Mk1\Brotherhood Mk1.sub' because it is being used by another process.}
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Barotrauma.IO.File.Open(String path, FileMode mode, FileAccess access) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Utils\SafeIO.cs:line 299
   at Barotrauma.SaveUtil.DecompressFiletoStream(String fileName) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Utils\SaveUtil.cs:line 363
   at Barotrauma.SubmarineInfo.OpenFile(String file, Exception& exception) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Map\SubmarineInfo.cs:line 707
[8/16/2020 0:36:37 AM] Content package load order: Vanilla 0.9  |  Brotherhood Mk1
[8/16/2020 0:36:36 AM] Content package load order: Vanilla 0.9
[8/16/2020 0:36:36 AM] Content package load order: Vanilla 0.9  |  Brotherhood Mk1
[8/16/2020 0:36:36 AM] Content package load order: Vanilla 0.9
[8/16/2020 0:36:34 AM] Content package load order: Vanilla 0.9  |  Brotherhood Mk1
[8/16/2020 0:36:34 AM] Content package load order: Vanilla 0.9
[8/16/2020 0:36:26 AM] Content package load order: Vanilla 0.9  |  Brotherhood Mk1
[8/16/2020 0:36:26 AM] Content package load order: Vanilla 0.9
[8/16/2020 0:32:13 AM] (Msg) RelayNetWorkStatus:  avail=OK  config=OK  anyrelay=OK   (OK)
[8/16/2020 0:32:13 AM] (Msg) Ping location: tyo=31+3,tyo1=31+3,hkg=76+7,sgp=102+10/103+10,sea=113+11,eat=118+11,maa=150+15/134+10,lax=138+13/137+11,syd=143+14,iad=168+16/169+15,fra=257+25/252+11,gru=278+27
[8/16/2020 0:32:13 AM] (Msg) Ping measurement completed
[8/16/2020 0:32:07 AM] (Verbose) Communications with routing cluster 'sto2' established.
[8/16/2020 0:32:05 AM] (Verbose) Communications with routing cluster 'scl' established.
[8/16/2020 0:32:05 AM] (Verbose) Communications with routing cluster 'vie' established.
[8/16/2020 0:32:05 AM] (Verbose) Communications with routing cluster 'waw' established.
[8/16/2020 0:32:05 AM] (Verbose) Communications with routing cluster 'sto' established.
[8/16/2020 0:32:04 AM] (Verbose) Communications with routing cluster 'lux' established.
[8/16/2020 0:32:04 AM] (Verbose) Communications with routing cluster 'lim' established.
[8/16/2020 0:32:04 AM] (Verbose) Communications with routing cluster 'mad' established.
[8/16/2020 0:32:04 AM] (Verbose) Communications with routing cluster 'syd' established.
[8/16/2020 0:32:04 AM] (Verbose) Communications with routing cluster 'lhr' established.
[8/16/2020 0:32:04 AM] (Verbose) Communications with routing cluster 'par' established.
[8/16/2020 0:32:04 AM] (Verbose) Communications with routing cluster 'sea' established.
[8/16/2020 0:32:04 AM] (Verbose) Communications with routing cluster 'jnb' established.
[8/16/2020 0:32:04 AM] (Verbose) Communications with routing cluster 'sgp' established.
[8/16/2020 0:32:04 AM] (Verbose) Communications with routing cluster 'gru' established.
[8/16/2020 0:32:04 AM] (Verbose) Communications with routing cluster 'okc' established.
[8/16/2020 0:32:04 AM] (Verbose) Communications with routing cluster 'ord' established.
[8/16/2020 0:32:04 AM] (Verbose) Communications with routing cluster 'fra' established.
[8/16/2020 0:32:04 AM] (Verbose) Communications with routing cluster 'dxb' established.
[8/16/2020 0:32:04 AM] (Verbose) Communications with routing cluster 'ams' established.
[8/16/2020 0:32:04 AM] (Verbose) Communications with routing cluster 'maa' established.
[8/16/2020 0:32:04 AM] (Verbose) Communications with routing cluster 'lax' established.
[8/16/2020 0:32:04 AM] (Verbose) Communications with routing cluster 'tyo' established.
[8/16/2020 0:32:04 AM] (Verbose) Communications with routing cluster 'tyo1' established.
[8/16/2020 0:32:04 AM] (Verbose) Communications with routing cluster 'atl' established.
[8/16/2020 0:32:04 AM] (Verbose) Communications with routing cluster 'iad' established.
[8/16/2020 0:32:04 AM] (Verbose) Communications with routing cluster 'bom' established.
[8/16/2020 0:32:04 AM] (Verbose) Communications with routing cluster 'eat' established.
[8/16/2020 0:32:04 AM] (Verbose) Communications with routing cluster 'hkg' established.
[8/16/2020 0:32:04 AM] (Msg) RelayNetWorkStatus:  avail=Attempting  config=OK  anyrelay=Attempting   (Performing ping measurement)
[8/16/2020 0:32:04 AM] (Msg) Performing ping measurement
[8/16/2020 0:32:04 AM] (Msg) Got SDR network config.  Loaded revision 281 OK
[8/16/2020 0:32:04 AM] (Warning) SDR network config fetch first attempt failed.  HTTP 504.  .  Trying again.
[8/16/2020 0:32:01 AM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[8/16/2020 0:32:00 AM] Content package load order: Vanilla 0.9  |  Brotherhood Mk1
[8/16/2020 0:32:00 AM] Content package load order: Vanilla 0.9  |  Brotherhood Mk1
[8/16/2020 0:31:58 AM] Attempting to open ALC device "OpenAL Soft on Realtek Digital Output (Realtek(R) Audio)"
[8/16/2020 0:31:58 AM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[8/16/2020 0:31:57 AM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[8/16/2020 0:31:56 AM] Logged in as MoikeZ (SteamID STEAM_1:1:33899773)

**Comment by Regalis11** [comment]
Potentially fixed in https://github.com/Regalis11/Barotrauma-development/commit/d176c5b53ae4b7278796b000a964580d9931f430

**Comment by Rokvach** [comment]
There hasn't been any sightings of this since the Unstable testing started, looks to be working correctly. Closing.
