### ISSUE TITLE
Crash in SteamAchievementManager

### ISSUE THREAD

**Issue by farukred** [Regalis11/Barotrauma#3576]
Barotrauma Client crash report (generated on 8/16/2020 5:16:55 AM)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

90AB60D51DD92D51657C9BB21A665329

Game version 0.10.4.0 (ReleaseMac, branch release, revision 965c31410a)
Graphics mode: 1440x900 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla 0.9, EK Utilities, EK Armory - GTD Patch, [KSMC]-Kimsun, Vengeance, EuroCurrency, BaroTech Expansion - Unstable, Shipwrecks Extended, Charon MK3, EK Armory, UnlimitedO2, Tiny baby man v0.2
Level seed: VortaBast
Loaded submarine: Vengeance Mk. II (6311CA682F08C87D5CE43FB33A6EF386)
Selected screen: Barotrauma.MainMenuScreen
SteamManager initialized

System info:
    Operating system: Unix 18.7.0.0 64 bit
    GPU name: 
    Display mode: {Width:1440 Height:900 Format:Color AspectRatio:1.6}
    GPU status: Normal

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void Update(Single)
Stack trace: 
   at Barotrauma.SteamAchievementManager.Update(Single deltaTime) in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Barotrauma/BarotraumaShared/SharedSource/SteamAchievementManager.cs:line 88
   at Barotrauma.Steam.SteamManager.Update(Single deltaTime) in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Barotrauma/BarotraumaShared/SharedSource/Networking/SteamManager.cs:line 151
   at Barotrauma.GameMain.Update(GameTime gameTime) in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Barotrauma/BarotraumaClient/ClientSource/GameMain.cs:line 995
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Libraries/MonoGame.Framework/Src/MonoGame.Framework/SDL/SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Barotrauma/BarotraumaClient/ClientSource/Program.cs:line 58

Last debug messages:
[8/16/2020 5:16:53 AM] Coroutine Barotrauma.SinglePlayerCampaign+<DoLoadInitialLevel>d__12 threw an exception: Object reference not set to an instance of an object.
   at Barotrauma.CargoManager.CreateItems(List`1 itemsToSpawn) in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Barotrauma/BarotraumaShared/SharedSource/GameSession/CargoManager.cs:line 220
   at Barotrauma.CargoManager.CreatePurchasedItems() in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Barotrauma/BarotraumaShared/SharedSource/GameSession/CargoManager.cs:line 147
   at Barotrauma.SinglePlayerCampaign.Start() in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Barotrauma/BarotraumaClient/ClientSource/GameSession/GameModes/SinglePlayerCampaign.cs:line 174
   at Barotrauma.GameSession.InitializeLevel(Level level) in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Barotrauma/BarotraumaShared/SharedSource/GameSession/GameSession.cs:line 379
   at Barotrauma.GameSession.StartRound(LevelData levelData, Boolean mirrorLevel, SubmarineInfo startOutpost, SubmarineInfo endOutpost) in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Barotrauma/BarotraumaShared/SharedSource/GameSession/GameSession.cs:line 319
   at Barotrauma.SinglePlayerCampaign.DoLoadInitialLevel(LevelData level, Boolean mirror)+MoveNext() in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Barotrauma/BarotraumaClient/ClientSource/GameSession/GameModes/SinglePlayerCampaign.cs:line 199
   at Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle) in /Users/eetupitkanen/Documents/Repositories/Barotrauma-development/Barotrauma/BarotraumaShared/SharedSource/CoroutineManager.cs:line 238
[8/16/2020 5:16:48 AM] Generating an outpost for the end of the level... (Location: Bast Habitation Outpost, level type: LocationConnection)
[8/16/2020 5:16:47 AM] Generating an outpost for the start of the level... (Location: Vorta Mining Facility, level type: LocationConnection)
[8/16/2020 5:16:45 AM] Could not compress a texture because the dimensions aren't a multiple of 4 (path: Mods/BaroTech Expansion - Unstable/Papers/DocumentSprites.png, size: 63x32)
[8/16/2020 5:16:01 AM] (Msg) RelayNetWorkStatus:  avail=OK  config=OK  anyrelay=OK   (OK)
[8/16/2020 5:16:01 AM] (Msg) Ping location: sgp=49+4/50+4,hkg=79+7/79+4,maa=84+8/81+4,bom=109+10/100+4,dxb=134+13/125+4,tyo=138+13/132+4,tyo1=144+14/132+4,syd=137+13,lhr=210+21,fra=249+24/217+21,iad=291+29/290+4,gru=391+39/395+21
[8/16/2020 5:16:01 AM] (Msg) Ping measurement completed
[8/16/2020 5:15:56 AM] (Verbose) Communications with routing cluster 'sea' established.
[8/16/2020 5:15:54 AM] Unnamed item (ironnail)in Mods/BaroTech Expansion - Unstable/Equipment/Security.xml!
[8/16/2020 5:15:53 AM] (Verbose) Communications with routing cluster 'vie' established.
[8/16/2020 5:15:53 AM] Duplicate affliction: 'ek_burn_threshold' defined in affliction of 'Mods/EK Armory/Afflictions.xml'
[8/16/2020 5:15:53 AM] (Verbose) Communications with routing cluster 'scl' established.
[8/16/2020 5:15:52 AM] (Verbose) Communications with routing cluster 'waw' established.
[8/16/2020 5:15:52 AM] (Verbose) Communications with routing cluster 'lim' established.
[8/16/2020 5:15:52 AM] (Verbose) Communications with routing cluster 'sto2' established.
[8/16/2020 5:15:52 AM] (Verbose) Communications with routing cluster 'sto' established.
[8/16/2020 5:15:52 AM] (Verbose) Communications with routing cluster 'gru' established.
[8/16/2020 5:15:52 AM] (Verbose) Communications with routing cluster 'okc' established.
[8/16/2020 5:15:52 AM] (Verbose) Communications with routing cluster 'ord' established.
[8/16/2020 5:15:52 AM] (Verbose) Communications with routing cluster 'tyo1' established.
[8/16/2020 5:15:52 AM] (Verbose) Communications with routing cluster 'tyo' established.
[8/16/2020 5:15:52 AM] (Verbose) Communications with routing cluster 'syd' established.
[8/16/2020 5:15:52 AM] (Verbose) Communications with routing cluster 'jnb' established.
[8/16/2020 5:15:52 AM] (Verbose) Communications with routing cluster 'lax' established.
[8/16/2020 5:15:52 AM] (Verbose) Communications with routing cluster 'mad' established.
[8/16/2020 5:15:52 AM] (Verbose) Communications with routing cluster 'lux' established.
[8/16/2020 5:15:52 AM] (Verbose) Communications with routing cluster 'par' established.
[8/16/2020 5:15:52 AM] (Verbose) Communications with routing cluster 'lhr' established.
[8/16/2020 5:15:52 AM] (Verbose) Communications with routing cluster 'iad' established.
[8/16/2020 5:15:52 AM] (Verbose) Communications with routing cluster 'atl' established.
[8/16/2020 5:15:52 AM] (Verbose) Communications with routing cluster 'eat' established.
[8/16/2020 5:15:52 AM] (Verbose) Communications with routing cluster 'sgp' established.
[8/16/2020 5:15:52 AM] (Verbose) Communications with routing cluster 'fra' established.
[8/16/2020 5:15:52 AM] (Verbose) Communications with routing cluster 'ams' established.
[8/16/2020 5:15:52 AM] (Verbose) Communications with routing cluster 'maa' established.
[8/16/2020 5:15:52 AM] (Verbose) Communications with routing cluster 'dxb' established.
[8/16/2020 5:15:52 AM] (Verbose) Communications with routing cluster 'bom' established.
[8/16/2020 5:15:52 AM] (Verbose) Communications with routing cluster 'hkg' established.
[8/16/2020 5:15:52 AM] (Msg) RelayNetWorkStatus:  avail=Attempting  config=OK  anyrelay=Attempting   (Performing ping measurement)
[8/16/2020 5:15:52 AM] (Msg) Performing ping measurement
[8/16/2020 5:15:52 AM] (Msg) Got SDR network config.  Loaded revision 281 OK
[8/16/2020 5:15:52 AM] (Warning) SDR network config fetch first attempt failed.  HTTP 504.  .  Trying again.
[8/16/2020 5:15:46 AM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[8/16/2020 5:15:46 AM] Content package load order: Vanilla 0.9  |  EK Utilities  |  EK Armory - GTD Patch  |  [KSMC]-Kimsun  |  Vengeance  |  EuroCurrency  |  BaroTech Expansion - Unstable  |  Shipwrecks Extended  |  Charon MK3  |  EK Armory  |  UnlimitedO2  |  Tiny baby man v0.2
[8/16/2020 5:15:46 AM] Content package load order: Vanilla 0.9  |  EK Utilities  |  EK Armory - GTD Patch  |  [KSMC]-Kimsun  |  Vengeance  |  EuroCurrency  |  BaroTech Expansion - Unstable  |  Shipwrecks Extended  |  Charon MK3  |  EK Armory  |  UnlimitedO2  |  Tiny baby man v0.2
[8/16/2020 5:15:43 AM] Attempting to open ALC device "External Headphones"
[8/16/2020 5:15:42 AM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[8/16/2020 5:15:41 AM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[8/16/2020 5:15:40 AM] Logged in as Largeredwolf (SteamID STEAM_1:1:241408462)

**Comment by Regalis11** [comment]
I suspect this was caused by the same race condition as #3494. Implemented a fix in https://github.com/Regalis11/Barotrauma-development/commit/a57a05d, let's see if this reoccurs.
