### ISSUE TITLE
Voting to kick resulted in Barotrauma crash

### ISSUE THREAD

**Issue by mygamingaccount** [Regalis11/Barotrauma#3591]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Rare crash involving an unhandled exception when trying to vote kick another player

**Steps To Reproduce**
1) Join a server
2) Encounter a crash
3) Rejoin the server
4) Try to vote kick

**Version**
v0.10.4 Linux

**Additional information**
```
Exception: Sequence contains no matching element (System.InvalidOperationException)
Target site: Void ThrowNoMatchException()
Stack trace: 
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Barotrauma.Networking.GameClient.VoteForKick(Client votedClient) in /home/joonas/Barotrauma/Barotrauma/BarotraumaClient/ClientSource/Networking/GameClient.cs:line 2621
   at Barotrauma.Networking.GameClient.<>c__DisplayClass150_0.<CreateSelectionRelatedButtons>b__5(GUIButton btn, Object userdata) in /home/joonas/Barotrauma/Barotrauma/BarotraumaClient/ClientSource/Networking/GameClient.cs:line 3288
   at Barotrauma.GUIButton.Update(Single deltaTime) in /home/joonas/Barotrauma/Barotrauma/BarotraumaClient/ClientSource/GUI/GUIButton.cs:line 247
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Barotrauma.GUI.Update(Single deltaTime) in /home/joonas/Barotrauma/Barotrauma/BarotraumaClient/ClientSource/GUI/GUI.cs:line 1220
   at Barotrauma.GameMain.Update(GameTime gameTime) in /home/joonas/Barotrauma/Barotrauma/BarotraumaClient/ClientSource/GameMain.cs:line 990
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in /home/joonas/Barotrauma/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in /home/joonas/Barotrauma/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in /home/joonas/Barotrauma/Libraries/MonoGame.Framework/Src/MonoGame.Framework/SDL/SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in /home/joonas/Barotrauma/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in /home/joonas/Barotrauma/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in /home/joonas/Barotrauma/Barotrauma/BarotraumaClient/ClientSource/Program.cs:line 59

```

[crashreport (13).log](https://github.com/Regalis11/Barotrauma/files/5090131/crashreport.13.log)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/211b307c91f04a4adb5429382482bb5f423404f5

**Comment by Rokvach** [comment]
No issues, closing.
