### ISSUE TITLE
Cancel button in server password prompt doesn't close the prompt and pressing "Ok" after you've pressed "Cancel" crashes the game

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#3789]
Tested on dev branch using a Release build

Reproduction steps:
1. Host a passworded dedicated server
2. Try to join the server so you get the password prompt
3. Press "Cancel" and notice that the server list only refreshes but the prompt doesn't go away
4. Now press "Ok" and notice that the game crashes

Crash report:
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/acf4a0f7-0c64-4183-8e24-6debedb009ee)
```
Barotrauma Client crash report (generated on 10.9.2020 10:02:14)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


89A72DE3A611C9FBAEEB42B786C8E4C2


Game version 0.10.504.0 (ReleaseWindows, branch dev, revision 5bdf1e4732)
Graphics mode: 2560x1440 (BorderlessWindowed)
VSync OFF
Language: English
Selected content packages: Vanilla 0.9, Bagango, EK Matriarch Mk-III, SecurityModule_02
Level seed: no level loaded
Loaded submarine: None
Selected screen: Barotrauma.ServerListScreen
SteamManager initialized


System info:
    Operating system: Microsoft Windows NT 10.0.18362.0 64 bit
    GPU name: NVIDIA GeForce GTX 980 Ti
    Display mode: {Width:2560 Height:1440 Format:Color AspectRatio:1,7777778}
    GPU status: Normal


Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Boolean <WaitForStartingInfo>b__2(Barotrauma.GUIButton, System.Object)
Stack trace: 
   at Barotrauma.Networking.GameClient.<>c__DisplayClass69_0.<WaitForStartingInfo>b__2(GUIButton button, Object obj) in C:\Users\RoniK\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 527
   at Barotrauma.GUIButton.Update(Single deltaTime) in C:\Users\RoniK\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIButton.cs:line 253
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Barotrauma.GUI.Update(Single deltaTime) in C:\Users\RoniK\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1220
   at Barotrauma.GameMain.Update(GameTime gameTime) in C:\Users\RoniK\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 948
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in C:\Users\RoniK\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in C:\Users\RoniK\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in C:\Users\RoniK\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in C:\Users\RoniK\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in C:\Users\RoniK\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in C:\Users\RoniK\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58


Last debug messages:
[10.9.2020 10:02:12] LobbyMatchList:  LobbiesMatching: 11
[10.9.2020 10:02:12] LobbyMatchList:  LobbiesMatching: 11
[10.9.2020 10:02:12] SteamAPICallCompleted:   AsyncCall: 13333427713147769859
   Callback: 510
 ParamCount: 4
[10.9.2020 10:02:12] PersonaStateChange:      SteamID: 76561197997586661
 ChangeFlags: 256
[10.9.2020 10:01:54] (Msg) RelayNetWorkStatus:  avail=OK  config=OK  anyrelay=OK   (OK)
[10.9.2020 10:01:54] (Msg) Ping location: sto=14+1,sto2=14+1,fra=39+3/33+1,ams=38+3/34+1,waw=45+4/34+1,lux=46+4/38+1,lhr=45+4/39+1,par=50+5/43+1,vie=50+5/45+1,iad=123+12/119+1,sgp=195+19/196+19,gru=246+24/263+1
[10.9.2020 10:01:54] (Msg) Ping measurement completed
[10.9.2020 10:01:53] SteamRelayNetworkStatus:                      Avail: Current
 PingMeasurementInProgress: 0
        AvailNetworkConfig: Current
             AvailAnyRelay: Current
                  DebugMsg: System.Byte[]
[10.9.2020 10:01:53] LobbyMatchList:  LobbiesMatching: 12
[10.9.2020 10:01:53] LobbyMatchList:  LobbiesMatching: 12
[10.9.2020 10:01:53] SteamAPICallCompleted:   AsyncCall: 12352756413073785222
   Callback: 510
 ParamCount: 4
[10.9.2020 10:01:52] (Debug) Destroying relay 'man#130 (155.133.253.34:27036)' because initial_ping_timeout
[10.9.2020 10:01:49] (Debug) Destroying relay 'man#129 (155.133.253.34:27035)' because initial_ping_timeout
[10.9.2020 10:01:47] (Debug) Destroying relay 'man#143 (155.133.253.34:27049)' because initial_ping_timeout
[10.9.2020 10:01:44] (Debug) Destroying relay 'man#30 (155.133.253.4:27044)' because initial_ping_timeout
[10.9.2020 10:01:42] (Verbose) Communications with routing cluster 'syd' established.
[10.9.2020 10:01:42] (Verbose) Communications with routing cluster 'tyo1' established.
[10.9.2020 10:01:42] (Verbose) Communications with routing cluster 'scl' established.
[10.9.2020 10:01:42] (Verbose) Communications with routing cluster 'tyo' established.
[10.9.2020 10:01:42] (Verbose) Communications with routing cluster 'sgp' established.
[10.9.2020 10:01:42] (Verbose) Communications with routing cluster 'lim' established.
[10.9.2020 10:01:42] (Verbose) Communications with routing cluster 'sea' established.
[10.9.2020 10:01:42] (Verbose) Communications with routing cluster 'maa' established.
[10.9.2020 10:01:41] (Verbose) Communications with routing cluster 'lax' established.
[10.9.2020 10:01:41] (Verbose) Communications with routing cluster 'vie' established.
[10.9.2020 10:01:41] (Verbose) Communications with routing cluster 'okc' established.
[10.9.2020 10:01:41] (Verbose) Communications with routing cluster 'waw' established.
[10.9.2020 10:01:41] (Verbose) Communications with routing cluster 'gru' established.
[10.9.2020 10:01:41] (Verbose) Communications with routing cluster 'ord' established.
[10.9.2020 10:01:41] (Verbose) Communications with routing cluster 'hkg' established.
[10.9.2020 10:01:41] (Verbose) Communications with routing cluster 'jnb' established.
[10.9.2020 10:01:41] (Verbose) Communications with routing cluster 'sto2' established.
[10.9.2020 10:01:41] (Verbose) Communications with routing cluster 'sto' established.
[10.9.2020 10:01:41] (Verbose) Communications with routing cluster 'eat' established.
[10.9.2020 10:01:41] (Verbose) Communications with routing cluster 'mad' established.
[10.9.2020 10:01:41] (Verbose) Communications with routing cluster 'par' established.
[10.9.2020 10:01:41] (Verbose) Communications with routing cluster 'bom' established.
[10.9.2020 10:01:41] (Verbose) Communications with routing cluster 'dxb' established.
[10.9.2020 10:01:41] (Verbose) Communications with routing cluster 'lux' established.
[10.9.2020 10:01:41] (Verbose) Communications with routing cluster 'lhr' established.
[10.9.2020 10:01:41] (Verbose) Communications with routing cluster 'atl' established.
[10.9.2020 10:01:41] (Verbose) Communications with routing cluster 'iad' established.
[10.9.2020 10:01:41] (Verbose) Communications with routing cluster 'fra' established.
[10.9.2020 10:01:41] (Verbose) Communications with routing cluster 'ams' established.
[10.9.2020 10:01:41] (Msg) RelayNetWorkStatus:  avail=Attempting  config=OK  anyrelay=Attempting   (Performing ping measurement)
[10.9.2020 10:01:41] (Msg) Performing ping measurement
[10.9.2020 10:01:41] (Msg) Got SDR network config.  Loaded revision 281 OK
[10.9.2020 10:01:41] (Warning) SDR network config fetch first attempt failed.  HTTP 504.  .  Trying again.
[10.9.2020 10:01:36] Attempting to open ALC device "OpenAL Soft on Kaiuttimet (Realtek High Definition Audio)"
[10.9.2020 10:01:35] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[10.9.2020 10:01:35] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[10.9.2020 10:01:34] Error in content package "SecurityModule_02" - no content files defined.
[10.9.2020 10:01:34] Error in content package "Berilia_Wrecked" - no content files defined.
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/fd3ca2cf4b2f68421d348e8fbb530b0696c2de0d

**Comment by Rokvach** [comment]
Working correctly, closing.
