### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by Xecular** [Regalis11/Barotrauma#383]
This consistently happens at a random time after spawning a creature in a server via console.

```
Barotrauma Client crash report (generated on 4/22/2018 8:26:35 PM)


Barotrauma seems to have crashed. Sorry for the inconvenience! 
If you'd like to help fix the bug that caused the crash, please send this file to the developers on the Undertow Games forums.


Game version 0.8.0.5
Graphics mode: 1920x1080 (BorderlessWindowed)
Selected content package: BTE 5.5
Level seed: KWttbMjL
Loaded submarine: [BTE] Class A Station (8A486510344DFEE711A99ECEFE7D29A8)
Selected screen: Barotrauma.GameScreen
Server (Round hadn't been started)


System info:
    Operating system: Microsoft Windows NT 6.2.9200.0 64 bit
    GPU name: NVIDIA GeForce GTX 1060 6GB
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.777778}
    GPU status: Normal


Exception: Object reference not set to an instance of an object.
Target site: Microsoft.Xna.Framework.Vector2 DiffToCurrentNode()
Stack trace: 
   at Barotrauma.IndoorsSteeringManager.DiffToCurrentNode() in E:\Barotrauma\Barotrauma\BarotraumaShared\Source\Characters\AI\IndoorsSteeringManager.cs:line 172
   at Barotrauma.IndoorsSteeringManager.DoSteeringSeek(Vector2 target, Single speed) in E:\Barotrauma\Barotrauma\BarotraumaShared\Source\Characters\AI\IndoorsSteeringManager.cs:line 89
   at Barotrauma.SteeringManager.SteeringSeek(Vector2 targetSimPos, Single speed) in E:\Barotrauma\Barotrauma\BarotraumaShared\Source\Characters\AI\SteeringManager.cs:line 40
   at Barotrauma.EnemyAIController.UpdateAttack(Single deltaTime) in E:\Barotrauma\Barotrauma\BarotraumaShared\Source\Characters\AI\EnemyAIController.cs:line 368
   at Barotrauma.EnemyAIController.Update(Single deltaTime) in E:\Barotrauma\Barotrauma\BarotraumaShared\Source\Characters\AI\EnemyAIController.cs:line 187
   at Barotrauma.AICharacter.Update(Single deltaTime, Camera cam) in E:\Barotrauma\Barotrauma\BarotraumaShared\Source\Characters\AICharacter.cs:line 77
   at Barotrauma.Character.UpdateAll(Single deltaTime, Camera cam) in E:\Barotrauma\Barotrauma\BarotraumaShared\Source\Characters\Character.cs:line 1471
   at Barotrauma.GameScreen.Update(Double deltaTime) in E:\Barotrauma\Barotrauma\BarotraumaShared\Source\Screens\GameScreen.cs:line 98
   at Barotrauma.GameMain.Update(GameTime gameTime) in E:\Barotrauma\Barotrauma\BarotraumaClient\Source\GameMain.cs:line 414
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at MonoGame.Framework.WinFormsGameWindow.RunLoop()
   at MonoGame.Framework.WinFormsGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Barotrauma.Program.Main() in E:\Barotrauma\Barotrauma\BarotraumaClient\Source\Program.cs:line 41
```

**Comment by Regalis11** [comment]
Fixed in 276798d8
