### ISSUE TITLE
Barotrauma seems to have crashed (Cannot access a closed pipe)

### ISSUE THREAD

**Issue by BloodWitcher** [Regalis11/Barotrauma#3847]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
After finished mission to kill Moloh, game freezes and after 30 sec it comes an error. Save game with all progress is broken. When checking by Steam, its found 3 errors and fix it, but save still didnt loading correctly. ( New game starting good.
**Steps To Reproduce**
I can send u save to check it.
**Version**
0.10.4.0 (ReleaseWindows, branch release, revision 20132d25fb)
Microsoft Windows NT 10.0.18363.0 64 bit

**Additional information**
Exception: One or more errors occurred. (Cannot access a closed pipe.) (System.AggregateException)
Target site: Boolean Wait(Int32, System.Threading.CancellationToken)
Stack trace: 
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(TimeSpan timeout)
   at Barotrauma.Networking.ChildServerRelay.ReadIncomingMsgs() in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Networking\ChildServerRelay.cs:line 102
   at Barotrauma.Networking.ChildServerRelay.UpdateRead() in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Networking\ChildServerRelay.cs:line 143
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadHelper.ThreadStart()

InnerException: Cannot access a closed pipe.
Target site: Void CheckReadOperations()
Stack trace: 
   at System.IO.Pipes.PipeStream.CheckReadOperations()
   at System.IO.Pipes.PipeStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.<>c.<BeginReadInternal>b__43_0(Object <p0>)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at System.IO.Stream.EndRead(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
Last debug messages:
[16.09.2020 23:53:06] Exiting...
[16.09.2020 23:53:02] Coroutine Barotrauma.Networking.GameClient+<StartGame>d__82 threw an exception: Object reference not set to an instance of an object.
   at Barotrauma.Submarine.SetPosition(Vector2 position, List`1 checkd) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Map\Submarine.cs:line 1027
   at Barotrauma.LinkedSubmarine.OnMapLoaded() in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Map\LinkedSubmarine.cs:line 231
   at Barotrauma.MapEntity.MapLoaded(List`1 entities, Boolean updateHulls) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Map\MapEntity.cs:line 643
   at Barotrauma.Submarine..ctor(SubmarineInfo info, Boolean showWarningMessages, Func`2 loadEntities) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Map\Submarine.cs:line 1280
   at Barotrauma.GameSession.StartRound(LevelData levelData, Boolean mirrorLevel, SubmarineInfo startOutpost, SubmarineInfo endOutpost) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameSession.cs:line 294
   at Barotrauma.Networking.GameClient.StartGame(IReadMessage inc)+MoveNext() in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 1510
   at Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 238

.

**Comment by Regalis11** [comment]
Thank you for the report! If you could provide us the save file it'd help us a lot in diagnosing this. Sorry for the trouble!

**Comment by BloodWitcher** [comment]
There is a link. There are save, and models in archive.
https://yadi.sk/d/lw3dfw3xh3B3XQ

**Comment by Regalis11** [comment]
The underlying cause for the crash seems to be the same as https://github.com/Regalis11/Barotrauma/issues/3459 (the save file somehow getting corrupted and the submarine XML being empty), but we should also look into why ChildServerRelay threw an exception instead of shutting down gracefully when the game was shutting down.
