### ISSUE TITLE
Attacking a creature with a Discharge Coil crashes the game

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#4070]
Reproduction steps:
1. Spawn a crawler near a Discharge Coil
2. Once Crawler is close to the Discharge Coil shock it
3. Game crashes

```
Barotrauma Client crash report (generated on 13.10.2020 18:41:45)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


3C55CEF6AFAB74629E313F4CB6F7543C


Game version 0.10.6.0 (ReleaseWindows, branch dev, revision 7e28bcdef2)
Graphics mode: 2560x1440 (BorderlessWindowed)
VSync OFF
Language: English
Selected content packages: Vanilla 0.9
Level seed: Dunwice
Loaded submarine: Dugong (97B41937CFAEE223755F8914B25BB333)
Selected screen: Barotrauma.GameScreen
SteamManager initialized


System info:
    Operating system: Microsoft Windows NT 10.0.18362.0 64 bit
    GPU name: NVIDIA GeForce GTX 980 Ti
    Display mode: {Width:2560 Height:1440 Format:Color AspectRatio:1,7777778}
    GPU status: Normal


Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Barotrauma.AttackResult ApplyAttack(Barotrauma.Character, Microsoft.Xna.Framework.Vector2, Barotrauma.Attack, Single, Boolean, Barotrauma.Limb)
Stack trace: 
   at Barotrauma.Character.ApplyAttack(Character attacker, Vector2 worldPosition, Attack attack, Single deltaTime, Boolean playSound, Limb targetLimb)
   at Barotrauma.Items.Components.ElectricalDischarger.Discharge()
   at Barotrauma.Items.Components.ElectricalDischarger.Update(Single deltaTime, Camera cam)
   at Barotrauma.Item.Update(Single deltaTime, Camera cam)
   at Barotrauma.MapEntity.UpdateAll(Single deltaTime, Camera cam)
   at Barotrauma.GameScreen.Update(Double deltaTime)
   at Barotrauma.GameMain.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Microsoft.Xna.Framework.Game.Run()
   at Barotrauma.Program.Main(String[] args)


Last debug messages:
[13.10.2020 18:41:23] spawncharacter crawler cursor
[13.10.2020 18:40:53] Generating an outpost for the start of the level... (Location: Dunwice, level type: Outpost)
[13.10.2020 18:40:27] spawnitem "Incendium Bar" inventory
[13.10.2020 18:40:22] Steam achievements have been disabled during this play session.
[13.10.2020 18:40:22] Enabled cheat commands.
[13.10.2020 18:40:22] enablecheats
[13.10.2020 18:40:05] Generating an outpost for the start of the level... (Location: Dunwice, level type: Outpost)
[13.10.2020 18:38:44] (Msg) RelayNetWorkStatus:  avail=OK  config=OK  anyrelay=OK   (OK)
[13.10.2020 18:38:44] (Msg) Ping location: sto2=13+1,sto=14+1/13+1,ams=39+3/33+1,fra=42+4/33+1,waw=45+4/33+1,lux=47+4/37+1,lhr=47+4/38+1,par=51+5/42+1,vie=50+5/45+1,iad=127+12/118+1,sgp=196+19/197+19,gru=258+25/262+1
[13.10.2020 18:38:44] (Msg) Ping measurement completed
[13.10.2020 18:38:42] (Verbose) Communications with routing cluster 'iad' established.
[13.10.2020 18:38:42] (Debug) Destroying relay 'iad#209 (162.254.192.86:27017)' because initial_ping_timeout
[13.10.2020 18:38:40] (Verbose) Communications with routing cluster 'syd' established.
[13.10.2020 18:38:40] (Verbose) Communications with routing cluster 'tyo1' established.
[13.10.2020 18:38:40] (Verbose) Communications with routing cluster 'tyo' established.
[13.10.2020 18:38:40] (Verbose) Communications with routing cluster 'sgp' established.
[13.10.2020 18:38:40] (Verbose) Communications with routing cluster 'sea' established.
[13.10.2020 18:38:40] (Verbose) Communications with routing cluster 'lim' established.
[13.10.2020 18:38:40] (Verbose) Communications with routing cluster 'scl' established.
[13.10.2020 18:38:40] (Verbose) Communications with routing cluster 'maa' established.
[13.10.2020 18:38:40] (Verbose) Communications with routing cluster 'hkg' established.
[13.10.2020 18:38:40] (Verbose) Communications with routing cluster 'lax' established.
[13.10.2020 18:38:40] (Verbose) Communications with routing cluster 'gru' established.
[13.10.2020 18:38:40] (Verbose) Communications with routing cluster 'okc' established.
[13.10.2020 18:38:40] (Verbose) Communications with routing cluster 'vie' established.
[13.10.2020 18:38:40] (Msg) Relay waw#265 (155.133.230.66:27063) is going offline in 237 seconds
[13.10.2020 18:38:40] (Verbose) Communications with routing cluster 'waw' established.
[13.10.2020 18:38:40] (Verbose) Communications with routing cluster 'ord' established.
[13.10.2020 18:38:40] (Verbose) Communications with routing cluster 'jnb' established.
[13.10.2020 18:38:40] (Verbose) Communications with routing cluster 'sto' established.
[13.10.2020 18:38:40] (Verbose) Communications with routing cluster 'sto2' established.
[13.10.2020 18:38:40] (Verbose) Communications with routing cluster 'eat' established.
[13.10.2020 18:38:40] (Verbose) Communications with routing cluster 'mad' established.
[13.10.2020 18:38:40] (Verbose) Communications with routing cluster 'bom' established.
[13.10.2020 18:38:40] (Verbose) Communications with routing cluster 'par' established.
[13.10.2020 18:38:40] (Verbose) Communications with routing cluster 'dxb' established.
[13.10.2020 18:38:39] (Verbose) Communications with routing cluster 'lux' established.
[13.10.2020 18:38:39] (Verbose) Communications with routing cluster 'lhr' established.
[13.10.2020 18:38:39] (Verbose) Communications with routing cluster 'atl' established.
[13.10.2020 18:38:39] (Verbose) Communications with routing cluster 'fra' established.
[13.10.2020 18:38:39] (Verbose) Communications with routing cluster 'ams' established.
[13.10.2020 18:38:39] (Msg) RelayNetWorkStatus:  avail=Attempting  config=OK  anyrelay=Attempting   (Performing ping measurement)
[13.10.2020 18:38:39] (Msg) Performing ping measurement
[13.10.2020 18:38:39] (Msg) Got SDR network config.  Loaded revision 282 OK
[13.10.2020 18:38:39] (Warning) SDR network config fetch first attempt failed.  HTTP 504.  .  Trying again.
[13.10.2020 18:38:32] Attempting to open ALC device "OpenAL Soft on Kaiuttimet (Realtek High Definition Audio)"
[13.10.2020 18:38:31] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[13.10.2020 18:38:31] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
```

**Comment by Rokvach** [comment]
Looks like the same can happen if a Volcano damages a creature

**Comment by alkaid7205** [comment]
I had a similar crash, no discharge coil involved though.
Bot was shooting at 2-3 crawlers through the only top gun and it crashed.
The sub was besides a wreck I looted moments before the crash.
```
Barotrauma Client crash report (generated on 14-Oct-20 12:20:36 AM)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


3C55CEF6AFAB74629E313F4CB6F7543C


Game version 0.10.6.0 (ReleaseWindows, branch dev, revision 7e28bcdef2)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla 0.9
Level seed: New SiberiaVersas
Loaded submarine: Hamsterino (6D83E79302B44EDE0206D2129BAA2E66)
Selected screen: Barotrauma.GameScreen
SteamManager initialized


System info:
    Operating system: Microsoft Windows NT 10.0.19041.0 64 bit
    GPU name: AMD Radeon HD 7800 Series
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal


Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Barotrauma.AttackResult ApplyAttack(Barotrauma.Character, Microsoft.Xna.Framework.Vector2, Barotrauma.Attack, Single, Boolean, Barotrauma.Limb)
Stack trace: 
   at Barotrauma.Character.ApplyAttack(Character attacker, Vector2 worldPosition, Attack attack, Single deltaTime, Boolean playSound, Limb targetLimb)
   at Barotrauma.Character.AddDamage(Character attacker, Vector2 worldPosition, Attack attack, Single deltaTime, Boolean playSound)
   at Barotrauma.Attack.DoDamage(Character attacker, IDamageable target, Vector2 worldPosition, Single deltaTime, Boolean playSound)
   at Barotrauma.Items.Components.Engine.UpdatePropellerDamage(Single deltaTime)
   at Barotrauma.Items.Components.Engine.Update(Single deltaTime, Camera cam)
   at Barotrauma.Item.Update(Single deltaTime, Camera cam)
   at Barotrauma.MapEntity.UpdateAll(Single deltaTime, Camera cam)
   at Barotrauma.GameScreen.Update(Double deltaTime)
   at Barotrauma.GameMain.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Microsoft.Xna.Framework.Game.Run()
   at Barotrauma.Program.Main(String[] args)


Last debug messages:
[13-Oct-20 11:56:58 PM] Generating an outpost for the start of the level... (Location: New Siberia Station, level type: LocationConnection)
[13-Oct-20 11:56:58 PM] Generating an outpost for the end of the level... (Location: The city of Versas, level type: LocationConnection)
[13-Oct-20 11:56:48 PM] Transitioning to New SiberiaVersas (current location: The city of Versas, selected location: New Siberia Station, leaving sub: Hamsterino, at start: True, at end: False, transition type: LeaveLocation)
[13-Oct-20 11:55:16 PM] Generating an outpost for the start of the level... (Location: The city of Versas, level type: Outpost)
[13-Oct-20 11:55:07 PM] Transitioning to Versas (current location: The city of Versas, selected location: New Siberia Station, leaving sub: Hamsterino, at start: True, at end: False, transition type: ReturnToPreviousLocation)
[13-Oct-20 11:51:24 PM] Generating an outpost for the start of the level... (Location: New Siberia Station, level type: LocationConnection)
[13-Oct-20 11:51:23 PM] Generating an outpost for the end of the level... (Location: The city of Versas, level type: LocationConnection)
[13-Oct-20 11:51:13 PM] Transitioning to New SiberiaVersas (current location: The city of Versas, selected location: New Siberia Station, leaving sub: Hamsterino, at start: True, at end: False, transition type: LeaveLocation)
[13-Oct-20 11:46:28 PM] Generating an outpost for the start of the level... (Location: The city of Versas, level type: Outpost)
[13-Oct-20 11:46:19 PM] Transitioning to Versas (current location: The city of Dunwice, selected location: The city of Versas, leaving sub: Hamsterino, at start: False, at end: True, transition type: ProgressToNextLocation)
[13-Oct-20 11:27:11 PM] OpenAL Soft on Microphone (Realtek High Definition Audio) 57
[13-Oct-20 11:23:49 PM] Generating an outpost for the end of the level... (Location: The city of Versas, level type: LocationConnection)
[13-Oct-20 11:23:48 PM] Generating an outpost for the start of the level... (Location: The city of Dunwice, level type: LocationConnection)
[13-Oct-20 11:23:38 PM] Transitioning to DunwiceVersas (current location: The city of Dunwice, selected location: The city of Versas, leaving sub: Hamsterino, at start: True, at end: False, transition type: LeaveLocation)
[13-Oct-20 11:20:45 PM] Generating an outpost for the start of the level... (Location: The city of Dunwice, level type: Outpost)
[13-Oct-20 11:20:00 PM] (Msg) RelayNetWorkStatus:  avail=OK  config=OK  anyrelay=OK   (OK)
[13-Oct-20 11:20:00 PM] (Msg) Ping location: fra=67+6,lux=80+8/70+6,lhr=72+7,ams=74+7/73+6,par=73+7,vie=86+8/79+6,waw=103+10/82+6,sto=93+9/86+6,sto2=95+9/86+6,iad=148+14/149+7,sgp=333+33/247+21,gru=288+28/293+7
[13-Oct-20 11:20:00 PM] (Msg) Ping measurement completed
[13-Oct-20 11:19:59 PM] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Submarines/Downloaded/Indra.sub, size: 700x313)
[13-Oct-20 11:19:56 PM] (Verbose) Communications with routing cluster 'syd' established.
[13-Oct-20 11:19:56 PM] (Verbose) Communications with routing cluster 'sgp' established.
[13-Oct-20 11:19:56 PM] (Verbose) Communications with routing cluster 'tyo' established.
[13-Oct-20 11:19:56 PM] (Verbose) Communications with routing cluster 'tyo1' established.
[13-Oct-20 11:19:56 PM] (Verbose) Communications with routing cluster 'scl' established.
[13-Oct-20 11:19:56 PM] (Verbose) Communications with routing cluster 'sea' established.
[13-Oct-20 11:19:56 PM] (Verbose) Communications with routing cluster 'lim' established.
[13-Oct-20 11:19:56 PM] (Verbose) Communications with routing cluster 'maa' established.
[13-Oct-20 11:19:56 PM] (Verbose) Communications with routing cluster 'okc' established.
[13-Oct-20 11:19:56 PM] (Verbose) Communications with routing cluster 'waw' established.
[13-Oct-20 11:19:56 PM] (Verbose) Communications with routing cluster 'hkg' established.
[13-Oct-20 11:19:56 PM] (Verbose) Communications with routing cluster 'lax' established.
[13-Oct-20 11:19:56 PM] (Verbose) Communications with routing cluster 'sto' established.
[13-Oct-20 11:19:56 PM] (Verbose) Communications with routing cluster 'sto2' established.
[13-Oct-20 11:19:56 PM] (Verbose) Communications with routing cluster 'gru' established.
[13-Oct-20 11:19:56 PM] (Verbose) Communications with routing cluster 'vie' established.
[13-Oct-20 11:19:56 PM] (Verbose) Communications with routing cluster 'ord' established.
[13-Oct-20 11:19:56 PM] (Verbose) Communications with routing cluster 'jnb' established.
[13-Oct-20 11:19:56 PM] (Verbose) Communications with routing cluster 'eat' established.
[13-Oct-20 11:19:56 PM] (Verbose) Communications with routing cluster 'dxb' established.
[13-Oct-20 11:19:56 PM] (Verbose) Communications with routing cluster 'bom' established.
[13-Oct-20 11:19:56 PM] (Verbose) Communications with routing cluster 'mad' established.
[13-Oct-20 11:19:56 PM] (Verbose) Communications with routing cluster 'lux' established.
[13-Oct-20 11:19:56 PM] (Verbose) Communications with routing cluster 'par' established.
[13-Oct-20 11:19:56 PM] (Verbose) Communications with routing cluster 'lhr' established.
[13-Oct-20 11:19:56 PM] (Verbose) Communications with routing cluster 'atl' established.
[13-Oct-20 11:19:56 PM] (Verbose) Communications with routing cluster 'iad' established.
[13-Oct-20 11:19:56 PM] (Verbose) Communications with routing cluster 'ams' established.
[13-Oct-20 11:19:56 PM] (Verbose) Communications with routing cluster 'fra' established.
[13-Oct-20 11:19:56 PM] (Msg) RelayNetWorkStatus:  avail=Attempting  config=OK  anyrelay=Attempting   (Performing ping measurement)
[13-Oct-20 11:19:56 PM] (Msg) Performing ping measurement
[13-Oct-20 11:19:56 PM] (Msg) Got SDR network config.  Loaded revision 282 OK
[13-Oct-20 11:19:55 PM] (Warning) SDR network config fetch first attempt failed.  HTTP 504.  .  Trying again.
[13-Oct-20 11:19:46 PM] Attempting to open ALC device "OpenAL Soft on Speakers (Realtek High Definition Audio)"
[13-Oct-20 11:19:45 PM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[13-Oct-20 11:19:44 PM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[13-Oct-20 11:19:43 PM] Logged in as Zas (SteamID STEAM_1:0:34539448)

```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/bbde1fb8f94058abbbc37367071e516c4860351d

**Comment by Rokvach** [comment]
Tested, wasn't able to reproduce the issue anymore. Working correctly. Closing.
