### ISSUE TITLE
My game crashed -- here is the report

### ISSUE THREAD

**Issue by xXPANAGE28** [Regalis11/Barotrauma#4120]
Barotrauma Client crash report (generated on 10/22/2020 5:15:18 PM)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

6F558E05A9FD96EA104348A23A5B582A

Game version 0.10.5.1 (ReleaseWindows, branch release, revision 9e259b2148)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla 0.9
Level seed: MeltwaterSermilik
Loaded submarine: Humpback (2A65405F7C635B57EEC14988A0BE6EE1)
Selected screen: Barotrauma.GameScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19041.0 64 bit
    GPU name: NVIDIA GeForce GTX 960
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void UpdateUseItem(Boolean, Microsoft.Xna.Framework.Vector2)
Stack trace: 
   at Barotrauma.HumanoidAnimController.UpdateUseItem(Boolean allowMovement, Vector2 handWorldPos) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\Animation\HumanoidAnimController.cs:line 2002
   at Barotrauma.Items.Components.Repairable.UpdateFixAnimation(Character character) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Repairable.cs:line 481
   at Barotrauma.Items.Components.Repairable.Update(Single deltaTime, Camera cam) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Repairable.cs:line 301
   at Barotrauma.Item.Update(Single deltaTime, Camera cam) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 1459
   at Barotrauma.MapEntity.UpdateAll(Single deltaTime, Camera cam) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Map\MapEntity.cs:line 518
   at Barotrauma.GameScreen.Update(Double deltaTime) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 228
   at Barotrauma.GameMain.Update(GameTime gameTime) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 921
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in C:\Users\Joonas\Documents\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in C:\Users\Joonas\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[10/22/2020 5:10:29 PM] Generating an outpost for the end of the level... (Location: The city of Sermilik, level type: LocationConnection)
[10/22/2020 5:10:28 PM] Generating an outpost for the start of the level... (Location: Meltwater, level type: LocationConnection)
[10/22/2020 5:10:19 PM] Transitioning to MeltwaterSermilik (current location: Meltwater, selected location: The city of Sermilik, leaving sub: Humpback, at start: True, at end: False, transition type: LeaveLocation)
[10/22/2020 5:04:17 PM] Generating an outpost for the start of the level... (Location: Meltwater, level type: Outpost)
[10/22/2020 5:04:09 PM] Transitioning to Meltwater (current location: Androgeos Linea, selected location: Meltwater, leaving sub: Humpback, at start: False, at end: True, transition type: ProgressToNextLocation)
[10/22/2020 4:55:21 PM] Generating an outpost for the end of the level... (Location: Meltwater, level type: LocationConnection)
[10/22/2020 4:55:13 PM] Transitioning to Androgeos LineaMeltwater (current location: Androgeos Linea, selected location: Meltwater, leaving sub: Humpback, at start: False, at end: True, transition type: ProgressToNextEmptyLocation)
[10/22/2020 4:37:51 PM] Generating an outpost for the start of the level... (Location: Androgeos Linea, level type: LocationConnection)
[10/22/2020 4:37:42 PM] Transitioning to Androgeos LineaBinnsmouth (current location: Binnsmouth, selected location: Androgeos Linea, leaving sub: Humpback, at start: True, at end: False, transition type: LeaveLocation)
[10/22/2020 4:30:41 PM] Generating an outpost for the start of the level... (Location: Binnsmouth, level type: Outpost)
[10/22/2020 4:30:33 PM] Transitioning to Binnsmouth (current location: Topol, selected location: Binnsmouth, leaving sub: Humpback, at start: False, at end: True, transition type: ProgressToNextLocation)
[10/22/2020 4:14:22 PM] Generating an outpost for the end of the level... (Location: Topol, level type: LocationConnection)
[10/22/2020 4:14:14 PM] Transitioning to BinnsmouthTopol (current location: Topol, selected location: Binnsmouth, leaving sub: Humpback, at start: False, at end: True, transition type: ProgressToNextEmptyLocation)
[10/22/2020 3:55:01 PM] Generating an outpost for the start of the level... (Location: Binnsmouth, level type: LocationConnection)
[10/22/2020 3:54:18 PM] Invalid ragdoll physics. Ragdoll frozen to prevent crashes.
[10/22/2020 3:54:18 PM] Collider velocity invalid ({X:1976.0969 Y:-119.66772}, character: Crawler), resetting the ragdoll.
[10/22/2020 3:54:18 PM] Collider velocity invalid ({X:1972.3591 Y:-119.61871}, character: Crawler), resetting the ragdoll.
[10/22/2020 3:54:18 PM] Collider velocity invalid ({X:1968.624 Y:-119.661545}, character: Crawler), resetting the ragdoll.
[10/22/2020 3:54:18 PM] Collider velocity invalid ({X:1965.3617 Y:-119.70585}, character: Crawler), resetting the ragdoll.
[10/22/2020 3:20:01 PM] Generating an outpost for the start of the level... (Location: Binnsmouth, level type: LocationConnection)
[10/22/2020 3:19:16 PM] (Msg) RelayNetWorkStatus:  avail=OK  config=OK  anyrelay=OK   (OK)
[10/22/2020 3:19:16 PM] (Msg) Ping location: iad=28+2,atl=42+4/41+2,ord=44+4,okc=61+6/61+4,eat=97+9/89+4,lhr=89+8,lax=86+8/90+4,sea=90+9/92+4,ams=94+9/94+8,fra=108+10/100+9,gru=151+15,sgp=278+27/269+4
[10/22/2020 3:19:16 PM] (Msg) Ping measurement completed
[10/22/2020 3:19:15 PM] (Debug) Destroying relay 'sof#4 (139.45.193.10:27018)' because initial_ping_timeout
[10/22/2020 3:19:12 PM] (Debug) Destroying relay 'sof#5 (139.45.193.10:27019)' because initial_ping_timeout
[10/22/2020 3:19:10 PM] (Debug) Destroying relay 'sof#1 (139.45.193.10:27015)' because initial_ping_timeout
[10/22/2020 3:19:07 PM] (Debug) Destroying relay 'sof#3 (139.45.193.10:27017)' because initial_ping_timeout
[10/22/2020 3:19:05 PM] (Verbose) Communications with routing cluster 'sgp' established.
[10/22/2020 3:19:05 PM] (Verbose) Communications with routing cluster 'syd' established.
[10/22/2020 3:19:05 PM] (Verbose) Communications with routing cluster 'tyo1' established.
[10/22/2020 3:19:05 PM] (Verbose) Communications with routing cluster 'tyo' established.
[10/22/2020 3:19:05 PM] (Verbose) Communications with routing cluster 'maa' established.
[10/22/2020 3:19:05 PM] (Verbose) Communications with routing cluster 'waw' established.
[10/22/2020 3:19:05 PM] (Verbose) Communications with routing cluster 'vie' established.
[10/22/2020 3:19:05 PM] (Verbose) Communications with routing cluster 'sto' established.
[10/22/2020 3:19:05 PM] (Verbose) Communications with routing cluster 'sto2' established.
[10/22/2020 3:19:05 PM] (Verbose) Communications with routing cluster 'jnb' established.
[10/22/2020 3:19:05 PM] (Verbose) Communications with routing cluster 'sea' established.
[10/22/2020 3:19:05 PM] (Verbose) Communications with routing cluster 'bom' established.
[10/22/2020 3:19:04 PM] (Verbose) Communications with routing cluster 'scl' established.
[10/22/2020 3:19:04 PM] (Verbose) Communications with routing cluster 'lim' established.
[10/22/2020 3:19:04 PM] (Verbose) Communications with routing cluster 'hkg' established.
[10/22/2020 3:19:04 PM] (Verbose) Communications with routing cluster 'mad' established.
[10/22/2020 3:19:04 PM] (Verbose) Communications with routing cluster 'dxb' established.
[10/22/2020 3:19:04 PM] (Verbose) Communications with routing cluster 'lux' established.
[10/22/2020 3:19:04 PM] (Verbose) Communications with routing cluster 'par' established.
[10/22/2020 3:19:04 PM] (Verbose) Communications with routing cluster 'lhr' established.
[10/22/2020 3:19:04 PM] (Verbose) Communications with routing cluster 'lax' established.
[10/22/2020 3:19:04 PM] (Verbose) Communications with routing cluster 'okc' established.
[10/22/2020 3:19:04 PM] (Verbose) Communications with routing cluster 'gru' established.
[10/22/2020 3:19:04 PM] (Verbose) Communications with routing cluster 'ord' established.
[10/22/2020 3:19:04 PM] (Verbose) Communications with routing cluster 'fra' established.
[10/22/2020 3:19:04 PM] (Verbose) Communications with routing cluster 'eat' established.
[10/22/2020 3:19:04 PM] (Verbose) Communications with routing cluster 'ams' established.
[10/22/2020 3:19:04 PM] (Verbose) Communications with routing cluster 'atl' established.
[10/22/2020 3:19:04 PM] (Verbose) Communications with routing cluster 'iad' established.
[10/22/2020 3:19:04 PM] (Msg) RelayNetWorkStatus:  avail=Attempting  config=OK  anyrelay=Attempting   (Performing ping measurement)
[10/22/2020 3:19:04 PM] (Msg) Performing ping measurement
[10/22/2020 3:19:04 PM] (Msg) Got SDR network config.  Loaded revision 283 OK
[10/22/2020 3:19:04 PM] (Warning) SDR network config fetch first attempt failed.  HTTP 504.  .  Trying again.
[10/22/2020 3:18:59 PM] Attempting to open ALC device "OpenAL Soft on Monitor (NVIDIA High Definition Audio)"
[10/22/2020 3:18:59 PM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[10/22/2020 3:18:58 PM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d5ba0330f9a9dc252dd27c617265bc4c3bc0f03d

**Comment by Rokvach** [comment]
What would be the easiest way to test this? @Regalis11

**Comment by Regalis11** [comment]
1. Start repairing some device
2. While repairing, create an explosion strong enough to rip the character's arms off with console commands (e.g. explosion 100 0 10000)

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
