### ISSUE TITLE
Debug console is flooded when engine max force is 0

### ISSUE THREAD

**Issue by Xeavas** [Regalis11/Barotrauma#4156]
**Description**
It will spam a ton of debug messages, flooding the debug console and effectively locks you in that till the engine is either off or 0% thrust.

**Steps To Reproduce**
Spawn shuttle engine, set max force to 0 (power consumption too for ease), load into test mode and try adjusting the thrust %.

**Version**
[v0.1100.0.0 (unstable)]

**Additional information**
```
Attempted to set the SoundRange of an AITarget to NaN.
   at System.Environment.get_StackTrace()
   at Barotrauma.AITarget.set_SoundRange(Single value) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\AITarget.cs:line 41
   at Barotrauma.AITarget.IncreaseSoundRange(Single deltaTime, Single speed) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\AITarget.cs:line 215
   at Barotrauma.Items.Components.Engine.UpdateAITargets(Single increaseSpeed, Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Machines\Engine.cs:line 146
   at Barotrauma.Items.Components.Engine.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Machines\Engine.cs:line 127
   at Barotrauma.Item.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 1487
   at Barotrauma.MapEntity.UpdateAll(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\MapEntity.cs:line 522
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 228
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 926
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 651
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f52fbf984a1cfef9948fe95c9a8e4bb110ccdf57

**Comment by Xeavas** [comment]
Retested, cannot replicate 👍

**Comment by Rokvach** [comment]
Closing.
