### ISSUE TITLE
Outpost AIs pathfinding to submarines causes crashes

### ISSUE THREAD

**Issue by martinkors** [Regalis11/Barotrauma#4159]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When outpost AIs try to pathfind into a submarine the server crashes.

**Steps To Reproduce**

1. Create a new game (single player or multiplayer it happens on both)
2. Steal something from the outpost
3. Make guards notice it to make them follow you.
4. Run to the submarine.
5. Almost as soon as you or the AI enters the submarine the game/server crashes.

**Version**
Platform: PC
Game version: 0.10.6.2

**Additional information**
```
Barotrauma Dedicated Server crash report (generated on 29-10-2020 19:54:38)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


Game version 0.10.6.2 (ReleaseWindows, branch release, revision d0702df35e)
Language: English
Selected content packages: Vanilla 0.9, Eel Mk2 (Stage 1), Eel Mk2 (Stage 2), Eel Mk2 (Stage 3), Eel Mk2 (Stage 4), Eel Mk2 (Stage 5 Prototype)
Level seed: New Siberia
Loaded submarine: Dugong (C04442922F0114CB928F162A23390BF9)
Selected screen: Barotrauma.GameScreen
Server (Round had started)


System info:
    Operating system: Microsoft Windows NT 6.2.9200.0 64 bit


Exception: Collection was modified; enumeration operation may not execute. (System.InvalidOperationException)
Target site: Void ThrowInvalidOperationException_InvalidOperation_EnumFailedVersion()
Stack trace: 
   at Barotrauma.AIObjectiveManager.SortObjectives() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\Objectives\AIObjectiveManager.cs:line 247
   at Barotrauma.HumanAIController.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\HumanAIController.cs:line 209
   at Barotrauma.Character.UpdateAll(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 2313
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 184
   at Barotrauma.GameMain.Run() in <DEV>\Barotrauma\BarotraumaServer\ServerSource\GameMain.cs:line 352
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Program.cs:line 51
```

**Comment by martinkors** [comment]
I made a pull request with a fix. #4168

**Comment by Regalis11** [comment]
Thank you for the report and proposed fix! We have an existing ticket about this (https://github.com/Regalis11/Barotrauma/issues/4125) and have fixed it in our private repo. We went with a slightly different approach: creating new arrays every frame generates a lot of garbage, so instead we enumerate the objectives in a for loop.
