### ISSUE TITLE
NullReferenceException related to physics while spectating

### ISSUE THREAD

**Issue by mygamingaccount** [Regalis11/Barotrauma#4187]
Unhandled exception when calling `Void SolveVelocityConstraints(FarseerPhysics.Dynamics.SolverData ByRef)`

**Steps To Reproduce**
Seems completely random. The game client was spectating while the campaign players were near alien ruins
[crashreport (8).log](https://github.com/Regalis11/Barotrauma/files/5471203/crashreport.8.log)

**Version**
v0.10.6.2

**Additional information**
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/5471203/crashreport.8.log)

```
Barotrauma Client crash report (generated on 11/01/2020 16:28:01)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


0D1C0453A0E27468236A3A931FAB4DDD


Game version 0.10.6.2 (ReleaseLinux, branch release, revision d0702df35e)
Graphics mode: 2560x1440 (Fullscreen)
VSync ON
Language: English
Selected content packages: Vanilla 0.9, (K.Y.R) Crimson Shard Ausf. K1, (K.Y.R) Crimson Shard Ausf. DB
Level seed: AylesburyKogavostok
Loaded submarine: Dugong Mk3-6 (Extended+Rail) (1D4F37BD3BE04BC6D2C5AEF4699DACE8)
Selected screen: Barotrauma.GameScreen
SteamManager initialized
Client (Round had started)


System info:
    Operating system: Unix 5.7.0.15 64 bit
    GPU name: 
    Display mode: {Width:2560 Height:1440 Format:Color AspectRatio:1.7777778}
    GPU status: Normal


Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void SolveVelocityConstraints(FarseerPhysics.Dynamics.SolverData ByRef)
Stack trace: 
   at FarseerPhysics.Dynamics.Joints.WeldJoint.SolveVelocityConstraints(SolverData& data) in <DEV>/Libraries/Farseer Physics Engine 3.5/Dynamics/Joints/WeldJoint.cs:line 280
   at FarseerPhysics.Dynamics.Island.Solve(TimeStep& step, Vector2& gravity) in <DEV>/Libraries/Farseer Physics Engine 3.5/Dynamics/Island.cs:line 190
   at FarseerPhysics.Dynamics.World.Solve(TimeStep& step) in <DEV>/Libraries/Farseer Physics Engine 3.5/Dynamics/World.cs:line 307
   at FarseerPhysics.Dynamics.World.Step(Single dt, SolverIterations& iterations) in <DEV>/Libraries/Farseer Physics Engine 3.5/Dynamics/World.cs:line 1455
   at FarseerPhysics.Dynamics.World.Step(Single dt) in <DEV>/Libraries/Farseer Physics Engine 3.5/Dynamics/World.cs:line 1394
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Screens/GameScreen.cs:line 266
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/GameMain.cs:line 921
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/SDL/SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Program.cs:line 58


Last debug messages:
[11/01/2020 16:27:55] Bleat
[11/01/2020 16:27:55] Scrino
[11/01/2020 16:27:55] Joseph
[11/01/2020 16:27:55] Ozone
[11/01/2020 16:27:54] Bleat
[11/01/2020 16:27:54] Scrino
[11/01/2020 16:27:54] Joseph
[11/01/2020 16:27:54] Ozone
[11/01/2020 16:27:11] Bleat
[11/01/2020 16:27:11] Scrino
[11/01/2020 16:27:11] Joseph
[11/01/2020 16:27:11] Ozone
[11/01/2020 16:22:34] Bleat
[11/01/2020 16:22:34] Scrino
[11/01/2020 16:22:34] Joseph
[11/01/2020 16:22:34] Ozone
[11/01/2020 16:21:52] Bleat
[11/01/2020 16:21:52] Scrino
[11/01/2020 16:21:52] Joseph
[11/01/2020 16:21:52] Ozone
[11/01/2020 16:21:50] Bleat
[11/01/2020 16:21:50] Joseph
[11/01/2020 16:21:49] Scrino
[11/01/2020 16:21:49] Ozone
[11/01/2020 16:21:46] Task count: 0
[11/01/2020 16:21:42] Generating an outpost for the start of the level... (Location: Aylesbury Research Facility, level type: LocationConnection)
[11/01/2020 16:21:41] Generating an outpost for the end of the level... (Location: Kogavostok Habitation Outpost, level type: LocationConnection)
[11/01/2020 16:21:24] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Submarines/Downloaded/Alkonost.sub, size: 700x313)
[11/01/2020 16:21:24] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Submarines/Downloaded/Phorcys.sub, size: 1750x1080)
[11/01/2020 16:21:08] (Msg) RelayNetWorkStatus:  avail=OK  config=OK  anyrelay=OK   (OK)
[11/01/2020 16:21:08] (Msg) Ping location: fra=20+2,lux=22+2,ams=32+3/26+2,par=30+3/27+2,vie=50+5/31+2,lhr=75+7/34+2,waw=78+7/36+2,sto2=46+4/40+2,sto=47+4/40+2,iad=143+14/104+2,sgp=257+25/196+14,gru=232+23/247+2
[11/01/2020 16:21:08] (Msg) Ping measurement completed
[11/01/2020 16:21:07] LobbyMatchList:  LobbiesMatching: 50
[11/01/2020 16:21:07] LobbyMatchList:  LobbiesMatching: 50
[11/01/2020 16:21:07] SteamAPICallCompleted:   AsyncCall: 17674763867900429840
   Callback: 510
 ParamCount: 4
[11/01/2020 16:21:07] (Debug) Destroying relay 'sof#1 (139.45.193.10:27015)' because initial_ping_timeout
[11/01/2020 16:21:06] AvatarImageLoaded:    SteamID: 76561198005943901
     Image: 2761
      Wide: 184
      Tall: 184
[11/01/2020 16:21:04] (Debug) Destroying relay 'sof#4 (139.45.193.10:27018)' because initial_ping_timeout
[11/01/2020 16:21:01] (Debug) Destroying relay 'sof#5 (139.45.193.10:27019)' because initial_ping_timeout
[11/01/2020 16:20:59] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Submarines/Downloaded/Alkonost.sub, size: 700x313)
[11/01/2020 16:20:59] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Submarines/Downloaded/Phorcys.sub, size: 1750x1080)
[11/01/2020 16:20:59] (Debug) Destroying relay 'sof#2 (139.45.193.10:27016)' because initial_ping_timeout
[11/01/2020 16:20:57] (Verbose) Communications with routing cluster 'hkg' established.
[11/01/2020 16:20:57] (Verbose) Communications with routing cluster 'gru' established.
[11/01/2020 16:20:56] (Verbose) Communications with routing cluster 'jnb' established.
[11/01/2020 16:20:56] (Verbose) Communications with routing cluster 'eat' established.
[11/01/2020 16:20:56] (Verbose) Communications with routing cluster 'lax' established.
[11/01/2020 16:20:56] (Verbose) Communications with routing cluster 'syd' established.
[11/01/2020 16:20:56] (Verbose) Communications with routing cluster 'bom' established.
[11/01/2020 16:20:56] (Verbose) Communications with routing cluster 'iad' established.
[11/01/2020 16:20:56] (Verbose) Communications with routing cluster 'dxb' established.
[11/01/2020 16:20:56] (Verbose) Communications with routing cluster 'scl' established.
[11/01/2020 16:20:56] (Verbose) Communications with routing cluster 'lim' established.
[11/01/2020 16:20:56] (Verbose) Communications with routing cluster 'maa' established.
[11/01/2020 16:20:56] (Verbose) Communications with routing cluster 'lhr' established.
[11/01/2020 16:20:56] (Verbose) Communications with routing cluster 'okc' established.
[11/01/2020 16:20:56] (Verbose) Communications with routing cluster 'tyo' established.
[11/01/2020 16:20:56] (Verbose) Communications with routing cluster 'sea' established.
[11/01/2020 16:20:56] (Verbose) Communications with routing cluster 'tyo1' established.
[11/01/2020 16:20:56] (Verbose) Communications with routing cluster 'ord' established.
[11/01/2020 16:20:56] (Verbose) Communications with routing cluster 'sgp' established.
[11/01/2020 16:20:56] (Verbose) Communications with routing cluster 'atl' established.
[11/01/2020 16:20:56] (Verbose) Communications with routing cluster 'fra' established.
[11/01/2020 16:20:56] (Verbose) Communications with routing cluster 'ams' established.
[11/01/2020 16:20:56] (Verbose) Communications with routing cluster 'par' established.
[11/01/2020 16:20:56] (Verbose) Communications with routing cluster 'lux' established.
[11/01/2020 16:20:56] (Verbose) Communications with routing cluster 'mad' established.
[11/01/2020 16:20:56] (Verbose) Communications with routing cluster 'waw' established.
[11/01/2020 16:20:56] (Verbose) Communications with routing cluster 'vie' established.
[11/01/2020 16:20:56] (Verbose) Communications with routing cluster 'sto' established.
[11/01/2020 16:20:56] (Verbose) Communications with routing cluster 'sto2' established.
[11/01/2020 16:20:56] (Msg) RelayNetWorkStatus:  avail=Attempting  config=OK  anyrelay=Attempting   (Performing ping measurement)
[11/01/2020 16:20:56] (Msg) Performing ping measurement
[11/01/2020 16:20:56] (Msg) Got SDR network config.  Loaded revision 283 OK
[11/01/2020 16:20:47] Attempting to open ALC device "Steinberg UR22mkII  Analogue Stereo"
[11/01/2020 16:20:46] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[11/01/2020 16:20:46] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean

```

**Comment by Regalis11** [comment]
No further sightings of this and no known steps to repro, I think we can close this.
