### ISSUE TITLE
[ready-check] Don't allow player to initialized a ready check to participate on it, also participating on the voting causes a crash

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#4226]
Player who initialized a ready check shouldn't be able to participate on the voting

Encountered a crash when I answered No on my own ready check, could be that someone also just joined at that time.

```
Barotrauma Client crash report (generated on 5.11.2020 20:24:48)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


8AB886D1F3EF76D3F08EE9EC4CF59ACF


Game version 0.1100.0.3 (UnstableWindows, branch dev, revision 697e2215b5)
Graphics mode: 2560x1440 (BorderlessWindowed)
VSync OFF
Language: English
Selected content packages: Vanilla 0.9
Level seed: Wolstone
Loaded submarine: Kail Terra (335F6B6D2D3550495283355493550D02)
Selected screen: Barotrauma.GameScreen
SteamManager initialized
Client (Round had started)


System info:
    Operating system: Microsoft Windows NT 10.0.18363.0 64 bit
    GPU name: NVIDIA GeForce GTX 980 Ti
    Display mode: {Width:2560 Height:1440 Format:Color AspectRatio:1,7777778}
    GPU status: Normal


Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void CreateResultsMessage()
Stack trace: 
   at Barotrauma.ReadyCheck.CreateResultsMessage() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameSession\ReadyCheck.cs:line 82
   at Barotrauma.ReadyCheck.<CreateMessageBox>b__16_1(GUIButton <p0>, Object <p1>) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameSession\ReadyCheck.cs:line 59
   at Barotrauma.GUIButton.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIButton.cs:line 262
   at Barotrauma.GUIComponent.UpdateAuto(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIComponent.cs:line 451
   at Barotrauma.GUI.<>c__DisplayClass143_0.<Update>b__0(GUIComponent c) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1211
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Barotrauma.GUI.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1211
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 950
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58


Last debug messages:
[5.11.2020 20:24:43] Jerry Jalopy
[5.11.2020 20:24:43] P_F
[5.11.2020 20:24:43] Gostak
[5.11.2020 20:24:43] Xeavas
[5.11.2020 20:24:43] Rokvach
[5.11.2020 20:24:43] Cpt. D.B. Cooper
[5.11.2020 20:24:19] Jerry Jalopy
[5.11.2020 20:24:19] P_F
[5.11.2020 20:24:19] Gostak
[5.11.2020 20:24:19] Xeavas
[5.11.2020 20:24:19] Rokvach
[5.11.2020 20:24:19] Kaillera
[5.11.2020 20:24:19] Cpt. D.B. Cooper
[5.11.2020 20:24:09] OpenAL Soft on Mikrofoni (Blackstorm Scout ) 44
[5.11.2020 20:24:06] FPS counter disabled
[5.11.2020 20:24:06] fpscounter
[5.11.2020 20:24:02] Jerry Jalopy
[5.11.2020 20:24:02] P_F
[5.11.2020 20:24:02] Gostak
[5.11.2020 20:24:02] Xeavas
[5.11.2020 20:24:02] Rokvach
[5.11.2020 20:24:02] Kaillera
[5.11.2020 20:24:02] Cpt. D.B. Cooper
[5.11.2020 20:23:31] P_F
[5.11.2020 20:23:31] Gostak
[5.11.2020 20:23:31] Xeavas
[5.11.2020 20:23:31] Rokvach
[5.11.2020 20:23:31] Kaillera
[5.11.2020 20:23:31] Cpt. D.B. Cooper
[5.11.2020 20:23:31] P_F
[5.11.2020 20:23:31] Gostak
[5.11.2020 20:23:31] Xeavas
[5.11.2020 20:23:31] Rokvach
[5.11.2020 20:23:31] Kaillera
[5.11.2020 20:23:31] Cpt. D.B. Cooper
[5.11.2020 20:23:28] P_F
[5.11.2020 20:23:28] Gostak
[5.11.2020 20:23:28] Xeavas
[5.11.2020 20:23:28] Rokvach
[5.11.2020 20:23:28] Kaillera
[5.11.2020 20:23:28] Cpt. D.B. Cooper
[5.11.2020 20:23:27] P_F
[5.11.2020 20:23:27] Gostak
[5.11.2020 20:23:27] Xeavas
[5.11.2020 20:23:27] Rokvach
[5.11.2020 20:23:27] Kaillera
[5.11.2020 20:23:27] Cpt. D.B. Cooper
[5.11.2020 20:23:23] P_F
[5.11.2020 20:23:23] Gostak
[5.11.2020 20:23:23] Xeavas
[5.11.2020 20:23:23] Rokvach
[5.11.2020 20:23:23] Kaillera
[5.11.2020 20:23:23] Cpt. D.B. Cooper
[5.11.2020 20:23:03] P_F
[5.11.2020 20:23:03] Gostak
[5.11.2020 20:23:03] Xeavas
[5.11.2020 20:23:03] Rokvach
[5.11.2020 20:23:03] Kaillera
[5.11.2020 20:23:03] Cpt. D.B. Cooper
[5.11.2020 20:22:49] P_F
[5.11.2020 20:22:49] Gostak
[5.11.2020 20:22:49] Xeavas
[5.11.2020 20:22:49] Rokvach
[5.11.2020 20:22:49] Kaillera
[5.11.2020 20:22:49] Cpt. D.B. Cooper
[5.11.2020 20:22:49] P_F
[5.11.2020 20:22:49] Gostak
[5.11.2020 20:22:49] Xeavas
[5.11.2020 20:22:49] Rokvach
[5.11.2020 20:22:49] Kaillera
[5.11.2020 20:22:49] Cpt. D.B. Cooper
[5.11.2020 20:22:33] P_F
[5.11.2020 20:22:33] Gostak
[5.11.2020 20:22:33] Xeavas
[5.11.2020 20:22:33] Rokvach
[5.11.2020 20:22:33] Kaillera
[5.11.2020 20:22:33] Cpt. D.B. Cooper
[5.11.2020 20:22:32] P_F
[5.11.2020 20:22:32] Gostak
[5.11.2020 20:22:32] Xeavas
[5.11.2020 20:22:32] Rokvach
[5.11.2020 20:22:32] Kaillera
[5.11.2020 20:22:32] Cpt. D.B. Cooper
[5.11.2020 20:22:22] P_F
[5.11.2020 20:22:22] Gostak
[5.11.2020 20:22:22] Xeavas
[5.11.2020 20:22:22] Rokvach
[5.11.2020 20:22:22] Kaillera
[5.11.2020 20:22:22] Cpt. D.B. Cooper
[5.11.2020 20:22:16] Task count: 0
[5.11.2020 20:22:12] Generating an outpost for the start of the level... (Location: Wolstone City, level type: Outpost)
[5.11.2020 20:22:04] Could not find the method "Load" in Barotrauma.LinkedSubmarine.
[5.11.2020 20:20:23] Loading additional level object prefabs from file 'Content/Map/Biomes/TheGreatSea/TheGreatSeaObjects.xml'
[5.11.2020 20:20:23] Loading additional level object prefabs from file 'Content/Map/Biomes/HydrothermalWastes/HydrothermalWastesObjects.xml'
[5.11.2020 20:20:23] Loading additional level object prefabs from file 'Content/Map/Biomes/EuropanRidge/EuropanRidgeObjects.xml'
[5.11.2020 20:20:23] Loading additional level object prefabs from file 'Content/Map/Biomes/ColdCaverns/ColdCavernsObjects.xml'
[5.11.2020 20:20:23] Loading additional level object prefabs from file 'Content/Map/Biomes/AphoticPlateau/AphoticPlateauObjects.xml'
[5.11.2020 20:20:23] Loading additional level object prefabs from file 'Content/Map/Biomes/IceCave/IceCaveObjects.xml'
[5.11.2020 20:20:23] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Submarines/Downloaded/Khors.sub, size: 700x313)
[5.11.2020 20:20:23] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Submarines/Downloaded/Inglia.sub, size: 700x313)
[5.11.2020 20:20:23] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Submarines/Downloaded/Indra.sub, size: 700x313)
[5.11.2020 20:20:07] LobbyMatchList:  LobbiesMatching: 50
[5.11.2020 20:20:07] LobbyMatchList:  LobbiesMatching: 50
[5.11.2020 20:20:07] SteamAPICallCompleted:   AsyncCall: 16444518435981045384
   Callback: 510
 ParamCount: 4
[5.11.2020 20:20:07] PersonaStateChange:      SteamID: 76561198122113652
 ChangeFlags: 64
[5.11.2020 20:20:07] PersonaStateChange:      SteamID: 76561197984598532
 ChangeFlags: 64
[5.11.2020 20:20:07] PersonaStateChange:      SteamID: 76561198065320958
 ChangeFlags: 64
[5.11.2020 20:20:07] PersonaStateChange:      SteamID: 76561197993764162
 ChangeFlags: 64
[5.11.2020 20:20:07] PersonaStateChange:      SteamID: 76561198010943892
 ChangeFlags: 64
[5.11.2020 20:20:07] PersonaStateChange:      SteamID: 76561198122113652
 ChangeFlags: 1089
[5.11.2020 20:20:07] PersonaStateChange:      SteamID: 76561197984598532
 ChangeFlags: 1089
[5.11.2020 20:20:07] PersonaStateChange:      SteamID: 76561198065320958
 ChangeFlags: 1089
[5.11.2020 20:20:07] PersonaStateChange:      SteamID: 76561197993764162
 ChangeFlags: 1089
[5.11.2020 20:20:07] PersonaStateChange:      SteamID: 76561198010943892
 ChangeFlags: 1089
[5.11.2020 20:20:07] AvatarImageLoaded:    SteamID: 76561198864735284
     Image: 99
      Wide: 184
      Tall: 184
[5.11.2020 20:20:07] AvatarImageLoaded:    SteamID: 76561198077192008
     Image: 98
      Wide: 184
      Tall: 184
[5.11.2020 20:20:07] AvatarImageLoaded:    SteamID: 76561198064369668
     Image: 97
      Wide: 184
      Tall: 184
[5.11.2020 20:20:07] AvatarImageLoaded:    SteamID: 76561198043655698
     Image: 96
      Wide: 184
      Tall: 184
[5.11.2020 20:20:07] AvatarImageLoaded:    SteamID: 76561198043328459
     Image: 95
      Wide: 184
      Tall: 184
[5.11.2020 20:20:07] AvatarImageLoaded:    SteamID: 76561198039285786
     Image: 94
      Wide: 184
      Tall: 184
[5.11.2020 20:20:07] AvatarImageLoaded:    SteamID: 76561198037706105
     Image: 93
      Wide: 184
      Tall: 184
[5.11.2020 20:20:07] AvatarImageLoaded:    SteamID: 76561198011638813
     Image: 92
      Wide: 184
      Tall: 184
[5.11.2020 20:20:07] AvatarImageLoaded:    SteamID: 76561198009517162
     Image: 91
      Wide: 184
      Tall: 184
[5.11.2020 20:20:07] AvatarImageLoaded:    SteamID: 76561198001061840
     Image: 90
      Wide: 184
      Tall: 184
[5.11.2020 20:20:07] AvatarImageLoaded:    SteamID: 76561197997567718
     Image: 89
      Wide: 184
      Tall: 184
[5.11.2020 20:20:07] AvatarImageLoaded:    SteamID: 76561197995836791
     Image: 88
      Wide: 184
      Tall: 184
[5.11.2020 20:19:41] Loading additional level object prefabs from file 'Content/Map/Biomes/TheGreatSea/TheGreatSeaObjects.xml'
[5.11.2020 20:19:41] Loading additional level object prefabs from file 'Content/Map/Biomes/HydrothermalWastes/HydrothermalWastesObjects.xml'
[5.11.2020 20:19:41] Loading additional level object prefabs from file 'Content/Map/Biomes/EuropanRidge/EuropanRidgeObjects.xml'
[5.11.2020 20:19:41] Loading additional level object prefabs from file 'Content/Map/Biomes/ColdCaverns/ColdCavernsObjects.xml'
[5.11.2020 20:19:41] Loading additional level object prefabs from file 'Content/Map/Biomes/AphoticPlateau/AphoticPlateauObjects.xml'
[5.11.2020 20:19:41] Loading additional level object prefabs from file 'Content/Map/Biomes/IceCave/IceCaveObjects.xml'
[5.11.2020 20:19:39] (Msg) SDR RelayNetworkStatus:  avail=OK  config=OK  anyrelay=OK   (OK)
[5.11.2020 20:19:39] (Msg) Ping location: sto=13+1,sto2=15+1/14+1,ams=38+3/33+1,fra=39+3/33+1,waw=47+4/34+1,lux=45+4/36+1,lhr=44+4/38+1,par=49+4/42+1,vie=51+5/45+1,iad=126+12/118+1,sgp=205+20/206+20,gru=243+24/262+1
[5.11.2020 20:19:39] (Msg) Ping measurement completed
[5.11.2020 20:19:38] (Debug) Destroying relay 'sof#3 (139.45.193.10:27017)' because initial_ping_timeout
[5.11.2020 20:19:35] (Debug) Destroying relay 'sof#2 (139.45.193.10:27016)' because initial_ping_timeout
[5.11.2020 20:19:32] (Debug) Destroying relay 'sof#5 (139.45.193.10:27019)' because initial_ping_timeout
[5.11.2020 20:19:32] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Submarines/Downloaded/Khors.sub, size: 700x313)
[5.11.2020 20:19:32] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Submarines/Downloaded/Inglia.sub, size: 700x313)
[5.11.2020 20:19:32] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Submarines/Downloaded/Indra.sub, size: 700x313)
[5.11.2020 20:19:30] (Verbose) Communications with routing cluster 'sea' established.
[5.11.2020 20:19:30] (Debug) Destroying relay 'sof#1 (139.45.193.10:27015)' because initial_ping_timeout
[5.11.2020 20:19:30] (Debug) Destroying relay 'sea#103 (205.196.6.148:27025)' because initial_ping_timeout
[5.11.2020 20:19:28] (Verbose) Communications with routing cluster 'syd' established.
[5.11.2020 20:19:27] (Verbose) Communications with routing cluster 'tyo1' established.
[5.11.2020 20:19:27] (Verbose) Communications with routing cluster 'tyo' established.
[5.11.2020 20:19:27] (Verbose) Communications with routing cluster 'sgp' established.
[5.11.2020 20:19:27] (Verbose) Communications with routing cluster 'scl' established.
[5.11.2020 20:19:27] (Verbose) Communications with routing cluster 'maa' established.
[5.11.2020 20:19:27] (Verbose) Communications with routing cluster 'lim' established.
[5.11.2020 20:19:27] (Verbose) Communications with routing cluster 'lax' established.
[5.11.2020 20:19:27] (Verbose) Communications with routing cluster 'okc' established.
[5.11.2020 20:19:27] (Verbose) Communications with routing cluster 'vie' established.
[5.11.2020 20:19:27] (Verbose) Communications with routing cluster 'waw' established.
[5.11.2020 20:19:27] (Verbose) Communications with routing cluster 'gru' established.
[5.11.2020 20:19:27] (Verbose) Communications with routing cluster 'ord' established.
[5.11.2020 20:19:27] (Verbose) Communications with routing cluster 'hkg' established.
[5.11.2020 20:19:27] (Verbose) Communications with routing cluster 'sto2' established.
[5.11.2020 20:19:27] (Verbose) Communications with routing cluster 'jnb' established.
[5.11.2020 20:19:27] (Verbose) Communications with routing cluster 'sto' established.
[5.11.2020 20:19:27] (Verbose) Communications with routing cluster 'eat' established.
[5.11.2020 20:19:27] (Verbose) Communications with routing cluster 'bom' established.
[5.11.2020 20:19:27] (Verbose) Communications with routing cluster 'mad' established.
[5.11.2020 20:19:27] (Verbose) Communications with routing cluster 'dxb' established.
[5.11.2020 20:19:27] (Verbose) Communications with routing cluster 'par' established.
[5.11.2020 20:19:27] (Verbose) Communications with routing cluster 'lux' established.
[5.11.2020 20:19:27] (Verbose) Communications with routing cluster 'lhr' established.
[5.11.2020 20:19:27] (Verbose) Communications with routing cluster 'atl' established.
[5.11.2020 20:19:27] (Verbose) Communications with routing cluster 'iad' established.
[5.11.2020 20:19:27] (Verbose) Communications with routing cluster 'fra' established.
[5.11.2020 20:19:27] (Verbose) Communications with routing cluster 'ams' established.
[5.11.2020 20:19:27] (Msg) SDR RelayNetworkStatus:  avail=Attempting  config=OK  anyrelay=Attempting   (Performing ping measurement)
[5.11.2020 20:19:27] (Msg) Performing ping measurement
[5.11.2020 20:19:27] (Msg) Got SDR network config.  Loaded revision 283 OK
[5.11.2020 20:19:27] (Warning) SDR network config fetch first attempt failed.  HTTP 504.  .  Trying again.
[5.11.2020 20:19:18] Attempting to open ALC device "OpenAL Soft on Kaiuttimet (Realtek High Definition Audio)"
[5.11.2020 20:19:18] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[5.11.2020 20:19:17] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
```

**Comment by 3e849f2e5c** [comment]
Added in https://github.com/Regalis11/Barotrauma-development/commit/23484b222dc507047e7314b0e43c9d0f5cb33ecc

Was unable to reproduce the crash but I've added some error logging and safety checks to hopefully prevent it from happening again in https://github.com/Regalis11/Barotrauma-development/commit/c0bf3c22524d42c861c80bcff19b3985c6c0a2ee

**Comment by Rokvach** [comment]
Still need to test crashing, otherwise working correctly.

**Comment by Rokvach** [comment]
Haven't been able to get this to crash, seems to be working correctly. Closing.
