### ISSUE TITLE
[0.1100.0.3] Some Error when creating a P2P server.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4228]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Loading additional level object prefabs from file 'Content/Map/Biomes/IceCave/IceCaveObjects.xml'
Loading additional level object prefabs from file 'Content/Map/Biomes/AphoticPlateau/AphoticPlateauObjects.xml'
Loading additional level object prefabs from file 'Content/Map/Biomes/ColdCaverns/ColdCavernsObjects.xml'
Loading additional level object prefabs from file 'Content/Map/Biomes/EuropanRidge/EuropanRidgeObjects.xml'
Loading additional level object prefabs from file 'Content/Map/Biomes/HydrothermalWastes/HydrothermalWastesObjects.xml'
Loading additional level object prefabs from file 'Content/Map/Biomes/TheGreatSea/TheGreatSeaObjects.xml'
WARNING: GameSession set to null while in the game screen
   at System.Environment.get_StackTrace()
   at Barotrauma.GameMain.set_GameSession(GameSession value) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 82
   at Barotrauma.Networking.GameClient.Disconnect() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 2611
   at Barotrauma.Networking.GameClient.CancelConnect() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 431
   at Barotrauma.Networking.GameClient.OnDisconnect(Boolean disableReconnect) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 1009
   at Barotrauma.Networking.SteamP2PClientPeer.Close(String msg, Boolean disableReconnect) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\Primitives\Peers\SteamP2PClientPeer.cs:line 369
   at Barotrauma.Networking.GameClient.Disconnect() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 2577
   at Barotrauma.GameMain.QuitToMainMenu(Boolean save) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 1063
   at Barotrauma.GUI.<>c.<TogglePauseMenu>b__181_15(GUIButton yesBtn, Object userdata) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 2251
   at Barotrauma.GUIButton.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIButton.cs:line 262
   at Barotrauma.GUIComponent.UpdateAuto(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIComponent.cs:line 451
   at Barotrauma.GUI.<>c__DisplayClass143_0.<Update>b__0(GUIComponent c) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1211
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Barotrauma.GUI.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1211
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 950
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 651
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58
Lobby created!
Generating an outpost for the end of the level... (Location: Nome City, level type: LocationConnection)
Task count: 0
Kaillera

**Steps To Reproduce**
Was playing another server, left, and then hosted my own server to test something.

**Version**
0.1100.0.3

**Comment by Regalis11** [comment]
This is an intentional warning, not an error, closing
