### ISSUE TITLE
[0.1100.0.3] Spineling's attacks causes errors

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4229]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Failed to read event for entity "Spineling's spike"! {Object reference not set to an instance of an object.}
   at Barotrauma.Items.Components.Projectile.ClientRead(ServerNetObject type, IReadMessage msg, Single sendingTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Components\Projectile.cs:line 75
   at Barotrauma.Item.ClientRead(ServerNetObject type, IReadMessage msg, Single sendingTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Item.cs:line 1116
   at Barotrauma.Networking.ClientEntityEventManager.ReadEvent(IReadMessage buffer, IServerSerializable entity, Single sendingTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\NetEntityEvent\ClientEntityEventManager.cs:line 287
   at Barotrauma.Networking.ClientEntityEventManager.Read(ServerNetObject type, IReadMessage msg, Single sendingTime, List`1 entities) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\NetEntityEvent\ClientEntityEventManager.cs:line 238
Failed to read event for entity "Spineling's spike"! {Object reference not set to an instance of an object.}
   at Barotrauma.Items.Components.Projectile.ClientRead(ServerNetObject type, IReadMessage msg, Single sendingTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Components\Projectile.cs:line 75
   at Barotrauma.Item.ClientRead(ServerNetObject type, IReadMessage msg, Single sendingTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Item.cs:line 1116
   at Barotrauma.Networking.ClientEntityEventManager.ReadEvent(IReadMessage buffer, IServerSerializable entity, Single sendingTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\NetEntityEvent\ClientEntityEventManager.cs:line 287
   at Barotrauma.Networking.ClientEntityEventManager.Read(ServerNetObject type, IReadMessage msg, Single sendingTime, List`1 entities) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\NetEntityEvent\ClientEntityEventManager.cs:line 238
Failed to read event for entity "Spineling's spike"! {Object reference not set to an instance of an object.}
   at Barotrauma.Items.Components.Projectile.ClientRead(ServerNetObject type, IReadMessage msg, Single sendingTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Components\Projectile.cs:line 75
   at Barotrauma.Item.ClientRead(ServerNetObject type, IReadMessage msg, Single sendingTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Item.cs:line 1116
   at Barotrauma.Networking.ClientEntityEventManager.ReadEvent(IReadMessage buffer, IServerSerializable entity, Single sendingTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\NetEntityEvent\ClientEntityEventManager.cs:line 287
   at Barotrauma.Networking.ClientEntityEventManager.Read(ServerNetObject type, IReadMessage msg, Single sendingTime, List`1 entities) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\NetEntityEvent\ClientEntityEventManager.cs:line 238
Failed to read event for entity "Spineling's spike"! {Object reference not set to an instance of an object.}
   at Barotrauma.Items.Components.Projectile.ClientRead(ServerNetObject type, IReadMessage msg, Single sendingTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Components\Projectile.cs:line 75
   at Barotrauma.Item.ClientRead(ServerNetObject type, IReadMessage msg, Single sendingTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Item.cs:line 1116
   at Barotrauma.Networking.ClientEntityEventManager.ReadEvent(IReadMessage buffer, IServerSerializable entity, Single sendingTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\NetEntityEvent\ClientEntityEventManager.cs:line 287
   at Barotrauma.Networking.ClientEntityEventManager.Read(ServerNetObject type, IReadMessage msg, Single sendingTime, List`1 entities) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\NetEntityEvent\ClientEntityEventManager.cs:line 238

**Steps To Reproduce**
Get attacked by Spinelings

**Version**
0.1100.0.3

**Additional information**
Was happening in multiplayer.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/96cc40d93e68b814c2833b333a2badc3b6816e7c

**Comment by Rokvach** [comment]
No issues, closing.
