### ISSUE TITLE
[Unstable V0.1100.0.6] Index was out of range on Hull.DrawSectionColors

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#4327]
Crash report posted on Discord by Rofelix2, no context other than that the crash happened at the start of a multiplayer mission

```
Barotrauma Client crash report (generated on 11/15/2020 7:52:05 PM)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


9E160F0A835C22ADD1B4390249D28AD1


Game version 0.1100.0.6 (ReleaseWindows, branch release, revision cdf2c0711f)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla 0.9, Coral 2.7, Coral 2.7, P1LL-1.0, P1LL-1.0, ORG-2.7, ORG-2.7, Guppy 2.8, Guppy 2.8
Level seed: ncmg0xoM
Loaded submarine: P1LL-1.0 + Trdrop (2B10E566F070CD2262E9ADCCAF5F7606)
Selected screen: Barotrauma.GameScreen
SteamManager initialized
Client (Round had started)


System info:
    Operating system: Microsoft Windows NT 10.0.18362.0 64 bit
    GPU name: NVIDIA GeForce GTX 1650
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal


Exception: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index') (System.ArgumentOutOfRangeException)
Target site: Void ThrowArgumentOutOfRange_IndexException()
Stack trace: 
   at Barotrauma.Hull.DrawSectionColors(SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Map\Hull.cs:line 339
   at Barotrauma.Submarine.DrawPaintedColors(SpriteBatch spriteBatch, Boolean editing, Predicate`1 predicate) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Map\Submarine.cs:line 354
   at Barotrauma.GameScreen.DrawMap(GraphicsDevice graphics, SpriteBatch spriteBatch, Double deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\GameScreen.cs:line 186
   at Barotrauma.GameScreen.Draw(Double deltaTime, GraphicsDevice graphics, SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\GameScreen.cs:line 122
   at Barotrauma.GameMain.Draw(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 1008
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 669
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 511
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59


Last debug messages:
[11/15/2020 7:52:02 PM] AI debug info visible
[11/15/2020 7:52:02 PM] debugai
[11/15/2020 7:52:00 PM] Command "dev" not found.
[11/15/2020 7:52:00 PM] Server command: dev
[11/15/2020 7:52:00 PM] dev
[11/15/2020 7:51:59 PM] hUbert
[11/15/2020 7:51:59 PM] Rofelix2
[11/15/2020 7:51:59 PM] freecam
[11/15/2020 7:51:55 PM] hUbert
[11/15/2020 7:51:55 PM] Rofelix2
[11/15/2020 7:51:53 PM] Task count: 0
[11/15/2020 7:51:50 PM] Generating an outpost for the end of the level... (Location: Corick Linea Biomedical Research Center, level type: LocationConnection)
[11/15/2020 7:51:50 PM] Creating hulls between docking ports failed. The upper docking port seems to be very far from any hulls in the upper submarine.
[11/15/2020 7:51:49 PM] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Submarines/P1LL-1.0 + Trdrop.sub, size: 1650x800)
[11/15/2020 7:50:18 PM] hUbert
[11/15/2020 7:50:18 PM] Rofelix2
[11/15/2020 7:49:29 PM] Line of sight effect disabled
[11/15/2020 7:49:29 PM] los
[11/15/2020 7:47:22 PM] AI debug info hidden
[11/15/2020 7:47:22 PM] debugai
[11/15/2020 7:47:17 PM] Command "ok" not found.
[11/15/2020 7:47:17 PM] Server command: ok
[11/15/2020 7:47:17 PM] ok
[11/15/2020 7:46:59 PM] hUbert
[11/15/2020 7:46:59 PM] Rofelix2
[11/15/2020 7:46:59 PM] Server command: control Rofelix2
[11/15/2020 7:46:59 PM] control Rofelix2
[11/15/2020 7:46:46 PM] Server command: say behind us?
[11/15/2020 7:46:46 PM] say behind us?
[11/15/2020 7:46:29 PM] Server command: teleportsub
[11/15/2020 7:46:29 PM] teleportsub
[11/15/2020 7:46:17 PM] Server command: say left or right
[11/15/2020 7:46:17 PM] say left or right
[11/15/2020 7:46:13 PM] Command "left" not found.
[11/15/2020 7:46:13 PM] Server command: left or right
[11/15/2020 7:46:13 PM] left or right
[11/15/2020 7:46:03 PM] Server command: say where is our objective
[11/15/2020 7:46:03 PM] say where is our objective
[11/15/2020 7:45:28 PM] Server command: say there are 3 or 2 caves
[11/15/2020 7:45:28 PM] say there are 3 or 2 caves
[11/15/2020 7:45:07 PM] Lighting disabled
[11/15/2020 7:45:07 PM] lighting
[11/15/2020 7:45:03 PM] hUbert
[11/15/2020 7:45:03 PM] Rofelix2
[11/15/2020 7:45:03 PM] freecamera
[11/15/2020 7:44:56 PM] hUbert
[11/15/2020 7:44:56 PM] Rofelix2
[11/15/2020 7:44:53 PM] Task count: 0
[11/15/2020 7:44:49 PM] Generating an outpost for the end of the level... (Location: Belus Linea Biomedical Research Center, level type: LocationConnection)
[11/15/2020 7:44:48 PM] Creating hulls between docking ports failed. The upper docking port seems to be very far from any hulls in the upper submarine.
[11/15/2020 7:44:48 PM] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Submarines/P1LL-1.0 + Trdrop.sub, size: 1650x800)
[11/15/2020 7:42:46 PM] hUbert
[11/15/2020 7:42:46 PM] Rofelix2
[11/15/2020 7:42:32 PM] Server command: say im not permited to use ''spawnsub''
[11/15/2020 7:42:32 PM] say im not permited to use ''spawnsub''
[11/15/2020 7:42:17 PM] You're not permitted to use the command "spawnsub"!
[11/15/2020 7:42:17 PM] spawnsub TrDrop-3.0
[11/15/2020 7:41:54 PM] Server command: say make the sub idle
[11/15/2020 7:41:54 PM] say make the sub idle
[11/15/2020 7:41:45 PM] Server command: teleportsub 
[11/15/2020 7:41:45 PM] teleportsub 
[11/15/2020 7:40:52 PM] Server command: seed
[11/15/2020 7:40:52 PM] seed
[11/15/2020 7:40:30 PM] Server command: say pls tell me its not bellow us
[11/15/2020 7:40:30 PM] say pls tell me its not bellow us
[11/15/2020 7:40:23 PM] Server command: say where is the objective?
[11/15/2020 7:40:23 PM] say where is the objective?
[11/15/2020 7:40:08 PM] Server command: say this level
[11/15/2020 7:40:08 PM] say this level
[11/15/2020 7:40:04 PM] Server command: say bruh
[11/15/2020 7:40:04 PM] say bruh
[11/15/2020 7:40:01 PM] Server command: SAY
[11/15/2020 7:40:01 PM] SAY
[11/15/2020 7:39:57 PM] Command "ARE" not found.
[11/15/2020 7:39:57 PM] Server command: ARE YOU
[11/15/2020 7:39:57 PM] ARE YOU
[11/15/2020 7:39:56 PM] Command "BRUH" not found.
[11/15/2020 7:39:56 PM] Server command: BRUH
[11/15/2020 7:39:56 PM] BRUH
[11/15/2020 7:39:52 PM] AI debug info visible
[11/15/2020 7:39:52 PM] debugai
[11/15/2020 7:39:44 PM] Lighting disabled
[11/15/2020 7:39:44 PM] lighting
[11/15/2020 7:39:38 PM] Server command: say pull it down a lil
[11/15/2020 7:39:38 PM] say pull it down a lil
[11/15/2020 7:39:28 PM] hUbert
[11/15/2020 7:39:28 PM] Rofelix2
[11/15/2020 7:39:28 PM] freecam
[11/15/2020 7:39:24 PM] Server command: enablecheats
[11/15/2020 7:39:24 PM] enablecheats
[11/15/2020 7:39:10 PM] hUbert
[11/15/2020 7:39:10 PM] Rofelix2
[11/15/2020 7:39:08 PM] Task count: 0
[11/15/2020 7:39:05 PM] Generating an outpost for the end of the level... (Location: Delphi Flexus Prospecting Outpost, level type: LocationConnection)
[11/15/2020 7:37:48 PM] Lobby created!
[11/15/2020 7:37:34 PM] LobbyMatchList:  LobbiesMatching: 41
[11/15/2020 7:37:34 PM] LobbyMatchList:  LobbiesMatching: 41
[11/15/2020 7:37:34 PM] SteamAPICallCompleted:   AsyncCall: 17244571304262051536
   Callback: 510
 ParamCount: 4
[11/15/2020 7:37:34 PM] AvatarImageLoaded:    SteamID: 76561198161293902
     Image: 176
      Wide: 184
      Tall: 184
[11/15/2020 7:37:34 PM] SteamRelayNetworkStatus:                      Avail: Current
 PingMeasurementInProgress: 1
        AvailNetworkConfig: Current
             AvailAnyRelay: Current
                  DebugMsg: System.Byte[]
[11/15/2020 7:37:32 PM] Not attempting to reconnect (DisconnectReason doesn't allow reconnection).
[11/15/2020 7:37:32 PM] Received a disconnect message (ServerShutdown)
[11/15/2020 7:36:29 PM] Rofelix2
[11/15/2020 7:36:29 PM] Unstable hUbert
[11/15/2020 7:30:21 PM] Rofelix2
[11/15/2020 7:30:21 PM] Unstable hUbert
[11/15/2020 7:29:15 PM] Rofelix2
[11/15/2020 7:29:15 PM] Unstable hUbert
[11/15/2020 7:29:12 PM] Rofelix2
[11/15/2020 7:29:12 PM] Unstable hUbert
[11/15/2020 7:27:42 PM] Rofelix2
[11/15/2020 7:27:42 PM] Unstable hUbert
[11/15/2020 7:27:16 PM] Rofelix2
[11/15/2020 7:27:16 PM] Unstable hUbert
[11/15/2020 7:27:10 PM] Rofelix2
[11/15/2020 7:27:10 PM] Unstable hUbert
[11/15/2020 7:26:44 PM] Invalid ragdoll physics. Ragdoll frozen to prevent crashes.
[11/15/2020 7:26:44 PM] Collider velocity invalid ({X:1581.5688 Y:-1193.881}, character: Mudraptor_unarmored), resetting the ragdoll. Ragdoll controlled remotely. Playing as a client.
[11/15/2020 7:26:44 PM] Collider velocity invalid ({X:1581.6975 Y:-1193.9525}, character: Mudraptor_unarmored), resetting the ragdoll. Ragdoll controlled remotely. Playing as a client.
[11/15/2020 7:26:44 PM] Collider velocity invalid ({X:1581.825 Y:-1194.0216}, character: Mudraptor_unarmored), resetting the ragdoll. Ragdoll controlled remotely. Playing as a client.
[11/15/2020 7:26:39 PM] Collider velocity invalid ({X:1543.1112 Y:-1165.8986}, character: Mudraptor_unarmored), resetting the ragdoll. Ragdoll controlled remotely. Playing as a client.
[11/15/2020 7:26:06 PM] Invalid ragdoll physics. Ragdoll frozen to prevent crashes.
[11/15/2020 7:26:06 PM] Collider velocity invalid ({X:1542.5508 Y:-1164.2896}, character: Mudraptor_unarmored), resetting the ragdoll. Ragdoll controlled remotely. Playing as a client.
[11/15/2020 7:26:06 PM] Collider velocity invalid ({X:1541.7788 Y:-1163.7863}, character: Mudraptor_unarmored), resetting the ragdoll. Ragdoll controlled remotely. Playing as a client.
[11/15/2020 7:26:06 PM] Collider velocity invalid ({X:1541.012 Y:-1163.2817}, character: Mudraptor_unarmored), resetting the ragdoll. Ragdoll controlled remotely. Playing as a client.
[11/15/2020 7:26:06 PM] Collider velocity invalid ({X:1540.7439 Y:-1162.0072}, character: Mudraptor_unarmored), resetting the ragdoll. Ragdoll controlled remotely. Playing as a client.
[11/15/2020 7:21:05 PM] Rofelix2
[11/15/2020 7:21:05 PM] Unstable hUbert
[11/15/2020 7:20:54 PM] Rofelix2
[11/15/2020 7:20:54 PM] Unstable hUbert
[11/15/2020 7:19:55 PM] Rofelix2
[11/15/2020 7:19:55 PM] Unstable hUbert
[11/15/2020 7:19:33 PM] Rofelix2
[11/15/2020 7:19:33 PM] Unstable hUbert
[11/15/2020 7:19:22 PM] Rofelix2
[11/15/2020 7:19:22 PM] Unstable hUbert
[11/15/2020 7:18:56 PM] You're not permitted to use the command "lock"!
[11/15/2020 7:18:56 PM] lock
[11/15/2020 7:18:46 PM] Rofelix2
[11/15/2020 7:18:46 PM] Unstable hUbert
[11/15/2020 7:17:51 PM] Rofelix2
[11/15/2020 7:17:51 PM] Unstable hUbert
[11/15/2020 7:17:47 PM] Rofelix2
[11/15/2020 7:17:46 PM] Rofelix2
[11/15/2020 7:17:38 PM] Task count: 0
[11/15/2020 7:17:34 PM] Generating an outpost for the end of the level... (Location: Oshan, level type: LocationConnection)
[11/15/2020 7:17:31 PM] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Submarines/Downloaded/DOMA Prototype v6.sub, size: 1369x555)
[11/15/2020 7:17:31 PM] Creating hulls between docking ports failed. The upper docking port seems to be very far from any hulls in the upper submarine.
[11/15/2020 7:17:30 PM] Creating hulls between docking ports failed. The lower docking port seems to be very far from any hulls in the lower submarine.
[11/15/2020 7:15:53 PM] File transfer error: received data without a transfer initiation message
[11/15/2020 7:15:53 PM] File transfer error: received data without a transfer initiation message
[11/15/2020 7:15:53 PM] File transfer error: received data without a transfer initiation message
[11/15/2020 7:15:53 PM] File transfer error: received data without a transfer initiation message
[11/15/2020 7:15:53 PM] File transfer error: received data without a transfer initiation message
[11/15/2020 7:15:53 PM] File transfer error: received data without a transfer initiation message
[11/15/2020 7:15:53 PM] File transfer error: received data without a transfer initiation message
[11/15/2020 7:15:53 PM] File transfer error: received data without a transfer initiation message
[11/15/2020 7:15:53 PM] File transfer error: received data without a transfer initiation message
[11/15/2020 7:15:53 PM] File transfer error: received data without a transfer initiation message
[11/15/2020 7:15:53 PM] File transfer error: received data without a transfer initiation message
[11/15/2020 7:15:53 PM] File transfer error: received data without a transfer initiation message
[11/15/2020 7:15:53 PM] File transfer error: received data without a transfer initiation message
[11/15/2020 7:15:53 PM] File transfer error: received data without a transfer initiation message
[11/15/2020 7:15:53 PM] File transfer error: received data without a transfer initiation message
[11/15/2020 7:15:53 PM] File transfer error: received data without a transfer initiation message
[11/15/2020 7:15:53 PM] File transfer error: received data without a transfer initiation message
[11/15/2020 7:15:53 PM] File transfer error: received data without a transfer initiation message
[11/15/2020 7:15:53 PM] File transfer error: received data without a transfer initiation message
[11/15/2020 7:15:53 PM] File transfer error: received data without a transfer initiation message
[11/15/2020 7:15:53 PM] File transfer error: received data without a transfer initiation message
[11/15/2020 7:15:53 PM] File transfer error: received data without a transfer initiation message
[11/15/2020 7:15:53 PM] File transfer error: received data without a transfer initiation message
[11/15/2020 7:15:53 PM] File transfer error: received data without a transfer initiation message
[11/15/2020 7:15:53 PM] File transfer error: received data without a transfer initiation message
[11/15/2020 7:15:53 PM] File transfer error: received data without a transfer initiation message
[11/15/2020 7:15:53 PM] File transfer error: received data without a transfer initiation message
[11/15/2020 7:15:53 PM] File transfer error: received data without a transfer initiation message
[11/15/2020 7:15:53 PM] File transfer error: received data without a transfer initiation message
[11/15/2020 7:15:53 PM] File transfer error: received data without a transfer initiation message
[11/15/2020 7:15:53 PM] File transfer error: received data without a transfer initiation message
[11/15/2020 7:15:53 PM] File transfer error: received data without a transfer initiation message
[11/15/2020 7:15:53 PM] File transfer error: received data without a transfer initiation message
[11/15/2020 7:15:53 PM] File transfer error: received data without a transfer initiation message
[11/15/2020 7:15:53 PM] File transfer error: received data without a transfer initiation message
[11/15/2020 7:15:53 PM] File transfer error: received data without a transfer initiation message
[11/15/2020 7:15:53 PM] File transfer error: received data without a transfer initiation message
[11/15/2020 7:15:53 PM] File transfer error: received data without a transfer initiation message
[11/15/2020 7:15:53 PM] File transfer error: received data without a transfer initiation message
[11/15/2020 7:15:53 PM] File transfer error: received data without a transfer initiation message
[11/15/2020 7:15:53 PM] File transfer error: received data without a transfer initiation message
[11/15/2020 7:15:53 PM] File transfer error: received data without a transfer initiation message
[11/15/2020 7:15:53 PM] File transfer error: received data without a transfer initiation message
[11/15/2020 7:15:53 PM] File transfer error: received data without a transfer initiation message
[11/15/2020 7:15:53 PM] File transfer error: received data without a transfer initiation message
[11/15/2020 7:15:53 PM] File transfer error: received data without a transfer initiation message
[11/15/2020 7:15:53 PM] File transfer error: received data without a transfer initiation message
[11/15/2020 7:14:49 PM] LobbyMatchList:  LobbiesMatching: 47
[11/15/2020 7:14:49 PM] LobbyMatchList:  LobbiesMatching: 47
[11/15/2020 7:14:49 PM] SteamAPICallCompleted:   AsyncCall: 13497311312813131582
   Callback: 510
 ParamCount: 4
[11/15/2020 7:14:49 PM] PersonaStateChange:      SteamID: 76561198072441599
 ChangeFlags: 64
[11/15/2020 7:14:49 PM] PersonaStateChange:      SteamID: 76561198072441599
 ChangeFlags: 1024
[11/15/2020 7:14:36 PM] (Msg) RelayNetWorkStatus:  avail=OK  config=OK  anyrelay=OK   (OK)
[11/15/2020 7:14:36 PM] (Msg) Ping location: gru=7+0,scl=57+5/59+0,lim=87+8/89+0,iad=119+11,ord=135+13,atl=127+13/138+0,okc=146+14,eat=209+20/181+11,sea=197+19/184+11,lax=189+18/191+0,fra=211+21/205+11,sgp=372+37/361+13
[11/15/2020 7:14:36 PM] (Msg) Ping measurement completed
[11/15/2020 7:14:36 PM] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Mods/P1LL-1.0/P1LL-1.0.sub, size: 1370x650)
[11/15/2020 7:14:35 PM] (Debug) Destroying relay 'sof#2 (139.45.193.10:27016)' because initial_ping_timeout
[11/15/2020 7:14:35 PM] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Submarines/TrDrop-3.0.sub, size: 1650x800)
[11/15/2020 7:14:32 PM] (Debug) Destroying relay 'sof#1 (139.45.193.10:27015)' because initial_ping_timeout
[11/15/2020 7:14:30 PM] (Debug) Destroying relay 'sof#5 (139.45.193.10:27019)' because initial_ping_timeout
[11/15/2020 7:14:27 PM] (Debug) Destroying relay 'sof#4 (139.45.193.10:27018)' because initial_ping_timeout
[11/15/2020 7:14:25 PM] (Verbose) Communications with routing cluster 'syd' established.
[11/15/2020 7:14:25 PM] (Verbose) Communications with routing cluster 'sgp' established.
[11/15/2020 7:14:25 PM] (Verbose) Communications with routing cluster 'tyo1' established.
[11/15/2020 7:14:25 PM] (Verbose) Communications with routing cluster 'tyo' established.
[11/15/2020 7:14:25 PM] (Verbose) Communications with routing cluster 'maa' established.
[11/15/2020 7:14:25 PM] (Verbose) Communications with routing cluster 'sto2' established.
[11/15/2020 7:14:25 PM] (Verbose) Communications with routing cluster 'waw' established.
[11/15/2020 7:14:25 PM] (Verbose) Communications with routing cluster 'vie' established.
[11/15/2020 7:14:25 PM] (Msg) Cluster 'atl' selection penalty for load balancing purposes changed from 2ms to 1ms.  (As per atl#22 (162.254.199.178:27016)).
[11/15/2020 7:14:25 PM] (Verbose) Communications with routing cluster 'sto' established.
[11/15/2020 7:14:25 PM] (Verbose) Communications with routing cluster 'jnb' established.
[11/15/2020 7:14:25 PM] (Verbose) Communications with routing cluster 'sea' established.
[11/15/2020 7:14:25 PM] (Verbose) Communications with routing cluster 'bom' established.
[11/15/2020 7:14:25 PM] (Verbose) Communications with routing cluster 'hkg' established.
[11/15/2020 7:14:25 PM] (Msg) Relay dxb#75 (185.25.183.178:27051) is going offline in 241 seconds
[11/15/2020 7:14:25 PM] (Verbose) Communications with routing cluster 'dxb' established.
[11/15/2020 7:14:25 PM] (Verbose) Communications with routing cluster 'lux' established.
[11/15/2020 7:14:25 PM] (Verbose) Communications with routing cluster 'mad' established.
[11/15/2020 7:14:25 PM] (Verbose) Communications with routing cluster 'par' established.
[11/15/2020 7:14:25 PM] (Verbose) Communications with routing cluster 'lhr' established.
[11/15/2020 7:14:25 PM] (Verbose) Communications with routing cluster 'lax' established.
[11/15/2020 7:14:25 PM] (Verbose) Communications with routing cluster 'okc' established.
[11/15/2020 7:14:25 PM] (Verbose) Communications with routing cluster 'ord' established.
[11/15/2020 7:14:24 PM] (Verbose) Communications with routing cluster 'fra' established.
[11/15/2020 7:14:24 PM] (Verbose) Communications with routing cluster 'eat' established.
[11/15/2020 7:14:24 PM] (Verbose) Communications with routing cluster 'ams' established.
[11/15/2020 7:14:24 PM] (Verbose) Communications with routing cluster 'lim' established.
[11/15/2020 7:14:24 PM] (Verbose) Communications with routing cluster 'scl' established.
[11/15/2020 7:14:24 PM] (Msg) Cluster 'atl' has a selection penalty of 2ms for load balancing purposes.  (As per atl#22 (162.254.199.178:27016)).
[11/15/2020 7:14:24 PM] (Verbose) Communications with routing cluster 'atl' established.
[11/15/2020 7:14:24 PM] (Verbose) Communications with routing cluster 'iad' established.
[11/15/2020 7:14:24 PM] (Warning) SteamNetworkingSockets lock held for 36.0ms.  (Performance warning).  ServiceThread,RecvUDPPacket
[11/15/2020 7:14:24 PM] (Verbose) Communications with routing cluster 'gru' established.
[11/15/2020 7:14:24 PM] (Warning) SteamNetworkingSockets lock held for 129.0ms.  (Performance warning).  ServiceThread,CSDRHTTPRequest::Think,OnNetworkConfigFetchCompleted,OpenRawUDPSocketInternal(x10),SendUDPacket(x10)
[11/15/2020 7:14:24 PM] (Msg) RelayNetWorkStatus:  avail=Attempting  config=OK  anyrelay=Attempting   (Performing ping measurement)
[11/15/2020 7:14:24 PM] (Msg) Performing ping measurement
[11/15/2020 7:14:24 PM] (Msg) Got SDR network config.  Loaded revision 283 OK
[11/15/2020 7:14:24 PM] (Warning) SDR network config fetch first attempt failed.  HTTP 504.  .  Trying again.
[11/15/2020 7:14:05 PM] Attempting to open ALC device "OpenAL Soft on Alto-falantes (2- Realtek High Definition Audio)"
[11/15/2020 7:14:04 PM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[11/15/2020 7:14:03 PM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e283233f5aae36e20e9752734ae84c4b81b420f4

**Comment by Rokvach** [comment]
Tested, I wasn't able to reproduce the issue, looks to be working correctly. Closing.
