### ISSUE TITLE
[0.1100.0.6] - Crash when throwing grenades in quick succession at large number of ballast flora branches

### ISSUE THREAD

**Issue by Xeavas** [Regalis11/Barotrauma#4328]
**Description :**
Throwing grenades in quick succession will cause said game to spit out errors in console and crash after you close said console.
Possibly something to do with massive amounts of particles generated.
![juice](https://user-images.githubusercontent.com/72674994/99200472-78562080-27e0-11eb-8b27-24f94cf33afa.png)

**Steps To Reproduce :**
- Create campaign save
- `ballastflora infect ballastflora`
- `ballastflora growthwarp 1000`
- Find a good chunk of it and throw 4 grenades (incendium/frag) in quick succession

Here's the save I used to replicate
[testingflora.zip](https://github.com/Regalis11/Barotrauma/files/5543379/testingflora.zip)

**Version :** [0.1100.0.6]

**Additional information**
```
Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void Emit(Microsoft.Xna.Framework.Vector2)
Stack trace: 
   at Barotrauma.MapCreatures.Behavior.BallastFloraBehavior.DamageParticle.Emit(Vector2 pos) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Map\Creatures\BallastFloraBehavior.cs:line 47
   at Barotrauma.MapCreatures.Behavior.BallastFloraBehavior.CreateDamageParticle(BallastFloraBranch branch, Single damage) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Map\Creatures\BallastFloraBehavior.cs:line 137
   at Barotrauma.MapCreatures.Behavior.BallastFloraBehavior.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Creatures\BallastFloraBehavior.cs:line 425
   at Barotrauma.Hull.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Hull.cs:line 695
   at Barotrauma.MapEntity.UpdateAll(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\MapEntity.cs:line 541
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 235
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 924
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58
```

```
Last debug messages: 
Error in SerializableProperty.TrySetValue {Object reference not set to an instance of an object.}
   at Barotrauma.MapCreatures.Behavior.BallastFloraBehavior.DamageParticle.Emit(Vector2 pos) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Map\Creatures\BallastFloraBehavior.cs:line 47
   at Barotrauma.MapCreatures.Behavior.BallastFloraBehavior.CreateDeathParticle(BallastFloraBranch branch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Map\Creatures\BallastFloraBehavior.cs:line 150
   at Barotrauma.MapCreatures.Behavior.BallastFloraBehavior.RemoveBranch(BallastFloraBranch branch) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Creatures\BallastFloraBehavior.cs:line 943
   at Barotrauma.MapCreatures.Behavior.BallastFloraBehavior.DamageBranch(BallastFloraBranch branch, Single amount, AttackType type, Character attacker) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Creatures\BallastFloraBehavior.cs:line 888
   at Barotrauma.Explosion.<>c__DisplayClass37_1.<RangedBallastFloraDamage>b__0(BallastFloraBranch branch) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Explosion.cs:line 456
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Barotrauma.Explosion.RangedBallastFloraDamage(Vector2 worldPosition, Single worldRange, Single damage, Character attacker) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Explosion.cs:line 439
   at Barotrauma.Explosion.Explode(Vector2 worldPosition, Entity damageSource, Character attacker) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Explosion.cs:line 102
   at Barotrauma.StatusEffect.Apply(Single deltaTime, Entity entity, IEnumerable`1 targets, Nullable`1 worldPosition) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\StatusEffects\StatusEffect.cs:line 965
   at Barotrauma.StatusEffect.Apply(ActionType type, Single deltaTime, Entity entity, IEnumerable`1 targets, Nullable`1 worldPosition) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\StatusEffects\StatusEffect.cs:line 822
   at Barotrauma.Item.ApplyStatusEffect(StatusEffect effect, ActionType type, Single deltaTime, Character character, Limb limb, Entity useTarget, Boolean isNetworkEvent, Boolean checkCondition, Nullable`1 worldPosition) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 1384
   at Barotrauma.Item.ApplyStatusEffects(ActionType type, Single deltaTime, Character character, Limb limb, Entity useTarget, Boolean isNetworkEvent, Nullable`1 worldPosition) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 1293
   at Barotrauma.Item.set_Condition(Single value) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 433
   at Barotrauma.SerializableProperty.TrySetValueWithoutReflection(Object parentObject, Object value) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Serialization\SerializableProperty.cs:line 553
   at Barotrauma.SerializableProperty.TrySetValue(Object parentObject, Single value) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Serialization\SerializableProperty.cs:line 359
```

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6fe0919b8c75d7468b6d0f61d059dfb985351242

**Comment by Rokvach** [comment]
Tested, wasn't able to reproduce the issue, looks to be working correctly. Closing.
