### ISSUE TITLE
Unplayable due to continuous crash crashing

### ISSUE THREAD

**Issue by MoonEater916** [Regalis11/Barotrauma#438]
Barotrauma Client crash report (generated on 6/5/2018 5:55:06 PM)

Barotrauma seems to have crashed. Sorry for the inconvenience! 
If you'd like to help fix the bug that caused the crash, please send this file to the developers on the Undertow Games forums.

Game version 0.8.1.2
Graphics mode: 1680x1050 (BorderlessWindowed)
Selected content package: BTE 6.1
Level seed: QtniJfUT
Loaded submarine: [BTE] Hurricane (4A5C77682D06343032E50BA170C2EE01)
Selected screen: Barotrauma.GameScreen
Server (Round had started)

System info:
    Operating system: Microsoft Windows NT 6.2.9200.0 64 bit
    GPU name: AMD Radeon (TM) R9 380 Series
    Display mode: {Width:1680 Height:1050 Format:Color AspectRatio:1.6}
    GPU status: Normal

Exception: Object reference not set to an instance of an object.
Target site: Void UpdateWaiting(Single)
Stack trace: 
   at Barotrauma.Networking.RespawnManager.UpdateWaiting(Single deltaTime) in E:\Barotrauma\Barotrauma\BarotraumaShared\Source\Networking\RespawnManager.cs:line 207
   at Barotrauma.Networking.RespawnManager.Update(Single deltaTime) in E:\Barotrauma\Barotrauma\BarotraumaShared\Source\Networking\RespawnManager.cs:line 148
   at Barotrauma.Networking.GameServer.Update(Single deltaTime) in E:\Barotrauma\Barotrauma\BarotraumaShared\Source\Networking\GameServer.cs:line 365
   at Barotrauma.GameMain.Update(GameTime gameTime) in E:\Barotrauma\Barotrauma\BarotraumaClient\Source\GameMain.cs:line 421
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at MonoGame.Framework.WinFormsGameWindow.RunLoop()
   at MonoGame.Framework.WinFormsGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Barotrauma.Program.Main() in E:\Barotrauma\Barotrauma\BarotraumaClient\Source\Program.cs:line 41

Last debug messages:
[6/5/2018 5:54:39 PM] setclientcharacter Mike ; robot
[6/5/2018 5:54:37 PM] Character "roboto" not found
[6/5/2018 5:54:37 PM] setclientcharacter Mike ; roboto
[6/5/2018 5:52:04 PM] WRITING CHARACTER DATA: huskweak (ID: 2748)
[6/5/2018 5:52:04 PM] WRITING CHARACTER DATA: huskweak (ID: 2748)
[6/5/2018 5:47:17 PM] setclientcharacter Omni ; robot
[6/5/2018 5:47:05 PM] Invalid parameters. The command should be formatted as "setclientcharacter [client] ; [character]"
[6/5/2018 5:47:05 PM] setclientcharacter Omni : robot
[6/5/2018 5:46:58 PM] Invalid parameters. The command should be formatted as "setclientcharacter [client] ; [character]"
[6/5/2018 5:46:58 PM] setclientcharacter Omni : Robot
[6/5/2018 5:46:45 PM] WRITING CHARACTER DATA: robot (ID: 2754)
[6/5/2018 5:46:45 PM] WRITING CHARACTER DATA: robot (ID: 2754)
[6/5/2018 5:46:45 PM] WRITING CHARACTER DATA: robot (ID: 2754)
[6/5/2018 5:46:44 PM] WRITING CHARACTER DATA: robot (ID: 2754)
[6/5/2018 5:46:44 PM] WRITING CHARACTER DATA: robot (ID: 2754)
[6/5/2018 5:46:44 PM] spawn robot inside
[6/5/2018 5:45:44 PM] WRITING CHARACTER DATA: mantis (ID: 2747)
[6/5/2018 5:45:44 PM] WRITING CHARACTER DATA: mantis (ID: 2747)
[6/5/2018 5:45:44 PM] WRITING CHARACTER DATA: mantis (ID: 2747)
[6/5/2018 5:45:44 PM] WRITING CHARACTER DATA: mantis (ID: 2747)
[6/5/2018 5:45:43 PM] spawn mantis near
[6/5/2018 5:45:16 PM] save (187.122.125.232) couldn't join the server (wrong content package name)
[6/5/2018 5:43:22 PM] WRITING CHARACTER DATA: [BTE] Troll Free (ID: 2708)
[6/5/2018 5:43:21 PM] WRITING CHARACTER DATA: [BTE] Troll Free (ID: 2708)
[6/5/2018 5:43:21 PM] WRITING CHARACTER DATA: Mike Fisher (ID: 2691)
[6/5/2018 5:43:21 PM] WRITING CHARACTER DATA: Sir_Prize (ID: 2672)
[6/5/2018 5:43:21 PM] WRITING CHARACTER DATA: Mike Fisher (ID: 2691)
[6/5/2018 5:43:21 PM] WRITING CHARACTER DATA: Sir_Prize (ID: 2672)
[6/5/2018 5:43:20 PM] WRITING CHARACTER DATA: [BTE] Troll Free (ID: 2708)
[6/5/2018 5:43:20 PM] WRITING CHARACTER DATA: Mike Fisher (ID: 2691)
[6/5/2018 5:43:20 PM] WRITING CHARACTER DATA: Sir_Prize (ID: 2672)
[6/5/2018 5:43:20 PM] WRITING CHARACTER DATA: Mike Fisher (ID: 2691)
[6/5/2018 5:43:20 PM] WRITING CHARACTER DATA: Sir_Prize (ID: 2672)
[6/5/2018 5:41:49 PM] Enter "help" for a list of available console commands

**Comment by CommanderMark** [comment]
It looks like you had this crash while playing with the BTE mod installed. To be sure, can you check to see if this crash still occurs when running the vanilla version of the game?
