### ISSUE TITLE
Server crash on startup

### ISSUE THREAD

**Issue by deelight2k** [Regalis11/Barotrauma#4421]
Hi, i am facing a crash on startup:

```
Barotrauma Dedicated Server 0.10.6.2 (ReleaseLinux, branch release, revision d0702df35e)
Loading game settings
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at AssemblyInfo.CleanupStackTrace(String stackTrace) in /home/joonas/Barotrauma/Barotrauma/BarotraumaShared/SharedSource/Utils/AssemblyInfo.cs:line 46
   at Barotrauma.DebugConsole.ThrowError(String error, Exception e, Boolean createMessageBox, Boolean appendStackTrace) in /home/joonas/Barotrauma/Barotrauma/BarotraumaShared/SharedSource/DebugConsole.cs:line 1905
   at Barotrauma.GameSettings.SaveNewPlayerConfig() in /home/joonas/Barotrauma/Barotrauma/BarotraumaShared/SharedSource/GameSettings.cs:line 1330
   at Barotrauma.GameSettings.LoadPlayerConfig() in /home/joonas/Barotrauma/Barotrauma/BarotraumaShared/SharedSource/GameSettings.cs:line 1053
   at Barotrauma.GameSettings..ctor() in /home/joonas/Barotrauma/Barotrauma/BarotraumaShared/SharedSource/GameSettings.cs:line 755
   at Barotrauma.GameMain..ctor(String[] args) in /home/joonas/Barotrauma/Barotrauma/BarotraumaServer/ServerSource/GameMain.cs:line 82
   at Barotrauma.Program.Main(String[] args) in /home/joonas/Barotrauma/Barotrauma/BarotraumaServer/ServerSource/Program.cs:line 48
./server.sh: line 9: 22177 Aborted                 ./DedicatedServer $@
```

Any ideas what causes tha error or how to fix?

Server is running on CentOS7

**Comment by Regalis11** [comment]
Thank you for the report! It seems that the game for some reason fails to save the config file ("config_player.xml") in the game folder. Normally there should be a more descriptive error message about what actually went wrong, but in this case the error handling logic itself was bugged which lead to this generic error message. The latter bug should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/dbbad1da1335676edd34908b80f15ec0801628e1.

It's hard to say for sure what exactly went wrong here, but I'd guess the game doesn't have permissions to write to the file for some reason. This could for example happen if the first time game's first launch was done with elevated privileges and then you tried to launch the server as a normal user. It could be worth a shot to find that "config_player.xml" file inside the game folder and check its file permissions, or perhaps to remove that file altogether so the game can generate a fresh one. Sorry for the inconvenience!
