### ISSUE TITLE
(40964) crash to desktop if assigned voice capture device missing

### ISSUE THREAD

**Issue by monobi** [Regalis11/Barotrauma#4461]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Crash to desktop when searching for assigned voice capture device that is no longer connected, and no alternative options available.

**Steps To Reproduce**
1. Disable all voice capture devices
2. Connect and enable a USB headset
3. Assign headset as voice capture
4. Save settings
5. Close Barotrauma
6. Disconnect USB headset
7. Open Barotrauma
8. Join or host a server, or navigate to voice chat settings

CTD stops when device reconnected

**Version**
Game version 0.11.0.9
Selected screen: Barotrauma.MainMenuScreen
SteamManager initialized
Operating system: Microsoft Windows NT 10.0.19041.0 64 bit

**Additional information**

Did not experience CTD on versions prior to 11.0.9 with same issue.

Exception: Failed to open capture device: 40964 (AL) (System.Exception)
Target site: Void .ctor(System.String)
Stack trace: 
   at Barotrauma.Networking.VoipCapture..ctor(String deviceName) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\Voip\VoipCapture.cs:line 130
   at Barotrauma.Networking.VoipCapture.Create(String deviceName, Nullable`1 storedBufferID) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\Voip\VoipCapture.cs:line 66
   at Barotrauma.GameSettings.SelectTab(Tab tab) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameSettings.cs:line 1506
   at Barotrauma.GameSettings.<>c__DisplayClass21_0.<CreateSettingsFrame>b__18(GUIButton bt, Object userdata) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameSettings.cs:line 501
   at Barotrauma.GUIButton.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIButton.cs:line 262
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Barotrauma.GUI.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1214
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 951
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59

**Comment by KimmoKari** [comment]
Can you @Rokvach try to repro this ?

**Comment by Rokvach** [comment]
I didn't get a crash, but I did get a warning, looks like the game doesn't check for the capture device update if you don't enter the settings first but rather go directly to host a server.
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/23065f5b-e15a-40db-be57-1dde10770a88)

Tested on my microphone as I don't own a headset. 

Repro steps:
1. Make sure mic/headset is connected
2. Start the game and make sure mic is detected in the voice chat settings.
3. Close the game
4. Unplug mic/headset
5. Start the game and host a server
6. Should receive a warning when you enter lobby

**Comment by instrumentallyill** [comment]
@Regalis11 I am still having this error, its been months, im using an ASUS G14 2023 and the built in microphone and getting the same error.

**Comment by chewycheese** [comment]
> * [x]  I have searched the issue tracker to check if the issue has already been reported.
> 
> **Description** Crash to desktop when searching for assigned voice capture device that is no longer connected, and no alternative options available.
> 
> **Steps To Reproduce**
> 
> 1. Disable all voice capture devices
> 2. Connect and enable a USB headset
> 3. Assign headset as voice capture
> 4. Save settings
> 5. Close Barotrauma
> 6. Disconnect USB headset
> 7. Open Barotrauma
> 8. Join or host a server, or navigate to voice chat settings
> 
> CTD stops when device reconnected
> 
> **Version** Game version 0.11.0.9 Selected screen: Barotrauma.MainMenuScreen SteamManager initialized Operating system: Microsoft Windows NT 10.0.19041.0 64 bit
> 
> **Additional information**
> 
> Did not experience CTD on versions prior to 11.0.9 with same issue.
> 
> Exception: Failed to open capture device: 40964 (AL) (System.Exception) Target site: Void .ctor(System.String) Stack trace: at Barotrauma.Networking.VoipCapture..ctor(String deviceName) in \Barotrauma\BarotraumaClient\ClientSource\Networking\Voip\VoipCapture.cs:line 130 at Barotrauma.Networking.VoipCapture.Create(String deviceName, Nullable`1 storedBufferID) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\Voip\VoipCapture.cs:line 66 at Barotrauma.GameSettings.SelectTab(Tab tab) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameSettings.cs:line 1506 at Barotrauma.GameSettings.<>c__DisplayClass21_0.<CreateSettingsFrame>b__18(GUIButton bt, Object userdata) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameSettings.cs:line 501 at Barotrauma.GUIButton.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIButton.cs:line 262 at System.Collections.Generic.List`1.ForEach(Action`1 action) at Barotrauma.GUI.Update(Single deltaTime) in \Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1214 at Barotrauma.GameMain.Update(GameTime gameTime) in \Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 951 at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in \Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656 at Microsoft.Xna.Framework.Game.Tick() in \Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504 at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in \Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94 at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in \Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398 at Microsoft.Xna.Framework.Game.Run() in \Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368 at Barotrauma.Program.Main(String[] args) in \Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59

This issue has remained even past all of the updates trying to fix the issue. It works on Discord and every other game on Steam. I've tried many Steam posts that have resolved the issue for others. However, nothing is working for me and I this point I am completely out of ideas. PLEASE HELP

**Comment by michael-fakefish** [comment]
Tested in spring-update 466466e3

Could not reproduce the crash, but OpenAL error 40964 still displayed with the original post's steps.
Furhtermore, after enabling/reconnecting an audio device after the error, refreshing the audio devices no longer works, even though one would be available - every time the list is refreshed, the following console error is displayed: `Alc.GetStringList failed: AL error Invalid operation`.

The console logs before the list refresh issue happens are as follows:

> Attempting to open ALC device "OpenAL Soft on Headphones (WH-1000XM3)"
> ALC device initialization attempt `#1` failed: device is null (error code Invalid value)
> Switching to default device...
> ALC device initialization attempt `#2` failed: device is null (error code Invalid value)
> ALC device initialization attempt `#3` failed: device is null (error code Invalid value)
> ALC device creation failed too many times!
> WASAPI capture open failed: HRESULT 0x80004005 (1)
> alcCaptureOpenDevice failed: exception thrown (Device init failed: 0x80004005)
> Alc.CaptureOpenDevice attempt 1 failed: error code 40964
> WASAPI capture open failed: HRESULT 0x80004005 (1)
> alcCaptureOpenDevice failed: exception thrown (Device init failed: 0x80004005)
> Alc.CaptureOpenDevice attempt 2 failed: error code 40964
> WASAPI capture proxy open failed: HRESULT 0x80070490 (1)
> alcCaptureOpenDevice failed: exception thrown (Device init failed: 0x80070490)

Moving back to "bugfixes".
