### ISSUE TITLE
Crash when dragging an item out of a cabinet in the sub editor (GUITextBox.CalculateSelection)

### ISSUE THREAD

**Issue by Veritius** [Regalis11/Barotrauma#4576]
**This happened as I dragged an item out of a cabinet in the sub editor**

Game version 0.11.0.10 (ReleaseWindows, branch release, revision dc7157029e)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla 0.9
Level seed: no level loaded
Loaded submarine: Delta Seven (D1CD79FDF49D4AA8BA200EF2C7E7D100)
Selected screen: Barotrauma.SubEditorScreen
SteamManager initialized
Client (Round hadn't been started)

System info:
    Operating system: Microsoft Windows NT 10.0.18362.0 64 bit
    GPU name: NVIDIA GeForce GTX 1050
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Index and length must refer to a location within the string. (Parameter 'length') (System.ArgumentOutOfRangeException)
Target site: System.String Substring(Int32, Int32)
Stack trace: 
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Barotrauma.GUITextBox.CalculateSelection() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBox.cs:line 870
   at Barotrauma.GUITextBox.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBox.cs:line 498
   at System.Collections.Generic.List\`1.ForEach(Action`1 action)
   at Barotrauma.GUI.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1214
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 951
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59

**Comment by Regalis11** [comment]
I'm afraid I couldn't find a way to reproduce this. Are you able to get it to happen consistently or was it a one-time occurrence? Based on the crash report it seems something went wrong when trying to determine the highlighted area in a text box, so I would guess this requires some specific text box to be highlighted in some specific way when dragging/deselecting/deleting something in the editor.

**Comment by Veritius** [comment]
I did have the Vertical Hatches mod enabled, and the bug never happened again when uninstalled.

**Comment by Veritius** [comment]
I could get it to happen consistently, but I don't remember the conditions.

**Comment by KimmoKari** [comment]
Can you @Rokvach try to repro this ?

**Comment by Rokvach** [comment]
I wasn't able to reproduce this, but there's been some changes and fixes to this in Unstable.

**Comment by Rokvach** [comment]
Closing as I think this is already fixed
