### ISSUE TITLE
Frequent crash

### ISSUE THREAD

**Issue by ZackRobinson** [Regalis11/Barotrauma#4591]
I get the same error when loading into a game. Hosting or joining. Doesn't go away until I reinstall. 

System info:
    Operating system: Microsoft Windows NT 10.0.18363.0 64 bit
    GPU name: NVIDIA GeForce GTX 1080
    Display mode: {Width:3840 Height:2160 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void UpdateWaterAmbience(Single, Single)
Stack trace: 
   at Barotrauma.SoundPlayer.UpdateWaterAmbience(Single ambienceVolume, Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Sounds\SoundPlayer.cs:line 485
   at Barotrauma.SoundPlayer.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Sounds\SoundPlayer.cs:line 418
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 748
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

**Comment by itchyOwl** [comment]
I guess the reference to "sound" could be null here: ![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/8e137577-6782-4242-a253-580e24aee691) Could it be that some of the water ambience audio files was missing for some reason?

The crash should be fixed in Regalis11/Barotrauma-development@836375b.

**Comment by Rokvach** [comment]
There hasn't been any encounters to this during the Unstable period, seems to be working correctly. Closing.
