### ISSUE TITLE
Crashing game after pressing on spectator player which is control monsters

### ISSUE THREAD

**Issue by d3mever** [Regalis11/Barotrauma#4725]
**Crashreport log:**
Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Barotrauma.GUIComponent CreateClientInfoFrame(Barotrauma.GUIFrame, Barotrauma.Networking.Client, Barotrauma.Sprite)
Stack trace: 
   at Barotrauma.TabMenu.CreateClientInfoFrame(GUIFrame frame, Client client, Sprite permissionIcon) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\TabMenu.cs:line 751
   at Barotrauma.TabMenu.SelectElement(Object userData, GUIComponent crewList) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\TabMenu.cs:line 699
   at Barotrauma.TabMenu.<>c__DisplayClass34_1.<CreateCrewListFrame>b__4(GUIComponent component, Object obj) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\TabMenu.cs:line 335
   at Barotrauma.GUIListBox.Select(Int32 childIndex, Boolean force, Boolean autoScroll, Boolean takeKeyBoardFocus) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIListBox.cs:line 793
   at Barotrauma.GUIListBox.UpdateChildrenRect() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIListBox.cs:line 532
   at Barotrauma.GUIListBox.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIListBox.cs:line 646
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Barotrauma.GUI.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1214
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 951
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2e54a6217284aaaf3ea7ac8215073e574e7046ad

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
