### ISSUE TITLE
[DXGI_ERROR_NOT_CURRENTLY_AVAILABLE/NotCurrentlyAvailable] On each start-up

### ISSUE THREAD

**Issue by BearBrawnson** [Regalis11/Barotrauma#4916]
- [1 ] I have searched the issue tracker to check if the issue has already been reported.

for several months I try to start after every update to see if it's fixed, each time I start since I got win10 (or at least I think that's the issue, might be after one of the larger updates)  I get this error.
I've updated my drivers, my directx is v12, my monitor runs on DVI, set my launch options on steam for the game to -windowed
my OS is up to date, I can't change my default 60hertz refresh rate on my monitor, the rest of the information is on the crash report.

Barotrauma Client crash report (generated on 27.01.2021 13:38:37)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

47BDC83F092CDFE5B755C0308161F31E

Game version 0.11.0.10 (ReleaseWindows, branch release, revision dc7157029e)
Graphics mode: 1920x1080 (Fullscreen)
VSync ON
Language: English
Selected content packages: Vanilla 0.9
Level seed: no level loaded
Loaded submarine: None
Selected screen: None
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19041.0 64 bit
    GPU name: NVIDIA GeForce GTX 1050 Ti
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1,7777778}
    GPU status: Normal

Exception: HRESULT: [0x887A0022], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_NOT_CURRENTLY_AVAILABLE/NotCurrentlyAvailable], Message: A resource is not available at the time of the call, but may become available later.
 (SharpDX.SharpDXException)
Target site: Void CheckError()
Stack trace: 
   at SharpDX.Result.CheckError()
   at SharpDX.DXGI.Output.FindClosestMatchingMode(ModeDescription& modeToMatchRef, ModeDescription& closestMatchRef, IUnknown concernedDeviceRef)
   at SharpDX.DXGI.Output.GetClosestMatchingMode(ComObject device, ModeDescription modeToMatch, ModeDescription& closestMatch)
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.GetModeSwitchedSize(Int32& width, Int32& height) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\GraphicsDevice.DirectX.cs:line 645
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.CorrectBackBufferSize() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\GraphicsDevice.DirectX.cs:line 503
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformReset() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\GraphicsDevice.DirectX.cs:line 480
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.Reset() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\GraphicsDevice.cs:line 616
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.Reset(PresentationParameters presentationParameters) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\GraphicsDevice.cs:line 632
   at Microsoft.Xna.Framework.GraphicsDeviceManager.ApplyChanges() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\GraphicsDeviceManager.cs:line 328
   at Barotrauma.GameMain.SetWindowMode(WindowMode windowMode) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 292
   at Barotrauma.GameMain.ApplyGraphicsSettings() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 275
   at Barotrauma.GameMain.LoadContent() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 341
   at Microsoft.Xna.Framework.Game.Initialize() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 553
   at Barotrauma.GameMain.Initialize() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 320
   at Microsoft.Xna.Framework.Game.DoInitialize() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 685
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 382
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59

Last debug messages:
[27.01.2021 13:38:36] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[27.01.2021 13:38:36] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[27.01.2021 13:38:34] Logged in as HANS BESSLER (SteamID STEAM_1:0:29223478)

**Comment by someone972** [comment]
I've heard this can sometimes be fixed by going to your computer's display settings, setting it to a lower resolution, then setting it back to a higher resolution. Maybe try setting your PC to a lower resolution temporarily and see if the game will start before going back to 1080p. This is a tricky error otherwise, and I'm not sure if there's anything Barotrauma could do differently to avoid it. Maybe someone else knows differently though.

**Comment by BearBrawnson** [comment]
> I've heard this can sometimes be fixed by going to your computer's display settings, setting it to a lower resolution, then setting it back to a higher resolution. Maybe try setting your PC to a lower resolution temporarily and see if the game will start before going back to 1080p. This is a tricky error otherwise, and I'm not sure if there's anything Barotrauma could do differently to avoid it. Maybe someone else knows differently though.

That actually worked... Set my pc's reso to 1600x900, started the game and it didn't crash, Set my game to startup windowed as a precaution. Starts fine at my default resolution now. Thanks.
