### ISSUE TITLE
[0.12.0.0] Crash from null value when exporting event in event editor.

### ISSUE THREAD

**Issue by someone972** [Regalis11/Barotrauma#4919]
- [X] I have searched the issue tracker to check if the issue has already been reported.

Submitting on behalf of Udrakan who found this originally.

**Description**
Upon exporting event project to event XML, the game crashes with the following stacktrace:
```
Exception: Value cannot be null. (Parameter 'value') (System.ArgumentNullException)
Target site: Void .ctor(System.Xml.Linq.XName, System.Object)
Stack trace: 
   at System.Xml.Linq.XAttribute..ctor(XName name, Object value)
   at Barotrauma.EventEditorScreen.ExportChildNodes(EditorNode startNode, XElement parent) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\EventEditor\EventEditorScreen.cs:line 600
   at Barotrauma.EventEditorScreen.ExportChildNodes(EditorNode startNode, XElement parent) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\EventEditor\EventEditorScreen.cs:line 582
   at Barotrauma.EventEditorScreen.ExportChildNodes(EditorNode startNode, XElement parent) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\EventEditor\EventEditorScreen.cs:line 616
   at Barotrauma.EventEditorScreen.ExportChildNodes(EditorNode startNode, XElement parent) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\EventEditor\EventEditorScreen.cs:line 582
   at Barotrauma.EventEditorScreen.ExportChildNodes(EditorNode startNode, XElement parent) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\EventEditor\EventEditorScreen.cs:line 616
   at Barotrauma.EventEditorScreen.ExportChildNodes(EditorNode startNode, XElement parent) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\EventEditor\EventEditorScreen.cs:line 616
   at Barotrauma.EventEditorScreen.ExportChildNodes(EditorNode startNode, XElement parent) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\EventEditor\EventEditorScreen.cs:line 616
   at Barotrauma.EventEditorScreen.ExportChildNodes(EditorNode startNode, XElement parent) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\EventEditor\EventEditorScreen.cs:line 616
   at Barotrauma.EventEditorScreen.ExportChildNodes(EditorNode startNode, XElement parent) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\EventEditor\EventEditorScreen.cs:line 616
   at Barotrauma.EventEditorScreen.ExportXML() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\EventEditor\EventEditorScreen.cs:line 564
   at Barotrauma.EventEditorScreen.ExportEventToFile(GUIButton button, Object o) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\EventEditor\EventEditorScreen.cs:line 158
   at Barotrauma.GUIButton.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIButton.cs:line 262
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Barotrauma.GUI.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1226
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 952
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59
```
This is not reproducible on the previous release, so must be something introduced in 0.12.0.0
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/5884694/crashreport.log)

**Steps To Reproduce**
Load the event project attached. Attempt to export the event, it should crash immediately.

Event project:
[Unnamed.zip](https://github.com/Regalis11/Barotrauma/files/5884698/Unnamed.zip)

**Version**
0.12.0.0 Windows release.

**Additional information**
Udrakan mentioned that these are the only nodes different from an event that works:
![SuspectNodes](https://user-images.githubusercontent.com/1829181/106088556-70b9ce80-60e3-11eb-8454-f99c0dbd2743.png)

**Comment by 3e849f2e5c** [comment]
The issue was this conversation action, it had an option without text
![](https://kosblue.com/e/quswb.png)

Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4df77c47e39496dc63a12240104fa7e513c805d7

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
