### ISSUE TITLE
Outpost crew management screen crash

### ISSUE THREAD

**Issue by Bombermen2** [Regalis11/Barotrauma#4948]
When i play, i got a crash
A few seconds before the crash, some kind of Tyler when he shot at worms, he created a ladder from experience (I mean, he got it very quickly) I think it was something like an overload that caused the game to crash
Here the crashreport:
 Barotrauma Client crash report (generated on 30.01.2021 18:32:18)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

47BDC83F092CDFE5B755C0308161F31E

Game version 0.11.0.10 (ReleaseWindows, branch release, revision dc7157029e)
Graphics mode: 1920x1200 (BorderlessWindowed)
VSync ON
Language: Russian
Selected content packages: Vanilla 0.9
Level seed: Novaya MoskvaPelorus Linea
Loaded submarine: Typhon (C7BC4FEFFC56C772A0A65064749C8CC1)
Selected screen: Barotrauma.GameScreen
SteamManager initialized
Client (Round had started)

System info:
    Operating system: Microsoft Windows NT 10.0.18363.0 64 bit
    GPU name: NVIDIA GeForce GTX 1060 3GB
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1,7777778}
    GPU status: Normal

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void CreateCharacterFrame(Barotrauma.CharacterInfo, Barotrauma.GUIListBox)
Stack trace: 
   at Barotrauma.CrewManagement.CreateCharacterFrame(CharacterInfo characterInfo, GUIListBox listBox) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\CrewManagement.cs:line 373
   at Barotrauma.CrewManagement.UpdateCrew() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\CrewManagement.cs:line 293
   at Barotrauma.CrewManagement.UpdateLocationView(Location location, Boolean removePending, Location prevLocation) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\CrewManagement.cs:line 245
   at Barotrauma.CrewManagement..ctor(CampaignUI campaignUI, GUIComponent parentComponent) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\CrewManagement.cs:line 45
   at Barotrauma.CampaignUI.CreateUI(GUIComponent container) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\CampaignUI.cs:line 80
   at Barotrauma.CampaignUI..ctor(CampaignMode campaign, GUIComponent container) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\CampaignUI.cs:line 51
   at Barotrauma.MultiPlayerCampaign.InitCampaignUI() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameSession\GameModes\MultiPlayerCampaign.cs:line 169
   at Barotrauma.MultiPlayerCampaign.<InitProjSpecific>b__39_0(GUIButton btn, Object userdata) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameSession\GameModes\MultiPlayerCampaign.cs:line 138
   at Barotrauma.GUIButton.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIButton.cs:line 262
   at Barotrauma.MultiPlayerCampaign.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameSession\GameModes\MultiPlayerCampaign.cs:line 376
   at Barotrauma.GameSession.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameSession.cs:line 545
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 134
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 924
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

**Comment by ekqvist** [comment]
Hi! Thanks for the report! And sorry that you're experiencing issues with the game!

Did you happen to have any mods installed when this happened?

**Comment by ekqvist** [comment]
Not sure what caused this for you. The only way I managed to reproduce the issue was to define a job without defining any skills for it and make characters with that job hireable.

Fixed crash when no skills are defined in Regalis11/Barotrauma-development@5712195.

**Comment by Rokvach** [comment]
No idea how this can happen but at least the fix hasn't caused any other types of issues so closing.
