### ISSUE TITLE
[0.12.0.1] (Unstable) Crash when looking through a pericope with a stackable item loaded

### ISSUE THREAD

**Issue by Xeavas** [Regalis11/Barotrauma#4977]
**Description**
Seems to have trouble rendering stackable items in its periscope UI thus crashing.

**Steps To Reproduce**
-Obtain the tags of coilgun loader
-Paste said tags into an empty cabinet
-Link said cabinet to a coilgun (and have the coilgun properly hooked up to a periscope)
-Place anything stackable in cabinet (bandages, revolver rounds etc)
-Use periscope and observe

**Version :** [0.12.0.1] Unstable

**Additional information**
```
Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void DrawSlot(Microsoft.Xna.Framework.Graphics.SpriteBatch, Barotrauma.Inventory, Barotrauma.VisualSlot, Barotrauma.Item, Int32, Boolean, Barotrauma.InvSlotType)
Stack trace: 
   at Barotrauma.Inventory.DrawSlot(SpriteBatch spriteBatch, Inventory inventory, VisualSlot slot, Item item, Int32 slotIndex, Boolean drawItem, InvSlotType type) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Inventory.cs:line 0
   at Barotrauma.Items.Components.Turret.DrawHUD(SpriteBatch spriteBatch, Character character) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Components\Turret.cs:line 541
   at Barotrauma.Items.Components.Controller.DrawHUD(SpriteBatch spriteBatch, Character character) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Components\Machines\Controller.cs:line 15
   at Barotrauma.Item.DrawHUD(SpriteBatch spriteBatch, Camera cam, Character character) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Item.cs:line 1047
   at Barotrauma.CharacterHUD.Draw(SpriteBatch spriteBatch, Character character, Camera cam) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Characters\CharacterHUD.cs:line 342
   at Barotrauma.GameScreen.Draw(Double deltaTime, GraphicsDevice graphics, SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\GameScreen.cs:line 127
   at Barotrauma.GameMain.Draw(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 1004
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 669
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 508
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5a097469a23bc70244844d57937398a6d515ea99

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
