### ISSUE TITLE
Powercontainers crash

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#5151]
Couldn't find this issue anywhere else but it seems that powercontainers have a tendency to crash for reasons unknown.
```xml
Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void UpdateHUD(Barotrauma.Character, Single, Barotrauma.Camera)
Stack trace: 
   at Barotrauma.Items.Components.PowerContainer.UpdateHUD(Character character, Single deltaTime, Camera cam) i
n <DEV>/Barotrauma/BarotraumaClient/ClientSource/Items/Components/Power/PowerContainer.cs:line 102
   at Barotrauma.Item.UpdateHUD(Camera cam, Character character, Single deltaTime) in <DEV>/Barotrauma/Barotrau
maClient/ClientSource/Items/Item.cs:line 1004
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>/Barotrauma/Barotra
umaShared/SharedSource/Screens/GameScreen.cs:line 149
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/GameMain.cs:line 925
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/SDL/SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Program.cs:line 58
```
Looking into this. Happens when I select a UI for an itemcontainer in an item that also has a powercontainer, but only after i clone something. I will try to release something in a reproducable state. Making this report ahead of time.

**Comment by Regalis11** [comment]
Added a null check to prevent this from crashing the game (https://github.com/Regalis11/Barotrauma-development/commit/b0d645942c31413633fea5ccf179bd709188754f). I couldn't find a way to reproduce it though, does it happen with vanilla items or only with custom ones? Something that could explain this is an item that has a PowerContainer component with no GUIFrame defined.
