### ISSUE TITLE
Barotrauma Modded crash on docking

### ISSUE THREAD

**Issue by Speaker15071** [Regalis11/Barotrauma#5168]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Game crashed in MP session while attempted to finish round via docking.

**Version**
Current stable version, but heavily modded (one mod, but overriding almost everything).

**Additional information**
![изображение](https://user-images.githubusercontent.com/5286113/109680671-8c127080-7b9e-11eb-9ad6-6a40c51dd5e3.png)
![изображение](https://user-images.githubusercontent.com/5286113/109680724-97fe3280-7b9e-11eb-9e5e-01e928eb7def.png)
networkerror_data.log contains next:
```

Object reference not set to an instance of an object.
Message length: 3904 (488 bytes)
Read position: 1617
Header: SYNC_IDS
Error occurred on the very first header!
Previous object was 0 bits long (0 bytes)
 
   at Barotrauma.CrewManagement.CreateCharacterFrame(CharacterInfo characterInfo, GUIListBox listBox) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\CrewManagement.cs:line 373
   at Barotrauma.CrewManagement.UpdateCrew() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\CrewManagement.cs:line 293
   at Barotrauma.MultiPlayerCampaign.ClientRead(IReadMessage msg) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameSession\GameModes\MultiPlayerCampaign.cs:line 674
   at Barotrauma.Networking.GameClient.ReadIngameUpdate(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 2157
 
Last console messages:
[02.03.2021 23:18:27] Server command: teleport
[02.03.2021 23:18:27] teleport
[02.03.2021 23:17:14] Гл.Кор.Старшина Луна
[02.03.2021 23:17:14] Ст. Лейтенант Борис Бритва
[02.03.2021 23:17:14] Гл.Старшина Шерр
[02.03.2021 23:17:14] Старшина 1-ст Аболог
[02.03.2021 23:17:14] Матрос Фредерик МакРоберт
[02.03.2021 23:17:14] Старшина 2-ст. Дельта
[02.03.2021 23:17:14] Матрос Иван Гаген
[02.03.2021 23:17:14] Старшина 2-ст. Бари
[02.03.2021 23:17:14] Матрос 1-ст Сергей
[02.03.2021 23:17:14] Emerald Smith
[02.03.2021 23:16:16] Line of sight effect disabled
[02.03.2021 23:16:16] los
[02.03.2021 23:16:15] Гл.Кор.Старшина Луна
[02.03.2021 23:16:15] Ст. Лейтенант Борис Бритва
[02.03.2021 23:16:15] Матрос 2-ст Том Круз
[02.03.2021 23:16:15] Гл.Старшина Шерр
[02.03.2021 23:16:15] Старшина 1-ст Аболог
```

**Comment by ekqvist** [comment]
Hi! Sorry for the trouble caused by this! Could you tell me the mod you are using when you are experiencing this crash? There was another report of the same issue (#4948), and I only managed to reproduce it by defining a job without defining skills for it. I'd like to debug this with the mod in question if possible.

**Comment by Speaker15071** [comment]
I use custom modpack, which includes parts of Into the Abyss, 4 EK mods, xanmonsters 1&2 extended monsters, visual variety pack, wrecks, beacons etc. Not published in workshop, if you need it you can find it here: [https://disk.yandex.ru/d/wg8DD0oJQb4dvw](url)

**Comment by Krzeszny** [comment]
[networkerror_data.log](https://github.com/Regalis11/Barotrauma/files/6111243/networkerror_data.log)
The same thing happened again but I didn't have the healing menu open. I was infected and when I died, it disconnected me along with half of the players on the server.

**Comment by ekqvist** [comment]
I think that is a separate issue, at least the stack trace is different.

**Comment by Krzeszny** [comment]
I don't know what a stack trace is but I'm creating a new issue

**Comment by ekqvist** [comment]
Ah, sorry. It's the part in the line that basically tells us where the problem is. So, for the original issue it was:
```
at Barotrauma.CrewManagement.CreateCharacterFrame(CharacterInfo characterInfo, GUIListBox listBox) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\CrewManagement.cs:line 373
at Barotrauma.CrewManagement.UpdateCrew() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\CrewManagement.cs:line 293
at Barotrauma.MultiPlayerCampaign.ClientRead(IReadMessage msg) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameSession\GameModes\MultiPlayerCampaign.cs:line 674
at Barotrauma.Networking.GameClient.ReadIngameUpdate(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 2157
```

and in the log files you attached it was:

```
at Barotrauma.Character.ClientRead(ServerNetObject type, IReadMessage msg, Single sendingTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Characters\CharacterNetworking.cs:line 168
at Barotrauma.Networking.GameClient.ReadIngameUpdate(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 2186
```
