### ISSUE TITLE
[sub-editor] Game crashes when going past Enemy in the spawnpoint spawn type

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#5196]
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/625f694f-ba83-4075-b2ad-5ead8ce06ec2)

```
Barotrauma Client crash report (generated on 8.3.2021 9:49:17)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


20B80232D4234FA56719BE084345C70B


Game version 0.1300.0.1 (ReleaseWindows, branch dev, revision 022e5a2f58)
Graphics mode: 2560x1440 (BorderlessWindowed)
VSync OFF
Language: English
Selected content packages: Vanilla 0.9
Level seed: no level loaded
Loaded submarine: Dugong (29E7E727C236BBBDF51BDA2A64CDD4ED)
Selected screen: Barotrauma.SubEditorScreen
SteamManager initialized


System info:
    Operating system: Microsoft Windows NT 10.0.18363.0 64 bit
    GPU name: NVIDIA GeForce GTX 980 Ti
    Display mode: {Width:2560 Height:1440 Format:Color AspectRatio:1,7777778}
    GPU status: Normal


Exception: The given key 'Human, Enemy' was not present in the dictionary. (System.Collections.Generic.KeyNotFoundException)
Target site: Void ThrowKeyNotFoundException[T](T)
Stack trace: 
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Barotrauma.WayPoint.Draw(SpriteBatch spriteBatch, Vector2 drawPos) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Map\WayPoint.cs:line 59
   at Barotrauma.WayPoint.Draw(SpriteBatch spriteBatch, Boolean editing, Boolean back) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Map\WayPoint.cs:line 36
   at Barotrauma.Submarine.DrawFront(SpriteBatch spriteBatch, Boolean editing, Predicate`1 predicate) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Map\Submarine.cs:line 266
   at Barotrauma.SubEditorScreen.Draw(Double deltaTime, GraphicsDevice graphics, SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\SubEditorScreen.cs:line 4758
   at Barotrauma.GameMain.Draw(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 1031
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 669
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 511
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59


Last debug messages:
[8.3.2021 9:48:01] (Msg) SDR RelayNetworkStatus:  avail=OK  config=OK  anyrelay=OK   (OK)
[8.3.2021 9:48:01] (Msg) Ping location: sto=13+1,sto2=13+1,fra=39+3/32+1,ams=38+3/33+1,waw=46+4/33+1,lhr=45+4/38+1,par=50+5/42+1,vie=47+4/44+1,sof=51+5,iad=127+12/118+1,sgp=231+23/216+16,gru=260+26/261+1
[8.3.2021 9:48:01] (Msg) Ping measurement completed
[8.3.2021 9:47:57] (Verbose) Communications with routing cluster 'syd' established.
[8.3.2021 9:47:57] (Verbose) Communications with routing cluster 'tyo1' established.
[8.3.2021 9:47:57] (Verbose) Communications with routing cluster 'tyo' established.
[8.3.2021 9:47:57] (Verbose) Communications with routing cluster 'sgp' established.
[8.3.2021 9:47:57] (Verbose) Communications with routing cluster 'sea' established.
[8.3.2021 9:47:57] (Verbose) Communications with routing cluster 'lim' established.
[8.3.2021 9:47:57] (Verbose) Communications with routing cluster 'scl' established.
[8.3.2021 9:47:57] (Verbose) Communications with routing cluster 'jnb' established.
[8.3.2021 9:47:57] (Verbose) Communications with routing cluster 'maa' established.
[8.3.2021 9:47:57] (Verbose) Communications with routing cluster 'eze' established.
[8.3.2021 9:47:57] (Verbose) Communications with routing cluster 'hkg' established.
[8.3.2021 9:47:57] (Verbose) Communications with routing cluster 'lax' established.
[8.3.2021 9:47:57] (Verbose) Communications with routing cluster 'gru' established.
[8.3.2021 9:47:57] (Verbose) Communications with routing cluster 'waw' established.
[8.3.2021 9:47:57] (Verbose) Communications with routing cluster 'vie' established.
[8.3.2021 9:47:57] (Verbose) Communications with routing cluster 'sof' established.
[8.3.2021 9:47:57] (Verbose) Communications with routing cluster 'ord' established.
[8.3.2021 9:47:57] (Verbose) Communications with routing cluster 'iad' established.
[8.3.2021 9:47:57] (Verbose) Communications with routing cluster 'sto2' established.
[8.3.2021 9:47:57] (Verbose) Communications with routing cluster 'sto' established.
[8.3.2021 9:47:57] (Verbose) Communications with routing cluster 'eat' established.
[8.3.2021 9:47:57] (Verbose) Communications with routing cluster 'mad' established.
[8.3.2021 9:47:57] (Verbose) Communications with routing cluster 'bom' established.
[8.3.2021 9:47:57] (Verbose) Communications with routing cluster 'dxb' established.
[8.3.2021 9:47:57] (Verbose) Communications with routing cluster 'par' established.
[8.3.2021 9:47:57] (Verbose) Communications with routing cluster 'lhr' established.
[8.3.2021 9:47:57] (Verbose) Communications with routing cluster 'dfw' established.
[8.3.2021 9:47:57] (Verbose) Communications with routing cluster 'atl' established.
[8.3.2021 9:47:57] (Verbose) Communications with routing cluster 'fra' established.
[8.3.2021 9:47:57] (Verbose) Communications with routing cluster 'ams' established.
[8.3.2021 9:47:57] (Msg) SDR RelayNetworkStatus:  avail=Attempting  config=OK  anyrelay=Attempting   (Performing ping measurement)
[8.3.2021 9:47:57] (Msg) Performing ping measurement
[8.3.2021 9:47:57] (Msg) Got SDR network config.  Loaded revision 310 OK
[8.3.2021 9:47:56] (Warning) SDR network config fetch first attempt failed.  HTTP 504.  .  Trying again.
[8.3.2021 9:47:49] Attempting to open ALC device "OpenAL Soft on Kaiuttimet (Realtek High Definition Audio)"
[8.3.2021 9:47:48] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[8.3.2021 9:47:48] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1e7c9fc1a1066b8a162c8bc898789bdb0673de84

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
