### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by Enc4** [Regalis11/Barotrauma#5340]
When im clicking on the botton, to chose the mission and begin the sail, game crushing instantly. There is the log:
Barotrauma Client crash report (generated on 27.03.2021 18:28:01)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

32AA46FAB36BEE9386335D0F440A6AF3

Game version 0.12.0.3 (ReleaseWindows, branch release, revision ea245a2f34)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync OFF
Language: Russian
Selected content packages: Vanilla 0.9, REALLYBIGMAP, The Initiatior, EK Marauder Mk-II, Explorer, Fubuki, Anime Poster Pack, EK Armory, EK Utilities, EK Matriarch Mk-III, ExtendedMonsters [Spawner Edition], Deep Sea Alcohol, Shipwrecks Extended
Level seed: Pelorus Linea
Loaded submarine: SIDON FLEXUS (3C95EC5EE50AB60B729A8BA23041704D)
Selected screen: Barotrauma.GameScreen
SteamManager initialized
Client (Round had started)

System info:
    Operating system: Microsoft Windows NT 10.0.18362.0 64 bit
    GPU name: NVIDIA GeForce GTX 1660 SUPER
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1,7777778}
    GPU status: Normal

Exception: Index was outside the bounds of the array. (System.IndexOutOfRangeException)
Target site: Boolean IsInFogOfWar(Barotrauma.Location)
Stack trace: 
   at Barotrauma.Map.IsInFogOfWar(Location location) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Map\Map\Map.cs:line 222
   at Barotrauma.Map.Draw(SpriteBatch spriteBatch, GUICustomComponent mapContainer) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Map\Map\Map.cs:line 502
   at Barotrauma.CampaignUI.DrawMap(SpriteBatch spriteBatch, GUICustomComponent mapContainer) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\CampaignUI.cs:line 303
   at Barotrauma.GUICustomComponent.Draw(SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUICustomComponent.cs:line 43
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Barotrauma.GUI.Draw(Camera cam, SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 300
   at Barotrauma.GameScreen.Draw(Double deltaTime, GraphicsDevice graphics, SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\GameScreen.cs:line 150
   at Barotrauma.GameMain.Draw(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 1009
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 669
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 511
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59

Last debug messages:
[27.03.2021 18:27:51] Игорь Челядь
[27.03.2021 18:27:50] Василий Громохуй
[27.03.2021 18:27:49] Task count: 0
[27.03.2021 18:27:45] Generating an outpost for the start of the level... (Location: Старательский аванпост Pelorus Linea, level type: Outpost)
[27.03.2021 18:26:40] Lobby created!
[27.03.2021 18:26:30] OpenAL Soft on Микрофон (USB Audio Device) 42
[27.03.2021 18:26:25] OpenAL Soft on Микрофон (USB Audio Device) 42
[27.03.2021 18:26:17] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Mods/Shipwrecks Extended/Wrecks/Drifter_Wrecked.sub, size: 12x7)
[27.03.2021 18:26:17] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Mods/Shipwrecks Extended/Wrecks/Surveyor_Wrecked.sub, size: 12x7)
[27.03.2021 18:26:17] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Mods/Shipwrecks Extended/Wrecks/Vanguard_Wrecked.sub, size: 1x1)
[27.03.2021 18:26:17] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Mods/Shipwrecks Extended/Wrecks/U-1_Wrecked.sub, size: 12x7)
[27.03.2021 18:26:17] (Msg) SDR RelayNetworkStatus:  avail=OK  config=OK  anyrelay=OK   (OK)
[27.03.2021 18:26:17] (Msg) Ping location: sto=20+2,sto2=21+2,ams=39+3,waw=49+4/41+2,fra=42+4/43+2,sof=44+4,lhr=51+5/45+2,par=53+5/50+2,vie=53+5/52+2,iad=123+12/125+2,sgp=209+20/210+20,gru=258+25/253+12
[27.03.2021 18:26:17] (Msg) Ping measurement completed
[27.03.2021 18:26:17] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Mods/Shipwrecks Extended/Wrecks/Scrapper_Wrecked.sub, size: 12x7)
[27.03.2021 18:26:17] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Mods/Shipwrecks Extended/Wrecks/Nerka_Wrecked1.sub, size: 1x1)
[27.03.2021 18:26:17] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Mods/Shipwrecks Extended/Wrecks/Likho_Wrecked.sub, size: 1x1)
[27.03.2021 18:26:16] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Mods/Shipwrecks Extended/Wrecks/Hunnybee_Wrecked.sub, size: 12x7)
[27.03.2021 18:26:16] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Mods/Shipwrecks Extended/Wrecks/FlakeOnTheCurrent_Wrecked.sub, size: 12x7)
[27.03.2021 18:26:16] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Mods/Shipwrecks Extended/Wrecks/Finwal_Wrecked.sub, size: 12x7)
[27.03.2021 18:26:16] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Mods/Shipwrecks Extended/Wrecks/Egg_Wrecked.sub, size: 12x7)
[27.03.2021 18:26:16] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Mods/Shipwrecks Extended/Wrecks/B-71L_Wrecked3.sub, size: 1x1)
[27.03.2021 18:26:16] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Mods/Shipwrecks Extended/Wrecks/CargoSection_Wrecked.sub, size: 12x7)
[27.03.2021 18:26:16] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Mods/Shipwrecks Extended/Wrecks/Carina_Wrecked1.sub, size: 1x1)
[27.03.2021 18:26:16] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Mods/Shipwrecks Extended/Wrecks/Carina_Wrecked2.sub, size: 1x1)
[27.03.2021 18:26:16] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Mods/Shipwrecks Extended/Wrecks/B-71L_Wrecked2.sub, size: 1x1)
[27.03.2021 18:26:16] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Mods/Shipwrecks Extended/Wrecks/Abalone_Wrecked.sub, size: 12x7)
[27.03.2021 18:26:16] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Mods/[ENV] Beacons Extended/BeaconStations/BeaconSING5.sub, size: 1x1)
[27.03.2021 18:26:16] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Mods/[ENV] Beacons Extended/BeaconStations/BeaconSING4.sub, size: 1x1)
[27.03.2021 18:26:16] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Mods/[ENV] Beacons Extended/BeaconStations/BeaconSING3.sub, size: 1x1)
[27.03.2021 18:26:16] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Mods/[ENV] Beacons Extended/BeaconStations/BeaconSING2.sub, size: 1x1)
[27.03.2021 18:26:16] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Mods/[ENV] Beacons Extended/BeaconStations/BeaconSING1B.sub, size: 1x1)
[27.03.2021 18:26:16] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Mods/[ENV] Beacons Extended/BeaconStations/BeaconSING1.sub, size: 1x1)
[27.03.2021 18:26:16] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Mods/[ENV] Beacons Extended/BeaconStations/BeaconMOR1.sub, size: 1x1)
[27.03.2021 18:26:16] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Mods/[ENV] Beacons Extended/BeaconStations/BeaconRD3.sub, size: 1x1)
[27.03.2021 18:26:16] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Mods/[ENV] Beacons Extended/BeaconStations/BeaconRD2.sub, size: 1x1)
[27.03.2021 18:26:16] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Mods/[ENV] Beacons Extended/BeaconStations/BeaconRD1.sub, size: 1x1)
[27.03.2021 18:26:16] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Mods/[ENV] Beacons Extended/BeaconStations/BeaconRAV1.sub, size: 1x1)
[27.03.2021 18:26:13] (Verbose) Communications with routing cluster 'syd' established.
[27.03.2021 18:26:13] (Verbose) Communications with routing cluster 'tyo' established.
[27.03.2021 18:26:13] (Verbose) Communications with routing cluster 'tyo1' established.
[27.03.2021 18:26:13] (Verbose) Communications with routing cluster 'sgp' established.
[27.03.2021 18:26:13] (Verbose) Communications with routing cluster 'sea' established.
[27.03.2021 18:26:13] (Verbose) Communications with routing cluster 'scl' established.
[27.03.2021 18:26:13] (Verbose) Communications with routing cluster 'lim' established.
[27.03.2021 18:26:13] (Verbose) Communications with routing cluster 'jnb' established.
[27.03.2021 18:26:12] (Verbose) Communications with routing cluster 'maa' established.
[27.03.2021 18:26:12] (Verbose) Communications with routing cluster 'lax' established.
[27.03.2021 18:26:12] (Verbose) Communications with routing cluster 'eze' established.
[27.03.2021 18:26:12] (Verbose) Communications with routing cluster 'gru' established.
[27.03.2021 18:26:12] (Verbose) Communications with routing cluster 'vie' established.
[27.03.2021 18:26:12] (Verbose) Communications with routing cluster 'waw' established.
[27.03.2021 18:26:12] (Verbose) Communications with routing cluster 'sof' established.
[27.03.2021 18:26:12] (Verbose) Communications with routing cluster 'ord' established.
[27.03.2021 18:26:12] (Verbose) Communications with routing cluster 'hkg' established.
[27.03.2021 18:26:12] (Verbose) Communications with routing cluster 'iad' established.
[27.03.2021 18:26:12] (Verbose) Communications with routing cluster 'sto2' established.
[27.03.2021 18:26:12] (Verbose) Communications with routing cluster 'sto' established.
[27.03.2021 18:26:12] (Verbose) Communications with routing cluster 'eat' established.
[27.03.2021 18:26:12] (Msg) Relay dxb#28 (185.25.183.162:27042) is going offline in 158 seconds
[27.03.2021 18:26:12] (Verbose) Communications with routing cluster 'dxb' established.
[27.03.2021 18:26:12] (Msg) Relay mad#83 (155.133.246.66:27021) is going offline in 454 seconds
[27.03.2021 18:26:12] (Verbose) Communications with routing cluster 'mad' established.
[27.03.2021 18:26:12] (Verbose) Communications with routing cluster 'bom' established.
[27.03.2021 18:26:12] (Verbose) Communications with routing cluster 'par' established.
[27.03.2021 18:26:12] (Verbose) Communications with routing cluster 'lhr' established.
[27.03.2021 18:26:12] (Verbose) Communications with routing cluster 'dfw' established.
[27.03.2021 18:26:12] (Verbose) Communications with routing cluster 'atl' established.
[27.03.2021 18:26:12] (Verbose) Communications with routing cluster 'fra' established.
[27.03.2021 18:26:12] (Verbose) Communications with routing cluster 'ams' established.
[27.03.2021 18:26:12] (Msg) SDR RelayNetworkStatus:  avail=Attempting  config=OK  anyrelay=Attempting   (Performing ping measurement)
[27.03.2021 18:26:12] (Msg) Performing ping measurement
[27.03.2021 18:26:12] (Msg) Got SDR network config.  Loaded revision 315 OK
[27.03.2021 18:26:12] Overriding the map generation parameters with 'Mods/REALLYBIGMAP/Map/RBM_MapGen.xml'
[27.03.2021 18:26:12] (Warning) SDR network config fetch first attempt failed.  HTTP 504.  .  Trying again.
[27.03.2021 18:26:07] Attempting to open ALC device "OpenAL Soft on Наушники (2- High Definition Audio Device)"
[27.03.2021 18:26:07] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[27.03.2021 18:26:06] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[27.03.2021 18:26:06] Logged in as ♂3nc0d3r♂ 

I tried to disable mods, start new campaing, but the problem is not solved. Best regards, Enc4

**Comment by Regalis11** [comment]
Based on the crash log, this seems to happen because the map is larger than what's currently defined in the map generation parameters. This could for example happen if you started a campaign save with the "REALLYBIGMAP" mod and then switched off the mod, or if the creator of the mod decreased the size of the map.

In any case, I fixed this by making the game save the size of the map to the campaign save, and use that instead of the size that's currently defined in the map generation parameters. https://github.com/Regalis11/Barotrauma-development/commit/2d1eb350040d5d976bb06af35c53dfb2ce592dd3

**Comment by Enc4** [comment]
> 
> 
> Based on the crash log, this seems to happen because the map is larger than what's currently defined in the map generation parameters. This could for example happen if you started a campaign save with the "REALLYBIGMAP" mod and then switched off the mod, or if the creator of the mod decreased the size of the map.
> 
> In any case, I fixed this by making the game save the size of the map to the campaign save, and use that instead of the size that's currently defined in the map generation parameters. [Regalis11/Barotrauma-development@2d1eb35](https://github.com/Regalis11/Barotrauma-development/commit/2d1eb350040d5d976bb06af35c53dfb2ce592dd3)

Thanks a lot for explanation. Can you send me edited file or explain me how to edit a save? I tried by myself, but game dont see the edited saves

**Comment by Enc4** [comment]
[saves.zip](https://github.com/Regalis11/Barotrauma/files/6217575/saves.zip)
there is files. In modification its 8000*8000, in save - 40000*40000

**Comment by Rokvach** [comment]
Tested, I wasn't able to crash the game with the REALLYBIGMAP mod, tested with the mod enabled and then after disabling it on the same save. This seems to be working correctly. Closing.

**Comment by Regalis11** [comment]
I'm afraid this is not possible to fix just by modifying the save (unless you manually modify the positions of all the >8000 locations on the map), so if you can't load the map by re-enabling REALLYBIGMAP, unfortunately you need to wait for the fix to be released.
