### ISSUE TITLE
[Unstable 0.1300.0.4] - Crash when using togglecampaignteleport

### ISSUE THREAD

**Issue by Xeavas** [Regalis11/Barotrauma#5390]
**Description**
Using `debugai` then `togglecampaignteleport` and doubleclicking on a location crashes the game

EDIT : seems like just using `togglecampaignteleport` also crashes the game, ~~I think its actually clicking on some location not adjacent to where you are?~~

**Version**
V0.1300.0.4

**Additional information**
```
Exception: Delegate to an instance method cannot have null 'this'. (System.ArgumentException)
Target site: Void ThrowNullThisInDelegateToInstance()
Stack trace: 
   at System.MulticastDelegate.ThrowNullThisInDelegateToInstance()
   at System.MulticastDelegate.CtorClosed(Object target, IntPtr methodPtr)
   at Barotrauma.ChatBox.AddMessage(ChatMessage message) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\ChatBox.cs:line 393
   at Barotrauma.CrewManager.AddSinglePlayerChatMessage(String senderName, String text, ChatMessageType messageType, Character sender) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameSession\CrewManager.cs:line 575
   at Barotrauma.Map.ChangeLocationTypeProjSpecific(Location location, String prevName, LocationTypeChange change) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Map\Map\Map.cs:line 241
   at Barotrauma.Map.ChangeLocationType(Location location, LocationTypeChange change) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Map\Map.cs:line 976
   at Barotrauma.Map.ProgressLocationTypeChanges(Location location) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Map\Map.cs:line 904
   at Barotrauma.Map.ProgressWorld() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Map\Map.cs:line 841
   at Barotrauma.Map.Update(Single deltaTime, GUICustomComponent mapContainer) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Map\Map\Map.cs:line 433
   at Barotrauma.CampaignUI.UpdateMap(Single deltaTime, GUICustomComponent mapContainer) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\CampaignUI.cs:line 313
   at Barotrauma.GUICustomComponent.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUICustomComponent.cs:line 47
   at Barotrauma.GUIComponent.UpdateAuto(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIComponent.cs:line 451
   at Barotrauma.GUI.<>c__DisplayClass143_0.<Update>b__0(GUIComponent c) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1207
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Barotrauma.GUI.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1207
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 974
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/bd952549f4a352c73f4a595ab451dace2809d021

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
