### ISSUE TITLE
[1300.0.7]collection - Todays console errors from MP

### ISSUE THREAD

**Issue by CurePindal** [Regalis11/Barotrauma#5474]
- [ x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
copy&paste from the latest console errors with Udrakens Big Iron campaign (vanilla, unstable)

`A locked connection was selected - this should not be possible.
   at System.Environment.get_StackTrace()
   at Barotrauma.Map.SelectLocation(Location location) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Map\Map.cs:line 754
   at Barotrauma.Map.LoadState(XElement element, Boolean showNotifications) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Map\Map.cs:line 1084
   at Barotrauma.MultiPlayerCampaign.Load(XElement element) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameModes\MultiPlayerCampaign.cs:line 146
   at Barotrauma.MultiPlayerCampaign.LoadState(String filePath) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameSession\GameModes\MultiPlayerCampaign.cs:line 853
   at Barotrauma.Networking.GameClient.OnFileReceived(FileTransferIn transfer) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 2622
   at Barotrauma.Networking.FileReceiver.ReadMessage(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\FileTransfer\FileReceiver.cs:line 379
   at Barotrauma.Networking.GameClient.ReadDataMessage(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 949
   at Barotrauma.Networking.SteamP2PClientPeer.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\Primitives\Peers\SteamP2PClientPeer.cs:line 243
   at Barotrauma.Networking.GameClient.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 631
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 971
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 651
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58`

` Failed to read event for entity "Explosive Crate"! {Index was outside the bounds of the array.}
   at Lidgren.Network.NetBitWriter.ReadBytes(Byte[] fromBuffer, Int32 numberOfBytes, Int32 readBitOffset, Byte[] destination, Int32 destinationByteOffset) in <DEV>\Libraries\Lidgren.Network\NetBitWriter.cs:line 72
   at Barotrauma.Networking.MsgReader.ReadBytes(Byte[] buf, Int32& bitPos, Int32 numberOfBytes) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\Primitives\Message\Message.cs:line 368
   at Barotrauma.Networking.MsgReader.ReadSingle(Byte[] buf, Int32& bitPos) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\Primitives\Message\Message.cs:line 284
   at Barotrauma.Networking.ReadOnlyMessage.ReadSingle() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\Primitives\Message\Message.cs:line 687
   at Barotrauma.Items.Components.Holdable.ClientRead(ServerNetObject type, IReadMessage msg, Single sendingTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Components\Holdable\Holdable.cs:line 74
   at Barotrauma.Item.ClientRead(ServerNetObject type, IReadMessage msg, Single sendingTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Item.cs:line 1182
   at Barotrauma.Networking.ClientEntityEventManager.ReadEvent(IReadMessage buffer, IServerSerializable entity, Single sendingTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\NetEntityEvent\ClientEntityEventManager.cs:line 287
   at Barotrauma.Networking.ClientEntityEventManager.Read(ServerNetObject type, IReadMessage msg, Single sendingTime, List`1 entities) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\NetEntityEvent\ClientEntityEventManager.cs:line 238
   
   Failed to read event for entity "Metal Crate"! {Index was outside the bounds of the array.}
   at Lidgren.Network.NetBitWriter.ReadBytes(Byte[] fromBuffer, Int32 numberOfBytes, Int32 readBitOffset, Byte[] destination, Int32 destinationByteOffset) in <DEV>\Libraries\Lidgren.Network\NetBitWriter.cs:line 72
   at Barotrauma.Networking.MsgReader.ReadBytes(Byte[] buf, Int32& bitPos, Int32 numberOfBytes) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\Primitives\Message\Message.cs:line 368
   at Barotrauma.Networking.MsgReader.ReadSingle(Byte[] buf, Int32& bitPos) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\Primitives\Message\Message.cs:line 284
   at Barotrauma.Networking.ReadOnlyMessage.ReadSingle() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\Primitives\Message\Message.cs:line 687
   at Barotrauma.Items.Components.Holdable.ClientRead(ServerNetObject type, IReadMessage msg, Single sendingTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Components\Holdable\Holdable.cs:line 74
   at Barotrauma.Item.ClientRead(ServerNetObject type, IReadMessage msg, Single sendingTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Item.cs:line 1182
   at Barotrauma.Networking.ClientEntityEventManager.ReadEvent(IReadMessage buffer, IServerSerializable entity, Single sendingTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\NetEntityEvent\ClientEntityEventManager.cs:line 287
   at Barotrauma.Networking.ClientEntityEventManager.Read(ServerNetObject type, IReadMessage msg, Single sendingTime, List`1 entities) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\NetEntityEvent\ClientEntityEventManager.cs:line 238`

Finally dropped from the server with:
![20210408212318_1](https://user-images.githubusercontent.com/3466193/114085386-9b798d80-98b1-11eb-90e2-f50997a63baa.jpg)

**Comment by CurePindal** [comment]
`Couldn't load xml document "Content/Characters/Swarmcrawler/Swarmcrawler.xml"! {Could not find a part of the path 'E:\Program Files\Steam\steamapps\common\Barotrauma\Content\Characters\Swarmcrawler\Swarmcrawler.xml'.}
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.FinishInitUriString()
   at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
   at System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
   at Barotrauma.XMLExtensions.TryLoadXml(String filePath) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Serialization\XMLExtensions.cs:line 23`

**Comment by Regalis11** [comment]
These appear to be 3 separate issues:
- The connection was still locked client-side when it was selected, which should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/5f16852920f4cac2910d24845a54d0ba4428fdd3
- The "failed to read event for entity 'Metal Crate'" error most likely happened as a result of https://github.com/Regalis11/Barotrauma/issues/5451
- The swarmcrawler issue seems to be the same as this https://github.com/Regalis11/Barotrauma/issues/5064

**Comment by Rokvach** [comment]
Player joining in the middle of a campaign round got a error about a locked connection

```
A locked connection was selected - this should not be possible.
   at System.Environment.get_StackTrace()
   at Barotrauma.Map.SelectLocation(Location location) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Map\Map.cs:line 754
   at Barotrauma.Map.LoadState(XElement element, Boolean showNotifications) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Map\Map.cs:line 1085
   at Barotrauma.Map.Load(CampaignMode campaign, XElement element, CampaignSettings settings) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Map\Map.cs:line 999
   at Barotrauma.MultiPlayerCampaign.Load(XElement element) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameModes\MultiPlayerCampaign.cs:line 139
   at Barotrauma.MultiPlayerCampaign.LoadState(String filePath) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameSession\GameModes\MultiPlayerCampaign.cs:line 853
   at Barotrauma.Networking.GameClient.OnFileReceived(FileTransferIn transfer) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 2622
   at Barotrauma.Networking.FileReceiver.ReadMessage(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\FileTransfer\FileReceiver.cs:line 379
   at Barotrauma.Networking.GameClient.ReadDataMessage(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 949
   at Barotrauma.Networking.SteamP2PClientPeer.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\Primitives\Peers\SteamP2PClientPeer.cs:line 243
   at Barotrauma.Networking.GameClient.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 631
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 971
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 651
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58
A locked connection was selected - this should not be possible.
   at System.Environment.get_StackTrace()
   at Barotrauma.Map.SelectLocation(Int32 index) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Map\Map.cs:line 735
   at Barotrauma.MultiPlayerCampaign.ClientRead(IReadMessage msg) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameSession\GameModes\MultiPlayerCampaign.cs:line 696
   at Barotrauma.Networking.GameClient.ReadLobbyUpdate(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 2176
   at Barotrauma.Networking.GameClient.ReadDataMessage(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 758
   at Barotrauma.Networking.SteamP2PClientPeer.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\Primitives\Peers\SteamP2PClientPeer.cs:line 243
   at Barotrauma.Networking.GameClient.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 631
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 971
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 651
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58
```

**Comment by mrjpjr** [comment]
Yep, I just joined and got the error as well
![today's error](https://user-images.githubusercontent.com/58775950/114224496-22c11280-993f-11eb-949a-5e94e337ff4a.jpg)

**Comment by Rokvach** [comment]
Moved back to wrapping up

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8e9e7ebfac16587667511c156492cf6d57bcff16

**Comment by Rokvach** [comment]
Didn't encounter any issues, seems to be working correctly. Closing
