### ISSUE TITLE
"Safe handle has been closed" crash when pressing "Main Menu" from Esc menu during a multiplayer campaign round

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#5489]
No known steps to reproduce, tried to use the main menu button myself and didn't crash

```
Barotrauma Client crash report (generated on 09/04/2021 13:31:07)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


76E0673BB9692BD623C6D265C9C7CCB8


Game version 0.1300.0.8 (UnstableWindows, branch release, revision 6399ca3b0b)
Graphics mode: 1366x768 (Fullscreen)
VSync ON
Language: LePiromano
Selected content packages: Vanilla 0.9, LePiromano
Level seed: Asterius LineaSet
Loaded submarine: Humpback (42720E5386BBC793C919A27AE65447B9)
Selected screen: Barotrauma.GameScreen
SteamManager initialized
Client (Round had started)


System info:
    Operating system: Microsoft Windows NT 10.0.19041.0 64 bit
    GPU name: Intel(R) HD Graphics 520
    Display mode: {Width:1366 Height:768 Format:Color AspectRatio:1,7786459}
    GPU status: Normal


Exception: One or more errors occurred. (Safe handle has been closed.
Object name: 'SafeHandle'.) (System.AggregateException)
Target site: Boolean Wait(Int32, System.Threading.CancellationToken)
Stack trace: 
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(TimeSpan timeout)
   at Barotrauma.Networking.ChildServerRelay.ReadIncomingMsgs() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\ChildServerRelay.cs:line 102
   at Barotrauma.Networking.ChildServerRelay.UpdateRead() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\ChildServerRelay.cs:line 143
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadHelper.ThreadStart()


InnerException: Safe handle has been closed.
Object name: 'SafeHandle'.
Target site: Void DangerousAddRef(Boolean ByRef)
Stack trace: 
   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at Interop.Kernel32.ReadFile(SafeHandle handle, Byte* bytes, Int32 numBytesToRead, Int32& numBytesRead, IntPtr mustBeZero)
   at System.IO.Pipes.PipeStream.ReadFileNative(SafePipeHandle handle, Span`1 buffer, NativeOverlapped* overlapped, Int32& errorCode)
   at System.IO.Pipes.PipeStream.ReadCore(Span`1 buffer)
   at System.IO.Pipes.PipeStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.<>c.<BeginReadInternal>b__43_0(Object <p0>)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at System.IO.Stream.EndRead(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
Last debug messages:
[09/04/2021 13:27:32] LePiromano
[09/04/2021 13:27:22] Task count: 0
[09/04/2021 13:26:45] LePiromano
[09/04/2021 13:09:45] LePiromano
[09/04/2021 13:09:34] Task count: 0
[09/04/2021 13:09:12] Generating an outpost for the start of the level... (Location: LePiromano, level type: LocationConnection)
[09/04/2021 13:08:50] LePiromano
[09/04/2021 13:08:49] WARNING: Could not determine reputation change for faction "LePiromano" (faction was not present at the start of the round).
[09/04/2021 13:08:49] WARNING: Could not determine reputation change for faction "LePiromano" (faction was not present at the start of the round).
[09/04/2021 13:08:49] WARNING: Could not determine reputation change for faction "LePiromano" (faction was not present at the start of the round).
[09/04/2021 13:08:49] WARNING: Could not determine reputation change for faction "LePiromano" (faction was not present at the start of the round).
[09/04/2021 13:06:02] OpenAL Soft on Micrófono (Realtek High Definition Audio(SST)) 61
[09/04/2021 13:05:45] OpenAL Soft on Micrófono (Realtek High Definition Audio(SST)) 61
[09/04/2021 13:02:54] LePiromano
[09/04/2021 13:02:46] Task count: 0
[09/04/2021 13:02:39] Generating an outpost for the start of the level... (Location: LePiromano, level type: Outpost)
[09/04/2021 13:00:29] Lobby created!
[09/04/2021 12:59:06] (Msg) SDR RelayNetworkStatus:  avail=OK  config=OK  anyrelay=OK   (OK)
[09/04/2021 12:59:06] (Msg) Ping location: eze=22+2,scl=48+4/42+2,gru=52+5/49+2,lim=75+7/71+2,lax=168+16/173+2,atl=176+17/180+2,dfw=184+18,iad=182+18/193+2,sea=192+19/196+2,ord=184+18/199+2,fra=233+23/232+22,sgp=362+36/357+2
[09/04/2021 12:59:06] (Msg) Ping measurement completed
[09/04/2021 12:59:05] (Verbose) Communications with routing cluster 'sto2' established.
[09/04/2021 12:59:04] (Debug) Destroying relay 'sto2#492 (155.133.252.69:27026)' because initial_ping_timeout
[09/04/2021 12:59:02] (Verbose) Communications with routing cluster 'sgp' established.
[09/04/2021 12:59:02] (Verbose) Communications with routing cluster 'jnb' established.
[09/04/2021 12:59:02] (Verbose) Communications with routing cluster 'syd' established.
[09/04/2021 12:59:02] (Verbose) Communications with routing cluster 'tyo1' established.
[09/04/2021 12:59:02] (Verbose) Communications with routing cluster 'tyo' established.
[09/04/2021 12:59:02] (Verbose) Communications with routing cluster 'maa' established.
[09/04/2021 12:59:02] (Verbose) Communications with routing cluster 'waw' established.
[09/04/2021 12:59:02] (Verbose) Communications with routing cluster 'sof' established.
[09/04/2021 12:59:02] (Verbose) Communications with routing cluster 'vie' established.
[09/04/2021 12:59:02] (Verbose) Communications with routing cluster 'sto' established.
[09/04/2021 12:59:02] (Verbose) Communications with routing cluster 'sea' established.
[09/04/2021 12:59:02] (Verbose) Communications with routing cluster 'mad' established.
[09/04/2021 12:59:02] (Verbose) Communications with routing cluster 'bom' established.
[09/04/2021 12:59:02] (Verbose) Communications with routing cluster 'par' established.
[09/04/2021 12:59:02] (Verbose) Communications with routing cluster 'dxb' established.
[09/04/2021 12:59:02] (Verbose) Communications with routing cluster 'lhr' established.
[09/04/2021 12:59:02] (Verbose) Communications with routing cluster 'hkg' established.
[09/04/2021 12:59:02] (Verbose) Communications with routing cluster 'ord' established.
[09/04/2021 12:59:02] (Verbose) Communications with routing cluster 'iad' established.
[09/04/2021 12:59:02] (Verbose) Communications with routing cluster 'lax' established.
[09/04/2021 12:59:02] (Verbose) Communications with routing cluster 'fra' established.
[09/04/2021 12:59:02] (Verbose) Communications with routing cluster 'ams' established.
[09/04/2021 12:59:02] (Verbose) Communications with routing cluster 'eat' established.
[09/04/2021 12:59:02] (Verbose) Communications with routing cluster 'dfw' established.
[09/04/2021 12:59:02] (Verbose) Communications with routing cluster 'atl' established.
[09/04/2021 12:59:02] (Verbose) Communications with routing cluster 'lim' established.
[09/04/2021 12:59:02] (Verbose) Communications with routing cluster 'scl' established.
[09/04/2021 12:59:01] (Verbose) Communications with routing cluster 'gru' established.
[09/04/2021 12:59:01] (Verbose) Communications with routing cluster 'eze' established.
[09/04/2021 12:59:01] (Msg) SDR RelayNetworkStatus:  avail=Attempting  config=OK  anyrelay=Attempting   (Performing ping measurement)
[09/04/2021 12:59:01] (Msg) Performing ping measurement
[09/04/2021 12:59:01] (Msg) Got SDR network config.  Loaded revision 316 OK
[09/04/2021 12:59:01] (Warning) SDR network config fetch first attempt failed.  HTTP 504.  .  Trying again.
[09/04/2021 12:58:40] Attempting to open ALC device "OpenAL Soft on Altavoces (Realtek High Definition Audio(SST))"
[09/04/2021 12:58:39] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean, LePiromano
[09/04/2021 12:58:38] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
```

**Comment by Regalis11** [comment]
Haven't seen this in a while, possible fixed?

**Comment by Rokvach** [comment]
I haven't seen this in GA either for a while now so seems to be fixed. Closing.
