### ISSUE TITLE
[Unstable] Client tries to load the wrong hunting grounds mission than what the server has selected

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#5490]
We entered a hunting grounds level and couple players were disconnected with errors about a mission equality check failing

First error
```
Generating an outpost for the start of the level... (Location: Chandelle Crevasse Outpost, level type: LocationConnection)
Task count: 0
Error while reading a message from server. {Mission equality check failed. The mission selected at your end doesn't match the one loaded by the server (server: huntinggroundsnoreward2, client: huntinggroundsnoreward1)}
   at Barotrauma.Networking.GameClient.ReadStartGameFinalize(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 1005
   at Barotrauma.Networking.GameClient.ReadDataMessage(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 863
   at Barotrauma.Networking.SteamP2PClientPeer.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\Primitives\Peers\SteamP2PClientPeer.cs:line 243
   at Barotrauma.Networking.GameClient.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 631
There was an error initializing the round. {Object reference not set to an instance of an object.}
   at Barotrauma.Networking.GameClient.StartGame(IReadMessage inc)+MoveNext() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 1623
Error
Coroutine "Barotrauma.Networking.GameClient+<StartGame>d__93" has failed
```

Everytime they try to join the server and spectate they just get the equality check failed error again
```
Generating an outpost for the start of the level... (Location: Chandelle Crevasse Outpost, level type: LocationConnection)
Task count: 0
There was an error initializing the round. {Mission equality check failed. The mission selected at your end doesn't match the one loaded by the server (server: huntinggroundsnoreward2, client: huntinggroundsnoreward1)}
   at Barotrauma.Networking.GameClient.ReadStartGameFinalize(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 1005
   at Barotrauma.Networking.GameClient.StartGame(IReadMessage inc)+MoveNext() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 1637
Error
Coroutine "Barotrauma.Networking.GameClient+<StartGame>d__93" has failed
Coroutine Barotrauma.Networking.GameClient+<EndGame>d__94 threw an exception: Object reference not set to an instance of an object.
   at Barotrauma.SalvageMission.End() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\Missions\SalvageMission.cs:line 250
   at Barotrauma.GameSession.EndRound(String endMessage, List`1 traitorResults, TransitionType transitionType) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameSession.cs:line 619
   at Barotrauma.Networking.GameClient.EndGame(String endMessage, List`1 traitorResults, TransitionType transitionType)+MoveNext() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 1751
   at Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 217
```

Also equality check failed doesn't have a disconnection reason on the servers side, it just shows that the clients disconnected
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/4a7e9c49-c1ac-4476-a10e-70b8c89574c8)

**Comment by Rokvach** [comment]
We had to return to lobby and continue from there because of some issues and when we loaded the round this time the server host got the equality check failed error so the server shut down because of it

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f2e57b585de9bf47a94aec2ec0825c7fa60b3f8f

**Comment by Rokvach** [comment]
Tested, managed to come across a crash related to the hunting grounds but didn't run in to this specific issue. Working correctly, closing.
