### ISSUE TITLE
[Unstable] Game crashed when entering hunting grounds level

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#5510]
Repro steps:
1. Start a multiplayer campaign
2. Use maxupgrades and togglecampaignteleport commands
3. Teleport to a hunting grounds that ends at a formation, or find where there's two hunting grounds next to each other with no outpost in between
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/3cc16ff2-5fe2-4aa1-8274-90a00e8b930d)
4. Use killmonsters to complete the mission and teleportsub end command
5. Teleport to another hunting grounds level
6. The game should crash once it loads in

```
Barotrauma Client crash report (generated on 13.4.2021 22:10:06)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


BC29B2C6D676B21F82E74F948CA42A33


Game version 0.1300.0.9 (ReleaseWindows, branch release, revision f550a36b4e)
Graphics mode: 2560x1440 (BorderlessWindowed)
VSync OFF
Language: English
Selected content packages: Vanilla 0.9, Diving Boot, Leocyte MKIII, Sunfish, Dugong Mk4
Level seed: AnaOnga Linea
Loaded submarine: Typhon2 (37052BA40EA9E01D1062D2E260C31285)
Selected screen: Barotrauma.RoundSummaryScreen
SteamManager initialized
Client (Round hadn't been started)


System info:
    Operating system: Microsoft Windows NT 10.0.18363.0 64 bit
    GPU name: NVIDIA GeForce GTX 980 Ti
    Display mode: {Width:2560 Height:1440 Format:Color AspectRatio:1,7777778}
    GPU status: Normal


Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void AddExtraMissions(Barotrauma.LevelData)
Stack trace: 
   at Barotrauma.CampaignMode.AddExtraMissions(LevelData levelData) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameModes\CampaignMode.cs:line 288
   at Barotrauma.GameSession.InitializeLevel(Level level) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameSession.cs:line 447
   at Barotrauma.GameSession.StartRound(LevelData levelData, Boolean mirrorLevel, SubmarineInfo startOutpost, SubmarineInfo endOutpost) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameSession.cs:line 377
   at Barotrauma.CampaignMode.<>c__DisplayClass26_0.<<SelectSummaryScreen>b__0>d.MoveNext() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameSession\GameModes\CampaignMode.cs:line 265
--- End of stack trace from previous location where exception was thrown ---
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 947
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59


Last debug messages:
[13.4.2021 22:09:46] InfiltratingJack
[13.4.2021 22:09:46] Soup
[13.4.2021 22:09:46] Solbusaur
[13.4.2021 22:09:46] LePiromano
[13.4.2021 22:09:46] Rokvach
[13.4.2021 21:59:45] Rokvach's godmode on
[13.4.2021 21:59:45] Server command: godmode Rokvach
[13.4.2021 21:59:45] godmode Rokvach
[13.4.2021 21:59:43] Rokvach's godmode off
[13.4.2021 21:59:43] Server command: godmode Rokvach
[13.4.2021 21:59:43] godmode Rokvach
[13.4.2021 21:59:13] Server command: spawnitem Poop inventory
[13.4.2021 21:59:13] spawnitem Poop inventory
[13.4.2021 21:57:10] Server command: spawnitem Poop inventory
[13.4.2021 21:57:10] spawnitem Poop inventory
[13.4.2021 21:57:09] Server command: spawnitem Poop inventory
[13.4.2021 21:57:09] spawnitem Poop inventory
[13.4.2021 21:57:09] Server command: spawnitem Poop inventory
[13.4.2021 21:57:09] spawnitem Poop inventory
[13.4.2021 21:57:09] Server command: spawnitem Poop inventory
[13.4.2021 21:57:09] spawnitem Poop inventory
[13.4.2021 21:57:08] Server command: spawnitem Poop inventory
[13.4.2021 21:57:08] spawnitem Poop inventory
[13.4.2021 21:57:07] Rokvach's godmode on
[13.4.2021 21:57:07] Server command: godmode Rokvach
[13.4.2021 21:57:07] godmode Rokvach
[13.4.2021 21:57:04] Rokvach's godmode off
[13.4.2021 21:57:04] Server command: godmode Rokvach
[13.4.2021 21:57:04] godmode Rokvach
[13.4.2021 21:57:04] Rokvach's godmode on
[13.4.2021 21:57:04] Server command: godmode Rokvach
[13.4.2021 21:57:04] godmode Rokvach
[13.4.2021 21:57:04] Rokvach's godmode off
[13.4.2021 21:57:04] Server command: godmode Rokvach
[13.4.2021 21:57:04] godmode Rokvach
[13.4.2021 21:57:04] Rokvach's godmode on
[13.4.2021 21:57:04] Server command: godmode Rokvach
[13.4.2021 21:57:04] godmode Rokvach
[13.4.2021 21:57:04] Rokvach's godmode off
[13.4.2021 21:57:04] Server command: godmode Rokvach
[13.4.2021 21:57:04] godmode Rokvach
[13.4.2021 21:57:03] Rokvach's godmode on
[13.4.2021 21:57:03] Server command: godmode Rokvach
[13.4.2021 21:57:03] godmode Rokvach
[13.4.2021 21:57:03] Rokvach's godmode off
[13.4.2021 21:57:03] Server command: godmode Rokvach
[13.4.2021 21:57:03] godmode Rokvach
[13.4.2021 21:57:03] Rokvach's godmode on
[13.4.2021 21:57:03] Server command: godmode Rokvach
[13.4.2021 21:57:03] godmode Rokvach
[13.4.2021 21:57:03] Rokvach's godmode off
[13.4.2021 21:57:03] Server command: godmode Rokvach
[13.4.2021 21:57:03] godmode Rokvach
[13.4.2021 21:57:02] Rokvach's godmode on
[13.4.2021 21:57:02] Server command: godmode Rokvach
[13.4.2021 21:57:02] godmode Rokvach
[13.4.2021 21:57:02] Server command: spawnitem Poop inventory
[13.4.2021 21:57:02] spawnitem Poop inventory
[13.4.2021 21:57:02] Server command: spawnitem Poop inventory
[13.4.2021 21:57:02] spawnitem Poop inventory
[13.4.2021 21:57:02] Server command: spawnitem Poop inventory
[13.4.2021 21:57:02] spawnitem Poop inventory
[13.4.2021 21:57:01] Server command: spawnitem Poop inventory
[13.4.2021 21:57:01] spawnitem Poop inventory
[13.4.2021 21:57:01] Server command: spawnitem Poop inventory
[13.4.2021 21:57:01] spawnitem Poop inventory
[13.4.2021 21:57:01] Server command: spawnitem Poop inventory
[13.4.2021 21:57:01] spawnitem Poop inventory
[13.4.2021 21:57:01] Server command: spawnitem Poop inventory
[13.4.2021 21:57:01] spawnitem Poop inventory
[13.4.2021 21:57:01] Server command: spawnitem Poop inventory
[13.4.2021 21:57:01] spawnitem Poop inventory
[13.4.2021 21:57:01] Server command: spawnitem Poop inventory
[13.4.2021 21:57:01] spawnitem Poop inventory
[13.4.2021 21:57:00] Server command: spawnitem Poop inventory
[13.4.2021 21:57:00] spawnitem Poop inventory
[13.4.2021 21:57:00] Server command: spawnitem Poop inventory
[13.4.2021 21:57:00] spawnitem Poop inventory
[13.4.2021 21:57:00] Server command: spawnitem Poop inventory
[13.4.2021 21:57:00] spawnitem Poop inventory
[13.4.2021 21:57:00] Server command: spawnitem Poop inventory
[13.4.2021 21:57:00] spawnitem Poop inventory
[13.4.2021 21:56:57] Server command: spawnitem Poop inventory
[13.4.2021 21:56:57] spawnitem Poop inventory
[13.4.2021 21:54:07] InfiltratingJack
[13.4.2021 21:54:07] Soup
[13.4.2021 21:54:07] Solbusaur
[13.4.2021 21:54:07] LePiromano
[13.4.2021 21:54:07] Rokvach
[13.4.2021 21:54:07] InfiltratingJack
[13.4.2021 21:54:07] Soup
[13.4.2021 21:54:07] Solbusaur
[13.4.2021 21:54:07] LePiromano
[13.4.2021 21:54:07] Rokvach
[13.4.2021 21:54:01] InfiltratingJack
[13.4.2021 21:54:01] Soup
[13.4.2021 21:54:01] Rokvach
[13.4.2021 21:54:01] Solbusaur
[13.4.2021 21:54:01] LePiromano
[13.4.2021 21:54:00] InfiltratingJack
[13.4.2021 21:54:00] Rokvach
[13.4.2021 21:54:00] Soup
[13.4.2021 21:54:00] Solbusaur
[13.4.2021 21:54:00] LePiromano
[13.4.2021 21:53:54] InfiltratingJack
[13.4.2021 21:53:54] Soup
[13.4.2021 21:53:54] Solbusaur
[13.4.2021 21:53:54] LePiromano
[13.4.2021 21:53:53] Rokvach
[13.4.2021 21:53:49] Task count: 0
[13.4.2021 21:53:46] Generating an outpost for the start of the level... (Location: Set Mining Facility, level type: LocationConnection)
[13.4.2021 21:53:30] InfiltratingJack
[13.4.2021 21:53:30] Soup
[13.4.2021 21:53:30] Solbusaur
[13.4.2021 21:53:30] LePiromano
[13.4.2021 21:53:30] Rokvach
[13.4.2021 21:51:39] Rokvach's godmode on
[13.4.2021 21:51:39] Server command: godmode Rokvach
[13.4.2021 21:51:39] godmode Rokvach
[13.4.2021 21:51:34] InfiltratingJack
[13.4.2021 21:51:34] Soup
[13.4.2021 21:51:34] Solbusaur
[13.4.2021 21:51:34] LePiromano
[13.4.2021 21:51:34] Rokvach
[13.4.2021 21:51:33] Server command: revive Rokvach
[13.4.2021 21:51:33] revive Rokvach
[13.4.2021 21:48:56] InfiltratingJack
[13.4.2021 21:48:56] Soup
[13.4.2021 21:48:56] Solbusaur
[13.4.2021 21:48:56] LePiromano
[13.4.2021 21:48:56] Rokvach
[13.4.2021 21:48:00] Server command: money 100000000
[13.4.2021 21:48:00] money 100000000
[13.4.2021 21:48:00] Server command: money 100000000
[13.4.2021 21:48:00] money 100000000
[13.4.2021 21:48:00] Server command: money 100000000
[13.4.2021 21:48:00] money 100000000
[13.4.2021 21:48:00] Server command: money 100000000
[13.4.2021 21:48:00] money 100000000
[13.4.2021 21:48:00] Server command: money 100000000
[13.4.2021 21:48:00] money 100000000
[13.4.2021 21:47:59] Server command: money 100000000
[13.4.2021 21:47:59] money 100000000
[13.4.2021 21:47:59] Server command: money 100000000
[13.4.2021 21:47:59] money 100000000
[13.4.2021 21:47:59] Server command: money 100000000
[13.4.2021 21:47:59] money 100000000
[13.4.2021 21:47:59] Server command: money 100000000
[13.4.2021 21:47:59] money 100000000
[13.4.2021 21:47:59] Server command: money 100000000
[13.4.2021 21:47:59] money 100000000
[13.4.2021 21:47:58] Server command: money 100000000
[13.4.2021 21:47:58] money 100000000
[13.4.2021 21:47:58] Server command: money 100000000
[13.4.2021 21:47:58] money 100000000
[13.4.2021 21:47:58] Server command: money 100000000
[13.4.2021 21:47:58] money 100000000
[13.4.2021 21:47:58] Server command: money 100000000
[13.4.2021 21:47:58] money 100000000
[13.4.2021 21:47:58] Server command: money 100000000
[13.4.2021 21:47:58] money 100000000
[13.4.2021 21:47:58] Server command: money 100000000
[13.4.2021 21:47:58] money 100000000
[13.4.2021 21:47:57] Server command: money 100000000
[13.4.2021 21:47:57] money 100000000
[13.4.2021 21:47:57] Server command: money 100000000
[13.4.2021 21:47:57] money 100000000
[13.4.2021 21:47:57] Server command: money 100000000
[13.4.2021 21:47:57] money 100000000
[13.4.2021 21:47:57] Server command: money 100000000
[13.4.2021 21:47:57] money 100000000
[13.4.2021 21:47:57] Server command: money 100000000
[13.4.2021 21:47:57] money 100000000
[13.4.2021 21:47:57] Server command: money 100000000
[13.4.2021 21:47:57] money 100000000
[13.4.2021 21:47:56] Server command: money 100000000
[13.4.2021 21:47:56] money 100000000
[13.4.2021 21:47:56] Soup
[13.4.2021 21:47:56] Solbusaur
[13.4.2021 21:47:56] LePiromano
[13.4.2021 21:47:56] Rokvach
[13.4.2021 21:47:31] Soup
[13.4.2021 21:47:31] Solbusaur
[13.4.2021 21:47:31] LePiromano
[13.4.2021 21:47:31] Rokvach
[13.4.2021 21:47:30] Soup
[13.4.2021 21:47:30] Solbusaur
[13.4.2021 21:47:30] LePiromano
[13.4.2021 21:47:30] Rokvach
[13.4.2021 21:47:29] Soup
[13.4.2021 21:47:29] Solbusaur
[13.4.2021 21:47:29] LePiromano
[13.4.2021 21:47:29] Rokvach
[13.4.2021 21:47:16] Soup
[13.4.2021 21:47:16] Solbusaur
[13.4.2021 21:47:16] LePiromano
[13.4.2021 21:47:16] Rokvach
[13.4.2021 21:47:13] Soup
[13.4.2021 21:47:13] Solbusaur
[13.4.2021 21:47:13] LePiromano
[13.4.2021 21:47:13] Rokvach
[13.4.2021 21:47:09] Soup
[13.4.2021 21:47:09] Solbusaur
[13.4.2021 21:47:09] LePiromano
[13.4.2021 21:47:09] Rokvach
[13.4.2021 21:47:08] Task count: 0
[13.4.2021 21:47:07] Generating an outpost for the start of the level... (Location: Set Mining Facility, level type: Outpost)
[13.4.2021 21:46:51] Soup
[13.4.2021 21:46:51] Solbusaur
[13.4.2021 21:46:51] LePiromano
[13.4.2021 21:46:51] Rokvach
[13.4.2021 21:46:49] Soup
[13.4.2021 21:46:49] Solbusaur
[13.4.2021 21:46:49] LePiromano
[13.4.2021 21:46:49] Rokvach
[13.4.2021 21:46:40] Soup
[13.4.2021 21:46:40] Solbusaur
[13.4.2021 21:46:40] LePiromano
[13.4.2021 21:46:40] Rokvach
[13.4.2021 21:46:25] Soup
[13.4.2021 21:46:25] Solbusaur
[13.4.2021 21:46:25] LePiromano
[13.4.2021 21:46:25] Rokvach
[13.4.2021 21:46:21] Task count: 0
[13.4.2021 21:46:18] Generating an outpost for the start of the level... (Location: Set Mining Facility, level type: LocationConnection)
[13.4.2021 21:46:02] Soup
[13.4.2021 21:46:02] Solbusaur
[13.4.2021 21:46:02] LePiromano
[13.4.2021 21:46:02] Rokvach
[13.4.2021 21:43:03] Soup
[13.4.2021 21:43:03] Solbusaur
[13.4.2021 21:43:03] LePiromano
[13.4.2021 21:43:03] Rokvach
[13.4.2021 21:43:03] Server command: revive LePiromano
[13.4.2021 21:43:03] revive LePiromano
[13.4.2021 21:41:30] Soup
[13.4.2021 21:41:30] Solbusaur
[13.4.2021 21:41:30] LePiromano
[13.4.2021 21:41:30] Rokvach
[13.4.2021 21:40:30] Solbusaur
[13.4.2021 21:40:30] LePiromano
[13.4.2021 21:40:30] Rokvach
[13.4.2021 21:40:29] Rokvach's godmode on
[13.4.2021 21:40:29] Server command: godmode Rokvach
[13.4.2021 21:40:29] godmode Rokvach
[13.4.2021 21:39:51] Solbusaur
[13.4.2021 21:39:51] LePiromano
[13.4.2021 21:39:51] Rokvach
[13.4.2021 21:39:46] Solbusaur
[13.4.2021 21:39:46] LePiromano
[13.4.2021 21:39:46] Rokvach
[13.4.2021 21:39:45] Solbusaur
[13.4.2021 21:39:45] LePiromano
[13.4.2021 21:39:45] Rokvach
[13.4.2021 21:39:39] Solbusaur
[13.4.2021 21:39:39] LePiromano
[13.4.2021 21:39:39] Rokvach
[13.4.2021 21:39:30] Solbusaur
[13.4.2021 21:39:30] LePiromano
[13.4.2021 21:39:30] Rokvach
[13.4.2021 21:39:29] Task count: 0
[13.4.2021 21:39:27] Generating an outpost for the start of the level... (Location: Seosu Outpost, level type: Outpost)
[13.4.2021 21:39:16] Solbusaur
[13.4.2021 21:39:16] LePiromano
[13.4.2021 21:39:16] Rokvach
[13.4.2021 21:39:07] Solbusaur
[13.4.2021 21:39:07] LePiromano
[13.4.2021 21:39:07] Rokvach
[13.4.2021 21:38:54] Solbusaur
[13.4.2021 21:38:54] LePiromano
[13.4.2021 21:38:54] Rokvach
[13.4.2021 21:38:51] Task count: 0
[13.4.2021 21:38:49] Generating an outpost for the start of the level... (Location: Sparti Linea, level type: LocationConnection)
[13.4.2021 21:38:33] LePiromano
[13.4.2021 21:38:33] Rokvach
[13.4.2021 21:35:58] LePiromano
[13.4.2021 21:35:58] Rokvach
[13.4.2021 21:35:19] Server command: say We are in a abandoned outpost, it doesn't let you spectate while we are here for some reason
[13.4.2021 21:35:19] say We are in a abandoned outpost, it doesn't let you spectate while we are here for some reason
[13.4.2021 21:35:07] Command "We" not found.
[13.4.2021 21:35:07] Server command: We are in a abandoned outpost, it doesn't let you spectate while we are here for some reason
[13.4.2021 21:35:07] We are in a abandoned outpost, it doesn't let you spectate while we are here for some reason
[13.4.2021 21:34:52] Server command: say always forget to take meds :D
[13.4.2021 21:34:52] say always forget to take meds :D
[13.4.2021 21:34:24] LePiromano
[13.4.2021 21:34:24] Rokvach
[13.4.2021 21:34:16] LePiromano
[13.4.2021 21:34:16] Rokvach
[13.4.2021 21:34:16] LePiromano
[13.4.2021 21:34:16] Rokvach
[13.4.2021 21:33:13] LePiromano
[13.4.2021 21:33:13] Rokvach
[13.4.2021 21:33:03] LePiromano
[13.4.2021 21:33:03] Rokvach
[13.4.2021 21:33:02] Task count: 0
[13.4.2021 21:33:00] Generating an outpost for the start of the level... (Location: Skadi's Cauldron Outpost, level type: Outpost)
[13.4.2021 21:32:50] LePiromano
[13.4.2021 21:32:50] Rokvach
[13.4.2021 21:32:41] LePiromano
[13.4.2021 21:32:41] Rokvach
```

**Comment by Rokvach** [comment]
Loaded up the save again and it says that we are in a mining outpost when we clearly aren't
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/f0004a5b-7efc-4838-aeae-ad4c5f141dca)

**Comment by Rokvach** [comment]
Extra issue I noticed after doing the above steps and loading up the save file after the crash

https://github.com/Regalis11/Barotrauma/issues/5512

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c088899be3851b12b6cbfa707faf3053d436d4fa

**Comment by Rokvach** [comment]
Tested, wasn't able to repro, working correctly. Closing.
