### ISSUE TITLE
Game crash upon logging into single player campaign

### ISSUE THREAD

**Issue by JaxC123** [Regalis11/Barotrauma#5515]
**Description**
When I load into my single player campaign the screen is black except for an "End Round" tab at the top of the screen. There is a large text box at the top left hand of the screen full of red text. The in game chat box can also be seen. Upon clicking "End Round" a map with missions pops up, but I can't start any of them. 

**Steps To Reproduce**
I bought a remora class sub and had been messing around with the drone and exploring the ship. After I saved and logged back on this bug appeared. I have never seen it before.

**Version**
I play on windows 10. I do not know which version of the game I play. If it means anything, I update it whenever steam says an update is ready.

**Additional information**
Here is the file with the crash info: 
[crashreport (17).log](https://github.com/Regalis11/Barotrauma/files/6314378/crashreport.17.log)

Barotrauma Client crash report (generated on 4/14/2021 7:07:05 PM)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

32AA46FAB36BEE9386335D0F440A6AF3

Game version 0.12.0.3 (ReleaseWindows, branch release, revision ea245a2f34)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla 0.9, ALIEN - XENOMORPH-Fix, ALIEN - XENOMORPH
Level seed: no level loaded
Loaded submarine: None
Selected screen: Barotrauma.GameScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19041.0 64 bit
    GPU name: Intel(R) UHD Graphics 630
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void Update(Single)
Stack trace: 
   at Barotrauma.SinglePlayerCampaign.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameSession\GameModes\SinglePlayerCampaign.cs:line 568
   at Barotrauma.GameSession.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameSession.cs:line 555
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 132
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 925
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[4/14/2021 7:06:28 PM] Couldn't start game session, submarine file corrupted.
[4/14/2021 7:06:27 PM] Loading submarine "C:\Users\jacks\AppData\Local\Daedalic Entertainment GmbH\Barotrauma\temp\Remora.sub" failed! (File not found)    at System.Environment.get_StackTrace()
   at Barotrauma.SubmarineInfo.OpenFile(String file, Exception& exception) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\SubmarineInfo.cs:line 673
   at Barotrauma.SubmarineInfo.Reload() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\SubmarineInfo.cs:line 283
   at Barotrauma.SubmarineInfo..ctor(String filePath, String hash, XElement element, Boolean tryLoad) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\SubmarineInfo.cs:line 231
   at Barotrauma.SaveUtil.LoadOwnedSubmarines(XDocument saveDoc, SubmarineInfo& selectedSub) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SaveUtil.cs:line 152
   at Barotrauma.SaveUtil.LoadGame(String filePath) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SaveUtil.cs:line 134
   at Barotrauma.MainMenuScreen.LoadGame(String saveFile) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\MainMenuScreen.cs:line 1095
   at Barotrauma.CampaignSetupUI.<UpdateLoadMenu>b__33_2(GUIButton btn, Object obj) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\CampaignSetupUI.cs:line 666
   at Barotrauma.GUIButton.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIButton.cs:line 262
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Barotrauma.GUI.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1224
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 952
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 651
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59 {Could not find file 'C:\Users\jacks\AppData\Local\Daedalic Entertainment GmbH\Barotrauma\temp\Remora.sub'.}
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Barotrauma.IO.File.Open(String path, FileMode mode, FileAccess access) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SafeIO.cs:line 306
   at Barotrauma.SaveUtil.DecompressFiletoStream(String fileName) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SaveUtil.cs:line 353
   at Barotrauma.SubmarineInfo.OpenFile(String file, Exception& exception) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\SubmarineInfo.cs:line 673
[4/14/2021 7:06:27 PM] Loading submarine "C:\Users\jacks\AppData\Local\Daedalic Entertainment GmbH\Barotrauma\temp\Dugong Mk2-6  Changed.sub" failed! (File not found)    at System.Environment.get_StackTrace()
   at Barotrauma.SubmarineInfo.OpenFile(String file, Exception& exception) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\SubmarineInfo.cs:line 673
   at Barotrauma.SubmarineInfo.Reload() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\SubmarineInfo.cs:line 283
   at Barotrauma.SubmarineInfo..ctor(String filePath, String hash, XElement element, Boolean tryLoad) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\SubmarineInfo.cs:line 231
   at Barotrauma.SaveUtil.LoadOwnedSubmarines(XDocument saveDoc, SubmarineInfo& selectedSub) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SaveUtil.cs:line 152
   at Barotrauma.SaveUtil.LoadGame(String filePath) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SaveUtil.cs:line 134
   at Barotrauma.MainMenuScreen.LoadGame(String saveFile) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\MainMenuScreen.cs:line 1095
   at Barotrauma.CampaignSetupUI.<UpdateLoadMenu>b__33_2(GUIButton btn, Object obj) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\CampaignSetupUI.cs:line 666
   at Barotrauma.GUIButton.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIButton.cs:line 262
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Barotrauma.GUI.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1224
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 952
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 651
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59 {Could not find file 'C:\Users\jacks\AppData\Local\Daedalic Entertainment GmbH\Barotrauma\temp\Dugong Mk2-6  Changed.sub'.}
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Barotrauma.IO.File.Open(String path, FileMode mode, FileAccess access) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SafeIO.cs:line 306
   at Barotrauma.SaveUtil.DecompressFiletoStream(String fileName) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SaveUtil.cs:line 353
   at Barotrauma.SubmarineInfo.OpenFile(String file, Exception& exception) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\SubmarineInfo.cs:line 673
[4/14/2021 7:06:27 PM] Loading submarine "C:\Users\jacks\AppData\Local\Daedalic Entertainment GmbH\Barotrauma\temp\Dugong.sub" failed! (File not found)    at System.Environment.get_StackTrace()
   at Barotrauma.SubmarineInfo.OpenFile(String file, Exception& exception) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\SubmarineInfo.cs:line 673
   at Barotrauma.SubmarineInfo.Reload() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\SubmarineInfo.cs:line 283
   at Barotrauma.SubmarineInfo..ctor(String filePath, String hash, XElement element, Boolean tryLoad) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\SubmarineInfo.cs:line 231
   at Barotrauma.SaveUtil.LoadOwnedSubmarines(XDocument saveDoc, SubmarineInfo& selectedSub) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SaveUtil.cs:line 152
   at Barotrauma.SaveUtil.LoadGame(String filePath) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SaveUtil.cs:line 134
   at Barotrauma.MainMenuScreen.LoadGame(String saveFile) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\MainMenuScreen.cs:line 1095
   at Barotrauma.CampaignSetupUI.<UpdateLoadMenu>b__33_2(GUIButton btn, Object obj) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\CampaignSetupUI.cs:line 666
   at Barotrauma.GUIButton.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIButton.cs:line 262
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Barotrauma.GUI.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1224
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 952
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 651
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59 {Could not find file 'C:\Users\jacks\AppData\Local\Daedalic Entertainment GmbH\Barotrauma\temp\Dugong.sub'.}
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Barotrauma.IO.File.Open(String path, FileMode mode, FileAccess access) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SafeIO.cs:line 306
   at Barotrauma.SaveUtil.DecompressFiletoStream(String fileName) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SaveUtil.cs:line 353
   at Barotrauma.SubmarineInfo.OpenFile(String file, Exception& exception) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\SubmarineInfo.cs:line 673
[4/14/2021 7:06:27 PM] Loading submarine "C:\Users\jacks\AppData\Local\Daedalic Entertainment GmbH\Barotrauma\temp\Remora.sub" failed! (File not found)    at System.Environment.get_StackTrace()
   at Barotrauma.SubmarineInfo.OpenFile(String file, Exception& exception) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\SubmarineInfo.cs:line 673
   at Barotrauma.SubmarineInfo.Reload() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\SubmarineInfo.cs:line 283
   at Barotrauma.SubmarineInfo..ctor(String filePath, String hash, XElement element, Boolean tryLoad) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\SubmarineInfo.cs:line 231
   at Barotrauma.SaveUtil.LoadOwnedSubmarines(XDocument saveDoc, SubmarineInfo& selectedSub) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SaveUtil.cs:line 141
   at Barotrauma.SaveUtil.LoadGame(String filePath) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SaveUtil.cs:line 134
   at Barotrauma.MainMenuScreen.LoadGame(String saveFile) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\MainMenuScreen.cs:line 1095
   at Barotrauma.CampaignSetupUI.<UpdateLoadMenu>b__33_2(GUIButton btn, Object obj) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\CampaignSetupUI.cs:line 666
   at Barotrauma.GUIButton.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIButton.cs:line 262
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Barotrauma.GUI.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1224
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 952
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 651
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59 {Could not find file 'C:\Users\jacks\AppData\Local\Daedalic Entertainment GmbH\Barotrauma\temp\Remora.sub'.}
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Barotrauma.IO.File.Open(String path, FileMode mode, FileAccess access) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SafeIO.cs:line 306
   at Barotrauma.SaveUtil.DecompressFiletoStream(String fileName) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SaveUtil.cs:line 353
   at Barotrauma.SubmarineInfo.OpenFile(String file, Exception& exception) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\SubmarineInfo.cs:line 673
[4/14/2021 7:06:10 PM] (Msg) SDR RelayNetworkStatus:  avail=OK  config=OK  anyrelay=OK   (OK)
[4/14/2021 7:06:10 PM] (Msg) Ping location: ord=24+2,iad=38+3,dfw=41+4,atl=49+4/42+2,sea=70+7/70+2,lax=88+8/70+2,eat=76+7/80+2,par=119+11/115+3,ams=117+11/116+2,fra=130+13/122+2,gru=172+17/173+2,sgp=252+25/258+4
[4/14/2021 7:06:10 PM] (Msg) Ping measurement completed
[4/14/2021 7:06:09 PM] (Verbose) Communications with routing cluster 'iad' established.
[4/14/2021 7:06:09 PM] (Debug) Destroying relay 'iad#231 (162.254.192.86:27039)' because initial_ping_timeout
[4/14/2021 7:06:07 PM] (Verbose) Communications with routing cluster 'lax' established.
[4/14/2021 7:06:06 PM] (Verbose) Communications with routing cluster 'sgp' established.
[4/14/2021 7:06:06 PM] (Verbose) Communications with routing cluster 'syd' established.
[4/14/2021 7:06:06 PM] (Verbose) Communications with routing cluster 'maa' established.
[4/14/2021 7:06:06 PM] (Verbose) Communications with routing cluster 'tyo1' established.
[4/14/2021 7:06:06 PM] (Verbose) Communications with routing cluster 'tyo' established.
[4/14/2021 7:06:06 PM] (Verbose) Communications with routing cluster 'waw' established.
[4/14/2021 7:06:06 PM] (Verbose) Communications with routing cluster 'vie' established.
[4/14/2021 7:06:06 PM] (Verbose) Communications with routing cluster 'jnb' established.
[4/14/2021 7:06:06 PM] (Verbose) Communications with routing cluster 'sto2' established.
[4/14/2021 7:06:06 PM] (Warning) Relay sof#2 (139.45.193.10:27016) sent CMsgSteamDatagramRouterPingReply with extra route info about data center 6c696d, but no ping for that data center?.
[4/14/2021 7:06:06 PM] (Warning) Relay sof#2 (139.45.193.10:27016) sent CMsgSteamDatagramRouterPingReply with extra route info about data center 6a6e62, but no ping for that data center?.
[4/14/2021 7:06:06 PM] (Warning) Relay sof#2 (139.45.193.10:27016) sent CMsgSteamDatagramRouterPingReply with extra route info about data center 656174, but no ping for that data center?.
[4/14/2021 7:06:06 PM] (Warning) Relay sof#2 (139.45.193.10:27016) sent CMsgSteamDatagramRouterPingReply with extra route info about data center 6d6161, but no ping for that data center?.
[4/14/2021 7:06:06 PM] (Warning) Relay sof#2 (139.45.193.10:27016) sent CMsgSteamDatagramRouterPingReply with extra route info about data center 6c6178, but no ping for that data center?.
[4/14/2021 7:06:06 PM] (Warning) Relay sof#2 (139.45.193.10:27016) sent CMsgSteamDatagramRouterPingReply with extra route info about data center 647862, but no ping for that data center?.
[4/14/2021 7:06:06 PM] (Warning) Relay sof#2 (139.45.193.10:27016) sent CMsgSteamDatagramRouterPingReply with extra route info about data center 626f6d, but no ping for that data center?.
[4/14/2021 7:06:06 PM] (Warning) Relay sof#2 (139.45.193.10:27016) sent CMsgSteamDatagramRouterPingReply with extra route info about data center 61746c, but no ping for that data center?.
[4/14/2021 7:06:06 PM] (Warning) Relay sof#2 (139.45.193.10:27016) sent CMsgSteamDatagramRouterPingReply with extra route info about data center 6f7264, but no ping for that data center?.
[4/14/2021 7:06:06 PM] (Warning) Relay sof#2 (139.45.193.10:27016) sent CMsgSteamDatagramRouterPingReply with extra route info about data center 696164, but no ping for that data center?.
[4/14/2021 7:06:06 PM] (Warning) Relay sof#2 (139.45.193.10:27016) sent CMsgSteamDatagramRouterPingReply with extra route info about data center 6d6164, but no ping for that data center?.
[4/14/2021 7:06:06 PM] (Warning) Relay sof#2 (139.45.193.10:27016) sent CMsgSteamDatagramRouterPingReply with extra route info about data center 776177, but no ping for that data center?.
[4/14/2021 7:06:06 PM] (Warning) Relay sof#2 (139.45.193.10:27016) sent CMsgSteamDatagramRouterPingReply with extra route info about data center 73746f, but no ping for that data center?.
[4/14/2021 7:06:06 PM] (Warning) Relay sof#2 (139.45.193.10:27016) sent CMsgSteamDatagramRouterPingReply with extra route info about data center 667261, but no ping for that data center?.
[4/14/2021 7:06:06 PM] (Warning) Relay sof#2 (139.45.193.10:27016) sent CMsgSteamDatagramRouterPingReply with extra route info about data center 766965, but no ping for that data center?.
[4/14/2021 7:06:06 PM] (Verbose) Communications with routing cluster 'sof' established.
[4/14/2021 7:06:06 PM] (Verbose) Communications with routing cluster 'sto' established.
[4/14/2021 7:06:06 PM] (Verbose) Communications with routing cluster 'scl' established.
[4/14/2021 7:06:06 PM] (Verbose) Communications with routing cluster 'sea' established.
[4/14/2021 7:06:06 PM] (Verbose) Communications with routing cluster 'bom' established.
[4/14/2021 7:06:06 PM] (Verbose) Communications with routing cluster 'mad' established.
[4/14/2021 7:06:06 PM] (Verbose) Communications with routing cluster 'dxb' established.
[4/14/2021 7:06:06 PM] (Verbose) Communications with routing cluster 'hkg' established.
[4/14/2021 7:06:06 PM] (Verbose) Communications with routing cluster 'par' established.
[4/14/2021 7:06:06 PM] (Verbose) Communications with routing cluster 'lim' established.
[4/14/2021 7:06:06 PM] (Verbose) Communications with routing cluster 'eze' established.
[4/14/2021 7:06:06 PM] (Verbose) Communications with routing cluster 'lhr' established.
[4/14/2021 7:06:06 PM] (Verbose) Communications with routing cluster 'gru' established.
[4/14/2021 7:06:06 PM] (Verbose) Communications with routing cluster 'fra' established.
[4/14/2021 7:06:06 PM] (Verbose) Communications with routing cluster 'ord' established.
[4/14/2021 7:06:06 PM] (Verbose) Communications with routing cluster 'ams' established.
[4/14/2021 7:06:06 PM] (Verbose) Communications with routing cluster 'eat' established.
[4/14/2021 7:06:06 PM] (Verbose) Communications with routing cluster 'atl' established.
[4/14/2021 7:06:06 PM] (Verbose) Communications with routing cluster 'dfw' established.
[4/14/2021 7:06:06 PM] Duplicate mission found with the identifier 'killxenos' in file 'Mods/ALIEN - XENOMORPH/Mods/Xeno/XenoMissions.xml'! Add <override></override> tags as the parent of the mission definition to allow overriding.
[4/14/2021 7:06:06 PM] (Msg) SDR RelayNetworkStatus:  avail=Attempting  config=OK  anyrelay=Attempting   (Performing ping measurement)
[4/14/2021 7:06:06 PM] (Msg) Performing ping measurement
[4/14/2021 7:06:06 PM] (Msg) Got SDR network config.  Loaded revision 316 OK
[4/14/2021 7:06:06 PM] Error registering "Facehugger", "facehugger" (Barotrauma.CharacterPrefab): base already exists; try overriding
[4/14/2021 7:06:06 PM] Error registering "Xeno", "xeno" (Barotrauma.CharacterPrefab): base already exists; try overriding
[4/14/2021 7:06:06 PM] (Warning) SDR network config fetch first attempt failed.  HTTP 504.  .  Trying again.
[4/14/2021 7:05:57 PM] Attempting to open ALC device "OpenAL Soft on Speakers (Realtek(R) Audio)"
[4/14/2021 7:05:57 PM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[4/14/2021 7:05:56 PM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[4/14/2021 7:05:56 PM] Error in content package "Kastrull_Wrecked" - no content files defined.
[4/14/2021 7:05:56 PM] Error in content package "Hemulen_Wrecked" - no content files defined.
[4/14/2021 7:05:56 PM] Error in content package "Berilia_Wrecked" - no content files defined.
[4/14/2021 7:05:56 PM] Logged in as Spoonman (SteamID STEAM_1:1:448136199)

**Comment by JaxC123** [comment]
I saw a player who had a similar issue (perhaps the same one). The fix was posted in a link: Regalis11/Barotrauma-development@1891ba8  but when I click on this link I get a 404 error message with a cloaked man saying this is not the page I was looking for.

**Comment by Regalis11** [comment]
Thank you for the report! The issue you mentioned (https://github.com/Regalis11/Barotrauma/issues/3459) seems to actually be slightly different than this: in that case the game failed to load a shuttle linked to the submarine, but here it fails to load the submarine itself for some reason.

It would help us a lot in diagnosing this if you could provide us the save file (located in `C:\Users\[username]\AppData\Local\Daedalic Entertainment GmbH`). Note that the file needs to be .zipped to attach it here, because GitHub doesn't support the .save file extension.

Thank you and sorry for the inconvenience!

**Comment by JaxC123** [comment]
[#1.zip](https://github.com/Regalis11/Barotrauma/files/6319864/1.zip)

**Comment by JaxC123** [comment]
I accidentally selected Apex legends when I was trying to open the folder and now the logo is attached. I
m not sure how to change that. I believe this is the correct file.
