### ISSUE TITLE
[Unstable] Singleplayer save glitching out on level change to research outpost

### ISSUE THREAD

**Issue by SumNutz** [Regalis11/Barotrauma#5553]
I was on my way from a natural formation after completing a crawler nest mission to a research outpost near the gating from the Europan Ridge to Aphotic Plateau in the Remora sub. There was a beacon side mission available but did not try to accomplish it.

Steps to reproduce: 
navigate through the level normally, attempt to dock at the research outpost and glitch out

Console output:

Could not move to the next location (no connection selected).
   at System.Environment.get_StackTrace()
   at Barotrauma.Map.MoveToNextLocation() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Map\Map.cs:line 652
   at Barotrauma.SinglePlayerCampaign.DoLevelTransition(TransitionType transitionType, LevelData newLevel, Submarine leavingSub, Boolean mirror, List`1 traitorResults)+MoveNext() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameSession\GameModes\SinglePlayerCampaign.cs:line 412
   at Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 218
   at Barotrauma.CoroutineManager.Update(Single unscaledDeltaTime, Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 259
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 979
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 651
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59

Save file:
[a less than normal.zip](https://github.com/Regalis11/Barotrauma/files/6346983/a.less.than.normal.zip)

**Comment by Rokvach** [comment]
Tested in release branch

I got this warning when I loaded up the save file
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/3b4d4bb1-bb44-44a6-a6a7-d54605e569c7)

Tried to reproduce the issue by going through this path, but I didn't encounter any errors
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/a741dbdf-5dfc-4fff-bb29-b433629f4e52)

**Comment by SumNutz** [comment]
weird, i'll try verifying game files see if the problem still persists.

**Comment by SumNutz** [comment]
got the same warning message at the beginning of the level, if it fails once again i'll try going back to the gate city from the formation.

**Comment by SumNutz** [comment]
backtracking to the city worked, no errors logged. will attempt to go back to formation and to research outpost see if it still glitches out.

**Comment by SumNutz** [comment]
route complete, no problems anymore... guess it was a one time glitch?

![image](https://user-images.githubusercontent.com/46006004/115555321-bff84100-a285-11eb-95b6-45096e0ff053.png)

**Comment by SumNutz** [comment]
route complete, no problems anymore... guess it was a one time glitch?

![image](https://user-images.githubusercontent.com/46006004/115555321-bff84100-a285-11eb-95b6-45096e0ff053.png)

**Comment by Rokvach** [comment]
I think we should keep this open until a programmer takes a look at it as there might be some glues on the error message as to why this happened
