### ISSUE TITLE
Crashes when loading

### ISSUE THREAD

**Issue by ShadowFMLCzZ** [Regalis11/Barotrauma#5675]
- [x] I have searched the issue tracker to check if the issue has already been reported.

I uninstalled and reinstalled and it works. but im not sure why it didnt work the first time

**Description**
once i launch it on steam when it reaches the loading screen it gets stuck and the mesage"oops Barotrauma just crashed" appears

**Version**
0.13.3.11 Windows 7

**Additional information**
Barotrauma Client crash report (generated on 01/05/2021 09:03:50 p.m.)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

To prevent further startup errors, installed mods will be disabled the next time you launch the game.

1E784E57B83E4AD2C454A781377E1373

Game version 0.13.3.11 (ReleaseWindows, branch release, revision 7096536cf1)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla 0.9
Level seed: no level loaded
Loaded submarine: None
Selected screen: None
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 6.1.7601 Service Pack 1 64 bit
    GPU name: NVIDIA GeForce GT 710
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1,7777778}
    GPU status: Normal

Exception: Loading was interrupted due to an error. (Barotrauma.GameMain+LoadingException)
Target site: Void Update(Microsoft.Xna.Framework.GameTime)
Stack trace: 
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 809
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59

InnerException: Could not determine container type!
Target site: Void .ctor(System.IO.Stream, Boolean)
Stack trace: 
   at NVorbis.VorbisReader..ctor(Stream stream, Boolean closeStreamOnDispose)
   at Barotrauma.Sounds.OggSound.InitializeALBuffers() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Sounds\OggSound.cs:line 71
   at Barotrauma.Sounds.OggSound..ctor(SoundManager owner, String filename, Boolean stream, XElement xElement) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Sounds\OggSound.cs:line 19
   at Barotrauma.Sounds.SoundManager.LoadSound(String filename, Boolean stream) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Sounds\SoundManager.cs:line 346
   at Barotrauma.Submarine.LoadRoundSound(XElement element, Boolean stream) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Map\Submarine.cs:line 119
   at Barotrauma.StatusEffect.InitProjSpecific(XElement element, String parentDebugName) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\StatusEffects\StatusEffect.cs:line 38
   at Barotrauma.StatusEffect..ctor(XElement element, String parentDebugName) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\StatusEffects\StatusEffect.cs:line 632
   at Barotrauma.StatusEffect.Load(XElement element, String parentDebugName) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\StatusEffects\StatusEffect.cs:line 347
   at Barotrauma.AfflictionPrefab.PeriodicEffect..ctor(XElement element, String parentDebugName) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Health\Afflictions\AfflictionPrefab.cs:line 218
   at Barotrauma.AfflictionPrefab.LoadEffects(XElement element) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Health\Afflictions\AfflictionPrefab.cs:line 650
   at Barotrauma.AfflictionPrefab.LoadFromFile(ContentFile file) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Health\Afflictions\AfflictionPrefab.cs:line 542
   at Barotrauma.AfflictionPrefab.LoadAll(IEnumerable`1 files) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Health\Afflictions\AfflictionPrefab.cs:line 370
   at Barotrauma.GameMain.Load(Boolean isSeparateThread)+MoveNext() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 551
   at Barotrauma.CoroutineManager.ExecuteCoroutineThread(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 173
Last debug messages:
[01/05/2021 09:03:50 p.m.] Coroutine "Load" has failed
[01/05/2021 09:03:50 p.m.] Coroutine "Load" has thrown an exception {Could not determine container type!}
   at NVorbis.VorbisReader..ctor(Stream stream, Boolean closeStreamOnDispose)
   at Barotrauma.Sounds.OggSound.InitializeALBuffers() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Sounds\OggSound.cs:line 71
   at Barotrauma.Sounds.OggSound..ctor(SoundManager owner, String filename, Boolean stream, XElement xElement) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Sounds\OggSound.cs:line 19
   at Barotrauma.Sounds.SoundManager.LoadSound(String filename, Boolean stream) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Sounds\SoundManager.cs:line 346
   at Barotrauma.Submarine.LoadRoundSound(XElement element, Boolean stream) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Map\Submarine.cs:line 119
   at Barotrauma.StatusEffect.InitProjSpecific(XElement element, String parentDebugName) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\StatusEffects\StatusEffect.cs:line 38
   at Barotrauma.StatusEffect..ctor(XElement element, String parentDebugName) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\StatusEffects\StatusEffect.cs:line 632
   at Barotrauma.StatusEffect.Load(XElement element, String parentDebugName) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\StatusEffects\StatusEffect.cs:line 347
   at Barotrauma.AfflictionPrefab.PeriodicEffect..ctor(XElement element, String parentDebugName) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Health\Afflictions\AfflictionPrefab.cs:line 218
   at Barotrauma.AfflictionPrefab.LoadEffects(XElement element) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Health\Afflictions\AfflictionPrefab.cs:line 650
   at Barotrauma.AfflictionPrefab.LoadFromFile(ContentFile file) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Health\Afflictions\AfflictionPrefab.cs:line 542
   at Barotrauma.AfflictionPrefab.LoadAll(IEnumerable`1 files) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Health\Afflictions\AfflictionPrefab.cs:line 370
   at Barotrauma.GameMain.Load(Boolean isSeparateThread)+MoveNext() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 551
   at Barotrauma.CoroutineManager.ExecuteCoroutineThread(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 173
[01/05/2021 09:03:49 p.m.] Error in fabricable item 40mm Grenade! Required item "uex" not found.
[01/05/2021 09:03:49 p.m.] Failed to find a matching MapEntityPrefab (name: "", identifier: "uex").
   at System.Environment.get_StackTrace()
   at Barotrauma.MapEntityPrefab.Find(String name, String identifier, Boolean showErrorMessages) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\MapEntityPrefab.cs:line 315
   at Barotrauma.FabricationRecipe..ctor(XElement element, ItemPrefab itemPrefab) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\ItemPrefab.cs:line 116
   at Barotrauma.ItemPrefab.InitFabricationRecipes() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\ItemPrefab.cs:line 642
   at Barotrauma.GameMain.Load(Boolean isSeparateThread)+MoveNext() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 550
   at Barotrauma.CoroutineManager.ExecuteCoroutineThread(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 173
   at Barotrauma.CoroutineManager.<>c__DisplayClass3_0.<StartCoroutine>b__0() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 50
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
[01/05/2021 09:03:49 p.m.] Error in fabricable item Frag Grenade! Required item "uex" not found.
[01/05/2021 09:03:49 p.m.] Failed to find a matching MapEntityPrefab (name: "", identifier: "uex").
   at System.Environment.get_StackTrace()
   at Barotrauma.MapEntityPrefab.Find(String name, String identifier, Boolean showErrorMessages) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\MapEntityPrefab.cs:line 315
   at Barotrauma.FabricationRecipe..ctor(XElement element, ItemPrefab itemPrefab) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\ItemPrefab.cs:line 116
   at Barotrauma.ItemPrefab.InitFabricationRecipes() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\ItemPrefab.cs:line 642
   at Barotrauma.GameMain.Load(Boolean isSeparateThread)+MoveNext() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 550
   at Barotrauma.CoroutineManager.ExecuteCoroutineThread(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 173
   at Barotrauma.CoroutineManager.<>c__DisplayClass3_0.<StartCoroutine>b__0() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 50
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
[01/05/2021 09:03:49 p.m.] Error in fabricable item EMP Grenade! Required item "uex" not found.
[01/05/2021 09:03:49 p.m.] Failed to find a matching MapEntityPrefab (name: "", identifier: "uex").
   at System.Environment.get_StackTrace()
   at Barotrauma.MapEntityPrefab.Find(String name, String identifier, Boolean showErrorMessages) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\MapEntityPrefab.cs:line 315
   at Barotrauma.FabricationRecipe..ctor(XElement element, ItemPrefab itemPrefab) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\ItemPrefab.cs:line 116
   at Barotrauma.ItemPrefab.InitFabricationRecipes() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\ItemPrefab.cs:line 642
   at Barotrauma.GameMain.Load(Boolean isSeparateThread)+MoveNext() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 550
   at Barotrauma.CoroutineManager.ExecuteCoroutineThread(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 173
   at Barotrauma.CoroutineManager.<>c__DisplayClass3_0.<StartCoroutine>b__0() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 50
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
[01/05/2021 09:03:49 p.m.] Error in fabricable item Explosive Harpoon! Required item "c4block" not found.
[01/05/2021 09:03:49 p.m.] Failed to find a matching MapEntityPrefab (name: "", identifier: "c4block").
   at System.Environment.get_StackTrace()
   at Barotrauma.MapEntityPrefab.Find(String name, String identifier, Boolean showErrorMessages) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\MapEntityPrefab.cs:line 315
   at Barotrauma.FabricationRecipe..ctor(XElement element, ItemPrefab itemPrefab) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\ItemPrefab.cs:line 116
   at Barotrauma.ItemPrefab.InitFabricationRecipes() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\ItemPrefab.cs:line 642
   at Barotrauma.GameMain.Load(Boolean isSeparateThread)+MoveNext() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 550
   at Barotrauma.CoroutineManager.ExecuteCoroutineThread(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 173
   at Barotrauma.CoroutineManager.<>c__DisplayClass3_0.<StartCoroutine>b__0() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 50
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
[01/05/2021 09:03:49 p.m.] Error in fabricable item Exploding Ammunition Box! Required item "uex" not found.
[01/05/2021 09:03:49 p.m.] Failed to find a matching MapEntityPrefab (name: "", identifier: "uex").
   at System.Environment.get_StackTrace()
   at Barotrauma.MapEntityPrefab.Find(String name, String identifier, Boolean showErrorMessages) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\MapEntityPrefab.cs:line 315
   at Barotrauma.FabricationRecipe..ctor(XElement element, ItemPrefab itemPrefab) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\ItemPrefab.cs:line 116
   at Barotrauma.ItemPrefab.InitFabricationRecipes() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\ItemPrefab.cs:line 642
   at Barotrauma.GameMain.Load(Boolean isSeparateThread)+MoveNext() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 550
   at Barotrauma.CoroutineManager.ExecuteCoroutineThread(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 173
   at Barotrauma.CoroutineManager.<>c__DisplayClass3_0.<StartCoroutine>b__0() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 50
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
[01/05/2021 09:03:49 p.m.] Error in fabricable item Exploding Ammunition Box! Required item "uex" not found.
[01/05/2021 09:03:49 p.m.] Failed to find a matching MapEntityPrefab (name: "", identifier: "uex").
   at System.Environment.get_StackTrace()
   at Barotrauma.MapEntityPrefab.Find(String name, String identifier, Boolean showErrorMessages) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\MapEntityPrefab.cs:line 315
   at Barotrauma.FabricationRecipe..ctor(XElement element, ItemPrefab itemPrefab) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\ItemPrefab.cs:line 116
   at Barotrauma.ItemPrefab.InitFabricationRecipes() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\ItemPrefab.cs:line 642
   at Barotrauma.GameMain.Load(Boolean isSeparateThread)+MoveNext() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 550
   at Barotrauma.CoroutineManager.ExecuteCoroutineThread(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 173
   at Barotrauma.CoroutineManager.<>c__DisplayClass3_0.<StartCoroutine>b__0() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 50
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
[01/05/2021 09:03:49 p.m.] (Msg) SDR RelayNetworkStatus:  avail=OK  config=OK  anyrelay=OK   (OK)
[01/05/2021 09:03:49 p.m.] (Msg) Ping location: lim=136+13,scl=138+13,eze=139+13,gru=148+14,atl=159+15,iad=172+17/172+15,ord=177+17/177+15,dfw=185+18/180+15,lax=212+21,eat=222+22/221+22,fra=257+25/248+23,sgp=381+38/359+27
[01/05/2021 09:03:49 p.m.] (Msg) Ping measurement completed
[01/05/2021 09:03:49 p.m.] Couldn't load xml document "Content/Items/Weapons/railgun.xml"! {'.', hexadecimal value 0x00, is an invalid character. Line 1, position 1.}
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ThrowInvalidChar(Char[] data, Int32 length, Int32 invCharPos)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
   at Barotrauma.XMLExtensions.TryLoadXml(String filePath) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Serialization\XMLExtensions.cs:line 23
[01/05/2021 09:03:49 p.m.] Couldn't load xml document "Content/Items/Weapons/explosives.xml"! {'.', hexadecimal value 0x00, is an invalid character. Line 1, position 1.}
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ThrowInvalidChar(Char[] data, Int32 length, Int32 invCharPos)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
   at Barotrauma.XMLExtensions.TryLoadXml(String filePath) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Serialization\XMLExtensions.cs:line 23
[01/05/2021 09:03:49 p.m.] Couldn't load xml document "Content/Items/Weapons/dischargecoil.xml"! {'.', hexadecimal value 0x00, is an invalid character. Line 1, position 1.}
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ThrowInvalidChar(Char[] data, Int32 length, Int32 invCharPos)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
   at Barotrauma.XMLExtensions.TryLoadXml(String filePath) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Serialization\XMLExtensions.cs:line 23
[01/05/2021 09:03:49 p.m.] Couldn't load xml document "Content/Items/Weapons/depthcharge.xml"! {'.', hexadecimal value 0x00, is an invalid character. Line 1, position 1.}
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ThrowInvalidChar(Char[] data, Int32 length, Int32 invCharPos)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
   at Barotrauma.XMLExtensions.TryLoadXml(String filePath) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Serialization\XMLExtensions.cs:line 23
[01/05/2021 09:03:49 p.m.] Couldn't load xml document "Content/Items/Weapons/coilgun.xml"! {'.', hexadecimal value 0x00, is an invalid character. Line 1, position 1.}
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ThrowInvalidChar(Char[] data, Int32 length, Int32 invCharPos)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
   at Barotrauma.XMLExtensions.TryLoadXml(String filePath) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Serialization\XMLExtensions.cs:line 23
[01/05/2021 09:03:49 p.m.] Couldn't load xml document "Content/Items/Tools/tools.xml"! {'.', hexadecimal value 0x00, is an invalid character. Line 1, position 1.}
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ThrowInvalidChar(Char[] data, Int32 length, Int32 invCharPos)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
   at Barotrauma.XMLExtensions.TryLoadXml(String filePath) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Serialization\XMLExtensions.cs:line 23
[01/05/2021 09:03:47 p.m.] (Verbose) Communications with routing cluster 'syd' established.
[01/05/2021 09:03:46 p.m.] (Debug) Destroying relay 'syd#88 (103.10.125.154:27048)' because initial_ping_timeout
[01/05/2021 09:03:44 p.m.] (Verbose) Communications with routing cluster 'sgp' established.
[01/05/2021 09:03:44 p.m.] (Verbose) Communications with routing cluster 'maa' established.
[01/05/2021 09:03:44 p.m.] (Verbose) Communications with routing cluster 'jnb' established.
[01/05/2021 09:03:44 p.m.] (Verbose) Communications with routing cluster 'tyo' established.
[01/05/2021 09:03:44 p.m.] (Verbose) Communications with routing cluster 'tyo1' established.
[01/05/2021 09:03:44 p.m.] (Verbose) Communications with routing cluster 'dxb' established.
[01/05/2021 09:03:44 p.m.] (Warning) Relay sof#2 (139.45.193.10:27016) sent CMsgSteamDatagramRouterPingReply with extra route info about data center 736770, but no ping for that data center?.
[01/05/2021 09:03:44 p.m.] (Warning) Relay sof#2 (139.45.193.10:27016) sent CMsgSteamDatagramRouterPingReply with extra route info about data center 6a6e62, but no ping for that data center?.
[01/05/2021 09:03:44 p.m.] (Warning) Relay sof#2 (139.45.193.10:27016) sent CMsgSteamDatagramRouterPingReply with extra route info about data center 656174, but no ping for that data center?.
[01/05/2021 09:03:44 p.m.] (Warning) Relay sof#2 (139.45.193.10:27016) sent CMsgSteamDatagramRouterPingReply with extra route info about data center 6d6161, but no ping for that data center?.
[01/05/2021 09:03:44 p.m.] (Warning) Relay sof#2 (139.45.193.10:27016) sent CMsgSteamDatagramRouterPingReply with extra route info about data center 6c6178, but no ping for that data center?.
[01/05/2021 09:03:44 p.m.] (Warning) Relay sof#2 (139.45.193.10:27016) sent CMsgSteamDatagramRouterPingReply with extra route info about data center 647862, but no ping for that data center?.
[01/05/2021 09:03:44 p.m.] (Warning) Relay sof#2 (139.45.193.10:27016) sent CMsgSteamDatagramRouterPingReply with extra route info about data center 626f6d, but no ping for that data center?.
[01/05/2021 09:03:44 p.m.] (Warning) Relay sof#2 (139.45.193.10:27016) sent CMsgSteamDatagramRouterPingReply with extra route info about data center 61746c, but no ping for that data center?.
[01/05/2021 09:03:44 p.m.] (Warning) Relay sof#2 (139.45.193.10:27016) sent CMsgSteamDatagramRouterPingReply with extra route info about data center 6f7264, but no ping for that data center?.
[01/05/2021 09:03:44 p.m.] (Warning) Relay sof#2 (139.45.193.10:27016) sent CMsgSteamDatagramRouterPingReply with extra route info about data center 696164, but no ping for that data center?.
[01/05/2021 09:03:44 p.m.] (Warning) Relay sof#2 (139.45.193.10:27016) sent CMsgSteamDatagramRouterPingReply with extra route info about data center 6d6164, but no ping for that data center?.
[01/05/2021 09:03:44 p.m.] (Warning) Relay sof#2 (139.45.193.10:27016) sent CMsgSteamDatagramRouterPingReply with extra route info about data center 776177, but no ping for that data center?.
[01/05/2021 09:03:44 p.m.] (Warning) Relay sof#2 (139.45.193.10:27016) sent CMsgSteamDatagramRouterPingReply with extra route info about data center 73746f, but no ping for that data center?.
[01/05/2021 09:03:44 p.m.] (Warning) Relay sof#2 (139.45.193.10:27016) sent CMsgSteamDatagramRouterPingReply with extra route info about data center 667261, but no ping for that data center?.
[01/05/2021 09:03:44 p.m.] (Warning) Relay sof#2 (139.45.193.10:27016) sent CMsgSteamDatagramRouterPingReply with extra route info about data center 766965, but no ping for that data center?.
[01/05/2021 09:03:44 p.m.] (Verbose) Communications with routing cluster 'sof' established.
[01/05/2021 09:03:44 p.m.] (Verbose) Communications with routing cluster 'sto' established.
[01/05/2021 09:03:44 p.m.] (Verbose) Communications with routing cluster 'sto2' established.
[01/05/2021 09:03:44 p.m.] (Verbose) Communications with routing cluster 'vie' established.
[01/05/2021 09:03:44 p.m.] (Verbose) Communications with routing cluster 'waw' established.
[01/05/2021 09:03:44 p.m.] (Verbose) Communications with routing cluster 'sea' established.
[01/05/2021 09:03:44 p.m.] (Verbose) Communications with routing cluster 'bom' established.
[01/05/2021 09:03:44 p.m.] (Verbose) Communications with routing cluster 'par' established.
[01/05/2021 09:03:44 p.m.] (Verbose) Communications with routing cluster 'hkg' established.
[01/05/2021 09:03:44 p.m.] (Verbose) Communications with routing cluster 'mad' established.
[01/05/2021 09:03:44 p.m.] (Verbose) Communications with routing cluster 'lhr' established.
[01/05/2021 09:03:44 p.m.] (Verbose) Communications with routing cluster 'lax' established.
[01/05/2021 09:03:44 p.m.] (Verbose) Communications with routing cluster 'ord' established.
[01/05/2021 09:03:44 p.m.] (Verbose) Communications with routing cluster 'iad' established.
[01/05/2021 09:03:44 p.m.] (Verbose) Communications with routing cluster 'fra' established.
[01/05/2021 09:03:44 p.m.] (Verbose) Communications with routing cluster 'ams' established.
[01/05/2021 09:03:44 p.m.] (Verbose) Communications with routing cluster 'scl' established.
[01/05/2021 09:03:44 p.m.] (Verbose) Communications with routing cluster 'lim' established.
[01/05/2021 09:03:44 p.m.] (Verbose) Communications with routing cluster 'eat' established.
[01/05/2021 09:03:44 p.m.] (Verbose) Communications with routing cluster 'dfw' established.
[01/05/2021 09:03:44 p.m.] (Verbose) Communications with routing cluster 'atl' established.
[01/05/2021 09:03:44 p.m.] (Verbose) Communications with routing cluster 'gru' established.
[01/05/2021 09:03:44 p.m.] (Verbose) Communications with routing cluster 'eze' established.
[01/05/2021 09:03:43 p.m.] (Msg) SDR RelayNetworkStatus:  avail=Attempting  config=OK  anyrelay=Attempting   (Performing ping measurement)
[01/05/2021 09:03:43 p.m.] (Msg) Performing ping measurement
[01/05/2021 09:03:43 p.m.] (Msg) Got SDR network config.  Loaded revision 318 OK
[01/05/2021 09:03:43 p.m.] (Warning) SDR network config fetch first attempt failed.  HTTP 504.  .  Trying again.
[01/05/2021 09:03:26 p.m.] Attempting to open ALC device "OpenAL Soft on Altavoces (Realtek High Definition Audio)"
[01/05/2021 09:03:25 p.m.] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[01/05/2021 09:03:24 p.m.] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[01/05/2021 09:03:22 p.m.] Logged in as ShadowFMCzZ (SteamID STEAM_1:0:92038900)

**Comment by Regalis11** [comment]
The error message seems to indicate that there were several corrupted item XML files which failed to load. I'm afraid there's probably no way for us to know how they got corrupted (failing to update the game, a mod messing up the game files, accidental modifications to the game files...?), so I'll close this one.
