### ISSUE TITLE
Error in the console ("a locked connection was selected")

### ISSUE THREAD

**Issue by muskaeragon** [Regalis11/Barotrauma#5949]
What is it? I don`t know what the problem.
![image](https://user-images.githubusercontent.com/15955108/120322212-5d777380-c30e-11eb-8a2f-9b55e92bb800.png)

**Comment by Regalis11** [comment]
This error happens if the game tries to select a connection between biomes that hasn't been unlocked yet. I'm not sure how exactly this can happen - would it be possible to give us some more details on what kind of a situation it happened in? What mods were you using? Had you completed the event that unlocks the path to the next biome (or were there any in the outpost)?

**Comment by muskaeragon** [comment]
We came to the transition on the assembly of modifications and some players had this error. In the modification, we increased the campaign map and it is possible that some outposts appeared behind the transition and the game thought that we had already passed to the next location.

**Comment by muskaeragon** [comment]
We ourselves were at an outpost that was before crossing into the great sea, and we had not yet discovered the location, but the reputation was enough to do it.

**Comment by Wheatley1001** [comment]
This issue occurred on 100.6.0.0. Here's the error log:

A locked connection was selected - this should not be possible.
   at System.Environment.get_StackTrace()
   at Barotrauma.Map.SelectLocation(Int32 index) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Map\Map.cs:line 1051
   at Barotrauma.MultiPlayerCampaign.ClientRead(IReadMessage msg) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameSession\GameModes\MultiPlayerCampaign.cs:line 609
   at Barotrauma.Networking.GameClient.<ReadLobbyUpdate>b__113_0(ServerNetSegment segment, IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 2012
   at Barotrauma.Networking.SegmentTableReader`1.Read(IReadMessage msg, SegmentDataReader segmentDataReader, ExceptionHandler exceptionHandler) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SegmentTable.cs:line 302
   at Barotrauma.Networking.GameClient.ReadDataMessage(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 626
   at Barotrauma.Networking.SteamP2PClientPeer.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\Primitives\Peers\SteamP2PClientPeer.cs:line 260
   at Barotrauma.Networking.GameClient.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 483
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 886
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 651
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

**Comment by Regalis11** [comment]
I think I finally found a way to reproduce this (with the help of a manually modified save file):

[se4g6f5.zip](https://github.com/Regalis11/Barotrauma/files/10428542/se4g6f5.zip)

Steps to repro:
1. Use the multiplayer save above 
2. Teleport to Phineus Linea (the location before the gate outpost)
3. Travel to the end of the level and dock

**Comment by 3e849f2e5c** [comment]
Tested, no trace of the bug found
