### ISSUE TITLE
(Unstable) Object reference not set to an instance of an object when selecting upgrade weapons at outpost

### ISSUE THREAD

**Issue by Drkriegerr** [Regalis11/Barotrauma#6004]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void CreateSwappableItemSlideDown(Barotrauma.GUIListBox, Int32, Barotrauma.Item, Barotrauma.Submarine)
Full crash report in additional information.

**Steps To Reproduce**
Hosted multiplayer campaign alone, custom sub with one hardpoint. Anytime I go to sub upgrade and click weapons I get this crash report.

**Version**
Game version 0.1400.3.0 (ReleaseWindows, branch release, revision 2006eac9ac)

**Additional information**
B72D3E5111987CA8905A40866FF4274D

Game version 0.1400.3.0 (ReleaseWindows, branch release, revision 2006eac9ac)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync OFF
Language: English
Selected content packages: Vanilla 0.9, Shipwrecks Extended, Underwater Sledge, T.I.T.A.N. power suit, [ENV] Beacons Extended, Seated Operators, Malborasek with Sound, MoreHeadgear, TC Instruments, OxyGear, Jukebox, Waistpack, Thalassophobia, TC Meme Horns, TC Guns, TC Fortunate son speaker, More Alarm Sounds, Meaningful CPR, BetterGlass, EK Gunnery, EK Utilities, EK Armory, EK Dockyard
Level seed: Sermilik
Loaded submarine: 1TUnstable (48035BF0576F39D5C066DCAEB7D805E0)
Selected screen: Barotrauma.GameScreen
SteamManager initialized
Client (Round had started)

System info:
    Operating system: Microsoft Windows NT 10.0.19041.0 64 bit
    GPU name: NVIDIA GeForce GTX 1080
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void CreateSwappableItemSlideDown(Barotrauma.GUIListBox, Int32, Barotrauma.Item, Barotrauma.Submarine)
Stack trace: 
   at Barotrauma.UpgradeStore.CreateSwappableItemSlideDown(GUIListBox parent, Int32 slotIndex, Item item, Submarine submarine) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\UpgradeStore.cs:line 869
   at Barotrauma.UpgradeStore.CreateSwappableItemList(GUIListBox parent, UpgradeCategory category, Submarine submarine) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\UpgradeStore.cs:line 825
   at Barotrauma.UpgradeStore.<>c__DisplayClass45_0.<SelectUpgradeCategory>b__2(GUIButton <p0>, Object <p1>) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\UpgradeStore.cs:line 792
   at Barotrauma.UpgradeStore.<CreateUpgradeTab>b__41_0(GUIComponent component, Object userData) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\UpgradeStore.cs:line 703
   at Barotrauma.GUIListBox.Select(Int32 childIndex, Boolean force, Boolean autoScroll, Boolean takeKeyBoardFocus) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIListBox.cs:line 841
   at Barotrauma.GUIListBox.SelectNext(Boolean force, Boolean autoScroll, Boolean takeKeyBoardFocus) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIListBox.cs:line 793
   at Barotrauma.GUIListBox.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIListBox.cs:line 762
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Barotrauma.GUI.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1250
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 986
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[6/9/2021 9:42:56 AM] WARNING: Received a potentially invalid ENTITY_POSITION message. Entity type does not match (server entity is not an item, client entity is Barotrauma.Item). Ignoring the message...
[6/9/2021 9:42:56 AM] WARNING: Received a potentially invalid ENTITY_POSITION message. Entity type does not match (server entity is not an item, client entity is Barotrauma.Item). Ignoring the message...
[6/9/2021 9:42:56 AM] WARNING: Received a potentially invalid ENTITY_POSITION message. Entity type does not match (server entity is not an item, client entity is Barotrauma.Item). Ignoring the message...
[6/9/2021 9:42:56 AM] WARNING: Received a potentially invalid ENTITY_POSITION message. Entity type does not match (server entity is not an item, client entity is Barotrauma.Item). Ignoring the message...
[6/9/2021 9:42:55 AM] WARNING: Received a potentially invalid ENTITY_POSITION message. Entity type does not match (server entity is not an item, client entity is Barotrauma.Item). Ignoring the message...
[6/9/2021 9:42:55 AM] WARNING: Received a potentially invalid ENTITY_POSITION message. Entity type does not match (server entity is not an item, client entity is Barotrauma.Item). Ignoring the message...
[6/9/2021 9:42:55 AM] WARNING: Received a potentially invalid ENTITY_POSITION message. Entity type does not match (server entity is not an item, client entity is Barotrauma.Item). Ignoring the message...
[6/9/2021 9:42:55 AM] WARNING: Received a potentially invalid ENTITY_POSITION message. Entity type does not match (server entity is not an item, client entity is Barotrauma.Item). Ignoring the message...
[6/9/2021 9:42:55 AM] WARNING: Received a potentially invalid ENTITY_POSITION message. Entity type does not match (server entity is not an item, client entity is Barotrauma.Item). Ignoring the message...
[6/9/2021 9:42:55 AM] WARNING: Received a potentially invalid ENTITY_POSITION message. Entity type does not match (server entity is not an item, client entity is Barotrauma.Item). Ignoring the message...
[6/9/2021 9:42:55 AM] WARNING: Received a potentially invalid ENTITY_POSITION message. Entity type does not match (server entity is not an item, client entity is Barotrauma.Item). Ignoring the message...
[6/9/2021 9:42:55 AM] WARNING: Received a potentially invalid ENTITY_POSITION message. Entity type does not match (server entity is not an item, client entity is Barotrauma.Item). Ignoring the message...
[6/9/2021 9:42:55 AM] WARNING: Received a potentially invalid ENTITY_POSITION message. Entity type does not match (server entity is not an item, client entity is Barotrauma.Item). Ignoring the message...
[6/9/2021 9:42:55 AM] Kriegerr
[6/9/2021 9:42:55 AM] WARNING: Received a potentially invalid ENTITY_POSITION message. Entity type does not match (server entity is not an item, client entity is Barotrauma.Item). Ignoring the message...
[6/9/2021 9:42:55 AM] WARNING: Received a potentially invalid ENTITY_POSITION message. Entity type does not match (server entity is not an item, client entity is Barotrauma.Item). Ignoring the message...
[6/9/2021 9:42:55 AM] WARNING: Received a potentially invalid ENTITY_POSITION message. Entity type does not match (server entity is not an item, client entity is Barotrauma.Item). Ignoring the message...
[6/9/2021 9:42:55 AM] WARNING: Received a potentially invalid ENTITY_POSITION message. Entity type does not match (server entity is not an item, client entity is Barotrauma.Item). Ignoring the message...
[6/9/2021 9:42:55 AM] WARNING: Received a potentially invalid ENTITY_POSITION message. Entity type does not match (server entity is not an item, client entity is Barotrauma.Item). Ignoring the message...
[6/9/2021 9:42:55 AM] WARNING: Received a potentially invalid ENTITY_POSITION message. Entity type does not match (server entity is not an item, client entity is Barotrauma.Item). Ignoring the message...
[6/9/2021 9:42:55 AM] WARNING: Received a potentially invalid ENTITY_POSITION message. Entity type does not match (server entity is not an item, client entity is Barotrauma.Item). Ignoring the message...
[6/9/2021 9:42:55 AM] WARNING: Received a potentially invalid ENTITY_POSITION message. Entity type does not match (server entity is not an item, client entity is Barotrauma.Item). Ignoring the message...
[6/9/2021 9:42:52 AM] Task count: 0
[6/9/2021 9:42:49 AM] Generating an outpost for the start of the level... (Location: Sermilik Station, level type: Outpost)
[6/9/2021 9:42:19 AM] Lobby created!
[6/9/2021 9:42:04 AM] Loading additional location types from file 'Mods/Thalassophobia/Map/locationtypes.xml'
[6/9/2021 9:41:56 AM] (Msg) SDR RelayNetworkStatus:  avail=OK  config=OK  anyrelay=OK   (OK)
[6/9/2021 9:41:56 AM] (Msg) Ping location: ord=21+2,iad=26+2,atl=39+3/39+2,dfw=46+4/42+2,lax=75+7/67+2,eat=/69+6,sea=69+6/71+2,par=105+10/102+2,lhr=104+10/110+2,fra=115+11/111+2,gru=170+17/170+2,sgp=239+23/244+16
[6/9/2021 9:41:56 AM] (Msg) Ping measurement completed
[6/9/2021 9:41:56 AM] (Debug) Destroying relay 'sof#5 (139.45.193.10:27019)' because initial_ping_timeout
[6/9/2021 9:41:56 AM] (Debug) Destroying relay 'syd#90 (103.10.125.154:27050)' because initial_ping_timeout
[6/9/2021 9:41:56 AM] (Debug) Destroying relay 'eat#74 (155.133.235.34:27050)' because initial_ping_timeout
[6/9/2021 9:41:54 AM] Overriding the CPR settings with 'Mods/Meaningful CPR/Overwrite_Afflictions.xml'
[6/9/2021 9:41:54 AM] Overriding an affliction or a buff with the identifier 'thal_scan' using the file 'Mods/Thalassophobia/GeneAfflictions.xml'
[6/9/2021 9:41:53 AM] (Verbose) Communications with routing cluster 'sto2' established.
[6/9/2021 9:41:53 AM] (Debug) Destroying relay 'syd#57 (103.10.125.154:27017)' because initial_ping_timeout
[6/9/2021 9:41:53 AM] (Debug) Destroying relay 'sto2#8 (155.133.252.35:27022)' because initial_ping_timeout
[6/9/2021 9:41:53 AM] (Debug) Destroying relay 'sof#4 (139.45.193.10:27018)' because initial_ping_timeout
[6/9/2021 9:41:53 AM] (Debug) Destroying relay 'eat#22 (155.133.235.18:27036)' because initial_ping_timeout
[6/9/2021 9:41:51 AM] (Verbose) Communications with routing cluster 'sgp' established.
[6/9/2021 9:41:51 AM] (Verbose) Communications with routing cluster 'jnb' established.
[6/9/2021 9:41:51 AM] (Verbose) Communications with routing cluster 'tyo1' established.
[6/9/2021 9:41:51 AM] (Verbose) Communications with routing cluster 'tyo' established.
[6/9/2021 9:41:51 AM] (Verbose) Communications with routing cluster 'maa' established.
[6/9/2021 9:41:51 AM] (Verbose) Communications with routing cluster 'waw' established.
[6/9/2021 9:41:51 AM] (Verbose) Communications with routing cluster 'vie' established.
[6/9/2021 9:41:51 AM] (Verbose) Communications with routing cluster 'sto' established.
[6/9/2021 9:41:51 AM] (Verbose) Communications with routing cluster 'lim' established.
[6/9/2021 9:41:51 AM] (Verbose) Communications with routing cluster 'sea' established.
[6/9/2021 9:41:51 AM] (Verbose) Communications with routing cluster 'scl' established.
[6/9/2021 9:41:51 AM] (Verbose) Communications with routing cluster 'bom' established.
[6/9/2021 9:41:51 AM] (Verbose) Communications with routing cluster 'mad' established.
[6/9/2021 9:41:51 AM] (Verbose) Communications with routing cluster 'dxb' established.
[6/9/2021 9:41:51 AM] (Verbose) Communications with routing cluster 'hkg' established.
[6/9/2021 9:41:51 AM] (Verbose) Communications with routing cluster 'par' established.
[6/9/2021 9:41:51 AM] (Verbose) Communications with routing cluster 'lhr' established.
[6/9/2021 9:41:51 AM] (Verbose) Communications with routing cluster 'eze' established.
[6/9/2021 9:41:51 AM] (Verbose) Communications with routing cluster 'lax' established.
[6/9/2021 9:41:51 AM] (Verbose) Communications with routing cluster 'gru' established.
[6/9/2021 9:41:51 AM] (Verbose) Communications with routing cluster 'ord' established.
[6/9/2021 9:41:51 AM] (Verbose) Communications with routing cluster 'fra' established.
[6/9/2021 9:41:51 AM] (Verbose) Communications with routing cluster 'iad' established.
[6/9/2021 9:41:50 AM] (Verbose) Communications with routing cluster 'ams' established.
[6/9/2021 9:41:50 AM] (Verbose) Communications with routing cluster 'dfw' established.
[6/9/2021 9:41:50 AM] (Verbose) Communications with routing cluster 'atl' established.
[6/9/2021 9:41:50 AM] (Msg) SDR RelayNetworkStatus:  avail=Attempting  config=OK  anyrelay=Attempting   (Performing ping measurement)

**Comment by Drkriegerr** [comment]
Just tested it on a sub with no hardpoints at all and got the same result.

**Comment by Drkriegerr** [comment]
Issue persists in latest Unstable version: Game version 0.14.4.0 (ReleaseWindows, branch release, revision 6d9bbbe023)

F61068170A890989ED8FC8FF2C63FDB7


Game version 0.14.4.0 (ReleaseWindows, branch release, revision 6d9bbbe023)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync OFF
Language: English
Selected content packages: Vanilla 0.9, Underwater Sledge, T.I.T.A.N. power suit, [ENV] Beacons Extended, Seated Operators, Malborasek with Sound, MoreHeadgear, TC Instruments, OxyGear, Jukebox, Waistpack, Thalassophobia, TC Meme Horns, TC Guns, TC Fortunate son speaker, More Alarm Sounds, Meaningful Upgrades, Meaningful CPR, BetterGlass, EK Gunnery, EK Utilities, EK Armory, EK Dockyard
Level seed: Sermilik
Loaded submarine: 1TUnstable (E9A05A9EFDCC93F7C1C2714B3BD1B1CB)
Selected screen: Barotrauma.GameScreen
SteamManager initialized
Client (Round had started)


System info:
    Operating system: Microsoft Windows NT 10.0.19041.0 64 bit
    GPU name: NVIDIA GeForce GTX 1080
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal


Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void CreateSwappableItemSlideDown(Barotrauma.GUIListBox, Int32, Barotrauma.Item, Barotrauma.Submarine)
Stack trace: 
   at Barotrauma.UpgradeStore.CreateSwappableItemSlideDown(GUIListBox parent, Int32 slotIndex, Item item, Submarine submarine) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\UpgradeStore.cs:line 875
   at Barotrauma.UpgradeStore.CreateSwappableItemList(GUIListBox parent, UpgradeCategory category, Submarine submarine) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\UpgradeStore.cs:line 831
   at Barotrauma.UpgradeStore.<>c__DisplayClass45_0.<SelectUpgradeCategory>b__2(GUIButton <p0>, Object <p1>) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\UpgradeStore.cs:line 798
   at Barotrauma.UpgradeStore.<CreateUpgradeTab>b__41_0(GUIComponent component, Object userData) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\UpgradeStore.cs:line 709
   at Barotrauma.GUIListBox.Select(Int32 childIndex, Boolean force, Boolean autoScroll, Boolean takeKeyBoardFocus) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIListBox.cs:line 830
   at Barotrauma.GUIListBox.SelectNext(Boolean force, Boolean autoScroll, Boolean takeKeyBoardFocus) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIListBox.cs:line 792
   at Barotrauma.GUIListBox.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIListBox.cs:line 768
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Barotrauma.GUI.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1250
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 986
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58


Last debug messages:
[6/9/2021 11:21:54 AM] Kriegerr
[6/9/2021 11:21:51 AM] Task count: 0
[6/9/2021 11:21:48 AM] Generating an outpost for the start of the level... (Location: The city of Sermilik, level type: Outpost)
[6/9/2021 11:21:14 AM] Lobby created!
[6/9/2021 11:17:01 AM] Loading additional location types from file 'Mods/Thalassophobia/Map/locationtypes.xml'
[6/9/2021 11:16:54 AM] (Msg) SDR RelayNetworkStatus:  avail=OK  config=OK  anyrelay=OK   (OK)
[6/9/2021 11:16:54 AM] (Msg) Ping location: ord=20+2,iad=37+3,atl=40+4/38+2,dfw=48+4/41+2,lax=76+7/66+2,sea=69+6/68+2,eat=/72+2,lhr=103+10,par=105+10,fra=116+11/117+2,gru=163+16/169+2,sgp=250+25/243+16
[6/9/2021 11:16:54 AM] (Msg) Ping measurement completed
[6/9/2021 11:16:54 AM] (Debug) Destroying relay 'sof#4 (139.45.193.10:27018)' because initial_ping_timeout
[6/9/2021 11:16:54 AM] (Debug) Destroying relay 'syd#89 (103.10.125.154:27049)' because initial_ping_timeout
[6/9/2021 11:16:53 AM] (Debug) Destroying relay 'eat#25 (155.133.235.18:27039)' because initial_ping_timeout
[6/9/2021 11:16:52 AM] Overriding the CPR settings with 'Mods/Meaningful CPR/Overwrite_Afflictions.xml'
[6/9/2021 11:16:52 AM] Overriding an affliction or a buff with the identifier 'thal_scan' using the file 'Mods/Thalassophobia/GeneAfflictions.xml'
[6/9/2021 11:16:51 AM] (Debug) Destroying relay 'syd#101 (103.10.125.154:27061)' because initial_ping_timeout
[6/9/2021 11:16:51 AM] (Debug) Destroying relay 'sof#2 (139.45.193.10:27016)' because initial_ping_timeout
[6/9/2021 11:16:51 AM] (Debug) Destroying relay 'eat#48 (155.133.235.34:27024)' because initial_ping_timeout
[6/9/2021 11:16:49 AM] (Verbose) Communications with routing cluster 'sgp' established.
[6/9/2021 11:16:49 AM] (Verbose) Communications with routing cluster 'tyo1' established.
[6/9/2021 11:16:49 AM] (Verbose) Communications with routing cluster 'jnb' established.
[6/9/2021 11:16:49 AM] (Verbose) Communications with routing cluster 'tyo' established.
[6/9/2021 11:16:49 AM] (Verbose) Communications with routing cluster 'maa' established.
[6/9/2021 11:16:49 AM] (Verbose) Communications with routing cluster 'waw' established.
[6/9/2021 11:16:49 AM] (Verbose) Communications with routing cluster 'vie' established.
[6/9/2021 11:16:49 AM] (Verbose) Communications with routing cluster 'sto2' established.
[6/9/2021 11:16:49 AM] (Verbose) Communications with routing cluster 'sto' established.
[6/9/2021 11:16:49 AM] (Verbose) Communications with routing cluster 'lim' established.
[6/9/2021 11:16:49 AM] (Verbose) Communications with routing cluster 'sea' established.
[6/9/2021 11:16:49 AM] (Verbose) Communications with routing cluster 'scl' established.
[6/9/2021 11:16:48 AM] (Verbose) Communications with routing cluster 'mad' established.
[6/9/2021 11:16:48 AM] (Verbose) Communications with routing cluster 'bom' established.
[6/9/2021 11:16:48 AM] (Verbose) Communications with routing cluster 'hkg' established.
[6/9/2021 11:16:48 AM] (Verbose) Communications with routing cluster 'dxb' established.
[6/9/2021 11:16:48 AM] (Verbose) Communications with routing cluster 'par' established.
[6/9/2021 11:16:48 AM] (Verbose) Communications with routing cluster 'lhr' established.
[6/9/2021 11:16:48 AM] (Verbose) Communications with routing cluster 'eze' established.
[6/9/2021 11:16:48 AM] (Verbose) Communications with routing cluster 'lax' established.
[6/9/2021 11:16:48 AM] (Verbose) Communications with routing cluster 'gru' established.
[6/9/2021 11:16:48 AM] (Verbose) Communications with routing cluster 'iad' established.
[6/9/2021 11:16:48 AM] (Verbose) Communications with routing cluster 'ord' established.
[6/9/2021 11:16:48 AM] (Verbose) Communications with routing cluster 'fra' established.
[6/9/2021 11:16:48 AM] (Verbose) Communications with routing cluster 'ams' established.
[6/9/2021 11:16:48 AM] (Verbose) Communications with routing cluster 'dfw' established.
[6/9/2021 11:16:48 AM] (Verbose) Communications with routing cluster 'atl' established.
[6/9/2021 11:16:48 AM] (Msg) SDR RelayNetworkStatus:  avail=Attempting  config=OK  anyrelay=Attempting   (Performing ping measurement)
[6/9/2021 11:16:48 AM] (Msg) Performing ping measurement
[6/9/2021 11:16:48 AM] (Msg) Got SDR network config.  Loaded revision 319 OK
[6/9/2021 11:16:48 AM] (Warning) SDR network config fetch first attempt failed.  HTTP 504.  .  Trying again.
[6/9/2021 11:16:42 AM] Attempting to open ALC device "OpenAL Soft on Headset Earphone (Corsair VOID PRO Wireless Gaming Headset)"
[6/9/2021 11:16:41 AM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[6/9/2021 11:16:41 AM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[6/9/2021 11:16:40 AM] Logged in as Dr Krieger

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e5783134e6044660b6f48ad13ff6e26883ee69cc

**Comment by Rokvach** [comment]
Testsed, working correctly. Closing.
