### ISSUE TITLE
Console error ("Failed to read event for entity "Pirate Captain"")

### ISSUE THREAD

**Issue by mortifia** [Regalis11/Barotrauma#6048]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
chaingun to pirate sub
-> end of ammo
-->
```
Failed to read event for entity "Pirate Captain"! {The given key 'navigatetactical' was not present in the dictionary.}
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Barotrauma.CrewManager.CreateOrderTooltip(Order orderPrefab, String option, Entity targetEntity) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameSession\CrewManager.cs:line 1068
   at Barotrauma.CrewManager.GetObjectiveIconTooltip(String identifier, String option, Entity targetEntity) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameSession\CrewManager.cs:line 1726
   at Barotrauma.CrewManager.CreateObjectiveIcon(Character character, String identifier, String option, Entity targetEntity) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameSession\CrewManager.cs:line 1702
   at Barotrauma.Character.ClientRead(ServerNetObject type, IReadMessage msg, Single sendingTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Characters\CharacterNetworking.cs:line 429
   at Barotrauma.Networking.ClientEntityEventManager.Read(ServerNetObject type, IReadMessage msg, Single sendingTime, List`1 entities) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\NetEntityEvent\ClientEntityEventManager.cs:line 239
```

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
Which version of the game did the bug happen in. Also, please include the operating system you're using (Windows/Linux/Mac).

**Additional information**

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ff6f7eaee4f74fd75514a334bfddb5658bcd4a16

**Comment by Rokvach** [comment]
There hasn't been any sightings to this, seems to be working correctly. Closing.
