### ISSUE TITLE
[Unstable] Unable to load campaign after crashing changing maps

### ISSUE THREAD

**Issue by Drkriegerr** [Regalis11/Barotrauma#6052]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Loading from one hunting grounds mission to another, crashed and now Im unable to load saved game on single player. I saw similar issues but stack trace was different so here is my crash log, and current error when I attempt to Load.

**Steps To Reproduce**
Attempt to load saved game: https://cdn.discordapp.com/attachments/825244526305869837/853440517693243422/Save_234.save

**Version**
Game version 0.14.4.0 (ReleaseWindows, branch release, revision 6d9bbbe023)
**Additional information**
Error when attempting to load :
![image](https://user-images.githubusercontent.com/85597359/121792435-9c38e380-cbc2-11eb-88b1-803fa5e23f2a.png)

Crash Report:

F61068170A890989ED8FC8FF2C63FDB7

Game version 0.14.4.0 (ReleaseWindows, branch release, revision 6d9bbbe023)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync OFF
Language: English
Selected content packages: Vanilla 0.9, New Wrecks For Barotrauma, XanRobots, Underwater Sledge, T.I.T.A.N. power suit, Seated Operators, Malborasek with Sound, MoreHeadgear, OxyGear, Jukebox, Waistpack, TC Guns, TC Fortunate son speaker, TransparentDivingHelmet, Meaningful CPR, BetterGlass, Thalassophobia, EK Armory, EK Utilities, EK Gunnery, EK Dockyard, Meaningful Upgrades, [ENV] Beacons Extended
Level seed: Sidon FlexusAlkonost
Loaded submarine: 1TUnstable (B0A7821BAC7F25544A85DD78BBC02F7A)
Selected screen: Barotrauma.RoundSummaryScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19041.0 64 bit
    GPU name: NVIDIA GeForce GTX 1080
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void .ctor(Barotrauma.Submarine)
Stack trace: 
   at Barotrauma.WreckAI..ctor(Submarine wreck) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\Wreck\WreckAI.cs:line 20
   at Barotrauma.Submarine.CreateWreckAI() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Submarine.cs:line 377
   at Barotrauma.Level.SpawnSubOnPath(String subName, ContentFile contentFile, SubmarineType type) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Levels\Level.cs:line 3115
   at Barotrauma.Level.CreateWrecks() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Levels\Level.cs:line 3366
   at Barotrauma.Level.Generate(Boolean mirror) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Levels\Level.cs:line 1156
   at Barotrauma.Level.Generate(LevelData levelData, Boolean mirror, SubmarineInfo startOutpost, SubmarineInfo endOutpost) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Levels\Level.cs:line 386
   at Barotrauma.GameSession.StartRound(LevelData levelData, Boolean mirrorLevel, SubmarineInfo startOutpost, SubmarineInfo endOutpost) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameSession.cs:line 398
   at Barotrauma.CampaignMode.<>c__DisplayClass26_0.<<SelectSummaryScreen>b__0>d.MoveNext() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameSession\GameModes\CampaignMode.cs:line 265
--- End of stack trace from previous location where exception was thrown ---
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 962
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/41c333db

**Comment by Rokvach** [comment]
Tested, I was able to load up the save without any issues, seems to be working correctly. Closing.
