### ISSUE TITLE
Crash: Collection was modified after the enumerator was instantiated. (System.InvalidOperationException)

### ISSUE THREAD

**Issue by Konfuz** [Regalis11/Barotrauma#6111]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Crash on first startup after update

**Steps To Reproduce**
I was not able to reproduce the crash. It was the first start after game-update and I was tabbed out of the game during startup. I got several mods installed. 

**Version**
Linux 0.14.6.0

**Additional information**

```
Exception: Collection was modified after the enumerator was instantiated. (System.InvalidOperationException)
Target site: Boolean MoveNext()
Stack trace: 
   at System.Collections.Generic.HashSet`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Barotrauma.Sounds.SoundBuffers.RequestAlBuffers() in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Sounds/SoundBuffer.cs:line 69
   at Barotrauma.Sounds.OggSound.InitializeALBuffers() in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Sounds/OggSound.cs:line 69
   at Barotrauma.Sounds.Sound..ctor(SoundManager owner, String filename, Boolean stream, Boolean streamsReliably, XElement xElement, Boolean getFullPath) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Sounds/Sound.cs:line 75
   at Barotrauma.Sounds.OggSound..ctor(SoundManager owner, String filename, Boolean stream, XElement xElement) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Sounds/OggSound.cs:line 19
   at Barotrauma.Sounds.SoundManager.LoadSound(String filename, Boolean stream) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Sounds/SoundManager.cs:line 346
   at Barotrauma.Submarine.LoadRoundSound(XElement element, Boolean stream) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Map/Submarine.cs:line 119
   at Barotrauma.StatusEffect.InitProjSpecific(XElement element, String parentDebugName) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/StatusEffects/StatusEffect.cs:line 38
   at Barotrauma.StatusEffect..ctor(XElement element, String parentDebugName) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/StatusEffects/StatusEffect.cs:line 632
   at Barotrauma.StatusEffect.Load(XElement element, String parentDebugName) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/StatusEffects/StatusEffect.cs:line 347
   at Barotrauma.AfflictionPrefab.PeriodicEffect..ctor(XElement element, String parentDebugName) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/Health/Afflictions/AfflictionPrefab.cs:line 218
   at Barotrauma.AfflictionPrefab.LoadEffects(XElement element) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/Health/Afflictions/AfflictionPrefab.cs:line 650
   at Barotrauma.AfflictionPrefab.LoadFromFile(ContentFile file) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/Health/Afflictions/AfflictionPrefab.cs:line 542
   at Barotrauma.AfflictionPrefab.LoadAll(IEnumerable`1 files) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/Health/Afflictions/AfflictionPrefab.cs:line 370
   at Barotrauma.GameSettings.RefreshContentPackageItems(IEnumerable`1 files) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/GameSettings.cs:line 615
   at Barotrauma.GameSettings.EnableRegularPackage(ContentPackage contentPackage) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/GameSettings.cs:line 441
   at Barotrauma.Steam.SteamManager.<>c__DisplayClass43_0.<InstallWorkshopItem>b__2(Task task, ContentPackage cp) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Networking/SteamManager.cs:line 1128
   at Barotrauma.TaskPool.<>c__DisplayClass7_0`1.<Add>b__0(Task t, Object obj) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Utils/TaskPool.cs:line 65
   at Barotrauma.TaskPool.Update() in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Utils/TaskPool.cs:line 77
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/GameMain.cs:line 995
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/SDL/SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Program.cs:line 59
```

**Comment by Regalis11** [comment]
I couldn't find a way to reproduce this, but I added some measures in https://github.com/Regalis11/Barotrauma-development/commit/84fc71d1f36dd2b1943994ae00ce91d97e0eca9b that I think should prevent this crash.

**Comment by Konfuz** [comment]
Thanks, I also noticed that the mod EK Armory does not load correctly anymore. (No error on loading the mod, but It wont find any Items defined by it) May or may not be related. 

Is there some kind of nightly linux build I can try - or do I have to compile myself to test the dev-version?

**Comment by Rokvach** [comment]
No known steps to reproduce, I will keep this open until the end of the Unstable testing period and see if anyone happens to encounter it.

**Comment by Rokvach** [comment]
As there's no known steps to reproduce this and no encounters to this issue during the Unstable testing period, I will be closing this ticket. This ticket can be opened again if the issue resurfaces. Closing.
