### ISSUE TITLE
[Crash] Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#6128]
- [x ] I have searched the issue tracker to check if the issue has already been reported. More or less.

**Description**
Desync event. Game crashed on loading after docking. Friend claims the crash occured when a station random event appeared.
```
Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void Draw(Microsoft.Xna.Framework.Graphics.SpriteBatch, Barotrauma.Character, Barotrauma.Camera)
Stack trace: 
   at Barotrauma.CharacterHUD.Draw(SpriteBatch spriteBatch, Character character, Camera cam) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Characters\CharacterHUD.cs:line 394
   at Barotrauma.GameScreen.Draw(Double deltaTime, GraphicsDevice graphics, SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\GameScreen.cs:line 130
   at Barotrauma.GameMain.Draw(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 1038
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 669
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 508
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58
```

**Steps To Reproduce**
n/a

**Version**
14.6.0 Windows Steam

**Additional information**
May or may not be related to the random event when some person is broadcasting on the station or to random events in general.
[crashreport (5).log](https://github.com/Regalis11/Barotrauma/files/6682283/crashreport.5.log)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/0e3f2186b9ca9ed771a6957f04aa780e3a6c43a5

**Comment by Rokvach** [comment]
No known steps to reproduce, I will keep this open until the end of the Unstable testing period and see if anyone happens to encounter it.

**Comment by Rokvach** [comment]
As there's no known steps to reproduce this and no encounters to this issue during the Unstable testing period, I will be closing this ticket. This ticket can be opened again if the issue resurfaces. Closing.
