### ISSUE TITLE
[Crash] Sequence contains no elements (System.InvalidOperationException)

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#6130]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The game crashed the moment I tried to take an item from a cabinet into my inventory. The item was from the mod Afflictions+
```
Exception: Sequence contains no elements (System.InvalidOperationException)
Target site: Void ThrowNoElementsException()
Stack trace: 
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Barotrauma.CharacterInventory.TryPutItemWithAutoEquipCheck(Item item, Character user, IEnumerable`1 allowedSlots, Boolean createNetworkEvent) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\CharacterInventory.cs:line 244
   at Barotrauma.CharacterInventory.QuickUseItem(Item item, Boolean allowEquip, Boolean allowInventorySwap, Boolean allowApplyTreatment, Nullable`1 action, Boolean playSound) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\CharacterInventory.cs:line 1068
   at Barotrauma.CharacterInventory.Update(Single deltaTime, Camera cam, Boolean isSubInventory) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\CharacterInventory.cs:line 638
   at Barotrauma.CharacterHUD.Update(Single deltaTime, Character character, Camera cam) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Characters\CharacterHUD.cs:line 180
   at Barotrauma.Character.UpdateControlled(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Characters\Character.cs:line 358
   at Barotrauma.Character.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 2688
   at Barotrauma.Character.UpdateAll(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 2572
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 212
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 962
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59
```

**Steps To Reproduce**
Unknown

**Version**
14.6.0 Windows Steam

**Additional information**
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/6682806/crashreport.log)

**Comment by Krzeszny** [comment]
[crashreport (2).log](https://github.com/Regalis11/Barotrauma/files/6682905/crashreport.2.log)
Secone one, same reason

**Comment by Regalis11** [comment]
This seems to happen when trying to pick up an item that can't be put into an inventory slot from a container. Can be reproduce for example by changing `slots="Any,RightHand,LeftHand"` in the bandage config to something like `slots="none"` and trying to pick up one from a cabinet.

Fixed in https://github.com/Regalis11/Barotrauma-development/commit/69f239867f7219cf1c7a64e14ee735e48785df8b

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
