### ISSUE TITLE
ballastfloratoxins error {ID taken by diving suit}

### ISSUE THREAD

**Issue by Botino123** [Regalis11/Barotrauma#6234]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
~2 minutes after docking with ballast flora and trying to remove it with plasma cutters the game breaks, my whole inventory was dropped and I could not pick up any items, I could still see other players moving around and doing stuff but they could not interact with anything either. The host could not walk out of a room due to rubber banding back inside as if the door was closed and only open on his client. The host also couldn't exit to lobby, nothing happened when clicking the button. The only way to fix it was to exit to main menu and restart the server. The console also printed an error for all three players on the server(See additional information below for the error). This happens every time we start the server, and it does not seem to be possible to continue playing on the savefile.

**Steps To Reproduce**
go on a mission in European ridge; get ballast flora, dock with an outpost, destroy the flora with plasma cutters while having a diving suit equipped.

**Version**
Version: 0.14.6.0
Windows 10 (all three players)

**Additional information**
Multiplayer campaign, with 2 other people. Total 3 people.

ERROR MESSAGE:

Failed to spawn item ballastfloratoxins {ID 245 is taken by Diving Suit}
   at Barotrauma.Entity..ctor(Submarine submarine, UInt16 id) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Entity.cs:line 91
   at Barotrauma.MapEntity..ctor(MapEntityPrefab prefab, Submarine submarine, UInt16 id) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\MapEntity.cs:line 256
   at Barotrauma.Item..ctor(Rectangle newRect, ItemPrefab itemPrefab, Submarine submarine, Boolean callOnItemLoaded, UInt16 id) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 759
   at Barotrauma.Item..ctor(ItemPrefab itemPrefab, Vector2 position, Submarine submarine, UInt16 id) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 750
   at Barotrauma.Item.ReadSpawnData(IReadMessage msg, Boolean spawn) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Item.cs:line 1595

ALSO THERE WERE A LOT OF THESE ERRORS:
(but they did not seem to be the direct reason for the game breaking. the error above seems like the culprit):

![image](https://user-images.githubusercontent.com/47068311/124351739-6fde1900-dbfc-11eb-99c3-2dd79f58c7a7.png)

**Comment by Regalis11** [comment]
Thank you for the report! 
If you still have the save file, posting it here would help us a lot in diagnosing this. Do note that the save file needs to be .zipped first since GitHub doesn't allow attaching files with the .save file extension. Thanks and sorry for the inconvenience!
