### ISSUE TITLE
Disconnected between rounds (collection was modified in Submarine.GetCargoContainers)

### ISSUE THREAD

**Issue by Aurani** [Regalis11/Barotrauma#6237]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Playing MP campaign with 2 friends, one of them being the host, every time we complete a round and try load into a new location the client players will get dropped from the game about 50% of the time with a network based error.

**Steps To Reproduce**
Complete a round.
Load into new location.
Get D/C'd back to server lobby.

**Version**
Unstable, Windows 10

**Additional information**
Could not locate any log file containing the debug error messages so I've included a screencap. We do have a few mods enabled but none of the errors seem to point to a mod location.
<img width="749" alt="ErrorCap" src="https://user-images.githubusercontent.com/13284814/124361917-1b559080-dc32-11eb-850e-12a68141f943.png">

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/538164ed32170d44758705e1c4cc1866ece33018

**Comment by Rokvach** [comment]
Tested, this still seems to happen in the Unstable build

We were doing a single cargo mission and once we docked to the destination outpost client disconnected without a disconnection reason on the server side, they did receive a error on the console. 

```
Error while reading a message from server. {Exception has been thrown by the target of an invocation.}
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.ConstructorInfo.Invoke(Object[] parameters)
   at Barotrauma.MissionPrefab.Instantiate(Location[] locations, Submarine sub) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\Missions\MissionPrefab.cs:line 381
   at Barotrauma.Location.InstantiateLoadedMissions(Map map) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Map\Location.cs:line 636
   at Barotrauma.Map.LoadState(XElement element, Boolean showNotifications) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Map\Map.cs:line 1102
   at Barotrauma.MultiPlayerCampaign.Load(XElement element) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameModes\MultiPlayerCampaign.cs:line 146
   at Barotrauma.MultiPlayerCampaign.LoadState(String filePath) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameSession\GameModes\MultiPlayerCampaign.cs:line 906
   at Barotrauma.Networking.GameClient.OnFileReceived(FileTransferIn transfer) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 2629
   at Barotrauma.Networking.FileReceiver.ReadMessage(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\FileTransfer\FileReceiver.cs:line 379
   at Barotrauma.Networking.GameClient.ReadDataMessage(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 944
   at Barotrauma.Networking.SteamP2PClientPeer.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\Primitives\Peers\SteamP2PClientPeer.cs:line 243
   at Barotrauma.Networking.GameClient.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 632

Inner exception: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at Barotrauma.Submarine.GetCargoContainers() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Submarine.cs:line 1269
   at Barotrauma.CargoMission.DetermineCargo() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\Missions\CargoMission.cs:line 66
   at Barotrauma.CargoMission..ctor(MissionPrefab prefab, Location[] locations, Submarine sub) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\Missions\CargoMission.cs:line 54
Overriding an affliction or a buff with the identifier 'huskinfection' using the file 'Mods/Huskmod/Afflictions.xml'
Overriding all location types with 'Mods/REALLYBIGMAP/Map/RBM_locationTypes.xml'
Loading additional location types from file 'Mods/XanMonsters/Map/LocationTypes.xml'
Loading additional location types from file 'Mods/XanMonsters2/Map/LocationTypes.xml'
Overriding the map generation parameters with 'Mods/REALLYBIGMAP/Map/RBM_MapGen.xml'
Coroutine Barotrauma.Networking.GameClient+<StartGame>d__93 threw an exception: Object reference not set to an instance of an object.
   at Barotrauma.Networking.GameClient.StartGame(IReadMessage inc)+MoveNext() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 1617
   at Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 217
Coroutine MultiplayerCampaign.DoInitialCameraTransition threw an exception: Object reference not set to an instance of an object.
   at Barotrauma.MultiPlayerCampaign.DoInitialCameraTransition()+MoveNext() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameSession\GameModes\MultiPlayerCampaign.cs:line 198
   at Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 217
```

**Comment by Regalis11** [comment]
2nd attempt: https://github.com/Regalis11/Barotrauma-development/commit/b38e3624730888d4e55bf941089f38ef59530ef1

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
