### ISSUE TITLE
Crash on Start-Up (PresentationParameters.DeviceWindowHandle must not be null)

### ISSUE THREAD

**Issue by jrandalldemllo** [Regalis11/Barotrauma#6292]
First installation of the game. Have tried reinstalling, altering config between window modes, VSYNC on/off, updated to latest graphics. Tried lowering resolution and raising again. 
Crash log below.

---

Barotrauma Client crash report (generated on 11/07/2021 9:07:21 PM)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

EECA616DF2BA4F9511EEC52AB1F63877

Game version 0.14.6.0 (ReleaseWindows, branch release, revision 12d7084c07)
Graphics mode: 1920x1080 (Windowed)
VSync ON
Language: English
Selected content packages: Vanilla 0.9
Level seed: no level loaded
Loaded submarine: None
Selected screen: None
SteamManager initialized

System info:
      Operating system: Microsoft Windows NT 10.0.19042.0 64 bit
      GPU name: NVIDIA GeForce GTX 970
      Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
      GPU status: Normal

Exception: PresentationParameters.DeviceWindowHandle must not be null. (System.ArgumentException)
Target site: Void PlatformReset()
Stack trace: 
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformReset() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\GraphicsDevice.DirectX.cs:line 483
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.Reset() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\GraphicsDevice.cs:line 616
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.Reset(PresentationParameters presentationParameters) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\GraphicsDevice.cs:line 632
   at Microsoft.Xna.Framework.GraphicsDeviceManager.ApplyChanges() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\GraphicsDeviceManager.cs:line 328
   at Barotrauma.GameMain.SetWindowMode(WindowMode windowMode) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 306
   at Barotrauma.GameMain.ApplyGraphicsSettings() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 289
   at Barotrauma.GameMain.LoadContent() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 355
   at Microsoft.Xna.Framework.Game.Initialize() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 553
   at Barotrauma.GameMain.Initialize() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 334
   at Microsoft.Xna.Framework.Game.DoInitialize() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 685
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 382
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59

Last debug messages:
[11/07/2021 9:07:21 PM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[11/07/2021 9:07:20 PM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean

**Comment by Dregz** [comment]
Any luck solving this problem?

**Comment by jrandalldemllo** [comment]
As far as I remember I solved it through both/or either:
- Graphics driver clean install
- Windows OS clean install.

I feel as if it was the latter unfortunately.
