### ISSUE TITLE
Error while trying to create New Game,Start training..etc.

### ISSUE THREAD

**Issue by JeffJeffMain** [Regalis11/Barotrauma#6311]
Barotrauma Client crash report (generated on 7/14/2021 7:30:28 PM)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

EECA616DF2BA4F9511EEC52AB1F63877

Game version 0.14.6.0 (ReleaseWindows, branch release, revision 12d7084c07)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla 0.9
Level seed: no level loaded
Loaded submarine: None
Selected screen: Barotrauma.MainMenuScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19042.0 64 bit
    GPU name: NVIDIA GeForce GTX 1050
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: One or more errors occurred. (Access to the path 'C:\Users\pc\Desktop\Barotrauma\Data\hashcache.txt' is denied.) (System.AggregateException)
Target site: Void ThrowIfExceptional(Boolean)
Stack trace: 
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Barotrauma.SubmarineInfo.get_MD5Hash() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\SubmarineInfo.cs:line 118
   at Barotrauma.CampaignSetupUI.<>c__DisplayClass40_0.<.ctor>b__5(GUIButton btn, Object userData) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\CampaignSetupUI.cs:line 172
   at Barotrauma.GUIButton.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIButton.cs:line 262
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Barotrauma.GUI.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1250
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 986
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59

InnerException: Access to the path 'C:\Users\pc\Desktop\Barotrauma\Data\hashcache.txt' is denied.
Target site: Microsoft.Win32.SafeHandles.SafeFileHandle ValidateFileHandle(Microsoft.Win32.SafeHandles.SafeFileHandle)
Stack trace: 
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding)
   at System.IO.File.WriteAllLines(String path, IEnumerable`1 contents, Encoding encoding)
   at Barotrauma.Md5Hash.SaveCache() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Md5Hash.cs:line 70
   at Barotrauma.Md5Hash.SaveToCache(String filename, Nullable`1 time) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Md5Hash.cs:line 106
   at Barotrauma.Md5Hash..ctor(XDocument doc, String filename, Boolean tryLoadFromCache) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Md5Hash.cs:line 171
   at Barotrauma.SubmarineInfo.<>c__DisplayClass116_0.<StartHashDocTask>b__0() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\SubmarineInfo.cs:line 425
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
Last debug messages:
[7/14/2021 7:30:13 PM] (Msg) SDR RelayNetworkStatus:  avail=OK  config=OK  anyrelay=OK   (OK)
[7/14/2021 7:30:13 PM] (Msg) Ping location: vie=30+3,waw=63+6/40+3,fra=49+4/42+3,ams=51+5/48+3,par=56+5/51+3,lhr=61+6/57+3,sto=64+6/60+3,sto2=71+7/61+3,mad=72+7/72+3,iad=130+13/128+3,sgp=226+22/218+16,gru=238+23
[7/14/2021 7:30:13 PM] (Msg) Ping measurement completed
[7/14/2021 7:30:13 PM] (Debug) Destroying relay 'sof#2 (139.45.193.10:27016)' because initial_ping_timeout
[7/14/2021 7:30:13 PM] (Debug) Destroying relay 'scl#6 (155.133.249.162:27020)' because initial_ping_timeout
[7/14/2021 7:30:13 PM] (Debug) Destroying relay 'eat#75 (155.133.235.34:27051)' because initial_ping_timeout
[7/14/2021 7:30:11 PM] (Verbose) Communications with routing cluster 'syd' established.
[7/14/2021 7:30:11 PM] (Verbose) Communications with routing cluster 'gru' established.
[7/14/2021 7:30:11 PM] (Debug) Destroying relay 'syd#83 (103.10.125.154:27043)' because initial_ping_timeout
[7/14/2021 7:30:11 PM] (Debug) Destroying relay 'sof#5 (139.45.193.10:27019)' because initial_ping_timeout
[7/14/2021 7:30:11 PM] (Debug) Destroying relay 'scl#9 (155.133.249.162:27023)' because initial_ping_timeout
[7/14/2021 7:30:11 PM] (Debug) Destroying relay 'gru#108 (205.185.194.36:27027)' because initial_ping_timeout
[7/14/2021 7:30:11 PM] (Debug) Destroying relay 'eat#54 (155.133.235.34:27030)' because initial_ping_timeout
[7/14/2021 7:30:08 PM] (Verbose) Communications with routing cluster 'tyo' established.
[7/14/2021 7:30:08 PM] (Verbose) Communications with routing cluster 'tyo1' established.
[7/14/2021 7:30:08 PM] (Verbose) Communications with routing cluster 'sgp' established.
[7/14/2021 7:30:08 PM] (Verbose) Communications with routing cluster 'sea' established.
[7/14/2021 7:30:08 PM] (Verbose) Communications with routing cluster 'lim' established.
[7/14/2021 7:30:08 PM] (Verbose) Communications with routing cluster 'jnb' established.
[7/14/2021 7:30:08 PM] (Verbose) Communications with routing cluster 'maa' established.
[7/14/2021 7:30:08 PM] (Verbose) Communications with routing cluster 'eze' established.
[7/14/2021 7:30:08 PM] (Verbose) Communications with routing cluster 'lax' established.
[7/14/2021 7:30:08 PM] (Verbose) Communications with routing cluster 'sto2' established.
[7/14/2021 7:30:08 PM] (Verbose) Communications with routing cluster 'waw' established.
[7/14/2021 7:30:08 PM] (Verbose) Communications with routing cluster 'sto' established.
[7/14/2021 7:30:08 PM] (Verbose) Communications with routing cluster 'hkg' established.
[7/14/2021 7:30:08 PM] (Verbose) Communications with routing cluster 'ord' established.
[7/14/2021 7:30:08 PM] (Verbose) Communications with routing cluster 'vie' established.
[7/14/2021 7:30:08 PM] (Verbose) Communications with routing cluster 'iad' established.
[7/14/2021 7:30:08 PM] (Verbose) Communications with routing cluster 'dxb' established.
[7/14/2021 7:30:08 PM] (Verbose) Communications with routing cluster 'dfw' established.
[7/14/2021 7:30:08 PM] (Verbose) Communications with routing cluster 'mad' established.
[7/14/2021 7:30:08 PM] (Verbose) Communications with routing cluster 'bom' established.
[7/14/2021 7:30:08 PM] (Verbose) Communications with routing cluster 'lhr' established.
[7/14/2021 7:30:08 PM] (Verbose) Communications with routing cluster 'par' established.
[7/14/2021 7:30:08 PM] (Verbose) Communications with routing cluster 'atl' established.
[7/14/2021 7:30:08 PM] (Verbose) Communications with routing cluster 'ams' established.
[7/14/2021 7:30:08 PM] (Verbose) Communications with routing cluster 'fra' established.
[7/14/2021 7:30:08 PM] (Msg) SDR RelayNetworkStatus:  avail=Attempting  config=OK  anyrelay=Attempting   (Performing ping measurement)
[7/14/2021 7:30:08 PM] (Msg) Performing ping measurement
[7/14/2021 7:30:08 PM] (Msg) Got SDR network config.  Loaded revision 320 OK
[7/14/2021 7:30:08 PM] (Warning) SDR network config fetch first attempt failed.  HTTP 504.  .  Trying again.
[7/14/2021 7:29:58 PM] Attempting to open ALC device "OpenAL Soft on Speakers (9- USB PnP Audio Device)"
[7/14/2021 7:29:57 PM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[7/14/2021 7:29:57 PM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[7/14/2021 7:29:55 PM] Logged in as Александр Сергей (SteamID STEAM_1:0:526188760)

**Comment by JeffJeffMain** [comment]
Thanks in advance :D

**Comment by Regalis11** [comment]
It seems the game is failing to create the file "Barotrauma\Data\hashcache.txt" for some reason. There was an earlier report about this issue https://github.com/Regalis11/Barotrauma/issues/6100, and in that case the problem was an antivirus software blocking access. I'd recommend adding the game folder as an exception to your antivirus software and seeing if that helps.

Sorry for the inconvenience!

**Comment by JeffJeffMain** [comment]
alright!thanks it worked,for anyone using avast antivirus just go to: menu>blocked/allowed>allow app>Barotrauma.exe
Thanks again :D!
