### ISSUE TITLE
[0.14.6.0] Players drop after loading level (Level equality check failed/campaign ID does not match) Corrupted save?

### ISSUE THREAD

**Issue by CurePindal** [Regalis11/Barotrauma#6349]
- [ x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
After a few game sessions all players besides the host now always drop from the server after a level change.
(after docking and after loading a route)
No console errors on the client hosts side.

IMPORTANT: Can anybody please tell me if this is fixable or if the save is corrupted? (is a save corruption even possible?)

**Steps To Reproduce**
Docking - all players drop when the station loads (hosting player not dropped)
starting a route all players drop when the route loads (hosting player not dropped)

**Version**
0.14.6.0, Win10, Client hosted, 5 players in this last session
Mods: ITA, EK Utilities/Amory, EK Utilities balance, New Wrecks, Wrecks Extended, Beacons Extended.
Tested the save without New Wrecks, Wrecks Extended, Beacons Extended - issue persists

**Additional information**
Not sure if correlated:
The issues started to happen after the client host crashed when after loading into a Pirate Vessel mission. This missions 100% crash the client hosted game.
Strangely 3 days later the save loaded docked at the last outpost before taking the Vessel-mission, so we continued to play. 
Roughly an hour later the players started to drop from the game after loading a level.

Errors from the other players console:
Most of the time:
Failed to start campaign round (campaign ID does not match).

Also: 
`Error while reading a message from server. {Level equality check failed. The level generated at your end doesn't match the level generated by the server (client value #0: 909380168, server value #0: 50A91A69, level value count: 13, seed: Binnsmouth, sub: TF Mk III Annihilator v1.2 (AAE00E4), mirrored: False).}
at Barotrauma.Networking.GameClient.ReadStartGameFinalize(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 964
at Barotrauma.Networking.GameClient.ReadDataMessage(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 861
at Barotrauma.Networking.SteamP2PClientPeer.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\Primitives\Peers\SteamP2PClientPeer.cs:line 243
at Barotrauma.Networking.GameClient.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 632`

And:
`Error loading item - item prefab "" (identifier "ekutility_miningdrill") not found.`

`Coroutine "Barotrauma.Networking.GameClient+<StartGame>d__93" has failed`

Save:
[ITA_EK.zip](https://github.com/Regalis11/Barotrauma/files/6855210/ITA_EK.zip)

**Comment by CurePindal** [comment]
Client drop today:
`Unauthorized multithreaded access to RandSync.Server
at System.Environment.get_StackTrace()
at Barotrauma.Rand.CheckRandThreadSafety(RandSync sync) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\Rand.cs:line 47
at Barotrauma.Rand.Range(Single minimum, Single maximum, RandSync sync) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\Rand.cs:line 56
at Barotrauma.PirateMission.GetRandomDifficultyModifiedElement(XElement parentElement, Single levelDifficulty, Single randomnessModifier) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\Missions\PirateMission.cs:line 142
at Barotrauma.PirateMission.SetDifficulty(Single difficulty) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\Missions\PirateMission.cs:line 102
at Barotrauma.PirateMission..ctor(MissionPrefab prefab, Location[] locations, Submarine sub) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\Missions\PirateMission.cs:line 90
at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
at Barotrauma.MissionPrefab.Instantiate(Location[] locations, Submarine sub) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\Missions\MissionPrefab.cs:line 381
at Barotrauma.Location.InstantiateLoadedMissions(Map map) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Map\Location.cs:line 621
at Barotrauma.Map.LoadState(XElement element, Boolean showNotifications) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Map\Map.cs:line 1109
at Barotrauma.MultiPlayerCampaign.Load(XElement element) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameModes\MultiPlayerCampaign.cs:line 146
at Barotrauma.MultiPlayerCampaign.LoadState(String filePath) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameSession\GameModes\MultiPlayerCampaign.cs:line 907
at Barotrauma.Networking.GameClient.OnFileReceived(FileTransferIn transfer) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 2626
at Barotrauma.Networking.FileReceiver.ReadMessage(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\FileTransfer\FileReceiver.cs:line 379
at Barotrauma.Networking.GameClient.ReadDataMessage(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 944
at Barotrauma.Networking.SteamP2PClientPeer.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\Primitives\Peers\SteamP2PClientPeer.cs:line 243
at Barotrauma.Networking.GameClient.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 632
at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 986
at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 651
at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59`

**Comment by jlopezantequera** [comment]
Same situation, just can't play with my friends. We've tried all sorts of acrobatics to get rid of this.

Here's my logfile. As stated by the op, the host does not see anything other than the player disconnecting. Only the client being disconnected gets to see the stack trace.

[paindump.txt](https://github.com/Regalis11/Barotrauma/files/6858949/paindump.txt)

**Comment by Regalis11** [comment]
I'm afraid I couldn't reproduce this, the save file seems to load with no errors.

@CurePindal & @jlopezantequera these errors seem to be caused by https://github.com/Regalis11/Barotrauma/issues/6184, will be fixed in the next patch. Sorry for the inconvenience!

**Comment by jlopezantequera** [comment]
Can't wait to play again!

Here's a save where we are also experiencing it, in case you might need it.
[Charon_D_Modded_with_Piano.save.csv](https://github.com/Regalis11/Barotrauma/files/6868705/Charon_D_Modded_with_Piano.save.csv) 

_Github does not enjoy .save so i gave it that bogus file extension_

**Comment by 49Arts** [comment]
Was this fixed in this latest patch?

**Comment by jlopezantequera** [comment]
Yes! Thanks

**Comment by 49Arts** [comment]
I am still experiencing this issue. How do I send you the logs?

**Comment by DEXTROUSPOON** [comment]
Hi, hate to re-open a closed issue but it seems like this bug still occurs a bit too frequently for me and my friends. Would like to add some screenshots of the console log during the moment this disconnection issue occurs. For context, we are using the most recent stable version (v0.15.22.0), plus we all run Vanilla only, with no mods. Can confirm that files are verified and that most of us are using Windows 10, however, the campaign is hosted through the in-game menu (not a dedicated server). It tends to occur when leaving the outpost for a mission, we have our campaign set to 1 max mission per round as setting this higher seems to cause more disconnections, though it could be unrelated. I am attaching the screenshots of the console when we experienced the disconnections, that said, we aren't able to provide logs for when these issues did occur, apologies for that.

The following is in the point of view of a user connecting to my game :
![clientPOV_disconnection_1_LI](https://user-images.githubusercontent.com/97667600/149308448-ff3b7bdd-e09f-46d4-a779-e50d9dfe8a35.jpg)
![clientPOV_disconnection_2](https://user-images.githubusercontent.com/97667600/149308462-e1836212-6c50-4fab-9d7f-d1dd38f3646e.jpg)


The following is in the point of view of the host of the campaign:
![serverPOV_disconnection_1_LI](https://user-images.githubusercontent.com/97667600/149309081-e11d0dfe-4cf6-4036-bce4-37e93972d291.jpg)
![serverPOV_disconnection_2_LI](https://user-images.githubusercontent.com/97667600/149309093-48446868-1c01-452b-aa73-5a08219ac41d.jpg)


A workaround we use is to simply go back to the lobby menu to reload and rehost the campaign. Hope this helps in your investigation.
