### ISSUE TITLE
[Unstable v0.1400.7.0] Player disconnected at level transition in end of round (Exception has been thrown by the target of an invocation at System.RuntimeMethodHandle.InvokeMethod)

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#6377]
We were doing a single cargo mission and once we docked to the destination outpost client disconnected without a disconnection reason on the server side, they did receive a error on the console. 

```
Error while reading a message from server. {Exception has been thrown by the target of an invocation.}
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.ConstructorInfo.Invoke(Object[] parameters)
   at Barotrauma.MissionPrefab.Instantiate(Location[] locations, Submarine sub) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\Missions\MissionPrefab.cs:line 381
   at Barotrauma.Location.InstantiateLoadedMissions(Map map) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Map\Location.cs:line 636
   at Barotrauma.Map.LoadState(XElement element, Boolean showNotifications) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Map\Map.cs:line 1102
   at Barotrauma.MultiPlayerCampaign.Load(XElement element) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameModes\MultiPlayerCampaign.cs:line 146
   at Barotrauma.MultiPlayerCampaign.LoadState(String filePath) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameSession\GameModes\MultiPlayerCampaign.cs:line 906
   at Barotrauma.Networking.GameClient.OnFileReceived(FileTransferIn transfer) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 2629
   at Barotrauma.Networking.FileReceiver.ReadMessage(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\FileTransfer\FileReceiver.cs:line 379
   at Barotrauma.Networking.GameClient.ReadDataMessage(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 944
   at Barotrauma.Networking.SteamP2PClientPeer.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\Primitives\Peers\SteamP2PClientPeer.cs:line 243
   at Barotrauma.Networking.GameClient.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 632

Inner exception: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at Barotrauma.Submarine.GetCargoContainers() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Submarine.cs:line 1269
   at Barotrauma.CargoMission.DetermineCargo() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\Missions\CargoMission.cs:line 66
   at Barotrauma.CargoMission..ctor(MissionPrefab prefab, Location[] locations, Submarine sub) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\Missions\CargoMission.cs:line 54
Overriding an affliction or a buff with the identifier 'huskinfection' using the file 'Mods/Huskmod/Afflictions.xml'
Overriding all location types with 'Mods/REALLYBIGMAP/Map/RBM_locationTypes.xml'
Loading additional location types from file 'Mods/XanMonsters/Map/LocationTypes.xml'
Loading additional location types from file 'Mods/XanMonsters2/Map/LocationTypes.xml'
Overriding the map generation parameters with 'Mods/REALLYBIGMAP/Map/RBM_MapGen.xml'
Coroutine Barotrauma.Networking.GameClient+<StartGame>d__93 threw an exception: Object reference not set to an instance of an object.
   at Barotrauma.Networking.GameClient.StartGame(IReadMessage inc)+MoveNext() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 1617
   at Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 217
Coroutine MultiplayerCampaign.DoInitialCameraTransition threw an exception: Object reference not set to an instance of an object.
   at Barotrauma.MultiPlayerCampaign.DoInitialCameraTransition()+MoveNext() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameSession\GameModes\MultiPlayerCampaign.cs:line 198
   at Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 217
```

**Comment by Rokvach** [comment]
Closing as a duplicate
