### ISSUE TITLE
[Unstable v0.1400.7.0] Event error disconnection + Server crashed when using a respawnnow command after player has rejoined the server after a event error desync

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#6378]
The event error happened whilst we were testing Reaper's tax issue from this ticket https://github.com/Regalis11/Barotrauma/issues/6141 the client who didn't respawn at the end of the round because the round ended was disconnected because of a event error and once we loaded into the outpost I used the respawnnow command which then lead to the crashing.

Logs for the event error (Client died and didn't respawn before the round ended):

event_error_log_server_Jade Harley_859
[https://app.zenhub.com/files/175046454/6be384c4-56ba-4fd0-8713-d5b75c88971d/download](https://app.zenhub.com/files/175046454/6be384c4-56ba-4fd0-8713-d5b75c88971d/download)

event_error_log_client_Jade_Harley_859_AM
[https://app.zenhub.com/files/175046454/a7f4d081-c205-4904-a2b1-65b6a6d13537/download](https://app.zenhub.com/files/175046454/a7f4d081-c205-4904-a2b1-65b6a6d13537/download)

(Host) event_error_log_server_Rokvach_859
[https://app.zenhub.com/files/175046454/4c6fb777-9579-4548-89ed-dca123e6649c/download](https://app.zenhub.com/files/175046454/4c6fb777-9579-4548-89ed-dca123e6649c/download)

(Host) event_error_log_client_Rokvach_859
[https://app.zenhub.com/files/175046454/29c9205f-2f57-4e6c-8cca-1bd10c989e16/download](https://app.zenhub.com/files/175046454/29c9205f-2f57-4e6c-8cca-1bd10c989e16/download)

```
Barotrauma Dedicated Server crash report (generated on 29.7.2021 12:00:34)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


Game version 0.1400.7.0 (UnstableWindows, branch feature/bugfixes, revision 7644391e74)
Language: English
Selected content packages: Vanilla 0.9
Level seed: Alkonost
Loaded submarine: Dugong (84A04EB9C0F45278D74AA7EBD296A43A)
Selected screen: Barotrauma.GameScreen
Server (Round had started)


System info:
    Operating system: Microsoft Windows NT 6.2.9200.0 64 bit


Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void SpawnInventoryItemsRecursive(Barotrauma.Inventory, System.Xml.Linq.XElement, System.Collections.Generic.List`1[Barotrauma.Item])
Stack trace: 
   at Barotrauma.Character.SpawnInventoryItemsRecursive(Inventory inventory, XElement element, List`1 extraDuffelBags) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 3950
   at Barotrauma.Character.SpawnInventoryItems(Inventory inventory, XElement itemData) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 3945
   at Barotrauma.CharacterCampaignData.SpawnInventoryItems(Character character, Inventory inventory) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\GameSession\GameModes\CharacterCampaignData.cs:line 40
   at Barotrauma.Networking.RespawnManager.RespawnCharactersProjSpecific(Nullable`1 shuttlePos) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Networking\RespawnManager.cs:line 429
   at Barotrauma.Networking.RespawnManager.RespawnCharacters(Nullable`1 shuttlePos) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\RespawnManager.cs:line 306
   at Barotrauma.Networking.RespawnManager.DispatchShuttle() in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Networking\RespawnManager.cs:line 180
   at Barotrauma.Networking.RespawnManager.UpdateWaiting(Single deltaTime) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Networking\RespawnManager.cs:line 137
   at Barotrauma.Networking.RespawnManager.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\RespawnManager.cs:line 154
   at Barotrauma.Networking.GameServer.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Networking\GameServer.cs:line 381
   at Barotrauma.GameMain.Run() in <DEV>\Barotrauma\BarotraumaServer\ServerSource\GameMain.cs:line 358
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Program.cs:line 58


Last debug messages:
   29.7.2021 12:00:34 - [29.7.2021 12:00:34]
  Saving banlist
   29.7.2021 12:00:34 - [29.7.2021 12:00:34]
  Respawning Jade Harley (STEAM_1:0:476582823) as Engineer
   29.7.2021 12:00:34 - [29.7.2021 12:00:34]
  Respawning everyone in main sub.
   29.7.2021 12:00:34 - [29.7.2021 12:00:34]
  Console command "respawnnow" executed by Rokvach.
   29.7.2021 12:00:12 - [29.7.2021 12:00:12]
  Saving client permissions
   29.7.2021 12:00:12 - [29.7.2021 12:00:12]
  Jade Harley has joined the server.
   29.7.2021 11:59:18 - [29.7.2021 11:59:18]
  Rokvach set the value "Channel" of the item "Headset" to "0".
   29.7.2021 11:59:11 - [29.7.2021 11:59:11]
  Arcelia Marchi unequipped Screwdriver
   29.7.2021 11:59:11 - [29.7.2021 11:59:11]
  Beverley Graves unequipped Wrench
   29.7.2021 11:59:11 - [29.7.2021 11:59:11]
  Filiberto Huynh unequipped Screwdriver
   29.7.2021 11:59:10 - [29.7.2021 11:59:10]
  Cathleen Simpson unequipped Crowbar
   29.7.2021 11:59:10 - [29.7.2021 11:59:10]
  Herman Ram unequipped Wrench
   29.7.2021 11:59:10 - [29.7.2021 11:59:10]
  Edgar Buckley equipped Crowbar
   29.7.2021 11:59:10 - [29.7.2021 11:59:10]
  Herman Ram equipped Wrench
```

**Comment by Abdent1** [comment]
So, this is all cool, but is there still an opportunity to play on save in multiplayer, if there was such an error before?

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2b520e6307abfde0ba47441c206879abef0c24c9

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
