### ISSUE TITLE
Everytime I got crashed in submarine editor

### ISSUE THREAD

**Issue by DetectiveKaktus** [Regalis11/Barotrauma#6379]
- [Barotrauma Client crash report (generated on 29-Jul-21 7:24:34 PM)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

EECA616DF2BA4F9511EEC52AB1F63877

Game version 0.14.6.0 (ReleaseWindows, branch release, revision 12d7084c07)
Graphics mode: 1680x1050 (BorderlessWindowed)
VSync ON
Language: Russian
Selected content packages: Vanilla 0.9, Leviathan, U-3506
Level seed: no level loaded
Loaded submarine: Unnamed ()
Selected screen: Barotrauma.SubEditorScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 6.1.7601 Service Pack 1 64 bit
    GPU name: NVIDIA GeForce GT 240
    Display mode: {Width:1680 Height:1050 Format:Color AspectRatio:1.6}
    GPU status: Normal

Exception: HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid Arguments], Message: Параметр задан неверно.
 (SharpDX.SharpDXException)
Target site: Void CheckError()
Stack trace: 
   at SharpDX.Result.CheckError()
   at Microsoft.Xna.Framework.Graphics.Texture2D.CreateTexture() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\Texture2D.DirectX.cs:line 410
   at Microsoft.Xna.Framework.Graphics.Texture2D.PlatformSetData[T](Int32 level, T[] data, Int32 startIndex, Int32 elementCount) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\Texture2D.DirectX.cs:line 87
   at Microsoft.Xna.Framework.Graphics.Texture2D.SetData[T](T[] data) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\Texture2D.cs:line 205
   at Barotrauma.CrossThread.ProcessTasks() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\CrossThread.cs:line 38
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 746
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59

Last debug messages:
[29-Jul-21 7:24:34 PM] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: Mods/U-3506/xxi.png, size: 10053x1623)
[29-Jul-21 7:23:35 PM] (Msg) SDR RelayNetworkStatus:  avail=OK  config=OK  anyrelay=OK   (OK)
[29-Jul-21 7:23:35 PM] (Msg) Ping location: waw=12+1,vie=49+4/22+1,fra=29+2/28+1,ams=33+3/33+1,sto2=33+3/33+1,sto=35+3/33+1,par=49+4/38+1,lhr=42+4/38+3,mad=59+5/60+1,iad=126+12/114+1,sgp=268+26/201+15,gru=254+25/257+1
[29-Jul-21 7:23:35 PM] (Msg) Ping measurement completed
[29-Jul-21 7:23:35 PM] (Debug) Destroying relay 'sof#4 (139.45.193.10:27018)' because initial_ping_timeout
[29-Jul-21 7:23:35 PM] (Debug) Destroying relay 'eat#54 (155.133.235.34:27030)' because initial_ping_timeout
[29-Jul-21 7:23:34 PM] (Verbose) Communications with routing cluster 'syd' established.
[29-Jul-21 7:23:34 PM] (Verbose) Communications with routing cluster 'sea' established.
[29-Jul-21 7:23:34 PM] (Debug) Destroying relay 'syd#85 (103.10.125.154:27045)' because initial_ping_timeout
[29-Jul-21 7:23:34 PM] (Debug) Destroying relay 'sof#1 (139.45.193.10:27015)' because initial_ping_timeout
[29-Jul-21 7:23:34 PM] (Debug) Destroying relay 'sea#92 (205.196.6.74:27068)' because initial_ping_timeout
[29-Jul-21 7:23:34 PM] (Debug) Destroying relay 'eat#30 (155.133.235.18:27044)' because initial_ping_timeout
[29-Jul-21 7:23:30 PM] (Verbose) Communications with routing cluster 'tyo' established.
[29-Jul-21 7:23:30 PM] (Verbose) Communications with routing cluster 'tyo1' established.
[29-Jul-21 7:23:30 PM] (Verbose) Communications with routing cluster 'sgp' established.
[29-Jul-21 7:23:30 PM] (Verbose) Communications with routing cluster 'scl' established.
[29-Jul-21 7:23:30 PM] (Verbose) Communications with routing cluster 'lim' established.
[29-Jul-21 7:23:30 PM] (Verbose) Communications with routing cluster 'jnb' established.
[29-Jul-21 7:23:30 PM] (Verbose) Communications with routing cluster 'lax' established.
[29-Jul-21 7:23:30 PM] (Verbose) Communications with routing cluster 'eze' established.
[29-Jul-21 7:23:30 PM] (Verbose) Communications with routing cluster 'maa' established.
[29-Jul-21 7:23:30 PM] (Verbose) Communications with routing cluster 'gru' established.
[29-Jul-21 7:23:30 PM] (Verbose) Communications with routing cluster 'vie' established.
[29-Jul-21 7:23:30 PM] (Verbose) Communications with routing cluster 'ord' established.
[29-Jul-21 7:23:30 PM] (Verbose) Communications with routing cluster 'sto' established.
[29-Jul-21 7:23:30 PM] (Verbose) Communications with routing cluster 'sto2' established.
[29-Jul-21 7:23:30 PM] (Verbose) Communications with routing cluster 'iad' established.
[29-Jul-21 7:23:30 PM] (Verbose) Communications with routing cluster 'waw' established.
[29-Jul-21 7:23:30 PM] (Verbose) Communications with routing cluster 'hkg' established.
[29-Jul-21 7:23:30 PM] (Verbose) Communications with routing cluster 'mad' established.
[29-Jul-21 7:23:30 PM] (Verbose) Communications with routing cluster 'dxb' established.
[29-Jul-21 7:23:30 PM] (Verbose) Communications with routing cluster 'dfw' established.
[29-Jul-21 7:23:30 PM] (Verbose) Communications with routing cluster 'par' established.
[29-Jul-21 7:23:30 PM] (Verbose) Communications with routing cluster 'bom' established.
[29-Jul-21 7:23:30 PM] (Verbose) Communications with routing cluster 'lhr' established.
[29-Jul-21 7:23:30 PM] (Verbose) Communications with routing cluster 'atl' established.
[29-Jul-21 7:23:30 PM] (Verbose) Communications with routing cluster 'ams' established.
[29-Jul-21 7:23:30 PM] (Verbose) Communications with routing cluster 'fra' established.
[29-Jul-21 7:23:30 PM] (Msg) SDR RelayNetworkStatus:  avail=Attempting  config=OK  anyrelay=Attempting   (Performing ping measurement)
[29-Jul-21 7:23:30 PM] (Msg) Performing ping measurement
[29-Jul-21 7:23:30 PM] (Msg) Got SDR network config.  Loaded revision 329 OK
[29-Jul-21 7:23:29 PM] (Warning) SDR network config fetch first attempt failed.  HTTP 504.  .  Trying again.
[29-Jul-21 7:23:05 PM] Attempting to open ALC device "OpenAL Soft on Динамики (VIA HD Audio)"
[29-Jul-21 7:23:01 PM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[29-Jul-21 7:23:00 PM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[29-Jul-21 7:22:56 PM] Logged in as GUS (SteamID STEAM_1:1:526098975)
 ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bug in submarine editor

**Steps To Reproduce**
When I switch tabs in submarine editor I always get this crash. 

**Version**
Barotrauma v0.14.6.0. I use Win7

**Additional information**
Nothing here.

**Comment by Regalis11** [comment]
This could potentially be caused by the U-3506 which seems to add a pretty significant amount of incompressible textures into the game. Could you try disabling that mod and seeing if it helps? Sorry for the inconvenience!
