### ISSUE TITLE
Crash when giving contextual orders to bots

### ISSUE THREAD

**Issue by tastesliketriangle** [Regalis11/Barotrauma#6427]
**Description**
Telling a bot to operate a coilgun or railgun from the hardpoint rather than the periscope causes a CTD with the included stack trace. happens in both sub editor and campaign mode with custom and vanilla subs.

**Steps To Reproduce**
Load the Dugong, go outside the sub, middle-click on a coilgun, select 'operate weapons'

**Version**
v0.14.6.0
Windows 10 x64

**Additional information**
```
Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Boolean IsItemTargetedBySomeone(Barotrauma.Items.Components.ItemComponent, Barotrauma.CharacterTeamType, Barotrauma.Character ByRef)
Stack trace: 
   at Barotrauma.HumanAIController.IsItemTargetedBySomeone(ItemComponent target, CharacterTeamType team, Character& operatingCharacter) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\HumanAIController.cs:line 1933
   at Barotrauma.CrewManager.GetCharacterForQuickAssignment(Order order, Character controlledCharacter, IEnumerable`1 characters, Boolean includeSelf) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\CrewManager.cs:line 419
   at Barotrauma.CrewManager.GetCharacterForQuickAssignment(Order order) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameSession\CrewManager.cs:line 3412
   at Barotrauma.CrewManager.<>c__DisplayClass156_0.<CreateOrderNode>b__0(GUIButton button, Object userData) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameSession\CrewManager.cs:line 2687
   at Barotrauma.GUIButton.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIButton.cs:line 262
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Barotrauma.GUI.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1250
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 986
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58
```

**Comment by Rokvach** [comment]
Already fixed, coming in the next update. Closing.
