### ISSUE TITLE
Mac version crashes when loading a save

### ISSUE THREAD

**Issue by VeganLeather** [Regalis11/Barotrauma#6616]
I'm using a 2013 macbook air with high Sierra. When I try to load any save file, the game crashes just as the zoom-in where you can't move your character finishes. I've launched the game several times previously and never encountered this issue, and as far as I can tell, neither the game, or my laptop have updated recently.

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void DrawMap(Microsoft.Xna.Framework.Graphics.GraphicsDevice, Microsoft.Xna.Framework.Graphics.SpriteBatch, Double)
Stack trace: 
   at Barotrauma.GameScreen.DrawMap(GraphicsDevice graphics, SpriteBatch spriteBatch, Double deltaTime)
   at Barotrauma.GameScreen.Draw(Double deltaTime, GraphicsDevice graphics, SpriteBatch spriteBatch) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Screens/GameScreen.cs:line 122
   at Barotrauma.GameMain.Draw(GameTime gameTime) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/GameMain.cs:line 1038
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime) in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 669
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 508
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/SDL/SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Program.cs:line 58

I would appreciate any help :)

**Comment by juanjp600** [comment]
This appears to have been caused by a mishap in our build process. If I'm not mistaken, a new build should be available. Please verify the integrity of your game files by going to Manage > Properties > Local files > Verify integrity of game files.

**Comment by JoyFish2021** [comment]
I have encountered this issue as well in similar, if not identical circumstances, but for me the game crashes on zoom-in when loading a new game as well.

Barotrauma Client crash report (generated on 9/9/2021 11:17:16 PM)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


E852FFF256948870565369B1C9D9B8B7


Game version 0.14.9.1 (ReleaseMac, branch release, revision df0088ca33)
Graphics mode: 1440x900 (BorderlessWindowed)
VSync ON
Language: Simplified Chinese
Selected content packages: Vanilla 0.9, Anime Poster Pack
Level seed: Xinzou
Loaded submarine: Dugong (586BD2DE378DB1F6C7D662F7B7DF34BA)
Selected screen: Barotrauma.GameScreen
SteamManager initialized


System info:
    Operating system: Unix 20.6.0.0 64 bit
    GPU name: 
    Display mode: {Width:1440 Height:900 Format:Color AspectRatio:1.6}
    GPU status: Normal


Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void DrawMap(Microsoft.Xna.Framework.Graphics.GraphicsDevice, Microsoft.Xna.Framework.Graphics.SpriteBatch, Double)
Stack trace: 
   at Barotrauma.GameScreen.DrawMap(GraphicsDevice graphics, SpriteBatch spriteBatch, Double deltaTime)
   at Barotrauma.GameScreen.Draw(Double deltaTime, GraphicsDevice graphics, SpriteBatch spriteBatch) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Screens/GameScreen.cs:line 122
   at Barotrauma.GameMain.Draw(GameTime gameTime) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/GameMain.cs:line 1038
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime) in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 669
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 508
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/SDL/SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Program.cs:line 58


Last debug messages:
[9/9/2021 11:16:57 PM] Generating an outpost for the start of the level... (Location: Xinzou城, level type: Outpost)
[9/9/2021 11:16:06 PM] (Msg) SDR RelayNetworkStatus:  avail=OK  config=OK  anyrelay=OK   (OK)
[9/9/2021 11:16:06 PM] (Msg) Ping location: hkg=103+10,sgp=138+13/133+10,tyo1=138+13,tyo=165+16/138+13,maa=440+44/165+10,bom=408+40/183+10,dxb=226+22/208+10,syd=225+22/220+20,sea=235+23,fra=284+28/266+25,iad=293+29/294+27,gru=449+44/423+27
[9/9/2021 11:16:06 PM] (Msg) Ping measurement completed
[9/9/2021 11:16:05 PM] (Debug) Destroying relay 'sto#17 (162.254.198.40:27031)' because consecutive_ping_timeout
[9/9/2021 11:16:05 PM] (Debug) Destroying relay 'vie#232 (146.66.155.50:27046)' because consecutive_ping_timeout
[9/9/2021 11:16:05 PM] (Debug) Destroying relay 'lhr#54 (162.254.196.70:27030)' because initial_ping_timeout
[9/9/2021 11:16:05 PM] (Verbose) Communications with routing cluster 'tyo' established.
[9/9/2021 11:16:04 PM] (Verbose) Communications with routing cluster 'atl' established.
[9/9/2021 11:16:04 PM] (Debug) Destroying relay 'sof#4 (139.45.193.10:27018)' because initial_ping_timeout
[9/9/2021 11:16:04 PM] (Debug) Destroying relay 'tyo#120 (155.133.239.26:27050)' because initial_ping_timeout
[9/9/2021 11:16:04 PM] (Debug) Destroying relay 'waw#275 (155.133.230.67:27019)' because initial_ping_timeout
[9/9/2021 11:16:03 PM] (Debug) Destroying relay 'lhr#53 (162.254.196.70:27029)' because consecutive_ping_timeout
[9/9/2021 11:16:03 PM] (Debug) Destroying relay 'jnb#103 (155.133.238.163:27063)' because initial_ping_timeout
[9/9/2021 11:16:03 PM] (Debug) Destroying relay 'mad#57 (155.133.246.50:27033)' because initial_ping_timeout
[9/9/2021 11:16:03 PM] (Debug) Destroying relay 'ams#56 (155.133.248.51:27016)' because initial_ping_timeout
[9/9/2021 11:16:03 PM] (Debug) Destroying relay 'atl#84 (162.254.199.173:27052)' because initial_ping_timeout
[9/9/2021 11:16:03 PM] (Debug) Destroying relay 'eat#30 (155.133.235.18:27044)' because initial_ping_timeout
[9/9/2021 11:16:02 PM] (Debug) Destroying relay 'sgp#183 (103.10.124.99:27045)' because initial_ping_timeout
[9/9/2021 11:16:02 PM] (Debug) Destroying relay 'dfw#55 (155.133.253.54:27023)' because consecutive_ping_timeout
[9/9/2021 11:16:01 PM] (Verbose) Communications with routing cluster 'vie' established.
[9/9/2021 11:16:01 PM] (Verbose) Communications with routing cluster 'iad' established.
[9/9/2021 11:16:01 PM] (Verbose) Communications with routing cluster 'fra' established.
[9/9/2021 11:16:01 PM] (Debug) Destroying relay 'waw#415 (155.133.230.69:27051)' because initial_ping_timeout
[9/9/2021 11:16:01 PM] (Debug) Destroying relay 'vie#343 (146.66.155.52:27049)' because initial_ping_timeout
[9/9/2021 11:16:01 PM] (Debug) Destroying relay 'tyo#46 (155.133.239.19:27060)' because initial_ping_timeout
[9/9/2021 11:16:01 PM] (Debug) Destroying relay 'sof#3 (139.45.193.10:27017)' because initial_ping_timeout
[9/9/2021 11:16:01 PM] (Debug) Destroying relay 'sgp#182 (103.10.124.99:27044)' because consecutive_ping_timeout
[9/9/2021 11:16:01 PM] (Debug) Destroying relay 'mad#72 (155.133.246.50:27048)' because initial_ping_timeout
[9/9/2021 11:16:01 PM] (Debug) Destroying relay 'jnb#45 (155.133.238.162:27059)' because initial_ping_timeout
[9/9/2021 11:16:01 PM] (Debug) Destroying relay 'iad#219 (162.254.192.86:27027)' because initial_ping_timeout
[9/9/2021 11:16:01 PM] (Debug) Destroying relay 'fra#259 (162.254.197.52:27043)' because initial_ping_timeout
[9/9/2021 11:16:01 PM] (Debug) Destroying relay 'eat#6 (155.133.235.18:27020)' because initial_ping_timeout
[9/9/2021 11:16:01 PM] (Debug) Destroying relay 'atl#60 (162.254.199.173:27028)' because initial_ping_timeout
[9/9/2021 11:16:01 PM] (Debug) Destroying relay 'ams#38 (155.133.248.50:27052)' because initial_ping_timeout
[9/9/2021 11:16:00 PM] (Verbose) Communications with routing cluster 'sto' established.
[9/9/2021 11:16:00 PM] (Verbose) Communications with routing cluster 'lhr' established.
[9/9/2021 11:15:59 PM] (Verbose) Communications with routing cluster 'scl' established.
[9/9/2021 11:15:59 PM] (Verbose) Communications with routing cluster 'maa' established.
[9/9/2021 11:15:59 PM] (Verbose) Communications with routing cluster 'sto2' established.
[9/9/2021 11:15:59 PM] (Verbose) Communications with routing cluster 'lim' established.
[9/9/2021 11:15:59 PM] (Verbose) Communications with routing cluster 'eze' established.
[9/9/2021 11:15:59 PM] (Verbose) Communications with routing cluster 'gru' established.
[9/9/2021 11:15:59 PM] (Verbose) Communications with routing cluster 'sea' established.
[9/9/2021 11:15:59 PM] (Verbose) Communications with routing cluster 'syd' established.
[9/9/2021 11:15:59 PM] (Verbose) Communications with routing cluster 'bom' established.
[9/9/2021 11:15:58 PM] (Verbose) Communications with routing cluster 'ord' established.
[9/9/2021 11:15:58 PM] (Verbose) Communications with routing cluster 'lax' established.
[9/9/2021 11:15:58 PM] (Verbose) Communications with routing cluster 'par' established.
[9/9/2021 11:15:58 PM] (Verbose) Communications with routing cluster 'tyo1' established.
[9/9/2021 11:15:58 PM] (Verbose) Communications with routing cluster 'sgp' established.
[9/9/2021 11:15:58 PM] (Verbose) Communications with routing cluster 'dfw' established.
[9/9/2021 11:15:58 PM] (Verbose) Communications with routing cluster 'dxb' established.
[9/9/2021 11:15:58 PM] (Verbose) Communications with routing cluster 'hkg' established.
[9/9/2021 11:15:58 PM] (Msg) SDR RelayNetworkStatus:  avail=Attempting  config=OK  anyrelay=Attempting   (Performing ping measurement)
[9/9/2021 11:15:58 PM] (Msg) Performing ping measurement
[9/9/2021 11:15:58 PM] (Msg) Got SDR network config.  Loaded revision 330 OK
[9/9/2021 11:15:58 PM] (Warning) SDR network config fetch first attempt failed.  HTTP 504.  .  Trying again.
[9/9/2021 11:15:55 PM] WARNING: 400 buffer(s) were generated. No more sound buffers will be generated.
[9/9/2021 11:15:44 PM] Attempting to open ALC device "Me的AirPods Pro"
[9/9/2021 11:15:43 PM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[9/9/2021 11:15:42 PM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[9/9/2021 11:15:39 PM] Logged in as JoyFish (SteamID STEAM_1:1:591884079)

I just verified the game files and the problem still persists.

**Comment by JoyFish2021** [comment]
The problem seems to have been solved with the latest update, thank you!

**Comment by Rokvach** [comment]
Closing as the issue has been fixed and is working correctly
