### ISSUE TITLE
New player spawning in the middle of a campaign round spawned with an incorrect ID item

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#6620]
Didn't create a entity error file

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/1d57ad85-d685-4a02-befb-fe7a30e1221e)

Error message which was prompted when the player spawned
```
Failed to spawn item Aluminum {ID 2909 is taken by Psychosis Alien Artifact (ID: 2909)}
   at Barotrauma.Entity..ctor(Submarine submarine, UInt16 id) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Entity.cs:line 95
   at Barotrauma.MapEntity..ctor(MapEntityPrefab prefab, Submarine submarine, UInt16 id) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\MapEntity.cs:line 252
   at Barotrauma.Item..ctor(Rectangle newRect, ItemPrefab itemPrefab, Submarine submarine, Boolean callOnItemLoaded, UInt16 id) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 760
   at Barotrauma.Item..ctor(ItemPrefab itemPrefab, Vector2 position, Submarine submarine, UInt16 id) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 745
   at Barotrauma.Item.ReadSpawnData(IReadMessage msg, Boolean spawn) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Item.cs:line 1612
Failed to read event for entity "EntitySpawner"! {ID 2909 is taken by Psychosis Alien Artifact (ID: 2909)}
   at Barotrauma.Entity..ctor(Submarine submarine, UInt16 id) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Entity.cs:line 95
   at Barotrauma.MapEntity..ctor(MapEntityPrefab prefab, Submarine submarine, UInt16 id) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\MapEntity.cs:line 252
   at Barotrauma.Item..ctor(Rectangle newRect, ItemPrefab itemPrefab, Submarine submarine, Boolean callOnItemLoaded, UInt16 id) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 760
   at Barotrauma.Item..ctor(ItemPrefab itemPrefab, Vector2 position, Submarine submarine, UInt16 id) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 745
   at Barotrauma.Item.ReadSpawnData(IReadMessage msg, Boolean spawn) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Item.cs:line 1612
   at Barotrauma.EntitySpawner.ClientRead(ServerNetObject type, IReadMessage message, Single sendingTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\EntitySpawner.cs:line 31
   at Barotrauma.Networking.ClientEntityEventManager.ReadEvent(IReadMessage buffer, IServerSerializable entity, Single sendingTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\NetEntityEvent\ClientEntityEventManager.cs:line 287
   at Barotrauma.Networking.ClientEntityEventManager.Read(ServerNetObject type, IReadMessage msg, Single sendingTime, List`1 entities) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\NetEntityEvent\ClientEntityEventManager.cs:line 238
```

**Comment by Regalis11** [comment]
This is so old that I'd say it's most likely impossible to reproduce with the information given (and may have been fixed already)
