### ISSUE TITLE
[Crash on launch] Null reference exception at Barotrauma.GameMain.GetFilesOfType

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#6636]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
My friend's game crashes on launch and he can't even disable mods. This problem started today.
He tried removing the Mods folder and verifying game files.

```
Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: System.Collections.Generic.IEnumerable`1[Barotrauma.ContentFile] GetFilesOfType(Barotrauma.ContentType, Boolean)
Stack trace: 
   at Barotrauma.GameMain.GetFilesOfType(ContentType type, Boolean searchAllContentPackages) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 695
   at Barotrauma.GameSettings.RefreshContentPackageItems(IEnumerable`1 files) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSettings.cs:line 614
   at Barotrauma.GameSettings.SelectCorePackage(ContentPackage contentPackage, Boolean forceReloadAll) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSettings.cs:line 356
   at Barotrauma.GameSettings.AutoSelectCorePackage(IEnumerable`1 toRemove) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSettings.cs:line 362
   at Barotrauma.GameSettings.SortContentPackages(Boolean refreshAll) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSettings.cs:line 479
   at Barotrauma.ContentPackage.SortContentPackages[T](Func`2 order, Boolean refreshAll, GameSettings config) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\ContentPackage.cs:line 823
   at Barotrauma.GameSettings.LoadContentPackages(XDocument doc) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSettings.cs:line 1576
   at Barotrauma.GameSettings.LoadPlayerConfigInternal() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSettings.cs:line 1059
   at Barotrauma.GameSettings.LoadPlayerConfig() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSettings.cs:line 1027
   at Barotrauma.GameSettings..ctor() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSettings.cs:line 806
   at Barotrauma.GameMain..ctor(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 211
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 57
```

**Steps To Reproduce**
Launch Barotrauma

**Version**
v0.14.9.1 Windows 10 64-bit

**Additional information**
Original crash log:
[message (1).txt](https://github.com/Regalis11/Barotrauma/files/7148146/message.1.txt)
After removing Mods and veryfying game files (the same stack trace)
[message (2).txt](https://github.com/Regalis11/Barotrauma/files/7148156/message.2.txt)

**Comment by drakebot5** [comment]
Im having the same issue and unsure how to fix it

**Comment by NilanthAnimosus** [comment]
Tested - Bug was caused by selecting a core content package back in 0.14.9.1 and then removing that core content package from the game folder. resulting in the same set of errors in the console and crash on the same line.

Tested the same against 0.18.9.0 and it correctly switches core content package if removed without errors.
