### ISSUE TITLE
Barotrauma Crash

### ISSUE THREAD

**Issue by Samsamsupersam27** [Regalis11/Barotrauma#6691]
Everytime when i start up Barotrauma it would give me this crash sign and say this 

Barotrauma Client crash report

Barotrauma seems to have crashed. Sorry for the inconvenience! 

48CA930394E1A7E117E5C694DE9CAF28

Game version 0.14.9.1 (ReleaseWindows, branch release, revision df0088ca33)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla 0.9
Level seed: no level loaded
Loaded submarine: None
Selected screen: None
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19043.0 64 bit
    GPU name: Intel(R) HD Graphics 630
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: One or more errors occurred. (Could not find a part of the path 'C:\Program Files (x86)\Steam\steamapps\common\Barotrauma\Mods\Let Me Choose ! I.T.A\.copying'.) (System.AggregateException)
Target site: Void ThrowIfExceptional(Boolean)
Stack trace: 
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Barotrauma.GameMain.<>c.<Load>b__98_0(Task task) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 475
   at Barotrauma.TaskPool.<>c__DisplayClass6_0.<Add>b__0(Task t, Object obj) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\TaskPool.cs:line 60
   at Barotrauma.TaskPool.Update() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\TaskPool.cs:line 77
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 995
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59

InnerException: Could not find a part of the path 'C:\Program Files (x86)\Steam\steamapps\common\Barotrauma\Mods\Let Me Choose ! I.T.A\.copying'.
Target site: Microsoft.Win32.SafeHandles.SafeFileHandle ValidateFileHandle(Microsoft.Win32.SafeHandles.SafeFileHandle)
Stack trace: 
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Barotrauma.Steam.SteamManager.CopyWorkShopItemAsync(Nullable`1 itemOrNull, ContentPackage contentPackage, String newContentPackagePath, String metaDataFilePath) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\SteamManager.cs:line 0
   at Barotrauma.Steam.SteamManager.AutoUpdateWorkshopItemsAsync() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\SteamManager.cs:line 1600
Last debug messages:
[19/09/2021 8:00:51 pm] Failed to copy "Let Me Choose ! I.T.A" {One or more errors occurred. (Could not find a part of the path 'C:\Program Files (x86)\Steam\steamapps\common\Barotrauma\Mods\Let Me Choose ! I.T.A\.copying'.)}

Inner exception: Could not find a part of the path 'C:\Program Files (x86)\Steam\steamapps\common\Barotrauma\Mods\Let Me Choose ! I.T.A\.copying'.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Barotrauma.Steam.SteamManager.CopyWorkShopItemAsync(Nullable`1 itemOrNull, ContentPackage contentPackage, String newContentPackagePath, String metaDataFilePath) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\SteamManager.cs:line 0
[19/09/2021 8:00:51 pm] Cannot create directory "Mods\Let Me Choose ! I.T.A": modifying the contents of this folder/using this extension is not allowed.
[19/09/2021 8:00:47 pm] Attempting to open ALC device "OpenAL Soft on Speakers (Realtek High Definition Audio)"
[19/09/2021 8:00:46 pm] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[19/09/2021 8:00:45 pm] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[19/09/2021 8:00:44 pm] Logged in as L0tuS (SteamID STEAM_1:0:559085413)

If anyone could help me fix this, it would be great

**Comment by Regalis11** [comment]
This seems to happen due to a bug that prevents the game from updating mods that have periods in their name (which causes the game to interpret the end of the name as an invalid file extension). Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2bf4d4b2b370ec5fc899d5d6ff817d4b15221e46

Until the fix is released, it should be possible to work around the issue by uninstalling the "Let Me Choose ! I.T.A" mod. Sorry for the inconvenience!

**Comment by Samsamsupersam27** [comment]
heyy it work, thank you for the help.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
