### ISSUE TITLE
Unstable - Player controlled humanhusks seem to freak out when using creature attacks, and cannot hit anything.

### ISSUE THREAD

**Issue by litrllyemma** [Regalis11/Barotrauma#6764]
- [✔️] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When trying to attack as a player controlled husk human, the animation bugged out and attacking anything was impossible. Upon testing further on a separate session, the animation for creature attack seems to be stuck on pulling me to a specific part of the ship, no matter how far away I am from it. Once again, even when this animation was not bugged I was unable to attack anyone. Upon running to that part that it was dragging me to while holding my creature attack key, I got the error in console pasted in Additional Info. Do note that the person was already dead, and turned into a husk aswell, and did not drag me to their current position, but instead a static position on the ship.

**Steps To Reproduce**
Use your creatureattack key as a player controlled huskhuman.

**Version**
Unstable v.01500.4.0, Windows 10

**Additional information**
The animation doesn't seem to always glitch out, and is fine at first, but the damage is always not there. As for what seems to be triggering the animations to break, I have no idea.

LOG START

Tried to apply an attack to a removed character (Ezequiel Mason).
   at System.Environment.get_StackTrace()
   at Barotrauma.Character.ApplyAttack(Character attacker, Vector2 worldPosition, Attack attack, Single deltaTime, Boolean playSound, Limb targetLimb, Single penetration)
   at Barotrauma.Character.AddDamage(Character attacker, Vector2 worldPosition, Attack attack, Single deltaTime, Boolean playSound)
   at Barotrauma.Attack.DoDamage(Character attacker, IDamageable target, Vector2 worldPosition, Single deltaTime, Boolean playSound, PhysicsBody sourceBody)
   at Barotrauma.Limb.ExecuteAttack(IDamageable damageTarget, Limb targetLimb, AttackResult& attackResult)
   at Barotrauma.Limb.UpdateAttack(Single deltaTime, Vector2 attackSimPos, IDamageable damageTarget, AttackResult& attackResult, Single distance, Limb targetLimb)
   at Barotrauma.Character.Control(Single deltaTime, Camera cam)
   at Barotrauma.Character.Update(Single deltaTime, Camera cam)
   at Barotrauma.AICharacter.Update(Single deltaTime, Camera cam)
   at Barotrauma.Character.UpdateAll(Single deltaTime, Camera cam)
   at Barotrauma.GameScreen.Update(Double deltaTime)
   at Barotrauma.GameMain.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Microsoft.Xna.Framework.Game.Run()
   at Barotrauma.Program.Main(String[] args)

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
