### ISSUE TITLE
[Unstable 0.1500.5.0] Game crashed when fighting against a Fractal Guardian with harpoons

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#6797]
Crash report from Unstable multiplayer testing, one of the testers was fighting against a Fractal Guardian that used a Harpoon Gun and they crashed. 

```
Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void Draw(Microsoft.Xna.Framework.Graphics.SpriteBatch, Boolean, Single)
Stack trace: 
   at Barotrauma.Items.Components.Rope.Draw(SpriteBatch spriteBatch, Boolean editing, Single itemDepth)
   at Barotrauma.Item.Draw(SpriteBatch spriteBatch, Boolean editing, Boolean back)
   at Barotrauma.Lights.LightManager.UpdateHighlights(GraphicsDevice graphics, SpriteBatch spriteBatch, Matrix spriteBatchTransform, Camera cam)
   at Barotrauma.Lights.LightManager.RenderLightMap(GraphicsDevice graphics, SpriteBatch spriteBatch, Camera cam, RenderTarget2D backgroundObstructor)
   at Barotrauma.GameScreen.DrawMap(GraphicsDevice graphics, SpriteBatch spriteBatch, Double deltaTime)
   at Barotrauma.GameScreen.Draw(Double deltaTime, GraphicsDevice graphics, SpriteBatch spriteBatch)
   at Barotrauma.GameMain.Draw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Microsoft.Xna.Framework.Game.Run()
   at Barotrauma.Program.Main(String[] args)
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6c6f41717abe145c4e96b1326be79c171eb41cbf
