### ISSUE TITLE
[Modding] Crash during loading screen when trying to load a mod

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#6813]
I didn't crash after launching the game for a second time so it doesn't seem to be a mod issue exactly, or at least doesn't seem that way. 

Branch: dev
Commit: https://github.com/Regalis11/Barotrauma-development/commit/5d7291bc2cf5a075f6a5dba0c0aa3eeb9160061a
Mods enabled: Stations from beyond https://steamcommunity.com/sharedfiles/filedetails/?id=2585543390

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/f2c170ab-7ba4-439e-b2ce-6167989a3373)

```
Barotrauma Client crash report (generated on 3.10.2021 12:15:23)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


0232C97DE23237FD7D5BE974E07F462D


Game version 0.1500.5.0 (ReleaseWindows, branch dev, revision 5d7291bc2c)
Graphics mode: 2560x1440 (BorderlessWindowed)
VSync OFF
Language: English
Selected content packages: Vanilla 0.9, Stations from beyond
Level seed: no level loaded
Loaded submarine: None
Selected screen: None
SteamManager initialized


System info:
    Operating system: Microsoft Windows NT 10.0.18363.0 64 bit
    GPU name: NVIDIA GeForce GTX 980 Ti
    Display mode: {Width:2560 Height:1440 Format:Color AspectRatio:1,7777778}
    GPU status: Normal


Exception: Value cannot be null. (Parameter 'source') (System.ArgumentNullException)
Target site: Void ThrowArgumentNullException(System.Linq.ExceptionArgument)
Stack trace: 
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at Barotrauma.NPCSet.Get(String identifier, String npcidentifier) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Outposts\NPCSet.cs:line 32
   at Barotrauma.OutpostGenerationParams..ctor(XElement element, String filePath) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Outposts\OutpostGenerationParams.cs:line 137
   at Barotrauma.OutpostGenerationParams.LoadPresets() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Outposts\OutpostGenerationParams.cs:line 229
   at Barotrauma.GameSettings.RefreshContentPackageItems(IEnumerable`1 files) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSettings.cs:line 629
   at Barotrauma.GameSettings.EnableRegularPackage(ContentPackage contentPackage) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSettings.cs:line 435
   at Barotrauma.Steam.SteamManager.<>c__DisplayClass43_0.<InstallWorkshopItem>b__2(Task task, ContentPackage cp) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\SteamManager.cs:line 1128
   at Barotrauma.TaskPool.<>c__DisplayClass7_0`1.<Add>b__0(Task t, Object obj) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\TaskPool.cs:line 65
   at Barotrauma.TaskPool.Update() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\TaskPool.cs:line 77
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 1014
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 60


Last debug messages:
[3.10.2021 12:15:16] Attempting to open ALC device "OpenAL Soft on Kaiuttimet (Realtek High Definition Audio)"
[3.10.2021 12:15:15] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[3.10.2021 12:15:15] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
```

**Comment by JoneKone** [comment]
Server crashed.


```
﻿Barotrauma Dedicated Server crash report (generated on 11/23/2021 9:51:26 PM)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


Game version 0.15.13.0 (ReleaseLinux, branch master, revision 5c6450c6a)
Language: English
Selected content packages: Vanilla 0.9, Matilda, Sever, Apo-4A Saber ENGLISH, Super Plague Rat 1.0.0, The Ultimatum, SSN-Honkmother, R-29 Hammerhead, Belfast, Sardiini MK.II, [VH] The Iroh, THT Death Squad, B-71 sub-fortress, Vengeance, Type 7 Akimbo SG, Zidrom MKVI, Salut11, [AP] Tanit, Glass Shuttle, Project-705k Lyra, Sardiini MK.I
Level seed: zobFdGvQ
Loaded submarine: Mazara (Missions) (9112B47B704E09A9D113F11EB93B0ED2)
Selected screen: Barotrauma.GameScreen
Server (Round had started)


System info:
    Operating system: Unix 4.19.0.16 64 bit


Exception: Value cannot be null. (Parameter 'collection') (System.ArgumentNullException)
Target site: Void ThrowArgumentNullException(System.ExceptionArgument)
Stack trace: 
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Barotrauma.Abilities.CharacterAbilityModifyAttackData.ApplyEffect(AbilityObject abilityObject)
   at Barotrauma.Abilities.CharacterAbilityGroupEffect.CheckAbilityGroup(AbilityObject abilityObject)
   at Barotrauma.CharacterTalent.CheckTalent(AbilityEffectType abilityEffectType, AbilityObject abilityObject)
   at Barotrauma.Character.CheckTalents(AbilityEffectType abilityEffectType, AbilityObject abilityObject)
   at Barotrauma.Character.ApplyAttack(Character attacker, Vector2 worldPosition, Attack attack, Single deltaTime, Boolean playSound, Limb targetLimb, Single penetration)
   at Barotrauma.Attack.DoDamageToLimb(Character attacker, Limb targetLimb, Vector2 worldPosition, Single deltaTime, Boolean playSound, PhysicsBody sourceBody)
   at Barotrauma.Items.Components.MeleeWeapon.HandleImpact(Body target)
   at Barotrauma.Items.Components.MeleeWeapon.Update(Single deltaTime, Camera cam)
   at Barotrauma.Item.Update(Single deltaTime, Camera cam)
   at Barotrauma.MapEntity.UpdateAll(Single deltaTime, Camera cam)
   at Barotrauma.GameScreen.Update(Double deltaTime)
   at Barotrauma.GameMain.Run()
   at Barotrauma.Program.Main(String[] args)


Last debug messages:
   11/23/2021 9:51:26 PM - [11/23/2021 9:51:26 PM]
  Saving banlist
   11/23/2021 9:51:23 PM - [11/23/2021 9:51:23 PM]
  Hank launched Coilgun (projectile: Coilgun Bolt)
   11/23/2021 9:51:19 PM - [11/23/2021 9:51:19 PM]
  JoneK placed Diving Suit in Diving Suit Locker (ID: 419)
   11/23/2021 9:51:14 PM - [11/23/2021 9:51:14 PM]
  Kelbor Hal dropped ID Card
   11/23/2021 9:51:13 PM - [11/23/2021 9:51:13 PM]
  JoneK unequipped Wrench
   11/23/2021 9:51:13 PM - [11/23/2021 9:51:13 PM]
  JoneK unequipped Screwdriver
   11/23/2021 9:51:13 PM - [11/23/2021 9:51:13 PM]
  Kelbor Hal placed Headset in Explosive Crate (ID: 738)
   11/23/2021 9:51:12 PM - [11/23/2021 9:51:12 PM]
  Rehex equipped Wrench
   11/23/2021 9:51:12 PM - [11/23/2021 9:51:12 PM]
  Rehex equipped Wrench
   11/23/2021 9:51:11 PM - [11/23/2021 9:51:11 PM]
  Kelbor Hal dropped Assistant Clothes
   11/23/2021 9:51:11 PM - [11/23/2021 9:51:11 PM]
  szkiller placed Morphine in Medic's Fatigues (ID: 9867)
   11/23/2021 9:51:11 PM - [11/23/2021 9:51:11 PM]
  szkiller placed Morphine in Medic's Fatigues (ID: 9867)
   11/23/2021 9:51:11 PM - [11/23/2021 9:51:11 PM]
  szkiller placed Morphine in Medic's Fatigues (ID: 9867)
   11/23/2021 9:51:10 PM - [11/23/2021 9:51:10 PM]
  Buster Tuff used item Ethanol
```

**Comment by Regalis11** [comment]
I don't think this can happen any longer after the modding refactor. It seems the issue was that we tried to find the human prefabs that are referenced in the outpost generation parameters, which meant the human prefabs always needed to be loaded before the generation params. If it was done in the wrong order, it'd lead to this exception. Now we just load the identifiers of the human prefabs, and don't try to find the human prefabs until we actually generate the outpost.
