### ISSUE TITLE
Ask for help. Please help me.

### ISSUE THREAD

**Issue by 0115liang** [Regalis11/Barotrauma#6832]
Barotrauma Client crash report (generated on 2021/10/5 10:28:45)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

30C54684AA148E0CE8B2F75522B1FE39

Game version 0.9.7.1 (ReleaseWindows, branch release, revision 6ec75fa2a)
Graphics mode: 1600x900 (BorderlessWindowed)
VSync ON
Selected content packages: Vanilla 0.9
Level seed: no level loaded
Loaded submarine: None
Selected screen: None
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 6.2.9200.0 64 bit
    GPU name: Intel(R) UHD Graphics 610
    Display mode: {Width:1536 Height:864 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Loading was interrupted due to an error: Could not load file or assembly 'RestSharp, Version=106.6.10.0, Culture=neutral, PublicKeyToken=598062e77f915f75'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
   at Barotrauma.MainMenuScreen.FetchRemoteContent()
   at Barotrauma.MainMenuScreen..ctor(GameMain game) in E:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Screens\MainMenuScreen.cs:line 103
   at Barotrauma.GameMain.Load(Boolean isSeparateThread)+MoveNext() in E:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 525
   at Barotrauma.CoroutineManager.ExecuteCoroutineThread(CoroutineHandle handle) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 167 (System.Exception)
Target site: Void Update(Microsoft.Xna.Framework.GameTime)
Stack trace: 
   at Barotrauma.GameMain.Update(GameTime gameTime) in E:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 749
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in E:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 42

Last debug messages:
[2021/10/5 10:28:45] Coroutine "Load" has failed
[2021/10/5 10:28:45] Coroutine "Load" has thrown an exception {Could not load file or assembly 'RestSharp, Version=106.6.10.0, Culture=neutral, PublicKeyToken=598062e77f915f75'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)}
   at Barotrauma.MainMenuScreen.FetchRemoteContent()
   at Barotrauma.MainMenuScreen..ctor(GameMain game) in E:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Screens\MainMenuScreen.cs:line 103
   at Barotrauma.GameMain.Load(Boolean isSeparateThread)+MoveNext() in E:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 525
   at Barotrauma.CoroutineManager.ExecuteCoroutineThread(CoroutineHandle handle) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 167
[2021/10/5 10:28:37] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[2021/10/5 10:28:37] Content package load order: Vanilla 0.9
[2021/10/5 10:28:35] Attempting to open ALC device "OpenAL Soft"
[2021/10/5 10:28:34] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[2021/10/5 10:28:34] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[2021/10/5 10:28:33] Logged in as Goldberg (SteamID STEAM_1:0:233076535)

**Comment by Regalis11** [comment]
This seems to be an old game version (from early 2020), I recommend updating to the latest one and checking if that helps!
