### ISSUE TITLE
Null Reference Exception on Character.cs Line 1352

### ISSUE THREAD

**Issue by Regretful123** [Regalis11/Barotrauma#6855]
- [ x ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
One of our crew got disconnected randomly from the part. After rejoin, a few minutes as gone by and game crashed stating that there's a null in the string variable under character.cs @ line 1352

**Steps To Reproduce**
Do not know how to replicate this. This appears to be an issue with networking sync with character class? Also I'm quite impress that you are using Microsoft XNA's game engine to make this game. Well done!

**Version**
Game version 0.14.9.1 (ReleaseWindows, branch release, revision df0088ca33)

**Additional information**
Barotrauma Client crash report (generated on 10/7/2021 7:40:16 PM)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

48CA930394E1A7E117E5C694DE9CAF28

Game version 0.14.9.1 (ReleaseWindows, branch release, revision df0088ca33)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla 0.9
Level seed: FalgaTectamus Linea
Loaded submarine: None
Selected screen: Barotrauma.MainMenuScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19043.0 64 bit
    GPU name: NVIDIA GeForce GTX 1080
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: System.String ToString()
Stack trace: 
   at Barotrauma.Character.ToString() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 1352
   at Barotrauma.Entity.RemoveAll() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Entity.cs:line 148
   at Barotrauma.Submarine.Unload() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Submarine.cs:line 1697
   at Barotrauma.MainMenuScreen.Select() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\MainMenuScreen.cs:line 500
   at Barotrauma.MainMenuScreen.ReturnToMainMenu(GUIButton button, Object obj) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\MainMenuScreen.cs:line 696
   at Barotrauma.GUIButton.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIButton.cs:line 262
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Barotrauma.GUI.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1244
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 986
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[10/7/2021 7:39:58 PM] LobbyMatchList:  LobbiesMatching: 0
[10/7/2021 7:39:58 PM] LobbyMatchList:  LobbiesMatching: 0
[10/7/2021 7:39:58 PM] SteamAPICallCompleted:   AsyncCall: 13139903328336192803
   Callback: 510
 ParamCount: 4
[10/7/2021 7:39:58 PM] LobbyMatchList:  LobbiesMatching: 25
[10/7/2021 7:39:58 PM] LobbyMatchList:  LobbiesMatching: 25
[10/7/2021 7:39:58 PM] SteamAPICallCompleted:   AsyncCall: 10211345630662922972
   Callback: 510
 ParamCount: 4
[10/7/2021 7:39:58 PM] PersonaStateChange:      SteamID: 76561198011858175
 ChangeFlags: 2
[10/7/2021 7:39:58 PM] LobbyMatchList:  LobbiesMatching: 50
[10/7/2021 7:39:58 PM] LobbyMatchList:  LobbiesMatching: 50

**Comment by Regalis11** [comment]
Thank you for the report!

This is a strange one. Looking at the line in question, it shouldn't be throwing nullref exceptions:
`return (info != null && !string.IsNullOrWhiteSpace(info.Name)) ? info.Name : SpeciesName;`
The only explanation I can think of is that this is a multithreading issue, and that the info got set to null in another branch while this method was running. Moreover, the method was being called to log an error, which failed because of this exception, so we don't know what that initial error was. :/

In any case, we'll keep an eye out for this and hopefully figure out a way to diagnose it.

> I'm quite impress that you are using Microsoft XNA's game engine to make this game. Well done!

Thank you. :) We're actually using MonoGame though: it just uses the same namespaces as XNA to maintain some degree of compatibility with XNA projects.

**Comment by Regalis11** [comment]
No known steps to repro, closing
