### ISSUE TITLE
[crash] Exception: The path is empty.

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#6888]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When I edit a spritesheet in sprite editor and I click "Save selected sprites", I keep getting this error, no idea why:
```
Exception: The path is empty. (Parameter 'path') (System.ArgumentException)
Target site: System.String GetFullPath(System.String)
Stack trace: 
   at System.IO.Path.GetFullPath(String path)
   at Barotrauma.IO.Validation.CanWrite(String path, Boolean isDirectory) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SafeIO.cs:line 0
   at Barotrauma.IO.SafeXML.SaveSafe(XDocument doc, String path) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SafeIO.cs:line 61
   at Barotrauma.SpriteEditorScreen.SaveSprites(IEnumerable`1 sprites) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\SpriteEditorScreen.cs:line 441
   at Barotrauma.SpriteEditorScreen.<CreateUI>b__37_8(GUIButton button, Object userData) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\SpriteEditorScreen.cs:line 130
   at Barotrauma.GUIButton.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIButton.cs:line 262
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Barotrauma.GUI.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1244
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 986
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59
```

**Steps To Reproduce**
???

**Version**
v0.14.9.1

**Additional information**
There's a lot of errors in this crash report but why? Everything seems to override just fine.
[crashreport (7).log](https://github.com/Regalis11/Barotrauma/files/7318776/crashreport.7.log)

**Comment by NilanthAnimosus** [comment]
Tested on 0.14.9.1 and reproduced by modifying an active mods sprites with the XDocument.Uri being "" for any modded item's XML doc.

Tested on version 0.18.9.0 with both workshop and local mods, Found the bug now appears to be resolved.
