### ISSUE TITLE
Game crashes when enter a new location

### ISSUE THREAD

**Issue by SadBoto** [Regalis11/Barotrauma#7096]
Barotrauma Client crash report (generated on 30/10/2021 15:31:30)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

0120CFF13F68A29ABC62BE1077A0F8E0

Game version 0.15.12.0 (ReleaseWindows, branch release, revision 575e12eab6)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla 0.9, DIY Reactor Controllers
Level seed: Corick LineaSparti Linea
Loaded submarine: Remora (AED25C2E87561DC9782A53CD1F279157)
Selected screen: Barotrauma.GameScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19042.0 64 bit
    GPU name: Radeon RX 560 Series
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1,7777778}
    GPU status: Normal

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Int32 NumberOfMissionsAtLocation(Barotrauma.Location)
Stack trace: 
   at Barotrauma.CampaignMode.NumberOfMissionsAtLocation(Location location) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameModes\CampaignMode.cs:line 910
   at Barotrauma.CampaignUI.<>c__DisplayClass47_0.<SelectLocation>b__7() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\CampaignUI.cs:line 631
   at Barotrauma.GUITextBlock.Draw(SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITextBlock.cs:line 682
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Barotrauma.GUI.Draw(Camera cam, SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 333
   at Barotrauma.GameScreen.Draw(Double deltaTime, GraphicsDevice graphics, SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\GameScreen.cs:line 161
   at Barotrauma.GameMain.Draw(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 1057
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 669
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 508
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59

Last debug messages:
[30/10/2021 15:31:21] Generating an outpost for the end of the level... (Location: Sparti Linea, level type: LocationConnection)
[30/10/2021 15:30:11] Could not move to the next location (no connection selected).
   at System.Environment.get_StackTrace()
   at Barotrauma.Map.MoveToNextLocation() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Map\Map.cs:line 670
   at Barotrauma.SinglePlayerCampaign.DoLevelTransition(TransitionType transitionType, LevelData newLevel, Submarine leavingSub, Boolean mirror, List`1 traitorResults)+MoveNext() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameSession\GameModes\SinglePlayerCampaign.cs:line 411
   at Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 213
   at Barotrauma.CoroutineManager.Update(Single unscaledDeltaTime, Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 254
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 1010
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 651
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 60
[30/10/2021 15:30:10] Transitioning to Corick Linea (current location: Sparti Linea, selected location: null, leaving sub: Remora, at start: False, at end: True, transition type: ProgressToNextLocation)
[30/10/2021 15:14:32] Generating an outpost for the end of the level... (Location: Sparti Linea, level type: LocationConnection)
[30/10/2021 15:14:05] Transitioning to Corick LineaSparti Linea (current location: Sparti Linea, selected location: Corick Linea Mining Claim, leaving sub: Remora, at start: False, at end: True, transition type: ProgressToNextEmptyLocation)
[30/10/2021 14:35:40] Generating an outpost for the start of the level... (Location: Arid Troma Station, level type: LocationConnection)
[30/10/2021 14:33:05] Generating an outpost for the start of the level... (Location: Arid Troma Station, level type: LocationConnection)
[30/10/2021 14:32:47] Transitioning to Arid TromaSparti Linea (current location: Arid Troma Station, selected location: Sparti Linea, leaving sub: Remora, at start: True, at end: False, transition type: LeaveLocation)
[30/10/2021 14:27:25] Unlocked mission "Killing a Hammerhead" in the location "Arid Troma Station".
[30/10/2021 14:27:06] Unlocked mission "Destroy a Crawler nest" in the location "Arid Troma Station".
[30/10/2021 14:27:04] Unlocked mission "Terrorist Stakeout" in the location "Arid Troma Station".
[30/10/2021 14:20:33] Generating an outpost for the start of the level... (Location: Arid Troma Station, level type: Outpost)
[30/10/2021 14:05:54] Unlocked mission "Pirate Vessel" in the location "Arid Troma Station".
[30/10/2021 14:05:51] Unlocked mission "Handle with care" in the location "Arid Troma Station".
[30/10/2021 14:00:19] Generating an outpost for the start of the level... (Location: Arid Troma Station, level type: Outpost)
[30/10/2021 14:00:06] Transitioning to Arid Troma (current location: Serac Outpost, selected location: Arid Troma Station, leaving sub: Remora, at start: False, at end: True, transition type: ProgressToNextLocation)
[30/10/2021 13:51:35] Generating an outpost for the start of the level... (Location: Arid Troma Station, level type: LocationConnection)
[30/10/2021 13:51:34] Generating an outpost for the end of the level... (Location: Serac Outpost, level type: LocationConnection)
[30/10/2021 13:51:15] Transitioning to Arid TromaSerac (current location: Serac Outpost, selected location: Arid Troma Station, leaving sub: Remora, at start: True, at end: False, transition type: LeaveLocation)
[30/10/2021 13:45:00] Unlocked mission "Explosive cargo" in the location "Serac Outpost".
[30/10/2021 13:44:40] Unlocked mission "Destroy a Crawler nest" in the location "Serac Outpost".
[30/10/2021 13:44:38] Unlocked mission "Destroy a Tiger Thresher nest" in the location "Serac Outpost".
[30/10/2021 13:40:32] Generating an outpost for the start of the level... (Location: Serac Outpost, level type: Outpost)
[30/10/2021 13:40:19] Transitioning to Serac (current location: Wolstone Outpost, selected location: Serac Outpost, leaving sub: Remora, at start: False, at end: True, transition type: ProgressToNextLocation)
[30/10/2021 13:08:02] Generating an outpost for the end of the level... (Location: Serac Outpost, level type: LocationConnection)
[30/10/2021 13:08:01] Generating an outpost for the start of the level... (Location: Wolstone Outpost, level type: LocationConnection)
[30/10/2021 13:07:40] Transitioning to WolstoneSerac (current location: Wolstone Outpost, selected location: Serac Outpost, leaving sub: Remora, at start: True, at end: False, transition type: LeaveLocation)
[30/10/2021 12:26:16] Unlocked mission "Killing a Moloch" in the location "Wolstone Outpost".
[30/10/2021 12:26:02] Unlocked mission "Salvaging an artifact" in the location "Wolstone Outpost".
[30/10/2021 12:25:59] Unlocked mission "VIP Transport" in the location "Wolstone Outpost".
[30/10/2021 12:14:05] Generating an outpost for the start of the level... (Location: Wolstone Outpost, level type: Outpost)
[30/10/2021 12:13:52] Transitioning to Wolstone (current location: Rhadamanthys Linea Fortification, selected location: Wolstone Outpost, leaving sub: Remora, at start: False, at end: True, transition type: ProgressToNextLocation)
[30/10/2021 12:04:43] Generating an outpost for the end of the level... (Location: Wolstone Outpost, level type: LocationConnection)
[30/10/2021 12:04:42] Generating an outpost for the start of the level... (Location: Rhadamanthys Linea Fortification, level type: LocationConnection)
[30/10/2021 12:04:26] Transitioning to Rhadamanthys LineaWolstone (current location: Rhadamanthys Linea Fortification, selected location: Wolstone Outpost, leaving sub: Remora, at start: True, at end: False, transition type: LeaveLocation)
[30/10/2021 12:03:56] Unlocked mission "Pirate Vessel" in the location "Rhadamanthys Linea Fortification".
[30/10/2021 12:03:54] Unlocked mission "Destroy a Crawler nest" in the location "Rhadamanthys Linea Fortification".
[30/10/2021 12:02:59] Unlocked mission "Praise the honkmother" in the location "Rhadamanthys Linea Fortification".
[30/10/2021 11:57:11] Generating an outpost for the start of the level... (Location: Rhadamanthys Linea Fortification, level type: Outpost)
[30/10/2021 11:56:59] Transitioning to Rhadamanthys Linea (current location: Kennet Linea Research Facility, selected location: Rhadamanthys Linea Fortification, leaving sub: Remora, at start: False, at end: True, transition type: ProgressToNextLocation)
[30/10/2021 11:32:11] Generating an outpost for the end of the level... (Location: Rhadamanthys Linea Fortification, level type: LocationConnection)
[30/10/2021 11:32:11] Generating an outpost for the start of the level... (Location: Kennet Linea Research Facility, level type: LocationConnection)
[30/10/2021 11:31:54] Transitioning to Kennet LineaRhadamanthys Linea (current location: Kennet Linea Research Facility, selected location: Rhadamanthys Linea Fortification, leaving sub: Remora, at start: True, at end: False, transition type: LeaveLocation)
[30/10/2021 11:09:42] Unlocked mission "Killing a Moloch" in the location "Kennet Linea Research Facility".
[30/10/2021 11:09:10] Unlocked mission "Pirate Vessel" in the location "Kennet Linea Research Facility".
[30/10/2021 11:09:07] Unlocked mission "Chemical shipment" in the location "Kennet Linea Research Facility".
[30/10/2021 11:07:29] Generating an outpost for the start of the level... (Location: Kennet Linea Research Facility, level type: Outpost)
[30/10/2021 11:06:49] (Msg) SDR RelayNetworkStatus:  avail=OK  config=OK  anyrelay=OK   (OK)
[30/10/2021 11:06:49] (Msg) Ping location: gru=25+2,eze=37+3,scl=56+5/57+3,lim=87+8/86+3,iad=153+15,atl=143+14/155+2,ord=169+16/161+14,dfw=164+16/164+14,lax=192+19/188+3,sea=202+20/211+3,fra=224+22/225+21,sgp=365+36/373+29
[30/10/2021 11:06:49] (Msg) Ping measurement completed
[30/10/2021 11:06:49] (Debug) Destroying relay 'sof#3 (139.45.193.10:27017)' because initial_ping_timeout
[30/10/2021 11:06:49] (Debug) Destroying relay 'eat#45 (155.133.235.34:27021)' because initial_ping_timeout
[30/10/2021 11:06:47] (Debug) Destroying relay 'sof#1 (139.45.193.10:27015)' because initial_ping_timeout
[30/10/2021 11:06:46] (Debug) Destroying relay 'eat#37 (155.133.235.18:27051)' because initial_ping_timeout
[30/10/2021 11:06:44] (Verbose) Communications with routing cluster 'waw' established.
[30/10/2021 11:06:44] (Verbose) Communications with routing cluster 'sgp' established.
[30/10/2021 11:06:44] (Verbose) Communications with routing cluster 'seo' established.
[30/10/2021 11:06:44] (Verbose) Communications with routing cluster 'syd' established.
[30/10/2021 11:06:44] (Verbose) Communications with routing cluster 'tyo1' established.
[30/10/2021 11:06:44] (Verbose) Communications with routing cluster 'tyo' established.
[30/10/2021 11:06:44] (Verbose) Communications with routing cluster 'maa' established.
[30/10/2021 11:06:44] (Verbose) Communications with routing cluster 'jnb' established.
[30/10/2021 11:06:44] (Verbose) Communications with routing cluster 'sto' established.
[30/10/2021 11:06:44] (Verbose) Communications with routing cluster 'sto2' established.
[30/10/2021 11:06:44] (Verbose) Communications with routing cluster 'vie' established.
[30/10/2021 11:06:44] (Verbose) Communications with routing cluster 'dxb' established.
[30/10/2021 11:06:44] (Verbose) Communications with routing cluster 'sea' established.
[30/10/2021 11:06:44] (Verbose) Communications with routing cluster 'bom' established.
[30/10/2021 11:06:44] (Verbose) Communications with routing cluster 'mad' established.
[30/10/2021 11:06:44] (Verbose) Communications with routing cluster 'hkg' established.
[30/10/2021 11:06:44] (Verbose) Communications with routing cluster 'par' established.
[30/10/2021 11:06:44] (Verbose) Communications with routing cluster 'lhr' established.
[30/10/2021 11:06:44] (Verbose) Communications with routing cluster 'lax' established.
[30/10/2021 11:06:44] (Verbose) Communications with routing cluster 'ord' established.
[30/10/2021 11:06:44] (Verbose) Communications with routing cluster 'iad' established.
[30/10/2021 11:06:44] (Verbose) Communications with routing cluster 'fra' established.
[30/10/2021 11:06:44] (Verbose) Communications with routing cluster 'ams' established.
[30/10/2021 11:06:44] (Verbose) Communications with routing cluster 'lim' established.
[30/10/2021 11:06:44] (Verbose) Communications with routing cluster 'dfw' established.
[30/10/2021 11:06:44] (Verbose) Communications with routing cluster 'scl' established.
[30/10/2021 11:06:44] (Verbose) Communications with routing cluster 'atl' established.
[30/10/2021 11:06:44] (Verbose) Communications with routing cluster 'eze' established.
[30/10/2021 11:06:44] (Verbose) Communications with routing cluster 'gru' established.
[30/10/2021 11:06:44] (Msg) SDR RelayNetworkStatus:  avail=Attempting  config=OK  anyrelay=Attempting   (Performing ping measurement)
[30/10/2021 11:06:44] (Msg) Performing ping measurement
[30/10/2021 11:06:44] (Msg) Got SDR network config.  Loaded revision 343 OK
[30/10/2021 11:06:44] (Warning) SDR network config fetch first attempt failed.  HTTP 504.  .  Trying again.
[30/10/2021 11:06:35] Attempting to open ALC device "OpenAL Soft on Alto-falantes (Realtek High Definition Audio)"
[30/10/2021 11:06:34] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[30/10/2021 11:06:33] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[30/10/2021 11:06:31] Logged in as KneeGgar (SteamID STEAM_1:1:56850345)

**Comment by Regalis11** [comment]
Potentially fixed in https://github.com/Regalis11/Barotrauma-development/commit/53514deb96991c419dbcbaabff6a939d8d4c2857

**Comment by Rokvach** [comment]
There hasn't been any encounters to this issue in the Unstable build, seems to be working correctly. Closing.
