### ISSUE TITLE
Crashed after someone deconstructed a harpoon gun full of harpoons

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#7143]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
This was posted on the #baro-tech-support channel on Discord

**Steps To Reproduce**
Haven't managed to reproduce the issue

**Version**
0.15.13.0 Stable

**Additional information**

Crash report:

```
Barotrauma Client crash report (generated on 11/1/2021 8:25:07 PM)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


0120CFF13F68A29ABC62BE1077A0F8E0


Game version 0.15.12.0 (ReleaseWindows, branch release, revision 575e12eab6)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla 0.9, R-29 Hammerhead, Leviathan
Level seed: VortaPhoenix Linea
Loaded submarine: Typhon (D7B244B38975FC1F85DB02A0A6515EE8)
Selected screen: Barotrauma.GameScreen
SteamManager initialized
Client (Round had started)


System info:
    Operating system: Microsoft Windows NT 6.1.7601 Service Pack 1 64 bit
    GPU name: NVIDIA GeForce GTX 950
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal


Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Microsoft.Xna.Framework.Vector2 get_TransformedBarrelPos()
Stack trace: 
   at Barotrauma.Items.Components.RangedWeapon.get_TransformedBarrelPos() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Holdable\RangedWeapon.cs:line 78
   at Barotrauma.Items.Components.Rope.Draw(SpriteBatch spriteBatch, Boolean editing, Single itemDepth) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Components\Rope.cs:line 152
   at Barotrauma.Item.Draw(SpriteBatch spriteBatch, Boolean editing, Boolean back) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Item.cs:line 473
   at Barotrauma.Submarine.DrawBack(SpriteBatch spriteBatch, Boolean editing, Predicate`1 predicate) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Map\Submarine.cs:line 353
   at Barotrauma.GameScreen.DrawMap(GraphicsDevice graphics, SpriteBatch spriteBatch, Double deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\GameScreen.cs:line 241
   at Barotrauma.GameScreen.Draw(Double deltaTime, GraphicsDevice graphics, SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\GameScreen.cs:line 124
   at Barotrauma.GameMain.Draw(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 1057
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 669
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 508
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59
```

**Comment by ekqvist** [comment]
Seems to be the same stack trace as in #7020. Duplicate?

**Comment by Rokvach** [comment]
Didn't check the game version on the crash report, this is most likely already fixed

**Comment by Rokvach** [comment]
Yeah forgot to check when this was posted in the channel too <_< Closing as this issue has been fixed.
