### ISSUE TITLE
Crashed after used an modded Fabricator after the last Update

### ISSUE THREAD

**Issue by DivineX7** [Regalis11/Barotrauma#7156]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Hello,
Iam Using a modded Fabricator which worked well before the Ancient Update, the fabricator is creating food to consume.
Another modded Fabricator is working well, what have changed with the last update. 
I can understand that you don't give support on mods, but can you explain me the error message?

Error log:
Barotrauma Client crash report (generated on 02.11.2021 19:58:28)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

53369B525C73F08AF404DBAF116B0ADA

Game version 0.15.13.0 (ReleaseWindows, branch release, revision 4e66dd7b5d)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync OFF
Language: German
Selected content packages: Vanilla 0.9, U797-Community Mod
Level seed: no level loaded
Loaded submarine: A_Test (21F1C63444D2CEC30A832D4924D44320)
Selected screen: Barotrauma.GameScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19042.0 64 bit
    GPU name: NVIDIA GeForce GTX 1660 Ti
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1,7777778}
    GPU status: Normal

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void Update(Single, Barotrauma.Camera)
Stack trace: 
   at Barotrauma.Items.Components.Fabricator.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Machines\Fabricator.cs:line 284
   at Barotrauma.Item.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 1662
   at Barotrauma.MapEntity.UpdateAll(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\MapEntity.cs:line 567
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 264
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 981
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 60

**Comment by Regalis11** [comment]
Thank you for the report!

This seems to have been caused by an oversight that crashed the game if the fabricator doesn't have a Repairable component. I fixed it in https://github.com/Regalis11/Barotrauma-development/commit/eb038b7d6c99e7c8abd222bb8885c8baadd2f797, but until the fix is out, it should be possible to work around the problem by adding a Repairable component to the device.

**Comment by DivineX7** [comment]
Thank you a lot @Regalis11, keep up the good work
