### ISSUE TITLE
Crash in Barotrauma.NetLobbyScreen.UpdateJobPreferences

### ISSUE THREAD

**Issue by Hegny** [Regalis11/Barotrauma#7204]
- [ Yes] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Talent tab does not update properly if a round started as an observer and a player gets control on human later. The client crashes every time. Checked at several machines with different dedicated servers.

**Steps To Reproduce**
1. Connect to a dedicated server.
2. Start round as an observer
3. Take control on any human (I have tried only bots so far)
4. Open Tab-window
5. Click Talent button.

**Version**
Game version 0.15.13.0 
Windows

**Additional information**
Crashreport:

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void UpdateJobPreferences()
Stack trace: 
   at Barotrauma.NetLobbyScreen.UpdateJobPreferences() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\NetLobbyScreen.cs:line 3201
   at Barotrauma.NetLobbyScreen.UpdatePlayerFrame(CharacterInfo characterInfo, Boolean allowEditing, GUIComponent parent, Boolean createPendingText) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\NetLobbyScreen.cs:line 1560
   at Barotrauma.NetLobbyScreen.CreatePlayerFrame(GUIComponent parent, Boolean createPendingText, Boolean alwaysAllowEditing) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\NetLobbyScreen.cs:line 1411
   at Barotrauma.TabMenu.CreateTalentInfo(GUIFrame infoFrame) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\TabMenu.cs:line 1248
   at Barotrauma.TabMenu.SelectInfoFrameTab(GUIButton button, Object userData) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\TabMenu.cs:line 320
   at Barotrauma.GUIButton.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIButton.cs:line 262
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Barotrauma.GUI.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1253
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 1005
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 60

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/58327546f9e62b62ffefb42b2a0e1ced48d29da8

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
