### ISSUE TITLE
Game Crash on Server Host: Index out of Range

### ISSUE THREAD

**Issue by u7120482** [Regalis11/Barotrauma#7276]
My friends and I have all individually tried to host a server, and are all receiving near-identical crash reports. This issue occurs whenever we try to host a game, the game crashes immediately straight to desktop with an "Exception: Index was out of range" error in the crash report.

Here is my particular crash report:

```
Barotrauma Client crash report (generated on 11/12/2021 11:38:43 PM)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


D5EB38A63483E94A91461F9E0F4F90C5


Game version 0.15.13.0 (ReleaseMac, branch release, revision 4e66dd7b5d)
Graphics mode: 1920x1080 (Windowed)
VSync ON
Language: English
Selected content packages: Vanilla 0.9
Level seed: no level loaded
Loaded submarine: None
Selected screen: Barotrauma.NetLobbyScreen
SteamManager initialized
Client (Round hadn't been started)


System info:
    Operating system: Unix 21.1.0.0 64 bit
    GPU name: 
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal


Exception: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index') (System.ArgumentOutOfRangeException)
Target site: Void ThrowArgumentOutOfRange_IndexException()
Stack trace: 
   at Barotrauma.ScalableFont.DrawStringWithColors(SpriteBatch sb, String text, Vector2 position, Color color, Single rotation, Vector2 origin, Vector2 scale, SpriteEffects se, Single layerDepth, List`1 richTextData, Int32 rtdOffset) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Fonts/ScalableFont.cs:line 439
   at Barotrauma.GUITextBlock.Draw(SpriteBatch spriteBatch) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/GUI/GUITextBlock.cs:line 682
   at Barotrauma.GUIComponent.DrawManually(SpriteBatch spriteBatch, Boolean alsoChildren, Boolean recursive) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/GUI/GUIComponent.cs:line 568
   at Barotrauma.GUIListBox.Draw(SpriteBatch spriteBatch) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/GUI/GUIListBox.cs:line 1063
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Barotrauma.GUI.Draw(Camera cam, SpriteBatch spriteBatch) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/GUI/GUI.cs:line 333
   at Barotrauma.NetLobbyScreen.Draw(Double deltaTime, GraphicsDevice graphics, SpriteBatch spriteBatch) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Screens/NetLobbyScreen.cs:line 2593
   at Barotrauma.GameMain.Draw(GameTime gameTime) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/GameMain.cs:line 1062
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime) in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 669
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 511
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/SDL/SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Program.cs:line 61


Last debug messages:
[11/12/2021 11:35:28 PM] External Microphone 19
[11/12/2021 11:35:20 PM] External Microphone 19
[11/12/2021 11:34:33 PM] (Msg) SDR RelayNetworkStatus:  avail=OK  config=OK  anyrelay=OK   (OK)
[11/12/2021 11:34:33 PM] (Msg) Ping location: syd=8+0,sgp=100+10/96+10,hkg=132+13/125+10,maa=416+41/128+10,sea=148+14/145+10,bom=411+41/153+10,seo=209+20/166+10,lax=171+17/168+10,tyo=173+17,iad=285+28/208+10,fra=297+29/288+10,gru=323+32/322+29
[11/12/2021 11:34:33 PM] (Msg) Ping measurement completed
[11/12/2021 11:34:30 PM] (Warning) SteamNetworkingSockets lock held for 8.4ms.  (Performance warning.)  ServiceThread,RecvUDPPacket(x2)
This is usually a symptom of a general performance problem such as thread starvation.
[11/12/2021 11:34:30 PM] (Verbose) Communications with routing cluster 'jnb' established.
[11/12/2021 11:34:30 PM] (Verbose) Communications with routing cluster 'vie' established.
[11/12/2021 11:34:30 PM] (Verbose) Communications with routing cluster 'sto' established.
[11/12/2021 11:34:30 PM] (Verbose) Communications with routing cluster 'maa' established.
[11/12/2021 11:34:30 PM] (Verbose) Communications with routing cluster 'waw' established.
[11/12/2021 11:34:30 PM] (Verbose) Communications with routing cluster 'sto2' established.
[11/12/2021 11:34:29 PM] (Verbose) Communications with routing cluster 'mad' established.
[11/12/2021 11:34:29 PM] (Verbose) Communications with routing cluster 'par' established.
[11/12/2021 11:34:29 PM] (Verbose) Communications with routing cluster 'seo' established.
[11/12/2021 11:34:29 PM] (Verbose) Communications with routing cluster 'bom' established.
[11/12/2021 11:34:29 PM] (Verbose) Communications with routing cluster 'lim' established.
[11/12/2021 11:34:29 PM] (Verbose) Communications with routing cluster 'ord' established.
[11/12/2021 11:34:29 PM] (Verbose) Communications with routing cluster 'tyo1' established.
[11/12/2021 11:34:29 PM] (Verbose) Communications with routing cluster 'scl' established.
[11/12/2021 11:34:29 PM] (Verbose) Communications with routing cluster 'lhr' established.
[11/12/2021 11:34:29 PM] (Verbose) Communications with routing cluster 'tyo' established.
[11/12/2021 11:34:29 PM] (Verbose) Communications with routing cluster 'gru' established.
[11/12/2021 11:34:29 PM] (Verbose) Communications with routing cluster 'sgp' established.
[11/12/2021 11:34:29 PM] (Verbose) Communications with routing cluster 'fra' established.
[11/12/2021 11:34:29 PM] (Verbose) Communications with routing cluster 'eze' established.
[11/12/2021 11:34:29 PM] (Verbose) Communications with routing cluster 'iad' established.
[11/12/2021 11:34:29 PM] (Verbose) Communications with routing cluster 'atl' established.
[11/12/2021 11:34:29 PM] (Verbose) Communications with routing cluster 'ams' established.
[11/12/2021 11:34:29 PM] (Verbose) Communications with routing cluster 'lax' established.
[11/12/2021 11:34:29 PM] (Verbose) Communications with routing cluster 'dxb' established.
[11/12/2021 11:34:29 PM] (Verbose) Communications with routing cluster 'sea' established.
[11/12/2021 11:34:29 PM] (Verbose) Communications with routing cluster 'syd' established.
[11/12/2021 11:34:29 PM] (Verbose) Communications with routing cluster 'dfw' established.
[11/12/2021 11:34:29 PM] (Verbose) Communications with routing cluster 'hkg' established.
[11/12/2021 11:34:29 PM] (Msg) SDR RelayNetworkStatus:  avail=Attempting  config=OK  anyrelay=Attempting   (Performing ping measurement)
[11/12/2021 11:34:29 PM] (Msg) Performing ping measurement
[11/12/2021 11:34:29 PM] (Msg) Got SDR network config.  Loaded revision 350 OK
[11/12/2021 11:34:29 PM] (Warning) SDR network config fetch first attempt failed.  HTTP 504.  .  Trying again.
[11/12/2021 11:34:27 PM] WARNING: 400 buffer(s) were generated. No more sound buffers will be generated.
[11/12/2021 11:34:20 PM] Attempting to open ALC device "External Headphones"
[11/12/2021 11:34:19 PM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[11/12/2021 11:34:19 PM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
```

Is this an issue with the new update?

**Comment by u7120482** [comment]
Oh! So this is apparently an issue with me having '-=' in my Steam name, and given that all my friends have the same prefix, we all had the same issue.

**Comment by Regalis11** [comment]
No longer seems to happen in the latest unstable version, most likely fixed by the changes in https://github.com/Regalis11/Barotrauma-development/pull/2969

**Comment by Rokvach** [comment]
There hasn't been any encounters to this issue during Unstable testing, seems to be working correctly. Closing.
