### ISSUE TITLE
Barotrauma Client crash report (generated on 16.11.2021 17:37:11)

### ISSUE THREAD

**Issue by Alexout31** [Regalis11/Barotrauma#7341]
Barotrauma Client crash report (generated on 16.11.2021 17:37:11)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

53369B525C73F08AF404DBAF116B0ADA

Game version 0.15.13.0 (ReleaseWindows, branch release, revision 4e66dd7b5d)
Graphics mode: 1600x900 (Windowed)
VSync ON
Language: Russian
Selected content packages: Vanilla 0.9
Level seed: KimjuMolovsk
Loaded submarine: Orca (1610F8ED078868D326E33A0B1645703D)
Selected screen: Barotrauma.GameScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19042.0 64 bit
    GPU name: NVIDIA GeForce 940MX
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1,7777778}
    GPU status: Normal

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void DrawHUDBack(Microsoft.Xna.Framework.Graphics.SpriteBatch, Barotrauma.GUICustomComponent)
Stack trace: 
   at Barotrauma.Items.Components.MiniMap.DrawHUDBack(SpriteBatch spriteBatch, GUICustomComponent container) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Components\Machines\MiniMap.cs:line 1091
   at Barotrauma.GUICustomComponent.Draw(SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUICustomComponent.cs:line 43
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Barotrauma.GUI.Draw(Camera cam, SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 333
   at Barotrauma.GameScreen.Draw(Double deltaTime, GraphicsDevice graphics, SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\GameScreen.cs:line 161
   at Barotrauma.GameMain.Draw(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 1057
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 669
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 508
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 60

Last debug messages:
[16.11.2021 17:00:14] Generating an outpost for the start of the level... (Location: Kimju, level type: LocationConnection)
[16.11.2021 17:00:12] Generating an outpost for the end of the level... (Location: Molovsk, level type: LocationConnection)
[16.11.2021 16:59:41] Transitioning to KimjuMolovsk (current location: Molovsk, selected location: Kimju, leaving sub: Orca, at start: True, at end: False, transition type: LeaveLocation)
[16.11.2021 16:42:39] Unlocked mission "Перевозка ВИП-персоны" in the location "Molovsk".
[16.11.2021 16:42:34] Unlocked mission "Уничтожить гнездо акульего тигра" in the location "Molovsk".
[16.11.2021 16:42:29] Unlocked mission "Уничтожение роя" in the location "Molovsk".
[16.11.2021 16:21:32] Generating an outpost for the start of the level... (Location: Molovsk, level type: Outpost)
[16.11.2021 16:20:53] (Msg) SDR RelayNetworkStatus:  avail=OK  config=OK  anyrelay=OK   (OK)
[16.11.2021 16:20:53] (Msg) Ping location: sto=17+1,sto2=17+1,waw=39+3/37+1,ams=45+4/37+1,fra=43+4/39+1,lhr=48+4/42+1,par=61+6/45+1,vie=50+5/47+1,mad=69+6/68+1,iad=119+11/123+1,sgp=191+19/192+19,gru=231+23
[16.11.2021 16:20:53] (Msg) Ping measurement completed
[16.11.2021 16:20:53] (Debug) Destroying relay 'syd#172 (103.10.125.155:27048)' because initial_ping_timeout
[16.11.2021 16:20:53] (Debug) Destroying relay 'dxb#12 (185.25.183.162:27026)' because initial_ping_timeout
[16.11.2021 16:20:51] (Debug) Destroying relay 'syd#50 (103.10.125.147:27018)' because initial_ping_timeout
[16.11.2021 16:20:51] (Debug) Destroying relay 'dxb#64 (185.25.183.178:27040)' because initial_ping_timeout
[16.11.2021 16:20:50] (Verbose) Communications with routing cluster 'gru' established.
[16.11.2021 16:20:48] (Verbose) Communications with routing cluster 'tyo1' established.
[16.11.2021 16:20:48] (Verbose) Communications with routing cluster 'tyo' established.
[16.11.2021 16:20:48] (Verbose) Communications with routing cluster 'seo' established.
[16.11.2021 16:20:48] (Verbose) Communications with routing cluster 'sgp' established.
[16.11.2021 16:20:48] (Verbose) Communications with routing cluster 'sea' established.
[16.11.2021 16:20:48] (Verbose) Communications with routing cluster 'lim' established.
[16.11.2021 16:20:48] (Verbose) Communications with routing cluster 'scl' established.
[16.11.2021 16:20:48] (Verbose) Communications with routing cluster 'jnb' established.
[16.11.2021 16:20:48] (Verbose) Communications with routing cluster 'maa' established.
[16.11.2021 16:20:48] (Verbose) Communications with routing cluster 'lax' established.
[16.11.2021 16:20:48] (Verbose) Communications with routing cluster 'eze' established.
[16.11.2021 16:20:48] (Verbose) Communications with routing cluster 'vie' established.
[16.11.2021 16:20:48] (Verbose) Communications with routing cluster 'waw' established.
[16.11.2021 16:20:48] (Verbose) Communications with routing cluster 'ord' established.
[16.11.2021 16:20:48] (Verbose) Communications with routing cluster 'sto2' established.
[16.11.2021 16:20:48] (Verbose) Communications with routing cluster 'sto' established.
[16.11.2021 16:20:48] (Verbose) Communications with routing cluster 'hkg' established.
[16.11.2021 16:20:48] (Verbose) Communications with routing cluster 'mad' established.
[16.11.2021 16:20:48] (Verbose) Communications with routing cluster 'par' established.
[16.11.2021 16:20:48] (Verbose) Communications with routing cluster 'bom' established.
[16.11.2021 16:20:48] (Verbose) Communications with routing cluster 'dfw' established.
[16.11.2021 16:20:48] (Verbose) Communications with routing cluster 'lhr' established.
[16.11.2021 16:20:48] (Verbose) Communications with routing cluster 'atl' established.
[16.11.2021 16:20:48] (Verbose) Communications with routing cluster 'iad' established.
[16.11.2021 16:20:48] (Verbose) Communications with routing cluster 'fra' established.
[16.11.2021 16:20:48] (Verbose) Communications with routing cluster 'ams' established.
[16.11.2021 16:20:48] (Msg) SDR RelayNetworkStatus:  avail=Attempting  config=OK  anyrelay=Attempting   (Performing ping measurement)
[16.11.2021 16:20:48] (Msg) Performing ping measurement
[16.11.2021 16:20:48] (Msg) Got SDR network config.  Loaded revision 351 OK
[16.11.2021 16:20:48] (Warning) SDR network config fetch first attempt failed.  HTTP 504.  .  Trying again.
[16.11.2021 16:20:31] Attempting to open ALC device "OpenAL Soft on Динамики (Realtek High Definition Audio)"
[16.11.2021 16:20:30] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[16.11.2021 16:20:29] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[16.11.2021 16:20:27] Logged in as Alex_out (SteamID STEAM_1:1:75862178)

**Comment by Regalis11** [comment]
Based on the error message, this seems to have been caused by the same issue as https://github.com/Regalis11/Barotrauma/issues/7279
