### ISSUE TITLE
(Server crash) Object reference not set / System.String get_SpeciesName()

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#7358]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Logs extracted from this youtube video (34:28) https://youtu.be/2mSPvFC7aow?t=2068
![ga7aBf6qLk](https://user-images.githubusercontent.com/10529134/142326904-26678838-400c-4f8a-a346-242f61960184.png)

Stack trace written by hand from the screenshot above:
```
(missing part here)
at Barotrauma.EntitySpawner.ClientRead(ServerNetObject type, IReadMessage message, Single sendingTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\EntitySpawner.cs:line 37
at Barotrauma.Networking.ClientEntityEventManager.Read(ServerNetObject type, IReadMessage msg, Single sendingtime, List`1 entities) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\NetEntityEvent\ClientEntityEventManager.cs:line 239

Error while reading a message from server. (Object not set to an instance of an object.)
at Barotrauma.Character.get_SpeciesName() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 263
at Barotrauma.Character.ToString() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 1352
at Barotrauma.Networking.GameClient.ReadIngameUpdate(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 2322
at Barotrauma.Networking.Gameclient.ReadDataMessage(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 761
at Barotrauma.Networking.SteamP2POwnerPeer.HandleDataMessage(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\Primitives\Peers\SteamP2POwnerPeer.cs:line 0
at Barotrauma.Networking.SteamP2POwnerPeer.Update(Single deltaTime) in <DEV>\Barotrauma\Barotraumaclient\ClientSource\Networking\Primitives\Peers|SteamP2POwnerPeer.cs:line 232
at Barotrauma.Networking.GameClient.Update(Single deltaTime) in <DEV>\BarotraumaClient\ClientSource'Networking\GameClient.cs:line 623
```

**Steps To Reproduce**
Unknown, the player was not doing anything specific, just climbing a ladder. Notice the old version.

**Version**
v0.14.9.1

**Additional information**
Some YouTuber's Barotrauma server crashed to main menu and I extracted the logs from the video from the exact frame the console appeared in. (lol the things I do to make this game better)

**Comment by Regalis11** [comment]
Wow, thanks for catching this and taking the time to write out that whole thing by hand! Addressed in https://github.com/Regalis11/Barotrauma-development/commit/4c87746b0aa344f7ae5045d5aa50c5c16ba47dd7.

> lol the things I do to make this game better

Yeah, I really appreciate the amount of effort you're putting into helping us fix issues in the game! If you want to be included in the "GitHub contributors" section in the credits btw I'd be happy to add yoy.

**Comment by Krzeszny** [comment]
> Yeah, I really appreciate the amount of effort you're putting into helping us fix issues in the game! If you want to be included in the "GitHub contributors" section in the credits btw I'd be happy to add yoy.

Sure, go ahead.

**Comment by Rokvach** [comment]
No known steps to repro and there hasn't been any sightings of this happening after the fix so this seems to be working correctly. Closing.
