### ISSUE TITLE
The Game crashes when i try to update my published file (can't find PreviewImage.png)

### ISSUE THREAD

**Issue by Navenv** [Regalis11/Barotrauma#7364]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The Game is crush every time when i try to update my published file (an custom submarine) in Steam Workshop

**Steps To Reproduce**
May be i nead to install a addittion framework or something like it?

**Version**
Game version 0.15.13.0 (ReleaseWindows, branch release, revision 4e66dd7b5d)
Windows 7 SP 1

**Additional information**
Please look the crashreport.log:

```
Barotrauma Client crash report (generated on 18.11.2021 15:36:57)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


53369B525C73F08AF404DBAF116B0ADA


Game version 0.15.13.0 (ReleaseWindows, branch release, revision 4e66dd7b5d)
Graphics mode: 2560x1080 (BorderlessWindowed)
VSync ON
Language: Russian
Selected content packages: Vanilla 0.9, # U 1, Unnamed
Level seed: no level loaded
Loaded submarine: None
Selected screen: Barotrauma.SteamWorkshopScreen
SteamManager initialized


System info:
    Operating system: Microsoft Windows NT 6.1.7601 Service Pack 1 64 bit
    GPU name: Intel(R) HD Graphics 4600
    Display mode: {Width:2560 Height:1080 Format:Color AspectRatio:2,3703704}
    GPU status: Normal


Exception: Could not find file 'D:\games\steam\steamapps\common\Barotrauma\Mods\# U 1\PreviewImage.png'. (System.IO.FileNotFoundException)
Target site: Void Move(System.String, System.String, Boolean)
Stack trace: 
   at System.IO.File.Move(String sourceFileName, String destFileName, Boolean overwrite)
   at System.IO.File.Move(String sourceFileName, String destFileName)
   at Barotrauma.IO.File.Move(String src, String dest) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SafeIO.cs:line 304
   at Barotrauma.Steam.SteamManager.StartPublishItem(ContentPackage contentPackage, Nullable`1 item) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\SteamManager.cs:line 931
   at Barotrauma.SteamWorkshopScreen.PublishWorkshopItem() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\SteamWorkshopScreen.cs:line 1831
   at Barotrauma.SteamWorkshopScreen.<>c__DisplayClass52_0.<ShowCreateItemFrame>b__18(GUIButton btn, Object userData) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\SteamWorkshopScreen.cs:line 1560
   at Barotrauma.GUIButton.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIButton.cs:line 262
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Barotrauma.GUI.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1253
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 1005
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 61


Last debug messages:
[18.11.2021 15:36:55] Sprite "D:\games\steam\steamapps\common\Barotrauma\Mods\# U 1\PreviewImage.png" not found!    at System.Environment.get_StackTrace()
   at Barotrauma.Sprite.LoadTexture(String file, Sprite& reusedSprite, Boolean compress) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Sprite\Sprite.cs:line 172
   at Barotrauma.Sprite.LoadTexture(Vector4& sourceVector, Boolean& shouldReturn) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Sprite\Sprite.cs:line 56
   at Barotrauma.Sprite.Init(String newFile, Nullable`1 sourceRectangle, Nullable`1 newOrigin, Nullable`1 newOffset, Single newRotation) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Sprite\Sprite.cs:line 212
   at Barotrauma.SteamWorkshopScreen.ShowCreateItemFrame() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\SteamWorkshopScreen.cs:line 1326
   at Barotrauma.SteamWorkshopScreen.<CreateUI>b__23_5(GUIComponent component, Object userdata) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\SteamWorkshopScreen.cs:line 213
   at Barotrauma.GUIListBox.Select(Int32 childIndex, Boolean force, Boolean autoScroll, Boolean takeKeyBoardFocus) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIListBox.cs:line 878
   at Barotrauma.GUIListBox.UpdateChildrenRect() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIListBox.cs:line 602
   at Barotrauma.GUIListBox.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIListBox.cs:line 719
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Barotrauma.GUI.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1250
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 1005
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 651
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 61
[18.11.2021 15:36:42] (Msg) SDR RelayNetworkStatus:  avail=OK  config=OK  anyrelay=OK   (OK)
[18.11.2021 15:36:42] (Msg) Ping location: sto2=22+2,sto=23+2/22+2,fra=37+3,ams=39+3,waw=53+5/43+2,lhr=49+4/44+3,par=55+5/46+3,vie=52+5/49+3,mad=67+6/67+3,iad=111+11,sgp=218+21/219+21,gru=239+23
[18.11.2021 15:36:42] (Msg) Ping measurement completed
[18.11.2021 15:36:39] (Verbose) Communications with routing cluster 'seo' established.
[18.11.2021 15:36:39] (Verbose) Communications with routing cluster 'tyo' established.
[18.11.2021 15:36:39] (Verbose) Communications with routing cluster 'tyo1' established.
[18.11.2021 15:36:39] (Verbose) Communications with routing cluster 'syd' established.
[18.11.2021 15:36:39] (Verbose) Communications with routing cluster 'sgp' established.
[18.11.2021 15:36:39] (Verbose) Communications with routing cluster 'scl' established.
[18.11.2021 15:36:39] (Verbose) Communications with routing cluster 'lim' established.
[18.11.2021 15:36:39] (Verbose) Communications with routing cluster 'jnb' established.
[18.11.2021 15:36:39] (Verbose) Communications with routing cluster 'sea' established.
[18.11.2021 15:36:39] (Verbose) Communications with routing cluster 'maa' established.
[18.11.2021 15:36:39] (Verbose) Communications with routing cluster 'lax' established.
[18.11.2021 15:36:39] (Verbose) Communications with routing cluster 'eze' established.
[18.11.2021 15:36:39] (Warning) SteamNetworkingSockets lock held for 16.8ms.  (Performance warning.)  ServiceThread,RecvUDPPacket
This is usually a symptom of a general performance problem such as thread starvation.
[18.11.2021 15:36:39] (Verbose) Communications with routing cluster 'waw' established.
[18.11.2021 15:36:39] (Verbose) Communications with routing cluster 'vie' established.
[18.11.2021 15:36:39] (Verbose) Communications with routing cluster 'gru' established.
[18.11.2021 15:36:39] (Verbose) Communications with routing cluster 'ord' established.
[18.11.2021 15:36:39] (Verbose) Communications with routing cluster 'sto' established.
[18.11.2021 15:36:39] (Verbose) Communications with routing cluster 'sto2' established.
[18.11.2021 15:36:39] (Verbose) Communications with routing cluster 'hkg' established.
[18.11.2021 15:36:39] (Verbose) Communications with routing cluster 'bom' established.
[18.11.2021 15:36:39] (Verbose) Communications with routing cluster 'dxb' established.
[18.11.2021 15:36:39] (Verbose) Communications with routing cluster 'mad' established.
[18.11.2021 15:36:39] (Verbose) Communications with routing cluster 'par' established.
[18.11.2021 15:36:39] (Verbose) Communications with routing cluster 'lhr' established.
[18.11.2021 15:36:39] (Verbose) Communications with routing cluster 'dfw' established.
[18.11.2021 15:36:39] (Verbose) Communications with routing cluster 'atl' established.
[18.11.2021 15:36:39] (Verbose) Communications with routing cluster 'iad' established.
[18.11.2021 15:36:39] (Verbose) Communications with routing cluster 'ams' established.
[18.11.2021 15:36:39] (Verbose) Communications with routing cluster 'fra' established.
[18.11.2021 15:36:39] (Msg) SDR RelayNetworkStatus:  avail=Attempting  config=OK  anyrelay=Attempting   (Performing ping measurement)
[18.11.2021 15:36:39] (Msg) Performing ping measurement
[18.11.2021 15:36:39] (Msg) Got SDR network config.  Loaded revision 351 OK
[18.11.2021 15:36:38] (Warning) SDR network config fetch first attempt failed.  HTTP 504.  .  Trying again.
[18.11.2021 15:36:31] Attempting to open ALC device "OpenAL Soft on Динамики (Realtek High Definition Audio)"
[18.11.2021 15:36:30] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[18.11.2021 15:36:30] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[18.11.2021 15:36:28] Logged in as naven (SteamID STEAM_1:1:10134342)
```

**Comment by Regalis11** [comment]
According to the crash report, the game can't find the preview file for the mod from the path "D:\games\steam\steamapps\common\Barotrauma\Mods\# U 1\PreviewImage.png". Please check that the file is present there, and if not, add the file there (it should also be possible to do this by selecting the preview image in the publish menu).

But in any case, we need to look into this and make sure it doesn't crash the game even if the preview image can't be found.

**Comment by Navenv** [comment]
Yes, when i upload a PNG preview cover file, i get a possibility to update my file. But, when i am updated it, the preview file was disappear. AND when it is no file, the game is crushed. So, i had to upload the preview every time when i like to update Workshop item. IMHO this is not critical, but i think you should to know about this failure to repair it in future.

```
Barotrauma Client crash report (generated on 18.11.2021 22:32:37)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


53369B525C73F08AF404DBAF116B0ADA


Game version 0.15.13.0 (ReleaseWindows, branch release, revision 4e66dd7b5d)
Graphics mode: 2560x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla 0.9
Level seed: no level loaded
Loaded submarine: None
Selected screen: Barotrauma.SteamWorkshopScreen
SteamManager initialized


System info:
    Operating system: Microsoft Windows NT 6.1.7601 Service Pack 1 64 bit
    GPU name: Intel(R) HD Graphics 4600
    Display mode: {Width:2560 Height:1080 Format:Color AspectRatio:2,3703704}
    GPU status: Normal


Exception: Could not find file 'D:\games\steam\steamapps\common\Barotrauma\Mods\# U 1\PreviewImage.png'. (System.IO.FileNotFoundException)
Target site: Void Move(System.String, System.String, Boolean)
Stack trace: 
   at System.IO.File.Move(String sourceFileName, String destFileName, Boolean overwrite)
   at System.IO.File.Move(String sourceFileName, String destFileName)
   at Barotrauma.IO.File.Move(String src, String dest) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SafeIO.cs:line 304
   at Barotrauma.Steam.SteamManager.StartPublishItem(ContentPackage contentPackage, Nullable`1 item) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\SteamManager.cs:line 931
   at Barotrauma.SteamWorkshopScreen.PublishWorkshopItem() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\SteamWorkshopScreen.cs:line 1831
   at Barotrauma.SteamWorkshopScreen.<>c__DisplayClass52_0.<ShowCreateItemFrame>b__18(GUIButton btn, Object userData) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\SteamWorkshopScreen.cs:line 1560
   at Barotrauma.GUIButton.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIButton.cs:line 262
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Barotrauma.GUI.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1253
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 1005
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 61


Last debug messages:
```
**[18.11.2021 22:32:34] Command ">>" not found.
[18.11.2021 22:32:34] >> push UPDATE ITEM button but dont upload preview image (now it was gone away)**
```
[18.11.2021 22:31:31] Sprite "D:\games\steam\steamapps\common\Barotrauma\Mods\# U 1\PreviewImage.png" not found!    at System.Environment.get_StackTrace()
   at Barotrauma.Sprite.LoadTexture(String file, Sprite& reusedSprite, Boolean compress) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Sprite\Sprite.cs:line 172
   at Barotrauma.Sprite.LoadTexture(Vector4& sourceVector, Boolean& shouldReturn) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Sprite\Sprite.cs:line 56
   at Barotrauma.Sprite.Init(String newFile, Nullable`1 sourceRectangle, Nullable`1 newOrigin, Nullable`1 newOffset, Single newRotation) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Sprite\Sprite.cs:line 212
   at Barotrauma.SteamWorkshopScreen.ShowCreateItemFrame() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\SteamWorkshopScreen.cs:line 1326
   at Barotrauma.SteamWorkshopScreen.<CreateUI>b__23_5(GUIComponent component, Object userdata) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\SteamWorkshopScreen.cs:line 213
   at Barotrauma.GUIListBox.Select(Int32 childIndex, Boolean force, Boolean autoScroll, Boolean takeKeyBoardFocus) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIListBox.cs:line 878
   at Barotrauma.GUIListBox.UpdateChildrenRect() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIListBox.cs:line 602
   at Barotrauma.GUIListBox.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIListBox.cs:line 719
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Barotrauma.GUI.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1250
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 1005
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 651
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 61
```
**[18.11.2021 22:31:27] Command ">>" not found.
[18.11.2021 22:31:27] >> choose my item again**
```
[18.11.2021 22:30:59] Published workshop item # U 1 successfully.
[18.11.2021 22:30:59] True
```
**[18.11.2021 22:30:53] Command "i" not found.
[18.11.2021 22:30:53] i push UPDATE ITEM:
[18.11.2021 22:30:29] Command ">>" not found.
[18.11.2021 22:30:29] >> i choose PNG file in preview image:**
```
[18.11.2021 22:29:59] Sprite "D:\games\steam\steamapps\common\Barotrauma\Mods\# U 1\PreviewImage.png" not found!    at System.Environment.get_StackTrace()
   at Barotrauma.Sprite.LoadTexture(String file, Sprite& reusedSprite, Boolean compress) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Sprite\Sprite.cs:line 172
   at Barotrauma.Sprite.LoadTexture(Vector4& sourceVector, Boolean& shouldReturn) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Sprite\Sprite.cs:line 56
   at Barotrauma.Sprite.Init(String newFile, Nullable`1 sourceRectangle, Nullable`1 newOrigin, Nullable`1 newOffset, Single newRotation) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Sprite\Sprite.cs:line 212
   at Barotrauma.SteamWorkshopScreen.ShowCreateItemFrame() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\SteamWorkshopScreen.cs:line 1326
   at Barotrauma.SteamWorkshopScreen.<CreateUI>b__23_5(GUIComponent component, Object userdata) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\SteamWorkshopScreen.cs:line 213
   at Barotrauma.GUIListBox.Select(Int32 childIndex, Boolean force, Boolean autoScroll, Boolean takeKeyBoardFocus) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIListBox.cs:line 878
   at Barotrauma.GUIListBox.UpdateChildrenRect() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIListBox.cs:line 602
   at Barotrauma.GUIListBox.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIListBox.cs:line 719
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Barotrauma.GUI.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1250
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 1005
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 651
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 61
```
**[18.11.2021 22:29:56] Command ">>" not found.
[18.11.2021 22:29:56] >> i choose my file in PUBLISHED ITEMS
[18.11.2021 22:29:20] Command ">>" not found.
[18.11.2021 22:29:20] >> i try to go in to Steam Workshop**
```
[18.11.2021 22:28:03] (Msg) SDR RelayNetworkStatus:  avail=OK  config=OK  anyrelay=OK   (OK)
[18.11.2021 22:28:03] (Msg) Ping location: sto=21+2,sto2=23+2/21+2,ams=43+4/41+2,fra=41+4/42+2,waw=47+4/42+2,lhr=47+4/46+2,par=56+5/50+4,vie=51+5/51+2,mad=67+6,iad=117+11/126+2,sgp=215+21,gru=247+24
[18.11.2021 22:28:03] (Msg) Ping measurement completed
[18.11.2021 22:28:00] (Verbose) Communications with routing cluster 'seo' established.
[18.11.2021 22:28:00] (Verbose) Communications with routing cluster 'tyo' established.
[18.11.2021 22:28:00] (Verbose) Communications with routing cluster 'tyo1' established.
[18.11.2021 22:28:00] (Verbose) Communications with routing cluster 'syd' established.
[18.11.2021 22:28:00] (Verbose) Communications with routing cluster 'sgp' established.
[18.11.2021 22:28:00] (Verbose) Communications with routing cluster 'scl' established.
[18.11.2021 22:28:00] (Verbose) Communications with routing cluster 'lim' established.
[18.11.2021 22:28:00] (Verbose) Communications with routing cluster 'jnb' established.
[18.11.2021 22:28:00] (Verbose) Communications with routing cluster 'sea' established.
[18.11.2021 22:28:00] (Verbose) Communications with routing cluster 'maa' established.
[18.11.2021 22:28:00] (Verbose) Communications with routing cluster 'lax' established.
[18.11.2021 22:28:00] (Verbose) Communications with routing cluster 'eze' established.
[18.11.2021 22:28:00] (Verbose) Communications with routing cluster 'vie' established.
[18.11.2021 22:28:00] (Verbose) Communications with routing cluster 'waw' established.
[18.11.2021 22:28:00] (Verbose) Communications with routing cluster 'gru' established.
[18.11.2021 22:28:00] (Verbose) Communications with routing cluster 'ord' established.
[18.11.2021 22:28:00] (Verbose) Communications with routing cluster 'sto2' established.
[18.11.2021 22:28:00] (Verbose) Communications with routing cluster 'sto' established.
[18.11.2021 22:28:00] (Verbose) Communications with routing cluster 'hkg' established.
[18.11.2021 22:28:00] (Verbose) Communications with routing cluster 'bom' established.
[18.11.2021 22:28:00] (Verbose) Communications with routing cluster 'dxb' established.
[18.11.2021 22:28:00] (Verbose) Communications with routing cluster 'mad' established.
[18.11.2021 22:27:59] (Verbose) Communications with routing cluster 'par' established.
[18.11.2021 22:27:59] (Verbose) Communications with routing cluster 'dfw' established.
[18.11.2021 22:27:59] (Verbose) Communications with routing cluster 'lhr' established.
[18.11.2021 22:27:59] (Verbose) Communications with routing cluster 'atl' established.
[18.11.2021 22:27:59] (Verbose) Communications with routing cluster 'iad' established.
[18.11.2021 22:27:59] (Verbose) Communications with routing cluster 'ams' established.
[18.11.2021 22:27:59] (Verbose) Communications with routing cluster 'fra' established.
[18.11.2021 22:27:59] (Msg) SDR RelayNetworkStatus:  avail=Attempting  config=OK  anyrelay=Attempting   (Performing ping measurement)
[18.11.2021 22:27:59] (Msg) Performing ping measurement
[18.11.2021 22:27:59] (Msg) Got SDR network config.  Loaded revision 351 OK
[18.11.2021 22:27:59] (Warning) SDR network config fetch first attempt failed.  HTTP 504.  .  Trying again.
[18.11.2021 22:27:51] Attempting to open ALC device "OpenAL Soft on Динамики (Realtek High Definition Audio)"
[18.11.2021 22:27:50] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[18.11.2021 22:27:50] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[18.11.2021 22:27:49] Logged in as naven (SteamID STEAM_1:1:10134342)

```

**Comment by Navenv** [comment]
if you manually put the PreviewImage.png file in the mod folder, the game deletes it at the moment of selecting an item from the workshop menu. and I lost pictures in the workshop and in other games too, in the steam overlay. apparently, the problem is rather in steam. perhaps this is due to permissions to write to folders. I will unsubscribe if there is a solution.
