### ISSUE TITLE
Bug report (nullref exception in NetLobbyScreen)

### ISSUE THREAD

**Issue by HopeLessSou1** [Regalis11/Barotrauma#7616]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Playing around multiplayer, host selected destination for sub to go to and server kicked me out and it crashed.

**Steps To Reproduce**
N/A

**Version**
Barotrauma version 0.15.13.0 on Windows

**Additional information**
Barotrauma Client crash report (generated on 12/4/2021 1:54:27 PM)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

53369B525C73F08AF404DBAF116B0ADA

Game version 0.15.13.0 (ReleaseWindows, branch release, revision 4e66dd7b5d)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla 0.9
Level seed: DankAndrogeos Linea
Loaded submarine: Orca (D48C3F177EBC60C9DAD54483B9694A4E)
Selected screen: Barotrauma.NetLobbyScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19043.0 64 bit

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Boolean <.ctor>b__165_20(Barotrauma.GUITickBox)
Stack trace: 
   at Barotrauma.NetLobbyScreen.<>c.<.ctor>b__165_20(GUITickBox tickbox) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\NetLobbyScreen.cs:line 691
   at Barotrauma.GUITickBox.set_Selected(Boolean value) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUITickBox.cs:line 41
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Barotrauma.GUI.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1253
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 1005
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 60

Last debug messages:
[12/4/2021 1:54:06 PM] Attempting to reconnect...
[12/4/2021 1:54:06 PM] Received a disconnect message (ServerMessage.YouLeftServer/
/ServerMessage.Reason/: /ServerMessage.HasDisconnected~[client]=Hope)
[12/4/2021 1:53:52 PM] Attempting to reconnect...
[12/4/2021 1:53:52 PM] Received a disconnect message ()
[12/4/2021 1:53:50 PM] Generating an outpost for the end of the level... (Location: Androgeos Linea, level type: LocationConnection)
[12/4/2021 1:53:28 PM] Qowyn
[12/4/2021 1:53:28 PM] Hope
[12/4/2021 1:53:28 PM] x89rt
[12/4/2021 1:53:28 PM] Mahamies
[12/4/2021 1:53:28 PM] SoapMaker
[12/4/2021 1:53:28 PM] Corneliu Vadim Tudor
[12/4/2021 1:43:05 PM] Qowyn
[12/4/2021 1:43:05 PM] Hope
[12/4/2021 1:43:05 PM] x89rt
[12/4/2021 1:43:05 PM] Mahamies
[12/4/2021 1:43:05 PM] SoapMaker
[12/4/2021 1:43:05 PM] Corneliu Vadim Tudor
[12/4/2021 1:42:10 PM] x89rt
[12/4/2021 1:42:10 PM] Mahamies
[12/4/2021 1:42:10 PM] SoapMaker
[12/4/2021 1:42:10 PM] Corneliu Vadim Tudor
[12/4/2021 1:40:37 PM] x89rt
[12/4/2021 1:40:37 PM] Mahamies
[12/4/2021 1:40:37 PM] SoapMaker
[12/4/2021 1:40:37 PM] Corneliu Vadim Tudor
[12/4/2021 1:40:37 PM] x89rt
[12/4/2021 1:40:37 PM] Mahamies
[12/4/2021 1:40:37 PM] SoapMaker
[12/4/2021 1:40:37 PM] Corneliu Vadim Tudor
[12/4/2021 1:40:35 PM] x89rt
[12/4/2021 1:40:35 PM] Mahamies
[12/4/2021 1:40:35 PM] SoapMaker
[12/4/2021 1:40:35 PM] Corneliu Vadim Tudor
[12/4/2021 1:40:32 PM] Task count: 0
[12/4/2021 1:40:28 PM] Generating an outpost for the start of the level... (Location: New Nanhui, level type: LocationConnection)
[12/4/2021 1:39:08 PM] LobbyMatchList:  LobbiesMatching: 0
[12/4/2021 1:39:08 PM] LobbyMatchList:  LobbiesMatching: 0
[12/4/2021 1:39:08 PM] SteamAPICallCompleted:   AsyncCall: 2134539995529017551
   Callback: 510
 ParamCount: 4
[12/4/2021 1:39:08 PM] LobbyMatchList:  LobbiesMatching: 18
[12/4/2021 1:39:08 PM] LobbyMatchList:  LobbiesMatching: 18
[12/4/2021 1:39:08 PM] SteamAPICallCompleted:   AsyncCall: 7852772089665160848
   Callback: 510
 ParamCount: 4
[12/4/2021 1:39:08 PM] LobbyMatchList:  LobbiesMatching: 50
[12/4/2021 1:39:08 PM] LobbyMatchList:  LobbiesMatching: 50
[12/4/2021 1:39:08 PM] SteamAPICallCompleted:   AsyncCall: 15578550968370085316
   Callback: 510
 ParamCount: 4
[12/4/2021 1:39:07 PM] LobbyMatchList:  LobbiesMatching: 49
[12/4/2021 1:39:07 PM] LobbyMatchList:  LobbiesMatching: 49
[12/4/2021 1:39:07 PM] SteamAPICallCompleted:   AsyncCall: 17142470281503483680
   Callback: 510
 ParamCount: 4
[12/4/2021 1:39:07 PM] LobbyMatchList:  LobbiesMatching: 50
[12/4/2021 1:39:07 PM] LobbyMatchList:  LobbiesMatching: 50
[12/4/2021 1:39:07 PM] SteamAPICallCompleted:   AsyncCall: 12649551123041854005
   Callback: 510
 ParamCount: 4
[12/4/2021 1:39:07 PM] LobbyMatchList:  LobbiesMatching: 50
[12/4/2021 1:39:07 PM] LobbyMatchList:  LobbiesMatching: 50
[12/4/2021 1:39:07 PM] SteamAPICallCompleted:   AsyncCall: 15497343275037467771
   Callback: 510
 ParamCount: 4
[12/4/2021 1:39:07 PM] LobbyMatchList:  LobbiesMatching: 50
[12/4/2021 1:39:07 PM] LobbyMatchList:  LobbiesMatching: 50
[12/4/2021 1:39:07 PM] SteamAPICallCompleted:   AsyncCall: 16668665913809834849
   Callback: 510
 ParamCount: 4
[12/4/2021 1:39:06 PM] LobbyMatchList:  LobbiesMatching: 50
[12/4/2021 1:39:06 PM] LobbyMatchList:  LobbiesMatching: 50
[12/4/2021 1:39:06 PM] SteamAPICallCompleted:   AsyncCall: 13093184330004426907
   Callback: 510
 ParamCount: 4
[12/4/2021 1:38:01 PM] LobbyMatchList:  LobbiesMatching: 0
[12/4/2021 1:38:01 PM] LobbyMatchList:  LobbiesMatching: 0
[12/4/2021 1:38:01 PM] SteamAPICallCompleted:   AsyncCall: 16410097176804303824
   Callback: 510
 ParamCount: 4
[12/4/2021 1:38:01 PM] LobbyMatchList:  LobbiesMatching: 22
[12/4/2021 1:38:01 PM] LobbyMatchList:  LobbiesMatching: 22
[12/4/2021 1:38:01 PM] SteamAPICallCompleted:   AsyncCall: 11834984630243339270
   Callback: 510
 ParamCount: 4
[12/4/2021 1:38:01 PM] LobbyMatchList:  LobbiesMatching: 50
[12/4/2021 1:38:01 PM] LobbyMatchList:  LobbiesMatching: 50
[12/4/2021 1:38:01 PM] SteamAPICallCompleted:   AsyncCall: 8182585457102968306
   Callback: 510
 ParamCount: 4
[12/4/2021 1:38:01 PM] LobbyMatchList:  LobbiesMatching: 50
[12/4/2021 1:38:01 PM] LobbyMatchList:  LobbiesMatching: 50
[12/4/2021 1:38:01 PM] SteamAPICallCompleted:   AsyncCall: 3252002997042469615
   Callback: 510
 ParamCount: 4
[12/4/2021 1:38:00 PM] LobbyMatchList:  LobbiesMatching: 50
[12/4/2021 1:38:00 PM] LobbyMatchList:  LobbiesMatching: 50
[12/4/2021 1:38:00 PM] SteamAPICallCompleted:   AsyncCall: 9584682439971024372
   Callback: 510
 ParamCount: 4
[12/4/2021 1:38:00 PM] LobbyMatchList:  LobbiesMatching: 50
[12/4/2021 1:38:00 PM] LobbyMatchList:  LobbiesMatching: 50
[12/4/2021 1:38:00 PM] SteamAPICallCompleted:   AsyncCall: 9703165167067133512
   Callback: 510
 ParamCount: 4
[12/4/2021 1:38:00 PM] LobbyMatchList:  LobbiesMatching: 50
[12/4/2021 1:38:00 PM] LobbyMatchList:  LobbiesMatching: 50
[12/4/2021 1:38:00 PM] SteamAPICallCompleted:   AsyncCall: 14387717221040967663
   Callback: 510
 ParamCount: 4
[12/4/2021 1:37:59 PM] LobbyMatchList:  LobbiesMatching: 50
[12/4/2021 1:37:59 PM] LobbyMatchList:  LobbiesMatching: 50
[12/4/2021 1:37:59 PM] SteamAPICallCompleted:   AsyncCall: 4732323994938803799
   Callback: 510
 ParamCount: 4
[12/4/2021 1:37:27 PM] (Msg) SDR RelayNetworkStatus:  avail=OK  config=OK  anyrelay=OK   (OK)
[12/4/2021 1:37:27 PM] (Msg) Ping location: iad=19+1,ord=26+2,atl=30+3/32+1,dfw=54+5/47+2,sea=88+8/72+2,lax=83+8/73+2,lhr=88+8,ams=89+8,par=93+9/96+1,fra=102+10/96+8,gru=140+14,sgp=242+24/243+24
[12/4/2021 1:37:27 PM] (Msg) Ping measurement completed
[12/4/2021 1:37:25 PM] (Verbose) Communications with routing cluster 'sgp' established.
[12/4/2021 1:37:25 PM] (Verbose) Communications with routing cluster 'syd' established.
[12/4/2021 1:37:25 PM] (Verbose) Communications with routing cluster 'seo' established.
[12/4/2021 1:37:25 PM] (Verbose) Communications with routing cluster 'tyo' established.
[12/4/2021 1:37:25 PM] (Verbose) Communications with routing cluster 'tyo1' established.
[12/4/2021 1:37:25 PM] (Verbose) Communications with routing cluster 'maa' established.
[12/4/2021 1:37:25 PM] (Verbose) Communications with routing cluster 'jnb' established.
[12/4/2021 1:37:25 PM] (Verbose) Communications with routing cluster 'sto' established.
[12/4/2021 1:37:25 PM] (Verbose) Communications with routing cluster 'vie' established.
[12/4/2021 1:37:25 PM] (Verbose) Communications with routing cluster 'sto2' established.
[12/4/2021 1:37:25 PM] (Verbose) Communications with routing cluster 'waw' established.
[12/4/2021 1:37:25 PM] (Verbose) Communications with routing cluster 'dxb' established.
[12/4/2021 1:37:25 PM] (Verbose) Communications with routing cluster 'bom' established.
[12/4/2021 1:37:25 PM] (Verbose) Communications with routing cluster 'scl' established.
[12/4/2021 1:37:25 PM] (Verbose) Communications with routing cluster 'hkg' established.
[12/4/2021 1:37:24 PM] (Verbose) Communications with routing cluster 'mad' established.
[12/4/2021 1:37:24 PM] (Verbose) Communications with routing cluster 'lim' established.
[12/4/2021 1:37:24 PM] (Verbose) Communications with routing cluster 'lax' established.
[12/4/2021 1:37:24 PM] (Verbose) Communications with routing cluster 'sea' established.
[12/4/2021 1:37:24 PM] (Verbose) Communications with routing cluster 'par' established.
[12/4/2021 1:37:24 PM] (Verbose) Communications with routing cluster 'lhr' established.
[12/4/2021 1:37:24 PM] (Verbose) Communications with routing cluster 'eze' established.
[12/4/2021 1:37:24 PM] (Verbose) Communications with routing cluster 'gru' established.
[12/4/2021 1:37:24 PM] (Verbose) Communications with routing cluster 'ord' established.
[12/4/2021 1:37:24 PM] (Verbose) Communications with routing cluster 'fra' established.
[12/4/2021 1:37:24 PM] (Verbose) Communications with routing cluster 'ams' established.
[12/4/2021 1:37:24 PM] (Verbose) Communications with routing cluster 'dfw' established.
[12/4/2021 1:37:24 PM] (Verbose) Communications with routing cluster 'atl' established.
[12/4/2021 1:37:24 PM] (Verbose) Communications with routing cluster 'iad' established.
[12/4/2021 1:37:24 PM] (Msg) SDR RelayNetworkStatus:  avail=Attempting  config=OK  anyrelay=Attempting   (Performing ping measurement)
[12/4/2021 1:37:24 PM] (Msg) Performing ping measurement
[12/4/2021 1:37:24 PM] (Msg) Got SDR network config.  Loaded revision 354 OK
[12/4/2021 1:37:24 PM] (Warning) SDR network config fetch first attempt failed.  HTTP 504.  .  Trying again.
[12/4/2021 1:37:17 PM] Attempting to open ALC device "OpenAL Soft on Headphones (High Definition Audio Device)"
[12/4/2021 1:37:17 PM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[12/4/2021 1:37:16 PM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/45b4971e6174df75a8479c3342b796afeb2ada3b

**Comment by Rokvach** [comment]
There hasn't been any sightings of this happening in Unstable, seems to be working correctly. Closing.
