### ISSUE TITLE
Mac holiday update crush

### ISSUE THREAD

**Issue by Yakostoch** [Regalis11/Barotrauma#7787]
Barotrauma Client crash report (generated on 12/15/2021 10:23:41 PM)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

C4161C5B0C1FBD8D2ABA8510772A7EB5

Game version 0.15.21.0 (ReleaseMac, branch release, revision 31b8ac03f4)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: Russian
Selected content packages: Vanilla 0.9
Level seed: no level loaded
Loaded submarine: None
Selected screen: None
SteamManager initialized

System info:
    Operating system: Unix 19.6.0.0 64 bit
    GPU name: 
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: The type initializer for 'GameAnalyticsSDK.Net.Logging.GALogger' threw an exception. (System.TypeInitializationException)
Target site: Void D(System.String)
Stack trace: 
   at GameAnalyticsSDK.Net.Logging.GALogger.D(String format) in <DEV>/Libraries/GameAnalytics/GA-SDK-MONO-SHARED/Logging/GALogger.cs:line 143
   at GameAnalyticsSDK.Net.Threading.GAThreading.Run() in <DEV>/Libraries/GameAnalytics/GA-SDK-MONO-SHARED/Threading/GAThreading.cs:line 66
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

InnerException: The type initializer for 'GameAnalyticsSDK.Net.Device.GADevice' threw an exception.
Target site: Void .ctor()
Stack trace: 
   at GameAnalyticsSDK.Net.Logging.GALogger..ctor() in <DEV>/Libraries/GameAnalytics/GA-SDK-MONO-SHARED/Logging/GALogger.cs:line 88
   at GameAnalyticsSDK.Net.Logging.GALogger..cctor() in <DEV>/Libraries/GameAnalytics/GA-SDK-MONO-SHARED/Logging/GALogger.cs:line 20
Last debug messages:
[12/15/2021 10:23:41 PM] Initializing GameAnalytics failed. Disabling user statistics... {Exception has been thrown by the target of an invocation.}
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Barotrauma.GameAnalyticsManager.Implementation.<>c__DisplayClass34_0`2.<Call>b__0(T1 arg1, T2 arg2) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/GameAnalytics/GameAnalyticsManager.cs:line 114
   at Barotrauma.GameAnalyticsManager.Implementation.Initialize(String gameKey, String secretKey) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/GameAnalytics/GameAnalyticsManager.cs:line 39
   at Barotrauma.GameAnalyticsManager.InitKeys() in <DEV>/Barotrauma/BarotraumaShared/SharedSource/GameAnalytics/GameAnalyticsKeys.cs:line 11
   at Barotrauma.GameAnalyticsManager.Init() in <DEV>/Barotrauma/BarotraumaShared/SharedSource/GameAnalytics/GameAnalyticsManager.cs:line 352

Inner exception: The type initializer for 'GameAnalyticsSDK.Net.Device.GADevice' threw an exception.
   at GameAnalyticsSDK.Net.GameAnalytics.Initialize(String gameKey, String gameSecret) in <DEV>/Libraries/GameAnalytics/GA-SDK-MONO-SHARED/GameAnalytics.cs:line 238
[12/15/2021 10:23:35 PM] Attempting to open ALC device "Built-in Output"
[12/15/2021 10:23:33 PM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[12/15/2021 10:23:33 PM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[12/15/2021 10:23:31 PM] Logged in as Yakostoch (SteamID STEAM_1:0:493402427)

**Comment by pobedaperidot** [comment]
Having the same issue. Here's the crash log:

Barotrauma Client crash report (generated on 12/15/2021 11:08:10 PM)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


C4161C5B0C1FBD8D2ABA8510772A7EB5


Game version 0.15.21.0 (ReleaseMac, branch release, revision 31b8ac03f4)
Graphics mode: 1440x900 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla 0.9
Level seed: no level loaded
Loaded submarine: None
Selected screen: None
SteamManager initialized


System info:
    Operating system: Unix 20.6.0.0 64 bit
    GPU name: 
    Display mode: {Width:1440 Height:900 Format:Color AspectRatio:1.6}
    GPU status: Normal


Exception: The type initializer for 'GameAnalyticsSDK.Net.Logging.GALogger' threw an exception. (System.TypeInitializationException)
Target site: Void D(System.String)
Stack trace: 
   at GameAnalyticsSDK.Net.Logging.GALogger.D(String format) in <DEV>/Libraries/GameAnalytics/GA-SDK-MONO-SHARED/Logging/GALogger.cs:line 143
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()


InnerException: The type initializer for 'GameAnalyticsSDK.Net.Device.GADevice' threw an exception.
Target site: Void .ctor()
Stack trace: 
   at GameAnalyticsSDK.Net.Logging.GALogger..ctor() in <DEV>/Libraries/GameAnalytics/GA-SDK-MONO-SHARED/Logging/GALogger.cs:line 88
   at GameAnalyticsSDK.Net.Logging.GALogger..cctor() in <DEV>/Libraries/GameAnalytics/GA-SDK-MONO-SHARED/Logging/GALogger.cs:line 20
Last debug messages:
[12/15/2021 11:08:10 PM] Initializing GameAnalytics failed. Disabling user statistics... {Exception has been thrown by the target of an invocation.}
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Barotrauma.GameAnalyticsManager.Implementation.<>c__DisplayClass34_0`2.<Call>b__0(T1 arg1, T2 arg2) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/GameAnalytics/GameAnalyticsManager.cs:line 114
   at Barotrauma.GameAnalyticsManager.Implementation.Initialize(String gameKey, String secretKey) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/GameAnalytics/GameAnalyticsManager.cs:line 39
   at Barotrauma.GameAnalyticsManager.InitKeys() in <DEV>/Barotrauma/BarotraumaShared/SharedSource/GameAnalytics/GameAnalyticsKeys.cs:line 11
   at Barotrauma.GameAnalyticsManager.Init() in <DEV>/Barotrauma/BarotraumaShared/SharedSource/GameAnalytics/GameAnalyticsManager.cs:line 352

Inner exception: The type initializer for 'GameAnalyticsSDK.Net.Device.GADevice' threw an exception.
   at GameAnalyticsSDK.Net.GameAnalytics.Initialize(String gameKey, String gameSecret) in <DEV>/Libraries/GameAnalytics/GA-SDK-MONO-SHARED/GameAnalytics.cs:line 238
[12/15/2021 11:07:59 PM] Attempting to open ALC device "Philips UH202"
[12/15/2021 11:07:56 PM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[12/15/2021 11:07:52 PM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[12/15/2021 11:07:45 PM] Logged in as Peridot (SteamID STEAM_1:0:103448854)

**Comment by ekqvist** [comment]
Potential duplicate of #7780. Seems that there's slight differences in the errors, but all of them are related to Mac and GA.

**Comment by Regalis11** [comment]
Duplicate of #7780
