### ISSUE TITLE
Status Monitor Crashing Any Modded Sub

### ISSUE THREAD

**Issue by Koningkrush** [Regalis11/Barotrauma#7794]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Whenever using any mod that ends any new entities that would show up on the Status monitor, attempting to view the status monitor will crash the game.

**Steps To Reproduce**
Install any mod that adds something new to the submarine editor, like Visual Variety Pack or Beacons Extended.
Then attempt to view the General Status of the submarine through the Status monitor, handheld or otherwise.
Game will crash due to error posted below.

**Version**
v0.15.21.0 - Windows 10

**Additional information**
Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void DrawHUDFront(Microsoft.Xna.Framework.Graphics.SpriteBatch, Barotrauma.GUICustomComponent)
Stack trace: 
   at Barotrauma.Items.Components.MiniMap.DrawHUDFront(SpriteBatch spriteBatch, GUICustomComponent container) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Components\Machines\MiniMap.cs:line 713
   at Barotrauma.GUICustomComponent.Draw(SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUICustomComponent.cs:line 43
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Barotrauma.GUI.Draw(Camera cam, SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 333
   at Barotrauma.GameScreen.Draw(Double deltaTime, GraphicsDevice graphics, SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\GameScreen.cs:line 161
   at Barotrauma.GameMain.Draw(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 1014
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 669
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 508
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

**Comment by Regalis11** [comment]
This seems to happen when a mod doesn't configure the red "you are here" indicator for the status monitor. Made that optional in https://github.com/Regalis11/Barotrauma-development/commit/29f1499308f09c9965e5b786f479005113288c47

**Comment by Rokvach** [comment]
Tested, wasn't able to reproduce the issue, working correctly. Closing.
