### ISSUE TITLE
Object reference not set / Void UpdateBleedingProjSpecific

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#7847]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Most likely mod-related.
```
Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void UpdateBleedingProjSpecific(Barotrauma.AfflictionBleeding, Barotrauma.Limb, Single)
Stack trace: 
   at Barotrauma.CharacterHealth.UpdateBleedingProjSpecific(AfflictionBleeding affliction, Limb targetLimb, Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Characters\Health\CharacterHealth.cs:line 571
   at Barotrauma.CharacterHealth.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Health\CharacterHealth.cs:line 735
   at Barotrauma.Character.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 2780
   at Barotrauma.Character.UpdateAll(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 2646
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 204
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 938
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58
```

**Steps To Reproduce**
```
Selected content packages: Vanilla 0.9, Survivor Vanilla Creature Overhauls, EK Dockyard, IntoTheAbyss, EK Gunnery, Huskmod, EK Armory, EK Utilities, New Wrecks For Barotrauma, Shipwrecks Extended, VisualVarietyPack, Stations from beyond, oClockRadar, Blast Door, [ENV] Beacons Extended, XanMonsters, XanMonsters2, Calic's Resource Storage Containers, No Role Balance, MedOverhaul
```

**Version**
v0.15.22.1

**Additional information**
I got this report from a friend, Most likely related to the mod MedOverhaul but I'm not sure.

**Comment by Regalis11** [comment]
This seemed to happen as a result of non-limb-specific bleeding afflictions (e.g. "Opened Wound" in MedOverhaul). Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1a2c4bb8ac27cd6459081c942d18e9841ca31cd4

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
