### ISSUE TITLE
9fps when tried to join server, had to stop from steam

### ISSUE THREAD

**Issue by rukna08** [Regalis11/Barotrauma#7970]
Barotrauma Client crash report (generated on 1/1/2022 6:24:19 PM)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

25F2DA9FCBD0323CBDF4FC2DA2092C7B

Game version 0.15.22.1 (ReleaseWindows, branch release, revision 898f64d2c0)
Graphics mode: 1366x768 (BorderlessWindowed)
VSync OFF
Language: English
Selected content packages: Vanilla 0.9
Level seed: no level loaded
Loaded submarine: None
Selected screen: Barotrauma.ServerListScreen
SteamManager initialized
Client (Round hadn't been started)

System info:
    Operating system: Microsoft Windows NT 10.0.19043.0 64 bit
    GPU name: Radeon RX 570 Series
    Display mode: {Width:1366 Height:768 Format:Color AspectRatio:1.7786459}
    GPU status: Normal

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Boolean SendP2PPacket(Steamworks.SteamId, Byte[], Int32, Int32, Steamworks.P2PSend)
Stack trace: 
   at Steamworks.SteamNetworking.SendP2PPacket(SteamId steamid, Byte[] data, Int32 length, Int32 nChannel, P2PSend sendType) in <DEV>\Libraries\Facepunch.Steamworks\SteamNetworking.cs:line 130
   at Barotrauma.Networking.SteamP2PClientPeer.Close(String msg, Boolean disableReconnect) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\Primitives\Peers\SteamP2PClientPeer.cs:line 365
   at Barotrauma.Networking.GameClient.Disconnect() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 2717
   at Barotrauma.Networking.GameClient.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 655
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 952
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[1/1/2022 6:24:19 PM] Error while reading a message from server. {Object reference not set to an instance of an object.}
   at Steamworks.SteamNetworking.GetP2PSessionState(SteamId steamid) in <DEV>\Libraries\Facepunch.Steamworks\SteamNetworking.cs:line 156
   at Barotrauma.Networking.SteamP2PClientPeer.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\Primitives\Peers\SteamP2PClientPeer.cs:line 166
   at Barotrauma.Networking.GameClient.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 641
[1/1/2022 6:24:19 PM] Attempting to reconnect...
[1/1/2022 6:24:19 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:19 PM] Attempting to reconnect...
[1/1/2022 6:24:19 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:18 PM] Attempting to reconnect...
[1/1/2022 6:24:18 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:18 PM] Attempting to reconnect...
[1/1/2022 6:24:18 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:18 PM] Attempting to reconnect...
[1/1/2022 6:24:18 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:18 PM] Attempting to reconnect...
[1/1/2022 6:24:18 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:18 PM] Attempting to reconnect...
[1/1/2022 6:24:18 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:18 PM] Attempting to reconnect...
[1/1/2022 6:24:18 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:18 PM] Attempting to reconnect...
[1/1/2022 6:24:18 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:18 PM] Attempting to reconnect...
[1/1/2022 6:24:18 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:17 PM] Attempting to reconnect...
[1/1/2022 6:24:17 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:17 PM] Attempting to reconnect...
[1/1/2022 6:24:17 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:17 PM] Attempting to reconnect...
[1/1/2022 6:24:17 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:17 PM] Attempting to reconnect...
[1/1/2022 6:24:17 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:17 PM] Attempting to reconnect...
[1/1/2022 6:24:17 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:17 PM] Attempting to reconnect...
[1/1/2022 6:24:17 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:17 PM] Attempting to reconnect...
[1/1/2022 6:24:17 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:17 PM] Attempting to reconnect...
[1/1/2022 6:24:17 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:16 PM] Attempting to reconnect...
[1/1/2022 6:24:16 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:16 PM] Attempting to reconnect...
[1/1/2022 6:24:16 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:16 PM] Attempting to reconnect...
[1/1/2022 6:24:16 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:16 PM] Attempting to reconnect...
[1/1/2022 6:24:16 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:16 PM] Attempting to reconnect...
[1/1/2022 6:24:16 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:16 PM] Attempting to reconnect...
[1/1/2022 6:24:16 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:16 PM] Attempting to reconnect...
[1/1/2022 6:24:16 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:16 PM] Attempting to reconnect...
[1/1/2022 6:24:16 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:16 PM] Attempting to reconnect...
[1/1/2022 6:24:16 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:16 PM] Attempting to reconnect...
[1/1/2022 6:24:16 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:15 PM] Attempting to reconnect...
[1/1/2022 6:24:15 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:15 PM] Attempting to reconnect...
[1/1/2022 6:24:15 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:15 PM] Attempting to reconnect...
[1/1/2022 6:24:15 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:15 PM] Attempting to reconnect...
[1/1/2022 6:24:15 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:15 PM] Attempting to reconnect...
[1/1/2022 6:24:15 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:15 PM] Attempting to reconnect...
[1/1/2022 6:24:15 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:15 PM] Attempting to reconnect...
[1/1/2022 6:24:15 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:15 PM] Attempting to reconnect...
[1/1/2022 6:24:15 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:15 PM] Attempting to reconnect...
[1/1/2022 6:24:15 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:14 PM] Attempting to reconnect...
[1/1/2022 6:24:14 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:14 PM] Attempting to reconnect...
[1/1/2022 6:24:14 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:14 PM] Attempting to reconnect...
[1/1/2022 6:24:14 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:14 PM] Attempting to reconnect...
[1/1/2022 6:24:14 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:14 PM] Attempting to reconnect...
[1/1/2022 6:24:14 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:14 PM] Attempting to reconnect...
[1/1/2022 6:24:14 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:14 PM] Attempting to reconnect...
[1/1/2022 6:24:14 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:14 PM] Attempting to reconnect...
[1/1/2022 6:24:14 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:14 PM] Attempting to reconnect...
[1/1/2022 6:24:14 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:14 PM] Attempting to reconnect...
[1/1/2022 6:24:14 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:13 PM] Attempting to reconnect...
[1/1/2022 6:24:13 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:13 PM] Attempting to reconnect...
[1/1/2022 6:24:13 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:13 PM] Attempting to reconnect...
[1/1/2022 6:24:13 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:13 PM] Attempting to reconnect...
[1/1/2022 6:24:13 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:13 PM] Attempting to reconnect...
[1/1/2022 6:24:13 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:13 PM] Attempting to reconnect...
[1/1/2022 6:24:13 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:13 PM] Attempting to reconnect...
[1/1/2022 6:24:13 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:13 PM] Attempting to reconnect...
[1/1/2022 6:24:13 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:13 PM] Attempting to reconnect...
[1/1/2022 6:24:13 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:13 PM] Attempting to reconnect...
[1/1/2022 6:24:13 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:12 PM] Attempting to reconnect...
[1/1/2022 6:24:12 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:12 PM] Attempting to reconnect...
[1/1/2022 6:24:12 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:12 PM] Attempting to reconnect...
[1/1/2022 6:24:12 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:12 PM] Attempting to reconnect...
[1/1/2022 6:24:12 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:12 PM] Attempting to reconnect...
[1/1/2022 6:24:12 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:12 PM] Attempting to reconnect...
[1/1/2022 6:24:12 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:12 PM] Attempting to reconnect...
[1/1/2022 6:24:12 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:12 PM] Attempting to reconnect...
[1/1/2022 6:24:12 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:12 PM] Attempting to reconnect...
[1/1/2022 6:24:12 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:11 PM] Attempting to reconnect...
[1/1/2022 6:24:11 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:11 PM] Attempting to reconnect...
[1/1/2022 6:24:11 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:11 PM] Attempting to reconnect...
[1/1/2022 6:24:11 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:11 PM] Attempting to reconnect...
[1/1/2022 6:24:11 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:11 PM] Attempting to reconnect...
[1/1/2022 6:24:11 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:11 PM] Attempting to reconnect...
[1/1/2022 6:24:11 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:11 PM] Attempting to reconnect...
[1/1/2022 6:24:11 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:11 PM] Attempting to reconnect...
[1/1/2022 6:24:11 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:11 PM] Attempting to reconnect...
[1/1/2022 6:24:11 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:10 PM] Attempting to reconnect...
[1/1/2022 6:24:10 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:10 PM] Attempting to reconnect...
[1/1/2022 6:24:10 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:10 PM] Attempting to reconnect...
[1/1/2022 6:24:10 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:10 PM] Attempting to reconnect...
[1/1/2022 6:24:10 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:10 PM] Attempting to reconnect...
[1/1/2022 6:24:10 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:10 PM] Attempting to reconnect...
[1/1/2022 6:24:10 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:10 PM] Attempting to reconnect...
[1/1/2022 6:24:10 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:10 PM] Attempting to reconnect...
[1/1/2022 6:24:10 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:09 PM] Attempting to reconnect...
[1/1/2022 6:24:09 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:09 PM] Attempting to reconnect...
[1/1/2022 6:24:09 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:09 PM] Attempting to reconnect...
[1/1/2022 6:24:09 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:09 PM] Attempting to reconnect...
[1/1/2022 6:24:09 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:09 PM] Attempting to reconnect...
[1/1/2022 6:24:09 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:09 PM] Attempting to reconnect...
[1/1/2022 6:24:09 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:09 PM] Attempting to reconnect...
[1/1/2022 6:24:09 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:09 PM] Attempting to reconnect...
[1/1/2022 6:24:09 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:08 PM] Attempting to reconnect...
[1/1/2022 6:24:08 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:08 PM] Attempting to reconnect...
[1/1/2022 6:24:08 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:08 PM] Attempting to reconnect...
[1/1/2022 6:24:08 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:08 PM] Attempting to reconnect...
[1/1/2022 6:24:08 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:08 PM] Attempting to reconnect...
[1/1/2022 6:24:08 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:08 PM] Attempting to reconnect...
[1/1/2022 6:24:08 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:08 PM] Attempting to reconnect...
[1/1/2022 6:24:08 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:08 PM] Attempting to reconnect...
[1/1/2022 6:24:08 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:08 PM] Attempting to reconnect...
[1/1/2022 6:24:08 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:07 PM] Attempting to reconnect...
[1/1/2022 6:24:07 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:07 PM] Attempting to reconnect...
[1/1/2022 6:24:07 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:07 PM] Attempting to reconnect...
[1/1/2022 6:24:07 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:07 PM] Attempting to reconnect...
[1/1/2022 6:24:07 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:07 PM] Attempting to reconnect...
[1/1/2022 6:24:07 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:07 PM] Attempting to reconnect...
[1/1/2022 6:24:07 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:07 PM] Attempting to reconnect...
[1/1/2022 6:24:07 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:07 PM] Attempting to reconnect...
[1/1/2022 6:24:07 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:07 PM] Attempting to reconnect...
[1/1/2022 6:24:07 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:06 PM] Attempting to reconnect...
[1/1/2022 6:24:06 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:06 PM] Attempting to reconnect...
[1/1/2022 6:24:06 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:06 PM] Attempting to reconnect...
[1/1/2022 6:24:06 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:06 PM] Attempting to reconnect...
[1/1/2022 6:24:06 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:06 PM] Attempting to reconnect...
[1/1/2022 6:24:06 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:06 PM] Attempting to reconnect...
[1/1/2022 6:24:06 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:06 PM] Attempting to reconnect...
[1/1/2022 6:24:06 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:06 PM] Attempting to reconnect...
[1/1/2022 6:24:06 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:05 PM] Attempting to reconnect...
[1/1/2022 6:24:05 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:05 PM] Attempting to reconnect...
[1/1/2022 6:24:05 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:05 PM] Attempting to reconnect...
[1/1/2022 6:24:05 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:05 PM] Attempting to reconnect...
[1/1/2022 6:24:05 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:05 PM] Attempting to reconnect...
[1/1/2022 6:24:05 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:05 PM] Attempting to reconnect...
[1/1/2022 6:24:05 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:05 PM] Attempting to reconnect...
[1/1/2022 6:24:05 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:05 PM] Attempting to reconnect...
[1/1/2022 6:24:05 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:05 PM] Attempting to reconnect...
[1/1/2022 6:24:05 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:04 PM] Attempting to reconnect...
[1/1/2022 6:24:04 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:04 PM] Attempting to reconnect...
[1/1/2022 6:24:04 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:04 PM] Attempting to reconnect...
[1/1/2022 6:24:04 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:04 PM] Attempting to reconnect...
[1/1/2022 6:24:04 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:04 PM] Attempting to reconnect...
[1/1/2022 6:24:04 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:04 PM] Attempting to reconnect...
[1/1/2022 6:24:04 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:04 PM] Attempting to reconnect...
[1/1/2022 6:24:04 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:04 PM] Attempting to reconnect...
[1/1/2022 6:24:04 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:04 PM] Attempting to reconnect...
[1/1/2022 6:24:04 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:04 PM] Attempting to reconnect...
[1/1/2022 6:24:04 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:03 PM] Attempting to reconnect...
[1/1/2022 6:24:03 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:03 PM] Attempting to reconnect...
[1/1/2022 6:24:03 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:03 PM] Attempting to reconnect...
[1/1/2022 6:24:03 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:03 PM] Attempting to reconnect...
[1/1/2022 6:24:03 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:03 PM] Attempting to reconnect...
[1/1/2022 6:24:03 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:03 PM] Attempting to reconnect...
[1/1/2022 6:24:03 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:03 PM] Attempting to reconnect...
[1/1/2022 6:24:03 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:03 PM] Attempting to reconnect...
[1/1/2022 6:24:03 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:03 PM] Attempting to reconnect...
[1/1/2022 6:24:03 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:02 PM] Attempting to reconnect...
[1/1/2022 6:24:02 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:02 PM] Attempting to reconnect...
[1/1/2022 6:24:02 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:02 PM] Attempting to reconnect...
[1/1/2022 6:24:02 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:02 PM] Attempting to reconnect...
[1/1/2022 6:24:02 PM] Received a disconnect message (SteamP2P connection could not be established)
[1/1/2022 6:24:02 PM] Attempting to reconnect...

**Comment by Regalis11** [comment]
Looks like a couple of things went wrong here: the game failed to establish a connection to the server for some reason, which would cause it to attempt reconnecting constantly, leading to the enormous FPS drop. Eventually it would give up, and try to disconnect from the server, which would cause the crash when the game tried to tell the server it's disconnecting, without having established a connection to the server in the first place.

Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/4617c4187db002357dcb4b1d4859ba49189a1b4f and https://github.com/Regalis11/Barotrauma-development/commit/5f8921c385a257e5cc9fd52ea4e0a95ed3aeff77

**Comment by Rokvach** [comment]
There hasn't been any sightings of this happening in the Unstable since the fix released there, seems to be working correctly. Closing.
