### ISSUE TITLE
Game Crash, suspect firing Harpoon at Terminal Cells

### ISSUE THREAD

**Issue by stephenmcgruer** [Regalis11/Barotrauma#7973]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When fighting a Thalamus-infested wreck, we encountered a game crash:

[crashreport.log](https://github.com/Regalis11/Barotrauma/files/7798476/crashreport.log)

```
Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void Update(Single, Barotrauma.Camera)
Stack trace: 
   at Barotrauma.Items.Components.Rope.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\Rope.cs:line 0
   at Barotrauma.Item.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Item.cs:line 1683
   at Barotrauma.MapEntity.UpdateAll(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\MapEntity.cs:line 567
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 264
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 938
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58
```

Given the stack trace and what our team was up to at the point, we think it was caused by someone killing a Terminal Cell (the red floating enemy) with a Harpoon gun. It was loaded with Physicorium ammo, if that matters.

**Steps To Reproduce**

1. Equip a harpoon gun and harpoon (possibly physicorium harpoon)
2. Shoot at and kill a Terminal Cell

**Version**
Windows 0.15.22.1

**Additional information**
Other possible relevant info:

- We were generally under attack by a Thalmus wreck.
- Multiplayer game with 5 players total.
- One player was cutting into the wreck just at the wreck's railgun.
- Other players were mostly fighting Terminal Cells on our submarine, using non-harpoon weapons (e.g. revolvers, SMG, etc)

**Comment by itchyOwl** [comment]
Couldn't repro either in sp or mp.

**Comment by itchyOwl** [comment]
The stack trace doesn't make any sense either: There's no line 0 and the Update method is certainly not located at line 0. Can't spot anything that could throw a null reference exception in the Update method.

**Comment by Ek-Videogames** [comment]
Could be trying to rope to a creature that no longer exists, Because terminal cells pop on impact?

**Comment by itchyOwl** [comment]
Everything is possible, but like I said, I can't spot anything wrong in the code, can't repro it, and the line numbers don't make sense. So it's difficult to fix this.
![image](https://user-images.githubusercontent.com/5370738/149491079-1d4289ed-e461-45a9-a2e7-abe34405a75f.png)

**Comment by cshingle** [comment]
I had a crash with a stack trace similar to this one. Everyone but the host crashed to desktop. We were able to join back in and regain control over our characters.
The host loves his physicorium harpoons and was fighting a tiger thrasher nest at the time of the crash, so it very well could be related. The host has the Deep Sea Slayer talent.

[crashreport (5).log](https://github.com/Regalis11/Barotrauma/files/8508279/crashreport.5.log)

**Comment by Regalis11** [comment]
Not fixed, reopening

**Comment by Regalis11** [comment]
I found one way to cause a crash with this exact error message (the line number was 0 for me as well - no idea why though). Happened when the limb the rope was attached to was removed. Here's one way to repro this:

1. Spawn a latcher in single player and take control of it with console commands
2. Fire the tongue at the sub and wait for it to attach
3. Kill and despawn the latcher with the commands `kill` and `despawnnow`
