### ISSUE TITLE
[Crash] readStream was disconnected unexpectedly

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#7985]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I was doing some performance testing on multiplayer and was running a wreck salvage mission with 100% hellish difficulty, when I got closer to the wreck a massive amount of creatures suddenly spawned in and moments later my game crashed. 

```
Exception: readStream was disconnected unexpectedly (System.Exception)
Target site: Void CheckPipeConnected(System.String, System.IO.Pipes.AnonymousPipeServerStream)
Stack trace: 
   at Barotrauma.Networking.ChildServerRelay.CheckPipeConnected(String name, AnonymousPipeServerStream pipe) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\ChildServerRelay.cs:line 126
   at Barotrauma.Networking.ChildServerRelay.UpdateRead() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\ChildServerRelay.cs:line 154
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadHelper.ThreadStart()
```

**Steps To Reproduce**
No known steps

**Version**
Branch: dev
Commit: https://github.com/Regalis11/Barotrauma-development/commit/3fe18f28e7d9c4cab8a969a3fe1dc7cd5378080c

**Additional information**
This was my VS view after the crash
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/6e3ed1cf-6bf0-4ac7-ba1f-1b27014f264f)

**Comment by thedogs1** [comment]
My issue, happens every time I start a game no matter what making the game completely unplayable with no fixes at all.

**Comment by Ksarper** [comment]
Any fixes already?

**Comment by kamiokk** [comment]
I met similar problem, here is crash report:

`Barotrauma Client crash report (generated on 03/16/2023 00:46:24)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

71290F513E6B598EAA3CFF037A2EAB34

Game version 1.0.7.0 (ReleaseWindows, branch release/1.0, revision e1df60d5cc)
Graphics mode: 1920x1080 (Windowed)
VSync OFF
Language: Simplified Chinese
Selected content packages: Vanilla, [EA-HI]木卫二萌化计划, Týr-提尔号[cn][en]
Level seed: Nwoska18
Loaded submarine: Týr-提尔号 [cn] (118100C200C2511A75C945E28A34262A)
Selected screen: Barotrauma.RoundSummaryScreen
SteamManager initialized
Client (Round hadn't been started)

System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit
    GPU name: NVIDIA GeForce RTX 3070
    Display mode: {Width:2560 Height:1440 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: readStream was disconnected unexpectedly (System.Exception)
Target site: Void CheckPipeConnected(System.String, System.IO.Pipes.AnonymousPipeServerStream)
Stack trace: 
   at Barotrauma.Networking.ChildServerRelay.CheckPipeConnected(String name, AnonymousPipeServerStream pipe) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\ChildServerRelay.cs:line 164
   at Barotrauma.Networking.ChildServerRelay.UpdateRead() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\ChildServerRelay.cs:line 175
   at System.Threading.Thread.StartCallback()

Last debug messages:
[03/16/2023 00:44:48] Generating an outpost for the start of the level... (Location: Nwoska采矿公司, level type: Outpost)
[03/16/2023 00:44:48] Level identifier: outpostlevel
[03/16/2023 00:44:48] Creating hulls between docking ports failed. The upper docking port seems to be very far from any hulls in the upper submarine.`

**Comment by Regalis11** [comment]
We've now added some more logging that should hopefully help us find what's causing these crashes. Now the "pipe is broken" crash report should include the exit code of the server process, giving us more clues for diagnosing the issue, and the server should create simplified crash report if there's some kind of an issue with creating the normal crash report.

**Comment by shockingboring** [comment]
[crashreport (2).log](https://github.com/FakeFishGames/Barotrauma/files/14115242/crashreport.2.log)
[crashreport (3).log](https://github.com/FakeFishGames/Barotrauma/files/14115244/crashreport.3.log)
[crashreport (4).log](https://github.com/FakeFishGames/Barotrauma/files/14115245/crashreport.4.log)
[crashreport (5).log](https://github.com/FakeFishGames/Barotrauma/files/14115246/crashreport.5.log)
[crashreport (6).log](https://github.com/FakeFishGames/Barotrauma/files/14115247/crashreport.6.log)
[crashreport (7).log](https://github.com/FakeFishGames/Barotrauma/files/14115248/crashreport.7.log)
[crashreport (8).log](https://github.com/FakeFishGames/Barotrauma/files/14115249/crashreport.8.log)
[crashreport.log](https://github.com/FakeFishGames/Barotrauma/files/14115251/crashreport.log)


since this needs more info. here's a bunch of possibly related crash reports.
it crashes pretty consitently unfortunately. we have barely finished a single mission for 3 days and not for a lack of trying.
