### ISSUE TITLE
Game crashes when opening a specific hatch on a custom submarine (Unable to cast object of type 'Barotrauma.Item' to type 'Barotrauma.Hull')

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#8036]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Originally reported by JP on Discord, but I managed to reproduce the issue too

Opening a specific hatch on JP's Malaco submarine leads to a crash

Submarine: [https://app.zenhub.com/files/93301055/09f33e41-d47e-45f9-b571-350dfa4630e9/download](https://app.zenhub.com/files/93301055/09f33e41-d47e-45f9-b571-350dfa4630e9/download)

**Steps To Reproduce**
Install the custom sub and load it up on sub editor test mode, try and open this hatch and notice that the game crashes
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/df71f02b-7d95-47f8-9668-f412c0eb5afa)

**Version**
Unstable 0.16.0.0

**Additional information**
```
Barotrauma Client crash report (generated on 14.1.2022 11:35:45)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


596A9C4F202B44E2713E2432AB256455


Game version 0.16.0.0 (UnstableWindows, branch dev, revision 4d8515da6f)
Graphics mode: 2560x1440 (BorderlessWindowed)
VSync OFF
Language: English
Selected content packages: Vanilla 0.9, Malaco_1.068
Level seed: no level loaded
Loaded submarine: Malaco_2.1 (0150E5B0BCAB20A760FFD10B50909BA1)
Selected screen: Barotrauma.GameScreen
SteamManager initialized


System info:
    Operating system: Microsoft Windows NT 10.0.19042.0 64 bit
    GPU name: NVIDIA GeForce GTX 980 Ti
    Display mode: {Width:2560 Height:1440 Format:Color AspectRatio:1,7777778}
    GPU status: Normal


Exception: Unable to cast object of type 'Barotrauma.Item' to type 'Barotrauma.Hull'. (System.InvalidCastException)
Target site: Void EmitParticles(Single)
Stack trace: 
   at Barotrauma.Gap.EmitParticles(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Map\Gap.cs:line 135
   at Barotrauma.MapEntity.UpdateAll(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\MapEntity.cs:line 562
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 270
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 941
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59


Last debug messages:
[14.1.2022 11:32:40] OpenAL Soft on Mikrofoni (Blackstorm Scout ) 44
[14.1.2022 11:30:21] (Msg) SDR RelayNetworkStatus:  avail=OK  config=OK  anyrelay=OK   (OK)
[14.1.2022 11:30:21] (Msg) Ping location: sto2=13+1,sto=14+1/13+1,ams=38+3/33+1,waw=51+5/34+1,lhr=45+4/37+1,fra=44+4/42+1,par=53+5/42+1,vie=51+5/44+1,mad=68+6/64+1,iad=/119+1,sgp=202+20/203+20,gru=225+22
[14.1.2022 11:30:21] (Msg) Ping measurement completed
[14.1.2022 11:30:21] (Debug) Destroying relay 'iad#85 (162.254.192.70:27053)' because initial_ping_timeout
[14.1.2022 11:30:19] (Debug) Destroying relay 'iad#71 (162.254.192.70:27039)' because initial_ping_timeout
[14.1.2022 11:30:16] (Verbose) Communications with routing cluster 'seo' established.
[14.1.2022 11:30:16] (Verbose) Communications with routing cluster 'syd' established.
[14.1.2022 11:30:16] (Verbose) Communications with routing cluster 'tyo1' established.
[14.1.2022 11:30:16] (Verbose) Communications with routing cluster 'tyo' established.
[14.1.2022 11:30:16] (Verbose) Communications with routing cluster 'sgp' established.
[14.1.2022 11:30:16] (Verbose) Communications with routing cluster 'maa' established.
[14.1.2022 11:30:16] (Verbose) Communications with routing cluster 'scl' established.
[14.1.2022 11:30:16] (Verbose) Communications with routing cluster 'jnb' established.
[14.1.2022 11:30:16] (Verbose) Communications with routing cluster 'lim' established.
[14.1.2022 11:30:16] (Verbose) Communications with routing cluster 'bom' established.
[14.1.2022 11:30:16] (Verbose) Communications with routing cluster 'sea' established.
[14.1.2022 11:30:16] (Verbose) Communications with routing cluster 'lax' established.
[14.1.2022 11:30:16] (Verbose) Communications with routing cluster 'waw' established.
[14.1.2022 11:30:16] (Verbose) Communications with routing cluster 'eze' established.
[14.1.2022 11:30:16] (Verbose) Communications with routing cluster 'vie' established.
[14.1.2022 11:30:16] (Verbose) Communications with routing cluster 'ord' established.
[14.1.2022 11:30:16] (Verbose) Communications with routing cluster 'hkg' established.
[14.1.2022 11:30:16] (Verbose) Communications with routing cluster 'gru' established.
[14.1.2022 11:30:16] (Verbose) Communications with routing cluster 'sto' established.
[14.1.2022 11:30:16] (Verbose) Communications with routing cluster 'sto2' established.
[14.1.2022 11:30:16] (Verbose) Communications with routing cluster 'mad' established.
[14.1.2022 11:30:16] (Verbose) Communications with routing cluster 'dxb' established.
[14.1.2022 11:30:16] (Verbose) Communications with routing cluster 'par' established.
[14.1.2022 11:30:16] (Verbose) Communications with routing cluster 'lhr' established.
[14.1.2022 11:30:16] (Verbose) Communications with routing cluster 'dfw' established.
[14.1.2022 11:30:16] (Verbose) Communications with routing cluster 'atl' established.
[14.1.2022 11:30:16] (Verbose) Communications with routing cluster 'fra' established.
[14.1.2022 11:30:16] (Verbose) Communications with routing cluster 'ams' established.
[14.1.2022 11:30:16] (Msg) SDR RelayNetworkStatus:  avail=Attempting  config=OK  anyrelay=Attempting   (Performing ping measurement)
[14.1.2022 11:30:16] (Msg) Performing ping measurement
[14.1.2022 11:30:16] (Msg) Got SDR network config.  Loaded revision 369 OK
[14.1.2022 11:30:16] (Warning) SDR network config fetch first attempt failed.  HTTP 504.  .  Trying again.
[14.1.2022 11:30:03] Attempting to open ALC device "OpenAL Soft on Kaiuttimet (Realtek High Definition Audio)"
[14.1.2022 11:30:03] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[14.1.2022 11:30:02] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c421e7eefc0179729a8cfb8862b8ce0648acb306

**Comment by Rokvach** [comment]
Tested, I wasn't able to reproduce the issue anymore. Working correctly. Closing.
