### ISSUE TITLE
Nullref exception in GUIListBox.CalculateChildrenOffsets

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#8136]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Crash report received through GA

**Steps To Reproduce**
Unknown

**Version**
v0.16.1.0

**Additional information**
```
Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void CalculateChildrenOffsets(System.Action`2[System.Int32,Microsoft.Xna.Framework.Point])
Stack trace: 
   at Barotrauma.GUIListBox.CalculateChildrenOffsets(Action`2 callback) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIListBox.cs:line 0
   at Barotrauma.GUIListBox.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIListBox.cs:line 841
   at Barotrauma.GUI.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1257
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 990
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58
```

**Comment by Regalis11** [comment]
Might be fixed in https://github.com/Regalis11/Barotrauma-development/commit/4550606918566df8349200fdba3516c5b369e775

**Comment by Rokvach** [comment]
There hasn't been new sightings of this happening in Unstable, seems to be working correctly. Closing.
