### ISSUE TITLE
Error while attempting to host campaign server

### ISSUE THREAD

**Issue by thebabyjesusus** [Regalis11/Barotrauma#8147]
- [✓] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Unable to host a campaign online server. I have tried verifying files as well as reinstalling.

**Steps To Reproduce**
- Create a server and click on the campaign mission type
- hourglass loading cursor comes up
- error message appears
- get sent to the server browser page

Happens every time 

**Version**
v0.15.23.0
Windows 10 (can provide further specifications if needed)

**Additional information**
Every time this happens there are three files that fail to be validated. 

**Log:** 
Error while reading a message from server. {Object reference not set to an instance of an object.}
   at Barotrauma.MultiPlayerCampaignSetupUI.UpdateLoadMenu(IEnumerable`1 saveFiles) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\CampaignSetupUI\MultiPlayerCampaignSetupUI.cs:line 267
   at Barotrauma.MultiPlayerCampaignSetupUI..ctor(GUIComponent newGameContainer, GUIComponent loadGameContainer, IEnumerable`1 saveFiles) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\CampaignSetupUI\MultiPlayerCampaignSetupUI.cs:line 194
   at Barotrauma.MultiPlayerCampaign.StartCampaignSetup(IEnumerable`1 saveFiles) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameSession\GameModes\MultiPlayerCampaign.cs:line 63
   at Barotrauma.Networking.GameClient.ReadDataMessage(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 918
   at Barotrauma.Networking.SteamP2POwnerPeer.HandleDataMessage(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\Primitives\Peers\SteamP2POwnerPeer.cs:line 0
   at Barotrauma.Networking.SteamP2POwnerPeer.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\Primitives\Peers\SteamP2POwnerPeer.cs:line 227
   at Barotrauma.Networking.GameClient.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 641

**Comment by Regalis11** [comment]
Duplicate of https://github.com/regalis11/barotrauma/issues/7982

As mentioned in the other ticket, the error seems to happen because the client is trying to display a save file with no file path. I'm not sure how that can happen, but something you could try is deleting the multiplayer campaign saves (located in `C:/Users/*user*/AppData/Local/Daedalic Entertainment GmbH/Barotrauma`), or temporarily moving them to another location and seeing if that helps if there's anything in there you don't want to lose.

**Comment by thebabyjesusus** [comment]
Sorry for the duplicate, must have only been looking at open issues... 

Just tried your suggested fix and so far it is working perfectly. Thanks!
