### ISSUE TITLE
AI crash while trying to get to fire extinguisher

### ISSUE THREAD

**Issue by Instant2116** [Regalis11/Barotrauma#8219]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
AI crash while trying to get to fire extinguisher, that was stolen (i have noticed that bots can pass airlock only if the accidently fall cross it, so i stolen fire extinguishers and left it in submarine airlock

**Steps To Reproduce**
Stole all or most of fire extinguishers and left them in submarine airlock or in neighboring to it with opened door

**Version**
Game version 0.15.23.0 (ReleaseWindows, branch release, revision 0a990787e8) (Windows).

**Additional information**
Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void Act(Single)
Stack trace: 
   at Barotrauma.AIObjectiveExtinguishFire.Act(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\Objectives\AIObjectiveExtinguishFire.cs:line 119
   at Barotrauma.AIObjective.TryComplete(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\Objectives\AIObjective.cs:line 177
   at Barotrauma.HumanAIController.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\HumanAIController.cs:line 431
   at Barotrauma.Character.UpdateAll(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 2646
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 204
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 938
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58 # #

**Comment by Regalis11** [comment]
I'm afraid I could not find a way to reproduce this. Tested by stealing all the fire extinguishers in an outpost and taking them to the sub's airlock, and then lighting some fires in the outpost.

**Comment by Regalis11** [comment]
No known steps to repro, closing

**Comment by R4to0** [comment]
I have the same issue as well. Was able to reproduce multiple times on both Dedicated and Listen/Host.

Steps to reproduce (the only that actually crashed for me, other ways didn't):
 1. In a outpost that you can interact with the Reactor, increase the turbine output to max until all the junction boxes gets overloaded and start catching under fire.
 2. Hold it high so the fire is continuously burning everything (lol).
 3. Wait for multiple outpost NPC to grab a fire extinguisher to try extinguish the fire.
 4. Once one of the places in the outpost get its fire extinguished and the NPC announces it, the dedicated server process will crash.


```
Barotrauma Dedicated Server crash report (generated on 22/03/2022 21:59:01)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


Game version 0.16.7.0 (ReleaseWindows, branch release, revision aa4c852c2c)
Language: English
Selected content packages: Vanilla 0.9, DynamicEuropa, REALLYBIGMAP, Stations from beyond, Zombies, Meaningful Upgrades, Huskmod, Shipwrecks Extended, [ENV] Beacons Extended, Genes+, Survivor Survivator Fixes, Tail's Melee Weapons Pack, Survivor Vanilla Creature Overhauls, Survivor Extended Monsters Fixes, Survivor Monster Pack Test fixes, Survivor Undersea Horrors Fixes, Survivor Other Creature fixes, Survivor Xanmonsters1 Fixes, Rucksack 2.0, Survivor Xanmonsters2 Fixes, EK Gunnery, EK Armory, EK Utilities, RIBA Portable Items, Abyssal Warsuit (Abyss update), BaroTraumatic, Survivor New Creatures
Level seed: Telephassa Linea
Loaded submarine: Dugong (2BCF3ACB16580D94EB9C371A0D75C8F1)
Selected screen: Barotrauma.GameScreen
Server (Round had started)


System info:
    Operating system: Microsoft Windows NT 6.2.9200.0 64 bit


Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void Act(Single)
Stack trace: 
   at Barotrauma.AIObjectiveExtinguishFire.Act(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\Objectives\AIObjectiveExtinguishFire.cs:line 119
   at Barotrauma.AIObjective.TryComplete(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\Objectives\AIObjective.cs:line 178
   at Barotrauma.HumanAIController.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\HumanAIController.cs:line 433
   at Barotrauma.Character.UpdateAll(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 2669
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 207
   at Barotrauma.GameMain.Run() in <DEV>\Barotrauma\BarotraumaServer\ServerSource\GameMain.cs:line 391
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Program.cs:line 58


Last debug messages:
   22/03/2022 21:59:01 - [22/03/2022 21:59:01]
  Saving banlist
   22/03/2022 21:58:59 - [22/03/2022 21:58:59]
  Esteban Lucas: Extinguished a fire in upper aft side!
   22/03/2022 21:58:59 - [22/03/2022 21:58:59]
  Ethel Fonte equipped Fire Extinguisher
   22/03/2022 21:58:58 - [22/03/2022 21:58:58]
  Micheal Kinney: Need someone to repair devices in upper aft side!
   22/03/2022 21:58:58 - [22/03/2022 21:58:58]
  Frances Day equipped Fire Extinguisher
   22/03/2022 21:58:56 - [22/03/2022 21:58:56]
  Lena Hines equipped Fire Extinguisher
   22/03/2022 21:58:55 - [22/03/2022 21:58:55]
  Esteban Lucas equipped Fire Extinguisher
   22/03/2022 21:58:53 - [22/03/2022 21:58:53]
  Katrina Lawrence unequipped Screwdriver
   22/03/2022 21:58:53 - [22/03/2022 21:58:53]
  Mckinley Elliott started repairing Junction Box
   22/03/2022 21:58:51 - [22/03/2022 21:58:51]
  Peter Gonzales: Fire in upper aft side!
   22/03/2022 21:58:51 - [22/03/2022 21:58:51]
  Lena Hines: Upper aft side is on fire!
   22/03/2022 21:58:51 - [22/03/2022 21:58:51]
  Erline Buckley: Upper aft side is on fire!
   22/03/2022 21:58:51 - [22/03/2022 21:58:51]
  Mckinley Elliott: Fire in upper aft side!
   22/03/2022 21:58:51 - [22/03/2022 21:58:51]
  Dannette Santistevan: Upper aft side is on fire!

```

**Comment by itchyOwl** [comment]
Couldn't repro, but I added some null checks and increased the code robustness in places that I think could in some edge cases cause the null reference exception: Regalis11/Barotrauma-development@e85d7bf.

I did follow the steps provided and also attempted to repro it by spawning fires everywhere. Both in single player and in multiplayer. You seem to have a lot of mods enabled. Did you try if it happens without them too? The reactors in vanilla outposts shouldn't be interactable by the player, although you can change this in the subeditor.

**Comment by R4to0** [comment]
> Couldn't repro, but I added some null checks and increased the code robustness in places that I think could in some edge cases cause the null reference exception: [Regalis11/Barotrauma-development@e85d7bf](https://github.com/Regalis11/Barotrauma-development/commit/e85d7bf).
> 
> I did follow the steps provided and also attempted to repro it by spawning fires everywhere. Both in single player and in multiplayer. You seem to have a lot of mods enabled. Did you try if it happens without them too? The reactors in vanilla outposts shouldn't be interactable by the player, although you can change this in the subeditor.

Yes, I have a few mods enabled as this was a friend's save that I started hosting on a dedicated server. You're right, in a vanilla game you usually don't interact with them so I think I can only do a trial and error with a few mods on a clean save and see which one causes it. I do *suspect* [Stations from beyond](https://steamcommunity.com/sharedfiles/filedetails/?id=2585543390) is doing that.

Thank you a lot for checking it anyway.

Enabled mods:
```
DynamicEuropa
Stations from beyond
Zombies
Meaningful Upgrades
Huskmod
Shipwrecks Extended
[ENV] Beacons Extended
Genes+
Survivor Survivator Fixes
Tail's Melee Weapons Pack
Survivor Vanilla Creature Overhauls
Survivor Extended Monsters Fixes
Survivor Monster Pack Test fixes
Survivor Undersea Horrors Fixes
Survivor Other Creature fixes
Survivor Xanmonsters1 Fixes
Rucksack 2.0
Survivor Xanmonsters2 Fixes
EK Gunnery
EK Armory
EK Utilities
RIBA Portable Items
Abyssal Warsuit (Abyss update)
BaroTraumatic
Survivor New Creatures

```

**Comment by Regalis11** [comment]
No known steps to repro, closing
