### ISSUE TITLE
When player turned into husk the game crashed

### ISSUE THREAD

**Issue by Lucian0410** [Regalis11/Barotrauma#8256]
Full crash report:

Barotrauma Client crash report (generated on 2/12/2022 5:42:27 PM)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

9EB15224D06FF5330A4D7A4BAF52D263

Game version 0.16.4.0 (UnstableWindows, branch release, revision 96d2e50b12)
Graphics mode: 1920x1080 (Fullscreen)
VSync ON
Language: English
Selected content packages: Vanilla 0.9
Level seed: no level loaded
Loaded submarine: Humpback (F506AF52477A49E96CF552CA67700823)
Selected screen: Barotrauma.GameScreen
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19043.0 64 bit
    GPU name: NVIDIA GeForce GTX 1050 Ti
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void DrawHUD(Microsoft.Xna.Framework.Graphics.SpriteBatch)
Stack trace: 
   at Barotrauma.CharacterHealth.DrawHUD(SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Characters\Health\CharacterHealth.cs:line 1002
   at Barotrauma.GameScreen.Draw(Double deltaTime, GraphicsDevice graphics, SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\GameScreen.cs:line 101
   at Barotrauma.GameMain.Draw(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 1050
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 669
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 508
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

Last debug messages:
[2/12/2022 5:42:27 PM] Attempted to access a potentially removed character. Character: Tania Pollard, id: 1108, removed: True. AnimController.Collider == null
   at System.Environment.get_StackTrace()
   at Barotrauma.Character.get_SimPosition() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 894
   at Barotrauma.Character.get_Position() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 911
   at Barotrauma.Entity.get_WorldPosition() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Entity.cs:line 43
   at Barotrauma.Character.UpdateAll(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 2635
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 212
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 966
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 651
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59
[2/12/2022 5:39:55 PM] spawn mudraptor cursor
[2/12/2022 5:38:56 PM] giveaffliction huskinfection 50 "Tania Pollard"
[2/12/2022 5:38:48 PM] Character "taniapollard" not found
[2/12/2022 5:38:48 PM] giveaffliction huskinfection 50 "TaniaPollard"
[2/12/2022 5:38:18 PM] Steam achievements have been disabled during this play session.
[2/12/2022 5:38:18 PM] Enabled cheat commands.
[2/12/2022 5:38:18 PM] enablecheats
[2/12/2022 5:37:29 PM] (Msg) SDR RelayNetworkStatus:  avail=OK  config=OK  anyrelay=OK   (OK)
[2/12/2022 5:37:29 PM] (Msg) Ping location: lax=29+2,sea=47+4,dfw=48+4,atl=66+6,ord=70+7/69+4,iad=84+8/79+6,tyo1=126+12,tyo=138+13/126+12,lim=159+15/130+2,fra=169+16/164+6,sgp=177+17/178+17,gru=230+23/197+6
[2/12/2022 5:37:29 PM] (Msg) Ping measurement completed
[2/12/2022 5:37:28 PM] (Verbose) Communications with routing cluster 'atl' established.
[2/12/2022 5:37:28 PM] (Debug) Destroying relay 'atl#63 (162.254.199.173:27031)' because initial_ping_timeout
[2/12/2022 5:37:26 PM] (Verbose) Communications with routing cluster 'jnb' established.
[2/12/2022 5:37:26 PM] (Verbose) Communications with routing cluster 'waw' established.
[2/12/2022 5:37:26 PM] (Verbose) Communications with routing cluster 'vie' established.
[2/12/2022 5:37:26 PM] (Verbose) Communications with routing cluster 'maa' established.
[2/12/2022 5:37:26 PM] (Verbose) Communications with routing cluster 'sgp' established.
[2/12/2022 5:37:26 PM] (Verbose) Communications with routing cluster 'sto2' established.
[2/12/2022 5:37:26 PM] (Verbose) Communications with routing cluster 'sto' established.
[2/12/2022 5:37:26 PM] (Verbose) Communications with routing cluster 'seo' established.
[2/12/2022 5:37:26 PM] (Verbose) Communications with routing cluster 'syd' established.
[2/12/2022 5:37:26 PM] (Verbose) Communications with routing cluster 'tyo' established.
[2/12/2022 5:37:26 PM] (Verbose) Communications with routing cluster 'tyo1' established.
[2/12/2022 5:37:26 PM] (Verbose) Communications with routing cluster 'mad' established.
[2/12/2022 5:37:26 PM] (Verbose) Communications with routing cluster 'scl' established.
[2/12/2022 5:37:26 PM] (Verbose) Communications with routing cluster 'bom' established.
[2/12/2022 5:37:26 PM] (Verbose) Communications with routing cluster 'par' established.
[2/12/2022 5:37:26 PM] (Verbose) Communications with routing cluster 'dxb' established.
[2/12/2022 5:37:26 PM] (Verbose) Communications with routing cluster 'lim' established.
[2/12/2022 5:37:26 PM] (Verbose) Communications with routing cluster 'lhr' established.
[2/12/2022 5:37:26 PM] (Verbose) Communications with routing cluster 'gru' established.
[2/12/2022 5:37:26 PM] (Verbose) Communications with routing cluster 'hkg' established.
[2/12/2022 5:37:26 PM] (Verbose) Communications with routing cluster 'eze' established.
[2/12/2022 5:37:25 PM] (Verbose) Communications with routing cluster 'ord' established.
[2/12/2022 5:37:25 PM] (Verbose) Communications with routing cluster 'fra' established.
[2/12/2022 5:37:25 PM] (Verbose) Communications with routing cluster 'ams' established.
[2/12/2022 5:37:25 PM] (Verbose) Communications with routing cluster 'sea' established.
[2/12/2022 5:37:25 PM] (Verbose) Communications with routing cluster 'lax' established.
[2/12/2022 5:37:25 PM] (Verbose) Communications with routing cluster 'iad' established.
[2/12/2022 5:37:25 PM] (Verbose) Communications with routing cluster 'dfw' established.
[2/12/2022 5:37:25 PM] (Msg) SDR RelayNetworkStatus:  avail=Attempting  config=OK  anyrelay=Attempting   (Performing ping measurement)
[2/12/2022 5:37:25 PM] (Msg) Performing ping measurement
[2/12/2022 5:37:25 PM] (Msg) Got SDR network config.  Loaded revision 371 OK
[2/12/2022 5:37:25 PM] (Warning) SDR network config fetch first attempt failed.  HTTP 504.  .  Trying again.
[2/12/2022 5:36:58 PM] Attempting to open ALC device "OpenAL Soft on Speaker/Headphone (Realtek High Definition Audio)"
[2/12/2022 5:36:58 PM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[2/12/2022 5:36:57 PM] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[2/12/2022 5:36:56 PM] Logged in as Lucian (SteamID STEAM_1:0:242209154)

**Comment by Regalis11** [comment]
I couldn't find a way to reproduce this, but added some null checks that should hopefully prevent this from crashing the game https://github.com/Regalis11/Barotrauma-development/commit/295bbf0a9f98729e71fb46e18aa9f160ce5dc56b

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
