### ISSUE TITLE
NullReferenceException on attempt to use an incorrectly formatted character file

### ISSUE THREAD

**Issue by DrinkFromTheCup** [Regalis11/Barotrauma#8279]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Steps are synthetic! Invalid game modification only!

Attempt to use inappropriate data from mod results in crash instead of console error (or whatever other means of notifying end user of invalid content possible).

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void Draw(Double, Microsoft.Xna.Framework.Graphics.GraphicsDevice, Microsoft.Xna.Framework.Graphics.SpriteBatch)
Stack trace: 
   at Barotrauma.CharacterEditor.CharacterEditorScreen.Draw(Double deltaTime, GraphicsDevice graphics, SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\CharacterEditor\CharacterEditorScreen.cs:line 855
   at Barotrauma.GameMain.Draw(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 1050
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 669
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 508
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58

**Steps To Reproduce**

For me, it was like that:
Assemble faulty mod with ragdoll/texture/character replacer. No problem.
Load faulty mod on game start. No problem.
Open character editor with replaced character preselected. Crash.

**Version**
Today's Unstable.

**Additional information**
An archive with the modification: 
[somemod.zip](https://github.com/Regalis11/Barotrauma/files/8060506/somemod.zip)
Log: 
[crashreport (2).log](https://github.com/Regalis11/Barotrauma/files/8060529/crashreport.2.log)

**Comment by Regalis11** [comment]
No longer seems to happen: the mod can't be enabled due to the errors.
