### ISSUE TITLE
Crash when opening the tab menu on a sub that hasn't been saved

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#8348]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The game crashes when you try to view the specs of a submarine that has never been saved

**Steps To Reproduce**
1. Create the bare minimum of a sub in the sub editor
2. Start the test mode
3. Open the submarine tab of the tab menu

**Version**
v0.16.x

**Additional information**
```
Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Boolean IsVanillaSubmarine()
Stack trace: 
   at Barotrauma.SubmarineInfo.IsVanillaSubmarine() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\SubmarineInfo.cs:line 413
   at Barotrauma.SubmarineInfo.CreateSpecsWindow(GUIListBox parent, ScalableFont font, Boolean includeTitle, Boolean includeClass, Boolean includeDescription) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Map\SubmarineInfo.cs:line 180
   at Barotrauma.TabMenu.CreateSubmarineInfo(GUIFrame infoFrame, Submarine sub) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\TabMenu.cs:line 1209
   at Barotrauma.TabMenu.SelectInfoFrameTab(InfoFrameTab selectedTab) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\TabMenu.cs:line 316
   at Barotrauma.TabMenu.<>c__DisplayClass30_0.<CreateInfoFrame>b__1(GUIButton btn, Object userData) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\TabMenu.cs:line 228
   at Barotrauma.GUIButton.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIButton.cs:line 256
   at Barotrauma.GUI.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1257
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 990
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b0a5d41e46c9a998288d09c1f8f95da192e2bf51

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
