### ISSUE TITLE
Network error? "Attempted to create a network event for an item (Sonar Beacon) that hasn't been fully initialized yet."

### ISSUE THREAD

**Issue by JoneKone** [Regalis11/Barotrauma#8369]
**Description**
```
[2/25/2022 1:12:16 PM]
  Starting a new round...                                                                                           
Generating an outpost for the end of the level... (Location: Thasus Linea, level type: LocationConnection)                                  WARNING: Entity events have been created during level generation. Events should not be created until the round is fully initialized.        [2/25/2022 1:12:23 PM]                                                                                                                        Mission: Explosive cargo                                                                                          
[2/25/2022 1:12:23 PM]                                                                                                                        A local arms dealer is offering 3,000 marks in exchange for delivering a shipment of high explosives to a customer in Thasus Linea.                                                                                                                           
[2/25/2022 1:12:23 PM]                                                                                                                        Game mode: Mission                                                                                                
[2/25/2022 1:12:23 PM]
  Submarine: Mazara (Missions) rev7                                                                                 
[2/25/2022 1:12:23 PM]
  Level seed: ouwj8BpV                                                                                              
[2/25/2022 1:12:23 PM]
  Mission: Explosive cargo                                                                                          
Attempted to create a network event for an item (Sonar Beacon) that hasn't been fully initialized yet.
   at System.Environment.get_StackTrace()
   at Barotrauma.Item.CreateServerEvent[T](T ic) in <DEV>/Barotrauma/BarotraumaServer/ServerSource/Items/Item.cs:line 388
   at Barotrauma.Items.Components.CustomInterface.OnItemLoaded() in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Items/Components/Signal/CustomInterface.cs:line 246
   at Barotrauma.Item..ctor(Rectangle newRect, ItemPrefab itemPrefab, Submarine submarine, Boolean callOnItemLoaded, UInt16 id) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Items/Item.cs:line 1015
   at Barotrauma.Item..ctor(ItemPrefab itemPrefab, Vector2 position, Submarine submarine, UInt16 id) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Items/Item.cs:line 818
   at Barotrauma.AutoItemPlacer.SpawnItem(ItemPrefab itemPrefab, List`1 containers, KeyValuePair`2 validContainer, Single difficultyModifier) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/GameSession/AutoItemPlacer.cs:line 255
   at Barotrauma.AutoItemPlacer.<>c__DisplayClass6_0.<Place>g__SpawnItems|3(ItemPrefab itemPrefab) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/GameSession/AutoItemPlacer.cs:line 187
   at Barotrauma.AutoItemPlacer.Place(IEnumerable`1 subs, ItemContainer regeneratedContainer, Single difficultyModifier) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/GameSession/AutoItemPlacer.cs:line 120
   at Barotrauma.AutoItemPlacer.PlaceIfNeeded() in <DEV>/Barotrauma/BarotraumaShared/SharedSource/GameSession/AutoItemPlacer.cs:line 28
   at Barotrauma.Networking.GameServer.StartGame(SubmarineInfo selectedSub, SubmarineInfo selectedShuttle, GameModePreset selectedMode, CampaignSettings settings)+MoveNext() in <DEV>/Barotrauma/BarotraumaServer/ServerSource/Networking/GameServer.cs:line 2203
   at Barotrauma.CoroutineManager.PerformCoroutineStep(CoroutineHandle handle) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/CoroutineManager.cs:line 196
   at Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/CoroutineManager.cs:line 229
   at Barotrauma.CoroutineManager.Update(Single unscaledDeltaTime, Single deltaTime) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/CoroutineManager.cs:line 270
   at Barotrauma.GameMain.Run() in <DEV>/Barotrauma/BarotraumaServer/ServerSource/GameMain.cs:line 401
   at Barotrauma.Program.Main(String[] args) in <DEV>/Barotrauma/BarotraumaServer/ServerSource/Program.cs:line 59   
Attempted to create a network event for an item (Sonar Beacon) that hasn't been fully initialized yet.
   at System.Environment.get_StackTrace()
   at Barotrauma.Item.CreateServerEvent[T](T ic) in <DEV>/Barotrauma/BarotraumaServer/ServerSource/Items/Item.cs:line 388
   at Barotrauma.Items.Components.CustomInterface.OnItemLoaded() in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Items/Components/Signal/CustomInterface.cs:line 246
   at Barotrauma.Item..ctor(Rectangle newRect, ItemPrefab itemPrefab, Submarine submarine, Boolean callOnItemLoaded, UInt16 id) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Items/Item.cs:line 1015
   at Barotrauma.Item..ctor(ItemPrefab itemPrefab, Vector2 position, Submarine submarine, UInt16 id) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Items/Item.cs:line 818
   at Barotrauma.AutoItemPlacer.SpawnItem(ItemPrefab itemPrefab, List`1 containers, KeyValuePair`2 validContainer, Single difficultyModifier) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/GameSession/AutoItemPlacer.cs:line 255
   at Barotrauma.AutoItemPlacer.<>c__DisplayClass6_0.<Place>g__SpawnItems|3(ItemPrefab itemPrefab) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/GameSession/AutoItemPlacer.cs:line 187
   at Barotrauma.AutoItemPlacer.Place(IEnumerable`1 subs, ItemContainer regeneratedContainer, Single difficultyModifier) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/GameSession/AutoItemPlacer.cs:line 120
   at Barotrauma.AutoItemPlacer.PlaceIfNeeded() in <DEV>/Barotrauma/BarotraumaShared/SharedSource/GameSession/AutoItemPlacer.cs:line 28
   at Barotrauma.Networking.GameServer.StartGame(SubmarineInfo selectedSub, SubmarineInfo selectedShuttle, GameModePreset selectedMode, CampaignSettings settings)+MoveNext() in <DEV>/Barotrauma/BarotraumaServer/ServerSource/Networking/GameServer.cs:line 2203
   at Barotrauma.CoroutineManager.PerformCoroutineStep(CoroutineHandle handle) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/CoroutineManager.cs:line 196
   at Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/CoroutineManager.cs:line 229
   at Barotrauma.CoroutineManager.Update(Single unscaledDeltaTime, Single deltaTime) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/CoroutineManager.cs:line 270
   at Barotrauma.GameMain.Run() in <DEV>/Barotrauma/BarotraumaServer/ServerSource/GameMain.cs:line 401
   at Barotrauma.Program.Main(String[] args) in <DEV>/Barotrauma/BarotraumaServer/ServerSource/Program.cs:line 59   
Attempted to create a network event for an item (Sonar Beacon) that hasn't been fully initialized yet.
   at System.Environment.get_StackTrace()
   at Barotrauma.Item.CreateServerEvent[T](T ic) in <DEV>/Barotrauma/BarotraumaServer/ServerSource/Items/Item.cs:line 388
   at Barotrauma.Items.Components.CustomInterface.OnItemLoaded() in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Items/Components/Signal/CustomInterface.cs:line 246
   at Barotrauma.Item..ctor(Rectangle newRect, ItemPrefab itemPrefab, Submarine submarine, Boolean callOnItemLoaded, UInt16 id) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Items/Item.cs:line 1015
   at Barotrauma.Item..ctor(ItemPrefab itemPrefab, Vector2 position, Submarine submarine, UInt16 id) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Items/Item.cs:line 818
   at Barotrauma.AutoItemPlacer.SpawnItem(ItemPrefab itemPrefab, List`1 containers, KeyValuePair`2 validContainer, Single difficultyModifier) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/GameSession/AutoItemPlacer.cs:line 255
   at Barotrauma.AutoItemPlacer.<>c__DisplayClass6_0.<Place>g__SpawnItems|3(ItemPrefab itemPrefab) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/GameSession/AutoItemPlacer.cs:line 187
   at Barotrauma.AutoItemPlacer.Place(IEnumerable`1 subs, ItemContainer regeneratedContainer, Single difficultyModifier) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/GameSession/AutoItemPlacer.cs:line 120
   at Barotrauma.AutoItemPlacer.PlaceIfNeeded() in <DEV>/Barotrauma/BarotraumaShared/SharedSource/GameSession/AutoItemPlacer.cs:line 28
   at Barotrauma.Networking.GameServer.StartGame(SubmarineInfo selectedSub, SubmarineInfo selectedShuttle, GameModePreset selectedMode, CampaignSettings settings)+MoveNext() in <DEV>/Barotrauma/BarotraumaServer/ServerSource/Networking/GameServer.cs:line 2203
   at Barotrauma.CoroutineManager.PerformCoroutineStep(CoroutineHandle handle) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/CoroutineManager.cs:line 196
   at Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/CoroutineManager.cs:line 229
   at Barotrauma.CoroutineManager.Update(Single unscaledDeltaTime, Single deltaTime) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/CoroutineManager.cs:line 270
   at Barotrauma.GameMain.Run() in <DEV>/Barotrauma/BarotraumaServer/ServerSource/GameMain.cs:line 401
   at Barotrauma.Program.Main(String[] args) in <DEV>/Barotrauma/BarotraumaServer/ServerSource/Program.cs:line 59   
Attempted to create a network event for an item (Sonar Beacon) that hasn't been fully initialized yet.
   at System.Environment.get_StackTrace()
   at Barotrauma.Item.CreateServerEvent[T](T ic) in <DEV>/Barotrauma/BarotraumaServer/ServerSource/Items/Item.cs:line 388
   at Barotrauma.Items.Components.CustomInterface.OnItemLoaded() in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Items/Components/Signal/CustomInterface.cs:line 246
   at Barotrauma.Item..ctor(Rectangle newRect, ItemPrefab itemPrefab, Submarine submarine, Boolean callOnItemLoaded, UInt16 id) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Items/Item.cs:line 1015
   at Barotrauma.Item..ctor(ItemPrefab itemPrefab, Vector2 position, Submarine submarine, UInt16 id) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Items/Item.cs:line 818
   at Barotrauma.AutoItemPlacer.SpawnItem(ItemPrefab itemPrefab, List`1 containers, KeyValuePair`2 validContainer, Single difficultyModifier) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/GameSession/AutoItemPlacer.cs:line 255
   at Barotrauma.AutoItemPlacer.<>c__DisplayClass6_0.<Place>g__SpawnItems|3(ItemPrefab itemPrefab) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/GameSession/AutoItemPlacer.cs:line 187
   at Barotrauma.AutoItemPlacer.Place(IEnumerable`1 subs, ItemContainer regeneratedContainer, Single difficultyModifier) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/GameSession/AutoItemPlacer.cs:line 120
   at Barotrauma.AutoItemPlacer.PlaceIfNeeded() in <DEV>/Barotrauma/BarotraumaShared/SharedSource/GameSession/AutoItemPlacer.cs:line 28
   at Barotrauma.Networking.GameServer.StartGame(SubmarineInfo selectedSub, SubmarineInfo selectedShuttle, GameModePreset selectedMode, CampaignSettings settings)+MoveNext() in <DEV>/Barotrauma/BarotraumaServer/ServerSource/Networking/GameServer.cs:line 2203
   at Barotrauma.CoroutineManager.PerformCoroutineStep(CoroutineHandle handle) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/CoroutineManager.cs:line 196
   at Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/CoroutineManager.cs:line 229
   at Barotrauma.CoroutineManager.Update(Single unscaledDeltaTime, Single deltaTime) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/CoroutineManager.cs:line 270
   at Barotrauma.GameMain.Run() in <DEV>/Barotrauma/BarotraumaServer/ServerSource/GameMain.cs:line 401
   at Barotrauma.Program.Main(String[] args) in <DEV>/Barotrauma/BarotraumaServer/ServerSource/Program.cs:line 59
[2/25/2022 1:12:24 PM]
  Round started.                                                                                                    
[2/25/2022 1:12:32 PM]                                                                                                                        JoneK set the value "Channel" of the item "Headset" to "0".                                                       
WARNING: Running slowly (56 updates/s)!                                                                                                     [2/25/2022 1:12:41 PM]                                                                                                                        JoneK placed Fuel Rod in Nuclear Reactor (ID: 625)  
```

**Steps To Reproduce**
Start dedicated server and start a mission 

**Version**
0.16.6.1

**Additional information**
was testing the new dedicated server with Mazara (Mission) ship, spat out these errors.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/098887256fbaa06fe45da4f208e75389a73635c3 and changed this from an error to a warning. This shouldn't cause any issues in practice: the server should just ignore this message (it can help us catch other situations where it does cause problems though).

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
