### ISSUE TITLE
[Modding refactor] Game crashed after selecting a mod on the publish tab right after publishing it

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#8560]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I was testing the recent modding changes by publishing a local copy of the Thalassophobia mod, publishing worked without any issues buy when I returned to the published mods list and selected the Thalassophobia mod which I just published the game crashed. 

**Steps To Reproduce**
What I did was

1. Install Thalassophibia from workshop
2. Go where the mod is installed at and just copy the folder over to localmods folder (Not sure how well this approach is supported in general)
3. Launch the game and publish the local copy of the Thalassophobia mod
4. Return back to the publish tab
5. Select Thalassophobia from the list
6. Game crashes

**Version**
Branch: dev
Commit: https://github.com/Regalis11/Barotrauma-development/commit/10d69ffe62ff75d84356ada276e600f41f79b111

**Additional information**
```
Exception: Content package "Thalassophobia Ultra Science Content Pack [MD5DA8EC08]" is not a local package! (System.Exception)
Target site: Void PopulatePublishTab(Barotrauma.Either`2[Steamworks.Ugc.Item,Barotrauma.ContentPackage], Barotrauma.GUIFrame)
Stack trace: 
   at Barotrauma.Steam.WorkshopMenu.PopulatePublishTab(Either`2 itemOrPackage, GUIFrame parentFrame) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Steam\PublishTab.cs:line 182
   at Barotrauma.Steam.WorkshopMenu.<>c__DisplayClass4_0.<CreateWorkshopItemDetailContainer>b__2(Either`2 itemOrPackage) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Steam\ItemList.cs:line 107
   at Barotrauma.Steam.WorkshopMenu.<>c__DisplayClass8_0.<CreateWorkshopItemOrPackageList>b__1(GUIComponent component, Object userData) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Steam\ItemList.cs:line 170
   at Barotrauma.GUIListBox.Select(Int32 childIndex, Boolean force, Boolean autoScroll, Boolean takeKeyBoardFocus) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIListBox.cs:line 1004
   at Barotrauma.GUIListBox.UpdateChildrenRect() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIListBox.cs:line 724
   at Barotrauma.GUIListBox.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIListBox.cs:line 845
   at Barotrauma.GUI.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1188
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 883
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 3
```

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/7463b78695b1f105cf237d6c850673b29359479d

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
