### ISSUE TITLE
Index was outside the bounds of the array at Barotrauma.Map.RemoveFogOfWar

### ISSUE THREAD

**Issue by R4to0** [Regalis11/Barotrauma#8583]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Game crashes upon loading a save file in multiplayer with level seed "Ana", global map seed "0BbWWUbw". It started after we docked into an abandoned outpost. Disabling all the mods and loading the same save gave the same issue. Save attached.

**Steps To Reproduce**
Load the following save with or without the mods, I have no idea what is causing this actually, except that it is hitting a nullpointer check in the game code judging from the referenced lines.

**Version**
Game version 0.16.7.0 (ReleaseWindows, branch release, revision aa4c852c2c)
Windows 10 Pro 21H2 64-bit

**Additional information**
```
Index was outside the bounds of the array.
Message length: 6856 (857 bytes)
Read position: 2605
Header: SYNC_IDS
Error occurred on the very first header!
Previous object was 0 bits long (0 bytes)
 
   at Barotrauma.Map.RemoveFogOfWar(Location location, Boolean removeFromAdjacentLocations) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Map\Map\Map.cs:line 209
   at Barotrauma.Map.RemoveFogOfWar(Location location, Boolean removeFromAdjacentLocations) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Map\Map\Map.cs:line 231
   at Barotrauma.Map.LocationChanged(Location prevLocation, Location newLocation) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Map\Map\Map.cs:line 205
   at Barotrauma.MultiPlayerCampaign.ClientRead(IReadMessage msg) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameSession\GameModes\MultiPlayerCampaign.cs:line 738
   at Barotrauma.Networking.GameClient.ReadIngameUpdate(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 2248
```
[issue_8583.zip](https://github.com/Regalis11/Barotrauma/files/8330616/issue_8583.zip)

Edit: Did a trial an error for about 3 hours or so and found that one of the connections are doing that crash. Editing the save (after decompression) and removing

```
      <connection passed="false" locked="false" difficulty="36.927406" biome="theaphoticplateau" locations="590,621">
        <Level seed="AnaAylesbury" biome="theaphoticplateau" type="LocationConnection" difficulty="36.927406" size="250000,60000" generationparams="plateaubasic" initialdepth="314826" hashuntinggrounds="true" originallyhadhuntinggrounds="true" />
      </connection>
```

then re-compressing and loading it works as expected! Really curious now..

Edit 2: After a few rounds with that workaround got another one right after reaching a checkpoint:

```
Exception: Index was outside the bounds of the array. (System.IndexOutOfRangeException)
Target site: Void RemoveFogOfWar(Barotrauma.Location, Boolean)
Stack trace: 
   at Barotrauma.Map.RemoveFogOfWar(Location location, Boolean removeFromAdjacentLocations) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Map\Map\Map.cs:line 209
   at Barotrauma.Map.RemoveFogOfWar(Location location, Boolean removeFromAdjacentLocations) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Map\Map\Map.cs:line 231
   at Barotrauma.Map.Update(Single deltaTime, GUICustomComponent mapContainer) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Map\Map\Map.cs:line 285
   at Barotrauma.CampaignUI.UpdateMap(Single deltaTime, GUICustomComponent mapContainer) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\CampaignUI.cs:line 335
   at Barotrauma.GUI.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1257
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 990
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6f04f05eb8e55310267959105d00d6bc370c6bf0 and https://github.com/Regalis11/Barotrauma-development/commit/fcf2060bfae244226681ad12b4d680a0113975cb

**Comment by R4to0** [comment]
Cannot reproduce on unstable. Fix confirmed.

Closing as fixed.
