### ISSUE TITLE
[Modding Refactor] Trying to use too many mods crashes the game

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#8596]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I just wanted to see what happens if I enable every mod I have, seems like the game can't handle the amount. Good thing that this does disable all the mods so you can load the game again and everything is fine. 

Here's the mods I had enabled

> Heroin- Drug&Alcohol Modification (Drugmod), AlienWrenchBase, T0 Precursor Suit, Neurotrauma, Lead Zeppelin, Survivor Survivator Fixes, Survivor Xanmonsters2 Fixes, Survivor Other Creature fixes, EK | Gunnery, Electric Guitar, Alto saxophone, EK | Armory, EK | Dockyard, EK | Utility, Vindicator MkII, The Aeche (III), Malaco, Deep Sea Alcohol, Maxed Skills, Transparent Diving Helmet [OUTDATED], Jobs+, Improved Husks, Shipwrecks Extended, Malborasek with Sound (Vanilla Overhaul), Mark Currency Mod, Let Me Choose !, A Way Out (WIP), Military Clothing, Ammo Vest [OUTDATED AF], Roomba, SCP-420-J, Trick or Trauma, Salty Dogs, Whaleys Guns, Soviet banner, Drunken Sailor, Piano man!, B-71(L) light-fortress, Hungry Sailor, Extra Clothes (Discontinued), Duffle Bag 2.0, Backpack & WaistBelt, Meaningful CPR, World War II - German Weapons, Equipment & Friends, Shapeshifter (mobile turrets), Kitchen Gun!, No Role Balance, MoreHeadgear, Better Human Damage, T.I.T.A.N. power suit - New update, New me., Normal Health Outposts NPCs, ITA No Role Balance, EuropaWaifu! 二次元妹子 (Longhair&diving suit update，Search Waifu addon！长发更新，搜索Waifu addon ）, Let Me Choose ! I.T.A, Saber Armaments (Uprising Midpoint Update), Saber Personal Protection (Abyss Hotfix), Defibrillator (Batteries), TC Guns, TC Meme Horns, TC Instruments, TC Meds, Barotronics - The Turret Collection, Coloured PUCS, EK Tazer Fix, Map Extended, Old Ness Melee Pack, Exoskeleton Equipment [Outdated], [AH] Cooking Grenades, Programmable Computer, Salvaged Equipment, Gravity Hammer, SOFA'S DECO, Survivor Extended Monsters Fixes, The Box 1.1, Extended Prisoners, Black Sea's Armory(BWeapons), Survivor Monster Pack Test fixes, More Medical, Zidrom MKVI, [CN]“战刃”级 突袭潜艇, Detonator Stick, Hazardous Reactors + advanced medecin/neurotrauma patch, Mola Mola, Survivor Xanmonsters1 Fixes, Stations from beyond, Good Talent Stuff Balance Mod, Transparent Diving Helmets, Crescent - Pre-Release, 松鼠快乐箱 [Insufficient Capacity], Multiplayer crew manager, oClockRadar / Sonar [Alt Appearance], Wreck Corpses, 莱德的二次元贴图替换, Undersea Horrors, B4 ABYSS NURSE, Consent Required (Neurotrauma Addon), Unlimited Railgun EK Pack, Faces Realistas Son, Survivor Vanilla Creature Overhauls, Afflictions +, TC Tools, Defibrillator

**Steps To Reproduce**
Install over 100 mods and try a host a server or then restart game and get a crash at the start. 

**Version**
0.17.3.0
Branch: dev
Commit: https://github.com/Regalis11/Barotrauma-development/commit/f55769b45351302063572bfa037f9be70dc0bd1a

**Additional information**
```
Barotrauma Client crash report (generated on 23.3.2022 23:45:45)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


To prevent further startup errors, installed mods will be disabled the next time you launch the game.


43514EE6704BD429F4485E449C267C22


Game version 0.17.3.0 (ReleaseWindows, branch dev, revision f55769b453)
Graphics mode: 2560x1440 (BorderlessWindowed)
VSync OFF
Language: English
Selected content packages: None
Level seed: no level loaded
Loaded submarine: None
Selected screen: None
SteamManager initialized


System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit
    GPU name: NVIDIA GeForce GTX 980 Ti
    Display mode: {Width:2560 Height:1440 Format:Color AspectRatio:1,7777778}
    GPU status: Normal


Exception: Loading was interrupted due to an error. (Barotrauma.GameMain+LoadingException)
Target site: Void Update(Microsoft.Xna.Framework.GameTime)
Stack trace: 
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 717
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59


InnerException: Range<Single>.End set to a value less than Start (0,009803922 < 0,01)
Target site: Void VerifyEndGreaterThanStart()
Stack trace: 
   at Barotrauma.Range`1.VerifyEndGreaterThanStart() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\Range.cs:line 43
   at Barotrauma.ContentPackageManager.Init()+MoveNext() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\ContentManagement\ContentPackageManager.cs:line 465
   at Barotrauma.GameMain.Load(Boolean isSeparateThread)+MoveNext() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 467
   at Barotrauma.CoroutineManager.PerformCoroutineStep(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 196
   at Barotrauma.CoroutineManager.ExecuteCoroutineThread(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 204
Last debug messages:
[23.3.2022 23:45:45] Coroutine "Load" has failed
[23.3.2022 23:45:45] Coroutine "Load" has thrown an exception {Range<Single>.End set to a value less than Start (0,009803922 < 0,01)}
   at Barotrauma.Range`1.VerifyEndGreaterThanStart() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\Range.cs:line 43
   at Barotrauma.ContentPackageManager.Init()+MoveNext() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\ContentManagement\ContentPackageManager.cs:line 465
   at Barotrauma.GameMain.Load(Boolean isSeparateThread)+MoveNext() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 467
   at Barotrauma.CoroutineManager.PerformCoroutineStep(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 196
   at Barotrauma.CoroutineManager.ExecuteCoroutineThread(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 204
[23.3.2022 23:45:41] Attempting to open ALC device "OpenAL Soft on Kaiuttimet (Realtek High Definition Audio)"
```

**Comment by Rokvach** [comment]
Update: Seems like its just finicky with that amount, uninstalled couple of the mods and reinstalled them and no issues so far.

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/78f9ba2c970ccc2d3c39cfe1bede67534325fd4e

**Comment by juanjp600** [comment]
Tested, seems to be working correctly. Closing.
