### ISSUE TITLE
[Mods] Installing a mod called "Map Extended" throws a "Attempted to divide by zero" crash when trying to launch singleplayer

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#8604]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Steps To Reproduce**
Install "Map extended" mod and try to start singleplayer

Workshop:
https://steamcommunity.com/sharedfiles/filedetails/?id=2530473859

**Version**
0.17.3.0
Branch: dev
Commit: https://github.com/Regalis11/Barotrauma-development/commit/2892f1c637e9955ff54c7bbdd5a6f650750405ed

**Additional information**
```
Exception: Attempted to divide by zero. (System.DivideByZeroException)
Target site: Void ChangeType(Barotrauma.LocationType)
Stack trace: 
   at Barotrauma.Location.ChangeType(LocationType newType) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Map\Location.cs:line 430
   at Barotrauma.Map.Generate() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Map\Map.cs:line 245
   at Barotrauma.Map..ctor(CampaignMode campaign, String seed, CampaignSettings settings) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Map\Map.cs:line 207
   at Barotrauma.SinglePlayerCampaign..ctor(String mapSeed, CampaignSettings settings) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameSession\GameModes\SinglePlayerCampaign.cs:line 65
   at Barotrauma.GameSession.InstantiateGameMode(GameModePreset gameModePreset, String seed, SubmarineInfo selectedSub, CampaignSettings settings, IEnumerable`1 missionPrefabs, MissionType missionType) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameSession.cs:line 217
   at Barotrauma.GameSession..ctor(SubmarineInfo submarineInfo, String savePath, GameModePreset gameModePreset, CampaignSettings settings, String seed, MissionType missionType) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameSession.cs:line 127
   at Barotrauma.MainMenuScreen.StartGame(SubmarineInfo selectedSub, String saveName, String mapSeed, CampaignSettings settings) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\MainMenuScreen.cs:line 1041
   at Barotrauma.SinglePlayerCampaignSetupUI.FinishSetup(GUIButton btn, Object userdata) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\CampaignSetupUI\SinglePlayerCampaignSetupUI.cs:line 497
   at Barotrauma.GUIButton.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIButton.cs:line 253
   at Barotrauma.GUI.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1188
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 883
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d00ef7f96fc51fc5842b022b8cfc73f9b3eb2b0f

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
