### ISSUE TITLE
[Modding refactor] Publishing a mod failed during installation

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#8642]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I was trying to publish a local copy of the thalassophobia mod, but the publishing process got stuck at "Downloading 0%" and then threw a error on the console when I waited further

Error:

> Failed to install item: download task ended with status RanToCompletion, exception was [NULL]    at Barotrauma.Steam.WorkshopMenu.PublishItem(GUITextBlock currentStepText, GUIMessageBox messageBox, String modVersion, Editor editor, ContentPackage localPackage)+MoveNext() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Steam\PublishTab.cs:line 0
>    at Barotrauma.Steam.WorkshopMenu.MessageBoxCoroutine(Func`3 subcoroutine)+MoveNext() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Steam\PublishTab.cs:line 389

**Steps To Reproduce**
Try to publish a large mod, I doubt it always happens however. 

**Version**
0.17.4.0
Branch: dev
Commit: https://github.com/Regalis11/Barotrauma-development/commit/2fd7af4793cd6590bf5d73dc594d2ea9f4fb395f

**Additional Information**
My game also crashed when I tried to select the content package from the publish list after the failed publish attempt
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/3ba1b263-89f9-4cad-b42b-b494afa1d717)
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/1ba6670a-b34e-434e-bfc6-c83073abea6b)
```
Exception: Content package "Thalassophobia Ultra Science Content Pack [MD5DA8EC08]" is not a local package! (System.Exception)
Target site: Void PopulatePublishTab(Barotrauma.Either`2[Steamworks.Ugc.Item,Barotrauma.ContentPackage], Barotrauma.GUIFrame)
Stack trace: 
   at Barotrauma.Steam.WorkshopMenu.PopulatePublishTab(Either`2 itemOrPackage, GUIFrame parentFrame) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Steam\PublishTab.cs:line 181
   at Barotrauma.Steam.WorkshopMenu.<>c__DisplayClass4_0.<CreateWorkshopItemDetailContainer>b__2(Either`2 itemOrPackage) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Steam\ItemList.cs:line 107
   at Barotrauma.Steam.WorkshopMenu.<>c__DisplayClass8_0.<CreateWorkshopItemOrPackageList>b__1(GUIComponent component, Object userData) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Steam\ItemList.cs:line 170
   at Barotrauma.GUIListBox.Select(Int32 childIndex, Boolean force, Boolean autoScroll, Boolean takeKeyBoardFocus) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIListBox.cs:line 1003
   at Barotrauma.GUIListBox.UpdateChildrenRect() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIListBox.cs:line 723
   at Barotrauma.GUIListBox.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIListBox.cs:line 844
   at Barotrauma.GUI.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1190
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 881
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59
```

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/823cfaa62aa3434168464141c4a1a6ae9c262940
