### ISSUE TITLE
Game crashes if you try and save a submarine with spaces at the end of the submarine's name

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#8663]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Steps To Reproduce**
1. Load up sub editor
2. Save a submarine with a space at the end of the name
3. Game should crach

**Version**
0.17.5.0
Branch: dev
Commit: https://github.com/Regalis11/Barotrauma-development/commit/38353cbb0c7f1d94c0983682ba3a1b1de7e829e7

**Additional information**
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/aef9314d-2725-4659-a969-351f3e9f0b15)
```
Exception: Could not find a part of the path 'C:\Users\RoniK\Documents\Barotrauma-development\Barotrauma\bin\ReleaseWindows\netcoreapp3.1\LocalMods\Barsuk 2 3   \filelist.xml'. (System.IO.DirectoryNotFoundException)
Target site: Microsoft.Win32.SafeHandles.SafeFileHandle ValidateFileHandle(Microsoft.Win32.SafeHandles.SafeFileHandle)
Stack trace: 
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
   at System.Xml.XmlWriterSettings.CreateWriter(String outputFileName)
   at System.Xml.XmlWriter.Create(String outputFileName, XmlWriterSettings settings)
   at System.Xml.Linq.XDocument.Save(String fileName, SaveOptions options)
   at Barotrauma.IO.SafeXML.SaveSafe(XDocument doc, String path, SaveOptions saveOptions, Boolean throwExceptions) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SafeIO.cs:line 85
   at Barotrauma.ModProject.Save(String path) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\ContentManagement\ContentPackage\ModProject.cs:line 165
   at Barotrauma.SubEditorScreen.<>c__DisplayClass126_0.<SaveSubToFile>g__addSubAndSaveModProject|1(ModProject modProject, String filePath, String packagePath) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\SubEditorScreen.cs:line 1836
   at Barotrauma.SubEditorScreen.SaveSubToFile(String name, String specialSavePath) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\SubEditorScreen.cs:line 1934
   at Barotrauma.SubEditorScreen.SaveSub(GUIButton button, Object obj) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\SubEditorScreen.cs:line 1789
   at Barotrauma.GUIButton.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIButton.cs:line 253
   at Barotrauma.GUI.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1190
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 885
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f6eda4857aa348634804c8f5d0c6ab9cb5c92cee

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
