### ISSUE TITLE
[Modding refactor] Game crashed when downloading mods from a server 

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#8693]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I tried to join a modded server but crashed in the middle of downloading mods from the server

**Version**
Unstable 0.17.6.0

**Additional information**
```
Barotrauma Client crash report (generated on 1.4.2022 17:39:03)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


EF6CBF8D2C6AFF33CEFB177318EB9992


Game version 0.17.6.0 (UnstableWindows, branch dev, revision 1d65f4dd5c)
Graphics mode: 2560x1440 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla
Level seed: no level loaded
Loaded submarine: None
Selected screen: Barotrauma.ServerListScreen
SteamManager initialized


System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit
    GPU name: NVIDIA GeForce GTX 980 Ti
    Display mode: {Width:2560 Height:1440 Format:Color AspectRatio:1,7777778}
    GPU status: Normal


Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: FileTransferIn <Select>g__getTransfer|6_21()
Stack trace: 
   at Barotrauma.ModDownloadScreen.<Select>g__getTransfer|6_21() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\ModDownloadScreen.cs:line 211
   at Barotrauma.ModDownloadScreen.<>c.<Select>b__6_25() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\ModDownloadScreen.cs:line 237
   at Barotrauma.ModDownloadScreen.<>c__DisplayClass6_6.<Select>b__28(Single f, GUICustomComponent component) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\ModDownloadScreen.cs:line 235
   at Barotrauma.GUI.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1190
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 885
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58


Last debug messages:
[1.4.2022 17:39:03] WARNING: Tried to restore enabled packages multiple times/without performing a backup
[1.4.2022 17:39:03] Error while reading a message from server. {Object reference not set to an instance of an object.}
   at Barotrauma.SaveUtil.DecompressFile(Boolean writeFile, String sDir, GZipStream zipStream, ProgressDelegate progress, String& fileName) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SaveUtil.cs:line 464
   at Barotrauma.SaveUtil.DecompressToDirectory(String sCompressedFile, String sDir, ProgressDelegate progress) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SaveUtil.cs:line 508
   at Barotrauma.ModDownloadScreen.CurrentDownloadFinished(FileTransferIn transfer) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\ModDownloadScreen.cs:line 314
   at Barotrauma.Networking.GameClient.OnFileReceived(FileTransferIn transfer) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 2638
   at Barotrauma.Networking.FileReceiver.ReadMessage(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\FileTransfer\FileReceiver.cs:line 388
   at Barotrauma.Networking.GameClient.ReadDataMessage(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 951
   at Barotrauma.Networking.SteamP2PClientPeer.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\Primitives\Peers\SteamP2PClientPeer.cs:line 237
   at Barotrauma.Networking.GameClient.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 612
[1.4.2022 17:39:03] Cannot open "TempMods_Download\Workshop_Turrets Extended_2782817100\.vscode/settings.json" in Create mode: modifying the contents of this folder/using this extension is not allowed.
[1.4.2022 17:38:46] LobbyMatchList:  LobbiesMatching: 0
[1.4.2022 17:38:46] LobbyMatchList:  LobbiesMatching: 0
[1.4.2022 17:38:46] SteamAPICallCompleted:   AsyncCall: 1041645428329391854
   Callback: 510
 ParamCount: 4
[1.4.2022 17:38:46] LobbyMatchList:  LobbiesMatching: 3
[1.4.2022 17:38:46] LobbyMatchList:  LobbiesMatching: 3
[1.4.2022 17:38:46] SteamAPICallCompleted:   AsyncCall: 2074758829400968301
   Callback: 510
 ParamCount: 4
[1.4.2022 17:38:46] LobbyMatchList:  LobbiesMatching: 50
[1.4.2022 17:38:46] LobbyMatchList:  LobbiesMatching: 50
[1.4.2022 17:38:46] SteamAPICallCompleted:   AsyncCall: 3725685263389101428
   Callback: 510
 ParamCount: 4
[1.4.2022 17:38:46] LobbyMatchList:  LobbiesMatching: 50
[1.4.2022 17:38:46] LobbyMatchList:  LobbiesMatching: 50
[1.4.2022 17:38:46] SteamAPICallCompleted:   AsyncCall: 8132376863765647754
   Callback: 510
 ParamCount: 4
[1.4.2022 17:38:45] SteamRelayNetworkStatus:                      Avail: Current
 PingMeasurementInProgress: 1
        AvailNetworkConfig: Current
             AvailAnyRelay: Current
                  DebugMsg: System.Byte[]
[1.4.2022 17:38:44] WARNING: Tried to restore enabled packages multiple times/without performing a backup
[1.4.2022 17:35:18] LobbyMatchList:  LobbiesMatching: 0
[1.4.2022 17:35:18] LobbyMatchList:  LobbiesMatching: 0
[1.4.2022 17:35:18] SteamAPICallCompleted:   AsyncCall: 6228735836117864861
   Callback: 510
 ParamCount: 4
[1.4.2022 17:35:17] LobbyMatchList:  LobbiesMatching: 5
[1.4.2022 17:35:17] LobbyMatchList:  LobbiesMatching: 5
[1.4.2022 17:35:17] SteamAPICallCompleted:   AsyncCall: 12373109062381813751
   Callback: 510
 ParamCount: 4
[1.4.2022 17:35:17] LobbyMatchList:  LobbiesMatching: 50
[1.4.2022 17:35:17] LobbyMatchList:  LobbiesMatching: 50
[1.4.2022 17:35:17] SteamAPICallCompleted:   AsyncCall: 4470696170171499621
   Callback: 510
 ParamCount: 4
[1.4.2022 17:35:17] LobbyMatchList:  LobbiesMatching: 50
[1.4.2022 17:35:17] LobbyMatchList:  LobbiesMatching: 50
[1.4.2022 17:35:17] SteamAPICallCompleted:   AsyncCall: 4683609749460990951
   Callback: 510
 ParamCount: 4
[1.4.2022 17:34:55] LobbyMatchList:  LobbiesMatching: 0
[1.4.2022 17:34:55] LobbyMatchList:  LobbiesMatching: 0
[1.4.2022 17:34:55] SteamAPICallCompleted:   AsyncCall: 1686359326659445344
   Callback: 510
 ParamCount: 4
[1.4.2022 17:34:55] LobbyMatchList:  LobbiesMatching: 4
[1.4.2022 17:34:55] LobbyMatchList:  LobbiesMatching: 4
[1.4.2022 17:34:55] SteamAPICallCompleted:   AsyncCall: 3212169426838771743
   Callback: 510
 ParamCount: 4
[1.4.2022 17:34:54] LobbyMatchList:  LobbiesMatching: 50
[1.4.2022 17:34:54] LobbyMatchList:  LobbiesMatching: 50
[1.4.2022 17:34:54] SteamAPICallCompleted:   AsyncCall: 1798117464839519697
   Callback: 510
 ParamCount: 4
[1.4.2022 17:34:54] LobbyMatchList:  LobbiesMatching: 50
[1.4.2022 17:34:54] LobbyMatchList:  LobbiesMatching: 50
[1.4.2022 17:34:54] SteamAPICallCompleted:   AsyncCall: 15425026865714845188
   Callback: 510
 ParamCount: 4
[1.4.2022 17:34:34] LobbyMatchList:  LobbiesMatching: 0
[1.4.2022 17:34:34] LobbyMatchList:  LobbiesMatching: 0
[1.4.2022 17:34:34] SteamAPICallCompleted:   AsyncCall: 6979954517500378371
   Callback: 510
 ParamCount: 4
[1.4.2022 17:34:34] LobbyMatchList:  LobbiesMatching: 4
[1.4.2022 17:34:34] LobbyMatchList:  LobbiesMatching: 4
[1.4.2022 17:34:34] SteamAPICallCompleted:   AsyncCall: 7121295590290606505
   Callback: 510
 ParamCount: 4
[1.4.2022 17:34:34] LobbyMatchList:  LobbiesMatching: 50
[1.4.2022 17:34:34] LobbyMatchList:  LobbiesMatching: 50
[1.4.2022 17:34:34] SteamAPICallCompleted:   AsyncCall: 11742282543241930280
   Callback: 510
 ParamCount: 4
[1.4.2022 17:34:34] LobbyMatchList:  LobbiesMatching: 50
[1.4.2022 17:34:34] LobbyMatchList:  LobbiesMatching: 50
[1.4.2022 17:34:34] SteamAPICallCompleted:   AsyncCall: 14120216959760808849
   Callback: 510
 ParamCount: 4
[1.4.2022 17:33:28] LobbyMatchList:  LobbiesMatching: 0
[1.4.2022 17:33:28] LobbyMatchList:  LobbiesMatching: 0
[1.4.2022 17:33:28] SteamAPICallCompleted:   AsyncCall: 11222169490848493584
   Callback: 510
 ParamCount: 4
[1.4.2022 17:33:28] PersonaStateChange:      SteamID: 76561198127079321
 ChangeFlags: 64
[1.4.2022 17:33:28] PersonaStateChange:      SteamID: 76561198331643379
 ChangeFlags: 64
[1.4.2022 17:33:28] PersonaStateChange:      SteamID: 76561198033617179
 ChangeFlags: 64
[1.4.2022 17:33:28] PersonaStateChange:      SteamID: 76561198049884400
 ChangeFlags: 64
[1.4.2022 17:33:28] PersonaStateChange:      SteamID: 76561198355965286
 ChangeFlags: 64
[1.4.2022 17:33:28] PersonaStateChange:      SteamID: 76561198046049031
 ChangeFlags: 64
[1.4.2022 17:33:28] PersonaStateChange:      SteamID: 76561198997058335
 ChangeFlags: 64
[1.4.2022 17:33:28] LobbyMatchList:  LobbiesMatching: 6
[1.4.2022 17:33:28] LobbyMatchList:  LobbiesMatching: 6
[1.4.2022 17:33:28] SteamAPICallCompleted:   AsyncCall: 16305919321604865477
   Callback: 510
 ParamCount: 4
[1.4.2022 17:33:28] PersonaStateChange:      SteamID: 76561198315352170
 ChangeFlags: 64
[1.4.2022 17:33:28] PersonaStateChange:      SteamID: 76561198326194254
 ChangeFlags: 64
[1.4.2022 17:33:28] PersonaStateChange:      SteamID: 76561198081135817
 ChangeFlags: 64
[1.4.2022 17:33:28] PersonaStateChange:      SteamID: 76561198079805369
 ChangeFlags: 64
[1.4.2022 17:33:28] PersonaStateChange:      SteamID: 76561198098198461
 ChangeFlags: 64
[1.4.2022 17:33:28] PersonaStateChange:      SteamID: 76561198101616885
 ChangeFlags: 64
[1.4.2022 17:33:28] PersonaStateChange:      SteamID: 76561198064387329
 ChangeFlags: 64
[1.4.2022 17:33:28] PersonaStateChange:      SteamID: 76561198088559588
 ChangeFlags: 64
[1.4.2022 17:33:28] PersonaStateChange:      SteamID: 76561197967131061
 ChangeFlags: 64
[1.4.2022 17:33:28] PersonaStateChange:      SteamID: 76561197993155871
 ChangeFlags: 64
[1.4.2022 17:33:28] PersonaStateChange:      SteamID: 76561198060005668
 ChangeFlags: 64
[1.4.2022 17:33:28] PersonaStateChange:      SteamID: 76561199146801386
 ChangeFlags: 64
[1.4.2022 17:33:28] PersonaStateChange:      SteamID: 76561198913431374
 ChangeFlags: 64
[1.4.2022 17:33:28] PersonaStateChange:      SteamID: 76561198817626608
 ChangeFlags: 64
[1.4.2022 17:33:28] PersonaStateChange:      SteamID: 76561198032887388
 ChangeFlags: 64
[1.4.2022 17:33:28] PersonaStateChange:      SteamID: 76561198059694705
 ChangeFlags: 64
[1.4.2022 17:33:28] PersonaStateChange:      SteamID: 76561198126256825
 ChangeFlags: 64
[1.4.2022 17:33:28] PersonaStateChange:      SteamID: 76561198127079321
 ChangeFlags: 1089
[1.4.2022 17:33:28] PersonaStateChange:      SteamID: 76561198331643379
 ChangeFlags: 1089
[1.4.2022 17:33:28] PersonaStateChange:      SteamID: 76561198033617179
 ChangeFlags: 1089
[1.4.2022 17:33:28] PersonaStateChange:      SteamID: 76561198049884400
 ChangeFlags: 1089
[1.4.2022 17:33:28] PersonaStateChange:      SteamID: 76561198355965286
 ChangeFlags: 1089
[1.4.2022 17:33:28] PersonaStateChange:      SteamID: 76561198046049031
 ChangeFlags: 1089
[1.4.2022 17:33:28] PersonaStateChange:      SteamID: 76561198997058335
 ChangeFlags: 1089
[1.4.2022 17:33:28] LobbyMatchList:  LobbiesMatching: 50
[1.4.2022 17:33:28] LobbyMatchList:  LobbiesMatching: 50
[1.4.2022 17:33:28] SteamAPICallCompleted:   AsyncCall: 7410081426139995703
   Callback: 510
 ParamCount: 4
[1.4.2022 17:33:28] PersonaStateChange:      SteamID: 76561198315352170
 ChangeFlags: 1089
[1.4.2022 17:33:28] PersonaStateChange:      SteamID: 76561198326194254
 ChangeFlags: 1089
[1.4.2022 17:33:28] PersonaStateChange:      SteamID: 76561198081135817
 ChangeFlags: 1089
[1.4.2022 17:33:28] PersonaStateChange:      SteamID: 76561198098198461
 ChangeFlags: 1089
[1.4.2022 17:33:28] PersonaStateChange:      SteamID: 76561198101616885
 ChangeFlags: 1089
[1.4.2022 17:33:28] PersonaStateChange:      SteamID: 76561198064387329
 ChangeFlags: 1089
[1.4.2022 17:33:28] PersonaStateChange:      SteamID: 76561198079805369
 ChangeFlags: 1089
[1.4.2022 17:33:28] PersonaStateChange:      SteamID: 76561198088559588
 ChangeFlags: 1089
[1.4.2022 17:33:28] PersonaStateChange:      SteamID: 76561197967131061
 ChangeFlags: 1089
[1.4.2022 17:33:28] PersonaStateChange:      SteamID: 76561197993155871
 ChangeFlags: 1089
[1.4.2022 17:33:28] PersonaStateChange:      SteamID: 76561198060005668
 ChangeFlags: 1089
[1.4.2022 17:33:28] PersonaStateChange:      SteamID: 76561199146801386
 ChangeFlags: 1089
[1.4.2022 17:33:28] PersonaStateChange:      SteamID: 76561198913431374
 ChangeFlags: 1089
[1.4.2022 17:33:28] PersonaStateChange:      SteamID: 76561198817626608
 ChangeFlags: 1089
[1.4.2022 17:33:28] PersonaStateChange:      SteamID: 76561198032887388
 ChangeFlags: 1089
[1.4.2022 17:33:28] PersonaStateChange:      SteamID: 76561198059694705
 ChangeFlags: 1089
[1.4.2022 17:33:28] PersonaStateChange:      SteamID: 76561198126256825
 ChangeFlags: 1089
[1.4.2022 17:33:28] LobbyMatchList:  LobbiesMatching: 50
[1.4.2022 17:33:28] LobbyMatchList:  LobbiesMatching: 50
[1.4.2022 17:33:28] SteamAPICallCompleted:   AsyncCall: 300240222397036534
   Callback: 510
 ParamCount: 4
[1.4.2022 17:33:27] AvatarImageLoaded:    SteamID: 76561198864735284
     Image: 96
      Wide: 184
      Tall: 184
[1.4.2022 17:33:27] AvatarImageLoaded:    SteamID: 76561198084639914
     Image: 95
      Wide: 184
      Tall: 184
[1.4.2022 17:33:27] AvatarImageLoaded:    SteamID: 76561198077192008
     Image: 94
      Wide: 184
      Tall: 184
[1.4.2022 17:33:27] AvatarImageLoaded:    SteamID: 76561198056754183
     Image: 93
      Wide: 184
      Tall: 184
[1.4.2022 17:33:27] AvatarImageLoaded:    SteamID: 76561198043655698
     Image: 92
      Wide: 184
      Tall: 184
[1.4.2022 17:33:27] AvatarImageLoaded:    SteamID: 76561198039285786
     Image: 91
      Wide: 184
      Tall: 184
[1.4.2022 17:33:27] AvatarImageLoaded:    SteamID: 76561198035847747
     Image: 90
      Wide: 184
      Tall: 184
[1.4.2022 17:33:27] AvatarImageLoaded:    SteamID: 76561198032486764
     Image: 89
      Wide: 184
      Tall: 184
[1.4.2022 17:33:27] AvatarImageLoaded:    SteamID: 76561198025355756
     Image: 88
      Wide: 184
      Tall: 184
[1.4.2022 17:33:27] AvatarImageLoaded:    SteamID: 76561198001061840
     Image: 87
      Wide: 184
      Tall: 184
[1.4.2022 17:33:27] AvatarImageLoaded:    SteamID: 76561197995836791
     Image: 86
      Wide: 184
      Tall: 184
[1.4.2022 17:32:23] Attempting to open ALC device "OpenAL Soft on Kaiuttimet (Realtek High Definition Audio)"
```

**Comment by juanjp600** [comment]
Crash should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/ba4f2dab6b064aa865bc1ae62a916c05387cddd8. The bug that caused the client to fail to connect should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/04c1720ea84f9c997cb5837bd4d4ca872983226d.

**Comment by Rokvach** [comment]
This might not be anyway related to this but it happened at the same place as this crash

Udrakan tried to join my server and hes game crashed when the mods required window came up, first he noticed this error on the console and it was followed with a crash.

```
Error while reading a message from server. {The given key 'defib' was not present in the dictionary.}
   at System.Collections.Concurrent.ConcurrentDictionary`2.ThrowKeyNotFoundException(Object key)
   at System.Collections.Concurrent.ConcurrentDictionary`2.get_Item(TKey key)
   at Barotrauma.PrefabCollection`1.get_Item(Identifier identifier) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Prefabs\PrefabCollection.cs:line 229
   at Barotrauma.MultiPlayerCampaign.ReadPurchasedItems(IReadMessage msg, Client sender) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameModes\MultiPlayerCampaign.cs:line 272
   at Barotrauma.MultiPlayerCampaign.ClientRead(IReadMessage msg) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameSession\GameModes\MultiPlayerCampaign.cs:line 642
   at Barotrauma.Networking.GameClient.ReadLobbyUpdate(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 2158
   at Barotrauma.Networking.GameClient.ReadDataMessage(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 755
   at Barotrauma.Networking.SteamP2PClientPeer.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\Primitives\Peers\SteamP2PClientPeer.cs:line 237
   at Barotrauma.Networking.GameClient.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 612
```

He was the only one who crashed like this while other players were able to join the server without much issues. 

He does seem to have a local mod which is still shown as selected on the crash report
`Selected content packages: Vanilla, New wreckloot`

I only had one workshop mod enabled on my server which adds a defibilator to the game, which seems to have caused the above error. Rest of my mods were just local custom subs.

Here's the crash

```
Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void <Select>b__6_11()
Stack trace: 
   at Barotrauma.ModDownloadScreen.<>c.<Select>b__6_11() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\ModDownloadScreen.cs:line 155
   at Barotrauma.ModDownloadScreen.<>c__DisplayClass6_2.<Select>b__18(GUIButton _, Object __) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\ModDownloadScreen.cs:line 144
   at Barotrauma.GUIButton.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIButton.cs:line 253
   at Barotrauma.GUI.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1190
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 887
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58
```

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/a26b10f71672d96c6714a1688b497fff8d40b421 and https://github.com/Regalis11/Barotrauma-development/commit/dece242cbf3131ce9d5acbf24216603800a9bee8.

**Comment by Rokvach** [comment]
There hasn't been any indication of this still happening in GA or from the community. Seems to be working correctly. Closing.
