### ISSUE TITLE
Sending initial lobby update fails if round already started.

### ISSUE THREAD

**Issue by MassCraxx** [Regalis11/Barotrauma#8731]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I am running a dedicated server on Linux, most config is vanilla, server is public but has a password. Whenever a round is already started, newly joining players will not receive the status of the server which results in an empty lobby UI. In this state, the client can not go spectate or do anything but wait. 
Finishing the current round or starting a new one will fix this and automatically spawn all players in this state.

**Steps To Reproduce**
1. Start a vanilla Linux dedicated Server, public=true, password protected
2. Start a round using an admin client (e.g random Mission)
3. Connect with another client while the round has already started

**Expected Behaviour**
Connected player can see that the round has already started and spectate.

**Actual Behaviour**
Connected player sees an empty lobby UI, attempt to spectate does not work.

**Version**
Barotrauma: 0.16.7.0
OS: Ubuntu 20.04.3 LTS

**Additional information**
The reason for this seems to be an exception thrown while sending the initial lobby update as can be seen in the attached log (L650+). [DebugConsoleLog_Server_04052022_14%3A02.txt](https://github.com/Regalis11/Barotrauma/files/8418958/DebugConsoleLog_Server_04052022_14.3A02.txt)

[04/05/2022 14:01:58] Sending initial lobby update
[04/05/2022 14:01:58] Failed to write a network message for the client "Teh Couch"! {Object reference not set to an instance of an object.}
   at Barotrauma.Networking.GameServer.ClientWriteLobby(Client c) in <DEV>/Barotrauma/BarotraumaServer/ServerSource/Networking/GameServer.cs:line 1833
   at Barotrauma.Networking.GameServer.ClientWrite(Client c)
   at Barotrauma.Networking.GameServer.Update(Single deltaTime) in <DEV>/Barotrauma/BarotraumaServer/ServerSource/Networking/GameServer.cs:line 605`

**Comment by Regalis11** [comment]
Dupliacte of https://github.com/Regalis11/Barotrauma/issues/8381
