### ISSUE TITLE
Crash when creating a humanoid character in the character editor (HumanCrouchParams not implemented)

### ISSUE THREAD

**Issue by AngelicAngels** [Regalis11/Barotrauma#8844]
Crash when trying to create character using clown.png in Clown jobgear folder. do png's need to be loaded from ''Characters'' folder?

﻿Barotrauma Client crash report (generated on 04/18/2022 15:25:50)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

47893D839ADBE3DD256A400A1C0EBF08

Game version 0.17.10.0 (ReleaseLinux, branch release, revision dd019c748c)
Graphics mode: 1920x1080 (Fullscreen)
VSync ON
Language: English
Selected content packages: Vanilla, Clowntest
Level seed: no level loaded
Loaded submarine: AnimEditor (B9856B3F97C56866A95FE75D0038FA16)
Selected screen: Barotrauma.CharacterEditor.CharacterEditorScreen
SteamManager initialized

System info:
    Operating system: Unix 5.4.0.105 64 bit
    GPU name: 
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Barotrauma.HumanCrouchParams (System.NotImplementedException)
Target site: Barotrauma.AnimationParams Create(System.String, Barotrauma.Identifier, Barotrauma.AnimationType, System.Type)
Stack trace: 
   at Barotrauma.AnimationParams.Create(String fullPath, Identifier speciesName, AnimationType animationType, Type type) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/Params/Animation/AnimationParams.cs:line 280
   at Barotrauma.CharacterEditor.CharacterEditorScreen.CreateCharacter(Identifier name, String mainFolder, Boolean isHumanoid, ContentPackage contentPackage, XElement ragdoll, XElement config, IEnumerable`1 animations) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Screens/CharacterEditor/CharacterEditorScreen.cs:line 1805
   at Barotrauma.CharacterEditor.Wizard.CreateCharacter(XElement ragdollElement, XElement characterElement, IEnumerable`1 animations) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Screens/CharacterEditor/Wizard.cs:line 127
   at Barotrauma.CharacterEditor.Wizard.RagdollView.<>c__DisplayClass3_0.<Create>b__18(GUIButton b, Object d) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Screens/CharacterEditor/Wizard.cs:line 848
   at Barotrauma.GUIButton.Update(Single deltaTime) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/GUI/GUIButton.cs:line 253
   at Barotrauma.GUI.Update(Single deltaTime) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/GUI/GUI.cs:line 1138
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/GameMain.cs:line 884
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/SDL/SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Program.cs:line 59

Last debug messages:
[04/18/2022 15:25:50] [AnimationParams] New animation file of type SwimFast created.
[04/18/2022 15:25:50] [AnimationParams] New animation file of type SwimSlow created.
[04/18/2022 15:25:50] [AnimationParams] New animation file of type Run created.
[04/18/2022 15:25:50] [AnimationParams] New animation file of type Walk created.
[04/18/2022 15:25:50] [RagdollParams] New default ragdoll params successfully created at LocalMods/Clowntest/Characters/Clowntest1/Ragdolls/Clowntest1DefaultRagdoll.xml
[04/18/2022 15:25:50] Content package saved at: LocalMods/Clowntest/filelist.xml
[04/18/2022 15:24:35] Watcher
[04/18/2022 15:24:35] Tigerthresher_hatchling
[04/18/2022 15:24:35] Tigerthresher
[04/18/2022 15:24:35] Terminalcell
[04/18/2022 15:24:35] Swarmfeeder
[04/18/2022 15:24:35] Swarmcrawler
[04/18/2022 15:24:35] Spineling_giant
[04/18/2022 15:24:35] Spineling
[04/18/2022 15:24:35] Psilotoad
[04/18/2022 15:24:35] Peanut
[04/18/2022 15:24:35] Orangeboy
[04/18/2022 15:24:35] Mudraptor_veteran
[04/18/2022 15:24:35] Mudraptor_unarmored
[04/18/2022 15:24:35] Mudraptor_passive
[04/18/2022 15:24:35] Mudraptor_hatchling
[04/18/2022 15:24:35] Mudraptor
[04/18/2022 15:24:35] Molochblack_m
[04/18/2022 15:24:35] Molochblack
[04/18/2022 15:24:35] Molochbaby
[04/18/2022 15:24:35] Moloch_m
[04/18/2022 15:24:35] Moloch
[04/18/2022 15:24:35] Mantis
[04/18/2022 15:24:35] Leucocyte
[04/18/2022 15:24:35] Legacywatcher
[04/18/2022 15:24:35] Legacytigerthresher
[04/18/2022 15:24:35] Legacymoloch
[04/18/2022 15:24:35] Legacyhusk
[04/18/2022 15:24:35] Legacyfractalguardian2
[04/18/2022 15:24:35] Legacyfractalguardian
[04/18/2022 15:24:35] Legacyendworm
[04/18/2022 15:24:35] Legacycrawler
[04/18/2022 15:24:35] Legacycharybdis
[04/18/2022 15:24:35] Latcher
[04/18/2022 15:24:35] Husk
[04/18/2022 15:24:35] Humanhusk
[04/18/2022 15:24:35] Human
[04/18/2022 15:24:35] Hammerheadspawn
[04/18/2022 15:24:35] Hammerheadmatriarch
[04/18/2022 15:24:35] Hammerheadgold_m
[04/18/2022 15:24:35] Hammerheadgold
[04/18/2022 15:24:35] Hammerhead_mNamed
[04/18/2022 15:24:35] Hammerhead_m
[04/18/2022 15:24:35] Hammerhead
[04/18/2022 15:24:35] Fractalguardian2
[04/18/2022 15:24:35] Fractalguardian
[04/18/2022 15:24:35] Endworm
[04/18/2022 15:24:35] Doomworm
[04/18/2022 15:24:35] Crawlerhusk
[04/18/2022 15:24:35] Crawlerbroodmother
[04/18/2022 15:24:35] Crawler_hatchling
[04/18/2022 15:24:35] Crawler
[04/18/2022 15:24:35] Coelanth
[04/18/2022 15:24:35] Charybdisold
[04/18/2022 15:24:35] Charybdis
[04/18/2022 15:24:35] Carrier
[04/18/2022 15:24:35] Bonethresher
[04/18/2022 15:24:35] Balloon
[04/18/2022 15:24:34] Trying to spawn human
[04/18/2022 15:24:18] LobbyMatchList:  LobbiesMatching: 0
[04/18/2022 15:24:18] LobbyMatchList:  LobbiesMatching: 0
[04/18/2022 15:24:18] SteamAPICallCompleted:   AsyncCall: 17273182092379782912
   Callback: 510
 ParamCount: 4
[04/18/2022 15:24:18] LobbyMatchList:  LobbiesMatching: 46
[04/18/2022 15:24:18] LobbyMatchList:  LobbiesMatching: 46
[04/18/2022 15:24:18] SteamAPICallCompleted:   AsyncCall: 12355762209411826262
   Callback: 510
 ParamCount: 4
[04/18/2022 15:24:18] PersonaStateChange:      SteamID: 76561198147246305
 ChangeFlags: 64
[04/18/2022 15:24:18] PersonaStateChange:      SteamID: 76561198147246305
 ChangeFlags: 1024
[04/18/2022 15:24:18] LobbyMatchList:  LobbiesMatching: 50
[04/18/2022 15:24:18] LobbyMatchList:  LobbiesMatching: 50
[04/18/2022 15:24:18] SteamAPICallCompleted:   AsyncCall: 2586303652389273422
   Callback: 510
 ParamCount: 4
[04/18/2022 15:23:18] WARNING: No core package selected. Switching to the "Vanilla" package.
[04/18/2022 15:23:17] Attempting to open ALC device "HyperX Virtual Surround Sound Analog Stereo"
[04/18/2022 15:23:13] Logged in as AngeL (SteamID STEAM_1:1:99912460)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d736dcd28133e6655cd3906e011c53fe347f93b6

**Comment by AngelicAngels** [comment]
@Regalis11 Thank's for clarification.

**Comment by Regalis11** [comment]
Thanks for taking your time to close this, but we'll keep the issue open until we've tested the fix internally and verified it's working fully. :)

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
