### ISSUE TITLE
[Unstable 0.17.10.0] Client kept crashing when trying to interact with a merchant in Colony

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#8848]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
One of the players on my server kept crashing whenever they interacted with merchants in a colony, none of the other players were, I also tried to reproduce the issue on the same colony where the player got the crash but I didn't crash.

**Steps To Reproduce**
No known steps

**Version**
Unstable 0.17.10.0

**Additional information**

Crash:
```
Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Barotrauma.PriceInfo GetPriceInfo(StoreInfo)
Stack trace:
   at Barotrauma.ItemPrefab.GetPriceInfo(StoreInfo store) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\ItemPrefab.cs:line 960
   at Barotrauma.Store.RefreshItemsToSell() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\Store.cs:line 1184
   at Barotrauma.Store.SelectStore(Identifier identifier) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\Store.cs:line 235
   at Barotrauma.CampaignUI.SelectTab(InteractionType tab, Identifier storeIdentifier) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\CampaignUI.cs:line 732
   at Barotrauma.CampaignMode.NPCInteractProjSpecific(Character npc, Character interactor) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameSession\GameModes\CampaignMode.cs:line 292
   at Barotrauma.CampaignMode.NPCInteract(Character npc, Character interactor) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameModes\CampaignMode.cs:line 781
   at Barotrauma.Character.DoInteractionUpdate(Single deltaTime, Vector2 mouseSimPos) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 2612
   at Barotrauma.Character.ControlLocalPlayer(Single deltaTime, Camera cam, Boolean moveCam) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Characters\Character.cs:line 366
   at Barotrauma.Character.UpdateControlled(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Characters\Character.cs:line 405
   at Barotrauma.Character.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 2842
   at Barotrauma.Character.UpdateAll(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 2716
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 187
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 860
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58
```

**Comment by ekqvist** [comment]
Possible null reference is now taken into account and the error is logged (Regalis11/Barotrauma-development@c6cbecf, Regalis11/Barotrauma-development@db78f0b).

Haven't yet reproduce the issue so the root cause isn't fixed yet. But based on the crash report, `Store.ActiveStore` was null for the client for some reason which lead to the crash.

**Comment by Rokvach** [comment]
It might be quite a rare occurrence as there were only two crashes in GA and both from the same player and there was quite a lot of activity in Unstable

**Comment by ekqvist** [comment]
Added some additional logging to try and help diagnose what's causing Store.ActiveStore to be null in Regalis11/Barotrauma-development@511c029. Note that this is on the bugfixes branch and not included in the current Unstable.

**Comment by Rokvach** [comment]
There hasn't been further sightings to the issue, if it does still happen there is going to be a new ticket about it so don't see the need to keep this open, closing.
