### ISSUE TITLE
Mystery error on startup related to content packages ("Name is null or empty")

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#8864]
v0.17.12.0

Something may have gone wrong migrating mods to the new system and caused a junk xml file somewhere, but clearing mod folder over and over again I am unable to find the cause of it.

Here's the error that appears in console every time the game starts:
`Failed to load "": Name is null or empty:    at Barotrauma.ContentPackage.AssertCondition(Boolean condition, String errorMsg) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\ContentManagement\ContentPackage\ContentPackage.cs:line 189
   at Barotrauma.ContentPackage..ctor(XDocument doc, String path) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\ContentManagement\ContentPackage\ContentPackage.cs:line 61
   at Barotrauma.RegularPackage..ctor(XDocument doc, String path) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\ContentManagement\ContentPackage\RegularPackage.cs:line 10
   at Barotrauma.ContentPackage.TryLoad(String path) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\ContentManagement\ContentPackage\ContentPackage.cs:line 137`

**Comment by Regalis11** [comment]
Thank you for the report!

The stack trace seems to imply that there's a mod present that has neither a name or a path - I can't think of how that could happen, so if you are able to find any more info about this, it'd help us a lot. Is that the full error message? The stack trace seems to be cut short, not indicating which part of the code the loading is happening from.

And to be sure, did you clear both of the mod folders, LocalMods and the Workshop folder in AppData? Have you tried resetting your config file?

**Comment by JoneKone** [comment]
i was just about to make a new report
![Screenshot from 2022-04-21 12-26-30](https://user-images.githubusercontent.com/1114115/164426420-a41e65f7-bc63-4912-bf33-bad54321cfae.png)


```
Failed to load "": Name is null or empty:    at Barotrauma.ContentPackage.AssertCondition(Boolean condition, String errorMsg) in /home/joonas/Barotrauma/Barotrauma/BarotraumaShared/SharedSource/ContentManagement/ContentPackage/ContentPackage.cs:line 191
   at Barotrauma.ContentPackage..ctor(XDocument doc, String path) in /home/joonas/Barotrauma/Barotrauma/BarotraumaShared/SharedSource/ContentManagement/ContentPackage/ContentPackage.cs:line 70
   at Barotrauma.RegularPackage..ctor(XDocument doc, String path) in /home/joonas/Barotrauma/Barotrauma/BarotraumaShared/SharedSource/ContentManagement/ContentPackage/RegularPackage.cs:line 10
   at Barotrauma.ContentPackage.TryLoad(String path) in /home/joonas/Barotrauma/Barotrauma/BarotraumaShared/SharedSource/ContentManagement/ContentPackage/ContentPackage.cs:line 137
```

The conversion procedure removed all my mods, all I have are submarine + 2 actual mods, that survived the transfer, (Into Abyss and Beacons Extended)

![Screenshot from 2022-04-21 12-41-10](https://user-images.githubusercontent.com/1114115/164427427-58527f7b-cdf4-453b-ac1c-52e5d540175c.png)


When I open the workshop, it spams the error again.

**Comment by RoskoFerguson** [comment]
I'm having the exact same error after a mod I'm subscribed to had been updated. Identical error even down to the line numbers. The mod was having an issue with a hash number mismatch so the creator tried deleting and re-uploading the mod as a fresh workshop page. After this point is when I started getting this error, apparently from the old mod having some remaining files that the game was angry about.

I did manage to fix it, by deleting the folder: C:\Users\[your username here]\AppData\Local\Daedalic Entertainment GmbH\Barotrauma\WorkshopMods

Much gratitude to Regalis for the suggestion above. That did the trick for me.

**Comment by Regalis11** [comment]
I suspect this is some side-effect of #8874 or migrating mods from a pre-modding-refactor version to the newer version. Let's see if this still resurfaces, and close later if not.

**Comment by esirprus** [comment]
Failed to load "": Name is null or empty:    at Barotrauma.ContentPackage.AssertCondition(Boolean condition, String errorMsg)
   at Barotrauma.ContentPackage..ctor(XDocument doc, String path)
   at Barotrauma.RegularPackage..ctor(XDocument doc, String path)
   at Barotrauma.ContentPackage.TryLoad(String path)
   I got the same error, I wonder how to solve this annoying problem

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/pull/3710/commits/20d2fd1ac22aafe7fbff11b785a1efe558e395b5 and https://github.com/Regalis11/Barotrauma-development/pull/3710/commits/ba2885311c22be4a4f66df19d1e8741222a7b130

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
