### ISSUE TITLE
Traitor Server Crash

### ISSUE THREAD

**Issue by optim02** [Regalis11/Barotrauma#8896]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Server Crash when the Traitor is selected

**Steps To Reproduce**
Start a multiplayer game with traitor mode on, a spectator or a dead player can be selected as traitor and so the server crash

**Version**
Game version 0.17.12.0 (ReleaseWindows, branch release, revision 2971300777)
Microsoft Windows NT 6.2.9200.0 64 bit

**Additional information**
"Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Barotrauma.LocalizedString get_StartMessageServerText()
Stack trace: 
   at Barotrauma.Traitor.Objective.get_StartMessageServerText() in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Traitors\Objective.cs:line 67
   at Barotrauma.Traitor.Greet(GameServer server, String codeWords, String codeResponse, MessageSender messageSender) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Traitors\Traitor.cs:line 33
   at Barotrauma.Traitor.TraitorMission.Start(GameServer server, TraitorManager traitorManager, CharacterTeamType team) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Traitors\TraitorMission.cs:line 229
   at Barotrauma.TraitorManager.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Traitors\TraitorManager.cs:line 176
   at Barotrauma.Networking.GameServer.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Networking\GameServer.cs:line 392
   at Barotrauma.GameMain.Run() in <DEV>\Barotrauma\BarotraumaServer\ServerSource\GameMain.cs:line 328
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Program.cs:line 74"

**Comment by optim02** [comment]
we tried with and without mod (it was a small one editing jobs & some items values) & with and without custom subs (a Typhon 1 a bit edited or a vanilla one) for 1hours with 10 players, and the only working case was when i was "alive" as host, if i was a spectator or dead (even after one or more traitor) [killed by the console] -> crash.

Idk we will try again, maybe it was link to a player with us.

**Comment by Regalis11** [comment]
No known steps to repro, closing

**Comment by DanJF** [comment]
I am having this same issue. Today, and as far back as April.
Which is unfortunate: public traitors is my favorite! :(

Crash log:
[servercrashreport (12).log](https://github.com/Regalis11/Barotrauma/files/10097442/servercrashreport.12.log)

The message is similar to OP. 
The mission ran for a while, then crashed when the game tried to assign a traitor.
No mods used, just custom subs also without mods.
