### ISSUE TITLE
After trying to save the cool, long submarine name I'd been thinking of for ages, the clever game truncated my submarine name, causing me to crash the next time I saved it.

### ISSUE THREAD

**Issue by esirprus** [Regalis11/Barotrauma#8911]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The sub editor will truncate excessively long submarine names on save and then cause you to crash the next time you edit.

**Steps To Reproduce**
open sub editor, and make a small sub, name it "abcdefghijklmnopqrstuvwxyz", will save successfully. but if you open it next time, you can see your sub name is “abcdefghijklmnopqrstuv...” on save window, then click save botton.
Game will give you a crash report, that is  cooooooooooool!

**Version**
0.17.12.0 on Windows 10

**Additional information**
Exception: Could not find a part of the path 'D:\steam\steamapps\common\Barotrauma\LocalMods\abcdefghijklmnopqrstuv...\filelist.xml'. (System.IO.DirectoryNotFoundException)
Target site: Microsoft.Win32.SafeHandles.SafeFileHandle ValidateFileHandle(Microsoft.Win32.SafeHandles.SafeFileHandle)
Stack trace: 
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
   at System.Xml.XmlWriterSettings.CreateWriter(String outputFileName)
   at System.Xml.XmlWriter.Create(String outputFileName, XmlWriterSettings settings)
   at System.Xml.Linq.XDocument.Save(String fileName, SaveOptions options)
   at Barotrauma.IO.SafeXML.SaveSafe(XDocument doc, String path, SaveOptions saveOptions, Boolean throwExceptions)
   at Barotrauma.ModProject.Save(String path)
   at Barotrauma.SubEditorScreen.<>c__DisplayClass127_0.<SaveSubToFile>g__addSubAndSaveModProject|1(ModProject modProject, String filePath, String packagePath)
   at Barotrauma.SubEditorScreen.SaveSubToFile(String name)
   at Barotrauma.SubEditorScreen.<>c__DisplayClass123_0.<SaveSub>b__0(GUIButton bt, Object userdata)
   at Barotrauma.GUIButton.Update(Single deltaTime)
   at Barotrauma.GUI.Update(Single deltaTime)
   at Barotrauma.GameMain.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4e2b9af1a0ed311873542e9b00662a1cf6dae360

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
