### ISSUE TITLE
Game crashed when ship hit the bottom (Turret.TryLaunch)

### ISSUE THREAD

**Issue by Hary309** [Regalis11/Barotrauma#8918]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The game crashed when the ship hit the bottom and the turrets were in use and probably all batteries disconnected. (I deduced this part from the crash log and the code)

**Steps To Reproduce**
Disconnect the batteries when firing the turrets.

**Version**
v0.17.12.0, Linux, Dedicated Server

**Additional information**
```
Game version 0.17.12.0 (ReleaseLinux, branch release, revision 2971300777)
Language: English
Selected content packages: Vanilla
Level seed: Thasus LineaPhineus Linea
Loaded submarine: Herja (851232493E2EC47A2D0875E950743778)
Selected screen: Barotrauma.GameScreen
Server (Round had started)


System info:
    Operating system: Unix 5.13.0.1021 64 bit


Exception: Sequence contains no elements (System.InvalidOperationException)
Target site: Void ThrowNoElementsException()
Stack trace: 
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.Min[TSource](IEnumerable`1 source, Func`2 selector)
   at Barotrauma.Items.Components.Turret.TryLaunch(Single deltaTime, Character character, Boolean ignorePower) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Items/Components/Turret.cs:line 665
   at Barotrauma.Items.Components.Turret.ReceiveSignal(Signal signal, Connection connection) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Items/Components/Turret.cs:line 1612
   at Barotrauma.Items.Components.Connection.SendSignal(Signal signal) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Items/Components/Signal/Connection.cs:line 327
   at Barotrauma.Item.SendSignal(Signal signal, Connection connection) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Items/Item.cs:line 2266
   at Barotrauma.Item.SendSignal(Signal signal, String connectionName) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Items/Item.cs:line 2206
   at Barotrauma.Items.Components.Controller.Use(Single deltaTime, Character activator) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Items/Components/Machines/Controller.cs:line 282
   at Barotrauma.Item.Use(Single deltaTime, Character character, Limb targetLimb) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Items/Item.cs:line 2478
   at Barotrauma.Character.Control(Single deltaTime, Camera cam) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/Character.cs:line 1972
   at Barotrauma.Character.Update(Single deltaTime, Camera cam) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/Character.cs:line 2924
   at Barotrauma.Character.UpdateAll(Single deltaTime, Camera cam) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/Character.cs:line 2714
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Screens/GameScreen.cs:line 200
   at Barotrauma.GameMain.Run() in <DEV>/Barotrauma/BarotraumaServer/ServerSource/GameMain.cs:line 328
   at Barotrauma.Program.Main(String[] args) in <DEV>/Barotrauma/BarotraumaServer/ServerSource/Program.cs:line 75
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/13f6ff21929d09f179bd7b7b5b1f3c7a91ca4d72

**Comment by Rokvach** [comment]
There hasn't been any crashes relating to this, I remember seeing this somewhat often during testing the previous patch, so there should of been at least one crash report regarding this in GA by now. Closing as working correctly.
