### ISSUE TITLE
Sequence contains no matching element when trying to reconnect to a server after a SteamP2P timeout 

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#8953]
**Description**
Watched a streamer and their crew get booted off from server with "Connection lost - SteamP2P connection timed out" message prompt and once they tried to rejoin the server they received the following error.

The error mentions mod download screen even though the server wasn't using any mods
```
Error while reading a message from server. {System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Barotrauma.ModDownloadScreen.Select() in C:\Users\User\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Screens\ModDownloadScreen.cs:line 83
   at Barotrauma.Networking.GameClient.OnConnectionInitializationComplete() in C:\Users\User\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 1262
   at Barotrauma.Networking.SteamP2PClientPeer.Update(Single deltaTime) in C:\Users\User\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Networking\Primitives\Peers\SteamP2PClientPeer.cs:line 222
   at Barotrauma.Networking.GameClient.Update(Single deltaTime) in C:\Users\User\Documents\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 612}. 
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Barotrauma.ModDownloadScreen.Select() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\ModDownloadScreen.cs:line 83
   at Barotrauma.Networking.GameClient.OnConnectionInitializationComplete() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 1262
   at Barotrauma.Networking.SteamP2PClientPeer.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\Primitives\Peers\SteamP2PClientPeer.cs:line 222
   at Barotrauma.Networking.GameClient.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 612
```

Host has to fully restart the server in order for clients to be able to join back. 
There's no indication that something has gone wrong on the hosts end, all the clients are just standing still. It doesn't even show that the clients have disconnected. 

**Steps To Reproduce**
Cause for the time out is not known, but seems to be the most common cause of sudden disconnections since the Urban Expanses update.

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/8ea8ffe1-e85d-4901-a77b-fb1d19391367)
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/b330fe70-2fe8-4904-9624-ca6841d154ab)

**Version**
0.17.12.0 and 0.17.13.0

**Additional information**

Stream timestamp:

Client:
https://youtu.be/LnMiFMRExnw?t=5484

Host: 
https://youtu.be/UVxWbJENyfs?t=5440

**Comment by Rokvach** [comment]
Seems like I've written a ticket about this previously too, I think this ticket holds more details and is more accurate, so I'll close the older one

https://github.com/Regalis11/Barotrauma/issues/8765

**Comment by Ek-Videogames** [comment]
It seems at least one of the ways this glitched state can occur when the server aborts sending the campaign file to the clients.
![image](https://user-images.githubusercontent.com/55356135/165001214-e279bcb4-7056-407a-9edf-c1b2d181131c.png)
![image](https://user-images.githubusercontent.com/55356135/165001228-89d16598-f941-41a4-865a-2e47514dfbc7.png)
![image](https://user-images.githubusercontent.com/55356135/165001238-1df1eee4-5a34-4a99-8130-dc66171e1d8e.png)

**Comment by Regalis11** [comment]
I unfortunately couldn't find a way to reproduce this

**Comment by Regalis11** [comment]
Attempt to fix this: https://github.com/Regalis11/Barotrauma-development/commit/b4cd8b4dcaef1c3fa63307e17b80c4de25fc7f45

**Comment by Rokvach** [comment]
So far no errors about this has shown up in GA

**Comment by Rokvach** [comment]
This error should of already been shown in GA if it happened still, so seems to be working correctly

**Comment by Rokvach** [comment]
Closing as there hasn't been any errors anymore in GA, seems to be working correctly.

**Comment by Rokvach** [comment]
There was one sighting in the 0.18.8.0 build, so it can still happen but is a lot rarer than previously. 

```
Error while reading a message from server. {System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Barotrauma.ModDownloadScreen.Select() in E:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Screens\ModDownloadScreen.cs:line 84
   at Barotrauma.Networking.GameClient.OnConnectionInitializationComplete() in E:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 1278
   at Barotrauma.Networking.SteamP2PClientPeer.Update(Single deltaTime) in E:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Networking\Primitives\Peers\SteamP2PClientPeer.cs:line 225
   at Barotrauma.Networking.GameClient.Update(Single deltaTime) in E:\Barotrauma-development\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 634}. 
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Barotrauma.ModDownloadScreen.Select() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\ModDownloadScreen.cs:line 84
   at Barotrauma.Networking.GameClient.OnConnectionInitializationComplete() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 1278
   at Barotrauma.Networking.SteamP2PClientPeer.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\Primitives\Peers\SteamP2PClientPeer.cs:line 225
   at Barotrauma.Networking.GameClient.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 634
```

**Comment by Regalis11** [comment]
Added a bunch more logging in https://github.com/Regalis11/Barotrauma-development/commit/6dcf608cf528e655819a659b3a3fe7782371e9d9 to help us diagnose this

> I suspect what's going on here is that the clients consider their initialization complete before they receive the list of content packages the server has enabled, causing them to attempt to enable an empty list of packages. My theory on how that could happen is that the clients can in some situation receive non-initialization data before the ContentPackageOrder message, which will make them consider themselves initialized (which they probably shouldn't do if the haven't received the package list?).

**Comment by itsdarf** [comment]
![image](https://user-images.githubusercontent.com/110042776/181038690-b44fea0e-3d13-4f3f-855f-61c8e75ed534.png)
![image](https://user-images.githubusercontent.com/110042776/181038895-394a0a5e-5f0d-4ff6-a845-48806c0e3874.png)

Recently got this today. Not exactly sure whats causing it. It'll disconnect me as a P2P issue but when trying to rejoin, it'll give me the text as described in the screenshots. The only fix so far that I've been able to do is verifying my game files but then the issue persists after about 2-10 minutes in a server. 

Not sure what is done to reproduce the issue as it just happens randomly (every time I'm able to rejoin in 2-10 minutes).

**Comment by mariovata** [comment]
It seems to be also present in the v0.18.15.0 and v0.19.0.0 (This is after my friend got disconnected before we started a mission)
![JUSk8SvjBF](https://user-images.githubusercontent.com/33606897/182045352-e232b7b8-5d37-4bac-8b94-19a09c2197c0.png)
 But there were some funky stuff with the v0.19.0.0, so I will probably need to test this again.

**Comment by Rokvach** [comment]
I haven't seen this issue come up in GA or discussed in a long time now, I think its finally safe to close this ticket. Closing.
