### ISSUE TITLE
Editor: No way to tell where interactable point on rotated periscopes is

### ISSUE THREAD

**Issue by JamesTheAwesomeDude** [Regalis11/Barotrauma#8991]
- [x] I [have searched the issue tracker](https://github.com/Regalis11/Barotrauma/issues?q=pathfind+is%3Aopen) to check if the issue has already been reported.

**Description**

The following Periscope is not reachable:

![sub waypoints screenshot](https://user-images.githubusercontent.com/2776014/165443775-d2b81603-fb29-4c8a-bc5b-f093d23d071b.png)

There are **two** possible outcomes, and I am not sure what causes each one:

1. The bot walks into Waypoint `42` and gets stuck: ![bot walking into wall screenshot](https://user-images.githubusercontent.com/2776014/165446110-9463a4b2-d541-4719-9c8b-7470c877c26b.png)
2. The game crashes: ![crashed game screenshot](https://user-images.githubusercontent.com/2776014/165443993-2f2f3915-ec93-4116-a50c-649147654327.png)

**Steps To Reproduce**

1. Open [this submarine](https://github.com/Regalis11/Barotrauma/files/8568962/broken_sub.zip) in the Sub Editor
2. Test it
3. Order a crewmate to man the weapons

**Version**

v0.17.12.0 (ReleaseLinux, branch release, revision 2971300777)

**Additional information**

```log
﻿Barotrauma Client crash report (generated on 04/26/2022 23:59:16)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


1248F5EFE3252F20D21AD0C7AC802ABE


Game version 0.17.12.0 (ReleaseLinux, branch release, revision 2971300777)
Graphics mode: 1680x1050 (BorderlessWindowed)
VSync OFF
Language: English
Selected content packages: Vanilla, Dog, Foray, Foray_attempt1, D
Level seed: no level loaded
Loaded submarine: D (4ABCA413B1484A2D3C6A688D6619C493)
Selected screen: Barotrauma.GameScreen
SteamManager initialized


System info:
    Operating system: Unix 5.13.0.40 64 bit
    GPU name: 
    Display mode: {Width:1680 Height:1050 Format:Color AspectRatio:1.6}
    GPU status: Normal


Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Boolean AIOperate(Single, Barotrauma.Character, Barotrauma.AIObjectiveOperateItem)
Stack trace: 
   at Barotrauma.Items.Components.Turret.AIOperate(Single deltaTime, Character character, AIObjectiveOperateItem objective) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Items/Components/Turret.cs:line 1154
   at Barotrauma.AIObjectiveOperateItem.Act(Single deltaTime) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/AI/Objectives/AIObjectiveOperateItem.cs:line 212
   at Barotrauma.HumanAIController.Update(Single deltaTime) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/AI/HumanAIController.cs:line 432
   at Barotrauma.Character.UpdateAll(Single deltaTime, Camera cam) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/Character.cs:line 2716
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Screens/GameScreen.cs:line 187
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/GameMain.cs:line 860
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/SDL/SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Program.cs:line 58


Last debug messages:
[04/26/2022 23:40:24] spawn Hammerhead cursor
[04/26/2022 23:39:49] spawn Crawler cursor
[04/26/2022 23:38:24] Watcher
[04/26/2022 23:38:24] Tigerthresher_hatchling
[04/26/2022 23:38:24] Tigerthresher
[04/26/2022 23:38:24] Terminalcell
[04/26/2022 23:38:24] Swarmfeeder
[04/26/2022 23:38:24] Swarmcrawler
[04/26/2022 23:38:24] Spineling_giant
[04/26/2022 23:38:24] Spineling
[04/26/2022 23:38:24] Psilotoad
[04/26/2022 23:38:24] Peanut
[04/26/2022 23:38:24] Orangeboy
[04/26/2022 23:38:24] Mudraptor_veteran
[04/26/2022 23:38:24] Mudraptor_unarmored
[04/26/2022 23:38:24] Mudraptor_passive
[04/26/2022 23:38:24] Mudraptor_hatchling
[04/26/2022 23:38:24] Mudraptor
[04/26/2022 23:38:24] Molochblack_m
[04/26/2022 23:38:24] Molochblack
[04/26/2022 23:38:24] Molochbaby
[04/26/2022 23:38:24] Moloch_m
[04/26/2022 23:38:24] Moloch
[04/26/2022 23:38:24] Mantis
[04/26/2022 23:38:24] Leucocyte
[04/26/2022 23:38:24] Legacywatcher
[04/26/2022 23:38:24] Legacytigerthresher
[04/26/2022 23:38:24] Legacymoloch
[04/26/2022 23:38:24] Legacyhusk
[04/26/2022 23:38:24] Legacyfractalguardian2
[04/26/2022 23:38:24] Legacyfractalguardian
[04/26/2022 23:38:24] Legacyendworm
[04/26/2022 23:38:24] Legacycrawler
[04/26/2022 23:38:24] Legacycharybdis
[04/26/2022 23:38:24] Latcher
[04/26/2022 23:38:24] Husk
[04/26/2022 23:38:24] Humanhusk
[04/26/2022 23:38:24] Human
[04/26/2022 23:38:24] Hammerheadspawn
[04/26/2022 23:38:24] Hammerheadmatriarch
[04/26/2022 23:38:24] Hammerheadgold_m
[04/26/2022 23:38:24] Hammerheadgold
[04/26/2022 23:38:24] Hammerhead_mNamed
[04/26/2022 23:38:24] Hammerhead_m
[04/26/2022 23:38:24] Hammerhead
[04/26/2022 23:38:24] Fractalguardian2
[04/26/2022 23:38:24] Fractalguardian
[04/26/2022 23:38:24] Endworm
[04/26/2022 23:38:24] Doomworm
[04/26/2022 23:38:24] Crawlerhusk
[04/26/2022 23:38:24] Crawlerbroodmother
[04/26/2022 23:38:24] Crawler_hatchling
[04/26/2022 23:38:24] Crawler
[04/26/2022 23:38:24] Coelanth
[04/26/2022 23:38:24] Charybdisold
[04/26/2022 23:38:24] Charybdis
[04/26/2022 23:38:24] Carrier
[04/26/2022 23:38:24] Bonethresher
[04/26/2022 23:38:24] Balloon
[04/26/2022 23:38:23] Trying to spawn human
[04/26/2022 23:37:13] Attempting to open ALC device "Built-in Audio Analog Stereo"
[04/26/2022 23:37:10] Logged in as starboy98 (SteamID STEAM_1:0:64963800)
```

**Comment by JamesTheAwesomeDude** [comment]
Incase the autosave format is different, here's a copy of the sub after it's been properly Saved:

[broken_sub_export.zip](https://github.com/Regalis11/Barotrauma/files/8569044/broken_sub_export.zip)

**Comment by JamesTheAwesomeDude** [comment]
I think the root of the problem is bots getting confused when something can be reached _from_ multiple hulls.

Further pathfinding AI glitches demoed by this sub:

* "Need to find a diving suit" to repair engine; "Can't reach Engine" if there is no diving suit
  * Bot subsequently accessed the engine via waypoint `43`, which does _not_ need a diving suit
* Bot occasionally **softlocks** when falling into the ballast due to failing at engine repair
  * Controlling the bot for a moment does not fix this
  * Grabbing the bot and moving it closer to the ladder does fix this

**Comment by JamesTheAwesomeDude** [comment]
Some further changes -- ["D" v2.0.2](https://github.com/Regalis11/Barotrauma/files/8577978/D-2.0.2.zip)

* Engineer ran to waypoint `42` then crashed the game when ordered to man the guns from Amidships (trial \#‌1, deets below)
* Engineer spawned in the ballast then got stuck walking leftwards into waypoint `59` indefinitely (trial \#‌2)
* Engineer got stuck walking rightwards into waypoint `62` indefinitely when ordered to man the guns from Ballast (trial \#‌2)

As you can see from the below screenshots, the center of the periscope isn't in the hull. I can run more suggested trials on this version of the sub, or make suggested changes and try again.

Outside of sub: ![outside of sub](https://user-images.githubusercontent.com/2776014/165636865-f93740ad-12f1-4b0e-8533-4227691e6d79.png)

Zoomed-in view with shell removed and walls+interactables highlighted: 
![zoomed-in view with shell removed and walls+interactables highlighted](https://user-images.githubusercontent.com/2776014/165637331-61c57618-e17d-4f70-a8d3-244a6bdf7933.png)

-----

Game crashed after ordering Electrician to man the guns: ![game crashed after ordering Electrician to man the guns](https://user-images.githubusercontent.com/2776014/165636290-bda135e4-4f6d-43ee-9244-40d49810931e.png)

```log
﻿Barotrauma Client crash report (generated on 04/27/2022 16:42:58)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


1248F5EFE3252F20D21AD0C7AC802ABE


Game version 0.17.12.0 (ReleaseLinux, branch release, revision 2971300777)
Graphics mode: 1680x1050 (BorderlessWindowed)
VSync OFF
Language: English
Selected content packages: Vanilla, Dog, Foray, Foray_attempt1, D
Level seed: no level loaded
Loaded submarine: D (D095B955D7745E0A59CD0D3BAA1914FB)
Selected screen: Barotrauma.GameScreen
SteamManager initialized


System info:
    Operating system: Unix 5.13.0.40 64 bit
    GPU name: 
    Display mode: {Width:1680 Height:1050 Format:Color AspectRatio:1.6}
    GPU status: Normal


Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Boolean AIOperate(Single, Barotrauma.Character, Barotrauma.AIObjectiveOperateItem)
Stack trace: 
   at Barotrauma.Items.Components.Turret.AIOperate(Single deltaTime, Character character, AIObjectiveOperateItem objective) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Items/Components/Turret.cs:line 1154
   at Barotrauma.AIObjectiveOperateItem.Act(Single deltaTime) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/AI/Objectives/AIObjectiveOperateItem.cs:line 212
   at Barotrauma.HumanAIController.Update(Single deltaTime) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/AI/HumanAIController.cs:line 432
   at Barotrauma.Character.UpdateAll(Single deltaTime, Camera cam) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/Character.cs:line 2716
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Screens/GameScreen.cs:line 187
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/GameMain.cs:line 860
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/SDL/SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Program.cs:line 58


Last debug messages:
[04/27/2022 16:37:41] Attempting to open ALC device "Built-in Audio Analog Stereo"
[04/27/2022 16:37:39] Logged in as starboy98 (SteamID STEAM_1:0:64963800)
```

**Comment by JamesTheAwesomeDude** [comment]
> The error was not sent to the developers because user statistics have been disabled…

I'm not sure why it says that -- 
![settings, Send User Statistics are enabled](https://user-images.githubusercontent.com/2776014/165640408-54b0882a-e85a-4a9b-a8a4-c6c25cb9df78.png)

**Comment by Regalis11** [comment]
Thank you for the extra info! I managed to repro that crash: it seems to happen when a character is trying to operate a turret _outside the submarine_, which often happens here because there's some space between the hulls and the exterior walls at the edges of the sub, from which the characters can "slip outside".

The position the characters try to get to when operating the turret is inside the walls. It's not at bottom-center of the periscope, but shifted to the right (the characters don't stand directly under the periscope). I would advise turning the periscope back to the normal vertical orientation; placing them horizontally like this isn't really supported behavior, and I can't think of how we could make the characters grab them in any way that makes sense when they're placed like this.

**Comment by Regalis11** [comment]
Fixed the crash in https://github.com/Regalis11/Barotrauma-development/commit/43d1aae0c9eec87c05c9590f079e2e620f49db46

**Comment by JamesTheAwesomeDude** [comment]
> I would advise turning the periscope back to the normal vertical orientation; placing them horizontally like this isn't really supported behavior

~~I was under the impression that "Rotation" is just cosmetic… (if it's not, then what does the white square represent in the sub editor?)~~

> The position the characters try to get to when operating the turret is … not at bottom-center of the periscope, but **shifted to the right (the characters don't stand directly under the periscope)**.

Aha, on further testing, that was the key to fixing it:

1. Reset periscope to prefab
2. Position the "wall-mounted" periscope _without_ rotating it
3. Set the X and Y mirroring such that the **viewport** is inside the sub
4. Test it
5. Rotate it to cosmetic taste
6. Test it again

Admittedly, the ragdolls don't _look_ very graceful while using horizontal periscopes under the current codebase, but at least the pathfinding is fixed by this method (placing hull-intersecting periscopes and testing them _before_ any rotation is done, while the sprite still aligns with the access node).

-----

> Engineer spawned in the ballast then got stuck walking leftwards into waypoint `59` indefinitely

This seems to have been resolved by moving the waypoint a bit further away from the wall:  
![waypoint 59 is somewhat near to the rear sub wall](https://user-images.githubusercontent.com/2776014/165709712-88c4b9a4-2fd7-483c-a956-d5826e258e20.png)


-----

> I can't think of how we could make the characters grab [a horizontal periscope] in any way that makes sense

Standing upright, with the head tilted forwards to face _down into it_, I would think, with the hands reaching out in front of the character to grip it at the normal location --  
![gettyimages-1309024730-2048x2048](https://user-images.githubusercontent.com/2776014/165706668-66800a62-fae6-4c3e-ad94-b45792cd2950.jpg)  
![istockphoto-466347713-612x612](https://user-images.githubusercontent.com/2776014/165704083-34865c2d-98da-4867-a275-c1c3271ba2fb.jpg)

**Comment by JamesTheAwesomeDude** [comment]
If you don't intend to add a visual indicator for the residual viewport location of rotated periscopes in the sub editor, or to add formal support for horizontal periscopes, then feel free to close this issue

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
