### ISSUE TITLE
Game Crash and Audio issues

### ISSUE THREAD

**Issue by Just-Martin-Really** [Regalis11/Barotrauma#9020]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Starting the game ouputs this in the console: Error after assigning ALC context: Invalid device. Disabling audio playback...
Opening Settings outputs this three times: Alc.GetStringList failed: AL error Invalid operation

i have no sound at any point and there are no output or input devices selectable in the settings.
I am using "voicemeeter" which kind of reroutes my audio and enhances it, i did try disabling it and putting my raw headphones as standard on windows, didnt help.

the game crashing seemed random to me, i can load into games perfectly but at some point i just crashed.
Then i found a thread from 2019 in which it was explained that some "splash" sound made the game crash; with that in mind, i can say that every crash is connected to me or another player entering water.

**Steps To Reproduce**
no idea sorry

**Version**
current version v0.17.15.0 // Windows 10

**Additional information**
i have installed OpenAL, re-installed the game, refreshed my audio drivers and prayed to god, none of that worked so far.

**Comment by Just-Martin-Really** [comment]
i forgot to paste the newest crashreport, so here it is.

Barotrauma Client crash report (generated on 28.04.2022 22:35:23)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


095A39E9025803C60F024FFA1049DA7B


Game version 0.17.15.0 (ReleaseWindows, branch release, revision 62bb4ecab3)
Graphics mode: 1920x1200 (BorderlessWindowed)
VSync OFF
Language: English
Selected content packages: Vanilla
Level seed: Alphesiboea LineaNew Siberia
Loaded submarine: Humpback (3806591D0C8B3170CEA39A87DC3E3979)
Selected screen: Barotrauma.GameScreen
SteamManager initialized
Client (Round had started)


System info:
    Operating system: Microsoft Windows NT 10.0.19043.0 64 bit
    GPU name: NVIDIA GeForce GTX 1060 6GB
    Display mode: {Width:1920 Height:1200 Format:Color AspectRatio:1,6}
    GPU status: Normal


Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void PlaySplashSound(Microsoft.Xna.Framework.Vector2, Single)
Stack trace: 
   at Barotrauma.SoundPlayer.PlaySplashSound(Vector2 worldPosition, Single strength) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Sounds\SoundPlayer.cs:line 856
   at Barotrauma.Ragdoll.Splash(Limb limb, Hull limbHull) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Characters\Animation\Ragdoll.cs:line 342
   at Barotrauma.Ragdoll.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Animation\Ragdoll.cs:line 1261
   at Barotrauma.Ragdoll.UpdateAll(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Animation\Ragdoll.cs:line 935
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 262
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 862
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58


Last debug messages:
[28.04.2022 22:35:20] Martin haha
[28.04.2022 22:35:20] Rinnington III
[28.04.2022 22:35:20] ITz Ghosty
[28.04.2022 22:35:18] Rinnington III
[28.04.2022 22:35:18] ITz Ghosty
[28.04.2022 22:35:15] Received STARTGAMEFINALIZE packet. Round init status: Started
[28.04.2022 22:35:08] Task count: 0
[28.04.2022 22:35:04] Generating an outpost for the start of the level... (Location: Alphesiboea Linea Station, level type: LocationConnection)
[28.04.2022 22:35:02] Generating an outpost for the end of the level... (Location: New Siberia Outpost, level type: LocationConnection)
[28.04.2022 22:33:57] Error after assigning ALC context: Invalid device. Disabling audio playback...
[28.04.2022 22:33:57] Attempting to open ALC device "OpenAL Soft on Lautsprecher (Realtek High Definition Audio)"
[28.04.2022 22:33:55] Logged in as Martin haha (SteamID STEAM_1:1:515335575)

**Comment by Regalis11** [comment]
The crash should now be fixed https://github.com/Regalis11/Barotrauma-development/commit/be658b0eeaef084ad9c4c0b6cf1fdd3cf83cdc55 (link to our private repo)

I'm not sure what's preventing the audio from working in the first place though. Have you tried plugging in the headphones and disabling VoiceMeeter before launching the game? The game not detecting the new audio device on the fly is the only explanation I can think of off the top of my head.

**Comment by taggedzi** [comment]
I am also getting this exact issue, I also use VoiceMeter.  When I go to settings and look at audio the dropdown menus for both input and output are completely empty. 

When I start the game it opens up the console and gives the error: 
```
Attempting to open ALC device "OpenAL Soft on Speakers (Realtek High Definition Audio)
Error after assigning ALC context: Invalid device. Disabling audio playback... 
```

Here is the Crash report: 

```
Barotrauma Client crash report (generated on 5/3/2022 8:08:11 PM)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

095A39E9025803C60F024FFA1049DA7B

Game version 0.17.15.0 (ReleaseWindows, branch release, revision 62bb4ecab3)
Graphics mode: 1600x1024 (Windowed)
VSync OFF
Language: English
Selected content packages: Vanilla
Level seed: PZbKqJbh
Loaded submarine: Typhon2 (7F5C7D2C0C1322535167D5BBED66E5A3)
Selected screen: Barotrauma.GameScreen
SteamManager initialized
Client (Round had started)


System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit
    GPU name: NVIDIA GeForce GTX 1060 3GB
    Display mode: {Width:2560 Height:1080 Format:Color AspectRatio:2.3703704}
    GPU status: Normal


Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void PlaySplashSound(Microsoft.Xna.Framework.Vector2, Single)
Stack trace: 
   at Barotrauma.SoundPlayer.PlaySplashSound(Vector2 worldPosition, Single strength) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Sounds\SoundPlayer.cs:line 856
   at Barotrauma.Ragdoll.Splash(Limb limb, Hull limbHull) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Characters\Animation\Ragdoll.cs:line 342
   at Barotrauma.Ragdoll.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Animation\Ragdoll.cs:line 1261
   at Barotrauma.Ragdoll.UpdateAll(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Animation\Ragdoll.cs:line 935
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 262
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 862
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58
```

**Comment by Just-Martin-Really** [comment]
Hey, i tried what you said and the drop-downs are still empty for me.

**Comment by Just-Martin-Really** [comment]
Update: After uninstalling Voicemeeter it now works fine, no crashes, no console open on startup, no errors.
