### ISSUE TITLE
Unable to Transition to Next Level

### ISSUE THREAD

**Issue by IConnC** [Regalis11/Barotrauma#9023]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The bug makes it impossible to traverse to the next station. Whenever the sub becomes docked with the station, the level transition never occurs and the same error message is repeated in the logs 100s of times a second. Un-docking and re-docking does not fix the issue nor does restarting the server on the same campaign. It seems to be isolated to the campaign that the issue occurred in and I have not experienced it again on a new campaign.

**Steps To Reproduce**
I have no method to reproduce the bug at this moment. It seems to be specific to my campaign.

**Version**
Linux Dedicated Server 0.17.15.0
Uses Lua but I believe it's unrelated.

**Additional information**

I can provide save files on request but it seems I can't upload them at this moment.

These errors are repeated 1000s of times a minute and blew my log file up to 100s of MB.
```
Transitioning to Undermoist (current location: Newellstead Habitation Outpost, selected location: Undermoist Outpost, leaving sub: The Immolator, at start: False, at end: True, transition type: ProgressToNextLocation)
Coroutine LevelTransition threw an exception: The given key 'Explored' was not present in the dictionary.
   at System.Collections.Concurrent.ConcurrentDictionary`2.ThrowKeyNotFoundException(Object key)
   at System.Collections.Concurrent.ConcurrentDictionary`2.get_Item(TKey key)
   at Barotrauma.PrefabCollection`1.get_Item(Identifier identifier) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Prefabs/PrefabCollection.cs:line 229
   at Barotrauma.Map.ChangeLocationType(Location location, LocationTypeChange change) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Map/Map/Map.cs:line 1016
   at Barotrauma.Map.ProgressLocationTypeChanges(Location location) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Map/Map/Map.cs:line 966
   at Barotrauma.Map.ProgressWorld() in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Map/Map/Map.cs:line 884
   at Barotrauma.Map.ProgressWorld(TransitionType transitionType, Single roundDuration) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Map/Map/Map.cs:line 853
   at Barotrauma.MultiPlayerCampaign.DoLevelTransition(TransitionType transitionType, LevelData newLevel, Submarine leavingSub, Boolean mirror, List`1 traitorResults)+MoveNext() in <DEV>/Barotrauma/BarotraumaServer/ServerSource/GameSession/GameModes/MultiPlayerCampaign.cs:line 324
   at Barotrauma.CoroutineManager.PerformCoroutineStep(CoroutineHandle handle) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/CoroutineManager.cs:line 197
   at Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/CoroutineManager.cs:line 255
```
```
Transitioning to Undermoist (current location: Undermoist Outpost, selected location: null, leaving sub: The Immolator, at start: False, at end: True, transition type: ProgressToNextLocation)
Could not move to the next location (no location selected).
   at System.Environment.get_StackTrace()
   at Barotrauma.Map.MoveToNextLocation() in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Map/Map/Map.cs:line 696
   at Barotrauma.MultiPlayerCampaign.DoLevelTransition(TransitionType transitionType, LevelData newLevel, Submarine leavingSub, Boolean mirror, List`1 traitorResults)+MoveNext() in <DEV>/Barotrauma/BarotraumaServer/ServerSource/GameSession/GameModes/MultiPlayerCampaign.cs:line 311
   at Barotrauma.CoroutineManager.PerformCoroutineStep(CoroutineHandle handle) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/CoroutineManager.cs:line 196
   at Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/CoroutineManager.cs:line 227
   at Barotrauma.CoroutineManager.Update(Single unscaledDeltaTime, Single deltaTime) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/CoroutineManager.cs:line 270
   at Barotrauma.GameMain.Run() in <DEV>/Barotrauma/BarotraumaServer/ServerSource/GameMain.cs:line 350
   at Barotrauma.Program.Main(String[] args) in <DEV>/Barotrauma/BarotraumaServer/ServerSource/Program.cs:line 84
```

**Comment by Regalis11** [comment]
Based on the error message, this seems to be caused by some mod (there's no location type called "Explored" in the vanilla game). Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/6b8ac9636e8328e2c0ca3f5a7209b6c0fec26fcd
