### ISSUE TITLE
Game crash when im trying to set the graphics mode from windowed to borderless window or fullscreen

### ISSUE THREAD

**Issue by rarerir** [Regalis11/Barotrauma#9095]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

At first game seems to still have fullscreen mode when i change it to borderless window, so i switched to borderless, and then to windowed, it worked the same way as borderless for me but there was a catch, after restarting the game the windowed mode worked not as borderless but a windowed, usually i just redo all thing again but after another restart and reset to borderless game just crashed. Tried to disable all mods, it didn't work out and game still crush. Just checked that it works with resolution too. After third retry to change the settings I set resolution to 1920x1080 and screen mode to borderless window no crush happened. After restart in windowed mode and resetting it to borderless no crush.

### Reproduction steps

1.Change to a windowed mode
2.Restart the game
3.Change to a fullscreen/borderless
4.Game crash

### Bug prevalence

Happens now and then

### Version

0.17.15.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 09.05.2022 19:48:47)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


1016D98423A72C6DF5EA9018A539D79E


Game version 0.17.15.0 (ReleaseWindows, branch master, revision 48a7cbda6)
Graphics mode: 2560x1440 (BorderlessWindowed)
VSync ON
Language: Russian
Selected content packages: Vanilla
Level seed: no level loaded
Loaded submarine: None
Selected screen: Barotrauma.MainMenuScreen
SteamManager initialized


System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit
    GPU name: NVIDIA GeForce GTX 1660
    Display mode: {Width:2560 Height:1440 Format:Color AspectRatio:1,7777778}
    GPU status: Normal


Exception: Loading GUI component "head" from XML is not implemented. (System.NotImplementedException)
Target site: Barotrauma.GUIComponent FromXML(Barotrauma.ContentXElement, Barotrauma.RectTransform)
Stack trace: 
   at Barotrauma.GUIComponent.FromXML(ContentXElement element, RectTransform parent)
   at Barotrauma.MainMenuScreen.<.ctor>b__25_0()
   at Barotrauma.GameMain.ApplyGraphicsSettings()
   at Barotrauma.GameSettings.SetCurrentConfig(Config& newConfig)
   at Barotrauma.SettingsMenu.<CreateBottomButtons>b__38_1(GUIButton btn, Object obj)
   at Barotrauma.GUIButton.Update(Single deltaTime)
   at Barotrauma.GUI.Update(Single deltaTime)
   at Barotrauma.GameMain.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in E:\Barotrauma-development\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args)
```

**Comment by Regalis11** [comment]
Thank you for the report!

Based on the error message, it seems that the game is for some reason failing to read the main menu content (the update notifications and changelogs at the corner of the main menu) it's received from our server. I'm not entirely sure how that can happen - perhaps there was some connection issue with the server...?

In any case, I added some error handling to fix this in https://github.com/Regalis11/Barotrauma-development/commit/674a85270d87047da1cefc946ff701da30e8b32e (link to our private repo). Now when this happens, it should log an error instead of crashing.
