### ISSUE TITLE
Game crashed when having tab menu crewlist open while someone respawns

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#9115]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I was hosting a server and when a player joined I had the crewlist tab menu open while they respawned and the game crashed. 

### Reproduction steps

Unkown

### Bug prevalence

Just once

### Version

Other

### -

Unstable 0.18.0.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 12.5.2022 18:50:38)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


41C28D58980A8835A65371C041D5E751


Game version 0.18.0.0 (UnstableWindows, branch dev, revision cb8ad58c45)
Graphics mode: 2560x1440 (BorderlessWindowed)
VSync OFF
Language: English
Selected content packages: Vanilla
Level seed: KogavostokSalthole
Loaded submarine: Typhon2 (BBF7AC8E4D988A9CA4D43151A60A1572)
Selected screen: Barotrauma.GameScreen
SteamManager initialized
Client (Round had started)


System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit
    GPU name: NVIDIA GeForce GTX 980 Ti
    Display mode: {Width:2560 Height:1440 Format:Color AspectRatio:1,7777778}
    GPU status: Normal


Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void .ctor(Barotrauma.Networking.Client, Barotrauma.GUIFrame, Barotrauma.GUITextBlock, Barotrauma.GUIImage)
Stack trace: 
   at Barotrauma.TabMenu.LinkedGUI..ctor(Client client, GUIFrame frame, GUITextBlock textBlock, GUIImage permissionIcon) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\TabMenu.cs:line 71
   at Barotrauma.TabMenu.CreateMultiPlayerCharacterElement(Character character, Client client, Int32 i) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\TabMenu.cs:line 0
   at Barotrauma.TabMenu.CreateMultiPlayerList(Boolean refresh) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\TabMenu.cs:line 640
   at Barotrauma.TabMenu.CreateCrewListFrame(GUIFrame crewFrame) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\TabMenu.cs:line 518
   at Barotrauma.TabMenu.SelectInfoFrameTab(InfoFrameTab selectedTab) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\TabMenu.cs:line 0
   at Barotrauma.TabMenu..ctor() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\TabMenu.cs:line 169
   at Barotrauma.GameSession.ToggleTabMenu() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameSession\GameSession.cs:line 39
   at Barotrauma.GameSession.UpdateProjSpecific(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameSession\GameSession.cs:line 217
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 145
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 866
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58


Last debug messages:
[12.5.2022 18:50:35] hUbert
[12.5.2022 18:50:35] Rehex
[12.5.2022 18:50:35] Jade Harley
[12.5.2022 18:50:35] Rokvach
[12.5.2022 18:50:25] Rehex
[12.5.2022 18:50:25] Jade Harley
[12.5.2022 18:50:25] Rokvach
[12.5.2022 18:50:20] Rehex
[12.5.2022 18:50:20] Jade Harley
[12.5.2022 18:50:20] Rokvach
[12.5.2022 18:49:57] Rehex
[12.5.2022 18:49:57] Jade Harley
[12.5.2022 18:49:57] Rokvach
[12.5.2022 18:49:55] Rehex
[12.5.2022 18:49:55] Jade Harley
[12.5.2022 18:49:55] Rokvach
[12.5.2022 18:49:55] Rehex
[12.5.2022 18:49:55] Jade Harley
[12.5.2022 18:49:55] Rokvach
[12.5.2022 18:47:59] Rehex
[12.5.2022 18:47:59] Jade Harley
[12.5.2022 18:47:59] Rokvach
[12.5.2022 18:45:42] DeadBrutal
[12.5.2022 18:45:42] Rehex
[12.5.2022 18:45:42] Jade Harley
[12.5.2022 18:45:42] Rokvach
[12.5.2022 18:45:31] DeadBrutal
[12.5.2022 18:45:31] Rehex
[12.5.2022 18:45:31] Jade Harley
[12.5.2022 18:45:31] Rokvach
[12.5.2022 18:45:31] DeadBrutal
[12.5.2022 18:45:31] Rehex
[12.5.2022 18:45:31] Jade Harley
[12.5.2022 18:45:31] Rokvach
[12.5.2022 18:45:30] Received STARTGAMEFINALIZE packet. Round init status: Started
[12.5.2022 18:45:29] Task count: 0
[12.5.2022 18:45:29] Received STARTGAMEFINALIZE packet. Round init status: WaitingForStartGameFinalize
[12.5.2022 18:45:27] Generating an outpost for the end of the level... (Location: Salthole Habitation Outpost, level type: LocationConnection)
[12.5.2022 18:45:26] Generating an outpost for the start of the level... (Location: Kogavostok Habitation Outpost, level type: LocationConnection)
[12.5.2022 18:45:08] Server running slowly (57 updates/s)!
[12.5.2022 18:45:06] Rehex
[12.5.2022 18:45:06] Jade Harley
[12.5.2022 18:45:06] Rokvach
[12.5.2022 18:45:06] Rehex
[12.5.2022 18:45:06] Jade Harley
[12.5.2022 18:45:06] Rokvach
[12.5.2022 18:45:05] Rehex
[12.5.2022 18:45:05] Jade Harley
[12.5.2022 18:45:05] Rokvach
[12.5.2022 18:44:48] Rehex
[12.5.2022 18:44:48] Jade Harley
[12.5.2022 18:44:48] Rokvach
[12.5.2022 18:44:44] Rehex
[12.5.2022 18:44:44] Jade Harley
[12.5.2022 18:44:44] Rokvach
[12.5.2022 18:44:43] Rehex
[12.5.2022 18:44:43] Jade Harley
[12.5.2022 18:44:43] Rokvach
[12.5.2022 18:44:43] Rehex
[12.5.2022 18:44:43] Jade Harley
[12.5.2022 18:44:43] Rokvach
[12.5.2022 18:44:43] Rehex
[12.5.2022 18:44:43] Jade Harley
[12.5.2022 18:44:43] Rokvach
[12.5.2022 18:44:32] Rehex
[12.5.2022 18:44:32] Jade Harley
[12.5.2022 18:44:32] Rokvach
[12.5.2022 18:41:05] Enabled HUD
[12.5.2022 18:41:05] togglehud
[12.5.2022 18:40:53] Disabled HUD
[12.5.2022 18:40:53] togglehud
[12.5.2022 18:40:28] Rehex
[12.5.2022 18:40:28] Jade Harley
[12.5.2022 18:40:28] Rokvach
[12.5.2022 18:40:10] Rehex
[12.5.2022 18:40:10] Jade Harley
[12.5.2022 18:40:10] Rokvach
[12.5.2022 18:39:57] Server command: heal Rokvach
[12.5.2022 18:39:57] heal Rokvach
[12.5.2022 18:39:44] Server command: teleport
[12.5.2022 18:39:44] teleport
[12.5.2022 18:39:36] Server command: heal Rokvach
[12.5.2022 18:39:36] heal Rokvach
[12.5.2022 18:39:27] Server command: heal Rokvach
[12.5.2022 18:39:27] heal Rokvach
[12.5.2022 18:39:06] Rehex
[12.5.2022 18:39:06] Jade Harley
[12.5.2022 18:39:06] Rokvach
[12.5.2022 18:38:51] Rehex
[12.5.2022 18:38:51] Jade Harley
[12.5.2022 18:38:51] Rokvach
[12.5.2022 18:38:43] Rehex
[12.5.2022 18:38:43] Jade Harley
[12.5.2022 18:38:43] Rokvach
[12.5.2022 18:38:28] Rehex
[12.5.2022 18:38:28] Jade Harley
[12.5.2022 18:38:28] Rokvach
[12.5.2022 18:36:19] Server command: spawnitem "Auto-Injector Headset" inventory
[12.5.2022 18:36:19] spawnitem "Auto-Injector Headset" inventory
[12.5.2022 18:30:35] Server command: heal Rokvach
[12.5.2022 18:30:35] heal Rokvach
[12.5.2022 18:30:11] Server command: spawnitem "Shotgun Shell" inventory 30
[12.5.2022 18:30:11] spawnitem "Shotgun Shell" inventory 30
[12.5.2022 18:29:59] Server command: spawnitem "Riot Shotgun"
[12.5.2022 18:29:59] spawnitem "Riot Shotgun"
[12.5.2022 18:28:27] Rehex
[12.5.2022 18:28:27] Jade Harley
[12.5.2022 18:28:27] Rokvach
[12.5.2022 18:28:17] Jade Harley
[12.5.2022 18:28:17] Rokvach
[12.5.2022 18:28:00] Jade Harley
[12.5.2022 18:28:00] Rokvach
[12.5.2022 18:27:59] Jade Harley
[12.5.2022 18:27:59] Rokvach
[12.5.2022 18:27:58] Jade Harley
[12.5.2022 18:27:58] Rokvach
[12.5.2022 18:27:58] Jade Harley
[12.5.2022 18:27:58] Rokvach
[12.5.2022 18:26:48] Server command: spawnitem "Riot Shotgun" cursor
[12.5.2022 18:26:48] spawnitem "Riot Shotgun" cursor
[12.5.2022 18:26:37] Server command: enablecheats
[12.5.2022 18:26:37] enablecheats
[12.5.2022 18:17:13] Jade Harley
[12.5.2022 18:17:13] Rokvach
[12.5.2022 18:17:13] Server command: respawnnow
[12.5.2022 18:17:13] respawnnow
[12.5.2022 18:17:07] Rokvach
[12.5.2022 18:16:54] Rokvach
[12.5.2022 18:16:52] Rokvach
[12.5.2022 18:16:48] Rokvach
[12.5.2022 18:16:47] Rokvach
[12.5.2022 18:16:47] Rokvach
[12.5.2022 18:16:47] Rokvach
[12.5.2022 18:15:33] Rokvach
[12.5.2022 18:15:31] Received STARTGAMEFINALIZE packet. Round init status: Started
[12.5.2022 18:15:31]  -1: WaitForPingDataAsync (owner), RanToCompletion
[12.5.2022 18:15:31]  -0: WaitForPingDataAsync (owner), RanToCompletion
[12.5.2022 18:15:31] Task count: 2
[12.5.2022 18:15:31] Received STARTGAMEFINALIZE packet. Round init status: WaitingForStartGameFinalize
[12.5.2022 18:15:29] Generating an outpost for the start of the level... (Location: Kogavostok Habitation Outpost, level type: Outpost)
[12.5.2022 18:15:09] ModeSelectionMode
[12.5.2022 18:15:09] SubSelectionMode
[12.5.2022 18:15:09] LosMode
[12.5.2022 18:15:09] PlayStyle
[12.5.2022 18:15:00] Server running slowly (58 updates/s)!
[12.5.2022 18:14:54] Rokvach
[12.5.2022 18:14:54] WARNING: Could not determine reputation change for faction "Children of the Honkmother" (faction was not present at the start of the round).
[12.5.2022 18:14:54] WARNING: Could not determine reputation change for faction "The Church of Husk" (faction was not present at the start of the round).
[12.5.2022 18:14:54] WARNING: Could not determine reputation change for faction "Jovian Separatists" (faction was not present at the start of the round).
[12.5.2022 18:14:54] WARNING: Could not determine reputation change for faction "Europa Coalition" (faction was not present at the start of the round).
[12.5.2022 18:14:35] Rokvach
[12.5.2022 18:14:10] Rokvach
[12.5.2022 18:14:09] Rokvach
[12.5.2022 18:14:08] Rokvach
[12.5.2022 18:14:08] Rokvach
[12.5.2022 18:13:49] Rokvach
[12.5.2022 18:13:48] Rokvach
[12.5.2022 18:13:48] Rokvach
[12.5.2022 18:13:48] Rokvach
[12.5.2022 18:11:23] Rokvach
[12.5.2022 18:09:33] Rokvach
[12.5.2022 18:09:32] Rokvach
[12.5.2022 18:09:32] Rokvach
[12.5.2022 18:09:32] Rokvach
[12.5.2022 18:04:50] Performance statistics enabled
[12.5.2022 18:04:50] showperf
[12.5.2022 18:04:32] Server running slowly (57 updates/s)!
[12.5.2022 18:04:30] Rokvach
[12.5.2022 18:04:27] Received STARTGAMEFINALIZE packet. Round init status: Started
[12.5.2022 18:04:27]  -2: WaitForPingDataAsync (owner), RanToCompletion
[12.5.2022 18:04:27]  -1: WaitForPingDataAsync (owner), RanToCompletion
[12.5.2022 18:04:27]  -0: WaitForPingDataAsync (owner), RanToCompletion
[12.5.2022 18:04:27] Task count: 3
[12.5.2022 18:04:27] Received STARTGAMEFINALIZE packet. Round init status: WaitingForStartGameFinalize
[12.5.2022 18:04:23] Generating an outpost for the start of the level... (Location: Kogavostok Habitation Outpost, level type: Outpost)
[12.5.2022 18:03:45] ModeSelectionMode
[12.5.2022 18:03:45] SubSelectionMode
[12.5.2022 18:03:45] LosMode
[12.5.2022 18:03:45] PlayStyle
[12.5.2022 18:03:45] MinRespawnRatio
[12.5.2022 18:03:45] RespawnInterval
[12.5.2022 18:03:12] MaximumTransferRequest
[12.5.2022 18:03:12] LootedMoneyDestination
[12.5.2022 18:03:12] ModeSelectionMode
[12.5.2022 18:03:12] SubSelectionMode
[12.5.2022 18:03:12] AllowLinkingWifiToChat
[12.5.2022 18:03:12] LosMode
[12.5.2022 18:03:12] PlayStyle
[12.5.2022 18:02:26] Lobby created!
[12.5.2022 18:01:33] Attempting to open ALC device "OpenAL Soft on Kaiuttimet (Realtek High Definition Audio)"
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4ca3eb75721d3e9a217d12431fd17eebf3732501

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
