### ISSUE TITLE
Trying to host a sandbox round throws level equality errors

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#9116]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Trying to host a sandbox round throws level equality errors

### Reproduction steps

1. Host a server
2. Select sandbox game mode
3. Start round
4. Receive errors

### Bug prevalence

Happens every time I play

### Version

Other

### -

Unstable 0.18.0.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Error while reading a message from server. {Level equality check failed. The level generated at your end doesn't match the level generated by the server (client value VoronoiGen: 212EE262, server value VoronoiGen: 3A7D8A80, level value count: 13, seed: s7zVXXry, sub: Typhon2 (D9C8F2A), mirrored: False).}
   at Barotrauma.Networking.GameClient.ReadStartGameFinalize(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 996
   at Barotrauma.Networking.GameClient.ReadDataMessage(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 885
   at Barotrauma.Networking.SteamP2POwnerPeer.HandleDataMessage(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\Primitives\Peers\SteamP2POwnerPeer.cs:line 0
   at Barotrauma.Networking.SteamP2POwnerPeer.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\Primitives\Peers\SteamP2POwnerPeer.cs:line 227
   at Barotrauma.Networking.GameClient.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 634

There was an error initializing the round. {Object reference not set to an instance of an object.}
   at Barotrauma.Networking.GameClient.StartGame(IReadMessage inc)+MoveNext() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 1709
```

**Comment by Rokvach** [comment]
Just to add, only campaign works

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/55f0017c913b8e6bf59bd1a6979b3acd5f9cb198

**Comment by Rokvach** [comment]
Tested, I wasn't able to reproduce the issue anymore. Working correctly. Closing.
