### ISSUE TITLE
[Level-progression] Game crashed when talking with a mission giver

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#9162]
**Description**
I walked to a mission giver and pressed E to talk to them and then E again to get the mission and my game crashed

**Steps To Reproduce**
1. Start singleplayer game
2. Walk to mission giver
3. Press E to interact with mission giver
4. Press E to accpet mission
5. Crash

**Version**
0.18.1.0
Branch: level-progression

**Additional information**

```
Barotrauma Client crash report (generated on 18.5.2022 16.24.58)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


919E1EB2568C583F384E744CEF889A66


Game version 0.18.1.0 (ReleaseWindows, branch feature/level-progression, revision 5f218bcc1e)
Graphics mode: 2560x1440 (BorderlessWindowed)
VSync OFF
Language: English
Selected content packages: Vanilla, Vengeance Mk. III, Vengeance Mk. III no wall, Vengeance Mk. III stripped, Vengeance Mk. III limited stor, Vengeance Mk. III no shuttle, Vengeance Mk. III no display, Vengeance Mk. III no text, Vengeance Mk. III no display 2, Vengeance Mk. III 2
Level seed: Salthole
Loaded submarine: Humpback (3734029703A670308A10AC580167CCD8)
Selected screen: Barotrauma.GameScreen
SteamManager initialized


System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit
    GPU name: NVIDIA GeForce GTX 980 Ti
    Display mode: {Width:2560 Height:1440 Format:Color AspectRatio:1,7777778}
    GPU status: Normal


Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Single <InstantiateMission>g__GetConnectionWeight|123_2(Barotrauma.Location, Barotrauma.LocationConnection)
Stack trace: 
   at Barotrauma.Location.<InstantiateMission>g__GetConnectionWeight|123_2(Location location, LocationConnection c) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Map\Location.cs:line 783
   at Barotrauma.Location.<>c__DisplayClass123_0.<InstantiateMission>b__1(LocationConnection c) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Map\Location.cs:line 771
   at System.Linq.Enumerable.WhereSelectListIterator`2.ToList()
   at Barotrauma.Location.InstantiateMission(MissionPrefab prefab, LocationConnection& connection) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Map\Location.cs:line 769
   at Barotrauma.Location.UnlockMissionByTag(Identifier tag) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Map\Location.cs:line 734
   at Barotrauma.MissionAction.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\EventActions\MissionAction.cs:line 79
   at Barotrauma.ScriptedEvent.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\ScriptedEvent.cs:line 215
   at Barotrauma.EventManager.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\EventManager.cs:line 695
   at Barotrauma.GameSession.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameSession.cs:line 721
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 145
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 866
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58


Last debug messages:
[18.5.2022 16.18.00] Game paused: False
[18.5.2022 16.18.00] pause
[18.5.2022 16.17.33] Game paused: True
[18.5.2022 16.17.33] pause
[18.5.2022 16.17.11] Line of sight effect disabled
[18.5.2022 16.17.11] los
[18.5.2022 16.17.11] Steam achievements have been disabled during this play session.
[18.5.2022 16.17.11] Enabled cheat commands.
[18.5.2022 16.17.11] enablecheats
[18.5.2022 16.17.08] Enabling cheats will disable Steam achievements during this play session.
[18.5.2022 16.17.08] You need to enable cheats using the command "enablecheats" before you can use the command "los".
[18.5.2022 16.17.08] los
[18.5.2022 16.16.56] Generating an outpost for the start of the level... (Location: Salthole Habitation Outpost, level type: Outpost)
[18.5.2022 16.16.04] Generating an outpost for the start of the level... (Location: Salthole Habitation Outpost, level type: Outpost)
[18.5.2022 16.15.19] Attempting to open ALC device "OpenAL Soft on Kaiuttimet (Realtek High Definition Audio)"
```

**Comment by JeroonBosch** [comment]
![image.png](https://images.zenhubusercontent.com/6231d99e9bac55c4e55dd66a/dec41dff-f0b1-4de9-a00f-d8b8fe416a77)

My repro steps: 
1. Start a new single player campaign, get the missions from the outpost manager - No problems here
2. Load the save game, get missions from the outpost manager - Crash

**Comment by Regalis11** [comment]
I was able to repro this with old saves. The issue was that we never saved the biomes of the locations, which hadn't been a problem until now because we didn't try to access the biomes either. Fixed that in https://github.com/Regalis11/Barotrauma-development/commit/29934ab12776fc20120a50831b1a9061f75b4189

Couldn't repro with new saves though.

**Comment by Rokvach** [comment]
I haven't encountered this issue since the fix

**Comment by Rokvach** [comment]
There hasn't been any records of this happening in GA nor have I encountered this crash since the fix, working correctly. Closing.
