### ISSUE TITLE
Closing submarine preview crashes the game + ladders aren't rendered in submarine preview

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#9178]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Previewing a submarine on the new game menu shows the submarine without any ladders and when you try and close the preview your game crashes

![image](https://user-images.githubusercontent.com/7299826/169491827-874b584d-e445-4571-8901-c4f8171c7242.png)

### Reproduction steps

1. Press New Game on main menu
2. Click a submarine thumbnail to preview it
3. Notice that there's no ladders rendered on the submarine
4. Close submarine preview
5. Game crashes

### Bug prevalence

Happens every time I play

### Version

0.18.2.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 20.5.2022 11.46.58)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


A193386672786C5FA31A3F2662F3AE4E


Game version 0.18.2.0 (UnstableWindows, branch dev, revision a5d17a19f1)
Graphics mode: 2560x1440 (BorderlessWindowed)
VSync OFF
Language: English
Selected content packages: Vanilla
Level seed: no level loaded
Loaded submarine: None
Selected screen: Barotrauma.MainMenuScreen
SteamManager initialized


System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit
    GPU name: NVIDIA GeForce GTX 980 Ti
    Display mode: {Width:2560 Height:1440 Format:Color AspectRatio:1,7777778}
    GPU status: Normal


Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void <.ctor>b__13_0(Microsoft.Xna.Framework.Graphics.SpriteBatch, Barotrauma.GUICustomComponent)
Stack trace: 
   at Barotrauma.SubmarinePreview.<.ctor>b__13_0(SpriteBatch spriteBatch, GUICustomComponent component) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Map\SubmarinePreview.cs:line 107
   at Barotrauma.GUICustomComponent.Draw(SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUICustomComponent.cs:line 43
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Barotrauma.GUI.Draw(Camera cam, SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 249
   at Barotrauma.MainMenuScreen.Draw(Double deltaTime, GraphicsDevice graphics, SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\MainMenuScreen.cs:line 978
   at Barotrauma.GameMain.Draw(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 951
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 669
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 508
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58


Last debug messages:
[20.5.2022 11.46.02] Attempting to open ALC device "OpenAL Soft on Kaiuttimet (Realtek High Definition Audio)"
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ea0678f6011cb4bbb4b7b2a27470973324e9a1f2 and https://github.com/Regalis11/Barotrauma-development/commit/df46558e947d5b3415108d676a8a1d963a8c549d

**Comment by Varangianoi** [comment]
Happens in 1.18.3.0 (Unstable) too.
