### ISSUE TITLE
Sprite editor crashes if you press reload texture twice

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#9192]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Tested sprite editor and noticed that pressing reload texture multiple times causes a crash

### Reproduction steps

1. Load up sprite editor using `spriteeditor` command
2. Press reload texture twice
3. Game should crash

If game doesn't crash then install some mods which adds sprites to the editor and do the same

### Bug prevalence

Happens every time I play

### Version

0.18.3.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 22.5.2022 11.33.30)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


0B6FA08477B6ED41939778DEE79DD2D9


Game version 0.18.3.0 (UnstableWindows, branch dev, revision 28cfd67df5)
Graphics mode: 2560x1440 (BorderlessWindowed)
VSync OFF
Language: English
Selected content packages: Vanilla, New Wrecks For Barotrauma (With sellable wrecks)
Level seed: no level loaded
Loaded submarine: None
Selected screen: Barotrauma.SpriteEditorScreen
SteamManager initialized


System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit
    GPU name: NVIDIA GeForce GTX 980 Ti
    Display mode: {Width:2560 Height:1440 Format:Color AspectRatio:1,7777778}
    GPU status: Normal


Exception: Sequence contains no elements (System.InvalidOperationException)
Target site: Void ThrowNoElementsException()
Stack trace: 
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Barotrauma.SpriteEditorScreen.<CreateUI>b__38_4(GUIButton button, Object userData) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\SpriteEditorScreen.cs:line 89
   at Barotrauma.GUIButton.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIButton.cs:line 253
   at Barotrauma.GUI.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1233
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 890
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59


Last debug messages:
[22.5.2022 11.33.09] spriteeditor
[22.5.2022 11.32.53] Failed to load package "Thalassophobia Ultra Science Content Pack [MD5DA8EC08]" {Failed to add the prefab "music_controlledchaos_ruins" (Barotrauma.BackgroundMusic) from "Thalassophobia Ultra Science Content Pack [MD5DA8EC08]" (LocalMods\Thalassophobia Ultra Science Content Pack [MD5DA8EC08]): a prefab with the same identifier from "Thalassophobia Ultra Science Content Pack [MD5DA8EC08]" (LocalMods\Thalassophobia Ultra Science Content Pack [MD5DA8EC08]) already exists; try overriding}
   at Barotrauma.PrefabSelector`1.AddInternal(T prefab, Boolean isOverride) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Prefabs\PrefabSelector.cs:line 93
   at Barotrauma.PrefabSelector`1.Add(T prefab, Boolean isOverride) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Prefabs\PrefabSelector.cs:line 31
   at Barotrauma.PrefabCollection`1.Add(T prefab, Boolean isOverride) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Prefabs\PrefabCollection.cs:line 368
   at Barotrauma.GenericPrefabFile`1.LoadFromXElement(ContentXElement parentElement, Boolean overriding) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\ContentManagement\ContentFile\GenericPrefabFile.cs:line 39
   at Barotrauma.GenericPrefabFile`1.LoadFromXElement(ContentXElement parentElement, Boolean overriding) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\ContentManagement\ContentFile\GenericPrefabFile.cs:line 49
   at Barotrauma.ContentPackage.<>c__DisplayClass34_0.<<LoadPackageEnumerable>g__loadFiles|1>d.MoveNext() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\ContentManagement\ContentPackage\ContentPackage.cs:line 237
[22.5.2022 11.32.53] WARNING: Error in "thal_chaoshorn"'s fabrication recipe: out condition is above 100% (10000).
[22.5.2022 11.32.53] WARNING: Error in "thal_bananapeel"'s fabrication recipe: out condition is above 100% (10000).
[22.5.2022 11.32.03] Attempting to open ALC device "OpenAL Soft on Kaiuttimet (Realtek High Definition Audio)"
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/819a8124c6cebe2f57bfee1886609cc89e49a853

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
