### ISSUE TITLE
Game crashed when shooting a crawler with a coilgun

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#9209]
**Description**
I was doing a crawler swarm mission in singleplayer and the game crashed when I killed a crawler which was attacking the hull of my submarine, not sure if it was latched or if crawlers even latch to the submarine anymore. 

**Steps To Reproduce**
Unkown as it just happened during normal gameplay

**Version**
0.18.3.0
Branch: dev
Commit: https://github.com/Regalis11/Barotrauma-development/commit/72e6b13345779691d105a2321f87d7bccac11b8d

**Additional information**
```
Barotrauma Client crash report (generated on 26.5.2022 0.47.23)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


D4530BC8F51E65CA4C002F22A523B980


Game version 0.18.3.0 (ReleaseWindows, branch dev, revision 72e6b13345)
Graphics mode: 2560x1440 (BorderlessWindowed)
VSync OFF
Language: English
Selected content packages: Vanilla
Level seed: AnnwnAstypalaea Linea
Loaded submarine: Dugong (1C39AF3F1F1B2B9875072234AA0F171B)
Selected screen: Barotrauma.GameScreen
SteamManager initialized


System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit
    GPU name: NVIDIA GeForce GTX 980 Ti
    Display mode: {Width:2560 Height:1440 Format:Color AspectRatio:1,7777778}
    GPU status: Normal


Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Barotrauma.Limb GetLimb(Barotrauma.LimbType, Boolean)
Stack trace: 
   at Barotrauma.Ragdoll.GetLimb(LimbType limbType, Boolean excludeSevered) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Animation\Ragdoll.cs:line 1870
   at Barotrauma.FishAnimController.UpdateDying(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Animation\FishAnimController.cs:line 903
   at Barotrauma.FishAnimController.UpdateAnim(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Animation\FishAnimController.cs:line 139
   at Barotrauma.Character.UpdateAnimAll(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 2669
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 259
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 866
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58


Last debug messages:
[26.5.2022 0.44.00] Could not find a spawn point for a SpawnAction (spawn location: BeaconStation (tag: beacon_bandit), skipping.
[26.5.2022 0.43.57] Generating an outpost for the end of the level... (Location: Astypalaea Linea Mining Facility, level type: LocationConnection)
[26.5.2022 0.43.56] Generating an outpost for the start of the level... (Location: Annwn Mining Claim, level type: LocationConnection)
[26.5.2022 0.43.56] Level identifier: coldcavernsadvanced
[26.5.2022 0.43.47] Transitioning to AnnwnAstypalaea Linea (current location: Annwn Mining Claim, selected location: Astypalaea Linea Mining Facility, leaving sub: Dugong, at start: True, at end: False, transition type: LeaveLocation)
[26.5.2022 0.42.24] Unlocked mission "Killing Hammerheads" in the location "Annwn Mining Claim".
[26.5.2022 0.42.22] Unlocked mission "Personnel Transport" in the location "Annwn Mining Claim".
[26.5.2022 0.42.19] Unlocked mission "Terminate a Swarm" in the location "Annwn Mining Claim".
[26.5.2022 0.40.32] Generating an outpost for the start of the level... (Location: Annwn Mining Claim, level type: Outpost)
[26.5.2022 0.40.32] Level identifier: outpostlevel
[26.5.2022 0.40.24] Transitioning to Annwn (current location: Gangpo Habitation Outpost, selected location: Annwn Mining Claim, leaving sub: Dugong, at start: False, at end: True, transition type: ProgressToNextLocation)
[26.5.2022 0.29.50] Generating an outpost for the start of the level... (Location: Annwn Mining Claim, level type: LocationConnection)
[26.5.2022 0.29.49] Generating an outpost for the end of the level... (Location: Gangpo Habitation Outpost, level type: LocationConnection)
[26.5.2022 0.29.49] Level identifier: coldcavernsbasic
[26.5.2022 0.29.40] Transitioning to AnnwnGangpo (current location: Gangpo Habitation Outpost, selected location: Annwn Mining Claim, leaving sub: Dugong, at start: True, at end: False, transition type: LeaveLocation)
[26.5.2022 0.29.19] Unlocked mission "Killing Hammerheads" in the location "Gangpo Habitation Outpost".
[26.5.2022 0.29.17] Unlocked mission "Personnel Transport" in the location "Gangpo Habitation Outpost".
[26.5.2022 0.29.15] Unlocked mission "Medical item transport" in the location "Gangpo Habitation Outpost".
[26.5.2022 0.29.08] FPS counter disabled
[26.5.2022 0.29.08] fpscounter
[26.5.2022 0.28.46] Generating an outpost for the start of the level... (Location: Gangpo Habitation Outpost, level type: Outpost)
[26.5.2022 0.28.46] Level identifier: outpostlevel
[26.5.2022 0.28.06] Attempting to open ALC device "OpenAL Soft on Kaiuttimet (Realtek High Definition Audio)"
```

**Comment by itchyOwl** [comment]
Based on the report, caused by Regalis11/Barotrauma-development@981650b. Fixed the code without trying to repro in Regalis11/Barotrauma-development@33bf375. The code was obviously flawed: we referenced to a wrong variable.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
