### ISSUE TITLE
Unable to load old save

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#9214]
**Description**
When I try to load TheColdsBelow test save it fails to load, when the save fails to load I'm unable to launch any other save too.

**Steps To Reproduce**
1. Load TheColdsBelow save and there should be a error

Try this version of the save if the error doesn't happen
[https://app.zenhub.com/files/93301055/c66c266f-e231-4dd2-9812-ac1beb00b4cb/download](https://app.zenhub.com/files/93301055/c66c266f-e231-4dd2-9812-ac1beb00b4cb/download)

**Version**
0.18.3.0
Branch: dev
Commit: https://github.com/Regalis11/Barotrauma-development/commit/72e6b13345779691d105a2321f87d7bccac11b8d

**Additional information**

This is the error that shows up when I try to load the save
```
Coroutine Barotrauma.SinglePlayerCampaign+<DoLoadInitialLevel>d__16 threw an exception: Index was outside the bounds of the array.
   at System.Collections.Immutable.ImmutableArray`1.get_Item(Int32 index)
   at Barotrauma.Items.Components.ItemContainer.CanBeContained(Item item, Int32 index) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\Components\ItemContainer.cs:line 350
   at Barotrauma.ItemInventory.CanBePutInSlot(Item item, Int32 i, Boolean ignoreCondition) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Items\ItemInventory.cs:line 50
   at Barotrauma.Character.SpawnInventoryItemsRecursive(Inventory inventory, ContentXElement element, List`1 extraDuffelBags) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 4357
   at Barotrauma.Character.SpawnInventoryItemsRecursive(Inventory inventory, ContentXElement element, List`1 extraDuffelBags) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 4427
   at Barotrauma.CrewManager.InitRound() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\CrewManager.cs:line 212
   at Barotrauma.CrewManager.InitSinglePlayerRound() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameSession\CrewManager.cs:line 3654
   at Barotrauma.SinglePlayerCampaign.Start() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameSession\GameModes\SinglePlayerCampaign.cs:line 246
   at Barotrauma.GameSession.InitializeLevel(Level level) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameSession.cs:line 578
   at Barotrauma.GameSession.StartRound(LevelData levelData, Boolean mirrorLevel, SubmarineInfo startOutpost, SubmarineInfo endOutpost) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameSession.cs:line 439
   at Barotrauma.SinglePlayerCampaign.DoLoadInitialLevel(LevelData level, Boolean mirror)+MoveNext() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameSession\GameModes\SinglePlayerCampaign.cs:line 266
   at Barotrauma.CoroutineManager.PerformCoroutineStep(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 197
   at Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 255
```

This error shows up after the above error has happened whenever I try to load any other save
```
Failed to load a new campaign level. No available level transitions (current location: Annwn Mining Claim, selected location: Astypalaea Linea Mining Facility, leaving sub: null, at start: null, at end: null)
   at System.Environment.get_StackTrace()
   at Barotrauma.CampaignMode.LoadNewLevel() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameModes\CampaignMode.cs:line 436
   at Barotrauma.GameSession..ctor(SubmarineInfo submarineInfo, List`1 ownedSubmarines, XDocument doc, String saveFile) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameSession.cs:line 153
   at Barotrauma.SaveUtil.LoadGame(String filePath) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SaveUtil.cs:line 141
   at Barotrauma.MainMenuScreen.LoadGame(String saveFile) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\MainMenuScreen.cs:line 1072
   at Barotrauma.SinglePlayerCampaignSetupUI.<UpdateLoadMenu>b__25_2(GUIButton btn, Object obj) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\CampaignSetupUI\SinglePlayerCampaignSetupUI.cs:line 705
   at Barotrauma.GUIButton.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIButton.cs:line 253
   at Barotrauma.GUI.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1233
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 890
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 651
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59
```

Here's how the error looks when it happens on a debug build
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/19f4483b-7cb1-4af5-a071-d696de1edfc6)

**Comment by Regalis11** [comment]
The issue of not being able to load saves after this (or some other kind of exception during loading) should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/c6332e86e4be81089d87a1e219384ee7dd8f0f1f

And the ItemContainer issue in https://github.com/Regalis11/Barotrauma-development/commit/cbb64472434e023b95339e5f13960f6d93ac3589

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
