### ISSUE TITLE
Increased stack sizes and large containers can lead to "Packet Size Exceeded" errors

### ISSUE THREAD

**Issue by RunoLight** [Regalis11/Barotrauma#9216]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I'm pretty much sure a lot of people like to have more space. Due to this problem there are many mods that can fix this problem, like Duffle Bags 2.0, EK Utility, x32 stack, which makes gameplay more comfortable for casual players (as all my party I play with at least).
When using x32 stack mod it becomes to impossible to fill big shelves or some big crates with full stacks of items. I done some research and wanted to make an advise how to lower networking packet size which can ease networking data size, prevent issues that happens due to inefficient networking.

If I correct, the game networking using same format as saves, so it is beautified XML filled with items and other data.
So there possible solutions to lower networking size.
1) Minify XML before sending over internet
2) Move default items data to client-side configs
`<Item name="" identifier="wrenchdementonite" ID="5574" rect="-66,570,32,10" NonInteractable="False" NonPlayerTeamInteractable="False" AllowSwapping="True" Rotation="0" Scale="0.5" SpriteColor="136,142,166,255" InventoryIconColor="136,142,166,255" ContainerColor="255,255,255,255" Condition="100" InvulnerableToDamage="False" Tags="mechanicalrepairtool,smallitem,tool,wrenchitem,simpletool" DisplaySideBySideWhenLinked="False" DisallowedUpgrades="" SpriteDepth="0.55" HiddenInGame="False" i="1">
            <MeleeWeapon Swing="True" SwingPos="2,0" SwingForce="3,-1" HoldPos="0,0" HoldAngle="60" SwingAmount="0,0" SwingSpeed="0" SwingWhenHolding="False" SwingWhenAiming="False" SwingWhenUsing="False" SpriteDepthWhenDropped="0.55" PickingTime="0" CanBePicked="True" AllowInGameEditing="True" Msg="ItemMsgPickUpSelect" />
            <Quality QualityLevel="3" PickingTime="0" CanBePicked="False" AllowInGameEditing="True" Msg="" />
</Item>`
This is an example of storing dementonite wrench in XML saves (maybe I'm totally wrong and it passes over internet not the same XML, I'm analyzing it using barotrauma saves). Things like Color, InvulnerableToDamage, well, most of them (despite of ID, 
 condition, quality) may be moved to some default configs table which can be used to populate needed data to items. If there really situtaions when let's say "InvulnerableToDamage" parameter can differ on one same item - we can just not include data while it's default one, and store it in serialized object when its changed.
Further, if we even not store static data (itemwide, for example all wrenches has `SwingWhenUsing="True"`, and never False) which can be moved in configs, then we can lower even RAM load due to referencing instantly to config instead of objects parameters. By this option we hold objects static configs for whole session, but the more items players have, the more impact this change will give. 

### Reproduction steps

1. Install mod [x32 stack](https://steamcommunity.com/sharedfiles/filedetails/?id=2683570256) and [EK Utility](https://steamcommunity.com/sharedfiles/filedetails/?id=2683570256).
2. Start multiplayer campaign.
3. Make "Industrial storage crate".
4. Try to fill it with stacked (where stack is 32 items) items.
5. Look the message "Packet Size Exceeded" after a half of crate and further.
6. Get a crash after ending the mission for everyone on server, and maybe(?) desync when placing and taking items when getting message above.

### Bug prevalence

Happens every time I play

### Version

0.17.15.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Including last crash report on ending mission (coming to station).

Barotrauma Client crash report (generated on 28.05.2022 13:52:03)
Barotrauma seems to have crashed. Sorry for the inconvenience! 
095A39E9025803C60F024FFA1049DA7B

Game version 0.17.15.0 (ReleaseWindows, branch release, revision 62bb4ecab3)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: Russian
Selected content packages: Vanilla, Barsuk 2, Shipwrecks Extended, Beacons Extended, EK | Utility, Molot Storage System  [100 slots]  Multi Player Ready, 32x Stack, EK Matriarch Mk-VII, Duffle Bag 2.0, Backpack & WaistBelt, Pockets For All, Thanatos, SuperRemora, Týr class battleship [cn][en][ru], DIP-OceanCatII-EKII, [VH] The Iroh, Zidrom MKVI, EK Kira Mk-V, EK | Gunnery, EK | Armory, Lua For Barotrauma, Medusa, [RH] Lethan, JSS. Juggernaut mk-II
Level seed: Dyfed
Loaded submarine: Winterhalter (C1542D17DF93C3FD68908D0551D9A768)
Selected screen: Barotrauma.RoundSummaryScreen
SteamManager initialized
Client (Round hadn't been started)


System info:
    Operating system: Microsoft Windows NT 10.0.21996.0 64 bit
    GPU name: NVIDIA GeForce GTX 1050
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1,7777778}
    GPU status: Normal


Exception: Collection was modified after the enumerator was instantiated. (System.InvalidOperationException)
Target site: Boolean MoveNext()
Stack trace: 
   at System.Collections.Generic.HashSet`1.Enumerator.MoveNext()
   at Barotrauma.CollectionConcat`1.GetEnumerator()+MoveNext() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\CollectionConcat.cs:line 56
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Barotrauma.UpgradeCategory.CanBeApplied(Item item, UpgradePrefab upgradePrefab) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Upgrades\UpgradePrefab.cs:line 146
   at Barotrauma.UpgradeManager.SanityCheckUpgrades(Submarine submarine) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\UpgradeManager.cs:line 560
   at Barotrauma.GameSession.InitializeLevel(Level level) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameSession.cs:line 615
   at Barotrauma.GameSession.StartRound(LevelData levelData, Boolean mirrorLevel, SubmarineInfo startOutpost, SubmarineInfo endOutpost) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameSession.cs:line 442
   at Barotrauma.CampaignMode.<>c__DisplayClass32_0.<<SelectSummaryScreen>b__0>d.MoveNext() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameSession\GameModes\CampaignMode.cs:line 268
--- End of stack trace from previous location where exception was thrown ---
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 862
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59


Last debug messages:
[28.05.2022 13:51:56] Generating an outpost for the start of the level... (Location: Аванпост Dyfed, level type: Outpost)
[28.05.2022 13:51:38] Server running slowly (50 updates/s)!
[28.05.2022 13:51:30] Шмурдяк
[28.05.2022 13:51:30] Marlina_Ra
[28.05.2022 13:51:30] Rengoku Kyōjurō
[28.05.2022 13:51:30] Шмурдяк
[28.05.2022 13:51:30] Marlina_Ra
[28.05.2022 13:51:30] Rengoku Kyōjurō
[28.05.2022 13:51:29] WARNING: Could not determine reputation change for faction "Дети красного носа" (faction was not present at the start of the round).
[28.05.2022 13:51:29] WARNING: Could not determine reputation change for faction "Церковь Паразита" (faction was not present at the start of the round).
[28.05.2022 13:51:29] WARNING: Could not determine reputation change for faction "Юпитерианские сепаратисты" (faction was not present at the start of the round).
[28.05.2022 13:51:29] WARNING: Could not determine reputation change for faction "Коалиция Европы" (faction was not present at the start of the round).
[28.05.2022 13:38:34] Maximum packet size exceeded (1240 > 1200)
[28.05.2022 13:37:54] Maximum packet size exceeded (1268 > 1200)
[28.05.2022 13:23:19] Maximum packet size exceeded (1224 > 1200)
[28.05.2022 13:16:02] Шмурдяк
[28.05.2022 13:16:02] Marlina_Ra
[28.05.2022 13:16:02] Rengoku Kyōjurō
[28.05.2022 13:15:57] Шмурдяк
[28.05.2022 13:15:57] Marlina_Ra
[28.05.2022 13:15:57] Rengoku Kyōjurō
[28.05.2022 13:15:48] Шмурдяк
[28.05.2022 13:15:48] Marlina_Ra
[28.05.2022 13:15:48] Rengoku Kyōjurō
[28.05.2022 13:15:44] Шмурдяк
[28.05.2022 13:15:44] Marlina_Ra
[28.05.2022 13:15:44] Rengoku Kyōjurō
[28.05.2022 13:15:43] Шмурдяк
[28.05.2022 13:15:43] Marlina_Ra
[28.05.2022 13:15:42] Rengoku Kyōjurō
[28.05.2022 13:15:41] Received STARTGAMEFINALIZE packet. Round init status: Started
[28.05.2022 13:15:40] Server running slowly (56 updates/s)!
[28.05.2022 13:15:36]  -3: WaitForPingDataAsync (owner), RanToCompletion
[28.05.2022 13:15:36]  -2: WaitForPingDataAsync (owner), RanToCompletion
[28.05.2022 13:15:36]  -1: WaitForPingDataAsync (owner), RanToCompletion
[28.05.2022 13:15:36]  -0: WaitForPingDataAsync (owner), RanToCompletion
[28.05.2022 13:15:36] Task count: 4
[28.05.2022 13:15:36] Received STARTGAMEFINALIZE packet. Round init status: WaitingForStartGameFinalize
[28.05.2022 13:15:35] Server running slowly (57 updates/s)!
[28.05.2022 13:15:29] Generating an outpost for the end of the level... (Location: Аванпост Dyfed, level type: LocationConnection)
[28.05.2022 13:15:27] Generating an outpost for the start of the level... (Location: Исследовательская станция Pelagon Linea, level type: LocationConnection)
[28.05.2022 13:14:24] Lobby created!
[28.05.2022 13:14:10] WARNING: Tried to restore enabled packages multiple times/without performing a backup
[28.05.2022 13:13:51] Coroutine "Barotrauma.Networking.GameClient+<StartGame>d__97" has failed
[28.05.2022 13:13:51] Failed to start campaign round (campaign ID does not match).
[28.05.2022 13:13:34] Server running slowly (56 updates/s)!
[28.05.2022 13:13:30] Marlina_Ra
[28.05.2022 13:13:30] Шмурдяк
[28.05.2022 13:13:30] Rengoku Kyōjurō
[28.05.2022 13:13:29] WARNING: Could not determine reputation change for faction "Дети красного носа" (faction was not present at the start of the round).
[28.05.2022 13:13:29] WARNING: Could not determine reputation change for faction "Церковь Паразита" (faction was not present at the start of the round).
[28.05.2022 13:13:29] WARNING: Could not determine reputation change for faction "Юпитерианские сепаратисты" (faction was not present at the start of the round).
[28.05.2022 13:13:29] WARNING: Could not determine reputation change for faction "Коалиция Европы" (faction was not present at the start of the round).
[28.05.2022 13:12:06] Marlina_Ra
[28.05.2022 13:12:06] Шмурдяк
[28.05.2022 13:12:06] Rengoku Kyōjurō
[28.05.2022 13:11:58] Marlina_Ra
[28.05.2022 13:11:58] Шмурдяк
[28.05.2022 13:11:58] Rengoku Kyōjurō
[28.05.2022 13:11:58] Marlina_Ra
[28.05.2022 13:11:58] Шмурдяк
[28.05.2022 13:11:58] Rengoku Kyōjurō
[28.05.2022 13:11:57] Marlina_Ra
[28.05.2022 13:11:57] Шмурдяк
[28.05.2022 13:11:57] Rengoku Kyōjurō
[28.05.2022 13:11:55] Marlina_Ra
[28.05.2022 13:11:55] Шмурдяк
[28.05.2022 13:11:55] Rengoku Kyōjurō
[28.05.2022 13:11:52] Marlina_Ra
[28.05.2022 13:11:52] Шмурдяк
[28.05.2022 13:11:52] Rengoku Kyōjurō
[28.05.2022 13:11:49] Marlina_Ra
[28.05.2022 13:11:49] Шмурдяк
[28.05.2022 13:11:48] Rengoku Kyōjurō
[28.05.2022 13:11:47] Received STARTGAMEFINALIZE packet. Round init status: Started
[28.05.2022 13:11:46] Received STARTGAMEFINALIZE packet. Round init status: Started
[28.05.2022 13:11:40] Task count: 0
[28.05.2022 13:11:40] Received STARTGAMEFINALIZE packet. Round init status: WaitingForStartGameFinalize
[28.05.2022 13:11:28] Generating an outpost for the start of the level... (Location: Аванпост Dyfed, level type: LocationConnection)
[28.05.2022 13:11:27] Generating an outpost for the end of the level... (Location: Исследовательская станция Pelagon Linea, level type: LocationConnection)
[28.05.2022 13:11:22] Server running slowly (51 updates/s)!
[28.05.2022 13:10:47] WARNING: Could not determine reputation change for faction "Дети красного носа" (faction was not present at the start of the round).
[28.05.2022 13:10:47] WARNING: Could not determine reputation change for faction "Церковь Паразита" (faction was not present at the start of the round).
[28.05.2022 13:10:47] WARNING: Could not determine reputation change for faction "Юпитерианские сепаратисты" (faction was not present at the start of the round).
[28.05.2022 13:10:47] WARNING: Could not determine reputation change for faction "Коалиция Европы" (faction was not present at the start of the round).
[28.05.2022 13:10:43] Шмурдяк
[28.05.2022 13:10:43] Rengoku Kyōjurō
[28.05.2022 13:10:27] Шмурдяк
[28.05.2022 13:10:27] Rengoku Kyōjurō
[28.05.2022 13:10:27] Шмурдяк
[28.05.2022 13:10:27] Rengoku Kyōjurō
[28.05.2022 13:09:37] Шмурдяк
[28.05.2022 13:09:37] Rengoku Kyōjurō
[28.05.2022 12:16:46] Marlina_Ra
[28.05.2022 12:16:46] Шмурдяк
[28.05.2022 12:16:46] Rengoku Kyōjurō
[28.05.2022 12:16:34] Marlina_Ra
[28.05.2022 12:16:34] Шмурдяк
[28.05.2022 12:16:34] Rengoku Kyōjurō
[28.05.2022 12:16:33] Marlina_Ra
[28.05.2022 12:16:33] Шмурдяк
[28.05.2022 12:16:33] Rengoku Kyōjurō
[28.05.2022 12:16:29] Received STARTGAMEFINALIZE packet. Round init status: Started
[28.05.2022 12:16:29] Task count: 0
[28.05.2022 12:16:29] Received STARTGAMEFINALIZE packet. Round init status: WaitingForStartGameFinalize
[28.05.2022 12:16:20] Generating an outpost for the start of the level... (Location: Исследовательская станция Pelagon Linea, level type: Outpost)
[28.05.2022 12:11:44] Lobby created!
[28.05.2022 12:10:38] Attempting to open ALC device "OpenAL Soft on Speakers (2- USB Audio Device)"
[28.05.2022 12:10:32] Logged in as Rengoku Kyōjurō (SteamID STEAM_1:1:68939684)
```

**Comment by Regalis11** [comment]
Thank you for the suggestion!

This is definitely something we need to look into (as very large stacks of items tend to cause many kinds of issues, not just networking problems). However, the game doesn't send the XML data to the clients on the fly like this - the only time XML files are sent is when the server syncs the campaign saves to the clients at the end of the round, and the files are sent in a compressed format, split into multiple packets, so they're not the cause to the "packet size exceeded" errors. 

The problem here most likely has to do with the [inventory updates that are sent when placing items in a container](https://github.com/Regalis11/Barotrauma-development/blob/4c49999b71e10ae73a3a897f71ee754aca9bce71/Barotrauma/BarotraumaShared/SharedSource/Items/Inventory.cs#L960), and those don't contain any other data than the numbers of contained items and their IDs.

**Comment by RunoLight** [comment]
Thanks for clarifying!
Also there is thing in all issues, developers using links to repository (like there with link to inventory updates, or to commits when issue is closed in some commit) within `github.com/Regalis11/`**Barotrauma-development**`/`, 
when open-source repository is `github.com/Regalis11/`**Barotrauma**`/`.
So, Barotrauma-development links leads to **404** at least by **non**-contributor (I think because it's hidden repository). Just telling you in case you didn't know it is works as it works, because I was wonder to see how some issues are fixed but can't get to link where and how it's fixed to get known with project base and maybe contribute to it. :)

**Comment by Regalis11** [comment]
The first link was intentionally to our private repo (just for our dev team's internal use), but the 2nd one was supposed to be to the code in the public repo. Fixed that now! :)

**Comment by Regalis11** [comment]
Finally got around to addressing this (commit in our private repo: https://github.com/Regalis11/Barotrauma-development/commit/ce15d143cc802d1cacfb14364693cadf0a6280ee)

**Comment by Rokvach** [comment]
While testing with the provided repro steps I noticed that newly moved items started to fall out of the industrial storage crate when its little less than half full, you can still keep filling up the crate but it becomes a bit tedious as you have to place a stack then wait for it to drop pick the stack back up and place it again, no error sightings however. 

It becomes increasingly more difficult to fill the crate the more items you have in it

There also starts to be a noticeable stutter whenever you place an item in the crate or when a item drops from the crate the more full the crate is.

![image](https://github.com/Regalis11/Barotrauma/assets/7299826/7d1de7f3-65ca-4a75-9e8d-c2e29f9cc314)

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/pull/4284/commits/b992647936bba37184a5ecd26b492fd3d78357a1 and https://github.com/Regalis11/Barotrauma-development/pull/4284/commits/de58e431ec6873c48f09f5aed293f6a2af7d0f8a

**Comment by Rokvach** [comment]
Its a lot more reliable now, no issues when double clicking stacks to move them to the crate. I did notice that using the number keys to move multiple stacks at once can still cause a stack or two to drop on the floor but you really need to be spamming those number keys or pressing multiple/all of them at once and even then it isn't as bad as it was before the recent fixes. Loading to the round was a also a lot faster. 

Moving multiple stacks at once seems to also lead into slight fps drops, so maybe we should consider adding some type of cooldown on how fast you can store items considering as currently you can press all the 1-0 keys at once to store your entire inventory at the same time. But this feels like out of the scope for this PR.

**Comment by Rokvach** [comment]
Tested, working correctly, can be merged and closed.
