### ISSUE TITLE
NoSuitableGraphicsDeviceException on game launch in Linux after today's update

### ISSUE THREAD

**Issue by Trevortds** [Regalis11/Barotrauma#9226]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When clicking the "start" button through steam, the game immediately crashes and produces the following bug report log. 

### Reproduction steps

1. Install game through Steam for linux
2. Attempt to run game

### Bug prevalence

Happens every time I play

### Version

Other

### -

v0.17.16.0

### Which operating system did you encounter this bug on?

Linux

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 05/30/2022 12:52:18)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


167F2CA0B7E9C63F71A5C1DD62D7F666


Game version 0.17.16.0 (ReleaseLinux, branch release, revision 05309f303f)
Graphics mode: 0x0 (Windowed)
VSync OFF
Language: 
Selected content packages: None
Level seed: no level loaded
Loaded submarine: None
Selected screen: None
SteamManager initialized


System info:
    Operating system: Unix 5.15.38.1 64 bit
    Game not initialized


Exception: Unable to retrieve OpenGL version (Microsoft.Xna.Framework.Graphics.NoSuitableGraphicsDeviceException)
Target site: Void PlatformSetup()
Stack trace: 
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformSetup() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Graphics/GraphicsDevice.OpenGL.cs:line 313
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.Setup() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Graphics/GraphicsDevice.cs:line 249
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice..ctor(GraphicsAdapter adapter, GraphicsProfile graphicsProfile, PresentationParameters presentationParameters) in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Graphics/GraphicsDevice.cs:line 224
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice..ctor(GraphicsDeviceInformation gdi) in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Graphics/GraphicsDevice.cs:line 191
   at Microsoft.Xna.Framework.GraphicsDeviceManager.CreateDevice(GraphicsDeviceInformation gdi) in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/GraphicsDeviceManager.cs:line 131
   at Microsoft.Xna.Framework.GraphicsDeviceManager.CreateDevice() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/GraphicsDeviceManager.cs:line 114
   at Microsoft.Xna.Framework.GraphicsDeviceManager.ApplyChanges() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/GraphicsDeviceManager.cs:line 305
   at Barotrauma.GameMain..ctor(String[] args) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/GameMain.cs:line 218
   at Barotrauma.Program.Main(String[] args) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Program.cs:line 57


Last debug messages:
[05/30/2022 12:52:18] Logged in as HannasAnarion (SteamID STEAM_1:0:47784190)
```

**Comment by Trevortds** [comment]
Fixed by a reboot. Must have been a driver update that weirded out the graphics detection. Sorry for polluting the issue page.
