### ISSUE TITLE
Trying to save a newly created submarine throws an error and prevents saving

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#9238]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When creating a totally new submarine and trying to save it there's a error which prevents from saving it, only way to save it is to save it into a existing submarines content package. 

### Reproduction steps

1. Open up sub editor
2. Place down a hull and a spawnpoint
3. Save the submarine
4. Receive an error and the submarine isn't saved

### Bug prevalence

Happens every time I play

### Version

Other

### -

0.18.4.0 Unstable

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
An error occurred while trying to save testsub {Object reference not set to an instance of an object.}
   at Barotrauma.SubEditorScreen.SaveSubToFile(String name, ContentPackage packageToSaveTo) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\SubEditorScreen.cs:line 1873
   at Barotrauma.SubEditorScreen.<>c__DisplayClass123_0.<SaveSub>b__4() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\SubEditorScreen.cs:line 1742
   at Barotrauma.SubEditorScreen.<>c__DisplayClass123_0.<SaveSub>g__handleExceptions|0(Action action) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\SubEditorScreen.cs:line 1713
```

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/754ccbadf39e196ba7d8a284935078cb0b96a33d

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
