### ISSUE TITLE
crach the game while using the editor

### ISSUE THREAD

**Issue by sinsikyan** [Regalis11/Barotrauma#9288]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

the game crash

### Reproduction steps

1. open submarine editor
2. in "add submarine", add submarine
3. save that submarine as item assembly
4. crash

after the first crash
1. open item assembly
2. crash

### Bug prevalence

Just once

### Version

0.17.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

I'm afraid I could not reproduce this. Could you post the crash report if you still have it?

**Comment by JoneKone** [comment]
1.  Load Kastrul drone
2. Load from (Place another submarine in to the current submarine) menu another kastrull drone
3. Select Linked submarine
4. Click Save as Item assembly
5. Open Item assembly
6. Click on set assembly
7. place assembly

```
Error while loading entity of the type Barotrauma.LinkedSubmarine. {ID 1 is taken by Docking Hatch (ID: 1)}
   at Barotrauma.Entity..ctor(Submarine submarine, UInt16 id) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Map/Entity.cs:line 122
   at Barotrauma.MapEntity..ctor(MapEntityPrefab prefab, Submarine submarine, UInt16 id) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Map/MapEntity.cs:line 252
   at Barotrauma.LinkedSubmarine..ctor(Submarine submarine, UInt16 id) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Map/LinkedSubmarine.cs:line 98
   at Barotrauma.LinkedSubmarine.CreateDummy(Submarine mainSub, XElement element, Vector2 position, UInt16 id) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Map/LinkedSubmarine.cs:line 131
   at Barotrauma.LinkedSubmarine.Load(ContentXElement element, Submarine submarine, IdRemap idRemap) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Map/LinkedSubmarine.cs:line 204
```

![Editor_error_save outline as itemassembly](https://user-images.githubusercontent.com/1114115/172792918-202a0f34-8ecb-4016-9f9a-1e9045b5244a.jpg)

**Comment by Regalis11** [comment]
Oh, so it doesn't actually crash to desktop, just throws an error in the console? In that case I'll set this as low prio

**Comment by sinsikyan** [comment]
thank you !!! JoneKone and Regalis11

**Comment by Regalis11** [comment]
(Finally) fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/4e878ead9b2822dfb34ea76175768d53afcea4e9 (commit in our private repo)
