### ISSUE TITLE
[Dev Version] Opening fabricator crashes the game.

### ISSUE THREAD

**Issue by samhamnam** [Regalis11/Barotrauma#929]
Whenever you try to open a fabricator by pressing e the game instantly crashes, and no crashlog is given. However when run through Visual Studio it points toward line 180 in the file HUDLayoutsettings.cs and gives a System.NullReferenceException. I am going to check if this happens when you try to open other interfaces. 

Edit 1: Submarine doesn't seem to matter as it happens with both of the included ones, and it also happens with the Deconstructor and Medical Fabricator, i.e crafting interfaces.

`System.NullReferenceException
  HResult=0x80004003
  Message=Objektreferensen har inte angetts till en instans av ett objekt.
  Source=Barotrauma
  StackTrace:
   at Barotrauma.Inventory.IsMouseOnInventory() in C:\Gitrepo\Barotrauma\Barotrauma\BarotraumaClient\Source\Items\Inventory.cs:line 496
   at Barotrauma.HUD.CloseHUD(Rectangle rect) in C:\Gitrepo\Barotrauma\Barotrauma\BarotraumaClient\Source\GUI\HUDLayoutSettings.cs:line 180
   at Barotrauma.ItemInventory.ControlInput(Camera cam) in C:\Gitrepo\Barotrauma\Barotrauma\BarotraumaClient\Source\Items\ItemInventory.cs:line 11
   at Barotrauma.Inventory.Update(Single deltaTime, Camera cam, Boolean subInventory) in C:\Gitrepo\Barotrauma\Barotrauma\BarotraumaClient\Source\Items\Inventory.cs:line 275
   at Barotrauma.Items.Components.ItemContainer.UpdateHUD(Character character, Single deltaTime, Camera cam) in C:\Gitrepo\Barotrauma\Barotrauma\BarotraumaClient\Source\Items\Components\ItemContainer.cs:line 143
   at Barotrauma.Item.UpdateHUD(Camera cam, Character character, Single deltaTime) in C:\Gitrepo\Barotrauma\Barotrauma\BarotraumaClient\Source\Items\Item.cs:line 498
   at Barotrauma.GameScreen.Update(Double deltaTime) in C:\Gitrepo\Barotrauma\Barotrauma\BarotraumaShared\Source\Screens\GameScreen.cs:line 108
   at Barotrauma.GameMain.Update(GameTime gameTime) in C:\Gitrepo\Barotrauma\Barotrauma\BarotraumaClient\Source\GameMain.cs:line 551
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at MonoGame.Framework.WinFormsGameWindow.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Barotrauma.Program.Main() in C:\Gitrepo\Barotrauma\Barotrauma\BarotraumaClient\Source\Program.cs:line 46
`

**Comment by Regalis11** [comment]
Are you sure your code is up to date? I think this was fixed in 0ed21d0

**Comment by samhamnam** [comment]
Pretty sure I am running the latest version, but will clone it again and try.

**Comment by samhamnam** [comment]
I re-cloned the code and it seems to be working now, unsure why but the issue was fixed at least. Sorry for any inconvenience.

**Comment by BillCombs** [comment]
Doesn't seem to happen on my side. I am running the latest version. Neither legacy nor dev fabricator crash the game.

**Comment by Regalis11** [comment]
No worries. :) And btw, just in case you're not familiar with git: you don't need to re-clone the entire repo to get the most up-to-date version, you only need to pull the latest commits.

**Comment by samhamnam** [comment]
Yea i know :p I was updated as I had just pulled the latest commits before playing.
