### ISSUE TITLE
You can lose money if you buy "Replace lost shuttles" and then do a submarine switch on the same outpost

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#9309]
**Steps To Reproduce**
1. Start campaign with Remora
2. Undock from outpost and lose your drone by driving it away from the main sub
3. Dock back to outpost
4. Buy "Replace lost shuttles"
5. Buy a new submarine and switch to it
6. Redock to outpost
7. Switch to Remora
8. Undock and notice that Remora doesn't have a drone
9. Dock back to outpost and notice that you can buy "Replace lost shuttles" again

**Version**
0.18.6.0
Branch: bugfixes

**Additional information**
I haven't tested the other options from the maintenance menu

**Comment by CurePindal** [comment]
I think i can even use the "replace lost shuttle" action with a sub that has no shuttles at all.
Expected: Option not possible if the actual sub has no shuttles.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/cd2d88bd256230f0dd2cd1926b466b2ec3a62165

**Comment by NilanthAnimosus** [comment]
Tested, not working as intended. Crashed on attempting to test.

Steps taken:
Started a new singleplayer campaign and added enough money to buy a remora.
Switched submarine to remora with the funds
Left the outpost and lost the shuttle, re-docked at the same starting outpost.
Bought the option to replace lost shuttles. Changed submarine to the one I started with without leaving first.
Game crashed on the loading screen on trying to change level.

Crashed in SharedSource\map\Linkedsubmarine.cs:456
`System.InvalidOperationException
  HResult=0x80131509
  Message=Sequence contains no elements
  Source=System.Linq
  StackTrace:
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Barotrauma.LinkedSubmarine.Save(XElement parentElement) in C:\Github_Sources\Barotrauma\Barotrauma\BarotraumaShared\SharedSource\Map\LinkedSubmarine.cs:line 456
   at Barotrauma.Submarine.SaveToXElement(XElement element) in C:\Github_Sources\Barotrauma\Barotrauma\BarotraumaShared\SharedSource\Map\Submarine.cs:line 1634
   at Barotrauma.SubmarineInfo..ctor(Submarine sub) in C:\Github_Sources\Barotrauma\Barotrauma\BarotraumaShared\SharedSource\Map\SubmarineInfo.cs:line 278
   at Barotrauma.SinglePlayerCampaign.<DoLevelTransition>d__18.MoveNext() in C:\Github_Sources\Barotrauma\Barotrauma\BarotraumaClient\ClientSource\GameSession\GameModes\SinglePlayerCampaign.cs:line 438
   at Barotrauma.CoroutineManager.PerformCoroutineStep(CoroutineHandle handle) in C:\Github_Sources\Barotrauma\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 196
   at Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle) in C:\Github_Sources\Barotrauma\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 229
   at Barotrauma.CoroutineManager.Update(Single unscaledDeltaTime, Single deltaTime) in C:\Github_Sources\Barotrauma\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 270
   at Barotrauma.GameMain.Update(GameTime gameTime) in C:\Github_Sources\Barotrauma\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 922
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in C:\Github_Sources\Barotrauma\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 651
   at Microsoft.Xna.Framework.Game.Tick() in C:\Github_Sources\Barotrauma\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in C:\Github_Sources\Barotrauma\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in C:\Github_Sources\Barotrauma\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in C:\Github_Sources\Barotrauma\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in C:\Github_Sources\Barotrauma\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58`

**Comment by NilanthAnimosus** [comment]
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/36e3a2755f5fc201a748a32b63cc93a8eb30d90a, Working correctly, closing.

**Comment by Rokvach** [comment]
Tested, this is working fine after the recent changes to attached shuttles, closing.
