### ISSUE TITLE
[Unstable 0.18.8.0]

### ISSUE THREAD

**Issue by Lefttroll** [Regalis11/Barotrauma#9326]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

When launching campaign with mods in unstable it crashes (any mod that is not player submarine, including item mods, wrecks mods, station mods and etc).
When launching pure vanilla campaign - game works absolutely fine.

### Reproduction steps

1. Select any mods (for example mods in provided .txt file [dont forget to turn it back into .xml])
2. launch campaign
3. get crashed
[basic preset.txt](https://github.com/Regalis11/Barotrauma/files/8886871/basic.preset.txt)

### Bug prevalence

Happens every time I play

### Version

0.18.8.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Logged in as heheboi (SteamID STEAM_1:1:452965244)
Attempting to open ALC device "OpenAL Soft on Динамики (Logitech PRO X Gaming Headset)"
Level identifier: outpostlevel
Generating an outpost for the start of the level... (Location: New Nanhui Outpost, level type: Outpost)
Overriding an affliction or a buff with the identifier 'huskinfection' using the file 'C:/Users/ilyab/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2085783214/Afflictions.xml'
WARNING: Error in affliction "Dementonite poisoning" - additional afflictions caused by the affliction should be configured inside status effects.
Level identifier: outpostlevel
Generating an outpost for the start of the level... (Location: Gangpo Habitation Outpost, level type: Outpost)
Failed to find any spawn point for the sub: Losgann_Wrecked2T (No valid waypoints left).
Failed to position wreck Losgann_Wrecked2T. Used 0 (ms).
Failed to find any spawn point for the sub: Structure_Wrecked (No valid waypoints left).
Failed to position wreck Structure_Wrecked. Used 0 (ms).
Coroutine Barotrauma.SinglePlayerCampaign+<DoLoadInitialLevel>d__16 threw an exception: The given key 'missionevent_killswarm' was not present in the dictionary.
   at System.Collections.Concurrent.ConcurrentDictionary`2.ThrowKeyNotFoundException(Object key)
   at System.Collections.Concurrent.ConcurrentDictionary`2.get_Item(TKey key)
   at Barotrauma.PrefabCollection`1.get_Item(Identifier identifier) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Prefabs\PrefabCollection.cs:line 229
   at Barotrauma.EventSet.SubEventPrefab.get_EventPrefabs()+MoveNext() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\EventSet.cs:line 143
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Barotrauma.EventManager.<CreateEvents>b__80_1(SubEventPrefab e) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\EventManager.cs:line 413
   at System.Linq.Enumerable.WhereArrayIterator`1.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Barotrauma.EventManager.CreateEvents(EventSet eventSet) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\EventManager.cs:line 412
   at Barotrauma.EventManager.CreateEvents(EventSet eventSet) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\EventManager.cs:line 477
   at Barotrauma.EventManager.StartRound(Level level) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\EventManager.cs:line 166
   at Barotrauma.GameSession.InitializeLevel(Level level) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameSession.cs:line 586
   at Barotrauma.GameSession.StartRound(LevelData levelData, Boolean mirrorLevel, SubmarineInfo startOutpost, SubmarineInfo endOutpost) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameSession.cs:line 433
   at Barotrauma.SinglePlayerCampaign.DoLoadInitialLevel(LevelData level, Boolean mirror)+MoveNext() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameSession\GameModes\SinglePlayerCampaign.cs:line 255
   at Barotrauma.CoroutineManager.PerformCoroutineStep(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 197
   at Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 255
```

**Comment by Rokvach** [comment]
Looks like its FrithsMissionTweak which causes the crash on startup or unable to launch campaign after enabling the mod

https://steamcommunity.com/sharedfiles/filedetails/?id=2788861460

```
Barotrauma Client crash report (generated on 06/13/2022 10:53:26)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


To prevent further startup errors, installed mods will be disabled the next time you launch the game.


257114797036D46F80C8DC0F11A5EF23


Game version 0.18.8.0 (ReleaseWindows, branch release, revision fad64ef824)
Graphics mode: 2560x1440 (BorderlessWindowed)
VSync OFF
Language: English
Selected content packages: Vanilla, FrithsMissionTweak
Level seed: no level loaded
Loaded submarine: None
Selected screen: None
SteamManager initialized


System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit
    GPU name: NVIDIA GeForce GTX 980 Ti
    Display mode: {Width:2560 Height:1440 Format:Color AspectRatio:1.7777778}
    GPU status: Normal


Exception: Loading was interrupted due to an error. (Barotrauma.GameMain+LoadingException)
Target site: Void Update(Microsoft.Xna.Framework.GameTime)
Stack trace: 
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 732
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59


InnerException: The given key 'missionevent_killswarm' was not present in the dictionary.
Target site: Void ThrowKeyNotFoundException(System.Object)
Stack trace: 
   at System.Collections.Concurrent.ConcurrentDictionary`2.ThrowKeyNotFoundException(Object key)
   at System.Collections.Concurrent.ConcurrentDictionary`2.get_Item(TKey key)
   at Barotrauma.PrefabCollection`1.get_Item(Identifier identifier) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Prefabs\PrefabCollection.cs:line 229
   at Barotrauma.EventSet.SubEventPrefab.get_EventPrefabs()+MoveNext() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\EventSet.cs:line 143
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Barotrauma.EventSet.AddSetEventPrefabsToList(List`1 list, EventSet set) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\EventSet.cs:line 74
   at Barotrauma.EventSet.AddSetEventPrefabsToList(List`1 list, EventSet set) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\EventSet.cs:line 74
   at Barotrauma.EventSet.GetAllEventPrefabs() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\EventSet.cs:line 64
   at Barotrauma.EventEditorScreen.CreateGUI() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\EventEditor\EventEditorScreen.cs:line 102
   at Barotrauma.EventEditorScreen..ctor() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\EventEditor\EventEditorScreen.cs:line 53
   at Barotrauma.GameMain.Load(Boolean isSeparateThread)+MoveNext() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 551
   at Barotrauma.CoroutineManager.PerformCoroutineStep(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 197
   at Barotrauma.CoroutineManager.ExecuteCoroutineThread(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 204
Last debug messages:
[06/13/2022 10:53:26] Coroutine "Load" has failed
[06/13/2022 10:53:25] Coroutine "Load" has thrown an exception {The given key 'missionevent_killswarm' was not present in the dictionary.}
   at System.Collections.Concurrent.ConcurrentDictionary`2.ThrowKeyNotFoundException(Object key)
   at System.Collections.Concurrent.ConcurrentDictionary`2.get_Item(TKey key)
   at Barotrauma.PrefabCollection`1.get_Item(Identifier identifier) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Prefabs\PrefabCollection.cs:line 229
   at Barotrauma.EventSet.SubEventPrefab.get_EventPrefabs()+MoveNext() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\EventSet.cs:line 143
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Barotrauma.EventSet.AddSetEventPrefabsToList(List`1 list, EventSet set) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\EventSet.cs:line 74
   at Barotrauma.EventSet.AddSetEventPrefabsToList(List`1 list, EventSet set) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\EventSet.cs:line 74
   at Barotrauma.EventSet.GetAllEventPrefabs() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\EventSet.cs:line 64
   at Barotrauma.EventEditorScreen.CreateGUI() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\EventEditor\EventEditorScreen.cs:line 102
   at Barotrauma.EventEditorScreen..ctor() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\EventEditor\EventEditorScreen.cs:line 53
   at Barotrauma.GameMain.Load(Boolean isSeparateThread)+MoveNext() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 551
   at Barotrauma.CoroutineManager.PerformCoroutineStep(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 197
   at Barotrauma.CoroutineManager.ExecuteCoroutineThread(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 204
[06/13/2022 10:52:57] Attempting to open ALC device "OpenAL Soft on Kaiuttimet (Realtek High Definition Audio)"
```

**Comment by Rokvach** [comment]
The mod does get disabled if you get the crash at the start, so it doesn't break the game fully for players

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/34b14106bc000a59c8c2dddeb728baae43d70dde and https://github.com/Regalis11/Barotrauma-development/commit/224ed04e25dc8eab66156e9602f80487c6cd922d
