### ISSUE TITLE
New clients getting kicked out of server if someone has placed down and wired in components previously during campaign

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#9332]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I tried to join a community hosted server and upon loading into the round I was bombarded with errors and kicked out of the server because of a event error

Host was running a dedicated server

The errors seems to point at a manually wired ARC setup for the reactor that was wired couple levels before I joined the server

Seems like this issue only happens once when you try to join a new campaign, after you have been kicked out and you try and join again you do get in just fine. 

![image](https://user-images.githubusercontent.com/7299826/173424456-6e618ee3-0131-45a1-9fce-f55c006a62ed.png)

[event_error_log_server_Rokvach_1845.log](https://github.com/Regalis11/Barotrauma/files/8893691/event_error_log_server_Rokvach_1845.log)
[event_error_log_client_Rokvach_1845.log](https://github.com/Regalis11/Barotrauma/files/8893699/event_error_log_client_Rokvach_1845.log)

### Reproduction steps

Speculative

1. Have someone place down components or create a ARC
2. Join the server

### Bug prevalence

Just once

### Version

0.18.9.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
ERROR 1 ===========================================================

Failed to read event 712 for entity "Divide Component (ID: 496)", id 496  {Index was outside the bounds of the array.}
   at Lidgren.Network.NetBitWriter.ReadByte(Byte[] fromBuffer, Int32 numberOfBits, Int32 readBitOffset) in <DEV>\Libraries\Lidgren.Network\NetBitWriter.cs:line 41
   at Lidgren.Network.NetBitWriter.ReadUInt16(Byte[] fromBuffer, Int32 numberOfBits, Int32 readBitOffset) in <DEV>\Libraries\Lidgren.Network\NetBitWriter.cs:line 229
   at Barotrauma.Networking.MsgReader.ReadUInt16(Byte[] buf, Int32& bitPos) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\Primitives\Message\Message.cs:line 261
   at Barotrauma.Items.Components.ConnectionPanel.ClientEventRead(IReadMessage msg, Single sendingTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Components\Signal\ConnectionPanel.cs:line 158
   at Barotrauma.Item.ClientEventRead(IReadMessage msg, Single sendingTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Item.cs:line 1299
   at Barotrauma.Networking.ClientEntityEventManager.Read(ServerNetObject type, IReadMessage msg, Single sendingTime, List`1 entities) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\NetEntityEvent\ClientEntityEventManager.cs:line 224

Failed to read event 713 for entity "Memory Component (ID: 2777)", id 2777  {Index was outside the bounds of the array.}
   at Lidgren.Network.NetBitWriter.ReadByte(Byte[] fromBuffer, Int32 numberOfBits, Int32 readBitOffset) in <DEV>\Libraries\Lidgren.Network\NetBitWriter.cs:line 41
   at Lidgren.Network.NetBitWriter.ReadUInt16(Byte[] fromBuffer, Int32 numberOfBits, Int32 readBitOffset) in <DEV>\Libraries\Lidgren.Network\NetBitWriter.cs:line 229
   at Barotrauma.Networking.MsgReader.ReadUInt16(Byte[] buf, Int32& bitPos) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\Primitives\Message\Message.cs:line 261
   at Barotrauma.Items.Components.ConnectionPanel.ClientEventRead(IReadMessage msg, Single sendingTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Components\Signal\ConnectionPanel.cs:line 158
   at Barotrauma.Item.ClientEventRead(IReadMessage msg, Single sendingTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Item.cs:line 1299
   at Barotrauma.Networking.ClientEntityEventManager.Read(ServerNetObject type, IReadMessage msg, Single sendingTime, List`1 entities) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\NetEntityEvent\ClientEntityEventManager.cs:line 224

Failed to read event 729 for entity "Nuclear Reactor (ID: 125)", id 125  {Index was outside the bounds of the array.}
   at Lidgren.Network.NetBitWriter.ReadByte(Byte[] fromBuffer, Int32 numberOfBits, Int32 readBitOffset) in <DEV>\Libraries\Lidgren.Network\NetBitWriter.cs:line 41
   at Lidgren.Network.NetBitWriter.ReadUInt16(Byte[] fromBuffer, Int32 numberOfBits, Int32 readBitOffset) in <DEV>\Libraries\Lidgren.Network\NetBitWriter.cs:line 229
   at Barotrauma.Networking.MsgReader.ReadUInt16(Byte[] buf, Int32& bitPos) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\Primitives\Message\Message.cs:line 261
   at Barotrauma.Items.Components.ConnectionPanel.ClientEventRead(IReadMessage msg, Single sendingTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Components\Signal\ConnectionPanel.cs:line 158
   at Barotrauma.Item.ClientEventRead(IReadMessage msg, Single sendingTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Item.cs:line 1299
   at Barotrauma.Networking.ClientEntityEventManager.Read(ServerNetObject type, IReadMessage msg, Single sendingTime, List`1 entities) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\NetEntityEvent\ClientEntityEventManager.cs:line 224

Failed to read event 736 for entity "Greater Component (ID: 2778)", id 2778  {Index was outside the bounds of the array.}
   at Lidgren.Network.NetBitWriter.ReadByte(Byte[] fromBuffer, Int32 numberOfBits, Int32 readBitOffset) in <DEV>\Libraries\Lidgren.Network\NetBitWriter.cs:line 41
   at Lidgren.Network.NetBitWriter.ReadUInt16(Byte[] fromBuffer, Int32 numberOfBits, Int32 readBitOffset) in <DEV>\Libraries\Lidgren.Network\NetBitWriter.cs:line 229
   at Barotrauma.Networking.MsgReader.ReadUInt16(Byte[] buf, Int32& bitPos) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\Primitives\Message\Message.cs:line 261
   at Barotrauma.Items.Components.ConnectionPanel.ClientEventRead(IReadMessage msg, Single sendingTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Components\Signal\ConnectionPanel.cs:line 158
   at Barotrauma.Item.ClientEventRead(IReadMessage msg, Single sendingTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Item.cs:line 1299
   at Barotrauma.Networking.ClientEntityEventManager.Read(ServerNetObject type, IReadMessage msg, Single sendingTime, List`1 entities) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\NetEntityEvent\ClientEntityEventManager.cs:line 224

Failed to read event 1990 for entity "Multiply Component (ID: 2880)", id 2880  {Index was outside the bounds of the array.}
   at Lidgren.Network.NetBitWriter.ReadByte(Byte[] fromBuffer, Int32 numberOfBits, Int32 readBitOffset) in <DEV>\Libraries\Lidgren.Network\NetBitWriter.cs:line 41
   at Lidgren.Network.NetBitWriter.ReadUInt16(Byte[] fromBuffer, Int32 numberOfBits, Int32 readBitOffset) in <DEV>\Libraries\Lidgren.Network\NetBitWriter.cs:line 229
   at Barotrauma.Networking.MsgReader.ReadUInt16(Byte[] buf, Int32& bitPos) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\Primitives\Message\Message.cs:line 261
   at Barotrauma.Items.Components.ConnectionPanel.ClientEventRead(IReadMessage msg, Single sendingTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Components\Signal\ConnectionPanel.cs:line 158
   at Barotrauma.Item.ClientEventRead(IReadMessage msg, Single sendingTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Item.cs:line 1299
   at Barotrauma.Networking.ClientEntityEventManager.Read(ServerNetObject type, IReadMessage msg, Single sendingTime, List`1 entities) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\NetEntityEvent\ClientEntityEventManager.cs:line 224

ERROR 2 ===========================================================

Message byte position incorrect after reading an event for the entity "Docking Hatch (ID: 6632)" (ID 6632). The previous entity was "Docking Hatch (ID: 179)" (ID 179) Read 456 bits, expected message length was 176 bits.

Message byte position incorrect after reading an event for the entity "Docking Hatch (ID: 3455)" (ID 3455). The previous entity was "" (ID 0) Read 456 bits, expected message length was 192 bits.

Message byte position incorrect after reading an event for the entity "Custom Hatch (ID: 3336)" (ID 3336). The previous entity was "Junction Box (ID: 3167)" (ID 3167) Read 488 bits, expected message length was 104 bits.

ERROR 3 ===========================================================

Error while reading a message from the server. Entity event data exceeds the size of the buffer (current position: 8112, length: 8120).
Previous entities:
Chaingun Bolt (ID: 2699)
Chaingun (ID: 285)
EntitySpawner
Crawlerhusk
Window Vertical
Crawlerhusk
Chaingun (ID: 285)
EntitySpawner
Chaingun (ID: 285)
EntitySpawner
Chaingun Ammunition Box (ID: 299)
Shuttle Navigation Terminal (ID: 3436)
Fabricator (ID: 554)
Supercapacitor (ID: 3387)
Chaingun Loader (ID: 3429)
Fuel Rod (ID: 3101)
EntitySpawner
EntitySpawner
EntitySpawner
EntitySpawner
Fuel Rod (ID: 3101)
EntitySpawner
Fabricator (ID: 554)
Crawlerhusk
Crawlerhusk
EntitySpawner
EntitySpawner
EntitySpawner
EntitySpawner
EntitySpawner
Crawlerhusk
Crawlerhusk
EntitySpawner
Deconstructor (ID: 566)
Crawlerhusk
Crawlerhusk
Deconstructor (ID: 566)
Crawlerhusk
Crawlerhusk
Light Component (ID: 3488)
Shuttle Navigation Terminal (ID: 3436)
Shuttle Navigation Terminal (ID: 3436)
Relay Component (ID: 3473)
Fabricator (ID: 554)
EntitySpawner
EntitySpawner
EntitySpawner
EntitySpawner
EntitySpawner
Crawlerhusk
Crawlerhusk
Fuel Rod (ID: 2935)
EntitySpawner
EntitySpawner
EntitySpawner
EntitySpawner
Fuel Rod (ID: 2935)
EntitySpawner
Fabricator (ID: 554)
NULL
Docking Hatch (ID: 3455)

ERROR 4 ===========================================================

Failed to launch a projectile - item with the ID "7048 not found
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5e8ed8ef4d9cbf4d599d094f60b52632a3fbfb16

**Comment by Rokvach** [comment]
Tested, wasn't able to reproduce this. Seems to be working correctly. Closing.
