### ISSUE TITLE
Tried to overwrite a submarine that's not in a local package error when saving a submarine

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#9340]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

.

### Reproduction steps

1. Save a new submarine
2. Delete the newly saved submarine in editor
3. Save it again without changing the name or save a new submarine with the same name as you used previously
4. You should receive an error and the sub doesn't save

### Bug prevalence

Happens every time I play

### Version

0.18.10.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
An error occurred while trying to save Berilia 2 {Tried to overwrite a submarine (Berilia 2) that's not in a local package!}
   at Barotrauma.SubEditorScreen.SaveSubToFile(String name, ContentPackage packageToSaveTo) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\SubEditorScreen.cs:line 0
   at Barotrauma.SubEditorScreen.<>c__DisplayClass123_0.<SaveSub>b__1() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\SubEditorScreen.cs:line 1758
   at Barotrauma.SubEditorScreen.<>c__DisplayClass123_0.<SaveSub>g__handleExceptions|0(Action action) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\SubEditorScreen.cs:line 1715
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c8cbb0f4bc6a3cd2f4a8f65519117852f7a6c4fd

**Comment by NilanthAnimosus** [comment]
Tested, Working correctly, closing.
