### ISSUE TITLE
STILL CRASHING

### ISSUE THREAD

**Issue by Noxurius** [Regalis11/Barotrauma#9367]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

After I've done everything people told me to do the game is still crashing for no reason, this is NOT a duplicate of #1833 since I did everything, every solutions of that issue and it's still crashing, help me.

### Reproduction steps

1.Start a game
2.Play 5-10mn
3.Crash

### Bug prevalence

Happens every time I play

### Version

0.18.11.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 16/06/2022 14:56:28)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


126A1EFE280FCB5E98C29D91D4C57FA1


Game version 0.18.11.0 (ReleaseWindows, branch release, revision 75c2f92d56)
Graphics mode: 1920x1080 (Fullscreen)
VSync ON
Language: English
Selected content packages: Vanilla, Onyx Spear, Onyx Spear, The Spear
Level seed: AttisBrunhes
Loaded submarine: Onyx Spear (CC395E68B2B522FA0AF42A490926ABE4)
Selected screen: Barotrauma.GameScreen
SteamManager initialized
Client (Round had started)


System info:
    Operating system: Microsoft Windows NT 10.0.19043.0 64 bit
    GPU name: NVIDIA GeForce GTX 1050
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1,7777778}
    GPU status: Normal


Exception: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: L’instance de périphérique GPU a été suspendue. Utilisez GetDeviceRemovedReason pour déterminer l’action appropriée.
 (SharpDX.SharpDXException)
Device removed reason: HRESULT = 0x887A0006
Target site: Void CheckError()
Stack trace: 
   at SharpDX.Result.CheckError()
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformPresent() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\GraphicsDevice.DirectX.cs:line 1017
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 511
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59


Last debug messages:
[16/06/2022 14:55:23] Engagé zeke
[16/06/2022 14:55:23] Noxurius
[16/06/2022 14:55:21] Received STARTGAMEFINALIZE packet. Round init status: Started
[16/06/2022 14:55:21] Task count: 0
[16/06/2022 14:55:21] Received STARTGAMEFINALIZE packet. Round init status: WaitingForStartGameFinalize
[16/06/2022 14:55:18] Generating an outpost for the start of the level... (Location: Attis Facility, level type: LocationConnection)
[16/06/2022 14:55:17] Generating an outpost for the end of the level... (Location: Brunhes Habitation Outpost, level type: LocationConnection)
[16/06/2022 14:55:16] Level identifier: coldcavernsbasic
[16/06/2022 14:55:05] Engagé zeke
[16/06/2022 14:55:05] Noxurius
[16/06/2022 14:55:05] Engagé zeke
[16/06/2022 14:55:05] Noxurius
[16/06/2022 14:53:01] Engagé zeke
[16/06/2022 14:53:01] Noxurius
[16/06/2022 14:52:59] Received STARTGAMEFINALIZE packet. Round init status: Started
[16/06/2022 14:52:59] Task count: 0
[16/06/2022 14:52:59] Received STARTGAMEFINALIZE packet. Round init status: WaitingForStartGameFinalize
[16/06/2022 14:52:56] Generating an outpost for the start of the level... (Location: Brunhes Habitation Outpost, level type: Outpost)
[16/06/2022 14:52:56] Level identifier: outpostlevel
[16/06/2022 14:52:45] Engagé zeke
[16/06/2022 14:52:45] Noxurius
[16/06/2022 14:52:44] Engagé zeke
[16/06/2022 14:52:44] Noxurius
[16/06/2022 14:52:44] Engagé zeke
[16/06/2022 14:52:44] Noxurius
[16/06/2022 14:48:37] Engagé zeke
[16/06/2022 14:48:37] Noxurius
[16/06/2022 14:48:36] Received STARTGAMEFINALIZE packet. Round init status: Started
[16/06/2022 14:48:35] Task count: 0
[16/06/2022 14:48:35] Received STARTGAMEFINALIZE packet. Round init status: WaitingForStartGameFinalize
[16/06/2022 14:48:31] Generating an outpost for the end of the level... (Location: Brunhes Habitation Outpost, level type: LocationConnection)
[16/06/2022 14:48:30] Generating an outpost for the start of the level... (Location: Kogavostok Outpost, level type: LocationConnection)
[16/06/2022 14:48:30] Level identifier: coldcavernsbasic
[16/06/2022 14:48:19] Engagé zeke
[16/06/2022 14:48:19] Noxurius
[16/06/2022 14:48:18] Engagé zeke
[16/06/2022 14:48:18] Noxurius
[16/06/2022 14:48:17] WARNING: Could not determine reputation change for faction "Children of the Honkmother" (faction was not present at the start of the round).
[16/06/2022 14:48:17] WARNING: Could not determine reputation change for faction "The Church of Husk" (faction was not present at the start of the round).
[16/06/2022 14:48:17] WARNING: Could not determine reputation change for faction "Jovian Separatists" (faction was not present at the start of the round).
[16/06/2022 14:48:17] WARNING: Could not determine reputation change for faction "Europa Coalition" (faction was not present at the start of the round).
[16/06/2022 14:44:52] Server running slowly (57 updates/s)!
[16/06/2022 14:44:48] Engagé zeke
[16/06/2022 14:44:48] Noxurius
[16/06/2022 14:44:48] Engagé zeke
[16/06/2022 14:44:48] Noxurius
[16/06/2022 14:44:48] Engagé zeke
[16/06/2022 14:44:47] Noxurius
[16/06/2022 14:44:44] Received STARTGAMEFINALIZE packet. Round init status: Started
[16/06/2022 14:44:44]  -2: WaitForPingDataAsync (owner), RanToCompletion
[16/06/2022 14:44:44]  -1: WaitForPingDataAsync (owner), RanToCompletion
[16/06/2022 14:44:44]  -0: WaitForPingDataAsync (owner), RanToCompletion
[16/06/2022 14:44:44] Task count: 3
[16/06/2022 14:44:44] Received STARTGAMEFINALIZE packet. Round init status: WaitingForStartGameFinalize
[16/06/2022 14:44:40] Generating an outpost for the start of the level... (Location: Kogavostok Outpost, level type: Outpost)
[16/06/2022 14:44:40] Level identifier: outpostlevel
[16/06/2022 14:43:55] Lobby created!
[16/06/2022 14:42:49] WARNING: Tried to restore enabled packages multiple times/without performing a backup
[16/06/2022 14:41:37] Engagé zeke
[16/06/2022 14:41:37] Noxurius
[16/06/2022 14:41:37] Engagé zeke
[16/06/2022 14:41:37] Noxurius
[16/06/2022 14:41:37] Engagé zeke
[16/06/2022 14:41:36] Noxurius
[16/06/2022 14:41:35] Server running slowly (57 updates/s)!
[16/06/2022 14:41:32] Received STARTGAMEFINALIZE packet. Round init status: Started
[16/06/2022 14:41:32]  -3: WaitForPingDataAsync (owner), RanToCompletion
[16/06/2022 14:41:32]  -2: WaitForPingDataAsync (owner), RanToCompletion
[16/06/2022 14:41:32]  -1: WaitForPingDataAsync (owner), RanToCompletion
[16/06/2022 14:41:32]  -0: WaitForPingDataAsync (owner), RanToCompletion
[16/06/2022 14:41:32] Task count: 4
[16/06/2022 14:41:32] Received STARTGAMEFINALIZE packet. Round init status: WaitingForStartGameFinalize
[16/06/2022 14:41:25] Generating an outpost for the start of the level... (Location: Anid Habitation Outpost, level type: Outpost)
[16/06/2022 14:41:25] Level identifier: outpostlevel
[16/06/2022 14:41:12] Server running slowly (57 updates/s)!
[16/06/2022 14:39:52] Lobby created!
[16/06/2022 14:38:36] Attempting to open ALC device "OpenAL Soft on Haut-parleur/Ecouteurs (Realtek High Definition Audio)"
[16/06/2022 14:38:33] Logged in as Noxurius (SteamID STEAM_1:0:67774949)
```

**Comment by Regalis11** [comment]
I'm sorry for not being able to help you more, but so far we haven't been able to figure out what's causing this (aside from the potential causes listed in https://github.com/Regalis11/Barotrauma/issues/1833).

This is the exact same error as https://github.com/Regalis11/Barotrauma/issues/1833 though, so I'll close this as a duplicate.
