### ISSUE TITLE
Selecting Shredder ammunition box causes Editor crash.

### ISSUE THREAD

**Issue by JoneKone** [Regalis11/Barotrauma#9369]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![Screenshot from 2022-06-16 17-38-28](https://user-images.githubusercontent.com/1114115/174094860-ba3aed6c-1adf-4365-ad3a-12b0a5c9d95d.png)

I wanted to check what that was and it crashed the editor, (didn't have a preview image)

### Reproduction steps

Go editor.
select Shredder ammunition.

### Bug prevalence

Just once

### Version

0.18.11.0

### Which operating system did you encounter this bug on?

Linux

### Relevant error messages and crash reports

```shell
﻿Barotrauma Client crash report (generated on 06/16/2022 17:34:22)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


F6DC1FADC8D8B49294B9DAD8E9AB760C


Game version 0.18.11.0 (ReleaseLinux, branch release, revision 75c2f92d56)
Graphics mode: 2560x1440 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla, Jotunn - Self-conscious - 5,500 credit submarine, [EMS] The Whale Shark (ORIGINAL), [ESS] Reckoning, R0-Q Rorqual Heavy Freighter, Ulysses 2.37, K-141 Kursk [RU], ULYSSES II (Atlantis the lost empire), Vengeance Mk. III, [RH] Joustus II.B (Mission), Project-705k Lyra, Y-Model Orca, Zidrom MKVI, Vengeance Selkie Mk. III (Mis), ULYSSES IIB (Mission), Kaivo Älykäs, Pieni kaappi
Level seed: no level loaded
Loaded submarine: ULYSSES IIB (Mission) (73EEB81D9DF1B0CEF6102579F5BCCFD7)
Selected screen: Barotrauma.SubEditorScreen
SteamManager initialized


System info:
    Operating system: Unix 5.18.4.0 64 bit
    GPU name: 
    Display mode: {Width:2560 Height:1440 Format:Color AspectRatio:1.7777778}
    GPU status: Normal


Exception: Texture is disposed (System.InvalidOperationException)
Target site: Void CheckValid(Microsoft.Xna.Framework.Graphics.Texture2D)
Stack trace: 
   at Microsoft.Xna.Framework.Graphics.SpriteBatch.CheckValid(Texture2D texture) in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Graphics/SpriteBatch.cs:line 249
   at Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(Texture2D texture, Vector2 position, Nullable`1 sourceRectangle, Color color, Single rotation, Vector2 origin, Vector2 scale, SpriteEffects effects, Single layerDepth) in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Graphics/SpriteBatch.cs:line 472
   at Barotrauma.Sprite.Draw(ISpriteBatch spriteBatch, Vector2 pos, Color color, Vector2 origin, Single rotate, Vector2 scale, SpriteEffects spriteEffect, Nullable`1 depth) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Sprite/Sprite.cs:line 219
   at Barotrauma.Sprite.Draw(ISpriteBatch spriteBatch, Vector2 pos, Single rotate, Single scale, SpriteEffects spriteEffect) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Sprite/Sprite.cs:line 202
   at Barotrauma.GUI.Draw(Camera cam, SpriteBatch spriteBatch) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/GUI/GUI.cs:line 629
   at Barotrauma.SubEditorScreen.Draw(Double deltaTime, GraphicsDevice graphics, SpriteBatch spriteBatch) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Screens/SubEditorScreen.cs:line 5750
   at Barotrauma.GameMain.Draw(GameTime gameTime) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/GameMain.cs:line 1003
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime) in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 669
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 511
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/SDL/SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Program.cs:line 59


Last debug messages:
[06/16/2022 17:28:21] Creating hulls between docking ports failed. Could not find a hull next to the docking port.
[06/16/2022 17:25:38] Creating hulls between docking ports failed. Could not find a hull next to the docking port.
[06/16/2022 17:21:55] Creating hulls between docking ports failed. Could not find a hull next to the docking port.
[06/16/2022 17:18:15] Creating hulls between docking ports failed. Could not find a hull next to the docking port.
[06/16/2022 17:17:03] Creating hulls between docking ports failed. Could not find a hull next to the docking port.
[06/16/2022 17:03:12] Creating hulls between docking ports failed. Could not find a hull next to the docking port.
[06/16/2022 16:59:29] Creating hulls between docking ports failed. Could not find a hull next to the docking port.
[06/16/2022 16:55:26] Creating hulls between docking ports failed. Could not find a hull next to the docking port.
[06/16/2022 16:31:02] Creating hulls between docking ports failed. Could not find a hull next to the docking port.
[06/16/2022 16:22:24] Creating hulls between docking ports failed. Could not find a hull next to the docking port.
[06/16/2022 16:16:32] Creating hulls between docking ports failed. Could not find a hull next to the docking port.
[06/16/2022 16:08:45] Creating hulls between docking ports failed. Could not find a hull next to the docking port.
[06/16/2022 16:06:30] Creating hulls between docking ports failed. Could not find a hull next to the docking port.
[06/16/2022 16:04:34] Creating hulls between docking ports failed. Could not find a hull next to the docking port.
[06/16/2022 15:50:27] Alc.CaptureOpenDevice attempt 2 failed: error code 40964
[06/16/2022 15:50:27] Alc.CaptureOpenDevice attempt 1 failed: error code 40964
[06/16/2022 15:50:17] Performance statistics disabled
[06/16/2022 15:50:17] showperf
[06/16/2022 15:48:56] Alc.CaptureOpenDevice attempt 2 failed: error code 40964
[06/16/2022 15:48:56] Alc.CaptureOpenDevice attempt 1 failed: error code 40964
[06/16/2022 15:45:59] Performance statistics enabled
[06/16/2022 15:45:59] showperf
[06/16/2022 15:41:16] Creating hulls between docking ports failed. Could not find a hull next to the docking port.
[06/16/2022 15:12:34] Creating hulls between docking ports failed. Could not find a hull next to the docking port.
[06/16/2022 14:59:55] Debug draw mode disabled
[06/16/2022 14:59:55] debugdraw
[06/16/2022 14:59:19] Debug draw mode enabled
[06/16/2022 14:59:19] debugdraw
[06/16/2022 14:57:57] Error in RelatedItem config (Headset) - "" is not a valid relation type.
[06/16/2022 14:57:57] Error in RelatedItem config (Headset) - "" is not a valid relation type.
[06/16/2022 14:57:57] Error in RelatedItem config (Headset) - "" is not a valid relation type.
[06/16/2022 14:57:57] Error in RelatedItem config (Headset) - "" is not a valid relation type.
[06/16/2022 14:57:10] LobbyMatchList:  LobbiesMatching: 0
[06/16/2022 14:57:10] LobbyMatchList:  LobbiesMatching: 0
[06/16/2022 14:57:10] SteamAPICallCompleted:   AsyncCall: 7505715656561071147
   Callback: 510
 ParamCount: 4
[06/16/2022 14:57:10] LobbyMatchList:  LobbiesMatching: 41
[06/16/2022 14:57:10] LobbyMatchList:  LobbiesMatching: 41
[06/16/2022 14:57:10] SteamAPICallCompleted:   AsyncCall: 17218733106675121281
   Callback: 510
 ParamCount: 4
[06/16/2022 14:57:10] PersonaStateChange:      SteamID: 76561198004050929
 ChangeFlags: 64
[06/16/2022 14:57:10] PersonaStateChange:      SteamID: 76561198004050929
 ChangeFlags: 1089
[06/16/2022 14:57:10] PersonaStateChange:      SteamID: 76561198368784316
 ChangeFlags: 64
[06/16/2022 14:57:10] PersonaStateChange:      SteamID: 76561198071454113
 ChangeFlags: 64
[06/16/2022 14:57:10] PersonaStateChange:      SteamID: 76561198355965286
 ChangeFlags: 64
[06/16/2022 14:57:10] PersonaStateChange:      SteamID: 76561198170462491
 ChangeFlags: 64
[06/16/2022 14:57:10] PersonaStateChange:      SteamID: 76561198053989721
 ChangeFlags: 64
[06/16/2022 14:57:10] PersonaStateChange:      SteamID: 76561198842670241
 ChangeFlags: 64
[06/16/2022 14:57:10] PersonaStateChange:      SteamID: 76561199063306111
 ChangeFlags: 64
[06/16/2022 14:57:10] PersonaStateChange:      SteamID: 76561198199368577
 ChangeFlags: 64
[06/16/2022 14:57:10] PersonaStateChange:      SteamID: 76561198822103222
 ChangeFlags: 64
[06/16/2022 14:57:10] PersonaStateChange:      SteamID: 76561197980350907
 ChangeFlags: 64
[06/16/2022 14:57:10] PersonaStateChange:      SteamID: 76561198220804324
 ChangeFlags: 64
[06/16/2022 14:57:10] PersonaStateChange:      SteamID: 76561197999947346
 ChangeFlags: 64
[06/16/2022 14:57:10] PersonaStateChange:      SteamID: 76561199006008556
 ChangeFlags: 64
[06/16/2022 14:57:10] PersonaStateChange:      SteamID: 76561198351189024
 ChangeFlags: 64
[06/16/2022 14:57:10] PersonaStateChange:      SteamID: 76561199146801386
 ChangeFlags: 64
[06/16/2022 14:57:10] PersonaStateChange:      SteamID: 76561198067175335
 ChangeFlags: 64
[06/16/2022 14:57:10] PersonaStateChange:      SteamID: 76561198011768130
 ChangeFlags: 64
[06/16/2022 14:57:10] PersonaStateChange:      SteamID: 76561198142089192
 ChangeFlags: 64
[06/16/2022 14:57:10] PersonaStateChange:      SteamID: 76561198041192461
 ChangeFlags: 64
[06/16/2022 14:57:10] PersonaStateChange:      SteamID: 76561198081153465
 ChangeFlags: 64
[06/16/2022 14:57:10] PersonaStateChange:      SteamID: 76561198088875136
 ChangeFlags: 64
[06/16/2022 14:57:10] PersonaStateChange:      SteamID: 76561198164792497
 ChangeFlags: 64
[06/16/2022 14:57:10] PersonaStateChange:      SteamID: 76561198368784316
 ChangeFlags: 1089
[06/16/2022 14:57:10] PersonaStateChange:      SteamID: 76561198071454113
 ChangeFlags: 1089
[06/16/2022 14:57:10] PersonaStateChange:      SteamID: 76561198355965286
 ChangeFlags: 1089
[06/16/2022 14:57:10] PersonaStateChange:      SteamID: 76561198170462491
 ChangeFlags: 1089
[06/16/2022 14:57:10] PersonaStateChange:      SteamID: 76561198053989721
 ChangeFlags: 1089
[06/16/2022 14:57:10] PersonaStateChange:      SteamID: 76561198842670241
 ChangeFlags: 1089
[06/16/2022 14:57:10] PersonaStateChange:      SteamID: 76561199063306111
 ChangeFlags: 1089
[06/16/2022 14:57:10] PersonaStateChange:      SteamID: 76561198199368577
 ChangeFlags: 1089
[06/16/2022 14:57:10] PersonaStateChange:      SteamID: 76561198822103222
 ChangeFlags: 1089
[06/16/2022 14:57:10] PersonaStateChange:      SteamID: 76561197980350907
 ChangeFlags: 1089
[06/16/2022 14:57:10] PersonaStateChange:      SteamID: 76561198220804324
 ChangeFlags: 1089
[06/16/2022 14:57:10] PersonaStateChange:      SteamID: 76561197999947346
 ChangeFlags: 1089
[06/16/2022 14:57:10] PersonaStateChange:      SteamID: 76561199006008556
 ChangeFlags: 1089
[06/16/2022 14:57:10] PersonaStateChange:      SteamID: 76561198351189024
 ChangeFlags: 1089
[06/16/2022 14:57:10] PersonaStateChange:      SteamID: 76561199146801386
 ChangeFlags: 1089
[06/16/2022 14:57:10] PersonaStateChange:      SteamID: 76561198067175335
 ChangeFlags: 1089
[06/16/2022 14:57:10] PersonaStateChange:      SteamID: 76561198011768130
 ChangeFlags: 1089
[06/16/2022 14:57:10] PersonaStateChange:      SteamID: 76561198142089192
 ChangeFlags: 1089
[06/16/2022 14:57:10] PersonaStateChange:      SteamID: 76561198041192461
 ChangeFlags: 1089
[06/16/2022 14:57:10] PersonaStateChange:      SteamID: 76561198058649377
 ChangeFlags: 1089
[06/16/2022 14:57:10] PersonaStateChange:      SteamID: 76561198081153465
 ChangeFlags: 1089
[06/16/2022 14:57:10] PersonaStateChange:      SteamID: 76561198088875136
 ChangeFlags: 1089
[06/16/2022 14:57:10] PersonaStateChange:      SteamID: 76561198164792497
 ChangeFlags: 1089
[06/16/2022 14:57:10] LobbyMatchList:  LobbiesMatching: 50
[06/16/2022 14:57:10] LobbyMatchList:  LobbiesMatching: 50
[06/16/2022 14:57:10] SteamAPICallCompleted:   AsyncCall: 7174449917711735903
   Callback: 510
 ParamCount: 4
[06/16/2022 14:57:09] LobbyMatchList:  LobbiesMatching: 50
[06/16/2022 14:57:09] LobbyMatchList:  LobbiesMatching: 50
[06/16/2022 14:57:09] SteamAPICallCompleted:   AsyncCall: 2155551825134898306
   Callback: 510
 ParamCount: 4
[06/16/2022 14:57:09] PersonaStateChange:      SteamID: 76561198008060535
 ChangeFlags: 64
[06/16/2022 14:57:09] PersonaStateChange:      SteamID: 76561198008060535
 ChangeFlags: 1024
[06/16/2022 14:57:09] AvatarImageLoaded:    SteamID: 76561198059930640
     Image: 319
      Wide: 184
      Tall: 184
[06/16/2022 14:57:09] AvatarImageLoaded:    SteamID: 76561199009030727
     Image: 331
      Wide: 184
      Tall: 184
[06/16/2022 14:57:09] AvatarImageLoaded:    SteamID: 76561198827600092
     Image: 330
      Wide: 184
      Tall: 184
[06/16/2022 14:57:09] AvatarImageLoaded:    SteamID: 76561198420531530
     Image: 329
      Wide: 184
      Tall: 184
[06/16/2022 14:57:09] AvatarImageLoaded:    SteamID: 76561198369742395
     Image: 328
      Wide: 184
      Tall: 184
[06/16/2022 14:57:09] AvatarImageLoaded:    SteamID: 76561198276136034
     Image: 327
      Wide: 184
      Tall: 184
[06/16/2022 14:57:09] AvatarImageLoaded:    SteamID: 76561198271701507
     Image: 326
      Wide: 184
      Tall: 184
[06/16/2022 14:57:09] AvatarImageLoaded:    SteamID: 76561198180966795
     Image: 325
      Wide: 184
      Tall: 184
[06/16/2022 14:57:09] AvatarImageLoaded:    SteamID: 76561198175547038
     Image: 324
      Wide: 184
      Tall: 184
[06/16/2022 14:57:09] AvatarImageLoaded:    SteamID: 76561198081969605
     Image: 323
      Wide: 184
      Tall: 184
[06/16/2022 14:57:09] AvatarImageLoaded:    SteamID: 76561198076732649
     Image: 322
      Wide: 184
      Tall: 184
[06/16/2022 14:57:09] AvatarImageLoaded:    SteamID: 76561198070379736
     Image: 321
      Wide: 184
      Tall: 184
[06/16/2022 14:57:09] AvatarImageLoaded:    SteamID: 76561198065397054
     Image: 320
      Wide: 184
      Tall: 184
[06/16/2022 14:57:09] AvatarImageLoaded:    SteamID: 76561198019109683
     Image: 318
      Wide: 184
      Tall: 184
[06/16/2022 14:57:09] AvatarImageLoaded:    SteamID: 76561198018221755
     Image: 317
      Wide: 184
      Tall: 184
[06/16/2022 14:57:09] AvatarImageLoaded:    SteamID: 76561198007397094
     Image: 316
      Wide: 184
      Tall: 184
[06/16/2022 14:57:09] AvatarImageLoaded:    SteamID: 76561198003345195
     Image: 315
      Wide: 184
      Tall: 184
[06/16/2022 14:57:09] AvatarImageLoaded:    SteamID: 76561198002248399
     Image: 314
      Wide: 184
      Tall: 184
[06/16/2022 14:57:09] AvatarImageLoaded:    SteamID: 76561197997276373
     Image: 313
      Wide: 184
      Tall: 184
[06/16/2022 14:57:09] AvatarImageLoaded:    SteamID: 76561197992781969
     Image: 312
      Wide: 184
      Tall: 184
[06/16/2022 14:57:09] AvatarImageLoaded:    SteamID: 76561197987547400
     Image: 311
      Wide: 184
      Tall: 184
[06/16/2022 14:57:09] AvatarImageLoaded:    SteamID: 76561197986607521
     Image: 310
      Wide: 184
      Tall: 184
[06/16/2022 14:57:09] AvatarImageLoaded:    SteamID: 76561197979006245
     Image: 309
      Wide: 184
      Tall: 184
[06/16/2022 14:57:09] AvatarImageLoaded:    SteamID: 76561197960616712
     Image: 308
      Wide: 184
      Tall: 184
[06/16/2022 14:57:09] AvatarImageLoaded:    SteamID: 76561197960270624
     Image: 307
      Wide: 184
      Tall: 184
[06/16/2022 14:51:52] Attempting to open ALC device "Starship/Matisse HD Audio Controller Analoginen stereo"
[06/16/2022 14:51:51] Logged in as JoneK (SteamID STEAM_1:0:1958739)
```

**Comment by Regalis11** [comment]
I haven't been able to reproduce this, so I suspect it's some kind of a race condition that doesn't occur consistently. Based on the error message, I think it might be related to the same bug that caused https://github.com/Regalis11/Barotrauma/issues/9775. Moving to testing.

**Comment by Rokvach** [comment]
Wasn't able to repro and if this issue is related to the other issue as Regalis mentioned then I think this is working correctly, closing.
