### ISSUE TITLE
Crash report (AIObjectivePumpWater.Filter)

### ISSUE THREAD

**Issue by PiatraAlatyr** [Regalis11/Barotrauma#9371]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Just crash while I was cutting raptor eggs.

### Bug prevalence

Just once

### Version

0.18.11.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 16.06.2022 19:08:28)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


126A1EFE280FCB5E98C29D91D4C57FA1


Game version 0.18.11.0 (ReleaseWindows, branch release, revision 75c2f92d56)
Graphics mode: 1920x1080 (Fullscreen)
VSync OFF
Language: Russian
Selected content packages: Vanilla, Barsuk BFC, Barsuk NFS, electric test, Meaningful Upgrades local, sub, Winterhalter Modernized, Wintershtorm, Автореактор продвинутый, Кирпич, Лампа, Морковка, ппп, Реактор R-278, Рубильники для балласта, Хемуль-М, Ядерный шкафчик, R-278 «Dugong»
Level seed: Phoenix LineaAna
Loaded submarine: R-278 «Dugong» [РУС] (C39045B6D20D5C27D34DCAEDF5DFA576)
Selected screen: Barotrauma.GameScreen
SteamManager initialized


System info:
    Operating system: Microsoft Windows NT 10.0.19043.0 64 bit
    GPU name: NVIDIA GeForce GTX 1080 Ti
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1,7777778}
    GPU status: Normal


Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Boolean Filter(Barotrauma.Items.Components.Pump)
Stack trace: 
   at Barotrauma.AIObjectivePumpWater.Filter(Pump pump) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\Objectives\AIObjectivePumpWater.cs:line 40
   at Barotrauma.AIObjectiveLoop`1.FindTargets() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\Objectives\AIObjectiveLoop.cs:line 187
   at Barotrauma.AIObjectiveLoop`1.UpdateTargets() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\Objectives\AIObjectiveLoop.cs:line 173
   at Barotrauma.AIObjectiveLoop`1.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\Objectives\AIObjectiveLoop.cs:line 77
   at Barotrauma.AIObjectiveManager.UpdateObjectives(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\Objectives\AIObjectiveManager.cs:line 271
   at Barotrauma.HumanAIController.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\HumanAIController.cs:line 396
   at Barotrauma.Character.UpdateAll(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 2750
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 190
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 874
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58


Last debug messages:
[16.06.2022 18:52:14] Could not find a spawn point for a SpawnAction (spawn location: BeaconStation (tag: beacon_bandit), skipping.
[16.06.2022 18:51:59] Generating an outpost for the start of the level... (Location: Исследовательская станция Phoenix Linea, level type: LocationConnection)
[16.06.2022 18:51:58] Generating an outpost for the end of the level... (Location: Институт астробиологии Ana, level type: LocationConnection)
[16.06.2022 18:51:44] Level identifier: greatseabasic
[16.06.2022 18:51:25] Transitioning to Phoenix LineaAna (current location: Институт астробиологии Ana, selected location: Исследовательская станция Phoenix Linea, leaving sub: R-278 «Dugong» [РУС], at start: True, at end: False, transition type: LeaveLocation)
[16.06.2022 18:48:53] Unlocked mission "Перевозка заключенных" in the location "Институт астробиологии Ana".
[16.06.2022 18:48:51] Unlocked mission "Разбор обломков" in the location "Институт астробиологии Ana".
[16.06.2022 18:48:49] Unlocked mission "Вредные грязевые рапторы" in the location "Институт астробиологии Ana".
[16.06.2022 18:48:47] Unlocked mission "Уничтожить гнездо грязевого раптора" in the location "Институт астробиологии Ana".
[16.06.2022 18:48:20] Generating an outpost for the start of the level... (Location: Институт астробиологии Ana, level type: Outpost)
[16.06.2022 18:48:20] Level identifier: outpostlevel
[16.06.2022 18:48:00] Transitioning to Ana (current location: Аванпост Gangpo, selected location: Институт астробиологии Ana, leaving sub: R-278 «Dugong» [РУС], at start: False, at end: True, transition type: ProgressToNextLocation)
[16.06.2022 18:36:56] Could not find a spawn point for a SpawnAction (spawn location: BeaconStation (tag: beacon_bandit), skipping.
[16.06.2022 18:36:41] Generating an outpost for the start of the level... (Location: Институт астробиологии Ana, level type: LocationConnection)
[16.06.2022 18:36:40] Generating an outpost for the end of the level... (Location: Аванпост Gangpo, level type: LocationConnection)
[16.06.2022 18:36:32] Level identifier: plateaubasic
[16.06.2022 18:36:14] Transitioning to AnaGangpo (current location: Аванпост Gangpo, selected location: Институт астробиологии Ana, leaving sub: R-278 «Dugong» [РУС], at start: True, at end: False, transition type: LeaveLocation)
[16.06.2022 18:25:06] Generating an outpost for the start of the level... (Location: Аванпост Gangpo, level type: Outpost)
[16.06.2022 18:25:06] Level identifier: outpostlevel
[16.06.2022 18:24:48] Transitioning to Gangpo (current location: Институт астробиологии Ana, selected location: Аванпост Gangpo, leaving sub: R-278 «Dugong» [РУС], at start: False, at end: True, transition type: ProgressToNextLocation)
[16.06.2022 18:12:49] Could not find a spawn point for a SpawnAction (spawn location: BeaconStation (tag: beacon_bandit), skipping.
[16.06.2022 18:12:33] Generating an outpost for the end of the level... (Location: Аванпост Gangpo, level type: LocationConnection)
[16.06.2022 18:12:32] Generating an outpost for the start of the level... (Location: Институт астробиологии Ana, level type: LocationConnection)
[16.06.2022 18:12:27] Level identifier: plateaubasic
[16.06.2022 18:12:08] Transitioning to AnaGangpo (current location: Институт астробиологии Ana, selected location: Аванпост Gangpo, leaving sub: R-278 «Dugong» [РУС], at start: True, at end: False, transition type: LeaveLocation)
[16.06.2022 17:51:56] Unlocked mission "Гигантский шипостай" in the location "Институт астробиологии Ana".
[16.06.2022 17:51:50] Unlocked mission "Уничтожить гнездо акульего тигра" in the location "Институт астробиологии Ana".
[16.06.2022 17:51:41] Unlocked mission "Добыча урана" in the location "Институт астробиологии Ana".
[16.06.2022 17:51:35] Unlocked mission "Зачистка руин" in the location "Институт астробиологии Ana".
[16.06.2022 17:37:02] Generating an outpost for the start of the level... (Location: Институт астробиологии Ana, level type: Outpost)
[16.06.2022 17:37:02] Level identifier: outpostlevel
[16.06.2022 17:35:36] Attempting to open ALC device "OpenAL Soft on Динамики (Logitech PRO X Gaming Headset)"
[16.06.2022 17:35:34] Logged in as Alatyr (SteamID STEAM_1:0:31224204)
```

**Comment by Regalis11** [comment]
This seemed to happen when a bot had the AIObjectivePumpWater and there were pumps outside the sub (e.g. a portable pump in someone's inventory). Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/ef3405c0de146a68fb188829ab51f890a036b8cd

Steps to repro:
1. Spawn some pumps in the crew's inventory
2. Start a new round (the available pumps are searched for at the beginning of the round when instantiating AIObjectivePumpWater)
3. Wait a while for the bots to evaluate the objective

**Comment by Rokvach** [comment]
Tested, compared to stable and I wasn't able to cause the crash anymore, working correctly. Can be closed if nothing comes up during review
