### ISSUE TITLE
Game crashes when detaching modded vending machines.

### ISSUE THREAD

**Issue by ghost** [Regalis11/Barotrauma#9375]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Creating a detachable fabricator that acts like a vending machine crashes the game.

### Reproduction steps

1.Copy the vending machine code and make the necessary changes to it to make it work as a new item
2.Add appropriate body and holdable code to the item
3.Try to detach the machine or spawn it as an item ingame

### Bug prevalence

Happens every time I play

### Version

0.18.11.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Exception: Index was outside the bounds of the array. (System.IndexOutOfRangeException)
Target site: Void DrawSlot(Microsoft.Xna.Framework.Graphics.SpriteBatch, Barotrauma.Inventory, Barotrauma.VisualSlot, Barotrauma.Item, Int32, Boolean, Barotrauma.InvSlotType)
Stack trace: 
   at Barotrauma.Inventory.DrawSlot(SpriteBatch spriteBatch, Inventory inventory, VisualSlot slot, Item item, Int32 slotIndex, Boolean drawItem, InvSlotType type) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Inventory.cs:line 0
   at Barotrauma.Inventory.Draw(SpriteBatch spriteBatch, Boolean subInventory) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Inventory.cs:line 825
   at Barotrauma.ItemInventory.Draw(SpriteBatch spriteBatch, Boolean subInventory) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\ItemInventory.cs:line 46
   at Barotrauma.GUICustomComponent.Draw(SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUICustomComponent.cs:line 43
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Barotrauma.GUI.Draw(Camera cam, SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 251
   at Barotrauma.SubEditorScreen.Draw(Double deltaTime, GraphicsDevice graphics, SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\SubEditorScreen.cs:line 5750
   at Barotrauma.GameMain.Draw(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 1003
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 669
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 511
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3918360d4561d16b2b4ee5303d3fd9452e61d40a

**Comment by NilanthAnimosus** [comment]
Tested, working correctly. Closing
