### ISSUE TITLE
MonsterEvent Crash When Spawning null prefabs

### ISSUE THREAD

**Issue by MasonMachineGun** [Regalis11/Barotrauma#9377]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

When a modded creature without a present prefab attempts to spawn with type Wreck or Abyss via the RandomEvents.xml, the game crashes: 

In the previous update, the event would simply not spawn the creatures that are missing, but a crash at this point is disruptive to my event driven creature compatibility mod called BaroTraumatic. This forces users to have all available monster packs, this ruins a core feature of the mod: Customizability.

Could this exception be avoided or converted into a WARN to console perhaps?

I understand that it is not typical that creatures with no prefab shouldn't exist in the vanilla game, but in a heavily modded creature world, people want the ability to have options which has been disrupted.

### Reproduction steps

Load a RandomEvents.xml which has abyss or wreck monsterevents for a creature prefab that doesn't exist.

Trigger event. (Go to abyss)

Crash.

### Bug prevalence

Happens every time I play

### Version

0.18.11.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Object reference not set to an instance of an object. (NullReferenceException)    at Barotrauma.MonsterEvent.<>c.<Update>b__32_1(Character m) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Events\MonsterEvent.cs:line 592
   at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
   at Barotrauma.MonsterEvent.Update(Single deltaTime) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Events\MonsterEvent.cs:line 592
   at Barotrauma.EventManager.Update(Single deltaTime) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Events\EventManager.cs:line 709
   at Barotrauma.GameSession.Update(Single deltaTime) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameSession.cs:line 713
   at Barotrauma.GameScreen.Update(Double deltaTime) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 151
   at Barotrauma.GameMain.Run() in E:\Barotrauma-development\Barotrauma\BarotraumaServer\ServerSource\GameMain.cs:line 324
   at Barotrauma.Program.Main(String[] args) in E:\Barotrauma-development\Barotrauma\BarotraumaServer\ServerSource\Program.cs:line 74

Barotrauma seems to have crashed. Sorry for the inconvenience! 


Game version 0.18.11.0 (ReleaseWindows, branch release, revision 75c2f92d56)
Language: English
Selected content packages: Vanilla, BaroTraumatic Nightmare, Shipwrecks Extended, DynamicEuropa, The Skipjack, R-29-793 Hammerhead - RFR
Level seed: Androgeos LineaAna
Loaded submarine: The Skipjack (98729961DB1E3DC36DC99615269B5D34)
Selected screen: Barotrauma.GameScreen
Server (Round had started)


System info:
    Operating system: Microsoft Windows NT 6.2.9200.0 64 bit


Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Boolean <Update>b__32_1(Barotrauma.Character)
Stack trace: 
   at Barotrauma.MonsterEvent.<>c.<Update>b__32_1(Character m) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\MonsterEvent.cs:line 592
   at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
   at Barotrauma.MonsterEvent.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\MonsterEvent.cs:line 592
   at Barotrauma.EventManager.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\EventManager.cs:line 709
   at Barotrauma.GameSession.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameSession.cs:line 713
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 151
   at Barotrauma.GameMain.Run() in <DEV>\Barotrauma\BarotraumaServer\ServerSource\GameMain.cs:line 324
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Program.cs:line 74


Last debug messages:
   6/16/2022 3:43:22 PM - [6/16/2022 3:43:22 PM]
  Saving banlist
   6/16/2022 3:43:22 PM - Failed to create character "Abyssalhammerhead". Matching prefab not found.
   at System.Environment.get_StackTrace()
   at Barotrauma.Character.Create(Identifier speciesName, Vector2 position, String seed, CharacterInfo characterInfo, UInt16 id, Boolean isRemotePlayer, Boolean hasAi, Boolean createNetworkEvent, RagdollParams ragdoll) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 1047
   at Barotrauma.MonsterEvent.<>c__DisplayClass32_1.<Update>b__4() in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Events\MonsterEvent.cs:line 531
   at Barotrauma.CoroutineManager.DoInvokeAfter(Action action, Single delay)+MoveNext() in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 128
   at Barotrauma.CoroutineManager.PerformCoroutineStep(CoroutineHandle handle) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 196
   at Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 227
   at Barotrauma.CoroutineManager.Update(Single unscaledDeltaTime, Single deltaTime) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 270
   at Barotrauma.GameMain.Run() in E:\Barotrauma-development\Barotrauma\BarotraumaServer\ServerSource\GameMain.cs:line 334
   at Barotrauma.Program.Main(String[] args) in E:\Barotrauma-development\Barotrauma\BarotraumaServer\ServerSource\Program.cs:line 75
   6/16/2022 3:43:22 PM - Failed to create character "Husker". Matching prefab not found.
   at System.Environment.get_StackTrace()
   at Barotrauma.Character.Create(Identifier speciesName, Vector2 position, String seed, CharacterInfo characterInfo, UInt16 id, Boolean isRemotePlayer, Boolean hasAi, Boolean createNetworkEvent, RagdollParams ragdoll) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 1047
   at Barotrauma.MonsterEvent.<>c__DisplayClass32_1.<Update>b__4() in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Events\MonsterEvent.cs:line 531
   at Barotrauma.CoroutineManager.DoInvokeAfter(Action action, Single delay)+MoveNext() in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 128
   at Barotrauma.CoroutineManager.PerformCoroutineStep(CoroutineHandle handle) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 196
   at Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 227
   at Barotrauma.CoroutineManager.Update(Single unscaledDeltaTime, Single deltaTime) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 270
   at Barotrauma.GameMain.Run() in E:\Barotrauma-development\Barotrauma\BarotraumaServer\ServerSource\GameMain.cs:line 334
   at Barotrauma.Program.Main(String[] args) in E:\Barotrauma-development\Barotrauma\BarotraumaServer\ServerSource\Program.cs:line 75
   6/16/2022 3:43:22 PM - Failed to create character "Archimorur". Matching prefab not found.
   at System.Environment.get_StackTrace()
   at Barotrauma.Character.Create(Identifier speciesName, Vector2 position, String seed, CharacterInfo characterInfo, UInt16 id, Boolean isRemotePlayer, Boolean hasAi, Boolean createNetworkEvent, RagdollParams ragdoll) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 1047
   at Barotrauma.MonsterEvent.<>c__DisplayClass32_1.<Update>b__4() in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Events\MonsterEvent.cs:line 531
   at Barotrauma.CoroutineManager.DoInvokeAfter(Action action, Single delay)+MoveNext() in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 128
   at Barotrauma.CoroutineManager.PerformCoroutineStep(CoroutineHandle handle) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 196
   at Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 227
   at Barotrauma.CoroutineManager.Update(Single unscaledDeltaTime, Single deltaTime) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 270
   at Barotrauma.GameMain.Run() in E:\Barotrauma-development\Barotrauma\BarotraumaServer\ServerSource\GameMain.cs:line 334
   at Barotrauma.Program.Main(String[] args) in E:\Barotrauma-development\Barotrauma\BarotraumaServer\ServerSource\Program.cs:line 75
   6/16/2022 3:43:22 PM - Coroutine Barotrauma.CoroutineManager+<DoInvokeAfter>d__5 threw an exception: Object reference not set to an instance of an object.
   at Barotrauma.SwarmBehavior.CreateSwarm(IEnumerable`1 swarm) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\SwarmBehavior.cs:line 39
   at Barotrauma.MonsterEvent.<>c__DisplayClass32_1.<Update>b__4() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\MonsterEvent.cs:line 0
   at Barotrauma.CoroutineManager.DoInvokeAfter(Action action, Single delay)+MoveNext() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 130
   at Barotrauma.CoroutineManager.PerformCoroutineStep(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 197
   at Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 255
   6/16/2022 3:43:22 PM - Failed to create character "Thalamuscarrier". Matching prefab not found.
   at System.Environment.get_StackTrace()
   at Barotrauma.Character.Create(Identifier speciesName, Vector2 position, String seed, CharacterInfo characterInfo, UInt16 id, Boolean isRemotePlayer, Boolean hasAi, Boolean createNetworkEvent, RagdollParams ragdoll) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 1047
   at Barotrauma.MonsterEvent.<>c__DisplayClass32_1.<Update>b__4() in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Events\MonsterEvent.cs:line 531
   at Barotrauma.CoroutineManager.DoInvokeAfter(Action action, Single delay)+MoveNext() in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 128
   at Barotrauma.CoroutineManager.PerformCoroutineStep(CoroutineHandle handle) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 196
   at Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 227
   at Barotrauma.CoroutineManager.Update(Single unscaledDeltaTime, Single deltaTime) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 270
   at Barotrauma.GameMain.Run() in E:\Barotrauma-development\Barotrauma\BarotraumaServer\ServerSource\GameMain.cs:line 334
   at Barotrauma.Program.Main(String[] args) in E:\Barotrauma-development\Barotrauma\BarotraumaServer\ServerSource\Program.cs:line 75
   6/16/2022 3:43:22 PM - Coroutine Barotrauma.CoroutineManager+<DoInvokeAfter>d__5 threw an exception: Object reference not set to an instance of an object.
   at Barotrauma.SwarmBehavior.CreateSwarm(IEnumerable`1 swarm) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AI\SwarmBehavior.cs:line 39
   at Barotrauma.MonsterEvent.<>c__DisplayClass32_1.<Update>b__4() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\MonsterEvent.cs:line 0
   at Barotrauma.CoroutineManager.DoInvokeAfter(Action action, Single delay)+MoveNext() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 130
   at Barotrauma.CoroutineManager.PerformCoroutineStep(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 197
   at Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 255
   6/16/2022 3:43:22 PM - Failed to create character "Voidstalker". Matching prefab not found.
   at System.Environment.get_StackTrace()
   at Barotrauma.Character.Create(Identifier speciesName, Vector2 position, String seed, CharacterInfo characterInfo, UInt16 id, Boolean isRemotePlayer, Boolean hasAi, Boolean createNetworkEvent, RagdollParams ragdoll) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 1047
   at Barotrauma.MonsterEvent.<>c__DisplayClass32_1.<Update>b__4() in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Events\MonsterEvent.cs:line 531
   at Barotrauma.CoroutineManager.DoInvokeAfter(Action action, Single delay)+MoveNext() in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 128
   at Barotrauma.CoroutineManager.PerformCoroutineStep(CoroutineHandle handle) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 196
   at Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 227
   at Barotrauma.CoroutineManager.Update(Single unscaledDeltaTime, Single deltaTime) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 270
   at Barotrauma.GameMain.Run() in E:\Barotrauma-development\Barotrauma\BarotraumaServer\ServerSource\GameMain.cs:line 334
   at Barotrauma.Program.Main(String[] args) in E:\Barotrauma-development\Barotrauma\BarotraumaServer\ServerSource\Program.cs:line 75
   6/16/2022 3:43:22 PM - Failed to create character "Mudbouncer". Matching prefab not found.
   at System.Environment.get_StackTrace()
   at Barotrauma.Character.Create(Identifier speciesName, Vector2 position, String seed, CharacterInfo characterInfo, UInt16 id, Boolean isRemotePlayer, Boolean hasAi, Boolean createNetworkEvent, RagdollParams ragdoll) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 1047
```

**Comment by Regalis11** [comment]
Thank you for the report!

Fixed this in https://github.com/Regalis11/Barotrauma-development/commit/f4ace6e9d9a9bebc4340db8da34b940f1356237d.

By the way, I would recommend looking into "additive event sets" (there's an example in the `transitevents` set in OutpostEvents.xml). These can be used to add events without having to override existing sets: it could be a good idea to define the monster spawns in each mod as separate additive sets so you don't have to define all of them in the base mod.

**Comment by Rokvach** [comment]
Tested, I wasn't able to reproduce the issue, can be closed if nothing is found in review
