### ISSUE TITLE
NOT a duplicate - Crashing randomly EVEN in the Subeditor

### ISSUE THREAD

**Issue by Noxurius** [Regalis11/Barotrauma#9395]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The game crashes randomly even in the Subeditor, I have done EVERY possible solution and yet I still have that issue, I tried the Windows Compatibilty stuff that have done some changes to the game launching (I guess ?) but the game still crashes please help me, I've read through most of the issues here on github and none looks like mine, I know I might be bothering you but please help me I really want to play this game. I also bought for 80$ of external cooling systems so the temperature isn't, imo, the problem.

### Reproduction steps

1. Star a multiplayer OR a Solo Game OR be in the Subeditor
2. After few min the game crashes

### Bug prevalence

Happens every time I play

### Version

0.18.12.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 17/06/2022 19:41:02)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


A382F735B43D8E3FAD0FC906B3E782B4


Game version 0.18.12.0 (ReleaseWindows, branch release, revision 85532fbcbc)
Graphics mode: 1920x1080 (Fullscreen)
VSync ON
Language: English
Selected content packages: Vanilla, Onyx Spear, Onyx Spear, The Spear
Level seed: ApepCilicia Flexus
Loaded submarine: Barsuk (0B42EA2FA372CDE9A3C7823CF17EE788)
Selected screen: Barotrauma.GameScreen
SteamManager initialized


System info:
    Operating system: Microsoft Windows NT 6.0.6002 Service Pack 2 64 bit
    GPU name: NVIDIA GeForce GTX 1050
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1,7777778}
    GPU status: Normal


Exception: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: L’instance de périphérique GPU a été suspendue. Utilisez GetDeviceRemovedReason pour déterminer l’action appropriée.
 (SharpDX.SharpDXException)
Device removed reason: HRESULT = 0x887A0006
Target site: Void CheckError()
Stack trace: 
   at SharpDX.Result.CheckError()
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformPresent() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\GraphicsDevice.DirectX.cs:line 1017
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 511
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59


Last debug messages:
[17/06/2022 19:18:23] Could not find a spawn point for a SpawnAction (spawn location: BeaconStation (tag: beacon_bandit), skipping.
[17/06/2022 19:18:11] Generating an outpost for the start of the level... (Location: Apep Outpost, level type: LocationConnection)
[17/06/2022 19:18:10] Level identifier: coldcavernsadvanced
[17/06/2022 19:17:08] Attempting to open ALC device "OpenAL Soft on Haut-parleur/Ecouteurs (Realtek High Definition Audio)"
[17/06/2022 19:17:05] Logged in as Noxurius (SteamID STEAM_1:0:67774949)


Barotrauma Client crash report (generated on 17/06/2022 19:15:28)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


A382F735B43D8E3FAD0FC906B3E782B4


Game version 0.18.12.0 (ReleaseWindows, branch release, revision 85532fbcbc)
Graphics mode: 1920x1080 (Fullscreen)
VSync ON
Language: English
Selected content packages: Vanilla, Onyx Spear, Onyx Spear, The Spear
Level seed: ApepCilicia Flexus
Loaded submarine: Barsuk (0B42EA2FA372CDE9A3C7823CF17EE788)
Selected screen: Barotrauma.GameScreen
SteamManager initialized


System info:
    Operating system: Microsoft Windows NT 10.0.19043.0 64 bit
    GPU name: NVIDIA GeForce GTX 1050
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1,7777778}
    GPU status: Normal


Exception: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: L’instance de périphérique GPU a été suspendue. Utilisez GetDeviceRemovedReason pour déterminer l’action appropriée.
 (SharpDX.SharpDXException)
Device removed reason: HRESULT = 0x887A0006
Target site: Void CheckError()
Stack trace: 
   at SharpDX.Result.CheckError()
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformPresent() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\GraphicsDevice.DirectX.cs:line 1017
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 511
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59


Last debug messages:
[17/06/2022 19:01:34] Could not find a spawn point for a SpawnAction (spawn location: BeaconStation (tag: beacon_bandit), skipping.
[17/06/2022 19:01:27] Generating an outpost for the start of the level... (Location: Apep Outpost, level type: LocationConnection)
[17/06/2022 19:01:27] Level identifier: coldcavernsadvanced
[17/06/2022 18:41:27] Could not find a spawn point for a SpawnAction (spawn location: BeaconStation (tag: beacon_bandit), skipping.
[17/06/2022 18:41:18] Generating an outpost for the start of the level... (Location: Apep Outpost, level type: LocationConnection)
[17/06/2022 18:41:17] Level identifier: coldcavernsadvanced
[17/06/2022 18:41:06] Transitioning to ApepCilicia Flexus (current location: Apep Outpost, selected location: Cilicia Flexus, leaving sub: Barsuk, at start: True, at end: False, transition type: LeaveLocation)
[17/06/2022 18:37:35] Unlocked mission "Mining pyromorphite" in the location "Apep Outpost".
[17/06/2022 18:37:32] Unlocked mission "Killing Hammerheads" in the location "Apep Outpost".
[17/06/2022 18:37:28] Unlocked mission "Terminate a Swarm" in the location "Apep Outpost".
[17/06/2022 18:36:58] Generating an outpost for the start of the level... (Location: Apep Outpost, level type: Outpost)
[17/06/2022 18:36:58] Level identifier: outpostlevel
[17/06/2022 18:36:46] Transitioning to Apep (current location: Nome Station, selected location: Apep Outpost, leaving sub: Barsuk, at start: False, at end: True, transition type: ProgressToNextLocation)
[17/06/2022 18:24:54] Generating an outpost for the end of the level... (Location: Apep Outpost, level type: LocationConnection)
[17/06/2022 18:24:48] Generating an outpost for the start of the level... (Location: Nome Station, level type: LocationConnection)
[17/06/2022 18:24:48] Level identifier: coldcavernsbasic
[17/06/2022 18:24:27] Transitioning to NomeApep (current location: Nome Station, selected location: Apep Outpost, leaving sub: Barsuk, at start: True, at end: False, transition type: LeaveLocation)
[17/06/2022 18:23:06] Unlocked mission "Terminate a Swarm" in the location "Nome Station".
[17/06/2022 18:23:04] Unlocked mission "Killing Hammerheads" in the location "Nome Station".
[17/06/2022 18:23:02] Unlocked mission "Chemical shipment" in the location "Nome Station".
[17/06/2022 18:22:54] Unlocked mission "Praise the honkmother" in the location "Nome Station".
[17/06/2022 18:21:50] Generating an outpost for the start of the level... (Location: Nome Station, level type: Outpost)
[17/06/2022 18:21:50] Level identifier: outpostlevel
[17/06/2022 18:20:07] Attempting to open ALC device "OpenAL Soft on Haut-parleur/Ecouteurs (Realtek High Definition Audio)"
[17/06/2022 18:20:03] Logged in as Noxurius (SteamID STEAM_1:0:67774949)
```

**Comment by Regalis11** [comment]
I'm sorry we aren't able to give you more help than this, but we simply don't know what's causing this error in your situation. The error can be caused by tons of different reasons, and we have listed some ways that can fix it here: https://github.com/Regalis11/Barotrauma/issues/1833#issuecomment-981557503. To be sure, did you already try all of them and none of them helped?

In any case, there's an existing ticket about this exact same issue: https://github.com/Regalis11/Barotrauma/issues/1833. It's better to keep any relevant info about the issue in that one ticket instead of creating duplicate ones.
