### ISSUE TITLE
Deleting a door occures crash

### ISSUE THREAD

**Issue by CaptainSqrBeard** [Regalis11/Barotrauma#9458]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

If you delete door, then game will crash.

XML that i used
<details>
  <summary>dor.xml</summary>
  
  ```xml
<?xml version="1.0" encoding="utf-8"?>
<Items>
  <Override>
  <Item name="" identifier="doorwbuttons" tags="door" scale="0.5" health="100" requirebodyinsidetrigger="false" damagedbyrepairtools="true" damagedbymonsters="true" damagedbyexplosions="true" explosiondamagemultiplier="0.1" allowrotatingineditor="false" allowedlinks="structure,item" ondamagedthreshold="10" linkable="true">
    <Sprite texture="Content/Items/Door/door.png" sourcerect="0,0,49,416" depth="0.51" origin="0.5,0.5" />
    <DecorativeSprite texture="Content/Items/Door/door2.png" sourcerect="0,0,170,416" depth="0.89" origin="0.5,0.5"/>
    <Door canbeselected="true" canbepicked="true" pickkey="Action" msg="ItemMsgForceOpenCrowbar" PickingTime="10.0" shadowscale="0.7,1" hasintegratedbuttons="true">
      <RequiredItem items="crowbar" type="Equipped" optional="true"/>
      <Requireditem items="idcard" type="Picked" optional="true"/>
      <Sprite texture="Content/Items/Door/door.png" sourcerect="158,0,42,416" depth="0.05" origin="0.5,0.0" />
      <WeldedSprite texture="Content/Items/Door/door.png" sourcerect="203,0,65,377" depth="0.0" origin="0.5,0.5" />
      <BrokenSprite texture="Content/Items/Door/door.png" sourcerect="271,0,121,416" depth="0.509" origin="0.5,0.0" scale="true" />
      <sound file="Content/Items/Door/Door1.ogg" type="OnUse" range="500.0" />
      <sound file="Content/Items/Door/Door2.ogg" type="OnUse" range="500.0" />
      <sound file="Content/Items/Door/Door3.ogg" type="OnUse" range="500.0" />
      <sound file="Content/Items/Door/Door4.ogg" type="OnUse" range="500.0" />
      <sound file="Content/Items/Tools/Crowbar.ogg" type="OnPicked" range="4000.0" onlyinsamesub="true" />
      <sound file="Content/Items/Door/Duct1.ogg" type="OnFailure" selectionmode="Random" range="300" />
      <sound file="Content/Items/Door/Duct2.ogg" type="OnFailure" range="300" />
      <sound file="Content/Items/Door/DoorBreak1.ogg" type="OnBroken" selectionmode="Random" range="3000" />
      <sound file="Content/Items/Door/DoorBreak2.ogg" type="OnBroken" range="3000" />
      <StatusEffect type="OnDamaged" target="This">
        <sound file="Content/Items/Door/DoorBreak1.ogg" selectionmode="Random" range="800" />
        <sound file="Content/Items/Door/DoorBreak2.ogg" range="800" />
        <Remove/>  
      </StatusEffect>
      <!-- StatusEffect that deletes door -->
      <StatusEffect type="InWater" target="This">
        <sound file="Content/Items/Door/DoorBreak2.ogg" range="800" />
        <Remove/>  
      </StatusEffect>
    </Door>
    <trigger x="-60" y="-140" width="170" height="85" />
    <AiTarget sightrange="1500.0" static="True"/>
    <Repairable selectkey="Action" header="mechanicalrepairsheader" fixDurationHighSkill="10" fixDurationLowSkill="25" msg="ItemMsgRepairWrench" hudpriority="10">
      <GuiFrame relativesize="0.2,0.16" minsize="400,180" maxsize="480,280" anchor="Center" relativeoffset="0.0,0.27" style="ItemUI" />
      <RequiredSkill identifier="mechanical" level="40" />
      <RequiredItem items="wrench" type="equipped" />
    </Repairable>
    <ConnectionPanel selectkey="Action" canbeselected="true" msg="ItemMsgRewireScrewdriver" hudpriority="10">
      <GuiFrame relativesize="0.2,0.32" minsize="400,350" maxsize="480,420" anchor="Center" style="ConnectionPanel" />
      <RequiredItem items="screwdriver" type="Equipped" />
      <input name="toggle" displayname="connection.togglestate" />
      <input name="set_state" displayname="connection.setstate" />
      <output name="state_out" displayname="connection.stateout" fallbackdisplayname="connection.signalout"/>
      <output name="condition_out" displayname="connection.conditionout" />
    </ConnectionPanel>
  </Item>
  </Override>
</Items>
  ```
  
</details>

### Reproduction steps

1. Somehow delete a door. In my case i deleted it through adding ``<StatusEffect type="InWater" target="This">`` with ``<Remove/> `` to a door
3. Game crashes when door get deleted

### Bug prevalence

Happens regularly

### Version

0.18.12.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Exception: Value cannot be null. (Parameter 'texture') (System.ArgumentNullException)
Target site: Void CheckValid(Microsoft.Xna.Framework.Graphics.Texture2D)
Stack trace: 
   at Microsoft.Xna.Framework.Graphics.SpriteBatch.CheckValid(Texture2D texture) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\SpriteBatch.cs:line 249
   at Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(Texture2D texture, Vector2 position, Nullable`1 sourceRectangle, Color color, Single rotation, Vector2 origin, Vector2 scale, SpriteEffects effects, Single layerDepth) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\SpriteBatch.cs:line 472
   at Barotrauma.Items.Components.Door.Draw(SpriteBatch spriteBatch, Boolean editing, Single itemDepth) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Components\Door.cs:line 253
   at Barotrauma.Item.Draw(SpriteBatch spriteBatch, Boolean editing, Boolean back) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Item.cs:line 488
   at Barotrauma.Submarine.DrawBack(SpriteBatch spriteBatch, Boolean editing, Predicate`1 predicate) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Map\Submarine.cs:line 222
   at Barotrauma.GameScreen.DrawMap(GraphicsDevice graphics, SpriteBatch spriteBatch, Double deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\GameScreen.cs:line 263
   at Barotrauma.GameScreen.Draw(Double deltaTime, GraphicsDevice graphics, SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\GameScreen.cs:line 128
   at Barotrauma.GameMain.Draw(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 1003
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 669
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 511
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3d4642ab38ab629354405738497c8ca76efda3b3

**Comment by NilanthAnimosus** [comment]
Tested on 0.18.13.0, Does not work as one may expect but does prevent the crashes so it does work.

![image](https://user-images.githubusercontent.com/29177976/176977495-eaa5ed86-6d73-4fcd-a14c-98230e0d045e.png)

Deleting a door via status effects (Such as in water) no longer crashes the game, however it also leaves hulls without a gap between them (As the gap was originally tied to the door, the gap is deleted with the door regardless of it being open or closed at least)

This is probably not a good idea fundamentally in most use cases to make sense to do as a result, as its likely intended for the disappearing door to create a gap and link the hulls, and perhaps "Placing" a new door to remove the now-missing door's new gap if one was to be added as a workaround (Which I don't think you can just status effect in there currently).

Not sure about this behavior.

**Comment by Regalis11** [comment]
I'd consider that a separate issue. If it even is an issue, I think it'd be possible to spawn e.g. an invisible door to replace the original one if that's the desired behavior after the door is removed. It could also not be, depending on the use case - for instance, if I deleted a duct block from between hulls I might expect the flow of water to stop.
