### ISSUE TITLE
Unable to host a server through in-game menu (Pipe is broken)

### ISSUE THREAD

**Issue by CalmMagma** [Regalis11/Barotrauma#9461]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I have been completely unable to host a server at all by using the in-game multiplayer menu. Every time I try, the loading window pops up, loads for a bit, and then I'm just left with this:
![image](https://user-images.githubusercontent.com/100709631/175752145-a0227237-54ea-482f-afa4-557277b2d579.png)

I only played the 5 tutorials thus far, and never modded the game.
I tried verifying integrity of game files, which apparently fixed 2 corrupt files(?). Didn't work.
I tried uninstalling and re-installing. Didn't work.
Verifying integrity again didn't show any issues.

I literally just got the game and I'd really like to start a campaign with friends, but am currently unable to as it seems this has been happening to others in rare cases, with seemingly no cause or solution.

### Bug prevalence

Happens every time I play

### Version

0.18.12.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Dedicated Server crash report (generated on 24/06/2022 21:40:10)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


Game version 0.18.12.0 (ReleaseWindows, branch release, revision 85532fbcbc)
Language: English
Selected content packages: Vanilla
Level seed: no level loaded
Loaded submarine: None
Selected screen: None


System info:
    Operating system: Microsoft Windows NT 6.2.9200.0 64 bit


Exception: readStream was disconnected unexpectedly (System.Exception)
Target site: Void CheckPipeConnected(System.String, System.IO.Pipes.AnonymousPipeClientStream)
Stack trace: 
   at Barotrauma.Networking.ChildServerRelay.CheckPipeConnected(String name, AnonymousPipeClientStream pipe) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\ChildServerRelay.cs:line 153
   at Barotrauma.Networking.ChildServerRelay.UpdateRead() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\ChildServerRelay.cs:line 183
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

-------------------------------------------------------------------------------------------------

Barotrauma Dedicated Server crash report (generated on 24/06/2022 21:40:11)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


Game version 0.18.12.0 (ReleaseWindows, branch release, revision 85532fbcbc)
Language: English
Selected content packages: Vanilla
Level seed: no level loaded
Loaded submarine: None
Selected screen: None


System info:
    Operating system: Microsoft Windows NT 6.2.9200.0 64 bit


Exception: Pipe is broken. (System.IO.IOException)
Target site: Void WriteCore(System.ReadOnlySpan`1[System.Byte])
Stack trace: 
   at System.IO.Pipes.PipeStream.WriteCore(ReadOnlySpan`1 buffer)
   at System.IO.Pipes.PipeStream.Write(ReadOnlySpan`1 buffer)
   at Barotrauma.Networking.ChildServerRelay.<UpdateWrite>g__writeMsg|26_0(WriteStatus writeStatus, <>c__DisplayClass26_0& ) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\ChildServerRelay.cs:line 259
   at Barotrauma.Networking.ChildServerRelay.UpdateWrite() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\ChildServerRelay.cs:line 217
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()



#comment: Yes, one issue generated two servercrashreport.log files.
```

**Comment by Wheatley1001** [comment]
Issue occurred in 100.20.0.0, error log below: 

```
Barotrauma Client crash report (generated on 02/10/2023 16:52:24)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

577D6D5D23149E15A1A617E049B45AF3

Game version 100.20.0.0 (UnstableWindows, branch feature/fullrelease-testing, revision 45ea7d27ae)
Graphics mode: 2560x1440 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla, Fury, LETOHSS, Rex Malleus-Caput, SS HOTEL V.2, STVR, The Honked Mother, Typhon3, RVTS-Class, Sirens Violin, Sailor 4, The Schism, Tadpole Trader, Medusa, [RH] Barrisk Campaign, [RH] Tynler, Sand Tiger submarine, [RH] Herebus Campaign, Black Marlin, patrolman, Hierophant, [RH] Bivot Tier 3 Campaign
Level seed: Gangpo73Gortyna Flexus99
Loaded submarine: Black Marlin (FF63160E8A17C89E17CA797C941F8F92)
Selected screen: Barotrauma.GameScreen
SteamManager initialized
Client (Round had started)

System info:
    Operating system: Microsoft Windows NT 10.0.19045.0 64 bit
    GPU name: NVIDIA GeForce RTX 2070
    Display mode: {Width:2560 Height:1440 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: readStream was disconnected unexpectedly (System.Exception)
Target site: Void CheckPipeConnected(System.String, System.IO.Pipes.AnonymousPipeServerStream)
Stack trace: 
   at Barotrauma.Networking.ChildServerRelay.CheckPipeConnected(String name, AnonymousPipeServerStream pipe) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\ChildServerRelay.cs:line 164
   at Barotrauma.Networking.ChildServerRelay.UpdateRead() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\ChildServerRelay.cs:line 175
   at System.Threading.Thread.StartCallback()

Last debug messages:
[02/10/2023 16:51:04] Jade Harley
[02/10/2023 16:51:04] Rehex
[02/10/2023 16:51:04] Atobá Azul
[02/10/2023 16:51:04] Asriel
[02/10/2023 16:51:04] Edgy
[02/10/2023 16:51:04] fent
[02/10/2023 16:51:04] Gears
[02/10/2023 16:51:04] bananaman
[02/10/2023 16:51:04] Hawkins
[02/10/2023 16:51:04] CaithLoki
[02/10/2023 16:51:04] Vyk
[02/10/2023 16:51:04] Wheatley1001
[02/10/2023 16:51:03] Jade Harley
[02/10/2023 16:51:03] Rehex
[02/10/2023 16:51:03] Atobá Azul
[02/10/2023 16:51:03] Asriel
[02/10/2023 16:51:03] Edgy
[02/10/2023 16:51:03] fent
[02/10/2023 16:51:03] Gears
[02/10/2023 16:51:03] bananaman
[02/10/2023 16:51:03] Hawkins
[02/10/2023 16:51:03] CaithLoki
[02/10/2023 16:51:03] Vyk
[02/10/2023 16:51:03] Wheatley1001
[02/10/2023 16:51:03] Jade Harley
[02/10/2023 16:51:03] Rehex
[02/10/2023 16:51:03] Atobá Azul
[02/10/2023 16:51:03] Asriel
[02/10/2023 16:51:03] Edgy
[02/10/2023 16:51:03] fent
[02/10/2023 16:51:03] Gears
[02/10/2023 16:51:03] bananaman
[02/10/2023 16:51:03] Hawkins
[02/10/2023 16:51:03] CaithLoki
[02/10/2023 16:51:03] Vyk
[02/10/2023 16:51:03] Wheatley1001
[02/10/2023 16:51:03] Jade Harley
[02/10/2023 16:51:03] Rehex
[02/10/2023 16:51:03] Atobá Azul
[02/10/2023 16:51:03] Asriel
[02/10/2023 16:51:03] Edgy
[02/10/2023 16:51:03] fent
[02/10/2023 16:51:03] Gears
[02/10/2023 16:51:03] bananaman
[02/10/2023 16:51:03] Hawkins
[02/10/2023 16:51:03] CaithLoki
[02/10/2023 16:51:03] Vyk
[02/10/2023 16:51:03] Wheatley1001
[02/10/2023 16:51:02] Jade Harley
[02/10/2023 16:51:02] Rehex
[02/10/2023 16:51:02] Atobá Azul
[02/10/2023 16:51:02] Asriel
[02/10/2023 16:51:02] Edgy
[02/10/2023 16:51:02] fent
[02/10/2023 16:51:02] Gears
[02/10/2023 16:51:02] bananaman
[02/10/2023 16:51:02] Hawkins
[02/10/2023 16:51:02] CaithLoki
[02/10/2023 16:51:02] Vyk
[02/10/2023 16:51:02] Wheatley1001
[02/10/2023 16:51:02] Jade Harley
[02/10/2023 16:51:02] Rehex
[02/10/2023 16:51:02] Atobá Azul
[02/10/2023 16:51:02] Asriel
[02/10/2023 16:51:02] Edgy
[02/10/2023 16:51:02] fent
[02/10/2023 16:51:02] Gears
[02/10/2023 16:51:02] bananaman
[02/10/2023 16:51:02] Hawkins
[02/10/2023 16:51:02] CaithLoki
[02/10/2023 16:51:02] Vyk
[02/10/2023 16:51:02] Wheatley1001
[02/10/2023 16:51:01] Jade Harley
[02/10/2023 16:51:01] Rehex
[02/10/2023 16:51:01] Atobá Azul
[02/10/2023 16:51:01] Asriel
[02/10/2023 16:51:01] Edgy
[02/10/2023 16:51:01] fent
[02/10/2023 16:51:01] Gears
[02/10/2023 16:51:01] bananaman
[02/10/2023 16:51:01] Hawkins
[02/10/2023 16:51:01] CaithLoki
[02/10/2023 16:51:01] Vyk
[02/10/2023 16:51:01] Wheatley1001
[02/10/2023 16:51:01] Jade Harley
[02/10/2023 16:51:01] Rehex
[02/10/2023 16:51:01] Atobá Azul
[02/10/2023 16:51:01] Asriel
[02/10/2023 16:51:01] Edgy
[02/10/2023 16:51:01] fent
[02/10/2023 16:51:01] Gears
[02/10/2023 16:51:01] bananaman
[02/10/2023 16:51:01] Hawkins
[02/10/2023 16:51:01] CaithLoki
[02/10/2023 16:51:01] Vyk
[02/10/2023 16:51:01] Wheatley1001
[02/10/2023 16:51:01] Jade Harley
[02/10/2023 16:51:01] Rehex
[02/10/2023 16:51:01] Atobá Azul
[02/10/2023 16:51:01] Asriel
[02/10/2023 16:51:01] Edgy
[02/10/2023 16:51:01] fent
[02/10/2023 16:51:01] Gears
[02/10/2023 16:51:01] bananaman
[02/10/2023 16:51:01] Hawkins
[02/10/2023 16:51:01] CaithLoki
[02/10/2023 16:51:01] Vyk
[02/10/2023 16:51:01] Wheatley1001
[02/10/2023 16:50:57] Jade Harley
[02/10/2023 16:50:57] Rehex
[02/10/2023 16:50:57] Atobá Azul
[02/10/2023 16:50:57] Asriel
[02/10/2023 16:50:57] Edgy
[02/10/2023 16:50:57] fent
[02/10/2023 16:50:56] Gears
[02/10/2023 16:50:56] bananaman
[02/10/2023 16:50:56] Hawkins
[02/10/2023 16:50:56] CaithLoki
[02/10/2023 16:50:56] Vyk
[02/10/2023 16:50:56] Wheatley1001
[02/10/2023 16:50:55] Server running slowly (55 updates/s)!
[02/10/2023 16:50:55] Received STARTGAMEFINALIZE packet. Round init status: Started
[02/10/2023 16:50:54] Received STARTGAMEFINALIZE packet. Round init status: Started
[02/10/2023 16:50:51] Task count: 0
[02/10/2023 16:50:51] Received STARTGAMEFINALIZE packet. Round init status: WaitingForStartGameFinalize
[02/10/2023 16:50:47] Generating an outpost for the end of the level... (Location: Gortyna Flexus Habitation Outpost, level type: LocationConnection)
[02/10/2023 16:50:46] Generating an outpost for the start of the level... (Location: Gangpo Habitation Outpost, level type: LocationConnection)
[02/10/2023 16:50:46] Level identifier: coldcavernstransition
[02/10/2023 16:50:38] Jade Harley
[02/10/2023 16:50:38] Rehex
[02/10/2023 16:50:38] Atobá Azul
[02/10/2023 16:50:38] Asriel
[02/10/2023 16:50:38] Edgy
[02/10/2023 16:50:38] fent
[02/10/2023 16:50:38] Gears
[02/10/2023 16:50:38] bananaman
[02/10/2023 16:50:38] Hawkins
[02/10/2023 16:50:38] CaithLoki
[02/10/2023 16:50:38] Vyk
[02/10/2023 16:50:38] Wheatley1001
[02/10/2023 16:50:38] Jade Harley
[02/10/2023 16:50:38] Rehex
[02/10/2023 16:50:38] Atobá Azul
[02/10/2023 16:50:38] Asriel
[02/10/2023 16:50:38] Edgy
[02/10/2023 16:50:38] fent
[02/10/2023 16:50:38] Gears
[02/10/2023 16:50:38] bananaman
[02/10/2023 16:50:38] Hawkins
[02/10/2023 16:50:38] CaithLoki
[02/10/2023 16:50:38] Vyk
[02/10/2023 16:50:38] Wheatley1001
[02/10/2023 16:50:36] Jade Harley
[02/10/2023 16:50:36] Rehex
[02/10/2023 16:50:36] Atobá Azul
[02/10/2023 16:50:36] Asriel
[02/10/2023 16:50:36] Edgy
[02/10/2023 16:50:36] fent
[02/10/2023 16:50:36] Gears
[02/10/2023 16:50:36] bananaman
[02/10/2023 16:50:36] Hawkins
[02/10/2023 16:50:36] CaithLoki
[02/10/2023 16:50:36] Vyk
[02/10/2023 16:50:36] Wheatley1001
[02/10/2023 16:50:36] Jade Harley
[02/10/2023 16:50:36] Rehex
[02/10/2023 16:50:36] Atobá Azul
[02/10/2023 16:50:36] Asriel
[02/10/2023 16:50:36] Edgy
[02/10/2023 16:50:36] fent
[02/10/2023 16:50:36] Gears
[02/10/2023 16:50:36] bananaman
[02/10/2023 16:50:36] Hawkins
[02/10/2023 16:50:36] CaithLoki
[02/10/2023 16:50:36] Vyk
[02/10/2023 16:50:36] Wheatley1001
[02/10/2023 16:50:36] Jade Harley
[02/10/2023 16:50:36] Rehex
[02/10/2023 16:50:36] Atobá Azul
[02/10/2023 16:50:36] Asriel
[02/10/2023 16:50:36] Edgy
[02/10/2023 16:50:36] fent
[02/10/2023 16:50:36] Gears
[02/10/2023 16:50:36] bananaman
[02/10/2023 16:50:36] Hawkins
[02/10/2023 16:50:36] CaithLoki
[02/10/2023 16:50:36] Vyk
[02/10/2023 16:50:36] Wheatley1001
[02/10/2023 16:50:35] Jade Harley
[02/10/2023 16:50:35] Rehex
[02/10/2023 16:50:35] Atobá Azul
[02/10/2023 16:50:35] Asriel
[02/10/2023 16:50:35] Edgy
[02/10/2023 16:50:35] fent
[02/10/2023 16:50:35] Gears
[02/10/2023 16:50:35] bananaman
[02/10/2023 16:50:35] Hawkins
[02/10/2023 16:50:35] CaithLoki
[02/10/2023 16:50:35] Vyk
[02/10/2023 16:50:35] Wheatley1001
[02/10/2023 16:50:35] Jade Harley
[02/10/2023 16:50:35] Rehex
[02/10/2023 16:50:35] Atobá Azul
[02/10/2023 16:50:35] Asriel
[02/10/2023 16:50:35] Edgy
[02/10/2023 16:50:35] fent
[02/10/2023 16:50:35] Gears
[02/10/2023 16:50:35] bananaman
[02/10/2023 16:50:35] Hawkins
[02/10/2023 16:50:35] CaithLoki
[02/10/2023 16:50:35] Vyk
[02/10/2023 16:50:35] Wheatley1001
[02/10/2023 16:50:35] Jade Harley
[02/10/2023 16:50:35] Rehex
[02/10/2023 16:50:35] Atobá Azul
[02/10/2023 16:50:35] Asriel
[02/10/2023 16:50:35] Edgy
[02/10/2023 16:50:35] fent
[02/10/2023 16:50:35] Gears
[02/10/2023 16:50:35] bananaman
[02/10/2023 16:50:35] Hawkins
[02/10/2023 16:50:35] CaithLoki
[02/10/2023 16:50:35] Vyk
[02/10/2023 16:50:35] Wheatley1001
[02/10/2023 16:50:35] Jade Harley
[02/10/2023 16:50:35] Rehex
[02/10/2023 16:50:35] Atobá Azul
[02/10/2023 16:50:35] Asriel
[02/10/2023 16:50:35] Edgy
[02/10/2023 16:50:35] fent
[02/10/2023 16:50:35] Gears
[02/10/2023 16:50:35] bananaman
[02/10/2023 16:50:35] Hawkins
[02/10/2023 16:50:35] CaithLoki
[02/10/2023 16:50:35] Vyk
[02/10/2023 16:50:35] Wheatley1001
[02/10/2023 16:50:35] Jade Harley
[02/10/2023 16:50:35] Rehex
[02/10/2023 16:50:35] Atobá Azul
[02/10/2023 16:50:35] Asriel
[02/10/2023 16:50:35] Edgy
[02/10/2023 16:50:35] fent
[02/10/2023 16:50:35] Gears
[02/10/2023 16:50:35] bananaman
[02/10/2023 16:50:35] Hawkins
[02/10/2023 16:50:35] CaithLoki
[02/10/2023 16:50:35] Vyk
[02/10/2023 16:50:35] Wheatley1001
[02/10/2023 16:50:35] Server running slowly (57 updates/s)!
[02/10/2023 16:50:35] Jade Harley
[02/10/2023 16:50:35] Rehex
[02/10/2023 16:50:35] Atobá Azul
[02/10/2023 16:50:35] Asriel
[02/10/2023 16:50:35] Edgy
[02/10/2023 16:50:35] fent
[02/10/2023 16:50:35] Gears
[02/10/2023 16:50:35] bananaman
[02/10/2023 16:50:35] Hawkins
[02/10/2023 16:50:35] CaithLoki
[02/10/2023 16:50:35] Vyk
[02/10/2023 16:50:35] Wheatley1001
[02/10/2023 16:50:35] Jade Harley
[02/10/2023 16:50:35] Rehex
[02/10/2023 16:50:35] Atobá Azul
[02/10/2023 16:50:35] Asriel
[02/10/2023 16:50:35] Edgy
[02/10/2023 16:50:35] fent
[02/10/2023 16:50:35] Gears
[02/10/2023 16:50:35] bananaman
[02/10/2023 16:50:35] Hawkins
[02/10/2023 16:50:35] CaithLoki
[02/10/2023 16:50:35] Vyk
[02/10/2023 16:50:35] Wheatley1001
[02/10/2023 16:50:34] Jade Harley
[02/10/2023 16:50:34] Rehex
[02/10/2023 16:50:34] Atobá Azul
[02/10/2023 16:50:34] Asriel
[02/10/2023 16:50:34] Edgy
[02/10/2023 16:50:34] fent
[02/10/2023 16:50:34] Gears
[02/10/2023 16:50:34] bananaman
[02/10/2023 16:50:34] Hawkins
[02/10/2023 16:50:34] CaithLoki
[02/10/2023 16:50:34] Vyk
[02/10/2023 16:50:34] Wheatley1001
[02/10/2023 16:50:34] Jade Harley
[02/10/2023 16:50:34] Rehex
[02/10/2023 16:50:34] Atobá Azul
[02/10/2023 16:50:34] Asriel
[02/10/2023 16:50:34] Edgy
[02/10/2023 16:50:34] fent
[02/10/2023 16:50:34] Gears
[02/10/2023 16:50:34] bananaman
[02/10/2023 16:50:34] Hawkins
[02/10/2023 16:50:34] CaithLoki
[02/10/2023 16:50:34] Vyk
[02/10/2023 16:50:34] Wheatley1001
[02/10/2023 16:38:46] Jade Harley
[02/10/2023 16:38:46] Rehex
[02/10/2023 16:38:46] Atobá Azul

```

**Comment by Regalis11** [comment]
Potentially related to (or the same issue as) https://github.com/Regalis11/Barotrauma/issues/7985.

This seems to indicate the server is failing to start - if there's a server crash report that'd help a lot in diagnosing this (could be that there isn't though, the error message implies the server shut down ungracefully).

Another thing that might help is trying to launch the server in a console window (by launching the server executable directly) and seeing if there's any extra info there.

**Comment by Regalis11** [comment]
No known steps to repro, closing
