### ISSUE TITLE
Attaching a shuttle to outposts/ruins crashes the game

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#9465]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Attaching a shuttle to outposts/ruins crashes the game

### Reproduction steps

Use the mod:
[Ruins Enhanced.zip](https://github.com/Regalis11/Barotrauma/files/8987165/Ruins.Enhanced.zip)

Generate a level with Ruins in it
If it tries generating the Alien_ShuttleEntranceN module the game will crash
_I isolated the module in that mod so it always generates it_

![image](https://user-images.githubusercontent.com/73229309/175827342-c44882bc-a83d-46a9-9b25-8bf508e247c6.png)

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 26-Jun-22 19:15:33)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


A382F735B43D8E3FAD0FC906B3E782B4


Game version 0.18.12.0 (ReleaseWindows, branch release, revision 85532fbcbc)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla, Ruins Enhanced
Level seed: 07QzR6vp
Loaded submarine: None
Selected screen: Barotrauma.LevelEditorScreen
SteamManager initialized


System info:
    Operating system: Microsoft Windows NT 10.0.19043.0 64 bit
    GPU name: NVIDIA GeForce GTX 1060 6GB
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal


Exception: ID 65531 is taken by Barotrauma.Submarine (Ruinsshuttle, 2510) (System.Exception)
Target site: Void .ctor(Barotrauma.Submarine, UInt16)
Stack trace: 
   at Barotrauma.Entity..ctor(Submarine submarine, UInt16 id) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Entity.cs:line 122
   at Barotrauma.Submarine..ctor(SubmarineInfo info, Boolean showWarningMessages, Func`2 loadEntities, IdRemap linkedRemap) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Submarine.cs:line 1304
   at Barotrauma.OutpostGenerator.Generate(OutpostGenerationParams generationParams, LocationType locationType, Location location, Boolean onlyEntrance, Boolean allowInvalidOutpost) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Outposts\OutpostGenerator.cs:line 216
   at Barotrauma.RuinGeneration.Ruin.Generate(Level level, LocationType locationType, Point position, Boolean mirror) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Levels\Ruins\RuinGenerator.cs:line 40
   at Barotrauma.Level.GenerateRuin(Point ruinPos, Boolean mirror) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Levels\Level.cs:line 2015
   at Barotrauma.Level.Generate(Boolean mirror, Location startLocation, Location endLocation) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Levels\Level.cs:line 1097
   at Barotrauma.Level.Generate(LevelData levelData, Boolean mirror, Location startLocation, Location endLocation, SubmarineInfo startOutpost, SubmarineInfo endOutpost) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Levels\Level.cs:line 444
   at Barotrauma.LevelEditorScreen.<.ctor>b__26_12(GUIButton btn, Object obj) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\LevelEditorScreen.cs:line 223
   at Barotrauma.GUIButton.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIButton.cs:line 263
   at Barotrauma.GUI.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1229
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 898
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59


Last debug messages:
[26-Jun-22 19:15:33] Creating hulls between docking ports failed. Could not find a hull next to the docking port.
[26-Jun-22 19:15:26] Level identifier: coldcavernstutorial
[26-Jun-22 19:15:01] leveleditor
[26-Jun-22 19:13:40] Hash calculation for content package "EK | Dockyard" didn't match expected hash (059D749F62C8CCEE88FC5B9101130BD8 != F2DC874DC596C9F056A0326EA8EF077E)
[26-Jun-22 19:13:38] Attempting to open ALC device "OpenAL Soft on Headset Earphone (HyperX 7.1 Audio)"
[26-Jun-22 19:13:37] Logged in as hUbert (SteamID STEAM_1:0:17500415)
```

**Comment by Regalis11** [comment]
Reopening, doesn't seem to be working correctly. The game no longer crashes, but the shuttle doesn't spawn either.

**Comment by ubertpendragon** [comment]
![image](https://user-images.githubusercontent.com/73229309/222226748-4693dea2-f70e-48c5-97eb-ca143120a3a7.png)

![image](https://user-images.githubusercontent.com/73229309/222226695-9fb56c27-9ba7-44fc-be7f-5f1348f3ecde.png)

![image](https://user-images.githubusercontent.com/73229309/222226819-70a803de-1248-46ac-9886-5c06cf01dc9f.png)

**Comment by ubertpendragon** [comment]
The shuttle spawns now.

Problem: 
It shows up on sonar, and in the abyss rather than their docking location
![image](https://user-images.githubusercontent.com/73229309/230602993-598713dd-0127-4853-b4f0-6826d18a9159.png)

**Comment by giists** [comment]
Couldn't find any issues, closing.
