### ISSUE TITLE
Client crashes in startup

### ISSUE THREAD

**Issue by ragnaros12** [Regalis11/Barotrauma#9524]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I wanted to build the game from source, but when I start the game I get this error

Barotrauma Client crash report (generated on 04.07.2022 15:29:59)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

152E290A019067F5963BC4657541F166

Game version 0.18.12.0 (ReleaseWindows, branch master, revision 06e72bb63)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: None
Level seed: no level loaded
Loaded submarine: None
Selected screen: None

System info:
    Operating system: Microsoft Windows NT 10.0.22000.0 64 bit
    GPU name: NVIDIA GeForce RTX 2060
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1,7777778}
    GPU status: Normal

Exception: Could not find file 'C:\Users\khlop\source\repos\Barotrauma\Barotrauma\bin\ReleaseWindows\netcoreapp3.1\Content\Effects\waterbump.png'. (System.IO.FileNotFoundException)
Target site: Microsoft.Win32.SafeHandles.SafeFileHandle ValidateFileHandle(Microsoft.Win32.SafeHandles.SafeFileHandle)
Stack trace: 
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.Open(String path, FileMode mode, FileAccess access, FileShare share)
   at Barotrauma.IO.File.Open(String path, FileMode mode, FileAccess access, Nullable`1 share) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SafeIO.cs:line 383
   at Barotrauma.IO.File.OpenRead(String path) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SafeIO.cs:line 388
   at Barotrauma.TextureLoader.FromFile(String path, Boolean compress, Boolean mipmap) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Utils\TextureLoader.cs:line 193
   at Barotrauma.WaterRenderer..ctor(GraphicsDevice graphicsDevice, ContentManager content) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Map\Levels\WaterRenderer.cs:line 78
   at Barotrauma.GameMain.LoadContent() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 404
   at Microsoft.Xna.Framework.Game.Initialize() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 553
   at Barotrauma.GameMain.Initialize() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 375
   at Microsoft.Xna.Framework.Game.DoInitialize() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 685
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 382
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59

Last debug messages:
[04.07.2022 15:29:58] SteamManager initialization threw an exception {SteamApi_Init returned false. Steam isn't running, couldn't find Steam, AppId is ureleased, Don't own AppId.}
   at Steamworks.SteamClient.Init(UInt32 appid, Boolean asyncCallbacks) in <DEV>\Libraries\Facepunch.Steamworks\SteamClient.cs:line 31
   at Barotrauma.Steam.SteamManager.InitializeProjectSpecific() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Steam\SteamManager.cs:line 26

### Reproduction steps

Запустить игру

### Bug prevalence

Happens every time I play

### Version

0.18.12.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 04.07.2022 15:29:59)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


152E290A019067F5963BC4657541F166


Game version 0.18.12.0 (ReleaseWindows, branch master, revision 06e72bb63)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: None
Level seed: no level loaded
Loaded submarine: None
Selected screen: None


System info:
    Operating system: Microsoft Windows NT 10.0.22000.0 64 bit
    GPU name: NVIDIA GeForce RTX 2060
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1,7777778}
    GPU status: Normal


Exception: Could not find file 'C:\Users\khlop\source\repos\Barotrauma\Barotrauma\bin\ReleaseWindows\netcoreapp3.1\Content\Effects\waterbump.png'. (System.IO.FileNotFoundException)
Target site: Microsoft.Win32.SafeHandles.SafeFileHandle ValidateFileHandle(Microsoft.Win32.SafeHandles.SafeFileHandle)
Stack trace: 
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.Open(String path, FileMode mode, FileAccess access, FileShare share)
   at Barotrauma.IO.File.Open(String path, FileMode mode, FileAccess access, Nullable`1 share) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SafeIO.cs:line 383
   at Barotrauma.IO.File.OpenRead(String path) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SafeIO.cs:line 388
   at Barotrauma.TextureLoader.FromFile(String path, Boolean compress, Boolean mipmap) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Utils\TextureLoader.cs:line 193
   at Barotrauma.WaterRenderer..ctor(GraphicsDevice graphicsDevice, ContentManager content) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Map\Levels\WaterRenderer.cs:line 78
   at Barotrauma.GameMain.LoadContent() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 404
   at Microsoft.Xna.Framework.Game.Initialize() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 553
   at Barotrauma.GameMain.Initialize() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 375
   at Microsoft.Xna.Framework.Game.DoInitialize() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 685
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 382
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59


Last debug messages:
[04.07.2022 15:29:58] SteamManager initialization threw an exception {SteamApi_Init returned false. Steam isn't running, couldn't find Steam, AppId is ureleased, Don't own AppId.}
   at Steamworks.SteamClient.Init(UInt32 appid, Boolean asyncCallbacks) in <DEV>\Libraries\Facepunch.Steamworks\SteamClient.cs:line 31
   at Barotrauma.Steam.SteamManager.InitializeProjectSpecific() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Steam\SteamManager.cs:line 26
```

**Comment by Regalis11** [comment]
Since this isn't an issue in the game itself, I think the[ "modding support" section in Discussions](https://github.com/Regalis11/Barotrauma/discussions/categories/code-questions-and-modding-support) would be a more appropriate place for this. Based on the error message, the game fails to find the texture "Content\Effects\waterbump.png". Have you copied the content folder into the project? As mentioned [here](https://github.com/Regalis11/Barotrauma/blob/master/CONTRIBUTING.md), it's not included in the public repository.
