### ISSUE TITLE
Crash while starting the game

### ISSUE THREAD

**Issue by Fah-maker** [Regalis11/Barotrauma#9547]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

While I was opening the game, it crashed, I've searched and haven't found anything that helps

### Bug prevalence

Happens every time I play

### Version

Other

### -

0.17.15.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 08/07/2022 23:02:43)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


095A39E9025803C60F024FFA1049DA7B


Game version 0.17.15.0 (ReleaseWindows, branch release, revision 62bb4ecab3)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: None
Level seed: no level loaded
Loaded submarine: None
Selected screen: None
SteamManager initialized


System info:
    Operating system: Microsoft Windows NT 10.0.19043.0 64 bit
    GPU name: Intel(R) 82945G Express Chipset Family (Microsoft Corporation - WDDM 1.0)
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1,7777778}
    GPU status: Normal


Exception: HRESULT: [0x8007000E], Module: [General], ApiCode: [E_OUTOFMEMORY/Out of memory], Message: Recursos de memória insuficientes disponíveis para concluir a operação.
 (SharpDX.SharpDXException)
Target site: Void CheckError()
Stack trace: 
   at SharpDX.Result.CheckError()
   at SharpDX.Direct3D11.Device.CreateTexture2D(Texture2DDescription& descRef, DataBox[] initialDataRef, Texture2D texture2DOut)
   at SharpDX.Direct3D11.Texture2D..ctor(Device device, Texture2DDescription description)
   at Microsoft.Xna.Framework.Graphics.Texture2D.CreateTexture() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\Texture2D.DirectX.cs:line 415
   at Microsoft.Xna.Framework.Graphics.Texture.GetTexture() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\Texture.DirectX.cs:line 33
   at Microsoft.Xna.Framework.Graphics.Texture2D.PlatformSetData[T](Int32 level, T[] data, Int32 startIndex, Int32 elementCount) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\Texture2D.DirectX.cs:line 76
   at Microsoft.Xna.Framework.Graphics.Texture2D.SetData[T](T[] data) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\Texture2D.cs:line 205
   at Barotrauma.TextureLoader.<>c__DisplayClass10_0.<FromStream>b__0() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Utils\TextureLoader.cs:line 228
   at Barotrauma.CrossThread.RequestExecutionOnMainThread(TaskDelegate deleg) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\CrossThread.cs:line 61
   at Barotrauma.TextureLoader.FromStream(Stream stream, String path, Boolean compress, Boolean mipmap) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Utils\TextureLoader.cs:line 229
   at Barotrauma.TextureLoader.FromFile(String path, Boolean compress, Boolean mipmap) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Utils\TextureLoader.cs:line 195
   at Barotrauma.LoadingScreen..ctor(GraphicsDevice graphics) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\LoadingScreen.cs:line 115
   at Barotrauma.GameMain.LoadContent() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 401
   at Microsoft.Xna.Framework.Game.Initialize() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 553
   at Barotrauma.GameMain.Initialize() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 367
   at Microsoft.Xna.Framework.Game.DoInitialize() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 685
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 382
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59


Last debug messages:
[08/07/2022 23:02:41] Logged in as Kindelícia
```

**Comment by Regalis11** [comment]
Thank you for the report!

The error message seems to indicate that you ran out of GPU memory. The reported GPU (Intel 82945G) is a low-end integrated GPU that unfortunately doesn't meet the game's minimum hardware requirements.
