### ISSUE TITLE
Crashed on the start up

### ISSUE THREAD

**Issue by ellennnnlin** [Regalis11/Barotrauma#9581]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The game crashed when I started

### Bug prevalence

Happens every time I play

### Version

0.18.12.0

### Which operating system did you encounter this bug on?

MacOS

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 7/16/2022 11:27:04 PM)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


FB928C2924CE5C80A43AF226086DA515


Game version 0.18.15.0 (ReleaseMac, branch release, revision a7b22109e9)
Graphics mode: 1680x1050 (BorderlessWindowed)
VSync ON
Language: Traditional Chinese
Selected content packages: Vanilla
Level seed: SeosuDolgovskoy
Loaded submarine: Azimuth (1B313D86D150030F4439C9AC694AF53F)
Selected screen: Barotrauma.GameScreen
SteamManager initialized
Client (Round had started)


System info:
    Operating system: Unix 21.5.0.0 64 bit
    GPU name: 
    Display mode: {Width:1680 Height:1050 Format:Color AspectRatio:1.6}
    GPU status: Normal


Exception: Failed to set regular buffer data for non-streamed audio! Invalid operation (System.Exception)
Target site: Void FillBuffers()
Stack trace: 
   at Barotrauma.Sounds.OggSound.FillBuffers() in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Sounds/OggSound.cs:line 108
   at Barotrauma.Sounds.SoundChannel..ctor(Sound sound, Single gain, Nullable`1 position, Single freqMult, Single near, Single far, String category, Boolean muffle) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Sounds/SoundChannel.cs:line 88
   at Barotrauma.Sounds.Sound.Play(Nullable`1 position, Single gain, Single freqMult, Boolean muffle) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Sounds/Sound.cs:line 99
   at Barotrauma.Items.Components.ItemComponent.PlaySound(ItemSound itemSound, Vector2 position) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Items/Components/ItemComponent.cs:line 380
   at Barotrauma.Items.Components.ItemComponent.PlaySound(ActionType type, Character user) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Items/Components/ItemComponent.cs:line 339
   at Barotrauma.Item.Update(Single deltaTime, Camera cam) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Items/Item.cs:line 1856
   at Barotrauma.MapEntity.UpdateAll(Single deltaTime, Camera cam) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Map/MapEntity.cs:line 608
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Screens/GameScreen.cs:line 258
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/GameMain.cs:line 874
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/SDL/SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>/Libraries/MonoGame.Framework/Src/MonoGame.Framework/Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>/Barotrauma/BarotraumaClient/ClientSource/Program.cs:line 59


Last debug messages:
[7/16/2022 11:27:02 PM] Received STARTGAMEFINALIZE packet. Round init status: Started
[7/16/2022 11:27:01 PM] Task count: 0
[7/16/2022 11:27:01 PM] Received STARTGAMEFINALIZE packet. Round init status: WaitingForStartGameFinalize
[7/16/2022 11:26:53 PM] Generating an outpost for the end of the level... (Location: Dolgovskoy居住前哨站, level type: LocationConnection)
[7/16/2022 11:26:50 PM] Generating an outpost for the start of the level... (Location: Seosu前哨站, level type: LocationConnection)
[7/16/2022 11:26:48 PM] Level identifier: coldcavernsbasic
[7/16/2022 11:26:38 PM] 宅魚
[7/16/2022 11:26:38 PM] Anna
[7/16/2022 11:26:38 PM] Stevent
[7/16/2022 11:26:37 PM] 宅魚
[7/16/2022 11:26:37 PM] Anna
[7/16/2022 11:26:37 PM] Stevent
[7/16/2022 11:26:37 PM] 宅魚
[7/16/2022 11:26:37 PM] Anna
[7/16/2022 11:26:37 PM] Stevent
[7/16/2022 11:25:53 PM] 宅魚
[7/16/2022 11:25:53 PM] Anna
[7/16/2022 11:25:53 PM] Stevent
[7/16/2022 11:20:59 PM] Anna
[7/16/2022 11:20:59 PM] Stevent
[7/16/2022 11:20:54 PM] Received STARTGAMEFINALIZE packet. Round init status: Started
[7/16/2022 11:20:53 PM] Task count: 0
[7/16/2022 11:20:44 PM] Generating an outpost for the start of the level... (Location: Seosu前哨站, level type: Outpost)
[7/16/2022 11:20:43 PM] Level identifier: outpostlevel
[7/16/2022 11:20:03 PM] LobbyMatchList:  LobbiesMatching: 0
[7/16/2022 11:20:03 PM] LobbyMatchList:  LobbiesMatching: 0
[7/16/2022 11:20:03 PM] SteamAPICallCompleted:   AsyncCall: 6382161442796236730
   Callback: 510
 ParamCount: 4
[7/16/2022 11:20:02 PM] LobbyMatchList:  LobbiesMatching: 30
[7/16/2022 11:20:02 PM] LobbyMatchList:  LobbiesMatching: 30
[7/16/2022 11:20:02 PM] SteamAPICallCompleted:   AsyncCall: 12534469874506459486
   Callback: 510
 ParamCount: 4
[7/16/2022 11:20:02 PM] LobbyMatchList:  LobbiesMatching: 49
[7/16/2022 11:20:02 PM] LobbyMatchList:  LobbiesMatching: 49
[7/16/2022 11:20:02 PM] SteamAPICallCompleted:   AsyncCall: 12547273408267536767
   Callback: 510
 ParamCount: 4
[7/16/2022 11:20:02 PM] LobbyMatchList:  LobbiesMatching: 50
[7/16/2022 11:20:02 PM] LobbyMatchList:  LobbiesMatching: 50
[7/16/2022 11:20:02 PM] SteamAPICallCompleted:   AsyncCall: 10521262258789498528
   Callback: 510
 ParamCount: 4
[7/16/2022 11:20:02 PM] LobbyDataUpdate:   SteamIDLobby: 109775244830356074
 SteamIDMember: 109775244830356074
       Success: 1
[7/16/2022 11:20:01 PM] LobbyMatchList:  LobbiesMatching: 50
[7/16/2022 11:20:01 PM] LobbyMatchList:  LobbiesMatching: 50
[7/16/2022 11:20:01 PM] SteamAPICallCompleted:   AsyncCall: 7823643789434084960
   Callback: 510
 ParamCount: 4
[7/16/2022 11:19:29 PM] WARNING: 400 buffer(s) were generated. No more sound buffers will be generated.
[7/16/2022 11:18:57 PM] Attempting to open ALC device "Built-in Output"
[7/16/2022 11:18:52 PM] Logged in as 宅魚 (SteamID STEAM_1:1:212677176)
```

**Comment by Regalis11** [comment]
Thank you for the report!

The error message seems to indicate that this is some kind of an audio issue. It also seems to indicate the crash was caused by an item, so I guess by "start up" you mean the round starting, not that it happens when the game itself launches? Does the issue occur every time you start a round?

**Comment by ellennnnlin** [comment]
Hi Joonas

Thanks for the reply and sorry about the confusion. It should be a round
start, not the launch of the game
Yes, the issue occurs every time when I start a round in multiplayer mode.

Hope it's more clear.

Best,

Joonas Rikkonen ***@***.***> 於 2022年7月19日 週二 下午5:17寫道：
