### ISSUE TITLE
Vitality reductions are displayed incorrectly in the health interface

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#9594]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Certain limbs have modifiers which make afflictions on them cause a larger/smaller vitality drop. E.g. a gunshot wound to the head drops the vitality by x2 more than elsewhere in the body. These modifiers aren't taken into account in the readings in the health interface though, making it misleading (which based on some conversations on Discord seems to have lead to a lot of misconceptions and confusion about the health system).

### Reproduction steps

1. `giveaffliction gunshotwound 15 [character] Head`
2. `giveaffliction gunshotwound 15 [character] LeftLeg`
3. Notice that the vitality reading on the affliction tooltip is 15 on both afflictions in the health interface, even though it should be 7 on the one on the left leg and 30 on the head
![image](https://user-images.githubusercontent.com/14351070/179534348-49d00104-b3bc-4f2a-8ada-9a5b35f83785.png)

### Bug prevalence

Happens every time I play

### Version

0.18.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/9a1c547f0215befce7ea9d9c3adfdd30c20fccb9

**Comment by Rokvach** [comment]
The above provided repro steps didn't cause a crash

But I crashed when I shot a bot couple times and then inspected their health by selecting torso on the health interface
![image](https://user-images.githubusercontent.com/7299826/184809419-9aba9160-23fb-40c9-bddb-9b9ebe6a04c0.png)


```
Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Single GetVitalityMultiplier(Barotrauma.Affliction, LimbHealth)
Stack trace: 
   at Barotrauma.CharacterHealth.GetVitalityMultiplier(Affliction affliction, LimbHealth limbHealth) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Health\CharacterHealth.cs:line 922
   at Barotrauma.CharacterHealth.GetVitalityDecreaseWithVitalityMultipliers(Affliction affliction) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Health\CharacterHealth.cs:line 935
   at Barotrauma.CharacterHealth.UpdateAfflictionInfos(IEnumerable`1 afflictions) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Characters\Health\CharacterHealth.cs:line 1508
   at Barotrauma.CharacterHealth.UpdateHUD(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Characters\Health\CharacterHealth.cs:line 815
   at Barotrauma.Character.UpdateProjSpecific(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Characters\Character.cs:line 723
   at Barotrauma.Character.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 2778
   at Barotrauma.AICharacter.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AICharacter.cs:line 72
   at Barotrauma.Character.UpdateAll(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 2772
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 190
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 874
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/73eacb8c8234c9360f74a4f7961e52487b5b8515

**Comment by Rokvach** [comment]
Tested, I wasn't able to reproduce the above crash anymore and didn't notice any other issue as well, can be merged.
