### ISSUE TITLE
Exception: The given key '' was not present in the dictionary.

### ISSUE THREAD

**Issue by SunnyFreedoms** [Regalis11/Barotrauma#9670]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Once following through hydrothermal wastes, arriving at an abandoned station with a save file with jovian radiation enabled, over and over. Throwing out the following error: 

Exception: The given key '' was not present in the dictionary. (System.Collections.Generic.KeyNotFoundException)
Target site: Void ThrowKeyNotFoundException(System.Object)
Now as the files number states I've done a bit of testing on my end to see if mods were involved in the crash, and it looks like even by rolling back to vanilla with zero mods on, verifying files and resubbing to said mods does not seem to work, potentially capable of soft locking a run if a station just happens to spawn in the linea leading to the end of the game. Now to clarify I've used mods in this save previously, only reason I've ticked it off is because of it happening with the vanilla pack. Rolling back to a previous save seems to work with both vanilla and modded packs, as in it loads everything no problem. So now I'm working towards seeing if a completely vanilla run could trigger this.

But I've really no clue what to do here other than wait for a response if this could be fix'd. Thanks in advance folks

[crashreport (4).log](https://github.com/Regalis11/Barotrauma/files/9237493/crashreport.4.log)

### Reproduction steps

1. load up a save
2. Go towards any linea that follows up to an abandoned station inside the hydrothermal wastes biome.
3. Go to said cavern that leads to the abandoned station line in the map.
4. Crash, the cavern doesn't even load.

### Bug prevalence

Happens regularly

### Version

0.18.15.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

oroutine Barotrauma.SinglePlayerCampaign+<DoLoadInitialLevel>d__16 threw an exception: The given key '' was not present in the dictionary.
   at System.Collections.Concurrent.ConcurrentDictionary`2.ThrowKeyNotFoundException(Object key)
   at System.Collections.Concurrent.ConcurrentDictionary`2.get_Item(TKey key)
   at Barotrauma.PrefabCollection`1.get_Item(Identifier identifier) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Prefabs\PrefabCollection.cs:line 229
   at Barotrauma.PrefabCollection`1.get_Item(String identifier) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Prefabs\PrefabCollection.cs:line 241
   at Barotrauma.Location.GetLocationType() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Map\Location.cs:line 909
   at Barotrauma.OutpostGenerator.Generate(OutpostGenerationParams generationParams, LocationType locationType, Location location, Boolean onlyEntrance, Boolean allowInvalidOutpost) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Outposts\OutpostGenerator.cs:line 85
   at Barotrauma.Level.CreateOutposts() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Levels\Level.cs:line 3900
   at Barotrauma.Level.Generate(Boolean mirror, Location startLocation, Location endLocation) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Levels\Level.cs:line 1275
   at Barotrauma.Level.Generate(LevelData levelData, Boolean mirror, Location startLocation, Location endLocation, SubmarineInfo startOutpost, SubmarineInfo endOutpost) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Levels\Level.cs:line 444
   at Barotrauma.GameSession.StartRound(LevelData levelData, Boolean mirrorLevel, SubmarineInfo startOutpost, SubmarineInfo endOutpost) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameSession.cs:line 425
   at Barotrauma.SinglePlayerCampaign.DoLoadInitialLevel(LevelData level, Boolean mirror)+MoveNext() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameSession\GameModes\SinglePlayerCampaign.cs:line 240
   at Barotrauma.CoroutineManager.PerformCoroutineStep(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 197
   at Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\CoroutineManager.cs:line 255

**Comment by NilanthAnimosus** [comment]
Thank you for the report!

I've noticed you have a good number of mods active in your crash report (including LUA for barotrauma which modifies the game code) yet did not check the box for mods, does this also occur in vanilla?

he bug appears to be related to getting a location type, and its possible one of your mods adds or changes location types in some form (and the outposts)? for instance barotraumatic claims to add biomes.

if you could create a modlist (So I can make sure I have the correct mods) from the mods settings menu, as well as perhaps the campaign save file if you still have it this could be looked into far faster.

**Comment by esirprus** [comment]
I've had this error before, but it's a little less severe than this one, he simply prevented me from joining the game in progress "The given key 'xxx' was not present in the dictionary......."
"xxx" should be outpost rescue, can't quite remember. If this happens, just quit lobby, then enable the mods enabled on the server and join again. I think this information may be useful (I have 2000h of game experience, most are on mods campaign)

**Comment by Regalis11** [comment]
Potentially addressed in https://github.com/Regalis11/Barotrauma-development/commit/2587bcbbf542e1f4e4741e2f1e821c4986c3bb2b. @thesteveirwin created [another report](https://github.com/Regalis11/Barotrauma/issues/10066) about this today; let's keep this ticket open for a while longer in case they or someone else can provide us with a save we could use to diagnose this, or information on which mods were in use when this occurred.

**Comment by Rokvach** [comment]
Tested by changing the replaceinradiation value on locationTypes.xml file to something which doesn't exist, only received error "Error when trying to get a new location type for an irradiated location - location type "" not found." and the game didn't crash. Working correctly, closing.
