### ISSUE TITLE
clownrelations1 crash

### ISSUE THREAD

**Issue by ConnorsSilverpaws** [Regalis11/Barotrauma#9686]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Station event clownrelations1 (clown toolbox/storage container) causes a crash to desktop with errorlog in single player, crash to server browser in multiplayer. This occurs when clicking the first option in the first stage of the event to "Inspect", where the second stage continues to appear even if you've been crashed from the multiplayer server. 

### Reproduction steps

1. Play campaign
2. Be at a station
3. Have/trigger event clownrelations1
4. Press E on event storage container to begin event
5. Click "Inspect"
6. Crash

### Bug prevalence

Happens every time I play

### Version

Other

### -

0.19.0.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 8/7/2022 11:51:14 PM)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


5B743FA9A748D6BD3CDD24AF87E83BC6


Game version 0.19.0.0 (UnstableWindows, branch dev, revision db44110378)
Graphics mode: 2560x1600 (Windowed)
VSync ON
Language: English
Selected content packages: Vanilla, Humpback Debug, CSS Thalia, CSS Thalia AA, CSS WarpDrive
Level seed: Attis
Loaded submarine: Dugong (78E2F25DC5F3E8681B6DD389B85B0133)
Selected screen: Barotrauma.GameScreen
SteamManager initialized


System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit
    GPU name: NVIDIA GeForce GTX 1070
    Display mode: {Width:3840 Height:2160 Format:Color AspectRatio:1.7777778}
    GPU status: Normal


Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void SetBackgroundIcon(Barotrauma.Sprite)
Stack trace: 
   at Barotrauma.GUIMessageBox.SetBackgroundIcon(Sprite icon) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIMessageBox.cs:line 487
   at Barotrauma.ConversationAction.CreateDialog(String text, Character speaker, IEnumerable`1 options, Int32[] closingOptions, String spriteIdentifier, ConversationAction actionInstance, Nullable`1 actionId, Boolean fadeToBlack, DialogTypes dialogType, Boolean continueConversation) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Events\EventActions\ConversationAction.cs:line 117
   at Barotrauma.ConversationAction.ShowDialog(Character speaker, Character targetCharacter) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Events\EventActions\ConversationAction.cs:line 45
   at Barotrauma.ConversationAction.TryStartConversation(Character speaker, Character targetCharacter) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\EventActions\ConversationAction.cs:line 374
   at Barotrauma.ConversationAction.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\EventActions\ConversationAction.cs:line 210
   at Barotrauma.ConversationAction.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\EventActions\ConversationAction.cs:line 210
   at Barotrauma.ScriptedEvent.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\ScriptedEvent.cs:line 216
   at Barotrauma.EventManager.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\EventManager.cs:line 733
   at Barotrauma.GameSession.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameSession.cs:line 713
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 150
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 874
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58


Last debug messages:
[8/7/2022 11:51:01 PM] Initialized event clownrelations1
[8/7/2022 11:51:01 PM] triggerevent clownrelations1
[8/7/2022 11:50:49 PM] Generating an outpost for the start of the level... (Location: Attis Outpost, level type: Outpost)
[8/7/2022 11:50:49 PM] Level identifier: outpostlevel
[8/7/2022 11:46:57 PM] Line of sight effect disabled
[8/7/2022 11:46:57 PM] los
[8/7/2022 11:46:55 PM] Initialized event clownrelations1
[8/7/2022 11:46:55 PM] triggerevent clownrelations1
[8/7/2022 11:46:35 PM] Generating an outpost for the start of the level... (Location: Attis Outpost, level type: Outpost)
[8/7/2022 11:46:35 PM] Level identifier: outpostlevel
[8/7/2022 11:45:12 PM] LobbyMatchList:  LobbiesMatching: 0
[8/7/2022 11:45:12 PM] LobbyMatchList:  LobbiesMatching: 0
[8/7/2022 11:45:12 PM] SteamAPICallCompleted:   AsyncCall: 3976407510796709621
   Callback: 510
 ParamCount: 4
[8/7/2022 11:45:12 PM] LobbyMatchList:  LobbiesMatching: 40
[8/7/2022 11:45:12 PM] LobbyMatchList:  LobbiesMatching: 40
[8/7/2022 11:45:12 PM] SteamAPICallCompleted:   AsyncCall: 12224255069592478628
   Callback: 510
 ParamCount: 4
[8/7/2022 11:45:11 PM] LobbyMatchList:  LobbiesMatching: 50
[8/7/2022 11:45:11 PM] LobbyMatchList:  LobbiesMatching: 50
[8/7/2022 11:45:11 PM] SteamAPICallCompleted:   AsyncCall: 7884662540265982803
   Callback: 510
 ParamCount: 4
[8/7/2022 11:45:11 PM] LobbyMatchList:  LobbiesMatching: 49
[8/7/2022 11:45:11 PM] LobbyMatchList:  LobbiesMatching: 49
[8/7/2022 11:45:11 PM] SteamAPICallCompleted:   AsyncCall: 5573411759458607883
   Callback: 510
 ParamCount: 4
[8/7/2022 11:45:11 PM] PersonaStateChange:      SteamID: 76561197984598532
 ChangeFlags: 2
[8/7/2022 11:45:11 PM] PersonaStateChange:      SteamID: 76561197984598532
 ChangeFlags: 16384
[8/7/2022 11:45:11 PM] FriendRichPresenceUpdate:  SteamIDFriend: 76561197984598532
         AppID: 602960
[8/7/2022 11:45:10 PM] LobbyMatchList:  LobbiesMatching: 49
[8/7/2022 11:45:10 PM] LobbyMatchList:  LobbiesMatching: 49
[8/7/2022 11:45:10 PM] SteamAPICallCompleted:   AsyncCall: 11812289610910284348
   Callback: 510
 ParamCount: 4
[8/7/2022 11:45:10 PM] PersonaStateChange:      SteamID: 76561197984598532
 ChangeFlags: 16416
[8/7/2022 11:45:10 PM] FriendRichPresenceUpdate:  SteamIDFriend: 76561197984598532
         AppID: 602960
[8/7/2022 11:45:10 PM] AvatarImageLoaded:    SteamID: 76561198012411028
     Image: 1412
      Wide: 184
      Tall: 184
[8/7/2022 11:45:10 PM] WARNING: Tried to restore enabled packages multiple times/without performing a backup
[8/7/2022 11:45:10 PM] Error while reading a message from server. {Object reference not set to an instance of an object.}
   at Barotrauma.GUIMessageBox.SetBackgroundIcon(Sprite icon) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIMessageBox.cs:line 474
   at Barotrauma.ConversationAction.CreateDialog(String text, Character speaker, IEnumerable`1 options, Int32[] closingOptions, String spriteIdentifier, ConversationAction actionInstance, Nullable`1 actionId, Boolean fadeToBlack, DialogTypes dialogType, Boolean continueConversation) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Events\EventActions\ConversationAction.cs:line 91
   at Barotrauma.EventManager.ClientRead(IReadMessage msg) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Events\EventManager.cs:line 644
   at Barotrauma.Networking.GameClient.ReadDataMessage(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 989
   at Barotrauma.Networking.SteamP2POwnerPeer.HandleDataMessage(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\Primitives\Peers\SteamP2POwnerPeer.cs:line 0
   at Barotrauma.Networking.SteamP2POwnerPeer.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\Primitives\Peers\SteamP2POwnerPeer.cs:line 235
   at Barotrauma.Networking.GameClient.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 634
[8/7/2022 11:44:50 PM] Line of sight effect disabled
[8/7/2022 11:44:50 PM] los
[8/7/2022 11:44:44 PM] Server command: triggerevent clownrelations1
[8/7/2022 11:44:44 PM] triggerevent clownrelations1
[8/7/2022 11:44:34 PM] Server command: enablecheats
[8/7/2022 11:44:34 PM] enablecheats
[8/7/2022 11:44:30 PM] Server running slowly (57 updates/s)!
[8/7/2022 11:44:30 PM] lepiromano
[8/7/2022 11:44:27 PM] Received STARTGAMEFINALIZE packet. Round init status: Started
[8/7/2022 11:44:27 PM]  -1: WaitForPingDataAsync (owner), RanToCompletion
[8/7/2022 11:44:27 PM]  -0: WaitForPingDataAsync (owner), RanToCompletion
[8/7/2022 11:44:27 PM] Task count: 2
[8/7/2022 11:44:27 PM] Received STARTGAMEFINALIZE packet. Round init status: WaitingForStartGameFinalize
[8/7/2022 11:44:22 PM] Generating an outpost for the start of the level... (Location: Gangpo Habitation Outpost, level type: Outpost)
[8/7/2022 11:44:22 PM] Level identifier: outpostlevel
[8/7/2022 11:44:11 PM] Server running slowly (54 updates/s)!
[8/7/2022 11:44:01 PM] Lobby created!
[8/7/2022 11:42:44 PM] Attempting to open ALC device "OpenAL Soft on Headset Earphone (G435 Wireless Gaming Headset)"
[8/7/2022 11:42:41 PM] Logged in as ConnorsSilverpaws (SteamID STEAM_1:0:12166402)
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b967a5c0c629c60d08e8f909e532bddc7dbe49ab

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
