### ISSUE TITLE
Dedicated Server on Ubuntu wont start

### ISSUE THREAD

**Issue by DieserIBP** [Regalis11/Barotrauma#9689]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Im trying to setup a dedicated Server on Ubuntu 20.04 LTS. I've tried to set up the server using LinuxGSM as well as setting it up manually. Whenever i try to start the server it exits without any errors or logs after:

Barotrauma Dedicated Server 0.18.15.0 (ReleaseLinux, branch release, revision a7b22109e9)
Loading game settings
Loading MD5 hash cache
Initializing SteamManager
Initializing GameScreen
Selected shuttle: Hemulen

Are there actually no log files or am i just not finding them?...

### Reproduction steps

1. Install Barotrauma server on Ubuntu 20.04 LTS
2. Make sure ~/.local/share/Daedalic Entertainment GmbH/Barotrauma/ exists
3. Start the server

### Bug prevalence

Happens every time I play

### Version

0.18.15.0

### Which operating system did you encounter this bug on?

Linux

**Comment by Regalis11** [comment]
Potential duplicate of https://github.com/Regalis11/Barotrauma/issues/1987

**Comment by mygamingaccount** [comment]
@DieserIBP post your serversettings.xml

**Comment by GWXerxes** [comment]
@DieserIBP I had this issue and found it was caused by a different service binding to port 20715. Mine was crashing at the same spot in log output with no error message. Are you running any other steam game servers? Killing Floor 2 was causing the issue in my case. 

Check https://github.com/Regalis11/Barotrauma/issues/5705

**Comment by ryanalexmartin** [comment]
Seems that some paths are hard coded, and `steamcmd` installs Barotrauma to a different location.

```
Barotrauma Dedicated Server crash report (generated on 11/28/2022 14:51:36)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


Game version 0.19.14.0 (ReleaseLinux, branch release, revision 0daf5b87bd)
Language: English
Selected content packages: None
Level seed: no level loaded
Loaded submarine: None
Selected screen: None


System info:
    Operating system: Unix 5.15.0.1019 64 bit


Exception: Could not find a part of the path '/home/ubuntu/.local/share/Daedalic Entertainment GmbH/Barotrauma'. (System.IO.DirectoryNotFoundException)
Target site: IntPtr CreateDirectoryHandle(System.String, Boolean)
Stack trace: 
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserEntries(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.GetFileSystemEntries(String path, String searchPattern, EnumerationOptions enumerationOptions)
   at System.IO.Directory.GetFileSystemEntries(String path)
   at Barotrauma.ToolBox.CorrectFilenameCase(String filename, Boolean& corrected, String directory) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\ToolBox.cs:line 131
   at Barotrauma.ToolBox.CleanUpPathCrossPlatform(String path, Boolean correctFilenameCase, String directory) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\ToolBox.cs:line 660
   at Barotrauma.IO.Validation.CanWrite(String path, Boolean isDirectory) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SafeIO.cs:line 52
   at Barotrauma.IO.SafeXML.SaveSafe(XDocument doc, String path, SaveOptions saveOptions, Boolean throwExceptions) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SafeIO.cs:line 103
   at Barotrauma.GameSettings.SaveCurrentConfig() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Settings\GameSettings.cs:line 613
   at Barotrauma.GameSettings.Init() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Settings\GameSettings.cs:line 502
   at Barotrauma.GameMain..ctor(String[] args) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\GameMain.cs:line 84
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Program.cs:line 76


Last debug messages:
Unhandled exception. System.IO.DirectoryNotFoundException: Could not find a part of the path '/home/ubuntu/.local/share/Daedalic Entertainment GmbH/Barotrauma'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserEntries(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.GetFileSystemEntries(String path, String searchPattern, EnumerationOptions enumerationOptions)
   at System.IO.Directory.GetFileSystemEntries(String path)
   at Barotrauma.ToolBox.CorrectFilenameCase(String filename, Boolean& corrected, String directory) in C:\Users\joona\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Utils\ToolBox.cs:line 131
   at Barotrauma.ToolBox.CleanUpPathCrossPlatform(String path, Boolean correctFilenameCase, String directory) in C:\Users\joona\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Utils\ToolBox.cs:line 660
   at Barotrauma.IO.Validation.CanWrite(String path, Boolean isDirectory) in C:\Users\joona\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Utils\SafeIO.cs:line 52
   at Barotrauma.IO.SafeXML.SaveSafe(XDocument doc, String path, SaveOptions saveOptions, Boolean throwExceptions) in C:\Users\joona\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Utils\SafeIO.cs:line 103
   at Barotrauma.GameSettings.SaveCurrentConfig() in C:\Users\joona\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Settings\GameSettings.cs:line 613
   at Barotrauma.GameSettings.Init() in C:\Users\joona\Documents\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\Settings\GameSettings.cs:line 502
   at Barotrauma.GameMain..ctor(String[] args) in C:\Users\joona\Documents\Barotrauma-development\Barotrauma\BarotraumaServer\ServerSource\GameMain.cs:line 84
   at Barotrauma.Program.Main(String[] args) in C:\Users\joona\Documents\Barotrauma-development\Barotrauma\BarotraumaServer\ServerSource\Program.cs:line 76
Aborted (core dumped)
```

**Comment by ryanalexmartin** [comment]
Could be related to:
https://github.com/Regalis11/Barotrauma/issues/2310
