### ISSUE TITLE
After a game flash, the game can no longer be opened

### ISSUE THREAD

**Issue by ineedpowe** [Regalis11/Barotrauma#9708]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

![0DTQJ`5{R$G@P)L%(Q2`$KO](https://user-images.githubusercontent.com/111226288/184533176-c13a1865-807b-46f1-94ab-490f8198fddf.jpg)

### Reproduction steps

在一次航行中发生了游戏崩溃（无响应），强行关闭了游戏后，再也无法启动游戏。
After a game flash, the game can no longer be opened

### Bug prevalence

Just once

### Version

0.18.15.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma seems to have crashed. Sorry for the inconvenience! 


116B6C514DB831BB68D5A8F96ACE87C4


Game version 0.18.15.1 (ReleaseWindows, branch hf, revision 91a05f31ff)
Graphics mode: 0x0 (Windowed)
VSync OFF
Language: 
Selected content packages: None
Level seed: no level loaded
Loaded submarine: None
Selected screen: None
SteamManager initialized


System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit
    Game not initialized


Exception: Adapter 'NVIDIA GeForce MX230' does not support the Reach profile. (Microsoft.Xna.Framework.Graphics.NoSuitableGraphicsDeviceException)
Target site: Void .ctor(Microsoft.Xna.Framework.Graphics.GraphicsAdapter, Microsoft.Xna.Framework.Graphics.GraphicsProfile, Microsoft.Xna.Framework.Graphics.PresentationParameters)
Stack trace: 
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice..ctor(GraphicsAdapter adapter, GraphicsProfile graphicsProfile, PresentationParameters presentationParameters) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\GraphicsDevice.cs:line 218
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice..ctor(GraphicsDeviceInformation gdi) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\GraphicsDevice.cs:line 191
   at Microsoft.Xna.Framework.GraphicsDeviceManager.CreateDevice(GraphicsDeviceInformation gdi) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\GraphicsDeviceManager.cs:line 131
   at Microsoft.Xna.Framework.GraphicsDeviceManager.CreateDevice() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\GraphicsDeviceManager.cs:line 114
   at Microsoft.Xna.Framework.GraphicsDeviceManager.ApplyChanges() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\GraphicsDeviceManager.cs:line 305
   at Barotrauma.GameMain..ctor(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 220
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 57
```

**Comment by Regalis11** [comment]
Thank you for the report! 

We've received a similar report before https://github.com/Regalis11/Barotrauma/issues/9515, and it that case it seems the error disappeared by rebooting the computer.

> A quick google search seems to suggest that the "Adapter does not support the Reach profile" error might be a driver issue that can be fixed with a reboot. You might also want to ensure your graphics drivers are up to date.

So I would recommend rebooting your computer and ensuring your drivers are up-to-date. Please let us know if that helps!
