### ISSUE TITLE
crashes whenever using fabricator

### ISSUE THREAD

**Issue by GreatBlueMoon** [Regalis11/Barotrauma#9774]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

happens whenever i try to craft

### Reproduction steps

1. singleplayer
2. have resources
3. craft abyssal diving suit or something

### Bug prevalence

Happens every time I play

### Version

0.19.2.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 8/26/2022 8:05:01 PM)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


AEDD53F050B2F69C0F80B80C7FA739B3


Game version 0.19.2.0 (UnstableWindows, branch dev, revision d78ee17245)
Graphics mode: 1600x900 (Fullscreen)
VSync OFF
Language: English
Selected content packages: Vanilla
Level seed: Astypalaea LineaXinzou
Loaded submarine: Orca2 (8C0020CC5F0B4B452A53A9608F204FBE)
Selected screen: Barotrauma.GameScreen
SteamManager initialized


System info:
    Operating system: Microsoft Windows NT 6.1.7600.0 64 bit
    GPU name: NVIDIA GeForce GT 1030
    Display mode: {Width:1600 Height:900 Format:Color AspectRatio:1.7777778}
    GPU status: Normal


Exception: Sequence contains no elements (System.InvalidOperationException)
Target site: Void ThrowNoElementsException()
Stack trace: 
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Barotrauma.Items.Components.Fabricator.<>c__DisplayClass31_4.<DrawInputOverLay>b__6(KeyValuePair`2 i) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Components\Machines\Fabricator.cs:line 404
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Barotrauma.Items.Components.Fabricator.DrawInputOverLay(SpriteBatch spriteBatch, GUICustomComponent overlayComponent) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Components\Machines\Fabricator.cs:line 402
   at Barotrauma.GUICustomComponent.Draw(SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUICustomComponent.cs:line 43
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Barotrauma.GUI.Draw(Camera cam, SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 251
   at Barotrauma.GameScreen.Draw(Double deltaTime, GraphicsDevice graphics, SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\GameScreen.cs:line 170
   at Barotrauma.GameMain.Draw(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 982
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 669
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 511
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59


Last debug messages:
[8/26/2022 7:45:46 PM] Could not find a spawn point for a SpawnAction (spawn location: BeaconStation (tag: beacon_bandit), skipping.
[8/26/2022 7:45:19 PM] Generating an outpost for the start of the level... (Location: Astypalaea Linea, level type: LocationConnection)
[8/26/2022 7:45:17 PM] Generating an outpost for the end of the level... (Location: Xinzou Biomedical Research Center, level type: LocationConnection)
[8/26/2022 7:45:07 PM] Failed to connect waypoints between outpost modules. No waypoint in the top gap of the module "Alien_Entrance3".
[8/26/2022 7:45:07 PM] Failed to connect waypoints between outpost modules. No waypoint in the bottom gap of the module "Alien_Entrance3".
[8/26/2022 7:44:58 PM] Level identifier: ridgebasic
[8/26/2022 7:44:31 PM] Transitioning to Astypalaea LineaXinzou (current location: Xinzou Biomedical Research Center, selected location: Astypalaea Linea, leaving sub: Orca2, at start: True, at end: False, transition type: LeaveLocation)
[8/26/2022 7:39:13 PM] Unlocked mission "Clear Ruin" in the location "Xinzou Biomedical Research Center".
[8/26/2022 7:39:10 PM] Unlocked mission "Terminate a Swarm" in the location "Xinzou Biomedical Research Center".
[8/26/2022 7:39:08 PM] Unlocked mission "Salvaging an artifact" in the location "Xinzou Biomedical Research Center".
[8/26/2022 7:39:06 PM] Unlocked mission "Scan ruin" in the location "Xinzou Biomedical Research Center".
[8/26/2022 7:33:24 PM] Generating an outpost for the start of the level... (Location: Xinzou Biomedical Research Center, level type: Outpost)
[8/26/2022 7:33:24 PM] Level identifier: outpostlevel
[8/26/2022 7:32:57 PM] Transitioning to Xinzou (current location: The Bucket Outpost, selected location: Xinzou Biomedical Research Center, leaving sub: Orca2, at start: False, at end: True, transition type: ProgressToNextLocation)
[8/26/2022 6:25:54 PM] Could not find a spawn point for a SpawnAction (spawn location: BeaconStation (tag: beacon_bandit), skipping.
[8/26/2022 6:25:29 PM] Generating an outpost for the start of the level... (Location: Xinzou Biomedical Research Center, level type: LocationConnection)
[8/26/2022 6:25:28 PM] Generating an outpost for the end of the level... (Location: The Bucket Outpost, level type: LocationConnection)
[8/26/2022 6:25:22 PM] Failed to connect waypoints between outpost modules. No waypoint in the bottom gap of the module "Alien_Entrance3".
[8/26/2022 6:25:22 PM] Failed to connect waypoints between outpost modules. No waypoint in the top gap of the module "Alien_Entrance3".
[8/26/2022 6:25:16 PM] Level identifier: ridgebasic
[8/26/2022 6:24:25 PM] Attempting to open ALC device "OpenAL Soft on Speakers (High Definition Audio Device)"
[8/26/2022 6:24:23 PM] Logged in as Great Blue (SteamID STEAM_1:0:97010883)
```

**Comment by ubertpendragon** [comment]
Some items crash the game upon opening Fabricator UI, others don't

![image](https://user-images.githubusercontent.com/73229309/187013013-f90ca6fa-5b86-4d85-a431-7e262eea3fe3.png)

**Comment by NilanthAnimosus** [comment]
Tested on 0.19.2.0.

Noticing after a craft has finished (IE. abyssal diving suit) I got a crash for drawing the required items overlay.

![image](https://user-images.githubusercontent.com/29177976/187017518-beabe76a-1c1a-4f0d-87ba-ea7febd24cd8.png)

In my case I just started with no linked containers on an azimuth, crafted the abyss diving suit with skill set to 100 so its faster, placed the needed materials in (though it doesn't say you need 2 titanium-aluminium alloy) and watched it finish not closing the UI. this appears to cause the game to crash.

![image](https://user-images.githubusercontent.com/29177976/187017526-ee12236a-1dda-4c88-b020-7d445f02c631.png)

**Comment by GreatBlueMoon** [comment]
a workaround found is to have extra for any resource used in crafting, the game crashes when you run out of stuff

storage container needs 2 steel, once crafted it'l crash if thats all you had, if you have 3 steel when crafting it you get leftover with excess and dont crash, please fix

**Comment by GreatBlueMoon** [comment]
> a workaround found is to have extra for any resource used in crafting, the game crashes when you run out of stuff
> 
> storage container needs 2 steel, once crafted it'l crash if thats all you had, if you have 3 steel when crafting it you get leftover with excess and dont crash, please fix

how do you add in labels, i think unstable should be tagged

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/54412aa3ea311e4e6caf91dc4c7a3bce2ce7ea2b

**Comment by GreatBlueMoon** [comment]
> Fixed in [Regalis11/Barotrauma-development@54412aa](https://github.com/Regalis11/Barotrauma-development/commit/54412aa3ea311e4e6caf91dc4c7a3bce2ce7ea2b)

do you mean its fixed in the next unstable update or? cause in 19.2 is crashing

**Comment by GreatBlueMoon** [comment]
also the link you send is broken

**Comment by Rokvach** [comment]
Tested by crafting a abyss suit, no crashes. Working correctly, closing.

**Comment by NilanthAnimosus** [comment]
Just an FYI for the above comments, that is a link to the private repo (code that is not public, but is referenced in the tickets here for developer reference to keep track of things). It will likely be in the next unstable build.
