### ISSUE TITLE
"Recreating ragdoll" in the character editor under certain conditions causes a crash.

### ISSUE THREAD

**Issue by LatekVo** [Regalis11/Barotrauma#9815]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Caused a crash by pressing "reload textures" and "regenerate ragdoll" in a sequence, in the character editor.

### Reproduction steps

1. Open the character editor.
2. Click "Reload Textures"
3. Click "Regenerate sprites"

### Bug prevalence

Happens every time I play

### Version

0.19.3.0 (unstable)

### -

Latest Native Linux Build.

### Which operating system did you encounter this bug on?

Linux

### Relevant error messages and crash reports

```shell
﻿Barotrauma Client crash report (generated on 09/02/2022 21:24:40)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


AA0FABA7B021621B9FF337EF2D2E272F


Game version 0.18.15.1 (ReleaseLinux, branch hf, revision 91a05f31ff)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync OFF
Language: English
Selected content packages: Vanilla, advanced full airlock
Level seed: no level loaded
Loaded submarine: AnimEditor (B9856B3F97C56866A95FE75D0038FA16)
Selected screen: Barotrauma.CharacterEditor.CharacterEditorScreen
SteamManager initialized


System info:
    Operating system: Unix 5.18.XX.XX 64 bit
    GPU name: 
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal


Exception: Texture is disposed (System.InvalidOperationException)
Target site: Void CheckValid(Microsoft.Xna.Framework.Graphics.Texture2D)
Stack trace: 
   at Microsoft.Xna.Framework.Graphics.SpriteBatch.CheckValid(Texture2D texture) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\SpriteBatch.cs:line 249
   at Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(Texture2D texture, Vector2 position, Nullable`1 sourceRectangle, Color color, Single rotation, Vector2 origin, Vector2 scale, SpriteEffects effects, Single layerDepth) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\SpriteBatch.cs:line 472
   at Barotrauma.Sprite.Draw(ISpriteBatch spriteBatch, Vector2 pos, Color color, Vector2 origin, Single rotate, Vector2 scale, SpriteEffects spriteEffect, Nullable`1 depth) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Sprite\Sprite.cs:line 219
   at Barotrauma.PhysicsBody.Draw(SpriteBatch spriteBatch, Sprite sprite, Color color, Nullable`1 depth, Single scale, Boolean mirrorX, Boolean mirrorY) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Physics\PhysicsBody.cs:line 33
   at Barotrauma.Limb.Draw(SpriteBatch spriteBatch, Camera cam, Nullable`1 overrideColor, Boolean disableDeformations) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Characters\Limb.cs:line 794
   at Barotrauma.Ragdoll.Draw(SpriteBatch spriteBatch, Camera cam) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Characters\Animation\Ragdoll.cs:line 480
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Barotrauma.CharacterEditor.CharacterEditorScreen.Draw(Double deltaTime, GraphicsDevice graphics, SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\CharacterEditor\CharacterEditorScreen.cs:line 806
   at Barotrauma.GameMain.Draw(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 1003
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 669
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 511
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59


Last debug messages:
[09/02/2022 21:24:36] Watcher
[09/02/2022 21:24:36] Tigerthresher_hatchling
[09/02/2022 21:24:36] Tigerthresher
[09/02/2022 21:24:36] Terminalcell
[09/02/2022 21:24:36] Swarmfeeder
[09/02/2022 21:24:36] Spineling_giant
[09/02/2022 21:24:36] Spineling
[09/02/2022 21:24:36] Psilotoad
[09/02/2022 21:24:36] Peanut
[09/02/2022 21:24:36] Orangeboy
[09/02/2022 21:24:36] Mudraptor_veteran
[09/02/2022 21:24:36] Mudraptor_unarmored
[09/02/2022 21:24:36] Mudraptor_passive
[09/02/2022 21:24:36] Mudraptor_hatchling
[09/02/2022 21:24:36] Mudraptor
[09/02/2022 21:24:36] Moloch_m
[09/02/2022 21:24:36] Molochblack_m
[09/02/2022 21:24:36] Molochblack
[09/02/2022 21:24:36] Molochbaby
[09/02/2022 21:24:36] Moloch
[09/02/2022 21:24:36] Mantis
[09/02/2022 21:24:36] Leucocyte
[09/02/2022 21:24:36] Legacywatcher
[09/02/2022 21:24:36] Legacytigerthresher
[09/02/2022 21:24:36] Legacymoloch
[09/02/2022 21:24:36] Legacyhusk
[09/02/2022 21:24:36] Legacyfractalguardian2
[09/02/2022 21:24:36] Legacyfractalguardian
[09/02/2022 21:24:36] Legacyendworm
[09/02/2022 21:24:36] Legacycrawler
[09/02/2022 21:24:36] Legacycharybdis
[09/02/2022 21:24:36] Latcher
[09/02/2022 21:24:36] Husk
[09/02/2022 21:24:36] Humanhusk
[09/02/2022 21:24:36] Human
[09/02/2022 21:24:36] Hammerhead_mNamed
[09/02/2022 21:24:36] Hammerhead_m
[09/02/2022 21:24:36] Hammerheadspawn
[09/02/2022 21:24:36] Hammerheadmatriarch
[09/02/2022 21:24:36] Hammerheadgold_m
[09/02/2022 21:24:36] Hammerheadgold
[09/02/2022 21:24:36] Hammerhead
[09/02/2022 21:24:36] Fractalguardian2
[09/02/2022 21:24:36] Fractalguardian
[09/02/2022 21:24:36] Endworm
[09/02/2022 21:24:36] Doomworm
[09/02/2022 21:24:36] Crawler_large
[09/02/2022 21:24:36] Crawler_hatchling
[09/02/2022 21:24:36] Crawlerhusk
[09/02/2022 21:24:36] Crawlerbroodmother_m
[09/02/2022 21:24:36] Crawlerbroodmother
[09/02/2022 21:24:36] Crawler
[09/02/2022 21:24:36] Coelanth
[09/02/2022 21:24:36] Charybdisold
[09/02/2022 21:24:36] Charybdis
[09/02/2022 21:24:36] Carrier
[09/02/2022 21:24:36] Bonethresher
[09/02/2022 21:24:36] Balloon
[09/02/2022 21:24:35] Trying to spawn human
[09/02/2022 21:23:30] Attempting to open ALC device "Built-in Audio Analog Stereo"
[09/02/2022 21:23:28] Logged in as XXXXX (SteamID STEAM_1:0:XXXXXXXXX)
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/da1d8549c226ea183463513d3c3483edd5da6991

**Comment by Regalis11** [comment]
I noticed that there was actually bigger underlying issue in the ReloadTexture command, which caused both this and https://github.com/Regalis11/Barotrauma/issues/9815. Reverted the previous fix and fixed properly in https://github.com/Regalis11/Barotrauma-development/commit/8a032439540555d6d1c31b0597077dbab947e4f2.

> Fixed ReloadTexture method causing "texture is disposed" exceptions in some situations. Seems to have happened as a result of https://github.com/Regalis11/Barotrauma-development/commit/63bb08faa949256a6bd2a006a98fc237d92a6147 and https://github.com/Regalis11/Barotrauma-development/commit/a6a653dfdc495c19b29003ae97f04f1c07903df9. Other sprites might've shared the same texture, which caused the previous exception if they weren't refreshed. A reference to the disposed texture was also kept in textureRefCounts, causing the same exception if another sprite tries to use it later.

**Comment by Rokvach** [comment]
Tested I wasn't able to cause a crash no matter what I did, working correctly. Closing.
