### ISSUE TITLE
unable to launched the game at all and get this bug report

### ISSUE THREAD

**Issue by pika1up** [Regalis11/Barotrauma#9837]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

okay so i was playing baro with some friends and for some reason everyone got diconected and my game refused to close and i couldnt force close the game or pull up task manager and i was forced to restart my entire pc, upon reopening steam i try to launch steam and i was greeted with, sorry ur game wasnt able to launch cause files were corupted or something so i try reinstalling the game, nope that didnt work and i try deleting the local files and it will not but it gave me a crash report but i aint no tech on reading and figuring out a fix...if someone could help id appreciate it 
[crashreport.log](https://github.com/Regalis11/Barotrauma/files/9502507/crashreport.log)

### Bug prevalence

Happens every time I play

### Version

Other

### -

idk how to see version, im just using the latest barotrauma

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 8/9/2022 9:49:19 PM)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


116B6C514DB831BB68D5A8F96ACE87C4


Game version 0.18.15.1 (ReleaseWindows, branch hf, revision 91a05f31ff)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla, Better Cleanup, Lua For Barotrauma, Community Conversation Pack, GunLights Remade, Shipwrecks Extended, Meaningful CPR, New Wrecks For Barotrauma (With sellable wrecks), Dont Open Debug Console On Errors, oClockRadar / Sonar [Alt Appearance], Vanilla Clothes Redone, Transparent Diving Helmets, Alarms Extended
Level seed: no level loaded
Loaded submarine: AnimEditor (B9856B3F97C56866A95FE75D0038FA16)
Selected screen: Barotrauma.CharacterEditor.CharacterEditorScreen
SteamManager initialized


System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit
    GPU name: NVIDIA GeForce RTX 2080 SUPER
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal


Exception: Texture is disposed (System.InvalidOperationException)
Target site: Void CheckValid(Microsoft.Xna.Framework.Graphics.Texture2D)
Stack trace: 
   at Microsoft.Xna.Framework.Graphics.SpriteBatch.CheckValid(Texture2D texture) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\SpriteBatch.cs:line 249
   at Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(Texture2D texture, Vector2 position, Nullable`1 sourceRectangle, Color color, Single rotation, Vector2 origin, Vector2 scale, SpriteEffects effects, Single layerDepth) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\SpriteBatch.cs:line 472
   at Barotrauma.Sprite.Draw(ISpriteBatch spriteBatch, Vector2 pos, Color color, Vector2 origin, Single rotate, Vector2 scale, SpriteEffects spriteEffect, Nullable`1 depth) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Sprite\Sprite.cs:line 219
   at Barotrauma.PhysicsBody.Draw(SpriteBatch spriteBatch, Sprite sprite, Color color, Nullable`1 depth, Single scale, Boolean mirrorX, Boolean mirrorY) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Physics\PhysicsBody.cs:line 46
   at Barotrauma.Limb.Draw(SpriteBatch spriteBatch, Camera cam, Nullable`1 overrideColor, Boolean disableDeformations) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Characters\Limb.cs:line 794
   at Barotrauma.Ragdoll.Draw(SpriteBatch spriteBatch, Camera cam) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Characters\Animation\Ragdoll.cs:line 480
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Barotrauma.CharacterEditor.CharacterEditorScreen.Draw(Double deltaTime, GraphicsDevice graphics, SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\CharacterEditor\CharacterEditorScreen.cs:line 806
   at Barotrauma.GameMain.Draw(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 1003
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 669
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 511
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59


Last debug messages:
[8/9/2022 9:48:47 PM] Watcher
[8/9/2022 9:48:47 PM] Tigerthresher_hatchling
[8/9/2022 9:48:47 PM] Tigerthresher
[8/9/2022 9:48:47 PM] Terminalcell
[8/9/2022 9:48:47 PM] Swarmfeeder
[8/9/2022 9:48:47 PM] Spineling_giant
[8/9/2022 9:48:47 PM] Spineling
[8/9/2022 9:48:47 PM] Psilotoad
[8/9/2022 9:48:47 PM] Peanut
[8/9/2022 9:48:47 PM] Orangeboy
[8/9/2022 9:48:47 PM] Mudraptor_veteran
[8/9/2022 9:48:47 PM] Mudraptor_unarmored
[8/9/2022 9:48:47 PM] Mudraptor_passive
[8/9/2022 9:48:47 PM] Mudraptor_hatchling
[8/9/2022 9:48:47 PM] Mudraptor
[8/9/2022 9:48:47 PM] Molochblack_m
[8/9/2022 9:48:47 PM] Molochblack
[8/9/2022 9:48:47 PM] Molochbaby
[8/9/2022 9:48:47 PM] Moloch_m
[8/9/2022 9:48:47 PM] Moloch
[8/9/2022 9:48:47 PM] Mantis
[8/9/2022 9:48:47 PM] Leucocyte
[8/9/2022 9:48:47 PM] Legacywatcher
[8/9/2022 9:48:47 PM] Legacytigerthresher
[8/9/2022 9:48:47 PM] Legacymoloch
[8/9/2022 9:48:47 PM] Legacyhusk
[8/9/2022 9:48:47 PM] Legacyfractalguardian2
[8/9/2022 9:48:47 PM] Legacyfractalguardian
[8/9/2022 9:48:47 PM] Legacyendworm
[8/9/2022 9:48:47 PM] Legacycrawler
[8/9/2022 9:48:47 PM] Legacycharybdis
[8/9/2022 9:48:47 PM] Latcher
[8/9/2022 9:48:47 PM] Husk
[8/9/2022 9:48:47 PM] Humanhusk
[8/9/2022 9:48:47 PM] Human
[8/9/2022 9:48:47 PM] Hammerheadspawn
[8/9/2022 9:48:47 PM] Hammerheadmatriarch
[8/9/2022 9:48:47 PM] Hammerheadgold_m
[8/9/2022 9:48:47 PM] Hammerheadgold
[8/9/2022 9:48:47 PM] Hammerhead_mNamed
[8/9/2022 9:48:47 PM] Hammerhead_m
[8/9/2022 9:48:47 PM] Hammerhead
[8/9/2022 9:48:47 PM] Fractalguardian2
[8/9/2022 9:48:47 PM] Fractalguardian
[8/9/2022 9:48:47 PM] Endworm
[8/9/2022 9:48:47 PM] Doomworm
[8/9/2022 9:48:47 PM] Crawlerhusk
[8/9/2022 9:48:47 PM] Crawlerbroodmother_m
[8/9/2022 9:48:47 PM] Crawlerbroodmother
[8/9/2022 9:48:47 PM] Crawler_large
[8/9/2022 9:48:47 PM] Crawler_hatchling
[8/9/2022 9:48:47 PM] Crawler
[8/9/2022 9:48:47 PM] Coelanth
[8/9/2022 9:48:47 PM] Charybdisold
[8/9/2022 9:48:47 PM] Charybdis
[8/9/2022 9:48:47 PM] Carrier
[8/9/2022 9:48:47 PM] Bonethresher
[8/9/2022 9:48:47 PM] Balloon
[8/9/2022 9:48:46 PM] Trying to spawn human
[8/9/2022 9:48:42 PM] WARNING: Tried to restore enabled packages multiple times/without performing a backup
[8/9/2022 9:43:16 PM] ModeSelectionMode
[8/9/2022 9:43:16 PM] SubSelectionMode
[8/9/2022 9:43:16 PM] LosMode
[8/9/2022 9:43:16 PM] PlayStyle
[8/9/2022 9:42:33 PM] ModeSelectionMode
[8/9/2022 9:42:33 PM] SubSelectionMode
[8/9/2022 9:42:33 PM] LosMode
[8/9/2022 9:42:33 PM] PlayStyle
[8/9/2022 9:41:30 PM] Lobby created!
[8/9/2022 9:39:57 PM] WARNING: Tried to restore enabled packages multiple times/without performing a backup
[8/9/2022 9:39:54 PM] ModeSelectionMode
[8/9/2022 9:39:54 PM] SubSelectionMode
[8/9/2022 9:39:54 PM] LosMode
[8/9/2022 9:39:54 PM] PlayStyle
[8/9/2022 9:39:28 PM] Lobby created!
[8/9/2022 9:38:10 PM] Attempting to open ALC device "OpenAL Soft on Headphones (3- Arctis 7 Game)"
[8/9/2022 9:38:05 PM] Logged in as Pika1up (SteamID STEAM_1:0:29587128)
```

**Comment by Regalis11** [comment]
Thank you for the report!

The crash report is quite strange here: it seems to indicate the game crashed in the character editor (which shouldn't be possible if it occurs when trying to launch the game). Are you absolutely sure this is the correct crash report file? Have you tried verifying the integrity of game files (in your Steam Library, right-click on Barotrauma on the list and select ’Properties’ from the menu -> Local files tab -> ‘Verify integrity of game files’). 

I'm sorry for the inconvenience, I hope we can figure out what's causing this. :/

**Comment by Regalis11** [comment]
Not enough information to diagnose the issue, closing
