### ISSUE TITLE
Having the talent section previously selected and pressing TAB while controlling a monster causes a crash

### ISSUE THREAD

**Issue by evilfactory** [Regalis11/Barotrauma#9862]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Controlling a creature/monster with the talent section in the TAB menu previously opened and then pressing TAB causes the game to crash.

### Reproduction steps

1. Control a human
2. Press TAB and click in the talent section
3. Spawn a creature and take control of it using the `control` console command
4. Press TAB
5. Crash

### Bug prevalence

Happens every time I play

### Version

0.18.15.1 / 0.18.15.2 on macOS

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 12/09/2022 17:41:15)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


E0AC24F4E957C88887977A0D88C10E3A


Game version 0.18.15.0 (ReleaseWindows, branch master, revision 56d997624e)
Graphics mode: 1280x1024 (BorderlessWindowed)
VSync OFF
Language: English
Selected content packages: Vanilla
Level seed: jdPzSRiW
Loaded submarine: Azimuth (07D8EED10EC4C0ABB05BDADFB699C0BA)
Selected screen: Barotrauma.GameScreen
SteamManager initialized
Client (Round had started)


System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit
    GPU name: AMD Radeon(TM) Vega 8 Graphics
    Display mode: {Width:1280 Height:1024 Format:Color AspectRatio:1,25}
    GPU status: Normal


Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void Update(Single)
Stack trace: 
   at Barotrauma.TabMenu.Update(Single deltaTime)
   at Barotrauma.GameSession.UpdateProjSpecific(Single deltaTime)
   at Barotrauma.GameScreen.Update(Double deltaTime)
   at Barotrauma.GameMain.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in G:\Repositories\Barotrauma\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in G:\Repositories\Barotrauma\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in G:\Repositories\Barotrauma\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in G:\Repositories\Barotrauma\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in G:\Repositories\Barotrauma\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args)


Last debug messages:
[12/09/2022 17:41:13] Crawler
[12/09/2022 17:41:13] Server command: control Crawler
[12/09/2022 17:41:13] control Crawler
[12/09/2022 17:41:11] Server command: spawn crawler cursor
[12/09/2022 17:41:11] spawn crawler cursor
[12/09/2022 17:41:04] Evil Factory
[12/09/2022 17:41:04] Server command: control "Evil Factory"
[12/09/2022 17:41:04] control "Evil Factory"
[12/09/2022 17:40:58] Evil Factory
[12/09/2022 17:40:58] freecam
[12/09/2022 17:40:51] Evil Factory
[12/09/2022 17:40:49] Received STARTGAMEFINALIZE packet. Round init status: Started
[12/09/2022 17:40:48] Creating hulls between docking ports failed. The upper docking port seems to be very far from any hulls in the upper submarine.
[12/09/2022 17:40:46]  -1: WaitForPingDataAsync (owner), RanToCompletion
[12/09/2022 17:40:46]  -0: WaitForPingDataAsync (owner), RanToCompletion
[12/09/2022 17:40:46] Task count: 2
[12/09/2022 17:40:46] Received STARTGAMEFINALIZE packet. Round init status: WaitingForStartGameFinalize
[12/09/2022 17:40:43] Generating an outpost for the end of the level... (Location: Skadi's Cauldron Mine, level type: LocationConnection)
[12/09/2022 17:40:43] Level identifier: coldcavernsadvanced
[12/09/2022 17:39:52] Evil Factory
[12/09/2022 17:39:31] Evil Factory
[12/09/2022 17:39:31] Server command: control "Evil Factory"
[12/09/2022 17:39:31] control "Evil Factory"
[12/09/2022 17:39:26] Evil Factory
[12/09/2022 17:39:26] freecam
[12/09/2022 17:38:42] Evil Factory
[12/09/2022 17:38:42] Server command: control "Evil Factory"
[12/09/2022 17:38:42] control "Evil Factory"
[12/09/2022 17:38:39] Server command: teleportsub
[12/09/2022 17:38:39] teleportsub
[12/09/2022 17:38:38] Server command: teleportsub
[12/09/2022 17:38:38] teleportsub
[12/09/2022 17:38:37] Server command: teleportsub
[12/09/2022 17:38:37] teleportsub
[12/09/2022 17:38:33] Evil Factory
[12/09/2022 17:38:33] freecam
[12/09/2022 17:37:17] Server command: teleportsub
[12/09/2022 17:37:17] teleportsub
[12/09/2022 17:37:13] Server command: explosion
[12/09/2022 17:37:13] explosion
[12/09/2022 17:37:12] Server command: explosion
[12/09/2022 17:37:12] explosion
[12/09/2022 17:37:12] Server command: explosion
[12/09/2022 17:37:12] explosion
[12/09/2022 17:37:12] Server command: explosion
[12/09/2022 17:37:12] explosion
[12/09/2022 17:37:12] Server command: explosion
[12/09/2022 17:37:12] explosion
[12/09/2022 17:37:11] Server command: explosion
[12/09/2022 17:37:11] explosion
[12/09/2022 17:37:11] Server command: explosion
[12/09/2022 17:37:11] explosion
[12/09/2022 17:37:01] Server command: teleportsub
[12/09/2022 17:37:01] teleportsub
[12/09/2022 17:37:01] Server command: teleportsub
[12/09/2022 17:37:01] teleportsub
[12/09/2022 17:36:56] Server command: killmonsters
[12/09/2022 17:36:56] killmonsters
[12/09/2022 17:36:53] Server command: fixitems
[12/09/2022 17:36:53] fixitems
[12/09/2022 17:36:46] Lighting enabled
[12/09/2022 17:36:46] lighting
[12/09/2022 17:36:44] Debug draw mode disabled
[12/09/2022 17:36:44] debugdraw
[12/09/2022 17:36:41] Server command: spawnitem "Incendium Grenade" inventory
[12/09/2022 17:36:41] spawnitem "Incendium Grenade" inventory
[12/09/2022 17:36:24] Server command: spawnitem "Compound N" inventory 32
[12/09/2022 17:36:24] spawnitem "Compound N" inventory 32
[12/09/2022 17:36:20] Server command: spawnitem "Compound N" inventory
[12/09/2022 17:36:20] spawnitem "Compound N" inventory
[12/09/2022 17:36:19] Server command: spawnitem "Compound N" inventory
[12/09/2022 17:36:19] spawnitem "Compound N" inventory
[12/09/2022 17:36:19] Server command: spawnitem "Compound N" inventory
[12/09/2022 17:36:19] spawnitem "Compound N" inventory
[12/09/2022 17:36:19] Server command: spawnitem "Compound N" inventory
[12/09/2022 17:36:19] spawnitem "Compound N" inventory
[12/09/2022 17:36:18] Server command: spawnitem "Compound N" inventory
[12/09/2022 17:36:18] spawnitem "Compound N" inventory
[12/09/2022 17:36:18] Server command: spawnitem "Compound N" inventory
[12/09/2022 17:36:18] spawnitem "Compound N" inventory
[12/09/2022 17:36:18] Server command: spawnitem "Compound N" inventory
[12/09/2022 17:36:18] spawnitem "Compound N" inventory
[12/09/2022 17:36:17] Server command: spawnitem "Compound N" inventory
[12/09/2022 17:36:17] spawnitem "Compound N" inventory
[12/09/2022 17:36:07] Evil Factory
[12/09/2022 17:36:07] Server command: control "Evil Factory"
[12/09/2022 17:36:07] control "Evil Factory"
[12/09/2022 17:01:45] LobbyMatchList:  LobbiesMatching: 0
[12/09/2022 17:01:45] LobbyMatchList:  LobbiesMatching: 0
[12/09/2022 17:01:45] SteamAPICallCompleted:   AsyncCall: 7397970056915920343
   Callback: 510
 ParamCount: 4
[12/09/2022 17:01:44] LobbyMatchList:  LobbiesMatching: 41
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4f9c30201826076197e9dd386339bc22910996da

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
