### ISSUE TITLE
Immediate crash

### ISSUE THREAD

**Issue by AlanGuardsman** [Regalis11/Barotrauma#9892]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Barotrauma Client crash report (generated on 19.09.2022 5:16:58)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

116B6C514DB831BB68D5A8F96ACE87C4

Game version 0.18.15.1 (ReleaseWindows, branch hf, revision 91a05f31ff)
Graphics mode: 1280x720 (Fullscreen)
VSync ON
Language: Russian
Selected content packages: None
Level seed: no level loaded
Loaded submarine: None
Selected screen: None
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit
    GPU name: NVIDIA GeForce MX230
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1,7777778}
    GPU status: Normal

Exception: An item with the same key has already been added. Key: music (System.ArgumentException)
Target site: Void ThrowAddingDuplicateWithKeyArgumentException[T](T)
Stack trace: 
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Barotrauma.Sounds.SoundManager.SetCategoryGainMultiplier(String category, Single gain, Int32 index) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Sounds\SoundManager.cs:line 543
   at Barotrauma.Sounds.SoundManager.Update() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Sounds\SoundManager.cs:line 656
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 930
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 654
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59

Last debug messages:
[19.09.2022 5:16:57] Attempting to open ALC device "OpenAL Soft on Динамики (Realtek(R) Audio)"
[19.09.2022 5:16:54] Logged in as NeTagaty (SteamID STEAM_1:1:207038420)

### Reproduction steps

1. launch the game. Exact condition unknown for reasons

### Bug prevalence

Just once

### Version

Other

### -

0.18.15.1

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

I unfortunately haven't been able to get this exception to occur at my end, but looking at the error message, I think I have a guess of what could've caused it and attempted a fix: https://github.com/Regalis11/Barotrauma-development/commit/afff5f7c81fcfbbb6166f8d7b353af5f7540dc84

> Attempt to fix a crash in SoundManager.SetCategoryGainMultiplier. No known steps to repro, but I suspect categoryModifiers was being modified from multiple threads and added locks to prevent it.

**Comment by Rokvach** [comment]
No repro steps so just need to wait and see if this crash appears in GA

**Comment by Rokvach** [comment]
There hasnt been any entries about this in GA, seems to be working, closing.
