### ISSUE TITLE
When Throwable applies OnActive StatusEffect and causes the picker to die, the server crashes and throws a NRE

### ISSUE THREAD

**Issue by zhu-rengong** [Regalis11/Barotrauma#9902]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [x] My issue happened while using mods.

### What happened?

As the title says.
```
System info:
    Operating system: Microsoft Windows NT 6.2.9200.0 64 bit


Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void Update(Single, Barotrauma.Camera)
Stack trace: 
   at Barotrauma.Items.Components.Throwable.Update(Single deltaTime, Camera cam) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Items/Components/Holdable/Throwable.cs:line 115
   at Barotrauma.Item.Update(Single deltaTime, Camera cam) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Items/Item.cs:line 1851
   at Barotrauma.MapEntity.UpdateAll(Single deltaTime, Camera cam) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Map/MapEntity.cs:line 632
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Screens/GameScreen.cs:line 253
   at Barotrauma.GameMain.Run() in <DEV>/Barotrauma/BarotraumaServer/ServerSource/GameMain.cs:line 340
   at Barotrauma.Program.Main(String[] args) in <DEV>/Barotrauma/BarotraumaServer/ServerSource/Program.cs:line 83
```

Navigate to `Throwable.Update(Single deltaTime, Camera cam)` and checks bug-causing code:
```C#
ApplyStatusEffects(ActionType.OnActive, deltaTime, picker);

// line: 115
if (item.body.Dir != picker.AnimController.Dir) { item.FlipX(relativeToSub: false); }
```

`picker.AnimController` is null when `picker` dies after applying statuseffect.

### Reproduction steps

Take frag grenade as an example, the following is its definition in xml:
```xml
  <Item name="" identifier="fraggrenade" category="Weapon" maxstacksize="8" cargocontaineridentifier="explosivecrate" tags="smallitem,weapon,explosive,demolitionsexpert" scale="0.5" impactsoundtag="impact_metal_heavy">
    <PreferredContainer primary="secarmcab" minamount="1" maxamount="3" spawnprobability="0.75" notcampaign="true"/>
    <PreferredContainer secondary="wreckarmcab,abandonedarmcab" minamount="1" maxamount="2" spawnprobability="0.2"/>
    <PreferredContainer secondary="armcab"/>
    <Upgrade gameversion="0.9.3.0" scale="0.5"/>
    <Price baseprice="150">
      <Price storeidentifier="merchantoutpost" sold="false" multiplier="1.35" />
      <Price storeidentifier="merchantcity" multiplier="1.25" minavailable="2" sold="false"/>
      <Price storeidentifier="merchantresearch" sold="false" multiplier="1.25" />
      <Price storeidentifier="merchantmilitary" multiplier="0.9" minavailable="3" />
      <Price storeidentifier="merchantmine" sold="false" multiplier="1.25" />
      <Price storeidentifier="merchantarmory" multiplier="0.9" minavailable="3" />
    </Price>
    <Deconstruct time="10">
      <Item identifier="iron" />
      <Item identifier="sodium" />
    </Deconstruct>
    <Fabricate suitablefabricators="fabricator" requiredtime="20">
      <RequiredSkill identifier="weapons" level="60" />
      <RequiredItem identifier="iron" />
      <RequiredItem identifier="uex" />
    </Fabricate>
    <InventoryIcon texture="Content/Items/InventoryIconAtlas.png" sourcerect="580,770,54,63" origin="0.5,0.5" />
    <Sprite texture="Content/Items/Weapons/weapons_new.png" sourcerect="217,305,40,61" depth="0.55" origin="0.5,0.5" />
    <Body radius="20" height="10" density="30" />
    <ItemComponent characterusable="false">
      <!-- statuseffect that explodes the grenade when used by something else than a character (e.g. a detonator) -->
      <StatusEffect type="OnUse" target="This" Condition="-100.0" disabledeltatime="true" />
      <StatusEffect type="OnBroken" target="This">
        <sound file="Content/Items/Weapons/ExplosionMedium1.ogg" type="OnUse" range="10000" selectionmode="All" />
        <sound file="Content/Items/Weapons/ExplosionDebris1.ogg" type="OnUse" range="10000" />
        <Explosion range="600.0" structuredamage="20" ballastfloradamage="120" itemdamage="500" force="10" severlimbsprobability="0.5" decal="explosion" decalsize="0.5">
          <Affliction identifier="bleeding" strength="80" />
          <Affliction identifier="explosiondamage" strength="180" />
          <Affliction identifier="stun" strength="5"/>
        </Explosion>
        <Remove />
      </StatusEffect>
    </ItemComponent>
    <Throwable slots="Any,RightHand,LeftHand" holdpos="0,0" handle1="0,0" throwforce="4.0" msg="ItemMsgPickUpSelect">
      <StatusEffect type="OnSecondaryUse" target="This" Condition="-100.0" delay="3.0" disabledeltatime="true" checkconditionalalways="true" />
    </Throwable>
    <Quality>
      <QualityStat stattype="ExplosionRadius" value="0.1"/>
      <QualityStat stattype="ExplosionDamage" value="0.1"/>
    </Quality>
  </Item>
```

Add a statusEffect to Throwable:
```xml
<StatusEffect type="OnActive" target="Character"  IsDead="true" />
```

Server crashes when you hold frag grenade in hand.

### Bug prevalence

Happens every time I play

### Version

0.18.15.1 / 0.18.15.2 on macOS

### Which operating system did you encounter this bug on?

Windows

**Comment by NilanthAnimosus** [comment]
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/749914f4707c8b61fc62ade029de1ff75aee3ac9, no issues found, closing.
