### ISSUE TITLE
Crash after turning off vertical sync

### ISSUE THREAD

**Issue by DieOrsons** [Regalis11/Barotrauma#9920]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Barotrauma Client crash report (generated on 23.09.2022 17:45:46)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

116B6C514DB831BB68D5A8F96ACE87C4

Game version 0.18.15.1 (ReleaseWindows, branch hf, revision 91a05f31ff)
Graphics mode: 1920x1080 (Fullscreen)
VSync OFF
Language: Russian
Selected content packages: Vanilla
Level seed: HuroniaDolgovskoy
Loaded submarine: Orca (A7C044B42BFD15447EA725D7F9D77D62)
Selected screen: Barotrauma.GameScreen
SteamManager initialized
Client (Round had started)

System info:
    Operating system: Microsoft Windows NT 10.0.22000.0 64 bit
    GPU name: NVIDIA GeForce GTX 1050 Ti
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1,7777778}
    GPU status: Normal

Exception: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index') (System.ArgumentOutOfRangeException)
Target site: Void ThrowArgumentOutOfRange_IndexException()
Stack trace: 
   at Barotrauma.ScalableFont.DrawString(SpriteBatch sb, String text, Vector2 position, Color color, Single rotation, Vector2 origin, Vector2 scale, SpriteEffects se, Single layerDepth, Alignment alignment, ForceUpperCase forceUpperCase) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Fonts\ScalableFont.cs:line 485
   at Barotrauma.GUI.DrawMessages(SpriteBatch spriteBatch, Camera cam) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1684
   at Barotrauma.GUI.Draw(Camera cam, SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 593
   at Barotrauma.GameScreen.Draw(Double deltaTime, GraphicsDevice graphics, SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\GameScreen.cs:line 165
   at Barotrauma.GameMain.Draw(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 1003
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 669
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 511
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59

Last debug messages:
[23.09.2022 17:45:29] Die Orsons
[23.09.2022 17:45:29] PeI4zeS
[23.09.2022 17:45:29] Boxxy
[23.09.2022 17:45:29] Canned sandwich
[23.09.2022 17:45:29] SheetFrost
[23.09.2022 17:45:27] Die Orsons
[23.09.2022 17:45:27] PeI4zeS
[23.09.2022 17:45:26] Boxxy
[23.09.2022 17:45:26] Canned sandwich
[23.09.2022 17:45:26] SheetFrost
[23.09.2022 17:45:25] Received STARTGAMEFINALIZE packet. Round init status: Started
[23.09.2022 17:45:25] Received STARTGAMEFINALIZE packet. Round init status: Started
[23.09.2022 17:45:25] Received STARTGAMEFINALIZE packet. Round init status: Started
[23.09.2022 17:45:20] Task count: 0
[23.09.2022 17:45:20] Received STARTGAMEFINALIZE packet. Round init status: WaitingForStartGameFinalize
[23.09.2022 17:45:07] Generating an outpost for the end of the level... (Location: Жилой аванпост Dolgovskoy, level type: LocationConnection)
[23.09.2022 17:45:06] Generating an outpost for the start of the level... (Location: Станция Huronia, level type: LocationConnection)
[23.09.2022 17:45:06] Level identifier: ridgebasic
[23.09.2022 17:44:57] Die Orsons
[23.09.2022 17:44:57] PeI4zeS
[23.09.2022 17:44:57] Boxxy
[23.09.2022 17:44:57] Canned sandwich
[23.09.2022 17:44:57] SheetFrost
[23.09.2022 17:44:56] Die Orsons
[23.09.2022 17:44:56] PeI4zeS
[23.09.2022 17:44:56] Boxxy
[23.09.2022 17:44:56] Canned sandwich
[23.09.2022 17:44:56] SheetFrost
[23.09.2022 17:44:55] Die Orsons
[23.09.2022 17:44:55] PeI4zeS
[23.09.2022 17:44:55] Boxxy
[23.09.2022 17:44:55] Canned sandwich
[23.09.2022 17:44:55] SheetFrost
[23.09.2022 17:44:24] Die Orsons
[23.09.2022 17:44:24] PeI4zeS
[23.09.2022 17:44:24] Boxxy
[23.09.2022 17:44:24] Canned sandwich
[23.09.2022 17:44:24] SheetFrost
[23.09.2022 17:43:28] PeI4zeS
[23.09.2022 17:43:28] Boxxy
[23.09.2022 17:43:28] Canned sandwich
[23.09.2022 17:43:27] SheetFrost
[23.09.2022 17:43:24] Received STARTGAMEFINALIZE packet. Round init status: Started
[23.09.2022 17:43:24] Task count: 0
[23.09.2022 17:43:18] Generating an outpost for the start of the level... (Location: Станция Huronia, level type: Outpost)
[23.09.2022 17:43:18] Level identifier: outpostlevel
[23.09.2022 17:42:50] LobbyMatchList:  LobbiesMatching: 0
[23.09.2022 17:42:50] LobbyMatchList:  LobbiesMatching: 0
[23.09.2022 17:42:50] SteamAPICallCompleted:   AsyncCall: 10881010049689869345
   Callback: 510
 ParamCount: 4
[23.09.2022 17:42:49] LobbyMatchList:  LobbiesMatching: 45
[23.09.2022 17:42:49] LobbyMatchList:  LobbiesMatching: 45
[23.09.2022 17:42:49] SteamAPICallCompleted:   AsyncCall: 7269827268199472704
   Callback: 510
 ParamCount: 4
[23.09.2022 17:42:49] LobbyMatchList:  LobbiesMatching: 50
[23.09.2022 17:42:49] LobbyMatchList:  LobbiesMatching: 50
[23.09.2022 17:42:49] SteamAPICallCompleted:   AsyncCall: 6049105086337966012
   Callback: 510
 ParamCount: 4
[23.09.2022 17:42:49] LobbyMatchList:  LobbiesMatching: 50
[23.09.2022 17:42:49] LobbyMatchList:  LobbiesMatching: 50
[23.09.2022 17:42:49] SteamAPICallCompleted:   AsyncCall: 8759321341839237912
   Callback: 510
 ParamCount: 4
[23.09.2022 17:42:11] Attempting to open ALC device "OpenAL Soft on Динамики (Realtek High Definition Audio)"
[23.09.2022 17:42:03] Logged in as Die Orsons (SteamID STEAM_1:1:198699763)

### Reproduction steps

Joined the game from the list, round started, trying to off vertical sync, crash

### Bug prevalence

Just once

### Version

0.18.15.1 / 0.18.15.2 on macOS

### Which operating system did you encounter this bug on?

Windows

**Comment by DieOrsons** [comment]
Happened again twice

Barotrauma Client crash report (generated on 26.09.2022 23:21:23)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


116B6C514DB831BB68D5A8F96ACE87C4


Game version 0.18.15.1 (ReleaseWindows, branch hf, revision 91a05f31ff)
Graphics mode: 1920x1080 (Fullscreen)
VSync OFF
Language: Russian
Selected content packages: Vanilla
Level seed: NomeHuronia
Loaded submarine: Orca (657FA1DD75A6070F37D60453BC0572EC)
Selected screen: Barotrauma.GameScreen
SteamManager initialized
Client (Round had started)


System info:
    Operating system: Microsoft Windows NT 10.0.22000.0 64 bit
    GPU name: NVIDIA GeForce GTX 1050 Ti
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1,7777778}
    GPU status: Normal


Exception: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index') (System.ArgumentOutOfRangeException)
Target site: Void ThrowArgumentOutOfRange_IndexException()
Stack trace: 
   at Barotrauma.ScalableFont.DrawString(SpriteBatch sb, String text, Vector2 position, Color color, Single rotation, Vector2 origin, Vector2 scale, SpriteEffects se, Single layerDepth, Alignment alignment, ForceUpperCase forceUpperCase) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Fonts\ScalableFont.cs:line 485
   at Barotrauma.GUI.DrawMessages(SpriteBatch spriteBatch, Camera cam) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1684
   at Barotrauma.GUI.Draw(Camera cam, SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 593
   at Barotrauma.GameScreen.Draw(Double deltaTime, GraphicsDevice graphics, SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\GameScreen.cs:line 165
   at Barotrauma.GameMain.Draw(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 1003
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 669
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 511
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59


Last debug messages:
[26.09.2022 23:21:09] Die Orsons
[26.09.2022 23:21:08] Received STARTGAMEFINALIZE packet. Round init status: Started
[26.09.2022 23:21:06] Task count: 0
[26.09.2022 23:21:06] Received STARTGAMEFINALIZE packet. Round init status: WaitingForStartGameFinalize
[26.09.2022 23:21:03] Generating an outpost for the start of the level... (Location: Старательский участок Nome, level type: LocationConnection)
[26.09.2022 23:21:02] Generating an outpost for the end of the level... (Location: Жилой аванпост Huronia, level type: LocationConnection)
[26.09.2022 23:21:01] Level identifier: coldcavernsbasic
[26.09.2022 23:20:53] Die Orsons
[26.09.2022 23:20:52] WARNING: Could not determine reputation change for faction "Дети красного носа" (faction was not present at the start of the round).
[26.09.2022 23:20:52] WARNING: Could not determine reputation change for faction "Церковь Паразита" (faction was not present at the start of the round).
[26.09.2022 23:20:52] WARNING: Could not determine reputation change for faction "Юпитерианские сепаратисты" (faction was not present at the start of the round).
[26.09.2022 23:20:52] WARNING: Could not determine reputation change for faction "Коалиция Европы" (faction was not present at the start of the round).
[26.09.2022 23:17:24] Server running slowly (57 updates/s)!
[26.09.2022 23:17:18] Die Orsons
[26.09.2022 23:17:15] Received STARTGAMEFINALIZE packet. Round init status: Started
[26.09.2022 23:17:15]  -2: WaitForPingDataAsync (owner), RanToCompletion
[26.09.2022 23:17:15]  -1: WaitForPingDataAsync (owner), RanToCompletion
[26.09.2022 23:17:15]  -0: WaitForPingDataAsync (owner), RanToCompletion
[26.09.2022 23:17:15] Task count: 3
[26.09.2022 23:17:15] Received STARTGAMEFINALIZE packet. Round init status: WaitingForStartGameFinalize
[26.09.2022 23:17:12] Generating an outpost for the start of the level... (Location: Жилой аванпост Huronia, level type: Outpost)
[26.09.2022 23:17:12] Level identifier: outpostlevel
[26.09.2022 23:17:05] Server running slowly (57 updates/s)!
[26.09.2022 23:16:36] Lobby created!
[26.09.2022 23:16:24] WARNING: Tried to restore enabled packages multiple times/without performing a backup
[26.09.2022 23:16:16] WARNING: Tried to restore enabled packages multiple times/without performing a backup
[26.09.2022 23:13:49] Die Orsons
[26.09.2022 23:13:47] Server running slowly (57 updates/s)!
[26.09.2022 23:13:44] Received STARTGAMEFINALIZE packet. Round init status: Started
[26.09.2022 23:13:44]  -3: WaitForPingDataAsync (owner), RanToCompletion
[26.09.2022 23:13:44]  -2: WaitForPingDataAsync (owner), RanToCompletion
[26.09.2022 23:13:44]  -1: WaitForPingDataAsync (owner), RanToCompletion
[26.09.2022 23:13:44]  -0: WaitForPingDataAsync (owner), RanToCompletion
[26.09.2022 23:13:44] Task count: 4
[26.09.2022 23:13:44] Received STARTGAMEFINALIZE packet. Round init status: WaitingForStartGameFinalize
[26.09.2022 23:13:39] Generating an outpost for the start of the level... (Location: Жилой аванпост Eightercua Fossa, level type: Outpost)
[26.09.2022 23:13:39] Level identifier: outpostlevel
[26.09.2022 23:13:28] Server running slowly (57 updates/s)!
[26.09.2022 23:13:14] ModeSelectionMode
[26.09.2022 23:13:14] SubSelectionMode
[26.09.2022 23:13:14] LosMode
[26.09.2022 23:13:14] PlayStyle
[26.09.2022 23:13:14] RespawnInterval
[26.09.2022 23:11:58] Lobby created!
[26.09.2022 23:11:12] LobbyMatchList:  LobbiesMatching: 0
[26.09.2022 23:11:12] LobbyMatchList:  LobbiesMatching: 0
[26.09.2022 23:11:12] SteamAPICallCompleted:   AsyncCall: 7757614366233521416
   Callback: 510
 ParamCount: 4
[26.09.2022 23:11:11] LobbyMatchList:  LobbiesMatching: 35
[26.09.2022 23:11:11] LobbyMatchList:  LobbiesMatching: 35
[26.09.2022 23:11:11] SteamAPICallCompleted:   AsyncCall: 12729611055497884010
   Callback: 510
 ParamCount: 4
[26.09.2022 23:11:11] LobbyMatchList:  LobbiesMatching: 50
[26.09.2022 23:11:11] LobbyMatchList:  LobbiesMatching: 50
[26.09.2022 23:11:11] SteamAPICallCompleted:   AsyncCall: 3150854374265661530
   Callback: 510
 ParamCount: 4
[26.09.2022 23:10:53] LobbyMatchList:  LobbiesMatching: 0
[26.09.2022 23:10:53] LobbyMatchList:  LobbiesMatching: 0
[26.09.2022 23:10:53] SteamAPICallCompleted:   AsyncCall: 14680274753208820475
   Callback: 510
 ParamCount: 4
[26.09.2022 23:10:52] LobbyMatchList:  LobbiesMatching: 33
[26.09.2022 23:10:52] LobbyMatchList:  LobbiesMatching: 33
[26.09.2022 23:10:52] SteamAPICallCompleted:   AsyncCall: 10256068183293128672
   Callback: 510
 ParamCount: 4
[26.09.2022 23:10:52] PersonaStateChange:      SteamID: 76561198811420473
 ChangeFlags: 64
[26.09.2022 23:10:52] PersonaStateChange:      SteamID: 76561198340650366
 ChangeFlags: 64
[26.09.2022 23:10:52] PersonaStateChange:      SteamID: 76561198851593584
 ChangeFlags: 64
[26.09.2022 23:10:52] PersonaStateChange:      SteamID: 76561197981246389
 ChangeFlags: 64
[26.09.2022 23:10:52] PersonaStateChange:      SteamID: 76561198078776462
 ChangeFlags: 64
[26.09.2022 23:10:52] PersonaStateChange:      SteamID: 76561199034028507
 ChangeFlags: 64
[26.09.2022 23:10:52] PersonaStateChange:      SteamID: 76561198811420473
 ChangeFlags: 1089
[26.09.2022 23:10:52] PersonaStateChange:      SteamID: 76561198340650366
 ChangeFlags: 1089
[26.09.2022 23:10:52] PersonaStateChange:      SteamID: 76561198851593584
 ChangeFlags: 1089
[26.09.2022 23:10:52] PersonaStateChange:      SteamID: 76561197981246389
 ChangeFlags: 1089
[26.09.2022 23:10:52] PersonaStateChange:      SteamID: 76561198078776462
 ChangeFlags: 1089
[26.09.2022 23:10:52] PersonaStateChange:      SteamID: 76561199034028507
 ChangeFlags: 1089
[26.09.2022 23:10:52] LobbyMatchList:  LobbiesMatching: 50
[26.09.2022 23:10:52] LobbyMatchList:  LobbiesMatching: 50
[26.09.2022 23:10:52] SteamAPICallCompleted:   AsyncCall: 9957081806029490633
   Callback: 510
 ParamCount: 4
[26.09.2022 23:10:11] Attempting to open ALC device "OpenAL Soft on Динамики (Realtek High Definition Audio)"
[26.09.2022 23:10:02] Logged in as Die Orsons (SteamID STEAM_1:1:198699763)
