### ISSUE TITLE
Tandem Fire talent crashes the game if there's no allies alive

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#9932]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Tandem Fire talent crashes the game if there's no allies alive. Seems to have been caused by the refactoring done in https://github.com/Regalis11/Barotrauma-development/commit/9c7ac37eacb37e0276d943fc1aa7a70428c04ede

### Reproduction steps

1. Start a new round
2. `givetalent tandemfire`
3. Kill all your other crewmates
4. Operate a gun

### Bug prevalence

Happens regularly

### Version

0.19.6.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Boolean <ApplyEffect>g__SelectedItemHasTag|2_0(Barotrauma.Character)
Stack trace: 
   at Barotrauma.Abilities.CharacterAbilityTandemFire.<ApplyEffect>g__SelectedItemHasTag|2_0(Character character) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Talents\Abilities\CustomAbilities\CharacterAbilityTandemFire.cs:line 43
   at Barotrauma.Abilities.CharacterAbilityTandemFire.ApplyEffect() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Talents\Abilities\CustomAbilities\CharacterAbilityTandemFire.cs:line 25
   at Barotrauma.Abilities.CharacterAbilityGroupInterval.UpdateAbilityGroup(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Talents\AbilityGroups\CharacterAbilityGroupInterval.cs:line 29
   at Barotrauma.CharacterTalent.UpdateTalent(Single deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Talents\CharacterTalent.cs:line 59
   at Barotrauma.Character.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 2925
   at Barotrauma.AICharacter.Update(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\AICharacter.cs:line 72
   at Barotrauma.Character.UpdateAll(Single deltaTime, Camera cam) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\Character.cs:line 2870
   at Barotrauma.GameScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Screens\GameScreen.cs:line 192
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 855
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/fad6499e849759cab534e32a3357c8cff6f668a2

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
