### ISSUE TITLE
Submarine equality check failed on modded server

### ISSUE THREAD

**Issue by Clintonio** [Regalis11/Barotrauma#9949]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I see the error message that the submarine equality check has failed for a couple of larger ships on a friend's dedicated server.

I have tried;

a) Verifying game files
b) Deleting the older Mods, LocalMods and Submarines folder and unsubscribing all mods in the workshop
c) Restarting the server and my local game client

We previously were playing successfully in the same session until a larger sub was purchased.

I saw several older issues that were all closed and supposedly fixed.

### Reproduction steps

1. Start a modded multiplayer dedicated server 
2. Start in a smaller sub
3. Purchase a larger sub and switch to it
4. Observe a failure to connect

### Bug prevalence

Happens every time I play

### Version

0.18.15.1 / 0.18.15.2 on macOS

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Error while reading a message from server. {Submarine equality check failed. The submarine loaded at your end doesn't match the one loaded by the server. There may have been an error in receiving the up-to-date submarine file from the server.}
   at Barotrauma.Networking.GameClient.ReadStartGameFinalize(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 1027
   at Barotrauma.Networking.GameClient.ReadDataMessage(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 889
   at Barotrauma.Networking.LidgrenClientPeer.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\Primitives\Peers\LidgrenClientPeer.cs:line 105
   at Barotrauma.Networking.GameClient.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 634
```

**Comment by Krzeszny** [comment]
Same, after a round had ended
```
Error while reading a message from server. 
Submarine equality check failed. The submarine loaded at your end doesn't match the one loaded by the server. There may have been an error in receiving the up-to-date submarine file from the server.
   at Barotrauma.Networking.GameClient.ReadStartGameFinalize(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 874
   at Barotrauma.Networking.GameClient.ReadDataMessage(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 742
   at Barotrauma.Networking.SteamP2PClientPeer.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\Primitives\Peers\SteamP2PClientPeer.cs:line 260
   at Barotrauma.Networking.GameClient.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 500
```
