### ISSUE TITLE
[Unstable] Picking a mining mission will crash the game.

### ISSUE THREAD

**Issue by AngelicAngels** [Regalis11/Barotrauma#9958]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Every time i try to pick a mining mission, like "Mining Quartz" for example. It always crash 100% of the time (I've tried it about 10 times) and it 100% of the time, Soft locks me out of my save. the crash report says that it cant find a place to put the minerals.

### Reproduction steps

1.Get a mining mission (Tested in singleplayer)
2. Pick it and head to the next outpost with said mining mission.
3. Crash
4. Try and load the save that crashed
5. Get soft locked

### Bug prevalence

Happens every time I play

### Version

0.19.8.0 (unstable)

### Which operating system did you encounter this bug on?

Linux

### Relevant error messages and crash reports

```shell
﻿Barotrauma Client crash report (generated on 09/29/2022 20:12:47)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


6989204505EA2B7CE5D1DC1A0273C18D


Game version 0.19.8.0 (ReleaseLinux, branch release, revision 373b429eae)
Graphics mode: 1920x1080 (Fullscreen)
VSync ON
Language: English
Selected content packages: Vanilla
Level seed: ThawDank
Loaded submarine: Camel (DB6D52AAB6952F9FFD56D32A8AB89C99)
Selected screen: Barotrauma.RoundSummaryScreen
SteamManager initialized


System info:
    Operating system: Unix 5.4.0.126 64 bit
    GPU name: 
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal


Exception: Failed to find a suitable level wall edge to place level resources on. (System.Exception)
Target site: System.Collections.Generic.List`1[Barotrauma.Item] GenerateMissionResources(Barotrauma.ItemPrefab, Int32, PositionType, Single ByRef, System.Collections.Generic.IEnumerable`1[Barotrauma.Level+Cave])
Stack trace: 
   at Barotrauma.Level.GenerateMissionResources(ItemPrefab prefab, Int32 requiredAmount, PositionType positionType, Single& rotation, IEnumerable`1 targetCaves) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Levels\Level.cs:line 3030
   at Barotrauma.MineralMission.StartMissionSpecific(Level level) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\Missions\MineralMission.cs:line 140
   at Barotrauma.Mission.Start(Level level) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\Missions\Mission.cs:line 260
   at Barotrauma.GameSession.InitializeLevel(Level level) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameSession.cs:line 574
   at Barotrauma.GameSession.StartRound(LevelData levelData, Boolean mirrorLevel, SubmarineInfo startOutpost, SubmarineInfo endOutpost) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameSession.cs:line 430
   at Barotrauma.CampaignMode.<>c__DisplayClass32_0.<<SelectSummaryScreen>b__0>d.MoveNext() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameSession\GameModes\CampaignMode.cs:line 268
--- End of stack trace from previous location ---
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 855
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58


Last debug messages:
[09/29/2022 20:12:44] Generating an outpost for the end of the level... (Location: Dank Outpost, level type: LocationConnection)
[09/29/2022 20:12:43] Generating an outpost for the start of the level... (Location: Thaw Habitation Outpost, level type: LocationConnection)
[09/29/2022 20:12:41] Level identifier: coldcavernsadvanced
[09/29/2022 20:12:29] Transitioning to ThawDank (current location: Thaw Habitation Outpost, selected location: Dank Outpost, leaving sub: Camel, at start: True, at end: False, transition type: LeaveLocation)
[09/29/2022 20:12:14] Unlocked mission "Killing a large Crawler" in the connection from "Thaw Habitation Outpost" to "Mehen Linea".
[09/29/2022 20:12:12] Unlocked mission "Mining Quartz" in the connection from "Thaw Habitation Outpost" to "Dank Outpost".
[09/29/2022 20:12:10] Unlocked mission "Mining outpost material transport" in the connection from "Thaw Habitation Outpost" to "Dank Outpost".
[09/29/2022 20:10:05] Generating an outpost for the start of the level... (Location: Thaw Habitation Outpost, level type: Outpost)
[09/29/2022 20:10:05] Level identifier: outpostlevel
[09/29/2022 20:09:53] Transitioning to Thaw (current location: Agenor Linea, selected location: Thaw Habitation Outpost, leaving sub: Camel, at start: False, at end: True, transition type: ProgressToNextLocation)
[09/29/2022 20:01:55] Could not find a spawn point for a SpawnAction (spawn location: BeaconStation (tag: beacon_bandit), skipping.
[09/29/2022 20:01:51] Could not find a suitable module for the location type LocationType (None). Module flag: Airlock.
[09/29/2022 20:01:50] Generating an outpost for the end of the level... (Location: Agenor Linea, level type: LocationConnection)
[09/29/2022 20:01:49] Level identifier: coldcavernsadvanced
[09/29/2022 20:01:37] Transitioning to ThawAgenor Linea (current location: Agenor Linea, selected location: Thaw Habitation Outpost, leaving sub: Camel, at start: False, at end: True, transition type: ProgressToNextEmptyLocation)
[09/29/2022 19:42:00] Could not find a spawn point for a SpawnAction (spawn location: BeaconStation (tag: beacon_bandit), skipping.
[09/29/2022 19:41:53] Generating an outpost for the start of the level... (Location: Onga Linea Prospecting Outpost, level type: LocationConnection)
[09/29/2022 19:41:52] Level identifier: coldcavernsadvanced
[09/29/2022 19:41:39] Transitioning to Onga LineaAgenor Linea (current location: Onga Linea Prospecting Outpost, selected location: Agenor Linea, leaving sub: Camel, at start: True, at end: False, transition type: LeaveLocation)
[09/29/2022 19:37:26] Unlocked mission "Personnel Transport" in the connection from "Onga Linea Prospecting Outpost" to "Wolstone Habitation Outpost".
[09/29/2022 19:37:24] Unlocked mission "Getting rid of Mudraptors" in the connection from "Onga Linea Prospecting Outpost" to "Agenor Linea".
[09/29/2022 19:37:22] Unlocked mission "Killing a large Crawler" in the connection from "Onga Linea Prospecting Outpost" to "Mehen Linea".
[09/29/2022 19:34:50] Generating an outpost for the start of the level... (Location: Onga Linea Prospecting Outpost, level type: Outpost)
[09/29/2022 19:34:50] Level identifier: outpostlevel
[09/29/2022 19:34:38] Transitioning to Onga Linea (current location: Wolstone Habitation Outpost, selected location: Onga Linea Prospecting Outpost, leaving sub: Camel, at start: False, at end: True, transition type: ProgressToNextLocation)
[09/29/2022 19:11:44] Could not find a spawn point for a SpawnAction (spawn location: BeaconStation (tag: beacon_bandit), skipping.
[09/29/2022 19:11:39] Generating an outpost for the end of the level... (Location: Onga Linea Prospecting Outpost, level type: LocationConnection)
[09/29/2022 19:11:38] Generating an outpost for the start of the level... (Location: Wolstone Habitation Outpost, level type: LocationConnection)
[09/29/2022 19:11:36] Level identifier: coldcavernsadvanced
[09/29/2022 19:11:24] Transitioning to WolstoneOnga Linea (current location: Wolstone Habitation Outpost, selected location: Onga Linea Prospecting Outpost, leaving sub: Camel, at start: True, at end: False, transition type: LeaveLocation)
[09/29/2022 19:09:53] Unlocked mission "Mining outpost material transport" in the connection from "Wolstone Habitation Outpost" to "Kury".
[09/29/2022 19:09:51] Unlocked mission "Terminate a Swarm" in the connection from "Wolstone Habitation Outpost" to "Onga Linea Prospecting Outpost".
[09/29/2022 19:09:49] Unlocked mission "Personnel Transport" in the connection from "Wolstone Habitation Outpost" to "Onga Linea Prospecting Outpost".
[09/29/2022 19:07:42] Generating an outpost for the start of the level... (Location: Wolstone Habitation Outpost, level type: Outpost)
[09/29/2022 19:07:42] Level identifier: outpostlevel
[09/29/2022 19:07:30] Transitioning to Wolstone (current location: Katreus Linea Outpost, selected location: Wolstone Habitation Outpost, leaving sub: Camel, at start: False, at end: True, transition type: ProgressToNextLocation)
[09/29/2022 18:52:46] Generating an outpost for the end of the level... (Location: Wolstone Habitation Outpost, level type: LocationConnection)
[09/29/2022 18:52:45] Generating an outpost for the start of the level... (Location: Katreus Linea Outpost, level type: LocationConnection)
[09/29/2022 18:52:43] Level identifier: coldcavernsbasic
[09/29/2022 18:52:31] Transitioning to Katreus LineaWolstone (current location: Katreus Linea Outpost, selected location: Wolstone Habitation Outpost, leaving sub: Camel, at start: True, at end: False, transition type: LeaveLocation)
[09/29/2022 18:51:57] Unlocked mission "Killing Hammerheads" in the connection from "Katreus Linea Outpost" to "Kury".
[09/29/2022 18:51:55] Unlocked mission "Mining outpost material transport" in the connection from "Katreus Linea Outpost" to "Wolstone Habitation Outpost".
[09/29/2022 18:51:53] Unlocked mission "Personnel Transport" in the connection from "Katreus Linea Outpost" to "Sontu Mining Claim".
[09/29/2022 18:49:39] Generating an outpost for the start of the level... (Location: Katreus Linea Outpost, level type: Outpost)
[09/29/2022 18:49:39] Level identifier: outpostlevel
[09/29/2022 18:46:15] Object reference not set to an instance of an object.:    at Barotrauma.ContentPackage.TryLoad(String path) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\ContentManagement\ContentPackage\ContentPackage.cs:line 141
[09/29/2022 18:46:15] Couldn't load xml document "LocalMods/Endocrine New talents/filelist.xml"! {Root element is missing.}
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ThrowWithoutLineInfo(String res)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at Barotrauma.XMLExtensions.TryLoadXml(String filePath, Exception& exception) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Serialization\XMLExtensions.cs:line 110
[09/29/2022 18:45:19] Object reference not set to an instance of an object.:    at Barotrauma.ContentPackage.TryLoad(String path) in E:\Barotrauma-development\Barotrauma\BarotraumaShared\SharedSource\ContentManagement\ContentPackage\ContentPackage.cs:line 131
[09/29/2022 18:45:19] Couldn't load xml document "LocalMods/Endocrine New talents/filelist.xml"! {Root element is missing.}
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at Barotrauma.XMLExtensions.TryLoadXml(String filePath, Exception& exception) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Serialization\XMLExtensions.cs:line 98
[09/29/2022 18:45:18] Attempting to open ALC device "HyperX Virtual Surround Sound Analog Stereo"
[09/29/2022 18:45:14] Logged in as AngeL (SteamID STEAM_1:1:99912460)
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d3f28af251c47585827190373cf770887d606c88

**Comment by Rokvach** [comment]
Tested, working correctly. closing.
