### ISSUE TITLE
Players Cant join modded lobby (Failed to find the end of the bit field after 100 reads)

### ISSUE THREAD

**Issue by mrcalzon02** [Regalis11/Barotrauma#9992]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Players attempting to join get error ( Error while reading a message from server. {Failed to find the end of the bit field after 100 reads. Terminating to prevent the game from freezing.}
at Barotrauma.ReadOnlyBitField..ctor(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\NetStructBitField.cs:line 122
at Barotrauma.INetSerializableStruct.Read[T](IReadMessage inc) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\INetSerializableStruct.cs:line 693
at Barotrauma.Networking.ClientPeer.ReadConnectionInitializationStep(IncomingInitializationMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\Primitives\Peers\ClientPeer.cs:line 118
at Barotrauma.Networking.SteamP2PClientPeer.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\Primitives\Peers\SteamP2PClientPeer.cs:line 251
at Barotrauma.Networking.GameClient.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 477 ) 

### Reproduction steps

1. loaded mods 
2. Selected Host server
3. selected (Lua For Barotrauma- Dedicatedserver)
4. wait. 
5. players Cannot join.
will report to Lua For Barotrauma as well.

### Bug prevalence

Happens every time I play

### Version

0.19.10.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
No Crashlog Due to the game not Crashing on Error.
Error while reading a message from server. {Failed to find the end of the bit field after 100 reads. Terminating to prevent the game from freezing.}
at Barotrauma.ReadOnlyBitField..ctor(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\NetStructBitField.cs:line 122
at Barotrauma.INetSerializableStruct.Read[T](IReadMessage inc) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Networking\INetSerializableStruct.cs:line 693
at Barotrauma.Networking.ClientPeer.ReadConnectionInitializationStep(IncomingInitializationMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\Primitives\Peers\ClientPeer.cs:line 118
at Barotrauma.Networking.SteamP2PClientPeer.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\Primitives\Peers\SteamP2PClientPeer.cs:line 251
at Barotrauma.Networking.GameClient.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 477
```

**Comment by mrcalzon02** [comment]
[TEST Fear the deep_2022-10-05_1446.txt](https://github.com/Regalis11/Barotrauma/files/9719588/TEST.Fear.the.deep_2022-10-05_1446.txt)
server log.

**Comment by mrcalzon02** [comment]
[Fear the deep.zip](https://github.com/Regalis11/Barotrauma/files/9719621/Fear.the.deep.zip)
campaign save used.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c8d64177ff0f3e99a4da6806e97392125131cf11

**Comment by Ksarper** [comment]
> Fixed in [Regalis11/Barotrauma-development@c8d6417](https://github.com/Regalis11/Barotrauma-development/commit/c8d64177ff0f3e99a4da6806e97392125131cf11)

No it's not. 
![image](https://user-images.githubusercontent.com/48825686/194614076-f8e2e5e7-2297-4286-9592-4b4479593773.png)

Five of my friends just bought the game and can't play

**Comment by Ksarper** [comment]
Or are you going to release another hotfix in the near future?

**Comment by NilanthAnimosus** [comment]
Tested against bitfield-size-limit-fix commit https://github.com/Regalis11/Barotrauma-development/commit/057d32efc184648d4eaf6dfb58593dfc86ae5948

Fix did not work for approximately 34 +- 1 mods (All content mods for the most part).

Reproduced without the fix first (failed to find the end of the bit field after 100 reads. Terminating to prevent the game from freezing.) then tested with the fix and had this error occur:

![image](https://user-images.githubusercontent.com/29177976/194879185-2715097f-74ea-4958-8bb7-e9442eee5c89.png)

Mods used (its probably quantity not specific mods, but just noting how they are by majority not submarine mods):
![image](https://user-images.githubusercontent.com/29177976/194879380-361f80af-fd69-47f7-b8b1-8f11368710d6.png)

**Comment by daaurpoj** [comment]
Can confirm, issue is still occurring for me

**Comment by Ksarper** [comment]
Up

**Comment by Regalis11** [comment]
> Can confirm, issue is still occurring for me

The fix is still not out in the latest unstable version, it turned out to be more tricky to solve than we initially though. We have a new fix in testing atm though, and it'll hopefully be included in the next unstable.

**Comment by NilanthAnimosus** [comment]
Tested against bitfield-size-limit-fix commit https://github.com/Regalis11/Barotrauma-development/commit/057d32efc184648d4eaf6dfb58593dfc86ae5948

Tested against the same mod list as previously used (with 34 +- 1 mods) and found no issues, unless there are further things to test than too many mods I believe this issue is fixed now and likely ready for merging.
