### ISSUE TITLE
"%ModDir:OTHERMOD%/..."will be replaced by "Content/ContentPackages/..." and cause error and crash.

### ISSUE THREAD

**Issue by esirprus** [Regalis11/Barotrauma#9994]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

"%ModDir:OTHERMOD%/..."will be replaced by "Content/ContentPackages/..." and cause error and crash.

### Reproduction steps

eg: https://steamcommunity.com/sharedfiles/filedetails/?id=2853393887
enable this mod will post an error on console.

### Bug prevalence

Happens every time I play

### Version

0.19.10.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 10/06/2022 09:57:58)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


740F99807DE7DF37B0C523EA8E4AE655


Game version 0.19.10.0 (ReleaseWindows, branch release, revision 811fb37ab3)
Graphics mode: 1600x900 (Windowed)
VSync OFF
Language: Simplified Chinese
Selected content packages: Vanilla, CsForBarotrauma, Lua For Barotrauma, Neurotrauma+Animated Barotrauma, [EA-HI]Animated Barotrauma#Vanilla, Neurotrauma
Level seed: no level loaded
Loaded submarine: None
Selected screen: Barotrauma.NetLobbyScreen
SteamManager initialized
Client (Round hadn't been started)


System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit
    GPU name: NVIDIA GeForce GTX 1050 Ti
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal


Exception: Could not find a part of the path 'D:\steam\steamapps\common\Barotrauma\Content\ContentPackages\Content\Characters\Human'. (System.IO.DirectoryNotFoundException)
Target site: IntPtr CreateDirectoryHandle(System.String, Boolean)
Stack trace: 
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.GetFiles(String path, String searchPattern, EnumerationOptions enumerationOptions)
   at System.IO.Directory.GetFiles(String path)
   at Barotrauma.CharacterInfo.LoadHeadSprite() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\CharacterInfo.cs:line 1016
   at Barotrauma.CharacterInfo.get_HeadSprite() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Characters\CharacterInfo.cs:line 351
   at Barotrauma.CharacterInfo.DrawIcon(SpriteBatch spriteBatch, Vector2 screenPos, Vector2 targetAreaSize) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Characters\CharacterInfo.cs:line 439
   at Barotrauma.CharacterInfo.<CreateIcon>b__36_0(SpriteBatch sb, GUICustomComponent component) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Characters\CharacterInfo.cs:line 566
   at Barotrauma.GUICustomComponent.Draw(SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUICustomComponent.cs:line 43
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Barotrauma.GUI.Draw(Camera cam, SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 251
   at Barotrauma.NetLobbyScreen.Draw(Double deltaTime, GraphicsDevice graphics, SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\NetLobbyScreen.cs:line 2747
   at Barotrauma.GameMain.Draw(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 957
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 669
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 508
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58


Last debug messages:
[10/06/2022 09:57:58] 
/// Running Neurotrauma V A1.8h1 ///
------------------------------------------
- Not running any expansions

[10/06/2022 09:57:33] Sprite "Content/ContentPackages/Images/AfflictionIcons.png" not found!
[10/06/2022 09:57:33] Sprite "Content/ContentPackages/Images/AfflictionIcons.png" not found!
[10/06/2022 09:57:33] Sprite "Content/ContentPackages/Images/AfflictionIcons.png" not found!
[10/06/2022 09:57:33] Sprite "Content/ContentPackages/Images/AfflictionIcons.png" not found!
[10/06/2022 09:57:33] Sprite "Content/ContentPackages/Images/AfflictionIcons.png" not found!
[10/06/2022 09:57:33] Sprite "Content/ContentPackages/Images/AfflictionIcons.png" not found!
[10/06/2022 09:57:33] Sprite "Content/ContentPackages/Images/AfflictionIcons.png" not found!
[10/06/2022 09:48:25] Sprite "Content/ContentPackages/Images/AfflictionIcons.png" not found!
[10/06/2022 09:48:25] Sprite "Content/ContentPackages/Images/AfflictionIcons.png" not found!
[10/06/2022 09:48:25] Sprite "Content/ContentPackages/Images/AfflictionIcons.png" not found!
[10/06/2022 09:48:25] Sprite "Content/ContentPackages/Images/AfflictionIcons.png" not found!
[10/06/2022 09:48:25] Sprite "Content/ContentPackages/Images/AfflictionIcons.png" not found!
[10/06/2022 09:48:25] Sprite "Content/ContentPackages/Images/AfflictionIcons.png" not found!
[10/06/2022 09:48:25] Sprite "Content/ContentPackages/Images/AfflictionIcons.png" not found!
[10/06/2022 09:46:54] Overriding an affliction or a buff with the identifier 'combatstimulant' using the file 'C:/Users/esirp/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[10/06/2022 09:46:54] Overriding an affliction or a buff with the identifier 'implacable' using the file 'C:/Users/esirp/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[10/06/2022 09:46:54] Overriding an affliction or a buff with the identifier 'concussion' using the file 'C:/Users/esirp/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[10/06/2022 09:46:54] Overriding an affliction or a buff with the identifier 'radiationsickness' using the file 'C:/Users/esirp/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[10/06/2022 09:46:54] Overriding an affliction or a buff with the identifier 'drunk' using the file 'C:/Users/esirp/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[10/06/2022 09:46:54] Overriding an affliction or a buff with the identifier 'invertcontrols' using the file 'C:/Users/esirp/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[10/06/2022 09:46:54] Overriding an affliction or a buff with the identifier 'chemwithdrawal' using the file 'C:/Users/esirp/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[10/06/2022 09:46:54] Overriding an affliction or a buff with the identifier 'chemaddiction' using the file 'C:/Users/esirp/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[10/06/2022 09:46:54] Overriding an affliction or a buff with the identifier 'opiatewithdrawal' using the file 'C:/Users/esirp/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[10/06/2022 09:46:54] Overriding an affliction or a buff with the identifier 'opiateoverdose' using the file 'C:/Users/esirp/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[10/06/2022 09:46:54] Overriding an affliction or a buff with the identifier 'opiateaddiction' using the file 'C:/Users/esirp/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[10/06/2022 09:46:54] Overriding an affliction or a buff with the identifier 'burn' using the file 'C:/Users/esirp/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[10/06/2022 09:46:54] Overriding an affliction or a buff with the identifier 'explosiondamage' using the file 'C:/Users/esirp/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[10/06/2022 09:46:54] Overriding an affliction or a buff with the identifier 'organdamage' using the file 'C:/Users/esirp/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[10/06/2022 09:46:54] Overriding an affliction or a buff with the identifier 'gunshotwound' using the file 'C:/Users/esirp/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[10/06/2022 09:46:54] Overriding an affliction or a buff with the identifier 'bitewounds' using the file 'C:/Users/esirp/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[10/06/2022 09:46:54] Overriding an affliction or a buff with the identifier 'lacerations' using the file 'C:/Users/esirp/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[10/06/2022 09:46:54] Overriding an affliction or a buff with the identifier 'blunttrauma' using the file 'C:/Users/esirp/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[10/06/2022 09:46:54] Overriding an affliction or a buff with the identifier 'internaldamage' using the file 'C:/Users/esirp/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[10/06/2022 09:46:54] Overriding an affliction or a buff with the identifier 'bleedingnonstop' using the file 'C:/Users/esirp/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[10/06/2022 09:46:54] Overriding an affliction or a buff with the identifier 'bleeding' using the file 'C:/Users/esirp/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[10/06/2022 09:46:54] Overriding an affliction or a buff with the identifier 'sufforinpoisoning' using the file 'C:/Users/esirp/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[10/06/2022 09:46:54] Overriding an affliction or a buff with the identifier 'cyanidepoisoning' using the file 'C:/Users/esirp/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[10/06/2022 09:46:54] Overriding an affliction or a buff with the identifier 'morbusinepoisoning' using the file 'C:/Users/esirp/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[10/06/2022 09:46:54] Overriding an affliction or a buff with the identifier 'bloodloss' using the file 'C:/Users/esirp/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[10/06/2022 09:46:54] Overriding an affliction or a buff with the identifier 'oxygenlow' using the file 'C:/Users/esirp/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[10/06/2022 09:46:54] Duplicate affliction: 'shockpain' defined in Affliction of 'C:/Users/esirp/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[10/06/2022 09:46:54] Duplicate affliction: 'pain' defined in Affliction of 'C:/Users/esirp/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[10/06/2022 09:46:54] Duplicate affliction: 'severepainlite' defined in Affliction of 'C:/Users/esirp/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[10/06/2022 09:46:54] Duplicate affliction: 'severepain' defined in Affliction of 'C:/Users/esirp/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[10/06/2022 09:46:54] Duplicate affliction: 'sym_hematemesis' defined in Affliction of 'C:/Users/esirp/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[10/06/2022 09:46:54] Duplicate affliction: 'sym_vomiting' defined in Affliction of 'C:/Users/esirp/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[10/06/2022 09:46:54] Duplicate affliction: 'sym_cough' defined in Affliction of 'C:/Users/esirp/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[10/06/2022 09:46:53] Overriding an affliction or a buff with the identifier 'nausea' using the file 'C:/Users/esirp/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2850994195/Content/Afflictions.xml'
[10/06/2022 09:46:53] Overriding an affliction or a buff with the identifier 'concussion' using the file 'C:/Users/esirp/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2850994195/Content/Afflictions.xml'
[10/06/2022 09:46:53] Sprite "Content/ContentPackages/Images/AfflictionIcons.png" not found!
[10/06/2022 09:46:53] Sprite "Content/ContentPackages/Images/AfflictionIcons.png" not found!
[10/06/2022 09:46:53] Sprite "Content/ContentPackages/Images/AfflictionIcons.png" not found!
[10/06/2022 09:46:53] Sprite "Content/ContentPackages/Images/AfflictionIcons.png" not found!
[10/06/2022 09:46:53] Sprite "Content/ContentPackages/Images/AfflictionIcons.png" not found!
[10/06/2022 09:46:53] Sprite "Content/ContentPackages/Images/AfflictionIcons.png" not found!
[10/06/2022 09:46:53] Sprite "Content/ContentPackages/Images/AfflictionIcons.png" not found!
[10/06/2022 09:43:23] Overriding an affliction or a buff with the identifier 'nausea' using the file 'C:/Users/esirp/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2850994195/Content/Afflictions.xml'
[10/06/2022 09:43:23] Overriding an affliction or a buff with the identifier 'concussion' using the file 'C:/Users/esirp/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2850994195/Content/Afflictions.xml'
[10/06/2022 09:43:08] Command "e" not found.
[10/06/2022 09:43:08] e
[10/06/2022 09:42:17] Overriding an affliction or a buff with the identifier 'nausea' using the file 'C:/Users/esirp/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2850994195/Content/Afflictions.xml'
[10/06/2022 09:42:17] Overriding an affliction or a buff with the identifier 'concussion' using the file 'C:/Users/esirp/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2850994195/Content/Afflictions.xml'
[10/06/2022 09:42:17] Overriding an affliction or a buff with the identifier 'combatstimulant' using the file 'C:/Users/esirp/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[10/06/2022 09:42:17] Overriding an affliction or a buff with the identifier 'implacable' using the file 'C:/Users/esirp/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[10/06/2022 09:42:17] Overriding an affliction or a buff with the identifier 'concussion' using the file 'C:/Users/esirp/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[10/06/2022 09:42:17] Overriding an affliction or a buff with the identifier 'radiationsickness' using the file 'C:/Users/esirp/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[10/06/2022 09:42:17] Overriding an affliction or a buff with the identifier 'drunk' using the file 'C:/Users/esirp/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[10/06/2022 09:42:17] Overriding an affliction or a buff with the identifier 'invertcontrols' using the file 'C:/Users/esirp/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[10/06/2022 09:42:17] Overriding an affliction or a buff with the identifier 'chemwithdrawal' using the file 'C:/Users/esirp/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[10/06/2022 09:42:17] Overriding an affliction or a buff with the identifier 'chemaddiction' using the file 'C:/Users/esirp/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[10/06/2022 09:42:17] Overriding an affliction or a buff with the identifier 'opiatewithdrawal' using the file 'C:/Users/esirp/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[10/06/2022 09:42:17] Overriding an affliction or a buff with the identifier 'opiateoverdose' using the file 'C:/Users/esirp/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[10/06/2022 09:42:17] Overriding an affliction or a buff with the identifier 'opiateaddiction' using the file 'C:/Users/esirp/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[10/06/2022 09:42:17] Overriding an affliction or a buff with the identifier 'burn' using the file 'C:/Users/esirp/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[10/06/2022 09:42:17] Overriding an affliction or a buff with the identifier 'explosiondamage' using the file 'C:/Users/esirp/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[10/06/2022 09:42:17] Overriding an affliction or a buff with the identifier 'organdamage' using the file 'C:/Users/esirp/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[10/06/2022 09:42:17] Overriding an affliction or a buff with the identifier 'gunshotwound' using the file 'C:/Users/esirp/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[10/06/2022 09:42:17] Overriding an affliction or a buff with the identifier 'bitewounds' using the file 'C:/Users/esirp/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[10/06/2022 09:42:17] Overriding an affliction or a buff with the identifier 'lacerations' using the file 'C:/Users/esirp/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[10/06/2022 09:42:17] Overriding an affliction or a buff with the identifier 'blunttrauma' using the file 'C:/Users/esirp/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[10/06/2022 09:42:17] Overriding an affliction or a buff with the identifier 'internaldamage' using the file 'C:/Users/esirp/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[10/06/2022 09:42:17] Overriding an affliction or a buff with the identifier 'bleedingnonstop' using the file 'C:/Users/esirp/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[10/06/2022 09:42:17] Overriding an affliction or a buff with the identifier 'bleeding' using the file 'C:/Users/esirp/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[10/06/2022 09:42:17] Overriding an affliction or a buff with the identifier 'sufforinpoisoning' using the file 'C:/Users/esirp/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[10/06/2022 09:42:17] Overriding an affliction or a buff with the identifier 'cyanidepoisoning' using the file 'C:/Users/esirp/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[10/06/2022 09:42:17] Overriding an affliction or a buff with the identifier 'morbusinepoisoning' using the file 'C:/Users/esirp/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[10/06/2022 09:42:17] Overriding an affliction or a buff with the identifier 'bloodloss' using the file 'C:/Users/esirp/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[10/06/2022 09:42:17] Overriding an affliction or a buff with the identifier 'oxygenlow' using the file 'C:/Users/esirp/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[10/06/2022 09:42:17] Duplicate affliction: 'shockpain' defined in Affliction of 'C:/Users/esirp/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[10/06/2022 09:42:17] Duplicate affliction: 'pain' defined in Affliction of 'C:/Users/esirp/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[10/06/2022 09:42:17] Duplicate affliction: 'severepainlite' defined in Affliction of 'C:/Users/esirp/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[10/06/2022 09:42:17] Duplicate affliction: 'severepain' defined in Affliction of 'C:/Users/esirp/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[10/06/2022 09:42:17] Duplicate affliction: 'sym_hematemesis' defined in Affliction of 'C:/Users/esirp/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[10/06/2022 09:42:17] Duplicate affliction: 'sym_vomiting' defined in Affliction of 'C:/Users/esirp/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[10/06/2022 09:42:17] Duplicate affliction: 'sym_cough' defined in Affliction of 'C:/Users/esirp/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2776270649/Xml/Afflictions.xml'
[10/06/2022 09:42:17] Sprite "Content/ContentPackages/Images/AfflictionIcons.png" not found!
[10/06/2022 09:42:17] Sprite "Content/ContentPackages/Images/AfflictionIcons.png" not found!
[10/06/2022 09:42:17] Sprite "Content/ContentPackages/Images/AfflictionIcons.png" not found!
[10/06/2022 09:42:17] Sprite "Content/ContentPackages/Images/AfflictionIcons.png" not found!
[10/06/2022 09:42:17] Sprite "Content/ContentPackages/Images/AfflictionIcons.png" not found!
[10/06/2022 09:42:17] Sprite "Content/ContentPackages/Images/AfflictionIcons.png" not found!
[10/06/2022 09:42:17] Sprite "Content/ContentPackages/Images/AfflictionIcons.png" not found!
[10/06/2022 09:41:43] WARNING: Tried to restore enabled packages multiple times/without performing a backup
[10/06/2022 09:41:43] WARNING: Tried to restore enabled packages multiple times/without performing a backup
[10/06/2022 09:41:39] Server command: install_cl_lua
[10/06/2022 09:41:39] install_cl_lua
[10/06/2022 09:41:13]  
It seems you didn't enabled GMTools in mod list
If you want enable it by force, use command ".gmtools_forcedrun"
Mod will be launched right now and will be hidden from players
 
[10/06/2022 09:41:13] Lobby created!
[10/06/2022 09:41:13] WARNING: Hair index out of range (character: loafer, index: 22)
[10/06/2022 09:41:12] WARNING: Hair index out of range (character: loafer, index: 22)
[10/06/2022 09:40:15] 连接到主服务器时发生错误 { System.Net.WebException: The SSL connection could not be established, see inner exception.
 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.IO.IOException:  Received an unexpected EOF or 0 bytes from the transport stream.
   at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|189_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at System.Net.HttpWebRequest.SendRequest(Boolean async)
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at RestSharp.Http.GetRawResponseAsync(IAsyncResult result, Action`1 callback)
   at RestSharp.Http.ResponseCallback(IAsyncResult result, Action`1 callback) }
[10/06/2022 09:39:39] Attempting to open ALC device "OpenAL Soft on 扬声器 (Realtek(R) Audio)"
[10/06/2022 09:39:37] Logged in as Loafer (SteamID STEAM_1:1:77218839)
```

**Comment by shangjiaxuan** [comment]
Issue already reported. Devs have fixed this #9985 , should wait for hotfixx
